{100}{}{You use the door computer. The computer does not recognize your access code.}
{101}{}{You use the door computer. A speaker crackles to life.}
{102}{}{Sorry, but we can't let you back in right now. Uh,
 technical problems. Try again later.}
{103}{}{You see the Vault-13 door entry computer.}