{100}{}{Vedi Abel.}
{101}{}{Vedi un grosso mutante.}
{102}{}{Tu no dovere essere qui.}
{103}{}{Hng.}
{104}{}{Certo che no. Sono qui per ucciderti!}
{105}{}{Perche'?}
{106}{}{Ah, davvero? Tua sorella!}
{107}{}{Pik!}
{108}{}{Se dire di nuovo me spacca te culo!}
{109}{}{Pik! Pik!}
{110}{}{Oh, adesso tu vedere!}
{111}{}{Tu umano. Me mutante. Mutante uccide umano.}
{112}{}{E come pensi di farlo? Cosa mi dici del campo di forza?}
{113}{}{Abel si occupare di quello. Poi Abel spacca tuo culo!}
{114}{}{Umani no essere ammessi qui. Questo posto di mutanti. Andare via.}
{115}{}{Hng!}
{116}{}{Devo attraversare questo campo di forza. Abbassalo, per favore.}
{117}{}{No.}
{118}{}{Tu ancora. Abel spacca tuo culo!}
#
# Tell Me About name
#
# Duplicates are needed due to how engine processes the Tell-Me-Abouts.  -Sduibek
{970}{}{Me Abel.}
{971}{}{Me Abel.}
{972}{}{Me Abel.}
{973}{}{Me Abel.}
{974}{}{Me Abel.}
{975}{}{Me Abel.}
{976}{}{Me Abel.}
{977}{}{Me Abel.}
{978}{}{Me Abel.}
{979}{}{Me Abel.}
#
# Tell Me About, "don't know what that is"
#
{980}{}{Hng.}
{981}{}{Perche'?}
{982}{}{Pik!}
{983}{}{Ung... wuh?}
{984}{}{Hmm?}
{985}{}{What you say?}
{986}{}{What, hmm?}
{987}{}{Uh... me not know.}
{988}{}{Me not know.}
{989}{}{What that?}
{990}{}{}
{991}{}{}
{992}{}{}
{993}{}{}
{994}{}{}
{995}{}{}
{996}{}{}
{997}{}{}
{998}{}{}
{999}{}{}
