{100}{}{Vedi Mitch, del negozio Tutto-In-Uno.}
{101}{}{Come posso aiutarti?}
{102}{}{Vorrei comprare qualcosa.}
{103}{}{Vorrei vendere qualcosa.}
{104}{}{Niente. Grazie.}
{105}{}{Runk.}
{106}{}{Ottimo. Ecco quello che ho.}
{107}{}{Ottimo, sono sempre in cerca di nuove cose.}
{108}{}{Mi dispiace, ma non capisco quel che dici. Torna quando avrai trovato un po' piu' di cervello.}
{109}{}{Grazie e arrivederci.}
{110}{}{Vedi Jake, il venditore di armi.}
