{100}{}{Vedi un Cavaliere.}
{101}{}{La sala d'apprendimento si trova laggiu', se e' quella che cerchi.}
{102}{}{Ti sei perso? La sala d'apprendimento e' proprio laggiu'.}
{103}{}{Il laboratorio medico si trova subito dietro l'angolo.}
