{100}{}{Vedi un uomo che ti fissa negli occhi per un attimo, ma poi rivolge altrove lo sguardo.}
{101}{}{Vedi Greg.}
{102}{}{Cosa c'e'? Perche' stai parlando con me? Ti sentiranno, sai?}
{103}{}{Ehi, sei tornato. Non gridare cosi', loro sono la' fuori.}
{104}{}{Ok, ma cerca di parlare piano; ci prenderanno entrambi se non la smetti di gridare.}
{105}{}{Chi sei?}
{106}{}{Perche' sei cosi' teso?}
{107}{}{Non e' che ti sei dimenticato di prendere le tue medicine?}
{108}{}{Lasciamo perdere.}
{109}{}{Sono... Greg... ma non dirlo a nessuno, o verranno a cercarmi.}
{110}{}{Teso? Io non sono teso. Solo prudente. Tutti dicono che sono paranoico, ma sono io quello che rimarra' qui quando verranno a prendervi.}
{111}{}{Verranno a prenderci? Chi?}
{112}{}{Anch'io penso che tu sia paranoico. Parleremo un'altra volta.}
{113}{}{Beh, sono...Ma si' che lo sai...La malattia e' stata solo l'inizio. Adesso loro stanno per venire a prenderci tutti. Ma tu sei proprio come tutti gli altri. Tu non mi crederai... e sarai condannato. Presta ascolto alle mie parole. IO SARO' ANCORA QUI, E TUTTO QUESTO, INCLUSO TE, SARA' PRESO. PRESO. [Greg si mette le mani in testa e si raggomitola gemendo e piagnucolando]}
{114}{}{Medicine...Oh, cosi' tu sei uno di loro e cerchi di farmi prendere di nuovo le mie medicine... Beh, non riuscirai a convincermi. NON LE PRENDERO', NO, NON LO FARO'. LE VOCI, NON LO FARO', NON PUOI COSTRINGERMI. [Greg chiude gli occhi e si afferra la testa, parlando freneticamente con le voci che solo lui riesce a sentire.]}
{115}{}{NON PUOI COSTRINGERMI!}
{116}{}{NIENTE DI CIO' CHE FARAI POTRA' SALVARCI!}
{117}{}{E' TUTTO FINITO!}
{118}{}{STANNO ARRIVANDO, E TU NON PUOI FERMARLI!}
{119}{}{VI PRENDERANNO TUTTI!}
