{100}{}{Vedi un negoziante.}
{101}{}{La Sacra Fiamma non apprezza che ladri e mascalzoni entrino in questo luogo di culto. Sarai punito!}
{102}{}{Hng!}
{103}{}{Non stavo rubando, davvero!}
{104}{}{Questo dillo alla Sacra Fiamma quando la vedrai... dopo la tua punizione.}
{105}{}{Le tue bugie non mi interessano... ne' interessano al Master.}
{106}{}{Mi dispiace, ma il negozio e' chiuso.}
{107}{}{Nugga.}
{108}{}{Beh, grazie al cavolo.}
{109}{}{Cosa?}
{110}{}{Non dirlo.}
{111}{}{La Cattedrale non ha tempo di occuparsi di quelli come te. Eppure ci hai causato un sacco di problemi. Vorrei che te ne andassi prima di esser costretto a chiamare i rinforzi.}
{112}{}{Non ce n'e' bisogno. Sono tuo amico.}
{113}{}{Vabbe'.}
{114}{}{Mi rifiuto di trattare con chi usa delle armi per fare delle richieste. Noi della Cattedrale abbiamo raggiunto un livello che va oltre il semplice uso delle armi.}
{115}{}{Fascista d'un antimilitarista!}
{116}{}{Permettimi di riporre la mia arma, cosi' potremo parlare in pace.}
{117}{}{Cosi' va meglio. Saro' felice di fare affari con te.}
{118}{}{Benvenuto, compagno. Come posso aiutarti?}
{119}{}{Lugga!?}
{120}{}{Cosa vendi di bello?}
{121}{}{Grazie. Ci si vede, compare.}
{122}{}{Mi dispiace. Ma forse possiamo metterci d'accordo.}
{123}{}{Brye!}
{124}{}{A tra un po', cocorico'. Non riesco a credere di averlo detto.}
{125}{}{Benvenuto! Posso aiutarti? Spero che tu sappia quanto le tue decisioni future potrebbero interessare il destino della tua anima...}
{126}{}{Baarta!}
{127}{}{Cosa vendi?}
{128}{}{Dove posso trovare una di quelle strane vesti che indossate...?}
{129}{}{Solo i membri fidati della Cattedrale possono indossare il sacro viola.}
{130}{}{Immagino che questo risponda alla mia domanda, grazie!}
{131}{}{Pazzo borioso. Saro' costretto a prendere la tua!}
{132}{}{Oh, pazienza. Cosa vendi?}
{133}{}{Oh, solo della roba per gabbare gli zotici che entrano dalla porta. Niente di speciale. Ma prego, guarda pure.}
{134}{}{Grazie, ci vediamo.}
{135}{}{Abbiamo ogni tipo d'oggetto che serve per ricordare il pellegrinaggio alla Cattedrale. Certi ricordi non costano poco, tu capisci...}
{136}{}{Grazie...}
{137}{}{Prego. Che la tua vita sia sempre radiosa.}