{100}{}{Tempo rimasto:  }
{101}{}{ secondi.}
{102}{}{Alla fine sei riuscito a lasciare un segno tangibile nella storia (un piccolo mucchietto di polvere).}
{104}{}{Tempo rimasto:  }
{105}{}{ secondi.}
{106}{}{Alla fine sei riuscito a lasciare un segno tangibile nella storia (un piccolo mucchietto di polvere).}
{108}{}{Tempo rimasto:  }
{109}{}{ secondi.}
{110}{}{Alla fine sei riuscito a lasciare un segno tangibile nella storia (un piccolo mucchietto di polvere).}
