{100}{}{You see: Dragon, a member of the Blades.}
{101}{}{}
{102}{}{}
{103}{}{Vedi un membro dei Blade.}
{104}{}{Vedi un membro dei Blade.}
{105}{}{Dovrebbe trattarsi di Books.}
{106}{}{Dovrebbe trattarsi di Scars.}
{107}{}{Dovrebbe trattarsi di Gunner.}
{108}{}{Dovrebbe trattarsi di Twitch.}
{109}{}{Dovrebbe trattarsi di Hammer.}
{110}{}{Dovrebbe trattarsi di Razor.}
{111}{}{Sparisci! Non vedi che sto cercando di riposare?!}
{112}{}{Che ci fai da queste parti?}
{113}{}{Sto guardando le stelle.}
{114}{}{Cercavo te.}
{115}{}{Sono a caccia.}
{116}{}{Il tuo aspetto ti tradisce. Com'e' 'sta storia? Dimmi la verita', e forse ti risparmiero'.}
{117}{}{Sono qui per ucciderti. Davvero.}
{118}{}{Voglio mettere fine alla guerra tra bande.}
{119}{}{Sto cercando la via di casa. E' proprio la'. La luna.}
{120}{}{Non credo che mi farebbe piacere, ma non ho paura dei morti.}
{121}{}{Bel tentativo. Ora, se non te ne vai immediatamente, ti faccio cacciare dalle guardie.}
{122}{}{Giusto cielo, la tua vita non dev'essere piacevole. Ti aiutero' a porre fine ad essa.}
{123}{}{Bene, mi hai trovato. Adesso sparisci o sei morto!}
{124}{}{I think I'll go.}
{125}{}{I'd really rather live.}
{126}{}{Cosa hanno detto i Ripper?}
{127}{}{Che vi ammazzeranno!}
{128}{}{They're dead. Deathclaws killed'em all, see?}
{129}{}{Ancora nulla.}
{130}{}{Ottimo. Vallo a dire a Razor.}
{131}{}{Non provare a mentirmi. Sparisci!}
{132}{}{Allora porta le tue chiappe fuori di qui e secca quei bastardi!}
{133}{}{Yo, homie! Nice job you did on the Regulators!}
