{100}{}{Non voglio parlarti.}
{101}{}{Vattene.}
{102}{}{Lasciami in pace!}
{103}{}{Qualcuno dovrebbe darti una lezione.}
{104}{}{Fuori dai piedi, stronzo.}
{105}{}{Non voglio avere niente a che fare con te.}
{106}{}{I'm not supposed to talk to strangers.}
{107}{}{Go away, I don't wanna talk to you!}
