{100}{}{Pompa d'idropressurizzazione, cavo elettro-fibroso, vaporatore di condensa, griglia energetica, adattatori a tre poli... in parole povere, un bel po' di pezzi di ricambio.}
{101}{}{Con questi pezzi di ricambio Miles potrebbe riparare le fattorie idroponiche.}
