{100}{}{You see Fire, a member of the Blades.}
{101}{}{}
{102}{}{}
{103}{}{Vedi un membro dei Blade.}
{104}{}{Vedi un membro dei Blade.}
{105}{}{Potrebbe trattarsi di Books.}
{106}{}{Potrebbe trattarsi di Scars.}
{107}{}{Potrebbe trattarsi di Gunner.}
{108}{}{Potrebbe trattarsi di Twitch.}
{109}{}{Potrebbe trattarsi di Hammer.}
{110}{}{Potrebbe trattarsi di Razor.}
{111}{}{Cazzo vuoi, sfigato?}
{112}{}{Err.}
{113}{}{Vorrei diventare un Blade.}
{114}{}{Cosa posso fare perche' tra voi e Adytum ci sia la pace?}
{115}{}{This! [you slap him]}
{116}{}{Niente. Scusa se ti ho disturbato.}
{117}{}{Sto solo dando un'occhiata al vostro covo.}
{118}{}{Great, another idiot. You sound like a Ripper.}
{119}{}{Rrrrr.}
{120}{}{Arrrr.}
{121}{}{Arrooo?}
{122}{}{Anche a te non piacciono, eh? Forse potresti fare un "lavoretto" per noi.}
{123}{}{Urroo.}
{124}{}{Un nah.}
{125}{}{Okay, parla con la nostra boss. Razor ti dira' cosa fare.}
{126}{}{Stupido e cacasotto. Ti faro' un favore, uccidendoti subito.}
{127}{}{Quindi sei un Regolatore! Dovrei essere stupito, ma gia' sapevo che erano tutti degli idioti. Buonanotte!}
{128}{}{I Regolatori. Quei coglioni dall'altra parte della citta'. Lasciamo perdere. Sei troppo stupido per sapere qualcosa.}
{129}{}{Vuoi diventare un Blade? Buona fortuna. Ma se riesci a trovare Razor, puoi parlarne con lei. Forse ti dara' un "compitino".}
{130}{}{Okay, grazie.}
{131}{}{Allora non voglio!}
{132}{}{Che cosa intendi per "compitino"?}
{133}{}{Non puoi farmi entrare tu, nella banda?}
{134}{}{Tua madre non ti ha mai voluto, e nemmeno noi.}
{135}{}{Semplice. Per diventare uno di noi ci dovrai aiutare a liberarci di qualcuno. Lei ti dira' chi.}
{136}{}{Okay, grazie.}
{137}{}{Lasciamo perdere. Non voglio far parte di questa stupida banda.}
{138}{}{No. Non posso. Non comando io. Il mio compito e' solo quello di tenere d'occhio Razor.}
{139}{}{Semplice. Elimina i nostri nemici e Adytum non avra' piu' problemi.}
{140}{}{Chi sono i vostri nemici?}
{141}{}{Mi sta bene. Posso fidarmi di voi?}
{142}{}{Combattere e' sbagliato! Non lo faro'!}
{143}{}{The Regulators. They rule Adytum. They ain't stupid and are very dangerous.}
{144}{}{Okay, I'll kill the Regulators.}
{145}{}{Come non detto.}
{146}{}{Se pensi di farlo, faresti meglio a dirlo a Razor. Forse ha qualche consiglio da darti.}
{147}{}{Fa' come vuoi. Addio.}
{148}{}{Io non faccio accordi. Io do soltanto consigli. Se vuoi accordarti, parla con Razor.}
{149}{}{Credo che ucciderti adesso ti risparmierebbe lunghi anni di sofferenza.}
{150}{}{E allora prova questo!}
{151}{}{Se vuoi vivere... sparisci.}
{152}{}{Silenzio. Stiamo cercando di infiltrarci nel territorio dei Regolatori.}
{153}{}{Se hai fatto quello che dovevi fare, parlane con Razor. Ha proprio bisogno di sentire qualche buona notizia. Altrimenti, vattene!}
{154}{}{Yo, compare!}
