{100}{}{Hai acceso la torcia chimica.}
{101}{}{Questa torcia chimica e' esaurita.}
{102}{}{La torcia ha finito il combustibile e si e' spenta.}
{103}{}{Vedi una torcia chimica accesa.}
{104}{}{Vedi una torcia chimica esaurita.}
{105}{}{Vedi una torcia chimica.}
