{100}{}{Vedi Garret.}
{101}{}{Durante il giorno non dovresti farti vedere qui attorno. La cosa rende inquieto Set. Torna stanotte.}
{102}{}{Oh, okay.}
{103}{}{Dovrebbe imparare ad affrontare i suoi problemi.}
{104}{}{Non ha importanza. E' assolutamente necessario che io parli subito con lui.}
{105}{}{Dovresti parlare con Set.}
{106}{}{You receive: a shotgun, 10 shotgun shells, 4 flares, 4 bottles of Nuka-Cola, and 200 caps.}
{107}{}{Ricevi: un fucile a pompa, 10 proiettili e 100$.}
{108}{}{You receive: 4 flares, 4 bottles of Nuka-Cola, and 50 caps.}
{109}{}{Adesso faresti meglio ad andartene.}
{110}{}{Ci vediamo.}
{111}{}{E' tutto qui? Mi merito di piu', e faresti meglio a darmelo!}
{112}{}{Yerg.}
{113}{}{Devi andartene... e subito.}
{114}{}{Seguimi. Ti daro' la tua ricompensa.}
{115}{}{Spero di no, per il tuo bene. Set non era molto contento d'aver usato te. Forse faresti meglio a lasciare Necropolis... e in fretta.}
{116}{}{I told you to leave.}
{117}{}{Vabbe'.}
{118}{}{Forse hai ragione. Hmm. Ecco, prendi anche questi.}
{119}{}{You receive 100 caps.}
{120}{}{Adesso vattene.}
{121}{}{Hmm. Dal frigo mancano alcune cose. Pare che siamo stati derubati.}
{200}{}{Garret ti ignora.}
{201}{}{Ecco la tua ricompensa.}
{202}{}{Ricevi una grossa ricompensa.}
{203}{}{Ricevi: }
{204}{}{un fucile a pompa}
{205}{}{dei proiettili}
{206}{}{delle torce chimiche}
{207}{}{una torcia chimica}
{208}{}{a few bottles of Nuka-Cola}
{209}{}{a bottle of Nuka-Cola}
{210}{}{ caps}
