{100}{}{Vedi un Corista della Cattedrale.}
{101}{}{Il Master perdonera' i tuoi peccati! Unisciti a noi e sarai libero! Lode al Master e alla Sua clemenza!}
{102}{}{Salve, amico! Che ne diresti di cantare un "Lode" insieme a me? ...Vagavo cieco un tempo, in una terra che non lascia scampo...}
{103}{}{Odio interrompere il tuo inno, ma dove potrei incontrare il Master?}
{104}{}{Continua pure con le tue filastrocche.}
{105}{}{Chi e' che comanda qui?}
{106}{}{...ma del Master il culo ora bacio contento...}
{107}{}{Grazie, Signore, grazie! Grazie, Signore, grazie! Grazie!}
{108}{}{Egli ti trova quando e dove meno te lo aspetti! Lode al Master! Lode alla Sacra Fiamma! Lode al mondo!}
{109}{}{Che magnifica battuta! Una volta non avevo il minimo senso dell'umorismo, ma grazie al Master adesso sono pieno di humor! Lode al Master!}
{110}{}{Colui che risiede in alto. Colui che risiede in basso. Colui che risiede nel profondo. Lode al Master per la Sua chiarezza!}
{111}{}{Oh, se solo fossi cosi' fortunato! Che giorno glorioso sarebbe, se il Master mi permettesse di baciare una parte del suo corpo. Lode al Master! Lode alla Sacra Fiamma!}
{112}{}{Hmm, non e' quello che avevo in mente. Faresti meglio ad esercitarti di piu', amico mio. Lode al Master! Lode alla Sacra Fiamma!}
{113}{}{[Fatto]}
