{100}{}{Il predone ha troppa paura di Garl per parlarti ancora.}
{101}{}{Vedi un robusto predone del deserto.}
{102}{}{E' "Mano della Morte". E' tornato!}
{103}{}{Mi perdoni, Mano della Morte. Mi dispiace di averla disturbata.}
{104}{}{E' tornato per uccidere suo figlio?}
{105}{}{Aiyeee! Un fantasma!}
{106}{}{I morti ritornano a vivere! La Mano della Morte e' tornata!}
{107}{}{Salve.}
{108}{}{Ciao.}
{109}{}{Sto aspettando che Garl si decida a schiacciare Shady Sands. Ho voglia di bottino.}
{110}{}{Ehila', amico.}
{111}{}{Sono contento che tu sia tornato a farci visita.}
{112}{}{A meno che tu non voglia guai, faresti meglio a metter via quell'arma.}
{113}{}{Vuoi divertirti?}
{114}{}{Oh, un duro, eh?}
{115}{}{"Mano della Morte" Garl adora i suoi guerrieri. Metti via quell'arma e va' a parlare con lui.}
{116}{}{E cosi' ti credi un duro, eh? Prova a darmi fastidio e scopriremo se hai ragione.}
{117}{}{La tua faccia non mi piace.}
{118}{}{Vattene!}
{119}{}{Che vuoi?}
{120}{}{Sto cercando una ragazza di nome Tandi. L'hai vista?}
{121}{}{Niente. Davo solo un'occhiata in giro.}
{122}{}{Eh??}
{123}{}{Oh. Forse stai cercando lavoro. Va' da Garl, nella sala grande, e lascia in pace noialtri.}
{124}{}{E allora vedi di farlo da qualche altra parte.}
{125}{}{Nah. Non l'ho vista. Perche' lo chiedi?}
{126}{}{Niente. Un mio amico mi ha chiesto di cercarla.}
{127}{}{C'e' una taglia sulla sua testa. Se la uccido mi becco un mucchio di quattrini.}
{128}{}{Stai mentendo. Dov'e'?}
{129}{}{Ah, okay.}
{130}{}{Davvero? Che aspetto ha?}
{131}{}{Alta circa un metro e settanta. Bionda. Viene da Shady Sands.}
{132}{}{Si', e' qui. Sta nella baracca grande. Ma, sai, se lo dicessimo a Garl, lui vorrebbe per se' una parte della taglia. Forse dovresti pensarci.}
{133}{}{Non me la dai a bere. Credo che tu stia tramando qualcosa. Ma se invece dici la verita', vorra' dire che saro' io ad intascare l'intera ricompensa.}
{134}{}{Io... io non posso dire altro o Garl mi uccidera'.}
{135}{}{Fottiti!}
{136}{}{La tua faccia non mi piace. Faresti meglio ad andartene.}
{137}{}{Che cazzo vuoi? Sparisci!}
#
# Fallout Fixt:
#
{200}{}{He looks to be seasoned by combat and accustomed to the harsh life of the wastes.}
{201}{}{His body language says more than his expression. Both aren't very nice.}
{202}{}{He sneers at you and tightens the grip on his weapon.}
{203}{}{She looks to be seasoned by combat and accustomed to the harsh life of the wastes.}
{204}{}{You get the feeling that "lady" would not be an appropriate word for this woman.}
{205}{}{She makes a lewd gesture with her hips and winks at you.}
