{100}{}{Vedi un membro della banda degli Skulz.}
{101}{}{Ehi! Cosa cazzo credi di fare?!}
{102}{}{Sei nel territorio degli Skulz, straniero. Faresti meglio a levare le tende.}
{103}{}{Hai qualche moneta che ti avanza?}
{104}{}{Cosa cazzo c'hai da guardare?}
{105}{}{Sparisci.}
{106}{}{Zzzzzzzz}
{107}{}{Cazzo, fa un caldo allucinante.}
{108}{}{Ho fame.}
{109}{}{Facciamo qualcosa.}
{110}{}{Perche' non facciamo la festa a qualcuno?}
{111}{}{Ho voglia di divertirmi un po'.}
{112}{}{Yawn...}
