{100}{}{Vedi un abitante del Vault.}
{101}{}{Non riesco a credere che tu ci abbia traditi!}
{102}{}{Traditore!}
{103}{}{Ti odio. Perche' sei tornato?!}
{104}{}{Che tu possa strozzarti!}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Grazie per averci salvati.}
{110}{}{Non credevo che ce l'avresti fatta, ma adesso mi fido di te.}
{111}{}{Grazie! Grazie!}
{112}{}{Sei un eroe. Il mio bambino vuole diventare come te, quando sara' grande. Non credo che mi farebbe piacere, pero'.}
{113}{}{Sei un'eroina. La mia piccola vuole diventare come te, quando sara' grande. Ma non credo mi faccia piacere.}
{114}{}{Sei grande!}
{115}{}{Sei grande!}
{116}{}{Credi davvero che quella ti serva anche qui dentro?}
{117}{}{Quella e' un'arma!}
{118}{}{Hai davvero usato quell'arma contro qualcuno?}
{119}{}{Perche' credi che sia necessario girare qui dentro con un'arma?}
{120}{}{E' un piacere rivederti.}
{121}{}{Sono felice che tu stia bene.}
{122}{}{Mi sembri un tipo a posto. Tutte quelle voci devono essere false.}
{123}{}{Ciao }
{124}{}{. Continua cosi'.}
{125}{}{Spero che tutto stia andando per il meglio, la' fuori. Abbiamo proprio bisogno di quell'acqua.}
{126}{}{Stiamo finendo le razioni d'acqua. E' terribile!}
{127}{}{Ti prego, sbrigati a ritrovare quel chip. Abbiamo bisogno di te.}
{128}{}{Sono felice che tu stia bene. Continua cosi'.}
{129}{}{Non mi piace dirlo, ma se non troverai in fretta il water chip, moriremo tutti.}
{130}{}{Ogni notte la mia bambina si sveglia piangendo e mi chiede un po' d'acqua da bere... e io non posso darle niente.}
{131}{}{Non sopravviveremo, vero?}
{132}{}{Le razioni d'acqua stanno per finire.}
{133}{}{Anche la sezione idroponica e' stata chiusa. Cio' significa che presto finiremo anche il cibo.}
{134}{}{Hmm. Mi sembri ancora un essere umano. La vita la' fuori non dev'essere poi cosi' dura.}
{135}{}{Ciao }
{136}{}{. }
{137}{}{Spero che la tua missione proceda per il meglio.}
{138}{}{Ci vediamo.}
{139}{}{Hai parlato con il Supervisore, ultimamente?}
{140}{}{Il Supervisore e' molto preoccupato per lo stato della tua missione.}
{141}{}{Devi sbrigarti. Non ci possiamo permettere passi falsi da parte tua.}
{142}{}{Spero che tu stia facendo del tuo meglio.}
{143}{}{Non hai tempo per riposarti. Torna la' fuori.}
{144}{}{Non e' questo che dovresti fare, non credi?}
{145}{}{Moriremo tutti. E sara' soltanto colpa tua.}
{146}{}{Non stare qui impalato e torna all'esterno! Subito!}
{147}{}{Se moriremo, sara' tutta colpa tua.}
{148}{}{Il mondo esterno ti ha corrotto, vero?}
{149}{}{Lasciami in pace.}
{150}{}{Credo che dovresti lasciare in pace me e la mia famiglia, }
{151}{}{. E faresti meglio ad ascoltarmi.}
{152}{}{Dovresti solo vergognarti.}
{153}{}{E pensare che una volta mi piacevi.}
{154}{}{L'abitante del Vault non ti risponde.}
{155}{}{Uno sguardo di ghiaccio accoglie la tua domanda.}
{156}{}{Mi dispiace solo che abbiano scelto te.}
{157}{}{L'acqua e' malsana, ma la tua presenza e' peggiore.}
{158}{}{Vattene. Vattene e basta. L'unico modo per farti perdonare sarebbe quello di trovare il chip.}
{159}{}{Spero che tu sia soddisfatto.}
{160}{}{L'abitante del Vault si rifiuta di rispondere.}
{161}{}{E' tutta colpa tua! E probabilmente sei stato tu a danneggiare il water chip!}
{162}{}{Ti odio. Ma davvero tanto.}
{163}{}{L'abitante del Vault si limita a versare calde lacrime.}
{164}{}{La tua domanda e' accolta da uno sguardo gelido.}
{165}{}{Grazie.}
{166}{}{E' tardi. Torna in un altro momento.}
{167}{}{L'abitante del Vault sta riposando.}
