{100}{}{Vedi un corpo senza vita che giace a terra.}
{101}{}{Qui giace un'anima sfortunata.}
{102}{}{I resti di un umano mutato riposano sul pavimento.}
{103}{}{Un ottimo pasto per i mangiatori di carogne.}
{104}{}{Questa persona deve aver sfidato Thanatos. E sembra proprio che abbia perso la sfida.}
