{100}{}{Vedi un profugo ghoul.}
{101}{}{Ti prego, non uccidermi.}
{102}{}{Vedi di tacere e forse ti risparmiero'.}
{103}{}{Non temere... non ne varrebbe la pena.}
{104}{}{Cos'e' successo?}
{105}{}{Gah.}
{106}{}{Mi... mi ucciderai lo stesso, lo so!}
{107}{}{Ah, oh. Okay.}
{108}{}{Bene, continua cosi'.}
{109}{}{Adesso dimmi cos'e' successo.}
{110}{}{Mi ucciderai!}
{111}{}{Ah, ma non mi hai appena detto di tacere?}
{112}{}{Adesso sei morto.}
{113}{}{Si', ma adesso voglio sapere cos'e' successo.}
{114}{}{I super mutanti ci hanno attaccati. Siamo stati massacrati. Avevano armi e bombe, alcuni persino carri a vapore. Hanno ucciso i miei amici. I mutanti ci hanno ammazzati come animali, proprio come tra poco tu farai con me.}
{115}{}{I super mutanti ci hanno attaccati. Siamo stati massacrati. Avevano armi e bombe, alcuni persino carri a vapore. Hanno ucciso i miei amici. I mutanti ci hanno ammazzati come animali.}
{116}{}{Cos'e' un carro a vapore?}
{117}{}{Come hai fatto a salvarti?}
{118}{}{E conosci il motivo di questo massacro?}
{119}{}{Non lo so.}
{120}{}{Grazie.}
{121}{}{Sei inutile.}
{122}{}{Pare che fossero infuriati perche' un umano ha ucciso i mutanti che presidiavano la citta'.}
{123}{}{Oh, ehm... c'e' dell'altro?}
{124}{}{Hmmm. Ok. Sparisci.}
{125}{}{No.}
{126}{}{Grazie.}
{127}{}{Sei inutile.}
{128}{}{Ho sentito che forse qualche ghoul che viveva nelle fogne e' sopravvissuto, ma non mi piace quel posto.}
{129}{}{Okay, thanks.}
{130}{}{Tutto qua?}
{131}{}{Si', tutto qua.}
{132}{}{Okay, thanks.}
{133}{}{Mi sono nascosto finche' la maggior parte dei mutanti non ha lasciato la citta'.}
{134}{}{C'e' altro?}
{135}{}{E' un coso enorme che si muove su ruote, ma senza essere trainato da brahmin.}
{136}{}{Hmm, okay. Anything else?}
{137}{}{Che idiozia.}
{138}{}{Ehi, e allora perche' me l'hai chiesto?}
{139}{}{Basta cosi'! Non tollerero' oltre la tua insolenza!}
{140}{}{Ero solo curioso. Tutto qua.}
{141}{}{Ancora tu? E adesso che cosa vuoi?}
{142}{}{Qualche novita'?}
{143}{}{Volevo solo fare una chiacchierata.}
{144}{}{No. Beh, ho sentito che dovrebbero arrivare altri super mutanti. Ma non so quando.}
{145}{}{Hmm. Okay.}
{146}{}{Sara' meglio che me ne vada. Devo mantenere un basso profilo.}
