{100}{}{Vedi una creatura fosforescente.}
{101}{}{Mmmm...}
{102}{}{Ahhh...}
{103}{}{L'essere fosforescente borbotta qualcosa; poi tace. Sta sbavando in maniera incontrollata.}
{104}{}{You receive no response.}
{105}{}{You see: Glowing One.}
