{100}{}{Un cadavere congelato.}
{101}{}{L'origine di questo cadavere non e' sicuramente terrestre.}
{102}{}{Questo corpo potrebbe essere il risultato di un esperimento genetico.}
{103}{}{Cosa? E' un cadavere.}
{104}{}{Questo corpo congelato ha un aspetto insolito.}
