{100}{}{Questo si direbbe il bauletto di qualche guardia.}
{101}{}{Hai scassinato la serratura.}
{102}{}{Non riesci a scassinare la serratura.}
{103}{}{Questo oggetto e' inutile, qui.}
{104}{}{La scatola e' chiusa a chiave.}
{105}{}{Hai scassinato la serratura.}
{106}{}{Non riesci a scassinare la serratura.}
{107}{}{Questa abilita' e' inutile, qui.}
