{100}{}{Vedi un ometto un po' in carne.}
{101}{}{Vedi Gretch, l'assistente del dottor Morbid.}
{102}{}{Cosa diavolo tu fai qui?}
{103}{}{Urgh?}
{104}{}{Mi manda il tuo capo.}
{105}{}{Non parlarmi in quel modo, idiota.}
{106}{}{Sono venuto a vedere come te la cavavi.}
{107}{}{Niente. Arrivederci.}
{108}{}{Io conosco te... giusto?}
{109}{}{No.}
{110}{}{Si'.}
{111}{}{Lasciamo perdere.}
{112}{}{Um... okay.}
{113}{}{Che cosa stai facendo?}
{114}{}{Bene? Vuoi forse dire che hai quasi finito?}
{115}{}{Sei un pochino tardo, vero?}
{116}{}{Si', si', quasi finito.}
{117}{}{Cosa?}
{118}{}{Era ora.}
{119}{}{Ottimo. Ci vediamo dopo.}
{120}{}{I pezzi di corpi quasi pronti sono per andare a Hub.}
{121}{}{Per cosa?}
{122}{}{Ma certo. E' per questo che sono qui.}
{123}{}{Non credo di voler sapere altro.}
{124}{}{Bob degli Iguana manda te... lui felice, un sacco di buona carne...}
{125}{}{Vende pezzi di cadaveri umani come cibo?}
{126}{}{Brutto pidocchio malato! Adesso ti faro' a pezzi io e poi ti vendero' ad una macelleria!}
{127}{}{Certo... Torna tra in uno minuto.}
{128}{}{Per Bob... da vendere... come cibo... perche' tu me lo chiedi?}
{129}{}{Cosi'. Ci vediamo.}
{130}{}{Non ero certo che Bob prendesse la sua carne umana proprio da qui.}
{131}{}{A volte la memoria mi fa dei brutti scherzi.}
{132}{}{Anche a me ricordare e' difficile... di cosa noi parlavamo?}
{133}{}{Non ricordo. Ci vediamo.}
{134}{}{Mi stavi dicendo quello che stavi facendo.}
{135}{}{Stavamo discutendo di quanto stupido tu sia.}
{136}{}{Boh?}
{137}{}{Non parlero' piu' io con te.}
{138}{}{Si'... Dottore ha lui le migliori parti umane della zona. Nessuno ha migliori.}
{139}{}{Uh... Tornero' per prendere i... pezzi... tra poco. Ci vediamo.}
{140}{}{Io torno al lavoro, adesso.}
{141}{}{Non fare tu casino con roba di Dottore!}
