{100}{}{You see a desert bandit. Based on how the others look at her, she must have some position of importance or authority.}
{101}{}{Sono Gwen. Sono uno dei consiglieri di Garl. E tu chi saresti?}
{102}{}{Sono }
{103}{}{. Di cosa vi occupate?}
{104}{}{Nessuno di speciale. Puoi parlarmi un po' della vostra banda?}
{105}{}{Hroo?}
{106}{}{Sono quello che ti fara' le scarpe, dolcezza.}
{107}{}{Come consigliere, faccio in modo che nessun pezzente dia fastidio a Garl.}
{108}{}{E come ci riesci?}
{109}{}{Tu... e quale esercito?}
{110}{}{Dubito che tu possa fermare chicchessia.}
{111}{}{Dev'essere dura: a me sembra che qui dentro sia pieno di pezzenti. A cominciare da te.}
{112}{}{Hmpf. Se non sei nessuno di speciale, di certo non perdero' del tempo a parlare con te. Vattene.}
{113}{}{Gli idioti come te li tengo alla larga da Garl. Sparisci!}
{114}{}{So il fatto mio, soprattutto quando si tratta di tenere alla larga da qui certi individui indesiderabili.}
{115}{}{Evidentemente mi sbagliavo. Forse sei davvero in grado di fare bene il tuo lavoro. Arrivederci.}
{116}{}{Dimostramelo!}
{117}{}{Muori!}
{118}{}{E' da un po' di tempo che non pesto qualcuno. E' un peccato che tu abbia gia' perso in partenza. Eccoti una prova delle mie capacita'!}
{119}{}{Ti pentirai delle tue parole. Soprattutto perche' saranno le ultime che dirai!}
{120}{}{Se questo e' il meglio che sai fare, vuol dire che uccidendoti faro' un favore al mondo.}
{121}{}{Io e questo esercito!}
{122}{}{Mi stai stufando. Vattene, prima che mi arrabbi sul serio.}
#
# Fallout Fixt:
#
{200}{}{You see: Gwen, the Khans' second-in-command and advisor to Garl.}
