{100}{}{Vedi Harold.}
{101}{HROLD0}{Hai degli spiccioli, vecchio amico, vecchio amico mio? Puoi aiutare un povero mutante tormentato dalla sfortuna? [Cough]}
{102}{}{Yeah, here are 25 caps. Good luck to you.}
{103}{}{How about 5 caps?}
{104}{}{Mi spiace, ma non ho soldi con me.}
{105}{}{Stammi lontano!}
{106}{}{Uhhh?}
{107}{HROLD1}{Capperi. Sei messo peggio di me, amico. Buona fortuna a te.}
{108}{HROLD2}{Oh, gentile da parte tua, amico. Davvero gentile. Sai, se potessi togliermi le porcherie che c'ho dentro, potresti persino trovarci una lacrima, negli occhi del vecchio Harold.}
{109}{}{Come mai?}
{110}{}{Non c'e' di che.}
{111}{HROLD3}{[Cough] Da quando sono tornato in citta', gli Hubbitani mi trattano peggio di un cane. Non posso andarmene, pero'. Tutto sommato [wheez] e' ancora casa mia.}
{112}{}{Che cosa ti e' successo?}
{113}{}{Chi sono gli Hubbitani?}
{114}{}{Spero che le cose ti vadano meglio. Ci si vede.}
{115}{HROLD4}{Beh, dopo la Grande Guerra il mio Vault e' stato uno dei primi ad aprirsi. [Fa un profondo respiro] Fiuu. Ne e' passato di tempo.}
{116}{}{Parlami un po' di quei giorni.}
{117}{}{No, no. Voglio sapere cosa ti ha ridotto cosi'.}
{118}{HROLD5}{Tutto comincio' con le sirene. Ero giovane, ma ohhh, me lo ricordo bene. Molti terribili anni seguirono... E mi rivedo mentre, in una tarda mattinata, esco dal mio Vault.}
{119}{}{Cosa hai fatto a quel punto?}
{120}{}{Dove si trovava il tuo Vault?}
{121}{}{Ma questo vuol dire che sei vecchissimo!}
{122}{HROLD6}{Sai, [cough] non ne sono certo nemmeno io. Ad ovest, credo. Hm, aspetta - ad est? Ohh, non lo so.  [cough cough]}
{123}{}{Cosa hai fatto a quel punto?}
{124}{HROLD7}{Beh, ho fatto il mercante. E me la cavavo bene, girando tra i vari gruppi di sopravvissuti. Ho perso un sacco di brava gente, pero'. [Tossisce]}
{125}{}{Come?}
{126}{HROLD8}{Colpa dei banditi. Dei disperati che attaccavano le carovane. E dei mutanti: figlio d'un cane, che mi venga un colpo se non sbucavano fuori come conigli. [cough] Ho dovuto assoldare un esercito di guardie.}
{127}{}{E sono servite a qualcosa?}
{128}{}{Da dove venivano i mutanti?}
{129}{HROLD9}{Certo che sono servite a qualcosa, testa di legno! Semplicemente ce n'erano troppi!}
{130}{}{Come hai fatto a sopravvivere?}
{131}{HROLD9A}{Non sono sopravvissuto. Infatti sono morto. [Ride tossendo] Adoro questo scherzo.}
{132}{}{Ah, certo.}
{133}{HROLD10}{Dappertutto! Diavolo, sembrava che non si potesse scoreggiare senza colpirne uno. Ma soprattutto verso nordovest.}
{134}{}{Avete esplorato quella zona?}
{135}{}{Perche' non avete evitato quella zona, allora?}
{136}{}{Hai scoreggiato verso nordovest?}
{137}{hrold10a}{*chuckle* Pretty good... Noo...}
{138}{HROLD11}{Abbiamo messo su una spedizione.  Dio, Richard.  Richard Grey.  E' stato lui a guidare il nostro gruppo lassu'.}
{139}{}{Richard Grey?}
{140}{}{Dove siete andati esattamente?}
{141}{HROLD12}{Dovevamo vedere cosa c'era laggiu'. E magari metter fine alle attivita' di quei bastardi. Pensavamo di essere preparati. Ci sbagliavamo.}
{142}{}{Che cosa avete fatto?}
{143}{HROLD13}{Non ricordo ne' il percorso ne' altro. Ma sono dannatamente sicuro che fosse a nordovest, pero'... credo.}
{144}{}{Non e' che conosci una versione breve della storia?}
{145}{}{Cosa mi puoi dire del vostro leader?}
{146}{HROLD14}{Richard Grey era un dottore. Un po' piu' anziano di me, e cavoli se era sveglio. Ha trovato la fonte.}
{147}{}{E cos'era?}
{148}{HROLD15}{Mi piace raccontarla a modo mio. La versione breve ti costera' un extra di 25$, amico. Quale preferisci?}
{149}{}{Ok, vada per la lunga.}
{150}{}{La breve.}
{151}{}{La breve, ma non ho i soldi.}
{152}{}{E se ti dicessi "nessuna", vecchio bacucco?}
{153}{HROLD16}{Beh, mi sembri un tipo a posto.  Cerchero' di accorciare un po'.}
{154}{}{Grazie.}
{155}{hrold16a}{Mentire ad un povero vecchio mutante. Cos'e' diventato il mondo? [cough]}
{156}{hrold17}{Siamo un po' a corto di soldi, eh?}
{157}{hrold17a}{A modo mio, oppure puoi andartene. La scelta sta a te, amico.}
{158}{}{Me ne vado.}
{159}{}{Okay. Long it is.}
{160}{HROLD18}{Una specie di vecchia base militare. Solo per entrare abbiamo perso una marea di compagni.}
{161}{}{Come sapevate che era da quella base che uscivano i mutanti?}
{162}{}{Contro cosa vi siete trovati a combattere?}
{163}{HROLD19}{Robot e cose del genere. Una marea. Che fottuta sorpresa scoprire che funzionavano ancora dopo tutto quel tempo, dopo una guerra di quel tipo.  Whaa, ragazzi: ci hanno proprio massacrato.}
{164}{}{Cosa avete fatto dopo aver superato i robot?}
{165}{HROLD20}{Perche' sembrava di essere ad una svendita di fine stagione: mutanti in ogni angolo! Cavoli! C'erano persino le offerte speciali! Non poteva esserci altra spiegazione: ci trovavamo nel posto dove li fabbricavano.}
{166}{}{Avete esaminato la base da vicino?}
{167}{HROLD21}{Siamo penetrati un bel po' all'interno. Ma a quel punto non eravamo rimasti in tanti. Grey, io ed un paio di altri.}
{168}{}{E poi?}
{169}{HROLD22}{Uno di quei robot ha ucciso Francine. Mark era ferito e l'abbiamo rimandato in superficie. Quindi rimanevamo solo io e Grey.}
{170}{}{Che ne e' stato di Mark?}
{171}{}{E poi cos'e' successo?}
{172}{HROLD23}{In tutti questi anni non l'ho mai saputo. Non e' mai tornato qui e... beh, io... non me la sono piu' sentita di affrontare di nuovo le lande, per cui... non l'ho mai cercato.}
{173}{}{E cos'e' successo a te e Grey?}
{174}{HROLD24}{Siamo arrivati ad una specie di nucleo centrale, una sorta di impianto. E' stato allora che e' successo.}
{175}{}{Cosa?}
{176}{HROLD25}{Una gru ci ha travolto. L'ultima volta che ho visto Grey, stava volando dentro una specie di vasca piena di acido. Io ero messo male e... beh, sono svenuto.}
{177}{}{Come sei sopravvissuto?}
{178}{}{E non hai piu' rivisto Grey?}
{179}{hrold25a}{Didn't. Got killed! Haha! *cough* God, I love that joke.}
{180}{}{Gia', lo vedo.}
{181}{HROLD26}{Beh, non ne ho idea. Mi sono risvegliato nelle lande che mi reggevo a malapena in piedi. Ho avuto fortuna e alcuni mercanti che conoscevo mi hanno trovato qualche giorno dopo. Mi e' andata bene, dato che stavo gia' cambiando. Mi hanno portato qui... e qui sono rimasto da allora.}
{182}{}{Cosa ha causato la tua mutazione?}
{183}{}{Davvero una bella storia. Grazie.}
{184}{hrold26a}{Beh... grazie a te per avermi permesso di raccontartela.}
{185}{}{E questa era la versione breve?}
{186}{hrold26a}{Beh... grazie per avermi permesso di raccontartela.}
{187}{hrold26b}{Per me lo era.}
{188}{HROLD27}{No, idiota! Ti ho appena detto che non l'ho piu' rivisto, no?}
{189}{}{Come sei sopravvissuto?}
{190}{HROLD28}{Tutto quel che so e' che e' stato qualcosa che era dentro quella base.}
{191}{}{Credi sia possibile che le radiazioni c'entrino qualcosa?}
{192}{}{Una bella sfortuna. Grazie per la storia.}
{193}{HROLD29}{E come diavolo faccio a saperlo? Se c'era qualcuno che ci capiva qualcosa, quello era Gray. [sigh] Comunque, e' cosi' che e' andata la faccenda.}
{194}{}{Grazie per la storia.}
{195}{HROLD30}{Gia'... avro' uno o due secoli, in anni canini.}
{196}{}{Cosa?}
{197}{HROLD31}{Lascia perdere, e' una cosa che aveva senso ai miei tempi. Sono malfermo, vecchio ed e' cosi' sin da quando sono cambiato.}
{198}{}{Che cosa facevi prima?}
{199}{HROLD32}{Beh, sono mutato. Di certo non sono nato cosi' brutto. E' successo quando abbiamo tentato di scoprire da dove provenivano tutti i mutanti.}
{200}{}{Cos'e' successo?}
{201}{HROLD33}{E' roba che appartiene al passato. E probabilmente e' giusto che rimanga cosi'.}
{202}{}{Ti prego, dimmi cos'e' successo. Potrebbe tornarmi utile.}
{203}{}{Come preferisci.}
{204}{HROLD34}{Beh, se la metti cosi'. Non credo possa far male.}
{205}{}{Grazie.}
{206}{HROLD35}{No, no. E' troppo doloroso, persino adesso. Grazie dell'aiuto, amico. Buona fortuna.}
{207}{HROLD36}{Ti trovi nell'Hub, giusto? Le persone che vivono nell'Hub? Hubbitani. Capito? [cough] Sheesh! Grazie dell'aiuto e buona fortuna... penso che ne avrai bisogno.}
{208}{HROLD37}{Sei fatto della loro stessa pasta bastarda. [tossisce ansimando]}
{209}{HROLD38}{Oh beh, grazie lo stesso. [cough]}
{210}{HROLD39}{Ehi, non e' che puoi aiutarmi, amico?}
{211}{}{Yeah, here are 25 caps.}
{212}{}{Take 5 caps.}
{213}{}{Non seccarmi.}
{214}{}{Uhhh?}
{215}{HROLD40}{Ehi, ti ringrazio! Devo ammetterlo, appena ti ho visto [cough] credevo che volessi maltrattarmi.}
{216}{}{Perche'?}
{217}{}{Nah, non io! Prenditene una di quelle buone.}
{218}{HROLD41}{Oh, ehi, sei di nuovo tu.}
{219}{}{Here are 20 caps, if you need it.}
{220}{}{Ciao.}
{221}{}{Uhh?}
{222}{hrold42}{Cerchi di tirarmi su, eh?}
{223}{HROLD43}{Posso fare qualcosa?}
{224}{}{Hai sentito qualche voce interessante, ultimamente?}
{225}{}{Ho bisogno di informazioni sul Deathclaw, e ho sentito che tu sei la persona giusta.}
{226}{}{Qual e' la tua storia?}
{227}{}{Nope.}
{228}{hrold43a}{Vuoi sapere tutto? Beh...}
{229}{HROLD44}{Oooh... beh, grazie. Spero che non sia stato troppo faticoso. [cough]}
{230}{HROLD45}{Oooh, quel coso. Amico, quello e' uscito dagli incubi. Perche' diavolo vuoi che te ne parli?}
{231}{}{Devo ucciderlo.}
{232}{}{Se mi incontra, voglio sapere come comportarmi.}
{233}{HROLD47}{Okay. Beh, e' come un uomo dannatamente grosso. E' cosi' che e'. Ha aculei e artigli in grado di penetrare la corazza piu' robusta. Ma la stazza non deve ingannarti: e' veloce.}
{234}{}{Punti deboli?}
{235}{HROLD49}{Beh, da quello che ho sentito... forse colpirlo bello forte in testa? Io mirerei agli occhi. Certo, anche qui c'e' un problema.}
{236}{}{Che tipo di problema?}
{237}{HROLD50}{Non si possono guardare! Si dice che il Deathclaw sia in grado di ipnotizzare con un solo sguardo. A quel punto si avvicina e "bum", sei finito!}
{238}{}{Ottimo. Grazie.}
{239}{HROLD51}{Buona fortuna a te... ne avrai bisogno.}
{240}{}{Forse.}
{241}{HROLD52}{Tu NON vuoi sapere del Deathclaw e non saro' IO a parlartene.}
{242}{HROLD53}{Beh, ho sentito uno degli uomini di Decker dire che qualcuno tiene prigioniero un tizio della Confraternita d'Acciaio all'interno della Citta' Vecchia.}
{243}{}{Grazie.}
{244}{HROLD54}{A questa non ci credo, ma qualcuno dice che sta per arrivare un esercito di mutanti. [cough]}
{245}{}{Grazie.}
{246}{HROLD55}{Lasciami in pace. [cough]}
{247}{}{Voglio parlare con te.}
{248}{}{Eccoti un po' di spiccioli.}
{249}{HROLD56}{Beh, io non voglio parlare con te. Vattene!}
{250}{HROLD57}{Non voglio i tuoi soldi. Vattene. [cough]}
{251}{hrold200}{Anche se mi piacerebbe molto fare qualche baratto, non ho niente da darti in cambio. [cough]}
{252}{hrold201}{Ho bisogno di dormire un po'. Sono piuttosto stanco.}
{253}{hrold202}{Forse dovresti fare un po' piu' di attenzione. [cough] Ho sentito che hai ucciso diverse persone, ultimamente.}
{254}{hrold203}{Umm... Decker ti sta cercando. Vuole parlarti. [cough]}
{255}{hrold204}{Tutto cio' che ho sono questi vestiti e la liberta'. E quest'ultima e' negoziabile.}
{256}{hrold300}{Un tipo sveglio. Un dottore e un filosofo. Molto tempo fa ha condotto la spedizione durante la quale sono diventato un mutante.}
{257}{hrold301}{Chi? E' una specie di terapista del sesso? Sai, ne avrei proprio bisogno.}
{258}{hrold302}{Mutanti. Non importa il nome che si danno.}
{259}{hrold303}{Oh, lui. Guida la Cerchia dei Ladri. Crede di essere Robin Hood. [cough] Un tipo a posto, credo.}
{260}{hrold304}{Ho visto religioni nascere e morire... e spero che questa muoia. In fretta.}
{261}{hrold305}{Gia', vengo da un Vault. Troppe persone, cibo e acqua scarsi. Ma tanto tu non ne sai nulla, no?}
{262}{hrold306}{Orribile. Il mondo e' impazzito. E' successo tanto tempo fa, ma non lo scordero' mai. Mai.}
{263}{hrold307}{[Cough] Guai.  Nient'altro che guai.}
{264}{hrold400}{Beh, come ti ho detto...}
{265}{}{Niente, grazie.}

#
# TRANSLATION NOTE: The following groups of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ('my friend' will be masculine); the second line is
# for the case of the player-character feminine ('my friend' will be feminine).
#

{266}{HROLD0}{Hai degli spiccioli, vecchio amico, vecchio amico mio? Puoi aiutare un povero mutante tormentato dalla sfortuna? [Cough]}
{267}{HROLD0}{Hai degli spiccioli, cara, carissima amica mia? Puoi aiutare un povero mutante tormentato dalla sfortuna? [Cough]}
{268}{HROLD2}{Oh, gentile da parte tua, amico. Davvero gentile. Sai, se potessi togliermi le porcherie che c'ho dentro, potresti persino trovarci una lacrima, negli occhi del vecchio Harold.}
{269}{HROLD2}{Oh, gentile da parte tua, amica mia. Davvero gentile. Sai, se potessi togliermi le porcherie che c'ho dentro, potresti persino trovarci una lacrima, negli occhi del vecchio Harold.}
{270}{HROLD35}{No, no. E' troppo doloroso, persino adesso. Grazie dell'aiuto, amico. Buona fortuna.}
{271}{HROLD35}{No, no. E' troppo doloroso, persino adesso. Grazie dell'aiuto, amica mia. Buona fortuna.}
{272}{HROLD39}{Ehi, puoi aiutarmi, amico?}
{273}{HROLD39}{EHi, puoi aiutarmi, amica mia?}

#
# Harold's Tell-Me-Abouts
#
{1000}{}{Richard}
{1001}{}{Master}
{1002}{}{Ghoul}
{1003}{}{Loxley}
{1004}{}{Cattedrale}
{1005}{}{Vault}
{1006}{}{Guerra}
{1007}{}{Decker}
{1008}{}{Grey}

{1100}{hrold300}{Un tipo sveglio. Un dottore e un filosofo. Molto tempo fa ha condotto la spedizione durante la quale sono diventato un mutante.}
{1101}{hrold301}{Chi? E' una specie di terapista del sesso? Sai, ne avrei proprio bisogno.}
{1102}{hrold302}{Mutanti. Non importa il nome che si danno.}
{1103}{hrold303}{Oh, lui. Guida la Cerchia dei Ladri. Crede di essere Robin Hood. [cough] Un tipo a posto, credo.}
{1104}{hrold304}{Ho visto religioni nascere e morire... e spero che questa muoia. In fretta.}
{1105}{hrold305}{Gia', vengo da un Vault. Troppe persone, cibo e acqua scarsi. Ma tanto tu non ne sai nulla, no?}
{1106}{hrold306}{Orribile. Il mondo e' impazzito. E' successo tanto tempo fa, ma non lo scordero' mai. Mai.}
{1107}{hrold307}{[Cough] Guai.  Nient'altro che guai.}
{1108}{hrold300}{Un tipo sveglio. Un dottore e un filosofo. Molto tempo fa ha condotto la spedizione durante la quale sono diventato un mutante.}

