{100}{}{Vedi lo Sceriffo Justin Greene.}
{101}{}{Perdinci, l'uccisore degli innocenti e' proprio davanti a me. Ho sentito parlare di te, e sei fortunato che questo distintivo mi impedisca di spazzarti via all'istante. Ti consiglio di lasciare la citta' -- immediatamente. E sta' lontano dai nostri bambini.}
{102}{}{Salve, amico! Io sono Justin Greene. Sono lo sceriffo di questa bella citta'. E' una splendida giornata. C'e' qualcosa che posso fare per te?}
{103}{}{Salve, miss! Io sono Justin Greene. Sono lo sceriffo di questa bella citta'. E' una splendida giornata. C'e' qualcosa che posso fare per te?}
{104}{}{Ebbene, sputa il rospo!}
{105}{}{Decker ha cercato di assoldarmi perche' uccidessi un mercante e sua moglie.}
{106}{}{Decker ha cercato di assoldarmi perche' uccidessi una certa Jain.}
{107}{}{Niente. Scusa il disturbo.}
{108}{}{Mi dispiace, ma non posso parlare. Se lo facessi sarei morto.}
{109}{}{Beh, grazie. Noi facciamo del nostro meglio. E' davvero dura in una citta' cosi' grande, ma facciamo il massimo con quello che abbiamo. E' dura far rispettare la legge quando i delinquenti hanno un arsenale migliore del tuo.}
{110}{}{Grazie.}
{111}{}{E' ora che tu te ne vada, ammazzabambini.}
{112}{}{Non possiamo costringerti. Ma, se dovessi cambiare idea, ti prego di farmelo sapere. La' fuori e' un posto pericoloso, e qualcuno deve pur combattere per cio' che e' giusto.}
{113}{}{Magnifico! Avevo gia' sentito del suo piano da altre fonti. La tua e' la conferma che mi serviva per poter agire contro di lui. Sara' dura, e avremo bisogno di tutto l'aiuto possibile. Se vuoi unirti a noi, posso darti 1000 testoni. 200 subito, e il resto quando sara' tutto finito. Cosa ne dici?}
{114}{}{Troppo tardi... Merda! Sapevo che il responsabile era lui. Se solo l'avessi saputo in tempo per fermarlo. Ad ogni modo, tu sei l'ultimo testimone che mi serviva per poter agire. Dovremo andare a "stanarlo". Sara' dura e avro' bisogno di tutto l'aiuto possibile. Se vuoi darmi una mano, posso darti 1000 testoni. 200 subito, e il resto quando sara' tutto finito. Che ne dici?}
{115}{}{Troppo tardi... Ma come faccio a sapere che il responsabile non sei tu? Decker non e' tipo da rivelare i suoi piani al primo che passa.}
{116}{}{Mi hanno appena riferito che e' stata uccisa... Aspetta un attimo. Come faccio a sapere che il responsabile non sei tu? Decker non e' tipo da rivelare i suoi piani al primo venuto.}
{117}{}{Sara' un piacere.}
{118}{}{Mi dispiace, ma li voglio tutti subito.}
{119}{}{Scordatelo! Dovrai arrangiarti.}
{120}{}{Scordatelo. Sembri affidabile, ma non posso essere sicuro che tu non ci abbandonerai quando l'atmosfera si fara' incandescente. In questo modo, uno di noi deve sopravvivere perche' tu possa ricevere l'intera ricompensa. Possiamo definirla una specie di "assicurazione".}
{121}{}{Diamoci dentro.}
{122}{}{Allora dovrai arrangiarti, Sceriffo.}
{123}{}{Ottimo! Partiremo non appena sarai pronto.}
{124}{}{Sono pronto.}
{125}{}{Okay, ci vediamo.}
{126}{}{Ah, mi dispiace. Se cambiassi idea, fammelo sapere. Ma ricorda che non aspettero' ancora a lungo.}
{127}{}{Okay, lo faro'. Prima pero' devo comprare un po' di provviste.}
{128}{}{Sei matto.}
{129}{}{Ci si vede.}
{130}{}{Ottimo! Ti aspetteremo, ma non impiegarci troppo}
{131}{}{Cosa? Ti aspetti forse che resti qui e gli permetta di uccidere delle persone innocenti? Ho delle responsabilita' nei confronti di questa citta', anche se non mi aspetto che tu capisca cosa questo significhi.}
{132}{}{Hai ragione. E adesso e' il tuo turno.}
{133}{}{Come osi accusarmi?!}
{134}{}{Non mi interessa quello che pensi.}
{135}{}{Beh, eppure l'ha fatto.}
{136}{}{Eravamo al Falcone, e c'erano un sacco di persone presenti.}
{137}{}{Mi dispiace. Sono anni che Decker si diverte a metterci l'uno contro l'altro. Ormai non so piu' di chi fidarmi. Il tuo aiuto, tuttavia, mi farebbe molto comodo. Sara' dura, ma ti paghero' 1000 testoni. 200 adesso e 800 quando avremo finito.}
{138}{}{Riconosco un bastardo appena ne vedo uno! Sei fortunato che io non abbia prove, ma ti consiglio di lasciare la citta' prima che ne trovi qualcuna.}
{139}{}{Davvero molto strano. Sapevo che Decker non usciva mai dal suo ufficio. Dev'essersi fatto piu' coraggioso. Quel dannato assassino... argh! Ma lo prendero'! Senti: aiutami a stanarlo e ti daro' 1000 testoni -- 200 adesso e 800 quando sara' tutto finito. Cosa ne dici?}
{140}{}{E' il piu' grande mucchio di stronzate che io abbia mai sentito. Decker non lascia mai il suo ufficio. Lo sapevo che c'era qualcosa che non andava, in te. Sei fortunato che io non abbia prove, ma ti consiglio di lasciare la citta' prima che riesca a trovarne qualcuna!}
{141}{}{Okay, andiamo...}
{142}{}{Sei venuto per costituirti? Sono impressionato.}
{143}{}{Si', mi pento di tutte le mie colpe.}
{144}{}{Costituirmi? Io? Non farmi ridere.}
{145}{}{Prendetelo!}
{146}{}{Prendetela!}
{147}{}{D'accordo, fila in cella.}
{148}{}{Rimani fermo li'. Per un po' di tempo non andrai da nessuna parte.}
{149}{}{E' l'evaso! Prendetelo!}
{150}{}{E' l'evasa! Prendetela!}
{151}{}{Sei pronto?}
{152}{}{Si'.}
{153}{}{No.}
{154}{}{Ug.}
{155}{}{Non riesco a credere che Decker sia finalmente morto. Non avrei mai creduto di poter assistere a questo avvenimento.}
{156}{}{Hai cambiato idea? Potremmo ancora aver bisogno di te per quella "disinfestazione" di cui parlavamo prima.}
{157}{}{Vengo con voi.}
{158}{}{No, mi dispiace.}
{159}{}{Fah?}
{160}{}{Ti teniamo d'occhio.}
{161}{}{Devo denunciare un crimine!}
{162}{}{State facendo un buon lavoro.}
{163}{}{Sono solo di passaggio. Ci si vede.}
{164}{}{Oula.}
{165}{}{Bentornato, amico. Cosa posso fare per te, oggi?}
{166}{}{Bentornata, miss. Cosa posso fare per te, oggi?}
{167}{}{Salve. Posso aiutarti?}
{168}{}{Si'?}
{169}{}{Dimenticatene e basta, okay?}
