{100}{}{Vedi un bambino che vende fiori.}
{101}{}{Hello! Would you... oh, excuse me...}
{102}{}{Tu! Ho sentito parlare di te! Tu uccidi i bambini e poi li mangi! Madre Jain! Madre Jain! Aiuto!}
{103}{}{Vorresti un fiore, signore?}
{104}{}{Would you like a flower, mistress?}
{105}{}{Vuoto}
{106}{}{C'e' qualcosa di speciale in questo posto?}
{107}{}{Cos'ha di particolare questo fiore?}
{108}{}{Quanti soldi vuoi, ragazzo?}
{109}{}{Certo, ragazzo!}
{110}{}{No, grazie.}
{111}{}{Certo. Non vedo l'ora di schiacciarlo!}
{112}{}{*sniff sniff* Smell nice!}
{113}{}{*sniff sniff* Smell yuck!}
{114}{}{Scemo! Ce l'hai gia' un fiore!}
{115}{}{Lo vuoi un fiore, o no?}
{116}{}{Prendero' il fiore solo se mi parlerai un po' di questo posto.}
{117}{}{Cos'ha di particolare questo fiore?}
{118}{}{Certo, ragazzo!}
{119}{}{Ne ho abbastanza di quel dannato fiore. Rispondi alla mia domanda!}
{120}{}{}
{121}{}{E' una Rosa dell'Unita'. Ha il colore della Sacra Fiamma e rappresenta la pace e l'armonia che avremo quando i Figli della Cattedrale riusciranno a rendere tutti gli abitanti del mondo forti e buoni! Ehm, ne vuoi una?}
{122}{}{}
{123}{}{E una rosa sarebbe in grado di fare tutto questo?}
{124}{}{Parlami di questa Sacra Fiamma...}
{125}{}{Quanto costa, ragazzo?}
{126}{}{Certo, ragazzo!}
{127}{}{}
{128}{}{Ascoltami bene: non lo voglio il tuo dannato fiore.}
{129}{}{E' gratis. Noi non crediamo nei soldi. La Sacra Fiamma ci fornisce tutto cio' di cui abbiamo bisogno! E' meraviglioso! Perche' non ti unisci a noi, nella Cattedrale della Felicita'? Ehm, ne vuoi uno?}
{130}{}{Parlami della Cattedrale}
{131}{}{Parlami della Sacra Fiamma}
{132}{}{Certo, ragazzo!}
{133}{}{}
{134}{}{}
{135}{}{Grazie, oh grazie! Ho donato un fiore! Non e' meraviglioso...?}
{136}{}{Sei cattivo! Ti odio! Spero che la Sacra Fiamma ti divori!}
{137}{}{Ma certo! Prendine una! Ho donato un fiore! Non e' meraviglioso...?}
{138}{}{Sei stupido! Spero che la Sacra Fiamma ti uccida prima che tu dica altre cose stupide. Madre Jain, sta' attenta a questo stupido!}
{139}{}{Noi siamo i Figli della Cattedrale. La Sacra Fiamma ci ha dato il compito di sfamare gli affamati e di curare i malati. Diffonderemo dappertutto la pace e l'unita'... e tutto sara' bellissimo! Ecco, prendi il tuo fiore!}
{140}{}{Non credo che tu voglia un fiore. Sei cattivo!}
{141}{}{Le rose non possono fare una cosa del genere, sciocco! Solo le persone possono cambiare il mondo! E se la Sacra Fiamma continuera' a guidarci, riusciremo sicuramente a fare qualcosa di bello e speciale! Dai, prendi un fiore...}
{142}{}{Parlami della Cattedrale...}
{143}{}{Parlami della Sacra Fiamma...}
{144}{}{Certo, ragazzo!}
{145}{}{No, grazie.}
{146}{}{Ti faccio vedere io chi e' sciocco, piccolo...}
{147}{}{E' il fuoco che ha purificato il mondo e se le obbediremo, non lo fara' piu'! Desidera che diventiamo piu' intelligenti e piu' pacifici e piu' uniti e piu'... piu'... altre cose! Dai, prendi un fiore...}
{148}{}{Parlami di questa unita'...}
{149}{}{Certo, ragazzo!}
{150}{}{No, grazie.}
{151}{}{Al diavolo quel dannato fiore!}
{152}{}{E' uno splendido posto vicino all'oceano, dove la gente passa tutto il suo tempo a pregare la Sacra Fiamma e a fare opere buone. E tutti sono gentili, a parte forse Padre Lasher. Uh... lo vuoi un fiore?}
{153}{}{Parlami di padre Lasher...}
{154}{}{Certo, ragazzo!}
{155}{}{No, grazie.}
{156}{}{Enough with the damn flower!}
