{100}{}{Si direbbe una guardia esperta.}
{101}{}{Farai meglio a non causare guai.}
{102}{}{Se credi di poter fare il furbo, questa non e' la citta' giusta.}
{103}{}{Comportati bene e non saremo costretti ad usare le maniere forti.}
{104}{}{Sei un tipo a posto.}
{105}{}{Continua cosi'.}
{106}{}{Bella giornata, vero?}
{107}{}{Questa e' Junktown. Un bel posto dove vivere, se ti comporti bene.}
{108}{}{Attento a Gizmo e ai suoi sgherri.}
{109}{}{Il mio capo e' un grand'uomo.}
{110}{}{Farai meglio a metterla via. Junktown e' un posto tranquillo, amico, e ci piacerebbe che lo restasse.}
{111}{}{Metter via cosa?}
{112}{}{Non dirmi quello che devo fare, sfigato.}
{113}{}{Mi sta bene. A proposito, cosa dicono le leggi locali riguardo al possesso di armi?}
{114}{}{Uh-oh.}
{115}{}{La tua arma, idiota. Killian non requisisce le armi, ma faresti meglio a tenerle nel fodero.}
{116}{}{Oh, scusa.}
{117}{}{Puoi scordartelo! Nessuno mi puo' convincere a riporre la mia sputafuoco!}
{118}{}{Farai meglio a darmi retta, dal momento che questa e' la legge e io sono chiamato a farla rispettare. Metti via quell'arma, non estrarla se non per legittima difesa e vedrai che non avrai problemi con noi. Infrangi la legge e ti rispediremo nelle lande selvagge - vivo o morto.}
{119}{}{Se la metti su questo piano... d'accordo.}
{120}{}{Al diavolo le vostre leggi!}
{121}{}{Beh, ehm, a me sta bene. Ma farai meglio a stare attento.}
{122}{}{Mi fa piacere che tu me l'abbia chiesto. Le armi non vanno estratte se non per legittima difesa. Se fai scoppiare una rissa, la colpa e' tua. Inoltre, girare armato e' un tuo diritto. Basta che non estrai il coltello o la pistola senza una giusta causa. Buona giornata.}
{123}{}{Ehi tu, niente armi! E non mi interessa se sei caduto dal seggiolone quand'eri piccolo. Niente armi.}
{124}{}{Ehi! Tu! Perche' cerchi di passare inosservato?}
{125}{}{Non c'e' un motivo preciso.}
{126}{}{Non stavo cercando di passare inosservato. Stavo solo camminando con prudenza.}
{127}{}{Uhhh.}
{128}{}{Qualunque cosa tu stia facendo, non farla in questa citta'.}
{129}{}{La guardia ti fissa per un attimo. Dalla sua faccia capisci che ti ha riconosciuto. Inoltre, ha appena estratto la sua arma.}
{130}{}{Beh, uh, ok. Come vuoi. Cerca solo di non infrangere la legge.}
{131}{}{Grazie. Arrivederci.}
{132}{}{Certo. Sapro' indirizzare meglio le mie attenzioni, signore.}
{133}{}{Certo. Sapro' indirizzare meglio le mie attenzioni, signora.}
{134}{}{Metti via quell'arma o pagane le conseguenze!}
{135}{}{Okay, basta avvertimenti. Vattene dalla citta', subito, e non tornare mai piu', o te ne pentirai!}
{136}{}{Ehi! Cosa credi di fare?}
{137}{}{Basta, te la sei cercata, amico.}
{138}{}{Adesso sei nei guai.}
{139}{}{Fermi dove siete, Skulz! Siete in arresto!}
