{100}{}{You see a safe.}
{101}{}{La cassaforte non e' chiusa a chiave.}
{103}{}{Voila'!}
{104}{}{Merda! C'ero quasi.}
{105}{}{La cassaforte e' chiusa a chiave.}
{106}{}{You earn 500 experience for cracking Killian's personal safe, you big jerk.}
{107}{}{Armeggiando con i perni sei riuscito ad inceppare la serratura. Davvero magnifico.}
