{100}{}{Vedi Lasher della Cattedrale.}
{101}{}{Lo so chi sei. Sei un uomo malvagio e peccatore: ti meriti una punizione.}
{102}{}{Lo so chi sei. Sei il diavolo in forma di donna! Ma il tuo aspetto non ti salvera'.}
{103}{}{Lo so chi sei. La tua malvagita' ti precede. Tu sei colui che invia le anime di fronte ad Ade, dove saranno purificate della loro perfidia. Le tue azioni sono la quintessenza della malvagita' e per questo dovrai essere punito.}
{104}{}{Lo so chi sei. Tu sei la Morte, la Pestilenza fatta persona. Dove giungi tu, il sangue scorre a fiumi. Ma tali malvagita' possono essere fermate da un'anima virtuosa!}
{105}{}{Come osi disturbarmi! Forse non conosci l'importanza della mia posizione? Fuori!}
{106}{}{Non e' saggio presentarsi di fronte a me con un'arma spianata. Su me, lo scudo del Master: nessuno puo' toccarmi senza subirne le conseguenze!}
{107}{}{Devo ammettere che anche a me farebbe comodo lo scudo del Master.}
{108}{}{Nessuno mi ha mai accusato di esser saggio!}
{109}{}{Vorrei solo parlare con chi comanda qui dentro.}
{110}{}{Bel bastone! E' per questo che ti chiamano "Lasher", ovvero "Sferzatore"?}
{111}{}{E' vero che abusi dei bambini?}
{112}{}{Vuoi sapere cos'e' poco saggio? Poco saggio e' farmi la predica, stronzo!}
{113}{}{Perche' parli in un modo cosi' buffo?}
{114}{}{Perche' sei qui, iniziato? Sai bene che non amo essere disturbato.}
{115}{}{Perdonami, Padre, ma ho un problema.}
{116}{}{Cerco la via che solo i saggi della Cattedrale possono indicarmi.}
{117}{}{Sono qui per discutere del trattamento che riservi ai tuoi discepoli.}
{118}{}{Volevo solo fare due chiacchiere.}
{119}{}{Bel bastone! E' per questo che ti chiamano "Lasher", ovvero "Sferzatore"?}
{120}{}{E cosi' vorresti non essere piu' disturbato... Ci penso io!}
{121}{}{Non saprei. Perche' sono qui? Tu lo sai?}
{122}{}{Come osi entrare nelle mie stanze con un'arma in mano! Imbecille! Dileguati, orsu'!}
{123}{}{Chi ti credi di essere per entrare nei miei appartamenti con un'arma sguainata? Fuori!}
{124}{}{Perdonatemi, signore, ma le forze dell'oscurita' sono dappertutto e non si puo' mai sapere in che momento saremo chiamati a difenderci.}
{125}{}{Cerco la via che solo i saggi della Cattedrale possono indicarmi.}
{126}{}{Sono qui per discutere del trattamento che riservi ai tuoi discepoli.}
{127}{}{Volevo solo fare due chiacchiere.}
{128}{}{Bel bastone! E' per questo che ti chiamano "Lasher", ovvero "Sferzatore"?}
{129}{}{Non ti piacciono le armi sguainate, eh? Allora credo proprio che quello che ti sto per fare lo odierai!}
{130}{}{Da che parte?}
{131}{}{Le mie stanze non sono aperte ai non consacrati. Devo chiederti di andartene immantinente.}
{132}{}{Perdona la mia intrusione, ma ho delle domande importanti.}
{133}{}{Sono qui per discutere del trattamento che riservi ai tuoi discepoli.}
{134}{}{Volevo appunto chiederti della consacrazione.}
{135}{}{Bel bastone! E' per questo che ti chiamano "Lasher", ovvero "Sferzatore"?}
{136}{}{Siamo pari. Io non ho ancora consacrato questo luogo: infatti non ho ucciso ancora nessuno!}
{137}{}{You stupid! I got plenty of conse...cra...tion...}
{138}{}{E' un privilegio riservato solo ai nostri servitori piu' fedeli. Solo il battesimo rappresenta un onore piu' grande.}
{139}{}{E cosa bisogna fare per meritare il battesimo?}
{140}{}{E immagino che tu stia educando i tuoi discepoli per prepararli al battesimo.}
{141}{}{Puoi aiutarmi ad esser battezzato?}
{142}{}{Wow! Devi essere una persona molto importante!}
{143}{}{E' un peccato che certi privilegi non valgano il buco del culo di un radscorpione, quando sei morto!}
{144}{}{Non vedo ragione per discutere con un pazzo. Sparisci.}
{145}{}{Dovresti parlare con Padre Morpheus. Si trova nella torre, ma sara' invero arduo che i Nightkin ti cedano il passo.}
{146}{}{Potresti convincere i Nightkin a lasciarmi passare?}
{147}{}{Cosa puoi dirmi di Morpheus?}
{148}{}{Parlami un po' dei Nightkin.}
{149}{}{Grazie, signore.}
{150}{}{Ho i miei sistemi per risolvere problemi di questo genere.}
{151}{}{Siffatto bastone e' uno strumento sacro, tramite il quale istruisco i miei discepoli. Il dolore purifica la mente da pensieri malvagi e permette di comprendere meglio la gloria del Master.}
{152}{}{Capisco. Quindi il Master e' dolore?}
{153}{}{Ma una cosa del genere e' disumana!}
{154}{}{Un ragionamento piuttosto arzigogolato. Che ne diresti di provarci con me?}
{155}{}{Io istruisco i miei discepoli. E' il mio compito. I miei discepoli sono bestie malvagie. E' mio compito obbligarli ad evolversi in esseri umani. Forse ti sara' giunta all'orecchio la voce che io non tollero la futilita'. Cio' corrisponde al vero. Desidero che i miei discepoli soffrano quanto piu' possibile.}
{156}{}{E i mutanti sono piu' evoluti degli esseri umani?}
{157}{}{Bastardo senza cuore!}
{158}{}{Non ti fai mai una bella scopata, vero?}
{159}{}{Dimmi di piu' dei tuoi metodi d'insegnamento.}
{160}{}{E cosa mi dici del piacere di uccidere? E' ammesso, quello?}
{161}{}{Lurido abominio senza cervello! Come osi imputridire le mie stanze con la tua presenza! Fuori di qui! Fuori! Ora!}
{162}{}{Sei una femmina e quindi sei sempre inquieta. E' una condizione innata della tua stirpe. Dimmi il tuo problema, donna, e io lo risolvero' per te.}
{163}{}{Se il tuo cuore non fosse cosi' pieno di malvagita', figliolo, staresti molto meglio. Un cuore puro non ha pensieri. Esponi, orsu', il tuo problema!}
{164}{}{Dimmi come ottenere la purezza!}
{165}{}{Vorrei saperne di piu' a proposito della Cattedrale.}
{166}{}{Vorrei avere delle informazioni sul Master.}
{167}{}{Il fatto che tu sia vivo... questo e' il mio problema, figlio di puttana!}
{168}{}{Impara ad accogliere il dolore come fosse il tuo migliore amico, dacche' il dolore e' la forza piu' istruttiva dell'universo. Distruggi te stesso fino a quando non esisterai piu' come un unico individuo, poi riplasmati sottoforma di uno strumento del Master. Questa e' la soluzione per tutti i tuoi problemi.}
{169}{}{E allora dove posso trovare la maggiore fonte di dolore?}
{170}{}{Evvai, voglio subire abbastanza danni cerebrali da diventare uno dei vostri migliori zombie! Sognatelo, amico!}
{171}{}{Non ci avrei mai pensato!}
{172}{}{Davvero? Ma e' uno schifo, amico!}
{173}{}{Io il dolore lo accolgo gia'. E' solo che mi piace dividerlo con chi mi sta attorno.}
{174}{}{Le bestie emettono versi senza senso. Gli esseri umani prima pensano e solo in seguito parlano. Dovrai evolverti in un essere umano prima che io possa desiderare di parlare con te. Sparisci.}
{175}{}{Le tue parole trasudano verita'. Molto bene, ti aiutero'. Ma sii breve.}
{176}{}{Devo vedere Padre Morpheus per discutere di una questione urgente.}
{177}{}{Parlami della Cattedrale.}
{178}{}{Mi stavo chiedendo dove potrei trovare il Master.}
{179}{}{Vorrei saperne di piu' sui Figli della Cattedrale.}
{180}{}{L'unica cosa breve che posso proporti e' la tua morte.}
{181}{}{Viene un tempo in cui ognuno di noi deve trovare da solo le risposte alle proprie domande. Quel tempo, per te, e' adesso. Sparisci!}
{182}{}{Non e' il mio compito. Adesso vattene.}
{183}{}{Tramite la sopportazione del dolore, l'acquisizione della saggezza e la dedizione al servizio. Il Dolore e' conoscenza, la Saggezza obbedienza, il Servizio coraggio. }
{184}{}{[Altro]}
{185}{}{Bisogna fuggire la Luce che quasi ha distrutto il mondo e votarsi all'Oscurita' nella quale tutti sono uguali. Ora che ti ho annunciato questa verita', impegnati per realizzarla. Cerca il Master e la sua saggezza.}
{186}{}{Non mi sono consultato con lui, ma sono certo abbia apprezzato le anime pure che ho condotto alla sua presenza. E' un lavoro arduo, ma io lo faccio bene. Malauguratamente, consuma una gran quantita' del mio tempo... ed e' per questo che devo chiederti di andartene immantinente.}
{187}{}{La lingua di un adulatore sta nella bocca di un demonio! Un demonio come te! Vade retro!}
{188}{}{Bestia dalla lingua impura! Lontano da me! Impara le buone maniere, prima di rivolgerti di nuovo alla mia persona.}
{189}{}{Una richiesta ragionevole. Prendi questo simbolo. Mostralo ai Nightkin, quando vorrai passare.}
{190}{}{Non posso aiutarti. Sparisci.}
{191}{}{E' la nostra guida. E', tra noi, il piu' prossimo al Master e conosce molti dei suoi propositi. Puo' bastare?}
{192}{}{Potresti convincere i Nightkin a lasciarmi passare?}
{193}{}{Cos'altro mi sai dire di Morpheus?}
{194}{}{Che cosa mi sai dire dei Nightkin?}
{195}{}{Grazie, padre.}
{196}{}{E perche' seguite questo rincitrullito di Morpheus?}
{197}{}{Essi sono al servizio del Master. Essi portano nel mondo il dolore della guarigione. Angeli della Notte, redimono il mondo con lo strumento del massacro. La curiosita' e' un sentimento sconsiderato e cio' vale doppio quando si tratta dei Nightkin. E' l'unica avvertenza che posso darti. Ho molto da fare, ora. Sei congedato.}
{198}{}{La tua cortesia ti rende merito. Forse sei degno di parlare con Morpheus. Dovessero i Nightkin opporsi al tuo passaggio, mostra loro questo sacro simbolo. E adesso va'!}
{199}{}{Sei un pazzo se pensi che un ridicolo sotterfugio possa bastare per sconfiggere i Nightkin. Fuori di qui!}
{200}{}{La dissolutezza e il benessere prevengono l'evoluzione. Evoluzione che e' necessaria per la sopravvivenza in un mondo ostile. Fortunatamente, io sono un uomo tutto d'un pezzo che non si lascia corromperere da piaceri lascivi. Vedo che abbiamo opinioni diverse. Della tua non me ne cale punto. Fuori di qui!}
{201}{}{Non bisogna temere la mutazione. Ogni nascita non e' altro che una mutazione del DNA dei genitori. Siamo tutti mutanti. L'unica cosa importante e' che il mutante sia condotto su un sentiero morale e produttivo. Tale e' il mio lavoro. E cosi' termina la nostra discussione. Puoi andare.}
{202}{}{Io distribuisco dolore. Se l'animale e' degno e puo' imparare da esso, potra' evolvere in un'anima pura. Altrimenti non merita di esistere. Rare sono le occasioni in cui all'animale si estrae il pool genetico; il mio augurio sarebbe che avvenisse piu' spesso. Succede soprattutto agli animali che non sono cresciuti normalmente.}
{203}{}{E il Master approva i tuoi metodi d'insegnamento?}
{204}{}{Sei un mostro!}
{205}{}{Credo proprio di dover andare.}
{206}{}{Insegni anche agli adulti?}
{207}{}{Animali cresciuti?}
{208}{}{Ehi, posso pensarci io! Nessun altro deve saperlo!}
{209}{}{Sei una donna malvagia. Farai meglio a prestare prudenza, qui dentro. I Nightkin non amano i rivali. Ora sparisci!}
{210}{}{Sei un uomo malvagio. Farai meglio a prestare prudenza, qui dentro. I Nightkin non amano i rivali. Ora sparisci!}
{211}{}{La purezza si ottiene attraverso la sofferenza, le ferite e la guarigione. Siamo solo bestie e dobbiamo continuamente esser spezzati prima di poter accettare la verita' del Master senza esitazioni. Ora che hai udito la verita', dalle forma con le tue esperienze. Adesso puoi andare.}
{212}{}{La tua lingua e' talmente pregna di peccato che non puo' esser redenta. Sparisci dalla mia vista!}
{213}{}{La Cattedrale insegna cose che una mente indisciplinata non e' in grado di comprendere. Adesso ho altre cose di cui occuparmi. Sparisci!}
{214}{}{Lo stesso vale per me. Pare che noi due si abbia parecchie cose in comune, ma, sfortunatamente, la tua presenza mi irrita oltre le mie capacita' di tolleranza. Fuori di qui. Adesso.}
{215}{}{Non e' mio compito giudicare. Dovrai convincere i Nightkin. Buona fortuna. Ne avrai bisogno.}
{216}{}{La Cattedrale e' un rifugio per la razza umana. Quando l'apocalisse si abbatte' su questa citta' marcia, la Cattedrale fu risparmiata e cio' permise la nascita del Master. E cosi', da una terribile luce, emerse un'oscurita' rigeneratrice. }
{217}{}{ Quando giunsi qui, vidi che questo luogo mancava di un centro di moralita' e quindi feci voto di distribuire l'istruttivo dolore in un posto un tempo consumato da vani piaceri. E' tutto cio' che ti serve sapere.}
{218}{}{E' scritto che il Master risiede nel profondo, nell'Oscurita', poiche' la Luce della superficie ha tradito e quasi distrutto il Genere Umano. Ma molti benedicono la luce, perche' dicono che da essa e' originato il Master.}
{219}{}{ Non conosco queste cose con certezza e non ho mai avuto il privilegio di vederlo. Ora, se vuoi scusarmi, ho del lavoro da fare.}
{220}{}{La tua presenza qui non e' mai stata particolarmente ben vista. Vedi di sparire.}
{221}{}{Una tempo lo facevo, ma molti dei miei metodi sono stati abbandonati in favore dei rumori molesti che s'odono provenire dall'Auditorio. E' fonte di tristezza, per me. Fortunatamente, posso ancora istruire i bambini. Ora, se vuoi scusarmi, devo prepararmi per la prossima lezione.}
{222}{}{Uh... e', naturalmente, un evento raro e all'animale e' data ogni possibilita' di evolvere. Ora vattene! Vattene subito!}
{223}{}{[Done]}
{224}{}{Questo potrebbe esserti utile. Prendi questo sacro simbolo. Mostralo ai Nightkin se desideri che ti cedano il passo. Ti permettera' di vedere Padre Morpheus.}
