{100}{}{Vedi il Master, il capo dei Super Mutanti.}
{101}{Mast00}{Allora, cos'hai deciso? Entri nell'Unita' o muori? Entra! Muori! Entra! Muori!}
{102}{}{Non posso vincere. Mi unisco a voi.}
{103}{}{Se sei in grado di dimostrarmi che la tua Unita' e' il percorso migliore che l'umanita' puo' intraprendere, allora ti aiutero'.}
{104}{}{E se invece quello a morire fossi tu e io poi me ne andassi senza problemi?}
{105}{}{Oh, una morte ci sara' sicuramente, ma non la mia. Ho un piano.}
{106}{}{Ungh.. wuh?}## "Ugh. Lee."
{107}{Mast01}{Eccellente. I tuoi talenti mi saranno utili. Ma prima dovrai dirmi tutto quel che sai del tuo Vault.}
{108}{}{Perche'?}
{109}{}{OK. Ti diro' tutto quello che vuoi sapere.}
{110}{Mast02}{Lo conquistero' e trasformero' in mutanti tutti gli umani di sangue puro che lo abitano. Essi andranno a formare l'esercito che mi serve per portare la pace in tutte le Lande.}
{111}{}{Mi dispiace, ma la prospettiva non mi attira molto.}
{112}{}{Mi sembra ragionevole. Procediamo.}
{113}{Mast03}{E sia. Ti sei appena scavato la fossa. Fossa! Fossa!}
{114}{Mast04}{Non ti devo dimostrare nulla! Dimostrare.}
{115}{}{Il tuo ego ti impone di dirmelo. Tutti i cattivi hanno questo strano bisogno di spiegare i loro piani nei minimi dettagli.}
{116}{}{Finche' non me lo dimostri, non posso sapere se davvero tu rappresenti il miglior futuro possibile per l'umanita'.}
{117}{Mast05}{Pretendi molto per essere uno che si trova nella tua precaria condizione. Ma voglio rispettare i tuoi bisogni.}
{118}{}{Allora parla.}
{119}{Mast06}{L'Unita' determinera' l'avvento della razza dominante. Dominante! Dominante! Una razza in grado di sopravvivere, e persino prosperare, nelle lande. Finche' ci saranno differenze, non faremo altro che distruggerci combattendo uno contro l'altro. Abbiamo bisogno di un'unica razza. Razza! Razza! Di un unico scopo. Scopo! Scopo! Un'unica gente... per adempiere il nostro destino. Destino!}
{120}{}{E questa razza sarebbe quella dei mutanti, naturalmente.}
{121}{}{Spero che non diventeremo tutti brutti come te.}
{122}{Mast07}{Naturalmente. I mutanti sono le creature dotate delle caratteristiche migliori per affrontare il mondo odierno. Chi altri? I ghoul? Ti prego! Gli umani? Ma se ci hanno portato la morte! Questa sara' l'era dei mutanti. Mutanti!}
{123}{}{Tu intendi trasformare tutti in mutanti, quindi.}
{124}{}{Sei davvero un bigotto.}
{125}{}{E cosa mi dici di quelli che si oppongono a te?}
{126}{Mast08}{Tutti quelli che resistono, si'. E anche tutti quelli che ritengo necessari per l'Unita'. Gli altri potranno vivere la loro vita, ma sotto il controllo e la protezione dell'Unita'. Ma nessuno potra' procreare, poiche' essi saranno gli ultimi rappresentanti della loro razza.}
{127}{}{Nel tuo Grande Piano c'e' una falla.}
{128}{}{Sembra proprio che tu abbia tutto sotto controllo. Mi unisco a voi.}
{129}{}{I think everyone here is nuts - you most of all. I need to stop you right now.}
{130}{Mast09}{E sarebbe?}
{131}{}{Non hai considerato me! Mettero' fine a questa follia, qui e adesso!}
{132}{}{Non riuscirai mai a conquistare il mondo intero.}
{133}{}{So che i tuoi mutanti sono sterili.}
{134}{Mast10}{Non posso ancora conquistare il mondo... per adesso. Ma quando avro' trasformato in mutanti gli abitanti del tuo Vault, le mie forze saranno troppo potenti perche' qualcuno possa contrastarle! Ma non temere, a te non importera'. Importera'! Importera'!}
{135}{Mast11}{Ridicolo! il virus FEV-2 non distrugge gli organi riproduttivi degli individui che infetta.}
{136}{}{Forse il virus non sterilizzava le persone UNA VOLTA... ma adesso lo fa.}
{137}{}{Hai provato a parlarne con i tuoi mutanti?}
{138}{}{Forse e' colpa delle troppe radiazioni.}
{139}{Mast12}{Hai delle prove?}
{140}{}{Certo che le ho! Ecco qua...}
{141}{}{Credimi sulla parola: e' cosi'.}
{142}{}{Chiedilo ai tuoi mutanti.}
{143}{Mast13}{Questo non prova nulla! La pagherai per la tua insolenza. Pagherai!}
{144}{}{Devo assimilare queste informazioni. Un attimo.}
{145}{Mast14}{Devo assimilare queste informazioni. Un attimo... adesso capisco. Hai creato un falso molto verosimile. L'hai creato per ingannarmi... ingannare me! Ingannare! Me!}
{146}{}{Cosa!? Non capisco, credevo fosse tutto giusto!}
{147}{}{Stai mentendo! Stai negando la realta' dei fatti!}
{148}{Mast16}{La pagherai per quel che hai fatto! Pagherai! Fatto!}
{149}{Mast17}{Ma non puo' essere. Questo vorrebbe dire che tutto il mio lavoro e' stato inutile. Tutto quel che ho tentato... un fallimento! Non puo' essere. Essere. Essere. Essere.}
{150}{}{Mi dispiace, ma non puoi farci nulla. La tua razza cessera' di esistere dopo questa generazione.}
{151}{}{Forse qualcosa si puo' fare. Magari avete solo bisogno di altri soggetti su cui effettuare degli esperimenti.}
{152}{Mast18}{Si'. Altri soggetti. E credo che comincero' con te. Te! Te!}
{153}{Mast19}{Io... non credo di poter continuare. Continuare? E pensare che le cose che ho fatto le ho fatte in nome del progresso e della scienza. Solo follie. Ora me ne rendo conto. Follie. Follie? Non c'e' speranza. Vattene, vattene finche' tu hai ancora speranza...}
{154}{Mast20}{Credo che lo faro'. Non muoverti.}
{155}{Mast21}{I miei scienziati mi assicurano che non c'e' nulla di sbagliato. E adesso cosa rispondi? Rispondi! Rispondi!}
{156}{}{Hai provato a chiedere ad una femmina mutante?}
{157}{}{Chiedilo al tuo Tenente.}
{158}{}{Hanno paura di te. Credi davvero che potrebbero dirti una simile verita'?}
{159}{Mast22}{Un attimo. Non riesco a raggiungerlo. Dev'essere morto... e credo di sapere chi l'ha ucciso. Ucciso! Uccidere!}
{160}{Mast23}{Nega tutto. E dice anche di sapere chi ha dato vita a queste voci...}
{161}{Mast24}{Credo di sapere chi e' il bugiardo. Bugiardo!}
{162}{Mast25}{Ragionevole. Un attimo. Sei sicura? E cosa dicono le altre femmine? Non puo' essere. Essere.}
{163}{}{Mi dispiace. La tua razza e' condannata.}
{164}{}{Scusami se rido... ma che ti avevo detto?!}
{165}{Mast26}{Senza prove, temo di non poterti credere. Ora: entri nel mio esercito come mutante o muori! Muori! Entra!}
{166}{}{Meglio morto che simile a te.}
{167}{}{Anche se significa dover rinunciare a tutto cio' che ero, mi uniro' a voi.}
{168}{Mast27}{Il tuo umorismo non ti salvera', adesso. Accetti la mia offerta, o no? Accetta! NO!}
{169}{}{No.}
{170}{}{Okay, it's better than dying... }
{171}{Mast28}{Le radiazioni non hanno effetto su di noi. Il virus FEV ci rende immuni. I tuoi argomenti sono deboli... e lo sei anche tu.}
{172}{Mast29}{Oh, credo che ti sbagli. Ma giusto per esser sicuro, ordinero' che la questione sia studiata in dettaglio. Dopo che mi saro' preso cura di te. Cura. Cura!}
{173}{Mast30}{Il mio unico problema sei tu. Ora: lavorerai per l'Unita', o no?}
{174}{}{No.}
{175}{}{Certo.}
{176}{Mast31}{Saranno puniti per la loro insolenza.}
{177}{}{Vuoi dire che li ucciderai tutti?}
{178}{}{Allora dovro' fermarti subito!}
{179}{Mast32}{Certo che no. A molti verra' offerta l'opportunita' di diventare mutanti. Quelli che rifiuteranno saranno sterilizzati e lasciati liberi. Quelli che faranno resistenza... saranno uccisi.}
{180}{}{Sei una marionetta fuori di testa. E' giunta l'ora di tagliarti i fili.}
{181}{}{Hmm, non mi alletta l'idea di essere uccisso... Mi unisco a voi.}
{182}{Mast33}{Siamo tutti egoisti, nevvero? Ognuno di noi si preoccupa della sua propria comunita' individuale invece che degli altri. Non siamo cambiati. E ti diro' un'altra cosa...}
{183}{}{E sarebbe?}
{184}{Mast34}{Noi non cambieremo, finche' non faremo parte di un'unica gente. Unica. Unica. Unica. Unica razza. Unica. Unica. Unica. L'Unita' ci permettera' di superare i problemi piu' insulsi e di affrontare cosi' le problematiche piu' importanti. Anche tu vuoi farne parte, non e' vero? Parte. No.}
{185}{}{Mi hai convinto. Entrero' nell'Unita'.}
{186}{}{Una parte la vorrei... la tua testa!}
{187}{Mast35}{Ma certo! I mutanti sopravviveranno! I mutanti ricostruiranno questo mondo! E solo come mutante ti sara' permesso di vivere! Vivere. Morire!}
{188}{}{Vivere!}
{189}{}{Morire!}
{190}{}{A te interessano solo i tuoi mutanti e la tua Unita'.}
{191}{Mast36}{Non sono un essere malvagio. Tu non hai idea di cosa io sia. Di cosa l'UNITA' sia.}
{192}{}{E allora dimmelo tu.}
{193}{}{Tu SEI malvagio. Stai solo negando i tuoi sentimenti piu' profondi.}
{194}{Mast37}{Non devo certo giustificarmi con te. Usando la tua logica, questo dovrebbe convicerti che io non sono un malvagio. Sarebbe una causa persa cercare di spiegartelo. }
{195}{Mast38}{Oh? Dimmi, ti prego: di che piano dovrebbe trattarsi?}
{196}{}{Piazzero' una testata nucleare in questo Vault. Esplodera' in poco tempo e vi mandera' tutti quanti all'inferno!}
{197}{}{Ti ammazzero'. Questo dovrebbe renderti piuttosto difficile continuare il tuo progetto, giusto?}
{198}{}{Ho convinto la Confraternita d'Acciaio ad invadere questo posto, nel caso in cui io fossi stato catturato e non rilasciato immediatamente. Saranno qui a momenti.}
{199}{Mast39}{Forse stai dicendo la verita'. Ma non importa: ti lascero' andare, per adesso.}
{200}{Mast40}{Stai mentendo. E sara' l'ultima menzogna che dirai. }
{201}{Mast41}{Un attimo mentre controllo la tua storia. Forse stai dicendo il vero. Guardie! Portate questo umano nel nucleo del reattore. Risolvete questo problema prima che sia troppo tardi.}
{202}{Mast42}{Credo che nemmeno il FEV potrebbe aiutarti. Ma perche' parlo? E' improbabile che tu mi capisca...}
{203}{Mast43}{Stai scherzando. }
{204}{Mast44}{La mia pazienza e' quasi giunta al limite. Ora: entrerai a far parte dell'Unita', o no? Entra. No!}
{205}{}{Si'.}
{206}{}{Not.}
{207}{Mast45}{Bene. Allora morirai!}
{208}{Mast46}{Hai disattivato il dispositivo. Eccellente. Dimmi: c'e' qualcos'altro che vuoi dire prima che ti uccida?}
{209}{}{Si'. Posso unirmi a voi, adesso?}
{210}{}{Anche da morto avro' comunque un aspetto migliore del tuo.}
{211}{Mast47}{No. No. No. No.}
{212}{Mast200}{Io sono il Master. Non sono obbligato a risponderti.}
{213}{Mast201}{Non sono qui per rispondere alle tue domande. TU sei qui per rispondere alle MIE.}
{214}{Mast202}{Una volta che avro' ottenuto la posizione del tuo Vault, si compira' il mio destino! Destino! Destino! Destino!}
{215}{Mast203}{Credi di poter distruggere me!? Distruggere! Me?}
{300}{}{Duh!}


# Master Tell-Me-Abouts generic response
{980}{Mast200}{Io sono il Master. Non sono obbligato a risponderti.}

#
# Master Tell-Me-Abouts
#


{1000}{}{Unita'}
{1001}{}{Master}

{1100}{Mast200}{Io sono il Master. Non sono obbligato a risponderti.}
{1101}{Mast201}{Non sono qui per rispondere alle tue domande. TU sei qui per rispondere alle MIE.}

