{100}{}{Vedi Mephisto, un mercante arrabbiato.}
{101}{}{Vedi un mercante di nome Harms.}
{102}{}{Vedi un mercante arrabbiato di nome Fowler.}
{103}{}{Vedi Dixon, un mercante arrabbiato.}
{104}{}{Vedi Morgan, un mercante.}
{105}{}{Vedi Marco, un mercante adirato.}
{106}{}{Vedi Kjolnir, un mercante.}
{107}{}{Vedi Marzen, un mercante.}
{108}{}{Vedi Joshua, un mercante adirato.}
{109}{}{Vedi Anthony, un mercante.}
{110}{}{Vedi Clark, un mercante.}
{111}{}{Vedi Malantic, un mercante arrabbiato.}
{112}{}{Vedi Orlando, un mercante.}
{113}{}{Vedi un mercante di nome Ilya.}
{114}{}{Vedi Tracy, un mercante arrabbiato.}
{115}{}{Ma e' mai possibile che accadano simili casini?}
{116}{}{Rispetta la fila.}
{117}{}{Tu non sei uno della compagnia.}
{118}{}{Anche la tua carovana e' stata rinviata?}
{119}{}{Spero che le cose ti vadano meglio che a me.}
{120}{}{Hai visto Hightower?}
{121}{}{Se fossi in te, mi rivolgerei ai Mercanti FarGo.}
{122}{}{Stai cercando il mercante capo? La trovi proprio la'.}
{123}{}{Se il mio carico non parte a breve, chiedero' un rimborso colossale.}
{124}{}{Martha e' proprio laggiu'.}
{125}{}{Tu non sei un mercante, sparisci.}
{126}{}{I dormitori delle guardie sono dall'altra parte.}
{127}{}{Non ti daro' un soldo, percio' sparisci.}
{128}{}{Il mio carico non partira' mai...}
{129}{}{Che non ti sfiori nemmeno l'idea di prenderti il mio territorio.}
{130}{}{Perche' il mio carico non e' ancora partito?}
{131}{}{Dove sono le mie cose?}
{132}{}{I vostri prezzi sono scandalosi!}
{133}{}{Dov'e' Hightower?}
{134}{}{Mi avevate detto che il mio carico avrebbe avuto la priorita'!}
{135}{}{Il mio carico ha due settimane di ritardo!}
{136}{}{Rivoglio i miei soldi!}
{137}{}{Voglio parlare con Hightower.}
{138}{}{D'ora in poi faro' affari solo con le Carovane Scarlatte.}
{139}{}{Cosa c'e' che non va?}
{140}{}{Sono stanco di aspettare!}
{141}{}{Non ne posso piu' di sentire scuse!}
{142}{}{Il mio carico e' piu' importante del suo!}
{143}{}{Cos'e' che non riuscite a capire?}
{144}{}{Spedite il mio carico o mi rivolgero' a qualcun altro!}
