{100}{}{Vedi una porta a chiusura stagna.}
{101}{}{La porta e' chiusa elettronicamente.}
{102}{}{La porta non e' chiusa.}
{103}{}{Sei riuscito a bypassare la serratura elettronica.}
{104}{}{Il tuo tentativo di bypassare la serratura elettronica non e' riuscito.}
