{100}{}{La pompa e' stata riparata e funziona bene.}
{101}{}{La pompa non funziona per via di un tubo rotto.}
{102}{}{La pompa non funziona.}
{103}{}{Un macchinario.}
{104}{}{Questa pompa non funziona a causa di un tubo rotto.}
{105}{}{Forse ha bisogno di una valvola nuova.}
{106}{}{La pompa non funziona.}
{107}{}{Non puoi riparare la pompa senza un tubo di ricambio.}
{108}{}{Non riesci a riparare la pompa. Forse ha bisogno di una valvola nuova.}
{109}{}{Non riesci a riparare la pompa.}
{110}{}{Questa pompa non funziona a causa di un tubo rotto.}
{111}{}{Forse questa pompa ha bisogno di una valvola nuova.}
{112}{}{La pompa non funziona.}
{113}{}{Non noti nulla di strano.}
{114}{}{L'enorme pompa torna faticosamente a funzionare grazie al tuo intervento di sostituzione delle parti danneggiate.}
{115}{}{In qualche modo riesci a distruggere i pezzi di ricambio, ferendoti nel contempo le mani per 1 punto di danno.}
{116}{}{Hai qualche difficolta' ad installare i pezzi di ricambio.}
{117}{}{Questo oggetto non puo' essere usato con la pompa.}
{118}{}{You earn 1000 experience for fixing the water pump. The ghouls will be grateful!}
