{100}{}{Paladino}
{101}{}{Buongiorno, Iniziato.}
{102}{}{Se ti serve qualcosa, puoi rivolgerti a Vree.}
{103}{}{Se vuoi parlare con qualcuno, Vree si trova proprio la'.}
{104}{}{Se voglio continuare i miei studi devo riuscire a trovare un po' di tempo libero tra i turni di pattuglia e l'addestramento. Credo di essere un po' arrugginito.}
{105}{}{Bisogna mantenere la mente e il corpo sempre al massimo della forma, Iniziato.}
{106}{}{Noi Scriba progettiamo tutto l'equipaggiamento, le armi e i dispositivi usati dalla Confraternita. E' davvero eccitante.}
{107}{}{Essere un Paladino non significa solo combattere, figliolo.}
{108}{}{Essere un Paladino non significa solo combattere, signorina.}
