{100}{}{Vedi Rae.}
{101}{}{Vedi un super mutante.}
{102}{}{Non dovresti essere qui.}
{103}{}{(sembra confuso e triste) credo di si', ma... perche' sei qui?}
{104}{}{Nemmeno tu.}
{105}{}{Uh... si', invece. Il Master mi ha ordinato di girare in incognito per controllare la sicurezza.}
{106}{}{Si', invece... sono qui per ucciderti.}
{107}{}{Okay, me ne vado.}
{108}{}{huh.}
{109}{}{(sigh) E adesso cosa vuoi?}
{110}{}{Mi sono perso... puoi mostrarmi la strada piu' breve per raggiungere il Master? Sai, devo ucciderlo.}
{111}{}{Niente. Addio.}
{112}{}{Voglio vedere come diventerai quando ti avro' strappato la pelle dal corpo, brutta feccia mutante.}
{113}{}{Qual e' il tuo problema?}
{114}{}{great oogly moogly.}
{115}{}{Sono qui per... contemplare l'unicita' del Master.}
{116}{}{Naturalmente. L'Unita' porta pace. Posso chiederti da dove vieni?}
{117}{}{Anch'io. Ho fatto un lungo viaggio per vedere il Master con i miei occhi.}
{118}{}{Ho molto da imparare. Come posso fare per farmi ricevere dal Master?}
{119}{}{Quello l'ho fatto ieri. Oggi vorrei vedere che aspetto avrebbe il Master se gli dessi fuoco e arrostissi dei marshmallow sulla sua putrida carcassa.}
{120}{}{Credo che il Master sia un pazzo.}
{121}{}{Vengo da... un'altra... parte.}
{122}{}{Che coincidenza! Anch'io.}
{123}{}{Dove?}
{124}{}{Vengo da un vault... sono un umano puro.}
{125}{}{Cosa sei? Un imbecille?}
{126}{}{Da dove vieni?}
{127}{}{(sussurra) Vengo da un vault... sono un umano puro.}
{128}{}{Preferirei non dirtelo. Addio.}
{129}{}{Da un piccolo villaggio a nord di qui.}
{130}{}{Perche' dovrei dirtelo? Sei soltanto un leccapiedi del "Capo".}
{131}{}{Forse dovrei portarti davanti al Master...}
{132}{}{Ma non lo farai.}
{133}{}{Provaci pure.}
{134}{}{Beh, io invece dovrei ficcarti la mia pistola in gola e premere il grilletto!}
{135}{}{Non farlo, ti prego.}
{136}{}{Conosco il motivo del tuo dolore.}
{137}{}{Me ne vado.}
{138}{}{Hai ragione... se solo potessi liberare la mia mente. C'e' qualcosa...}
{139}{}{Io so perche' non puoi liberare la mente.}
{140}{}{E' il Master che ti impedisce di pensare chiaramente. Il pensiero disturba l'Unita'.}
{141}{}{Il motivo di tutto il tuo dolore e' uno solo: il Master.}
{142}{}{Ehi, ho un'idea - apriamo in due il Master e vediamo cosa c'e' dentro!!!}
{143}{}{Dimmelo! Ti prego!}
{144}{}{You used to be human, too. The Master dipped you in the Forced Evolutionary Virus and mutated you.}
{145}{}{Mi dispiace, non posso.}
{146}{}{Solo il Master potra' rivelarti ogni cosa.}
{147}{}{Solo il Master potra' rivelarti ogni cosa. Ma farai meglio a parlargli in fretta, perche' sto per ucciderlo.}
{148}{}{Mi dispiace, devo andare.}
{149}{}{Ti dovrei uccidere per avermi preso in giro!}
{150}{}{Ho un'idea migliore - aiutami a distruggere il Master per vendicarti di quello che ti ha fatto.}
{151}{}{No, dovresti uccidere il Master per averti fatto questo. Io sono intenzionato a farlo... Che ne diresti di unirti a me?}
{152}{}{Perche'? Non sono stato io a trasformarti in un mutante!}
{153}{}{Provaci pure.}
{154}{}{No grazie. Addio!}
{155}{}{Torciamogli la testa finche' non gli escono gli occhi!}
{156}{}{Non ucciderai mai il Master. Il Master non puo' morire.}
{157}{}{Hai ragione. Sara' meglio che me ne vada.}
{158}{}{Lo vedremo.}
{159}{}{Hmmm. Mi domando come fara' a vivere quando la sua Unita' sara' stata distrutta...}
{160}{}{Non puo' essere... il Master... protegge... unifica...}
{161}{}{Beh, tu sei un esempio vivente di questa "unificazione", amico mio. Sai, io ho visto come avviene il processo. E sono qui per impedire al Master di "unificare" altre persone.}
{162}{}{Come ci si sente ad essere protetti ed unificati?}
{163}{}{Si'... protegge se stesso controllando tutti gli altri.}
{164}{}{Ne ho abbastanza. Ci si vede.}
{165}{}{Vattene subito o saro' costretto ad usare le maniere forti.}
{166}{}{AAAUGH!!! (si afferra la testa in preda al dolore e alla confusione) Io... non posso...}
{167}{}{E' cosi'. Il tuo amico Master ti ha privato di tutto quello che avevi al mondo, inclusa la tua umanita'.}
{168}{}{Anche tu sai che e' vero... e' per questo che sei cosi' confuso. Stai rigettando la mutazione. Aiutami a vendicarti e distruggiamo il Master!}
{169}{}{Certo che puoi. Forza, uccidiamo il Master... sara' divertente.}
{170}{}{Sara' meglio che vada.}
{171}{}{Mi dispiace che tu stia provando tutto questo dolore, ma la colpa e' del Master.}
{172}{}{Gli cavero' l'occhio!! Strappero' la sua testolina viscida dai suoi cavi!!!! Tu... vattene da qui... mi occupero' io del Master.}
{173}{}{Ottimo!!}
{174}{}{Grazie dell'offerta, ma preferisco farlo con le mie mani. Vuoi aiutarmi?}
{175}{}{Io mi fermo qui. Ho alcune cose da fare.}
