{100}{}{Vedi Razlo.}
{101}{}{Mi dispiace, ma non posso aiutarti.}
{102}{}{Non puoi... o non vuoi?}
{103}{}{Razlo ti guarda per un attimo, poi si gira dall'altra parte.}
{104}{}{Sembri disperato. Ti serve aiuto?}
{105}{}{Tandi e' stata rapita.}
{106}{}{Hng, Tanny bu'.}
{107}{}{Tandi e' sparita? Ma e' terribile. Spero che riusciate a trovarla.}
{108}{}{Hmm, Tandi e' sparita? Mi pare davvero strano, ma forse e' scappata con Seth. So che ultimamente si facevano gli occhi dolci, quei due. Aradesh ha sempre avuto un animo un po' troppo puritano e forse Tandi non ne poteva piu'.}
{109}{}{Hmm, non credo.}
{110}{}{Non credo. Temo invece che sia stata rapita.}
{111}{}{Forse... provero' a chiedere a qualcun altro.}
{112}{}{Che cosa orribile! Se e' davvero cosi', spero che stia bene. Chi la sta cercando?}
{113}{}{Tutti, praticamente.}
{114}{}{Molte persone, me incluso.}
{115}{}{Spero che la trovino prima che sia troppo tardi.}
{116}{}{Se e' ferita, potrebbe essere grave. Ecco, prendi questi... e spero che non ti servano.}
{117}{}{Spero che Tandi torni presto. Aradesh deve essere a pezzi.}
{118}{}{Mi hanno detto che ci hai aiutato a trovare Tandi. Congratulazioni... e grazie. Se hai bisogno di cure, dimmelo pure.}
{119}{}{Il mio dolore non ha fine. Tandi, l'unica figlia del mio piu' caro amico, e' morta. Adesso non posso lavorare.}
{120}{}{Sono Razlo. Posso aiutarti?}
{121}{}{Non adesso, ma e' stato un piacere conoscerti.}
{122}{}{Ho bisogno di cure.}
{123}{}{Hnngh!}
{124}{}{Hmmm. Ho visto brahmin con piu' cervello di te. Beh, vediamo se sei ferito.}
{125}{}{Beh, mi sembri in perfetta salute. Magari un'altra volta, eh?}
{126}{}{Vediamo un po'.}
{127}{}{Ti ho gia' dato tutto quel che potevo. Buona fortuna.}
{128}{}{Hmmm, la tua faccia non mi piace. Spero che tu sia venuto qui per un motivo, e che te ne vada in fretta...}
{129}{}{Non c'e' bisogno di mettersi sulla difensiva, sto solo dando un'occhiata in giro.}
{130}{}{Aiutami... ho bisogno di cure.}
{131}{}{Bentornato. Come posso servirti?}
{132}{}{Salve. Sono solo di passaggio.}
{133}{}{Ho bisogno di cure.}
{134}{}{Ug!}
{135}{}{E' stato un piacere rivederti. Buona giornata.}
{136}{}{Certo. Ancora tu. Cosa vuoi?}
{137}{}{Niente.}
{138}{}{Ho bisogno di cure.}
{139}{}{Luki!}
{140}{}{E' evidente.}
{141}{}{Posso aiutarti?}
{142}{}{No.}
{143}{}{Ho bisogno di cure.}
{144}{}{Sono stato avvelenato!}
{145}{}{Che cosa sai dei radscorpioni?}
{146}{}{Ho un po' di veleno di radscorpione. Puo' esserti utile?}
{147}{}{Luki!}
{148}{}{Mi dispiace, ma non posso curarti. Non ho gli ingredienti giusti per creare un antidoto adatto.}
{149}{}{Ecco, vediamo...}
{150}{}{Si', proprio come pensavo. Un attimo che prendo il necessario...}
{151}{}{Adesso mi sembri a posto. La prossima volta fa' piu' attenzione.}
{152}{}{Ripassa quando vuoi, ma cerca di curare la salute.}
{153}{}{Non molto. Sembrano essere delle versioni extra-large dello Scorpione Imperatore del Nord-America. In contraddizione con tutte le mie nozioni mediche, il loro veleno risulta essere piu' potente e non diluito come mi sarei aspettato. Seth e le sue guardie li cacciano, il che mi e' discretamente utile per i miei esperimenti. }
{154}{}{E non riesco a capacitarmi delle dimensioni di queste creature, siano esse il risultato di una evoluzione naturale o di una mutazione indotta dalle radiazioni.}
{155}{}{Grazie.}
{156}{}{Sembri molto colto. Di cosa ti occupi?}
{157}{}{Altro?}
{158}{}{Sembrano essere sensibili alla luce. Sono animali notturni. Se riuscissi ad avere un campione del loro veleno, o, meglio, della sacca velenifera contenuta nella loro coda, potrei creare un antidoto.}
{159}{}{Grazie.}
{160}{}{Il dottor Morbid di Junktown mi ha insegnato un paio di cose. E solo perche' viviamo in capanne, questo non significa che la nostra intelligenza o la nostra cultura siano inferiori a priori. Buona giornata.}
{161}{}{Fammi vedere quella sacca! Si', posso ricavarne qualcosa.}
{162}{}{Ecco, prendi questo campione. Sembra funzionare bene contro le punture di radscorpione, naturalmente, ma si dimostra un antidoto efficace contro un gran numero di veleni.}
{163}{}{E' tardi. Torna domattina.}
{164}{}{Ma mi serve il tuo aiuto.}
{165}{}{Sto cercando di uccidere dei radscorpioni. Hai qualcosa che potrebbe tornarmi utile?}
{166}{}{Sto cercando Tandi. Puoi aiutarmi?}
{167}{}{Hnn.}
{168}{}{Hnn?! Cosa succede...? Magnifico. Sono stato appena svegliato dalla grande bestia farfugliante del nord. Torna domattina.}
{169}{}{Sei ferito?}
{170}{}{Si'.}
{171}{}{No.}
{172}{}{Lo sarai, se continui a disturbarmi mentre dormo. Torna domattina.}
{173}{}{Grande Brahmin! Perche' non l'hai detto subito?}
{174}{}{Uhhh. I did... }
{175}{}{Hai solo qualche graffio. Ti consiglio una bella notte di sonno e un po' di riposo; vedrai che guarirai spontaneamente.}
{176}{}{Hai solo qualche graffio, mammoletta. Torna domattina.}
{177}{}{Ouch, deve farti piuttosto male. Fanno 25$.}
{178}{}{Okay, here you go.}
{179}{}{Non ho abbastanza soldi.}
{180}{}{Oh Grande Brahmin! Le tue ferite sono molto, molto gravi. Ti devo chiedere 50$.}
{181}{}{Okay, here you go.}
{182}{}{Non ho abbastanza soldi.}
{183}{}{Come fai ad essere ancora in piedi?! Quelle ferite sembrano gravissime. Avremo bisogno di preghiere speciali e di un bel po' di fortuna. E naturalmente di 100$.}
{184}{}{Okay, here you go.}
{185}{}{Non ho abbastanza soldi.}
{186}{}{Non hai abbastanza soldi! Mi dispiace, ma la mia etica non mi permette di curarti gratuitamente. Torna quando avrai il denaro necessario.}
{187}{}{Accetteresti qualche oggetto, in cambio?}
{188}{}{Al diavolo.}
{189}{}{Non adesso, mi spiace.}
{190}{}{E come potrei aiutarti ad uccidere i radscorpioni? Sono un dottore, non un guerriero. Per il tuo problema dovresti rivolgerti ad Aradesh, o a Tandi, o al suo fidanzato Seth. Lasciami in pace.}
{191}{}{Ho bisogno di qualcosa per il loro veleno.}
{192}{}{Se avessi un campione del loro veleno potrei preparare un antidoto.}
{194}{}{Non credo. Temo sia stata rapita.}
{195}{}{Forse... provero' a parlare con qualcun altro.}
{196}{}{Ci vorra' un po' di tempo. Va' nella stanza sul retro e rilassati. Il succo di junga potrebbe farti venire una leggera emicrania. Vieni, vieni...}
{197}{}{Ti ho gia' dato tutto quel che potevo. Buona fortuna.}
{300}{}{You earn 250 experience for helping to make an antidote for radscorpion venom.}
{301}{}{K, me da'?}
{302}{}{Nunga.}
{303}{}{Scorpin, Scorpin?}
{304}{}{My da' esto?}
{305}{}{Che ne diresti di una coda di radscorpione?}
{306}{}{Fammi vedere la sacca velenifera! Si', questa mi sara' molto utile. Per ringraziarti di questo splendido regalo, ti curero' gratuitamente.}
{307}{}{Ci vorra' un po' di tempo. Va' nella stanza sul retro e rilassati, mentre io lavoro con la sacca. Il succo di junga potrebbe farti venire una leggera emicrania. Vieni, vieni...}
{308}{}{Sei pregato di non prendere le mie cose.}


{1000}{}{Khan}
{1001}{}{Garl}
{1002}{}{Junktown}
{1003}{}{Shady}
{1004}{}{Hub}
{1005}{}{Water}
{1006}{}{Tandi}
{1007}{}{Aradesh}
{1008}{}{Seth}
{1009}{}{Razlo}
{1010}{}{Sands}


{1100}{}{Sono un gruppo di fuorilegge che si spacciano per chissa' chi.}
{1101}{}{E' il capo dei Khan. Da quando ha messo gli occhi su Shady Sans non dormiamo piu' sonni tranquilli. Tutti i clan dei predoni lo seguono senza obiezioni.}
{1102}{}{Si trova a circa una settimana da qui, verso sudovest. E' una citta' di mercanti, ma non sono tutti onesti... specialmente con i contadini come noi.}
{1103}{}{Ci sei dentro.}
{1104}{}{E' a sud di Junktown.  L'Hub e' la piu' grande citta' della zona. Il commercio, laggiu', e' molto florido.}
{1105}{}{Mi dispiace, ma non posso aiutarti.}
{1106}{}{E' la figlia di Aradesh. Probabilmente un giorno prendera' le redini del villaggio. Spero che per allora riesca ad addolcire il suo caratteres.}
{1107}{}{E' il capo della comunita' e l'eroe del villaggio. Ha tanto di quel lavoro da fare che raramente lascia la sala comune.}
{1108}{}{E' il braccio destro di Aradesh, nonche' il capo delle guardie.}
{1109}{}{Sono io. Sono il medico di Shady Sands.}
{1110}{}{Ci sei dentro.}
