#
# North, vanilla
#
{100}{}{Sei caduto vittima di un agguato organizzato dai mutanti!}
{101}{}{Pare proprio che tu sia capitato nel bel mezzo di uno scontro tra bande!}
{102}{}{Un gruppo di predoni ostili avanza nella tua direzione!}
{103}{}{Un nutrito gruppo di ratti avanza rapidamente nella tua direzione!}
{104}{}{Un gruppo di banditi ostili avanza nella tua direzione!}
{105}{}{Improvvisamente dei ratti ti attaccano!}
#
# Cathedral
#
{106}{}{You encounter a group of tough-looking Super Mutants in leather armor.}
