{100}{}{Vedi la fonte d'acqua potabile di Shady Sands. L'acqua e' troppo poca per salvare il tuo Vault.}
{101}{}{Non hai alcun motivo per calarti nel pozzo, ma forse la corda ti sara' utile per scendere in altri buchi.}
{102}{}{Non scopri niente di nuovo a proposito del pozzo.}
{103}{}{Non appena senti cadere il tappo nell'acqua, esprimi un desiderio.}
