{100}{}{Vedi Mrs. Stapleton, la bibliotecaria.}
{101}{}{Vedi una donna di mezz'eta'.}
{102}{}{Salve, e benvenuto nella Biblioteca. Non credo di averla mai vista da queste parti. Che cosa sta cercando sulla via della conoscenza?}
{103}{}{E' un piacere rivederla. Che cosa cerca, oggi?}
{104}{}{Che cos'hai da vendere, sulla via dei libri?}
{105}{}{Sto cercando un Water Chip.}
{106}{}{Niente, ma grazie lo stesso.}
{107}{}{Bene, lasci che le mostri la nostra selezione.}
{108}{}{Beh, nel corso dei miei studi ho sentito parlare di tali cose. Inoltre sono in possesso di un olodisco che contiene alcune informazioni che credo potrebbero esserle utili.}
{109}{}{Un olodisco? E cos'e'?}
{110}{}{Posso avere l'olodisco?}
{111}{}{Un olodisco contiene delle informazioni, ma puo' essere letto solo da un numero ristretto di dispositivi elettronici. Vedo che ha con lei un PIP Boy. Puo' usarlo per decodificare, visionare e immagazzinare le informazioni contenute in un olodisco.}
{112}{}{Ma e' grandioso! Posso avere l'olodisco?}
{113}{}{Di questi tempi e' cosi' difficile mettere le mani sulle informazioni che ci interessano. Il disco le costera' 750 testoni.}
{114}{}{D'accordo. Ecco i soldi.}
{115}{}{Ohibo'! Ma questo olodisco e' uno dei piu' rovinati che abbia mai visto! Ti daro' 500 testoni.}
{116}{}{E se invece io portassi qui dentro un lanciafiamme? Eh, signora?!}
{117}{}{Mi spiace, non ho tutti quei soldi.}
{118}{}{Mi dispiace, ma questo olodisco posso venderlo soltanto al prezzo che le ho detto.  Ritorni quando avra' la cifra completa.}
{119}{}{Mi dispiace, ma dovra' tenere per se' le sue tendenze piromaniache. Se ne vada, per favore.}
{120}{}{[Mrs Stapleton prende i tuoi soldi.]}
{121}{}{Ha ragione, questo disco ha visto giorni migliori. Visto e considerato il suo stato, accettero' i 500 testoni al posto del prezzo che le avevo detto prima. [Mrs Stapleton prende i tuoi soldi.]}
{122}{}{Di solito non cederei a tali ricatti, ma, per proteggere da una simile minaccia la mia collezione, le daro' il disco. In cambio le chiedo di non farsi rivedere mai piu' qui dentro.}
{123}{}{Come mi pare di averle spiegato, dovra' prima usare il disco e poi consultare le informazioni che contiene tramite il PIP Boy.  [Mrs. Stapleton ti da' l'olodisco]}
{124}{}{Deve scusarmi, ma ho delle ricerche da fare.}
{125}{}{Ruk?}
{126}{}{Scusami, ma non ti capisco. Da qualche parte dovrei avere un olodisco per imparare l'italiano, se ti interessa.}
{127}{}{Arrivederci.}
{128}{}{Grazie.}
{129}{}{Ug.}
{130}{}{Hai delle riviste di chimica? Miles di Adytum mi ha detto che qui avrei potuto trovarne qualcuna.}
{131}{}{Si', Miles me l'ha detto e ho proprio quello che lei sta cercando.  Le costeranno 750 testoni.}
{132}{}{Ecco a lei. Saluti Miles da parte mia.}
{133}{}{Mi dispiace, ma non ha abbastanza soldi. Torni quando avra' di che pagare.}
