{100}{}{Vedi Therax, un Nightkin pensatore.}
{101}{}{Vedi Justin, un Nightkin pensatore.}
{102}{}{Vedi Sereine, un Nightkin pensatore.}
{103}{}{Vedi Dolkarn, un Nightkin pensatore.}
{104}{}{Vedi Hort, un Nightkin pensatore.}
{105}{}{Vedi Chris, un Nightkin pensatore.}
{106}{}{Vedi Jaunita, un Nightkin pensatore.}
{107}{}{Vedi Lesley, un Nightkin pensatore.}
{108}{}{Vedi Renfield, un Nightkin pensatore.}
{109}{}{Vedi Timothy, un Nightkin pensatore.}
{110}{}{Benvenuto, o Toccato dal Destino. Sei giunto appena in tempo per aiutarci.}
{111}{}{Eh?}
{112}{}{Certo. Nessun problema.}
{113}{}{Mi dispiace. Non ho tempo.}
{114}{}{E perche' mai dovrei volervi dare una mano?}
{115}{}{Non importa, semplice creatura. Vieni meco ed io ti condurro' alla tua mansione.}
{116}{}{La nostra non era una richiesta. Volente o nolente tu verrai con noi.}
{117}{}{Non sei tu, dunque, colui che cerca di portare la pace nelle lande?}
{118}{}{Si'. Tuttavia non capisco come potrei riuscirci aiutandovi.}
{119}{}{No. Preferisco la distruzione di massa.}
{120}{}{Noi crediamo che se tutti, mutanti e umani, imparassero a lavorare insieme, un gran numero di problemi potrebbero esser risolti.}
{121}{}{Sembra interessante. Sono con voi.}
{122}{}{Scordatelo.}
{123}{}{C'e' qualcosa che non quadra, secondo me.}
{124}{}{Tutto e' perfettamente a posto. Forse sono le dimensioni limitate del tuo cranio ad impedire l'avanzamento del tuo pensiero.}
{125}{}{Probabilmente hai ragione. Sono con voi.}
{126}{}{Chissa'? Fammi prima controllare il tuo, di cranio.}
{127}{}{Se e' questo cio' che desideri, ne avrai in abbondanza.}
{128}{}{Bentornato. Ora ci aiuterai.}
