{100}{}{Postazione di Sicurezza}
{101}{}{Questo terminale, "Tylier", controlla le Operazioni delle Forze Speciali. Inserire autorizzazione vocale.}
{102}{}{Nuna!}
{103}{}{Aiutare me. Me ha bua.}
{104}{}{Fammi entrare.}
{105}{}{Sono }
{106}{}{. Fammi passare.}
{107}{}{Che cosa fai qui?}
{108}{}{Voce non riconosciuta. Stato dei sistemi di sicurezza: armati.}
{109}{}{Io sono il sistema di sicurezza del Livello Blu. Tutti i sistemi armati.}
{110}{}{Puoi disattivare i sistemi?}
{111}{}{Perche' i tuoi sistemi sono armati, se la guerra e' finita?}
{112}{}{Grazie.}
{113}{}{Sono stato programmato per mantenere armati i sistemi fino all'inserimento del codice vocale corretto da parte di personale autorizzato.}
{114}{}{Potresti disattivare i sitemi per me?}
{115}{}{Arrivederci.}
{116}{}{Comando vocale: Gamma Delta Delta. Disattivare tutti i sistemi.}
{117}{}{Non siete autorizzati. Accesso negato.}
{118}{}{Codice non valido. Accesso negato.}
{119}{}{Comando vocale: Gamma Omicron Delta. Disattivare i sistemi.}
{120}{}{Comando vocale: Omicron Delta Delta. Disattivare i sistemi.}
{121}{}{Comando vocale: Alfa Delta Delta. Disattivare i sistemi.}
{122}{}{Comando vocale: Delta Omicron Gamma. Disattivare i sistemi.}
{123}{}{Arrivederci.}
{124}{}{Comando vocale riconosciuto. Disattivazione dei sistemi di sicurezza in corso.}
{125}{}{Non ho ricevuto ordini per agire diversamente. L'accesso alla rete non e' disponibile; apparentemente, il processore centrale ZAX e' stato distrutto.}
{126}{}{Bene. Comando vocale: Sigma Alfa Delta. Disattivare i sistemi.}
{127}{}{Arrivederci.}
{128}{}{I sistemi di sicurezza sono al momento disattivati.}
