{100}{}{Vedi una persona molto abbronzata. Forse lavora nei campi.}
{101}{}{Non ho nulla da dirti, straniero.}
{102}{}{Questo e' il periodo dell'anno in cui i brahmin puzzano di piu'.}
{103}{}{Abbiamo bisogno di espandere la nostra rete d'irrigazione.}
{104}{}{Non disturbarmi.}
{105}{}{Ho sentito che i radscorpioni hanno ucciso ancora, l'altra notte.}
{106}{}{Hai mai provato gli hamburger di brahmin?}
{107}{}{E' da un po' che non subiamo attacchi da parte dei predoni. Solo fortuna, temo.}