{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Ton.}
{100}{}{你看见唐。}
#{101}{}{You see a huge member of the Children.}
{101}{}{你看见一个大个子的教堂教徒。}
#{102}{}{man}
{102}{}{男子}
#{103}{}{woman}
{103}{}{女子}
#{104}{}{【Done】}
{104}{}{【完成】}
#{105}{}{【More】}
{105}{}{【更多】}
#{106}{}{Sorry man, but you passed the point of no return with us. Time to slam off!}
{106}{}{抱歉哥们儿，上了我们的船就没回头路了。该走了！}
#{107}{}{Sorry woman, but you passed the point of no return with us. Time to slam off!}
{107}{}{抱歉姐们儿，上了我们的船就没回头路了。该走了！}
#{108}{}{Why would I want to talk with someone who goes around killing kids? Get out of my face!}
{108}{}{我为什么要和到处杀小孩的人说话？从我面前消失！}
#{109}{}{I hear you're pretty tough. But tough don't impress Ton. You got something to say or you wanna get it on? Let's do it!}
{109}{}{我听说你很强。但那不能让唐感兴趣。你是有话要说还是就开搞？快点！}
#{110}{}{Peace, brother! I'm just checking the place out.}
{110}{}{安静，兄弟！我只是查看一下这地方。}
#{111}{}{I'm not interested in impressing you. You got something intelligent to say, say it!}
{111}{}{我不在乎怎么引起你的兴趣。有话快说！}
#{112}{}{Get it on? Mister, I don't go for scrawny little boys.}
{112}{}{开搞？先生，我不是为了这些瘦孩子而来的。}
#{113}{}{What do you want?}
{113}{}{你想要什么？}
#{114}{}{You talk too much.}
{114}{}{你话太多了。}
#{115}{}{You wanna die, and I wanna kill someone. Works for me.}
{115}{}{你想找死，我想杀人。我有活干了。}
#{116}{}{Waa!}
{116}{}{哇！}
#{117}{}{Man, I already talked to you! Take your shit somewhere else!}
{117}{}{老兄，我已经说过了！去别的地方吧！}
#{118}{}{boy}
{118}{}{男孩}
#{119}{}{girl}
{119}{}{女孩}
#{120}{}{Hey, you think your weapon's gonna earn you some 'spect? It's gonna earn you a grave, man. Put it away.}
{120}{}{嗨，你觉得武器会让你出人头地？它只会让你踏进棺材，老兄。把它拿开。}
#{121}{}{Hey, you think your weapon's gonna earn you some 'spect? It's gonna earn you a grave, girl. Put it away.}
{121}{}{嗨，你觉得武器会让你出人头地？它只会让你踏进棺材，姑娘。把它拿开。}
#{122}{}{What do you want, you stupid zombie? Get outta my face before I break it.}
{122}{}{你想要什么，你这蠢货？从我面前消失，不然我打烂你。}
#{123}{}{I was looking for someone smart enough to tell me what's really going on around this joint!}
{123}{}{我在找一个够聪明的人，能告诉我这里究竟发生了什么！}
#{124}{}{What will the priests say if they hear you talking like this?}
{124}{}{如果牧师听到你说这些话，他们会怎么说？}
#{125}{}{Any time, pal. I've been waiting for a good scrap!}
{125}{}{随时奉陪，朋友。我一直在等一场好斗呢！}
#{126}{}{Hey, what's the problem? A few drinks and we'll be buds!}
{126}{}{嗨，有什么问题？来点喝的，我们交个朋友！}
#{127}{}{Did you know that even a child can apply enough pressure to the right spot in your kneecap to cripple you for life? Just thought you'd want to know.}
{127}{}{你知不知道，只要在你膝盖的某点准确的用点力，一个小孩也能让你一辈子成瘸子？你可能想知道这点吧。}
#{128}{}{You wanna talk to Ton? Fine. But if I hear the word "praise," I'll kill you.}
{128}{}{你想和唐说话？好吧。不过如果我听到了“赞美”这个词，我会杀了你。}
#{129}{}{You're not a big fan of worship services?}
{129}{}{你不信教吧？}
#{130}{}{What's your problem, pal?}
{130}{}{你有什么问题，朋友？}
#{131}{}{I want to speak with the man in charge.}
{131}{}{我想和主管说话。}
#{132}{}{Sure thing. The only thing I feel like praising is a bottle of Rad Scorpion.}
{132}{}{当然。我唯一想赞美的是一瓶蝎子汁。}
#{133}{}{Fine. The first one of us who says that word dies. Bargain?}
{133}{}{好吧。我们中谁先说那个词的就得死。怎么样？}
#{134}{}{Hello, miss. I am Ton, 2,000 pounds of the Master's toughest fighter. I have also been evolved by the FEV into something that you need to check out. Let's get it on, baby.}
{134}{}{你好，小姐。我是唐，主教的最强战士。我也被FEV改造成了别的东西，这点你会知道的。我们开搞吧，宝贝。}
#{135}{}{No way in hell.}
{135}{}{决不可能。}
#{136}{}{That's a little too fast. Let's get to know each other first.}
{136}{}{这有点太快了。我们先互相了解一下。}
#{137}{}{Hello. I've been evolved by the FEV so that anyone that annoys me dies. Stop annoying me, little man.}
{137}{}{你好。我被FEV改造了，所以任何烦我的人都得死。别烦我，小子。}
#{138}{}{Check it out somewhere else. Ton don't like your company.}
{138}{}{去别的地方吧。唐不喜欢你陪着。}
#{139}{}{Fine. You want to play it straight? Sometimes killing's necessary. Sometimes I even like it. But I hear you love killing . . . all the time. Every time I've met a psycho, either he dies, or Ton dies. Ton is still here. So why don't you go elsewhere.}
{139}{}{好吧。你想开门见山？有时候杀人是必须的。有时候我甚至喜欢杀人。但我听说你酷爱杀人……任何时候。每次我碰到一个疯子，不是他死，就是唐死。唐现在还活着。所以你还是去别的地方吧。}
#{140}{}{Man, I could learn to like you. You're either an incredible asshole,or you got guts. Either way is fine with Ton, as long as you don't jam me up. You want to join up?}
{140}{}{老兄，我可能会喜欢上你。你要不是个英雄，就是个极品混蛋。两样唐都喜欢，只要你不给我惹麻烦。你想加入我们吗？}
#{141}{}{Whatever happened to peace and love?}
{141}{}{和平和爱也不管了？}
#{142}{}{What's involved?}
{142}{}{有什么好处？}
#{143}{}{No way in hell, pal.}
{143}{}{决不，朋友。}
#{144}{}{I'll jam whatever I want, wherever I want. So let's kick out the jams!}
{144}{}{我想惹什么麻烦就惹，想在哪里就在哪里。所以让麻烦见鬼去吧！}
#{145}{}{To see you suffer. Let's go, hombre, give me what I want.}
{145}{}{来看你吃苦头。来吧，老兄，给我点我想要的东西。}
#{146}{}{Beware of what you want. You may not like what you get.}
{146}{}{你要小心你要的东西。你可能不会喜欢的。}
#{147}{}{I'd rather be your friend.}
{147}{}{我愿意成为你的朋友。}
#{148}{}{You aren't worth my time.}
{148}{}{你不值得我花功夫。}
#{149}{}{Go ahead. Make the first move. The last one's mine.}
{149}{}{来吧，你先动手。我最后动。}
#{150}{}{Fine. Talking's over. Make your move.}
{150}{}{好吧。话都说完了。动手吧。}
#{151}{}{I just wanted to talk.}
{151}{}{我只想说话。}
#{152}{}{You're dead . . .}
{152}{}{你去死……}
#{153}{}{Shit! You're dumber than the zombies! Just get out of here!}
{153}{}{操！你比僵尸还蠢！快滚吧！}
#{154}{}{The Master wants peace, and he wants us to get it for him, so we're going to have fun. Capiche?}
{154}{}{主教想要和平，他要我们为他取得和平，所以我们就有乐子找了。明白?}
#{155}{}{Yeah, but there's got to be more going on than just that.}
{155}{}{是的，但还有更多的事情。}
#{156}{}{Does the Master really want peace or does he just want killing?}
{156}{}{主教是真的想要和平还是只想要杀戮？}
#{157}{}{Who is this Master?}
{157}{}{这个主教是谁？}
#{158}{}{Sounds good to me.}
{158}{}{听起来很不错。}
#{159}{}{Screw the Master! Let's kill them all!}
{159}{}{去你妈的主教！我们把他们都干掉！}
#{160}{}{It's not healthy to ask the wrong question, compadre. They have all the answers they want you to hear. People who ask the wrong questions, or people who screw up, well, they don't stay around here very long.}
{160}{}{兄弟，别问错问题。他们只告诉你他们想说的事。问错问题的人，惹麻烦的人，嗯，他们在这里都呆不长。}
#{161}{}{I do my job. They like it when I do my job. They like it when street trash and Followers stop breathing. It lets the Nightkin do other things. Don't mess with me . . . it ain't healthy.}
{161}{}{我做我的事。他们喜欢我做事。他们喜欢街头的混混和末世论者都死绝。这让夜行团能去做别的事。别把我扯进去……这不好。}
#{162}{}{What are you doing dressed like a zombie? If you got the 'tude, you gotta let it show!}
{162}{}{你穿得像个僵尸干什么？如果你有礼貌，你得把它表示出来！}
#{163}{}{I don't care about the clothes, man. I just want to know what's going on here!}
{163}{}{老兄，我并不在乎衣服。我只想知道这里发生了什么！}
#{164}{}{They don't bother you as much if you don't look like they might want to convert you.}
{164}{}{如果你不是他们想要昄依的人，他们就不会太在意你。}
#{165}{}{None of your business, pal.}
{165}{}{不关你的事，朋友。}
#{166}{}{I've been thinking of converting.}
{166}{}{我是在想昄依。}
#{167}{}{It ain't 'tude. It's a way of death.}
{167}{}{这不是你的礼貌. 这是想找死。}
#{168}{}{We don't drink in here. Nightkin don't like it. You better get a few more clues before you talk to Ton again.}
{168}{}{我们在这里不喝酒。夜行团不喜欢。你最好在和唐谈话前能明白些基本的道理。}
#{169}{}{You're crazy! I could almost like you, except that I have the feeling that people who hang around you don't live long. Get the hell out of here.}
{169}{}{你疯了！我差不多喜欢你了，不过我感觉和你扯上关系的人都活不长。快给我出去。}
#{170}{}{You stand around this for months and you go crazy as them. What do you want from Ton?}
{170}{}{你在这呆几个月就会变得和他们一样疯。你想从唐那里得到些什么？}
#{171}{}{How'd these people get like this?}
{171}{}{这些人怎么会变成这个样子的？}
#{172}{}{I want sex and violence, without the sex. You know where I can get it?}
{172}{}{我想要性和没有性的暴力。你知道哪里有？}
#{173}{}{I am losing it in this zombie pit, and I don't need you helping me. Get the hell away from me.}
{173}{}{我在这里把它弄丢了，而我不需要你帮我。快走开。}
#{174}{}{That's Morpheus. He stays upstairs, except to give sermons. He don't even do that much anymore. He's smart and he's a winner, and that's all that counts. Go see him for yourself.}
{174}{}{那是墨菲斯。他除了布道，一直呆在楼上。他也不常布道。他很聪明，也是个成功者，这才最关键。你自己去找他吧。}
#{175}{}{You need to go out into the Boneyard, pal. Ain't no slosh in here, and I've looked!}
{175}{}{你得去晒骨场，朋友。这里没有，我已经看过了！}
#{176}{}{Agree. What can Ton do for you?}
{176}{}{同意。唐能为你做什么？}
#{177}{}{Bitch! You don't know what you're missing! Get out!}
{177}{}{婊子！你不知道你正失去什么！滚出去！}
#{178}{}{Life is too short for that. Let me show you why you don't want to wait.}
{178}{}{对它来说生命太短了。我来告诉你为什么你不该等。}
#{179}{}{But I want someone who knows what's going on.}
{179}{}{但我要找到知道发生了什么的人。}
#{180}{}{No thank you. But I wouldn't mind being friends.}
{180}{}{不，谢了。不过我不介意做朋友。}
#{181}{}{Get lost, you piece of trash.}
{181}{}{快滚蛋，你这废物。}
#{182}{}{Sure.}
{182}{}{当然。}
#{183}{}{Life IS shorter than you think. Die, asshole!}
{183}{}{生命比你想的还短。去死吧，杂种！}
#{184}{}{I'm not LITTLE, bitch!}
{184}{}{我不是小人物，婊子！}
#{185}{}{Who believes in that bullshit? They have to program these morons to believe in that stuff anyway.}
{185}{}{谁相信那些胡扯？他们得设法让这些白痴相信那些鬼话。}
#{186}{}{How did it happen?}
{186}{}{那是怎么发生的？}
#{187}{}{Really?}
{187}{}{真的？}
#{188}{}{What a bunch of losers.}
{188}{}{这些废物。}
#{189}{}{Tell me more about your posse.}
{189}{}{多跟我说些你那队人的事。}
#{190}{}{Okay, I'll join up.}
{190}{}{好吧，我加入。}
#{191}{}{Someone should put them out of their misery. Like me . . .}
{191}{}{总得有人结束他们的不幸。就像我……}
#{192}{}{When we get the word, we go out and kill people. People like the Followers or some of the more dangerous gang types.}
{192}{}{我们一得到命令，就出去杀人。杀那些末世论者或者更危险一点的帮派之类。}
#{193}{}{So the Followers are a problem?}
{193}{}{所以末世论者是个问题？}
#{194}{}{This sounds pretty sick to me.}
{194}{}{这听起来很恶心。}
#{195}{}{Who needs the word? Why not just kill them?}
{195}{}{谁需要命令？为什么不直接杀了他们？}
#{196}{}{Fine. Do what you want. But I'd get out before it becomes unhealthy around here.}
{196}{}{好吧。随你干什么。不过我得在这里变糟之前离开。}
#{197}{}{You annoying little piece of shit. You're worse than a Junktowner, you coward. Get the hell out.}
{197}{}{你这讨厌的杂种。你比迦克镇的人还坏。滚出去。}
#{198}{}{What else is there to know? I get to eat well, sleep in peace and kill some of the people who used to screw me over. You want something more from life?}
{198}{}{还要知道什么？我吃得好，睡得好，杀了以前惹我的人。你还能从生活中得到更多吗？}
#{199}{}{Who knows? Who cares? I get to eat well, sleep in peace and kill some of the people who used to screw me over. You want something more from life?}
{199}{}{谁知道？谁在乎？我吃得好，睡得好，杀了以前惹我的人。你还能从生活中得到更多吗？}
#{200}{}{Hmmm, Ton never thought of that. But if they bother me too much, I break their face. Then they stop bothering Ton. What do you want?}
{200}{}{呣，唐从没想过那个。不过如果他们太烦我，我就干掉他们。他们就不能再烦唐了。他们想要什么？}
#{201}{}{Converting? Well, good luck. You'll need it.}
{201}{}{昄依？嗯，祝你好运。你需要这个。}
#{202}{}{Why would I need luck?}
{202}{}{为什么我需要好运？}
#{203}{}{That doesn't sound good.}
{203}{}{听起来不好。}
#{204}{}{Thanks. You're a true friend.}
{204}{}{多谢。你是真正的朋友。}
#{205}{}{I don't need luck as long as I've got ammo.}
{205}{}{只有我有弹药，我就不需要好运。}
#{206}{}{These people, these zombies, weren't always like this. I could even stand a few of them. Then they got converted. Some of them came out like this. Some of them didn't come out at all. Ton doesn't like it, but these people pay Ton well.}
{206}{}{这些人，这些僵尸，他们也不总是这样子。有些我都能忍受。一旦他们昄依了，一些人出来就成了这样子。还有一些人根本就没出来。唐不喜欢，但这些人给了唐很多。}
#{207}{}{Why do you keep jumping between first and third person?}
{207}{}{为什么你在第一人称和第三人称之间不停地变换？}
#{208}{}{Tell me more about the conversion process.}
{208}{}{告诉我更多有关昄依的程序。}
#{209}{}{Did you go through the conversion process?}
{209}{}{你通过昄依的程序了吗？}
#{210}{}{This place is strictly low-rent.}
{210}{}{这个地方很便宜。}
#{211}{}{Really, how much?}
{211}{}{真的，多少？}
#{212}{}{Nobody's gonna do this to me!}
{212}{}{没人敢对我做这个！}
#{213}{}{You talk to Morpheus or to Lasher, or you can bother Ton, and Ton give you more violence than you can handle.}
{213}{}{你和墨菲斯或者拉舍尔谈吧，如果你去打扰唐，唐会让你吃不了兜着走的。}
#{214}{}{Well baby, what's going on is that there are a lot of zombies chanting, a lot of people dying and the Children are going to take over everything. And there's you and me and nothing else matters!}
{214}{}{好了宝贝，发生了什么？发生的就是许多僵尸在唱圣歌，许多人死了，大教堂教徒要接管所有东西。还有就是你和我，没别的了！}
#{215}{}{But Barracas, darling, surely there's more going on than that . . .}
{215}{}{但是巴拉卡斯，亲爱的，肯定还有更多的事发生了……}
#{216}{}{Oh, Ton!}
{216}{}{喔，唐！}
#{217}{}{Forget it, creep. You ain't my type.}
{217}{}{算了吧，马屁精。你不是我喜欢的那种。}
#{218}{}{Nothing else matters? Hell no! I wanna hear about the dying part!}
{218}{}{没别的了？喔，不！我想知道关键的！}
#{219}{}{Unfortunately, this is the worst place on earth to experience what Ton does best. Too many zombies cramp my style. I'll let you know when I think about some place more convenient . . .}
{219}{}{很不幸，这是地球上最糟的体验唐所做的事的地方。僵尸太多了，我不能随便就说。等我想到一个更安全的地方再跟你说……}
#{220}{}{You'll find out soon enough what happens upstairs. If you tough, you get through it fine. It happened to Ton, and Ton is just fine!}
{220}{}{你很快就会知道楼上发生了什么。如果你够强，你会很安全地通过。唐就是这样，唐现在很安全！}
#{221}{}{Uh . . . I didn't say anything. You forget what Ton told you or Ton will make you forget, permanently!}
{221}{}{喔……我什么也没说。你最好忘了唐和你说的话，要不然唐就会让你永远地忘记的！}
#{222}{}{They used to be whiners. But Ton talks too much. You get out of my face.}
{222}{}{他们以前也是哀诉者。但是唐说的太多了。你快走吧。}
#{223}{}{Fine. You stay low-profile until I give you the word. Then we have fun.}
{223}{}{很好。你老老实实等着我发话，然后我们乐一乐。}
#{224}{}{They're cowards. They set ambushes against our patrols. They send spies and saboteurs. They know they can't win a real fight. The Master says we should feel sorry for them, but Ton just want to kill them. Smart man, Ton.}
{224}{}{他们是些懦夫。他们伏击我们的巡逻队。他们派遣间谍和破坏分子。他们知道他们赢不了真正的战争。主教说我们应该为他们感到难过，但唐只想杀了他们。是个聪明人，唐。}
#{225}{}{We need discipline, fool! We're soldiers now! We obey orders. Killers die, but soldiers win their battles. We're going to beat the Followers. We're going to beat EVERYONE!}
{225}{}{我们需要纪律，白痴！我们现在是战士！我们要服从命令。杀手会丧命，而战士会赢得战斗。我们要打败末世论者。我们要打败所·有·人！}
#{226}{}{Who the hell knows? Maybe it's just Morpheus pulling the strings. Things are good, and if this dries up, Ton goes somewhere else.}
{226}{}{谁他妈知道？也许只是墨菲斯在操纵。目前情况还不错，要是这里不行了，唐就到别的地方去。}
#{227}{}{Well, don't get too eager. Even with the Nightkin, it's still tough fighting. But if we play it smart, we get out ahead. That's the only thing Ton cares about.}
{227}{}{好了，别太激动。就算是和夜行团, 那也是很困难的战斗。但是如果我们干得聪明，我们就能搞定。那是唐唯一关心的事。}
#{228}{}{The conversion isn't easy. You see these people, all these zombies? They used to be like you and me. Ton survived. These people didn't. But why should Ton care about you?}
{228}{}{昄依并不简单。你看见这些人了，这些僵尸?他们以前就和你我一样。唐幸免了。这些人没有。不过我为什么要管你呢？}
#{229}{}{You don't like the way Ton talk? Then Ton kill you!}
{229}{}{你不喜欢唐说话的方式？那么唐要杀了你！}
#{230}{}{Ton go through it fine. I . . . uh . . . I . . . uh . . . Ton . . . Ton just fine.}
{230}{}{唐安全地通过了。我……喔……我……喔……唐……唐很安全。}
#{231}{}{I used to be with the Dead Dog gang. Always hungry, always tired. This place is much better for Ton. Why should I worry about anyone else? Nobody ever worry about me.}
{231}{}{我以前在死狗帮。总是很饿，总是很累。这地方对唐来说好多了。我为什么要替别人担心？从来没人担心过我。}
#{232}{}{You greedy asshole! Get outta here before Ton kills you!}
{232}{}{你这贪心鬼！在唐杀你之前快滚！}
#{233}{}{Then get out of here now, before it's too late.}
{233}{}{那么现在快滚，不然就晚了。}
#{234}{}{Nothing important as you and me. Unfortunately, this is the worst place on earth to experience what Ton does best. Too many zombies cramp my style. I'll let you know when I think about some place more convenient . . .}
{234}{}{没什么事有你我重要。很不幸，这是地球上最糟的体验唐所做的事的地方。僵尸太多了，我不能随便就说。等我想到一个更安全的地方再跟你说……}
#{235}{}{Why you manipulative bitch! Nobody screws with Ton like that!}
{235}{}{你这婊子要干嘛！没人敢对唐这样！}

