{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Bob, proprietor of Bob's Iguana Bits.}
{100}{}{你看见鲍勃，“鲍勃蜥蜴料理”的老板。}
#{101}{}{Ok, Ok, I've got your money.}
{101}{}{好了，好了，我准备好给你的钱了。}
#{102}{}{I've got more expenses.  I need to increase the payment.}
{102}{}{我最近开销大了些。我要提高你的付费。}
#{103}{}{Screw this.  I want ALL of your money now, or you're a dead Bob.}
{103}{}{滚你娘的蛋！我要你所有的钱，要不你就是一只死鲍勃！}
#{104}{}{I can't take the heat.  I'm calling off the payments.}
{104}{}{我不会再受你摆布了。没钱给你。}
#{105}{}{I want information on Decker.}
{105}{}{我想知道有关德克的情况。}
#{106}{}{I want information on Doc Morbid.}
{106}{}{我想知道有关莫彼得医生的情况。}
#{107}{}{Gimme' an iguana on a stick.}
{107}{}{给我一串烤蜥蜴。}
#{108}{}{I'm sorry.  I ain't payin' no more.  Do what you want with me.}
{108}{}{对不起，我不会付钱了。你想怎么着就怎么着吧。}
#{109}{}{Bob, I thought we were pals!  In fact, I was thinking about giving you a promotion in my organization.  Instead, you betray me.  This is very disappointing...}
{109}{}{鲍勃，我还以为我们是朋友！事实上。我还想提拔你呢。而你，却背叛了我。这太让我失望了……}
#{110}{}{Bob, why should I take no for an answer?  Especially from a scumbag like you?}
{110}{}{鲍勃，我怎么能让人对我说不？尤其是像你这样的烂人？}
#{111}{}{Glad to see you're standing up for yourself.}
{111}{}{很高兴看到你能为自己辩护。}
#{112}{}{Your reputation is history, Bob.  Hi-sto-ree!}
{112}{}{你的名声已经是过去式了，鲍勃。过-去-了！}
#{113}{}{Fine, I'll decide what to do with you later.}
{113}{}{很好，我慢慢再想怎么对付你。}
#{114}{}{Well, it was nice knowing you Bob.  Say 'hi' to Satan for me.}
{114}{}{很好，很高兴认识你，鲍勃。替我向撒旦问好吧。}
#{115}{}{What are you doing back so soon?  It ain't time for the payment.}
{115}{}{你这么快回来干嘛？还没到付款的时间。}
#{116}{}{You've got a lot of nerve showing your face around here.  Get lost!}
{116}{}{你还敢在这里露面。快滚！}
#{117}{}{Hey, I don't want any trouble!}
{117}{}{嘿，我不想惹什么麻烦！}
#{118}{}{Hi!  Welcome to Bob's Iguana Bits, the family eating place.  Can I take your order?}
{118}{}{嗨！欢迎到“鲍勃蜥蜴料理”，吃饭的好地方。要来点什么？}
#{119}{}{Forget it.}
{119}{}{没什么。}
#{120}{}{You are?  Well, Ok...}
{120}{}{你是？嗯，好吧...}
#{121}{}{He's a mean son of a bitch.  You don't want to mess with him.  Anything else?}
{121}{}{他是个婊子养的杂种。你可不要惹祸上身。还要什么？}
#{122}{}{Fine.  What do you want me to pay?}
{122}{}{好吧，你想要我付多少？}
#{123}{}{I want }
{123}{}{我想要每五天}
#{124}{}{ bucks every five days.}
{124}{}{块钱。}
#{125}{}{Doc Morbid?  All I know is that he's up around Junktown and he's the cheapest source of food I could find.  That's all!}
{125}{}{莫彼得医生？我只知道他住在迦克城，而且他的货是我能找到的最便宜的食材。就这些！}
#{126}{}{Let's see what I've got in stock.}
{126}{}{我看看还有什么存货。}
#{127}{}{I've got a whole iguana for twenty caps.}
{127}{}{整个的烤蜥蜴我收二十瓶盖。}
#{128}{}{I've got prime cut choice for eight caps.}
{128}{}{精选肉块我收八瓶盖。}
#{129}{}{I'll take one of the real ones.}
{129}{}{我来一份整个的。}
#{130}{}{Nothing for me right now.  I'm on a diet.}
{130}{}{这会不要。我在节食。}
#{131}{}{I'll take one of the prime cuts.}
{131}{}{我来一份精选肉块。}
#{132}{}{I could go for some prime cut right now.  I'll even pay for it.}
{132}{}{这会我就来烤肉块吧。我只付得起这个。}
#{133}{}{Uhh... Me no hungry now.}
{133}{}{喔……偶现在不饿饿。}
#{134}{}{Fine!  Take your money and get out!}
{134}{}{好了！拿上你的钱快走吧！}
#{135}{}{You can stick it!  I ain't ever payin' you!  Get lost!}
{135}{}{你就跟我耗吧！我不会给你钱的！快滚！}
#{136}{}{Yeah, sure.  Why don't you find someone else to screw over.}
{136}{}{是的，当然。你为什么不去敲诈别人。}
#{137}{}{You can't throw crap without getting some of it on your fingers.  Get out of here!}
{137}{}{放屁糟践别人前先想想你有什么证据。滚出去！}
#{138}{}{Sure you will.  Get lost!}
{138}{}{当然你会的。快滚！}
#{139}{}{Sorry.  We're all out of iguana.}
{139}{}{对不起，我们的蜥蜴都用完了。}
#{140}{}{We only have whole iguana on a stick.  Twenty bucks each.}
{140}{}{我们只有烤整蜥蜴了。一个二十块。}
#{141}{}{We only have prime select choice.  It tastes great, though.  Eight bucks each.}
{141}{}{我们只有精选肉块了。不过吃起来很棒。一个八块。}
#{142}{}{Sure.  We got whole iguana on a stick for twenty bucks, and our prime select pieces for eight bucks.}
{142}{}{当然。烤整蜥蜴是二十块，精选肉块的是八块。}
#{143}{}{I'll take a whole iguana.}
{143}{}{我来份烤整蜥蜴。}
#{144}{}{I'll take your prime select.}
{144}{}{我来精选肉块。}
#{145}{}{You know, I hear your prime select tastes like chicken.  Do you like eating cowardly guys?}
{145}{}{你知道吗，我听说你的精选肉块吃起来像鸡肉。你喜欢吃人肉吗？}
#{146}{}{No sissy portions!  Me want all iguana!  Ugh!}
{146}{}{别小家子气了！我要所有的烤蜥蜴！噢！}
#{147}{}{Hmm, smell good!  Me want prime!}
{147}{}{呣, 闻来好！偶要精选的！}
#{148}{}{Never seen any of them around here.  Water Merchants don't need 'em.}
{148}{}{这里从没见过这种东西。纯水商队不会需要它们的。}
#{149}{}{Water Merchants?}
{149}{}{纯水商队？}
#{150}{}{Mr. Decker is a distinguished businessman in a less than distinguished business.  Anything else?}
{150}{}{德克先生是一个高尚的商人，却干着不那么高尚的行业。还要别的吗？}
{151}{}{}
{151}{}{}
#{152}{}{What kind of business?}
{152}{}{哪种行业？}
#{153}{}{What are you talking about?}
{153}{}{你在说些什么？}
#{154}{}{Your secret ingredients.  How fresh does the corpse have to be before it develops a bitter aftertaste?  Do you use mutants, humans, or a mix?}
{154}{}{你的秘密原料。那些尸体变味前新鲜吗？你是用变种人，还是人类，或者混着用？}
#{155}{}{I found an invoice in Doc Morbid's lair.  An invoice for dead bodies...}
{155}{}{我在莫彼得医生的老窝里找到一张发货单。死尸的发货单……}
#{156}{}{If you've got a memory loss, I can talk to the sheriff.}
{156}{}{如果你失忆了，我可以去和治安官谈谈。}
#{157}{}{Prime Choice Select is made of people!!!!  It's made of people!!!}
{157}{}{精选肉块是用人肉做的！！！用人肉做的！！！}
#{158}{}{Nothing.  Sorry to bring it up.  Now is there anything else I can do for you?}
{158}{}{没什么。抱歉提起它。我还能为你做什么？}
#{159}{}{Well, he's dead now, and my cash flow has increased because of it.}
{159}{}{好吧，他现在死了，因为这个我的钱包也鼓了。}
#{160}{}{Someone killed Decker.  We're in mourning. 【snicker】}
{160}{}{有人杀了德克。我们现在很悲伤。【窃笑】}
#{161}{}{Someone shot Sheriff Greene.  Don't know about the deputy, though.}
{161}{}{有人向治安官格林开枪。现在还不知道代理治安官有没有出事。}
#{162}{}{Daren Hightower was murdered.  And all that money couldn't save him.  Ironic, ain't it?}
{162}{}{达伦·海托被谋杀了。所有的钱都救不了他的命。很讽刺，是不是？}
#{163}{}{Someone stole a necklace from the Hightowers.  Man, did they ever make a big mistake.  They're dead for sure!}
{163}{}{有人从海托家里偷了一条项链。老兄，他们犯了大错。他们死定了！}
#{164}{}{Someone killed Jain over at the Cathedral.  I hear she was a real pain in the butt!}
{164}{}{有人在大教堂杀了简恩。我听说她都被打得不成人形了！}
#{165}{}{Well, the only new thing is that the Children of the Cathedral has taken over the Hospital.  It's pretty boring around here lately.}
{165}{}{嗯，唯一的新闻是大教堂教徒接管了医院。最近这里很无聊。}
#{166}{}{Anything else?}
{166}{}{还要什么？}
#{167}{}{Man, I'm gonna be out of business in a week.  Anything else, oh high and mighty?}
{167}{}{老兄，这个礼拜我就要破产了。还要别的吗，老大？}
#{168}{}{I don't like your attitude.}
{168}{}{我不喜欢你的态度。}
#{169}{}{Sorry, you can't afford it.}
{169}{}{抱歉，你肯定买不起。}
#{170}{}{One whole iguana coming up!  Anything else?}
{170}{}{一份烤整蜥蜴来了！还要别的吗？}
#{171}{}{You know what they're made from and you still want one?  You make Decker look like a charity worker!  Anything else?}
{171}{}{你知道了它们是用什么做的你还想要一份？跟你这个变态比起来，德克简直就像个义务志愿者了！还想要什么？}
#{172}{}{I don't like your attitude.}
{172}{}{我不喜欢你的态度。}
#{173}{}{Sorry, you can't afford it.}
{173}{}{抱歉，你肯定买不起。}
#{174}{}{One iguana prime select choice, coming up!  Anything else?}
{174}{}{一份精选肉块来了！还要别的吗？}
#{175}{}{Smart choice.  You could stand to lose a few pounds.}
{175}{}{聪明的选择。你减几磅肉应该死不了的。}
#{176}{}{Wh...what!  Oh, I see, you're joking...}
{176}{}{什……什么！喔，我明白了，你是在开玩笑……}
#{177}{}{Of course I am...}
{177}{}{当然我是……}
#{178}{}{No, I'm not.  I'm going to see that you pay for your crime.}
{178}{}{不，不是。我是来惩罚你的罪行。}
#{179}{}{No, I'm not.  And I want a piece of the action.}
{179}{}{不，不是。我是要你意思一下。}
#{180}{}{You must be new in town if you're asking me about the Water Merchants.  Water is life, and you don't get much more powerful than life and death.}
{180}{}{如果你会问我纯水商队的事，那你一定是刚进城的。水就是命，没有什么事情比生死还大。}
#{181}{}{Who's in charge of the Water Merchants?}
{181}{}{谁是纯水商队的头儿？}
#{182}{}{If there's anything that involves misery and suffering in the Hub, Decker either controls it or wants to control it.  Anything else?}
{182}{}{在哈勃，如果有什么事情牵扯到不幸和痛苦，那么即使不是德克干的，也是他琢磨着想干的。你还要什么？}
#{183}{}{I don't know what you're talking about, and I don't appreciate your slander!  I suggest you don't show your face in here again.}
{183}{}{我不知道你在说什么，也不喜欢你的诬蔑！希望你不要再来了}
#{184}{}{Don't do that!  Fine, I've been using some questionable portions.  But it's not like I'm committing murder.  Doc Morbid's stuff is already dead, isn't it?}
{184}{}{不要那样做！好吧，我是用了一些可疑的配料。但这和我搞谋杀不一样。莫彼得的原料本来就是死的，是不是？}
#{185}{}{I'm sure it is, Bob.  Have a nice day...}
{185}{}{我想是的，鲍勃。再见……}
#{186}{}{Cannibalism is a crime against humanity, Bob.  I'm going to see that you pay for it.}
{186}{}{吃人是违背人性的罪行，鲍勃。我是来惩罚你的。}
#{187}{}{Maybe it is.  Maybe it isn't.  I don't care.  I want a piece of the action.}
{187}{}{也许是。也许不是。我不在乎。我想要你意思一下。}
#{188}{}{Not so loud!  I don't need you saying that all over the Hub...}
{188}{}{别那么大声！我不想让你喊得全哈勃城都知道……}
#{189}{}{I guess I was rude.  Have a nice day...}
{189}{}{我想我有点无礼。再见……}
#{190}{}{You know, the police station is just across the street.  I really should take a little walk.}
{190}{}{你知道，警察局就在街对面。我真该过去一趟。}
#{191}{}{I can get even louder.  But I can also shut up.  Noise is cheap, silence is expensive.}
{191}{}{我还能更大声。但我也可以闭嘴。话多无益，沉默是“金”。}
#{192}{}{How the hell am I gonna pay you if you eat all my stock?  Fine!  Have another iguana!  I hope you choke on it!}
{192}{}{如果你吃掉了我所有的存货，该死的我拿什么付你钱？好了！再来一串！最好噎死你！}
#{193}{}{I don't like your attitude.}
{193}{}{我不喜欢你的态度。}
#{194}{}{Tough.  You want money, I'll give it to you.  You want food, I'll give it to you.  You want to die, I'll arrange it.  But "like" ain't part of the equation.}
{194}{}{呸。你想要钱，我给你。你想要吃的，我给你。你想要死，我帮你安排。但不要说什么“喜欢”，态度不是我的义务。}
#{195}{}{Nothing I can think of.  Now if you'll excuse me, I have a business to run.}
{195}{}{我想不起还有什么。如果你不介意，我还有事要办。}
#{196}{}{Sorry, we're all out of iguana.}
{196}{}{对不起，我们的蜥蜴都用完了。}
#{197}{}{We only have whole iguana on a stick.  Twenty bucks.}
{197}{}{我们只有烤整蜥蜴了。二十块。}
#{198}{}{We only have prime select choice.  Eight bucks.}
{198}{}{我们只有精选肉块了。八块。}
#{199}{}{Again?  Man you must be hungry.  We got whole iguana on a stick for twenty bucks, and our prime select pieces for eight bucks.}
{199}{}{又来了？老兄你肯定是饿了。烤整蜥蜴是二十块，精选肉块是八块。}
#{200}{}{I'll take a whole iguana.}
{200}{}{我来份烤整蜥蜴。}
#{201}{}{I'll take your prime select.}
{201}{}{我来份精选肉块。}
#{202}{}{You know, I hear your prime select tastes like chicken.  Do you like eating cowardly guys?}
{202}{}{你知道吗，我听说你的精选肉块吃起来像鸡肉。你喜欢吃人肉吗？}
#{203}{}{No sissy portions!  Me want all iguana!  Ugh!}
{203}{}{别小家子气！我要所有的烤蜥蜴！噢！}
#{204}{}{Hmm, smell good!  Me want prime!}
{204}{}{呣, 闻来好！偶要精花肉！}
#{205}{}{How the hell am I gonna pay you if you eat all my stock?  Fine!  Have another iguana!  I hope you choke on it!}
{205}{}{如果你吃掉了我所有的存货，该死的我拿什么付你钱？好了！再来一串！最好噎死你！}
#{206}{}{I don't like your attitude.}
{206}{}{我不喜欢你的态度。}
#{207}{}{Uh, bye.}
{207}{}{喔，再见。}
#{208}{}{Wait a minute.  We've got to find a way to reach a mutual understanding!}
{208}{}{等一下。我们可以想办法达成默契。}
#{209}{}{The only way you'll be able to keep me quiet is to kill me.}
{209}{}{要让我保持沉默的唯一办法就是杀了我。}
#{210}{}{Sorry, no deal.}
{210}{}{对不起，没得谈。}
#{211}{}{Fine.  What can I get out of this?}
{211}{}{好吧。我能得到什么？}
#{212}{}{Fine.  What do you want me to pay?}
{212}{}{好吧。你要我付你多少？}
#{213}{}{I want }
{213}{}{我想要每五天}
#{214}{}{50}
{214}{}{50}
#{215}{}{75}
{215}{}{75}
#{216}{}{100}
{216}{}{100}
#{217}{}{150}
{217}{}{150}
#{218}{}{200}
{218}{}{200}
#{219}{}{ bucks every five days.}
{219}{}{块。}
#{220}{}{I don't think I'll blackmail you.  Carry on.}
{220}{}{我想我不会勒索你的。就这样吧。}
#{221}{}{I'd change your mind if I were you, friend.  People have died for less in the Hub.}
{221}{}{朋友，我是你的话就改主意。在哈勃城是很容易丧命的。}
#{222}{}{Fine.  It's a deal. }
{222}{}{好吧。就这样。}
#{223}{}{ bucks, due every five days.  I guess I'll see you in five...}
{223}{}{块，每五天。我想我们五天后再见……}
#{224}{}{No way I'm going for that.  I can't afford more than what I'm paying you now.}
{224}{}{那没办法。我付不起比现在更多的钱了。}
#{225}{}{Too bad, Bob.  I'd hate to start singing.}
{225}{}{太糟了，鲍勃。我讨厌唱歌。}
#{226}{}{Fine.  We'll stay with the current arrangement... for now.}
{226}{}{好吧。暂时……我们就按目前的协议吧。}
#{227}{}{Can you afford a funeral, Bob?}
{227}{}{你付得起一个葬礼吗，鲍勃？}
#{228}{}{Fine.  Maybe it would be good if our paths didn't cross again.}
{228}{}{好吧。最好我们以后别再打交道了。}
#{229}{}{You may be a songbird, but I'm the golden goose.  You ain't gonna sing, not when I'm the only goose you've got.  Now get out!}
{229}{}{也许你就是只会唱的小鸟，但我是下金蛋的鹅。只要我还能有你要的金蛋，在这你就别唱。现在滚吧！}
#{230}{}{First sensible thing I remember you saying.  Now get out!}
{230}{}{这是你说的第一件有理智的事。现在滚吧！}
#{231}{}{Gimme' an iguana on a stick.}
{231}{}{给我一串烤蜥蜴。}
#{232}{}{What can you tell me about a Water Chip?}
{232}{}{你能跟我说一些有关净水芯片的事吗？}
#{233}{}{What can you tell me about Decker?}
{233}{}{你能跟我说一些有关德克的情况吗？}
#{234}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{234}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{235}{}{Do you know anything about the missing caravans?}
{235}{}{有关失踪的商队，你知道些什么吗？}
#{236}{}{What, me trouble?  What gives you that impression?}
{236}{}{什么，我有麻烦？你从哪里看出来的？}
#{237}{}{Anything interesting happening in the Hub?}
{237}{}{哈勃城发生了什么有趣的事吗？}
#{238}{}{Me hungry!  Grrrrr!}
{238}{}{我饿了！呃啊！}
#{239}{}{Terrible business.  Those poor people.  Oh, those poor people.  Losing their lives in such a ghastly way!  Is there anything else I can do for you?  Like feed you, perhaps?}
{239}{}{可怕的行当。那些可怜的人。喔，那些可怜虫，小命丢得这么惨！我还能为你做些什么？也许，来点吃的？}
#{240}{}{Nothing, bye.}
{240}{}{没什么，再见。}
#{241}{}{Me go now.}
{241}{}{我走唔。}
