{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a member of the Blades.}
{100}{}{你看见一个利刃帮的成员。}
#{101}{}{Hi.}
{101}{}{嗨。}
#{102}{}{Hello.}
{102}{}{你好。}
#{103}{}{Have a nice day.}
{103}{}{你好。}
#{104}{}{Nice weather we are having today.}
{104}{}{今天天气不错。}
#{105}{}{I wonder if it will rain.}
{105}{}{我在想会不会下雨。}
#{106}{}{Have you ever seen the rain glow?}
{106}{}{你看到过雨水会发光吗？}
#{107}{}{Gotta get back to work.}
{107}{}{我得回去干活了。}
#{108}{}{We don't get many outsiders here.}
{108}{}{我们这里很少有外面来的人。}
#{109}{}{Gotta go.}
{109}{}{我得走了。}
#{110}{}{See ya.}
{110}{}{再见。}
#{111}{}{Good day.}
{111}{}{好。}
#{112}{}{Thanks for your help.}
{112}{}{多谢你帮忙。}
#{113}{}{We won't forget you.}
{113}{}{我们不会忘记你的。}
#{114}{}{Nice to have you on our side.}
{114}{}{很高兴你站在我们这一边。}
#{115}{}{Things are going to be better now.}
{115}{}{现在情况不错。}
