{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Closed by order of Sheriff Justin Greene.}
{100}{}{治安官贾斯廷下令关闭。}
#{101}{}{There is a small sign on the booth.}
{101}{}{货摊上有个小的告示。}
#{102}{}{Wanted: Iguana Bob Frazier, dead or alive. If you have seen any information on his present location or the persons responsible for his escape, please inform the Sheriff immediately.}
{102}{}{通缉令：鲍勃·弗兰舍，不论死活。如果你知道他当前的下落，或者认识帮助他潜逃的人，请立即通知治安官。}
