
#{100}{}{Time left:  }
{100}{}{剩余时间：}

#{101}{}{ seconds.}
{101}{}{秒。}

#{102}{}{This is where you make your mark on the world. (a small pile of ash.)}
{102}{}{这里可能就是你遗恨人间的地方【变成一小堆灰烬】。}

#{104}{}{Time left:  }
{104}{}{剩余时间：}

#{105}{}{ seconds.}
{105}{}{秒。}

#{106}{}{This is where you make your mark on the world. (a small pile of ash.)}
{106}{}{这里可能就是你遗恨人间的地方【变成一小堆灰烬】。}

#{108}{}{Time left:  }
{108}{}{剩余时间：}

#{109}{}{ seconds.}
{109}{}{秒。}

#{110}{}{This is where you make your mark on the world. (a small pile of ash.)}
{110}{}{这里可能就是你遗恨人间的地方【变成一小堆灰烬】。}
