{1099}{}{?}
{1199}{}{我可以告诉你：Deathclaw-死亡爪、Raiders-歹徒、Junktown-迦克镇、Brahmin-双头牛、Chip-芯片、Merchants-商人、Khans-可汗帮、Garl-伽尔、Shady Sands-沙荫镇、Hub-哈勃城、Tandi-坦蒂、Aradesh-亚拉德什、Seth-赛思、Razlo-拉斯洛、Police-警察、Caravans-商队、Traders-商人、Children-大教堂教徒、Necropolis-大墓地城、Spot-辐射中心、Brotherhood-兄弟会、Boneyard-晒骨场、Towers-水塔、Town-城里、Downtown-商业区、Heights-高地区。}

#{100}{}{You see a small child.}
{100}{}{你看见一个孩子。}

#{101}{}{Hi!}
{101}{}{嗨！}

#{102}{}{Hello.}
{102}{}{你好。}

#{103}{}{Where are your parents?}
{103}{}{你爸妈呢？}

#{104}{}{Erf.}
{104}{}{呃……}

#{105}{}{I dunno. Around here somewhere.}
{105}{}{不知道，附近吧。}

#{106}{}{You're funny!}
{106}{}{你有意思！}

#{107}{}{Hey, are you gonna kill someone?}
{107}{}{嘿，你会杀人？}

#{108}{}{Yes.}
{108}{}{对。}

#{109}{}{No!}
{109}{}{不会。}

#{110}{}{Erf.}
{110}{}{呃。}

#{111}{}{I'm gonna tell my mommy!}
{111}{}{我要告诉我妈妈！}

#{112}{}{Then you shouldn't carry around a weapon like that.}
{112}{}{那你就不该拿着武器乱晃。}


#{980}{}{Huh?}
{980}{}{哈？}

#{981}{}{I da know. Ask mommy.}
{981}{}{我不知道，问我妈妈。}

#{982}{}{Ask daddy.}
{982}{}{问我爸爸。}


#{1000}{}{Deathclaw}
#{1001}{}{Raiders}
#{1002}{}{Junktown}
#{1003}{}{Brahmin}
#{1004}{}{Chip}
#{1005}{}{Merchants}
#{1006}{}{Khans}
#{1007}{}{Garl}
#{1008}{}{Shady Sands}
#{1009}{}{Hub}
#{1010}{}{Tandi}
#{1011}{}{Aradesh}
#{1012}{}{Seth}
#{1013}{}{Razlo}
#{1014}{}{Police}
#{1015}{}{Caravans}
#{1016}{}{Traders}
#{1017}{}{Children}
#{1018}{}{Necropolis}
#{1019}{}{Spot}
#{1020}{}{Brotherhood}
#{1021}{}{Boneyard}
#{1022}{}{Towers}
#{1023}{}{Town}
#{1024}{}{Downtown}
#{1025}{}{Heights}

{1000}{}{Deathclaw}
{1001}{}{Raiders}
{1002}{}{Junktown}
{1003}{}{Brahmin}
{1004}{}{Chip}
{1005}{}{Merchants}
{1006}{}{Khans}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Hub}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Police}
{1015}{}{Caravans}
{1016}{}{Traders}
{1017}{}{Children}
{1018}{}{Necropolis}
{1019}{}{Spot}
{1020}{}{Brotherhood}
{1021}{}{Boneyard}
{1022}{}{Towers}
{1023}{}{Town}
{1024}{}{Downtown}
{1025}{}{Heights}

#{1100}{}{Wah! Nightmare monster!}
{1100}{}{哦！恐怖恐怖的怪物！}

#{1101}{}{Big meanies!}
{1101}{}{大坏蛋！}

#{1102}{}{I da know.}
{1102}{}{不知道。}

#{1103}{}{Big stinkies.}
{1103}{}{很大，很臭的东东。}

#{1104}{}{Ask mommy.}
{1104}{}{问我妈妈。}

#{1105}{}{Funny sea songs.}
{1105}{}{一帮有趣的家伙。}

#{1106}{}{Big meanies!}
{1106}{}{大坏蛋！}

#{1107}{}{Bad man.}
{1107}{}{坏蛋。}

#{1108}{}{I'm not tellin' ya.}
{1108}{}{我不告诉你。}

#{1109}{}{Big city.}
{1109}{}{大城市。}

#{1110}{}{I'm not tellin'.}
{1110}{}{不告诉你。}

#{1111}{}{Nope, not gonna tell ya.}
{1111}{}{我不说。}

#{1112}{}{Mommy doesn't want me to talk about him.}
{1112}{}{妈妈不让我说他。}

#{1113}{}{Daddy thinks he's funny.}
{1113}{}{爸爸说他很好玩。}

#{1114}{}{Big peoples.}
{1114}{}{大人。}

#{1115}{}{They have those stinkies that pull them.}
{1115}{}{臭臭的东西拉着他们的货。}

#{1116}{}{Nice people. They give me candy.}
{1116}{}{好人，他们给我糖糖吃。}

#{1117}{}{They don't like to play hide and seek.}
{1117}{}{他们都不喜欢躲猫猫。}

#{1118}{}{Scary place.}
{1118}{}{可怕的地方。}

#{1119}{}{Yucky place.}
{1119}{}{不好玩的地方。}

#{1120}{}{Scary place.}
{1120}{}{可怕的地方。}

#{1121}{}{Scary place.}
{1121}{}{可怕的地方。}

#{1122}{}{Mommy won't let us play there.}
{1122}{}{妈妈不让我去那里玩。}

#{1123}{}{Daddy keeps telling us to play there.}
{1123}{}{爸爸老是让我在那里玩。}

#{1124}{}{Big people area.}
{1124}{}{大人的地方。}

#{1125}{}{Big people area.}
{1125}{}{大人的地方。}
