{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a dark-skinned man adorned with bright scarves and trinkets.}
{100}{}{你看见一个戴着亮闪闪围巾和各种饰物的黝黑皮肤男人。}

#{101}{}{You see Chuck, the gypsy fortune-teller.}
{101}{}{你看见查克，吉普赛算命师。}

#{102}{}{Hello, stranger. May I be of service?}
{102}{}{你好陌生人。我能帮你什么？}

#{103}{}{Uugh!}
{103}{}{喔！}

#{104}{}{I'm just looking around, thanks.}
{104}{}{我就是看看，谢谢。}

#{105}{}{I'm getting to know the people of Adytum.}
{105}{}{我想了解一些内城区的人。}

#{106}{}{Why do you assume that I need something?}
{106}{}{你怎么知道我想要什么？}

#{107}{}{Hmm. Don't worry, my simple friend, you have great things ahead.}
{107}{}{嗯。别紧张，我的朋友，你有大事要做。}

#{108}{}{And what do you think of our town?}
{108}{}{你觉得这个城市怎么样？}

#{109}{}{It's okay.}
{109}{}{还好。}

#{110}{}{Don't like it much. Not too friendly.}
{110}{}{不是很喜欢，不太友好。}

#{111}{}{You've done remarkably well, considering the hostile circumstances.}
{111}{}{在这样一个环境下，你已经做的很好了。}

#{112}{}{I'm called Chuck. Welcome to Adytum. I'm afraid that most of the people here aren't too forthcoming with strangers, though.}
{112}{}{我叫查克。欢迎来到内城区。不过其他住民对陌生人可不太友好啊。}

#{113}{}{Yeah, I noticed.}
{113}{}{是啊，我也发现了。}

#{114}{}{So, what's your job, Chuck?}
{114}{}{那么你是干什么的，查克？}

#{115}{}{See you around, Chuck.}
{115}{}{再见，查克。}

#{116}{}{Good journeys, wanderer.}
{116}{}{一路平安。}

#{117}{}{We all need something, don't we? And you wouldn't have talked to me if you didn't want something, whether information, conversation, or perhaps guidance. I can tell that you've been through a lot. What do you need?}
{117}{}{每个人都想做点什么，问点什么，对吧？你要是什么都不想要，比如消息，聊天，或是引导，也就不会和我说话了。我知道你经历了很多事情。你需要什么帮助？}

#{118}{}{Uh, I don't need anything, thanks.}
{118}{}{我什么都不需要，谢谢。}

#{119}{}{Now that you mention it, perhaps you can give me some advice.}
{119}{}{既然你这么说，也许你可以给我一些建议。}

#{120}{}{【Chuck pulls out a set of Tarot cards.】 Let me consult the cards. 【Chuck shuffles the cards.】}
{120}{}{【查克掏出了一些塔罗牌】抽个牌吧。【洗牌】}

#{121}{}{【Chuck pulls out a card with a picture of a man in a lab coat with a computer in one hand, and a card with a man in power armor.】 The Heirophant and the Prince of Wands in the south . . . great wisdom and nobility await in a place to the south.}
{121}{}{【查克取出了两张牌，其中一张牌上画着一个穿着实验室大褂的人坐在电脑旁，另一张牌上画的是一个穿着能量装甲的人。】教皇和权杖王子在南方……南方的某个地方有高度的智慧和尊贵。}

#{122}{}{【Chuck pulls out a card with a picture of a man with a vibro-blade and a flag.】 The Prince of Swords in the north . . . you must face a powerful foe far to the north.}
{122}{}{【查克取出了一张牌，牌上画着一个手持能量刀抗着大旗的人】带剑王子在北方……你在北方有一个我强大的敌人。}

#{123}{}{【Chuck pulls out a card with a picture of a radio tower, and a card with a picture of a man in a suit with a scepter.】 The Tower and the Emperor . . . great change awaits by the hands of a powerful leader. Whether that change is death, I cannot t#ell.}
{123}{}{【查克取出两张牌，一张上面画着无线电塔台，另一张画着一个拿着节杖身穿正装的人】高塔和皇帝……一个强大的领袖将要领导巨大变革。这个变革是好是坏，我不敢说。}

#{124}{}{【Chuck pulls out a card with a picture of a man dancing on a nuclear warhead.】 The Fool. I cannot help you; you must make your own way in the world.}
{124}{}{【查克取出一张牌，上面画的是一个人在核弹头上跳舞】愚人牌。我帮不了你，你必须自己在这个世界上闯荡。}

#{125}{}{【More】}
{125}{}{【更多】}

#{126}{}{Hmm. Thanks for the advice.}
{126}{}{嗯，多谢。}

#{127}{}{Do you actually believe this stuff?!}
{127}{}{你相信这些吗？}

#{128}{}{It works for me. If you don't want to believe then it's not for you.}
{128}{}{对我来说就是如此，心诚则灵。}

#{129}{}{No offense, but it sounds like a load of superstition.}
{129}{}{别生气，我觉得这有点迷信。}

#{130}{}{Well, I guess we each have our own beliefs.}
{130}{}{哈，我们都有自己的信仰吧。}

#{131}{}{If that is how you feel, then I suppose we have nothing more to discuss.}
{131}{}{如果你真是这么想的，那我们就没什么可聊的了。}

#{132}{}{Indeed, we do. And your universe is shaped by your beliefs, while my universe is shaped by my thoughts. We may not share beliefs, but I wish you well in your universe.}
{132}{}{没错。每个人的世界都是由他自己的信仰塑造的，而我的宇宙则是由我的思维所衍生的。我们的意见可能不尽相同，但我祝愿你的世界美好。}

#{133}{}{It is home.}
{133}{}{很灵。}

#{134}{}{Uh, yeah. See you around.}
{134}{}{哦，好，再见。}

#{135}{}{Things do seem a little quite around here.}
{135}{}{这里是有点安静。}

#{136}{}{I know what you mean. I've seen a lot of suffering.}
{136}{}{我知道你的意思，我在这里看到了很多痛苦。}

#{137}{}{The Regulators make sure of that. The people of Adytum sometimes
# suffer because of their strict rules.}
{137}{}{都是管理者们搞的，他们的苛政的确让这里的人受了不少苦。}

#{138}{}{I guess so. Well, see you around.}
{138}{}{我想也是。嗯，再见了。}

#{139}{}{And you're okay with this?}
{139}{}{你能忍受？}

#{140}{}{Since I wish to stay here, I accept the Regulators as part of that
# which is Adytum. However, I do what I can to lighten their lives.}
{140}{}{既然我要在这里过活，我就要忍受管理者的存在。再说，我也可以帮助这里的人啊。}

#{141}{}{You do not seem to agree with what they do.}
{141}{}{你看起来不喜欢他们的行为吧。}

#{142}{}{Is there anything else that you could do?}
{142}{}{你还能做什么？}

#{143}{}{The Regulators protect their own interests, and I must respect that.}
{143}{}{管理者有他们自己的利益，这点我尊重他们。}

#{144}{}{Yeah, whatever.}
{144}{}{好，随你怎么说了。}

#{145}{}{I don't necessarily agree with that view, but can understand it.}
{145}{}{我不一定非要同意他们的做法，但我能明白其中的利害。}

#{146}{}{It's been good talking. See you around.}
{146}{}{和你聊的很愉快，再见。}

#{147}{}{Well, I'm only one person, but help in what way I can.
# I advise you to fight for what you believe in, but most of all, choose
# the fights that are worth fighting, and find the times when compromise and
# hope will win greater victories.}
{147}{}{我只有一个人，但是我已经尽力地帮助他们了，我建议你为了自己的信仰而抗争，但首先，你要确定这是值得的。有时候，一定程度的妥协和企盼往往会带来更大的胜利。}

#{148}{}{Do you have any other advice?}
{148}{}{你还有什么其他建议？}

#{149}{}{The people of Adytum have much to do in a normal day.
# They do not want their work to be found wanting at the end of the day.}
{149}{}{内城区的人们白天的工作很多。他们不喜欢在夜里还要加班。}

#{150}{}{Yeah, well, whatever.}
{150}{}{嗯，也许吧。}

#{151}{}{Things do seem a little quiet around here.}
{151}{}{这里是有点安静。}

#{152}{}{Thank you. It has been difficult. We lose people to the Deathclaws
# sometimes, and winters can be hard, especially when the Hub traders don't
# come. But we are surviving.}
{152}{}{谢谢。日子很艰难。死在死亡爪下的人不少，冬天也很难熬，特别是哈勃城的商人不来的时候。尽管如此，我们还是活下来了。}

#{153}{}{Good luck.}
{153}{}{祝你好运！}

#{154}{}{What is going on with the DeathClaws?}
{154}{}{死亡爪是怎么回事？}

#{155}{}{They infest an area North-East from here, and can often take
# the lives of people given the task of trading with the Gun Runners.}
{155}{}{它们在离这里东北不远的地方筑巢，很多去找军火商做买卖的人都被它们料理了。}

#{156}{}{Hopefully you will find a solution.}
{156}{}{也许你有办法。}

#{157}{}{Yeah. Whatever.}
{157}{}{嗯，也许。}

#{158}{}{Perhaps. I think Adytum will be here. Instead of going to the world,
# the world must come to us, like you have.}
{158}{}{也许，与其让内城区去面对世界，不如让世界来发现它，不如你就是发现它的一个。}

#{159}{}{Hmm. I guess so.}
{159}{}{没错。}

#{160}{}{I'm a farmer. I also like to do a little bit of work on the buildings,
# restoring them and keeping them intact, and sometimes I give advice.}
{160}{}{我是一个农场主。我也喜欢搞点建筑什么的，房子修修补补还能用，我能给你一些建议。}

#{161}{}{What kind of advice?}
{161}{}{什么建议？}

#{162}{}{Yes, unfortunately. I think . . . it is a kind of crucible, that
# by surviving these hard times, we come to rely on each other and to learn
# the skills we need to survive. I think, eventually, mankind will be better for it.}
{162}{}{没错，很不幸。我想……现在是个艰难的时期，在熬这些日子的时候，我们互相依靠，学会了生存技巧。我想不管怎么样人们总会越过越好。}

#{163}{}{I don't agree.  I have come across many gangs and raiders in my travels.
# They've become petty killers and thieves. I think that we all risk that eventually.}
{163}{}{我不同意，我在路上遇见很多帮派和强盗，他们就是彻头彻尾的小偷和杀人犯。我们最后都会走上这条路的。}

#{164}{}{Perhaps you're right. Certainly those who survive will be stronger.}
{164}{}{也许你说的对，生存下来的人的确是强壮的。}

#{165}{}{They will eventually destroy themselves. And the people who will be
# left will be the ones who work together to survive, like us.}
{165}{}{他们会最后毁掉自己的。最后活下来的一定是团结的人们，就像我们。}

#{166}{}{I'm glad that some of the outsiders, like you, feel that way.
# We need to find ways to work together to build something new.
# It won't start here; we are too regulated, but it has to start somewhere.}
{166}{}{很高兴有像你这样的外乡人也能这么想。我们要精诚团结，建造新的未来。也许这里还没开始，我们被管得太死了，但肯定在其他地方会有这样一天的。}

#{167}{}{Hello. What can I do for you?}
{167}{}{你好，我能帮你做什么？}

#{168}{}{Can I help you?}
{168}{}{需要帮忙？}

#{169}{}{Yes?}
{169}{}{嗯？}

#{170}{}{Just stopping by to say hello.}
{170}{}{路过，问声好。}

#{171}{}{I'm looking for a little advice.}
{171}{}{我想向你咨询。}

#{172}{}{May I ask what you do around here?}
{172}{}{你在这里做什么？}

#{173}{}{Hello, then. I hope you're doing well.}
{173}{}{哦，你好啊，祝你一切顺利。}
