{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Cindy.}
{100}{}{你看见辛迪。}

#{101}{}{She is crying.}
{101}{}{她在哭。}

#{102}{}{Hello, }
{102}{}{你好，}

#{103}{}{. Have you found the water chip yet?}
{103}{}{。你找到净水芯片了？}

#{104}{}{Not yet. I haven't had much luck.}
{104}{}{还没。我运气不好。}

#{105}{}{No luck yet, but I know I'll find it. By the way, how are you doing?}
{105}{}{没找到。我会找到的，你们怎么样了？}

#{106}{}{Urug!}
{106}{}{喔！}

#{107}{}{Oh . . . you don't understand me. I guess we really don't have much hope
# after all. Excuse me while I cry.}
{107}{}{哦……你没听明白，我想本来我们的机会就不大了。刚才我哭了，让你见笑了。}

#{108}{}{Ugg!}
{108}{}{吼吼！}

#{109}{}{Please find it before we die of thirst.}
{109}{}{赶紧找到它，我们会渴死的。}

#{110}{}{You've got to find it! Don't let us die like this!}
{110}{}{你马上给我去找！别让我们这样死哇！}

#{111}{}{Keep trying. I believe in you. I know you will do everything you can
# to save us.}
{111}{}{继续吧，我信任你，我知道你会尽力的。}

#{112}{}{Who do you think might be involved?}
{112}{}{谁跟这件事有关？}

#{113}{}{I am afraid of what is happening. Someone has been stealing water and now
# everyone is on edge.}
{113}{}{最近的事情我好怕。有人在偷水，所有人现在都急得要死。}

#{114}{}{Who would do such a thing?}
{114}{}{谁会做这样的事？}

#{115}{}{What happened?}
{115}{}{发生什么了？}

#{116}{}{Some people have been accused and fights have broken out over it, but
# nobody really knows.}
{116}{}{有人互相指责，还有人大打出手，但没人知道谁是元凶。}

#{117}{}{Okay. Thanks.}
{117}{}{好，多谢。}

#{118}{}{Some people reported that their water had been stolen. They weren't given
# more water but some friends shared with them. After this everybody got very
# paranoid and started guarding their water. A few days later someone knocked the
# guard out in the ration supply area and stole water.}
{118}{}{有人报告说他们的水被偷了，上面的人说不能多发水，他们只能问朋友要水喝。这件事情后，所有人都疑神疑鬼的，把自己的水看得死死的。后来有一天，还有人把配给水站的守卫打晕了偷水！}

#{119}{}{That's terrible! What can I do?}
{119}{}{太可怕了！我能做什么？}

#{120}{}{Maybe you can stop whoever is doing this.}
{120}{}{你也许能帮我们找出这个人。}

#{121}{}{I'll take a look around.}
{121}{}{我去看看。}

#{122}{}{You're the water thief?! How could you?}
{122}{}{你是偷水贼？怎么可能？}

#{123}{}{Thank you so much for saving us all.}
{123}{}{谢谢你救了我们。}

#{124}{}{You did a good job catching the thief. Please hurry and find the water
# chip.}
{124}{}{你抓了偷水的人，做的好。那还是赶紧去找净水芯片吧。}

#{125}{}{How could you betray us? Now everyone here will die! But you don't care,
# do you?}
{125}{}{你怎么能背叛我们呢？这里所有人都会渴死的！你不在乎，是不是？}

#{126}{}{I'm scared. I don't know what will happen to us all. Please, don't let us
# down.}
{126}{}{我吓死了。我不知道以后还会发生什么。拜托，不要辜负我们。}

#{127}{}{Don't worry, I'll do my best. You'll be all right.}
{127}{}{别担心，我会尽力，你们不会有事的。}

#{128}{}{Yeah, whatever.}
{128}{}{对，随你说。}
