{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Cleo.}
{100}{}{你看见柯里奥。}

#{101}{}{No retreat, no surrender,  pal.}
{101}{}{不准后退，不准投降，弟兄们。}

#{102}{}{No retreat, no surrender, lady.}
{102}{}{不准后退，不准投降，姐妹们。}

#{103}{}{Weren't you just leaving? Get outta here.}
{103}{}{你要走？滚吧！}

#{104}{}{What do you want?}
{104}{}{你想干啥？}

#{105}{}{Tell me about Loxley.}
{105}{}{告诉我洛克西里的事情。}

#{106}{}{Tell me about Jasmine.}
{106}{}{告诉我关于茉莉的事情。}

#{107}{}{Tell me about the Circle.}
{107}{}{告诉我关于地下圈的事情。}

#{108}{}{Tell me about Decker.}
{108}{}{告诉我关于德克的事情。}

#{109}{}{Tell me about the missing caravans.}
{109}{}{告诉我关于失踪商队的事情。}

#{110}{}{Hi.}
{110}{}{嗨。}

#{111}{}{Um, ugh!}
{111}{}{嗯，吼！}

#{112}{}{Hey! What's happening?}
{112}{}{嘿！怎么回事？}

#{113}{}{Tell me about Loxley.}
{113}{}{告诉我关于洛克西里的事情。}

#{114}{}{Tell me about Jasmine.}
{114}{}{告诉我关于茉莉的事情。}

#{115}{}{Tell me about the Circle.}
{115}{}{告诉我关于地下圈的事情。}

#{116}{}{Tell me about Decker.}
{116}{}{告诉我关于德克的事情。}

#{117}{}{Tell me about the missing caravans.}
{117}{}{告诉我关于失踪商队的事情。}

#{118}{}{Tell me about the missing caravans.}
{118}{}{告诉我关于失踪商队的事情。}

#{119}{}{Hi.}
{119}{}{嗨。}

#{120}{}{Um, ugh!}
{120}{}{嗯，吼！}

#{121}{}{He's the boss. What else is there to know?}
{121}{}{他是我们老板，你还想知道什么？}

#{122}{}{Tell me about Jasmine.}
{122}{}{告诉我关于茉莉的事情。}

#{123}{}{Tell me about the Circle.}
{123}{}{告诉我关于地下圈的事情。}

#{124}{}{Tell me about Decker.}
{124}{}{告诉我关于德克的事情。}

#{125}{}{Tell me about the missing caravans.}
{125}{}{告诉我关于失踪商队的事情。}

#{126}{}{Hi.}
{126}{}{嗨！}

#{127}{}{Um, ugh!}
{127}{}{嗯，吼！}

#{128}{}{She's the bosses assistant. Not a bad gal.}
{128}{}{她是老板的助手。不错的妞。}

#{129}{}{Tell me about Loxley.}
{129}{}{告诉我关于洛克西里的事情。}

#{130}{}{Tell me about Jasmine.}
{130}{}{告诉我关于茉莉的事情。}

#{131}{}{Tell me about the Circle.}
{131}{}{告诉我关于地下圈的事情。}

#{132}{}{Tell me about Decker.}
{132}{}{告诉我关于德克的事情。}

#{133}{}{Tell me about the missing caravans.}
{133}{}{告诉我关于失踪商队的事情。}

#{134}{}{Hi.}
{134}{}{嗨！}

#{135}{}{Um, ugh!}
{135}{}{嗯，吼！}

#{136}{}{If you're lucky, you'll consider yourself one of us by the end of the day. At home, part of the
# furniture, you know?}
{136}{}{幸运的话，你今天就可以成为我们的一员，在家里，做某个家具，你懂我意思吗？}

#{137}{}{Tell me about Loxley.}
{137}{}{告诉我有关洛克西里的事情。}

#{138}{}{Tell me about Jasmine.}
{138}{}{告诉我有关茉莉的事情。}

#{139}{}{Tell me about Decker.}
{139}{}{告诉我有关德克的事情。}

#{140}{}{Tell me about the missing caravans.}
{140}{}{告诉我有关失踪商队的事情。}

#{141}{}{Hi.}
{141}{}{嗨！}

#{142}{}{Um, ugh!}
{142}{}{嗯，吼！}

#{143}{}{We don't discuss Mr. Decker in polite company.}
{143}{}{我们从来不在正式场合谈德克先生。}

#{144}{}{Tell me about Loxley.}
{144}{}{告诉我有关洛克西里的事情。}

#{145}{}{Tell me about Jasmine.}
{145}{}{告诉我有关茉莉的事情。}

#{146}{}{Tell me about the Circle.}
{146}{}{告诉我有关地下圈的事情。}

#{147}{}{Tell me about the missing caravans.}
{147}{}{告诉我有关失踪商队的事情。}

#{148}{}{Hi.}
{148}{}{嗨！}

#{149}{}{Um, ugh!}
{149}{}{嗯，吼！}

#{150}{}{We had nothing to do with that!}
{150}{}{我们和那个毫无瓜葛！}

#{151}{}{Tell me about Loxley.}
{151}{}{告诉我有关洛克西里的事情。}

#{152}{}{Tell me about Jasmine.}
{152}{}{告诉我有关茉莉的事情。}

#{153}{}{Tell me about the Circle.}
{153}{}{告诉我有关地下圈的事情。}

#{154}{}{Tell me about Decker.}
{154}{}{告诉我有关德克的事情。}

#{155}{}{Hi.}
{155}{}{嗨！}

#{156}{}{Um, ugh!}
{156}{}{嗯，吼！}

#{157}{}{Hi yourself.}
{157}{}{谁跟你嗨。}

#{158}{}{Why do you even bother talking to people, moron?}
{158}{}{你这样的白痴还和别人说话？}

#{159}{}{A great leader. He's doing everything to screw over the right people and keep the Hub together --
# for a small fee, of course.}
{159}{}{伟大的领袖。他把那些所谓的好人玩的团团转，是他团结了整个哈勃城……当然，他也收点钱的。}

#{160}{}{Tell me about Jasmine.}
{160}{}{告诉我有关茉莉的事情。}

#{161}{}{Tell me about the Circle.}
{161}{}{告诉我有关地下圈的事情。}

#{162}{}{Tell me about Decker.}
{162}{}{告诉我有关德克的事情。}

#{163}{}{Tell me about the missing caravans.}
{163}{}{告诉我有关失踪商队的事情。}

#{164}{}{Tell me about the missing caravans.}
{164}{}{告诉我有关失踪商队的事情。}

#{165}{}{Hi.}
{165}{}{嗨！}

#{166}{}{Um, ugh!}
{166}{}{嗯，吼！}

#{167}{}{It's both a job and an adventure. Helping the poor, risking your life, meeting new and interesting
# blokes. That us, the good guys!}
{167}{}{这是工作也是冒险。劫富济贫，浪荡生涯，脑袋别在裤腰带上拼命，和各种各样的混球打交道。这就是我们，都是棒小伙子！}

#{168}{}{Tell me about Loxley.}
{168}{}{告诉我有关洛克西里的事情。}

#{169}{}{Tell me about Jasmine.}
{169}{}{告诉我有关茉莉的事情。}

#{170}{}{Tell me about Decker.}
{170}{}{告诉我有关德克的事情。}

#{171}{}{Tell me about the missing caravans.}
{171}{}{告诉我有关失踪商队的事情。}

#{172}{}{Tell me about the missing caravans.}
{172}{}{告诉我有关失踪商队的事情。}

#{173}{}{Hi.}
{173}{}{嗨！}

#{174}{}{Um, ugh!}
{174}{}{嗯，吼！}

#{175}{}{I had a friend who worked for him once. When the assignment went bad, he ran back to Decker for# reinforcements. Decker called him a fool, 
#and he had him lobotomized as an example to others. We don't# like Decker very much around here.}
{175}{}{我有一个兄弟以前帮他做事。后来活儿搞砸了，他回去找德克想再带点弟兄去帮忙，结果呢，德克说他是猪头，还拿他当弱者的典型给大家看！我们这里的人都不喜欢德克这家伙。}
#{176}{}{What rumors do you want to hear? The Water Merchants are playing games. Decker's squeezing merchants# for more protection. The Children 
#of the Cathedral sacrificed it to their god. The Deathclaw ate it. Rumors# ain't worth nothing. The world's full of rumor and suspicion, and empty of truth.  
#Look for fact, not# fiction. But why are you asking? You had friends on the caravan?}
{176}{}{你想知道什么小道消息？有可能是纯水商队在玩把戏，也有可能是德克压榨商队，想多搞点保护费，说不定是大教堂教徒那帮家伙把商队祭了神，没准还是死亡爪美餐了一顿。谣言不是一无是处啊。世界充满了谣言，人人都在怀疑，却查不出多少真相。不要被假象迷惑了，要查找事实……对了，你问这个干什么啊？有朋友在商队？}
#{177}{}{I can't talk about my reasons.}
{177}{}{不能告诉你，我有隐衷。}

#{178}{}{I promised a friend I'd look into it.}
{178}{}{我答应一个朋友要调查清除这件事。}

#{179}{}{I need water for my town and can't afford to have caravans disappear.}
{179}{}{我的城市需要水，商队的消失是个打击。}

#{180}{}{Yeah, I had a friend.}
{180}{}{没错，我有朋友在里面。}

#{181}{}{Fine. I got secrets, too. Good luck, friend.}
{181}{}{好，那我也有秘密，再见吧。}

#{182}{}{Sorry I can't be more useful. Oh, and then there's the rumor about the ship from outer space. I think
# someone's been playing around with too many of Rufus's stupid games.}
{182}{}{抱歉，我所知也不多。据说外太空掉下来一艘太空船，我想大概是有人玩鲁弗斯的游戏过火了吧。}

#{183}{}{Really? Where are you from?}
{183}{}{是吗？你从哪里来？}

#{184}{}{Shady Sands.}
{184}{}{沙荫镇。}

#{185}{}{A place just north of Shady Sands.}
{185}{}{沙荫镇往北一点。}

#{186}{}{Vault 13.}
{186}{}{13号避难所。}

#{187}{}{Here and there. I do odd jobs for places which let me stick around.}
{187}{}{不定，到处打零工，我很少在一个地方多待。}

#{188}{}{Sorry to hear that. I've lost a couple of good friends in my time, and one of them I found worse than
# dead, but I'd rather not go into it.}
{188}{}{同情你，我过去也失去了好多好兄弟，而且我知道其中一个比死还惨，还好建议我没卷进去。}

#{189}{}{Didn't we already discuss that? You've got a one-track mind, pal.}
{189}{}{我们不是聊过这破事儿吗？伙计，你脑袋一根筋啊。}

#{190}{}{Not a bad place if you like sand. A little too dry and wilderness for me. At least in the Hub you don't
# have to worry about wandering Rad Scorpions. We've got enough of our own predators, I suppose.}
{190}{}{你要是喜欢沙子的话，那里确实是个好地方啊。对我来说太荒凉太干燥了。至少，在哈勃城，你不用担心那些满地乱爬的辐射蝎吧。当然，我们这里的厉害主也不少了，我觉得。}

#{191}{}{You're from a Vault? Get out of here! Don't go feeding me that bull.}
{191}{}{你是避难所出来的？！滚！少给我放屁扯淡了！}

#{192}{}{I don't envy you. Of course if you make a name for yourself, you can become one of those wilderness
# fighting legends like Magnum Tom Goddard or Scorpion Joe Cornelius. Man, that must be something!}
{192}{}{我不会嫉妒你的。如果你能打出名堂来，你就是一个荒野战神啦，就像“麦格农”·汤姆·戈达德和“天蝎”·乔伊·科内留斯什么的。嗯，肯定会很爽的吧！}
