{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{This is a badly worn-out desk with a dusty, cracked computer
# seated precariously atop it.}
{100}{}{这张老旧的桌子上，一台灰尘斑斑的破电脑摇摇欲坠。}

#{101}{}{The computer looks badly damaged and unrepairable.}
{101}{}{电脑似乎损坏严重，不能修复。}

#{102}{}{Many circuits are fried from an EMP burst.}
{102}{}{可能是被电磁枪击中，很多电路烤焦了。}

#{103}{}{It doesn't work.}
{103}{}{用不了了。}

#{104}{}{You slice your hands on the case.}
{104}{}{你把自己的手划破了。}
