{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Doc Morbid's assistant, Cougar.}
{100}{}{莫彼得医生的助手，库戈尔。}

#{101}{}{How's it going?}
{101}{}{过的怎样？}

#{102}{}{Good, and you?}
{102}{}{好啊，你呢？}

#{103}{}{I need to see the Doc.}
{103}{}{我要见医生。}

#{104}{}{Ung.}
{104}{}{哼。}

#{105}{}{The Cougar is always fine.}
{105}{}{我总是很好的。}

#{106}{}{Hey, I gotta know . . .}
{106}{}{嘿，我想知道……}

#{107}{}{You need to talk to my man, Flash, here. He can help you out.}
{107}{}{你应该和我的哥们弗莱士谈一谈，他会帮你的。}

#{108}{}{Yow! Don't talk too fast man. You give the Cougar a headhurt.
# Talk to Flash instead.}
{108}{}{喂，别说那么快，你的语速让我头疼。去和弗莱士说吧。}

#{109}{}{It's you, again. The Cougar got nothing more to say.}
{109}{}{又是你。我没什么话和你讲了。}

#{110}{}{The Cougar is watching you, man!}
{110}{}{我在看着你！}

#{111}{}{Nice outfit, you scavenge that yourself?}
{111}{}{衣服不错，你自己搞的？}
