
#
# Talking cows special encounter text
#


#{100}{}{Moo.}
{100}{}{哞。}

#{101}{}{Moo!}
{101}{}{哞！}

#{102}{}{Moo, I say.}
{102}{}{哞。我说，哞。}

#{103}{}{It's a wild Brahmin.}
{103}{}{那是一只野生双头牛。奇怪的，它在紧紧的盯着你，好像它能听懂你说的话。}

#{104}{}{There is nothing natural about these cows. The second head can only be the result of some strange mutation.}
{104}{}{这些牛不是原来就这样的。第二个脑袋显然是辐射变异的结果。}

#{105}{}{Looks pretty normal to you.}
{105}{}{看起来似乎很正常。}



