
#{100}{}{The door is locked. You have never seen a lock quite like this.}
{100}{}{门被锁住了，你以前从没见过这种锁。}

#{101}{}{The door is closed, but it is unlocked.}
{101}{}{门是关着的，但没锁。}

#{102}{}{You try to open the door, but fail. You suddenly realized the door is locked.}
{102}{}{你想开门，但是开不了。你现在才发现这门是锁着的。}

#{103}{}{You fail to pick the lock on the door.}
{103}{}{你开锁失败。}

#{104}{}{You pick the lock on the door.}
{104}{}{你解开了门上的锁。}
