{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a Caravan Driver.}
{100}{}{你看见商队的车夫。}

#{101}{}{Sorry, I don't know you.  If you want a job you need to talk to Rutger.}
{101}{}{抱歉，我不认识你，如果想找工作的话，和罗格尔说去。}

#{102}{}{Don't talk to me about a job, talk to Rutger.}
{102}{}{工作的事不要找我，和罗格尔说去。}

#{103}{}{What, did you spend all your money on drugs? If you keep that up you'll find your new home in old town
# surrounded by skags.}
{103}{}{什么，你把钱都花在毒品上了？如果你再这样，你总有一天会烂在一堆瘾君子里的。}

#{104}{}{You'd better sober up.  Come back when you're ready and able to work.}
{104}{}{你最好还是少嗑药。等你准备好了再回来找工作。}

#{105}{}{Looking for another job?}
{105}{}{找工作？}

#{106}{}{Sure.}
{106}{}{是啊。}

#{107}{}{No, maybe later.}
{107}{}{不，以后再说。}

#{108}{}{Lug.}
{108}{}{啊。}

#{109}{}{Rok!}
{109}{}{吼！}

#{110}{}{Ready to go?  We leave today.}
{110}{}{走吗？我们今天就出发。}

#{111}{}{Yep!}
{111}{}{好的！}

#{112}{}{Nope.}
{112}{}{不了。}

#{113}{}{Hrurra?}
{113}{}{呼？}

#{114}{}{Sorry, we won't deal with you anymore.  Try your luck with another caravan; maybe they'll put up with
# you.}
{114}{}{抱歉，我们不想再和你打交道了。你和其他商队谈谈吧，也许他们会习惯你这种人。}

#{115}{}{Sorry, we're not hiring.}
{115}{}{抱歉，我们人员满了。}

#{116}{}{You've got a lot of nerve showing your face here again.  I think you should leave.}
{116}{}{你还真敢露面啊。赶紧给我走！}

#{117}{}{I said beat it!}
{117}{}{我说了，滚！}

#{118}{}{What do you want?  Hiring you was a disaster.}
{118}{}{你还想干什么？雇你是一种灾难。}

#{119}{}{Please give me another chance!  I had no choice!}
{119}{}{请再给我一次机会！我没有其他选择了！}

#{120}{}{Oh, yeah? I could care less.}
{120}{}{哦？随你的便。}

#{121}{}{Nothing. Bye.}
{121}{}{没事，再见。}

#{122}{}{Kah.}
{122}{}{咔。}

#{123}{}{Moo.}
{123}{}{哞。}

#{124}{}{Look, I don't know what happened out there but we lost the entire caravan!  You shouldn't have come
# back if you couldn't protect it.}
{124}{}{我不知道你们出了什么事，整个商队都完蛋了！你要是没本事保护商队，你就不要再来揽这个活儿！}

#{125}{}{No way, get lost!}
{125}{}{没门！滚！}

#{126}{}{I said get lost!}
{126}{}{我说了，滚！}

#{127}{}{What do you want?}
{127}{}{你想要什么？}

#{128}{}{Ah, shut up and get out of my way!}
{128}{}{啊，闭嘴！给我滚！！}

#{129}{}{I want another job.}
{129}{}{我要工作。}

#{130}{}{Nothing.}
{130}{}{没事。}

#{131}{}{Zug.}
{131}{}{甚？}

#{132}{}{Ug.}
{132}{}{唔。}

#{133}{}{What?  After you abandoned that last job?  You're lucky they survived.}
{133}{}{什么？你上次擅离职守，还想要工作？算你走运，商队没事，要不然我宰了你！}

#{134}{}{I'm lucky?  You're lucky I don't pound your face in!}
{134}{}{我幸运？你才幸运呢，我没有把你的脸砸烂。}

#{135}{}{Hey!  I had places to go and people to see.}
{135}{}{嘿！我当时还有事情要做嘛。}

#{136}{}{I didn't know I wasn't allowed to leave. Everything seemed okay.}
{136}{}{你们也没告诉我不能中途离开啊。这不大家都没事嘛。}

#{137}{}{Talk straight or get out.}
{137}{}{有话就说有屁就放！}

#{138}{}{Skag.}
{138}{}{嗑药的烂货！}

#{139}{}{We don't hire drunks.}
{139}{}{我们不要酒鬼。}

#{140}{}{We don't hire druggies.}
{140}{}{我们不要瘾君子。}

#{141}{}{(You're ignored)}
{141}{}{【他不理你】}

#{142}{}{Come back when you've slept it off.}
{142}{}{睡个觉，清醒了再来。}

#{143}{}{You sicko. Go back to the pens.}
{143}{}{你这个精神病！滚回猪圈去！}

#{144}{}{Seemed okay? You never leave a caravan, not even if it's a mile from its rendezvous. You were
# hired to guard it for the entire trip, otherwise we would have gotten someone else.}
{144}{}{没事吧？你不能离开商队！哪怕是距离集合点只有一里都不行。我们雇你是为了全程保护商队，要不然我们也用不着你了。}

#{145}{}{Well, no one told me I couldn't leave!}
{145}{}{哎，没人说我不能离开那。}

#{146}{}{I'm sorry, it will never happen again.}
{146}{}{对不起了，我保证以后不再犯。}

#{147}{}{Up yours.}
{147}{}{闭嘴。}

#{148}{}{What?  Is this your first caravan?  How did you get hired? This is a very delicate and important job;
# it's to be taken seriously. Lives are at stake, both the caravan and the towns we supply.}
{148}{}{什么？这是你第一次参加商队？你是怎么被挑中的？这是一个很重要也很棘手的工作，你必须时刻认认真真的，不管对我们商队还是要去的城市，生活就是赌命。}

#{149}{}{And you must be so proud of yourself.}
{149}{}{你肯定很自豪了。}

#{150}{}{What?  Do you want a medal or something?}
{150}{}{什么？你还想要个勋章还是什么的？}

#{151}{}{Let me save lives, please! I want to help!}
{151}{}{让我去拯救他们，拜托啦！我想帮忙啊！}

#{152}{}{I hope so!  This is a very delicate and important job; it's to be taken seriously. Lives are at
# stake! The caravans and the towns we supply depend on us!}
{152}{}{但愿如此，这是一个很重要也很棘手的工作，你必须要认认真真的。商队和我们要去的城市可全靠我们。}

#{153}{}{You must be so proud of yourself.}
{153}{}{你肯定很自豪了。}

#{154}{}{What?  Do you want a medal or something?}
{154}{}{什么？你还想要个勋章还是什么的？}

#{155}{}{Let me save lives, please!  I want to help!}
{155}{}{让我去拯救他们，拜托啦！我想帮忙啊！}

#{156}{}{Of course I am.}
{156}{}{当然了。}

#{157}{}{So, can I have another job?}
{157}{}{那么，我还能再要这个工作吗？}

#{158}{}{You're an idiot!}
{158}{}{你是个白痴！}

#{159}{}{I've got to go.  Bye.}
{159}{}{我要走了，再见。}

#{160}{}{Uh, yeah.  This is hard and dirty work! We risk our lives for those in less fortunate places.}
{160}{}{对，这是一件苦差事。我们要为那些穷地方的人冒生命危险。}

#{161}{}{Get a life! }
{161}{}{活得有意义点！}

#{162}{}{Oh?  And what about all the less fortunate people right under your nose?}
{162}{}{哦？那么你眼皮底下这些受苦的人呢？}

#{163}{}{You're right.  Can I have another job or what?}
{163}{}{你说的对，我能不能找这个工作或是其他什么的？}

#{164}{}{What?  I don't know what you're talking about! Oh, you mean the skags?  They don't count.  They choose
# to live that way.}
{164}{}{什么？我不知道你要说什么？你说这些瘾君子？他们不算。他们自己选择那样过活的。}

#{165}{}{I guess you're right.}
{165}{}{我想你是对的。}

#{166}{}{You make me sick.}
{166}{}{你真虚伪。}

#{167}{}{I've got to go.}
{167}{}{我走了。}

#{168}{}{What? What'd I say?}
{168}{}{什么？我说什么来着？}

#{169}{}{Of course I am. I'm a good person at heart . . . most of the time.}
{169}{}{当然，我是一个好人那……大多数时间里。}

#{170}{}{Of course you are.  Can I have another job or what?}
{170}{}{当然没错啊！我能不能找这个工作或是其他什么的？}

#{171}{}{I'm out of here.}
{171}{}{我受不了了。}

#{172}{}{That's the attitude!  To bad I can't give you another job.}
{172}{}{就这态度！我能再给你一份工作？笑话。}

#{173}{}{What? After all that?  Oh come on!  Please can I have another job?}
{173}{}{什么？这么多废话就……别啊，请问我能不能拿到这个工作哇。}

#{174}{}{Well, back to saving the world then.}
{174}{}{好吧，回来拯救世界吧。}

#{175}{}{That's just fine. But don't ever expect to work for us again!}
{175}{}{你能这样想很好，不过我们不能再给你机会了。}

#{176}{}{Oh, please!  It will never happen again!}
{176}{}{拜托！我保证不会再出事的！}

#{177}{}{Like I'd want to!}
{177}{}{好啊！我愿意！}

#{178}{}{Well okay, one more chance.  Our next caravan is leaving }
{178}{}{好吧，再给你一次机会，我们下一趟商队会在这个时间出发：}

#{179}{}{today}
#{180}{}{tomorrow}
#{181}{}{on the}
#{182}{}{8th}
#{183}{}{18th}
#184}{}{28th}

{179}{}{今天}
{180}{}{明天}
{181}{}{在}
{182}{}{8号}
{183}{}{18号}
{184}{}{28号}

#{185}{}{. Let me know when you're ready to leave. It pays the standard 400 scripts.}
{185}{}{，你想出发的时候跟我说，我会付你400块。}

#{186}{}{Sorry, but I already made a bad mistake about giving you a chance the last time you messed up.}
{186}{}{抱歉，我上次已经给了你机会，后来被你搞砸了。我不会再犯这种错误了。}

#{187}{}{Great, which route did you want to take?}
{187}{}{很好，你想去哪个路线？}

#{188}{}{Hi there.  The caravan doesn't leave until tomorrow.  You should come back then if you still want the
# job.}
{188}{}{嗨，商队明天走，你如果还想要这个工作，到时候要来。}

#{189}{}{I don't want the job.}
{189}{}{我不想干了。}

#{190}{}{I'll try to make it.}
{190}{}{我尽力吧。}

#{191}{}{Okay, I'll see you then.}
{191}{}{好，不见不散。}

#{192}{}{Da.}
{192}{}{那。}

#{193}{}{Hi there.  You're early.  Quite early.  The next caravan doesn't leave until the }
{193}{}{嗨，你来早了。太早了。下一趟商队要在这个时间才走：}

{194}{}{8号}
{195}{}{18号}
{196}{}{28号}
#{197}{}{. Come back then if you're still interested.}
{197}{}{。如果你那时候还有兴趣再来。}

#{198}{}{I don't want the job.}
{198}{}{我不干了。}

#{199}{}{I'll try to make it.}
{199}{}{我尽力赶过来吧。}

#{200}{}{Okay. Bye.}
{200}{}{好，再见。}

#{201}{}{Da.}
{201}{}{那。}

#{202}{}{Okay.  It doesn't matter to me.}
{202}{}{好，我没问题。}

#{203}{}{Hell, it doesn't matter to me if you show or not. We have people looking for jobs every day.  If you
# don't show, that's okay.}
{203}{}{你来不来都无所谓，每天来找工作的人很多，你如果不干，没事的。}

#{204}{}{I already told you.  Don't worry about it.  If you can't make it, I can make do.}
{204}{}{我说过了，别担心，你来不了的话，我们也能行。}

{205}{}{钢铁兄弟会}

#{206}{}{Boneyard }
{206}{}{晒骨场}

{207}{}{迦克镇}

#{208}{}{Never mind.  I don't want the job after all.}
{208}{}{算了，我不干了。}

#{209}{}{Great timing, our caravans are leaving today. It pays the standard 400 scripts.  Which caravan route
# did you want to take?}
{209}{}{很准时，我们的车队今天就走。工资是标准的400块。你想跟哪条线路？}

#{210}{}{Great.  Our next caravan is going out on the }
{210}{}{很好，我们的商队将在如下时间出发：}

{211}{}{8号}
{212}{}{18号}
{213}{}{28号}

#{214}{}{.  Come back then and we'll assign you to a caravan.  It pays the standard 400 scripts.}
{214}{}{。到时候来的话，我给你安排商队。报酬是400块。}

#{215}{}{Okay.}
{215}{}{好。}

#{216}{}{Sorry, I can't wait that long.}
{216}{}{对不起，我等不了那么久。}

#{217}{}{Great. I'll get your driver and the rest of the crew.  Be careful out there, it's been a little rough
# lately.}
{217}{}{很好，我给你安排车夫和其他乘员，出门要小心，最近不太平。}

#{218}{}{The crew's ready.  We'll leave right away.}
{218}{}{人员准备完毕。我们出发。}

#{219}{}{All right, it'll just take a few minutes to get the crew together.}
{219}{}{好的。我们要等一会，所有人员集合。}

#{220}{}{All right. We'll leave for the Brotherhood as soon as I get the rest of the crew together.}
{220}{}{很好，等人员都齐了，我们就动身去钢铁兄弟会。}

#{221}{}{Okay, you'll be off to the Brotherhood as soon as I assemble the crew.}
{221}{}{好，等我召集剩下的人，我们就去钢铁兄弟会。}

#{222}{}{Ready to go! Be sure to stay away from the mountains.}
{222}{}{可以出发了！路上离山区远一点。}

#{223}{}{The Boneyard's a rough place -- be careful. Make sure everyone sticks to their shifts.}
{223}{}{晒骨场是个不好处的地方。小心点，所有人都要守好岗位。}

#{224}{}{The crew's almost ready. I heard there was some trouble around the Boneyard recently -- watch your back.}
{224}{}{人员基本准备完毕。我听说最近晒骨场有麻烦，你要小心。}

#{225}{}{Okay, the caravan crew for the Boneyard is ready and waiting.}
{225}{}{好了，前往晒骨场的人员已待命。}

#{226}{}{Junktown is normally a short and easy trip -- you shouldn't have any problems.}
{226}{}{去迦克镇的路比较短，也比较安全，你们应该没什么太大问题。}

#{227}{}{Good, the crew for Junktown's caravan is ready.}
{227}{}{很好，去往迦克镇的商队整装待发。}

#{228}{}{All right.  Junktown's waiting, let's get going.}
{228}{}{好，下一站，迦克镇，出发！}

#{229}{}{Why, hello.  I understand you are looking for a job.  I'm surprised Rutger hired you, but I'm sure he
# has his reasons.  Our caravans leave here three times a month:  on the 8th, 18th and 28th.  There are three
# places we go to on a regular basis: the Brotherhood of Steel, Junktown, and the Boneyard. The pay is
# always 400 scripts, and that's one way.  You can come back with the caravan for another 400 scripts.}
{229}{}{嗨，你好。我知道你在找工作。我很奇怪罗格尔会挑上你，但是我相信他有自己的道理。我们商队每月出行三次，8号，18号和28号。通常的路线是三条：钢铁兄弟会、迦克镇和晒骨场。工资一样，都是400块，单程。你可以保护商队回程，那样又是400块。}

#{230}{}{You've got great timing because they're all heading out today.}
{230}{}{你来的真巧，三条路线都正准备出发。}

#{231}{}{They're all going out tomorrow.}
{231}{}{三条路线都在明天出发。}

#{232}{}{They aren't leaving for }
{232}{}{他们在}

#{233}{}{ days.}
{233}{}{天后出发。}

#{234}{}{Are you interested?}
{234}{}{有兴趣吗？}

#{235}{}{So, do you want the job? }
{235}{}{你想要这个工作吗？}

#{236}{}{They're all heading out today.}
{236}{}{三条路线今天都正准备出发。}

#{237}{}{They're all going out tomorrow.}
{237}{}{三条路线都在明天出发。}

#{238}{}{They aren't leaving for }
{238}{}{他们在}

#{239}{}{ days.}
{239}{}{天后出发。}

#{240}{}{I suppose you want a job.  I might give you one.  Are you interested?}
{240}{}{我猜你在找工作。我可以给你一个。有兴趣吗？}

#{241}{}{Sure.}
{241}{}{好。}

#{242}{}{Nope.}
{242}{}{没。}

#{243}{}{You know where you can stick your caravan.}
{243}{}{你知道商队的事情。}

#{244}{}{I don't know. I'll have to get back to you.}
{244}{}{我不知道，我会回来的。}

#{245}{}{Ug.}
{245}{}{唔。}

#{246}{}{Which route did you want to take?}
{246}{}{你想要哪条线路？}

#{247}{}{Brotherhood of Steel.}
{247}{}{钢铁兄弟会。}

#{248}{}{Boneyard.}
{248}{}{晒骨场。}

#{249}{}{Junktown.}
{249}{}{迦克镇。}

#{250}{}{Sorry, I changed by mind.}
{250}{}{不好意思，我改变主意了。}

#{251}{}{Well, come back on the }
{251}{}{那么，你}

{252}{}{8号}
{253}{}{18号}
{254}{}{28号}
#{255}{}{ and we'll get the crew together.}
{255}{}{回来，我们再给你安排队员。}

#{256}{}{What's your problem?}
{256}{}{你有什么问题？}

#{257}{}{You're the problem, and my fist is the solution. }
{257}{}{你就是我的问题，我会用拳头来解决的这个问题。}

#{258}{}{You'd better watch it.}
{258}{}{你给我小心点！}

#{260}{}{You are.}
{260}{}{就是你。}

#{261}{}{No problem.}
{261}{}{没问题。}

#{262}{}{Yeah, okay.  Come back if you change your mind.}
{262}{}{好，等你想好了再回来吧。}
