{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Hi! Welcome to my previously owned car lot. Which one of these beauties interests you today?}
#{101}{}{You must be joking. These cars are all wrecks.}
#{102}{}{Uh, nothing, thanks.}
#{103}{}{Lug!}
#{104}{}{Oh, I'm sorry, you don't look like you can afford our financing rates.}
#{105}{}{But, sir, these are fine examples of motor vehicles.}
#{106}{}{Ma'am, these are excellent vehicles.}
#{107}{}{They can't be in working condition.}
#{108}{}{Yeah, right. Okay. Bye.}
#{109}{}{These cars have been given a full 100-point service by our dedicated service department.}
#{110}{}{And where is your service department?}
#{111}{}{You are a loon.}
#{112}{}{Goodbye.}
#{113}{}{Right over there, sir. [The dealer points to nothing.]}
#{114}{}{Right over there, ma'am. [The dealer points to nothing.]}
#{115}{}{Where? There's nothing over there.}
#{116}{}{You're crazy.}
#{117}{}{What do you mean? They're working on a newly purchased '56 Corvega. An excellent buy, I might add.}
#{118}{}{Okay, whatever you say.}
#{119}{}{You're just insane.}
#{120}{}{Bye.}
#{121}{}{And we have an excellent warranty. You can bring it back to us for any oil changes, as well. The first one is free. What do you say?}
#{122}{}{Throw in a full tank of gas and you have a deal.}
#{123}{}{You need help.}
#{124}{}{I'm leaving now.}
#{125}{}{I'm sorry, we don't have any petrol. Maybe next time. Goodbye.}
#{126}{}{I'm insulted. I don't have to take that from a customer. Have a good day.}
#{127}{}{I'm on my coffee break, come back later.}
#{128}{}{Go ahead, and take one for a test drive.}
#{129}{}{You should get the rust preventive paint with that.}
#{130}{}{Can I interest you in an auto alarm?}
#{131}{}{Hi! I'm Bob.}

{100}{}{嗨！欢迎来看我的老爷车。这里面有你喜欢的吗？}
{101}{}{你一定是开玩笑。这些车都是坏的。}
{102}{}{呃，只是随便看看，谢谢。}
{103}{}{用力!}
{104}{}{哦，对不起，你看起来不像可以买得起我们的车。}
{105}{}{但是，先生，这些都是非常好的车。}
{106}{}{但是，女士，这些都是非常好的车。}
{107}{}{它们根本无法开动。}
{108}{}{好的，是的，再见。}
{109}{}{我们有专门的部门给这些车提供百分百的售后服务。}
{110}{}{好吧，你们的服务部门在哪？}
{111}{}{你是个笨蛋。}
{112}{}{再见。}
{113}{}{就在这，先生【这商人指着一块空地】}
{114}{}{就在这，女士【这商人指着一块空地】}
{115}{}{哪儿？这里什么都没有。}
{116}{}{你疯了。}
{117}{}{你说什么？你没看到他们正在为一辆新预定的'56科维嘎忙活吗？一笔非常棒的买卖。}
{118}{}{随便你怎么说。}
{119}{}{你真的是疯了。}
{120}{}{再见。}
{121}{}{我们还有非常棒的优惠。你随时可以带车来加油。而且第一次是免费的。你觉得怎么样？}
{122}{}{把油箱装满汽油，然后你会把你的车卖出去的。}
{123}{}{你需要一个医生。}
{124}{}{我走了。}
{125}{}{对不起，我们没有汽油。下次再来吧。再见。}
{126}{}{原谅我的无礼，我不需要它。祝你愉快。}
{127}{}{我去喝杯咖啡，一会儿回来。}
{128}{}{加油，最好能看到你试车。}
{129}{}{我觉得你得给它弄点防锈漆。}
{130}{}{我能让你对这个汽车警报器感兴趣吗？}
{131}{}{嗨，我是鲍勃。}
