{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Watch yourself around the Doc, and I won't have to get medieval on your face.}
#{101}{}{We're closed. Come back later.}
#{102}{}{I gotta see the Doc.}
#{103}{}{OK, will do.}
#{104}{}{It is very important that I see the doctor.}
#{105}{}{Hnnn.}
#{106}{}{Nice weather we're having, huh?}
#{107}{}{That's just too bad. Get out of here, and don't come back until morning. This office isn't open at night.}
#{108}{}{Hold on a second, I gotta check with the Doc.}
#{109}{}{What do you want now?}
#{110}{}{I gotta see the Doc.}
#{111}{}{Is the doctor available?}
#{112}{}{Hnnn!}
#{113}{}{No way. The Doc is sleeping. Come back later.}
#{114}{}{I dunno, why don't you talk to him yourself.}
#{115}{}{Yeah, OK. Get out.}
#{116}{}{Hey, this is private property. You'd better be leaving, now.}
#{117}{}{Eat my dung.}
#{118}{}{If you don't get out of my way, you'll be needing the doctor for personal reasons.}
#{119}{}{Don't you know that women are the weaker sex?}
#{120}{}{Think I'm weak? Watch this then . . .}
#{121}{}{I'll just be leaving.}
#{122}{}{Take your puny threats and run home to mamma. You're talking to a real man here.}
#{123}{}{Think I'm weak? Watch this then . . .}
#{124}{}{I'll just be leaving.}
#{125}{}{Whoa! If you really want to see him, go right ahead.}
#{126}{}{Well, when is the doctor here?}
#{127}{}{The doc sees patients from 8 to 5. Now get outta here.}
#{128}{}{When is the doctor here?}



{100}{}{留意着点附近的医生，我不想看你那张苦瓜脸。}
{101}{}{我们关门了，稍后再来把。}
{102}{}{我须要见医生。}
{103}{}{好把，行。}
{104}{}{我有要紧事，我看医生。}
{105}{}{哼。}
{106}{}{天气不错呀，对吧？}
{107}{}{别太过分，赶紧离开这，明早之前别回来，晚上不办公！}
{108}{}{等等！我必须见医生。}
{109}{}{你想干吗？}
{110}{}{我必须见医生。}
{111}{}{医生有空吗？}
{112}{}{哼！}
{113}{}{绝对不行，医生正在睡觉，稍后再来吧。}
{114}{}{我不知道，你为何不亲自去和他谈谈。}
{115}{}{好的，走开。}
{116}{}{嘿！这是私人财产，你最好马上离开！}
{117}{}{你只配吃我大便！}
{118}{}{你要再不给我离开，我就让你在医院住两天。}
{119}{}{你不认识那个弱弱的女人吗？}
{120}{}{认为我弱？看看这……}
{121}{}{我正好想离开。}
{122}{}{带着你那小小的恐吓滚回家吃奶把。你正在和一个男子汉说话。}
{123}{}{认为我弱？看看这……}
{124}{}{我正要离开。}
{125}{}{嚯！如果你真想见他，一直走就是。}
{126}{}{很好，医生什么时候来？}
{127}{}{医生见患者的时间是早8点到晚5点，现在离开这。}
{128}{}{医生什么时候来？}
