
# {100}{}{You see before you a Holodisk.}
# {101}{}{Pip Boy displays: Downloading data from disk.}
# {102}{}{This seems to have been a disk with some type of entertainment upon it.}
# {103}{}{The disk has been damaged too horribly to allow you to read anything on it.}
# {104}{}{This disk seems to talk about some pass code on another disk.}
# {105}{}{You see a small display appear and show the remnants of some World War II movie.}
# {106}{}{This disk seems empty.}
# {107}{}{You discard this worthless disk.}
{100}{}{你看到一张全息磁盘。}
{101}{}{哔哔小子显示：正在从全息磁盘下载数据。}
{102}{}{这全息磁盘上的数据好像是一些娱乐性的内容。}
{103}{}{这个全息磁盘损坏的太厉害了，没法从上面获取任何数据。}
{104}{}{这个全息磁盘好像上提到另一张全息磁盘的密码。}
{105}{}{你看到一些关于第二次世界大战的影像片断。}
{106}{}{这个全息磁盘是空的。}
{107}{}{你丢弃这个没用的磁盘。}