
# {100}{}{Boy, it sure is hot.}
# {101}{}{I could use a drink.}
# {102}{}{These trips sure are long.}
# {103}{}{I hope we don't run into any raiders.}
# {104}{}{I really need the money from this job.}
# {105}{}{I hate this job.}
{100}{}{好家伙，这真是热啊！}
{101}{}{我应该喝点饮料。}
{102}{}{这旅途真长。}
{103}{}{我希望我们别遇上强盗。}
{104}{}{我真的很需要这份工钱。}
{105}{}{我恨这工作。}