
# {100}{}{Your arrival was timely, friend. Best wishes for a safe journey.}
# {101}{}{We could use your assistance!}
# {102}{}{I am going to kill you!}
# {103}{}{Leave me alone!}
# {104}{}{Protect the caravan!}
{100}{}{朋友，你及时到达了，希望这次旅程一路平安。}
{101}{}{你的帮助对我们很有用！}
{102}{}{我现在就宰了你！}
{103}{}{别打扰我！}
{104}{}{保护商队！}
