{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a Knight.}
{100}{}{你见到了一名骑士。}

#{101}{}{I wonder what the old turbine engines were really like.}
{101}{}{我想知道老式涡轮引擎究竟是什么样子。}

#{102}{}{It would be great if we had a working automobile.}
{102}{}{我们要是有辆能发动的车就好了。}

#{103}{}{Did you know man has been on the moon? Or I think that's what they said.}
{103}{}{你知道吗，人类曾经登上过月球？至少我想他们是这么说的。}

#{104}{}{I can't find the file I need.}
{104}{}{我找不到我需要的文件。}

#{105}{}{I'll be a Paladin someday.}
{105}{}{总有一天我会成为游侠的。}

#{106}{}{Talus is a skilled warrior. I would never want to have to go up against him.}
{106}{}{塔鲁斯是个经验丰富的战士。我可不想和他对着干。}

#{107}{}{Thomas is the best fighter in the Brotherhood. I bet he could best Rhombus.}
{107}{}{托马斯是兄弟会里最好的战士。我敢打赌他能打败隆伯斯。}

#{108}{}{I'd like to get my hands on those raiders. Show them what thieves deserve.}
{108}{}{我想收拾这帮强盗。让他们知道知道小偷应有的下场。}

#{109}{}{That's it . . . what? Oh sorry. I can't talk right now.}
{109}{}{那是什么……什么来着？哦抱歉。我现在不能聊天。}

#{110}{}{I wonder . . . huh? Oh, you made me lose my train of thought.}
{110}{}{我想……呃？喔，你打断我的思路了。}

#{111}{}{I love working on new prototypes.}
{111}{}{我喜欢按照新原型工作。}

#{112}{}{When our supplies are limited, it can really be a challenge to find a way to use what we've got.}
{112}{}{当我们的补给有限时，怎样合理使用资源确实是个挑战。}

#{113}{}{I can't figure out why my last prototype didn't work.}
{113}{}{我不明白为什么我最新的原型无法工作。}

#{114}{}{Sorry, can't talk right now.}
{114}{}{抱歉，现在没法聊天。}

#{115}{}{Vree's over there.}
{115}{}{弗蕾在那里。}

#{116}{}{Now where did I put that file . . .}
{116}{}{我把那文件放到哪儿去了……}

#{117}{}{Where's that schematic?}
{117}{}{图纸在哪儿？}

#{118}{}{Well the computer says it should work; now what did I do wrong?}
{118}{}{好吧，电脑说它能运转的；我到底搞错了什么？}

