
#{100}{}{This locker is locked.}
{100}{}{这个锁柜被锁上了。}
#{101}{}{You unlock the locker.}
{101}{}{你开了锁。}
#{102}{}{You pick the lock on the locker.}
{102}{}{你撬开了锁。}
#{103}{}{You fail to pick the lock on the locker.}
{103}{}{你开锁失败了。}
#{104}{}{You break your lockpicks while trying to unlock the door.}
{104}{}{你开锁的时候弄坏了开锁器。}
#{105}{}{This lock seems too complicated for you.}
{105}{}{这个锁对你来说太复杂。}