{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

# Beth is female. She speaks with a normal accent.  She is a friendly person
# who is mostly interested in selling equipment and information.
{100}{}{你看见了贝斯，武器店的店主。}
{101}{}{你好，需要点什么？}
{102}{}{我能跟你打听点儿事儿吗？}
{103}{}{可以再问你几个问题吗？}
{104}{}{我想买点儿东西。}
{105}{}{我想卖点儿东西。}
{106}{}{有什么挣钱的营生？}
{107}{}{没了。再见。}
{108}{}{呜?}
{109}{}{关于失踪的商队的流言是怎么回事儿？}
# the Deathclaw is male
{110}{}{你了解死亡爪吗？}
{111}{}{再给我讲讲死亡爪好吗？}
# Decker is male
{112}{}{能跟我说说德克吗？}
{113}{}{各个不同的商会你有什么要告诉我的？}
{114}{}{有没有听到什么流言？}
{115}{}{多谢，就这些了。再见。}
{116}{}{嗯，没关系。}
# Jain is a female religious figure
{117}{}{嗯，我没工夫闲聊，不过我听说德克的死多少和简恩的被刺杀有关系。}
# The Maltese Falcon is a bar
{118}{}{嗯，一般我不在人背后说闲话，但是我知道有人说过他们看见在凶手之前有三个裹着袍子的巨大身影进了马耳他猎鹰酒吧。}
# the Children of the Cathedral is an organization - religious
{119}{}{嗯，一般我不在人背后说闲话，有人杀了简恩，大教堂教徒的高级祭司。对那些人我没什么兴趣，我也不知道她为什么会招此杀身之祸。}
# The Brotherhood of Steel is an organization - religious
{121}{}{嗯，一般我不在人背后说闲话，但是我的一个在商会的朋友告诉我，他看见在西北的钢铁兄弟会附近的沙漠地带看到一伙变种人出没。}
{122}{}{嗯，一般我不在人背后说闲话，但是大教堂教徒一直在打听你的行踪。我得小心。他们一伙很怪异。}
{123}{}{嗯，我没工夫闲聊，不过我听说德克的死多少和简恩的被刺杀有关系。}
{124}{}{另外，我知道有人说过他们看见在凶手之前有三个裹着袍子的巨大身影进了马耳他猎鹰。}
{125}{}{还有，有人杀了简恩，大教堂教徒的高级祭司。对那些人我没什么兴趣，我也不知道她为什么会招此杀身之祸。}
{126}{}{还有一件事儿。我的一个在商会的朋友告诉我，他看见在西北的钢铁兄弟会附近的沙漠地带看到一伙变种人出没。}
{127}{}{还有一件事儿。大教堂教徒一直在打听你的行踪。我得小心。他们一伙很怪异。}
{128}{}{没了？}
{129}{}{多谢，我能再问个问题吗？}
{130}{}{好的，谢谢。}
{131}{}{抱歉，那是什么？}
# Klug and Ruk are a stupid person saying something incomprehensible
{132}{}{嗯？}
{133}{}{恩!}
{134}{}{抱歉，我不懂。你感觉好点儿的时候再回来，好吗？}
# The Merchant Market is a location
{135}{}{我现在不缺人手，不过商人中心有海报招聘，你可以到那里碰碰运气。}
{136}{}{好的，多谢。}
{137}{}{没有，至少没什么好消息。别打扰我干活了。【她冲你眨眨眼】。还有别的事儿吗？}
{138}{}{是的。}
{139}{}{不。}
{140}{}{还有什么要我帮忙的？}
{141}{}{别傻了，你当然可以。}
{142}{}{啊，当然，我很乐意帮忙。你想知道什么？}
{143}{}{就这样。很高兴与你聊天，祝你愉快。}
{144}{}{就这么多了。你还想谈谈什么别的？}
{145}{}{是的。}
{146}{}{不。}
{147}{}{有空来看看。可别忘了这里。}
{148}{}{你绝对不要招惹那里的人，他可把我吓坏了。他现在“拥有”马耳他猎鹰。}
{149}{}{你为什么那么说？他“拥有”马耳他猎鹰。}
{150}{}{为什么他把你吓坏了？}
{151}{}{抱歉，我只是想起在他之前拥有那里的我的朋友的下场。德克非常想要，但是我的朋友不愿意卖。几天后我的朋友死在旧城区一条僻静的小巷里。}
{152}{}{为什么你觉得是德克干的？}
{153}{}{唉，我的朋友应该有自知之明不去招惹德克。}
{154}{}{抱歉，我得走了。}
{155}{}{我的朋友行事怪异。他几乎寸步不离旧城区。他死于麦格农手枪；旧城区没人买得起那东西。另外，他头部中了一枪，背后两枪。这看起来像是抢劫吗？我的朋友只是想能自己主宰生活。}
{156}{}{不错，我喜欢这样干。干掉一个家伙后，曝尸在他最厌恶的地方。}
{157}{}{掌控自己的生活？}
{158}{}{听到这些我很抱歉。}
{159}{}{噢，好的。}
{160}{}{你可能没法了解这一点，我们大部分人都盼望着有一天我们拥有我们自己，而不是属于商人或者高利贷者。}
{161}{}{哦，多谢。}
{162}{}{难道你就不能闭嘴？！}
{163}{}{我从来没听过这么愚蠢的事情！}
{164}{}{还有什么要我帮忙的？}
{165}{}{那么，对不起。是你问的。}
{166}{}{他是哈勃城最危险的人物；大部分人都认为这里是他而不是商人或者警察做主。如果不小心碰到他，你得当心了。}
{167}{}{那并不意味着他可以乱杀无辜。}
{168}{}{你让我恶心，请走开。我想他会很乐意与你合伙的。}
{169}{}{嗯，商队主要有三个，纯水商队，深红商队，远行商队。他们还掌控着市议会。你想打听些什么？}
{170}{}{纯水商队。}
{172}{}{深红商队。}
{173}{}{远行商队。}
{174}{}{市议会。}
{175}{}{就这样。谢谢你的帮助。}
{176}{}{事实上，没关系。}
{177}{}{他们控制着所有的水。这些贪婪的人，我不想为他们工作。他们给的薪水和对应的工作一样糟糕。}
{178}{}{他们一直控制着所有的水？}
{179}{}{是不是他们和商队的失踪有关？}
{180}{}{多谢，关于商队还有一个问题……}
{181}{}{谢了，再见。}
{182}{}{你还想打听些什么？}
{183}{}{不是的。据我所知，不久之前一伙商人控制了水塔，宣称他们是水商，人们必须从他们那里购买水。商人之间的混战持续了许多年，直到一个叫格林，对，就是贾斯丁的祖父，他设法使他们达成了协议才停止了这场争战。}
{184}{}{什么样的协议？}
{185}{}{该死！抱歉我问了。}
{186}{}{多谢，关于商人还有一个问题……}
{187}{}{多谢，拜拜。}
{188}{}{他创立了市议会并限制水的价格。但是我认为水的价格是不会被限制住的—哦，抱歉。我的意思是它们的价格取决于它们的老板。}
{189}{}{太好了。我本来没打算听到这么多的信息，但是我还是要说声谢谢。}
{190}{}{多谢，关于商人还有一个问题……}
{191}{}{多谢，拜拜。}
{192}{}{抱歉我有点儿走神。你还想打听些什么？}
{193}{}{深红商队是一伙疯狂的家伙。他们无所顾忌什么都干得出来。与此相比他们才失踪那么点儿商队真是令人惊异。}
{194}{}{他们也有商队失踪？}
{195}{}{怎么危险？}
{196}{}{多谢，关于商人还有一个问题……}
{197}{}{多谢，再见。}
{198}{}{他们必须得通过一个劫掠者出没的地方。因此他们斥巨资来扩充人手。报酬的确很丰厚，问题是有没有命来享受，对吧？}
{199}{}{他们也有商队失踪？}
{200}{}{多谢，关于商人还有一个问题……}
{201}{}{多谢，再见。}
{202}{}{事实上所有商会都有些商队失踪。我看远行商队运气不好。}
{203}{}{怎么危险？}
{204}{}{多谢，关于商人还有一个问题……}
{205}{}{多谢，再见。}
{206}{}{远行商队的报酬不错而且他们的工作也不算危险。布奇经营这里，他人不错。他们很宽松让我按自己喜欢的方式来经营；我喜欢和他们共事。另外如果你效力于布奇的话在这里买任何东西都有折扣。}
{207}{}{我并不这么认为。我猜可能是死亡爪或者钢铁兄弟会。}
{208}{}{为什么你不认为是纯水商队？}
{209}{}{死亡爪到底是什么玩意儿？}
{210}{}{你能再跟我说说死亡爪吗？}
{211}{}{兄弟会是？}
{212}{}{为什么你不认为是钢铁兄弟会？}
{213}{}{多谢，我们再回过来聊聊商队。}
{214}{}{好的，我得走了。}
{215}{}{有些人认为和纯水商队有关，可我不这么想。我认为是那些该死的死亡爪，或者是那边的钢铁兄弟会的人。}
{216}{}{嗯，我曾以为商队是因此失踪的，但现在看来不像。它虽然仍然在那边。有太多传闻说它并不在那附近。}
{217}{}{我想那就是商队失踪的原因。也有可能是钢铁兄弟会；那伙人行事诡异。有些人认为是纯水商队，他们错了。}
{218}{}{当然。}
{219}{}{因为，我跟每个人都这么说，他们也有几只商队失踪了。和远行商队没什么一样的，但他们也受到了影响。}
{220}{}{他们可能在撒谎或者这本是他们计划中的一部分以骗取信任。}
{221}{}{为什么对于远行商队遇到的更多？}
{222}{}{关于失踪的商队还有一个问题……}
{223}{}{多谢，我们把话题再回到商会上来。}
{224}{}{你简直满嘴喷粪！}
{225}{}{多谢，但我得走了。}
{226}{}{打断一下！你如此匆匆的作出结论，是否你害怕真相？}
{227}{}{总共六人，每个商会团体派出两名代表。所有决议都至少需要4票才能通过。他们从来就没有就什么事情达成过一致。}
{228}{}{这个观点不错，但我还是很怀疑。虽然多年来他们之间一直互相算计，但以他们的行事作风来看应该不会是他们干的。他们可不愿耗费巨大的资金来消灭商队。另外所有的商队都有重兵护卫。你可能认为有人生还。他们不愿花费人力物力去搜寻。再怎么也应该有一个生还者的。}
{229}{}{没错，但是为什么发生在远行商队的要比其他商会多得多？}
{230}{}{关于失踪的商队还有一个问题……}
{231}{}{多谢，我们再谈谈商会。}
{232}{}{多谢，我得走了。}
{233}{}{走霉运？我不清楚，也许他们商队的路线和其它商会不一样。也可能是因为他们的商队不像深红商队那样重兵护卫，呃……也许是因为他们的货物比纯水商队的贵重。鬼才知道。这三个商会看起来没有什么明显的差异。}
{234}{}{纯水商队可能在撒谎或者这就是他们计划的一部分，骗取你们的信任。}
{235}{}{关于失踪的商队还有一个问题……}
{236}{}{多谢，我们再谈谈商会。}
{237}{}{你就不能歇会儿？！}
{238}{}{多谢，我得走了。}
{239}{}{算了！你想走就走吧。你要是不想知道答案，早先你就不该问的。}
{240}{}{死亡爪是大战争之后废土上出现的最为邪恶的生物。有人说它是大战争中产生的强大的鬼魂，出没于废土。它并不是鬼魂，而是和你我一样真实。它身高20英尺，牙齿有你胳膊那么大。当整个世界卷入战火时，有人用某种方法造出来了这些魔鬼。}
{241}{}{呃，抱歉我这么问。}
{242}{}{你这个变态！我现在就杀了你。}
{243}{}{关于死亡爪你还知道什么？}
{244}{}{喔！你知道哪儿能找到它们吗？}
{245}{}{嗯，我知道旧城区有个叫哈罗德的老变种人见过它们。他是“唯一一个”碰到它们还活下来的人。}
{246}{}{唯一一个碰到它们还能活下来的人？}
{247}{}{是的，没错，我是死亡爪的爸爸。}
{248}{}{是的，没错，我还是死亡爪的妈妈呢。}
{249}{}{关于失踪的商队还有一个问题……}
{250}{}{多谢，我们再谈谈商会。}
{251}{}{我会去看看的。回见。}
{252}{}{旧城区那边的斯莱匹叔叔有时候会谈起这个。不过他纯粹是一个疯狂的老糊涂蛋。}
{253}{}{关于失踪的商队还有一个问题……}
{254}{}{多谢，我们再谈谈商会。}
{255}{}{我会去看看的。再见。}
{256}{}{你会看到的！}
{257}{}{对，很让人惊奇不是吗。位置是西南边某处。旧城区有一个叫哈罗德的曾在它们的巢穴里见过它们。他是个不错的人。}
{258}{}{关于失踪的商队还有一个问题……}
{259}{}{多谢，我们再谈谈商会。}
{260}{}{多谢。我会去看看的。再见。}
{261}{}{钢铁兄弟会都是一些崇尚技术的疯子；他们在西北边。他们无恶不作，包括使用人来祭祀。}
{262}{}{太夸张了吧！你听谁说的？}
{263}{}{关于失踪的商队还有一个问题……}
{264}{}{多谢，我们再谈谈商会。}
{265}{}{太恐怖了，谢谢你的忠告。再见。}
{266}{}{好，嗯。 我记不得了，但无论是谁，应该是真的……我的意思是，有可能是真的。反正你得小心点儿。}
{267}{}{关于失踪的商队还有一个问题……}
{268}{}{那么，我们再谈谈商会。}
{269}{}{你真是个白痴！}
{270}{}{时候不早了，我得走了！再会。}
{271}{}{什么？你不知道？【悄悄地说】我听说他们无恶不作，包括使用人来祭祀！}
{272}{}{没错，是这样的。有什么问题吗？}
{273}{}{作为兄弟会的“一员”，我能向你“保证”，“那样”的事情不会继续了。}
{274}{}{真的？我到过那儿，他们看起来有些怪异但是也没有那么邪恶。}
{275}{}{真的？我搞不明白。}
{276}{}{你像是不知道。你很明显就是和他们一伙的，看你那身金属服。你们都是一群恶心的家伙。}
{277}{}{我不知道你想表明什么，但我向你保证兄弟会没有什么“恶心”的事情。}
{278}{}{是的，我们不是所有吗？}
{279}{}{我不知道。}
{280}{}{先生，抱歉。请收起你的武器。}
{281}{}{女士，抱歉。请收起你的武器。}
{282}{}{抱歉，如果你不收起武器，我们没什么好谈的。这儿是商店不是竞技场。}
{283}{}{呃……那么，好吧……嗯，你……我……你还有什么事情？}
{284}{}{俗话说知人知面不知心，你得小心与人处世。还有什么事情？}
# Not believing the player for a moment, then getting nervous
{285}{}{你是……？我是说。我没那意思……嗯……天气真不错，是吗？那，还有什么我可以效劳的？}
{286}{}{关于失踪的商队还有一个问题……}
{287}{}{多谢，我们再谈谈商会。}
{288}{}{不，没什么了。再见。}
{289}{}{当然，无论你说什么。还有什么我可以效劳的？}
{290}{}{太好了！看看我这儿有什么！}
{291}{}{我这儿有最好的货色，你还犹豫什么？}
{292}{}{真高兴听到你这么说！你需要什么？}
{293}{}{咱们专心谈生意吧。}
{294}{}{我只对钱感兴趣。}
{295}{}{我最喜欢的这种主顾了。}
{296}{}{你想买东西？看来我低估你了。}
{297}{}{对，没错。你给贝斯办差，所以有15%的折扣。}
{298}{}{我仍然给你15%的折扣，因为我喜欢你这个人。}
{299}{}{抱歉，你现在不享有折扣了。}
{300}{}{给我看看你的货。}
{301}{}{有什么好货色?}
{302}{}{好吧，看看。}
{303}{}{当然。}
{304}{}{今天有些什么？}
{305}{}{太棒了！我总是要耗费更多的商品。}
{306}{}{很高兴能看看你有什么。}
{307}{}{可别想偷我的东西。}
{308}{}{如果有什么好东西的话，我可能会买点儿。}
{309}{}{可别浪费我的时间。}
{310}{}{希望这次你有我想要的东西。}
{311}{}{很高兴我们又见面了。今天天气不错，有什么要我帮忙的？}
{312}{}{嘿！很高兴我们又见面了。今天有什么要我帮忙的？}
{313}{}{我多希望我能休假一天。出去玩玩。}
{314}{}{怎么又回来了？我们有什么做的不够好的吗？}
{315}{}{这么快又回来了？}
{316}{}{刚走就想我了？}
{317}{}{需要的东西都准备好了。}
{318}{}{很久没见了，今天来点儿什么？}
{319}{}{有阵儿没见了，希望你一切还好。}
{320}{}{你还健在啊。我正在忙，我今天能为你作什么？}
{321}{}{你好。有一个多星期没来了。常来逛逛，“你”是我最喜欢的主顾。}
{322}{}{是吗？}
{323}{}{什么？}
{324}{}{买点儿东西还是有什么别的事情？}
{325}{}{这是我的店铺，你最好规矩点儿。}
{326}{}{什么！}
{327}{}{又是你？}
{328}{}{时间就是金钱，什么？}
{329}{}{需要点儿什么吗？}
{330}{}{听见了吗？他死了，可把我乐坏了。这是这个城市有史以来最大快人心的事情。}
{331}{}{我告诉过你。他已经死了！别再提他了，他的名字总让我想起那些糟糕的日子。}
{332}{}{哦，是！}
{333}{}{对，我觉得他是罪有应得。}
# Sid works for Beth. Sid is male.
{334}{}{你干的？真的？我爱死你了！【贝斯看了希德一眼】从来没有想过这样，聪明的家伙……为了表示我的感激，拿去吧…… 【贝斯给你六个治疗针。】菲薄之礼，聊表谢意！}
{335}{}{你干的？真的？你太棒了！你无法明白听到他的死讯我有多么高兴。这是给你的…… 【贝斯给你六个治疗针。】菲薄之礼，聊表谢意！}
{336}{}{抱歉没有你想要的东西。}
{337}{}{没有中意的？看来我得进点儿好货。}
{338}{}{很抱歉没有你中意的，但是我不得不靠这些赚点儿钱。}
{339}{}{也没有想卖的？那算了。}
{340}{}{抱歉没你想要的。祝你愉快。}
{341}{}{下次再说吧，再见。}
{342}{}{希望下次能有你需要的。}
{343}{}{别浪费我的时间。}
{344}{}{如果你没打算买东西的话，请离开。}
{345}{}{如果你没打算买东西的话，请别打扰我。}
{346}{}{如果你没什么想卖的，请离开。}
{347}{}{如果你没打算卖东西的话，请别打扰我。}
{348}{}{请离开。}
{349}{}{我知道你又是浪费我的时间。}
{350}{}{我没猜错，你就是个穷光蛋。}
{351}{}{真的谢谢你，我今天得早点儿回家。}
{352}{}{我这什么都没有了！}
{353}{}{希望你能搬得走！}
{354}{}{谢谢，我希望我能卖掉所有东西！}
{356}{}{卖得很好，谢谢你！}
{357}{}{这些我用得上。多谢！}
{358}{}{我希望我拥有整个房间的东西！}
{359}{}{十分感谢！祝你愉快！}
{360}{}{谢谢光顾，以后请常来。}
{361}{}{这里随时欢迎你。}
{362}{}{多谢，祝你愉快。}
{363}{}{再见！谢了！}
{364}{}{就买些弹药？让我失望。那么，下次的话，你得多买点儿！}
{365}{}{囤积弹药？主意不错。永远都不会嫌多。}
{366}{}{只要这些，对吗？再见！}
{367}{}{很好，我没有认为你会来买任何的东西。}
{368}{}{多谢惠顾，你还算不错。}
{369}{}{谢谢你的货。}
{370}{}{祝你愉快。}
{371}{}{再见。}
{372}{}{谢谢。}
{373}{}{多谢你的光顾，祝你愉快。}
{374}{}{我听到了！}
{375}{}{不是开玩笑。}
{376}{}{希德！住手！}
{377}{}{你要是还不住嘴，我会给你点儿惊喜。}
{378}{}{我听说过了！你被解雇了！}
{379}{}{别理他，我一向都是。}
{380}{}{哦，你确实应当高兴的！}
{381}{}{正是你希望的。}
{382}{}{住嘴。}
{383}{}{嘿。别动，希德。}
{384}{}{我不认为这样很聪明。}
{385}{}{如果你不离开我的客户我会给你点颜色看看！}
{386}{}{请原谅我这不招人爱的护卫。}
{387}{}{你真招人烦！}
{388}{}{希德！}
{389}{}{宝贝，你从哪找出这么烦人的名字？}
{390}{}{【贝斯叹气】我}
{391}{}{应当把他关起来的。不是吗？}
{392}{}{我认为他是忌妒！}
{393}{}{希德！对顾客放尊重些！}
{394}{}{你认识的人当中还有谁有关于死亡爪的信息？}
{395}{}{再见。}
{396}{}{多谢。}
{397}{}{哦。}
{398}{}{在城里我要注意点儿什么？}
{399}{}{噢，没错。你应当尽可能的离马耳他猎鹰酒吧远点儿。德克和他的胖走狗可不是好玩儿的。你要是不当心的话，会被他们生吞的。同样最好和罗仑佐的借贷公司也保持一定距离。}
