{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Billy.}
{100}{}{你看见比利。}

#{101}{}{Hey!  Leave my stuff alone!}
{101}{}{嗨！别动我的东西！}

#{102}{}{Hi there.}
{102}{}{嗨。}

#{103}{}{Hi, what are you doing?}
{103}{}{嗨，你在干什么？}

#{104}{}{Can I have a brahmin?}
{104}{}{能卖我只双头牛吗？}

#{105}{}{Hi.  Uh, bye.}
{105}{}{嗨。呃，再见。}

#{106}{}{Arg!}
{106}{}{啊！}

#{107}{}{Ta.}
{107}{}{哈。}

#{108}{}{Why would you want a brahmin?  Do you have a caravan?  Well, it doesn抰 matter. I only take
# care of them.  Dan is the one who owns them. He won抰 sell them though.}
{108}{}{你为什么想要双头牛？你有商队吗？算了，跟我没关系。我只是负责照料这些牛。他们的主人是丹。但是他不会卖的。}

#{109}{}{Why?}
{109}{}{为什么？}

#{110}{}{I was just kidding.}
{110}{}{我只是在开玩笑。}

#{111}{}{Cuz of all the missing caravans. He doesn抰 have any to spare, the use caravans most of them.
# The others are sold to for food. Well I'd better stop talking, Dan will get mad if he sees me talking
# to a stranger.}
{111}{}{因为那些商队失踪了，他现在没有多少富余的了，商队用掉了大部分。剩下的是准备作为食物出售的。嗯，不能再和你聊了，要是丹看见我和陌生人说话可是要生气的。}

#{112}{}{Oh, okay.}
{112}{}{喔，好的。}

#{113}{}{Nothing?I mean, I抦 taking care of the brahmin.}
{113}{}{没什么？我的意思是，我是看双头牛的。}

#{114}{}{What抯 the spear for? Are they dangerous? }
{114}{}{为什么用矛？它们很危险吗？}

#{115}{}{What抯 a brahmin?}
{115}{}{双头牛是什么？}

#{116}{}{What抯 a brahmin? You must be joking.  Why they're one of the major food sources and forms of
# transportation around here. They haul the caravans.  Dan says this is a really important job, but
# it sucks.}
{116}{}{双头牛是什么？你真会开玩笑。它们是主要食物来源和运输工具。是商队的脚力。丹说这是一个非常重要的工作。真他妈操蛋。}

#{117}{}{Oh, I knew that! }
{117}{}{哦，我知道了！}

#{118}{}{Dan抯 right.  You are doing a great job.}
{118}{}{丹是对的。你正在做一个很棒的工作。}

#{119}{}{Yea, it looks that way.  Have fun.}
{119}{}{是啊，看起来是那样。好好享受。}

#{120}{}{Hey, you抮e one of those skags aren抰 you?}
{120}{}{嘿，你跟那些毒贩子一伙的，不是吗？}

#{121}{}{Really?  You think so?  Jeee, thanks.}
{121}{}{真的？你这样认为？唉，多谢了。}

#{122}{}{You抮e not from around here are you. I抣l give you one tip.  Don抰 get caught stealing!}
{122}{}{你不是从附近来的对吧。让我给你个忠告，别想偷东西！}

#{123}{}{Sure, thanks.}
{123}{}{当然,谢谢。}

#{124}{}{I wouldn抰 dream of stealing.  Stealing is wrong.}
{124}{}{我从来不想偷东西。偷东西不好。}

#{125}{}{Yea, I think I抦 starting to agree with you.  This job isn抰 so bad really.  It makes me feel
# good for some reason.  Well, I抳e got to go before I get in trouble.}
{125}{}{是啊，我想我开始同意你。这个工作还没那么糟，多少感觉还不错。好吧，在惹上麻烦之前我得走了。}

#{126}{}{Please don抰 hurt me or my Brahmin.}
{126}{}{请不要伤害我和我的双头牛。}

#{127}{}{Don抰 hurt me!}
{127}{}{别伤害我！}

#{128}{}{Stop it!}
{128}{}{住手！}

#{129}{}{Please leave me alone.}
{129}{}{请让我独自待会儿。}

#{130}{}{You抮e scaring me.}
{130}{}{你吓坏我了。}

#{131}{}{Hey what are you trying to do?  I don抰 have anything you抎 want.}
{131}{}{嘿，你想干嘛？我这儿没什么你想要的东西。}

#{132}{}{Stop that!}
{132}{}{住手！}

#{133}{}{Dangerous?  No, not really.  They call give you a really nasty bite, but they抮e pretty cool.
# They fart and burp a lot.  I don抰 know why.}
{133}{}{危险？不，不是这样的。它们的叫声会让你厌恶，但它们很酷。他们老是放屁打嗝，我不知道为什么。}

#{134}{}{So what抯 the spear for?}
{134}{}{那矛是干什么用的？}

#{135}{}{Okay thanks.}
{135}{}{好的，谢谢。}

#{136}{}{Oh, they can be awfully stubborn when I want them to do something.  I just gently stick them
# to get them to move around?plus I don抰 want to get to close, they sometimes kick.}
{136}{}{哦，这些牛有时候很不听话。我要是轻轻的打它们能管用吗？再加上它们有时候会踢人，我可不想太靠近。}

#{137}{}{Please don抰 talk to me, Dan is going to yell at me again.  He really gets piss?I mean?mad,
# when I抦 not paying attention to what I抦 doing.}
{137}{}{别跟我说话了，不然丹又要骂我了。他看到我不专心干活儿的时候那表情真的像喝了尿似的，我是说，疯了。}

#{138}{}{He抯 just trying to help.  Work hard and I抦 sure he抣l be nicer.}
{138}{}{他只是想帮忙。好好干的话我想他肯定会好些。}

#{139}{}{Here kid, take 50 bucks and get away from this jerk. }
{139}{}{这里孩子，拿着这50块钱，离开这个性情古怪的人。}

#{140}{}{Okay.}
{140}{}{好的。}

#{141}{}{Aaaaaarg!}
{141}{}{啊啊啊！}

#{142}{}{Rhu?}
{142}{}{嗯？}

#{143}{}{Please don抰, I抦 already in enough trouble.}
{143}{}{请别这样，我最近已经够烦的了。}

#{144}{}{I 'am' working hard!}
{144}{}{我正在努力工作！}

#{145}{}{I抦 sorry, I didn抰 mean that. He抯 just trying to help you. }
{145}{}{对不起，我不是那个意思。他只是想帮助你。}

#{146}{}{No you aren抰! You lazy little brat!}
{146}{}{难道不是吗！你这个臭小子！}

#{147}{}{Okay.}
{147}{}{好的。}

#{148}{}{Yea, maybe you right?.  actually he seems pretty cool, but I wish he wouldn抰 yell at me so much.}
{148}{}{是啊，也许你是对的。实际上他似乎相当直爽，不过我希望他不要老是对我大喊大叫。}

#{149}{}{Yea, right.}
{149}{}{是啊，没错。}

#{150}{}{Up yours, you old fart!}
{150}{}{随你便，老玻璃！}

#{151}{}{Up yours, you old hag!}
{151}{}{随你便，老巫婆！}

#{152}{}{WOW! I can live on this for the rest of my life!  Thanks a lot, mister!}
{152}{}{哇！我可以一辈子住在这里！非常感谢，先生！}

#{153}{}{WOW! I can live on this for the rest of my life. Thanks a lot, ma抋m!}
{153}{}{哇！我可以一辈子住在这里！非常感谢，女士！}

#{154}{}{WOW!  Thanks?Well??You抮e just trying to get me in trouble again!}
{154}{}{哇！多谢？只是？？你让我陷入更大的麻烦了！}

#{155}{}{Please don抰 talk to me, Dan is really mad.}
{155}{}{请不要和我说话了，丹真的会发疯的。}

#{156}{}{Don抰 worry.  I had a talk with him, he抣l try to be nicer to you.}
{156}{}{不用担心。我跟他谈过了，他会对你好些的。}

#{157}{}{And he should be!  You抮e a terrible kid!}
{157}{}{他会的！你这个孩子！}

#{158}{}{Wac.}
{158}{}{噢。}

#{159}{}{Hi!}
{159}{}{嗨！}

#{160}{}{Those girls over there sure are dumb.}
{160}{}{那些在那边的女孩肯定都是闷瓜。}

#{161}{}{Hi again.}
{161}{}{嗨又见面了。}

#{162}{}{Brahmin are cool.}
{162}{}{双头牛很酷。}

#{163}{}{Dan抯 taking me to the Falcon if I do a good job.}
{163}{}{丹说如果我干的好，就带我去“猎鹰”。}

#{164}{}{Dan抯 going to take me on a caravan some day!}
{164}{}{丹打算某一天让我去商队！}

#{165}{}{I抦 going to be an adventurer when I grow up.}
{165}{}{我长大后要成为一个冒险家。}

#{166}{}{Really? Oh, okay.  I hope you didn抰 hurt him.  He抯 really not so bad.  He just yells a lot.}
{166}{}{真的？哦，好吧。我希望你没有伤害他。他真的没有那么坏，只不过是嗓门儿大点。}

#{167}{}{Hello again.}
{167}{}{又见面了。}

#{168}{}{What is it you do again? }
{168}{}{你又干什么？}

#{169}{}{Can I have a brahmin?}
{169}{}{能卖我只双头牛吗？}

#{170}{}{Just stopping by to say how things where going. Bye.}
{170}{}{路过只是顺便看看。再见。}

#{171}{}{Arg!}
{171}{}{啊！}

#{172}{}{Ta.}
{172}{}{哈。}

#{173}{}{I better get back to work.}
{173}{}{我最好回去工作了。}

#{174}{}{Those girls over there sure are dumb.}
{174}{}{那些在那里的女孩肯定都是闷瓜。}

#{175}{}{Hi again.}
{175}{}{嗨又见面了。}

#{176}{}{I抦 going to be an adventurer when I grow up.}
{176}{}{我长大后要成为一个冒险家。}

#{177}{}{Brahmin sure do shi?uh, poop a lot.}
{177}{}{双头牛会这么想了？一派胡言。}

#{178}{}{I can抰 talk right now.}
{178}{}{我现在不能聊天。}

#{179}{}{I don抰 want to get in trouble.}
{179}{}{我不想招惹麻烦。}
