{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see an Elder of the Brotherhood.}
{100}{}{你看见一位钢铁兄弟会的元老。}

#{101}{}{Greetings Initiate. I need to speak with you. (He motions for you to come closer.)}
{101}{}{你好新兵。我需要与你谈谈。【他靠近你。】}

#{102}{}{About what?}
{102}{}{关于什么？}

#{103}{}{I don't have time right now.}
{103}{}{我现在没有时间。}

#{104}{}{Err?}
{104}{}{呃？}

#{105}{}{There is an urgent matter I need you to help me
# with. It's Maxson. We are pretty sure he's gone off the
# deep end. He keeps babbling about an army massing to the
# north.}
{105}{}{我需要你帮助我解决一个紧急的问题。我们确信马克松犯了大错。他老是胡扯什么要把军队在北方集结。}

#{106}{}{ I'm not willing to send our troops up there into
# possibly radiated areas, unless I've got absolute proof
# that this "army" exists.}
{106}{}{我不愿意派遣我们的军队进入可能有幅射的区域，除非我已经得到绝对的证据表明那有支“军队”存在。}

#{107}{}{ I need someone who isn't a friend of the old man.
# Someone I can get an honest report from. Are you willing to check
# the northern region?}
{107}{}{我需要一个不是那老人朋友的人。我可以从那人得到一份诚实的报告。你愿意去北方的区域看看吗？}

#{108}{}{I'll do it.}
{108}{}{我去做。}

#{109}{}{I can't do it right now. I've got other things I need to deal with.}
{109}{}{我现在不行。还有其他事情需要我去处理。}

#{110}{}{I've already seen a base to the north run by an army of mutants.}
{110}{}{我已经在北方看见被变种人军队控制的基地了。}

#{111}{}{Good. First go talk to Maxson if you haven't already. Report back
# to me when you've checked the northern territory. After that, we'll decide
# what to do with Maxson.}
{111}{}{好的。如果你还没见过马克松，先去和他谈谈。当你侦查完北面后回来向我汇报。然后呢，我再和马克松确定下一步计划。}

#{112}{}{Wish me luck.}
{112}{}{祝我好运。}

#{113}{}{Have you explored the entire northern territory?}
{113}{}{你探察了全部北方地区？}

#{114}{}{Yes.}
{114}{}{是的。}

#{115}{}{No.}
{115}{}{不。}

#{116}{}{And what do you have to report?}
{116}{}{你有什么要汇报？}

#{117}{}{I've found a base guarded by heavily armed mutants. It looks pretty bad.}
{117}{}{我发现了一个由全副武装变种人守卫的基地。情况看起来相当不好。}

#{118}{}{I didn't think so. You weren't gone for very long. Now, get back out there and
# don't come back until you have a FULL report.}
{118}{}{我不这么认为。你没去很长时间。现在，回到那边去并且不要这么快回来，直到你有一份完整的报告。}

#{119}{}{Yes, sir.}
{119}{}{是的，先生。}

#{120}{}{I will inform the Elders. We will wait for Maxson's word on what to do.
# Go inform him on what you've found. Thanks for your help, Initiate.}
{120}{}{我将通知元老们。我们会等马克松作出决定该干什么。去告诉他你的发现。感谢你的帮助，新兵。}

#{121}{}{You're welcome.}
{121}{}{不用客气。}

#{122}{}{Then you will make time to hear me out.}
{122}{}{你会有时间听完我的话。}

#{123}{}{You've got my attention.}
{123}{}{你得到我的注意。}

#{124}{}{You can go to hell old man.}
{124}{}{去死吧老东西。}

#{125}{}{Forget it. I've got more important things to do.}
{125}{}{忘了它。我有更重要的事要做。}

#{126}{}{I understand. If you do travel up into that area and find anything, please, let me know.}
{126}{}{我了解。如果你进入那个地区并且发现了什么，拜托，告诉我。}

#{127}{}{If I find anything that resembles an army up north, I will let you know.}
{127}{}{如果我发现在北方有类似军队的任何事，我将告诉你。}

#{128}{}{Good work with the mutants. We already heard that you destroyed their
# production facility. Thanks for taking care of that problem for us.}
{128}{}{干的好。我们已经听到了你破坏他们制造设备的事。谢谢为我们解决了那个问题。}

#{129}{}{No problem.}
{129}{}{没问题。}

#{130}{}{Err? What kind of response is Err? Leave! Now!}
{130}{}{呃？算什么意思？快滚！}

#{131}{}{If it was up to me, you would be out of here.}
{131}{}{如果依我的意思，你最好离开。}

#{132}{}{I have nothing to say to you.}
{132}{}{我对你无话可说。}

#{133}{}{You should learn some respect.}
{133}{}{你应该学习一些尊敬。}

#{134}{}{The meeting will come to order. All Elders are present and have
# agreed to hear out the claims of Brother }
{134}{}{会议即将举行。全体元老在场并且同意听取}

#{135}{}{. We shall determine what actions will be taken. Brother }
{135}{}{兄弟的陈述。我们将确定采取什么行动。}

#{136}{}{, tell us what you have seen to the north.}
{136}{}{兄弟，告诉我们你在北方看到了什么。}

#{137}{}{During my explorations, I found a military installation being used
# by mutants. It is heavily guarded and patrolled regularly.}
{137}{}{在我的探险期间，我发现了变种人使用的一座军事设施。它被严密地保护着。}

#{138}{}{Norfa?}
{138}{}{北方？}

#{139}{}{And what did these mutants look like?}
{139}{}{这些变种人看起来像什么？}

#{140}{}{They are large humanoids. Their muscle mass is well beyond what a
# regular human could ever gain. There appear to be several of them guarding the
# gate in organized troops.}
{140}{}{他们是巨大的类人动物。他们的肌肉块远远超过一般的人类。那里他们有人守在大门口，像是有严密组织的军队。}

#{141}{}{They were big, greenish, and carrying weapons.}
{141}{}{他们是巨大的，绿色的, 并且带着武器。}

#{142}{}{As you may know, our Head Scribe, Vree, has done an autopsy on a
# creature very similar to what you have just described. Do you believe these
# are the same?}
{142}{}{正如您所知，我们的首席研究员弗蕾，对和你刚刚描述的非常相似的生物做过一个解剖。你相信他们是相同的？}

#{143}{}{Yes. The description of the creature is nearly identical.}
{143}{}{是的。生物的描述是几乎相同的。}

#{144}{}{What threat do you assume these "mutants" pose?}
{144}{}{你认为这些“变种人”会有什么威胁？}

#{145}{}{Just as the Brotherhood has been gearing up for battle, this "mutant
# army" has been preparing for something big.}
{145}{}{正如钢铁兄弟会已经为战争作好准备，这些“变种人军队”正准备有些大动作。}

#{146}{}{Frankly, your report has not shown us any proof that they are a
# threat to us. What proof can you give that they have hostile intentions.}
{146}{}{坦白说，你的报告未能证明他们对我们的威胁。你有什么证据能够表明他们怀有敌意。}

#{147}{}{They have invaded Necropolis. They won't stop there. }
{147}{}{他们侵略了大墓地。他们不会停留在那里。}

#{148}{}{They are gathering an army. A heavily armed army. They certainly aren't
# going to just parade around. They intend to use it.}
{148}{}{他们正在集结军队。一支全副武装的军队。他们不是恰好在附近行军。他们是想要进攻。}

#{149}{}{So, by these actions they are taking, it is feasable that they will eventually
# come here?}
{149}{}{那么，根据他们当前行动所显示，他们最终可能会来这里？}

#{150}{}{It is possible that they are already on their way here. The Brotherhood is
# the only real opposition they could have.}
{150}{}{他们可能已经在来这里的途中了。钢铁兄弟会是唯一能够对抗他们的人。}

#{151}{}{I don't believe that shows hostility. They could simply be protecting themselves
# from attack. Even we have to deal with the occasional attack.}
{151}{}{我不相信那表示敌意。他们可能只是简单的保护他们自己免受攻击。哪怕是我们也必须应对偶然的袭击。}

#{152}{}{If they attack, it will be NOTHING like the occasional attack you get from
# the raiders. This will be a slaughter.}
{152}{}{如果他们攻击，那可不会是以前那种强盗的骚扰。这将会是一场屠杀。}

#{153}{}{Since they are coming out of that old military installation, I would imagine
# that they would have weapons comparable to your own.}
{153}{}{因为他们从那个老军事基地出来，我可以想象他们的武器不比你们的差。}

#{154}{}{What do you suggest? A preemptive strike at their military base?}
{154}{}{你建议什么？先去袭击他们的军事基地？}

#{155}{}{Yes. I don't want them to know we are coming though.  A small team would
# stand a better chance of getting into their perimeter without being detected. }
{155}{}{是的。我不想让他们知道我们的行动。一个小规模的队伍有利于安全的潜入他们的地界。}

#{156}{}{That will only take care of one part of the problem. They're being led by a
# group coming out of the Boneyard Cathedral.}
{156}{}{这只能说明一部分问题。他们被晒骨场大教堂的另一支小队领导。}

#{157}{}{So be it. You shall have three Paladins of my choosing to meet you at the Military
# Base to help you get inside. Elders, thank you for your time. Best of luck to you Initiate.}
{157}{}{好吧。你会在军事基地和我为你挑选的三名骑士汇合，他们能帮你进入基地。元老，非常感谢你们。祝好运。}

#{158}{}{If they are being led by a group out of the Boneyard Cathdral, then chances are
# they have a small army down there as well. }
{158}{}{如果他们被晒骨场的大教堂领导，那么有可能他们也在那里驻扎了一小队人马。}

#{159}{}{If we take them out in the north, then it leaves our south side vulnerable.
# I can only spare a few men on this endeavor.}
{159}{}{如果我们从北方带他们出去，那我们的南边会很容易受到攻击。我只能尽量在这留一些人。}

#{160}{}{Give me a few Paladins to take out their base to the north.}
{160}{}{给我几名骑士去攻取他们的北方基地。}

#{161}{}{Give me a few Paladins to take out their base to the south.}
{161}{}{给我几名骑士去攻取他们的南方基地。}

#{162}{}{So be it. You shall have two Paladins of my choosing to meet you at the Boneyard
# Cathedral. Elders, thank you for your time. Best of luck to you Initiate.}
{162}{}{好吧。你将在晒骨场的大教堂和我为你挑选的两名骑士汇合，他们能帮助你进入。元老，非常感谢你们。祝好运。}

#{163}{}{So be it. You shall have three Paladins of my choosing to meet you at the Military
# Base to help you get inside. Elders, thank you for your time. Best of luck to you Initiate.}
{163}{}{好吧。你将在军事基地和我为你挑选的三名骑士汇合，他们能帮你进入基地。元老，非常感谢你们。祝好运。}

#{164}{}{Obviously we made a mistake. Elders, I am sorry for wasting your time. Would someone
# please remove this mental abomination?}
{164}{}{元老，显然我们犯了一个错误。有人能弥补这个过失吗？}

#{165}{}{I am too busy planning a defensive strategy.}
{165}{}{我正在忙于计划一个防御战略。}

#{166}{}{You gain }
{166}{}{因为你得到钢铁兄弟会的帮助，你获得了}

#{167}{}{ experience points for convincing the Brotherhood to help.}
{167}{}{点经验值。}
