{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

# {100}{}{You see Smitty.}
# {101}{}{You wanna talk after what you've pulled? Screw you!}
# {102}{}{The boss said get lost, so get lost!}
# {103}{}{We don't talk to no outsiders!}
# {104}{}{Hi yourself. Go blow smoke somewhere else.}
{100}{}{你看到施密蒂。}
{101}{}{你得了便宜还卖乖？孙子！}
{102}{}{老板让你滚，所以你快点滚吧！}
{103}{}{我们不会和陌生人说什么的。}
{104}{}{嗨你的头！滚一边凉快去！}