
#{101}{}{The caravan traders didn't have a chance. They're all dead.}
{101}{}{那些商队的成员全都死了，无一幸免。}

#{102}{}{It looks like the mutants were heavily armed. The caravan traders
# didn't have a chance against this kind of firepower.}
{102}{}{看起来那些变种人装备精良。商队的成员根本没有机会和这种程度的火力对抗。}

#{103}{}{They're dead.}
{103}{}{他们都死了。}

#{104}{}{You're pretty sure it's a dead person.}
{104}{}{你可以肯定这是一具尸体。}

#{105}{}{Through all the mutated flesh and muscle one of them looks familiar.
# It's one of the scouts that was sent out by the Vault that never returned...}
{105}{}{在一堆变种人的尸骨和肌肉组织中有一具看起来似乎很熟悉。它属于被避难所派出去但从未返回的侦察员之一……}

#{106}{}{Through all the mutated flesh and muscle you somehow recognize one of
# the mutants to be Sean, one of the scouts sent out by your Vault a few months
# before you left.}
{106}{}{在一堆变种人的尸骨和碎肉中，不知何故你认出了其中一具尸体是肖恩，在你之前几个月被派出避难所派的侦察员。}

#{107}{}{All the mutants are dead, but one looks strangely familiar, but you
# can't place the 'face'.}
{107}{}{所有的变种人都死了，其中一具尸体看起来不可思议的熟悉，但你却无法将它和任何记忆中的“面孔”联系起来。}

#{108}{}{Dead mutants.} 
{108}{}{死掉的变种人。}
