{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Jennifer.}
{100}{}{你看见詹妮佛。}

#{101}{}{You see a Paladin.}
{101}{}{你看见一名游侠。}

#{102}{}{Excuse me, Brother. You should put away your weapon whenever
# you are in the Brotherhood. We are a friendly order, but as
# you know, times are rough.}
{102}{}{抱歉，一旦你走进了兄弟会，你要把你的武器收好。我们是个友好的组织，但是你也知道，现在的时局不太平。}

#{103}{}{Some members of the Brotherhood might be offended if a
# stranger . . . I mean, a new Initiate . . . approaches them
# with a weapon.}
{103}{}{如果一个陌生人……呃，我是说新兵……带着武器靠近某些兄弟会成员，他们会发火的。}

#{104}{}{Good day, Initiate. How may I help you?}
{104}{}{你好，新兵，我能帮你什么呢？}

#{105}{}{Hello, Sister, it's good to see there are women of rank in
# this organization. I didn't know what to expect with a name like
# the Brotherhood.}
{105}{}{你好啊，姐妹。很高兴看到我们女同胞也进入了兄弟会。我都不知道以后兄弟会这个名字是不是要改改了。}

#{106}{}{Hey there, legs. You are looking mighty fine. What time should
# I pick you up?}
{106}{}{嗨，甜妞，你看起来不错，什么时候我带你耍？}

#{107}{}{Oooooga!}
{107}{}{噢噢哦噢噢哦！}

#{108}{}{Could you tell me where I might find our High Elder?}
{108}{}{你知道我在哪里可以找到最高元老吗？}

#{109}{}{Who's in charge of this hole?}
{109}{}{谁是这个破洞的管事？}

#{110}{}{Where's this High Elder guy?}
{110}{}{最高元老在哪里？}

#{111}{}{Gruk!}
{111}{}{咕噜！}

#{112}{}{Maxson, the High Elder, can be found on the Fourth Floor.
# If you take the other elevator down to level four, he should
# be either in the Council Room or the Elders's rooms.}
{112}{}{最高元老马克松在第四层。你可以坐另外那部电梯下去。他应该在会议室或者元老室。}

#{113}{}{You can ask one of the guards on that level; they should know
# where he is at the moment.}
{113}{}{你可以问问那层的守卫，他们应该知道他的下落。}

#{114}{}{Thank you.}
{114}{}{谢谢。}

#{115}{}{Where can I get some better weapons?}
{115}{}{我到哪里拿到更好的武器？}

#{116}{}{You should talk to Talus. He might be able to help you, or
# at least tell you who to talk to.}
{116}{}{你应该和塔鲁斯说说。他也许能帮你，或者至少他会告诉你去和谁说。}

#{117}{}{During the day, Talus is normally supervising in the training hall.
# Do you know where that is?}
{117}{}{白天的时候，塔鲁斯一般会在训练室督导，你知道训练室怎么走吧？}

#{118}{}{Yes, I do. Thank you.}
{118}{}{知道，多谢了。}

#{119}{}{No.}
{119}{}{不知道。}

#{120}{}{Of course I do!}
{120}{}{我当然知道！}

#{121}{}{The training hall is right around the corner. Just go down this
# corridor, make a left, go through the door at the end of
# the corridor and it will be through the door on your right.}
{121}{}{走廊拐过去就是训练室。顺着这条走廊走，左转，一直走到底，进门往右便是了。}

#{122}{}{You have been extremely helpful. Thank you very much.
# I hope we can talk again soon. Good day.}
{122}{}{你说的太清楚了！谢谢谢谢！我待会再来和你聊，再见。}

#{123}{}{Training hall? Do you think I could get some training there?
# I am a member of the Brotherhood now, right?}
{123}{}{训练室？我可以在那里得到训练吗？我现在已经是兄弟会成员了啊，对吧？}

#{124}{}{Thank you for your help, Sister. It's good to see there are
# women of rank in this organization. I didn't know what to
# expect with a name like the Brotherhood.}
{124}{}{谢谢你，姐妹。很高兴看到我们女同胞也进入了兄弟会。我都不知道以后兄弟会这个名字是不是要改改了。}

#{125}{}{Thanks, Sugar. You know, you're looking mighty fine. What
# do you say you and me check out each other's 'equipment'
# later? What time do you get off?}
{125}{}{多谢甜心。你看起来很不错啊。要不我们找机会互相检查一下“装备”？你什么时候有空啊？}

#{126}{}{Oh, that place. Okay, bye.}
{126}{}{啊，那里，好，再见。}

#{127}{}{Excuse me? Is there something wrong?}
{127}{}{对不起，你有什么毛病吗？}

#{128}{}{Muk lug?}
{128}{}{穆穆？}

#{129}{}{I'm sorry, I don't think I can help you. You should go see the
# doctor. She's on the second level.}
{129}{}{对不起，我帮不上你的忙，你应该去看看医生，她在第二层。}

#{130}{}{Of course there are. Two of our five Elders are women, our master
# scribe is a woman, and we have many other women in all the
# different ranks.}
{130}{}{没错，五大元老里有两人是女的，我们的首席研究员弗蕾也是女的，各个职位上都有我们女性。}

#{131}{}{The women of the Brotherhood are also called Brothers. We don't call
# the women Sisters. This is the Brotherhood of Steel, after all,
# not the Brother and Sisterhood of Steel.}
{131}{}{兄弟会的女性也要称呼为兄弟，我们不会姐姐妹妹的乱叫。这里毕竟是钢铁兄弟会，不是钢铁兄弟姊妹会什么的。}

#{132}{}{Don't you find it peculiar that it is called the Brotherhood,
# implying that its members consist solely of men?}
{132}{}{你不觉得叫钢铁兄弟会很特别吗？搞的好像这里只有男人似的。}

#{133}{}{But why is it called the Brotherhood, then?}
{133}{}{那么为什么要叫做兄弟会呢？}

#{134}{}{Well, it just seemed strange.}
{134}{}{就是有点怪嘛。}

#{135}{}{I do not know. That has been our name all of my life. I'm sure
# there is a reason for it.}
{135}{}{我也不知道，我出生以来他们一直是叫这个名字，这肯定是有原由的。}

#{136}{}{I guess you're right.}
{136}{}{有道理。}

#{137}{}{Well, it still seems a little strange to me.}
{137}{}{我还是觉得这个名字怪怪的。}

#{138}{}{That is strange. I've never really put much thought into it.
# We've been the Brotherhood of Steel all of my life. Our
# ancestors must have had a reason for naming it so.}
{138}{}{是很怪，但我从来没怎么想过。我出生以来他们一直是叫这个名字，前人起这个名字肯定是有原因的。}

#{139}{}{But that doesn't mean things can't change.}
{139}{}{这不代表以后不会改。}

#{140}{}{Yeah, you're probably right.}
{140}{}{嗯，你说的对。}

#{141}{}{So, is there anything else I can help you with?}
{141}{}{那么我还能帮你什么？}

#{142}{}{Yes, where can I find the High Elder?}
{142}{}{我想找最高元老。}

#{143}{}{Where can I get better weapons?}
{143}{}{我想要更好的武器。}

#{144}{}{No, that's it. Bye.}
{144}{}{没事了，再见。}

#{145}{}{No, we're very strict when it comes to tradition. I don't think
# it could ever be changed. It doesn't bother me at all to be
# addressed as a Brother. That is curious, though.}
{145}{}{不会的，我们严格遵循传统，名字应该不会改变的。叫我兄弟我其实也无所谓了，虽然有点怪。}

#{146}{}{I think I'll have a talk with Vree. She might be able to give
# some insight as to why our ancestors decided to call us the
# Brotherhood of Steel.}
{146}{}{我应该和弗蕾聊聊去，她应该知道为什么前辈们要起这样一个名字。}

#{147}{}{Who's Vree? One of the Elders?}
{147}{}{谁是弗蕾？她是元老？}

#{148}{}{Vree's the Master Scribe. She is the one you should talk to
# if you have any technical questions, but don't disturb her
# during her meditations at night.}
{148}{}{她是我们的首席研究员，如果你有技术问题，就应该去问她，但是不要在她冥想的时候去打搅她。}

#{149}{}{She almost always stays in her room, which is also occupied
# by the mainframe on the third floor.}
{149}{}{她永远都呆在自己的房间里，就在第三层的中央。}

#{150}{}{Hole? How dare you talk like that about the Brotherhood.
# You are a member of our order now, and should be proud
# to be a member of the Brotherhood of Steel.}
{150}{}{破洞？你怎么这么说钢铁兄弟会？你是一名兄弟会成员了，你要对自己的组织怀有敬意！}

#{151}{}{Proud? Why? You're all just a bunch of robotic hop-heads, hiding
# from the real world. There's nothing to be proud of there.}
{151}{}{敬意？为什么？你们就是一群机械化偏执狂，只会逃避世界。我对这里没什么敬意。}

#{152}{}{I'm sorry. I get a little carried away with myself
# sometimes.}
{152}{}{对不起，我有时候说话挺没谱的。}

#{153}{}{Yeah, right.}
{153}{}{啊，对。}

#{154}{}{Well, I guess we all do sometimes.}
{154}{}{人都有说漏嘴的时候吧。}

#{155}{}{So who is in charge of this place?}
{155}{}{那谁是这个地方的主管？}

#{156}{}{Yeah. Well, I've got to go.}
{156}{}{你说的对，我走了。}

#{157}{}{Maxson, the High Elder. He's on the fourth floor.}
{157}{}{高级元老马克松，在第四层。}

#{158}{}{}
{158}{}{}

#{159}{}{}
{159}{}{}

#{160}{}{}
{160}{}{}

#{161}{}{}
{161}{}{}

#{162}{}{}
{162}{}{}

#{163}{}{Well, you are cute . . . but I don't think so. I don't think
# it would be a good idea to get involved with an outsider,
# anyways. You are cute, though, and somewhat attractive. }
{163}{}{你是很帅……但是我不会和你那什么的。我想我不应该和一个外面来的人纠缠不清的。不过，你的确很帅，很有吸引力。}

#{164}{}{I don't know if it's because you're an outsider or because
# of your extreme . . . lack of tact? So, 'honey', is there
# anything else I can do for you?}
{164}{}{这个……我不知道是因为你是外来的，还是因为你太过……那个……直率了。那么，“甜心”，我还能为你做什么呢？}

#{165}{}{Yeah, uh, I guess. Uh, who's in charge around here?}
{165}{}{啊，对。谁是这里的主管？}

#{166}{}{Uh, okay . . . um. How about some weapons then? Where can
# I get my hands on some of those?}
{166}{}{哦，好吧……这里有什么好武器吗？我怎么才能拿到？}

#{167}{}{Hmmph!}
{167}{}{呼呼！}

#{168}{}{No.}
{168}{}{没了。}

#{169}{}{That's . . . pretty funny. You are joking, I hope? Actually . . .
# don't answer that. I don't think I want to know.}
{169}{}{真是……有趣，你在开玩笑吧，是吧？实际上……不要这么说。我也不想知道了。}

#{170}{}{Yeah, REAL funny. Almost as much as your face!}
{170}{}{太有趣了，和你的脸蛋一样有趣！}

#{171}{}{Thanks a lot. That's exactly what I needed to hear right now.}
{171}{}{多谢，我就想知道这些了。}

#{172}{}{I'm out of here.}
{172}{}{我走了。}

#{173}{}{I'm sorry. It's just that you outsiders have such a strange
# way of talking to people sometimes. Is there anything I can
# help you with?}
{173}{}{对不起，你们外面来的和人说话都是这样怪怪的。我还能帮你什么？}

#{174}{}{Well, I guess I should talk to this High Elder person.
# Where is he at?}
{174}{}{好，我就去见见这个高级元老。他在哪里？}

#{175}{}{I would like to get some better weapons. Who do I talk
# to about that?}
{175}{}{我想要更好的武器，应该问谁要？}

#{176}{}{No.}
{176}{}{没事。}

#{177}{}{Are you for real? I haven't heard such a pitiful line
# in all my life!}
{177}{}{你来真的？我这辈子没听过这么无赖的话！}

#{178}{}{Yeah? Well, I don't get out much. Okay?}
{178}{}{哦？我的忍耐是有限的，明白？}

#{179}{}{Get out of my face, you walking garbage can!}
{179}{}{滚开！你这个垃圾。}

#{180}{}{Pfft!}
{180}{}{呸！}

#{181}{}{Well, yes, you are a member of the Brotherhood, but the Elders
# have put a hold on all training of new Initiates.}
{181}{}{没错，你是新成员了。但元老对于新兵训练有名额控制。}

#{182}{}{Why?}
{182}{}{为什么？}

#{183}{}{Oh, that's just GREAT! Why the hell did I join this stupid
# group? Where's the door?!}
{183}{}{我拷，这太妙了！那我为什么还要加入这个愚蠢的组织？大门在哪里？！}

#{184}{}{There are rumors about some kind of army. I think the Elders
# want to concentrate their resources on the ones that are already
# far enough along in their training to make a difference if we
# do have a big battle on our hands.}
{184}{}{听说外面有邪恶的大军。元老们想用把那些原来就有基础的战士集中训练，让他们能再上个台阶，如果有恶仗要打就能派上用场了。}

#{185}{}{We strongly believe that training a few fighters extremely
# well is better than giving mediocre training to a bunch of
# fighters. Saving lives is one of our primary objectives.}
{185}{}{兵贵精而不贵多。主要就是为了减少伤亡。}

#{186}{}{You could probably get quite a bit out of the training just
# by watching. Brother Thomas is the best trainer we have ever had
# at the Brotherhood.}
{186}{}{你可以旁听，也能学的不少。托马斯兄弟是我们这里最好的训练官。}

#{187}{}{Well, I'm to be working on the outside of the Brotherhood, right?
# It's a very hostile world out there and I'll be putting my life
# on the line every minute I'm out there. Don't you think I should
# be given training if I want or need it, or do you only 'say'
# it is your primary objective to 'save' lives?}
{187}{}{我要在兄弟会外面执行任务的，对吧？外面很危险啊，每时每刻我都是脑袋别在裤腰带上干活。你难道不觉得我有理由在我需要的时候接受训练吗，这难道符合你们减少伤亡的初衷？}

#{188}{}{Thank you for the suggestion, I'll take a look.}
{188}{}{多谢你的建议，我会去看看的。}

#{189}{}{You're all a bunch of fools.}
{189}{}{你们都是白痴！}

#{190}{}{Can you tell me where Maxson is?}
{190}{}{那马克松在哪里？}

#{191}{}{Well, I'm only repeating what I was told. If you talk to Thomas
# or Talus they might be able to make an exception.}
{191}{}{我也是转述我听到的话，你可以和托马斯或者塔鲁斯聊聊，也许你可以被特许训练。}

#{192}{}{Okay, thanks.}
{192}{}{好，多谢。}

#{193}{}{They'd better. I've jumped through enough hoops for you guys.}
{193}{}{他们最好答应我，我这阵子也算是居功至伟了。}

#{194}{}{So, can you tell me where Maxson is?}
{194}{}{那么，你告诉我在哪里能找到马克松？}

#{195}{}{Oh, my darling. When are we going to marry?}
{195}{}{哦，亲爱的，我们啥时候成亲哇？}

#{196}{}{You're looking so handsome, as always.}
{196}{}{你总是那么漂亮，总是。}

#{197}{}{Give me a kiss.}
{197}{}{来，给我个吻吧。}

#{198}{}{I've missed you so much.}
{198}{}{我好好好好想你哦。}

#{199}{}{I'll wait up for you.}
{199}{}{我会一直一直一直等你的。}

#{200}{}{I've been thinking about you all day.}
{200}{}{我成天脑袋里就是你的倩影在晃来晃去的。}

#{201}{}{You're so cute when you look at me like that.}
{201}{}{你看我的样子太楚楚动人了。}

#{202}{}{Don't scare me like that. I thought I'd never see you again.}
{202}{}{别吓我，我还以为不会在见到你了呢。}

#{203}{}{You didn't come by last night.}
{203}{}{你昨天晚上没来找我。}

#{204}{}{How long has it been since I've last seen you? It seems
# like an eternity.}
{204}{}{我上次见到你是什么时候？感觉似乎几个世纪了呢。}

#{205}{}{I've missed you ever so much.}
{205}{}{我都想死你了。}

#{206}{}{Come to bed, honey.}
{206}{}{上床去，亲爱的。}

#{207}{}{We can get married in the morning.}
{207}{}{我们可以明天上午去结婚。}

#{208}{}{I think we should have about five kids.}
{208}{}{我想我们会有5个孩子。}

#{209}{}{Where do you want to go for our honeymoon? I hear
# the Children of the Cathedral have a beautiful place.}
{209}{}{蜜月你想去哪里？听说大教堂教徒那里很漂亮。}

#{210}{}{My parents are still waiting to meet you.}
{210}{}{我爸妈还等着见你呢。}

#{211}{}{Why hello again. I hope things are well with you.
# I hope you've talked to Vree.}
{211}{}{又见面了，一切都还好吧，和弗蕾说过话了？}

#{212}{}{Hello, Brother }
{212}{}{你好，}

#{213}{}{.}
{213}{}{。}

#{214}{}{Be careful if you go to the north. Our scouts never returned.}
{214}{}{你去北方一定要小心，我们的探子都有去无回的。}

#{215}{}{Brother }
{215}{}{嗨，}

#{216}{}{, it's good to see you again.}
{216}{}{，又看到你真好。}

#{217}{}{Have you talked to Rhombus? He's the Head Knight. He's just
# right over there in that room.}
{217}{}{你和隆伯斯说过话了？他是骑士的领袖，他就在那边那个房间。}

#{218}{}{I don't have time to talk. I'm busy.}
{218}{}{我没时间说话，我很忙。}

#{219}{}{Sorry, I'm not in the mood to talk to rude people.}
{219}{}{对不起，我不想和粗鲁的人说话。}

#{220}{}{Don't bother me.}
{220}{}{别烦我。}

#{221}{}{What? Can't you go bother someone else?}
{221}{}{什么？你就不能去烦烦别人啊？}

#{222}{}{Go away.}
{222}{}{走开。}

#{223}{}{I don't want to talk to you.}
{223}{}{我不想和你说话。}

#{224}{}{Initiate, get back to your studies.}
{224}{}{新兵，回去学习。}

#{225}{}{No time to talk, Initiate.}
{225}{}{没时间和你说话，新兵。}

#{226}{}{Come over here, you hunk!}
{226}{}{来，大个子！}

#{227}{}{Darling, over here!}
{227}{}{亲爱的，来这里！}

#{228}{}{ I've missed you.}
{228}{}{我想你。}

#{229}{}{I've got the nursery ready, darling.}
{229}{}{我找到托儿所了，亲爱的。}

#{230}{}{Hi, honey.}
{230}{}{嗨，亲亲。}

#{231}{}{I see you.}
{231}{}{再见哦。}

#{232}{}{You've got to meet my parents.}
{232}{}{你应该去见见我爸妈。}

#{233}{}{Yoo hoo!}
{233}{}{哟呼！}

#{234}{}{Come here, my little snookums.}
{234}{}{来这里，我的小甜心。}

#{235}{}{Are you teasing me?}
{235}{}{你在挑逗我？}

#{236}{}{You're playing hard to get, aren't you?}
{236}{}{你在故作淑女？}

#{237}{}{Over here, sweaty!}
{237}{}{来这里，甜心！}

#{238}{}{Hi honey!}
{238}{}{嗨，亲爱的！}

#{239}{}{There you are. I was starting to worry.}
{239}{}{你终于来了，我都开始担心了。}

#{240}{}{Come here and give me a kiss, handsome.}
{240}{}{来，给我一个吻，甜甜。}

#{241}{}{Come on in, darling.}
{241}{}{快来，亲爱的。}
