{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Jeremiah, a messenger for the Children.}
{100}{}{你看见耶利米，大教堂教徒的传令官。}

#{101}{}{You see a Child. He looks pensive.}
{101}{}{你看见一名教徒，他似乎在沉思。}

#{102}{}{Excuse me, brother. You startled me. How may I serve the Master?}
{102}{}{对不起，教友，你吓着我了。你有什么要我帮忙的？}

#{103}{}{Quip!}
{103}{}{哈！}

#{104}{}{What are you doing?}
{104}{}{你是做什么的？}

#{105}{}{Ah, yes, a super mutant in training. I will return to my tasks.}
{105}{}{一个超级变种人正在受训，我要回到自己的岗位。}

#{106}{}{If you do not know, it is none of your concern. If you are inquiring
# about something you should not know, then I will have to report you to our
# supervisors. You should know better.}
{106}{}{如果你什么都不知道，那你也没必要关心。如果你打听你不应该知道的事情，那我可就要向上级汇报了。你最好放明白点。}

#{107}{}{I am a person of high importance.}
{107}{}{我是一个很重要的人物。}

#{108}{}{I'm sorry to have bothered you.}
{108}{}{我很抱歉打扰你。}

#{109}{}{I am new here.}
{109}{}{我是新来的。}

#{110}{}{Who the hell are you to be asking me questions?! You're lucky I don't
# report you to the holy flame!!}
{110}{}{你是谁，怎么敢问我问题？！你应该庆幸我没有向圣火汇报你！}

#{111}{}{Transferring the reports, of course.}
{111}{}{当然，我要递送报告。}

#{112}{}{Reports of what? If I make ask.}
{112}{}{报告什么？我可以问问吗？}

#{113}{}{And a mighty fine job you're doing.}
{113}{}{你的工作干得不错。}

#{114}{}{That is all. Thank you.}
{114}{}{没事，多谢。}

#{115}{}{Very well, then. Peace be with you.}
{115}{}{很好，祝你平安。}

#{116}{}{I apologize. How may I be of service?}
{116}{}{对不起，您有何贵干？}

#{117}{}{What is it you are doing?}
{117}{}{你是干什么的？}

#{118}{}{You can start by answering my question.}
{118}{}{你可以开始回答我的问题了。}

#{119}{}{You can die!}
{119}{}{你可以死了！}

#{120}{}{Guards!!!}
{120}{}{卫兵！！！}

#{121}{}{It is obvious you do not belong here. Who are you?}
{121}{}{你显然不属于这里，你是谁？}

#{122}{}{I am actually a Vault Dweller and would like to speak to the Master.}
{122}{}{我是避难所的居民，我要和主教谈话。}

#{123}{}{Um... Dorpheus... hmm... Morpheus sent me.}
{123}{}{多非斯……不对，……是墨菲斯让我来的。}

#{124}{}{I am Loki. An initiate from the south.}
{124}{}{我是洛基，从南方来的新学员。}

#{125}{}{No, I don't belong here. But I know where this bullet belongs... in
# your head.}
{125}{}{没错，我不属于这里，但是我知道这颗子弹属于哪里……你脑袋！}

#{126}{}{I transfer the human purity reports for the surrounding areas. But
# you should know this. 【looking suspicious】 Who are you?}
{126}{}{我负责递送周边地区人类基因纯度的报告。你应该知道的。【可疑地看着你】你是谁？}

#{127}{}{I was sent here by Morpheus with a message for the Master.}
{127}{}{我是墨菲斯派来给主教送信的。}

#{128}{}{It is none of your business who I am... just answer my questions!}
{128}{}{我是谁不管你的事……回答我的问题！}

#{129}{}{You are not to know who I am, it is the wish of the Master.}
{129}{}{你不应该知道我是谁，这是主教的意志。}

#{130}{}{You dare question who I am? Fool, I should strike you down where you
# stand.}
{130}{}{你胆敢问我是谁？笨蛋！我应该把你原地砸扁。}

#{131}{}{That's rather odd... I've never heard of you.}
{131}{}{奇怪啊……我怎么从来没听说过你。}

#{132}{}{I was sent here by Morpheus with a message for the Master.}
{132}{}{我是墨菲斯派来给主教送信的。}

#{133}{}{I am of the High Order. Only the Master and Morpheus know of me in
# order to ensure my safety on the outside. But I have been called back by
# order of the Master.}
{133}{}{我是高阶间谍。只有主教和墨菲斯知道我，这也是为了保护我在外面时候的安全，我收到命令回来见主教。}

#{134}{}{Please forgive me. I apologize for questioning you. Please carry on
# about your business, and if I can be of any service let me know.}
{134}{}{对不起对不起，我道歉，我不该问您问题的。您请便吧，如有差遣，在下定当犬马之劳。}

#{135}{}{I do not know who you are, and you do not belong here. Guards!!!}
{135}{}{我不知道你是谁，你不属于这里。卫兵！！！！}

#{136}{}{Who are you and what are you doing down here?}
{136}{}{你是谁，你在这里做什么？}

#{137}{}{I am a worshiper and I am lost.}
{137}{}{我是个朝拜者，我迷路了。}

#{138}{}{Morpheus sent me with a message for the Master.}
{138}{}{墨菲斯派我来给主教送信的。}

#{139}{}{Looking for a lonely soul to send to heaven.}
{139}{}{我来找一个孤独的灵魂送他上西天。}

#{140}{}{Urk!}
{140}{}{恶！}

#{141}{}{You are not allowed in this area. Only Servitors and higher allowed
# down here. Return to the Cathedral proper.}
{141}{}{你不能来这里。只有侍从或者高层才能在这里，回大堂去。}

#{142}{}{I apologize for any trouble I have caused.}
{142}{}{对不起，给你添麻烦了。}

#{143}{}{May I ask you some questions before I leave?}
{143}{}{我走之前能问你几个问题吗？}

#{144}{}{OK, but not before I split your head open.}
{144}{}{好，我削完你脑袋就走。}

#{145}{}{Morpheus would not send a slag like you on such a mission. Guards!!}
{145}{}{墨菲斯不会让你这样一个瘾君子来送信的，卫兵！！！}

#{146}{}{You idiot! You are not allowed in this area. Return to the Cathedral
# proper at once!}
{146}{}{你白痴！你不能在这里，马上滚回大堂去！}

#{147}{}{Akay.}
{147}{}{好。}

#{148}{}{Hunh.}
{148}{}{呼。}

#{149}{}{Nah.}
{149}{}{咕噜。}

#{150}{}{I transfer records for the Master. That is all you need to know, my
# child. Now, you must leave.}
{150}{}{我为主教呈交记录。你就应该知道这些，我的教友，你可以走了。}

#{151}{}{I will leave now.}
{151}{}{我走了。}

#{152}{}{I just wish to ask you a few more questions.}
{152}{}{我还想再问几个问题？}

#{153}{}{I'll leave. I'll leave. But not until I blow your brains out.}
{153}{}{我走，我走，等我先把你脑浆敲出来！}

#{154}{}{How did you get in here?! What are you doing sneaking around?}
{154}{}{你是怎么进来的？！你鬼鬼祟祟干什么？}

#{155}{}{I just wish to ask you a few questions.}
{155}{}{我就想问你几个问题。}

#{156}{}{No, you may not ask me any questions. Now leave.}
{156}{}{你不能问我问题，走开。}

#{157}{}{Stop! You have no business being here!}
{157}{}{站住！这里不是你来的地方！}

#{158}{}{Duh?}
{158}{}{哇？}

#{159}{}{Sorry. I'm lost. I'll leave now.}
{159}{}{对不起，我迷路了，我马上走。}

#{160}{}{But I do have business here. Morpheus sent me on a mission for the
# Master.}
{160}{}{我有事情要做，墨菲斯让我来见主教。}

#{161}{}{I followed a suspicious looking character down here. Have you seen
# him?}
{161}{}{我看到一个可疑的家伙进来了，你看见没有？}

#{162}{}{No. Killing is my business and business is good.}
{162}{}{没有。杀人是我的专长，我学得还算不赖。}

#{163}{}{No, I have not seen anyone. What did he look like?}
{163}{}{没有，我没看见，他长什么样？}

#{164}{}{Doesn't matter. I think he got away.}
{164}{}{没关系，我想他已经走了。}

#{165}{}{It was a short little green man.}
{165}{}{是一个矮矮的绿皮肤的人。}

#{166}{}{He was about your height but was wearing a leather jacket... What
# do you have on under those robes?}
{166}{}{和你差不多高，穿一件皮甲……你们袍子里都穿什么？}

#{167}{}{He looked just like you, shit-for-brains!}
{167}{}{就和你一个样，脑袋里进屎的样子。}

#{168}{}{Um... I... I... You don't actually think it's m... me?  How ridiculous.
# I've never!}
{168}{}{呃……我……我……你不会认为那就是我吧？可笑啊，我不是的！}

#{169}{}{Ok. I'll be leaving then, but let me know if you see anything...}
{169}{}{好吧，那我走了，如果你看到的话一定向我汇报……}

#{170}{}{Yes! I do think it was you! Get down on the ground and spread 'em!}
{170}{}{没错，就是你！趴下，不准动。}

#{171}{}{No, I don't believe it was you but may I ask you some questions?}
{171}{}{可能不是你，我能问你几个问题吗？}

#{172}{}{Yes, my brother. How may I be of service?}
{172}{}{好，我能帮你什么？}

#{173}{}{Yes, my sister. How may I be of service?}
{173}{}{好，我能帮你什么？}

#{174}{}{What is it that you do here, brother?}
{174}{}{你在这里做什么工作？}

#{175}{}{Just serve the Master. That's all I ask. Brother.}
{175}{}{奉侍主教，我别无所求。}

#{176}{}{Sorry, wrong guy. All you guys look the same in these robes.}
{176}{}{哦，看错了，你们穿了袍子都一样啊。}

#{177}{}{You can serve me by dying, you whacked out bastard!}
{177}{}{帮我？那你可以去死，你这个笨蛋烂货！}

#{178}{}{I transfer the human purity reports for the surrounding areas.}
{178}{}{我呈交周围地区的人口基因纯度报告。}

#{179}{}{That is all. Thank you.}
{179}{}{没事，多谢。}

#{180}{}{I would like to ask you a few more questions, brother.}
{180}{}{我还想问你几个问题，兄弟。}

#{181}{}{Yes, and a very important job it is. And do you understand the
# importance of your duties to the Master and all of us?}
{181}{}{嗯，很重要的工作。你知道你的职责对于主教和我们的重要度吗？}

#{182}{}{Why, yes. I am the one who brings the Master the news of new,
# untainted humans untouched by radiation. I was the one who brought the
# Master the final news of a possible Lost Vault. It may still have pure-strain
# humans in it.}
{182}{}{嗯？当然。我向主教带来最新的未受辐射的纯种人类的消息。我向主教汇报有关消失避难所的搜寻的最新进展。那里可能有纯种人类存在。}

#{183}{}{Yes, my brother. You do understand. Thank you. That is all.}
{183}{}{好，看来你是明白的，就这样了。}

#{184}{}{I would like to ask you a few other questions.}
{184}{}{我还要问你一些问题。}

#{185}{}{You wouldn't know a pure-strain human if he was standing right in
# front of you. Idiot.}
{185}{}{你不知道站在你面前的就是一个纯种的人类，白痴！}

#{186}{}{You wouldn't know a pure-strain human if she was standing right in
# front of you. Idiot.}
{186}{}{你不知道站在你面前的就是一个纯种的人类，白痴！}

#{187}{}{You act very strangely. I do not believe that you are who you say you
# are. Guards!}
{187}{}{你的表现很奇怪，我不相信你了，卫兵！！！}

#{188}{}{You ask too many questions.  I do not believe that you are who you
# say you are. Guards!}
{188}{}{你问的太多了，我不相信你了，卫兵！！！}

#{189}{}{Hey! I told you were not allowed down here! Guards!}
{189}{}{嘿！我说过了你不能在这里！卫兵！}

#{190}{}{You ask too many questions. Who are you?}
{190}{}{你问的太多了，你是谁？}

#{192}{}{Excuse me, sister. You startled me. How may I serve the Master?}
{192}{}{对不起，教友，你吓着我了。你有什么要我帮忙的？}
