{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see the haggard shape of Bob.}
{100}{}{你看见憔悴的鲍勃。}

#{101}{}{Please don't kill me! I swear I'll get you your money.!}
{101}{}{别杀我！我发誓会给你钱的！}

#{102}{}{Duh-huh.}
{102}{}{嘟呼。}

#{103}{}{Yeah, you'd better pay up.}
{103}{}{那就赶紧给我！}

#{104}{}{I think I have the wrong room.}
{104}{}{我可能走错房间了。}

#{105}{}{What are you talking about?}
{105}{}{你说什么？}

#{106}{}{Ack! You must be Dumb Fred, Merciless Killer of the Dirt. Please
# don't kill me!}
{106}{}{啊！你就是“笨蛋”弗蕾德，肮脏血腥的杀手！不要杀我！}

#{107}{}{Here. Here. Take this. It's all I have.}
{107}{}{拿走，拿走，这是我的全部家当了。}

#{108}{}{You mean you're not here to kill me?}
{108}{}{你是说，你不是来杀我的？}

#{109}{}{Nope. It's your lucky day.}
{109}{}{我不是的，算你运气好。}

#{110}{}{No. Who would be threatening you?}
{110}{}{不是，谁要挟你？}

#{111}{}{Thanks. I just got a little nervous when you walked in here with a }
{111}{}{谢谢，你进来的时候手里拿着}

#{112}{}{ in your hand.}
{112}{}{我有点紧张。}

#{113}{}{Thanks. I just got a little nervous when you walked in here with a }
{113}{}{谢谢，我只是看到你进来的时候手里拿着}

#{114}{}{ in your hand.}
{114}{}{时有点紧张。}

#{115}{}{Geez, I thought you were from the Casino. Sure as sand in the
# desert, I owe them a lot of money.}
{115}{}{靠，我以为你是赌场里来催债的。的确，我欠他们很多钱。}

#{116}{}{Why do you owe them so much money?}
{116}{}{你怎么会欠他们那么多呢？}

#{117}{}{Who at the casino do you owe this money to?}
{117}{}{你欠赌场里的谁那么多钱？}

#{118}{}{How much money do you owe?}
{118}{}{你欠多少？}

#{119}{}{Hmmm. Thanks for the info.}
{119}{}{嗯，多谢。}

#{120}{}{They cheat. I played a little slots and some poker. But I'm a better
# player than that. I swear those machines are rigged. I lost a lot of money.}
{120}{}{他们出老千。我玩过轮盘和纸牌，我的水平不低的。我肯定，那些机器有问题，我输光了。}

#{121}{}{Who at the casino do you owe this money to?}
{121}{}{你欠赌场里的谁那么多钱？}

#{122}{}{How much money do you owe?}
{122}{}{你欠多少？}

#{123}{}{Hmmm. Thanks for the info.}
{123}{}{嗯，多谢。}

#{124}{}{Some goons. They say they work for the Casino Boss, but I never
# saw him. One was called Izo, I think, and the other was some big Guido
# looking guy. Damn cheaters.}
{124}{}{两个流氓。他们自称是赌场老板的手下，但是我从来没见过老板。有一个家伙叫艾佐，还有一个总是一付老是了不起的样子。两个骗子。}

#{125}{}{Why do you owe them so much money?}
{125}{}{你怎么会欠他们那么多？}

#{126}{}{How much money do you owe?}
{126}{}{你欠了多少？}

#{127}{}{Hmmm. Thanks for the info.}
{127}{}{嗯，多谢。}

#{128}{}{Oh, not too much. A couple thousand. I only played for four or
# five hours. Well, maybe a little longer. They gave me some markers, and
# I don't have enough here to cover it. I gotta get back to the Hub and get
# some cash. I'm afraid they'll beat me up if I try to leave.}
{128}{}{不多，两千块吧。我也就玩了四五个小时。也许还要长点。他们给了我一些筹码，我这里的钱还不起。我要去哈勃城拿钱，但是我要是走的话会被他们揍死的。}

#{129}{}{Why do you owe them so much money?}
{129}{}{你怎么会欠他们那么多？}

#{130}{}{Who at the casino do you owe this money to?}
{130}{}{你欠赌场里的谁那么多钱？}

#{131}{}{Hmmm. Thanks for the info.}
{131}{}{嗯，多谢。}

#{132}{}{Oh, it's you again. I hope you did better than me.}
{132}{}{又是你，你的手气比我好吧。}

#{133}{}{Hey, what are you doing in my room? Are you from the Casino?}
{133}{}{嘿，你在我这里干什么？你是赌场来的？}

#{134}{}{Nhhh!}
{134}{}{那！}

#{135}{}{Yeah, I'm from the Casino.}
{135}{}{是的，我是赌场来的。}

#{136}{}{No, I'm just looking around.}
{136}{}{不是，我就随便看看。}

#{137}{}{What's wrong with the Casino?}
{137}{}{赌场怎么了？}

#{138}{}{Oh gosh. I thought you were from the Casino. You scared me.}
{138}{}{呼呼，我还以为你是赌场来的，你吓死我了。}

#{139}{}{Oh, Ok. Bye.}
{139}{}{好好，我走。}

#{140}{}{Why?}
{140}{}{怎么？}

#{141}{}{Well, I got into some trouble there. I owe them a lot of money.}
{141}{}{我在那里惹了麻烦，我欠他们很多钱。}

#{142}{}{Why do you owe them so much money?}
{142}{}{你怎么会欠他们那么多？}

#{143}{}{Who at the casino do you owe this money to?}
{143}{}{你欠赌场里的谁那么多钱？}

#{144}{}{How much money do you owe?}
{144}{}{你欠多少钱？}

#{145}{}{Hmmm. Thanks for the info.}
{145}{}{嗯，多谢。}

#{146}{}{Oh, it's you again. You scared me for a moment. You haven't seen anyone
# from the Casino around here, have you?}
{146}{}{噢，又是你，你差点吓死我了。你看到附近有赌场的人么？}

#{147}{}{Hnnn!}
{147}{}{嗯！}

#{148}{}{No.}
{148}{}{没有。}

#{149}{}{Yep, sure did.}
{149}{}{有啊。}

#{150}{}{Hey, I got some questions for you.}
{150}{}{嘿，我有点问题问你。}

#{151}{}{Good, good. I just need a couple more days, and I'll make their money
# back and much more. I'm a better gambler than they think.}
{151}{}{好，好，我还需要几天，我连本带息还给他们钱。我是个很好的赌手。}

#{152}{}{Ack! Ohmygawd! I'm in trouble! Bye.}
{152}{}{啊！天！我有麻烦了！拜拜！}

#{153}{}{Go ahead, shoot. Oh, bad choice of words, Bob. Bad choice of words.}
{153}{}{来啊，开枪啊。噢，说错话了，鲍勃，说错话了。}

#{154}{}{Why do you owe them so much money?}
{154}{}{你怎么会欠他们那么多？}

#{155}{}{Who at the casino do you owe this money to?}
{155}{}{你欠赌场里的谁那么多钱？}

#{156}{}{How much money do you owe?}
{156}{}{你欠多少钱？}

#{157}{}{Hmmm. Thanks for the info.}
{157}{}{嗯，多谢。}
