{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{He looks like an experienced guardsman.}
{100}{}{他看起来是一个很有经验的守卫。}

#{101}{}{You'd better watch yourself here.}
{101}{}{你在城里老实点。}

#{102}{}{This isn't a good town to get in trouble in.}
{102}{}{这个镇子可不是你们闹事的好地方。}

#{103}{}{Behave, and we won't have to get nasty.}
{103}{}{守法，我们就不会对你怎么样。}

#{104}{}{You're ok.}
{104}{}{你可以进去了。}

#{105}{}{Keep up the good work.}
{105}{}{好好干。}

#{106}{}{Nice day, isn't it?}
{106}{}{天气不错，哈？}

#{107}{}{This is Junktown. Nice place to live, as long as you stay on
# our good side.}
{107}{}{这里是迦克镇，很好的地方，只要你不乱来。}

#{108}{}{Watch out for Gizmo and his cronies.}
{108}{}{小心吉斯莫和他的手下。}

#{109}{}{I like my boss.}
{109}{}{我喜欢我的老板。}

#{110}{}{You'd better put that away. Junktown is a friendly place, friend, and we
# want to keep it that way.}
{110}{}{你把那个收起来。迦克镇是一个和平的地方，我们希望保持这个气氛。}

#{111}{}{Put what away?}
{111}{}{把什么收起来？}

#{112}{}{Don't tell me what to do, loser boy.}
{112}{}{别想让我听你的话，小样。}

#{113}{}{Sounds fair. By the way, what is the local law regarding weapons?}
{113}{}{听起来不错。对了，本地对武器的法规是怎么样的？}

#{114}{}{Uh,oh.}
{114}{}{噢，噢。}

#{115}{}{Your weapon, idiot. Killian won't take your arms away, but you'd
# better damn well keep them in your holster.}
{115}{}{你的武器，白痴。基利安不会没收你的武器，但你必须把它们收好。}

#{116}{}{Oh, sorry.}
{116}{}{哦，对不起。}

#{117}{}{No way! I'm not putting down my shooters for nobody!}
{117}{}{没门！我不会让任何人缴我的枪！}

#{118}{}{You'd better behave, since it's the law, and I enforce the law.
# Put your weapon away, don't draw it unless in self-defense, and
# you won't have a problem with us guards. Disobey the law, and we
# will return you to the lawless wasteland - dead or alive.}
{118}{}{你最好遵照执行，这是法律，我是执法者。把你的武器收起来，除非自卫，不能再拿出来，我们守卫就不会再来麻烦你。如果你想违反法律，那我们就送你回废土去，不管你的死活。}

#{119}{}{Sure, since you put it that way.}
{119}{}{好吧，既然你这么说的话。}

#{120}{}{Bite your laws!}
{120}{}{滚蛋吧，破法律！}

#{121}{}{Well, uh, fine with me. But you'd better be careful.}
{121}{}{好，我接受，但你要小心点。}

#{122}{}{Good you asked. No weapons can be drawn except in self-defense. If
# you start a fight, it's your fault. Other than that, it's your right
# to go around armed. Just don't pull a knife or gun without just
# cause. Have a good day.}
{122}{}{很好。除了自卫，不准拿出武器来。你如果首先挑起战斗，那是你的错。记住这些，你可以携带武器四处转悠。但是没有正当理由不能动刀枪。再见。}

#{123}{}{Hey you, no weapons! And I don't care if your momma dropped you on
# your head as a kid. No weapons.}
{123}{}{嘿！你站住！不准拿出武器！你妈妈生你的时候让你脑袋砸在地上了？不准拿出武器！}

#{124}{}{Hey! You! What are you doing sneaking around?}
{124}{}{嘿！你！你鬼鬼祟祟干什么？}

#{125}{}{Nothing.}
{125}{}{没事。}

#{126}{}{I'm not sneaking around. I just like to walk cautiously.}
{126}{}{我不是鬼鬼祟祟，我是小心地在走路。}

#{127}{}{Uhhh.}
{127}{}{唔。}

#{128}{}{Whatever you're doing, don't do it in this town.}
{128}{}{我不管你想干什么，在城里不准这样。}

#{129}{}{The guard stares at you for a moment. You see a look of recognition
# on his face, and then he pulls his weapon.}
{129}{}{【守卫瞪了你一阵子，似乎认出了你，掏出了武器。】}

#{130}{}{Well, uh, ok. Whatever. Just don't do anything out of line.}
{130}{}{呃，好，不管怎样，别做出格的事情。}

#{131}{}{Thanks, bye.}
{131}{}{多谢，再见。}

#{132}{}{Certainly. I will throw caution to the wind, sir.}
{132}{}{当然，我时时刻刻都很小心的。}

#{133}{}{Certainly. I will throw caution to the wind, ma'am.}
{133}{}{当然，我时时刻刻都很小心的。}

#{134}{}{Put that weapon away, or face the consequences!}
{134}{}{把武器收起来，否则你不会有好日子过！}

#{135}{}{Okay, that's enough warnings. Leave town, now, and never return, or
# face the consequences!}
{135}{}{我们给了你很多警告了。离开镇子，不准回来，不然有你好看！}

#{136}{}{Hey! What do you think you're doing?}
{136}{}{嘿！你在做什么？}

#{137}{}{That's it, you've had it, buddy.}
{137}{}{好的，你自找的。}

#{138}{}{You're in trouble now . . .}
{138}{}{你有麻烦了……}

#{139}{}{You Skulz are under arrest!}
{139}{}{你们骷髅党都被逮捕了！}
