{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a raider who seems crazed.}
{100}{}{你看见一个看起来很疯狂的强盗。}

#{101}{}{That's it! Don't come any closer. I'll off her. I swear.}
{101}{}{站住！别过来！我会杀了她的，真的！}

#{102}{}{Nung!}
{102}{}{不不！}

#{103}{}{Don't do it!}
{103}{}{不要这样！}

#{104}{}{If you don't let her go, I'm gonna kill you.}
{104}{}{如果你不放她走，我就杀了你！}

#{105}{}{There is no need for violence. Let's talk about this.}
{105}{}{没必要动粗，我们可以谈一谈。}

#{106}{}{What? You just want to kill me, don't you?
# Just remember, this is your fault.}
{106}{}{什么？你想杀我？记住，这是你的错。}

#{107}{}{Any why not? She's just a whore.}
{107}{}{动手啊？她就是一个婊子嘛。}

#{108}{}{She has as much right to live as you do.}
{108}{}{她和你一样都有活下去的权利。}

#{109}{}{No. No way. Not this bitch.}
{109}{}{别，别啊，别杀这一个啊。}

#{110}{}{What world do you live in? Out here in the real world, blood flows, man.
# Blood flows, and it's gonna spill all over this room if you don't get out of here.}
{110}{}{你以为现在是什么社会？醒醒吧你，流血，流血啊！你再不出去，我要让这里到处都是血！}

#{111}{}{We can talk this over. What can I do to help?}
{111}{}{我们可以谈判解决的，你要我怎么样帮你？}

#{112}{}{Ok, ok. I'm backing off. You don't have to worry about me.}
{112}{}{好好好，我退后，你不要担心我来抓你。}

#{113}{}{Geez, that's funny. Who says I want help?}
{113}{}{哈！好笑，我还需要帮忙？}

#{114}{}{You do. By holding this woman hostage, you're asking
# for help. I can help.}
{114}{}{你需要的，你抓住了这个女人，就是想让别人来帮你，我就可以帮你。}

#{115}{}{I gotta think about this. Give me a moment.}
{115}{}{我要考虑下，给我点时间。}

#{116}{}{Yeah. Don't try anything, or she gets it.}
{116}{}{好，别再过来了，要不然她就死了。}

{117}{}{男人}

{118}{}{女人}

#{119}{}{Oh, big man. Let's see you try. But first . . .}
{119}{}{噢，你来啊，不过首先……}

#{120}{}{Oh, big woman. Let's see you try. But first . . .}
{120}{}{噢，你来啊，不过首先……}

#{121}{}{Stay back . . . I don't want to hurt her, but I will.}
{121}{}{退后……我不想伤害她，但不代表我不能。}

#{122}{}{Don't, or I'll have to hurt you.}
{122}{}{别这样，否则我就会伤害你。}

#{123}{}{Why do you want to hurt her?}
{123}{}{你为什么要伤害她？}

#{124}{}{Try it, and she dies first. Now, what were you saying?}
{124}{}{试试看啊，她先死！你刚才说什么？}

#{125}{}{It'll be hard to hurt her with that hole in your head.}
{125}{}{你脑袋上多个洞就很难再伤害她了。}

#{126}{}{Ok, but you got to keep talking to me.}
{126}{}{好，但你要一直和我说话。}

#{127}{}{What hole?}
{127}{}{什么洞？}

#{128}{}{The one I'm gonna put there right now.}
{128}{}{我马上就要在你脑袋上开的洞。}

#{129}{}{I'll keep talking as long as you do,
# but try anything tricky, and she'll take the fall.}
{129}{}{我会一直和你说话，但你别和我玩花样，要不然她就死掉。}

#{130}{}{I don't have to do anything. You got to do it, and
# you ain't doing so hot.}
{130}{}{我不需要做任何事情。你要是敢做，你就会很惨。}

#{131}{}{She laughed at me. They all laughed at me. I'll make 'em pay, I swear.}
{131}{}{她嘲笑我。他们都嘲笑我，我要他们好看，我发誓的。}

#{132}{}{I trust you. Let's work through this, ok?}
{132}{}{我信任你，我们把这个事情了了，如何？}

#{133}{}{Maybe. I dunno.}
{133}{}{也许，我不知道。}

{134}{}{哥们}

{135}{}{小妞}

#{136}{}{You sound like an all right kind of guy. No one ever wanted to help me before. I think we can talk some more.}
{136}{}{哥们你看起来人不错，以前没人愿意来帮助我。我们可以再谈会儿。}

#{137}{}{You sound like an all right kind of gal. No one ever wanted to help me before. I think we can talk some more.}
{137}{}{小妞你看起来人不错，以前没人愿意来帮助我。我们可以再谈会儿。}

#{138}{}{Just leave me alone. I hate you! You are the devil.
# I won't listen to you.}
{138}{}{别管我，我恨你！你就是魔鬼！我不听你的！}

#{139}{}{Have it your way.}
{139}{}{随你。}

#{140}{}{You have to hear me out. Your life, and the life of the
# girl, depend on it.}
{140}{}{你听我说，你和这姑娘的命都靠我对你说的话了。}

#{141}{}{Just relax. I won't harm you. I just want to listen
# to what you have to say.}
{141}{}{别紧张，我不会伤害你的。我只是想知道你的心里话。}

#{142}{}{There you go again, threatening me. Die!!}
{142}{}{你又来，威胁我，你去死！}

#{143}{}{I won't listen to you. You're just going to trick me with
# your words. I don't believe you. Go away.}
{143}{}{我不会听你的。你想用话来套我上当。我不相信你，快滚！}

#{144}{}{You might have a point. Prove it to me.}
{144}{}{有点道理，你说说看。}

#{145}{}{Where do we go from here?}
{145}{}{我们怎么办？}

#{146}{}{You tell me. You're in charge.}
{146}{}{你必须说，你是这里管事的。}

#{147}{}{I want some money, and I want to get out of here peacefully.
# No one follows me.}
{147}{}{我要点钱，我要安全地离开这里，不准有人跟着我。}

#{148}{}{Sorry, we can't do that.}
{148}{}{对不起，我们不能答应。}

#{149}{}{Sure.}
{149}{}{当然可以。}

#{150}{}{No money, but you can just walk away.
# No one will do anything. I promise.}
{150}{}{没有钱，但是你可以离开，没人会对你怎么样，我保证。}

#{151}{}{Ok, but you have to let the girl go first.
# Show me some trust, and I'll trust you.}
{151}{}{好，但是你要先放了姑娘，你要有点诚意，我才能信任你。}

#{152}{}{You lied to me!}
{152}{}{你撒谎！}

#{153}{}{Ok. I want $100. Then we walk out of here.
# No one follows me, and I'll let her go when we get to the edge of town.}
{153}{}{好，那我要100个瓶盖。然后我和她一起走出去，没人跟着我，到城边后我放她走。}

#{154}{}{Here's your money.}
{154}{}{这是你的钱。}

#{155}{}{I don't have that kind of cash on me.}
{155}{}{我没有那么多钱。}

#{156}{}{Then I guess she gets it.}
{156}{}{那我就杀了她。}

#{157}{}{That's ok, I guess.}
{157}{}{好的。}

#{158}{}{I don't like it. What stops you from just shooting me in the back
# when I walk out of here?}
{158}{}{不行，我走出去后，你们会在背后打枪的。}

#{159}{}{I won't shoot you. Trust me.}
{159}{}{我不会开枪的，相信我。}

#{160}{}{Nothing, you'll just have to believe what I say.}
{160}{}{你只能信任我一次了。}

#{161}{}{No way! I don't trust you!}
{161}{}{没门！我不信任你！}

#{162}{}{All right. We'll see what happens, won't we.}
{162}{}{好吧，走着瞧。}

#{163}{}{Here's $100. Have a good day.}
{163}{}{这是100个瓶盖，再见。}

#{164}{}{You can leave peacefully.}
{164}{}{你可以安全地离开了。}

#{165}{}{I want my money. I want $200.}
{165}{}{我要钱，200个瓶盖。}

#{166}{}{I don't have enough money.}
{166}{}{我没有那么多钱。}

#{167}{}{Here you go.}
{167}{}{给你。}

#{168}{}{You seem like a liar and a cheat to me.}
{168}{}{你看起来是在撒谎。}

#{169}{}{Feeling's mutual bud. Let the girl go.}
{169}{}{信任感是相互的，让女孩走。}

{170}{}{男人}

{171}{}{女人}

#{172}{}{Why don't you pick on me instead of her?
# See what a real man can do.}
{172}{}{有种你就你把我当人质吧。}

#{173}{}{Why don't you pick on me instead of her?
# See what a real woman can do.}
{173}{}{有种你就你把我当人质吧。}

#{174}{}{No! Don't tell me what to do! You can't tell me what to do!}
{174}{}{不！你不要指挥我！你没资格指挥我！}

#{175}{}{Yeah, I'm gonna show you.}
{175}{}{好，我给你看看我有没有种。}

#{176}{}{You just cost this whore her life!}
{176}{}{你害了她丢掉了性命！}

#{177}{}{Leave me alone, dammit!}
{177}{}{滚开，他妈的！}

#{178}{}{The raider, intent upon his business, ignores you.}
{178}{}{这个强盗坚决不理会你。}

#{179}{}{Hmmm . . .}
{179}{}{嗯……}

#{180}{}{Hey, let's get it on, baby. I got the cash if you've got the time.}
{180}{}{嘿，给我点时间，我去弄钱。}

#{181}{}{You don't talk to me like that, bitch! Nobody talks to me like that!}
{181}{}{你敢和我这样说话，你这个婊子！谁都不能这样和我说话！}

#{182}{}{That just cost you your life!}
{182}{}{那会把你小命搭进去的。}

#{183}{}{Your carefully-placed blow knocks the raider unconscious. He collapses
# like a rag doll.}
{183}{}{你精准的重击打昏了歹徒，他像条死狗一样晕倒了。}

#{184}{}{You might be able to sneak up on the raider if you're careful.}
{184}{}{如果小心点，你可以悄悄过去打昏这个歹徒。}
