
# {100}{}{The gunman pays you no heed.}
# {101}{}{The gunman sneers at you as he passes by.}
# {102}{}{You see a shady looking gunslinger.}
# {103}{}{Gizmo sends his regards!}
# {104}{}{You gain 400 experience points for helping Killian fight the assassin.}
{100}{}{这个持枪男子没注意到你在看他。}
{101}{}{这个持枪男子安静的从你面前经过。}
{102}{}{你看到一个冷峻的持枪男子。}
{103}{}{吉斯莫让我问候你！}
{104}{}{你帮基利安干掉了枪手，你得到400点经验值。}
