{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Kyle.}
{100}{}{你看见凯尔。}

#{101}{}{You see a Knight.}
{101}{}{你看见一名骑士。}

#{102}{}{Ahh...So you're the one, huh?}
{102}{}{啊……你就是那个人，是吧？}

#{103}{}{What?}
{103}{}{什么？}

#{104}{}{Well, who are you?}
{104}{}{嗯，你是谁？}

#{105}{}{Nothing. It's just that no one has ever made it back from the
# Ancient Order.}
{105}{}{没事。好像你是第一个能活着从古代遗迹走回来的人。}

#{106}{}{What do you do here?}
{106}{}{你在这里做什么？}

#{107}{}{What? Then why did they send me down there?}
{107}{}{啊！？那他们让我去那里干什么？}

#{108}{}{It was difficult, but not impossible.}
{108}{}{是很艰难，但还不是不可能。}

#{109}{}{Heh, heh. I guess they just wanted to get rid of ya, huh?
# Well, the jokes on them.}
{109}{}{呵呵，我想他们只是为了干掉你，哈？我开玩笑的。}

#{110}{}{Yeah. Say, what do you do here?}
{110}{}{嗯，那你是干什么的？}

#{111}{}{Well, the only reason I joined was to get some power armor.}
{111}{}{我来这里唯一的原因就是来拿能量装甲。}

#{112}{}{Screw all you guys. I'm leaving.}
{112}{}{你们这些家伙真可怕，我走了。}

#{113}{}{I fix stuff, run maintenance checks, that sort of crap.}
{113}{}{我修东西，做维护，这些烂事。}

#{114}{}{Could you fix a water chip?}
{114}{}{你能修理净水芯片吗？}

#{115}{}{What kind of "stuff"?}
{115}{}{什么样的“东西”？}

#{116}{}{That sounds like a real good time. I'll see ya later.}
{116}{}{和你聊天很愉快，再见啦。}

#{117}{}{Power armor and anything else that needs fixin'.}
{117}{}{能量装甲还有任何东西，我都能修。}

#{118}{}{How can I get my hands on some power armor?}
{118}{}{我怎么才能得到能量装甲？}

#{119}{}{I'd give ya this power armor right here, but it's missing it's
# Systolic Motivator. It's useless without it.}
{119}{}{我这里有一件可以给你，但是它需要一个启动器，没有的话它就是一个废物。}

#{120}{}{Where could someone get one of those?}
{120}{}{谁会有这个呢？}

#{121}{}{Well, thanks anyway.}
{121}{}{哦，多谢了。}

#{122}{}{Well, they've got more than enough up in the supply room, but
# Michael and his damn forms say that this particular suit isn't up to
# specs. Damn bureaucrats.}
{122}{}{在储备室有好多，但迈克尔和他的那些烂表格说这件不符合规格。真官僚！}

#{123}{}{What do you mean, not up to specs?}
{123}{}{什么叫不符合规格？}

#{124}{}{So if I brought you a Systolic Motivator, would you fix it for
# me?}
{124}{}{就是说，如果我找到了一个起动器，你就会帮我把这个修好？}

#{125}{}{You see this eye-piece right here? I had to re-solder it in
# place, and it don't look as pretty as it needs to for inspection, I
# guess.}
{125}{}{你看到这个眼镜了没？我要把这个重新安好位置，我觉得这根本不需要检验。}

#{126}{}{You're right. That looks like crap. I wouldn't be caught
# dead in that power armor.}
{126}{}{没错，这就是一件垃圾，我可不想死在这样的装甲里面。}

#{127}{}{Get the hell out of here, buddy.}
{127}{}{那就走开，伙计。}

#{128}{}{Whoa, wait a minute there, fella, that would take a good
# coupla hours. I'd loan you a manual and my tools, but you'd hafta
# repair it yourself.}
{128}{}{哇，等一下，这可能需要几个小时，我给你一份手册和我的工具，你自己来修理下。}

#{129}{}{Well, besides Michael, where else could I get one?}
{129}{}{除了迈克尔，还有谁会有这个？}

#{130}{}{That's fair. I'll be back.}
{130}{}{很好，我会回来的。}

#{131}{}{Heh, well, Rhombus has a couple of 'em. I wouldn't ask him
# for one, though. Only "the Honored" are supposed to wear these here
# power suits. Besides, I think he has an unnatural attachment to them.}
{131}{}{隆伯斯有一些。我从来没问过他。只有“赋予荣誉”的兄弟会成员才能穿能量装甲。另外，我觉得他自己对起动器也有不正常的需求。}

#{132}{}{Hmm. Okay, thanks a lot.}
{132}{}{嗯，好，多谢了。}

#{133}{}{I don't think so. Don't even know what one is.}
{133}{}{不行，我都不知道啥是啥的。}

#{134}{}{Thanks anyway.}
{134}{}{谢谢你。}

#{135}{}{What kind of weak mechanic are you, can't even fix a water
# chip?}
{135}{}{你真是个不称职的技工啊，净水芯片都修不好？}

#{136}{}{How can I get some power armor without studying for a hundred
# years?}
{136}{}{我要怎样才能不用学这学那的还能得到能量装甲呢？}

#{137}{}{The moniker's Kyle. I've never met a myth before.}
{137}{}{我是凯尔，这是我第一次遇见神话人物。}

#{138}{}{What's that supposed to mean?}
{138}{}{什么意思？}

#{139}{}{What do you do here?}
{139}{}{你在这里做什么？}

#{140}{}{Neither have I. I'll see you around.}
{140}{}{我也不会。再见。}

#{141}{}{To hear Maxson's stories you'd think it was the ninth level
# of hell.}
{141}{}{听马克松讲历史那简直就是炼狱啊。}

#{142}{}{Maxson? General Maxson?}
{142}{}{马克松？马克松将军？}

#{143}{}{Not General Maxson, his grandfather, Roger Maxson. I heard you
# brought back a disk that told what happened to the guys who rebelled
# against him and went down there to recover the lost technology.}
{143}{}{不是马克松将军，是他爷爷鲁格·马克松。我听说你找回了一块磁盘，上面记录了当年那些背叛鲁格·马克松的叛军去寻找古代科技的事情。}

#{144}{}{Yeah, I guess I did. I'm }
{144}{}{没错，是我找到的。我叫}

#{145}{}{, who're you?}
{145}{}{。你是？}

#{146}{}{I'd rather not talk about it.}
{146}{}{我还是不说这个的好。}

#{147}{}{Yeah, lousy bastards. I can't believe they sent you down there
# like that.}
{147}{}{是啊，那些混球，没想到他们真派你去那里找东西。}

#{148}{}{And all they gave me for my trouble was a handful of ammo!}
{148}{}{他们只是给了我一些子弹！}

#{149}{}{Hey, initiate, got anything for me?}
{149}{}{嘿，新兵，你拿到了？}

#{150}{}{No, I told them you sent me and he wouldn't give me the part.}
{150}{}{没，我和他们说了，但是他们不给。}

#{151}{}{No I haven't even looked into it yet.}
{151}{}{我还没去问呢。}

#{152}{}{No luck yet.}
{152}{}{还没。}

#{153}{}{No shit. And here I thought you was smart. I told ya that guy
# had official forms for brains.}
{153}{}{我靠。我以为你能聪明地搞定的。我跟你说了，那个军需官就是脑子里长了表格了！}

#{154}{}{Watch who you call an idiot.}
{154}{}{你说话小心点。}

#{155}{}{I was just tryin' to talk it out of Michael.}
{155}{}{我去再找迈克尔说说看。}

#{156}{}{What can I do if Michael won't give it to me.}
{156}{}{如果迈克尔真的不给，我怎么办？}

#{157}{}{I'm going.}
{157}{}{我走了。}

#{158}{}{Wella... I got to give you credit for that. But I think you blew
# your chances with getting it from the supply room. You'll just have to
# find another way to get it. Or find yourself Power Armor somewares else.}
{158}{}{那……我要说我很感激你。但是似乎从军需储备室取得这个玩艺基本不可能了。你应该想想其他办法。或者直接去搞一件完整的能量装甲。}

#{159}{}{OK, see you later.}
{159}{}{好，待会见。}

#{160}{}{Where else can I dig one up?}
{160}{}{还有哪里可以找到？}

#{161}{}{Good luck.}
{161}{}{好运。}

#{162}{}{Get lost, I'm busy.}
{162}{}{你走吧，我忙呢。}

#{163}{}{Hello, were you able to get that part?}
{163}{}{哈罗，你搞到了？}

#{164}{}{Yes. Here it is.}
{164}{}{是啊，这里。}

#{165}{}{Yes, but I think I'll hold on to it a little while.}
{165}{}{是，但我要自己先保管一阵子。}

#{166}{}{Great! Here just let me install this into the unit.}
{166}{}{太好了！我来把这个安装进去。}

#{167}{}{OK you're all set to go. Here take this manual. If you have any
# kind of aptitude with repairing things you should have no problem.
# Good Luck.}
{167}{}{好了，你可以自己动手了。这里是手册，如果你的修理技能过关，那你应该没什么问题的，好运！}

#{168}{}{After all that? Okay, just let me know when you want me to put
# it in. Then you can get started on repairing it.}
{168}{}{你要那个有什么用呢？好吧，等你想好了就给我，我帮你安装进去，你就可以开始修理了。}

#{169}{}{Well, I don't know what to tell you. I guess you need to
# polish up your repair skills a little. I'll keep the unit here for ya.}
{169}{}{我也不知道怎么和你说，你应该好好练练你的修理技能，我会把这个留给你的。}

#{170}{}{Ok. Thank you. Good bye.}
{170}{}{好，多谢，再见。}

#{171}{}{Hello agin. Can I help you?}
{171}{}{你好，你有什么需要？}

#{300}{}{【more】}
{300}{}{【更多】}
