{1099}{}{?}
{1199}{}{我可以告诉你：Set-赛特、Master-主教、Water-水、Watershed-水处理室、Hall-亡者大厅、Necropolis-大墓地城、Chip-芯片。}

#{100}{}{You see the ghoul leader.}
{100}{}{你看见一个僵尸头目。}

#{101}{}{Thank you for not shooting first. Can I help you with anything?}
{101}{}{谢谢你没直接一枪打过来，我有什么可以效劳的？}

#{102}{}{Yes, I'm looking for water.}
{102}{}{有，我在找水。}

#{103}{}{Sure, who are you?}
{103}{}{当然。你是谁？}

#{104}{}{Nah.}
{104}{}{不。}

#{105}{}{Ahh, if you like you may rest here, we will not harm you.}
{105}{}{啊，你如果需要的话，可以在这里休息，我们不会伤害你的。}

#{106}{}{Ahh.}
{106}{}{啊。}

#{107}{}{I am the leader of a simple people who have left the surface
# because of the others.}
{107}{}{我是一群被迫转到地下生活的人的领袖。}

#{108}{}{Who has forced you down here?}
{108}{}{谁把你们赶下来的？}

#{109}{}{Geez, that's pretty dumb.}
{109}{}{日，这太衰了。}

#{110}{}{Hmm. Ok. Bye.}
{110}{}{嗯，好，再见。}

#{111}{}{The surface of Necropolis and the water is controlled
# by Set and his Ghouls. We are a much more peaceful group - which
# disgusts Set.}
{111}{}{大墓地的地表和水源都被赛特和他的手下控制了，我们是相比而言更爱好和平的一群，这就激怒了赛特。}

#{112}{}{Who is this Set?}
{112}{}{谁是赛特？}

#{113}{}{Well, I've taken care of Set. He won't bother you further.}
{113}{}{我那赛特那厮处理了，他不会再麻烦你们了。}

#{114}{}{How then do you survive down here without water?}
{114}{}{那你们没了水怎么在这里活下去的？}

#{115}{}{Well I sure wouldn't like a bunch of pansies either, Set
# sounds like an OK guy.}
{115}{}{我本人也不喜欢娘娘腔的和平分子，赛特至少还算是个爷们。}

#{116}{}{Set is a Ghoul like us, but has assumed a certain amount of
# power in the above ground world. He is an oaf.}
{116}{}{赛特和我们一样也是一个僵尸，但在地表世界获得了一定的权力，他是个混球。}

#{117}{}{He sounds a lot more interesting than you freaks.}
{117}{}{他听起来比你们这些变态分子有趣儿多了。}

#{118}{}{Why does he let you survive down here?}
{118}{}{他为什么还让你们在这里活下来了？}

#{119}{}{He does not speak of it, however Set is afraid of not having
# enough people to defend Necropolis if it ever needed it. So, he gives
# us what water we need.}
{119}{}{他也没说，可能是因为赛特怕防御大墓地城的时候人手不够吧，所以他给了我们必需的水。}

#{120}{}{Where does all of this water come from?}
{120}{}{这些水都是哪里来的？}

#{121}{}{I need water for my people! If you know where he gets it
# from, tell me now!}
{121}{}{我的人民需要水！如果你知道从哪里拿的，告诉我！}

#{122}{}{I am looking for a Water Chip, to give my people the water
# they need. Do you know where I might find one?}
{122}{}{我在找净水芯片，为我的人民提供水源，你知道哪里有这个东西么？}

#{123}{}{I wouldn't keep you guys around to defend a paper bag. So
# what's this about water?}
{123}{}{我要是他才不会让你们这些人保护这个破地方，谈谈水的事情吧。}

#{124}{}{Up until recently we pumped our water from the ground, with
# a pump in the Watershed.}
{124}{}{知道不久前，我们还是从地表的水口用水泵抽水。}

#{125}{}{Until recently? What has happened that changed things?}
{125}{}{不久前之后呢？}

#{126}{}{How do I get to the Watershed?}
{126}{}{我怎么去水泵那里？}

#{127}{}{What is the Watershed?}
{127}{}{什么是水口？}

#{128}{}{Since our pump stopped working, we have been getting our water
# from a place under the ground. I have heard that a water computer
# is being used to purify the water.}
{128}{}{我们的水泵坏了，所以我们现在是从地下的某个地方取水，我听说那里有台净水控制电脑。}

#{129}{}{Thanks.}
{129}{}{谢谢。}

#{130}{}{Where is that?}
{130}{}{那在哪里？}

#{131}{}{The watershed is to the north. You'll need to take the sewers
# to get there.}
{131}{}{水口在北方，你可以从下水道去那里。}

#{132}{}{You aren't thinking of taking the Water Chip from us are you?}
{132}{}{你不会是想把净水芯片取走吧？}

#{133}{}{Umm.. Me, no, I would never do such a thing. I am just going
# to see how it all works.}
{133}{}{呃……不，不是的。我才不会做这种事情呢，我去看看它的工作情况。}

#{134}{}{Of course, my people need the Water Chip to survive.}
{134}{}{当然了，我们的人民需要净水芯片。}

#{135}{}{Why?}
{135}{}{怎么？}

#{136}{}{If you take the Water Chip from us, then we will all die. With
# our water pump broken we need it to survive.}
{136}{}{如果你把芯片拿走，我们都会死的，我们的水泵坏了，我们没有水了。}

#{137}{}{Well, I really don't care about you and your people. We need
# the water chip for our own survival. Goodbye.}
{137}{}{我才不管你们的死活，我们也要芯片才能生存下去，再见！}

#{138}{}{Is it possible that your pump could be fixed?}
{138}{}{也许你们的水泵能修好？}

#{139}{}{If that is the case then I can't let you leave my presence alive.}
{139}{}{如果这样，我不能让你走！}

#{140}{}{I do not think that I believe you.}
{140}{}{我不相信你。}

#{141}{}{I am sorry I did not mean to deceive you. What is wrong with
# taking the Water Chip.}
{141}{}{对不起，我不是想骗你的。如果我拿走了芯片，会怎么样？}

#{142}{}{Well I don't really care. If you won't get out of my way, I'll
# just remove you myself.}
{142}{}{我不在乎，如果你再挡道，我就会让你消失！}

#{143}{}{That may be difficult. The parts needed to fix the pump were lost
# in the sewers under the watershed.}
{143}{}{这很难的，修理水泵的那部分零件丢在水口下的下水道了。}

#{144}{}{Why is that so difficult?}
{144}{}{这有什么难的？}

#{145}{}{Do you mean these parts? (You show the parts you found to the
# Ghoul Leader)}
{145}{}{你是说这些零件么？【你把捡到的零件给他看】}

#{146}{}{The sewers there are filled with monsters, and none of my people
# that I have sent to retrieve them have come back. Are you willing to
# retrieve the parts, so that the Water Pump can be fixed?}
{146}{}{下水道里都是怪物，我派去找零件的人都没回来。你愿意去帮我们拿来再修好水泵吗？}

#{147}{}{Sounds like too much trouble, I think I'll just take the Water
# Chip.}
{147}{}{太烦人了，我还是直接拿走芯片方便。}

#{148}{}{Yes.}
{148}{}{好的。}

#{149}{}{Since you guys are to incompetent to do this yourself, I guess
# I'll have to lend a hand.}
{149}{}{你们既然这般无能，我就帮你们一把吧。}

#{150}{}{Thank you. When you get the parts, return here. It is possible
# that I can help you further.}
{150}{}{谢谢。拿到零件后，回来，也许我能帮上点忙。}

#{151}{}{Ok, I'll be on my way then.}
{151}{}{好，我去了。}

#{152}{}{Have you found the parts for the Water Pump yet?}
{152}{}{你找到水泵零件了？}

#{153}{}{Not yet.}
{153}{}{还没。}

#{154}{}{Nope. And I've decided to forget the whole thing.}
{154}{}{算了，我不费这个事了。}

#{155}{}{Where was I supposed to find them again?}
{155}{}{我要去哪里找，你再说一遍。}

#{156}{}{Well I wish you luck then.}
{156}{}{那好，我祝你好运。}

#{157}{}{You have returned. Do you have the parts needed to repair the
# Water Pump?}
{157}{}{你回来了，找到修水泵的零件了？}

#{158}{}{Yes, here they are.}
{158}{}{对，这里。}

#{159}{}{Yeah, but I've decided to forget about fixing the Water Pump.}
{159}{}{没错，但是我不打算去修那个什么水泵了。}

#{160}{}{Well it looks like you may need some help with the parts. Here
# are some books that we have found littered around. They may help you.
# Now please take the parts to the water shed and repair the pump.}
{160}{}{你用这些零件去修理，我可以帮你的。这是我们在附近找到的几本书，也许有用，带上零件去修好它吧。}

#{161}{}{Unfortunately I will be able to help you no further. Good luck
# with the Water Pump. Please take the parts to the water shed and
# repair the pump.}
{161}{}{我不能再帮你什么了，祝你修理顺利。带上零件去修好它吧。}

#{162}{}{Have you fixed the Water Pump yet?}
{162}{}{你修好水泵了？}

#{163}{}{No not yet, but I am still working on it.}
{163}{}{还没，我在努力。}

#{164}{}{No, and I am not planning on it now.}
{164}{}{还没，我不干了。}

#{165}{}{Yes those are the parts I was talking about. Thank the flow
# that you already have them.}
{165}{}{没错，这就是我说的那些零件。你先找到了，真是太好了。}

#{166}{}{Is there anything else I should know?}
{166}{}{我还需要知道些什么？}

#{167}{}{Well that's as close as they are going to get to the Water Pump.}
{167}{}{就在水泵旁边。}

#{168}{}{As I already told you, they can be found in the sewers underneath
# the Water shed. Go east from here, and then north. You will find the
# Watershed in that direction.}
{168}{}{我说过了，就在水口下方的下水道里，从这里往东，再往北走，你就可以看见水口了。}

#{169}{}{Thanks for the directions. Goodbye.}
{169}{}{谢谢你的指点，再见。}

#{170}{}{Well thank you for that service. Was there something else you
# wanted to know?}
{170}{}{谢谢你能帮忙，你还要知道什么？}

#{171}{}{How do you survive down here without water?}
{171}{}{你们在这里没水怎么活下去的？}

#{172}{}{It is where all the water is stored and handed out to us.}
{172}{}{那里就是我们储水和分发水的地方。}

#{173}{}{Where is it located?}
{173}{}{具体位置？}

#{174}{}{Lately I have heard rumors that someone has taken over the
# control of the Watershed. However, our rations are still being
# delivered for some reason.}
{174}{}{最近我听说有人控制了水口，但是，我们的份额没减少。不知道为什么。}

#{175}{}{How do I get to the Watershed?}
{175}{}{我怎么去水口？}

#{176}{}{What is the Watershed?}
{176}{}{什么是水口？}

#{177}{}{Thank you for repairing the Water Pump, and I hope all is
# well with your people when you return with what you have found.}
{177}{}{谢谢你修好了水泵，我希望你带着芯片回去之后能帮助你的人民度过难关。}

#{178}{}{Thank you for your help. Goodbye.}
{178}{}{多谢，再见。}

#{179}{}{You have fixed the Water Pump and the flow has returned from
# the deep. However, I see you have not found what you are looking for.}
{179}{}{你修好了水泵，水再次流出来了，但是，你还没有找到你需要的东西。}

#{180}{}{Yes, I cannot seem to find the location of the Water Chip.}
{180}{}{是的，我找不到净水芯片。}

#{181}{}{I have heard that it is located deeply below the Watershed.
# I wish you luck in searching for it.}
{181}{}{我听说它可以在水口地下很深的地方找到。我预祝你成功。}

#{182}{}{I see that you have what you came here to find. You realize
# that we will die if you take the Water Chip from us.}
{182}{}{我看到你找到了你要的东西，你要知道，如果拿走了芯片，我们都会死的。}

#{183}{}{Yes, but I am still working to fix the Water Pump. Where did
# you say I could find the parts?}
{183}{}{是，但是我正在修理水泵，你上次说在哪里找到零件来着？}

#{184}{}{I need the Water Chip and I don't have time to deal with your
# problems.}
{184}{}{我需要芯片，我没时间管你们的破事。}

#{185}{}{What other options do I have.}
{185}{}{我没有其他办法了。}

#{186}{}{I am tired of putting up with your snide remarks. I do not
# wish to speak with you any further.}
{186}{}{我受够了你的虚伪说辞了，我不想再和你多嘴了。}

#{187}{}{We once had a pump located in the Watershed that pumped the
# flow from the deep. However, it was broken and the parts needed to
# fix it were lost in the sewers directly below the Watershed.}
{187}{}{我们以前在水口有一台水泵可以抽水，但是现在它坏了，修理的零件就在水口地下的下水道里。}

#{189}{}{Why have you not retrieved the parts yourself?}
{189}{}{你们为什么自己不去拿零件？}

#{190}{}{You have nothing to fear from us!}
{190}{}{你不需要怕我们！}

#{191}{}{I will speak with you before you leave.}
{191}{}{在你离开前，我有话要和你说。}

#{192}{}{You have left me no choice, but to stop you myself.}
{192}{}{你逼人太甚，我要出手了。}

#{193}{}{Wait. Don't shoot!}
{193}{}{别！别开枪！}

#{194}{}{You have nothing to fear from us!}
{194}{}{你不需要怕我们！}

#{195}{}{I will speak with you before you leave.}
{195}{}{在你离开前，我有话要和你说。}

#{196}{}{You have left me no choice, but to stop you myself.}
{196}{}{你逼人太甚，我要出手了。}

#{200}{}{Tough luck.}
{200}{}{运气不好。}

#{201}{}{Can't the water pump be repaired?}
{201}{}{水泵不能修好吗？}

#{202}{}{I'm sorry but my people need the chip to survive.}
{202}{}{对不起，我们的人民需要芯片才能生存。}

#{203}{}{Please don't take our chip. Without it we will die.}
{203}{}{别拿走我们的芯片，我们会死的。}

#{204}{}{Maybe, but the parts are lost in the sewers beneath the watershed.
# With all those monsters there, we can't get them back.}
{204}{}{也许吧，但是零件在水口下方的下水道里，那里怪物很多，我们拿不回来。}

#{205}{}{Sorry, I wish I could help.}
{205}{}{对不起，爱莫能助。}

#{206}{}{I'll find the parts.}
{206}{}{我去找零件。}



############ Tell Me Abouts

{1000}{}{Set}
{1001}{}{Master}
{1002}{}{Water}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Necropolis}
{1006}{}{Chip}

#{1100}{}{He tries to control Necropolis, and has forced us underground.}
{1100}{}{他试图控制整个大墓地，还把我们赶到地下。}

#{1101}{}{He has something to do with the Mutants. I don't know much more.}
{1101}{}{他和变种人有联系，我也不知道太多。}

#{1102}{}{We get our water from the place under the Watershed. It might have something to do with that.}
{1102}{}{我们从水口下面的地方得到水，可能和那个地方有关系。}

#{1103}{}{The broken water pump is there. Also, that's where the Mutants hand out the water from their new source.}
{1103}{}{坏掉的水泵在那里，变种人在那里分发水。}

#{1104}{}{Set's so-called palace.}
{1104}{}{赛特所谓的宫殿。}

#{1105}{}{City of the Dead, where we would like to live peacefully, if Set or the Mutants will let us.}
{1105}{}{死城，我们希望和平地生活，可惜变种人和赛特不让。}

#{1106}{}{We get our water from the place under the Watershed. It might have something to do with that.}
{1106}{}{我们从水口下面的地方得到水，可能和那个地方有关系。}

