{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a peasant.}
#{101}{}{Oh, yeah, big man running from a scary dog. Phil,
# you sure showed it. Yep, you sure did.}
#{102}{}{What are you doing, Phil? You're checking the tread on those
# sneakers, aren't you?}
#{103}{}{Man, that dog looks hungry. It sure wants to eat you alive,
# Phil.}
#{104}{}{That might be a little overkill for a poor
# defenseless animal, don'cha think?}
#{105}{}{That sure is a nice pooch you have there.}
#{106}{}{I'm sure Phil would appreciate it if you were
# to get rid of his dog.}
#{107}{}{Thanks for dealing with that dog.}
#{108}{}{You see Lenore.}
{100}{}{你看到一位农民。}
{101}{}{靠，大个子男人被狗赶得满地跑。费尔，你可真够种那。}
{102}{}{费尔，你在干嘛？满地找鞋印啊？}
{103}{}{吼吼，那条狗看起来很饿。它会活活吃掉你的，费尔。}
{104}{}{这样对待一条可怜的小狗似乎有点过头了，您说呢？}
{105}{}{那确实是条好狗。}
{106}{}{如果你帮费尔摆脱那条狗，他会很感激你的。}
{107}{}{非常感谢你摆平了这条狗。}
{108}{}{你看到勒诺。}
