#{100}{}{The hairs on the back of your neck rise. You feel something from the
# corridor ahead. The bile rises as your recognize the mass of flesh ahead -
# human parts in the wall itself. The worst part is that it is moving,
# calling to you.}
{100}{}{脖颈后的头发不由竖了起来.你感到走廊的另一端有什么东西。当你意识到眼前的是一堆碎肉，来自深嵌于墙上的人类残破躯体，你感到一阵恶心。最糟的是那堆肉居然在蠕动，在呼唤着你。}


#{101}{}{Your nose starts to bleed. You hear voices in your head. They are
# calling your name. Darkness washes over your eyes for a moment, but you
# recover.}
{101}{}{你的鼻子开始流血，你听到有个声音在脑海里嗡嗡作响，它们呼唤着你的名字。你感觉眼前骤然一黑，但随即又恢复了知觉。}


#{102}{}{A voice calls to you. You turn you head and see the image of a
# forgotten friend, obviously dead. The worms fall from her rotted jaw as
# your headache grows.}
{102}{}{一个熟悉的声音呼唤着你，你转过头去，看见一个已遗忘的故人的影子，很明显他已经死了。蛆虫不断从他腐烂的下颌中掉出来，你的头更疼了。}


#{103}{}{It is getting harder to move forward. Your foot seems bonded to the
# floor. You look down, and the flesh of the floor is crawling up your leg.
# Teeth gnaw at your knees. Still, your headache gets worse.}
{103}{}{继续前行愈发的困难了，你的脚似乎粘到了地板上。你往下看，地板上的碎肉正沿着你的小腿蠕动着向上爬，牙齿啃噬着你的膝盖，还有，你的头愈发的疼了。}


#{104}{}{Something catches your attention, a flash of movement from the
# ceiling, and then a sliver of bone pierces your eye! With it comes the
# thoughts of the dead and tortured!}
{104}{}{你注意到了一些东西在天花板上以迅雷之势掠过，随即骨头的碎片就刺穿了你的眼睛！无数有关折磨与死亡的念头刹那间涌上心头。}



#{105}{}{The pain in your head is maddening. You feel the sins of others
# wash over your soul. And it gets worse, as your sins answer them. Like
# madmen, they fight through your psyche, and in the process tear your
# personality apart.}
{105}{}{头痛令你发疯，你感到他人的罪孽正如洪水般试图吞没你的灵魂，更糟的是你灵魂中邪恶的部分正在回应。像疯子那样，它们以你的灵魂为战场，逐步将你的人格一层层剥离出来。}


#{106}{}{Your head is pulsing with the intrusive thoughts of others. The
# pain grows and grows. Suddenly, as if it never existed, the pain vanishes.
# You fall to the ground and weep. But something does not feel right.}
{106}{}{你的大脑被那些不断侵入的，来自于他人的想法猛烈冲击着，头痛愈发的剧烈了。突然，就好像从未存在过那样，头痛消失了，你瘫倒在地上，但总有些感觉不对劲。}



#{107}{}{The pain in your head does not feel as bad as it did. The effects of
# this strange corridor do not feel as strong.}
{107}{}{你的头痛已经减轻了，这个古怪走廊的影响也没有那么强烈了。}

