{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a dirty, grubby prisoner.}
{100}{}{你看见一个又肮脏又邋遢的囚犯。}

#{101}{}{One prisoner in the second cell is not like the others. He stands
# tall and looks you squarely in the eye.}
{101}{}{在第二个房间的犯人和其它房间的不太一样。他是个大个子，站在那里盯着你。}

#{102}{}{The prisoner stares blankly at the wall.}
{102}{}{囚犯茫然的看着墙壁。}

#{103}{}{The prisoner ignores your attempts to talk.}
{103}{}{囚犯根本没有理会你和他说话。}

#{104}{}{He looks wildly at you for a moment, and then turns away.}
{104}{}{他用毫无顾忌的眼神看了你一会，然后扭头回去了。}

#{105}{}{She looks at you for a moment, and then drools.}
{105}{}{她看了你一会，然后开始流口水说胡话。}

#{106}{}{You get no response.}
{106}{}{你没有得到回应。}

#{107}{}{We're free! We're free!}
{107}{}{我们自由了！我们自由了！}

#{108}{}{Your kind is repugnant. Do not speak to me.}
{108}{}{你和我们不是一个种类。不要和我讲话。}

#{109}{}{Quib!}
{109}{}{垃圾！}

#{110}{}{You don't have the right to speak to me like that.}
{110}{}{你没有权利对我那样说话。}

#{111}{}{You don't understand. I'm here to free you.}
{111}{}{你不明白。我是来放你出去的。}

#{112}{}{Do not mock me.}
{112}{}{别来耍我。}

#{113}{}{I have no rights, and I could care less. Go away, and leave us alone.}
{113}{}{我没有这个权利，我也不关心，你快走，让我独自待会。}

#{114}{}{I refuse to tell you any information. Leave me alone.}
{114}{}{我不会告诉你任何事情。走开。}

#{115}{}{Hng!!}
{115}{}{吼！！}

#{116}{}{I'm really here to free you. I'm a normal human.}
{116}{}{我真的是来这里放你们走的。我是一个正常的人类。}

#{117}{}{If you want it that way. Sure. Goodbye.}
{117}{}{如果你想要那样。没问题。再见。}

#{118}{}{Don't you remember that you tried that trick last week? I didn't
# fall for it then, and I'm not going to start now.}
{118}{}{你不记得上周骗我的小手段了吗？上次我没有上当，这次也不会。}

#{119}{}{What? No cowl to hind behind? Your traitorous nature is self-evident.}
{119}{}{什么？没有穿长袍？你就是坏人！}

#{120}{}{I'm here to free you.}
{120}{}{我是来让你们获得自由的。}

#{121}{}{Goodbye, then.}
{121}{}{那么再见。}

#{122}{}{You are cruel. Leave us alone.}
{122}{}{残忍的人。离我们远点。}

#{123}{}{I won't spill the beans about my people. You cannot force a man to
# betray himself, you can only force a man to stop living.}
{123}{}{我不会出卖我们的人，你可以要了我的命，但是不能让我违背良心。}

#{124}{}{You really don't get it. I'm a human being, here to rescue here.}
{124}{}{你真的不明白嘛。我是一个人类，到这里来救你们。}

#{125}{}{I don't even have to force you to rot in hell. You're doing a fine
# job on your own.}
{125}{}{我不逼你在这个该死的地方继续腐烂。你随便好了。}

#{126}{}{You're still mocking me.}
{126}{}{你还在嘲笑我。}

#{127}{}{From the mouth of a man comes the serpent's words.}
{127}{}{从一个男人嘴里吐出了阴毒的字眼。}

#{128}{}{Right, I could guess that. Go away, and leave us alone.}
{128}{}{对，我能猜出来。走，离我们远点。}

#{200}{}{The prisoner looks dirty and tired. A collar around their neck is
# shiny and new.}
{200}{}{那囚犯看上去又肮脏又邋遢。他的脖子上戴着一个发亮的新项圈。}

#{201}{}{The prisoner looks back at you with a blank stare. You notice a
# collar around their neck.}
{201}{}{那囚犯空洞的望着你的身后。你注意到他们的脖子有一个项圈。}

#{300}{}{A sign on the wall reads: 'No Entrance. Secure Area. Prisoner
# Handlers Only!'}
{300}{}{在墙上的告示写着：“闲杂人员禁止入内。限制区域。囚犯看守除外。}

#{301}{}{You gain }
{301}{}{你得到了}

#{302}{}{ experience points for releasing prisoners from misery.}
{302}{}{点经验值，因为你把囚犯从痛苦中解救出来。}

