{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

# {100}{}{Before you is a Mach IV Computer.}
# {101}{}{It seems as though the system is in a reboot status.}
# {102}{}{The system seems to have locked up.}
# {103}{}{The monitor flickers.}
# {104}{}{The screen is showing odd color patterns.}
# {105}{}{The computer screen is displaying small green bombs falling endlessly towards the ground.}
# {106}{}{You cannot hack the screen password.}
# {107}{}{You access some electronic notes. The most interesting is a request from the Lieutenant for "...more human subjects to dip. Send them immediately to the Military Base."}
{100}{}{在你前面的是一台马赫IV型计算机}
{101}{}{好像系统正在重新启动。}
{102}{}{它的系统似乎已经被锁定了。}
{103}{}{这监视器不停的闪烁。}
{104}{}{这个屏幕显示一些奇怪的图案。}
{105}{}{这个屏幕上显示着一些绿色的炸弹不停的落下。}
{106}{}{你不能解开这个屏幕保护密码。}
{107}{}{你找到一些数据，最有趣的是来自副官的申请“……更多的人类试验品到货，马上送他们去军事基地。”}
