{1099}{}{?}
{1199}{}{我可以告诉你：Overseer-所长。}

#{100}{}{You! Stop right there and face the law!}
{100}{}{你！住手，你敢无视法律！}

#{101}{}{Thank you for returning the water-chip. It's really
# going to help morale, and keep people from breaking vault law.}
{101}{}{多谢你归还净水芯片。它真的能提升士气，还大大降低了避难所的犯罪率。}

#{102}{}{Good to see you again. Is there anything that I can do for you?}
{102}{}{很高兴再见到你。我能为你做些什么？}

#{103}{}{What do you do?}
{103}{}{你做什么呢？}

#{104}{}{Yeah, I need some weapons.}
{104}{}{是的，我需要些武器。}

#{105}{}{Why would there be a locked door in the Vault?}
{105}{}{为什么避难所会有一扇锁住的门？}

#{106}{}{Glop!}
{106}{}{嗝咯！}

#{107}{}{Hmmm. I think you should be somewhere else besides here. Have a nice day.}
{107}{}{嗯。我认为你最好待在别的地方而不是这儿。走好。}

#{108}{}{I'm in charge of Vault security and law enforcement.
# You might not know it, but the Vault wouldn't run as well if it wasn't for me.}
{108}{}{我主管避难所的安全和执法。你可能不知道我, 但是如果没有我，避难所不可能运行得这么好。}

#{109}{}{Hmm. Neat. Thanks.}
{109}{}{恩，非常好。谢谢。}

#{110}{}{Sounds important.}
{110}{}{听起来挺重要。}

#{111}{}{It is. Without proper adherence to the laws, the Vault
# would soon be a lawless place, with no direction. That would jeopardize
# the safety of us all.}
{111}{}{的确如此。如果法律得不到维护，避难所很快就会无法无天。那会危害你我和所有人的安全。}

#{112}{}{Now that I've been outside, are there any laws that
# apply specifically to me?}
{112}{}{我现在在外面，有什么特别的法律管我？}

#{113}{}{I've seen some places on the outside world that suffer
# because they have no laws.}
{113}{}{我在外面的很多地方看到，因为没有法律而动荡不安。}

#{114}{}{Well, even if weapons are required on the outside world,
# don't display them in a threatening manner in here.
# Other than that, I can't think of anything in particular.}
{114}{}{呃，虽说出门在外带武器是必需的，但也不要在这里拿出来恐吓人。至于其他，我还想不出什么特别的。}

#{115}{}{Thanks.}
{115}{}{谢谢。}

#{116}{}{You see, I knew that would happen. People obeying law
# is the only thing that has saved the Vault from misery
# and destruction. Keep up the good work.}
{116}{}{你瞧，我就知道会是那样。遵纪守法是唯一让避难所免受灾难和痛苦的方法。好好干吧。}

#{117}{}{The Overseer has not authorized me to open the armory and
# get you more weapons. I'm sorry, but I can't help you. }
{117}{}{所长没授权，所以我不能打开军械库给你更多武器。我很抱歉，我帮不了你。}

#{118}{}{Please! I really need them!}
{118}{}{求你了！我真的需要它们！}

#{119}{}{Ok. Thanks, anyways.}
{119}{}{好吧。不管怎样还是谢谢。}

#{120}{}{No. I can't do it.}
{120}{}{不。我不能那样做。}

#{121}{}{Have a nice day.}
{121}{}{祝你愉快。}

#{122}{}{To keep the weapons away from those who don't have
# access to them.}
{122}{}{确保没有武器使用权的人接触不到它们。}

#{123}{}{Who has access?}
{123}{}{谁有使用权？}

#{124}{}{That doesn't seem very fair.}
{124}{}{似乎不太公平。}

#{125}{}{Life isn't fair, sometimes. But our law is. Have
# a nice day.}
{125}{}{有时候，生活就是不公平的。但我们的法律很公平。祝你愉快。}

#{126}{}{The Overseer, myself and my security team. That's it.}
{126}{}{所长，我自己以及我的执法小队。就这些。}

#{127}{}{It sounds like only people with need have access.}
{127}{}{听起来像是只有需要它的人才有使用权。}

#{128}{}{That's really a small list.}
{128}{}{就这么些人，真少。}

#{129}{}{Yes, it is. I have to get back to work.}
{129}{}{是的，我必须回去工作了。}

#{130}{}{Yes, only people with need can get in.}
{130}{}{是的，只有有需求的人才能进入。}

#{131}{}{Well, I have need. Please open the door.}
{131}{}{好，我有需要。请打开门。}

#{132}{}{I'm sorry, it's a good argument, but I can't let you in.}
{132}{}{抱歉，这理由不错，但我不能让你进入。}

#{133}{}{Hmm. Now that you mention it, it sounds like you do. Here,
# let me get the door for you.}
{133}{}{唔。你这么一说，听起来的确需要。来，让我给你开门。}

#{134}{}{What can I do for you, }
{134}{}{我能为你做什么，}

#{135}{}{?}
{135}{}{？}

#{136}{}{I need more weapons.}
{136}{}{我需要更多武器。}

#{137}{}{You feeling ok?}
{137}{}{你感觉还好吗?}

#{138}{}{Huh-huh.}
{138}{}{咳-咳。}

#{139}{}{Great. Your intelligence staggers me. I can't possibly
# think anymore.}
{139}{}{你牛啊，都把我说晕了。我的脑子几乎不能再转了。}

#{140}{}{Sorry, you've gotten all we can spare. Good day.}
{140}{}{对不起，你已经拿了我们能给出的全部。走好。}

#{141}{}{I don't like your kind. Rabble-rousers. You should be ashamed.}
{141}{}{我不喜欢你这种蛊惑民心的人。你该感到羞耻。}

#{142}{}{Yeah, well, same to you, muttonhead.}
{142}{}{是啊，没错，和你一样，猪头。} 

#{143}{}{Don't you think you're being a little harsh?}
{143}{}{你不觉得你有些太苛刻了吗？}

#{144}{}{Watch your language, or I'll bring you in for failure
# to respect a law enforcement officer.}
{144}{}{嘴巴放干净些，否则我就以不尊重执法官的罪名把你抓起来。}

#{145}{}{Yeah, right. See you around.}
{145}{}{哦，是呀。回见了您呐。}

#{146}{}{That's it. I'm fed up with you rousting me.}
{146}{}{到此为止。我受够了你的挑衅。}

#{147}{}{Hmm. Possibly. It should be my job to be impartial,
# but I might have stepped over the line this time.
# I'll try and do better in the future.}
{147}{}{唔。可能。我的工作本是捍卫公正，但这次我也许有点过分了。将来我会努力做好的。}

#{148}{}{Hmm. No. Probably not harsh enough.}
{148}{}{唔。不。我看可能是不够苛刻。}

#{149}{}{Good luck. I hope you can do the job.}
{149}{}{好运。我希望你能做到。}

#{150}{}{You'd better not let me down.}
{150}{}{你最好别让我失望。}

#{151}{}{Put your weapon away, right now.}
{151}{}{立即把武器放下。}

#{152}{}{What do you think you are doing with that in here?}
{152}{}{你带着那东西在这里想做什么？}

#{153}{}{Just practicing my aim.}
{153}{}{只不过试试我的准星。}

#{154}{}{Nothing, sorry. Didn't mean to have it drawn.}
{154}{}{没什么，抱歉。我不是故意要把它拿出来的。}

#{155}{}{Hung.}
{155}{}{哼。}

#{156}{}{Be careful what you call me. And don't draw a weapon
# inside. This is the Vault for god's sake.}
{156}{}{注意你对我的称谓。也不要在室内拿出武器。看在上帝的份上这可是个避难所。}

#{157}{}{You'd better not be practicing it in here. Me and you
# will have a serious problem if you do it again.}
{157}{}{你最好别在这弄。下回你再这么做的话，你我之间就有大麻烦了。}

#{158}{}{I knew that outside life would get you into trouble.}
{158}{}{我就知道野外生活会给你惹上麻烦。}

#{159}{}{Halt! You're not permitted in there!}
{159}{}{站住！你没有进入那里的许可！}

{1000}{}{Overseer}

#{1100}{}{He is the supreme authority of the Vault. The Vault answers to his
# decisions.}
{1100}{}{他是避难所的最高权威，决定着避难所的未来。}