{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a Knight.}
#{101}{}{You see a Scribe.}
#{102}{}{What are you doing here?}
#{103}{}{Who are you?}
#{104}{}{Haven't I seen you before?}
#{105}{}{This is my room, please leave.}
#{106}{}{Please leave my room.}
#{107}{}{This isn't your room.}
#{108}{}{Initiate rooming is on the second level.}
#{109}{}{Are you lost?}
#{110}{}{I believe your quarters are on level two.}
#{111}{}{I'd appreciate some privacy.}
#{112}{}{Hi there, nice to see you.}
#{113}{}{Hello.}
#{200}{}{Hi}
#{201}{}{Hello}
#{202}{}{Good day}
#{203}{}{Yes?}
#{204}{}{What?}
#{205}{}{Whats up?}
#{206}{}{What do you want?}
#{207}{}{You want something?}
#{209}{}{Go away}
#{210}{}{Stop bothering me}
#{211}{}{Leave me alone}
#{212}{}{You are annoying me}
#{213}{}{He ignores you}
#{214}{}{She ignores you}

{100}{}{你看到一个骑士。}
{101}{}{你看到一个研究员。}
{102}{}{你在这里做什么？}
{103}{}{你是谁？}
{104}{}{以前我见过你吗？}
{105}{}{这是我的房间，请离开。}
{106}{}{请离开我的房间。}
{107}{}{这不是你的房间。}
{108}{}{新兵宿舍在第二层。}
{109}{}{你迷路了？}
{110}{}{我确信你的住所在第二层。}
{111}{}{能让我有点隐私，我会感激的。}
{112}{}{嗨，你好，看到你真好。}
{113}{}{你好。}
{200}{}{嗨}
{201}{}{你好}
{202}{}{再见}
{203}{}{嗯？}
{204}{}{什么？}
{205}{}{你最近在做什么？}
{206}{}{你想要什么？}
{207}{}{你想要什么东西？}
{209}{}{走开}
{210}{}{别来打拢我}
{211}{}{别烦我}
{212}{}{你让我感到很讨厌}
{213}{}{他不理睬你}
{214}{}{她不理睬你}

