{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{The hairs on the back of your neck rise. You feel something from the corridor ahead. The bile rises as your recognize the mass of flesh ahead -
# human parts in the wall itself. The worst part is that it is moving,
# calling to you.}
{100}{}{你脖子后面的头发都竖起来了。你感觉到走廊前方有些东西。当你发觉前面有大堆的肉块——人的残肢短臂在墙上时，你的怒气开始发作。它在动，在召唤你，这是最可怕的事情。}
#{101}{}{Your nose starts to bleed. You hear voices in your head. They are calling your name. Darkness washes over your eyes for a moment, but you recover.}
{101}{}{你的鼻子开始出血。你听见有声音在你脑中回响。它们在叫你的名字。你眼前一黑，但马上又恢复了。}
#{102}{}{A voice calls to you. You turn you head and see the image of a forgotten friend, obviously dead. The worms fall from her rotted jaw as your headache grows.}
{102}{}{一个声音在召唤你。你转过身去，看见一个被遗忘的朋友，很显然她已经死了。当看见虫子从她腐烂的额头里掉出来时，你的头开始剧烈地疼痛。}
#{103}{}{It is getting harder to move forward. Your foot seems bonded to the floor. You look down, and the flesh of the floor is crawling up your leg. Teeth gnaw at your knees. Still, your headache gets worse.}
{103}{}{向前走变得困难起来了。你的脚好象被绑在了地上。你低头看，地上的碎肉爬上了你的腿。牙齿咬着你的膝盖。你的头痛越来越厉害了。}
#{104}{}{Something catches your attention, a flash of movement from the ceiling, and then a sliver of bone pierces your eye! With it comes the thoughts of the dead and tortured!}
{104}{}{有些东西吸引了你，一个亮光从天花板上闪过，然后一个银色的骨头刺穿了你的双眼！它使你想到了死亡和磨难。}
#{105}{}{The pain in your head is maddening. You feel the sins of others wash over your soul. And it gets worse, as your sins answer them. Like
 # madmen, they fight through your psyche, and in the process tear your personality apart.}
{105}{}{头痛使你发狂。你感到别人的罪恶冲刷着你的灵魂。当是的罪恶迎合它的时候，它变得越来越厉害。像疯子一样，它们打击着你的精神，把你的人格撕个粉碎。}
#{106}{}{Your head is pulsing with the intrusive thoughts of others. The
# pain grows and grows. Suddenly, as if it never existed, the pain vanishes.
# You fall to the ground and weep. But something does not feel right.}
{106}{}{你的头被别塞入了别人侵犯性的思想。疼痛越来越厉害。突然，它消失了，再也不出现了。你倒在地上，呜呜地哭泣。你觉得很不对劲。}
#{107}{}{The pain in your head does not feel as bad as it did. The effects of this strange corridor do not feel as strong.}
{107}{}{你的头不那么痛了。这个奇怪的走廊的影响不那么强烈了。}
