{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Richie.}
{100}{}{你看见瑞奇。}

#{101}{}{You're not supposed to do that. I'm gonna have to stop you!}
{101}{}{你不能那么做。我不得不阻止你！}

#{102}{}{You're not supposed to be here. Do you realize I'm supposed to kill you?}
{102}{}{你不能呆在这里，你没意识到我会杀了你吗？}

#{103}{}{Your shift is over. I'm your replacement.}
{103}{}{你的工作时间结束了，下一个轮到的是我。}

#{104}{}{Hub vault inspector. I'm here to inspect the vault. Move aside.}
{104}{}{哈勃城避难所的巡视员，我来这里的目的是巡视这个避难所。让开。}

#{105}{}{Kid, fight it. End the cycle of violence now!}
{105}{}{小子，动手吧。从现在开始结束这无休止的暴力！}

#{106}{}{Who told you that! Mister, if you attack me, it'll be the biggest mistake of your life!}
{106}{}{这是谁告诉你的！先生，如果你敢碰我，那么你会后悔一辈子的。}

#{107}{}{Hi kid! What's in the steel vault?}
{107}{}{嘿，小子！在这个钢铁避难所里有些什么？}

#{108}{}{Too late, punk. You're dead.}
{108}{}{太晚了，小流氓。你死定了。}

#{109}{}{Uh?yeah?runk厎
{109}{}{哦？是吗？咯咯。}

#{110}{}{I'm not supposed to be talking to you! Scram!}
{110}{}{我（有任务）,不能和你闲聊！滚开！}

#{111}{}{It's about time! It's hot in here! Boring too! If I didn't need this job to feed my family, I'd tell
# Lorenzo to stick it. See you tomorrow.}
{111}{}{是时候了！这里真热！而且还很无聊！如果不是需要这个工作来养家户口的话，我会叫罗仑佐来做这个。明天见。}

#{112}{}{I'm not supposed to leave this place and you're not supposed to be here. Get out!}
{112}{}{我不想离开这个地方，而你也别想留下来。离开这里！}

#{113}{}{You Hub officials make me sick! Inspecting my bosses' vault! What's next, higher taxes? Can't a man
# earn an honest living anymore without you bureaucrats trying to control everything? One of these days we're
# going to take a stand. Yeah, one of these days the common man is going to give you fatcats a knee to the
# balls like you deserve. One of these days we'll get you real good?I can't wait?By the way, it's not meant
# personal. I know you're just doing your job. I'll get out of your face while you do your inspection. Bye.}
{113}{}{你这个哈勃城的官员真让我不舒服！检查我老板的避难所！接下来，还要提高税务？没有你这些官僚管这管那我们就不能遵纪守法的活着吗？总有一天我们会站起来。是的。总有一天我们这些平民会像踢球一样把你们这些人都踢飞，这都是你们应得的。总有一天，我们会要你好看，嗯？我几乎都等不及了？顺便说一下，我不是对你个人有意见。我知道你仅仅是执行公务。在你履行公务的时候，我才不鸟你们呢，再见。}

#{114}{}{Don't give me this crap! Get outta here now or I'll have to shoot you!}
{114}{}{别跟我说这种废话！现在就闪开，不然我真要开枪打你了！}

#{115}{}{Oh yeah. Well no one pushes around Richie Glowsteader and gets away with it!}
{115}{}{噢，是这样。的确，没有人能在胁迫瑞奇·格罗斯蒂尔后安然离开！}

#{116}{}{Oh just about ten thousand Hub Bucks. Hope you weren't thinking of stealing it. I'd have to kill
# you. I almost killed someone once, so you don't want to mess with me!}
{116}{}{啊，只不过是一万个哈勃币。希望你不要打这笔钱的主意。不然，我会杀了你的。上次我已经把某个不知好歹的打了个半死，所以你给我放聪明点，别添乱！}

#{117}{}{Man, you're stupid. Oh, sorry, I didn't mean to offend you. Now let's try this again. "Yes" means I
# blow your head off. "No" means you get your butt out of here. Which is it going to be?}
{117}{}{伙计，你真是够蠢的。哦，对不起，我没有冒犯你的意思。现在我们换个方式说话。“是”的意思是我把你的头轰飞。“不是”的意思是你给我夹着尾巴滚开。你选择哪一个？}

#{118}{}{Ah . . . yes . . .}
{118}{}{嗯……是……}

#{119}{}{Uh?no.}
{119}{}{嗯？不？}

#{120}{}{Runk! Runk!}
{120}{}{吼吼！吼吼！}

#{121}{}{Man, I can't do it! It'd be like shooting a dumb animal. Just get outta here, okay?}
{121}{}{伙计，我不能这么干！这就好比打死一个没脑子的畜牲。现在快从这里离开，成不成？}

#{122}{}{That's good. Now run along now. I'm sure you might find someone to feed you厎
{122}{}{不错。现在快滚吧。我敢肯定你能找到点什么东西来满足你自己！}

#{123}{}{Maybe one runk means "yes" and two runks mean "no". Okay, "runk" means I kill you. "Runk, runk" means
# you leave. Okay?}
{123}{}{也许一个吼吼的意思是“是的”而两个吼吼的意思是“不是”。好，“吼吼”的意思是我杀了你。“吼吼，吼吼”的意思是你可以离开。怎么样？}

#{124}{}{Runk}
{124}{}{吼吼}

#{125}{}{Runk, runk.}
{125}{}{吼吼，吼吼。}

#{126}{}{Runk, runk, runk!}
{126}{}{吼吼，吼吼，吼吼！}

#{127}{}{Three runks. Shit, this isn't working. Maybe I'll just ignore you and you'll wander off.}
{127}{}{三个“吼吼”。狗屎，这是他们的什么破事。也许我应该当你不存在，快滚蛋。}