{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

# {100}{}{You see Rufus.}
# {101}{}{Please don't kill me厎
# {102}{}{Shhhh! I'm trying to play my game!}
# {103}{}{Quiet! I'm trying to play my game. Cyberhood, Prince of the Matrix, what a classic!}
# {104}{}{Damn! My character got beat up again. Roger is such a wimp厎
# {105}{}{Where is the key to Cyberspace? I've been all over the damn Kruz building厎
# {106}{}{You wouldn't happen to know the password into Malibu Stu's? Oh, never mind厎
# {107}{}{That Kaira, what a fox!}
# {108}{}{Don't bother me. I'm trying to solve this damn duck puzzle厎
{100}{}{你看到鲁弗斯。}
{101}{}{请不要杀我。}
{102}{}{嘘！我正打算玩我的游戏！}
{103}{}{安静！我正打算玩我的游戏！赛博帝国，母体的选民！真是经典之作！}
{104}{}{可恶！我的角色又完蛋了，浪游者这种职业太逊了。}
{105}{}{网络次元空间的钥匙在哪里？我在该死的库陆兹大厦里翻遍了。}
{106}{}{你不想知道进入美宜堡的密码吗？唉，别介意。}
{107}{}{那个凯拉真是个狐狸精！}
{108}{}{别打扰我。我正在试着解开这道该死的鸭子谜语。}
