{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Shark.}
{100}{}{你看见沙克。}

#{101}{}{You see a man with filed teeth.}
{101}{}{你看见一个长着利齿的人。}

#{102}{}{You bitch!}
{102}{}{你这婊子！}

#{103}{}{Hey, fresh bait! So, what brings you in to our territory, chum? Here for a little fun? At your expense, of course.}
{103}{}{嘿！新人！那么，是什么风把你吹到我们的地盘来的，伙计？来这找点乐子？这要看你出手是不是大方啦。}

#{104}{}{Actually, I'm here to kick butt and chew gum . . . you can guess the rest.}
{104}{}{实际上，我来踢人的屁股和嚼口香糖……你能猜出我要干什么。}

#{105}{}{What do you do for fun around here?}
{105}{}{你在这玩什么？}

#{106}{}{Uh, I was just leaving. Bye.}
{106}{}{呃，我要走了。再见。}

#{107}{}{Just stopped by for a drink and some . . . entertainment.}
{107}{}{停下来喝一杯，再来点……好玩的。}

#{108}{}{Glopf!}
{108}{}{哎呀！}

#{109}{}{We beat up posers like you!}
{109}{}{我们干掉像你这样的麻烦！}

#{110}{}{Not so fast! Nobody just walks into our place without payin' the pain tax. }
{110}{}{慢着！没人在我们的地盘上打个滚还能好端端的站起来。}

#{111}{}{I think you'll do. Boys, grab her.}
{111}{}{我想你会这么做的。小的们！抓住她！}

#{112}{}{Let me introduce you to the tax man. He's called Mr. Sledgehammer!}
{112}{}{让我介绍你去见收税人。他叫做“无敌霹雳大锤子！”}

#{113}{}{I don't think so!}
{113}{}{我不这样认为！}

#{114}{}{Well, for this evening's entertainment, we've decided to thrash this place! Heh. Grab what you can carry and let's see some blood run, eh?}
{114}{}{好吧，为了今晚的娱乐，我们决定血洗这个地方！哈。烧杀抢掠吧，让他们血溅五步！好不好？}

#{115}{}{Think I'll just grab a brew.}
{115}{}{我会弄到酒的。}

#{116}{}{Smash and grab? Count me in!}
{116}{}{烧杀抢掠？算我一个！}

#{117}{}{Not tonight, I have a headache.}
{117}{}{今晚不行，我脑瓜子不舒服。}

#{118}{}{Nah, I'd rather have something to eat . . . perhaps grilled shark!}
{118}{}{不，我宁愿吃些东西……也许是烤鲨鱼！}

#{119}{}{Ah, you loser. Go run back to your momma.}
{119}{}{啊，你这懦夫。找你妈妈去吧！}

#{120}{}{You again? Geez, some people just don't learn!}
{120}{}{又是你？老天，有的人就不会吸取教训！}

#{121}{}{Just stopped in for a quick drink.}
{121}{}{喝一杯就走。}

#{122}{}{Just leaving, never mind.}
{122}{}{我走，别在意。}

#{123}{}{Glorpf!}
{123}{}{哎呀！}

#{124}{}{Not a bad idea. Think I'll have one myself. Of course, you always have to wash a beer down with some bloodshed!}
{124}{}{不错的主意。我自己会弄的。当然，你经常要用血来冲掉啤酒吧！}

#{125}{}{I thought you'd get the picture by now, to beat it. Guess I was wrong. Well, at least it'll be fun to beat you!}
{125}{}{我想你现在明白了，就是这么做。我猜我错了。好吧，至少揍你应该很好玩！}

#{126}{}{We'll be back, old man. This isn't over.}
{126}{}{我们会回来的，老不死的。这事没完。}