{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Sinthia, the seductive sellbaby.}
{100}{}{你看见辛西娅，一个诱人的街头女郎。}

#{101}{}{You see a pouty, shapely woman.}
{101}{}{你看见一个噘着嘴，身材很好的女人。}

#{102}{}{Hey, darling, how you doing?}
{102}{}{嗨，亲爱的，你好吗？}

#{103}{}{Okay. Bye.}
{103}{}{还好。再见。}

#{104}{}{Just fine, but I could be better.}
{104}{}{很好，不过还可以更好。}

#{105}{}{Uhh.}
{105}{}{呃。}

#{106}{}{Oh, baby, I understand. You gotta run home to momma.
# Well, come back here when you need some luvin'!}
{106}{}{哦，宝贝，我明白了。你应该回家找妈妈去。等你需要一些安慰的时候再来这里吧！}

#{107}{}{Yeah, sweets, same to you.}
{107}{}{好的，小蜜糖，你也是。}

#{108}{}{You'll find whatever, or whoever, you're looking for,
# honey, and that'll make you all better, I'm sure.}
{108}{}{你会找到所有你要找的人或东西，亲爱的。你会喜欢上所有的一切，我肯定。}

#{109}{}{Maybe I can help you with that.}
{109}{}{也许我能帮助你。}

#{110}{}{Maybe you can. How much to you charge?}
{110}{}{也许你能。你要多少钱？}

#{111}{}{I wouldn't let my dog touch you.}
{111}{}{我的狗都不愿意碰你。}

#{112}{}{Oh, baby, if you got to ask . . . more than you can afford.
# Maybe next time, sugar. See you around.}
{112}{}{哦，宝贝，如果你真要问的话……你是负担不起的。也许下次吧，下次见，甜心。}

#{113}{}{Oh, sugar, that's just plain disgusting.}
{113}{}{哦，甜心，那可真恶心。}

#{114}{}{Oh, gawd, please help me.}
{114}{}{哦，上帝呀，请帮帮我吧。}

#{115}{}{Please don't let him kill me.}
{115}{}{请不要让他杀了我。}

#{116}{}{I'm too young to die.}
{116}{}{我还年轻，不想死啊！}

#{117}{}{Oh, gawd, I'm too pretty to die.}
{117}{}{哦，上帝，我这么漂亮，不应该死啊！}

#{118}{}{Thank you for what you did. No one ever took care of me like
# that before.}
{118}{}{谢谢你做的一切。从没有人这样照顾过我。}

#{119}{}{I can really take care of you later.}
{119}{}{一会我还可以更好地照顾你哩。}

#{120}{}{You're welcome.}
{120}{}{不用谢。}

#{121}{}{Unh.}
{121}{}{呃。}

#{122}{}{Thanks again.}
{122}{}{再次感谢你。}

#{123}{}{Is that all you can think about? Geez. Some people.}
{123}{}{那就是你想要做的吗？唉，某些人啊。}

#{124}{}{I mean, my boss didn't even send some of his goons to help.
# You'd think for all the cash I make for that loser, he
# would at least live up to his part of the bargain.}
{124}{}{我的意思是，我的老板甚至都不派几个他手下的白痴过来保护我。你想想看，我为那家伙挣了多少钱？没有我挣的那些钱他现在能做大买卖嘛！}

#{125}{}{Who's your boss?}
{125}{}{你的老板是谁？}

#{126}{}{What bargain?}
{126}{}{什么买卖？}

#{127}{}{Gizmo, of course. He runs all the sin in this town.
# Killian sure as hell wouldn't put up with me or my kind.
# If it wasn't for the fact that I make Giz a whole hell of
# a lot of money, I'd have to do other things to him.}
{127}{}{当然是吉斯莫。他经营这里的罪恶产业。基利安当然也不会来管像我这种人的死活。要不是我为吉斯莫赚了这么多钱，也许我会对他做些其它的事。}

#{128}{}{And, honey, those thoughts just don't do my stomach a whole
# lot of good.}
{128}{}{哎呀，甜心，那些事情想起来就让我恶心。}

#{129}{}{What else does Gizmo control?}
{129}{}{除了你之外，吉斯莫还控制了什么？}

#{130}{}{You should just hang it up and move on with your life.}
{130}{}{你还是别想这些了，好好生活下去。}

#{131}{}{You're telling me. But what else can I do? It seems like
# my life has been designed by someone else. Oh, well. A
# girl has to make a living.}
{131}{}{天知道。但我还能做些什么？就好像我的命运已被注定了。唉，一个女孩必须得生活下去呀。}

#{132}{}{But sugar, this one's for free.}
{132}{}{甜心，这次是免费的。}

#{133}{}{Thanks again, honey. We women gotta stick together.}
{133}{}{再次感谢你，甜心。我们女人应该团结在一起。}

#{134}{}{Just about every bad thing a person could do in this town.
# He owns the Casino. He runs me and some of the other
# gals, even some little kids. I hear he is trying to take
# over the bar.}
{134}{}{就是这个城镇中每个人可能做的所有坏事。他是赌场的主人。他管理我还有其他女孩，有些甚至还是幼女呢。我听说他还试图控制酒吧。}

#{135}{}{You stay away from him, okay? Take it from me, he is not
# the kind of patron he wants to make you think he is.
# Stay away.}
{135}{}{你离他远点行吗？听我说，他和你不是一路人，还是离开吧。}

#{136}{}{Giz wants to take care of Killian, if you get my meaning.}
{136}{}{吉斯莫想要好好照顾一下基利安，如果你明白我的意思的话。}

#{137}{}{Why, honey, I take care of men, and they take care of me in
# return. Gizmo gets 25% and I supposedly get his protection.
# You saw how well that went, huh?"}
{137}{}{唉，甜心，我照顾男人，作为报答他们也照顾我。吉斯莫得到我收入的25%，象征性地为我提供保护。你看到他把我保护得有多“好”了吧？}

#{138}{}{What else does Gizmo control?}
{138}{}{吉斯莫还控制了什么？}

#{139}{}{You feel like paying another visit to Sinthia.}
{139}{}{你觉得应该再拜访一下辛西娅。}

#{140}{}{Maybe Sinthia would like some company . . .}
{140}{}{也许辛西娅需要人来陪陪她……}

#{141}{}{You shit! You killed him! Why did you have to kill him?
# You bastard! I can't believe you killed him. All he wanted was someone to
# talk to. You don't care about human life, do you?}
{141}{}{你这肮脏的家伙！你杀了他！你为什么要杀了他？你这婊子养的！我不敢相信你杀了他。他只是想要找个人聊天罢了。你不在意人们的生命吗？}

#{142}{}{You shit! You killed him! Why did you have to kill him?
# You bitch! I can't believe you killed him. All he wanted was someone to
# talk to. You don't care about human life, do you?}
{142}{}{你这肮脏的家伙！你杀了他！你为什么要杀了他？你这婊子！我不敢相信你杀了他。他只是想要找个人聊天罢了。你不在意人们的生命吗？}

#{143}{}{Just get the hell out of my room!}
{143}{}{赶快滚出我的房间！}

#{144}{}{You killed him! I can't believe you killed him. All he
# wanted was someone to talk to . . .}
{144}{}{你杀了他！我不敢相信你杀了他。他只是想要找个人聊天罢了……}

#{145}{}{He ain't dead. He's just gonna have a hurt head when he
# wakes up.}
{145}{}{他没有死。不过他醒来的时候头会有些痛。}

#{146}{}{Hnnn.}
{146}{}{哼。}

#{147}{}{Yeah, whatever. Get the hell out of my room!}
{147}{}{是吗？去你的吧！赶快滚出我的房间！}

#{148}{}{Oh, sorry. I though he was dead. I though you killed him.
# He's not such a bad guy, after all. Just a little lonely.}
{148}{}{哦，对不起。我以为他死了。我以为你杀了他。毕竟他并不是一个很坏的人。他只是有些寂寞。}

#{149}{}{No problem.}
{149}{}{没关系。}

#{150}{}{You again. What can I help you with this time?}
{150}{}{又是你。这一次我能如何帮你呢？}

#{151}{}{Just stopping by to see how you are doing.}
{151}{}{我只是来看看你怎么样了。}

#{152}{}{I've got $40, if you got ten minutes.}
{152}{}{我有40块，如果你能给我十分钟的话。}

#{153}{}{I need some more info on your boss.}
{153}{}{我需要更多关于你老板的情报。}

#{154}{}{Ah, honey, I don't think so. Imagine how the children
# would turn out.}
{154}{}{啊，甜心，我可不这么想。不太好吧。}

#{155}{}{Doing fine, thanks to you, sugar.}
{155}{}{我很好，谢谢你，甜心。}

#{156}{}{What do you want to know, but make it short, honey, I'm on
# the clock.}
{156}{}{你想知道什么呢？但请说的简短一些，甜心，我还有事情呢。}

#{157}{}{How many guards does he have?}
{157}{}{他有多少守卫？}

#{158}{}{Where does he stash the money?}
{158}{}{他把钱藏在哪里？}

#{159}{}{Does he have any weaknesses?}
{159}{}{他有什么弱点吗？}

#{160}{}{Thanks, doll, but I don't need to know anything else.}
{160}{}{谢谢你，宝贝，我不想知道别的什么了。}

#{161}{}{Hmm. I know about eight, personally, if you get my meaning.
# I think he has another ten or so.}
{161}{}{嗯。我知道他有八个守卫，但我想他应该另外还有十个左右。}

#{162}{}{Money? How would I know? He only takes my money, he doesn't
# show me his. I would guess that it's in his bedroom,
# but for all I know, he could keep it where the sun doesn't
# shine. And for Giz, that's a big place.}
{162}{}{钱？我怎么会知道呢？他只是从我这里把钱拿走，从来不把他的钱拿给我看。我想大概是在他的卧室里，但根据我对他的了解，他只会把钱放在见不到阳光的地方，而对于吉斯莫来说，这样的地方太多了。}

#{163}{}{Only that he thinks he doesn't have any. Well, that and
# he's a fat slob, who can't move for a damn. He's got to
# have his guards help him move around. Even then, they gotta
# use a little tricycle. Heh heh.}
{163}{}{只有他自己才认为他没有什么弱点。他是个肥胖的笨蛋，一动都不能动。他甚至得让他的守卫抬着他才能四处走，而且还得用一辆三轮车拉着他。呵呵。}

#{164}{}{Sugar, you got a date.}
{164}{}{甜心，我们约会吧。}

#{165}{}{Sure, honey, for you.}
{165}{}{当然，甜心，只为了你。}

#{166}{}{I'll show you a good time.}
{166}{}{我会让你爽的。}

#{167}{}{Honey, you need some more money. I like you and all,
# but a girl has to make a living.}
{167}{}{甜心，你得再多拿些钱来。我喜欢你，但一个女孩得生活下去啊。}

#{168}{}{I reserve the right to refuse admittance, and honey,
# you ain't getting nowhere near me!}
{168}{}{我保留不让你进来的权利。甜心，你别想靠近我！}

#{169}{}{Sinthia is asleep.}
{169}{}{辛西娅睡着了。}

#{170}{}{Sinthia is busy.}
{170}{}{辛西娅在忙着。}

#{171}{}{Sinthia refuses to speak with you.}
{171}{}{辛西娅拒绝与你谈话。}

#{172}{}{Sorry, honey, I don't do freaks.}
{172}{}{对不起，甜心，我不能做不着调的事。}

#{173}{}{Take your cash, your attitude, and your small prick somewhere else!}
{173}{}{把你的钱，你那糟糕的态度和你的小鸡鸡拿到别的地方去！}

#{174}{}{Oh, gawd, somebody help me!}
{174}{}{哦，上帝啊，来人帮帮我！}

#{175}{}{You gain }
{175}{}{你得到}

#{176}{}{ experience for successfully rescuing Sinthia.}
{176}{}{点经验值，因为你成功地救了辛西娅。}

#{177}{}{The guards remove the raider while he is unconscious.}
{177}{}{守卫没等歹徒恢复知觉就把他带走了。}
