{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Slappy.}
{100}{}{你看见斯莱匹。}

#{101}{}{Boogie, Boogie, Boogie.}
{101}{}{我摆，我摆，我摆。}

#{102}{}{It's a bitty spider, smashin', smashin'.}
{102}{}{是个小蜘蛛，我砸，我砸。}

#{103}{}{Let's play Global Thermo-Nuclear War.}
{103}{}{让我们玩全球热核战争吧。}

#{104}{}{Where's my blankie!?!}
{104}{}{我的魔毯呢！？！}

#{105}{}{Da... Da... Da...}
{105}{}{哒……哒……哒……}

#{106}{}{The Moon is out there.}
{106}{}{月亮在那里！}

#{107}{}{Gimme' the Sugar Baby.}
{107}{}{给我糖糖，宝贝。}

#{108}{}{Oooh, pretty, pretty stuff.  Why is the moon?}
{108}{}{哦哦哦，漂亮，漂亮东西。为什么是月亮？}

#{109}{}{Uh, I talked with Harold.  The Deathclaw sounds pretty nasty.  What can you tell me about it?}
{109}{}{呃，我和哈罗德谈了。死亡爪听起来相当骇人。关于它你能告诉我什么？}

#{110}{}{Beth told me to talk to you about the Deathclaw.}
{110}{}{贝斯让我和你谈谈死亡爪的事。}

#{111}{}{What do you do around here?}
{111}{}{你在这做什么？}

#{112}{}{What's your problem?}
{112}{}{你有什么问题？}

#{113}{}{Moon Big, me like Moon!}
{113}{}{月亮大，我喜欢月亮！}

#{114}{}{All bright, it's all bright, the bright comes down, and then we are doomed.}
{114}{}{全是亮的，所有的都是亮的，这亮光降到地面，我们就死了。}

#{115}{}{Ahh.}
{115}{}{啊。}

#{116}{}{Deathclaw, Deathclaw, Dah Dah Deathclaw.}
{116}{}{死亡爪，死亡爪，死死死亡爪。}

#{117}{}{Come on, what do you know about the Deathclaw?}
{117}{}{告诉我，你知道哪些关于死亡爪的事情？}

#{118}{}{What's your problem?}
{118}{}{你有什么问题？}

#{119}{}{Don't make me pound it out of you!}
{119}{}{快说，别让我把你敲个稀碎！}

#{120}{}{Do, I, do, then you do, then we all do.}
{120}{}{做，我，做，然后你做，然后我们都做。}

#{121}{}{No really, what do you do.}
{121}{}{不是，你是干什么的。}

#{122}{}{You're a loony.}
{122}{}{你是个疯子。}

#{123}{}{Problems are like Soup Bowls, wide and shallow.}
{123}{}{问题像汤碗，又宽又浅。}

#{124}{}{That's more like your mind.}
{124}{}{那更像你的思想。}

#{125}{}{Deathclaw scary, really scary.  Looks neat though.  Wanna' see it?}
{125}{}{死亡爪吓人，真的很吓人。尽管看起来很干净。想看看它吗？}

#{126}{}{You can take me to the Deathclaw?}
{126}{}{你能带我去看死亡爪？}

#{127}{}{Hell no!}
{127}{}{当然他妈的不！}

#{128}{}{Yeah, Deathclaw, Deathclaw, going to see the Deathclaw.}
{128}{}{耶，死亡爪，死亡爪，我们去见死亡爪。}

#{129}{}{Just shut up and take me there.}
{129}{}{闭嘴，带我去那。}

#{130}{}{Ah, nevermind.  You take care, now.}
{130}{}{啊，别在意。你现在要当心了。}

#{131}{}{I do this, then I do that.  You see Harold?  Harold's fun, his hair falls out, falls in the wind.  There it goes... wind, wind.}
{131}{}{我做这个，然后我做那个。你看见哈罗德了？哈罗德很滑稽，他的头发掉光了，随风而去了。飞了……风，风。}

#{132}{}{Whatever.}
{132}{}{随便。}

#{133}{}{Pound and Pound, and Pound and Pound.}
{133}{}{敲啊敲，敲啊敲。}

#{134}{}{Why is the wind?  Why why why why why.}
{134}{}{为什么是风？为什么为什么为什么为什么为什么。}

#{135}{}{Beth, Beth, shoo sha Beth.  Like Harold, you talk Harold.  Harold tell you story.  Slappy help then.}
{135}{}{贝斯，贝斯，嘘嗄贝斯。喜欢哈罗德，你跟哈罗德唠。哈罗德给你讲故事。斯莱匹帮忙。}

#{136}{}{OK, I'll go talk to Harold first.}
{136}{}{好，我先去和哈罗德谈谈。}