{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see before you Talius, a member of the Followers.}
{100}{}{你看见塔琉斯，末世论者的成员。}

#{101}{}{Please depart. I am attempting to retire here. Come back during the day.}
{101}{}{请离开。我正要睡觉。等白天再来。}

#{102}{}{Greetings sister. My name is Talius. How might I assist you today?}
{102}{}{你好兄弟。我是塔琉斯。今天需要什么帮助呢？}

#{103}{}{Greetings brother. My name is Talius. How might I assist you today?}
{103}{}{你好姐妹。我是塔琉斯。今天我怎么才能帮助你？}

#{104}{}{Huh?}
{104}{}{哼？}

#{105}{}{Me }
{105}{}{我系}

#{106}{}{. Me }
{106}{}{。我系}

#{107}{}{.}
{107}{}{。}

#{108}{}{I am }
{108}{}{我是}

#{109}{}{. What are you doing here?}
{109}{}{。你在这做什么？}

#{110}{}{You can die!}
{110}{}{去死！}

#{111}{}{Don't worry about me Mutie! How did you get in here?}
{111}{}{先别管我，变种人！你是怎么到这来的？}

#{112}{}{Greetings to you as well. I am called }
{112}{}{也问候你。我叫做}

#{113}{}{. How is it that you came into the realm of the Followers?}
{113}{}{。你是如何加入末世论者的？}

#{114}{}{Can you tell me how one, of your alterations, entered the Followers?}
{114}{}{你能告诉我你是如何来到末世论者这里的吗？}

#{115}{}{I see that you are a little slow. I, too, was once of your intelligence.
# But, through the teachings of the Followers, I have been able to transcend
# my shortcomings.}
{115}{}{我看你有点迟钝。我曾经也和你的智力一样。但是通过末世论者的教学，我已经能够克服我的缺点。}

#{116}{}{No know.}
{116}{}{不知道。}

#{117}{}{Too smart. Die now.}
{117}{}{太聪明了。现在死吧。}

#{118}{}{I apologize. I forget myself at times. Would you like some brain help?}
{118}{}{我道歉。我有时忘乎所以。你想要一些帮助吗？}

#{119}{}{Yeah. You's!}
{119}{}{呀。是你！}

#{120}{}{You hep. You hep!}
{120}{}{你啊。你啊！}

#{121}{}{Here. Take these pretty pills. Make you smarter.}
{121}{}{这里。吃下这些漂亮的药丸，可以使你更聪明。}

#{122}{}{Yes, }
{122}{}{是的，}

#{123}{}{. I am enthusiastic that you acknowledge your given
# nomenclature. How might I assist you this fine morrow?}
{123}{}{。我很高兴你能记得自己的名字，我今天能够帮你什么？}

#{124}{}{Wha?}
{124}{}{唔？}

#{125}{}{Brain hurt. Me kill you. Take brain.}
{125}{}{大脑痛痛。我杀你。拿大脑。}

#{126}{}{I am here to assist these good people in understanding the workings
# of the Children of the Cathedral.}
{126}{}{我在这里协助这些好人理解大教堂教徒的所作所为。}

#{127}{}{So you are a spy for the Children?}
{127}{}{因此你是教徒的间谍？}

#{128}{}{How can you know anything about the Children?}
{128}{}{你怎么知道关于教徒的任何事？}

#{129}{}{What can you do? You are a mutant.}
{129}{}{你能做什么？你是一个变种人。}

#{130}{}{Nay, I am no spy. Though many think as such. There is a spy within
# our humble abode. Yet, we are unable to ferret the spy out.}
{130}{}{不，我不是间谍。虽然许多人也是这么想。在我们的住所里确实有一个间谍。然而我们无法找出那个间谍。}

#{131}{}{Then how do you help the Followers?}
{131}{}{你怎么帮助末世论者？}

#{132}{}{Tell me what you know about this spy. Maybe I can help.}
{132}{}{告诉我你知道这位间谍的什么。也许我能帮忙。}

#{133}{}{Tough luck, Mutie!}
{133}{}{晦气，变种人！}

#{134}{}{I think I found the spy. Now I will remove the problem.}
{134}{}{我认为我找到了间谍。现在我将去解决这个问题。}

#{135}{}{Once, I was as you are. But, through the interaction of the Nightkin
# in Necropolis, I was thrust into this state.}
{135}{}{曾经，我和你是一样的。但是，夜行团和大墓地使我变成了如今的情形。}

#{136}{}{That's awful. But, tough luck. See you around.}
{136}{}{真是可怕。运气糟透了。再见。}

#{137}{}{Why were you in Necropolis?}
{137}{}{为什么是您在大墓地？}

#{138}{}{Where were you from originally?}
{138}{}{你最初从哪来的？}

#{139}{}{And now I will transform you once more. Rest in pieces.}
{139}{}{现在我要再次修理你，让你死无全尸。}

#{140}{}{Some time ago, I lived in a place far to the north of here. They were having
# a problem with the water supply and sought out people to find a way to fix it.}
{140}{}{从前，我住在离这里很远的北方。他们出现了供水问题，于是找人找方法解决这个问题。}

#{141}{}{So you volunteered.}
{141}{}{因此你是那个志愿者。}

#{142}{}{Where was this place?}
{142}{}{那个地方在哪里？}

#{143}{}{Did you find a way to fix this problem?}
{143}{}{你找到解决问题的方法了吗？}

#{144}{}{But why Necropolis?}
{144}{}{但为什么是大墓地？}

#{145}{}{Yes. The overseer of the community gave me a shotgun and some shells.
# However, those were lost many years passed. Since I have never found anything,
# I could not return.}
{145}{}{是的。社区的所长给了我支散弹猎枪和一些子弹。然而，经过许多年那些东西都丢光了。因为我从未发现过任何东西，所以我没脸回去。}

#{146}{}{That's really awful. I wish there was something I could do.}
{146}{}{真是可怕。我希望我能帮你。}

#{147}{}{Too bad. Gotta head out.}
{147}{}{太不幸了。必须要走了。}

#{148}{}{Where was this place?}
{148}{}{这个地方在哪里？}

#{149}{}{Did you ever find a way to fix the water problem?}
{149}{}{你曾经找到解决供水问题的方法了吗？}

#{150}{}{Why did you go to Necropolis?}
{150}{}{你为什么要去大墓地？}

#{151}{}{There is a way in which you can help. The one who did this to me must
# be stopped.}
{151}{}{你可以帮我一个忙，阻止那个把我害成这样的人。}

#{152}{}{Who is it?}
{152}{}{他是谁？}

#{153}{}{Their leader is the head of a mutant army. What he does is take
# pure humans and transform them. I'm not quite sure, because I was knocked
# unconscious before the process.}
{153}{}{他们的领袖是变种人军队的头儿。他要抓纯种人类然后转变他们。因为我在转变之前被敲晕了，所以不是很肯定。}

#{154}{}{I will go kill them for you then.}
{154}{}{我将会为你去杀了他们。}

#{155}{}{Sounds too risky for me. I'm out of here.}
{155}{}{听起来太危险了。我要离开这里。}

#{156}{}{I thank you for your kindness. You do me a great service. Please,
# accept this as a token of good will. I purloined it from the body of a
# deceased renegade.}
{156}{}{感谢你的好心。你帮了我一个大忙。为了表达我的谢意，请你务必收下这个。这个火焰喷射器是我从一个叛徒的尸体上拿来的。}

#{157}{}{Be at peace then. I can understand your unease. Mayhaps another will
# come to help remove this threat. Good day to you.}
{157}{}{别激动，我理解你的愤怒。不过也许其他人可以帮你除去这个威胁，祝你好运。}

#{158}{}{The place from whence I came was in the mountains far to the north.
# It was a small vault in which many people lived.}
{158}{}{我来的地方是在遥远北方的山中。它是一个有许多人居住的小避难所。}

#{159}{}{Did you ever find a way to fix the water problem?}
{159}{}{你曾经找到解决供水问题的方法了吗？}

#{160}{}{Why did you go to Necropolis?}
{160}{}{你为什么要去大墓地？}

#{161}{}{What was the name of this Vault?}
{161}{}{这个避难所叫什么名字？}

#{162}{}{Sounds nice. I've gotta run.}
{162}{}{听起来很好。我必须走了。}

#{163}{}{Unfortunately, I did not. I have heard that others were sent from the
# vault to search for a way to fix the water pump.}
{163}{}{很不幸，我没有找到。我听说避难所派出其它人在想办法修复水泵。}

#{164}{}{I have heard nothing more of them.}
{164}{}{我再也没有他们的消息了。}

#{165}{}{Why did you go to Necropolis?}
{165}{}{你为什么要去大墓地？}

#{166}{}{What was the name of this Vault?}
{166}{}{这个避难所叫什么名字？}

#{167}{}{Sounds nice. I've gotta run.}
{167}{}{听起来很好。我必须走了。}

#{168}{}{I heard from some of the other travelers that Necropolis had a way in
# which to produce water without much difficulty.}
{168}{}{有旅行者告诉我，大墓地能够轻松的制造干净的水。}

#{169}{}{So, I went there to see what they were doing.}
{169}{}{因此，我去那里看看他们是怎么做的。}

#{170}{}{What did you find?}
{170}{}{你找什么？}

#{171}{}{Did you kill them off?}
{171}{}{你杀了他们吗？}

#{172}{}{Feel at home there?}
{172}{}{在那里感觉自在吗？}

#{173}{}{I found a great deal of those Mutant things there. It was they who
# entrapped me and transformed me into my current form.}
{173}{}{我在那里发现了很多变种人的事。他们坑害了我并且把我变成了现在这个样子。}

#{174}{}{Apparently, they messed up, because I took on a different evolutionary
# course, rather than the enhanced ones.}
{174}{}{很显然，他们搞砸了，因为我的进化过程完全不同，没有成为改进型变种人。}

#{175}{}{Rough deal. See you around.}
{175}{}{悲惨的经历啊，再见。}

#{176}{}{I'll be sure to watch out for them. Thanks for the info.}
{176}{}{我会小心提防他们。谢谢你的信息。}

#{177}{}{Who lead them?}
{177}{}{谁带领他们？}

#{178}{}{No. I killed only some of the mutants. There was another mutant,
# a ghoul, named Set, who helped me take out most of them.}
{178}{}{不，我只杀了一些变种人。有另外一个变种人，一个僵尸，叫作赛特，他帮我干掉了大部份变种人。}

#{179}{}{Last I knew there were only half a dozen mutants left.}
{179}{}{最后我只知道还剩下大概半打变种人。}

#{180}{}{That sounds great. Well, I will see you around.}
{180}{}{听起来很棒。好吧，我们会再见的。}

#{181}{}{The rest of them are gone now. Set is doing fine.}
{181}{}{他们其余的人现在都死了。赛特做的很好。}

#{182}{}{That is good news indeed to hear. I am overjoyed to hear the destruction
# of one evil and a town set free. Please, take this.}
{182}{}{那的确是个好消息。我很高兴听到邪恶势力被摧毁，城镇被解放。请收下这个。}

#{183}{}{Sarcasm and slights shall not deter me my benevolent disposition.
# The time has come for you to depart. Good day.}
{183}{}{挖苦和轻蔑阻止不了我善良的性格。时间到了，请你离开，再见。}

#{184}{}{My vault had no name. It was merely numbered 13.}
{184}{}{我的避难所没有名字。它就是第13号。}

#{185}{}{That is where I am from.}
{185}{}{那是我来的地方。}

#{186}{}{Never heard of the place.}
{186}{}{没听说过那地方。}

#{187}{}{Thanks for the info. Now I'm going to tell those Mutants about it.}
{187}{}{谢谢你的信息。现在我把它告诉那些变种人。}

#{188}{}{Really? Has the Overseer finally seen his way through to allow people
# to travel outside the Vault?}
{188}{}{真的？所长最终允许人们离开避难所到外面去了吗？}

#{189}{}{No, he is still scared of the outside world.}
{189}{}{不，他仍然害怕外面的世界。}

#{190}{}{No, he fears for the safety of the dwellers.}
{190}{}{不，他为居民的安全担心。}

#{191}{}{Yes, he thinks everything is safe.}
{191}{}{是，他认为一切都很安全。}

#{192}{}{I believed as such. He always was a cautious man. I pity him his
# responsibility. May you fare better than myself on this fool's quest.}
{192}{}{我同样相信。他总是很谨慎。我同情他所担负的责任。愿你的探索进展比我顺利。}

#{193}{}{I am glad to hear that he has come to his senses to allow the people out.
# While it is far from safe out here, it will do good to restore the earth
# once more. Farewell, my friend.}
{193}{}{我很高兴听到他允许人们外出到很远的地方。出来是很危险，但有助于恢复地球。再会，我的朋友。}

#{194}{}{I doubt you would have, coming from the outside world. Now, I must retire.
# Please be careful out there with those creatures who see to destroy.}
{194}{}{我怀疑你是否来自外界。现在我要休息了。要是看见那些破坏者请小心。}

#{195}{}{Nay, I doubt you would be able to do as such.}
{195}{}{反对，我怀疑你是否能够做到。}

#{196}{}{Try and stop me.}
{196}{}{试试来阻止我。}

#{197}{}{Why do you say that?}
{197}{}{你为什么那样说？}

#{198}{}{Because I will stop you.}
{198}{}{因为我将阻止你。}

#{199}{}{I know very little. The only things I know are that our scouts are the
# only ones who ever go over to the Children to spy on them. No one else
# is allowed because of the danger.}
{199}{}{我所知不多，我只知道只有侦察兵被派出去侦查大教堂的教徒，其他人都不让去，因为这工作太危险了。}

#{200}{}{Then it might be a scout. I will look into that.}
{200}{}{他或许是侦察员。我会去调查的。}

#{201}{}{I think that it is you. Now die!}
{201}{}{我认为那就是你。去死！}

#{202}{}{I wish you would have been of greater intellect. No matter, I shall
# dispense with you shortly.}
{202}{}{我真希望你能变得聪明点。不过无所谓了，我很快就不需要你了。}

#{203}{}{All I know of the Children is that they are in league with these
# Nightkin, super mutants.}
{203}{}{我只知道大教堂教徒与夜行团和超级变种人是同盟。}

#{204}{}{It is they who transformed me from my original state of being in Necropolis.}
{204}{}{是他们在大墓地把我变成现在这个样子。}

#{205}{}{That's awful. But, tough luck. See you around.}
{205}{}{真可怕。晦气，再见。}

#{206}{}{Why were you in Necropolis?}
{206}{}{为什么你在大墓地？}

#{207}{}{Where were you from originally?}
{207}{}{你最初从哪来的？}

#{208}{}{And now I will transform you once more. Rest in pieces.}
{208}{}{现在我要再次修理你，让你彻底安息。}

#{209}{}{Though I am different in appearance, I have much knowledge to impart
# upon those who will listen.}
{209}{}{虽然我的外表不同，但我有很多知识传授给那些想听的人。}

#{210}{}{I have no time for this, I'm leaving.}
{210}{}{我没时间听这个，我要走了。}

#{211}{}{What can you tell me?}
{211}{}{你能告诉我什么？}

#{212}{}{Those whom the Followers and Children call Nightkin are not what they
# seem. They have been created by one called the Lieutenant. I believe he may
# follow another.}
{212}{}{那些夜行团似乎原本是一些末世论者的信徒和孩子。他们是由一个自称副官的家伙创造的。我相信他或许追随另一个幕后者。}

#{213}{}{Some information. Well, I will be off.}
{213}{}{不错的信息。我要走了。}

#{214}{}{What can you tell me about this Lieutenant?}
{214}{}{关于这个副官你能告诉我什么？}

#{215}{}{There isn't much that I know about him. Last I saw him, before my
# untimely transformation, he was searching for pure humans.}
{215}{}{关于他我知道的不多。我在转变之前最后看到的就是他。他正在搜寻纯种人类。}

#{216}{}{I will think on this for a while. Thank you.}
{216}{}{我要好好考虑一下。谢谢你。}

#{217}{}{Can you hazard a hypothesis as to why this may be so?}
{217}{}{你能否大胆假设一下他们为什么要这么做？}

#{218}{}{As yet, I am uncertain. Perhaps another group which seeks to disrupt
# their ways would know.}
{218}{}{目前为止，我还不敢确定。或许另外一个寻找瓦解他们方法的团体会知道。}

#{219}{}{Thank you. Good day.}
{219}{}{谢谢你。再见。}

#{220}{}{I regret that I cannot tolerate insolence. Be gone.}
{220}{}{我很遗憾我不能容忍傲慢。走开。}

#{221}{}{My entrance into the Followers was quite simple really. It was the
# Followers who rescued me from the full effects of the transformation into
# a heinous beast.}
{221}{}{我进入末世论者之内真的相当简单，是那些信徒挽救了我。让我没变成一只可憎的畜牲。}

#{222}{}{I do not fully understand. Please, go on.}
{222}{}{我不是很了解。请继续。}

#{223}{}{Once, I was as you are now - a pure human. But, through the intervention
# of Nightkin, I was taken to some place far removed from here.}
{223}{}{曾经，我和你是一样的纯种人类，但是在夜行团的干预，我被带到某个很远的地方。}

#{224}{}{Please, continue.}
{224}{}{请继续。}

#{225}{}{I was not of a state in which to observe what transpired. All I
# had known was that I awoke here and was tended by the good doctor.}
{225}{}{我不知道路上发生了什么，只知道我醒来就在这里了并由好医生照料着。}

#{226}{}{I am truly sorry to hear of your predicament. I will find those
# who did this to you and remedy the situation.}
{226}{}{听说你的困境我感到很难过。我会找出那些对你下手的人给你个交代。}

#{227}{}{I am sorry to hear of that. Alas, I am quite busy attempting to
# survive. Farewell.}
{227}{}{我很抱歉听说了那个。唉，我的生活相当忙碌。告辞。}

#{228}{}{Please, dispense justice upon the defouler who seeks to undermine
# the trust of the Followers.}
{228}{}{请找到那个正在破坏末世论者信徒之间信赖的间谍。}

#{229}{}{Excellent job on removing from our midst that dissembler, Heather.}
{229}{}{除去了我们中间那个叛徒希瑟，干得好。}

#{230}{}{You see a hideous ghoul.}
{230}{}{你看见一个丑陋的僵尸。}

#{231}{}{Somehow, he reminds you of someone.}
{231}{}{不知何故，他使你想起某人。}

#{232}{}{Alas, I have no more time to spare on you. Good day.}
{232}{}{唉，我没有多余的时间浪费在你身上。再见。}
