{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Brother Thomas.}
{100}{}{你看到托马斯兄弟。}

#{101}{}{Okay children. Today we will be going over some martial arts.}
{101}{}{好的孩子。今天我们将学习一些搏斗技巧。}

#{102}{}{In close combat the technique you use depends on your
# opponents size, reach, and quickness.}
{102}{}{在近战中使用什么技巧取决于你对手的大小，距离和速度。}

#{103}{}{If given the opportunity test your opponent.}
{103}{}{如果给你试探对手的机会。}

#{104}{}{Don't rush the attack.}
{104}{}{不要急于进攻。}

#{105}{}{All right my little one, try to hurt poor old gramps.}
{105}{}{来吧小伙子们，和我这个老头子较量较量。}

#{106}{}{Ah!}
{106}{}{啊！}

#{107}{}{Uhh.}
{107}{}{噢。}

#{108}{}{Well that's all for now, so let's review.}
{108}{}{人都到齐了，我们开始复习。}

#{109}{}{You see how he lost his balance?}
{109}{}{你们看到他刚才怎么失去平衡了吧？}

#{110}{}{Overextending yourself leaves you open for a counter attack.}
{110}{}{动作太大反而使你受到攻击。}

#{111}{}{When you attack be sure not to overextend.}
{111}{}{当你进攻时最好不要动作幅度太大。}

#{112}{}{Why is overextending so bad?}
{112}{}{为什么动作幅度太大不好？}

#{113}{}{If you have the opportunity for a kill, shouldn't you go for it?}
{113}{}{如果你有一个机会杀死对方，你会不去做吗？}

#{114}{}{That's a lot to risk your life over.}
{114}{}{那是一个致命的危险。}

#{115}{}{Overextending leaves your inside vulnerable to a counter attack
# and puts you off balance.}
{115}{}{动作幅度太大的话，你的弱点就被暴露，对方也会轻易的把你打倒。}

#{116}{}{One little shove will land you right on your ass.}
{116}{}{轻轻一推你就会屁股落地。}

#{117}{}{Okay, let's give another young punk a try at gramps.}
{117}{}{好，让我们给另外一个壮汉与老头子较量的机会。}

#{118}{}{Let's see if you've learned from the previous example.}
{118}{}{让我们看看你以前学过的是什么？}

#{119}{}{Not bad, that last move almost got me.}
{119}{}{不错，你快要打到我了。}

#{120}{}{Are you sure you want to be a Scribe Initiate?}
{120}{}{你真的打算做一个初级研究员？}

#{121}{}{Those talents would be a shame to waste.}
{121}{}{天赋被浪费是个耻辱。}

#{122}{}{We'll just keep you in reserve. Okay?}
{122}{}{我们将会让你继续留在预备役。怎么样？}

#{123}{}{I'm just fooling with ya.}
{123}{}{我只是开个玩笑。}

#{124}{}{You may want to reconsider a career as a Knight.}
{124}{}{应该考虑成为一名骑士。}

#{125}{}{Just think about it.}
{125}{}{考虑考虑。}

#{126}{}{Thank you Brother Thomas.}
{126}{}{谢谢你托马斯兄弟。}

#{127}{}{I hope you all noticed how Brother Anthony did not overextend
# himself.}
{127}{}{我希望你仔细学习安东尼兄弟是怎么小幅度动作进行进攻的。}

#{128}{}{He also tried to use my weight and bulkiness against me.}
{128}{}{他还知道怎么利用我的身材庞大和体重来进攻。}

#{129}{}{Martial arts have their good and bad sides.}
{129}{}{搏斗技巧有好的一面和坏的一面。}

#{130}{}{We will be learning many different styles to better understand
# their strengths and weaknesses.}
{130}{}{我们将会学习一些不同的流派，来更好的了解它们的力道和不足之处。}

#{131}{}{Okay. Show me what you've got.}
{131}{}{好。让我看看你学的如何。}

#{132}{}{Very good. You lasted much longer than I thought you would.}
{132}{}{非常好。你坚持的事件比我料想的还长。}

#{133}{}{You can go back to the line.}
{133}{}{回到你那一排里去。}

#{134}{}{Well, I hope you kids were able to catch what was going on.}
{134}{}{好的，我希望你们这些小子可以觉察正在发生什么事。}

#{135}{}{He's a natural fighter.}
{135}{}{他是一个天生的战士。}

#{136}{}{Let's have one more.}
{136}{}{我们再做一些练习。}

#{137}{}{Pay close attention...}
{137}{}{集中注意力……}

#{138}{}{and remember to always punch through your targets.}
{138}{}{然后盯紧目标出拳。}

#{139}{}{Pretend your target is a few inches beyond were the impact is
# going to be.}
{139}{}{假设你的目标是一些球从远处飞来。}

#{140}{}{Um, Brother Thomas?}
{140}{}{嗯，托马斯兄弟？}

#{141}{}{Yes, my little piece of clay.}
{141}{}{是的，我的小伙子。}

#{142}{}{Shouldn't we do that for kicking too?}
{142}{}{难道我们也不能像这样去踢？}

#{143}{}{Of, course.}
{143}{}{嗯，过程。}

#{144}{}{Very good. I think we'll let you live.}
{144}{}{很好。我想我应该让你在这里。}

#{145}{}{Just kidding, try to smile once in a while.}
{145}{}{利用微笑让对手放松警惕。}

#{146}{}{This isn't a life and death situation.}
{146}{}{这不是生死之战。}

#{147}{}{There'll be plenty of time for that later on.}
{147}{}{以后还有更多的机会。}

#{200}{}{Not bad.}
{200}{}{不错。}

#{201}{}{That was pretty good.}
{201}{}{做的漂亮。}

#{202}{}{Okay, you're learning.}
{202}{}{好，你正在学习。}

#{203}{}{Stay focused.}
{203}{}{集中精神。}

#{204}{}{Keep your eyes on me.}
{204}{}{盯着我。}

#{205}{}{Don't overextend.}
{205}{}{动作幅度不要太大。}

#{206}{}{Never look away from your opponent.}
{206}{}{盯紧你的对手。}

#{207}{}{Work on your blocks.}
{207}{}{注意脚下。}

#{208}{}{Keep your center of gravity low.}
{208}{}{压低你的重心。}

#{209}{}{Excellent!}
{209}{}{非常好！}

#{210}{}{Perfect form.}
{210}{}{保持正确姿势！}

#{211}{}{I'm impressed.}
{211}{}{我记住了。}

#{300}{}{You gain 500 experience points from watching the training.}
{300}{}{你观摩了这个训练所以你获得了500点经验值。}

