
#{100}{}{It looks like a small gold trophy, with a clasp and a bronze plaque.}
{100}{}{看起来是一个小小的金色装饰物，上面有扣环和铜铭牌。}
#{101}{}{You successfully steal the urn from the countertop.}
{101}{}{你成功的从柜台上偷走了骨灰坛子。}
#{102}{}{You swipe the urn, and hope that nobody saw your clumsy attempt.}
{102}{}{你击打骨灰坛子，并且希望没人看见你这愚蠢的行为。}
#{103}{}{That looks pretty valuable. If you're going to pick up the urn, you should be more surreptitious about it.}
{103}{}{那看起来非常值钱。如果你要带着这个骨灰坛子，你应该更加隐秘地行动。}