
#{100}{}{Security Station}
{100}{}{安全岗哨}

#{101}{}{This terminal, 'Tylier', controls Special Forces Operations. Please
# present voice authorization.}
{101}{}{这个终端【泰勒尔】，控制特殊武器运转。请提供声音认证。}

#{102}{}{Nuna!}
{102}{}{噜哪！}

#{103}{}{Help me. Me got owwie.}
{103}{}{救救我，我受伤了。}

#{104}{}{Let me in.}
{104}{}{让我进去。}

#{105}{}{I am }
{105}{}{我是}

#{106}{}{. Let me pass.}
{106}{}{。让我通过。}

#{107}{}{What do you do here?}
{107}{}{你在这里干吗？}

#{108}{}{Voice not recognized. Security systems status: armed.}
{108}{}{声音认证没有被通过。安全系统状态：防御。}

#{109}{}{I am the security system for Blue Level. All systems armed.}
{109}{}{我是蓝层的安全系统。所有系统进入防御状态。}

#{110}{}{Can you disarm the systems?}
{110}{}{你可以解除防御系统吗？}

#{111}{}{Why are the systems armed when the war has ended?}
{111}{}{为什么战争已经结束了系统却仍在防御状态中？}

#{112}{}{Thank you.}
{112}{}{谢谢。}

#{113}{}{I have been programmed to keep the systems armed until
# authorized personnel have entered the correct voice code.}
{113}{}{我已经被设定为防御状态，直到有授权工作人员输入声音代码。}

#{114}{}{Will you disarm the systems for me?}
{114}{}{你会为我接触防御系统吗？}

#{115}{}{Good bye.}
{115}{}{再见。}

#{116}{}{Voice override: Gamma Delta Delta. Disarm all systems.}
{116}{}{声音改变：伽马、德尔塔、贝塔。所有系统防御解除。}

#{117}{}{You are not authorized. Access denied.}
{117}{}{你不是工作人员。认证失败。}

#{118}{}{Invalid code. Access denied.}
{118}{}{错误的密码。认证失败。}

#{119}{}{Voice override: Gamma Omicron Delta. Disarm systems.}
{119}{}{声音改变：伽马－欧米咖－德尔塔。系统防御解除。}

#{120}{}{Voice override: Omicron Delta Delta. Disarm systems.}
{120}{}{声音改变：欧米咖－德尔塔－德尔塔。系统防御解除。}

#{121}{}{Voice override: Alpha Delta Delta. Disarm systems.}
{121}{}{声音改变：阿尔法－德尔塔－德尔塔。系统防御解除。}

#{122}{}{Voice override: Delta Omicron Gamma. Disarm systems.}
{122}{}{声音改变：德尔塔－欧米咖－伽马。系统防御解除。}

#{123}{}{Good bye.}
{123}{}{再见。}

#{124}{}{Voice override confirmed. Disarming security systems.}
{124}{}{声音认证通过，解除防御系统。}

#{125}{}{I have not received orders to do otherwise. Network access is
# unavailable; central processor ZAX has apparently been destroyed.}
{125}{}{我无法识别认证命令以外的语言。网络访问无法进行；中央处理器ZAX显然已经被损坏。}

#{126}{}{Fine. Voice override: Sigma Alpha Delta. Disarm systems.}
{126}{}{很好。声音改变：西格马、阿尔法、德尔塔。系统防御解除。}

#{127}{}{Good bye.}
{127}{}{再见。}

#{128}{}{Security systems are currently disarmed.}
{128}{}{现在安全系统解除了防御。}

