
# {100}{}{You could glean more information from this terminal with a more scientific approach.}
# {101}{}{This terminal is regulating Vault supplies and functions, and performing routine administrative work.}
# {102}{}{The terminals on this level perform atmosphere and temperature control and backup maintenance for the medical lab.}
{100}{}{你可以用比较科学的方法从这台计算机中得到信息。}
{101}{}{这台终端机负责地下掩体的补给控制，屏幕上显示着一些常规程序。}
{102}{}{这台终端机负责空气、温度的调整以及医学试验备用品。}