{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

# {100}{}{You look distraught. Are you in need of assistance?}
# {101}{}{I need healing.}
# {102}{}{Urrr.}
# {103}{}{My husband Razlo can help you . . . ask him.}
# {104}{}{I'm sorry but I don't understand you.}
# {105}{}{You will have to come back in the morning. Please let us sleep in peace.}
# {106}{}{No thanks.}
# {107}{}{No, I am not in need of healing.}
{100}{}{你看起来很烦噪。你需要帮助吗？}
{101}{}{我需要治疗。}
{102}{}{呃。}
{103}{}{我丈夫拉斯洛能帮助你……问他吧。}
{104}{}{抱歉，但是我不明白。}
{105}{}{你早晨再来吧，请让我们安静的睡会儿。}
{106}{}{不，谢谢。}
{107}{}{不，我不需要治疗。}
