
# {100}{}{You see a Water Caravan employee.}
# {101}{}{Talk to Martha if you want a job.}
# {102}{}{These caravan trips are getting too dangerous.}
# {103}{}{Hey, you got any smokes?}
# {104}{}{I need a bath.}
# {105}{}{Please leave.}
# {106}{}{You'd better be careful.  We don't pay those guards for their looks.}
# {107}{}{Go somewhere else if you want a job.}
{100}{}{你看到一个纯水商队的雇员。}
{101}{}{你如果想找个工作和玛撒讲。}
{102}{}{这些商队的旅行变得太危险了。}
{103}{}{嘿，你有没有烟？}
{104}{}{我需要洗个澡。}
{105}{}{请离开。}
{106}{}{你最好小心点。我们雇的警卫可不是放在这里做摆设的。}
{107}{}{如果你想找个工作去别处。}
