
# {100}{}{This door leads to your room. You have lived your entire life in this room, until now. Your fellow Vault citizens have told you that they will leave this room empty in your honor.}
{100}{}{这扇门通往你的房间。走出避难所之前的你一直在这个蜗居里生活。避难所的市民告诉你说，为了表达对你的尊重，他们决定永远空着这间房。}
 