{100}{}{To szczup³a, m³oda kobieta z umorusan¹ twarz¹ i ciemnym ubraniem.}
{101}{}{To Katja, z³odziejka.}
{102}{}{Nie pochodzisz z tych okolic. Kim jesteœ?}

# TRANSLATION NOTE
# The player-character's name is inserted between lines 103 and 104 by the code.

{103}{}{Nazywam siê }
{104}{}{.}
{105}{}{Jestem wêdrowcem.}
{106}{}{Mogê o to samo zapytaæ ciebie.}
{107}{}{A co, jeœli mogê spytaæ, robisz w Gruzach?}
{108}{}{Zadajesz mnóstwo pytañ.}
{109}{}{Najpierw powiedz mi, kim ty jesteœ.}
{110}{}{Po prostu wêdrujê po œwiecie.}
{111}{}{Szukam dla mojej Krypty zastêpczego procesora steruj¹cego systemem uzdatniania wody.}
{112}{}{Ka¿dy siê tutaj uczy ostro¿noœci. No to co tu robisz?}
{113}{}{W porz¹dku, niech bêdzie. Wo³aj¹ mnie Katja. Co masz do tego?}
{114}{}{Czemu jesteœ tak wrogo usposobiona?}
{115}{}{Hej, jeœli masz byæ w zwi¹zku z tym niegrzeczna, to do zobaczenia.}
{116}{}{Szukam informacji. Mo¿esz mi pomóc?}
{117}{}{Mo¿esz, ale jesteœ na moim rodzinnym terenie, a nie vice versa. Wiêc gadaj, albo spadaj.}
{118}{}{To niewa¿ne, jestem zwyk³ym wêdrowcem. Potrzebne mi s¹ pewne informacje.}
{119}{}{Procesora steruj¹cego systemem uzdatniania wody? Niestety, nic nie wiem na jego temat. Tu, w Gruzach, nie widuje siê wiele techniki tego typu, mo¿e z wyj¹tkiem rzeczy, nad którymi pracuje Miles.}
{120}{}{Có¿, i tak dziêki.}
{121}{}{Miles? Gdzie mo¿na go znaleŸæ, i czy móg³by mi pomóc?}
{122}{}{Czy w takim razie mo¿esz mi opowiedzieæ coœ wiêcej o Gruzach?}
{123}{}{Zwyk³ym wêdrowcem? Ju¿ to kiedyœ s³ysza³am. Nikt nie przychodzi do Gruzów z wyj¹tkiem tych kupców z Hubu, i ludzi szukaj¹cych szybkiej œmierci z r¹k gangów. Po co tu naprawdê jesteœ?}
{124}{}{Masz racjê. Szukam procesora steruj¹cego systemem uzdatniania wody.}
{125}{}{Nic ci nie muszê mówiæ.}
{126}{}{A jak¿e. Tyle, ¿e to ulica dwukierunkowa.}
{127}{}{Mo¿e. Na pewno nie jesteœ jedn¹ z tych gangolskich trzêsidup. Czego chcesz?}
{128}{}{Szukam procesora steruj¹cego systemem uzdatniania wody.}
{129}{}{Potrzebujê wiêcej informacji o Gruzach.}
{130}{}{Chcê siê czegoœ dowiedzieæ o terenach wokó³ tego miasta.}
{131}{}{Co mo¿esz mi powiedzieæ na temat Ostrz?}
{132}{}{Co mo¿esz mi powiedzieæ na temat Rozpruwaczy?}
{133}{}{Co mo¿esz mi powiedzieæ na temat Zbrojeniowców?}
{134}{}{Co mo¿esz mi powiedzieæ na temat Uczniów?}
{135}{}{Co mo¿esz mi powiedzieæ na temat Adytum?}
{136}{}{Có¿, mi³o by³o pogawêdziæ. Muszê lecieæ.}
{137}{}{Miles mieszka w Adytum. To naukowiec, robi g³ównie w chemii. Jeœli ktoœ móg³by sko³owaæ procesor, albo zrobiæ zamiennik, to w³aœnie on.}
{138}{}{Wielkie dziêki.}
{139}{}{Adytum jest moim prawdziwym domem. Trochê tam jednak dla mnie za nudno. To odgrodzone siatk¹, samowystarczalne miasteczko w po³udniowej czêœci Gruzów, ale nie tak daleko jak Katedra. Od czasu do czasu handlujemy z Hubem.}
{140}{}{Mia³am ju¿ z nimi do czynienia. Nie s¹ szczególnie Ÿli, jak na gang. Maj¹ kryjówkê w starym klubie, z paroma wysuniêtymi posterunkami. Jak bêdziesz postêpowaæ ostro¿nie, to mo¿e ci siê nawet uda sk³oniæ niektórych z nich, ¿eby z tob¹ pogadali.}
{141}{}{Rozpruwacze to po prostu zupe³ne dzikusy. S¹ band¹ siostrojebców, których raduj¹ tortury i morderstwa. Trzymam siê od nich z daleka, i tobie te¿ to radzê. Oni nawet ustawili pieprzone miny dooko³a swojej fortecy.}
{142}{}{Zbrojeniowcy byli kiedyœ prawdziwym gangiem, ale zmiêk³a im rura. Zaczêli prowadziæ interes, gdzie handluj¹ broni¹, któr¹ bior¹ od swoich ofiar albo kupuj¹ w Hubie. Poniewa¿ nikt siê tutaj osobiœcie nie pisze na wycieczkê do Hubu, robi¹ ca³kiem dobry biznes, nawet mimo tego, ¿e ich ceny s¹ wyœrubowane.}
{143}{}{Uczniowie Apokalipsy to grupa wyznawców pokoju, którzy mieszkaj¹ w wielkiej bibliotece niedaleko centrum Gruzów. Naprawdê nie wiem, czemu jeszcze nie zostali wyr¿niêci. To nêdzni bojownicy, i nie maj¹ pojêcia o prawdziwym œwiecie, ale poza tym s¹ uprzejmi i dobrze wykszta³ceni.}
{144}{}{Gruzy to ca³kiem groŸne miejsce. Nigdy nie mia³am okazji, ¿eby st¹d odejœæ, ale s¹dzê, ¿e bym z niej skorzysta³a. Popatrzmy... Zaraz na po³udnie st¹d masz Katedrê. Jest tam jakiegoœ rodzaju sekta, ale trzymam siê od nich z daleka. Dzieje siê tam coœ ponurego. S³ysza³am te¿ o oœrodku handlowym, zwanym Hubem, od czasu do czasu zjawiaj¹ siê tu karawany stamt¹d, ale nigdy tam nie by³am.}
{145}{}{Osobiœcie nie planujê tu zbyt d³ugo zostawaæ.}
{146}{}{Dziêki za informacje.}
{147}{}{Czy mo¿esz mi powiedzieæ coœ wiêcej?}
{148}{}{Bez jaj. Jak szukasz jeszcze kogoœ do pomocy, to siê na to piszê. Lepsze to ni¿ spêdzenie reszty mojego ¿ywota w tej nêdznej dziurze, nie?}
{149}{}{Jesteœ mile widzianym dodatkiem, ale pustynia nie jest o wiele bardziej rozrywkowa.}
{150}{}{Niech ciê o to g³owa nie boli. W ka¿dym razie dziêki.}
{151}{}{Czy mogê ci najpierw zadaæ jeszcze parê pytañ?}
{152}{}{Ta okolica jest opanowana przez trzy gangi - Ostrza, Rozpruwaczy i Zbrojeniowców - i równoczeœnie s³u¿y za dom Uczniów, i miejsce dla mojej w³asnej osady, Adytum.}
{153}{}{W porz¹dku, wygl¹da na to, ¿e mamy trochê ty³ków do skopania!}
{154}{}{S³uchaj, 90% ludzi w tym mieœcie podpada pod jedn¹ lub wiêcej z trzech kategorii - gwa³cicieli, morderców i z³odziei. Jestem z³odziejk¹, a ty wydajesz siê zachowywaæ uprzejmie, wiêc mnie to dziwi, OK? Mo¿esz to okreœliæ jako instynkt przetrwania.}
{155}{}{No to przepraszam za wchodzenie ci na odcisk. Chyba ju¿ sobie pójdê w cholerê.}
{156}{}{No có¿, mogê ci przynajmniej zadaæ kilka pytañ?}
{157}{}{Nie jestem st¹d, wiêc mnie to raczej nie dotyczy.}
{158}{}{OK, ale szybko.}
{159}{}{Hê. Chyba nie da siê walczyæ z tak¹ logik¹. No to czego chcesz?}
{160}{}{Czy mogê ci zadaæ parê pytañ?}
{161}{}{Szukam procesora steruj¹cego systemem uzdatniania wody. Mo¿esz mi pomóc?}
{162}{}{Dziêki, tak czy owak, ale ju¿ sobie pójdê.}
{163}{}{Co jest?}
{164}{}{Mog³abyœ siê spróbowaæ z tym zamkiem?}
{165}{}{Mog³abyœ rzuciæ okiem na tê pu³apkê?}
{166}{}{Masz jakieœ rady?}
{167}{}{Dziêkujê ci za pomoc. Mo¿esz ju¿ odejœæ.}
{168}{}{Jeszcze nic. Ale b¹dŸ czujna.}
{169}{}{Znowu ty? Po co teraz przychodzisz?}
{170}{}{Tylko przystajê, ¿eby siê przywitaæ.}
{171}{}{Mam jeszcze kilka pytañ, je¿eli mo¿esz mi poœwiêciæ trochê czasu.}
{172}{}{Otwarte.}
{173}{}{Jest coœ podejrzanego w tej biblioteczce przy wschodniej œcianie. Wygl¹da tak, jakby coœ ukrywa³a.}
{174}{}{Schowaj broñ.}
{175}{}{Nie cierpiê psów.}
{176}{}{To ¿arcie pachnie smakowicie.}
{177}{}{Jakie masz umiejêtnoœci bojowe?}
{178}{}{W Gruzach nauczy³am siê biæ. Jestem dobra w no¿ach i pistoletach maszynowych. Najbardziej lubiê rzucaæ no¿ami, oczywiœcie.}
{179}{}{W porz¹dku, chocia¿ Ÿle siê czujê bez porz¹dnego no¿a.}
{180}{}{Zyskujesz 200 punktów doœwiadczenia za zwerbowanie Katji, szabrowniczki z Gruzów.}
{181}{}{Czego teraz chcesz?}
{182}{}{Odwidzia³o mi siê. Wci¹¿ przyda³aby mi siê twoja pomoc.}
{183}{}{Nic. Niewa¿ne.}
{184}{}{Zaczynam naprawdê nienawidziæ tego miejsca.}
{185}{}{O rany. Szkoda, ¿e nie mam kie³baski i naprawdê d³ugiego patyka.}
{186}{}{Och, b³e. Chyba siê porzygam.}
{187}{}{Hej, ta œciana z uszkodzonym tynkiem wygl¹da, jakby by³a ruchoma.}
{188}{}{Uwa¿aj na Szpony Œmierci!}
{189}{}{Bara-bara!}
{190}{}{OdejdŸ!}
{191}{}{Przykro mi, ale zwyczajnie ciê nie rozumiem. ¯egnaj.}

#
# Katja tell-me-abouts
#

{980}{}{Nic o ty nie wiem.}
{981}{}{Naprawdê nie mogê powiedzieæ, ¿ebym o tym s³ysza³a.}
{982}{}{Nie, nigdy o tym nie s³ysza³am.}

{1000}{}{hydroprocesor}
{1001}{}{Gruzy}
{1002}{}{Wojna}
{1003}{}{Adytum}
{1004}{}{Uczniowie}
{1005}{}{Katedra}
{1006}{}{procesor}
{1007}{}{Garl}
{1008}{}{Mistrz}
{1009}{}{Jednoœæ}
{1010}{}{Set}
{1011}{}{Wododzia³}
{1012}{}{Nekropolis}
{1013}{}{Aula}
{1014}{}{Biblioteka}
{1015}{}{Opiekun}
{1016}{}{lekarz}
{1017}{}{leczenie}
{1018}{}{Krypta}
{1019}{}{Krypta 13}
{1020}{}{Krypta13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Z³omowo}
{1024}{}{Cieniste}
{1025}{}{Piaski}
{1026}{}{Hub}
{1027}{}{Kasyno}
{1028}{}{sklep}
{1029}{}{Szpon œmierci}
{1030}{}{Exodus}
{1031}{}{kadeci}
{1032}{}{paladyni}
{1033}{}{skrybowie}
{1034}{}{dzieci}
{1036}{}{Bractwo}
{1037}{}{Kadzie}
{1038}{}{Wojskowa}
{1039}{}{Baza}
{1041}{}{Apokalipsa}
{1042}{}{mutanci}
{1043}{}{Morfeusz}
{1044}{}{Chanowie}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{alkohol}
{1052}{}{narkotyki}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulatorzy}
{1058}{}{szabrownicy}
{1059}{}{Ostrza}
{1060}{}{Nicole}
{1061}{}{porucznik}
{1062}{}{psionika}
{1063}{}{eksperymenty}
{1064}{}{Policja}
{1065}{}{kupcy}

{1100}{}{Nie wiem, gdzie mo¿na znaleŸæ taki relikt dawnej technologii.}
{1101}{}{Gruzy to wszystko, co zosta³o po dawnym mieœcie Los Angeles. W wiêkszoœci s¹ podzielone miêdzy wojuj¹ce ze sob¹ grupy.}
{1102}{}{Wojna przynios³a niedolê i œmieræ na ca³ym œwiecie. Naprawdê mam nadziejê, ¿e coœ takiego ju¿ siê nigdy nie zdarzy. Ale z tego, co widzia³am, to dla ludzkoœci nie ma wiele nadziei.}
{1103}{}{Adytum by³o moim domem, ale ci ludzie s¹ po prostu za bardzo paranoiczni i stroni¹cy od innych. Nijak nie uda im siê przetrwaæ poprzez odsuniêcie siê od œwiata.}
{1104}{}{Uczniowie Apokalipsy g³osz¹ pokój i tolerancjê. Szkoda, ¿e one na nic nie poradz¹ na tym œwiecie.}
{1105}{}{Katedra to monumentalny gmach, jakiœ dzieñ wêdrówki na po³udnie od Adytum. Dzia³a tam dziwaczna sekta, która czci jakiegoœ mrocznego boga.}
{1106}{}{Nie wiem, gdzie mo¿na znaleŸæ taki relikt dawnej technologii.}
{1107}{}{Nie wiem o tym wiêcej od ciebie.}
{1108}{}{Nie wiem o tym wiêcej od ciebie.}
{1109}{}{Nie wiem o tym wiêcej od ciebie.}
{1110}{}{Nie wiem o tym wiêcej od ciebie.}
{1111}{}{Nie wiem o tym wiêcej od ciebie.}
{1112}{}{Co, Miasto Umar³ych? Czy to nie mit?}
{1113}{}{Nie wiem o tym wiêcej od ciebie.}
{1114}{}{Nie wiem o tym wiêcej od ciebie.}
{1115}{}{Nie wiem o tym wiêcej od ciebie.}
{1116}{}{Uczniowie maj¹ ca³y czas lekarza pod rêk¹.}
{1117}{}{Jak potrzebujesz leczenia, to idŸ do lekarza Uczniów.}
{1118}{}{Czy Krypty to nie by³y takie wielkie, podziemne schrony?}
{1119}{}{Czy Krypty to nie by³y takie wielkie, podziemne schrony?}
{1120}{}{Czy Krypty to nie by³y takie wielkie, podziemne schrony?}
{1121}{}{Nie wiem o tym wiêcej od ciebie.}
{1122}{}{Nie wiem o tym wiêcej od ciebie.}
{1123}{}{Ee, to ma³a osada na pó³noc od Hubu, tak myœlê.}
{1124}{}{Cieniaste co?}
{1125}{}{Cieniste Piaski? Nigdy o nich nie s³ysza³am.}
{1126}{}{Hub to ogromny oœrodek handlu, z wszelkiego rodzaju sklepami i kupcami.}
{1127}{}{Nie wiem o tym wiêcej od ciebie.}
{1128}{}{Zbrojeniowcy sprzedaj¹ ró¿ne rzeczy, i jest sklep w Adytum.}
{1129}{}{B³e! W Gruzach jest pe³no Szponów Œmierci. Wolê o nich nawet nie myœleæ. S¹ ogromne i trafnie nazwane.}
{1130}{}{Nie wiem o tym wiêcej od ciebie.}
{1131}{}{Nie wiem o tym wiêcej od ciebie.}
{1132}{}{Nie wiem o tym wiêcej od ciebie.}
{1133}{}{Nie wiem o tym wiêcej od ciebie.}
{1134}{}{Nie przepadam za dzieciakami.}
{1136}{}{S³ysza³am, ¿e to jacyœ zaawansowani technicznie mnisi.}
{1137}{}{Nie wiem o tym wiêcej od ciebie.}
{1138}{}{Nie wiem o tym wiêcej od ciebie.}
{1139}{}{S¹dzê, ¿e musz¹ tam byæ jakieœ pozosta³oœci po dawnym wojsku.}
{1141}{}{Chodzi ci o wielk¹ Wojnê? Rany, jeœli nic o niej nie wiesz, to rodzice naprawdê musieli trzymaæ ciê pod kloszem.}
{1142}{}{Widzia³am raz szczura z trzema oczami. To w zasadzie wszystko, co wiem o mutantach.}
{1143}{}{Myœlê, ¿e jest Najwy¿szym Kap³anem w Katedrze, czy czymœ takim.}
{1144}{}{Nie wiem o tym wiêcej od ciebie.}
{1145}{}{Nie wiem o tym wiêcej od ciebie.}
{1146}{}{Nie wiem o tym wiêcej od ciebie.}
{1147}{}{Nie wiem o tym wiêcej od ciebie.}
{1148}{}{Nie wiem o tym wiêcej od ciebie.}
{1149}{}{Nie wiem o tym wiêcej od ciebie.}
{1150}{}{Nie wiem o tym wiêcej od ciebie.}
{1151}{}{Nie, dziêki.}
{1152}{}{B³e. Nie, nie mam ochoty. Widzia³am kiedyœ, jak mój przyjaciel umiera z przedawkowania Psycho. Nie by³o to piêkne.}
{1153}{}{Nie wiem o tym wiêcej od ciebie.}
{1154}{}{Nie wiem o tym wiêcej od ciebie.}
{1155}{}{Nie wiem o tym wiêcej od ciebie.}
{1156}{}{To burmistrz Adytum. Sprawiedliwy cz³owiek, chocia¿ trochê chwiejny.}
{1157}{}{Strzeg¹ Adytum i trzymaj¹ je w ryzach.}
{1158}{}{By³am wczeœniej szabrowniczk¹. Wychodziliœmy noc¹ i próbowaliœmy znaleŸæ u¿yteczne rzeczy w ruinach Gruzów. To bardzo niebezpieczna robota. Mi siê jednak zrobi³o doœæ Adytum.}
{1159}{}{To grupa wyrzutków, którzy mieszkaj¹ poza Adytum.}
{1160}{}{Jest przywódczyni¹ Uczniów. To inteligentna kobieta, i ma te¿ dobre serce.}
{1161}{}{Nie wiem o tym wiêcej od ciebie.}
{1162}{}{Od czasu do czasu mam "kobiec¹ intuicjê", jeœli to o takie coœ ci chodzi.}
{1163}{}{Nie wiem o tym wiêcej od ciebie.}
{1164}{}{Nie wiem o tym wiêcej od ciebie.}
{1165}{}{Kupcy handluj¹ od czasu do czasu z Adytum, i zaopatruj¹ Zbrojeniowców.}




{1999}{}{Robiê siê w tym coraz lepsza!}
{2000}{}{Pogadajmy o taktyce walki.}
{2001}{}{S³ucham ciê.}
{2010}{}{U¿yj swojej najlepszej broni.}
{2011}{}{Za³ó¿ najlepszy pancerz jaki masz.}
{2012}{}{Staraj siê prowadziæ walkê na odleg³oœæ a nie w starciu bezpoœrednim.}
{2013}{}{Wybieraj walkê w starciu bezpoœrednim zamiast na odleg³oœæ.}
{2014}{}{Sama sobie wybierz jak chcesz walczyæ.}
{2015}{}{Na razie to wszystko.}
{2100}{}{Cokolwiek ka¿esz.}
