{100}{}{You see the ghoul manager.}
{101}{}{Whatta you doing here?}
{102}{}{Searching for the remains of the future past.}
{103}{}{I'm an explorer.}
{104}{}{What's it to you, wormface?}
{105}{}{Dug-duh.}
{106}{}{Whad' you say?}
{107}{}{Nothing.}
{108}{}{I'm looking for lost technology.}
{109}{}{That's what I thought you say. Getta outta my house.}
{110}{}{Oh, nonna dat around here. Maybe uppa da
 temple or atta water place. Getta going.}
{111}{}{Ack! Donna you be exploring any my stuff.
 Getta out! I mean it.}
{112}{}{Donna be in my face likka dat. I runna dis show.}
{113}{}{Oh, yeah.}
{114}{}{I'm gonna take that face of yours and shove it up yer...}
{115}{}{Ack! OK, I concede. I leave.}
{116}{}{You no biggie to order me like dat. Take some of dis and shove it!}
{117}{}{I don wanna talk to you.}