##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
##      (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{Razzo}
{200}{}{Sfera di Plasma}
{300}{}{Esplosione}
{400}{}{Sangue}
{500}{}{No-Trans hex}
{501}{}{}
{600}{}{Knife}
{700}{}{Spear}
{800}{}{Esplosione EMP}
{900}{}{Colpo Laser}
{1000}{}{Colpo al Plasma}
{1100}{}{Esplosione}
{1200}{}{Scroll Blocker}
{1300}{}{Lampo Elettrico}
{1400}{}{Esplosione}
{1500}{}{Esplosione}
{1600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2400}{}{Torcia}
{2500}{}{Granata}
{2600}{}{Roccia}
{2700}{}{Esplosione}
{2800}{}{Esplosione}
{2900}{}{Esplosione}
{3000}{}{Molotov}
{3100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
