{100}{}{Estás viendo al Anciano de Arenas Sombrías.}
{101}{}{Me complace conocerte. Espero que nuestro pequeño pueblo te haya parecido agradable.}
{102}{}{Sí.}
{103}{}{Nop, no hay suficiente acción por aquí.}
{104}{}{Excelente. Tengo un favor que pedirte. Te aseguro que se te recompensará muy bien por los servicios que hagas a esta comunidad.}
{105}{}{Te escucho... }
{106}{}{Esto es solo una demo, pero quizás te guste lo que voy a decir a continuación.}
{107}{}{Soy todo oídos... }
{108}{}{Hemos sido plagados con escorpiones rad desde hace ya una temporada. Todos los que han sido enviados a destruir a estos monstruos no han regresado. Te daré armas y armaduras si los sigues a su guarida y los matas.}
{109}{}{Suena bien.}
{110}{}{No, gracias. No es mi estilo.}
{111}{}{Es una pena. Por favor, vete}
{112}{}{Excelente. Seth te puede guiar a su guarida. Llévate esto, te será de ayuda.}
{113}{}{Por favor, ayúdanos tan pronto como sea posible. El tiempo apremia.}
{114}{}{No hablo con los de tu clase, forastero.}
{115}{}{¡Gracias! Has salvado nuestro pueblo del peligro. Ahora es seguro viajar por las zonas circundantes. Acepta esto como una señal de gratitud. [Te da unas cuantas chapas]}
{116}{}{Gracias. Te debemos tanto.}