{100}{}{Estás viendo a un miembro de los Navajas.}
{101}{}{Ey.}
{102}{}{Hola.}
{103}{}{Que tengas un buen día.}
{104}{}{Hace buen día.}
{105}{}{Me pregunto si lloverá.}
{106}{}{¿Alguna vez has visto resplandecer a la lluvia?}
{107}{}{Tengo que volver al trabajo.}
{108}{}{No nos suelen visitar forasteros.}
{109}{}{Me tengo que ir.}
{110}{}{Nos vemos.}
{111}{}{Bueno días.}
{112}{}{Gracias por la ayuda.}
{113}{}{No te hemos olvidado.}
{114}{}{Es bueno tenerte de nuestro lado.}
{115}{}{Ahora las cosas irán a mejor.}