# Alchemist: long phrases should be split and require some smooyhing.

{100}{}{Ves: a Lex, cabecilla del clan pirata, Víboras.}
{101}{}{Estás viendo a un tío enorme con mala actitud, te mira fijamente.}
{102}{}{[...te despiertas con rapidez y miras a tu alrededor. Estás en un lugar desconocido, ves tres tiendas y unas cuantas personas a su alrededor. Parece que te las arreglaste para mantenerte consciente antes de que te limpiasen los bolsillos. Tus ojos se fijan en el hombre que está ante ti] Oh, nuestro desafortunado comprador ha despertado.}
{103}{}{[Más]}
{104}{}{¿Qué será? Nos puedes dar todas tus chapas y te dejaremos ir. O podemos jugar a los vaqueros.}
{105}{}{¿Y que garantiza que saldré con vida esta si te doy el dinero?}
{106}{}{Siempre me han gustado los westerns.}
{107}{}{Vaqueros.}
{108}{}{¡La palabra del pirata!}
{109}{}{Creo que puedo confiar en ti. Aquí tienes, cógelo. [Le das tus ahorros]}
{110}{}{Esas palabras no significan nada para mí.}
{111}{}{¿Así que tenemos un terco? Creo que lo prefiero así. Creo que lo chicos se van a divertir contigo.}
{112}{}{¡Si no confías en las palabras, entonces tendrás que hacerlo en las armas! ¡Un cobarde como tú no es rival para todo el grupo!}
{113}{}{Que así sea entonces, prefiero matarte. Para asegurarme de que se acabe el parloteo. Hasta nunca.}
{114}{}{Buen chico. Una sabia decisión. Puedes irte.}

