{100}{}{Ves a un Paladín solitario. Parece estar enfadado y asustado a la vez.}

{101}{}{¡Alto ahí, extraño! ¡Identifícate!}

# low IQ
{102}{}{Yo }
{103}{}{.}

{104}{}{Soy }
{105}{}{. ¿Qué le ha pasado a este lugar?}
{106}{}{Mi nombre no es importante.}

# low IQ
{107}{}{Cuidado, }
{108}{}{, puede que te hagas daño. Un ejército de mutantes malos han venido a este lugar y han hecho un gran bum. ¿Ves?}
{109}{}{Eh-heh.}
{110}{}{Ves. Así que lo mejor será que busques otro lugar. Este no es seguro.}
{111}{}{Yo ir.}

{112}{}{Mutantes. Era un ejército realmente grande. Vinieron y mataron a todo el mundo, cogieron todo lo que pudieron e hicieron pedazos este sitio.}
{113}{}{¿Y cómo es que sobreviviste?}
{114}{}{Regresaba de una patrulla lejana. Cuando llegué la batalla ya había terminado. No pude hacer nada. Así que me escondí y los vigilé.}
{115}{}{¿Quieres decir que estabas muy asustado como para hacer nada?}
{116}{}{¿Nadie más sobrevivió a la invasión?}
{117}{}{Mira, puede que no sea el más valiente de la Hermandad, pero tampoco soy un idiota. No había absolutamente nada que pudiera haber hecho.}
{118}{}{Cobarde. Quédate y vigila este puñado de ruinas. Lo mejor es que me vaya y mate a algunos de tus mutantes.}
{119}{}{Lo siento. ¿Alguien más sobrevivió a esta masacre?}
{120}{}{Varios grupos de exploración, algunos paladines que patrullaban... muy pocos para hacer nada. La Hermandad de Acero está prácticamente muerta. Me quedaré aquí por ahora, intentaré reunir tantos supervivientes como pueda y contarles lo que ha pasado aquí. Y entonces... la verdad es que no sé qué pasará entonces. No he tenido tiempo para pensarlo.}
{121}{}{Lo entiendo. Sigue con el buen trabajo, Paladín, debo marcharme.}
{122}{}{Adiós, }
{123}{}{. Si te encuentras con algún superviviente es tus viajes, diles lo que ha pasado aquí.}

{124}{}{Alto ahí... Oh, eres tú, }
{125}{}{.}
{126}{}{Eh-heh.}
{127}{}{Sí, soy yo. ¿Qué ha pasado aquí?}

{130}{}{Adiós, }
{131}{}{. Si te encuentras con algunos de nuestros compañeros de la Hermandad, diles lo que ha pasado aquí.}
{132}{}{Claro. Tengo que irme.}

{133}{}{Entonces vete. No tengo nada que decirte.}

{150}{}{El Paladín te ignora. Parece que está absorto en sus pensamientos.}
