{100}{}{Ves: a Kyle.}
{101}{}{¿Qué pasa tío, como te va? Todavía viajas a pie... ¿No te cansas? A lo mejor es hora de considerar en unas bonitas ruedas para tu viaje ¿Tienes dinero?}
{102}{}{¿Que cómo me va? ¡Como nunca! ¿De verdad tienes unas ruedas para mí? El dinero no es problema.}
{103}{}{¿Si te rajo un poco, quizás me las darías gratis?}
{104}{}{Esa es una buena pregunta. Creo que volveré.}
{105}{}{Ummm... Bueno, no estoy seguro. Un comprador más adinerado vendría mejor. Escucha, ¿por qué no vuelves algo más tarde, cuando tengas más chapas?}
{106}{}{Créeme, un amigo mío tiene un negocio DE VERDAD. Parece, que es el único tío de todo el yermo que podría venderte un coche. El lugar no está muy lejos de aquí. Está como a un día de aquí. El tipo este usa su propia casa como garaje... 400 chapas serían suficientes como para que te enseñe el camino.}
{107}{}{Trato hecho. Solo llévame a tu amigo y yo me encargaré del resto.}
{108}{}{Lo siento, Kyle. Tengo cosas más importantes que hacer.}
{109}{}{Vale, te llevaré allí. Lo que sea por un cliente tan atractivo, ¡lo que sea! Sígueme. [acepta las 400 chapas]}
{110}{}{Sabía que te echarías para atrás. Todo el mundo que tiene tanto dinero le asusta viajar. ¡Sea como sea, mis amigos los piratas te ayudarán con eso! [Te empiezas a dar cuenta de que algo va mal, pero de repente una fuerte patada en la cabeza te deja inconsciente. Lo último que sientes es como te arrastran a algún sitio...]}
{111}{}{Escucha, escoria. Piérdete. Tú y tus amenazas vacías.}
{112}{}{Debería buscar un cliente más conveniente.}
