{100}{}{To krêpy mê¿czyzna.}
{101}{}{W tych stronach nie lubimy takich jak ty.}
{102}{}{Witaj. Jesteœ tu chyba po raz pierwszy. Jak siê nazywasz?}
{103}{}{To niewa¿ne.}
{104}{}{Jestem }
{105}{}{.}
{106}{}{Urg?}
{107}{}{No có¿, wiêc ty te¿.}
{108}{}{Mi³o ciê poznaæ. Ja jestem Ian.}
{109}{}{Co tu robisz?}
{110}{}{Chcê siê dowiedzieæ czegoœ wiêcej o tej osadzie. Mo¿esz mi pomóc?}
{111}{}{Wybacz, ale nie bêdê marnowa³ czasu na rozmowy z debilami.}
{112}{}{Pracowa³em jako stra¿nik dla kupców z Hubu. Podczas napadu najeŸdŸców
 zosta³em postrzelony. Zosta³em tutaj, bo miejscowi pomagaj¹ mi wróciæ do
 zdrowia. Dodatkowo, moja znajomoœæ œwiata zewnêtrznego czyni mnie
 tu u¿ytecznym. Cieniste Piaski s¹ teraz moim domem. Od czasu do czasu
 odwiedzam nawet Z³omowo albo Hub, ¿eby trochê pohandlowaæ, poniewa¿ jestem
 tu jedyn¹ osob¹, która kiedykolwiek rzeczywiœcie bywa³a poza osad¹.}
{113}{}{To Ian.}
{114}{}{Przykro mi s³yszeæ o twojej ranie.}
{115}{}{Gdzie jest ten Hub, i Z³omowo?}
{116}{}{Czy mo¿esz mi coœ powiedzieæ o tych najeŸdŸcach?}
{117}{}{Cieniste Piaski to ma³a, ale samowystarczalna spo³ecznoœæ. Jedynym
 problemem s¹ tu najeŸdŸcy i radskorpiony.}
{118}{}{Dlaczego te radskorpiony sprawiaj¹ wam k³opoty?}
{119}{}{Du¿o jest tych najeŸdŸców?}
{120}{}{Jest ich paru. Nale¿¹ do ró¿nych grup. Kradn¹ nam ¿ywnoœæ i czasem
 zastrzel¹ parê osób. Seth zorganizowa³ stra¿, ¿eby sprawniej ich odpieraæ.}
{121}{}{Czy mo¿esz mi coœ powiedzieæ o Secie?}
{122}{}{S¹ ich ró¿ne grupy? Jakie?}
{123}{}{Radskorpiony s¹ bardzo groŸne. Maj¹ jadowity kolec na koñcu ogona,
 i s¹ bardzo szybkie. Aradesh stara siê znaleŸæ sposób, ¿eby siê ich pozbyæ.
 Jeœli nie brakuje ci odwagi, mo¿esz z nim o nich porozmawiaæ.}
{124}{}{Dziêki. Goi siê dobrze, dziêki Razlowi.}
{125}{}{Seth to bardzo dzielny wojownik. Od czasu do czasu chodzi do jaskiñ
 radskorpionów, ¿eby zabiæ parê z nich, ale one zawsze w koñcu tu wracaj¹.
 Jest ich po prostu za du¿o, ¿eby móg³ pokonaæ je wszystkie.}
{126}{}{Czy te radskorpiony rzeczywiœcie s¹ takie niebezpieczne?}
{127}{}{W czym mogê ci pomóc?}
{128}{}{S¹ trzy grupy: Chanowie, ¯mije i Szakale. Dosyæ mocno siê nawzajem
 nienawidz¹, ale wszyscy napadaj¹ na Cieniste Piaski.}
{129}{}{Opowiedz mi coœ wiêcej o Cienistych Piaskach.}
{130}{}{Ma on przesycon¹ pewnoœci¹ siebie, rozluŸnion¹ postawê doœwiadczonego
 wojownika.}
{131}{}{No có¿, }
{132}{}{, co mogê dla ciebie zrobiæ?}
{133}{}{Opowiedz mi o najeŸdŸcach.}
{134}{}{Opowiedz mi o radskorpionach.}
{135}{}{Opowiedz mi o Cienistych Piaskach.}
{136}{}{Opowiedz mi o Secie.}
{137}{}{Czy mo¿esz daæ mi wskazówki, jak dotrzeæ do Hubu i Z³omowa?}
{138}{}{Nie, dziêki.}
{139}{}{Hub to wielki oœrodek handlu daleko na po³udnie od Cienistych Piasków.
 Rz¹dzi nim kilka ró¿nych karawanowych grup kupieckich: Kupcy Wodni,
 Karmazynowa Karawana i Wszêdobylscy Handlowcy. Z³omowo jest st¹d kawa³ drogi
 na po³udnie i odrobinê na zachód. Jest mniejsze od Hubu, ale mimo tego to
 dobre miejsce, ¿eby wpaœæ na drinka. Nadzoruje je jegomoœæ, który nazywa siê
 Killian Darkwater; to tamtejszy sklepikarz, szeryf i burmistrz.}
{140}{}{Dziêki.}
{141}{}{Mo¿e i ju¿ nie jestem bardzo dobrym wojownikiem, ale jestem
 wystarczaj¹co dobry, ¿eby pokonywaæ takich jak ty!}
{142}{}{No, }
{143}{}{, co mogê dla ciebie zrobiæ?}
{144}{}{Hmm. Nic. Nie zawracaj sobie tym g³owy, Ian.}
{145}{}{Mo¿esz ju¿ odejœæ.}
{146}{}{Czy mo¿esz daæ mi wskazówki, jak dotrzeæ do Hubu i Z³omowa?}
{147}{}{Có¿, skoro prosisz, w porz¹dku. Do zobaczenia.}
{148}{}{Nie, dziêki. Jestem tu potrzebny.}
{149}{}{Czy móg³byœ mi odrobinê pomóc? Przyda³oby mi siê twoje doœwiadczenie.}
{150}{}{Ruszajmy. Dobrze bêdzie wróciæ do akcji!}
{151}{}{To sklep wielobran¿owy Killiana. Killian to dobry cz³owiek, i maj¹ tu
 mnóstwo towaru.}
{152}{}{Kasyno Gizma. Jaskinia hazardu i centrum aktywnoœci pó³œwiatka.
 Uwa¿aj, gry s¹ tu ustawione.}
{153}{}{Dostajê tu gêsiej skórki.}
{154}{}{Co, u diab³a, siê tu sta³o?}
{155}{}{To bêdzie twardy orzech do zgryzienia.}
{156}{}{Hmm. Kusz¹ca oferta, jako ¿e tutaj robi siê nudno. Umówmy siê tak.
 Standardowa stawka. Setka kapsli, i ubijamy interes.}
{157}{}{Sztama.}
{158}{}{Nie, dziêki.}
{159}{}{A mo¿e byæ zamiast tego udzia³ w zyskach?}
{160}{}{W porz¹dku, pomogê ci w zamian za czêœæ ³upów.}
{161}{}{Nie, nie s¹dzê. Wróæ, jak zdobêdziesz trochê kapsli.}
{162}{}{To Sklep z Broni¹. Prowadzi go Beth. Jest dobra, jeœli chodzi o spluwy,
 ale lepsza, jeœli chodzi o plotki.}
{163}{}{Zbrojownia Jake'a. Wysokie ceny, ale naprawdê dobre armaty.}
{164}{}{Biuro Kupców Wodnych. To oni trzês¹ Hubem, bo dostarczaj¹ wodê, dziêki
 której wszystko siê krêci.}
{165}{}{To Karmazynowa Karawana. Trochê dla nich pracowa³em. Wykonuj¹ masê
 misji wysokiego ryzyka.}
{166}{}{Wszêdobylscy Handlowcy, kierowani przez Butcha Harrisa. On ie-nej
 est-jej byt-zej ystry-bej, jeœli ³apiesz, o co mi chodzi.}
{167}{}{Ach, Sokó³ Maltañski to wymarzone miejsce na relaks. Dobra muzyka,
 dobre drinki i dobre towarzystwo.}
{168}{}{To dopiero brzydki skurwysyn!}
{169}{}{Zyskujesz 100 punktów doœwiadczenia za przekonanie Iana do wziêcia
 udzia³u w twojej wyprawie.}
{170}{}{S³ysza³em ju¿ wczeœniej o paru takich miejscach, ale nigdy w ¿adnym
 nie by³em. Wygl¹da na mi³e i schludne... trochê za schludne, jak na mój gust.}
{171}{}{Nie, ¿eby mnie ktoœ pyta³, ale szef powinien daæ ci trochê miejsca do
 oddychania.}
{172}{}{Wiesz co, ta kobieta nie potrafi³aby prowadziæ w tangu, nie mówi¹c
 o rewolucji.}
{173}{}{W jakich broniach jesteœ bieg³y?}
{174}{}{Dobrze strzelam z prawie ka¿dego pistoletu, i potrafiê siê te¿
 pos³ugiwaæ pistoletem maszynowym. Wiem tak¿e, jak siê obchodziæ z no¿ami.}
#
# Translation note
# The following line is directed at Katja, a female scavenger, not at the player.
# Ian is noting that he thinks that the Boneyard was a worse place than the
# mutants' military base.
#
{175}{}{Myœlê, ¿e w Gruzach by³o gorzej.}
{200}{}{Jak siê zacznie walka, wyci¹gnij twoj¹ najlepsz¹ broñ.}
{201}{}{Jasna sprawa.}
{202}{}{Czy mogê coœ dla ciebie zrobiæ, zanim sobie pójdê?}
{203}{}{Hm, ta. Myœlê, ¿e mimo wszystko powinniœmy trzymaæ siê razem.}
{204}{}{Eee, nie. Dziêki.}
#
# Ian tell-me-abouts
#
{1000}{}{hydroprocesor}
{1001}{}{Wojna}
{1002}{}{Cieniste}
{1003}{}{Z³omowo}
{1004}{}{Hub}
{1005}{}{najeŸdŸcy}
{1006}{}{karawany}
{1007}{}{hydroprocesor}
{1008}{}{Piaski}
{1009}{}{Uczniowie}
{1010}{}{Katedra}
{1011}{}{Garl}
{1012}{}{Mistrz}
{1013}{}{Jednoœæ}
{1014}{}{Set}
{1015}{}{Wododzia³}
{1016}{}{Nekropolis}
{1017}{}{Aula}
{1018}{}{Biblioteka}
{1019}{}{Opiekun}
{1020}{}{lekarz}
{1021}{}{leczenie}
{1022}{}{Krypta}
{1023}{}{Krypta 13}
{1024}{}{Krypta13}
{1025}{}{Killian}
{1026}{}{Gizmo}
{1027}{}{Gruzy}
{1028}{}{Kasyno}
{1029}{}{sklep}
{1030}{}{Szpony œmierci}
{1031}{}{Exodus}
{1032}{}{kadeci}
{1033}{}{paladyni}
{1034}{}{skrybowie}
{1035}{}{Dzieci}
{1036}{}{Bractwo}
{1037}{}{Kadzie}
{1038}{}{Baza}
{1039}{}{Wojskowa}
{1041}{}{Apokalipsa}
{1042}{}{mutanci}
{1043}{}{Morfeusz}
{1044}{}{Chanowie}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{alkohol}
{1052}{}{narkotyki}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulatorzy}
{1058}{}{szabrownicy}
{1059}{}{Ostrza}
{1060}{}{Nicole}
{1061}{}{porucznik}
{1062}{}{psionika}
{1063}{}{eksperymenty}
{1064}{}{Policja}
{1065}{}{kupcy}
{1100}{}{Nie mam zielonego pojêcia, czym jest hydroprocesor. Wybacz.}
{1101}{}{Wydarzy³a siê parêdziesi¹t lat temu. Pomijaj¹c szczegó³y, parê krajów
 siê trochê poprztyka³o, i wszystko zrobi³o BUM!}
{1102}{}{To ma³a, spokojna wioska. Chyba najlepiej rokuj¹ca spo³ecznoœæ
 na Pustkowiu.}
{1103}{}{Œredniej wielkoœci osada zbudowana ze z³omu, nadzorowana przez szeryfa
 imieniem Killian. To tylko parê dni na po³udniowy zachód od Cienistych Piasków.}
{1104}{}{Hub jest najwiêkszym oœrodkiem handlu na Nowym Zachodzie. To kwitn¹ce
 miasto. Rz¹dzi nim przede wszystkim grupa zwana Kupcami Wodnymi, ale s¹ tam
 te¿ inni handlowcy; trwa miêdzy nimi wszystkimi ostra walka polityczna.}
{1105}{}{Jest kilka ró¿nych grup najeŸdŸców. Najlepiej zorganizowana zwie siê
 Chanami; wydaj¹ siê myœleæ, ¿e mog¹ podbiæ œwiat, czy coœ w tym stylu.}
{1106}{}{Wiêkszoœæ karawan przychodzi z Hubu. Wêdruj¹ po ca³ym Pustkowiu.
 Przed moim niefortunnym zranieniem pracowa³em dla grupy zwanej Karmazynow¹
 Karawan¹.}
{1107}{}{Nie mam zielonego pojêcia, czym jest hydroprocesor. Wybacz.}
{1108}{}{To ma³a, spokojna wioska. Chyba najlepiej rokuj¹ca spo³ecznoœæ na
 Pustkowiu.}
{1109}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1110}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1111}{}{Garl to pewien przyg³up, który myœli, ¿e ze swoimi cieniastymi
 najeŸdŸcami mo¿e podbiæ œwiat. Ta, jak tam sobie chce.}
{1112}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1113}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1114}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1115}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1116}{}{Czy to nie mityczne Miasto Umar³ych?}
{1117}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1118}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1119}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1120}{}{Razlo to œwietny lekarz. W razie zranienia powinno siê do niego
 zajrzeæ.}
{1121}{}{Razlo œwietnie sobie radzi ze stawianiem ludzi na nogi, a jego
 odtrutka jest z nawi¹zk¹ warta swojej ceny!}
{1122}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1123}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1124}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1125}{}{Killian jest burmistrzem Z³omowa. Prowadzi tam tak¿e sklep. To
 przyzwoity jegomoœæ. Nigdy nie wykonywa³em dla niego ¿adnej roboty, ale
 wydaje siê byæ w porz¹dku.}
{1126}{}{Gizmo prowadzi kasyno w Z³omowie. S³ysza³em, ¿e gry s¹ tam ustawione.}
{1127}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1128}{}{Kasyno w Z³omowie to wizytówka Gizma. Przyci¹ga masê turystów
 i pieniêdzy, ale razem z nimi pojawiaj¹ siê problemy.}
{1129}{}{Killian prowadzi w Z³omowie dobry sklep wielobran¿owy.}
{1130}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1131}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1132}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1133}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1134}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1135}{}{Ta, w Cienistych Piaskach jest parê dzieciaków. No i co? ¯aden z nich
 nie jest mój.}
{1136}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1137}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1138}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1139}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1141}{}{Wiesz, zawsze bêdziemy mieli wojny. Tyle ¿e nastêpna bêdzie stoczona
 kijami.}
{1142}{}{Widzia³em ró¿ne dziwaczne rzeczy, gdy strzeg³em karawan z Hubu.
 Zmutowane kojoty i modliszki, i skorpiony i tym podobne.}
{1143}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1144}{}{To ¿a³osna grupa najeŸdŸców, którzy atakuj¹ Cieniste Piaski i myœl¹,
 ¿e podbij¹ œwiat, albo wierz¹ w jakieœ podobne bzdety.}
{1145}{}{To córka Aradesha. Jest ca³kiem s³odka, ale na mnie ktoœ czeka w domu.}
{1146}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1147}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1148}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1149}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1150}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1151}{}{Co, masz jakiœ browar?}
{1152}{}{Wzi¹³em raz trochê Psycho podczas napadu na karawanê. Zrobi³em siê
 od tego nerwowy. Dziwne.}
{1153}{}{Seth jest kapitanem Stra¿ników. Mówi¹c miêdzy nami, on nie potrafi³by
 upilnowaæ owocu przybitego do jego w³asnej nogi.}
{1154}{}{Aradesh jest przywódc¹ Cienistych Piasków. To ¿yczliwy i wyrozumia³y
 cz³owiek, chocia¿ jest trochê szurniêty.}
{1155}{}{Hej, jak ktoœ potrzebuje pomocy, powinien zobaczyæ siê z Razlem. To
 œwietny lekarz.}
{1156}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1157}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1158}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1159}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1160}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1161}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1162}{}{Sam nie wiem. Myœlê, ¿e coœ w tym jest, ta, ale po prostu nie ma na
 to wystarczaj¹cych dowodów.}
{1163}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1164}{}{Wybacz, szefie. Niewiele wiem na ten temat.}
{1165}{}{Wêdruj¹ z karawanami po ca³ym Pustkowiu. Przed moim niefortunnym
 zranieniem pracowa³em dla grupy kupieckiej, zwanej Karmazynow¹ Karawan¹.}


{1999}{}{Nauczy³em siê paru nowych sztuczek.}
{2000}{}{Pogadajmy o taktyce walki.}
{2001}{}{Czego?}
{2010}{}{U¿yj swojej najlepszej broni.}
{2011}{}{Zmieñ pancerz na inny.}
{2012}{}{Staraj siê walczyæ na odleg³oœæ a nie w starciu bezpoœrednim.}
{2013}{}{Wybieraj walkê w starciu bezpoœrednim zamiast na odleg³oœæ.}
{2014}{}{Sam sobie wybierz jak chcesz walczyæ.}
{2015}{}{Na razie to wszystko.}
{2100}{}{Jasna sprawa, szefie.}
