# Alchemist: Warning! Achtung! Uwaga!
# Beca's script is bounf to the ol' black male at the Blades map, but this is
# temporary measure. Actually Quatermistress IS a women! So she must be
# referenced as 'SHE/HER' NOT 'he/his/him'.  'Jade' stands for nickname and
# 'Bec'a stands for the real one.

{100}{}{To Jade.}
{101}{}{To Beca.}
{102}{}{}
{103}{}{}
{104}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{105}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{106}{}{Myœlisz, ¿e to mo¿e byæ Kujon.}
{107}{}{Myœlisz, ¿e to mo¿e byæ Blizna.}
{108}{}{Myœlisz, ¿e to mo¿e byæ Strzelec.}
{109}{}{Myœlisz, ¿e to mo¿e byæ Nerwus.}
{110}{}{Myœlisz, ¿e to mo¿e byæ M³ot.}
{111}{}{Myœlisz, ¿e to mo¿e byæ Brzytwa.}
{112}{}{To sypialnia. Wynoœ siê st¹d, zanim skopiê ci zad.}
{113}{}{Spróbuj.}
{114}{}{Przepraszam. ¯egnaj.}
{115}{}{Mogê tu przekimaæ?}
{116}{}{Nie. To miejsce dla prawdziwych Ostrzy, a nie jakichœ cieniasów.}
{117}{}{Siema, ziomuœ! Jak leci? Kimaj tutaj jak potrzebujesz bezpiecznego wyrka.}
{118}{}{Wiêc, zdecydowa³eœ siê pomóc. Lepsze to ni¿ nic, doceniam to. Rozpowiemy o tym.}
{119}{}{Tak. Zobaczê co da siê zrobiæ.}
{120}{}{Wiatj ponownie. S³ysza³am, ¿e nam pomog³eœ. Jesteœ wiêcej ni¿ godny naszego szacunku. Odzyskaliœmy wolnoœæ. [Jesteœ teraz cz³onkiem Ostrzy.]}
{121}{}{Nie mogê ci w tym pomóc. Pogadaj z Brzytw¹.}
