{100}{}{To W¹¿.}
{101}{}{To Dolgan.}
{102}{}{}
{103}{}{}
{104}{}{To Ostrze.}
{105}{}{To Ostrze.}
{106}{}{Myœlisz, ¿e to mo¿e byæ Kujon.}
{107}{}{Myœlisz, ¿e to mo¿e byæ Blizna.}
{108}{}{Myœlisz, ¿e to mo¿e byæ Strzelec.}
{109}{}{Myœlisz, ¿e to mo¿e byæ Nerwus.}
{110}{}{Myœlisz, ¿e to mo¿e byæ M³ot.}
{111}{}{Myœlisz, ¿e to mo¿e byæ Brzytwa.}
{112}{}{Sp³ywaj! To jest tylko dla prawdziwych wojowników.}
{113}{}{A, myœlisz, ¿e jesteœ w stanie za³atwiæ Pl¹tacza i jego ³ajzy? Poka¿, nauczê ciê u¿ywaæ tego ostrza.}
{114}{}{Idzie ci to teraz trochê lepiej. Wykop dla mnie zad Pl¹tacza do przysz³ego roku.}
{115}{}{Posiekanie tych Rozpruwaczy by³o œwietne. Co mogê dla ciebie zrobiæ?}
{116}{}{Mo¿esz mnie jeszcze podszkoliæ w walce ostrzami?}
{117}{}{Jak mogê siê dostaæ do Zbrojeniowców?}
{118}{}{Nic, dziêki.}
{119}{}{Jasna rzecz. Ale to zajmie wiêkszoœæ dnia i da s³abe efekty. Nadal tego chcesz?}
{120}{}{Tak.}
{121}{}{Nie.}
{122}{}{Proszê bardzo. Wykazujesz pewn¹ poprawê. ¯yczê ci powodzenia.}
{123}{}{Jasna rzecz. Wróæ, jak bêdziesz mieæ ochotê na trening.}
{124}{}{Zdaje siê, ¿e przyjêliœmy g³upka. Có¿, jak siê chcesz dostaæ do ich siedziby, to przez w ich fosie jest niewielkie przewê¿enie. Poszukaj go i gnaj jak wariat. Mo¿e nawet uda ci siê przedostaæ.}
{125}{}{Dziêki.}