# Chris Avellone is a male bounty hunter. He has an abrupt attitude and is serious about
# his money. He does not like child killers (which is the only way the player will meet him).

{100}{}{To krzepki ³owca nagród, nosz¹cy znaczek o treœci "Ja jestem Christopher, a ty œcierwo".}
# Bounty Hunter is considered Male term

{101}{}{Czego chcesz?}
{102}{}{P¹czka.}
{103}{}{Co tu robisz?}
{104}{}{Tylko siê rozgl¹dam.}
{105}{}{Nic.}
{106}{}{Nie przepadamy tu za m¹dralami. Spierdalaj.}
# Alternate for "Buzz off" could be "Get lost" or "Get out of here"

{107}{}{Ten ¿art nie by³ œmieszny nawet za pierwszym razem. Zaraz odkryjesz, czemu jestem jednym z najbardziej przera¿aj¹cych ³owców nagród na Pustkowiu. A nawet nikt mi za to nie zap³aci.}
{108}{}{Nie twoja sprawa.}
{109}{}{Có¿, idŸ szperaæ gdzieœ indziej.}
# Alternate for "poke around" could be "Look around"

{110}{}{Czy wiesz, ¿e za twoj¹ g³owê wyznaczono nagrodê w wysokoœci 1500 kapsli, za mordowanie dzieci? Czas j¹ zainkasowaæ!}
# 1500 caps is equivalant to 1500 dollars. Children is considered male plural

{111}{}{[Christopher z bliska sprawia wra¿enie jakby bra³ coœ pod uwagê... Wygl¹da na to, ¿e on ju¿ podj¹³ decyzjê.] Powiedz mi jak czêsto jesteœ w Hubie lub Z³omowie? }
{112}{}{Dosyæ czêsto, dlaczego pytasz?}
{113}{}{Wiêc, widzisz... Interesy zajmuj¹ wiêkszoœæ mojego czasu i nie mam mo¿liwoœci aby dostaæ siê tam. Jako uzale¿niony palacz bardzo brakuje mi starej zapalniczki Zippo. Mówi siê, ¿e wiele przedwojennych przedmiotów mo¿na znaleŸæ w okolicznych sklepach. Jeœli dorwiesz dla mnie Zippo, ja udostêpniê Tobie pewne informacje na temat okolicznych osad. S¹dzê, ¿e to mo¿e byæ przydatne!}
{114}{}{Szkoda.. Wygl¹da na to, ¿e pomyli³em siê co do ciebie. Wynoœ siê st¹d.}
{115}{}{Dlaczego nie? Zdobêdê jedn¹ dla ciebie.}
{116}{}{Ok.}
{117}{}{Hej, mam jedn¹ tak¹ tutaj. Naprawdê tego nie potrzebujê i mogê Ci to daæ w zamian za informacjê.}
{118}{}{Dziêkujê! [bierze zapalniczkê.] Wiêc, co chcesz dok³adnie wiedzieæ?}
{119}{}{Oto twoja zapalniczka. Czas ¿ebyœ przekaza³ mi trochê informacji.}
{120}{}{Nie mam wiêcej pytañ, dziêki.}
{121}{}{[Wiêcej]}
{122}{}{Co jeszcze chcia³byœ wiedzieæ?}
{123}{}{Potrzebujê pewnych informacji.}

{300}{}{Adytum}
{301}{}{Uczniowie}
{302}{}{Dzieci Katedry}
{303}{}{Rozpruwacze}
{304}{}{Ostrza}
{305}{}{Zbrojeniowcy}
{306}{}{Hub}
{307}{}{Gruzy}

{300}{}{To ma³a osada na po³udnie st¹d. Od czasu do czasu w okolicy pojawia siê paru jej mieszkañców.}
{301}{}{To mi³uj¹cy pokój popaprañcy, którzy mieszkaj¹ zaraz obok nas.}
{302}{}{To dziwna sekta z siedzib¹ na po³udnie od Adytum i reszty Gruzów. Nicole twierdzi, ¿e coœ knuj¹.}
{313}{}{To skrajnie gwa³towny gang, mieszkaj¹cy na zachód od nas.}
{314}{}{To gang z siedzib¹ na wschodzie. U¿ywaj¹ wibrono¿y.}
{315}{}{To gang, który przyby³ z Hubu, i sprzedaje broñ. S¹ na pó³noc st¹d.}
{316}{}{Hub to du¿e miasto handlarzy, na pó³noc st¹d.}
{317}{}{To tutaj, pozosta³oœci starego miasta o nazwie Los Angeles.}

# Alchemist: These are currently disabled teel-me-abouts. Don't delete, they may be of use in the future.

# {1007}{}{Z³omowo}
# {1008}{}{hydroprocesor}
# {1009}{}{Nicole}
# {1011}{}{Zbrojeniowcy}
# {1012}{}{procesor}
# {1107}{}{Z³omowo to miasteczko zaraz na pó³noc od Hubu.}
# {1108}{}{Nie jestem w stanie ci z tym pomóc.}
# {1109}{}{Jest przywódczyni¹ Uczniów.}
# {1111}{}{To gang, który przyby³ z Hubu, i sprzedaje broñ. S¹ na pó³noc st¹d.}
# {1112}{}{Nie jestem w stanie ci z tym pomóc.}
