{100}{}{Widzisz Kyle'a.}
{101}{}{Co jest, kolego, jak siê masz? Wci¹¿ ³azisz pieszo? Nie jesteœ zmêczony? Mo¿e czas pomyœleæ o fajnych czterech kó³kach na twoje eskapady? Jesteœ gotów wydaæ trochê forsy?}
{102}{}{Jak siê mam? Dobrze jak nigdy! Naprawdê masz jakiœ zestaw czterech kó³ek dla mnie? Kasa to nie problem.}
{103}{}{Mo¿e jak ciê trochê uszkodzê, oddasz mi go za darmo?}
{104}{}{Dobre pytanie. Zajrzê do ciebie póŸniej.}
{105}{}{No dobra, nie jestem pewien. Bogatszy nabywca bardziej ci siê przyda. S³uchaj, dlaczego po prostu nie przyjdziesz trochê póŸniej, kiedy bêdziesz mieæ wiêcej kapsli? }
{106}{}{Uwierz mi, mój kumpel ma PRAWDZIWY interes. Zdaje siê, ¿e jest jedyn¹ osob¹ na pustkowiach, która mog³aby ci sprzedaæ brykê. To miejsce nie jest zbyt daleko st¹d. Kolesie u¿ywaj¹ jego w³asnego domu jako gara¿u. 400 kapsli powinno wystarczyæ, ¿ebym ci pokaza³ drogê.}
{107}{}{Zgoda. ZaprowadŸ mnie tylko do twojego kumpla, reszt¹ zajmê siê sam.}
{108}{}{Wybacz, Kyle. Mam wa¿niejsze rzeczy do roboty.}
{109}{}{Okej. Zabiorê ciê tam. Klient nasz pan! ChodŸ za mn¹. [ZgódŸ siê na 400 kapsli]}
{110}{}{Wiedzia³em, ¿e stchórzysz. Ka¿dy boi siê podró¿owaæ maj¹c za du¿o kasy. Tak czy siak, moi kumple z gangu pomog¹ ci siê jej pozbyæ! [Zaczynasz rozumieæ, ¿e coœ posz³o nie tak, kiedy nagle silny kopniak w g³owê pozbawia ciê przytomnoœci. Jesteœ gdzieœ wleczony i to ostatnia rzecz, jak¹ czujesz.}
{111}{}{S³uchaj, œmieciu. Zje¿d¿aj. Twoje pogró¿ki nie robi¹ na mnie wra¿enia.}
{112}{}{Powinienem poszukaæ wygodniejszego klienta.}