{100}{}{To sêdziwa kobieta.}
{101}{}{To Agatha.}
{102}{}{Ta kobieta jest wprawdzie siwa i pokryta zmarszczkami, ale jest bystra i ¿wawo siê porusza.}
{103}{}{Jesteœ z³¹ osob¹. Nie chcê mieæ z tob¹ nic do czynienia.}
{104}{}{To straszne, gdy nasza m³odzie¿ jest w niebezpieczeñstwie. Utrata Tandi by³aby straszna.}
{105}{}{Hnng.}
{106}{}{OK.}
{107}{}{Czemu?}
{108}{}{Co masz na myœli?}
{109}{}{Wiem, ¿e zrobisz wszystko, co w twojej mocy, z³otko. OdnajdŸ Tandi, pomó¿ jej uciec od tych bestii i zwróæ j¹ Aradeshowi. Przys³u¿ysz siê naszej spo³ecznoœci i zgromadzisz dobr¹ karmê.}
{110}{}{Aradesh bardzo kocha swoj¹ córkê. W³aœnie ta mi³oœæ czyni go dobrym cz³owiekiem i filarem naszej spo³ecznoœci. Bez tej mi³oœci by³by zgubiony, a Cieniste Piaski razem z nim...}
{111}{}{Zrobiê wszystko, co mo¿liwe. ¯egnaj.}
{112}{}{Przyda³aby mi siê pomoc.}
{113}{}{Hmmm. Zobaczymy.}
{114}{}{Wyczuwam, ¿e jest uwiêziona. By³a celem nienawiœci. Ta nienawiœæ jest bardzo silna na po³udniowym wschodzie. Jestem pewna, ¿e tam j¹ znajdziesz. Powodzenia.}
{115}{}{Dziêkujê.}
{116}{}{Nie wiesz o tym? Tandi zaginê³a. Czujê, ¿e zosta³a porwana. Aradesh jest zrozpaczony. To straszne...}
{117}{}{S³yszê, ¿e Tandi zosta³a ocalona przez ciebie. Twoje postêpowanie by³o w³aœciwe. Twoja karma jest silna. Spodziewam siê wiele po twojej przysz³oœci.}
{118}{}{Bardzo przykro mi s³uchaæ o tym, co sta³o siê z Tandi. By³a tak¹ b³yskotliw¹ dziewczyn¹. Dobrze pokierowa³aby swoim ¿yciem.}
{119}{}{Witaj. Musisz byæ tym przybyszem, o którym wszyscy mówi¹. [Agatha wzdycha.] Jak mogê ci pomóc?}
{120}{}{Hngh.}
{121}{}{Kim jesteœ?}
{122}{}{Wygl¹dasz na bardzo zmêczon¹. Czy coœ ci siê sta³o?}
{123}{}{Czemu jesteœ tak znu¿ona?}
{124}{}{Nie odzywaj siê do mnie, starucho.}
{125}{}{Potrzebujesz wiêkszej pomocy ni¿ mogê ci udzieliæ, moje dziecko. Niech Dharma bêdzie z tob¹.}
{126}{}{Nazywam siê Agatha. Jestem gawêdziark¹ Cienistych Piasków. Moim zadaniem jest przekazywanie historii, abyœmy pamiêtali i nigdy nie zapomnieli.}
{127}{}{Opowiedz mi jak¹œ historiê.}
{128}{}{OK, jak tam sobie chcesz.}
{129}{}{Dobrze jest nie zapominaæ.}
{130}{}{Przykro mi, moje dziecko, jestem teraz znu¿ona. Potrzebujê odpoczynku. PrzyjdŸ proszê póŸniej.}
{131}{}{To szczera prawda. [Agatha przygl¹da ci siê przez chwilê.] Dobrze, by m³odzi pamiêtali, ale trudno jest dzia³aæ wewn¹trz nurtu historii. Niekiedy samo nasze postêpowanie jest zdeterminowane wydarzeniami, które mia³y miejsce dawno temu. Niech Dharma bêdzie z tob¹. Muszê nieco odpocz¹æ. PrzyjdŸ znowu kiedy siê wzmocniê, a ponownie porozmawiamy.}
{132}{}{Dziêkujê, ¿e pytasz. Jestem po prostu stara, to wszystko. Nie mogê spaæ w nocy. Zamykam powieki... [Agatha przerywa.] Ale nie znajdujê spoczynku. To tylko moje stare, zmêczone koœci...}
{133}{}{Przykro mi, jestem bardzo zmêczona. PrzyjdŸ proszê póŸniej.}
{134}{}{Baba.}
{135}{}{OK.}
{136}{}{Czemu jesteœ tak znu¿ona?}
{137}{}{Nie sypiam dobrze w nocy, moje dziecko. To na pewno z powodu mojego wieku.}
{138}{}{Dzieñ dobry, moje dziecko. Dobrze wygl¹dasz. Przypominasz mi moj¹ w³asn¹ kruszynê.}
{139}{}{Hng.}
{140}{}{No to chcê us³yszeæ jak¹œ opowieœæ.}
{141}{}{Cieszê siê, ¿e czujesz siê lepiej.}
{142}{}{Dziêkujê ci. ¯egnaj.}
{143}{}{Naprawdê przypominasz mi moj¹ córeczkê. Kiedy mia³a tylko kilka miesiêcy, jeœli chodzi o œcis³oœæ.}
{144}{}{Dziêkujê. Dharma zawsze powtarza³, i¿ rolnik, który sadzi grzecznoœæ, po ¿niwach bêdzie kroczy³ swobodnie.}
{145}{}{Opowiedz mi proszê jak¹œ historiê.}
{146}{}{Ten Dharma gada³ jak idiota.}
{147}{}{Obra¿asz swoich rodziców. Powinni ciê byli lepiej wychowaæ.}
