{100}{}{To Amber, nauczycielka Uczniów Apokalipsy.}
{101}{}{Teraz jest moja pora spoczynku. Proszê, przyjdŸ ponownie wieczorem.}
{102}{}{Witaj szlachetny wêdrowcze. Czy przybywasz tu, aby studiowaæ?}
{103}{}{Nie. Tak naprawdê, to przybywam tu, aby zabijaæ.}
{104}{}{To zale¿y od tego, czego chcesz mnie nauczyæ.}
{105}{}{Tak, pragnê siê uczyæ.}
{106}{}{Prawdziwie przykro mi to s³yszeæ. Uczniowie wierz¹ w pokój za wszelk¹ cenê. Z tego powodu wyrzek³am siê przemocy. Dobranoc.}
{107}{}{Jestem bieg³a w wielu jêzykach i naukach humanistycznych. Mo¿e chcesz nauczyæ siê czegoœ z tej dziedziny?}
{108}{}{Przykro mi, lecz potrzebujê wiedzy, która pomo¿e mi przetrwaæ.}
{109}{}{Nie mam czasu na takie rzeczy. Znikam.}
{110}{}{Chêtnie pos³ucham jakiejœ pieœni.}
{111}{}{Czy mo¿esz nauczyæ mnie czegokolwiek innego?}
{112}{}{Ach, wiêc studiujesz ¿ycie. W takim przypadku mogê nauczyæ ciê nieco zielarstwa, ale nauka zajmie trochê czasu.}
{113}{}{Œwietnie, po prostu mnie naucz.}
{114}{}{Proszê, naucz mnie tyle, ile mo¿esz.}
{115}{}{Przepraszam, ale naprawdê nie mam czasu dla roœlin. ¯egnaj.}
{116}{}{Niegrzecznoœæ nie jest nam potrzebna. Przeproœ natychmiast, albo nie bêdê ciê uczyæ.}
{117}{}{Przepraszam. Proszê, czy bêdziesz sk³onna mnie nauczaæ?}
{118}{}{Daruj sobie.}
{119}{}{Ju¿ lepiej. Zacznijmy twoje studia.}
{120}{}{Przyswajanie wiedzy œwietnie ci idzie. Oby wyzwania, jakie napotkasz, by³y ³atwe. Ruszaj w pokoju.}
{121}{}{Jak ci pasuje. Oby przysz³oœæ zmiêkczy³a twe serce i poszerzy³a twój umys³.}
{122}{}{Dobrze, nauczê ciê sposobów przetrwania.}
{123}{}{Przyswajanie wiedzy œwietnie ci idzie. Oby wyzwania, jakie napotkasz, by³y ³atwe. Ruszaj w pokoju.}
{124}{}{Nie przekonujesz mnie. Myœlê, ¿e chcesz u¿yæ moich darów w z³ych celach. Dobranoc.}
{125}{}{Ach, studentów sztuk wyzwolonych rzadko widzi siê na tym œwiecie. Byæ mo¿e jest jeszcze dla ciebie nadzieja. Ka¿da z pieœni jest d³uga. Któr¹ pragniesz us³yszeæ?}
{126}{}{Œladem Cienia.}
{127}{}{Balladê o Pysze.}
{128}{}{Ku pamiêci Artemidy.}
{129}{}{Podniesienie Rydwanu Œwitu.}
{130}{}{Zadziwiaj¹ce dzie³o. Udzielê ci wystêpu.}
{131}{}{Muszê odpocz¹æ. Nauczanie bardzo mnie wyczerpuje. ¯yczê ci powodzenia.}
{132}{}{Zadziwiaj¹ce dzie³o. Udzielê ci wystêpu.}
{133}{}{Muszê odpocz¹æ. Nauczanie bardzo mnie wyczerpuje. ¯yczê ci powodzenia.}
{134}{}{Zadziwiaj¹ce dzie³o. Udzielê ci wystêpu.}
{135}{}{Muszê odpocz¹æ. Nauczanie bardzo mnie wyczerpuje. ¯yczê ci powodzenia.}
{136}{}{Zadziwiaj¹ce dzie³o. Udzielê ci wystêpu.}
{137}{}{Muszê odpocz¹æ. Nauczanie bardzo mnie wyczerpuje. ¯yczê ci powodzenia.}
{138}{}{Obawiam siê, ¿e ju¿ o wiele za bardzo nadu¿y³am moich si³. Wybacz.}
{139}{}{Pokój i Piêkno to wszystko, czego mogê uczyæ. Przykro mi, ¿e ciê one nie poci¹gaj¹. ¯egnaj.}
{140}{}{Mogê nauczyæ ciê sztuki dawnych bardów i minstreli.}
{141}{}{Us³yszeæ pieœñ by³oby dla mnie zaszczytem.}
{142}{}{Mo¿e innym razem. Dziêkujê.}
{143}{}{Pragnê nauczyæ siê czegoœ, co mo¿e mi bardziej pomóc.}
{144}{}{Nie potrzebujesz moich talentów. Pokojowo nastawieni ludzie nauczyli siê od ciebie sztuki wojennej. Op³akujê ich teraz.}