{100}{}{To uszkodzony pancerz wspomagany.}
{101}{}{Nie mo¿esz go u¿ywaæ, dopóki nie zostanie naprawiony.}
{102}{}{Wygl¹da na to, ¿e brakuje mu czêœci, której nie jesteœ w stanie znaleŸæ.}
{103}{}{Jest oczywiste, ¿e nie posiadasz jeszcze umiejêtnoœci pozwalaj¹cych na jego naprawê.}
{104}{}{Naprawiasz pancerz.}
{105}{}{To nic nie daje.}
{106}{}{Nie uda³o ci siê naprawiæ pancerza.}
{107}{}{Za naprawienie pancerza wspomaganego zyskujesz }
{108}{}{ PD.}
