{100}{}{Hej, ziomuœ, mo¿esz wspomóc drobnymi?}
{101}{}{Próbujê tu piæ!}
{102}{}{Nie czujê siê najlepiej.}
{103}{}{Kurde, muszê znaleŸæ jak¹œ robotê.}
{104}{}{Mo¿esz podaæ orzeszki?}
{105}{}{Jeszcze nie doœæ alkoholu...}
{106}{}{Vistula... Vistula...}