{100}{}{Potê¿na eksplozja zamyka tunel!}
{101}{}{Upuszczasz materia³y wybuchowe, a one eksploduj¹!}
{102}{}{Eksplozja tylko powiêksza dziurê. Zamkniêcie jej nie bêdzie teraz mo¿liwe.}
{103}{}{Zyskujesz punkty doœwiadczenia za skuteczne u¿ycie materia³ów wybuchowych.}
