{100}{}{Jasny gwint! Zabiæ to!}
{101}{}{Zastrzeliæ t¹ bestiê, zanim go po¿re!}
{102}{}{Spluwy!}
{103}{}{Zabierzcie go stamt¹d!}
{104}{}{Nie w³aŸ do ringu, t³umoku.}
{105}{}{Ej, a ty, to niby dok¹d?}
{106}{}{Pogadaj z Gustoferem, jak chcesz obstawiæ.}
{107}{}{Mecze bokserskie odbywaj¹ siê o 2:00 co trzeci dzieñ.}