{100}{}{To mê¿czyzna, który przez chwilê spogl¹da ci intensywnie w oczy i zaraz odwraca wzrok.}
{101}{}{To Greg.}
{102}{}{Co? Czemu do mnie mówisz? Wiesz, oni to us³ysz¹.}
{103}{}{Czeœæ, jesteœ z powrotem. Nie mów tak g³oœno, bo oni tam s¹.}
{104}{}{OK, ale po cichutku; oni przyjd¹ po nas, jak nie przestaniesz krzyczeæ.}
{105}{}{Kim jesteœ?}
{106}{}{Czemu jesteœ taki nerwus?}
{107}{}{S¹dzê, ¿e "oni" powinni ci zwiêkszyæ dawkê lekarstw.}
{108}{}{Niewa¿ne.}
{109}{}{Jestem... Greg... ale nie pozwól, ¿eby ktoœ inny to wiedzia³, albo oni przyjd¹ mnie szukaæ.}
{110}{}{Nerwus, nie jestem nerwus. Tylko ostro¿ny. Wszyscy mówi¹, ¿e jestem paranoikiem, ale to ja tu zostanê, kiedy przyjd¹ po nas.}
{111}{}{Przyjd¹ po was? Kto ma po was przyjœæ?}
{112}{}{Z pewnoœci¹ jesteœ paranoikiem. Pogadamy póŸniej.}
{113}{}{No, oni... Ty wiesz, prawda... Ta choroba to tylko pocz¹tek. Teraz przyjd¹ i zabior¹ nas wszystkich. Ale ty jesteœ jak ca³a reszta. Nie wierzysz mi, i to ciê zgubi. Zapamiêtaj moje s³owa. JA BÊDÊ TU DALEJ, A TO WSZYSTKO, £¥CZNIE Z TOB¥, BÊDZIE ZABRANE. ZABRANE. [Greg chwyta siê za g³owê i zwija w k³êbek, kwicz¹c i miotaj¹c siê we wszystkie strony.]}
{114}{}{Lekarstwa... A, wiêc nale¿ysz do nich, próbujesz mnie nak³oniæ, ¿ebym znowu wzi¹³ lekarstwo... Ale ci siê nie uda. NIE WEZMÊ TEGO, NIE, NIGDY. G£OSY, NIE WEZMÊ, NIE ZMUSICIE MNIE. [Greg zamyka oczy i ³apie siê nerwowo za g³owê, rozmawiaj¹c z g³osami, które tylko on jest w stanie us³yszeæ.]}
{115}{}{NIE ZMUSISZ MNIE!}
{116}{}{NIC, CO ZROBISZ, MI NIE POMO¯E!}
{117}{}{TO KONIEC!}
{118}{}{NADCHODZ¥, A TY NIE JESTEŒ W STANIE ICH POWSTRZYMAÆ!}
{119}{}{DORWÊ WAS WSZYSTKICH!}

