{100}{}{To sklepikarz.}
{101}{}{Œwiêtego P³omienia nie raduj¹ z³odzieje i ³ajdacy kalaj¹cy miejsce jego kultu. Nie minie ciê kara!}
{102}{}{Hng!}
{103}{}{To nie by³a kradzie¿, szczerze!}
{104}{}{No to naskar¿ o tym Œwiêtemu P³omieniowi, kiedy siê z nim spotkasz po tej twojej "karze".}
{105}{}{Twe k³amstwa nie obchodz¹ mnie, ani Mistrza.}
{106}{}{Przykro mi, sklep jest nieczynny.}
{107}{}{Nugga.}
{108}{}{Dziêki za nic.}
{109}{}{A to czemu?}
{110}{}{Nie ma o czym mówiæ.}
{111}{}{Dzieci nie maj¹ obowi¹zku zadawania siê z takimi jak ty. A ty sprawiasz nam powa¿ny k³opot. Lepiej st¹d odejdŸ, zanim zmusisz mnie do wezwania posi³ków.}
{112}{}{Wcale nie musisz tego robiæ. ¯ywiê do was przyjazne uczucia.}
{113}{}{Wisi mi to.}
{114}{}{Odmawiam zadawania siê z tymi, którzy u¿ywaj¹ broni, by stawiaæ ¿¹dania. My, Dzieci, wyroœliœmy poza prostackie pos³ugiwanie siê uzbrojeniem.}
{115}{}{Ty ograniczaj¹cy prawo do posiadania broni, lewicowy œwirze!}
{116}{}{Pozwól, ¿e to schowam i pohandlujemy w pokoju.}
{117}{}{Dobrze, tego pragnê. Bêdê szczêœliwy mog¹c prowadziæ z tob¹ interesy.}
{118}{}{Pozdrawiam ciê, moje bliŸnie Dzieciê. Jak mogê ci pomóc?}
{119}{}{Tuwaar!?}
{120}{}{Czym handlujesz?}
{121}{}{Dziêki. Spotkamy siê w norze, aligatorze.}
{122}{}{Przepraszam. Mo¿e po prostu ubijemy interes.}
{123}{}{Czyrœæ!}
{124}{}{Jak wrócisz znad Nilu, krokodylu. Nie mogê uwierzyæ, ¿e to przed chwil¹ powiedzia³em.}
{125}{}{Pozdrawiam ciê! Jak mogê ci pomóc? Mam szczer¹ nadziejê, ¿e poœwiêcisz chwilê, by zdaæ sobie sprawê ze znaczenia wszelkich przysz³ych decyzji, jakie mo¿esz tylko podj¹æ, w odniesieniu do twej duszy...}
{126}{}{Haandyl!}
{127}{}{Czym handlujesz?}
{128}{}{Gdzie mogê dostaæ jedn¹ z tych waszych eleganckich szat...}
{129}{}{Tylko zaufanym cz³onkom Katedry wolno nosiæ œwiêt¹ purpurê.}
{130}{}{To chyba odpowiada na moje pytanie, dziêki!}
{131}{}{Zarozumia³y g³upcze, chyba muszê wzi¹æ twoj¹!}
{132}{}{A, trudno. Czym handlujesz?}
{133}{}{Ach, mam towar schlebiaj¹cy gustom prostaków, którzy tu przychodz¹. Nic szczególnie nadzwyczajnego. Œmia³o, rzuæ okiem.}
{134}{}{Dziêki, do zobaczenia.}
{135}{}{Mamy wszelkiego rodzaju nadzwyczajne przedmioty, które pomog¹ ci zapamiêtaæ twoj¹ podró¿ do Katedry. Tych wspomnieñ nie mo¿na kupiæ tanio, rozumiesz.}
{136}{}{Dziêki...}
{137}{}{Nie ma za co. ¯yczê ci samych przyjemnych dni przez resztê twego ¿ywota.}