{100}{}{Œciana tej czêœci jaskini wydaje siê mieæ nieco s³absz¹ strukturê ni¿ pozosta³e.}
{101}{}{W tym miejscu ska³a wygl¹da na bardzo popêkan¹ i w skrajnych warunkach najprawdopodobniej siê skruszy.}