{100}{}{To Mroczny.}
{101}{}{Giñ!}
{102}{}{OdejdŸ lub zgiñ!}
{103}{}{Nie podoba mi siê twój ton. Jeœli wiadomoœæ, któr¹ przynoszê, nie dotrze do Mistrza, dopilnujê, by twoja œmieræ by³a powolna i bolesna.}
{104}{}{Chcê ci tylko pogratulowaæ tego œwietnie wygl¹daj¹cego garba na twoim grzbiecie. Nad twoim oddechem przyda³oby siê jednak trochê popracowaæ...}
{105}{}{Czy móg³byœ skierowaæ mnie do dowódcy?}
{106}{}{Kurde, potrzebujesz alkoholu bardziej ni¿ ja!}
{107}{}{Nie odejdê!}
{108}{}{OK. Ja odejŸæ.}
{109}{}{Niem¹drze jest igraæ z Mrocznymi. Wynoœ siê st¹d!}
{110}{}{Nie s¹dzê.}
{111}{}{Uraduje mnie widok twojej œmierci!}
{112}{}{Nie s³uchasz? Niem¹drze jest ignorowaæ Mrocznych.}
{113}{}{Muszê z nim porozmawiaæ. To pilne!}
{114}{}{Nikt nigdy nie pos¹dzi³ mnie o m¹droœæ!}
{115}{}{Chcê tylko porozmawiaæ z dowódc¹!}
{116}{}{Ty niby twardziel abo co?}
{117}{}{Przepraszam! ¯yczê ci dobrego dnia.}
{118}{}{Chcesz zobaczyæ, co jest niem¹drze? Niem¹drze jest mi pyskowaæ, dupku!}
{119}{}{IdŸ na górê. Inni z mojego rodzaju oceni¹ wartoœæ twojej wiadomoœci.}
{120}{}{To moje ostatnie ostrze¿enie!}
{121}{}{A pewnie, ¿e tak! Wielka mi rzecz...}
{122}{}{Ja NAPRAWDÊ muszê porozmawiaæ z goœciem, który tu dowodzi!}
{123}{}{OK! OK! Przepraszam! ¯yczê ci dobrego dnia.}
{124}{}{Wiesz, co jest twoim b³êdem? Dajesz ostrze¿enia. Ja nie. Giñ!}
{125}{}{[Koniec]}