{100}{}{To ciemnoskóry mê¿czyzna przystrojony jaskrawymi szarfami i b³yskotkami.}
{101}{}{To Chuck, cygañski wró¿.}
{102}{}{Witaj, wêdrowcze. Czym mogê ci s³u¿yæ?}
{103}{}{Uugh!}
{104}{}{Tylko siê rozgl¹dam, dziêki.}
{105}{}{Zapoznajê siê z mieszkañcami Adytum.}
{106}{}{Z jakiego powodu zak³adasz, ¿e czegoœ mi trzeba?}
{107}{}{Hmm. Nie martw siê, mój prostaczku, czekaj¹ ciê wielkie czyny.}
{108}{}{I co s¹dzisz o naszym osiedlu?}
{109}{}{Jest w porz¹dku.}
{110}{}{Nie za bardzo mi siê podoba. Nieszczególnie przyjazne.}
{111}{}{Powodzi siê wam wyj¹tkowo dobrze, bior¹c pod uwagê niesprzyjaj¹ce okolicznoœci.}
{112}{}{Nazywam siê Chuck. Witaj w Adytum. Obawiam siê jednak, ¿e wiêkszoœæ tutejszych nie jest zbyt przychylnie nastawionych do obcych.}
{113}{}{Ta, da³o siê to zauwa¿yæ.}
{114}{}{No, to czym siê zajmujesz, Chuck?}
{115}{}{Do zobaczenia, Chuck.}
{116}{}{Szczêœliwych podró¿y, wêdrowcze.}
{117}{}{Wszyscy czegoœ potrzebujemy, nieprawda¿? Nie rozmawialibyœmy, gdyby czegoœ ci nie by³o trzeba - informacji, rozmowy, albo mo¿e porady. Widzê, ¿e spotka³o ciê wiele przeciwnoœci. Czego zatem potrzebujesz?}
{118}{}{Umm, ja niczego nie potrzebujê, dziêki.}
{119}{}{Skoro ju¿ o tym wspomnia³eœ, mo¿e móg³byœ mi coœ doradziæ.}
{120}{}{[Chuck wyjmuje taliê kart tarota.] Niech no zapytam siê kart. [Chuck tasuje karty.]}
{121}{}{[Chuck wyci¹ga kartê z obrazkiem przedstawiaj¹cym mê¿czyznê w fartuchu laboratoryjnym, z komputerem w d³oni, oraz kartê z mê¿czyzn¹ w pancerzu wspomaganym.] Arcykap³an i Król Pa³ek na po³udniu... wielka m¹droœæ i szlachetnoœæ oczekuj¹ w miejscu na po³udniu.}
{122}{}{[Chuck wyci¹ga kartê z obrazkiem przedstawiaj¹cym mê¿czyznê z wibroostrzem i flag¹.] Król Mieczy na pó³nocy... musisz zmierzyæ siê z potê¿nym wrogiem daleko na pó³nocy.}
{123}{}{[Chuck wyci¹ga kartê z obrazkiem przedstawiaj¹cym maszt radiowy, oraz kartê z mê¿czyzn¹ w garniturze, trzymaj¹cym ber³o.] Wie¿a i Cesarz... wielka zmiana nadchodzi z r¹k wielkiego przywódcy. Czy ta zmiana jest œmierci¹, nie jestem w stanie powiedzieæ.}
{124}{}{[Chuck wyci¹ga kartê z obrazkiem przedstawiaj¹cym mê¿czyznê tañcz¹cego na g³owicy j¹drowej.] G³upiec. Nie mogê ci pomóc; musisz samodzielnie utorowaæ sobie drogê przez œwiat.}
{125}{}{[Wiêcej]}
{126}{}{Hmm. Dziêki za radê.}
{127}{}{Czy ty faktycznie w to wierzysz?!}
{128}{}{Dla mnie dzia³a. Jeœli nie chcesz wierzyæ, to karty nie s¹ dla ciebie.}
{129}{}{Bez urazy, ale to brzmi jak kupa przes¹dów.}
{130}{}{Có¿, chyba wszyscy mamy swoje w³asne wierzenia.}
{131}{}{Je¿eli tak uwa¿asz, to przypuszczam, ¿e nie mamy ju¿ o czym rozmawiaæ.}
{132}{}{Rzeczywiœcie, mamy. Twój œwiat kszta³tuj¹ twoje wierzenia, podczas gdy mój kszta³tuj¹ moje myœli. Mo¿emy nie mieæ wspólnych wierzeñ, ale ¿yczê ci dobrze w twoim œwiecie.}
{133}{}{To nasz dom.}
{134}{}{Umm, tak. Do zobaczenia.}
{135}{}{Faktycznie wydaje siê tu byæ dosyæ spokojnie.}
{136}{}{Wiem, co masz na myœli. Na Pustkowiu mo¿na zobaczyæ bardzo du¿o cierpienia.}
{137}{}{Regulatorzy o to dbaj¹. Lud Adytum czasem cierpi z powodu ich surowych regu³.}
{138}{}{Chyba tak. Có¿, do zobaczenia.}
{139}{}{A tobie to nie przeszkadza?}
{140}{}{Poniewa¿ chcê tu zostaæ, akceptujê Regulatorów jako czêœæ tego, czym jest Adytum. Jednak robiê co w mojej mocy, ¿eby rozjaœniæ ¿ycie miejscowych.}
{141}{}{Nie wydajesz siê popieraæ tego, co robi¹.}
{142}{}{Jesteœ w stanie robiæ coœ jeszcze?}
{143}{}{Regulatorzy dbaj¹ o swój w³asny interes, a ja muszê to respektowaæ.}
{144}{}{Ta, jak tam sobie chcesz.}
{145}{}{Niekoniecznie zgadzam siê z tym pogl¹dem, ale potrafiê go zrozumieæ.}
{146}{}{Mi³o by³o porozmawiaæ. Do zobaczenia.}
{147}{}{Có¿, jestem tylko jednostk¹, ale pomagam tak, jak tylko mogê. Radzê ci walczyæ o to, w co wierzysz, ale przede wszystkim wybieraj te walki, które s¹ warte toczenia, i naucz siê rozpoznawaæ momenty, gdy kompromisem i nadziej¹ mo¿na zyskaæ wiêcej.}
{148}{}{Czy masz jeszcze jakieœ inne rady?}
{149}{}{Lud Adytum ma w zwyk³e dni bardzo du¿o do zrobienia. Nie chc¹, by pod wieczór ich praca jeszcze nie by³a wykonana.}
{150}{}{Ta, no, jak sobie chcesz.}
{151}{}{Faktycznie wydaje siê tu byæ dosyæ spokojnie.}
{152}{}{Dziêkujê. Jest nam trudno. Czasem tracimy ludzi przez Szpony Œmierci, i zimy potrafi¹ byæ ciê¿kie, zw³aszcza gdy kupcy z Hubu nie przybêd¹. Ale udaje nam siê prze¿yæ.}
{153}{}{Powodzenia.}
{154}{}{O co chodzi ze Szponami Œmierci?}
{155}{}{Roj¹ siê na pó³nocny wschód st¹d i czêsto odbieraj¹ ¿ycie ludziom wyznaczonym do handlowania ze Zbrojeniowcami.}
{156}{}{Mam nadziejê, ¿e uda wam siê temu zaradziæ.}
{157}{}{Ta. Mi to wisi.}
{158}{}{Byæ mo¿e. Myœlê, ¿e Adytum siê nie zmieni. Zamiast iœæ w œwiat, œwiat musi przyjœæ do nas, tak jak ty.}
{159}{}{Hmm. Chyba tak.}
{160}{}{Jestem rolnikiem. Lubiê te¿ popracowaæ trochê przy budynkach, remontowaæ je i konserwowaæ, a czasem udzielam porad.}
{161}{}{Jakiego rodzaju porad?}
{162}{}{Tak, niestety. Uwa¿am... to swego rodzaju próba; dziêki prze¿yciu tych ciê¿kich czasów zaczniemy polegaæ na sobie nawzajem i nauczymy siê umiejêtnoœci koniecznych do przetrwania. Myœlê, ¿e w ostatecznym rachunku ludzkoœæ stanie siê po tym lepsza.}
{163}{}{Nie zgadzam siê. Znam ju¿ wiele gangów i band najeŸdŸców. Stali siê drobnymi mordercami i z³odziejami. Ja uwa¿am, ¿e ostatecznie w³aœnie to nam wszystkim grozi.}
{164}{}{Mo¿e masz racjê. Z pewnoœci¹ ci, którzy przetrwaj¹, bêd¹ silniejsi.}
{165}{}{W koñcu sami siê wyniszcz¹. A wtedy pozostan¹ ludzie, którzy wspó³pracuj¹ ze sob¹, by prze¿yæ, tacy jak my.}
{166}{}{Cieszê siê, ¿e niektórzy z nietutejszych, tak jak ty, myœl¹ w ten sposób. Musimy znaleŸæ metodê, ¿eby razem pracuj¹c zbudowaæ coœ nowego. Tu siê to nie zacznie, jesteœmy za bardzo uregulowani, ale gdzieœ musi.}
{167}{}{Witaj. Co mogê dla ciebie zrobiæ?}
{168}{}{Czy mogê ci pomóc?}
{169}{}{Tak?}
{170}{}{Tylko przystajê, ¿eby powiedzieæ "czeœæ".}
{171}{}{Potrzebujê drobnej porady.}
{172}{}{Czy mogê zapytaæ, czym siê tu zajmujesz?}
{173}{}{No to czeœæ. Mam nadziejê, ¿e dobrze ci idzie.}
