{100}{}{[Wiêcej]}
{101}{}{[Koniec]}
{102}{}{Matole! Znowu jesteœ ranny, ty g³upi skurwielu!}
{103}{}{Matole! Znowu jesteœ ranna, ty g³upia suko!}
{105}{}{? Ty dupo! Nie s³uchasz przes³ania Pokoju!}
{106}{}{Hej, ja tylko staram siê dopomóc Sprawie!}
{107}{}{Chcê ci zadaæ parê pytañ.}
{108}{}{Po prostu postaw mnie na nogi, OK, doktorku?}
{109}{}{Twoje rynsztokowe maniery s¹ do dupy.}
{110}{}{Doktorku, muszê siê napiæ, koniecznie! Masz jakiœ spirytus salicylowy?}
{111}{}{Mów tak dalej, a tobie bêdzie potrzebny lekarz.}
{112}{}{A³! Uuuu! Hnnh!}
{113}{}{Czego chcesz?! Czy wy, dupki, nigdy siê nie nauczycie? Mam dosyæ praktykowania moich talentów na ³amagach. Nastêpnym razem strzelaj prosto! Nie daj siê im trafiæ.}
{114}{}{Mieli przewagê liczebn¹!}
{115}{}{Kim ty jesteœ, lekarzem od dziur w dupie?}
{116}{}{Mo¿e u¿yjê ciebie w charakterze cela æwiczebnego.}
{117}{}{Nieudolny skurwysynie! ZNOWU wymagasz leczenia! Mam nadziejê, ¿e nastêpnym razem ciê zabij¹!}
{118}{}{Dziêki za wsparcie moralne, doktorku.}
{119}{}{Mam nadziejê, ¿e ciebie te¿ dorw¹...}
{120}{}{Jeœli tak zrobi¹, ty pójdziesz do piachu w pierwszej kolejnoœci.}
{121}{}{Z czym masz problem, dupo? Mo¿e mam ciê uœpiæ, matole!}
{122}{}{Du¿o ludzi usypiasz, doktorku?}
{123}{}{Lepiej nie próbuj.}
{124}{}{Jak ja chrapnê, to ty chrupniesz, dupku!}
{125}{}{Sprawie nie pomagaj¹ debile! Czemu zawracasz mi g³owê? Jestem bardzo zajêtym lekarzem, dupo! Potrzebujesz mnie, czy nie?}
{126}{}{Co ciê tak zajmuje?}
{127}{}{Pewnie, doktorku.}
{128}{}{Nie teraz.}
{129}{}{Jaka jest twoja diagnoza, doktorku?}
{130}{}{Nie jestem bibliotek¹! Poszukaj gdzie indziej odpowiedzi! Natychmiast wynocha!}
{131}{}{Œwietnie! Zawsze tylko "Za³ataj mnie!", "Postaw mnie na nogi!". Dupo!}
{132}{}{Mówi¹ o tobie bardzo z³e rzeczy...}
{133}{}{Wrogów Mistrza nic nie powstrzyma przed oczernianiem Wiernych.}
{134}{}{Z³o¿y³eœ przysiêgê, doktorze. Rób swoje.}
{135}{}{Zapomnij o tym. Nie mogê ci ufaæ.}
{136}{}{Lecz mnie lub giñ, doktorze!}
{137}{}{To powinno za³atwiæ sprawê...}
{138}{}{A³³³!!}
{139}{}{Ha ha ha!}
{140}{}{Wrzeszczysz jak kobieta! Ha ha ha!}
{141}{}{Suki nie powinny siê pchaæ do mêskiego œwiata! Ha ha ha!}
{142}{}{IdŸ do diab³a! Chcesz, ¿ebym ciê posk³ada³, czy tylko chcesz byæ dupkiem?}
{143}{}{Ty ³ajzo! Czemu po prostu nie wpe³zniesz do Blasku i nie zaczniesz wylizywaæ ka³u¿? G³upia, pijana, uzale¿niona dupo!}
{144}{}{A mo¿e któregoœ dnia bêdziesz potrzebowaæ lekarza, a lekarza nie bêdzie. Psycho-dupo! Mam ciê postawiæ na nogi? Mo¿e przy okazji zrobiê te¿ coœ z tym gównem w twoim mózgu!}
{145}{}{W porz¹dku - rób to i zamknij siê!}
{146}{}{IdŸ do diab³a.}
{147}{}{Zamknij siê i podaj mi diagnozê.}
{148}{}{Ty g³upi oœle! Masz za ma³o rozumu, ¿eby poczuæ ból. Przypominasz mi ni¿sz¹ formê ¿ycia!}
{149}{}{Mówi¹, ¿e z ciebie taki sam szaleniec, jak g³upek!}
{150}{}{Ha ha! Naprawdê nie masz oleju w g³owie! W³aœnie poda³em ci œmierteln¹ truciznê! Ha ha ha!}
{151}{}{To bêdzie cholernie boleæ!}
{152}{}{Aaaaach!}
{153}{}{Kwiczysz jak kastrowana œwinia! Ha ha ha!}
{154}{}{Przyg³up z ciebie! Liczy siê jakoœæ, nie iloœæ! Myœlisz, ¿e Mroczni przejmuj¹ siê, gdy s¹ w mniejszoœci? IdŸ siê wyp³akaæ do mamusi, maluchu! No to w koñcu chcesz wydobrzeæ, czy nie?}
{155}{}{Cicho b¹dŸ, albo usunê ci struny g³osowe! Uciszê ciê jak psa!
 Ha ha ha! To w koñcu chcesz wydobrzeæ, czy nie?}
{156}{}{Jestem lekarz, nie czirliderka! Potrzebujesz leczenia, czy nie?}
{157}{}{Trzêsê siê ze strachu, dupo! To w koñcu chcesz wydobrzeæ, czy nie?}
{158}{}{Zrób to. Tylko mnie nie spieprz!}
{159}{}{Jak cholera. Gdzieœ tu musi byæ prawdziwy lekarz.}
{160}{}{Najpierw rzuæ okiem i zobacz, co jest nie tak.}
{161}{}{Mroczni to preferuj¹. Czasem dajê im narkotyki. Nikt nie zwraca uwagi na doktora Wu. To same dupki! W koñcu chcesz, ¿ebym ciê posk³ada³?}
{162}{}{Za³ataj to, doktorku!}
{163}{}{Skoro Mroczni ci nie ufaj¹, to ja te¿ nie. Znikam st¹d.}
{164}{}{Matole! Katedra jest bardzo zajêta! Jednoœæ sprawia, ¿e doktor Wu jest bardzo zajêty. To w koñcu chcesz, ¿ebym ciê posk³ada³?}
{165}{}{Czas na najzabawniejszy moment!}
{166}{}{To powinno za³atwiæ sprawê...}
{167}{}{Co za debil! S³ysza³em o wiele wiêcej krzyków w wykonaniu dzieci! Ha ha ha!}
{168}{}{Doprowadzi³em sukê do jêku! Ha ha ha!}
{169}{}{Dupa! Mato³! Jestem bardzo zajêty, a ty mi musisz zawracaæ g³owê! Pierdolê ciê! Wynoœ siê st¹d, ty rzygowino! Ale ju¿!}
{170}{}{Zdrowiem dorównujesz braminowi, ale nie rozumem! Wynoœ siê st¹d, hipochondryczna dupo!}
{171}{}{Masz parê ran. Mogê je za³ataæ, fiucie, je¿eli siê nie bêdziesz poruszaæ!}
{172}{}{Traktujesz swoje cia³o jak kawa³ gówna. Z pewnoœci¹ jest z ciebie autentyczny idiota. Mogê wybawiæ ciê z twojej niedoli, albo ciê posk³adaæ.}
{173}{}{Nie teraz.}
{174}{}{W porz¹dku. Ale mam nadziejê, ¿e jeszcze przed wieczorem zrobiê sekcjê twoich zw³ok!}
{175}{}{A³! Ty kurw...}
{176}{}{Teraz siê st¹d wynoœ i nie wracaj!}
{177}{}{W porz¹dku, wyleczê ciê!}
{178}{}{To powinno naprawdê skutecznie postawiæ ciê na nogi!}
{179}{}{No to st¹d odejdŸ, dupo! Ju¿ nied³ugo zaœmiejê siê nad twoimi zw³okami.}
{180}{}{Ty smarkata dupo! Za kogo ty siê uwa¿asz, ¿e zawracasz g³owê doktora Wu? G³upi matole!}
{181}{}{Masz parê ran. Mogê je za³ataæ, fiucie, je¿eli siê nie bêdziesz poruszaæ!}
{182}{}{Przynajmniej piêæ z³amanych koœci, poza tym wielka utrata krwi. Bycie idiot¹ jest szkodliwe dla zdrowia! Chcesz, ¿ebym nad tob¹ popracowa³?}
{183}{}{Zale¿y jak definiujesz "popracowa³". Mo¿esz mnie LECZYÆ, doktorku.}
{184}{}{Ja iœæ.}
