{100}{}{To wêdrowny kupiec azjatyckiego pochodzenia.}
{101}{}{To Duc, wêdrowny kupiec.}
{102}{}{O witaj, wêdrowcze. Nazywam siê Duc i zmierzam do Cienistych Piasków, by trochê pohandlowaæ. Mo¿e zainteresuj¹ ciê moje towary?}
{103}{}{Co masz na sprzeda¿?}
{104}{}{Czy czêsto odwiedzasz Cieniste Piaski?}
{105}{}{Erf!}
{106}{}{Pozwól mi je zaprezentowaæ.}
{107}{}{Tak, Cieniste Piaski s¹ czêœci¹ mojej zwyk³ej trasy handlowej. Dla bezpieczeñstwa mo¿esz udaæ siê tam z nami, jeœli masz ochotê.}
{108}{}{Pewnie, brzmi to nieŸle.}
{109}{}{Nie, dziêki.}
{110}{}{O, przepraszam - nie zauwa¿y³em, ¿e jesteœ a¿ takim g³upolem.}
{111}{}{To powinno nam zaj¹æ jeden dzieñ lub tylko nieco d³u¿ej. Ruszajmy!}
{112}{}{ShadyW.map}
{113}{}{Niewielu ludzi zmaga siê z Pustkowiem w pojedynkê. Kim jesteœ?}
{114}{}{Nie twoja sprawa.}
{115}{}{Jestem }
{116}{}{.}
{117}{}{Erf!}
{118}{}{Witaj ponownie! Co mogê dla ciebie zrobiæ?}
{119}{}{Czy mogê przy³¹czyæ siê do twojej grupy w drodze do Cienistych Piasków?}
{120}{}{Co masz na sprzeda¿?}
{121}{}{Nic, dziêki.}
{122}{}{Czego chcesz?}
{123}{}{Nic, przepraszam.}
{124}{}{Co masz na sprzeda¿?}
{125}{}{Erf!}
{126}{}{Lepiej zachowaj ostro¿noœæ, je¿eli podró¿ujesz samotnie. Parê osób ostatnio zaginê³o w okolicy Cienistych Piasków.}
{127}{}{Hej, s³ysza³em, jak uda³o ci siê uratowaæ tê kobietê z Cienistych Piasków. Dobra robota.}