{100}{}{To Dugan, cz³onek Ostrzy uzale¿niony od Nuka-Coli.}
{101}{}{To bardzo wysoki, wychudzony mê¿czyzna w okularach. W d³oni kurczowo œciska butelkê Nuka-Coli.}
{102}{}{Tak?}
{103}{}{Tylko siê rozgl¹dam, dziêki.}
{104}{}{Co tu robisz?}
{105}{}{O co chodzi z t¹ Nuka-Col¹?}
{106}{}{Kto tu jest szefem?}
{107}{}{E, niewa¿ne.}
{108}{}{Ba, Cola, dobra?}
{109}{}{Có¿, to przestañ marnowaæ mój czas.}
{110}{}{Du¿o kontemplujê ¿ycie i pomagam Ostrzom zrozumieæ prawdziwe znaczenie Nuka-Coli.}
{111}{}{Co jest takiego dobrego w Nuka-Coli?}
{112}{}{To wszystko? Nie wydaje siê to komukolwiek zbytnio pomagaæ.}
{113}{}{Ile tego wypijasz?}
{114}{}{Czy mogê spytaæ ciê o coœ innego?}
{115}{}{A, OK. Jeszcze siê zobaczymy.}
{116}{}{To esencja ¿ycia... Có¿, w rzeczywistoœci, je¿eli nie pijê jej co godzinê, to dostajê koszmarnego bólu g³owy.}
{117}{}{I co? [Dugan unosi brwi.]}
{118}{}{Mniej wiêcej 5 litrów dziennie.}
{119}{}{Brzytwa to kobieta, z któr¹ chcesz rozmawiaæ.}
{120}{}{Jestem najdurniejsz¹ osob¹, jak¹ kiedykolwiek spotka³em - no, poza tob¹. Wynoœ siê st¹d!}
{121}{}{Potrzebujê kolejnej Nuka-Coli!}
{122}{}{Gdzie siê podzia³y moje w³osy?!}
{123}{}{Woda, dwutlenek wêgla, barwnik karmelowy, Aspartam, kwas fosforowy, benzoesan potasu - stabilizator, naturalne aromaty, kwasek cytrynowy - regulator kwasowoœci, kofeina.}
{124}{}{Szkoda, ¿e skoñczy³a siê nam Light.}
{125}{}{Gdzie siê podzia³y te niskie kobiety?}