{100}{}{To stra¿nik Wszêdobylskich Handlowców.}
{101}{}{Ci cholerni Kupcy Wodni roluj¹ nas wszystkich.}
{102}{}{Pamiêtaj, ¿eby sp³acaæ PTP na czas, ci goœcie s¹ œmiertelnie niebezpieczni.}
{103}{}{Musisz porozmawiaæ z Rutgerem.}
{104}{}{Wszêdobylscy Handlowcy s¹ najlepsi.}
{105}{}{Karmazynowa Karawana to banda idiotów i wariatów.}
{106}{}{Hmm, mam wielk¹ ochotê na iguanê na patyku.}
{107}{}{Kto, u diab³a, porywa nasze karawany?}
{108}{}{Mój brat by³ w ostatniej z zaginionych karawan.}
{109}{}{Ci wodni sk¹pcy za to odpowiadaj¹, na pewno.}
{110}{}{Mówi¹, ¿e karawany przechwycili mutanci. To straszne.}
{111}{}{S³yszê, ¿e mówisz o mutantach. Mam nadziejê, ¿e zap³acili krwi¹.}
{112}{}{Zdawa³o mi siê, ¿e odpowiada za to Szpon Œmierci, cholerni mutanci.}
{113}{}{Nieczynne. Wróæ rano.}
{114}{}{Hej, tu nie Sokó³. Wynoœ siê do Diab³a.}
{115}{}{Czym ty jesteœ? Czymœ w rodzaju ³acha? Wynoœ siê do Diab³a.}
{116}{}{Spadaj!}
{117}{}{Mamy otwarte tylko za dnia.}
{118}{}{Jesteœ na haju? To sp³ywaj.}
{119}{}{Musisz wróciæ tu rano.}