{100}{}{Pilnuj siê przy doktorku, to nie bêdê musia³ zrobiæ ci z gêby jesieni Œredniowiecza.}
{101}{}{Zamkniête. PrzyjdŸ póŸniej.}
{102}{}{Muszê zobaczyæ doktorka.}
{103}{}{OK, zrobiê tak.}
{104}{}{Muszê siê zobaczyæ z doktorem w bardzo wa¿nej sprawie.}
{105}{}{Hnnn.}
{106}{}{£adn¹ mamy pogodê, co?}
{107}{}{To wielka szkoda. Wynoœ siê st¹d i nie wracaj do rana. Ten gabinet nie jest czynny w nocy.}
{108}{}{Zaczekaj chwilê, muszê sprawdziæ, co na to doktorek.}
{109}{}{Czego znowu chcesz?}
{110}{}{Muszê zobaczyæ doktorka.}
{111}{}{Czy doktor jest teraz wolny?}
{112}{}{Hnnn!}
{113}{}{Mowy nie ma. Doktorek œpi. PrzyjdŸ póŸniej.}
{114}{}{Nie wim, porozmawiaj z nim osobiœcie.}
{115}{}{Ta, OK. Wynoœ siê.}
{116}{}{Ej, to w³asnoœæ prywatna. Lepiej st¹d odejdŸ, natychmiast.}
{117}{}{Ze¿ryj moje gówno.}
{118}{}{Jak nie zejdziesz mi z drogi, bêdziesz potrzebowaæ doktora z powodów osobistych.}
{119}{}{Nie wiesz, ¿e kobiety to s³aba p³eæ?}
{120}{}{Myœlisz, ¿e jestem s³aba? To co powiesz na to...}
{121}{}{Ju¿ wychodzê.}
{122}{}{Zabierz swoje cherlawe groŸby i leæ do domu, do mamusi. Gadasz tu z prawdziwym facetem.}
{123}{}{Myœlisz, ¿e jestem s³aby? To co powiesz na to...}
{124}{}{Ju¿ wychodzê.}
{125}{}{Rety! Je¿eli naprawdê chcesz go zobaczyæ, to zapraszam.}
{126}{}{Có¿, a kiedy mo¿na tu zastaæ doktora?}
{127}{}{Doktorek przyjmuje pacjentów od ósmej do pi¹tej. Teraz wynocha st¹d.}
{128}{}{Kiedy mo¿na tu zastaæ doktora?}