{100}{}{To kupiec z Wszêdobylskich Handlowców.}
{101}{}{Wynoœ siê do diab³a.}
{102}{}{Znikaj, bo nie po¿yjesz na tyle d³ugo, ¿eby po¿a³owaæ.}
{103}{}{£achu!}
{104}{}{Chcesz trochê, œmieciu?}
{105}{}{Masz ochotê na wiêcej bólu?}
{106}{}{Nie zmuszaj mnie do zrobienia ci wiêkszej krzywdy!}
{107}{}{Pragniesz umrzeæ, czy co? Sp³ywaj.}