{100}{}{Okazuje siê, ¿e na twojej drodze stoi zamkniêty zamek.}
{101}{}{Zrêcznie otwierasz zamek.}
{102}{}{Otwarcie tego zamka jest dla ciebie zbyt trudne.}
{103}{}{Nie udaje ci siê otworzyæ zamka.}
{104}{}{Zamek jest ju¿ otwarty.}
{105}{}{Twój wytrych ulega z³amaniu wewn¹trz zamka.}
