{100}{}{Witaj! Czym mogê ci s³u¿yæ?}
{101}{}{Kim jesteœ?}
{102}{}{Co robisz?}
{103}{}{OK, dawaj wszystko, co masz.}
{104}{}{£ub!}
{105}{}{Nazywam siê Lox. Jestem kupcem.}
{106}{}{Nazywam siê Terrance. Jestem handlowcem.}
{107}{}{Nazywam siê Julian. Jestem druciarzem.}
{108}{}{Jestem Dale. Kupujê i sprzedajê drobnicê.}
{109}{}{Kierujê siê do Adytum, by sprzedaæ tam nieco towarów.}
{110}{}{Zmierzam do Z³omowa, aby trochê pohandlowaæ.}
{111}{}{Wêdrujê do Hubu, ¿eby sprzedaæ mój towar.}
{112}{}{Zmierzam do Nekropolis w celach badawczych.}
{113}{}{Aaak!}
{114}{}{Czy mogê siê do ciebie przy³¹czyæ?}
{115}{}{Pewnie, chodŸ. Dobrze mieæ towarzystwo.}
{116}{}{Wybacz, mam ju¿ komplet.}
{117}{}{Niestety, ale chyba nie mogê ci zaufaæ.}