{100}{}{Stój!}
{101}{}{Giñ, cz³owiecze!}
{102}{}{Na œmieræ.}
{103}{}{Zap³acisz za twe grzechy!}
{104}{}{Nie powinieneœ byæ tutaj uzbrojony, ma³y bracie. Wyt³umacz siê.}
{105}{}{Nie powinnaœ byæ tutaj uzbrojona, ma³a siostro. Wyt³umacz siê.}
{106}{}{Hngg.}
{107}{}{To dozwolone, ja tu pracujê.}
{108}{}{To dozwolone, mam przepustkê.}
{109}{}{Noszê broñ za pozwoleniem porucznika.}
{110}{}{Có¿ to za podstêp?!}
{111}{}{Poka¿ mi j¹ zatem.}
{112}{}{Eee, zosta³a w moim drugim habicie.}
{113}{}{Tu jest, w lufie mojej spluwy.}
{114}{}{Zatem pospiesz siê ze swoim zadaniem, lecz wiedz, ¿e ciê obserwujê.}
{115}{}{Tak, ma³y bracie. Czego to ode mnie potrzebujesz?}
{116}{}{Tak, ma³a siostro. Czego to ode mnie potrzebujesz?}
{117}{}{Hng!}
{118}{}{Hmm, gdzie znajdê tego goœcia, Mistrza?}
{119}{}{Chwalmy Jednoœæ, bracie.}
{120}{}{Przykro mi, lecz drogê do Jednoœci musisz odkryæ samodzielnie.}
{121}{}{NajwyraŸniej nale¿ysz do pogan! P³aæ za twe grzechy!}
{122}{}{Rezyduje On na Poziomie 3, tak jak musi. Czemu zadajesz mi tak niedorzeczne pytanie?}
{123}{}{Och, e, bez powodu.}
{124}{}{Wykopiê st¹d jego dupê do, ee, jakiegoœ naprawdê odleg³ego miejsca!}
{125}{}{Jakie pytanie? To by³o "Cieszmy siê wielkoœci¹ Mistrza.".}
{126}{}{Obra¿asz mnie! Giñ!}
{127}{}{Chwalmy Jednoœæ.}
{128}{}{Wydajesz siê nie wierzyæ w to, co mówisz. Czy to mo¿e byæ prawd¹? Czy nie kroczysz ju¿ œcie¿k¹ prawoœci?}
{129}{}{Bierzesz dr¿enie mojego g³osu za objaw strachu, podczas gdy w rzeczywistoœci to jakieœ przeziêbienie.}
{130}{}{W rzeczywistoœci wierzê, i¿ twój rodzaj jest skazany na zag³adê. Pozwól, ¿e to od razu udowodniê z niewielk¹ pomoc¹ moich przyjació³...}
{131}{}{Kiedy staniesz siê jednym z nas, tak drobne sprawy nie bêd¹ przyprawiaæ twojego g³osu o dr¿enie. OdejdŸ.}
{132}{}{Czego chcesz tym razem? Mam ma³o czasu na twoje gadanie.}
{133}{}{£abbo!}
{134}{}{A ja mam ma³o czasu na twoje ¿ycie... Giñ!}
{135}{}{Nic, przepraszam.}
{136}{}{Chwalmy Jednoœæ, bracie.}
{137}{}{Kim ty w ogóle jesteœ? Niech no spojrzê... Ahgh! Intruzem!}
{138}{}{Ruszaj. Wykonaj tw¹ pracê na rzecz Jednoœci i przestañ zawracaæ mi g³owê!}
{139}{}{Zbieraj siê.}
{140}{}{Ruszaj. Wykonaj tw¹ pracê na rzecz Jednoœci.}
