{100}{}{To skryba.}
{101}{}{Vree jest moj¹ idolk¹.}
{102}{}{Vree jest taka œliczna.}
{103}{}{Sophia jest bardzo mi³a.}
{104}{}{Derek jest zajebistym goœciem.}
{105}{}{Czy wszechœwiat bêdzie siê nadal rozszerzaæ, czy te¿ zacznie siê zwê¿aæ i w koñcu zapadnie siê w sobie? A mo¿e ta teoria jest fa³szywa, i nasz wszechœwiat powsta³ w wyniku zderzenia dwóch innych?}
{106}{}{Uwielbiam te stare ksi¹¿ki i czasopisma, ale tak trudno je zdobyæ.}
{107}{}{Wiedza to potêgi klucz.}
{108}{}{Pióro jest potê¿niejsze od miecza.}
{109}{}{Technologia musi zostaæ zachowana.}
{110}{}{Nauki œcis³e to œwietna zabawa.}
{111}{}{Zdarzy³o mi siê ju¿ widzieæ obcy statek kosmiczny.}
{112}{}{Czy wiesz, ¿e S³oñce to w rzeczywistoœci wielki reaktor termoj¹drowy?}
{113}{}{Czy wiesz, ¿e czarna dziura to w rzeczywistoœci przejœcie do innego wszechœwiata?}
{114}{}{Czy wiesz, ¿e atom wodoru to w 99,9843425% pusta przestrzeñ?}
{115}{}{Kiedyœ mo¿liwe stan¹ siê podró¿e w czasie, i bêdziemy mogli zapobiec katastrofie, która w przesz³oœci zdruzgota³a nasz œwiat.}
{116}{}{Prowadzenie badañ to jedna z moich ulubionych czynnoœci. Czujê siê wtedy jak przy rozwi¹zywaniu zagadki.}
{117}{}{Bycie skryb¹ jest najlepsze. Mo¿na studiowaæ wszystkie stare technologie i staraæ siê opracowywaæ nowe.}
{118}{}{Te terminale przyda³oby siê ulepszyæ. Mo¿e powinniœmy wyœwietlacz umieœciæ tutaj.}
{119}{}{Wybacz, jestem w samym œrodku mo¿liwego prze³omu. Nie mogê teraz rozmawiaæ.}
{120}{}{Hej, kadecie. Jeœli jeszcze nie wiesz, co robiæ, szkol siê na skrybê.}
{121}{}{To my projektujemy wszelki sprzêt, broñ i materia³y zaopatrzeniowe. To bardzo ekscytuj¹ce.}
{122}{}{Proszê mi nie przeszkadzaæ, staram siê ukoñczyæ mój projekt badawczy.}
{123}{}{Ta kobieta tam, to Vree; ona te¿ jest skryb¹.}