{100}{}{Ej!}
{101}{}{Broñ tu zakazana!}
{102}{}{Uwa¿aj!}
{103}{}{Huzia!}
{104}{}{Przestañ siê skradaæ!}
{105}{}{¯adnych podchodów tutaj!}
{106}{}{Ej, ty! Przestañ siê chowaæ, albo wynocha!}
{107}{}{Co?}
{108}{}{Hej, czy mogê ci zadaæ parê pytañ?}
{109}{}{Czy masz na zbyciu parê kapsli?}
{110}{}{Niewa¿ne, przepraszam.}
{111}{}{Uuuch?}
{112}{}{Byle szybko. Jestem na s³u¿bie.}
{113}{}{Nie. Sp³ywaj.}
{114}{}{Mo¿esz mi coœ powiedzieæ o twoim szefie?}
{115}{}{Co jeszcze jest w tym mieœcie?}
{116}{}{Co ty, przyg³up? Zabieraj siê.}
{117}{}{Nie. IdŸ ¿ebraæ gdzieœ indziej.}
{118}{}{Odchrzañ siê.}
{119}{}{Niepotrzebni nam tu nêdzarze.}
{120}{}{Gizmo to uczciwy cz³owiek. Zap³ata jest dobra, praca lekka. Nie rób k³opotów, to wszyscy bêd¹ zadowoleni.}
{121}{}{IdŸ na parê drinków do Nory Szumowin. Maj¹ tam dobry grog. Otwieraj¹ o czwartej. Teraz daj mi spokój.}
{122}{}{Czemu nie pójdziesz na zakupy do Killiana? Jego sklep jest na po³udniowy wschód st¹d. Teraz spadaj.}
{123}{}{Pogadaj z krupierami.}
{124}{}{Hej, jak chcesz siê trochê zabawiæ, wpadnij do Noclegowni i zapytaj o Sinthiê. Jest tego warta.}
{125}{}{¯adnego kantowania.}
{126}{}{D³u¿nicy zostan¹ rozstrzelani.}
{127}{}{Kurde, ale mnie boli kark.}
{128}{}{Ta robota to katorga.}
{129}{}{Uwielbiam ten lokal.}
{130}{}{Chyba dzisiaj odwiedzê Sinthiê.}
{131}{}{Wynocha st¹d, t³umoku.}
{132}{}{Broñ tu zakazana!}
{133}{}{Ej! Ty! Schowaj to!}