{100}{}{Przed tob¹ znajduje siê stó³ do gry w koœci na du¿e stawki. Jedna gra kosztuje 40 kapsli.}
{101}{}{Wyrzucasz 7. Wygrywasz!!}
{102}{}{Wyrzucasz gadzie oczka. Przegrywasz.}
{103}{}{Wyrzucasz }
{104}{}{! Wygrywasz!!}
{105}{}{Wyrzucasz }
{106}{}{. Przegrywasz.}
{107}{}{Wyrzucasz }
{108}{}{ przed wypadniêciem twojego punktu. Przegrywasz.}
{109}{}{Wyrzucasz twój punkt. Wygrywasz.}
{110}{}{Wyrzucasz }
{111}{}{. To twój punkt. Ponowny rzut.}
{112}{}{Za rozbicie banku zyskujesz 70 punktów doœwiadczenia.}
