{100}{}{To przewodnik karawany.}
{101}{}{Dzisiaj bêdzie d³ugi dzieñ!}
{102}{}{Naprawdê nie chce mi siê dzisiaj harowaæ.}
{103}{}{Mam nadziejê, ¿e nie napadn¹ nas najeŸdŸcy... albo gorzej.}
{104}{}{Przykro mi, nie trzeba nam ju¿ wiêcej stra¿ników... tak myœlê.}
{105}{}{Wybacz, mamy komplet.}
{106}{}{Jeœli szukasz roboty, to sprawdŸ na Targu.}
{107}{}{Mam nadziejê, ¿e wszystko sprzedamy.}
{108}{}{Nie mogê siê doczekaæ koñca tej trasy.}
{109}{}{Chêtnie skopiê parê zadów.}
{110}{}{Zmywamy siê st¹d!}
{111}{}{Dzisiaj faktycznie by³o gor¹co.}
{112}{}{Rany, ale mi siê chce piæ.}
{113}{}{Jaki dzisiaj dzieñ?}
{114}{}{Jak tylko skoñczê, natychmiast polecê do Soko³a!}
{115}{}{Przykro mi, akurat wracamy z trasy.}
{116}{}{Je¿eli szukasz roboty, to sprawdŸ na Targu.}
{117}{}{Dzisiaj wyp³ata!}
{118}{}{Idê prosto do Boba!}
{119}{}{Muszê dzisiaj sp³aciæ po¿yczkê!}
{120}{}{Ale mnie dopad³o zmêczenie.}
{121}{}{To by³a d³uga wyprawa!}
