{100}{}{Praktykujemy leczenie cia³a, by uleczyæ ducha. Czy mogê ci pomóc?}
{101}{}{Tak. Pomó¿ mi.}
{102}{}{Kim wy jesteœcie?}
{103}{}{Co siê sta³o z ludŸmi, którzy zajmowali ten lokal przed wami?}
{104}{}{Uhym}
{105}{}{Dobrze, moje dziecko. Zaraz ciê zbadamy.}
{106}{}{B³ogos³awieni s¹ maluczcy na umyœle. Nic ci nie jest, moje dziecko. Biegnij siê pobawiæ.}
{107}{}{Uleczyliœmy ciê. W przysz³oœci zachowaj wiêksz¹ ostro¿noœæ.}
{108}{}{Masz rany.}
{109}{}{Widzê, ¿e cierpisz od jadu.}
{110}{}{Hmm, nieco napromieniowania. Niestety, nie mo¿emy tego wyleczyæ.}
{111}{}{Wymagamy ofiary w wysokoœci }
{112}{}{ kapsli przed kuracj¹. Czy to dla ciebie do przyjêcia?}
{113}{}{Tak.}
{114}{}{Nie.}
{115}{}{Ale¿ ja nie mam takich pieniêdzy!}
{116}{}{A wystarczy }
{117}{}{ kapsli?}
{118}{}{Dzieci siê nie targuj¹. Czy zatem akceptujesz nasz¹ cenê?}
{119}{}{Tak, oczywiœcie, ¿e tak.}
{120}{}{Mo¿ecie mnie poca³owaæ w dupê!}
{121}{}{Dziêkujê ci, mój synu. Pomódlmy siê za twoje ozdrowienie.}
{122}{}{Dziêkujê ci, moja córko. Pomódlmy siê za twoje ozdrowienie.}
{123}{}{Proszê bardzo. Niech towarzysz¹ ci Pokój i b³ogos³awieñstwo Dzieci.}
{124}{}{Nie masz tyle pieniêdzy. Ale jeœli ofiarujesz ca³¹ sumê, któr¹ posiadasz, uleczymy ciê. Czy to do przyjêcia?}
{125}{}{Tak.}
{126}{}{Nie.}
{127}{}{Jeœli ofiarujesz wszystkie pieni¹dze, które posiadasz, uleczymy ciê. Czy to dla ciebie do przyjêcia?}
{128}{}{Tak.}
{129}{}{Nie.}
{130}{}{Masz wiêcej ni¿ potrzeba do z³o¿enia ofiary. Wymagasz podszkolenia w matmie, moje dziecko.}
{131}{}{Jesteœmy Dzieæmi Katedry. ¯yjemy i pracujemy wœród nieszczêœników mieszkaj¹cych na Pustkowiu. Jeœli kiedykolwiek znajdziesz siê w Gruzach, odwiedŸ Katedrê.}
{132}{}{Dziêkujê.}
{133}{}{Czym siê zajmujecie?}
{134}{}{Jesteœmy uzdrowicielami i nauczycielami Pokoju. Leczymy cia³o, by uleczyæ ducha. Wszystko, o co prosimy, to niewielki datek na op³acenie naszych materia³ów leczniczych.}
{135}{}{Wygl¹da mi to na szczytn¹ ideê.}
{136}{}{Wygl¹da mi to na stek bzdetów.}
{137}{}{Nie pytaliœmy ciê o zdanie. Widzê, ¿e nu¿y ciê s³uchanie o naszych przekonaniach. W razie potrzeby znajdziesz nas tutaj.}
{138}{}{To najœwiêtsza z idei. Pracujemy na rzecz zaprowadzenia ostatecznego Pokoju na Pustkowiu. Wszystkie stworzenia bêd¹ ¿yæ jako jedno.}
{139}{}{Dziêkujê. Do widzenia.}
{140}{}{Przekazali nam ten budynek, abyœmy mogli rozg³aszaæ nowinê i wype³niaæ nasz obowi¹zek jako uzdrowiciele.}
{141}{}{Czy doktor Kostucha nie denerwuje siê z tego powodu?}
{142}{}{To by³o strasznie mi³e z ich strony. Dziêki.}
{143}{}{Cokolwiek czuje ta pogañska dusza, nie jest trosk¹ Dzieci. Jesteœmy tu, by spe³niæ nasz obowi¹zek, i tak siê w³aœnie stanie.}
{144}{}{Ee, rety, dziêki. Czeœæ.}
{145}{}{Czemu to robisz? Nie uczynimy ci ¿adnej krzywdy!}
{146}{}{Twój stan nie wymaga leczenia.}
