{100}{}{Wygl¹da on na doœwiadczonego stró¿a prawa.}
{101}{}{Lepiej uwa¿aj tu na siebie.}
{102}{}{To nie jest dobre miejsce, ¿eby wpaœæ w k³opoty.}
{103}{}{Zachowuj siê, to nie bêdziemy musieli staæ siê nieprzyjemni.}
{104}{}{Jesteœ w porz¹dku.}
{105}{}{Wykonuj dalej dobr¹ robotê.}
{106}{}{Mi³y dzieñ, nieprawda¿?}
{107}{}{Oto Z³omowo. Mi³e miejsce do ¿ycia, póki nas nie wkurzasz.}
{108}{}{Uwa¿aj na Gizma i jego kompanów.}
{109}{}{Lubiê mojego szefa.}
{110}{}{Lepiej to schowaj. Z³omowo jest przyjaznym miejscem, i chcemy, ¿eby tak zosta³o.}
{111}{}{Co mam schowaæ?}
{112}{}{Nie mów mi, co robiæ, frajerzyno.}
{113}{}{Brzmi to przekonywaj¹co. Przy okazji, jakie jest miejscowe prawo odnoœnie broni?}
{114}{}{Uch, och.}
{115}{}{Twoj¹ broñ, matole. Killian ci jej nie odbierze, ale lepiej nie trzymaj jej na cholernym widoku.}
{116}{}{O, przepraszam.}
{117}{}{Mowy nie ma! Dla nikogo nie schowam moich strzelajek!}
{118}{}{Lepiej siê uspokój, bo takie jest prawo, a ja wymuszam jego przestrzeganie. Schowaj broñ. Nie wyci¹gaj jej, chyba ¿e w samoobronie, to nie bêdziesz mieæ problemów z nami, Stra¿nikami. Narusz prawo, to zwrócimy ciê dzikiemu pustkowiu - niekoniecznie ¿ywcem.}
{119}{}{Jasne, skoro tak to ujmujesz.}
{120}{}{Poca³uj w dupê twoje prawa!}
{121}{}{No, ee, w porz¹dku. Ale lepiej zachowaj ostro¿noœæ.}
{122}{}{Dobrze, ¿e pytasz. Nie wolno siêgaæ po ¿adn¹ broñ poza sytuacj¹ obrony w³asnej. Kto zaczyna walkê, jest winny. Poza tym ka¿dy ma prawo chodziæ uzbrojony. Po prostu nie wyjmuj no¿a albo armaty bez s³usznego powodu. ¯yczê ci dobrego dnia.}
{123}{}{Ej, ty, schowaj broñ! I nie obchodzi mnie, czy twoja mamusia upuœci³a ciê na g³owê jako dziecko. Schowaj broñ.}
{124}{}{Ej! Ty! Co tu robisz, skradaj¹c siê?}
{125}{}{Nic.}
{126}{}{Nie skradam siê. Po prostu lubiê ostro¿nie st¹paæ.}
{127}{}{Uuuch.}
{128}{}{Cokolwiek robisz, nie rób tego w tej osadzie.}
{129}{}{Stra¿nik wpatruje siê w ciebie przez chwilê. Dostrzegasz na jego twarzy wyraz olœnienia, i natychmiast wyci¹ga broñ.}
{130}{}{No, ee, OK. Jak chcesz. Tylko nie rób nic niew³aœciwego.}
{131}{}{Dziêki, czeœæ.}
{132}{}{Oczywiœcie. Rzucê rozs¹dek na wiatr, jaœnie panie.}
{133}{}{Oczywiœcie. Rzucê rozs¹dek na wiatr, jaœnie pani.}
{134}{}{Schowaj broñ, albo poniesiesz tego konsekwencje!}
{135}{}{OK, starczy ostrze¿eñ. Natychmiast opuœæ tê osadê i nigdy nie wracaj, albo poniesiesz tego konsekwencje!}
{136}{}{Hej! Co ty wyrabiasz?}
{137}{}{Wystarczy, przebra³a siê miarka.}
{138}{}{Teraz to masz k³opoty...}
{139}{}{Czachy, jesteœcie aresztowani!}
