{100}{}{To pies. Wydaje siê on pod¹¿aæ za tob¹.}
{101}{}{To pies.}
{102}{}{Hau!}
{103}{}{Grrr!}
{104}{}{Zyskujesz 100 punktów doœwiadczenia za udzielenie Philowi pomocy w rozwi¹zaniu jego psiego problemu.}
{105}{}{Wygl¹da na to, ¿e ten pies zapa³a³ do ciebie przyjaŸni¹.}
{106}{}{Ten pies zdaje siê myœleæ, ¿e jesteœ jego w³aœcicielem.}
