{100}{}{To Keri.}
{101}{}{Kim ty, do diab³a, jesteœ? Jak szukasz roboty, to musisz pogadaæ z Demetrem.}
{102}{}{Powiedzia³am, ¿e jak szukasz pracy, to rozmawiaj z moim tatkiem, nie ze mn¹.}
{103}{}{Wiêc ten stary skurwiel da³ ci zgodê, ¿ebyœ dla nas pracowa³a, co? No to musi byæ z ciebie naprawdê twarda suka. Jestem pod wra¿eniem, ale zobaczymy, jak sobie bêdziesz radzi³a. Wyruszamy tylko dwa razy w miesi¹cu, trzeciego i siedemnastego. Pasuje ci to? Chodzimy do wszystkich miejscowych gor¹cych punktów: Cytadeli Bractwa Stali, Z³omowa, Nekropolis i Gruzów.}
{104}{}{Wiêc ten stary skurwiel da³ ci zgodê, ¿ebyœ dla nas pracowa³, co? No to jaja musisz mieæ pewno ze stali. Jestem pod wra¿eniem, ale zobaczymy, jak sobie bêdziesz radzi³. Wyruszamy tylko dwa razy w miesi¹cu, trzeciego i siedemnastego. Pasuje ci to? Chodzimy do wszystkich miejscowych gor¹cych punktów: Cytadeli Bractwa Stali, Z³omowa, Nekropolis i Gruzów.}
{105}{}{A zap³ata?}
{106}{}{Ee.}
{107}{}{Nasze stawki s¹ najlepsze, 600 kapsli, i tak, to za ka¿d¹ stronê... Ale nie musisz robiæ obu. To ca³kiem ciê¿kie trasy karawanowe, i ma siê niemal gwarancjê, ¿e wpadnie siê na jakichœ najeŸdŸców... albo gorzej. Na moich karawanach nie chcemy ¿adnych maminsynków, i lepiej weŸ ze sob¹ mnóstwo amunicji.}
{108}{}{ Wyruszamy dzisiaj. Reflektujesz na to?}
{109}{}{ Wyruszamy }
{110}{}{Pusto}
{111}{}{Pusto}
{112}{}{. Reflektujesz na to?}
{113}{}{Wszyscy wyruszamy dzisiaj.}
{114}{}{Wyruszamy }
{115}{}{}
{116}{}{}
{117}{}{ Reflektujesz na to?}
{118}{}{Nadal dam twojej ¿a³osnej dupie robotê, jeœli na ni¹ reflektujesz.}
{119}{}{Jasne.}
{120}{}{Nie.}
{121}{}{Chyba reflektujê na ciebie.}
{122}{}{Mo¿e.}
{123}{}{Ug.}
{124}{}{Ha, wiedzia³am, ¿e stchórzysz! Có¿... Jeœli zodwa¿niejesz, wpadnij tu, a mo¿e jednak dam ci robotê. Wyruszamy trzeciego i siedemnastego, mo¿esz siê tu po prostu zjawiæ tego dnia, jak bêdziesz mieæ ochotê. Wiêcej spluw zawsze siê nam przyda.}
{125}{}{Ty wprost kochasz marnowaæ mój czas, prawda?}
{126}{}{Jak tam sobie chcesz. Jeœli najdzie ciê ¿¹dza akcji, wróæ tu, to podczepiê ciê do najbli¿szej wychodz¹cej karawany.}
{127}{}{Hej! Wiem, ¿e mo¿na tu dostaæ parê niez³ych narkotyków, ale nie wolno mi ciê wynaj¹æ, póki nie wytrzeŸwiejesz.}
{128}{}{Facet, kaza³am ci odstawiæ dragi!}
{129}{}{Kaza³am ci odstawiæ dragi, suko!}
{130}{}{No có¿... G³upio mi to mówiæ, ale... s³ysza³am o tobie. Czy prywatnie jesteœ równie twardy jak publicznie? SprawdŸmy.. [Keri prowadzi ciê za róg.]}
{131}{}{[W drodze powrotnej Keri wsuwa ci do kieszeni kilka przedmiotów.]}
{132}{}{Có¿, mo¿esz wytrzymaæ BARDZO d³ugo.}
{133}{}{No có¿, "jesteœ" interesuj¹cy i "bardzo" odmienny od wiêkszoœci facetów... Poka¿ mi, co masz, twardzielu. [Keri prowadzi ciê za róg.]}
{134}{}{[W drodze powrotnej Keri wsuwa ci do kieszeni kilka przedmiotów.]}
{135}{}{Có¿, mo¿esz wytrzymaæ BARDZO d³ugo.}
{136}{}{Hej, Tatku, wygl¹da na to, ¿e mamy tutaj z³odzieja! Co masz do powiedzenia, ty szumowino?}
{137}{}{Przepraszam. Nigdy wiêcej tego nie zrobiê.}
{138}{}{Z³ap mnie, jeœli potrafisz...}
{139}{}{Nie lubiê spokoju! ChodŸ mnie dorwaæ!}
{140}{}{[Kiwasz g³ow¹ na "tak".]}
{141}{}{UUUGABUUUGA!!!}
{142}{}{Hej, Tatku, to durne gówno za pierwszym razem nie wziê³o sobie do serca nauczki. Znowu próbowa³a mnie okraœæ. Przypi¹chujmy jej.}
{143}{}{Hej, Tatku, to durne gówno za pierwszym razem nie wziê³o sobie do serca nauczki. Znowu próbowa³ mnie okraœæ. Przypi¹chujmy mu.}
{144}{}{Có¿... Wiem, jak ³atwo jest ulec pokusie kradzie¿y, ale... A niech to diabli wezm¹, dam ci szansê. Nie pokazuj tu wiêcej twojej mordy, to nie zawo³am glin. Teraz spadaj.}
{145}{}{Ach, dopilnujemy tego, prawda, Tatku?}
{146}{}{IdŸ do diab³a!}
{147}{}{Tak mi siê wydaje.}
{148}{}{Jesteœ ju¿ œcierwem.}
{149}{}{Kaza³am ci wychrzaniaæ!}
{150}{}{Policja!}
{151}{}{Wybacz, ale nie bêdziemy siê ju¿ wiêcej z tob¹ zadawaæ.}
{152}{}{Nie ma tu pracy, spadaj.}
{153}{}{Nie w³aŸ mi na odcisk, bo po¿a³ujesz.}
{154}{}{Matole.}
{155}{}{To intryguj¹ce, ale nie jesteœ w moim typie.}
{156}{}{Dobrze. Jak wczeœniej powiedzia³am, p³acimy 600 kapsli. Któr¹ chcesz trasê?}
{157}{}{Zajebiœcie. Nastêpna karawana wychodzi }
{158}{}{. PrzyjdŸ tu wtedy, to ciê w niej umieszczê. Jak zawsze, stawka to 600 kapsli.}
{159}{}{OK. }
{160}{}{Niestety, nie mogê tak d³ugo czekaæ.}
{161}{}{Powinnam ciê powiesiæ za powieki! Przez ciebie straciliœmy ca³¹, cholern¹ karawanê! Precz mi, do diab³a, z oczu! Bêdê mia³a za to powa¿nie przesrane.}
{162}{}{Powinnam ciê powiesiæ za jajca! Przez ciebie straciliœmy ca³¹, cholern¹ karawanê! Precz mi, do diab³a, z oczu! Bêdê mia³a za to powa¿nie przesrane.}
{163}{}{Do Cytadeli Bractwa Stali.}
{164}{}{Do Z³omowa.}
{165}{}{Do Nekropolis.}
{166}{}{Do Gruzów.}
{167}{}{Niewa¿ne. Mam coœ jeszcze do zrobienia. }
{168}{}{Gotowi, start! Zmiatamy z tej speluny!}
{169}{}{Daj mi znaæ, jak zdarzy siê cokolwiek zajebistego; Tata ka¿e mi siedzieæ w magazynie.}
{170}{}{Wspaniale! Reszta psychopatów jest gotowa. Wyruszymy od razu.}
{171}{}{Zajebiœcie, zebranie psycholi do kupy zajmie tylko parê minut.}
{172}{}{Bractwo Stali, przybywamy! No... Ja z wami nie idê, ale wiesz, o co mi chodzi.}
{173}{}{OK, zejdŸ mi ju¿ z widoku. Czekaj¹ na ciebie ci fanatycy z Bractwa.}
{174}{}{Mam nadziejê, ¿e lubisz góry! Idziesz prosto na nie. Pewnie czeka ciê tam mnóstwo akcji.}
{175}{}{Wszystko gotowe do drogi, a skierujecie siê prosto przez góry! To dopiero powinna byæ zadyma!}
{176}{}{Z³omowo jest ca³kiem nudne. Wolê bardziej niebezpieczne trasy.}
{177}{}{Podobno jest tam jakiœ szurniêty lekarz, lepiej zajrzyj do niego. Nazywa siê doktor Kostucha.}
{178}{}{Z³omowo to krótka wycieczka, powinniœcie nied³ugo byæ z powrotem.}
{179}{}{Uwa¿aj na twój ty³ek, Nekropolis nie jest zbyt przyjaznym miejscem.}
{180}{}{Przywódc¹ tego miasteczka jest Set. Przynajmniej by³ nim, kiedy ostatni raz tam by³am.}
{181}{}{Ta osada jest pe³na ³achów! Có¿, lepiej wyprawiê ciê w drogê.}
{182}{}{LA jest ca³kiem zajebiste. Spodoba ci siê, tylko nie opuszczaj karawany, zanim nie dotrze na miejsce. To niezbyt bezpieczne, dla karawan znaczy siê.}
{183}{}{Mam nadziejê, ¿e bêdziesz mieæ szansê je obejrzeæ, jest te¿ zajebisty koœció³ tylko parê mil na po³udnie stamt¹d. Ludzie w nim s¹ jednak walniêci.}
{184}{}{Mówiono mi, ¿e Gruzy by³y wczeœniej miejscem zwanym LA. Nie wiem, co znacz¹ inicja³y tego goœcia, ale to zajebiste miejsce.}
{185}{}{Czego, u diab³a, chcesz?}
{186}{}{Zamknij siê i zejdŸ mi z drogi, nie mam teraz nastroju!}
{187}{}{Chcê kolejn¹ robotê.}
{188}{}{Niczego.}
{189}{}{Zug.}
{190}{}{Ug.}
{191}{}{Ta, akurat! ¯eby daæ ci okazjê do porzucenia kolejnej karawany? Masz szczêœcie, ¿e tamci dotarli na miejsce w jednym kawa³ku.}
{192}{}{Ja mam szczêœcie? Ty masz szczêœcie, ¿e nie kasujê ci buŸki!}
{193}{}{Hej! Akurat trzeba by³o odwiedziæ parê miejsc i... takie tam!}
{194}{}{Hej! Nie mówi³aœ, ¿e nie mogê odejœæ! Nie jest tak, ¿e oni byli w œrodku walki.}
{195}{}{Wynoœ siê st¹d! Rzygaæ mi siê chce na twój widok! To dlatego nie uda³o ci siê wytrzymaæ do koñca trasy? Za³o¿ê siê, ¿e zdarzy³o ci siê byæ wtedy na haju!}
{196}{}{Ta? No to czemu siê tam teraz nie udasz! Z naszej listy wypadasz na dobre.}
{197}{}{Co? Pierwszy raz pracujesz przy karawanie? Nie mogê uwierzyæ, ¿e mój Tata w ogóle ciê wynaj¹³! Sp³ywaj! Zatrudniamy tylko personel z doœwiadczeniem! To dlatego p³acimy wielk¹ kasê!}
{198}{}{Ta ostatnia robota bardzo dobrze ci posz³a. Szukasz kolejnej?}
{199}{}{Pewnie.}
{200}{}{Nie.}
{201}{}{Mo¿e.}
{202}{}{Ug.}
{203}{}{Lug.}
{204}{}{Wszystko gotowe do drogi? Dzisiaj wyruszamy.}
{205}{}{Ta!}
{206}{}{Nie.}
{207}{}{Hrurra?}
{208}{}{Jesteœ tu o dzieñ za wczeœnie. Wróæ jutro, jeœli nadal chcesz tê robotê. Jeœli nie, nie pokazuj siê. Mam to w dupie.}
{209}{}{Hej, jesteœ tu za wczeœnie. Karawany wysy³am dopiero }
{210}{}{trzeciego}
{211}{}{siedemnastego}
{212}{}{. Wróæ wtedy, jeœli nadal bêdziesz chcieæ tê cholern¹ robotê. Naprawdê mnie nie obchodzi, czy siê zjawisz, czy nie. Ale je¿eli rzeczywiœcie nadal j¹ chcesz, to przyjdŸ wtedy.}
{213}{}{Jeszcze nie.}
{214}{}{Tato, zamknij siê, do jasnej cholery!}
{215}{}{Hej, Staruszku, jestem g³odna! Zrobiê sobie przerwê!}
{216}{}{Nienawidzê ksiêgowania.}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{}
{221}{}{}
{222}{}{}
{223}{}{}
{224}{}{}
{225}{}{}
{226}{}{}
{227}{}{}
{228}{}{}
{229}{}{Otrzymujesz trzy pakiety narkotyków.}
