{100}{}{To sejf.}
{101}{}{Zamek sejfu nie jest zamkniêty.}
{103}{}{Uda³o siê!}
{104}{}{A niech to dunder œwiœnie! Prawie siê uda³o.}
{105}{}{Zamek sejfu jest zamkniêty.}
{106}{}{Zyskujesz 500 punktów doœwiadczenia za otwarcie osobistego sejfu Killiana.}
{107}{}{Za pomoc¹ wytrycha wyginasz zapadki, dziêki czemu udaje ci siê zaklinowaæ zamek. Po prostu wspaniale.}
