{100}{}{To silnie umiêœniony, poznaczony bliznami mê¿czyzna z w¹sami.}
{101}{}{To Lars, sier¿ant Stra¿ników Z³omowa.}
{102}{}{Nosi blizny po dawnych ranach, i wygl¹da na starego wygê.}
{103}{}{Ma blizny po ranach zadanych broni¹ bia³¹ i paln¹. Sznury jego miêœni œwiadcz¹, ¿e jest to cz³owiek zahartowany przeciwnoœciami.}
{104}{}{Wiesz, nie jest m¹drze próbowaæ okradaæ stra¿ników tu, w Z³omowie, œmieciu!}
{105}{}{Mogê ci pomóc?}
{106}{}{No, to co jest tutaj do roboty?}
{107}{}{Czy móg³byœ mi przedstawiæ ogólny obraz Z³omowa?}
{108}{}{Kim jesteœ?}
{109}{}{Eergh.}
{110}{}{Je¿eli jesteœ tutaj szefem stra¿ników, to chyba mam dla ciebie trochê informacji.}
{111}{}{Ej! Ty! Wiemy o tobie, ty potworze!}
{112}{}{Mnóstwo, dopóki nas nie wkurzysz. Mamy tu sklep Killiana Darkwatera, gdzie mo¿esz trochê pohandlowaæ. I jest Kasyno Gizma, je¿eli poci¹ga ciê hazard. A jeœli chcesz siê po prostu napiæ, mo¿esz skierowaæ swe kroki do Nory Szumowin. Tylko zanadto nie rozrabiaj.}
{113}{}{Hej, ja lubiê porozrabiaæ!}
{114}{}{Có¿, najlepiej zrobisz, jak bêdziesz nad sob¹ panowaæ. Jesteœmy liberaln¹ osad¹, ale nie tolerujemy wchodzenia innym na odciski. Nie powoduj ¿adnych k³opotów, to nie dasz mi i moim ludziom powodu, ¿eby ci sprawiæ manto.}
{115}{}{Co za ciemnogród!}
{116}{}{S³uchaj, kole¿ko, moj¹ prac¹ tutaj jest utrzymywanie spokoju, a jeœli bêdê musia³ rozbiæ parê ³bów, ¿eby j¹ wykonywaæ, to paru ludzi bêdzie bola³o. Wiêc uwa¿aj.}
{117}{}{Ja i moi ludzie pracujemy dla Killiana Darkwatera. Utrzymujemy pewien porz¹dek w tym miasteczku, zajmuj¹c siê wszystkimi mordercami, z³odziejami i innymi mêtami, którzy przychodz¹ z pustyni. Jeœli chcesz mojej rady, to bêdziesz siê tak¿e trzymaæ z daleka od Gizma. Ten ba³wan prowadzi nieuczciw¹ dzia³alnoœæ, tylko nie jesteœmy w stanie niczego udowodniæ. On i jego s³ugusy, Czachy, dostan¹ nied³ugo po dupach, je¿eli Killian bêdzie mia³ w tej sprawie coœ do powiedzenia.}
{118}{}{Co za syf. Nie ma tu w ogóle rozrywek.}
{119}{}{Dobrze wiedzieæ, ¿e ktoœ w tej okolicy utrzymuje spokój. Dziêki.}
{120}{}{Wiêc co was, gliniarzy, powstrzymuje przed zwyczajnym zwiniêciem Gizma i Czach?}
{121}{}{Hej, to nasza praca. Ale mi³o jest wiedzieæ, ¿e ktoœ j¹ docenia. Dziêkujê.}
{122}{}{Musimy to wszystko zrobiæ w³aœciwie. Wiemy, ¿e Gizmo prowadzi ustawione gry, ale potrzebujemy namacalnych dowodów, ¿eby go przyskrzyniæ. To samo z Czachami; zlej¹ kogoœ, zwijamy jednego czy dwóch z nich, ale nic siê nie zmienia. Zwyczajnie nie mamy ¿adnych dowodów, wi¹¿¹cych ich bezpoœrednio z którymiœ zabójstwami lub rozbojami.}
{123}{}{Mo¿e ja bêdê w stanie wam w tym pomóc.}
{124}{}{Có¿, powodzenia.}
{125}{}{Do diab³a, jeœli uwa¿asz, ¿e uda ci siê zdobyæ jakieœ brudy na kogoœ z nich, to bylibyœmy wdziêczni za pomoc. O Gizmie rozmawiaj z Killianem. Ale jeœli zdo³asz zdobyæ jakieœ informacje o Czachach, wróæ tylko do mnie, a ju¿ ja i moi ch³opcy siê nimi zajmiemy.}
{126}{}{Dziêki. Uwa¿aj na siebie.}
{127}{}{Jestem szefem stra¿ników tu, w Z³omowie. Nazywam siê Lars. Jak ju¿ przy tym jesteœmy, to kim ty jesteœ?}
{128}{}{Jestem }
{129}{}{.}
{130}{}{Odchrzañ siê, nic ci nie muszê mówiæ.}
{131}{}{Witaj w Z³omowie, }
{132}{}{. W czym mogê ci pomóc?}
{133}{}{Czy móg³byœ uzupe³niæ moj¹ wiedzê o Z³omowie?}
{134}{}{Szukam tylko czegoœ do roboty. Masz jakieœ sugestie?}
{135}{}{Dzieñ dobry. Czy czegoœ potrzebujesz?}
{136}{}{Co?}
{137}{}{Szukam jakiejœ robótki.}
{138}{}{Tylko przystajê, ¿eby siê przywitaæ.}
{139}{}{Mam zeznanie o nielegalnych dzia³aniach, w które zaanga¿owane by³y Czachy.}
{140}{}{Tak, jestem tutaj dowódc¹ stra¿ników. Co masz dla mnie?}
{141}{}{Nic, tylko sprawdzam.}
{142}{}{Mam zeznanie Sherry, ¿e Czachy s¹ zaanga¿owane w pewne nielegalne dzia³ania.}
{143}{}{No, to masz trochê informacji o Czachach, tak? Co mo¿esz mi powiedzieæ?}
{144}{}{S¹ tutaj zaanga¿owani w rozboje i zabójstwa.}
{145}{}{Uda³o mi siê przekonaæ jedn¹ z nich, Sherry, by zezna³a, ¿e byli zaanga¿owani w dzia³alnoœæ kryminaln¹.}
{146}{}{To wspaniale i w ogóle, ale nie mogê po prostu uwiêziæ ich wszystkich na podstawie gadania jednej osoby. Potrzebujê namacalnych dowodów lub zeznania cz³onka gangu.}
{147}{}{Zobaczê, co mogê zrobiæ w tej sprawie.}
{148}{}{Mam zeznanie Sherry, by³ej cz³onkini Czach.}
{149}{}{Doskonale. Wezmê j¹ na ma³e przes³uchanie, i jestem pewien, ¿e zdobêdê wszystkie informacje, których potrzebujê, aby ich zapud³owaæ.}
{150}{}{S³uchaj, to nie jest gra. Ludzie tutaj obrywaj¹. Jak znajdziesz jakieœ prawdziwe dowody, przyjdŸ do mnie, ale poza tym przypadkiem nie marnuj mojego czasu!}
{151}{}{Je¿eli nie masz oporów, ¿eby odrobinê popracowaæ czerepem, to chcia³bym, aby ktoœ zdoby³ jakieœ namacalne dowody przeciw Czachom, wskazuj¹ce, ¿e s¹ tutaj zaanga¿owani w nielegaln¹ dzia³alnoœæ. Albo mo¿esz porozmawiaæ z Killianem; on mo¿e mieæ dla ciebie trochê pracy.}
{152}{}{Dziêkujê ci za pomoc. Z³omowo jest teraz nieco bezpieczniejsze, za spraw¹ twoich dzia³añ.}
{153}{}{Ruszaj st¹d, kole¿ko.}
{154}{}{Zyskujesz 300 punktów doœwiadczenia za przeprowadzenie ryzykownej operacji przeciw Czachom.}
{155}{}{Czujesz siê na si³ach, ¿eby pomóc za³atwiæ Gizma?}
{156}{}{A jak¿e. Upolujmy tego kaszalota.}
{157}{}{Nie, odwidzia³o mi siê.}
{158}{}{W porz¹dku, bierzmy siê za to.}
{159}{}{Có¿, najlepiej zaczekaj tutaj, ¿eby nie wpaœæ pod ogieñ krzy¿owy.}
{160}{}{Killian przysy³a mnie do pomocy przy wygonieniu Gizma z osady.}
{161}{}{Przysy³a mnie Killian. Za³atwimy Gizma.}
{162}{}{Dziêki za ca³¹ twoj¹ pomoc. Oto 500 kapsli. W Z³omowie zawsze bêdziesz mile widzianym goœciem.}
{163}{}{Co? Hmm. Przyjrzymy siê temu. Poœlê paru ludzi, ¿eby ich z³apali w zasadzkê, kiedy spróbuj¹ to zrobiæ. Bêdziesz tam?}
{164}{}{Nie, dziêki, mam ju¿ wyczerpany dzisiejszy limit dobrych uczynków.}
{165}{}{Tak.}
{166}{}{Czachy planuj¹ zabiæ Neala!}
{167}{}{Ludzie Larsa szybko eliminuj¹ Czachy.}
{168}{}{Wygl¹da na to, ¿e Lars mo¿e jeszcze ¿yæ, ale z ca³¹ pewnoœci¹ jest wy³¹czony z walki.}
{169}{}{W³aœnie uda³o ci siê spieprzyæ sprawê. Potrzebowaliœmy dowodów, ¿eby móc za³atwiæ Gizma czyœciutko i zgodnie z prawem. S³uchaj, poza protoko³em, jestem szczêœliwy, ¿e nie muszê siê ju¿ przejmowaæ tym t³ustym jobem, ale nie mo¿emy przymkn¹æ oka na morderstwo. Lepiej opuœæ Z³omowo i nigdy nie wracaj.}
{170}{}{Nie lubimy tu takich jak ty. Masz oko³o piêtnastu sekund, zanim rozwalê ci ³eb.}
{171}{}{Witaj ponownie! Co mogê dla ciebie zrobiæ?}
{172}{}{Uh-hum.}
{173}{}{Nuh-um.}
{174}{}{Zyskujesz 500 punktów doœwiadczenia za pomoc w wyeliminowaniu gangu Czach.}

{1000}{}{Gizmo}
{1100}{}{Prowadzi Kasyno. Jest kanali¹.}