{100}{}{To rycerz.}
{101}{}{Witaj, kadecie. Jestem Larry, jak mogê ci pomóc?}
{102}{}{Vree mówi³a, ¿e mo¿esz mi pokazaæ pistolet laserowy.}
{103}{}{Vree mówi³a, ¿e mo¿esz mi daæ pistolet laserowy.}
{104}{}{Ug.}
{105}{}{Eee, OK...}
{106}{}{Eee, ta. Te zabawki s¹ œwietne. Ich zasiêg jest... có¿, jak okiem siêgn¹æ. [Pogadanka Larry'ego wydaje siê trwaæ ca³ymi godzinami, ale udaje ci siê nauczyæ paru rzeczy z zakresu u¿ytkowania broni energetycznych.]}
{107}{}{Hê? Przecie¿ wie, ¿e one nie s¹ jeszcze gotowe... Ach, na pewno chodzi³o jej o to, ¿ebym ci go pokaza³. Ta, mogê ci zrobiæ demonstracjê. Widzisz, on chodzi na ogniwach energetycznych, które s¹ zbudowane z... [Pogadanka Larry'ego wydaje siê trwaæ ca³ymi godzinami, ale udaje ci siê nauczyæ paru rzeczy z zakresu u¿ytkowania broni energetycznych.]}
{108}{}{Akurat. Myœlê, ¿e lepiej bêdzie, jak sobie pójdziesz.}
{109}{}{Nie lubiê k³amców, proszê odejœæ.}
{200}{}{To w ogóle jest nie tak.}
{201}{}{Proszê bardzo.}
{202}{}{Mechanizm spustowy ci¹gle siê zacina.}
{203}{}{O wiele lepiej.}
{204}{}{Prawie siê uda³o.}
{205}{}{To trochê potrwa.}
{206}{}{Tu le¿y pies pogrzebany!}
{207}{}{John, chyba wyizolowa³em problem.}
{208}{}{Cholera!}
{209}{}{Niech to dunder œwiœnie!}
{210}{}{Przepraszam, moja wina!}
{211}{}{Nic mi nie jest.}
{212}{}{OK, to bola³o.}
{213}{}{To by³o celowo.}
{214}{}{Czemu to siê ci¹gle dzieje?}
{215}{}{Moje oczy!}
{216}{}{Nie jesteœ rycerzem.}
{217}{}{Muszê porozmawiaæ z rycerzem.}
{218}{}{Nie rozumiem, ogniwa energetyczne ci¹gle siê wyczerpuj¹.}
{219}{}{Lepiej siê cofnij, to mo¿e byæ niebezpieczne.}
{220}{}{Proszê mnie nie rozpraszaæ.}
{221}{}{Uwa¿aj, gdzie stoisz.}
{222}{}{Nie mo¿esz znaleŸæ drogi?}
{223}{}{Wybacz, nie mogê teraz rozmawiaæ.}
{300}{}{Twoja znajomoœæ broni energetycznych wzrasta o 5 punktów.}
