{100}{}{To Biczownik Dzieci.}
{101}{}{Wiem, kim jesteœ. Jesteœ nikczemnym, z³ym cz³owiekiem, i musisz zostaæ ukarany.}
{102}{}{Wiem, kim jesteœ. Jesteœ diab³em pod postaci¹ niewiasty, lecz twój kszta³t ciê nie ocali.}
{103}{}{Wiem, kim jesteœ. Wyprzedzaj¹ ciê wieœci o twej nikczemnoœci. Wysy³asz dusze dzieci do Hadesu, nim mog¹ zostaæ oczyszczone z ich wiaro³omstwa. To, co czynisz, to najczarniejsze z³o, i musi ciê za nie spotkaæ kara.}
{104}{}{Wiem, kim jesteœ. Jesteœ wcielon¹ œmierci¹, plag¹ w ludzkiej postaci. Gdzie postanie twoja stopa, krew p³ynie jak rzeka. Lecz takim niegodziwoœciom mo¿e po³o¿yæ kres prawa dusza!}
{105}{}{Jak œmiesz mi przeszkadzaæ! Nie wiesz, jak wa¿ne jest moje stanowisko? IdŸ precz!}
{106}{}{Niem¹drze jest podnosiæ na mnie broñ. Os³ania mnie tarcza Mistrza, i nie wolno mnie tkn¹æ, nie œci¹gaj¹c na siebie jego odwetu!}
{107}{}{Mi te¿ by siê przyda³a tarcza Mistrza.}
{108}{}{Nikt mnie nigdy nie pos¹dza³ o m¹droœæ!}
{109}{}{Chcê tylko pomówiæ z osob¹, która tu rz¹dzi.}
{110}{}{Masz tam niez³ego prêta! Czy to dlatego mówi¹ na ciebie "Biczownik"?}
{111}{}{Czy to prawda, ¿e sprawia ci przyjemnoœæ molestowanie dzieci?}
{112}{}{Chcesz wiedzieæ, co jest niem¹drze? Niem¹drze jest mi pyskowaæ, cwelu!}
{113}{}{Czego ty mówiæ tak œmieszna?}
{114}{}{Czemu tu przychodzisz? Wszyscy nowicjusze winni wiedzieæ, ¿e nie lubiê, gdy mi siê przeszkadza.}
{115}{}{Wybacz mi, Ojcze, lecz jestem w k³opocie.}
{116}{}{Pragnê przewodnictwa Katedry.}
{117}{}{Jestem tu, aby porozmawiaæ o tym, jak traktujesz dzieci.}
{118}{}{Chcê tylko porozmawiaæ.}
{119}{}{Masz tam niez³ego prêta! Czy to dlatego mówi¹ na ciebie "Biczownik"?}
{120}{}{Chcia³byœ, ¿eby nikt ci ju¿ nigdy nie przeszkadza³? Mogê siê tym zaj¹æ!}
{121}{}{Nie wim. Czego ja przysz³a? Ty wi?}
{122}{}{Jak œmiesz wkraczaæ do mojego sanktuarium z broni¹ w rêku! Ty ba³wanie! IdŸ precz!}
{123}{}{Za kogo ty siê uwa¿asz, ¿e wkraczasz do mojego sanktuarium z wyci¹gniêt¹ broni¹. IdŸ precz!}
{124}{}{Wybacz mi, panie, lecz si³y ciemnoœci s¹ wszêdzie, i nigdy nie wiadomo, kiedy siê trzeba bêdzie przed nimi broniæ.}
{125}{}{Pragnê przewodnictwa Katedry.}
{126}{}{Jestem tu, aby porozmawiaæ o tym, jak traktujesz dzieci.}
{127}{}{Chcê tylko porozmawiaæ.}
{128}{}{Masz tam niez³ego prêta! Czy to dlatego mówi¹ na ciebie "Biczownik"?}
{129}{}{Nie lubisz dobytej broni. Znienawidzisz to, co zrobiê teraz!}
{130}{}{IdŸ? Którêdy?}
{131}{}{Moja kwatera nie stoi otworem dla tych, którzy nie zostali konsekrowani. Muszê ciê prosiæ o natychmiastowe jej opuszczenie.}
{132}{}{Wybacz moje wtargniêcie, ale mam wa¿ne pytania.}
{133}{}{Jestem tu, aby porozmawiaæ o tym, jak traktujesz dzieci.}
{134}{}{Chcê ciê zapytaæ o konsekracjê.}
{135}{}{Masz tam niez³ego prêta! Czy to dlatego mówi¹ na ciebie "Biczownik"?}
{136}{}{To miejsce nie wygl¹da na konsekrowane. Jeszcze nikt tutaj nie zgin¹³ z mojej rêki.}
{137}{}{Ty g³upia! Ja mieæ masa koñ... se... krowa...}
{138}{}{To przywilej zarezerwowany jedynie dla najwierniejszych s³ug. Tylko chrzest jest wiêkszym zaszczytem.}
{139}{}{A jak mo¿na sobie zas³u¿yæ na chrzest?}
{140}{}{Domyœlam siê, ¿e uczysz dzieci i przygotowujesz je do chrztu.}
{141}{}{Czy mo¿esz mi pomóc siê ochrzciæ?}
{142}{}{Rety! Musisz byæ kimœ wyj¹tkowym!}
{143}{}{Szkoda, ¿e przywileje s¹ mniej warte od dupy radskorpiona, kiedy jest siê trupem.}
{144}{}{Nie widzê powodów, by wieœæ rozmowê z mato³kiem. Precz st¹d.}
{145}{}{Musisz porozmawiaæ w tej sprawie z ojcem Morfeuszem. Przebywa w wie¿y, ale to raczej wykluczone, by Mroczni ciê do niego dopuœcili.}
{146}{}{Czy móg³byœ przekonaæ Mrocznych, aby mnie przepuœcili?}
{147}{}{Co mo¿esz mi powiedzieæ o Morfeuszu?}
{148}{}{Co mo¿esz mi powiedzieæ o Mrocznych.}
{149}{}{Dziêkujê ci, panie.}
{150}{}{Mam sposoby na obchodzenie tego typu problemów.}
{151}{}{Ten prêt jest œwiêtym instrumentem, za pomoc¹ którego pouczam moich podopiecznych. Ból oczyszcza ich umys³y ze z³ych myœli i pozwala im lepiej poj¹æ chwa³ê Mistrza.}
{152}{}{Rozumiem. Wiêc Mistrz jest jak zadra?}
{153}{}{Jak mo¿esz robiæ coœ tak okropnego dzieciom?!}
{154}{}{Brzmi to rozkosznie wyuzdanie. Mo¿e byœ popróbowa³ trochê na mnie?}
{155}{}{Pouczam dzieci. To mój obowi¹zek. Wszystkie dzieci to nikczemne bestie. Moim obowi¹zkiem jest zmuszaæ je do rozwijania siê w istoty ludzkie. Byæ mo¿e dotar³o do twych uszu, ¿e nie tolerujê beztroski. To prawda. Chcê, by moi podopieczni cierpieli tak bardzo, jak to tylko mo¿liwe.}
{156}{}{A czy mutanci s¹ wy¿ej rozwiniêci ni¿ istoty ludzkie?}
{157}{}{Ty skurwielu bez serca!}
{158}{}{Ty siê nigdy nie bzyka³eœ, prawda?}
{159}{}{Opowiedz mi wiêcej o twoich metodach nauczania.}
{160}{}{Ale co z przyjemnoœci¹ wyp³ywaj¹c¹ z zabijania? Ona te¿ jest zabroniona?}
{161}{}{Ty plugawa, bezmózga szkarado! Jak œmiesz kalaæ mnie tw¹ obecnoœci¹! IdŸ precz! IdŸ! Natychmiast!}
{162}{}{Jesteœ kobiet¹, przeto zawsze jesteœ w k³opocie. To endemiczny stan twojej p³ci. Wyjaw mi twój problem, pani, a rozwi¹¿ê go dla ciebie.}
{163}{}{Gdyby twoje serce nie by³o tak pe³ne nikczemnoœci, panie, nic by ci nie zak³óca³o spokoju. Prawe serce nie zna trosk. Wyjaw mi twój problem, byle szybko!}
{164}{}{Wyjaw mi, jak osi¹gn¹æ prawoœæ!}
{165}{}{Pragnê wiedzieæ wiêcej o Katedrze.}
{166}{}{Pragnê wiedzieæ wiêcej o Mistrzu.}
{167}{}{¯yjesz. To mój problem, ty skurwysynu!}
{168}{}{Naucz siê kochaæ ból jak twojego najbli¿szego przyjaciela, gdy¿ ból jest najlepiej pouczaj¹c¹ si³¹ we Wszechœwiecie. Druzgocz siê, a¿ nie bêdziesz ju¿ w stanie istnieæ jako jednostka, wówczas przetwórz siê w narzêdzie Mistrza. To jest rozwi¹zanie dla wszystkich twoich problemów.}
{169}{}{Gdzie zatem znajdê najwiêcej bólu?}
{170}{}{Ta, chcê sobie wystarczaj¹co uszkodziæ mózg, ¿eby siê przy³¹czyæ do kultu zombi! Marz sobie dalej, koleœ!}
{171}{}{Nigdy by mi to nie przysz³o na myœl!}
{172}{}{Naprawdê? To jest do dupy, koleœ!}
{173}{}{Ja ju¿ kocham ból. Lubiê tylko dzieliæ siê nim z przyjació³mi.}
{174}{}{Zwierzêta paplaj¹ bez ³adu i sk³adu. Istoty ludzkie wpierw myœl¹, a potem mówi¹. Musisz siê rozwin¹æ w istotê ludzk¹, nim zapragnê z tob¹ rozmawiaæ. OdejdŸ.}
{175}{}{Twe s³owa s¹ prawdziwe. Dobrze, pomogê ci. Lecz spiesz siê.}
{176}{}{Muszê siê zobaczyæ z ojcem Morfeuszem w niezwykle pilnej sprawie.}
{177}{}{Opowiedz mi o Katedrze.}
{178}{}{Zastanawiam siê, gdzie mo¿na znaleŸæ Mistrza.}
{179}{}{Rozmyœlam nad Dzieæmi.}
{180}{}{Jedyne, co znam szybkiego, to œmieræ.}
{181}{}{Dla ka¿dego nadchodzi czas, gdy musi samodzielnie znaleŸæ odpowiedŸ na pytania, jakie stawia przed nim ¿ycie, a dla ciebie on w³aœnie nadszed³. OdejdŸ!}
{182}{}{To nie jest moim obowi¹zkiem. Teraz odejdŸ.}
{183}{}{Poprzez znoszenie bólu, poprzez nabywanie m¹droœci, i pe³nienie s³u¿by. Ból jest wiedz¹, m¹droœæ jest pos³uszeñstwem, zaœ s³u¿ba jest odwag¹. }
{184}{}{[Wiêcej]}
{185}{}{Musisz wyrzec siê Œwiat³a, które niemal unicestwi³o nas wszystkich, i zaprzysi¹c siê Ciemnoœci, w której wszyscy jesteœmy równi. Teraz, gdy ju¿ ci to powiedzia³em, zacznij do tego d¹¿yæ. Poszukuj Mistrza oraz Jego m¹droœci.}
{186}{}{Nie zwraca³em siê do Niego, ale mam absolutn¹ pewnoœæ, ¿e jest On zadowolony z prawych dusz, jakie Mu sprowadzam. To trudna praca, lecz wykonujê j¹ dobrze. Niestety, jest tak¿e nader czasoch³onna, co sprawia, ¿e muszê ci nakazaæ bezzw³ocznie odejœæ.}
{187}{}{Jêzyk pochlebcy mieszka w ustach diab³a! Diab³a takiego jak ty! Precz mi z oczu!}
{188}{}{Ty plugawogêbe zwierzê! OdejdŸ! Naucz siê nieco manier, zanim wrócisz.}
{189}{}{To rozs¹dna proœba. WeŸ ten symbol. Oka¿ go Mrocznym, gdy zapragniesz przejœæ.}
{190}{}{Nie mogê ci pomóc w tej sprawie. OdejdŸ.}
{191}{}{To nasz przywódca. Jest blisko Mistrza i zna wiele z Jego zamiarów. Czy to wszystko?}
{192}{}{Czy móg³byœ przekonaæ Mrocznych, aby mnie przepuœcili?}
{193}{}{Czy móg³byœ mi powiedzieæ wiêcej o Morfeuszu?}
{194}{}{Co mo¿esz mi powiedzieæ o Mrocznych?}
{195}{}{Dziêkujê ci, panie.}
{196}{}{No to czemu siê s³uchasz tego niedojdy, Morfeusza?}
{197}{}{S³u¿¹ Mistrzowi. Sprowadzaj¹ na ten œwiat lecz¹cy ból. To Anio³y Nocy, które odkupuj¹ œwiat poprzez rozlew krwi. Ciekawoœæ to ryzykanckie uczucie, lecz staje siê podwójnie takie w odniesieniu do Mrocznych. To moje jedyne ostrze¿enie dla ciebie. Mam teraz wiele do zrobienia. OdejdŸ.}
{198}{}{Twoja grzecznoœæ jest godna pochwa³y. Byæ mo¿e zas³ugujesz na rozmowê z Morfeuszem. Jeœli Mroczni ciê zatrzymaj¹, oka¿ im ten symbol. Teraz odejdŸ!}
{199}{}{Dajesz dowód g³upoty, jeœli uwa¿asz, ¿e drobnym fortelem pokonasz Mrocznych. IdŸ st¹d precz!}
{200}{}{Dekadencja i swoboda wstrzymuj¹ ewolucjê, ewolucjê konieczn¹ do przetrwania w surowym œwiecie. Na szczêœcie jestem twardym cz³owiekiem, który nie dba o zwodnicze przyjemnoœci. Widzê, ¿e siê ze mn¹ nie zgadzasz. Nie dbam o tw¹ opiniê. IdŸ st¹d precz!}
{201}{}{Mutacja nie jest czymœ, czego nale¿a³oby siê baæ. Ka¿de narodziny s¹ wynikiem mutacji DNA rodziców. Wszyscy jesteœmy mutantami. Jedyne, co siê liczy, to skierowanie mutanta na moraln¹ i produktywn¹ œcie¿kê. To moja praca. I tak¿e to koñczy tê dyskusjê. Zostaw mnie teraz samego.}
{202}{}{To ja rozdzielam ból. Jeœli zwierzê jest tego warte, i potrafi siê czegoœ z niego nauczyæ, rozwija siê w praw¹ duszê. Jeœli nie, to nie zas³uguje, by istnieæ. W rzadkich przypadkach zwierzêta s¹ usuwane z puli genetycznej, choæ nie na tyle czêsto, jak bym tego pragn¹³. Zdarza siê to powszechniej w odniesieniu do wyroœniêtych zwierz¹t.}
{203}{}{I Mistrz aprobuje te metody dydaktyczne?}
{204}{}{Jesteœ potworem!}
{205}{}{Chyba ciê ju¿ zostawiê samego.}
{206}{}{Czy nauczasz te¿ doros³ych?}
{207}{}{Wyroœniêtych zwierz¹t?}
{208}{}{Hej, mogê je dla ciebie usun¹æ! Nikt poza nami nie musi o tym wiedzieæ!}
{209}{}{Jesteœ z³¹ dziewk¹. Dobrze zrobisz, jak bêdziesz tutaj uwa¿aæ na ka¿dym kroku. Mroczni nie lubi¹ rywali. Teraz odejdŸ!}
{210}{}{Jesteœ z³ym cz³owiekiem. Dobrze zrobisz, jak bêdziesz tutaj uwa¿aæ na ka¿dym kroku. Mroczni nie lubi¹ rywali. Teraz odejdŸ!}
{211}{}{Prawoœæ osi¹ga siê poprzez zmaganie, traumê i ozdrowienie. Jesteœmy zwierzêtami, które musz¹ stale byæ druzgotane, dopóki nie przyjm¹ prawdy Mistrza bez wahania. Teraz, gdy ju¿ znasz prawdê, d¹¿ do niej ogó³em twoich doœwiadczeñ. IdŸ st¹d precz.}
{212}{}{Twój jêzyk jest tak nikczemny, ¿e nie mo¿na go odkupiæ w ¿aden sposób. Precz mi z oczu!}
{213}{}{Katedra naucza wielu rzeczy, których niezdyscyplinowany umys³ nie jest zdolny poj¹æ. Teraz mam inne obowi¹zki do wykonania. OdejdŸ!}
{214}{}{Tak samo jak ja. Wygl¹da na to, ¿e mamy ze sob¹ wiele wspólnego, lecz niestety irytujesz mnie nie do zniesienia. IdŸ st¹d precz. Natychmiast.}
{215}{}{Nie moj¹ rol¹ jest os¹dzaæ. Musisz przekonaæ Mrocznych. ¯yczê ci szczêœcia. Bêdzie ci potrzebne.}
{216}{}{Katedra stanowi sanktuarium rodzaju ludzkiego. Kiedy Apokalipsa spad³a na to plugawe miasto, Katedra zosta³a oszczêdzona, co umo¿liwi³o narodziny Mistrza. I tak lecz¹ca Ciemnoœæ wy³oni³a siê ze straszliwego Œwiat³a.}
{217}{}{ Gdy przyby³em, dostrzeg³em, ¿e brak tu koœæca moralnego, tak wiêc podj¹³em wysi³ek wymierzania dydaktycznego bólu w tym miejscu niegdyœ poch³oniêtym przez pró¿ne przyjemnoœci. To wszystko, co musisz wiedzieæ.}
{218}{}{Powiedziane jest, ¿e Mistrz czeka w dole, w Ciemnoœci, gdy¿ Œwiat³o w górze zdradzi³o ludzkoœæ i niemal nas unicestwi³o. Lecz wielu wielbi Œwiat³o, gdy¿ mówi¹, ¿e zrodzi³o Mistrza.}
{219}{}{ Nie dysponujê absolutn¹ pewnoœci¹ co do tych spraw, i nigdy nie mia³em zaszczytu Go spotkaæ. A teraz, jeœli wybaczysz, muszê siê zaj¹æ moj¹ prac¹.}
{220}{}{Od pocz¹tku nieszczególnie radowa³a mnie twoja tu obecnoœæ. Z twoim odejœciem kamieñ spadnie mi z serca.}
{221}{}{Niegdyœ to robi³em, lecz wiele z metod porzucono na korzyœæ tych g³oœnych ha³asów, które s³yszysz w Audytorium. Jest to dla mnie Ÿród³em goryczy. Szczêœliwie nadal mogê pouczaæ dzieci. A teraz, jeœli wybaczysz, muszê przygotowaæ siê do ich lekcji.}
{222}{}{Ee... To naturalnie zdarza siê rzadko, a tym zwierzêtom daje siê wszelkie szanse rozwoju. Teraz st¹d odejdŸ! OdejdŸ st¹d natychmiast!}
{223}{}{[Koniec]}
{224}{}{To mo¿e byæ dla ciebie u¿yteczne. WeŸ ten symbol. Pozwoli ci on spotkaæ siê z ojcem Morfeuszem. Oka¿ go Mrocznym, gdy zapragniesz siê do niego udaæ.}
