{100}{}{To mieszkanka Z³omowa.}
{101}{}{O, tak, wielki facet ucieka przed przera¿aj¹cym brytanem. Phil, ale mu pokaza³eœ. Ta, w samej rzeczy.}
{102}{}{Co ty robisz, Phil? Sprawdzasz bie¿nik na tych trampkach, zgadza siê?}
{103}{}{Rany, ten pies wygl¹da na g³odnego. Na pewno chce ciê po¿reæ ¿ywcem, Phil.}
{104}{}{To mo¿e byæ lekka przesada w stosunku do biednego, bezbronnego zwierzêcia, nie s¹dzisz?}
{105}{}{Masz tam naprawdê ³adnego psiaka.}
{106}{}{Phil na pewno by³by wdziêczny, gdyby uda³o ci siê pozbyæ tego psa.}
{107}{}{Dziêki za za³atwienie siê z tym psem.}
{108}{}{To Lenore.}