{100}{}{To Leone.}
{101}{}{Jak szukasz towarzystwa, wynajmij kurwê. Ja jestem zajêty.}
{102}{}{Nie, dopóki szef tak nie naka¿e. Zwyczajnie go zignoruj, to sobie pójdzie.}
{103}{}{Nie, dopóki szef tak nie naka¿e. Zwyczajnie j¹ zignoruj, to sobie pójdzie.}
{105}{}{Daj spokój. Ka¿dy mo¿e rozwaliæ kolano albo po³amaæ paluchy. To ju¿ po prostu nie szokuje ludzi tak jak dawniej.}