{100}{}{To ghul, kierownik motelu.}
{101}{}{Co tu robita?}
{102}{}{Szukam resztek przesz³oœci.}
{103}{}{Jestem odkrywc¹.}
{104}{}{Co ci do tego, robaczywa mordo?}
{105}{}{Dug-du.}
{106}{}{Co mówita?}
{107}{}{Nic.}
{108}{}{Poszukujê zaginionych technologii.}
{109}{}{Tak mi sie w³aœnie zda³o. Wynocha z mojego apartamenta.}
{110}{}{O, nic takiego tu ni ma. Mo¿e w œwiontyni, abo przy wodzie. Zbirajta sie.}
{111}{}{Ach! Tylko ni odkrywajta niczego z moich klamotów. Wynocha! Mówie syrio.}
{112}{}{Odczepta siê od mojij twarzy. Ja tu szefuje.}
{113}{}{O, doprawdy.}
{114}{}{Wyzmê tê twuj¹ facjatê i wypchnê ci j¹ g³êbuko w...}
{115}{}{Ach! OK, zgoda. Wychodzê.}
{116}{}{Ty nie olbrzym, co by mi tak rozkazywa³. WeŸ to i wsadŸ se w dupe!}
{117}{}{Ni chcy mi sie z tobom gadaæ.}
{118}{}{Czym jesteœ?}
{119}{}{Jestym ghul. Pirszy raz widzita ghula?}
{120}{}{Nie.}
{121}{}{Tak.}
{122}{}{Na pywno sputkaliœta jakomœ ciote z podziemia. Puœci³a was ¿ywcem, co byœta mnie niepokuili. Tyraz wynocha z mojego apartamenta.}
{123}{}{No to ju¿ zobaczyliœta. Wynocha stund!}