{100}{}{Dziêki, na razie.}
{101}{}{Dobrze, dziêkujê.}
{102}{}{Hmm. ¯egnaj.}
{103}{}{Na razie!}
{104}{}{Dziêki.}
{105}{}{Dobrze, ¿egnaj.}
{106}{}{[Wiêcej]}
{107}{}{Zzzzz}
{108}{}{[Zrobione]}
{109}{}{Nie mogê tego u¿ywaæ.}
