{100}{}{Na tej konsoli jest tabliczka z nazw¹: Komputer Steruj¹cy G³owic¹.}
{101}{}{Od komputera do g³owicy biegn¹ jakieœ przewody.}
{102}{}{G³owica zosta³a uzbrojona. Zegar zacz¹³ odmierzaæ czas od czterech minut.}
{103}{}{Uda³o ci siê rozbroiæ g³owicê nuklearn¹.}
{104}{}{BUUUUUUM! [Przez ciebie atomówka wybuch³a!]}
{105}{}{To chyba nie skutkuje.}
{106}{}{Odliczanie trwa... mo¿e trzeba przeci¹æ ten czerwony kabelek.}
{107}{}{Mo¿e trzeba skorzystaæ te¿ z klucza.}
{108}{}{Komputer jest wyposa¿ony w specjalne urz¹dzenie, które uniemo¿liwia uzbrojenie bomby bez odpowiedniego klucza.}
{109}{}{Nie da siê obejœæ tak doskonale zabezpieczonego zamka.}
{110}{}{Tego komputera nie mo¿na naprawiæ.}
{111}{}{Na tym komputerze nie mo¿na u¿yæ umiejêtnoœci Pu³apki.}
{112}{}{Brak ci umiejêtnoœci, ¿eby poradziæ sobie z mechanizmem bezpieczeñstwa.}
