{100}{}{Pompa wodna zosta³a naprawiona i dzia³a normalnie.}
{101}{}{System pomp nie dzia³a z powodu uszkodzenia pompy pró¿niowej.}
{102}{}{Pompa wodna nie dzia³a.}
{103}{}{To jakaœ maszyneria.}
{104}{}{System pomp nie dzia³a z powodu uszkodzenia pompy pró¿niowej.}
{105}{}{Chyba trzeba wymieniæ bezpiecznik.}
{106}{}{Pompa wodna nie dzia³a.}
{107}{}{Bez wymiany pompy pró¿niowej nie uda ci siê uruchomiæ systemu pomp.}
{108}{}{Nie uda³o ci siê naprawiæ pompy. Chyba trzeba wymieniæ bezpiecznik.}
{109}{}{Nie uda³o ci siê naprawiæ pompy.}
{110}{}{System pomp nie dzia³a z powodu uszkodzenia pompy pró¿niowej.}
{111}{}{Chyba trzeba zmieniæ bezpiecznik.}
{112}{}{Pompa wodna nie dzia³a.}
{113}{}{Nie zauwa¿asz niczego nadzwyczajnego.}
{114}{}{Po instalacji brakuj¹cych czêœci potê¿na pompa budzi siê do ¿ycia.}
{115}{}{Niszczysz czêœci i kaleczysz siê w d³oñ - otrzymujesz 1 punkt obra¿eñ.}
{116}{}{Masz problem z instalacj¹ tych czêœci.}
{117}{}{Tego przedmiotu nie mo¿na u¿yæ na pompie.}
{118}{}{Za naprawê pompy otrzymujesz 1,000 punktów doœwiadczenia.}

