{100}{}{Hej ty!!! Zatrzymaj siê i staw czo³a prawu!}
{101}{}{Dziêkujê za zdobycie hydroprocesora. To naprawdê poprawi morale i powstrzyma ludzi przed ³amaniem praw Krypty.}
{102}{}{Mi³o znowu ciê widzieæ. Mogê coœ dla ciebie zrobiæ?}
{103}{}{Czym siê zajmujesz?}
{104}{}{Tak, potrzebujê trochê broni.}
{105}{}{Dlaczego w Krypcie s¹ zamkniête drzwi?}
{106}{}{Glop!}
{107}{}{Hmm. Chyba masz byæ gdzie indziej. Mi³ego dnia.}
{108}{}{Dowodzê si³ami policyjnymi i bezpieczeñstwa Krypty. Mo¿e tego nie wiesz, ale beze mnie Krypta nie funkcjonowa³aby tak sprawnie.}
{109}{}{Hmm. Fajnie. Dziêki.}
{110}{}{To chyba wa¿ne?}
{111}{}{Bardzo. Bez odpowiedniego zastosowania praw Krypta szybko zamieni³a by siê w dzikie miejsce. To stanowi³oby zagro¿enie dla naszego bezpieczeñstwa.}
{112}{}{Skoro zdarza mi siê wychodziæ z Krypty s¹ mo¿e jakieœ prawa, które odnosz¹ siê szczególnie do mnie?}
{113}{}{Na zewn¹trz jest kilka miejsc, które cierpi¹ z powodu braku praw.}
{114}{}{No có¿, nawet jeœli na zewn¹trz broñ jest niezbêdna, to tutaj nie noœ jej w rêkach, gotowej do strza³u. Poza tym nic nie przychodzi mi na myœl.}
{115}{}{Dziêki.}
{116}{}{To by³o oczywiste, ¿e do tego dojdzie. Tylko przestrzeganie prawa ocali³o Kryptê przed zniszczeniem. Pracuj dalej.}
{117}{}{Opiekun nie zezwoli³ na otwarcie zbrojowni i przekazanie ci dodatkowej broni. Przykro mi, ale nie mogê ci pomóc. }
{118}{}{Proszê! Naprawdê jej potrzebujê!}
{119}{}{Dobrze. Dziêkujê.}
{120}{}{Nie. Nie mogê tego zrobiæ.}
{121}{}{Mi³ego dnia.}
{122}{}{¯eby do broni nie mia³ dostêpu nikt niepowo³any.}
{123}{}{A kto ma dostêp?}
{124}{}{To nieuczciwe.}
{125}{}{¯ycie czasem nie jest uczciwe. Ale nasze prawo tak. Mi³ego dnia.}
{126}{}{Opiekun, ja i moi stra¿nicy. To wszyscy.}
{127}{}{Wygl¹da na to, ¿e dostêp maj¹ tylko ci ludzie, którzy powinni go mieæ.}
{128}{}{To bardzo krótka lista.}
{129}{}{Tak. Muszê wracaæ do pracy.}
{130}{}{Tak, do œrodka mog¹ wejœæ tylko ci ludzie, którzy naprawdê musz¹.}
{131}{}{No có¿, ja muszê. Otwórz drzwi.}
{132}{}{Przykro mi, to dobry argument, ale nie mogê ciê wpuœciæ.}
{133}{}{Hmm. Skoro o tym wspominasz, to wygl¹da na to, ¿e rzeczywiœcie musisz. Poczekaj, zaraz otworzê drzwi.}
{134}{}{Co mogê dla ciebie zrobiæ,}
{135}{}{?}
{136}{}{Potrzebujê wiêcej broni.}
{137}{}{Dobrze siê czujesz?}
{138}{}{Huh-huh.}
{139}{}{Œwietnie. Twoja inteligencja mnie przyt³acza. Nie mogê ju¿ myœleæ.}
{140}{}{Przykro mi, da³em ci ju¿ wszystko co mog³em. Do widzenia.}
{141}{}{Nie lubiê takich jak ty. Krzykaczy. WstydŸ siê.}
{142}{}{Taaak, ty te¿ barani ³bie.}
{143}{}{Nie wydaje ci siê, ¿e jesteœ nieco za ostry?}
{144}{}{Uwa¿aj co mówisz, bo ciê oskar¿ê o l¿enie funkcjonariusza na s³u¿bie.}
{145}{}{Taak, pewnie. Na razie.}
{146}{}{Doœæ. Mam ciê ju¿ doœæ.}
{147}{}{Hmm. Mo¿liwe. Bezstronnoœæ powinna byæ czêœci¹ mojej pracy, ale tym razem chyba rzeczywiœcie przekroczy³em liniê. W przysz³oœci postaram siê tego unikaæ.}
{148}{}{Hmm. Nie. Chyba nie doœæ ostry.}
{149}{}{Powodzenia. Mam nadziejê, ¿e uda ci siê wykonaæ zadanie.}
{150}{}{Lepiej mnie nie zawiedŸ.}
{151}{}{Od³ó¿ broñ, natychmiast!}
{152}{}{Wydaje ci siê, ¿e co tutaj z tym robisz?}
{153}{}{Æwiczê celnoœæ.}
{154}{}{Nic, przepraszam. Ju¿ chowam broñ.}
{155}{}{Hung.}
{156}{}{Uwa¿aj jak do mnie mówisz. I trzymaj broñ w kaburze. To Krypta na litoœæ bosk¹!}
{157}{}{To lepiej nie rób tego tutaj. Je¿eli zrobisz to jeszcze raz, to bêdziemy mieæ powa¿ny problem.}
{158}{}{Wiedzia³em, ¿e wpadniesz w k³opoty przez tê wyprawê na zewn¹trz.}
{159}{}{Stój! Nie wolno ci tutaj przebywaæ!}
{1000}{}{Opiekun}
{1100}{}{Piastuje najwy¿sz¹ w³adzê w Krypcie. Mieszkañcy wykonuj¹ jego polecenia.}
