{100}{}{Paladyn}
{101}{}{Witaj, Kadecie.}
{102}{}{Je¿eli czegoœ potrzebujesz, to idŸ porozmawiaæ z Vree.}
{103}{}{Je¿eli chcesz z kimœ porozmawiaæ, to tam jest Vree.}
{104}{}{Muszê znaleŸæ trochê czasu na naukê pomiêdzy patrolami i treningami. Chyba mam trochê zaleg³oœci.}
{105}{}{Kadecie, przez ca³y czas musisz utrzymywaæ swoje cia³o i umys³ w doskona³ej kondycji.}
{106}{}{My, Skrybowie, projektujemy ca³e wyposa¿enie, broñ i zapasy. To doœæ ekscytuj¹ce.}
{107}{}{Synu, bycie paladynem to nie tylko walka.}
{108}{}{Moja droga, bycie paladynem to nie tylko walka.}
