{100}{}{Widzisz wieœniaka.}
{101}{}{No piêknie; taki du¿y ch³opiec i ucieka przed psem. Brawo Phil, ale mu pokaza³eœ. Œlicznie.}
{102}{}{Co robisz Phil? Sprawdzasz podeszwy tenisówek, prawda?}
{103}{}{Ale¿ ten pies jest wyg³odzony. Na pewno chcia³by ciê po¿reæ ¿ywcem Phil.}
{104}{}{To chyba lekka przesada. To tylko biedne, bezbronne zwierzê, nie s¹dzisz?}
{105}{}{£adnego masz pieska.}
{106}{}{Phil na pewno by³by ci wdziêczny za rozwi¹zanie problemu z tym psem.}
{107}{}{Dziêkujê za pomoc.}
