{100}{}{Widzisz wieœniaka.}
{101}{}{Widzisz Phila.}
{102}{}{To nie jest mój pies!}
{103}{}{Racja, zastrzeliæ bydlê!}
{104}{}{Na twoim miejscu nie ufa³bym tej bestii. To zabójca.}
{105}{}{Panie }
{106}{}{Pani }
{107}{}{, by³bym bardzo wdziêczny za pomoc w pozbyciu siê tego przeklêtego psa.}
{108}{}{Dlaczego?}
{109}{}{Nie. Ja zajmujê siê tylko powa¿nymi sprawami.}
{110}{}{Sk¹d siê wzi¹³?}
{111}{}{Hnn.}
{112}{}{Mo¿e uda ci siê zagadaæ go na œmieræ.}
{113}{}{Nie wpuszcza nas do domu, oto dlaczego.}
{114}{}{Dobrze.}
{115}{}{To nie twój pies?}
{116}{}{To "zwierz¹tko" pewnego podró¿nika. Kiedy ten podró¿nik umar³ to przeklête bydlê posadzi³o swój kud³aty zad na moim progu i nie chce odejœæ. Siedzi tu ju¿ od wielu dni.}
{117}{}{Aaa.}
{118}{}{Kim by³ ten podró¿nik?}
{119}{}{Jak wygl¹da³ ten podró¿nik?}
{120}{}{Nie wiem. Jakiœ dziwny koleœ. Powiedzia³, ¿e przyszed³ ze wschodu. Jak gdyby ktoœ móg³ pokonaæ pustyniê. Popad³ w konflikt z Gizmem; chcia³ mu namieszaæ w interesie.}
{121}{}{No i Gizmo nas³a³ na niego paru ch³opaków. St³ukli go i zrzucili z dachu kasyna. Skrêci³ sobie kark i sczez³. Pies strasznie siê wœciek³.}
{122}{}{Jak wygl¹da³ ten podró¿nik?}
{123}{}{Koleœ by³ wysoki, mia³ ciemne, lekko siwiej¹ce w³osy. Ca³y by³ ubrany w czarne skóry, jak gdyby to by³ odpowiedni ubiór na pustyniê. Mia³ ze sob¹ strzelbê.}
{124}{}{Mówi³ z takim zabawnym akcentem. Pies wszêdzie za nim chodzi³.}
{125}{}{Dziêki za opowieœæ.}
{126}{}{Nienawidzê tego psa.}
{127}{}{Dziêki za pomoc.}
{128}{}{Pomó¿ nam!}
{129}{}{Atakuj¹ nas!}
{130}{}{Dziêkujê za pomoc w obronie przed tymi przeklêtymi, pijanymi bandytami. W ramach podziêkowania mamy dla ciebie }
{131}{}{ kapsli.}
{132}{}{Dziêkujemy ci za pomoc! Zebraliœmy }
{133}{}{ kapsli, ¿eby ci podziêkowaæ za pomoc w obronie przed tymi zbirami.}

