{100}{}{Wpadasz w zasadzkê supermutantów!}
{101}{}{Wygl¹da na to, ¿e jesteœ w samym œrodku wojny gangów!}
{102}{}{Pêdzi na ciebie grupa wrogo nastawionych bandytów!}
{103}{}{Po ulicy pêdzi du¿a grupa szczurów!}
{104}{}{Pêdzi na ciebie grupa wrogo nastawionych bandytów!}
{105}{}{Nagle atakuj¹ ciê szczury!}
