{100}{}{Udaje ci siê stwierdziæ, ¿e Centrum Dowodzenia zosta³o pogrzebane pod tonami ska³. Musisz poszukaæ procesora gdzieœ indziej.}
{101}{}{Olbrzymia iloœæ skalnych od³amków blokuj¹cych to przejœcie robi na tobie spore wra¿enie. Nie wydaje ci siê, ¿eby mo¿na je by³o oczyœciæ, nawet przy u¿yciu silnych materia³ów wybuchowych.}
{102}{}{Zdobywasz }
{103}{}{ punktów doœwiadczenia.}
