{100}{}{Drzwi bezpieczeñstwa s¹ zamkniête.}
{101}{}{Drzwi bezpieczeñstwa s¹ otwarte.}
{102}{}{Uda³o ci siê otworzyæ drzwi bezpieczeñstwa.}
{103}{}{Nie uda³o ci siê otworzyæ drzwi bezpieczeñstwa.}
{104}{}{Popsuwszy zamek elektroniczny, uruchamiasz pasywny alarm. Dobra robota!}
{105}{}{Zdobywasz 25 punktów doœwiadczenia za otworzenie zamka.}
