{100}{}{Widzisz s³abo œwiec¹cy komputer.}
{101}{}{Dop³yw energii jest minimalny. Wiêkszoœæ z niej zosta³a najwyraŸniej skierowana do tych nielicznych systemów, które jeszcze choæ czêœciowo dzia³aj¹.}
{102}{}{Nie dostrzegasz niczego nadzwyczajnego.}
{103}{}{Ten komputer wydaje dziwne, bucz¹ce dŸwiêki.}
{104}{}{Monitor pod³¹czony do tego serwera wci¹¿ wyœwietla komunikat 'Awaria systemu'.}
{105}{}{Ten komputer wydaje siê byæ pozosta³oœci¹ po ataku jakiegoœ ghula.}
{106}{}{Ten komputer miga lampkami, jednak nie widzisz w tym ¿adnego sensu.}
{107}{}{Dotkniêcie tego komputera powoduje nieszkodliwe pora¿enie pr¹dem.}
{108}{}{Bli¿sze oglêdziny ukazuj¹, ¿e ten komputer zasiedli³a rodzina szczurów.}
{109}{}{Ekran pod³¹czony do tego systemu wyœwietla losowo dobrane liczby.}
{110}{}{Ten komputer wydaje z siebie ha³as, jakiego jeszcze nigdy nie uda³o ci siê us³yszeæ. Na monitorze widzisz s³owo 'Jared'.}
{111}{}{Po³owa tego komputera jest czarna i osmalona po starym po¿arze.}
