{100}{}{Widzisz zombi.}
{101}{}{Pope³ni³eœ wiele grzechów. Bêdê siê modliæ o ich odpuszczenie.}
{102}{}{Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ! Niech ¿yj¹ Pokój i Jednoœæ!}
{103}{}{Witam ciê, moje dziecko. Dlaczego dzier¿ysz broñ? Mo¿e chcesz poznaæ drogê pokoju?}
{104}{}{Chwa³a Mistrzowi, dziêki któremu wreszcie znalaz³em miejsce, w którym mogê z³o¿yæ broñ i przyj¹æ pokój za filozofiê!}
{105}{}{Brzmi nieŸle. Kto by mnie z tym zapozna³?}
{106}{}{Stojê na stra¿y.}
{107}{}{Brzmi nieŸle. Dostanê coœ ekstra, jak wys³ucham wyk³adu?}
{108}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{109}{}{Do diab³a z pokojem. Mistrz szykuje siê do wiêkszej rozgrywki, a ja mam zamiar siê w ni¹ wmieszaæ. Gdzie go znajdê?}
{110}{}{Ty mówiæ, ¿e ja g³upi?}
{111}{}{Witam. £adn¹ mamy dziœ pogodê, prawda?}
{112}{}{Owszem, ale szykuje siê burza. Wszêdzie czaj¹ siê wrogowie Katedry. S³ysza³eœ jakieœ plotki?}
{113}{}{Bywa³a ju¿ lepsza. Kto tu dowodzi?}
{114}{}{Taa, ³adna pogoda.}
{115}{}{Pod warunkiem, ¿e nie masz nic przeciwko radioaktywnej opaleniŸnie.}
{116}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{117}{}{Do diab³a z pogod¹. Przybywam, by zabiæ Mistrza. Gdzie znajdê tego œmiecia?}
{118}{}{Taa. S³oñce. S³oñce dobre.}
{119}{}{Witaj, przyjacielu. Dobrze ciê widzieæ. Od³ó¿ broñ, otaczaj¹ ciê tu przyjaciele!}
{120}{}{Przepraszam, ostatnich parê dni by³o ciê¿kich. Co mi mo¿esz powiedzieæ o tym miejscu?}
{121}{}{Przepraszam, ale doœwiadczenie nakazuje ostro¿noœæ. Kto tu dowodzi?}
{122}{}{Przyjaciele, co? Dziwne - mówi siê o was mnóstwo z³ych rzeczy.}
{123}{}{Mi³o s³yszeæ, ¿e otaczaj¹ mnie przyjaciele. Jak leci?}
{124}{}{Przyjaciele? A jak bardzo siê chcesz zaprzyjaŸniæ...}
{125}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{126}{}{Broñ?}
{127}{}{Witaj, przybyszu. Wybacz, ale nie powinno siê pos³ugiwaæ broni¹ w Katedrze.}
{128}{}{Moja broñ jest tu na us³ugi Katedry i jej Mistrza. Coœ ci nie pasuje?}
{129}{}{Dziêki. Z pewnoœci¹ to zapamiêtam.}
{130}{}{Stary nawyk. Ostatnio wiele stworów nastawa³o na moje ¿ycie. Co mi mo¿esz powiedzieæ o tym miejscu?}
{131}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{132}{}{Broñ?}
{133}{}{Witaj, przybyszu. Jeœli przybywasz w poszukiwaniu zbawienia, to jesteœ tu mile widziany, ale sugerujê od³o¿enie broni.}
{134}{}{Moja broñ jest tu na us³ugi Katedry i jej Mistrza. Coœ ci nie pasuje?}
{135}{}{Pewnie. Zbawienie. Brzmi nieŸle.}
{136}{}{Stary nawyk. Ostatnio wiele stworów nastawa³o na moje ¿ycie. Co mi mo¿esz powiedzieæ o tym miejscu?}
{137}{}{Sugeruj, co chcesz, ale jeœli chcesz dalej oddychaæ to lepiej odpowiadaj na moje pytania.}
{138}{}{Zbawienie-pierdzenie, ty durny zombi.}
{139}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{140}{}{Broñ?}
{141}{}{Witaj, przyjacielu! Tak siê cieszê, ¿e przy³¹czasz siê do naszej sprawy!}
{142}{}{Jeszcze nie - na razie tylko wyra¿am zainteresowanie. Co wy w ogóle robicie, oprócz g³oszenia tych bzdur o Pokoju i Jednoœci?}
{143}{}{Tak byæ musia³o. Do kogo mam siê zwróciæ w sprawie inicjacji?}
{144}{}{Przybywam po naukê. Czy mogê siê zobaczyæ z Mistrzem?}
{145}{}{Przyjaciele? A jak bardzo siê chcesz zaprzyjaŸniæ...}
{146}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{147}{}{Raaar! Sprawa! Raaar!?}
{148}{}{Witaj, przybyszu. Czy mogê ci w czymœ pomóc?}
{149}{}{Jasne. Znam wasze przes³anie i chce siê czegoœ wiêcej o was dowiedzieæ!}
{150}{}{Szukam szefa tego przybytku.}
{151}{}{Chyba nie próbujesz mi wmówiæ, ¿e te ca³e 'Pokój i Jednoœæ' s¹ na serio?}
{152}{}{Kim jest ten Mistrz?}
{153}{}{Przyda³by mi siê dobry masa¿ i mo¿e coœ jeszcze. Wchodzisz w to?}
{154}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{155}{}{Pomóc? Eee... nie.}
{156}{}{Wybacz mi, przybyszu, ale mam wiele obowi¹zków. Proszê o wybaczenie.}
{157}{}{Niech ¿yje Mistrz! Niech ¿yje Pokój! Niech ¿yje Œwiêty P³omieñ! Niech ¿yje Jednoœæ!}
{158}{}{Rozumiem ten kawa³ek o pokoju, ale dlaczego ten Mistrz jest w tym wszystkim taki wa¿ny?}
{159}{}{Szukam szefa tego przybytku.}
{160}{}{Chyba nie próbujesz mi wmówiæ, ¿e te ca³e 'Pokój i Jednoœæ' s¹ na serio?}
{161}{}{Kim jest ten Mistrz?}
{162}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{163}{}{Proponujê kontakt z Bratem Biczownikiem. To twardy cz³owiek, ale niezbadane s¹ œcie¿ki Mistrza... ¯egnaj.}
{165}{}{Ale przecie¿ my nie mamy ¿adnych stra¿y, oprócz Mrocznych. O czym ty mówisz?}
{166}{}{Mistrz zarz¹dzi³ dodatkowe œrodki bezpieczeñstwa. Nie wiem, po co - wydaje mi siê, ¿e Mroczni œwietnie siê sprawdzaj¹. Mo¿e ty wiesz, co siê dzieje?}
{167}{}{Ktoœ mi wyda³ z³e rozkazy. Nie przejmuj siê tym.}
{168}{}{Nie jestem ze stra¿y Katedry, tylko z jednego z patroli.}
{169}{}{Nie? Cholera!}
{170}{}{Ja...eee...Do diab³a, moja broñ ci wszystko wyt³umaczy. GIÑ!}
{171}{}{Wybacz. Niech ¿yje Mistrz i mi³ego dnia.}
{172}{}{Mo¿e póŸniej.}
{173}{}{Nie s¹dzê. Niech ¿yje Mistrz, to z pewnoœci¹ najlepsze rozwi¹zanie.}
{174}{}{Z pewnoœci¹. [Jêk].}
{175}{}{Co to za Katedra, w której nawet wina mszalnego nie ma?}
{176}{}{Skoro tak, to trzeba ciê bêdzie zabiæ na trzeŸwo. Na przyk³ad teraz. Zdychaj, sukinsynu!}
{177}{}{Wielu ju¿ próbowa³o zabiæ Mistrza, ale ¿adnemu siê nie powiod³o. Jeœli i ty dopuœcisz siê tego pod³ego czynu, Mistrz byæ mo¿e ci wybaczy i znajdzie dla ciebie zajêcie. Bêdê siê o ciebie modliæ.}
{178}{}{Tylko ¿artujê. Ludzie, którzy spêdzaj¹ du¿o czasu na Pustkowiach maj¹ dziwne poczucie humoru. Co siê tu dzieje?}
{179}{}{To siê jeszcze oka¿e...}
{180}{}{Nikt siê o mnie nie modli. Ale ktoœ powinien szybko zacz¹æ siê modliæ o ciebie, bo zaraz ciê zabijê!}
{181}{}{Przybywasz w z³e miejsce, przyjacielu. Tutaj nie chodzi o si³ê. Tutaj chodzi o pokój.}
{182}{}{Podobno Krucjata idzie dobrze. Wkrótce zaprowadzimy Pokój i Jednoœæ w Gruzach i innych okolicznych spo³ecznoœciach. Czy¿ to nie wspania³a wiadomoœæ?}
{183}{}{Kto ma zaznaæ Pokoju i Jednoœci w nastêpnej kolejnoœci?}
{184}{}{Niezbyt to konkretne. S³ysza³eœ mo¿e coœ jeszcze?}
{185}{}{To dobrze. Czas najwy¿szy, ¿eby ktoœ wyczyœci³ tamten œmietnik.}
{186}{}{Tak. Œmieræ jest wspania³a.}
{187}{}{Musisz siê udaæ do Ojca Morfeusza. Znajdziesz go w wie¿y. Czy to wszystko?}
{188}{}{Czy muszê siê jeszcze czegoœ dowiedzieæ, zanim go spotkam?}
{189}{}{To siê jeszcze oka¿e...}
{190}{}{Dziêki! Œwie¿e miêcho - nareszcie!}
{191}{}{Czy jeszcze coœ ciê trapi, moje dziecko?}
{192}{}{Przepraszam, ostatnich parê dni by³o ciê¿kich. Co mi mo¿esz powiedzieæ o tym miejscu?}
{193}{}{£aknê dalszych nauk Katedry. Do kogo muszê siê udaæ?}
{194}{}{Zastanawiam siê, kto tu rz¹dzi?}
{195}{}{Przyda³by mi siê dobry masa¿ i mo¿e coœ jeszcze. Wchodzisz w to?}
{196}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{197}{}{Zastanawiam siê, jakbyœ wygl¹da³, gdyby jakiœ wariat us³a³ pod³ogê Katedry kawa³kami twojego mózgu. Przekonajmy siê!}
{198}{}{Masz doskona³e poczucie humoru, moje dziecko. Tylko nie opowiadaj dowcipów Bratu Biczownikowi.}
{199}{}{Czy nale¿y uwa¿aæ na jeszcze jakieœ s³ugi Mistrza?}
{200}{}{Mo¿e spêdzi³a trochê za du¿o czasu na Pustkowiach?}
{201}{}{Chcê siê zobaczyæ z Mistrzem.}
{202}{}{Zastanawiam siê, kto tu rz¹dzi?}
{203}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{204}{}{To najmilsza rzecz, jak¹ dziœ s³yszê. Mo¿e ciê jednak nie zabijê.}
{205}{}{Obawiam siê, ¿e zbyt wiele przebywasz na s³oñcu. Mam nadziejê, ¿e pobyt tutaj ciê uleczy. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{206}{}{Twoje s³owa przepe³nia ból i nienawiœæ! ¯al mi ciebie, ale ¿al mo¿e siê zamieniæ w radoœæ. Odszukaj Ojca Morfeusza w wie¿y. To wspania³y cz³owiek, który umie ponownie otworzyæ serce dla mi³oœci.}
{207}{}{Nigdy przedtem nie uda³o ci siê odwiedziæ Katedry? To miejsce Pokoju i Jednoœci. To miejsce, w którym wszystkie ró¿nice id¹ w niepamiêæ, pozwalaj¹c nam na wybór przysz³oœci, w której zapanuje jednoœæ i dobrobyt dla wszystkich. Przysz³oœci, w której nie zdarz¹ siê cierpienia, jakie sobie nawzajem zadawali nasi przodkowie!}
{208}{}{Jak zamierzacie osi¹gn¹æ tê idealn¹ Utopiê?}
{209}{}{Czy stworzenie Utopii wymaga poœwiêcenia wolnej woli?}
{210}{}{Chêtnie zobaczê siê z Mistrzem i us³yszê, co on ma do powiedzenia.}
{211}{}{Sk¹d wiesz, ¿e to nie jest tylko jakaœ odmiana prania mózgu?}
{212}{}{A nie macie w tej dziurze jakiegoœ wina mszalnego?}
{213}{}{S³usznie. Zdecydowanie wolê zadawaæ cierpienia innym.}
{214}{}{Nasi wrogowie pos³uguj¹ siê oszczerstwem! Tak ³atwo przestraszyæ ludzi, zw³aszcza, gdy im siê mówi, co maj¹ robiæ! Ja jednak nie muszê siê ju¿ baæ, od kiedy moim panem jest Mistrz, a moj¹ religi¹ - Œwiêty P³omieñ. Mistrz zabroni³ mi siê baæ!}
{215}{}{Jak zamierzacie osi¹gn¹æ tê idealn¹ Utopiê?}
{216}{}{Brawa dla Mistrza! Nie wiesz, gdzie go mogê znaleŸæ?}
{217}{}{Ale tyle siê s³yszy plotek o armiach mutantów...}
{218}{}{Czy ktoœ ci kiedyœ powiedzia³, ¿e jesteœ zombi?}
{219}{}{S³usznie. Zdecydowanie wolê zadawaæ cierpienia innym.}
{220}{}{Wystarczy chwaliæ Mistrza. Nigdy mi siê to nie nudzi. Mo¿e siê przy³¹czysz, przyjacielu?}
{221}{}{Dlaczego niby mam chwaliæ Mistrza? No ju¿, przekonaj mnie.}
{222}{}{Pewnie. Niech ¿yje Mistrz! I jak?}
{223}{}{Raczej nie.}
{224}{}{Czy ktoœ ci kiedyœ powiedzia³, ¿e jesteœ zombi?}
{225}{}{Chwalmy go przy kilku butelczynach mszalnego wina. Znacznie lepiej siê chwali, gdy jest pod rêk¹ coœ dla kura¿u...}
{226}{}{Ta, któr¹ masz w d³oni?}
{227}{}{Ach, TA broñ.}
{228}{}{Czy jest na³adowana?}
{229}{}{Nie wiem zbyt wiele. Umys³ Mistrza jest tak wspania³y... Wiem tylko, ¿e Dzieci maszeruj¹ na pó³noc. Obejmiemy we w³adanie wszystkie osiedla i wszystkich ochrzcimy! Chrzest zbli¿y nas do Boga - osi¹gniemy pokój i jednoœæ, nie bêdzie wiêcej niszczycielskich wojen!}
{230}{}{A gdzie siê znajduje chrzcielnica?}
{231}{}{Wydaje mi siê, ¿e po prostu wystawi wszystkich na dzia³anie Wirusa FEV-2!}
{232}{}{To bêdzie wspania³y dzieñ!}
{233}{}{Wiem ju¿ wszystko.}
{234}{}{W takim razie lepiej jeszcze trochê sobie poniszczê, dopóki jeszcze mo¿na. Giñ, œmieciu!}
{235}{}{Niech ¿yje Mistrz! Pokój ci, dziecko! ¯yczê mi³ego pobytu w Katedrze.}
{236}{}{To sanktuarium, do którego mog¹ siê udaæ ci, którzy chc¹ zbudowaæ pokojow¹ przysz³oœæ - w³aœnie w celu realizacji swej wizji.}
{237}{}{Dlaczego wydaje siê wam, ¿e macie prawo zmuszaæ innych do przyjêcia waszej wizji przysz³oœci?}
{238}{}{Ale ludzie musz¹ mieæ mo¿liwoœæ opuszczenia sanktuarium i wyjœcia na œwiat. W przeciwnym wypadku sanktuarium staje siê wiêzieniem.}
{239}{}{Nikt nie chce pokoju. Wszyscy chc¹ w³adzy, koleœ. Przejrzyj na oczy!}
{240}{}{Brzmi nieŸle. Do kogo muszê iœæ, ¿eby siê przy³¹czyæ?}
{241}{}{Pokój? Sanktuarium? Rzygaæ mi siê chce przez ciebie, zombi matole!}
{242}{}{Cieszê siê, ¿e interesuje ciê pokój. Pomów o tym z Ojcem Morfeuszem lub Bratem Biczownikiem. Udziel¹ ci dalszych nauk.}
{243}{}{Obawiam siê, ¿e nie mogê ci pomóc. Tylko Ojciec Morfeusz kontaktuje siê z Mistrzem. Znajdziesz go w wie¿y.}
{244}{}{Czy muszê siê jeszcze czegoœ dowiedzieæ, zanim go spotkam?}
{245}{}{Dziêki. Do nastêpnego spotkania.}
{246}{}{Ojciec Morfeusz. To dopiero pokojowo brzmi¹ce miano. Kto jest jego zastêpc¹, Brat Morderca? A mo¿e Brat Œmieræ? Albo Siostra Zabójstwo?}
{247}{}{Jestem gotów odrodziæ siê w imiê sprawy. Zabij mnie, jeœli musisz, ale mnie czeka zbawienie, a ciebie œmieræ.}
{248}{}{Tak czy inaczej zaraz z ciebie wyprujê flaki!}
{249}{}{Móg³byœ siê zamkn¹æ? Wy, zombi, przyprawiacie mnie o ból g³owy.}
{250}{}{Masz jaja. Podziwiam to. Mo¿e ciê nie zabijê.}
{251}{}{Nic mnie nie obchodzi twoja dusza, ale nie mogê siê oprzeæ tak mi³emu zaproszeniu... Zaraz wst¹pisz w poczet mêczenników!}
{252}{}{Có¿... Eee... IdŸ w pokoju... Chyba... ¯egnaj...}
{253}{}{Rozejrzyj siê! Nie s³yszysz przes³añ? Jak mo¿esz poddawaæ w w¹tpliwoœæ szczeroœæ Mistrza?}
{254}{}{Nikt nie chce pokoju. Wszyscy chc¹ w³adzy, koleœ. Przejrzyj na oczy!}
{255}{}{£atwo siê mówi o pokoju, ale co tak naprawdê robi Mistrz, aby go osi¹gn¹æ?}
{256}{}{Przebacz mi, bracie. Œwiat jest strasznym miejscem i obawiam siê o nasz¹ wolnoœæ...}
{257}{}{£atwo siê mówi o pokoju, ale s³yszy siê te wszystkie plotki o armiach mutantów...}
{258}{}{Mo¿e i masz racjê. Do kogo muszê iœæ, ¿eby siê przy³¹czyæ?}
{259}{}{Jedynym Ÿród³em szczeroœci jest lufa karabinu!}
{260}{}{Mistrz jest Opiekunem Œwiêtego Ognia i usilnie pracuje nad usuniêciem wszystkich podzia³ów i wszelkiej nienawiœci. Dzier¿y zarówno miecz jak i lemiesz, ale zdecydowanie przedk³ada budowanie nad niszczenie. Niech ¿yje Mistrz! Niech ¿yje Jednoœæ!}
{261}{}{Podobno Krucjata idzie dobrze. Maszerujemy na pó³noc i, tak jak przyrzek³ Mistrz, si³y Ciemnego Wieku nie s¹ siê w stanie przeciwstawiæ armii Oœwieconych. To wspania³e czasy! Unieœ g³owê, przyjacielu i krzycz z radoœci!}
{262}{}{A co z tymi, których pokonujemy? Czy krew pokona Ciemny Wiek? Albo tyrania?}
{263}{}{A¿ siê chce tañczyæ z radoœci!}
{264}{}{Wiem ju¿ wszystko.}
{265}{}{Niestety. Boli mnie gard³o. Uczczê to raczej na swój sposób - zabijaj¹c ciê!}
{266}{}{Nie by³o moim zamiarem ciê obraziæ, ani przeszkodziæ w wype³nianiu obowi¹zków. Przyjmij moje przeprosiny. Niech ciê Mistrz b³ogos³awi za wiern¹ s³u¿bê.}
{267}{}{Przepraszam. Niech ¿yje Mistrz i mi³ego dnia.}
{268}{}{Masz smutn¹ duszê, przyjacielu. Mogê siê tylko domyœlaæ, jakie koszmary spowodowa³y ten stan. Otwórz swój umys³ i znajdŸ ukojenie. Patrz na ekrany, pos³uchaj Ojca Morfeusza i chwal Mistrza.}
{269}{}{Nic nie wiem, przyjacielu, naprawdê nic! Musisz znaleŸæ kogoœ innego, aby odpowiedzia³ na twoje pytania. Pamiêtaj tylko, ¿e pytanie o Mrocznych to nie jest dobre posuniêcie.}
{270}{}{Jasne. Rozumiem.}
{271}{}{Dlaczego?}
{272}{}{Mam tylko jedno pytanie, które ich dotyczy. Czy g³oœno wrzeszcz¹, gdy siê je zabija?}
{273}{}{Nic nie wiesz? Co ty, g³upi?}
{274}{}{Mroczni! Mroczni! Zabiæ!}
{275}{}{Œwietnie siê rozmawia, ale zaniedbujê pochwa³y. ¯egnaj. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ! Œpiewajmy œwiête pieœni...}
{276}{}{Jeœli ci siê tu nie podoba, to zawsze mo¿esz sobie st¹d pójœæ. Niech ¿yje Mistrz i mi³ego dnia.}
{277}{}{¯al mi Pustkowi, jeœli taki w³aœnie humor na nich powstaje. Na twoim miejscu nie dzieli³bym siê nim z innymi.}
{278}{}{Czy jest ktoœ konkretny, kogo nale¿y unikaæ?}
{279}{}{Strasznie tu musi byæ nudno!}
{280}{}{Dobra, nie bêdê ju¿ ¿artowaæ.}
{281}{}{A s³ysza³eœ dowcip o nagim d¿okeju i komiwoja¿erze?}
{282}{}{Na pewno nie chcesz zobaczyæ, co robiê dla zabawy...}
{283}{}{Nie wydaje mi siê. ¯egnaj, przyjacielu.}
{284}{}{Nie wydaje mi siê, abym móg³ ci pomóc. ¯egnam i mi³ego dnia. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{285}{}{Obawiam siê, ¿e w tym ci nie pomogê. Muszê pomedytowaæ nad wielkoœci¹ Mistrza. ¯egnam. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{286}{}{Wszystkich tutaj przepe³nia mi³oœæ. Niektórym jednak trudno daæ upust swej mi³oœci, a ju¿ zw³aszcza Mrocznym. To jednak musisz odkryæ na w³asn¹ rêkê. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{287}{}{Musimy poddaæ siê w³adzy Mistrza i Œwiêtego P³omienia. Gdy ju¿ udowodnimy, ¿e jesteœmy tego warci, dost¹pimy chrztu i zbli¿ymy siê do Boga. Gdy ju¿ wszyscy zostan¹ ochrzczeni, staniemy siê jednym, Jednoœci¹ pod w³adz¹ Mistrza!}
{288}{}{Powiedz mi coœ wiêcej o tym chrzcie.}
{289}{}{A co, jeœli ktoœ nie ma ochoty na ten zaszczyt?}
{290}{}{Brzmi nieŸle. Mogê siê trochê rozejrzeæ?}
{291}{}{Przecie¿ jesteœcie tylko gromad¹ zombi.}
{292}{}{Tylko w jednym wypadku wszyscy stan¹ siê Jednoœci¹ - jako nawóz.}
{293}{}{Mamy prawo do prze¿ycia. Staro¿ytni próbowali prze¿yæ i zachowaæ swoj¹ wolnoœæ - patrz, co dla nas z tego wynik³o! Nie wolno nam pope³niæ tych samych b³êdów. Jednoœæ to jedyne wyjœcie. To jedyny sposób na zachowanie ludzkoœci - a raczej tego, co z niej zosta³o!}
{294}{}{Co masz na myœli - 'tego, co z niej zosta³o'? Wci¹¿ jesteœmy przecie¿ ludŸmi.}
{295}{}{Byæ mo¿e b³êdem naszych przodków nie by³ brak jednoœci. Mo¿e nie umieli po prostu daæ spokoju innym.}
{296}{}{Filozofia mnie nie krêci, ale wiem, ¿e pewne rzeczy s¹ s³uszne, a inne - z³e. Wasza sprawa jest z³a.}
{297}{}{Mo¿e i masz racjê.}
{298}{}{Ludzkoœæ nie jest warta ratowania - ty te¿ nie. Giñ, zombi!}
{299}{}{Mistrz powiedzia³, ¿e przyczyn¹ by³ brak Jednoœci, wiêc tak musia³o byæ. OdnajdŸ jego naczelnego kap³ana! Ojciec Morfeusz pomo¿e ci w odrzuceniu k³amstw, jakimi ciê karmiono.}
{300}{}{Nie jesteœmy ¿adnymi zombi! Jako cz³onek gangu Walecznych Cia³ by³em psychotycznym durniem, który robi³ wszystko, co mu kazano! Chwa³a Mistrzowi, ¿e przejrza³em na oczy! Niech ¿yje Mistrz! Chwalmy go razem!}
{301}{}{Lepiej mi siê go bêdzie chwali³o, jeœli dowiem siê, co on robi.}
{302}{}{Niech ¿yje Mistrz!}
{303}{}{To ty go chwal, a ja siê st¹d zmywam.}
{304}{}{Mo¿e byœmy go tak chwalili nad butelczyn¹ œwiêtego wina. Muszê siê czegoœ napiæ!}
{305}{}{Mam jeszcze lepszy pomys³. Bêdê go chwali³ nad twoimi zw³okami. Czas umieraæ!}
{306}{}{Czy¿ to nie wspania³e, ¿e Mistrz ma zamiar po³¹czyæ ludzi i mutantów? Przekracza bariery nienawiœci i uprzedzeñ. Nie dostrzegasz tego - to dowodzi, ¿e on ¿yczy wszystkim jak najlepiej!}
{307}{}{Tak, z pewnoœci¹ wasze armie szerz¹ mi³oœæ i braterstwo wszêdzie, gdzie dotr¹...}
{308}{}{Tak, na pewno nie robi tego tylko dla tego, ¿e mutanty s¹ efektywnymi zabójcami...}
{309}{}{Niech ¿yje Mistrz!}
{310}{}{Potrzeba mi wiêcej dowodów.}
{311}{}{Mo¿e byœmy go tak chwalili nad butelczyn¹ œwiêtego wina. Muszê siê czegoœ napiæ!}
{312}{}{Teraz rozumiem. Pod¹¿ê za przyk³adem Mistrza! Wiem, co dla ciebie najlepsze, wiêc muszê ciê zabiæ. Natychmiast! Genialne...}
{313}{}{Otwórz swe serce. Otwórz swój umys³. S³uchaj, co mówi¹ ludzie, a znajdziesz oœwiecenie.}
{314}{}{Mo¿e znajdê kogoœ, kto mi lepiej wyt³umaczy. Na przyk³ad sam Mistrz...}
{315}{}{Rozumiem - jesteœcie band¹ zombi!}
{316}{}{To nie jest uzasadnienie, to propaganda!}
{317}{}{Chyba po prostu pochodzê po okolicy i siê rozejrzê.}
{318}{}{Wolê raczej otworzyæ jakieœ wiñsko. Gdzie tu macie barek?}
{319}{}{Chce mi siê rzygaæ, jak patrzê na was, zombi! Chcê pozabijaæ was wszystkich!}
{320}{}{To takie smutne. Bêdê siê o ciebie modliæ.}
{321}{}{Niestety, nigdy nie dost¹pi³em zaszczytu ujrzenia chrzcielnicy. Byæ mo¿e jeœli bêdê chwali³ Mistrza dostatecznie d³ugo, to zostanê b³ogos³awiony tym widokiem. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ! Niech ¿yj¹ Pokój i Jednoœæ!}
{322}{}{Oczywiœcie, ¿e nie. Jest Mistrzem. Nigdy by tak nie post¹pi³ ze swoimi uczniami. To jego œwiêta moc nas zmieni - poprzez chrzest i Œwiêty Ogieñ. Ten wirus to z³o przynale¿ne do starego œwiata - jestem pewien, ¿e zostanie on za nami.}
{323}{}{Nie chcemy powodowaæ u ciebie niepokoju. Jeœli przebywanie w naszym towarzystwie nie przynosi ci ukojenia, to chyba musisz znaleŸæ inne miejsce, które na to pozwoli. Tu króluje pokój.}
{324}{}{Wynoszê siê st¹d!}
{325}{}{Mia³eœ siê zamkn¹æ. Dlaczego mnie nie s³uchasz?}
{326}{}{Wygl¹da na to, ¿e jedynym sposobem na zaznanie ciszy i spokoju jest zabicie was wszystkich! Giñ!!}
{327}{}{Musisz samodzielnie znaleŸæ odpowiedŸ na to pytanie. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{328}{}{Chrzest zmieni nas wszystkich, równie¿ fizycznie zbli¿aj¹c nas do obrazu Boga. Gdy wszyscy siê nim staniemy, znikn¹ wszelkie ró¿nice - wreszcie osi¹gniemy pokój i jednoœæ i nie bêdzie ju¿ nigdy niszczycielskich wojen!}
{329}{}{A gdzie siê znajduje chrzcielnica?}
{330}{}{Wydaje mi siê, ¿e po prostu wystawi wszystkich na dzia³anie Wirusa FEV-2!}
{331}{}{To bêdzie wspania³y dzieñ!}
{332}{}{Wiem ju¿ wszystko.}
{333}{}{W takim razie lepiej jeszcze trochê sobie poniszczê, dopóki jeszcze mo¿na. Giñ, oœle!}
{334}{}{Gdy ludzie wreszcie zrozumiej¹ Mistrza i to, co sob¹ reprezentuje, ka¿dy bêdzie chcia³ dost¹piæ chrztu. Ci, którzy bêd¹ siê temu sprzeciwiali s¹ niepoczytalni i dla ich w³asnego dobra nale¿y skróciæ ich cierpienia.}
{335}{}{Nie zaskakuje ciê liczba dotychczas spotkanych niepoczytalnych osób?}
{336}{}{Wariat!}
{337}{}{Chyba siê lepiej trochê rozejrzê.}
{338}{}{Taa. Biedacy. Otwórzmy butelkê wina mszalnego i wypijmy za nich!}
{339}{}{Jeœli potrzebujecie kogoœ, kto to za³atwi, to ja tu jestem!}
{340}{}{Przyjacielu, jeœli szukasz prawdy i masz otwarty umys³, to jesteœmy tu dla ciebie. Niech ¿yje Mistrz! ¯yczê ci wszystkiego najlepszego na twojej drodze ku oœwieceniu.}
{341}{}{Zarówno mutanci jak i ludzie musz¹ siê zbli¿yæ do Boga. Nie jestem pewien, co Mistrz ma na myœli w tej czêœci swego przes³ania, ale to musi byæ s³uszne. Niech ¿yje Mistrz - on jest taki m¹dry!}
{342}{}{Czy jeœli naprawdê by³by taki m¹dry, to czy pozwoli³by na niejednoznacznoœæ swojego przes³ania?}
{343}{}{Wariat!}
{344}{}{Chyba siê lepiej trochê rozejrzê.}
{345}{}{Taa. Mam œwietny pomys³! Otwórzmy butelkê wina mszalnego i wypijmy za m¹droœæ Mistrza!}
{346}{}{Ca³a m¹droœæ tego œwiata nie zatrzyma pocisku z karabinu trafiaj¹cego prosto miêdzy oczy.}
{347}{}{Tworzymy œwiat lepszy dla wszystkich. To wszystko. Przykro mi, jeœli jeszcze tego nie rozumiesz. Bêdê siê modliæ, ¿eby ktoœ m¹drzejszy ode mnie ciê oœwieci³. ¯egnaj, przyjacielu. Niech ¿yje Mistrz! Niech ¿yj¹ Pokój i Jednoœæ!}
{348}{}{Œwiat kryje wiele niespodzianek, przyjacielu - niektóre s¹ mi³e, inne nie. ¯egnaj, przyjacielu i chwa³a Mistrzowi!}
{349}{}{[koniec]}
