{100}{}{Widzisz wysoce zaawansowany komputer Bractwa.}
{101}{}{Nie uda³o ci siê uzyskaæ dostêpu do terminala.}
{102}{}{Lekcja koñczy siê po szeœciu godzinach. Masz doœæ.}
{103}{}{Nie mo¿esz ju¿ przyswoiæ wiêcej wiedzy.}
{200}{}{Widzisz komputer, a tak¿e kilka kawa³ków czegoœ, co mo¿e byæ ludzkim
 miêsem.}
{201}{}{Chwilê majstrujesz przy komputerze, ale nie mo¿esz obejœæ systemu
 zabezpieczeñ.}
{202}{}{Ten komputer dzia³a wrêcz idealnie.}
{203}{}{Uda³o ci siê zdobyæ ciekawe informacje dotycz¹ce bazy na pó³nocnym
 zachodzie.}
{204}{}{Zdobywasz }
{205}{}{ punktów doœwiadczenia za w³amanie siê do tego komputera.}
