{100}{}{Widzisz Troya.}
{101}{}{Gratulacje, cz³owieku. Pozwolono ci do³¹czyæ do elitarnej grupy wyznawców. ChodŸ za mn¹.}
{102}{}{Nie ma to zapewne nic wspólnego z plotkami o armii supermutantów, co?}
{103}{}{Dok¹d?}
{104}{}{Na co czekasz? ChodŸmy!}
{105}{}{Raczej nie.}
{106}{}{Co to za okropny smród rozk³adaj¹cego siê cia³a? A, to ty!}
{107}{}{Ruh?}
{108}{}{ChodŸ za mn¹, a zobaczysz. Uj¹wszy to inaczej: idŸ za mn¹ i ¿yj, g³upia istoto!}
{109}{}{Wiêc zginê, jeœli nie pójdê? Nie brzmi mi to zbyt religijnie.}
{110}{}{Przekona³eœ mnie. Idziemy!}
{111}{}{Chyba raczej nie.}
{112}{}{Nie zaczynaj czegoœ, czego nie zdo³asz skoñczyæ!}
{113}{}{Doskonale!}
{114}{}{Nie nale¿y siê bawiæ z pani¹ Jain, ani z Dzieæmi.}
{115}{}{Nie nale¿y obra¿aæ kogoœ, kogo nie jest siê w stanie zabiæ. Idziesz ze mn¹, aby prze¿yæ, czy zostajesz, aby zgin¹æ?}
{116}{}{Idê!}
{117}{}{Zapomnij.}
{118}{}{Kurcze, niektórzy mutanci nie znaj¹ siê na ¿artach!}
{119}{}{Jak dalej bêdê ciê w¹chaæ, to i tak zdechnê!}
{120}{}{Ty durna bestio! Idziesz czy zostajesz?}
{121}{}{Eee... Iœæ!}
{122}{}{Eee... Ja zostawaæ!}
{123}{}{Nie mêcz mnie swoim niezdecydowaniem! Co postanawiasz, cz³owieku?}
{124}{}{Idê z tob¹. ChodŸmy.}
{125}{}{Zapomnij.}
{126}{}{Jak œmiesz mnie poganiaæ! Nikt mi nie bêdzie mówi³, co mam robiæ!}
{127}{}{Bezczelny psie! Teraz zginiesz!}
{128}{}{Nie mêcz mnie swoimi ¿artami! Co postanawiasz, cz³owieku?}
{129}{}{Idê z tob¹. ChodŸmy.}
{130}{}{Zapomnij.}
{131}{}{Nie popêdzaj mnie, koleœ. Próbujê wymyœliæ dowcipn¹ odpowiedŸ...}
{132}{}{Mutant ignoruje ciê.}
