{100}{}{Widzisz mieszkañca Krypty 13.}
{101}{}{Nie s¹dziliœmy, ¿e wrócisz. Masz taki fajny pokój, a nam by³o trochê za ciasno z jej jej rodzicami. Mam nadziejê, ¿e nie masz nic przeciwko.}
{102}{}{Owszem, mam. Wynoœcie siê z mojego pokoju!}
{103}{}{Nie mam. Mi³ego pobytu.}
{104}{}{Dobrze by by³o odzyskaæ moje mieszkanie. ZnajdŸcie sobie coœ innego.}
{105}{}{Hng.}
{106}{}{Nie chcê siê z tob¹ k³óciæ, ale to oczywiste, ¿e nie zas³ugujesz ju¿ na w³asny pokój. WyjdŸ, proszê.}
{107}{}{Naprawdê potrzebujemy tego pokoju. Mam nadziejê, ¿e zmienisz zdanie.}
{108}{}{Có¿... Niech no siê zastanowiê... Hmmm... Nie. Wynoœcie siê!}
{109}{}{Niech bêdzie. Potrzebujecie go bardziej ode mnie.}
{110}{}{Dziêki! Jesteœmy naprawdê wdziêczni. Twoje rzeczy schowaliœmy do kufra.}
{111}{}{No nie wiem. Nie korzystasz z niego zbyt czêsto, a nam by siê przyda³.}
{112}{}{Dobra. WeŸcie go sobie.}
{113}{}{To miejsce przypomina mi o moich korzeniach. Poza tym dobrze siê tu odpoczywa.}
{114}{}{Wydawa³o nam siê, ¿e nie to miejsce ju¿ ciê nie obchodzi. Mi³ego dnia. Znów zamieszkamy z jej rodzicami.}
{115}{}{Naprawdê nam siê tu podoba.}
{116}{}{WyjdŸ. Ju¿ tu nie mieszkasz.}
