{100}{}{Widzisz jedno z Dzieci Katedry.}
{101}{}{Nie rozmawiam z poganami takimi jak ty.}
{102}{}{Twój raport, VanHagan.}
{103}{}{Mistrza ciesz¹ twoje postêpy, ale potrzeby rosn¹, a czasu jest ma³o.}
{104}{}{Mistrz powinien wiedzieæ, ¿e nie mamy doœæ surowców. Bez nich nie mo¿emy tworzyæ ¿o³nierzy.}
{105}{}{On zdaje sobie sprawê z waszych problemów. Nawet w tej chwili stara siê je rozwi¹zaæ.}
{106}{}{Powiedz cos wiêcej o jego planach. Jeœli Jednoœæ ma zatryumfowaæ, to bêdziemy musieli skoordynowaæ nasze dzia³ania.}
{107}{}{Mistrz dowiedzia³ siê o nieznanej dot¹d, aktywnej Krypcie. Taka iloœæ surowca pozwoli nam na stworzenie wielkiej liczby ¿o³nierzy. A wed³ug programów przewiduj¹cych, to w³aœnie liczebnoœæ zadecyduje o naszym sukcesie.}
{108}{}{Doskonale. Szczêœliwie siê sk³ada. Czy mieszkañcy s¹ ska¿eni?}
{109}{}{To jest najlepsze. Jeœli ich przedstawiciel jest reprezentatywny, to s¹ czyœci. Jak ³za.}
{110}{}{To ekscytuj¹ce. Któr¹ to Kryptê bêdziemy zdobywaæ?}
{111}{}{Numer 13. Wkrótce. Naprawdê nied³ugo.}
{112}{}{Zdobywasz 1000 punktów doœwiadczenia za pods³uchanie ca³ej rozmowy dotycz¹cej twojej Krypty.}
