{100}{}{Widzisz kobietê.}
{101}{}{Nie chcê umieraæ. Nie jestem ¿o³nierzem.}
{102}{}{Nie chcê umieraæ. Nie jestem ¿o³nierzem.}
{103}{}{Zacznij gadaæ, a pozwolê ci ¿yæ.}
{104}{}{Ja równie¿ nim nie jestem. Zabijam tylko wtedy, kiedy muszê.}
{105}{}{Nie powinnaœ przypadkiem chwaliæ Mistrza, albo coœ?}
{106}{}{Oszczêdzê ciê za mocny trunek. Gdzie tu macie barek?}
{107}{}{Dobranoc, suko!}
{108}{}{Ja wielka ¿o³nierz! Hah! Hah! Hah!}
{109}{}{Dobrze, ¿e przybywasz, aby ze mn¹ pomówiæ. Wiem, co od ciebie us³ysza³a Laura. Nie wolno ci tego robiæ!}
{110}{}{Czego takiego?}
{111}{}{Laura? Jaka Laura?}
{112}{}{Och.}
{113}{}{To gruba pomy³ka - bêdzie ciê drogo kosztowaæ.}
{114}{}{Co? Jak? Raar!}
{115}{}{Chyba ju¿ wszystko sobie powiedzieliœmy. ¯egnam.}
{116}{}{Nie rozmawiam z osobami, które mierz¹ do mnie z broni. Schowaj j¹, to pogadamy.}
{117}{}{Witaj ponownie. Mam nadziejê, ¿e znajdujesz to miejsce ciekawym.}
{118}{}{Có¿, bywa³o siê ju¿ w miejscach zapewniaj¹cych lepsz¹ rozrywkê...}
{119}{}{Oczywiœcie, siostro. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{120}{}{Zawsze, kiedy z kimœ rozmawiam, ten ktoœ wci¹¿ tylko powtarza te same rzeczy.}
{121}{}{Ciekawe? Gdzie jest alkohol!}
{122}{}{Strasznie tu nudno! Gdzie krew? Gdzie œmieræ?}
{123}{}{Witaj, Nowicjuszu. W czym ci mogê pomóc?}
{124}{}{Trochê mnie martwi¹ nasze plany d³ugoterminowe.}
{125}{}{Co siê dzieje w okolicy?}
{126}{}{Gdzie znajdê Mistrza?}
{127}{}{Kto tu dowodzi?}
{128}{}{Ej¿e, bez jaj. Nikt nikomu nie pomaga, chyba, ¿e mu siê przystawi spluwê do czo³a!}
{129}{}{Witam pana! Pañska reputacja dotar³a ju¿ i do nas! Czy mogê pani w czymœ pomóc?}
{130}{}{Witam pani¹! Pani reputacja dotar³a ju¿ i do nas! Czy mogê pani w czymœ pomóc?}
{131}{}{Ciekawi mnie, o co chodzi w tej ca³ej Katedrze.}
{132}{}{Jak siê mo¿na do was przy³¹czyæ?}
{133}{}{Gdzie znajdê Mistrza?}
{134}{}{Kto tu dowodzi?}
{135}{}{Ej¿e, bez jaj. Nikt nikomu nie pomaga, chyba, ¿e mu siê przystawi spluwê do czo³a!}
{136}{}{Witam pana! Pañska reputacja dotar³a ju¿ i do nas! Czy mogê pani w czymœ pomóc?}
{137}{}{Witam pani¹! Pani reputacja dotar³a ju¿ i do nas! Czy mogê pani w czymœ pomóc?}
{138}{}{Ciekawi mnie, o co chodzi w tej ca³ej Katedrze.}
{139}{}{Jak siê mo¿na do was przy³¹czyæ?}
{140}{}{Gdzie znajdê Mistrza?}
{141}{}{Kto tu dowodzi?}
{142}{}{Ej¿e, bez jaj. Nikt nikomu nie pomaga, chyba, ¿e mu siê przystawi spluwê do czo³a!}
{143}{}{Wiem, kim jesteœ. Proszê mi wybaczyæ brak og³ady, ale nie zadajê siê z psycholami-mordercami. ¯egnam.}
{144}{}{Moja reputacja jest znacznie przesadzona. Czy Katedra ocenia ludzi na podstawie plotek i insynuacji?}
{145}{}{Psychol-morderca? Ja?}
{146}{}{¯aden ze mnie psychol, dziecinko. Mam jednak ¿ó³te papiery i udowodniê ich zasadnoœæ, jeœli nie bêdziesz odpowiadaæ na moje pytania!}
{147}{}{Nie³atwo nak³adam na siebie wiêzy lojalnoœci. Równie rzadko jednak te¿ je ³amiê. Nic ci nie powiem.}
{148}{}{Dobrze. Mo¿emy wiêc zostawiæ siê nawzajem w spokoju i og³osiæ remis.}
{149}{}{Chwalenie Mistrza nie ocali mojego ¿ycia. No ju¿, rób to. Nie mogê ciê w ¿aden sposób powstrzymaæ.}
{150}{}{Gdzieœ w pobli¿u Katedry sprzedaj¹ bimber. Narkotyki i alkohol s¹ tu towarami zakazanymi.}
{151}{}{Spróbowaæ wykraœæ Morfeuszowi klucz do tajnego wejœcia i zabiæ Mistrza.}
{152}{}{A dlaczegó¿ to?}
{153}{}{Nie wiem, o czym mówisz.}
{154}{}{I po co to niby planujê?}
{155}{}{A s³ysza³aœ, co siê dzieje z tymi, co wiedz¹ zbyt wiele?}
{156}{}{Szpiegiem Uczniów Apokalipsy. Obecnie przebywa w jednym z pokoi medytacyjnych.}
{157}{}{Jest tu szpieg? Natychmiast musimy poinformowaæ G³ównego Kap³ana!}
{158}{}{Nie wiem, o czym mówisz.}
{159}{}{Po co by mi by³o szpiegowanie was?}
{160}{}{A s³ysza³aœ, co siê dzieje z tymi, co wiedz¹ zbyt wiele?}
{161}{}{Tutaj chodzi o oœwiecenie, nie rozrywkê. A zw³aszcza o dokonywanie w³aœciwych wyborów dotycz¹cych przysz³oœci œwiata. Do zobaczenia.}
{162}{}{Taaaak. Pewnie. Oczywiœcie. Do zobaczenia.}
{163}{}{Wiem. Te¿ tak robiê, gdy nie mam nic odkrywczego do powiedzenia. Do zobaczenia.}
{164}{}{Ten, kogo wype³nia duch Œwiêtego Ognia nie potrzebuje innych u¿ywek. W ka¿dym razie tak mówi¹. Wiesz, jak jest.}
{165}{}{Na górze. Poproœ Mrocznych, ¿eby ciê sprali - zrobi¹ to z przyjemnoœci¹.}
{166}{}{Poniewa¿ Mistrz to z³o konieczne. Poniewa¿ ktoœ musi zjednoczyæ ten œwiat, a on jest jedynym, który ma szansê na wyrównanie ró¿nic.}
{167}{}{Ktoœ ci ju¿ mówi³, ¿e ta ca³a Jednoœæ jest przereklamowana?}
{168}{}{Dlaczego?}
{169}{}{Nie wierzê w koncept z³a koniecznego.}
{170}{}{Mi tam podoba siê ten œwiat.}
{171}{}{Nie podoba mi siê ta rozmowa.}
{172}{}{Dobra - jeœli nie przyznasz siê do w³asnych s³ów, to ci nie pomogê. ¯egnam.}
{173}{}{Poniewa¿ uwa¿asz, ¿e Dzieci nie maj¹ prawa naje¿d¿aæ swoich s¹siadów. Poniewa¿ s¹dzisz, ¿e zabicie Mistrza zatrzyma ten proces.}
{174}{}{Jeœli tak - na czym polega³by mój b³¹d?}
{175}{}{To herezja!}
{176}{}{Skoro s¹dzisz, ¿e ja w to wierzê, czemu mnie nie wyda³aœ?}
{177}{}{Czy ja wygl¹dam na kogoœ, kto nie lubi sobie od czasu do czasu pozabijaæ?}
{178}{}{Znasz sytuacjê, gdy jest siê zamieszanym w coœ, co nas przerasta? Nikt, niezale¿nie od uzbrojenia i umiejêtnoœci, nie zdo³a pokonaæ pó³ tuzina Mrocznych. Moj¹ filozofi¹ jest pokój. Próbujê ciê uratowaæ.}
{179}{}{Spójrz na tych, którzy spowodowali Apokalipsê! Oni te¿ nie wierzyli w pokój i jednoœæ - zobacz, do czego nas doprowadzili! Jednoœæ to jedyny sposób na zapobie¿enie powtórce z rozrywki, ale musi to nast¹piæ ju¿ teraz - zanim inne Krypty bêd¹ mia³y okazjê zebraæ si³y.}
{180}{}{Wydajesz siê byæ trochê zbyt inteligentna jak na tê bandê zombich.}
{181}{}{Chcesz, aby wszyscy zachowywali siê tak, jak ci tam w pokoju? Przecie¿ to jest gorsze od œmierci!}
{182}{}{Jesteœ szalona! To tylko doprowadzi do kolejnej Apokalipsy!}
{183}{}{A dlaczego to w³aœnie Mistrz ma nami rz¹dziæ?}
{184}{}{Nikt nigdy nie zgin¹³ z twojej rêki? Nie w³adasz dostatecznym arsena³em, ¿eby sprawiæ, ¿e ca³e Bractwo Stali zielenieje z zazdroœci? Doœæ tej hipokryzji! Uwa¿asz, ¿e obrona w³asna jest zasadna. Mistrz broni ludzkoœci przed kolejnym atakiem samozniszczenia. To przecie¿ to samo!}
{185}{}{Sk¹d wiesz, ¿e nie istnieje ktoœ lepszy?}
{186}{}{Muszê to przemyœleæ.}
{187}{}{A wiêc holocaust jest s³uszny, pod warunkiem, ¿e prowadzi do uratowania œwiata?}
{188}{}{To bzdury, paniusiu!}
{189}{}{Co ty sobie wyobra¿asz o tym œwiecie? To koszmar!}
{190}{}{Sk¹d wiesz, ¿e nie istnieje ktoœ lepszy?}
{191}{}{Muszê to przemyœleæ.}
{192}{}{Nie. To œwiat, w którym mam prawo do ¿ycia tak, jak chcê.}
{193}{}{¯ycie nie jest proste, siostro. Nigdy nie by³o i nigdy nie bêdzie.}
{194}{}{Szkoda. Ja tam nie przepadam za radiacj¹ i wirusem FEV, ale nie mia³am wyboru. Nie zawsze ¿ycie daje nam to, o czym marzyliœmy. Czasami trzeba pójœæ na kompromis. Albo otworzyæ swój umys³ na niewygodne teorie.}
{195}{}{Dziwne. Jakoœ trudno mi sobie wyobraziæ, jak Mistrz pozwala na to swojej trzódce.}
{196}{}{Kompromis kompromisem, a ludobójstwo ludobójstwem.}
{197}{}{Wynoœ siê st¹d!}
{198}{}{Jedyny interesuj¹cy mnie w chwili obecnej wybór to decyzja, ile pozwolê ci jeszcze ¿yæ.}
{199}{}{Mo¿e bêdê tak inteligentna, ¿e bêdê w stanie pomóc Mistrzowi, gdy obejmie w³adzê. Mo¿e ty te¿! Przy³¹cz siê do nas! Przy³¹cz siê i zmieñ œwiat! Tylko o tym pomyœl - nie proszê o wiele!}
{200}{}{W spo³eczeñstwach zawsze wystêpowa³y trutnie. Zapomnij o nich! S¹ nam potrzebne, ale potrzebujemy te¿ ¿o³nierzy i kilku królowych. Ty mi wygl¹dasz przynajmniej na dobrego ¿o³nierza... Zastanów siê nad tym - bardzo siê przydasz naszej sprawie. Pomó¿ nam. Przemyœl to, co ci mówi³am - tylko tyle!}
{201}{}{Lub mo¿e uda³oby nam siê pokonaæ je, zanim zdo³a³yby siê ufortyfikowaæ. Mo¿e uda³oby siê zjednoczyæ inne Krypty i miasto jednym, szybkim uderzeniem. Œwiat jednoœci nie bêdzie idealny, ale bêdzie mia³ wiêksz¹ szansê utrzymania siê. Pomyœl o tym!}
{202}{}{Znam ich wszystkich. Bractwo Stali i Uczniowie Apokalipsy chc¹ tylko, ¿eby ich zostawiæ w spokoju. Ci z Huba myœl¹, ¿e mog¹ kupiæ ca³y œwiat - co za durnie! Tylko Mistrz ma doœæ si³y, aby zrobiæ to, co trzeba. Pomyœl o tym!}
{203}{}{Mi³o mi to s³yszeæ. Mam nadziejê, ¿e podejmiesz w³aœciw¹ decyzjê.}
{204}{}{Nie. Nie jest s³uszny. Ale to jedyna mo¿liwoœæ, która daje szansê na uratowanie nas na d³u¿sz¹ metê - dlatego jestem z tymi tutaj. Nie ma lepszego sposobu! Pomyœl o tym!}
{205}{}{Naprawdê? Przemyœl to. Naprawdê mocno. Jeœli w dalszym ci¹gu bêdziesz dzia³aæ przeciwko nam, zginiesz. Znasz nasze si³y i wiesz, ¿e to tylko wierzcho³ek góry lodowej. Wielkiej góry! Nie powstrzymasz nas! Jeœli siê jednak do nas przy³¹czysz, mo¿esz kogoœ ocaliæ. Tylko o tym pomyœl!}
{206}{}{Nie. Ale jeœli zobaczê jeszcze kogoœ, kto mi siê spodoba, bêdê im mog³a pomóc. Nikt z tych ludzi nie ma szansy. Wszyscy zgin¹ lub dost¹pi¹ przemiany, jeœli bêd¹ mieli szczêœcie. Ty te¿ mo¿esz mieæ szczêœcie. Przy³¹cz siê do nas. Tylko o tym pomyœl!}
{207}{}{Œwiat nie jest niezmienny. Nigdy nie by³. Jeœli nie zrobimy nic oprócz wznoszenia potê¿nych enklaw, to z czasem jedna z nich stanie siê doœæ potê¿na, aby rozpocz¹æ od nowa Apokalipsê. Przy³¹cz siê do nas i zjednoczmy œwiat, zanim tak siê stanie! Pomyœl o tym!}
{208}{}{To tylko tchórzliwa wymówka, która nic nie rozwi¹zuje. Jeœli coœ nam nie pasuje w naszym ¿yciu, to powinniœmy spróbowaæ je zmieniæ. Jesteœmy to winni sobie samym i naszym potomkom. Myœlisz, ¿e podzielenie siê na wojuj¹ce frakcje pozostawi ten œwiat bez zmian? Pomyœl o tym!}
{209}{}{A mo¿e pod p³aszczykiem ludobójstwa ukrywa siê zbawienie. Mo¿e œwiat nie bêdzie a¿ tak strasznym miejscem, je¿eli ludzie zaakceptuj¹ wizjê Mistrza. Mo¿e znajdziemy sposób, aby ograniczyæ rozlew krwi. Pomyœl o tym!}
{210}{}{W porz¹dku. Jeœli jednak dalej bêdziesz pod¹¿aæ obecn¹ drog¹, czeka ciê œmieræ. Musia³am ciê ostrzec.}
{211}{}{Mo¿esz mnie zabiæ. Umrê, ale to udowodni, ¿e mia³am racjê. Wybór nale¿y do ciebie.}
{212}{}{Przez Apokalipsê! Spójrz, co z nami zrobi³a! Jednoœæ to jedyny sposób na zapobie¿enie powtórce z rozrywki, ale musi nast¹piæ ju¿ teraz - zanim inne Krypty bêd¹ mia³y okazjê zebraæ si³y.}
{213}{}{Wydajesz siê byæ trochê zbyt inteligentna jak na tê bandê zombich.}
{214}{}{Chcesz, aby wszyscy zachowywali siê tak, jak ci tam w pokoju? Przecie¿ to jest gorsze od œmierci!}
{215}{}{Zastanowiê siê nad tym.}
{216}{}{Jesteœ szalona! To tylko doprowadzi do kolejnej Apokalipsy!}
{217}{}{A dlaczego to w³aœnie Mistrz ma nami rz¹dziæ?}
{218}{}{Mnie nie obchodzi ¿adna filozofia, paniusiu. Ja po prostu dobrze zabijam.}
{219}{}{Poniewa¿ jesteœ inteligentn¹ i dzieln¹ osob¹, która bardzo by siê nam przyda³a. Niektóre z naszych postêpków s¹ rzeczywiœcie straszne. Ogólnie jednak to, co robimy jest nie tylko dobre, ale i konieczne dla podtrzymania rasy ludzkiej. Nie opowiadaj siê tak szybko za Wyznawcami. Nawet oni nie wiedz¹ wszystkiego!}
{220}{}{Wydajesz siê byæ trochê zbyt inteligentna jak na tê bandê zombich.}
{221}{}{Chcesz, aby wszyscy zachowywali siê tak, jak ci tam w pokoju? Przecie¿ to jest gorsze od œmierci!}
{222}{}{Zastanowiê siê nad tym.}
{223}{}{Jesteœ szalona! To tylko doprowadzi do kolejnej Apokalipsy!}
{224}{}{A dlaczego to w³aœnie Mistrz ma nami rz¹dziæ?}
{225}{}{Mnie nie obchodzi ¿adna filozofia, paniusiu. Ja po prostu dobrze zabijam.}
{226}{}{Ka¿dy z nas ma do odegrania jak¹œ rolê. Niektórzy z nas to bezmyœlne mu³y, wykonuj¹ce zadania przeznaczone dla g³upków. Niektórzy to myœliciele. Inni - zabójcy. Jest tam miejsce i dla ciebie, jeœli tego chcesz. Przemyœl to!}
{227}{}{Wiele spraw mamy ju¿ zaplanowanych. Najpierw przyby³ Œwiêty P³omieñ, który oczyœci³ œwiat ze z³a. Potem nadszed³ Mistrz. Teraz nadszed³ czas Jednoœci, gdy musimy pokonaæ nierównoœci tego œwiata. Po Jednoœci nadejdzie Pokój. Era Pokoju uzasadnia nasze wysi³ki, stanowi¹c ich cel i przyczynê zarazem.}
{228}{}{Dlaczego osi¹gniêcie pokoju wymaga tak wielu ofiar?}
{229}{}{To brzmi wspaniale. Niech ¿yje Mistrz!}
{230}{}{Czy¿ ogieñ Apokalipsy nie by³ z³em?}
{231}{}{Brzmi jak stek bzdur.}
{232}{}{Z pewnoœci¹. Nerwy to zdrowa emocja. Powstrzymuj¹ nas przed zagl¹daniem w nieodpowiednie miejsca i robieniem g³upot. ¯egnam.}
{233}{}{Nowicjusze szukaj¹ odpowiedzi na pytania. Dlaczego i ty tego teraz nie robisz? ¯egnam.}
{234}{}{Nie wiem. Ludzie wierz¹, ¿e jego duch przebywa wœród tych œcian. Jestem jedn¹ z nich.}
{235}{}{A co ludzie mówi¹ o jego fizycznej postaci?}
{236}{}{Czy¿by uda³o mi siê wyczuæ nutkê sceptycyzmu?}
{237}{}{W ogóle istnieje jakiœ Mistrz, czy to tylko bujda?}
{238}{}{To denerwuj¹co sk¹pa odpowiedŸ.}
{239}{}{Dziêkujê ci, siostro.}
{240}{}{G³ównym Kap³anem Katedry jest Morfeusz. Przebywa w Górnym Sanktuarium, ale nie udziela audiencji. Mo¿esz spróbowaæ przekonaæ Ojca Biczownika, aby siê za tob¹ wstawi³. Znajdziesz go tutaj, na dole.}
{241}{}{Morfeusz? To dobry cz³owiek?}
{242}{}{Dlaczego go nazywaj¹ Biczownikiem?}
{243}{}{A co z Mistrzem?}
{244}{}{Trzeba tu znaæ kogoœ jeszcze?}
{245}{}{Dziêkujê ci, siostro.}
{246}{}{Mo¿e zmienisz pogl¹dy. Albo stracisz ¿ycie. To zale¿y od twojego postêpowania i punktu widzenia. ¯egnam.}
{247}{}{Mamy podobne cele. Zabijasz potwory i bandytów, aby uczyniæ œwiat bezpieczniejszym. My planujemy to samo, tylko na wiêksz¹ skalê.}
{248}{}{Jak du¿¹, konkretnie?}
{249}{}{Kim s¹ potwory i bandyci, których siê zamierzacie pozbyæ?}
{250}{}{Czy to ma coœ wspólnego z tym ca³ym Œwiêtym P³omieniem, o którym wci¹¿ s³yszê?}
{251}{}{Przykro mi paniusiu, ale nie wierzê w ani jedno twoje s³owo.}
{252}{}{Wspaniale. Niech ¿yje Mistrz! Niech ¿yje Œwiêty P³omieñ!}
{253}{}{Pokój, mi³oœæ i Jednoœæ oczywiœcie. A có¿ innego? Ale musisz odkryæ to samodzielnie. ¯egnam.}
{254}{}{Musisz spêdziæ tu kilka tygodni poszcz¹c i medytuj¹c, a potem zwróciæ siê do jednego ze prze³o¿onych. Mo¿esz siê te¿ podj¹æ wykonywania dla nas zadañ.}
{255}{}{Uda³o mi siê zauwa¿yæ kilku waszych w innych miastach...}
{256}{}{Do kogo mam siê zwróciæ w sprawie przy³¹czenia siê?}
{257}{}{Kilka tygodni! To strasznie d³ugo.}
{258}{}{Do którego z prze³o¿onych najlepiej siê zwróciæ?}
{259}{}{Zadania? Na przyk³ad zabijanie waszych wrogów?}
{260}{}{Przepraszam. Przynajmniej mo¿esz uczciwie szukaæ odpuszczenia swoich win. W czym mogê pomóc?}
{261}{}{Ciekawi mnie, o co chodzi w tej ca³ej Katedrze.}
{262}{}{Jak siê mo¿na do was przy³¹czyæ?}
{263}{}{Gdzie znajdê Mistrza?}
{264}{}{Kto tu dowodzi?}
{265}{}{Ej¿e, bez jaj. Nikt nikomu nie pomaga, chyba, ¿e mu siê przystawi spluwê do czo³a!}
{266}{}{Niebezpiecznie jest wpuœciæ do domu wœciek³ego psa tylko dlatego, ¿e siê nie pieni. ¯egnam.}
{267}{}{Musia³ ciê ktoœ d³ugo oczerniaæ, bo ca³e Gruzy opowiadaj¹ horrory z tob¹ w roli g³ównej. Nie mam ochoty sprawdzaæ, czy s¹ oparte na faktach. ¯egnam.}
{268}{}{Ka¿dy wysi³ek ma sw¹ cenê, najwiêkszy nieuchronnie poci¹ga za sob¹ najwiêksze koszty. Obawiam siê, ¿e to jest paradoks pokoju. Materia³ do przemyœleñ. ¯egnam.}
{269}{}{To paradoks. Oczywiœcie, ¿e tak, ale najwiêksze niegodziwoœci mog¹ prowadziæ do wielkiego dobra. Potrzeba tylko inteligencji i odwagi tych, którzy prze¿yli. Materia³ do przemyœleñ. ¯egnam.}
{270}{}{Nie powinno siê oceniaæ ludzi na podstawie wygl¹du. Cel Mistrza jest szlachetny i to mi wystarcza. Nie wiem, co s¹dz¹ inni - ich siê spytaj.}
{271}{}{Mo¿e troszkê. Wizja Mistrza jest tak ambitna i genialna, ¿e chyba mogê sobie pozwoliæ na odrobinê w¹tpliwoœci. Jeœli wp³ynê³am na negatywnie na twoj¹ ocenê sytuacji, to przepraszam. Wygl¹da na to, ¿e po instrukcje musisz siê zwróciæ do kogoœ o silniejszej osobowoœci. ¯egnam.}
{272}{}{Oczywiœcie, ¿e Mistrz istnieje! Dlaczegó¿ by mia³o byæ inaczej? Robimy wiele rzeczy, z niektórych wcale nie jestem dumna, ale nie zajmujemy siê dezinformacj¹. Wizja Pokoju i Jednoœci, jak¹ ma Mistrz jest prawdziwa. ¯egnam.}
{273}{}{W stwierdzeniu 'nie wiem' nie ma nic sk¹pego. ¯egnam pana.}
{274}{}{W stwierdzeniu 'nie wiem' nie ma nic sk¹pego. ¯egnam pani¹.}
{275}{}{Nie ma za co. Niech Mistrz ciê natchnie sw¹ m¹droœci¹.}
{276}{}{Nie ma za co. Niech Mistrz ciê natchnie sw¹ m¹droœci¹.}
{277}{}{Jest inteligentny, a Mistrz mu ufa. To wystarczy. Niech Mistrz ciê natchnie sw¹ m¹droœci¹. ¯egnam.}
{278}{}{Wychowuje dzieci - doœæ surowo. Coœ jeszcze?}
{279}{}{Morfeusz? To dobry cz³owiek?}
{280}{}{Dlaczego pozwala siê Biczownikowi na krzywdzenie dzieci?}
{281}{}{A co z Mistrzem?}
{282}{}{Trzeba tu znaæ kogoœ jeszcze?}
{283}{}{Dziêkujê ci, siostro.}
{284}{}{Nie powiem ci nic, czego ju¿ nie wiesz. Przykro mi.}
{285}{}{Du¿o, z pewnoœci¹. Ale odpowiedzi powinno siê szukaæ samemu, nie wyci¹gaæ je z plotek i insynuacji. ¯egnam.}
{286}{}{Proszê bardzo.}
{287}{}{Proszê bardzo.}
{288}{}{Im wiêkszych, tym lepiej. Na œwiecie panuje chaos. Potrzebny jest porz¹dek, inaczej nie prze¿yjemy. Sprowadzimy ten porz¹dek i nie dopuœcimy, aby potwory krzywdzi³y ludzi, tak, jak to robi³y podczas Apokalipsy. Materia³ do przemyœleñ. ¯egnam.}
{289}{}{Ci, którzy pozwoliliby swoim samolubnym ¿¹dzom stan¹æ na drodze dobra ludzkoœci. To samolubstwo spowodowa³o Apokalipsê. Jeœli œwiat ma prze¿yæ, to musimy wyczyœciæ ludzkie serca z tego szaleñstwa. Materia³ do przemyœleñ. ¯egnam.}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{By³a Diakon Olivier, ale to by³o dawniej... I Ojciec Pinochet - nie, z nim teraz te¿ ju¿ nie mo¿na mówiæ. Niechêtnie wspominam Biczownika, ale tylko on pozosta³. Z pewnoœci¹ znajdziesz jakiœ sposób. Powodzenia.}
{295}{}{Œmieræ to nie zadanie, nawet, gdy jest konieczna. ¯egnam.}
{296}{}{Œmieræ to nie zadanie, nawet, gdy jest konieczna. ¯egnam.}
{297}{}{Sama siê nad tym zastanawia³am. Ale z pewnoœci¹ nie ma podstaw do krytyki. Pomów mo¿e z dzieæmi.}
{298}{}{[Koniec]}
{299}{}{Ja iœæ.}
{300}{}{Kiedyœ trwa³o to krócej, ale Koœció³ prowadzi powa¿ne Krucjaty i jesteœmy chyba bardziej wybredni, jeœli chodzi o rekrutów. Wiara jednak przetrwa, a cierpliwoœæ to zaleta. Powodzenia, przyjacielu.}
{301}{}{Kiedyœ trwa³o to krócej, ale Koœció³ prowadzi powa¿ne Krucjaty i jesteœmy chyba bardziej wybredni, jeœli chodzi o rekrutów. Wiara jednak przetrwa, a cierpliwoœæ to zaleta. Powodzenia, przyjacielu.}
{302}{}{Nie s³ysza³am o ¿adnych planach ponownego przyzwania Œwiêtego P³omienia. By³ œwiêty tylko dlatego, ¿e da³ nam mo¿liwoœæ oczyszczenia œwiata z jego niedoskona³oœci. To nasze czyny uœwiêc¹ ten p³omieñ. Musimy zmieniæ z³o tego œwiata w boskie narzêdzie. Tak jak nasza broñ broni naszego ¿ycia, tak nasze czyny strzeg¹ tego œwiata. ¯egnaj, przyjacielu.}
{303}{}{Nie s³ysza³am o ¿adnych planach ponownego przyzwania Œwiêtego P³omienia. By³ œwiêty tylko dlatego, ¿e da³ nam mo¿liwoœæ oczyszczenia œwiata z jego niedoskona³oœci. To nasze czyny uœwiêc¹ ten p³omieñ. Musimy zmieniæ z³o tego œwiata w boskie narzêdzie. Tak jak nasza broñ broni naszego ¿ycia, tak nasze czyny strzeg¹ tego œwiata. ¯egnaj, przyjacielu.}
{304}{}{S³u¿ymy ludziom na wiele ró¿nych sposobów. Leczymy chorych, karmimy g³odnych, nauczamy m³odych. Jestem z tego dumna. Jeœli uda ci siê dotrzeæ do Ojca Morfeusza, mo¿e on ci powie, jak zaanga¿owaæ siê w nasze projekty. ¯egnaj, przyjacielu.}
{305}{}{S³u¿ymy ludziom na wiele ró¿nych sposobów. Leczymy chorych, karmimy g³odnych, nauczamy m³odych. Jestem z tego dumna. Jeœli uda ci siê dotrzeæ do Ojca Morfeusza, mo¿e on ci powie, jak zaanga¿owaæ siê w nasze projekty. ¯egnaj, przyjacielu.}
{306}{}{Jeœli uda ci siê dotrzeæ do Ojca Morfeusza, mo¿e on ci powie jak zaanga¿owaæ siê w nasze projekty. ¯egnaj, przyjacielu.}
{307}{}{Jeœli uda ci siê dotrzeæ do Ojca Morfeusza, mo¿e on ci powie jak zaanga¿owaæ siê w nasze projekty. ¯egnaj, przyjacielu.}
