{100}{}{Zauwa¿asz cienki drut rozpiêty wszerz korytarza, co pozwala ci go omin¹æ.}
{101}{}{Czujesz potworny ból w nodze. Drut rozpiêty wszerz korytarza rozci¹³ j¹ do koœci.}
{102}{}{Twoja prawa noga jest powa¿nie uszkodzona.}
{103}{}{Twoja lewa noga jest powa¿nie uszkodzona.}
{104}{}{Uda³o ci siê rozbroiæ pu³apkê z drutem, zanim rozwali³a ci rêce.}
{105}{}{Próbujesz zdemontowaæ drut, ale nie mo¿esz go chwyciæ. Wycofujesz siê, zanim ciê rani.}
{106}{}{Próbujesz zdemontowaæ drut, ale nie udaje ci siê to i rani ciê on.}
