{100}{}{Widzisz stra¿nika.}
{101}{}{Witaj, }
{102}{}{. }
{103}{}{Witam. Jak leci?}
{104}{}{Gaaa!}
{105}{}{No có¿, Gaaa! Przykro mi, ¿e nie umiesz siê porozumieæ. Mogliœmy zostaæ przyjació³mi.}
{106}{}{Ouf.}
{107}{}{Nie czujê siê najlepiej. Ktoœ mi ³eb rozwali³ gazrurk¹. By³em u lekarza, ale g³owa wci¹¿ boli. Mam nadziejê, ¿e ktoœ z³apie tego durnia, który mnie uderzy³.}
{108}{}{Dlaczego ten ktoœ to zrobi³?}
{109}{}{Guk.}
{110}{}{Zaatakowano mnie, gdy którejœ nocy zosta³em tu d³u¿ej. Zwykle idê do domu ko³o ósmej, ale wtedy zosta³em d³u¿ej, bo komuœ ukradziono trochê wody i sprawdza³em zapasy. I nagle budzê siê u lekarza z wielkim guzem na g³owie. To co siê tu wyprawia, to szaleñstwo. Nied³ugo ktoœ zginie przez wodê - nie wiem, co mo¿emy na to poradziæ.}
{111}{}{Zobaczê, co siê da zrobiæ.}
{112}{}{Przykro mi. Mam nadziejê, ¿e poczujesz siê lepiej.}
{113}{}{Oto twoja woda.}
{114}{}{Oto twoja dzisiejsza porcja.}
{115}{}{Hej! Co ty wyrabiasz?!?}
{116}{}{Proszê, nie bierz tak du¿o. Te zapasy s¹ nam potrzebne.}
{117}{}{Raporty wysy³asz w systemie komputerowym biblioteki. Musisz wróciæ do Opiekuna, aby skoñczyæ swoje postêpy.}
{118}{}{Dzieñ dobry, }
{119}{}{.}
{120}{}{Czeœæ. Jak leci?}
{121}{}{Co tu robisz?}
{122}{}{Oczywiœcie wszyscy s¹ podenerwowani, ale nie mamy jeszcze zbyt wielu k³opotów. Mam nadziejê, ¿e znajdziesz wkrótce nowy procesor.}
{123}{}{To ja wydajê porcje wody. I pilnujê, aby nikt nie wzi¹³ wiêcej, ni¿ mu siê nale¿y. Nie s¹dzê jednak, ¿ebyœmy mieli z tym zbyt wiele k³opotów.}
{124}{}{Hmm. Tak trzymaj.}
{125}{}{Ty te¿. Mam nadziejê, ¿e wkrótce znajdziesz nowy procesor i wszyscy bêdziemy mogli wróciæ do normalnoœci.}
{126}{}{Mo¿esz braæ, co ci potrzebne, gdy¿ masz tak wa¿ne zadanie, ale nie bierz zbyt wiele. Zbyt du¿o nam nie zosta³o.}
{127}{}{Mogê siê trochê zaopatrzyæ?}
{1000}{}{Porcja}
{1001}{}{Porcje}
{1002}{}{Zapasy}
{1003}{}{Woda}
{1100}{}{Porcje wody wydajê z rana. Nie powinny ci byæ ju¿ potrzebne, skoro opuszczasz Kryptê.}
{1101}{}{Porcje wody wydajê z rana. Nie powinny ci byæ ju¿ potrzebne, skoro opuszczasz Kryptê.}
{1102}{}{Nie zosta³o nam zbyt wiele. Jeœli coœ jest ci potrzebne do wykonania twojej misji, to bierz, tylko nie za wiele.}
{1103}{}{Porcje wody wydajê z rana. Nie powinny ci byæ ju¿ potrzebne, skoro opuszczasz Kryptê.}
