{100}{}{Vracíme se zpátky do Hubu.}
{101}{}{Vracíš se s námi?}
{102}{}{Pøipraven.}
{103}{}{Doufám, že mám dost nábojù.}
{104}{}{Tuhle práci prostì miluju!}

{105}{}{Vyrážíme!}
{106}{}{Hnìte se!}
{107}{}{Všechny jsme je dostali!}
{108}{}{Tak tohle bylo snadný!}
{109}{}{Nevykecávejte se a hnìte zadkama!}
{110}{}{Pøipraven vyrazit?}
{111}{}{Nejsem tu placený za vykecávání.}
{112}{}{Pìknì odporný místo, èéèe!}
{113}{}{Nejsem tu placený za vykecávání.}
{114}{}{Hele hleï si svýho jo?}
{115}{}{Hele hleï si svýho jo?}