# Alchemist: long phrases should be split and require some smooyhing.

{100}{}{Vidíš: Lexe, hlavu nájezdnického klanu Zmije.}
{101}{}{Obrovský chlap, nevalnì se tváøící, zírá na tebe.}
{102}{}{[...Pozvolna se probouzíš a rozhlížíš se kolem sebe. Vidíš neznámé tváøe, tøi stany a nìkolik lidí poblíž. Vypadá to, že se ti vìdomí vrátilo døíve, než ti vybrali kapsy. Tvé oèi se soustøedí na muže stojícího vedle tebe] Oh, náš smolný kupec se probudil.}
{103}{}{[VÍCE]}
{104}{}{Tak jak to bude? Mùžeš nám dát všechny svoje zátky a my tì necháme jít. Nebo si mùžeme zahrát na nebojácné kovboje.}
{105}{}{A kde mám záruku, že odsud odejdu živý, když vám dám peníze?}
{106}{}{Westerny byli vždy v moji zálibì.}
{107}{}{Kovbojové.}
{108}{}{Slovo nájezdníka!}
{109}{}{Myslím, že ti mohu vìøit. Na, vem si to. [Dáváš mu své úspory]}
{110}{}{Takové slovo pro mì nemá žádnou váhu.}
{111}{}{Aha, tvrdá palice jo? To se mi zamlouvá. Myslím, že si s tebou tady chlapy užijou trochu srandy.}
{112}{}{Jestli nevìøíš mému slovu, vìø našim bouchaèkám! Cápek jako ty nemá proti celýmu gangu šanci!}
{113}{}{Tak jinak, to tì radìji zabiju. Jen pro jistotu, aby se to moc nerozneslo. Sbohem.}
{114}{}{Tak je to správnì. Moudré rozhodnutí. Teï mùžeš jít.}

