{100}{}{Vidíš Paladina.}

{101}{}{Okamžitì stùj, cizinèe! Identifikuj se!}

# low IQ
{102}{}{Já }
{103}{}{.}

{104}{}{Jmenuji se }
{105}{}{. Co se to tu stalo?}
{106}{}{Mé jméno není dùležité.}

# low IQ
{107}{}{Dávej si pozor, }
{108}{}{, mùžeš se tu zranit. Armáda zlých mutantù sem pøišla a udìlala velký BUM. Vidíš?}
{109}{}{Ah-hm.}
{110}{}{Vidíš. Takže jdi radìji jinam. Tady NE bezpeèný.}
{111}{}{Já jít.}

{112}{}{Mutanti. Byla to fakt velká armáda. Pøišli, všechny pozabíjeli, vzali co mohli a odpálili to tu.}
{113}{}{A jak se ti to podaøilo pøežít?}
{114}{}{Vrátil jsem se z daleké hlídky. Když jsem pøišel, bylo už dávno po všem. Už jsem nemohl nic udìlat. Tak jsem se ukryl a pozoroval je.}
{115}{}{A to jsi se bál cokoliv udìlat?}
{116}{}{Nikdo jiný to tu nepøežil?}
{117}{}{Hele, nejsem zrovna nejodvážnìjší èlen Bratrsva, ale taky nejsem idiot. Opravdu nebylo nic, co bych mohl udìlat.}
{118}{}{Zbabìlèe. Tak si tu teï zùstaò a hlídej tyhle ruiny. Já radìji jdu a zabiju nìjaké ty tvoje mutanty.}
{119}{}{Promiò. Pøežil ten masakr ještì nìkdo jiný?}
{120}{}{Nìkolik hlídkových skupin, pár paladinù v terénu... prostì pøíliš málo na to, abychom nìco zmohli. Bratrstvo oceli je v podstatì mrtvé. Já už tu asi zùstanu, pokusím se dát dohromady co nejvíce pøeživších a povím jim co se tu stalo. A potom... vlastnì ještì nevím co potom. Ani jsem ještì nemìl èas nad tím pøemýšlet.}
{121}{}{Tomu rozumím. Drž se tu, Paladine, už musím jít.}
{122}{}{Sbohem, }
{123}{}{. Pokud na svých cestách narazíš na nìjaké èleny Bratrstva, øekni jim, co se tu stalo.}

{124}{}{Okamžitì stùj... Aha, to jsi ty, }
{125}{}{.}
{126}{}{Ah-hm.}
{127}{}{Ano, to jsem já. Co se tu stalo?}

{130}{}{Sbohem, }
{131}{}{. Pokud narazíš na nìjaké mé bratry, povìz jim, co se tu stalo.}
{132}{}{Jasnì. Teï už ale vážnì musím jít.}

{133}{}{Tak už radìji bìž, nemám ti už co øíci.}

{150}{}{Paladin tì ignoruje. Vypadá to, že je hluboce zamyšlený.}
