{100}{}{Vidíš: Kyla.}
{101}{}{Tak jak to šlape, èloveèe? Poøád po svıch... Není to u únavnı? Moná je naèase popøemıšlet o super novıch kolech na cesty,hm? Utratíš nìjakı ty peníze?}
{102}{}{Jak se mám? Nebylo to lepší! A vánì tu máš pro mì takovou sadu kol? Peníze nejsou problém.}
{103}{}{Moná, e kdy tì trošku fiknu, nebude to zadarmo?}
{104}{}{To je dobrá otázka. Vypadá to, e se na tebe pozdìji obrátím.}
{105}{}{Hmmm... No, nejsem si jistej. Uvítal bych bohatšího kupce. Poslouchej, co takhle se vrátit, a budeš mít sebou víc zátek?}
{106}{}{Vìø mi, kámoš jede PRAVEJ kšeft. A øekl bych, e je jedinej, kdo ti mùe v Pustinì prodat auto. To místo není odtud tak daleko. Je to tak den chùze odtud. Ten tıpek pouívá vlastní barák jako gará... 400 zátek by mi mohlo staèit, abych ti ukázal cestu.}
{107}{}{Platí. Tak mì vem k tomu tvımu kámošovi a já u se o zbytek postarám.}
{108}{}{Promiò, Kyle. Mám na práci dùleitìjší vìci.}
{109}{}{Tak jo, vezmu tì tam. Cokoliv pro poøádnıho zákazníka, cokoliv! Pojï za mnou. [bere si od tebe 400 zátek]}
{110}{}{Tušil jsem, e vycouváš. Kadej se bojí cestovat s tolika penìzma. Nicménì mùj kámoš nájezdník ti s tím pomùe! [Zaène ti docházet, e tu nìco nesedí, ale v tu chvíli dostaneš prudkı kopanec do hlavy a upadáš do bezvìdomí. Poslední co cítíš je, e tì nìkam táhnou...]}
{111}{}{Tak hele, ty špíno. Ztra se. Ty tvoje hrozby jsou smìšnı.}
{112}{}{Asi bych se mìl poohlédnout po více vhodném zákazníkovi.}
