##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
##      (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{火箭}
{200}{}{电浆手榴弹}
{300}{}{爆炸}
{400}{}{血}
{500}{}{不能穿越区域}
{501}{}{}
{600}{}{Knife}
{700}{}{Spear}
{800}{}{电磁脉冲爆炸}
{900}{}{激光爆破}
{1000}{}{电浆爆破}
{1100}{}{爆炸}
{1200}{}{涡旋障碍}
{1300}{}{电矢}
{1400}{}{爆炸}
{1500}{}{爆炸}
{1600}{}{出入口通道}
{1700}{}{出入口通道}
{1800}{}{出入口通道}
{1900}{}{出入口通道}
{2000}{}{出入口通道}
{2100}{}{出入口通道}
{2200}{}{出入口通道}
{2300}{}{出入口通道}
{2400}{}{闪光弹}
{2500}{}{手榴弹}
{2600}{}{石头}
{2700}{}{爆炸}
{2800}{}{爆炸}
{2900}{}{爆炸}
{3000}{}{莫洛托夫酒}
{3100}{}{出入口通道}
{3200}{}{出入口通道}
{3300}{}{出入口通道}
{3400}{}{出入口通道}
{3500}{}{出入口通道}
{3600}{}{出入口通道}
{3700}{}{出入口通道}
{3800}{}{出入口通道}
{3900}{}{出入口通道}
{4000}{}{出入口通道}
{4100}{}{出入口通道}
{4200}{}{出入口通道}
{4300}{}{出入口通道}
{4400}{}{出入口通道}
{4500}{}{出入口通道}
{4600}{}{出入口通道}
