{100}{}{A robbanás lezárta az alagutat!}
{101}{}{Lerakod a robbanóanyagot, ami rögtön felrobban!}
{102}{}{The explosion just makes the hole larger. It is impossible to close it now.}
{103}{}{A robbanóanyag sikeres használatáért tapasztalati pontot kaptál.}
