{100}{}{This bookshelf is filled with religious and philosophical books. It's also very dusty.}
{101}{}{You take a book down, examine it, and put it back on the shelf. The shelf itself seems very sturdy.}
{102}{}{Találtál egy elrejtett reteszt.}
{103}{}{Ez nem csinál semmit.}
{104}{}{A könyvespol melletti falrész csendben félresiklik.}
{105}{}{Ügyetlenkedsz egy darabig a könyvespolccal, de nem jutsz semmire..}
{200}{}{A könyvespolc tele van vallásos és filozófiai témájú könyvekkel.}
{201}{}{A retesz az istennek nem akar mozdulni.}
