{100}{}{Egy fürkészõ tekintetû férfit látsz.}
{101}{}{Ez a férfi Michael.}
{102}{}{Helló, nem hiszem, hogy láttalak már itt korábban. Segíthetek valamiben?}
{103}{}{Üdv, tehetek érted valamit?}
{104}{}{Tudnál valami használhatót mondani a Csontteleprõl?}
{105}{}{Ki vagy?}
{106}{}{Miért éltek ti itt?}
{107}{}{Semmit, kösz.}
{108}{}{Persze. Dél felé megtalálod Adytumot, észak-keleti irányban ott vannak a Fegyverkészítõk, viszont keresztül kell magad verekedni a Halálkarmokon, ha oda akarsz jutni. Nyugatra megtalálod az Apokalipszis Tanítványait, messzebb délen pedig úgy hallottam, van valami templom is.}
{109}{}{Michael vagyok. A feleségem Christine, és én Pengésekként élünk itt és ott segítünk, ahol tudunk.}
{110}{}{Nem olyan rossz, mint amilyennek látszik. A Rendfenntartók és a Halálkarmok szoktak ugyan okozni problémákat, de Razor, a vezetõnk nagyon sokat segített az elmúlt hónapok során. A legutóbbi idõkben pedig MacRae volt az, aki számos védelmi fogásra tanított meg bennünket.}
{111}{}{Köszönjük, hogy segítettél kiirtani a Rendfenntartókat Adytumból. Fogadd el ezt a csekélységet cserébe, talán még jól jöhetnek az utazásod során.}
{112}{}{Semmiség az egész. Kösz az ajándékért.}
{113}{}{Nem tesz semmit, de nyugodtan tartsd meg ezeket. Nektek biztos nagyobb szükségetek van rá.}
{114}{}{Ragaszkodom hozzá.}
{115}{}{(He hands you some stimpaks and some caps.)}
{116}{}{Üdv! Jó szerencsét kívánok az utazásodhoz!}
