{100}{}{Egy kisgyereket látsz.}
{101}{}{Szia!}
{102}{}{Helló.}
{103}{}{Hol vannak a szüleid?}
{104}{}{Örf.}
{105}{}{Nem to'm. Valahol itt a közelben.}
{106}{}{Vicces vagy!}
{107}{}{Hé, meg akarsz ölni valakit?}
{108}{}{Igen.}
{109}{}{Dehogy!}
{110}{}{Örf.}
{111}{}{El fogom mondani a mamámnak!}
{112}{}{Akkor nem kéne ilyen fegyvereket hordanod itt.}

{980}{}{He?}
{981}{}{I dunno. Ask mommy.}
{982}{}{Kérdezd a papát!}

{1000}{}{Halalkarom}
{1001}{}{Fosztogato}
{1002}{}{Roncsvaros}
{1003}{}{Brahmin}
{1004}{}{Csip}
{1005}{}{Kereskedo}
{1006}{}{Khan}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Hub}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Rendorseg}
{1015}{}{Karavan}
{1016}{}{Traders}
{1017}{}{Gyermek}
{1018}{}{Nekropolisz}
{1019}{}{Spot}
{1020}{}{Testveriseg}
{1021}{}{Csonttelep}
{1022}{}{Torony}
{1023}{}{Város}
{1024}{}{Belvaros}
{1025}{}{Magaslat}
{1026}{}{The Boneyard}
{1027}{}{L.A. Boneyard}

{1100}{}{Jaj! Rémes szörnyeteg!}
{1101}{}{Csúnya rosszfiúk!}
{1102}{}{I dunno.}
{1103}{}{Büdös állat.}
{1104}{}{Kérdezd a mamát!}
{1105}{}{Fura tengerészdalokat nyomnak.}
{1106}{}{Csúnya rosszfiúk!}
{1107}{}{Rossz ember.}
{1108}{}{Nem mondom meeeg...}
{1109}{}{Nagy város.}
{1110}{}{Nem akarok beszélni róla...}
{1111}{}{Nem, nem fogok beszélni róla.}
{1112}{}{Mami nem szeretné, ha beszélnék róla.}
{1113}{}{A papa szerint furi egy alak.}
{1114}{}{Hatalmas fickók...}
{1115}{}{Vannak nekik azok a büdi állatok, amik húzzák õket.}
{1116}{}{Jó emberek, szoktak adni cukorkát.}
{1117}{}{Nem szeretnek bújócskázni.}
{1118}{}{Félelmetes hely.}
{1119}{}{Undi hely.}
{1120}{}{Félelmetes hely.}
{1121}{}{Félelmetes hely.}
{1122}{}{Mami nem engedi, hogy ott játsszunk.}
{1123}{}{A papa folyton azt akarja, hogy ott játsszunk}
{1124}{}{Nagy darab népek laknak ott.}
{1125}{}{Nagy darab népek laknak ott.}
{1126}{}{Scary place.}
{1127}{}{Scary place.}
