{100}{}{Õ Cleo.}
{101}{}{Nem vonulunk vissza, nem adjuk meg magunkat, haver.}
{102}{}{Nem vonulunk vissza, nem adjuk meg magunkat, kislány.}
{103}{}{Nem éppen menni készültél? Húzás innen!}
{104}{}{Mit akarsz?}
{105}{}{Mesélj nekem Loxleyrõl!}
{106}{}{Mesélj nekem Jasmine-ról!}
{107}{}{Mesélj nekem a Tolvajok Körérõl!}
{108}{}{Mesélj nekem Deckerrõl!}
{109}{}{Mesélj nekem az eltûnt karavánokról!}
{110}{}{Üdv!}
{111}{}{Öm, ögh!}
{112}{}{Hé! Mi történik itt?}
{113}{}{Mesélj nekem Loxleyrõl!}
{114}{}{Mesélj nekem Jasmine-ról!}
{115}{}{Mesélj nekem a Tolvajok Körérõl!}
{116}{}{Mesélj nekem Deckerrõl!}
{117}{}{Mesélj nekem az eltûnt karavánokról!}
{118}{}{Mesélj nekem az eltûnt karavánokról!}
{119}{}{Üdv!}
{120}{}{Öm, ögh!}
{121}{}{Õ a fõnök. Mi egyebet kéne róla tudni?}
{122}{}{Mesélj nekem Jasmine-ról!}
{123}{}{Mesélj nekem a Tolvajok Körérõl!}
{124}{}{Mesélj nekem Deckerrõl!}
{125}{}{Mesélj nekem az eltûnt karavánokról!}
{126}{}{Üdv!}
{127}{}{Öm, ögh!}
{128}{}{Õ a fõnökök asszisztense. Nem rossz kis csaj.}
{129}{}{Mesélj nekem Loxleyrõl!}
{130}{}{Mesélj nekem Jasmine-ról!}
{131}{}{Mesélj nekem a Tolvajok Körérõl!}
{132}{}{Mesélj nekem Deckerrõl!}
{133}{}{Mesélj nekem az eltûnt karavánokról!}
{134}{}{Üdv!}
{135}{}{Öm, ögh!}
{136}{}{Ha elég szerencsés vagy, még a végén közénk tartozhatsz. Otthon érezheted magad, mint egy régi bútordarab...}
{137}{}{Mesélj nekem Loxleyrõl!}
{138}{}{Mesélj nekem Jasmine-ról!}
{139}{}{Mesélj nekem Deckerrõl!}
{140}{}{Mesélj nekem az eltûnt karavánokról!}
{141}{}{Üdv!}
{142}{}{Öm, ögh!}
{143}{}{Jó társaságban nem beszélünk Mr. Deckerrõl.}
{144}{}{Mesélj nekem Loxleyrõl!}
{145}{}{Mesélj nekem Jasmine-ról!}
{146}{}{Mesélj nekem a Tolvajok Körérõl!}
{147}{}{Mesélj nekem az eltûnt karavánokról!}
{148}{}{Üdv!}
{149}{}{Öm, ögh!}
{150}{}{Ehhez nekünk semmi közünk!}
{151}{}{Mesélj nekem Loxleyrõl!}
{152}{}{Mesélj nekem Jasmine-ról!}
{153}{}{Mesélj nekem a Tolvajok Körérõl!}
{154}{}{Mesélj nekem Deckerrõl!}
{155}{}{Üdv!}
{156}{}{Öm, ögh!}
{157}{}{Köszöngess magadnak!}
{158}{}{Egyáltalán miért szólítasz meg embereket, félnótás?}
{159}{}{Nagyszerû vezetõ. Mindent megtesz, hogy összehozza a megfelelõ embereket, és egyben tartsa a Hubot. Nyilván egy kisebb összegért.}
{160}{}{Mesélj nekem Jasmine-ról!}
{161}{}{Mesélj nekem a Tolvajok Körérõl!}
{162}{}{Mesélj nekem Deckerrõl!}
{163}{}{Mesélj nekem az eltûnt karavánokról!}
{164}{}{Mesélj nekem az eltûnt karavánokról!}
{165}{}{Üdv!}
{166}{}{Öm, ögh!}
{167}{}{Egyszerre munka és kaland. Segítesz a szegényeken, kockáztatod az életedet és mindig új, érdekes fazonokkal találkozol. Mi lennénk azok, a jófiúk!}
{168}{}{Mesélj nekem Loxleyrõl!}
{169}{}{Mesélj nekem Jasmine-ról!}
{170}{}{Mesélj nekem Deckerrõl!}
{171}{}{Mesélj nekem az eltûnt karavánokról!}
{172}{}{Mesélj nekem az eltûnt karavánokról!}
{173}{}{Üdv!}
{174}{}{Öm, ögh!}
{175}{}{Volt egy barátom, aki vele dolgozott régen. Amikor rosszra fordultak a dolgok, visszaszaladt Deckerhez erõsítésért. Decker hülyének nézte, és példát statuálva rajta, lobotomizálta. Errefelé nemigen kedveljük Deckert.}
{176}{}{Miféle pletykákat akarsz hallani? A Vízkereskedõk játszogatnak. Decker szorongatja a kereskedõket az erõsebb védelem miatt. A Katedrális Gyermekei feláldozták az istenüknek. A Halálkarmok megették. Ilyesmit? A pletykák nem érnek semmit. A világ tele van pletykákkal meg gyanakvással, az igazság meg sehol. Keresd a tényeket, ne a kitalációkat! Amúgy miért kérdezed? Voltak barátaid a karavánosok között?}
{177}{}{Nem akarok beszélni a dolgaimról.}
{178}{}{Megigértem egy barátomnak, hogy utánanézek.}
{179}{}{A városomnak vízre van szüksége, és nem nagy luxus lenne részemrõl, ha engedném, hogy a karavánok csak úgy eltûnjenek.}
{180}{}{Igen, volt egy barátom.}
{181}{}{Remek. Nekem is vannak titkaim. Jó szerencsét, barátom!}
{182}{}{Bocs, de ennél többet nem segíthetek. Ja, és még arról is beszélnek, hogy érkezett egy hajó a világûrbõl. Szerintem valaki túl sokat játszott Rufus idióta játékaival.}
{183}{}{Csakugyan? Hova valósi vagy?}
{184}{}{Shady Sands-bõl jövök.}
{185}{}{Egy Shady Sands-tõl északra esõ helyrõl érkeztem.}
{186}{}{A 13-as Menedékbõl származom.}
{187}{}{Ide is, oda is. Mindenféle feladatokat hajtok vére, amik egy idõre odakötnek valahova.}
{188}{}{Sajnálattal hallom ezt. Én is elvesztettem néhány remek barátot, némelyikük rosszabbul járt, mintha csak simán meghalt volna... inkább nem mennék bele.}
{189}{}{Nem beszéltünk mi már errõl? Eléggé egy téma körül forog az agyad.}
{190}{}{Ha szereted a homokot, nem rossz hely. Egy kicsit túl száraz és kihalt számomra, viszont nem kell aggódnod a bóklászó Radskorpióktól. Persze nekünk is megvannak a saját bestiáink.}
{191}{}{Valami Menedékbõl jöttél? Na, tûnés innen! Ne akard, hogy kétszer mondjam!}
{192}{}{Nem irigyellek. Persze ha nevet szerzel magadnak, egyike lehetsz a pusztaság harcos legendáiknak, mint Magnum Tom Goddard vagy Scorpion Joe Cornelius. Na, barátom, az a valami!}
