{100}{}{Ez a nõ Dan felesége.}
{101}{}{Senkivel nem beszélhetek, kérlek keresd fel a férjemet!}
{102}{}{Elnézésed kérem, de beszélj inkább a férjemmel!}
{103}{}{Te szörnyeteg, miért tetted ezt? Megöldted az én Dannymet!}
{104}{}{Te szörnyeteg, miért tetted ezt? Megöldted az én Dannymet!}
{105}{}{Ez itt Dan síró felesége.}
