{100}{}{Ez az ember Decker egyik õre.}
{101}{}{A fõnökkel kéne beszélned.}
{102}{}{Jobb lesz, ha a mi oldalunkon maradsz.}
{103}{}{Szemmel tartunk ám!}
{104}{}{A fegyveredhez hozzá se érj!}
{105}{}{Ha csak rosszul nézel rá, meghalsz!}
{106}{}{Figyelj oda!}
{107}{}{Megadom magam!}
{108}{}{Amúgy sem szerettem sose dolgozni annak a Decker fiúnak.}
{109}{}{Most, hogy Decker és Kane jobblétre szenderült, átveszem a hatalmat!}
{110}{}{Mostantól jobb lesz, ha elõvigyázatos leszel a Hubban. Személyesen tartalak szemmel.}
