{100}{}{You see: Snake, a member of the Blades.}
{101}{}{You see: Dolgan, a member of the Blades.}
{102}{}{}
{103}{}{}
{104}{}{Ez itt a Pengések egyike.}
{105}{}{Ez itt a Pengések egyike.}
{106}{}{Szerinted õ Books.}
{107}{}{Szerinted õ Scars.}
{108}{}{Szerinted õ Gunner.}
{109}{}{Szerinted õ Twitch.}
{110}{}{Szerinted õ Hammer.}
{111}{}{Szerinted õ Razor.}
{112}{}{Get lost! This is for real fighters only.}
{113}{}{So, you think you can take on the Regulator wimps? Here, I'll teach you how to use that blade.}
{114}{}{You seem to have gotten better. Now go kick Caleb's butt into next year for me.}
{115}{}{Jó munka volt szétgyakni a Hasfelmetszõket. Mit tehetek érted?}
{116}{}{Tudsz még tanítani egy két fogást a pengével?}
{117}{}{How can I get through to the Gun Runners?}
{118}{}{Semmit, köszi.}
{119}{}{Persze. Viszont a nap nagy részét el fogja venni. Még így is érdekel?}
{120}{}{Érdekel.}
{121}{}{Inkább ne.}
{122}{}{Tessék. Valamennyit sikerült fejlõdnöd. Legyen szerencséd!}
{123}{}{Hogyne! Gyere csak vissza, ha további gyakorlásra van szükséged.}
{124}{}{Úgy tûnik, egy idiótát engedtünk közénk. Na, ha be akarsz jutni hozzájuk, van egy kis átjáró az árkukon. Keresd meg, és rohanj, mint állat! Talán még sikerülhet is átjutnod...}
{125}{}{Kösz.}
