{100}{}{Õ Dugan, a Pengések Nuka-Cola függõ tagja.}
{101}{}{Egy nagyon magas, vékony, szemüveges fickót látsz. Az egyik kezében egy üveg Nuka-Colát szorongat.}
{102}{}{Igen?}
{103}{}{Csak épp körbenézek, köszi.}
{104}{}{Mit csinálsz te itt?}
{105}{}{Milyen a hozzáállásod a Nuka-Colához?}
{106}{}{Ki itt a vezetõ?}
{107}{}{Ah, vedd úgy, hogy nem is szóltam.}
{108}{}{Bah, Cola, jó?}
{109}{}{Na, akkor ne fecséreld az idõmet!}
{110}{}{Sok nagy tanulságot vontam le az életet illetõen, és segítek a Pengéseknek, hogy megértsék a Nuka-Cola igazi jelentõségét.}
{111}{}{Mi olyan jó a Nuka-Colában?}
{112}{}{Ez minden? Ettõl nemigen lesz jobb az élete senkinek.}
{113}{}{Mennyit iszol abból a vacakból?}
{114}{}{Kérdezhetek valami mást?}
{115}{}{Ah, oké. Késõbb találkozunk.}
{116}{}{Ez az élet esszenciája... Ami azt illeti, ha nem iszom óránként egyet, rámjön a fejfájás.}
{117}{}{So? (He raises his eyebrows at you.)}
{118}{}{Körülbelül 5 litert naponta.}
{119}{}{Razor az a nõ, akivel beszéned kell.}
{120}{}{Én vagyok a leglököttebb ember, akivel valaha találkoztam... öö, téged leszámítva. Na, tûnés innen!}
{121}{}{Megint kell egy Nuka-Cola!}
{122}{}{Miért hullik a hajam?...}
{123}{}{Szénsav, Karamell színezék, Aspartame, Foszforsav, Kálium Benzoát (Az íz megtartása miatt), Természetes ízesítõk, Citromsav, Koffein.}
{124}{}{Kár, hogy elfogyott a diétás kóla.}
{125}{}{Hova lettek azok az alacsony nõk?}
