{100}{}{You see Fire, a member of the Blades.}
{101}{}{}
{102}{}{}
{103}{}{A Pengések egyik tagját látod.}
{104}{}{A Pengések egyik tagját látod.}
{105}{}{Szerinted õ Books.}
{106}{}{Szerinted õ Scars.}
{107}{}{Szerinted õ Gunner.}
{108}{}{Szerinted õ Twitch.}
{109}{}{Szerinted õ Hammer.}
{110}{}{Szerinted õ Razor.}
{111}{}{Na, mit akarsz, gyökér?}
{112}{}{Ööö.}
{113}{}{Pengés akarok lenni.}
{114}{}{Mibe kerülne nekem, ha békét akarnék kicsiholni köztetek és Adytum között?}
{115}{}{This! [you slap him]}
{116}{}{Semmit. Bocs, hogy zavartalak.}
{117}{}{Csak átvizsgálom ezt a helyet itt.}
{118}{}{Great, another idiot. You sound like a Ripper.}
{119}{}{Rrrrr.}
{120}{}{Arrrr.}
{121}{}{Arrúúú?}
{122}{}{Te sem nagyon komálod õket? Talán kaphatnál tõlünk egy kis "munkát".}
{123}{}{Urroo.}
{124}{}{Un nah.}
{125}{}{Oké, beszélj a fõluvnyával! Razortól majd megkapod a fejtágítást, mit kell csinálni.}
{126}{}{Hülye is vagy, hurka is vagy! Most rögtön bevégzem szánalmas életed!}
{127}{}{Szóval Hasfelmetszõ vagy! Sajnálattal hallom, mindig tudtam, hogy hülyék vagytok. Na, jóccakát!}
{128}{}{A Hasfelmetszõk. Azok a korcsok a város másik felében. Mindegy. Amúgy is túl hülye vagy, hogy akármit is felfogj.}
{129}{}{Pengés akarsz lenni? Jó szerencsét hozzá! Ha megtalálod Razor-t, beszélj vele errõl! Talán megengedi, hogy beugorj.}
{130}{}{Oké, kösz.}
{131}{}{Akkor nem akarok beállni!}
{132}{}{Mit értesz azalatt, hogy "beugrani"?}
{133}{}{Nem tudsz csak egyszerûen bevenni Pengésnek?}
{134}{}{Anyád nemigen akarhatott téged, és mi sem kérünk belõled.}
{135}{}{Egyszerû. Valaki meg kell ölnöd ahhoz, hogy bekerülj hozzánk. Õ majd elmondja neked, kit kell eltenni láb alól.}
{136}{}{Oké, kösz.}
{137}{}{Áh, felejtsük el. Nem akarok a hülye bandátok tagja lenni.}
{138}{}{Nem. Nekem nem áll módomban. Nem én vagyok a vezetõ. Én csak Razor keze alá dolgozom.}
{139}{}{Egyszerû. Mészárold le az ellenségeinket, utána békén hagyjuk Adytumot!}
{140}{}{Kik az ellenségeitek?}
{141}{}{Ez méltányosan hangzik. Will you give me proof of this?}
{142}{}{A harc nem helyes megoldás! Nem csinálok ilyet!}
{143}{}{The Regulators. They rule Adytum. They ain't stupid and are very dangerous.}
{144}{}{Okay, I'll kill the Regulators.}
{145}{}{Vedd úgy, hogy nem is szóltam.}
{146}{}{Ha ilyesmiben töröd a fejed, nem ártana szólni Razor-nek elõtte. Különben a fejed veszi, mielõtt kitennéd innen a lábad.}
{147}{}{Ahogy jónak látod!. Minden jót!}
{148}{}{Nem én kötöm az üzleteket. Én csak ajánlatokat teszek. Ha üzletet akarsz, beszélj Razor-rel!}
{149}{}{Akkor ha most megöllek, sokévnyi szenvedéstõl szabadít me téged, igaz?}
{150}{}{Akkor ezt vizsgáld át!}
{151}{}{Ha még akarsz élni, tûnés innen!}
{152}{}{Csendesebben! Megpróbálunk odaosonni a Hasfelmetszõkhöz.}
{153}{}{Ha van vér a pucádban, eridj Razor-höz! Mindig benne van egy kis balhéban. Egyéb esetben tûnj innen!}
{154}{}{Hela-hela, tesó!}
