{100}{}{Egy szerencsejátékost látsz.}
{101}{}{Fenébe! Nagyon döcögõs most a játék!}
{102}{}{Nem akarok semmilyen balhét veled.}
{103}{}{Fegyver van nála!}
{104}{}{Fegyver van nála!}
{105}{}{Óh, hát te vagy az.}
{106}{}{Sok rossz dolgot hallottam rólad ám. Nem semmi!}
{107}{}{Nem megy a szekér, mi?}
{108}{}{Szörnyû vagy! Megölted azokat a kölyköket. Nem tudom elhinni.}
{109}{}{Hallottam, hogy fejvadászok járnak a nyomodban. Csak nem õket is megölted?}
{110}{}{Ne szólj hozzám!}
{111}{}{Anyám, kinyírtad a Polgármestert?}
{112}{}{Amikor Killian még élt, nem szerettem ezt a helyet. Most már semmi gond vele.}
{113}{}{Menj innen!}
{114}{}{Mi az ábra? Nálam minden okés.}
{115}{}{Mi az ábra? Nálam minden okés.}
{116}{}{Hagyj békén! Nyerésben vagyok!}
{117}{}{Azok a nyerõgépek nekem dolgoznak, bébi.}
{118}{}{Aggy má' valamit innom, töki!}
{119}{}{Grrr! Ez a hely tök szívás!}
{120}{}{Gyártom a nagy zsét, mint gép.}
