{100}{}{Megállni!}
{101}{}{Meghalsz, emberfatty!}
{102}{}{Halálig!}
{103}{}{Megfizetsz a bûneidért!}
{104}{}{Szétzúzlak!}
{105}{}{Örökké éljen az Egység!}
{106}{}{A Mesterért!}
{107}{}{Itt nem szabad fegyvert hordani, kis barátom. Tisztázd magad!}
{108}{}{Itt nem szabad fegyvert hordani, kislányka. Tisztázd magad!}
{109}{}{Hngg.}
{110}{}{Semmi gond, itt dolgozom.}
{111}{}{Semmi gond, van engedélyem.}
{112}{}{A Hadnagy engedélyével hordok fegyvert.}
{113}{}{Miféle árulás ez már?!}
{114}{}{Then show me your pass.}
{115}{}{Öö, sajnos a másik ruhámban hagytam.}
{116}{}{Itt van ni, a fegyverem csövére van biggyesztve.}
{117}{}{Siess akkor a munkáddal! Amúgy jobb, ha tudatosítod magadban, hogy szemmel tartalak.}
{118}{}{Igen, kiskoma. Mit szeretnél tõlem?}
{119}{}{Igen, kislány. Mit szeretnél tõlem?}
{120}{}{Hng!}
{121}{}{Hmm, hol találom azt a Mester nevû egyént?}
{122}{}{Magasztald az Egységet, testvér!}
{123}{}{Nem az én dolgom, hogy az Egység útjára tereljelek. Távozz!}
{124}{}{Egyértelmû, hogy hitetlen kutya vagy! Megfizetsz a bûneidért!}
{125}{}{Helyben. Miért kérded?}
{126}{}{Ööö... csak úgy...}
{127}{}{Úgy picsán fogom rúgni, hogy... ööö... attól koldul!}
{128}{}{Miféle kérdésrõl beszélsz? Azt találtam mondani: "Azt kívánom, hogy a Mester mellett legyél!"}
{129}{}{Sértegetsz? Halál rád!}
{130}{}{Magasztald az Egységet!}
{131}{}{Úgy tûnik nekem, magad sem hiszed el, amit mondasz. Igazam lehet? Vagy letértél a jóság útjáról?}
{132}{}{A hangom remegését félelemnek hiszed, pedig valójában megfázástól van.}
{133}{}{Szerintem a magadfajták sorsa meg van pecsételve. Hadd bizonyítsam be néhány barátommal...}
{134}{}{Amikor közénk tartozol majd, nem fogsz félni semmiségektõl. Szívódj fel!}
{135}{}{Most meg mit akarsz? Nem érek rá csevegni veled.}
{136}{}{Labbo!}
{137}{}{Engem pedig zavar, hogy még mindig életben vagy... Készülj a halálra!}
{138}{}{Semmit, bocs.}
{139}{}{Magasztald az Egységet, testvér!}
{140}{}{Le sem tagadhatnád, hogy behatoló vagy!}
{141}{}{Tûnj a szemem elõl!}
{142}{}{Nincs idõm rád. Ne piszkálj!}
{200}{}{Egy Szupermutáns õrmestert látsz.}
{201}{}{Hé, ez itt nagyon úgy néz ki, mint egy atombomba. Miért van itt?}
{202}{}{Ez a Mesterünk utolsó ütõkártyája. Ha találunk egy legyõzhetetlen ellenséget, akkor bevetjük majd ellene. Mondjuk erõsen kétlem, hogy ez valaha is megtörténik. Még a mi Mesterünk is ódzkodik attól, hogy az atom félelmetes ereje újra elszabaduljon!}
{203}{}{Oké, kösz.}
{204}{}{Mûködik amúgy?}
{205}{}{Semmi gond. Most viszont maradj csendben! Ahhoz, hogy hatékonyan õrizhessem ezt a berendezést, nyugalomra van szükség itt.}
{206}{}{Persze, hogy mûködik! Rendszeresen karbantartjuk, bármikor bevethetõ. Az Egységet nem lehet eltiporni!}
{207}{}{Ah, kösz.}
{208}{}{Nem aggódtok, hogy valami rosszindulatú egyén belopódzik ide, és beindítja a bombát?}
{209}{}{Nem. Azért vagyunk itt mi, hogy megvédjük a behatolóktól. Anélkül, hogy észrevennénk, senki nem lenne képes megközelíteni. Ja, és egy Élesítõ Kulcs is kell hozzá, amit teljesen máshol tartanak.}
{210}{}{Hát igen, ebben van ráció. Kösz.}
{211}{}{A biztonságérzetem azt mondja, hogy nem ártana tudnom, merre van az a kulcs... Meg tudnád mondani?}
{212}{}{Persze-persze... A Hadnagy magánál tartja. A Katonai Bázison van, ide nem nagyon jön. Így nem lehet csak úgy felrobbantani a mi szeretett Mesterünk alatt.}
{213}{}{Kösz, hogy feltarthattalak.}
{214}{}{[A termetes mutáns felhúzza bozontos szemöldökét és rádbámul néhány pillanatig...] Azt hiszem, túl sokat kérdezõsködsz.}
