{100}{}{Ez itt egy Sóher.}
{101}{}{Jó kis hely ez! Sokkal jobb, mint a korábbi lakóhelyem.}
{102}{}{Szeretek itten lenni!}
{103}{}{Ha volnának vagyontárgyaim, rengeteg helyem lenne itt nekik.}
{104}{}{Hol a kutyám?}
{105}{}{Szomjas vagyok.}
{106}{}{Nincs valami kajád?}
{107}{}{Éhes vagyok.}
{108}{}{Csak nem megint eljött az alvás ideje?}
{109}{}{Tied lehet a régi lakóhelyem.}
{110}{}{Fáradt vagyok, miért vagy te itt?}
{111}{}{Ez az én otthonom! Menny el innét!}
{112}{}{Ez az én otthonom! Menny el innét!}
{113}{}{Hol a párnám?}
{114}{}{Álmos vagyok.}
{115}{}{Ne bánts!}
{116}{}{Te vagy az az alak, aki embereket bántalmaz!}
