{100}{}{Egy holttestet látsz a földön heverni.}
{101}{}{Egy szerencsétlen flótás fekszik itt.}
{102}{}{A földön egy mutáns ember maradványait látod.}
{103}{}{A dögevõk paradicsoma...}
{104}{}{Úgy tûnik, ez az illetõ kihívást intézett Thanatoshoz, és veszített.}
