{100}{}{Úgy tûnik, az ajtó a fegyverszekrényhez vezet.}
{101}{}{Megberheled az ajtó zárját.}
{102}{}{Nem sikerült megpiszkálnod az ajtó zárját.}
{103}{}{Ez a tárgy használhatatlan az ajtón.}
{104}{}{Az ajtó zárva van.}
{105}{}{Megberheled az ajtó zárját.}
{106}{}{Nem sikerült megpiszkálnod az ajtó zárját.}
{107}{}{Ez a képzettség használhatatlan az ajtón.}
