{100}{}{Az ajtó már nincs bezárva.}
{101}{}{Sikerült megbuherálni a zárat.}
{102}{}{Úgy tûnik, nem fog menni a zár megpiszkálása.}
{103}{}{Az elektronikus biztonsági rendszer megrázott!}
{104}{}{Sikerült beindítani az ajtóra szerelt riasztót.}
{105}{}{Az ajtón igazi zár van, amit csak megpiszkálni tudsz.}
{106}{}{Az elektronikus biztonsági rendszer már ki lett iktatva.}
{107}{}{Kiiktattad az elektronikus biztonsági rendszert.}
