{100}{}{Ez itt egy szivattyú.}
{101}{}{A szivattyú teljesen más tervezésû, mint amihez hozzászoktál a Menedékben.}
{102}{}{Rájössz, hogy a szivattyú alkatrészei sajnos nem illenek a Menedékedben található berendezéshez.}
