{100}{}{Õ Guido.}
{101}{}{Azt mondom, hogy csak nyers erõt használsz. Nem kerül sokba összezúzni egy térdkalácsot.}
{102}{}{Aztán kit érdekel a meglepetésszerû támadás? Nem mûvészek, hanem profik vagyunk. Te, Leone, valaki szól hozzánk. Nem azért vagyunk mi itt, hogyha valaki szóba áll velünk, megöljük?}
{103}{}{Azt mondom, hogy csak nyers erõt használsz. Nem kerül sokba összezúzni egy térdkalácsot}
{104}{}{Nem azért fizetnek, hogy beszéljek.}
{105}{}{WAztán kit érdekel a meglepetésszerû támadás? Nem mûvészek, hanem profik vagyunk. Te, Leone, valaki szól hozzánk. Nem azért vagyunk mi itt, hogyha valaki szóba áll velünk, megöljük?}
{106}{}{Azt mondom, hogy csak nyers erõt használsz. Nem kerül sokba összezúzni egy térdkalácsot}
{107}{}{WAztán kit érdekel a meglepetésszerû támadás? Nem mûvészek, hanem profik vagyunk. Te, Leone, valaki szól hozzánk. Nem azért vagyunk mi itt, hogyha valaki szóba áll velünk, megöljük?}
