{100}{}{You see a desert bandit. Based on how the others look at her, she must have some position of importance or authority.}
{101}{}{Gwen vagyok. Garl egyik tanácsadója. Te ki vagy?}
{102}{}{I'm }
{103}{}{ a becsületes nevem. Mivel foglalkozol itt?}
{104}{}{Nem vagyok én senki. Mondanál valamit a táborotokról?}
{105}{}{Hrú?}
{106}{}{Én vagyok az, aki ledönt a lábadról, kedvesem.}
{107}{}{Tanácsadóként az a dolgom, hogy egyetlen jöttment se okozzon fejfájást Garlnak.}
{108}{}{És ezt hogy éred el?}
{109}{}{Te? És még hozol egy hadseregnyi segítséget is hozzá?}
{110}{}{Kétlem, hogy képes lennél bárkit is megállítani.}
{111}{}{Szerintem az igazi jöttmentek itt élnek.}
{112}{}{Hmpf. Ha senki nem vagy, akkor miért beszélgetek veled? Lódulj innen!}
{113}{}{A magadfajta idiótákat eltanácsolom Garl közelébõl. Na, szakadj le innen, de gyorsan!}
{114}{}{Meg vannak a módszereim, hogy bizonyos nem kívánt elemeket eltávolítsak innen.}
{115}{}{Látom már, hogy tévedtem. Azt hiszem, mégiscsak értesz te a munkádhoz. Minden jót!}
{116}{}{Bizonyítsd be!}
{117}{}{Halál rád!}
{118}{}{Olyan régóta nem harcoltam egy jót. Nagy kár, hogy veszíteni fogsz. Nesze, itt a bizonyíték!}
{119}{}{Megbánod te még ezt a beszólást. Ez volt az utolsó!}
{120}{}{Ha ez a legjobb, amire képes vagy, szívességet teszek a világnak, ha megszabadítalak tõle.}
{121}{}{Én, és erre a seregre gondoltam segítségnek...}
{122}{}{Bosszantasz! Menj innen, mielõtt tényleg kihozol a sodromból!}
#
# Fallout Fixt:
#
{200}{}{You see: Gwen, the Khans' second-in-command and advisor to Garl.}
