{100}{}{Õ a Pengések egyik tagja.}
{101}{}{Csá!}
{102}{}{Helló.}
{103}{}{Legyen jó napod.}
{104}{}{Jó idõt fogtunk ki ma.}
{105}{}{Kiváncsi vagyok, fog-e esni.}
{106}{}{Láttál már izzó esõt?}
{107}{}{Vissza kell mennem dolgozni.}
{108}{}{Nem sok kívülállót látunk errefelé.}
{109}{}{Mennem kell.}
{110}{}{Viszlát!}
{111}{}{Minden jót!}
{112}{}{Kösz a segítséget.}
{113}{}{Nem fogunk elfelejteni téged.}
{114}{}{Örülök, hogy a mi oldalunkon állsz.}
{115}{}{Jóra fordultak a dolgok...}
