{100}{}{Egy vékony, mérges kinézetû embert látsz.}
{101}{}{Ez itt Ismarc.}
{102}{}{Mi van?}
{103}{}{Igen, mit akarsz?}
{104}{}{Hé, jól énekelsz.}
{105}{}{Az éneklésedtõl kilyukad a dobhártyám.}
{106}{}{Felejtsük el...}
{107}{}{Húú!}
{108}{}{Szuper! Nem is tudod, milyen jólesõ érzéssel tölt ez el. Menj innen!}
{109}{}{Kösz. Mit tehetek érted?}
{110}{}{Do you perform anywhere else?}
{111}{}{Csak úgy éreztem, dobnék egy kis pénzt abba a kalapba, ha szabad így mondanom.}
{112}{}{Hol tanultál énekelni?}
{113}{}{Kösz, hogy rabolhattam az idõdet.}
{114}{}{Mi van?!? Nincs nekem erre idõm.}
{115}{}{Igen, néha szoktam énekelni a Hubban és az Acél Testvériségét meg Adytumot is meglátogattam már a karavánok kíséretében. Miért kérded?}
{116}{}{Meg tudnád mondani, hogy juthatok el a Hubba?}
{117}{}{Meg kéne tudnom, hogy lehet eljutni a Testvériséghez.}
{118}{}{Hogy jutok el Adytumba?}
{119}{}{Öm, bocs, hogy zavartalak, kösz.}
{120}{}{A Hubba? Roncsvárostól délre megtalálod, nincs túl messze. Akarsz még valamit tudni?}
{121}{}{A Testvériség jónéhány napnyi utazásra van nyugati irányba, és egy kicsit északra. Ne menj oda egyébként! Nem fognak beengedni, hacsak nem egy karavánnal vagy. Szeretnél még valamit?}
{122}{}{Hmm. Haladj a Hubtól dél-nyugati irányba! Adytum a Csonttelep része. Apró, félig-meddig ipari város. Nem nagyon szerettem az ottani életet. Mit szeretnél még tudni?}
{123}{}{Hát, köszönöm szépen. Nehéz az éhezõmûvészek élete. Ha bármit tudni akarsz, csak kérdezz!}
{124}{}{Kösz, hogy így együttérzel, de úgy tûnik, te még jobban szûkölködsz, mint én.}
{125}{}{Itt is ott is ragadt rám. Egy Hubbeli öreg énekestõl is tanultam valamicskét, és kaptam néhány kottát a csonttelepi Adytumban tengõdõ gubizóktól is. Tudod, hogy van ez... ha gyakorolsz, megyeget.}
{126}{}{Egy fickó érdes hangon énekel a sarokban.}
{127}{}{A fejed zúgó folyó!}
{128}{}{Majd szétveti a méreg!}
{129}{}{Tõlem ugyan nem kapsz semmit,}
{130}{}{Egyenek inkább a férgek!}
{131}{}{Olvasok az agyadban:}
{132}{}{Acélketrec-tudat.}
{133}{}{A belsejében ott tombol egy}
{134}{}{Halálkarom csapat.}
{135}{}{Mindenestül kellesz,}
{136}{}{Mint egy méreg-belövés}
{137}{}{Mindenestül kellesz,}
{138}{}{Mint a skorpió-csípés.}
