{100}{}{A Tanítványok egyike, Jake.}
{101}{}{Az Apokalipszis Tanítványainak egyike.}
{102}{}{Üdvözöllek, barátom! Miben segíthetnék neked?}
{103}{}{Én seggít! Én seggít!}
{104}{}{Úgy hallottam, egész jó harcos vagy. Lássuk, így van-e!}
{105}{}{Úgy értesültem, segítségre van szükségetek. Mi a baj?}
{106}{}{Mit tudnál mondani a Tanítványokról?}
{107}{}{Segíteni akarsz, de nem hiszem, hogy elég jó vagy ehhez. Eridj beszélj Neil-el!.}
{108}{}{Szíves-örömest megküzdenék veled, de túlságosan lefoglal, hogy segítek Nicole-nak.}
{109}{}{Értem én. Amúgy eléggé mamlasznak tûntél nekem.}
{110}{}{Legyen, ahogy akarod... viszlát.}
{111}{}{Hogy lehet egy ilyen magadfajta mamlaszból parancsnokhelyettes?}
{112}{}{Hé, csak azért, mert nem akarok küzdeni, még nem vagyok mamlasz! Egyszerûen nincs kedvem hozzá.}
{113}{}{Nahiszen, igazam volt. Mamlasz vagy!}
{114}{}{Néhányan közülünk az eszüket használják, hogy elõrejussanak a világban. Békével és gondolkodással nagyon sok mindent el lehet érni.}
{115}{}{És mikor akarod végre használni az eszedet?}
{116}{}{Igazad van, elnézést.}
{117}{}{Na elég. Tudod, ki beszéljen veled egy szót is...}
{118}{}{Így máris jobb... amúgy... van egy kis problémánk egy itteni kémmel. Segítenél nekem?}
{119}{}{Persze, mirõl van szó?}
{120}{}{Oldd meg magad, ha annyira okosnak érzed magad.}
{121}{}{A lényeg a lényeg, van itt egy kém. Lehet, hogy az õrök egyike, de akár a felderítõk közül is lehet valaki. Csak ennek a két gárdának van szabad bejárása a Gyermekekhez.}
{122}{}{Oké. Megyek, elkapom a kémet, és pontot teszünk a problémára.}
{123}{}{Van valami elképzelésed a kémet illetõen?}
{124}{}{Felejtsd el! Nem segítek.}
{125}{}{Nagyon szépen köszönöm. Most menj!}
{126}{}{Nem igazán. Csak annyit tudok, hogy mindenféle kevésbé fontos információ már eljutott a Gyermekek kezébe. Ez sajnos nem túl jó így. Heather szerint Neil vagy Peter a kém.}
{127}{}{Oké. Utánanézek a dolognak.}
{128}{}{Felejtsd el! Nem segítek.}
{129}{}{Akkor nem hagyhatom, hogy elmenj.}
{130}{}{Majd utánanézek. Viszlát!}
{131}{}{Van egy kis problémánk azzal, hogy információk jutnak el a Gyermekek kezébe. Szerintem ez csakis egy kém mûve lehet.}
{132}{}{Értem. És mik azok a problémák?}
{133}{}{Oké, lerendezem azt a kémet.}
{134}{}{Van valami fogódzó a kémmel kapcsolatban?}
{135}{}{Felejtsd el! Nem segítek.}
{136}{}{Jelen pillanatban nem mondhatok semmit. Viszlát!}
{137}{}{Aludni próbálok, most ne zavarj!}
{138}{}{Siess és találd meg azt az aljas mocskot!}
{139}{}{Végig tudtam, hogy Heather az. Elejétõl fogva annyira álnoknak tûnt. Már elsõre mindenkinek el kellett volna mondanom a sejtésemet.}
{140}{}{Sosem tanultam tõled semmit. Az általad nyújtott tréning fabatkát sem ér.}
{141}{}{Hoztam neked egy csomagot Gabrieltõl.}
{142}{}{Hmm. Értem. Köszönöm.}
{143}{}{Húzz a francba innen!}
{144}{}{Mindig a nehezebb utat választják. Mindig!}
