{100}{}{Egy õrült tudóst látsz. Elmélyülten dolgozik valamin.}
{101}{}{Jó estét, testvérem. Mi szél fújt a mennyország e kis szegletébe?}
{102}{}{Jó estét, nõvérem. Mi szél fújt a mennyország e kis szegletébe?}
{103}{}{Azért vagyok itt, hogy ellenõrizzem, hogy haladsz.}
{104}{}{Mit csinálsz itt éppen?}
{105}{}{Mi?! Hogy mersz kérdéseket intézni hozzám? Mi lenne, ha kísérleteket végeznék az agyadon, te eltorzult sóher?!}
{106}{}{Gack.}
{107}{}{Már megint te vagy? Most éppen miért kell zavarnod a Mester dicsõséges jövõjét?}
{108}{}{A Mester kezd türelmetlenkedni a hibáid miatt, nem is beszélve a szemtelenkedéseidrõl!}
{109}{}{Tudni akarom, hogy haladnak a kísérleteid.}
{110}{}{Elég! Most majd véget vetünk szépen a kis JÖVÕDNEK. Itt és most, öcsisajt!}
{111}{}{Úfa!}
{112}{}{Jól halad. Épp most fecskendeztem be egy adag FEV-et az egyik alany agyalapi mirígyébe, de nem a várt eredményt kaptam.}
{113}{}{Miért nem egyenesen az Amygdalába próbáltad?}
{114}{}{Miért nem egyenesen a Medulába próbáltad?}
{115}{}{Mi lett az eredmény?}
{116}{}{Hmmm. És?}
{117}{}{Bocsánatodért esedezem. Miképp állhatnék rendelkezésedre?}
{118}{}{Bocsánatodért esedezem. Miképp állhatnék rendelkezésedre?}
{119}{}{Beszélj velem tisztelettudóan, különben soha többet nem beszélsz senkivel, ezt garantálom!}
{120}{}{A Mester igazsága testet öltött. Megnõttek a médiumokra jellemzõ képességek. [ingatja a fejét] Viszont a szegény párák megbolondultak, ezért el kell különíteni, le kell nullázni õket, hogy se maguknak se másoknak ne ártsanak.}
{121}{}{Ó, milyen meggondoltságra vall ez...}
{122}{}{Hol tartjátok õket?}
{123}{}{Te szívtelen mészáros! Most le fogom nullázni az agyadat, és elkülönítem a testedtõl! Ha nem haragszol, mocsok...}
{124}{}{Egy észak-nyugatra lévõ szobában. Van még valami, amiben segíthetnék?}
{125}{}{Kösz a segítséget. Viszlát!}
{126}{}{Jaja, öö, mi az a FEV?}
{127}{}{Most meghalsz!}
{128}{}{Nincs idõm az ostobaságaidra!}
{129}{}{Micsoda egyedülálló ötlet! Azonnal ki kell próbálnom!}
{130}{}{Öh, hol tároljátok a defektes kísérleti alanyokat?}
{131}{}{Ne is mondd...}
{132}{}{Igen! Próbáljuk ki rajtad!}
{133}{}{Vincent! Készítsd fel a legújabb önkéntesünket!}
{134}{}{MI? Ez a legviccesebb dolog, amit valaha hallottam. [Gyanakodva méreget] Egyébként ki vagy te valójában?}
{135}{}{Sajnálom, most mennem kell.}
{136}{}{Én... izé... új vagyok itt... azért küldtek, hogy megnézzem, miként boldogulsz.}
{137}{}{Már elmondtam, a Mester küldött, hogy ellenõrizzem a munkádat.}
{138}{}{Azért jöttem, hogy eltávolítsam a gerincedet... altatás nélkül!}
{139}{}{Jól van. Szóval hogy mennek a dolgok?}
{140}{}{A hozzáállásod mindent elmondott, amire szükségem volt. Minden jót!}
{141}{}{Ah ha! Egy betolakodó! Ahogy azt sejtettem! Vincent!}
{142}{}{Ki vagy te? És miért viseled azt az öltözéket? [magának] Régóta nem láttam már ilyesmit.}
{143}{}{Álruhában vagyok. Behatolók szivárogtak be a Mester szentélyébe és úgy kellett öltöznöm, hogy elnyerhessem a bizalmukat.}
{144}{}{Hogy merészeled megkérdõjelezni a Mester egyik speciális akcióját?}
{145}{}{Mikor láttál ehhez hasonló öltözéket?}
{146}{}{Ez préselt gumi, szóval elég könnyû letörölni a véredet, miután megöltelek!}
{147}{}{Ó, amikor az utolsó tiszta emberanyag beérkezett... hm, szerintem még van egy darab a karámban. Miért kérded?}
{148}{}{Semmi különös. Hogy haladnak a kísérletek?}
{149}{}{Jelentést kell vinnem a Mesternek, nincs nekem erre idõm.}
{150}{}{[ingatja a fejét] Sajnos a szegény párák megbolondultak, ezért el kell különíteni, le kell nullázni õket, hogy se maguknak se másoknak ne ártsanak.}
{151}{}{Ó, milyen meggondoltságra vall ez...}
{152}{}{Te szívtelen állat! Most le fogom nullázni az agyadat, és elkülönítem a testedtõl! Ha nem haragszol, mocsokláda...}
{200}{}{Õ Vincent, a szupermutás õr. Eléggé unatkozik.}
{201}{}{Egy szupermutánst látsz, aki szemlátomást a tudósokra vigyáz. Eléggé unatkozik.}
{202}{}{Betolakodók!}
{203}{}{Vigyázok a tudósokra. Ne szólj hozzám!}
{204}{}{Hagyj békén!}
{300}{}{Egy alvó õrült tudóst látsz.}
{301}{}{Zzzzzz}
{302}{}{He! Mi? [megtörli a szemét] Vincent, távolítsd el ezt a szentségtörõt a helyiségbõl!}
{303}{}{He? [horkant] ...zzzzzzzzz}
{400}{}{Ez itt Vincent. Õ vigyáz az alvó õrült tudósokra.}
{401}{}{Egy szupermutáns õrt látsz. Körülötte testek hevernek.}
{402}{}{Hagyd békén õket, és menj el innen! Senki nem jöhet ide, amikor alszanak.}
{403}{}{Már megint te vagy?! Már mondtam egyszer, hogy hagyd békén a tudósokat!}
{404}{}{Visszaéltél a bizalommal.}
