{100}{}{Mit akarsz?}
{101}{}{Hé, meg akarod enni azt a döglött patkányt?}
{102}{}{Mi?}
{103}{}{Láttad a kutyámat, Elvis? Valahol itt lófrál.}
{104}{}{Szia.}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Lerágom a csontjaidat!}
{108}{}{Halál! Halál! Halál!}
{109}{}{Hé, hallottad, hogy Setet kinyírták?}
{110}{}{Set halott. Set halott. Set halott....}
{111}{}{Elég víz jut mindenkinek. Set garantálja ezt.}
{112}{}{Azt hallottam, hogy a mutánsok elfutottak a városból.}
{113}{}{Sokkal jobb, amióta a mutánsok leléptek.}
{114}{}{Helló.}
