{100}{}{Ez itt valami hatalmas szupermutáns teremtmény! A kezében egy bazi nagy fegyvert szorongat!}
{101}{}{Vidd õt Harryhez! Õ majd tudja, mi a teendõ vele.}
{102}{}{El kéne vinned õt Harryhez. Az összes nõvel kapcsolatban van valami terve.}
