{100}{}{Ez egy nukleáris robbanófej.}
{101}{}{A kezelõ-számítógéptõl a mögötte álló robbanófejig kábelek futnak.}
{102}{}{You have armed the warhead. A timer displaying "4:00" has started a countdown.}
{103}{}{Hatástalanítottad a nukleáris robbanófejet.}
{104}{}{BUMMMMMMMMM! [Beindítottad a nukét!]}
{105}{}{Ez úgy tûnik, nem mûködik.}
{106}{}{A visszaszámlálás még tart... esetleg elvághatnád a piros kábelt.}
{107}{}{Esetleg a kulcsot is használhatnád.}
{108}{}{Ez nem más, mint egy nukleáris robbanófej. A kezelõ-számítógép kábelekkel van összekapcsolva vele.}
{109}{}{Nincs mit megjavítani ezen a nukleáris robbanófejen.}
{110}{}{Nincs zár vagy hasonló ezen a nukleáris robbanófejen.}
{111}{}{Ez egy hatalmas méretû csapda, amit innen nem lehet hatástalanítani vagy élesíteni.}
