{100}{}{Neal, a csapos.}
{101}{}{Egy csapost látsz.}
{102}{}{Olyannak tûnik, mint aki rendszeresen túldolgozza magát.}
{103}{}{Hé! Nehogy azt képzeld, hogy le tudsz lépni azzal, te tolvaj!}
{104}{}{Zárva vagyunk, gyere vissza négykor!}
{105}{}{Zzzz}
{106}{}{Üdvüzlünk a Vesztõhelyen. Mivel szolgálhatok?}
{107}{}{Öh, innék valamit.}
{108}{}{Felvilágosítást szeretnék.}
{109}{}{A nevem }
{110}{}{. Mi ez a hely?}
{111}{}{Gaa hnnngh!}
{112}{}{Szuper. Mit akarsz?}
{113}{}{Nuka-cola, 3 kupak.}
{114}{}{Sör, 5 kupak.}
{115}{}{A kerítésszaggató, 20 kupak.}
{116}{}{Jóvan, mit akarsz tudni?}
{117}{}{Mi a dörgés a városban?}
{118}{}{Ki az a veszélyes külsejû egyén a sarokban?}
{119}{}{Kik azok májer gyerekek?}
{120}{}{[Neal kötekedõen néz rád egy pillanatig.] Nem láttál még kocsmát életedben, idegen? Ez itt az én mûintézményem, a Vesztõhely. Te vásárlod az italt, és tolod a jattot.}
{121}{}{Öh, jaja. Tudtam én... volna valami itóka a gallér mögé?}
{122}{}{Ja. Öm, kaphatok még némi infót?}
{123}{}{Ah, kösz.}
{124}{}{Ja, ugyanazt neked is, haver.}
{125}{}{Mi az a serleg a polcon?}
{126}{}{Nyugat felé - ott ni - megtalálod Gizmo kaszinóját. Meg lennék lepve, ha nem ismernéd a helyet. Az itteniek többsége azokból tevõdik össze, akik ott vesztették el az utolsó petákjukat is. A város másik felében ott van Killian vegyesboltja, és Marcelles Hétalvónak keresztelt Fogadója. Killian jó gyerek, fasza kis boltot vezet, mindene van, ami csak kellhet. A Hétalvóban meg kialszod az itt átmulatott éjszakát. [Neal kuncog hozzá]}
{127}{}{Kösz. Kaphatok egy italt?}
{128}{}{Köszönöm a felvilágosítást. Minden jót!}
{129}{}{A ficerét Tychónak hívják. Szerintem valami felderítõ keletrõl vagy ilyesmi. Nagyon durva bunyós, legalábbis, amit hallottam róla. Szerintem nagyon gerinces ember.}
{130}{}{Nem baj, ha kérdezek még valamit?}
{131}{}{Ja, hogy õk... Skulznak hívják a bandájukat. Õk a helyi menõ csávók. Söpredék banda. Néha szoktak bunyót provokálnni, és kigarázdálkodják magukat. Killian általában féken tartja a bagázst.}
{132}{}{Nesze. Jó hörpölést!}
{133}{}{Hé! Elloptad az urnámat!}
{134}{}{Az nem közönséges serleg, hanem urna. A feleségem hamvai vannak benne. A kocsmámat leszámítva, a legfontosabb dolog a számomra.}
{135}{}{Valamit még?}
{136}{}{Információ kéne.}
{137}{}{Kösz, nem.}
{138}{}{Ah.}
{139}{}{Igen, innék valamit.}
{140}{}{Csak akkor gyere vissza, ha van pénzed!}
{141}{}{Mit adhatok, barátom?}
{142}{}{Mi történt azzal a serleggel, amit ott tartottál a polcon?}
{143}{}{Köszönöm. Nem is tudod, mit jelent ez nekem. Tudod mit? Soha többé nem kell fizetned a piáért, ha hozzám jössz.}
{144}{}{Visszaszereztem az urnádat.}
{145}{}{Valami görény ellopta. Nem közönséges serleg volt, hanem urna. A feleségem hamvait tartottam benne. A kocsmámat leszámítva, az a legfontosabb számomra.}
{146}{}{Húzzatok innen a véres francba, rohadt punkok! Ha még egyszer valamelyik egy ujjal is illetni merészeli, az egész bandát kicsinálom!}
{147}{}{Ha majd nem tudok elbánni az ilyen szarosokkal, mint ti, már nem is érdemes élnem!}
{148}{}{Mi a francot mûvelsz? Zárva vagyunk. Tûnés kifelé!}
{149}{}{Rohadék kölkök, majd mindjárt megmutatom én, ki az úr a háznál!}
