{100}{}{Egy vízfeldolgozást vezérlõ számítógépet látsz. Egy elengedhetetlen hardver eltávolítása miatt hibásan mûködik.}
{101}{}{A számítógép átkutatása sikerrel járt. Minden gond nélkül megtaláltad a víztisztító csipet.}
{102}{}{Átkutatod a számítógépet. Eltart egy darabig, de mit tesz isten, megtalálod a víztisztító csipet.}
{103}{}{Mûködõképes vízcsip hiányában a számítógép nem javítható meg.}
{104}{}{Könnyedén eltávolítod a vízcsipet a számítógépbõl. Hallod, amint a városba áramló vízáram megáll.}
{105}{}{Szenvedsz egy darabig a számítógéppel, de képtelen vagy kiszedni belõle a csipet. Rövid idõ múltán rádöbbensz, hogy elfelejtetted eltávolítani a csavarokat.}
{106}{}{A vízcsip sajnos marad a helyén... Esetleg újra próbálkozhatnál, mondjuk valamivel körültekintõbben.}
{107}{}{Túlságosan távol vagy, hogy gondosan megvizsgálhasd a számítógépet.}
{108}{}{Nem sikerült megjavítani a számítógépet.}
{109}{}{Semmi érdemlegeset nem sikerült megtudni a számítógéppel kapcsolatban.}
{110}{}{Visszaülteted a vízscsipet a számítógépbe, amely annak rendje és módja szerint bejelentkezik, és tökéletesen mûködik.}
{111}{}{Ezt a tárgyat nem lehet használni ezen a számítógépen.}
{112}{}{Ez itt egy vízfeldolgozást irányító számítógép. Tökéletesen mûködik.}
{113}{}{You earn }
{114}{}{ experience for getting a Water Chip.}
{115}{}{Gondosan áttanulmányozod a számítógépet. Analitikus gondolkodásmódod rávezet egy-két módszerre, melyek segítségével könnyedén eltávolítod a vízcsipet.}
{116}{}{Rájössz, hogy a vízcsip beültetése nélkül a számítógép nem hozható rendbe.}
{117}{}{Miután lekapcsoltad a víztisztító számítógépet, hallod a megjavított szivattyút mûködni a távolban, ahogy a Nekropolisz alatti mély kútból szépen hozza fel a vizet.}
