{100}{}{A szivattyút megjavítottad, és remekül mûködik.}
{101}{}{A szivattyú nem mûködik, mert elromlott a vákumpumpa.}
{102}{}{A szivattyú nem mûködik.}
{103}{}{Valami gépezet.}
{104}{}{Ez a szivattyú nem mûködik, mert elromlott a vákumpumpa.}
{105}{}{Lehet, hogy biztosítékcserére szorul.}
{106}{}{A szivattyú nem mûködik.}
{107}{}{A szivattyút addig nem lehet megjavítani, amíg nincs egy tartalék vákumpumpa.}
{108}{}{Nem sikerült megjavítani a szivattyút. Lehet, hogy biztosítékcserére szorul.}
{109}{}{Nem sikerült megjavítani a szivattyút.}
{110}{}{Ez a szivattyú nem mûködik, mert elromlott a vákumpumpa.}
{111}{}{A szivattyú biztosítékcserére szorul.}
{112}{}{A szivattyú nem mûködik.}
{113}{}{Semmi szokatlant nem veszel észre.}
{114}{}{Miután visszaépítetted a hiányzó alkatrészeket, a robosztus szivattyú dohogva beindul.}
{115}{}{Véletlenül megsemmisültek az alkatrészek, miközben elvágod a kezed és 1 pontnyi sérülést szenvedsz.}
{116}{}{Sajnos nehézséget okoz számodra, hogy mûködésbe hozd ezeket az alkatrészeket.}
{117}{}{Ez a tárgy nem használható a szivattyún.}
{118}{}{You earn 1000 experience for fixing the water pump. The ghouls will be grateful!}
