{100}{}{Õ nem más, mint Orfeo, a Katedrális Gyermekeinek régi tagja.}
{101}{}{Ah. Egy újonan megtért. Üdvözlünk!}
{102}{}{Én öl!!!}
{103}{}{Nem vagyok megtért!}
{104}{}{Köszönöm, Testvérem.}
{105}{}{Akkor gyorsan megoldjuk ezt a kis problémát.}
{106}{}{Elõször is meg kell tisztítanunk téged a pusztaság mocskától. Jer velem!}
{107}{}{Megtisztítunk téged!}
