{100}{}{Egy Paladin õrt látsz.}
{101}{}{Pssszzt, nem akarsz seftelni?}
{102}{}{Elnézést, de szolgálatban nem beszélgethetek.}
{103}{}{Nagyon szép napunk van ma. Remélem, senki nem támad ma ránk.}
{104}{}{Némelyik karavánkereskedõ meglehetõsen furán viselkedik.}
{105}{}{Jó napot!}
{106}{}{Üdvözöllek, szépségem!}
{107}{}{Üdv, Újonc!}
{108}{}{Ha bármilyen kérdésed van a rendünkkel kapcsolatban, Cabbottal beszélj. Õ az ajtónálló.}
{109}{}{Cabbottal kéne beszélned. Õ az a fiatal fickó az ajtónál.}
{110}{}{Pssszzt, nem akarsz seftelni?}
{111}{}{Ha üzletelni szeretnél, rossze emberhez fordultál.}
{112}{}{Tessék?}
{113}{}{Ne zavarj, féreg!}
{114}{}{Úgy nézek én ki, mint akit esetleg érdekel bármi is, amit fel tudsz ajánlani?}
{115}{}{Pfúú... ezt a pofátlanságot...}
{116}{}{Újonc, jobb dolgod is lehetne, mint bennünket zargatni, mialatt szolgálatban vagyunk.}
{117}{}{Ha bármilyen kérdésed van a rendünkkel kapcsolatban, Cabbottal beszélj. Õ az ajtónálló.}
{118}{}{Újonc, nem kéne inkább valami hasznos dologgal elfoglalni magad?}
{119}{}{Szerintem nem kéne itt lenned, idegen.}
