{100}{}{Egy parasztot látsz.}
{101}{}{Nahát, a nagy ember rohan a rettenetes kutyától. Phil, te aztán megmutattad a világnak, de meg ám!}
{102}{}{Mi a fenét csinálsz, Phil? Teszteled a cipõtalpad, mi?}
{103}{}{Apám, az a kutya aztán éhes lehet! Biztos, hogy elevenen fel akar falni, Phil.}
{104}{}{Az talán egy kicsit túlzás lehet egy szegény, védtelen állatnak, nem gondolja?}
{105}{}{Magának aztán szép kutyája van ám...}
{106}{}{Biztos vagyok benne, hogy Phil hálás lenne magának, ha elintézné azt a kutyát.}
{107}{}{Kösz, hogy elintézte azt a kutyát.}
