{100}{}{Egy ghoul foglyot látsz.}
{101}{}{Mi-mit akarsz?}
{102}{}{Öö, semmit.}
{103}{}{Hng.}
{104}{}{Azért jöttem, hogy szabadon engedjelek.}
{105}{}{Mire számítottál?}
{106}{}{Hé, ez engem nem érdekel, csak engedj ki innen!}
{107}{}{Nagyszerû! Csináld csak!}
{108}{}{Elloptam egy kis vizet. Szomjas voltam a jó életbe! Senki fiát nem bántottam érte!}
{109}{}{Többet vettél el, mint amennyi jár.}
{110}{}{Ah, ez semmi, mindjárt kiengedlek.}
{111}{}{A víz nélkül meghaltam volna. Csak egy pohárnyi volt. Épp annyi, hogy életben maradjak. Ki kell, hogy szabadíts innen! Menten megõrülök!}
{112}{}{Oké, várj egy pillanatot!}
{113}{}{Asszem, hagyom, hogy az illetékesek foglalkozzanak veled.}
{114}{}{Szabadíts ki, kérlek!}
{115}{}{Köszönöm, hogy kiengedtél.}
{116}{}{Semmiség.}
{117}{}{Honnan jön a víz?}
{118}{}{Ja.}
{119}{}{A lenti kutakból szivattyúzzák fel. Van egy csatornalejárat a következõ cellában, ami a régi bunkerbe vezet. Az a víz forrása. Ha a lentiek nem lennének, mindenki sokkal jobban járna.}
{120}{}{Ezt hogy érted?}
{121}{}{Köszönöm.}
{122}{}{Néha elég nehéz egy ósdi technológiát mûködésre bírni. Akárhányszor lemegyek a mélybe, a fénylõk kihajtanak onnan, mint a legyet. Mi ghoulok békén hagyjuk õket. A nagy darab mutánsokat meg nem nagyon érdekli a dolog.}
{123}{}{Sok szerencsét! Viszlát!}
{124}{}{You earn }
{125}{}{ tapasztalati pontot kaptál.}
{126}{}{Újra csak azt tudom mondani, köszönöm.}
