{100}{}{A számítógép felirata szerint ez a RÁDIÓFORGALMAZÓ KÖZPONT.}
{101}{}{ A rádiócsatornák szemlátomást le vannak kapcsolva.}
{102}{}{ A rádióvezérlõ mûködni látszik.}
{103}{}{Beizzítod a rádiócsatornákat.}
{104}{}{Kikapcsolod a rádiócsatornákat.}
{105}{}{Nyomogatod, tekergeted egy darabig a kapcsolókat, de a rádiócsatornák hallgatnak, mint a sír.}
