{100}{}{You see: Cindy. She is crying.}
{101}{}{You see: Lisa. She is crying.}
{102}{}{You see: Sandy. She is crying.}
{103}{}{You see: Mary. She is crying.}
{104}{}{You see: Stacy. She is crying.}
{105}{}{You see: Susan. She is crying.}
{106}{}{Cindy.}
{107}{}{Lisa.}
{108}{}{Sandy.}
{109}{}{Mary.}
{110}{}{Stacy.}
{111}{}{Susan.}
{112}{}{Helló, }
{113}{}{. Megtaláltad már a vízcsipet?}
{114}{}{Nem, még nem.}
{115}{}{Meg fogom találni. Hogy álltok?}
{116}{}{Urug!}
{117}{}{Óh... nem értesz engem. Én nem igazán hiszem hogy volna egyáltalán esélyünk. Bocsáss meg, amiért sírok!}
{118}{}{Ögg!}
{119}{}{Légy szíves találd meg, mert a gyerekem hamarosan szomjan hal!}
{120}{}{[Kész]}
{121}{}{Meg kell találnod! Ne hagyd, hogy így pusztuljunk el!}
{122}{}{[Kész]}
{123}{}{Ne add fel a keresést! Én hiszek benned. Tudom, hogy mindent megteszel, hogy megments minket.}
{124}{}{[Kész]}
{125}{}{Félek a kilátásoktól. Valaki lopja a vizünket és most már mindenkinek nagyon rosszul áll a szénája.}
{126}{}{Ki tenne ilyesmit}
{127}{}{Mi történt?}
{128}{}{Néhány embert megvádoltak itt, és nagy adok-kapok alakult ki köztük. Igazából senki nem tudja.}
{129}{}{Oké. Kösz.}
{130}{}{Néhányan jelentették, hogy a vizüket ellopta valaki. Õk nem kaphattak több vizet, de szerencséjükre a barátaik megosztották velük az övékét. Az eset után mindenki tiszta idegbeteg lett, és nekiálltak õrizni a vizet. Néhány nappal késõbb valaki leütötte a tartalékhoz rendelt õrt, és megintcsak lopott a vízbõl.}
{131}{}{Ez borzasztó! Mit tehetnék az ügy érdekében?}
{132}{}{Talán megfoghatnád az illetõt, bárki is legyen az.}
{133}{}{Körülnézek, és meglátom, mit tehetek.}
{134}{}{Bye.}
