{100}{}{Egy részeg alakot látsz.}
{101}{}{Egy kuncsaft.}
{102}{}{Egy nagyon csinos hölgyet látsz.}
{103}{}{Egy furcsa kinézetû embert látsz.}
{104}{}{Ez itt egy szerencsejátékos.}
{105}{}{Ez a nõ eléggé elfoglaltnak tûnik.}
{106}{}{Egy nõt látsz.}
{107}{}{Egy férfit látsz.}
{108}{}{Egy nagyon elkeseredett játékost látsz.}
{109}{}{Ez itt egy zsoldos.}
{110}{}{Hadd szomorkodjam egyedül.}
{111}{}{Te vagy az én legeslegkedvesebb barátom.}
{112}{}{Mér vagy... (hukk) hol vagyok?}
{113}{}{Ki vagy te?}
{114}{}{Ismerlek én téged?}
{115}{}{Egy picit émelygek.}
{116}{}{Most én fizetek, illetve te...}
{117}{}{Miért vagytok ketten?}
{118}{}{Maradj már veszteg, ecsém!}
{119}{}{Maradj már veszteg, bébi!}
{120}{}{Kopj már le, sóher!}
{121}{}{Csak lerontod itt a hely színvonalát...}
{122}{}{Húzz innen, balszerencsét hozol!}
{123}{}{Ne szakíts félbe, koncentrálok!}
{124}{}{Azért is nyerni fogok!}
{125}{}{Jól megy ez neked?}
{126}{}{Láttad ezt? Ez lehetetlen!}
{127}{}{Szerintem ezek csalnak}
{128}{}{Na, végre, jók az esélyek!}
{129}{}{Na, ez lesz a tuti, én mondom!}
{130}{}{Micsoda? Most meg hogy veszíthettem?}
{131}{}{Ez az asztal balszerencsés!}
{132}{}{Dolgom van.}
{133}{}{Nem látod, hogy épp játszom?}
{134}{}{Tedd meg a téted, vagy kopj le!}
{135}{}{Hagyj minket békén, különben hívom az õröket!}
{136}{}{Vigyázzál ám! Fry megbízott a közeli barátom.}
{137}{}{Ha nem haragszol...}
{138}{}{Nincs ám kukucskálás!}
{139}{}{Csoportszex nincs!}
{140}{}{Túl fáradt vagyok még egy menethez.}
{141}{}{Álmodozz csak, kedvesem... csak ne itt!}
{142}{}{Tûnj a fenébe!}
{143}{}{Mégis mit képzelsz, mit csinálsz?}
{144}{}{Viselkedj már!}
{145}{}{Hívom ám a zsarukat!}
{146}{}{Don't even think about it!}
{147}{}{Tûnés!}
{148}{}{Kopj le!}
{149}{}{Mit bámulsz?}
{150}{}{Ha nem haragszol...}
{151}{}{Húzz a retkes picsába a szobámból!}
{152}{}{Kifelé!}
{153}{}{Te is az orgiára jöttél?}
{154}{}{Kifelé, te perverz disznó!}
{155}{}{Mi a problémád?}
{156}{}{Kopj le, mielõtt mérges leszek!}
{157}{}{Szerezz magadnak egy luvnyát!}
{158}{}{A nõ az enyém!}
{159}{}{A fenébe!}
{160}{}{Te csalsz?}
{161}{}{Ezt nekem kellett volna megnyernem!}
{162}{}{Majdnem megvolt!}
{163}{}{Mellétrafált...}
{164}{}{Hogy is van a szabály?}
{165}{}{Régebben jobban ment ez a franc.}
{166}{}{Sokra nem jutottam, de azért kösz.}
{167}{}{Hát ezt nem hiszem el!}
{168}{}{Tudtam, hogy megint veszteni fogok.}
{169}{}{Tegyék meg a tétjeiket!}
{170}{}{Húzza hátrébb a kezét, uram!}
{171}{}{Íme a gyõztes!}
{172}{}{Sajnálom, emberek, talán legközelebb.}
{173}{}{Megvan az újabb gyõztes!}
{174}{}{El a kezekkel!}
{175}{}{Maga jön, uram!}
{176}{}{Sajnálom, ez érvénytelen tét.}
{177}{}{Ez az!}
{178}{}{Még valaki?}
