{100}{}{Feláll a nyakadon a szõr. Érzel valamit az elõtted lévõ folyosóról. A gyomrod is összerándul, amint felismered az elõtted tornyosuló hústömeget... emberi testrészek a falban. Az egészben az a legrosszabb, hogy egyre csak mozognak, és téged szólítanak.}
{101}{}{Elered az orrod vére. Hangokat hallasz a fejedben. A neveden szólítanak. Egy pillanatra sötétség telepszik a szemedre, de csakhamar elmúlik.}
{102}{}{Hallasz egy hangot. Odafordítod a fejed, és egy elfelejtett barátodat látod. Szemlátomást halott. Férgek potyognak bomló állkapcsai közül, a fejfájásod pedig egyre fokozódik.}
{103}{}{Az elõrehaladás lépésrõl-lépésre nehezebb. Úgy érzed, mintha odabilincselték volna a padlóhoz a lábaidat. Lepillantasz, és látod, amint a burjánzó padló felkúszik a lábszáradon. Fogak harapnak a térdedbe, a fejfájás pedig kezd elviselhetetlen lenni.}
{104}{}{Észreveszel valami gyorsan mozgó dolgot a mennyezeten, aztán hirtelenjében egy csontszilánk döfõdik a szemedbe! Szinte azonnal a holtak és a megkínzottak képei tolulnak az agyadba!}
{105}{}{Az agyadat mardosó fájdalom szinte az õrületbe kerget. Érzed, amint mások bûnei átmossák a lelkedet. Azzal, hogy a saját bûneiddel szembesülnek, még rosszabbá válik az érzés. Õrültek módjára csörtetnek át az agyadon, miközben a személyiségedet apró darabokra szaggatják.}
{106}{}{A fejed majd szétszakad mások tolakodó gondolataitól. A fájdalom csak nõttön-nõ... Hirtelen aztán, mintha sosem létezett volna, megszûnik a kín. A padlóra rogysz és keservesen zokogni kezdesz. Valami azonban még mindig aggaszt.}
{107}{}{A fejedet kínzó fájdalom nem olyan kegyetlen, mint korábban. A különös folyosó hatása mintha meggyengült volna.}

#	Fallout Fixt -- Sduibek
#
{250}{}{You have permanently lost 1 point of Perception.}
{251}{}{You have permanently lost 1 point of Intelligence.}
