{100}{}{Rhombus.}
{101}{}{Mondj magadról valamit!}
{102}{}{Tudnál mesélni valamit a Testvériség történelmérõl?}
{103}{}{Hallottál érdekes pletykákat?}
{104}{}{Mit tudnál mondani nekem a környezõ vidékrõl?}
{105}{Rhom1}{Segíthetek valamiben?}
{106}{}{Feltehetek néhány kérdést?}
{107}{}{Távolról sem úgy nézel ki, mint egy harcos.}
{108}{}{Öhhh?}
{109}{Rhom2}{Igen.}
{110}{Rhom3}{Szemtelen disznó! Kérj elnézést, különben megbánod!}
{111}{}{Csak viccelni próbáltam, igazán sajnálom.}
{112}{}{Csak nem te fogsz itt bekeményíteni?}
{113}{Rhom4}{Mit akarsz?}
{114}{}{Feltehetek néhány kérdést?}
{115}{}{Mennyire vagy gyáva?}
{116}{Rhom5}{A Testvériség szégyene vagy. Mindjárt megtanítalak jó modorra!}
{117}{Rhom6}{Nem fogom tovább pazarolni az idõmet rád.}
{118}{Rhom7}{Rhombus vagyok, a paladinok vezetõje. Én képzem ki a tanulni vágyókat.}
{119}{}{Rendben, tudnál nekem tanítani egy-két dolgot?}
{120}{}{Ennyi az egész? Errõl szól az életed?}
{121}{}{Mivel foglalkoznak paladinok?}
{122}{Rhom8}{Egy-két dolgot? Arra képzem ki az embereket, hogyan harcoljanak... ha megvan bennük a képesség. Igaz, ami igaz, a Nagyperjel megtiltotta, hogy az invázió veszélyének elmúlása elõtt újoncokat tanítsak.}
{123}{}{Milyen veszélyrõl van szó?}
{124}{}{Miért szüntette be a kiképzést?}
{125}{}{Szerintem én könnyen legyõznélek egy harcban.}
{126}{Rhom9}{Nem az én reszortom, hogy válaszoljak erre. Keresd meg a Nagyperjelt, ha mindenáron választ akarsz kapni.}
{127}{}{Ugyan már, légy szíves...}
{128}{}{Rendben, jól van. Kérdezhetek még?}
{129}{Rhom10}{Keringenek mendemondák egy furcsa hadsereg gyülekeztérõl, de nem áll módomban errõl többet mondani.}
{130}{}{Jaj, ne már, lécci, lécci...}
{131}{}{Azért kérdezhetek még valamit?}
{132}{Rhom11}{ Nem.}
{133}{}{Jaj, ne már, lécci, lécci...}
{134}{}{Rendben. Kérdezhetek azért még valamit?}
{135}{Rhom12}{Igen. Ennyi bõven elég.}
{136}{}{Az életed elég üresnek tûnik számomra.}
{137}{}{Tényleg?}
{138}{Rhom13}{Nem igazán érted, mirõl szól paladinnak lenni. Elég nagy baj ez.}
{139}{}{Gondolod, hogy lehetne belõle valaha paladin?}
{140}{}{Lovagnak lenni elég hülyeségnek hangzik.}
{141}{}{Nem, szerintem nem. Válaszolsz még néhány kérdésemre?}
{142}{Rhom14}{Meglehet. Ha a támadó hadsereget legyõztük, gyere vissza, és részt vehetsz a kiképzésen!}
{143}{}{Szerintem ez lesz, kösz.}
{144}{}{Te lennél a tréner? Mindjárt feltörlöm veled a padlót, öcsém!}
{145}{Rhom15}{Van még valami?}
{146}{}{Igen, feltehetek még kérdéseket?}
{147}{}{Nem, kösz.}
{148}{Rhom16}{Minden jót akkor...}
{149}{Rhom17}{Túl sokáig tart. Azzal töltöm az idõmet, hogy a kiképzetteket továbbképzem.}
{150}{}{Nagyon unalmas dolognak tûnik.}
{151}{}{Ennyi az egész? Errõl szól az életed?}
{152}{}{Fenébe... feltehetek még néhány kérdést?}
{153}{Rhom18}{Ha ha ha! Lássuk!}
{154}{Rhom19}{A Krónikások a fegyverek terveit másolgatják, a Lovagok pedig elkészítik õket. A Paladinok védelmezik a Testvériséget a külsõ veszélyek ellen.}
{155}{}{Milyen veszélyek fenyegetnek?}
{156}{}{Atyám, ez dög unalom!}
{157}{Rhom20}{Sokan sóvárognak a technológiánk után. Hetente legalább négy támadást kell visszavernünk, beleértve a fosztogatókat, meg a mindennapos tolvajokat, akik meg akarják kaparintani a dolgainkat.}
{158}{}{Hm, feltehetek még néhány kérdést?}
{159}{Rhom21}{Beszélj Vree-vel a fõkönyvtárban!}
{160}{Rhom22}{Nem szoktam hitelt adni a pletykáknak.}
{161}{}{Ugyan már, csak egyet! Légyszi!}
{162}{}{Jól van...}
{163}{Rhom23}{A Hub és a Csonttelep dél felé vannak, a hegyvidék keletre, északra pedig kietlen pusztaságot találsz. Akárki is megy oda, sosem tér vissza.}
{164}{Rhom24}{Tedd azt le azonnal!}
{165}{Rhom25}{Ezt csináljuk itt a bûnözõkkel...}
{166}{Rhom26}{Abbahagyod rögtön!}
{167}{Rhom27}{Szóval tolvajkodsz! Most megmutatom, mit csinálunk itt a tolvajokkal...}
{168}{}{Várj! Meg tudom magyarázni!}
{169}{}{Hajrá! Mutasd, mit tudsz!}
{170}{Rhom28}{Rendben, magyarázatot várok, Újonc!}
{171}{}{Csak szemrevételeztem a dolgokat!}
{172}{}{Elnézést kérek, nem tudtam, hogy ez a te szobád.}
{173}{Rhom29}{Nos távozz, hajlandó vagyok elfeledni ezt a kis incidenst.}
{174}{}{Oké, kösz.}
{175}{}{Mindjárt gondoltam!}
{176}{Rhom30}{Hazudsz, Újonc! Most majd megláthatod, mit csinálunk a tolvajokkal...}
{177}{Rhom32}{Akár hülye vagy, akár viccelni akarsz velem, nem fogom az idõm pazarolni rád.}
{178}{Rhom33}{Beszélj Talusszal, a helyettesemmel! Õ többet tudna mondani neked errõl.}
{179}{Rhom34}{Már mondtam...}
{180}{Rhom35}{Ahogy már mondtam...}
{181}{Rhom36}{Nem fogom ismételni magam.}
{182}{Rhom37}{Nem jó a füled? Nem fogom még egyszer elmondani!}
{183}{Rhom38}{Õ a Fõkrónikásunk. A könyvtárban megtalálod.}
{184}{Rhom39b}{Én vagyok Rhombus.}
{185}{}{Talus a helyettesem.}
{186}{Rhom40}{Maxson tábornok volt a valaha élt legnagyobb Fõpaladin. Amikor Nagyperjel lett belõle, én vettem át a posztját.}
{187}{Rhom41}{Õk sokszorosítják a fegyverdokumentációkat, és új ötletek kiagyalói. A kutatási eredményeiket a Lovagok valósítják meg.}
{188}{Rhom42}{Õk a fegyverek készítõi.}
{189}{Rhom43}{A Hub délre található, szoktunk velük kereskedni.}
{190}{Rhom44}{Kérdezd Vree-t! Õ majd tudja.}
{191}{Rhom45}{Nem vagyok felhatalmazva, hogy beszéljek errõl. Keresd meg ez ügyben a Nagyperjelt!}
{192}{Rhom46}{A Csonttelep messzi délen van. Csak erõszakot találni ott.}
{193}{Rhom47}{Errõl nem tudok mit mondani.}
{194}{Rhom48}{Errõl nem tudok mit mondani.}
{195}{Rhom49}{Nincs ilyesmirõl tudomásom.}
{200}{}{Új vagyok még itt, és nem tudom, mi a dörgés.}
{201}{}{Nem fogok én semmit elmagyarázni neked, te szörnyszülött.}
{202}{}{Köszönöm, viszlát!}
{203}{}{Menj a pokolba!}
{204}{}{Miközben megpróbálod kinyitni, az ajtó megnyikordul.}
{205}{}{A tudásod lehetõvé teszi, hogy zajtalanul lopj innen. Az ajtó kinyitásával semmilyen zajt nem csaptál.}
{206}{}{Ki van ott?}
{207}{}{Megriasztottak, ezért eleljtetted a zsákmányt.}
{208}{}{Ez a szekrény nincs bezárva.}
{209}{}{Hagyd el a körletemet!}
{210}{}{Ártatlan vagyok!}



{980}{Rhom47}{Errõl nem tudok mit mondani.}
{981}{Rhom48}{Sosem hallottam róla.}
{982}{Rhom49}{Nincs ilyesmirõl tudomásom.}

#
# Rhombus Tell-Me-Abouts
#


{1000}{}{Vree}
{1001}{}{Rhombus}
{1002}{}{Talus}
{1003}{}{Perjel}
{1004}{}{Kronikas}
{1005}{}{Lovag}
{1006}{}{Hub}
{1007}{}{Lemez}
{1008}{}{Hadsereg}
{1009}{}{Csonttelep}
{1010}{}{Paladin}
{1011}{}{Mester}
{1012}{}{Háborû}
{1013}{}{Exodus}
{1014}{}{Furcsa hadsereg}
{1015}{}{Kereskedo}
{1016}{}{Eltunt karavan}
{1017}{}{A Katedralis Gyermekei}
{1018}{}{Ujonc}
{1019}{}{Csip}

{1100}{Rhom38}{Õ a Fõkrónikásunk. A könyvtárban megtalálod.}
{1101}{Rhom39b}{Én vagyok Rhombus.}
{1102}{Rhom39a}{Talus a helyettesem.}
{1103}{Rhom40}{Maxson tábornok volt a valaha élt legnagyobb Fõpaladin. Amikor Nagyperjel lett belõle, én vettem át a posztját.}
{1104}{Rhom41}{Õk sokszorosítják a fegyverdokumentációkat, és új ötletek kiagyalói. A kutatási eredményeiket a Lovagok valósítják meg.}
{1105}{Rhom42}{Õk a fegyverek készítõi.}
{1106}{Rhom23}{A Hub és a Csonttelep dél felé vannak, a hegyvidék keletre, északra pedig kietlen pusztaságot találsz. Akárki is megy oda, sosem tér vissza.}
{1107}{Rhom44}{Kérdezd Vree-t! Õ majd tudja.}
{1108}{Rhom45}{Nem vagyok felhatalmazva, hogy beszéljek errõl. Keresd meg ez ügyben a Nagyperjelt!}
{1109}{Rhom46}{A Csonttelep messzi délen van. Csak erõszakot találni ott.}
{1110}{Rhom13}{Nem igazán érted, mirõl szól paladinnak lenni. Elég nagy baj ez.}
{1111}{Rhom44}{Kérdezd Vree-t! Õ majd tudja.}
{1112}{Rhom21}{Beszélj Vree-vel a fõkönyvtárban!}
{1113}{Rhom21}{Beszélj Vree-vel a fõkönyvtárban!}
{1114}{Rhom10}{Keringenek mendemondák egy furcsa hadsereg gyülekeztérõl, de nem áll módomban errõl többet mondani.}
{1115}{Rhom21}{Beszélj Vree-vel a fõkönyvtárban!}
{1116}{Rhom47}{Errõl nem tudok mit mondani.}
{1117}{Rhom49}{Nincs ilyesmirõl tudomásom.}
{1118}{Rhom21}{Beszélj Vree-vel a fõkönyvtárban!}
{1119}{Rhom49}{Nincs ilyesmirõl tudomásom.}
