{100}{}{Ez itt Rutger.}
{101}{}{Helló, üdvözlünk a Hosszútávú Kereskedõknél. Miben segíthetek?}
{102}{}{Tudtok vizet szállítani?}
{103}{}{A munkahirdetésre jöttem.}
{104}{}{Munkát keresek.}
{105}{}{Mivel foglalkoztok itt?}
{106}{}{Semmiben. Szia!}
{107}{}{Gak!}
{108}{}{Sóhereket nem alkalmazunk! Tûnés!}
{109}{}{Hmmmm. Nagy kár, hogy nincs elég eszed ehhez a bivaly erõhöz. Nagy hasznát vettük volna egy hozzád hasonló embernek.}
{110}{}{Nos, mi bizony tudunk vizet szállítani, de ez pénzbe kerül ám. Mennyit szeretnél, és hova menne az áru?}
{111}{}{Annyi kell, hogy egy egész Menedéket ellásson. Észak felé van, Roncsvároson túl, a hegyek közt.}
{112}{}{Annyi kell, hogy egy egész Menedéket ellásson. Észak felé van, a hegyek közt.}
{113}{}{Az összes létezõ víz kell! Egy nap, szeretném átváltoztatni a bolygó felszínét. Majd meglátod!}
{114}{}{Egy egész Menedéket? Meg vagy húzatva? Ennyi vízhez nem tudunk hozzáférni. Ezenkívül eszem ágában sincs a hegyek közé menni. Éppen elég eltûnt karavánunk van már.}
{115}{}{Szóval nem... és van valaki, aki esetleg igen?}
{116}{}{Nos, mi a helyzet a meghirdetett munkával?}
{117}{}{Szóval... van valami munkátok?}
{118}{}{Nem sokat segítettél, de azért kösz.}
{119}{}{Ó, elnézést, nem idevalósi vagy. Ebben a városban az összes víz felett a Vízkereskedõk rendelkeznek. Nekem eszembe nem jutna velük kereskedni. Egy rakás dögkeselyû az egész banda.}
{120}{}{Hol találom õket?}
{121}{}{Oké, kösz.}
{122}{}{Nem lehet elmenni mellettük. Délre vannak, amellé az átkozott víztorony mellé fészkelték be magukat.}
{123}{}{Megkérdezném azért... mivel foglalkoztok itt?}
{124}{}{Oké, kösz.}
{125}{}{Én vezetem a... úgy értem, segítek a Hosszútávú Kereskedõknek. Ha valaki idetolja a képét, velem kell lerendeznie az ügyes-bajos dolgát. Az összes létezõ településsel kereskedést folytatunk.}
{126}{}{Már elmondtam. Butch és én vezetjük a Hosszútávú Kereskedõket. Miért is jöttél?}
{127}{}{Miféle dolgokkal kereskedtek?}
{128}{}{Érdekes, nem mondom. Na, szia!}
{129}{}{Remek! Mi a helyzet a meghirdetett munkával?}
{130}{}{Ez jól hanzik. Nincs szükségetek segítségre?}
{131}{}{Hát bizony majdnem mindenfélével kereskedünk. Drog, abroncsok, fegyverek, lõszer, élelmiszer, brahmin, termõföld, sõt még fémhulladékkal is.}
{132}{}{Termõföld? Fémhulladék?}
{133}{}{Öh... ez nem semmi, de most mennem kell.}
{134}{}{Meglepõdnél, mi mindent nem akarnak az emberek. Ami az egyik helyen tök természetes, tíz mérfölddel arrébb hiánycikknek számíthat.}
{135}{}{Oké, elég a kereskedõs dumából. Merre van a kijárat?}
{136}{}{Kösz szépen, minden jót!}
{137}{}{Tudnál mondani valamit a meghirdetett munkáról?}
{138}{}{Van valami munkátok?}
{139}{}{Hallottam, hogy egy kicsit merész vagy, de most épp erre van szükség. Beszélj Butch barátommal! Õ minden újonccal szeret elbeszélgetni. Közvetlenül a mögöttem lévõ szobában megtalálod. Menj csak be!}
{140}{}{Nem hinném, hogy pont egy gyerekgyilkosra volna szükségünk a karavánjaink mellett.}
{141}{}{Gyerekgyilkos? Csak baleset volt!}
{142}{}{Én nem válogatok. Ha valami az utamba áll, nem érdekel, hány éves, felkenem a falra.}
{143}{}{Hát, balesetek történnek, tudom. Nagyon elcseszett világ ez. Egyelõre nem igazán tudom, megbízzak-e benned. Menj, beszélj Butch barátommal! A szomszéd szobában megtalálod.}
{144}{}{Baleset ám a valagam! Ismerem a fajtádat! Azt hiszitek, bármit megtehettek. Lehet, hogy így van, de nem itt, haver! Na mindegy, beszélj Butch barátommal, de szemmel tartalak! A mögöttem lévõ ajtón ha átmész, megtalálod õt.}
{145}{}{Baleset ám a valagam! Ismerem a fajtádat! Azt hiszitek, bármit megtehettek. Lehet, hogy így van, de nem itt, bébi! Na mindegy, beszélj Butch barátommal, de szemmel tartalak! A mögöttem lévõ ajtón ha átmész, megtalálod õt.}
{146}{}{Te egy könyörtelen mocsok vagy! Akár még kellhetsz is nekünk, de ez nem jelenti azt, hogy egyet is értek módszereiddel. A legjobb, ha békén hagyod az itteni gyerekeket, különben téged is felkenünk a falra. Eridj, beszélj Butch barátommal. A mögöttem lévõ irodában megtalálod.}
{147}{}{Munkát keresel? Jó dolgokat hallottam rólad. Az ilyen hírnévnek örvendõ embereket mindig szívesen látjuk. Menj, beszélj, Butch barátommal! A mögöttem lévõ szobában megtalálod õt.}
{148}{}{Szóval munkát keresel, mi? Nem tûnsz veszélyes alaknak. Minden bizonnyal beszélned kéne Butch barátommal. A mögöttem lévõ irodában megtalálod õt.}
{149}{}{Azt hittem, nem akarod a munkát. Mit is akarsz valójában?}
{150}{}{Nem is akarom. Csak egy utolsó pillantást akartam vetni arra a randa pofázmányodra.}
{151}{}{Elnézést, de nagyon kellett ez a munka. Felvennétek? Kérlek...}
{152}{}{Semmit.}
{153}{}{Grudda!}
{154}{}{Húzz innen a fenébe, te francos Sóher!}
{155}{}{Jól van. bárcsak meggondolnád magad. Elfoglalt ember vagyok... hadd mondjam el a részleteket.}
{156}{}{Annyit nem érsz, mint a tököm. Húzás innen kifelé!}
{157}{}{Mire akarsz te rábeszélni engem? Megmondtam, hogy Butch a te embered. Vele kell beszélned! Ha neki megfelelsz, orrodra kötöm a részleteket.}
{158}{}{Mi? Még nem mentetek el?}
{159}{}{Hogy halad a keresés?}
{160}{}{Nem nagyon találok én semmit...}
{161}{}{Elmondanád, kérlek még egyszer a munka részleteit?}
{162}{}{Van valami karaván melletti munkátok?}
{163}{}{Bocs, de most mennem kell.}
{164}{}{Rúúú?}
{165}{}{Hát, én nem mondtam, hogy könnyû lesz. Ha úgy lenne, már régen megoldottuk volna magunk a problémát. Kérdezgess körbe! Ha kell, ne fogd vissza magad, de a vérontást kerüld! Legalábbis ne mindenki szeme láttára!}
{166}{}{Mondok én valamit... szokj le a drogról. Csak tönkremész tõlük.}
{167}{}{A munkáért 500 hubdolcsit fizetünk. Ezt akkor kapod meg, ha pontosan el tudod magyarázni Butch-nak, mi történt a mostanában eltûnt karavánokkal. Gyûjts össze minden létezõ információt! Én személy szerint úgy vélem, hogy azok az átkozott Vízkereskedõk, esetleg az Acél Testvériségének fegyvermániákusai a ludasok. Butch szerint valami halálos karom is lehet az ügyben. Nézz be esetleg Beth-hez, õ többet tudhat errõl!}
{168}{}{Rendben, bár nem tudom, mit nem sikerült megjegyezni. Újdonságokkal természetesen nem tudok szolgálni.}
{169}{}{Biztosra vettem, hogy onnan jöttél. Próbára akartalak tenni. Viszont ha nem onnan vagy, honnan a francból van ilyen acélöltözéked, amiben õk szoktak flangálni?}
{170}{}{Ja, hogy ez? "Találtam", ha érted, mire gondolok.}
{171}{}{Nem áll módomban beszélni.}
{172}{}{Az istenit, te aztán nem semmi alak vagy. Örülök, hogy a mi oldalunkon állsz. Nem tudom, hogy nem tudsz róla, de a Testvériség egy nagyon furcsa társaság, akik a technológia elõtt hajtanak fejet, vagy valami ilyesmi. Nagyjából észak-kelet felé vannak tõlünk.}
{173}{}{Mi az az Acél Testvérisége?}
{174}{}{Leteszem a nagyesküt, hogy nincs köze a Testvériséghez.}
{175}{}{Mit tudsz a Halálkarmokról?}
{176}{}{Merre van Beth?}
{177}{}{Kösz, helló.}
{178}{}{Mondj, amit akarsz. Biztos vagyok benne, hogy mÁr találkoztál velük korábban. Fura egy társaság, akik a technológia elõtt hajbókolnak, vagy valami ilyesmi. Észak-nyugat felé megtalálod õket.}
{179}{}{Õk aztán igazán furcsa népség. A technológia elõtt hajbókolnak, vagy valami ilyesmi. Iszonyatos tûzerejû fegyvereik vannak. Egy karavánt simán lenyomnának. Észak-nyugat felé megtalálod õket.}
{180}{}{Tudtam, hogy közéjük tartozol. Ilyen öltözékkel nem is lehet másképp. Remélem, igazad van, és azt is remélem, hogy nem követünk el hibát azzal, hogy felbérelünk. Mivel nem te vagy az egyetlen, akit így fogadtunk fel, szerintem nem lehet gond.}
{181}{}{Miért mondod ezt?}
{182}{}{Azért, mert nemrég csatlakoztam a rendjükhöz, és alaposan kiismertem õket. Csendes, maguknak való társaság, nincs mitõl félni tõlük.}
{183}{}{Voltam a bunkerjükben. Õk nem azok, akiknek hiszed õket.}
{184}{}{Megérzés...}
{185}{}{Hm, azt kell mondjam, ez megnyugtató.}
{186}{}{Remélem, igazad van.}
{187}{}{A megérzéssel nem sokra megyünk. Bizonyítékra van szükség.}
{188}{}{Beth-et megtalálod, ha kimész azon az ajtón, és jobbra haladsz. Õ vezeti a fegyverboltunkat. Mondd meg neki, hogy nálunk dolgozol, és 15 százalék engedményt kapsz.}
{189}{}{Jaja, Halálkarom, vagy tökmindegy. Mindenki megkergült. Az egész csak az emberek vad képzelgése miatt létezik. Nincs se szellem, se szörny, semmise, aminek hiszik azt az izét. Maradjunk a realitás talaján, és mindenki jól jár.}
{190}{}{Igen? Miben segíthetek?}
{191}{}{Tudom, mi történik a karavánjaitokkal.}
{192}{}{Semmiben.}
{193}{}{Mia.}
{194}{}{Grrr.}
{195}{}{Tényleg? Na, ki az a mocsok? A Vízkereskedõk?}
{196}{}{Bezony, õk azok! Már beindultak, hogy elkapjanak titeket. A... brahminjaitok kellenek nekik.}
{197}{}{Az a helyzet, hogy egy csapat HATALMAS mutáns mûve az egész.}
{198}{}{A Halálkaromok voltak. Láttam, ahogy egy egész karavánt esznek.}
{199}{}{Elfelejtettem.}
{200}{}{Elfelejtetted? Nagyon vicces gyerek vagy. Na, húzz el innen, amíg jól van dolgod!}
{201}{}{Elfelejtetted? Nagyon vicces csajszi vagy. Na, húzz el innen, amíg jól van dolgod!}
{202}{}{Tudtam, hogy õk azok. Szereztél bizonyítékot? Majd most megfizetnek azok a mocsadékok!}
{203}{}{Öhh. Nem. Elveszítettem. De hihetsz a szavamban.}
{204}{}{Az a helyzet, hogy nem õk voltak, hanem egy rakás hatalmas mutáns.}
{205}{}{Bocs, de most mennem kell.}
{206}{}{Bizonyíték nélkül vajmi keveset tehetek. Nem akarok újabb kereskedõháborút. Ha hozol bizonyítékot, a törvény elé viszem a dolgot, és kicsináljuk õket.}
{207}{}{Szart nem érsz a szememben! Tûnés kifelé a szemem elõl!}
{208}{}{Mi? Hogyan? Ez lehetetlen. Te bizonyára viccelsz. Ugye csak viccelsz?}
{209}{}{Hát, sajnálom, hiszed vagy sem, de egy rakás hatalmas mutáns volt a bûnös.}
{210}{}{Szörnyû volt. Ilyen... nagy, hegyes fogai voltak...}
{211}{}{Egy egész karavánt? Tényleg? Szerinted tényleg ilyen naív vagyok? Menj a dolgodra, és találd ki, hogy ténylegesen ki áll a karavánok eltûnése mögött!}
{212}{}{Szóval hatalmas mutánsok tizedelik a karavánjaimat? Ez majdnem ugyanolyan jó, mint a Halálkarmos történet.}
{213}{}{Nem viccelek. Találtam egy-két Halálkarmot, és meg is öltem õket, ezt a hololemezt viszont azt egyik... szupermutánsnál találtam.}
{214}{}{Itt van ez a hololemez. Az egyik rajtaütést végrehajtó mutánsnál találtam.}
{215}{}{Igazat beszélek. Ott voltam, és láttam. Hozok inkább bizonyítékot...}
{216}{}{Jól van, ne higgy nekem...}
{217}{}{Most mennem kell.}
{218}{}{Hey, I know how to use one of those. Butch got some gizmo from some scout from the Brotherhood a long time ago that can read these things. Let's see... [Rutger inserts the disk into the device and quickly reads its contents] ...Sorry I didn't believe you. This does not bode well for the good guys. Well, here's your 500 caps. Hell, make it 800, and thanks for the information! If you need anymore work you will always be welcome.}
{219}{}{Kérlek, ne tüzeld jobban Butch paranoiáját. Egy kicsit túlérzékeny, amikor a Halálkarmokra kerül sor. Most pedig mondd el nekem, ha találtál valami érdemlegeset. Ugye a Vízkereskedõk csinálák a fesztivált?}
{220}{}{Igen, õk! Már beindultak, hogy elkapjanak titeket. A... ööö... brahminjaitok kell nekik.}
{221}{}{Az a helyzet, hogy egy csapat HATALMAS mutáns mûve az egész.}
{222}{}{A Halálkaromok voltak. Láttam, ahogy egy egész karavánt esznek.}
{223}{}{Elfelejtettem.}
{224}{}{Patkányok, mi? Találtál valamit vagy sem? Tudom, hogy azok a megveszekedett Vízkereskedõk a bûnösök!}
{225}{}{Igen, õk! Már beindultak, hogy elkapjanak titeket. A... ööö... brahminjaitok kellenek nekik.}
{226}{}{Az a helyzet, hogy egy csapat HATALMAS mutáns mûve az egész.}
{227}{}{A Halálkaromok voltak. Láttam, ahogy egy egész karavánt esznek.}
{228}{}{Elfelejtettem.}
{229}{}{Szóval hatalmas mutánsok tizedelték a karavánjaimat? Ez majdnem ugyanolyan jó, mint a Halálkarmos történet.}
{230}{}{Nem viccelek. Találtam egy-két Halálkarmot, és meg is öltem õket, ezt a hololemezt viszont azt egyik... szupermutánsnál találtam.}
{231}{}{Itt van ez a hololemez. Az egyik rajtaütést végrehajtó mutánsnál találtam.}
{232}{}{Igazat beszélek. Ott voltam, és láttam. Hozok inkább bizonyítékot...}
{233}{}{Most mennem kell.}
{234}{}{Tehát van valami bizonyítékod, ki szarakodik a karavánjaim... ööö a karavánjainkkal?}
{235}{}{Igen. Itt egy hololemez. Az egyik óriási mutánsnál találtam.}
{236}{}{Nem, még mindig kutakodom. Van valami ötleted, merre induljak?}
{237}{}{Nem, de majd szólok.}
{238}{}{Gak!}
{239}{}{Nos, ha valóban léteznek a Halálkarmok, szemügyre kéne venni a búvóhelyüket. Lehet, hogy elárulna egy-két dolgot.}
{240}{}{Üdvözlet. Miben segíthetek?}
{241}{}{Rájöttem, mi történt az eltûnt karavánokkal.}
{242}{}{Semmiben, kösz.}
{243}{}{Szevasz! Hallottam, hogy megölted azt a mocskot, aki azokat a mutánsokat vezette. Nem rossz! Valószínûleg az összes Hublakó életét megmentetted ezzel. Mondjuk érdekelne, honnan származnak.}
{244}{}{Ez az! Hulljon a férgese! Kiváncsi vagyok, hol rejtõznek.}
{245}{}{Igen, teljesen meg kell tisztítanom a vidéket a Mester gonosz ügyködésének nyomaitól. Kiváncsi vagyok, hol bújkálnak.}
{246}{}{Teljesen igazad van! Kiváncsi lennék, hol rejtõztek el.}
{247}{}{Kéne egy kis pénz. Nincs valami munkátok?}
{248}{}{Csak teszem a dolgomat. Minden jót neked!}
{249}{}{Ja, tomboltam egy kicsit. Illetve... Úgy értem... Gruk-Csákk!}
{250}{}{Szeva, haver. Hogy ityeg a fityeg?}
{252}{}{Szia, szépségem. Hogy ityeg a fityeg?}
{253}{}{Hogy van az én kedvenc hölgyeményem?}
{254}{}{Jól van, kösz. Van még munkátok?}
{255}{}{Királyul ityeg! Csak beugrottam, hogy megnézzem, rendben mennek-e a dolgok.}
{256}{}{Jogva?}
{257}{}{Minden a legnagyobb rendben! A mutánsok abbahagyták a rajtaütéseiket, az árucsere visszazökkent a régi kerékvágásba. Igazság szerint még jobb is, mint régebben. Rendes tõled, hogy érdeklõdsz.}
{258}{}{Hallottam, hogy megsemmisítettél valami bázist, ahova az a sok francos mutáns befészkelte magát! Remek munka volt! Kár, hogy a vezetõjüket nem tudtad becserkészni.}
{259}{}{Jaja! Gyilkolászik az ember gyereke... Kiváncsi vagyok, hol rejtõzködhet a Mester.}
{260}{}{Igen, el kell pusztítanom a Mestert. A gonosznak egyetlen pici esélyt sem szabad adni, hogy újra szétterjedjen a világban. Kiváncsi lennék, hol bújkál a Mester.}
{261}{}{A mester hamarosan találkozik a teremtõjével.}
{262}{}{Igazad van! Kiváncsi vagyok, hol bújkál a Mester.}
{263}{}{Elõször egy kis pénzre volna szükségem. Van valami munkátok?}
{264}{}{Ja, tomboltam egy kicsit. Illetve... Úgy értem... Gruk-Csákk!}
{265}{}{Na most, hallottam, hogy egyesek láttak szétszórt mutánsbandákat messze észak-nyugaton. Jóval az Acél Testvérisége fölött.}
{266}{}{Jó, ha tudod, a mutánsok megsemmisítése óta a Katedrális Gyermekei "szerfelett" furcsán viselkednek. Volt szerencsém kihallgatni az egyiket, amint épp rólad beszélt. Úgy tûnik, égre-földre keresnek téged.}
{267}{}{Nos, a dolgok nem mennek olyan hû de nagyon jól. Azok a mutánsok továbbra is fejtörést okoznak a Karavánjainknak. Majdnem az összes karavánutat törölni kellett. Azért rendes tõled, hogy érdeklõdsz.}
{268}{}{Hogyne, téged szívesen látnánk az egyik karavánunk mellett. Szoktál õrzõ-védõ munkát vállalni? A fizetség a szokásos, 400 hubdolcsi. Érdekel?}
{269}{}{Érdekel.}
{270}{}{Nem.}
{271}{}{Hogy? Mi van a hiányzó karavánokkal?}
{272}{}{Lehet-e jobb módot találni arra, hogy elkapd a tolvajokat, minthogy csatlakozol egy karavánhoz?}
{273}{}{Majd nyitva tartom a szemem, de elõbb pénzre van szükségem.}
{274}{}{Felejtsük el.}
{275}{}{Rendben, de szólj majd, ha meggondoltad magad. Az esetek többségében könnyû keresetrõl van szó.}
{276}{}{Remek, beszélj a karaván vezetõjével a fõbejáratnál, õ majd elmondja, mikor indul a következõ karaván. Amíg jól végzed a munkádat, a vezetõk mindig számítanak rád.}
{277}{}{Adok egy utolsó esélyt. A fizetség 400 hubdollár. Beszélj a karaván vezetõjével a fõbejáratnál, õ majd elmondja, mikor indul a következõ csapat.}
{278}{}{Bocs, de eljátszottad az esélyedet. Azt hiszem, jobb lenne, ha távoznál.}
{279}{}{Te viccelsz? Éppen hálás vagyok azért, amit tettél, de a múltbeli dolgokat nem fogom egykönnyen elfelejteni. Azt hiszem, jobb lenne, ha távoznál.}
{280}{}{Nem hallottad kristálytisztán? Nem bérelünk fel. Légy szíves, menj el innen!}
{281}{}{Nem hinném, hogy túl sok mindent megváltoztatna, de dolgozhatsz nálunk, ha akarsz.}
{282}{}{Ezt miért mondod?}
{283}{}{Igazad van, még szaglászom egy kicsit.}
{284}{}{Jól van, elfogadom a munkát.}
{285}{}{Remek. Ne felejts el kérdezõsködni!}
{286}{}{Hát, jó. Beszélj a fõbejáratnál álló karavánvezetõvel, õ elmondja, mikor indultok. Amíg jól végzed a munkádat, a vezetõk mindig számítanak rád.}
{287}{}{Persze, de ne velem beszélj, hanem a karavánvezetõnkkel!}
{288}{}{[More]}
{289}{}{Ez így van, lehet, hogy sok karavánt veszítünk el, de ez az üzletnek csak egy apró hányadát teszi ki. Annak az esélye, hogy éppen azt a karavánt támadják meg, amely mellett dolgozol, meglehetõsen kicsi. Akárki is mûveli ezt velünk, vagy nagyon nagy erõkkel rendelkezik, vagy szerfelett hatékonyak.}
{290}{}{Rendben van. Akkor még körbekérdezgetek. }
{291}{}{Hát, bizony kéne a pénz.}
{292}{}{Üdv újra nálunk. Mit ehetek... pontosabban, mit tehetek érted?}
{293}{}{Örülök, hogy újra látlak.}
{294}{}{Azon tûnõdtem, vajon vizet szállítotok-e?}
{295}{}{A meghirdetett munka ügyében jöttem.}
{296}{}{Munkát keresek.}
{297}{}{Mit csináltok itt?}
{298}{}{Bocs, de most mennem kell.}
{299}{}{Rarwa.}
{300}{}{Ja, mi a fenét akarsz?}
{301}{}{Kezd nagyon elegem lenni belõled. Mit akarsz?}
{302}{}{Micsoda?!}
{303}{}{Te mindig ilyen tenyérbemászóan viselkedsz?}
{304}{}{Mit akarsz, a fenébe?!?!}
{305}{}{Azon tûnõdtem, vajon vizet szállítotok-e?}
{306}{}{A meghirdetett munka ügyében jöttem.}
{307}{}{Munkát keresek.}
{308}{}{Mit csináltok itt?}
{309}{}{Bocs, de most mennem kell. }
{310}{}{Tuka?}
{311}{}{A fõnök ki van akadva rád. Menj innen a fenébe!}
{312}{}{Nagy esély van rá, hogy sikerült rájönnöm, mi történt az eltûnt karavánokkal.}
{313}{}{Nagyszerû! Mondd el Butch-nak, mit találtál, és szólj, ha megkaptad a jutalmadat!}
{314}{}{Grdddle Snpp!!!}
{315}{}{Bocs, de... mentális problémákkal küzdõ emberekkel, hogy úgy mondjam, nem szoktunk munkakapcsolatot létesíteni.}
