{100}{}{Krónikás.}
{101}{}{Üdvözlet, }
{102}{}{ Testvér! Miért nem csatlakozol hozzánk egy kis meditációra?}
{103}{}{Elnézésed kérem, }
{104}{}{ Testvér, de most meditálunk.}
{105}{}{A technológiát át kell menteni az utókor számára.}
{106}{}{A meditáció lenyugtatja a lelket, és megtisztítja az elmét.}
