{100}{}{Krónikás.}
{101}{}{Vree a bálványom.}
{102}{}{Vree annyira jól néz ki.}
{103}{}{Nem mondom, Sophia nagyon csinos...}
{104}{}{Derek jó ember.}
{105}{}{Vajon az univerzum tovább tágul, vagy egyszercsak magába omlik?}
{106}{}{Imádom a régi könyveket és magazinokat, de olyan nehéz találni belõlük.}
{107}{}{A tudás hatalom.}
{108}{}{A tollnak nagyobb ereje van, mint a kardnak.}
{109}{}{Át kell menteni a technológiát.}
{110}{}{A tudomány annyira szórakoztató.}
{111}{}{Régebben láttam egy idegen ûrhajót.}
{112}{}{Tudtad, hogy a nap gyakorlatilag egy nagy nukleáris reakció? Hasonlít arra, amely megsemmisítette a világunkat. Annyi a különbség, hogy nem maghasadásnak, hanem fúziónak hívják.}
{113}{}{Hallottál arról, hogy a fekete lyuk valójában ablak egy másik univerzumra? Papíron kidolgoztam az egészet. Nagy kár, hogy még sokkal a halálom után sem valósul meg az ûrutazás.}
{114}{}{Tudtad, hogy a hidrogénatom 99.9843425 százaléka üresség?}
{115}{}{Egy szép napon megvalósul az idõutazás, ezért a múltban képesek leszünk megakadályozni a világunkat leromboló katasztrófát. Mondjuk, nem az történne, hogy... nem tudnánk visszajönni?... megfájdul a fejem az ilyenektõl.}
