{100}{}{Seth, aki tudja az utat Shady Sands-be.}
{101}{}{Siessünk, és szabaduljunk meg azoktól a Radskorpióktól!}
{102}{}{Igyekezzünk vissza Shady Sands-be, és tudassuk velük, hogy elmúlt a radskorpió-veszély.}
