{100}{}{A Vesztõhely ajtaja zárva van.}
{101}{}{Sikerül kinyitnod a zárat.}
{102}{}{Elszöszmötölsz az ajtóval, de nem sikerül kinyitnod.}
{103}{}{Hallod, ahogy elpattan valami. Úgy látszik, beragadt a zár.}
{104}{}{Az ajtó nincs bezárva.}
