{100}{}{Egy zombi.}
{101}{}{Sok bûnt követett el. Imádkozni fogok a megváltásáért. }
{102}{}{Éljen a Mester! Éljen a Szentséges Láng! Éljen a Béke és az Egység! }
{103}{}{Üdvözlöm, gyermekem. Miért tart magánál fegyvert? Esetleg útmutatásra van szüksége a békét illetõen? }
{104}{}{Dícsértessék a Mester, amiért hosszú idõ után végre találtam egy helyet, ahol letehetem a fegyvert és magamhoz ölelhetem a békét! }
{105}{}{Jól hangzik. Ki lenne az útmutatóm? }
{106}{}{Õrszolgálatban vagyok. }
{107}{}{Jól hangzik, nem mondom. Elfogadnék egy kis útmutatást, aztán egy hátmasszázst... }
{108}{}{Van itt valami misebor ebben a kócerájban? }
{109}{}{Ez a hely tök gáz! A Mester alaposan benne van a hatalmi játszmában, és én részt akarok az akcióból. Hol van most? }
{110}{}{Azt állítja tehát, hogy hülye vagyok? }
{111}{}{Üdvözlöm! Szép idõnk van, nem igaz? }
{112}{}{Igen, de vihar van készülõben. A Katedrális ellenségei mindenütt ott leselkednek. Milyen pletykákat hallott? }
{113}{}{Láttam már jobbat is. Ki itt a góré? }
{114}{}{Igen, szép idõnk van. }
{115}{}{Szép az idõ, ha nem zavarja a radioaktív barnulás. }
{116}{}{Van itt valami misebor ebben a kócerájban? }
{117}{}{Szarom le az idõt. Azért jöttem, hogy megöljem a Mestert. Hol van az a punk? }
{118}{}{Igen. Süt. Napocska jó. }
{119}{}{Üdvözlet, barátom. Örülök, hogy látom. Tegye le nyugodtan a fegyvert, itt barátok közt van! }
{120}{}{Elnézést, kemény hét áll mögöttem. Mit tudna mondani errõl a helyrõl? }
{121}{}{Elnézést, engem világ életemben elõvigyázatosságra neveltek. Szóval ki itt a vezetõ? }
{122}{}{Szóval barátok? Ez különös, ugyanis elég rossz dolgokat hallottam magáról. }
{123}{}{Jó tudni, hogy itt barátok közt van az ember. Hogy mennek a dolgok? }
{124}{}{Barátok közt? Mennyire áll szándékában barátságosnak lenni? }
{125}{}{Van itt valami misebor ebben a kócerájban? }
{126}{}{Fegyver? }
{127}{}{Üdvözlöm, idegen. Bocsásson meg nekem, de a Katedrálisban ne vegye elõ a fegyverét! }
{128}{}{A fegyveremet a Katedrális és a Mester szolgálatába akarom állítani. Van ezzel valami problémája? }
{129}{}{Köszönöm. Erre biztos emlékezni fogok. }
{130}{}{Régi, javíthatatlan berögzõdés ez. Mostanában egész sokminden próbált az életemre törni. Mit lehet tudni errõl a helyrõl? }
{131}{}{Van itt valami misebor ebben a kócerájban? }
{132}{}{Fegyver? }
{133}{}{Üdv, barátom! Ha megváltásért jött, örömmel látjuk, de azt ajánlom, tegye el a fegyverét... }
{134}{}{A fegyveremet a Katedrális és a Mester szolgálatába akarom állítani. Van ezzel valami problémája? }
{135}{}{Hogyne. Megváltás. Jól hangzik... }
{136}{}{Régi, javíthatatlan berögzõdés ez. Mostanában egész sokminden próbált az életemre törni. Mit lehet tudni errõl a helyrõl? }
{137}{}{Ajánlgasson csak nyugodtan bármit, de ha még szeretne egy darabig lélegezni, elmondja szépen, amit tudni akarok! }
{138}{}{Megváltás ám a kis valagam, maga zombi! }
{139}{}{Van itt valami misebor ebben a kócerájban? }
{140}{}{Fegyver? }
{141}{}{Üdv, barátom! Annyira örülök, hogy csatlakozott az ügyünkhöz! }
{142}{}{Egyelõre nem, de érdekel a dolog. A Békét és az Egységet leszámítva miféle dolgokkal foglalkoznak maguk itt? }
{143}{}{Így kellett történnie. Amúgy a beavatáshoz kit kell felkeresnem? }
{144}{}{Útmutatásért jöttem. Láthatom a Mestert? }
{145}{}{Barátok közt? Mennyire akar barátságos lenni? }
{146}{}{Van itt valami misebor ebben a kócerájban? }
{147}{}{Hejhó! Az Ügyünk! Hejhó!? }
{148}{}{Üdvözlöm, idegen! Segíthetek valamiben? }
{149}{}{Hogyne, hallottam az üzenetüket, és többet szeretnék tudni magukról! }
{150}{}{Az itteni vezetõt keresem. }
{151}{}{Ez a béke meg egység balhé nem létezik, hogy komoly. }
{152}{}{Ki ez a Mester nevû ficere? }
{153}{}{El tudnék viselni egy teljes testmasszázst meg egy kis extrát is, ha nem gond. Lehet róla szó? }
{154}{}{Van itt valami misebor ebben a kócerájban? }
{155}{}{Segíteni akar? Öh.. nem, kösz. }
{156}{}{Bocsásson meg nekem, idegen, de nagyon sok dolgom van. Kérem, legyen elnézõ. }
{157}{}{Éljen a Mester! Éljen a Béke! Éljen a Szentséges Láng! Éljen az Egység! }
{158}{}{Ez a béke dolog jöhetne éppen, de minek kell ehhez a Mester? Miért olyan fontos õ? }
{159}{}{Az itteni vezetõt keresem. }
{160}{}{Ez a béke meg egység balhé nem létezik, hogy komoly. }
{161}{}{Ki ez a Mester nevû ficere? }
{162}{}{Van itt valami misebor ebben a kócerájban? }
{163}{}{Tudnám javasolni, hogy keresse fel Ostoros Testvérünket. Kemény ember, de ugyebár a Mester útjai kifürkészhetetlenek. Ég áldja!}
{165}{}{Nekünk nincsenek õreink, kivéve persze az Éjfajzatokat. Mirõl is beszél tulajdonképp? }
{166}{}{A Mester megerõsíttette a biztonsági készenlétet. Nem tudom, miért, hiszen az Éjfajzatok elég védelmet adnak. Van valami ötlete, mi folyhat itt? }
{167}{}{Valaki tojt a parancsaimra. Ne rajtam kérje számon! }
{168}{}{Én nem tartozom a Katedrális õrségéhez. Járõr vagyok. }
{169}{}{Nem? A francba! }
{170}{}{Én... ööö... szóval semmi olyasmi, amit ne lehetne lerendezni egy golyóval. Most pedig véged! }
{171}{}{Bocsánatot kérek. Dícsértessék a Mester, és legyen szép napja! }
{172}{}{Talán máskor. }
{173}{}{Nem hinném, hogy volna nekünk ilyesmink. Dícsértessék a Mester, biztos vagyok benne, hogy ez csak a legjobbaknak jár. }
{174}{}{Biztos is! [nyögés]. }
{175}{}{Miféle Katedrális az, ahol még misebor sincs? }
{176}{}{Helyes, ezek szerint, ha kijózanodtam, meg kell, hogy öljem. Áh, inkább most... Halál rád, mocsadék! }
{177}{}{Sokan próbálták már megölni a Mestert, és mind csõdöt mondtak. Mindazonáltal, ha letenne errõl az aljas tettrõl, a Mester megbocsáthatna, és megfelelõ hasznát vehetné magának. Imádkozni fogok a lelkéért. }
{178}{}{Csak vicceltem... azokra, akik túl sok idõt töltenek a pusztaságban, elég furcsa humor ragad az idõk folyamán. Tehát mit is érdemes tudnom errõl a helyrõl? }
{179}{}{Majd meglátjuk... }
{180}{}{Az én lelkemért ugyan senki ne imádkozzon! Ellenben jó lesz, ha valaki a maga lelkéért most azonnal elkezd imádkozni, ugyanis helyben megölöm! }
{181}{}{Rossz helyre jött, barátom. Ez a hely nem a hatalom, hanem a béke kiszolgálója. }
{182}{}{Úgy hallottam, a Keresztes hadjáratunk jól halad. Hamarosan eljuttatjuk a Békét és az Egységet a Csonttelepre, utána az összes környezõ településre. Hát nem nagyszerû dolog ez? }
{183}{}{Kik részesülnek legközelebb a Békébõl és az Egységbõl? }
{184}{}{Ez eléggé bizonytalan dolog. Hallott valami egyébrõl? }
{185}{}{Helyes. Épp eljött az idõ, hogy valaki kidzsuvázza ezt a koszfészket. }
{186}{}{Igen. Hát nem nagyszerû dolog a halál? }
{187}{}{Magának Morpheus Atyával kéne beszélnie. A toronyban megtalálja. Ennyi lenne? }
{188}{}{Érdemes még valamit tudnom, mielõtt találkoznék vele? }
{189}{}{Majd meglátjuk...}
{190}{}{Köszönöm! Végre friss hús érkezett! }
{191}{}{Szeretne még valamit, gyermekem? }
{192}{}{Elnézést, kemény hét áll mögöttem. Mit tudna mondani errõl a helyrõl? }
{193}{}{További útmutatásra van szükségem a Katedrálist illetõen. Tudja, kivel kéne beszélnem? }
{194}{}{Azon töprengtem, ki lehet itt a vezetõ? }
{195}{}{El tudnék viselni egy teljes testmasszázst meg egy kis extrát is, ha nem gond. Lehet róla szó? }
{196}{}{Van itt valami misebor ebben a kócerájban? }
{197}{}{Azon elmélkedém, vajon hogy nézne ki, ha valami mániákus szétloccsantaná az agyát ezen a szép kövezeten. Nézzük csak, ki lehetne ez a vállalkozó kedvû egyén... }
{198}{}{Nagyon jó humorérzéke van, gyermekem, csak Ostoros Atyának ne nagyon meséljen vicceket! }
{199}{}{Van itt még a Mesternek olyan szolgálója, akire jobban oda kéne figyelnem? }
{200}{}{Lehet, hogy túl sok idõt töltött a pusztaságban? }
{201}{}{Szeretnék találkozni a Mesterrel. }
{202}{}{Azon töprengtem, ki lehet itt a vezetõ? }
{203}{}{Van itt valami misebor ebben a kócerájban? }
{204}{}{Tudja... a mai napon ez volt a legszebb dolog, amit mondtak nekem. Még a végén meg sem ölöm magát. }
{205}{}{Félek, hogy túl sok napsütés érte. Remélem, nálunk sikerül felgyógyulnia belõle. Dícsértessék a Mester! Dícsértessék a Szentséges Láng! }
{206}{}{A szavaiból csak úgy süt a fájdalom és gyûlölet! Sajnálom magát, barátom, de a sajnálat akár még vidámsággá is változhat. Keresse fel Morpheus Atyát a toronyban! Csodálatos ember, és meg tudja nyitni a szívét, hogy újra képes legyen a szeretetre. }
{207}{}{Korábban még sosem volt a Katedrálisban? Ez a hely a Béke és Egység szentélye. Itt magunk mögött hagyjuk a különbségeket, és valamennyiünk jövõbeli egységéért, haladásáért munkálkodunk. Olyan jövõ a cél, ahol az õseink által okozott szörnyûségek sosem ismétlõdhetnek meg többé! }
{208}{}{És miképpen érhetjük el ezt a tökéletes utópiát? }
{209}{}{Az utópia létrehozása során nem sérül véletlenül a szabad akarat? }
{210}{}{Szeretnék találkozni a Mesterrel, és tõle hallani, miként vélekedik errõl! }
{211}{}{Hogy lehet biztos abban, hogy ez nem az elme egyfajta távirányítása? }
{212}{}{Van itt valami misebor ebben a kócerájban? }
{213}{}{Ez így helyes! Jobban szeretem a saját szörnyûségeimet magam prezentálni az embereknek. }
{214}{}{Az ellenségeink rágalomhadjáratot folytatnak ellenünk! Az embereket olyan könnyû megfélemlíteni, különösen, ha mindig megmondják nekik, mi a teendõ. Viszont amióta a Mestert és a Szentséges Lángot követem, semmitõl nem kell félnem. A Mester a lelkemre kötötte ezt! }
{215}{}{És miképpen érhetjük el ezt a tökéletes utópiát? }
{216}{}{Ez a Mester jól adja elõ a témát... van valami ötlete, hol futhatnék össze vele? }
{217}{}{Tegyük hozzá, hallottam én pletykákat bizonyos mutáns seregekrõl... }
{218}{}{Mondta már valaki magának, hogy egy kiköpött zombi? }
{219}{}{Ez így helyes! Jobban szeretem a saját szörnyûségeimet magam prezentálni az embereknek. }
{220}{}{A kulcs a Mester álhatatos dícsérete. Én sosem fáradok bele a Mester dicsõítésébe. Miért nem csatlakozik hozzám, barátom? }
{221}{}{Miért kéne nekem dícsérnem a Mestert? Gyerünk, gyõzzön meg! }
{222}{}{Miért is ne. Dícsértessék a Mester! Na, milyen volt? }
{223}{}{Aligha vállalom ezt be... }
{224}{}{Mondta már valaki magának, hogy egy kiköpött zombi? }
{225}{}{Dícsérjük õt egy jó kis misebor mellett. Egybõl jobban megy a dícséret, ha szívbõl jön... }
{226}{}{Tudja, arról beszélek, ami a kezében van... }
{227}{}{Ja, a fegyvert mondja! }
{228}{}{Öhm, meg van töltve? }
{229}{}{Nem sokat tudok. A Mester elméje olyan nagyszerû. Tudok róla, hogy a Gyermekek észak felé menetelnek. Az összes települést irányításunk alá vonjuk, és mindenkit megkeresztelünk! A keresztség megváltoztat bennünket, és közelebb visz Istenhez. Így érjük el a békét és az egységet, ami lehetõvé teszi, hogy háború és pusztítás soha többé ne tépázhasson minket! }
{230}{}{Na, és merre van a keresztelõkút? }
{231}{}{Úgy látom, mindenkit bele akar mártogatni a FEV-2 vírusba! }
{232}{}{Mily nagyszerû nap lesz az! }
{233}{}{Azt hiszem, minden lényeges dolgot hallottam. }
{234}{}{Akkor jobb lesz, ha mihamarabb beszállok a pusztításba, amíg még van rá esélyem. Halál rád, rohadék! }
{235}{}{Dícsértessék a Mester! Béke legyen magával! Jó idõtöltést a Katedrálisban. }
{236}{}{Ez itt egy szentély. Olyanok járnak ide, akik a jövõt akarják építeni és itt akarják megvalósítani elképzeléseiket. }
{237}{}{Na, és milyen jogon akarják mindenkire ráerõlteti a maguk jövõképét? }
{238}{}{Az embereknek el kell hagyniuk a szentélyeket, és ki kell lépniük a nagyvilágba, különben a szentély börtönné alacsonyodik. }
{239}{}{Mindenkit hidegen hagy a béke. Az emberek a tutira vágynak, ember! Ébredjen már fel! }
{240}{}{Nem hangzik rosszul. Kinél kell jelentkeznem? }
{241}{}{Béke? Szentély? Rosszul leszek magától, zombikám! }
{242}{}{Örömmel hallom, hogy megvan magában a béke iránti érdeklõdés. Keresse fel Morpheus Atyát és Ostoros Testvért. Õk további eligazítással tudnak szolgálni. }
{243}{}{Attól tartok, nem áll módomban segíteni. Morpheus Atya a Mester egyetlen bizalmasa. A toronyban megtalálja õt. }
{244}{}{Érdemes még valamit tudnom, mielõtt találkoznék vele? }
{245}{}{Köszönöm. Ég önnel. }
{246}{}{Morpheus Atya... Nagyon békés kis név ez. Kik a sameszai? Mészáros Testvér talán? Vagy Halál Testvér? Netán Gyilok nõvér? }
{247}{}{Mi sem áll közelebb a szívemhez, mintsem újjászületni az ügyünk érdekében. Öljön csak meg, ha ez a vágya! Én megváltást nyerek, maga viszont örökre meghal. }
{248}{}{Kisfiam, így vagy úgy, de most nagyon megütöd a bokád! }
{249}{}{Hálás lennék, ha most már befogná azt a nagy száját! Maguk zombik egész rendes fejfájást tudnak okozni. }
{250}{}{Neked aztán van gusztusod, kisfiam. Csodállak. Talán még életben is hagylak. }
{251}{}{A kiskutya faszát se érdekel a lelked, kisfiam, viszont átok száll rám, ha visszautasítom az ajánlatot. Egy darab mártír rendel! }
{252}{}{Nos... öh.. béke legyen magával... ugyebár... isten áldja... }
{253}{}{Kapjon már észbe! Nem hallja az üzenetet? Hogy képes megkérdõjelezni a Mester szavahihetõségét? }
{254}{}{Mindenkit hidegen hagy a béke. Az emberek a tutira vágynak, ember! Ébredjen már fel! }
{255}{}{A békérõl könnyû ám papolni, de vajon mit tesz érte a Mester valójában? }
{256}{}{Bocsásson meg, testvér! A világ annyira borzalmas, és nagyon félek, hogy elveszítjük a szabadságunkat... }
{257}{}{A békérõl könnyû ám papolni, de szörnyûséges mendemondákat hallottam bizonyos mutáns seregekrõl... }
{258}{}{Lehet, hogy igaza van. Kinél kell jelentkeznem? }
{259}{}{Igazi õszinteség csakis a fegyver csövén át érkezik hozzánk! }
{260}{}{Õ a Szentséges Láng Õrizõje, õ az aki eltörli a megosztottságot, a világot behálózó gyûlöletet. Egyszerre markol kardot és ragadja meg az eke szarvát, de ezerszer inkább épit, mint rombol. Éljen a Mester! Éljen az Egység! }
{261}{}{Úgy hallottam, a Keresztes hadjáratunk jól halad. Észak felé menetelünk, ahogy azt a Mester megígérte. A középkor erõi semmik a Megvilágosodottak seregeihez képest. Micsoda dicsõséges idõk ezek! Emelje fel a tekintetét, barátom, és kiáltsa az égbe a magasztalás szavait! }
{262}{}{És mi lesz azokkal, akik a vesztes oldalon állnak? Vérrel, zsarnoksággal semmissé tehetünk egy Sötét Kort? }
{263}{}{Hínnye, mindjárt táncra perdülök! }
{264}{}{Azt hiszem, minden lényeges dolgot hallottam. }
{265}{}{Nem, köszönöm. Be vagyok rekedve. Inkább a magam sajátos módján ünnepelnék.... így hát... megölöm magát! }
{266}{}{Nem állt szándékomban sértegetni magát, és nem igazán akartam a dolgába se ütni az orromat. Kérem, bocsásson meg nekem. A Mester áldása kísérje az ön kegyes szolgálatát... }
{267}{}{Elnézését kérem. Dícsértessék a Mester, és minden jót kívnánok! }
{268}{}{Szomorú lelket tudhat magának, barátom. Csak találgatni tudnék, miféle szörnyûségeken ment keresztül, hogy így magába zárkózik. Nyíljon meg, és lelje meg a békét! Figyelje a képernyõket, hallgassa Morpheus atyát, és dícsérje a Mestert! }
{269}{}{Semmit nem tudok, barátom, semmit! Találnia kell valaki mást, aki megválaszolja a kérdését. Az Éjfajzatokról azonban nem tanácsos érdeklõdni. }
{270}{}{Hogyne, semmi gond. }
{271}{}{Ez hogy lehet? }
{272}{}{Nekem csak egyetlen kérdésem van velük kapcsolatban. Hangosan visítanak, amikor megölöm õket? }
{273}{}{Semmit nem tud? Hülyének tetszik lenni tán? }
{274}{}{Éjfajzatok! Éjfajzatok! Gyilok van! }
{275}{}{Csodálatos beszélgetést folytattunk, de kezdem hanyagolni a dícséreteket. Isten önnel, és dícsértessék a Mester! Dícsértessék a Szentséges Láng! Énekeljük megszentelt dalainkat... }
{276}{}{Ha nem tetszik itt magának, el is mehet. Dícsértessék a Mester, és legyen szép napja! }
{277}{}{Sajnálom, hogy a Pusztaság csak ilyen torz humorra képes. Én nem nagyon osztanám ezt meg másokkal. }
{278}{}{Van valaki, akit kifejezetten kerülnöm kéne? }
{279}{}{Ebben a helyben semmi poén nincs! }
{280}{}{Oké, jegelem a vicceimet. }
{281}{}{Ismeri a viccet a nuke-sefterrõl meg a vándorkereskedõrõl? }
{282}{}{Biztos benne, hogy nem tudom bemutatni a nevettetõ képességem? }
{283}{}{Senki nem jut eszembe. Minden jót, barátom! }
{284}{}{Aligha hiszem, hogy tudnék segíteni, barátom. Isten önnen, és legyen szép napja! Dícsértessék a Mester! Dícsértessék a Szentséges Láng! }
{285}{}{Attól tartok, ebben nem tudok segíteni. Most azonban meditálnom kell a Mester nagyságán. Kérem, bocsásson meg. Éljen a Mester! Éljen a Szentséges Láng! }
{286}{}{Itt mindenkit betölt a szeretet, viszont egyes emberek számára nagyon nehéz kifejezni a szeretetüket. Az Éjfajzatoknak különösen nehézkes. Ezt saját magának kell megtapasztalnia. Dícsértessék a Mester! Dícsértessék a Szentséges Láng! }
{287}{}{Engedelmeskednünk kell a Mesternek és a Szentséges Lángnak. Amint bizonyságot tettünk elkötelezettségünkrõl, átesünk a keresztségen, és közelebb kerülünk Istenhez. Ha mindannyian átestünk ezen, egyek leszünk. A Mester vezetésével létrejön az Egység! }
{288}{}{Mondjon még valamit errõl a keresztségrõl. }
{289}{}{Mi történik azokkal, akik nem akarnak megkeresztelkedni? }
{290}{}{Érdekesen hangzik. Nem baj, ha egy kicsit körbenézek még? }
{291}{}{Szerintem maguk csak egy rakás zombi! }
{292}{}{Csak egyetlen Egység létezik az emberek számára. Akkor jön majd el, amikor mindannyiunk testét kikezdik a férgek. }
{293}{}{Jogunk van a túlélésre. Az õsök megpróbáltak fennmaradni, közben pedig megtartani a szabadságukat, és nézze, mit tettek velünk! Nem szabad ugyanazt a hibát elkövetnünk. Az Egység az egyetlen lehetõség. Az egyetlen mód arra, hogy megszabadítsuk az emberiséget jelenlegi állapotától! }
{294}{}{Mit ért azalatt, hogy jelenlegi állapotától? Egyelõre tökéletes emberek vagyunk. }
{295}{}{Elképzelhetõ, hogy az õsök tévedése nem az egység hiánya miatt volt. Lehet, hogy csak egyszerûen nem fértek a bõrükbe, és bele akartak kötni egymásba. }
{296}{}{Én nem vagyok filozófus, de meg tudom különböztetni a rosszat a jótól, és ez most rossz. }
{297}{}{Lehet, hogy igaza van. }
{298}{}{Az emberiség nem érdemli meg, hogy bárki is egyetlen ujját mozdítsa értük. Mondanom sem kell, hogy maga sem! Készülj a halálra, te kis zombi!! }
{299}{}{A Mester azt mondta, hogy az Egység hiánya miatt volt, és én nem vonom kétségbe a szavait. Keresse fel a Fõpapját! Morpheus Atya majd eligazítja a hazugságok rengetegében, amiket ezidáig hallott. }
{300}{}{Nem vagyunk zombik! Amikor a Bunyósok nevû utcai banda tagja voltam, eszeveszett bolondként mindent marhaságot megtettem, amit a felettem állók parancsoltak! Legyen hálás a Mesternek, hogy már nem vagyok olyan vaksi! Dícsértessék a Mester! Jöjjön, dícsérjük együtt Õt! }
{301}{}{Jobban tudnám dícsérni a Mestert, ha tisztában lennék a céljaival. }
{302}{}{Dícsértessék a Mester! }
{303}{}{Ha most elkezdi nekem dícsérni a Mestert, már itt sem vagyok. }
{304}{}{Mi lenne, ha valami jó kis misebor mellett állnánk neki dícsérni a Mestert? Innom kell valamit! }
{305}{}{Van egy sokkal jobb ötletem. Úgy fogom dícsérni a Mestert, hogy táncot járok a maga zombi hulláján. Ütött a halál pillanata! }
{306}{}{Hát nem csodálatos, hogy a Mester embert és mutánst egyaránt képes egységesíteni? Képes túllépni a gyûlöleten és az elõítéleteken. Nem látja, hogy mindez ékes bizonyítéka a széles tömegek érdekét szolgáló erõfeszítéseinek? }
{307}{}{Ezek szerint a hadserege szeretetet és megértést terjeszt mindenhol, ahová beteszik a lábukat... }
{308}{}{Szerintem nem errõl van szó, ugyanis a mutánsok sokkal hatékonyabb gyilkosok. }
{309}{}{Dícsértessék a Mester! }
{310}{}{Nekem ennél több bizonyíték kell. }
{311}{}{Mi lenne, ha valami jó kis misebor mellett állnánk neki dícsérni a Mestert? Innom kell valamit! }
{312}{}{Értem már! Követni fogom a Mester példáját! Tudom, hogy a maga érdekét az szolgálja, ha megölöm. Itt és most! Ennél jobb ötletem nem is támadhatott volna... }
{313}{}{Nyissa meg a szívét! Nyissa meg az elméjét! Hallgasson az emberekre, úgy rálel a megvilágosodásra! }
{314}{}{Esetleg van valaki errefelé, aki jobban el tudja ezt magyarázni nekem. Meg lehet látogatni a Mestert? }
{315}{}{Nem látok itt mást, csak egy rakás zombit! }
{316}{}{Ez nem indok. Ez propaganda! }
{317}{}{Azt hiszem, most távozom, és magam nézek utána a dolgoknak. }
{318}{}{Inkább felbontanék egy palack bort. Hol tartják a piákat? }
{319}{}{Zombik! Hányni tudnék maguktól! Ideje, hogy mindegyiküket egyenként kicsináljam! }
{320}{}{Szomorúsággal tölt ez el. Imádkozni fogok magáért. }
{321}{}{Sajnos, nekem sohasem adatott meg a tisztesség, hogy láthassam a keresztség kútját. Esetleg még az eddigieknél is serényebben kell dícsérnem a Mestert, akkor talán rámszáll az áldás. Éljen a Mester! Éljen a Szentséges Láng! Éljen a Béke és az Egység! }
{322}{}{Persze, hogy nem. Õ a Mester. Sosem tenne ilyet a híveivel. A keresztségben és a Szentséges Lángban testet öltött szent akarata fog megváltoztatni minket. A vírus a régi idõk gonosz maradványa, és biztos vagyok abban, hogy megtisztítjuk tõle a világot. }
{323}{}{Nem áll szándékunkban, hogy gyötrelmet okozzunk magának. Ha mi nem tudunk megnyugvással szolgálni, keressen valaki mást, aki megszünteti a kínjait! Ez itt a béke szentélye. }
{324}{}{Úgy húzok el innen, hogy a lábam nem éri a földet! }
{325}{}{Mondtam már, hogy fogja be a száját! Rossz a felfogóképessége? }
{326}{}{Azt hiszem, csak egyféle módon leszek képes békére és megnyugvásra lelni, mégpedig úgy, hogy mindannyiukat megölöm. Pusztulj! }
{327}{}{Erre a kérdésre saját magának kell megtalálnia a választ. Dícsértessék a Mester! Dícsértessék a Szentséges Láng! }
{328}{}{A keresztelkedés mindannyiunkat átváltoztatja, fizikai valónkat hasonlatosabbá teszi Isten képéhez. Amikor mindannyian Istenek leszünk, a különbségek elenyésznek, és beköszönt végre a béke, beköszönt a várva várt egység. Soha többé nem lesz háború, megszûnik a pusztítás! }
{329}{}{Merre van a keresztelõkút? }
{330}{}{Nagyon úgy néz ki, hogy mindenkit bele akar mártani a FEV-2 vírusba! }
{331}{}{Mily nagyszerû nap lesz az! }
{332}{}{Azt hiszem, minden lényeges dolgot hallottam. }
{333}{}{Akkor jobb lesz, ha mihamarabb beszállok a pusztításba, amíg még van rá esélyem. Halál rád, seggfej! }
{334}{}{Amint az emberek megértik a Mestert és a céljait, mindenki át akar majd esni a keresztségen. Csak az õrültek utasítanák el ezt a szent lehetõséget. Ezeket a szerencsétlen flótásokat a saját érdekükben meg kell szabadítani szenvedéseiktõl. }
{335}{}{Nem lepte még meg az, milyen nagy számban találkozott már ezekkel az "õrültekkel"? }
{336}{}{Maguk begolyóztak! }
{337}{}{Azt hiszem, egy kicsit még körbe kéne néznem. }
{338}{}{Jaja. Szerencsétlen félnótások. Rúgjunk ki a hámból, nyissunk ki egy palack misebort, és igyunk az egészségükre! }
{339}{}{Ha szükségük van valakire, hogy õket - vagy magát - megszabadítsam a szenvedéstõl, bármikor kéznél vagyok! }
{340}{}{Barátom, ha megnyílt elmével keresi az igazságot, bennünket mindig megtalál. Dícsértessék a Mester! Kívánom, hogy szerencsével járjon a megvilágosodás útján! }
{341}{}{Emberrõl vagy mutánsról legyen szó, közelebb kell kerülnünk Istenhez. Nem vagyok egészen biztos abban, mit ért a Mester ez alatt, de bizonyára ott van benne az igazság. Dícsérjük a Mestert az õ végtelen bölcsességéért! }
{342}{}{Szerintem ha igazán bölcs lenne, nem lenne kétértelmû az üzenete. }
{343}{}{Maguk begolyóztak! }
{344}{}{Azt hiszem, egy kicsit még körbe kéne néznem. }
{345}{}{Jaja, viszont van egy elsõrangú ötletem! Rúgjunk ki a hámból, bontsunk fel egy palack misebort, és mondjunk pohárköszöntõt a Mester bölcsességére! }
{346}{}{A világ összes bölcsessége sem ér semmit egy .56-os kaliberû töltény ellen, amikor épp a szemed közé fúródik... }
{347}{}{Olyan világot akarunk összekovácsolni, ahol mindenki megtalálja a számítását. Ennyi. Sajnálom, ha eddig nem értette meg a céljainkat. Imádkozom, hogy egy nálam bölcsebb ember fel tudja majd nyitni a szemét. Isten önnel, barátom! Dícsértessék a Mester! Dícsértessék a Béke és az Egység! }
{348}{}{A világ számos meglepetést tartogat, barátom. Némelyik kellemes, némelyik kellemetlen. Isten önnel, barátom, a Mester kísérje útján! }
{349}{}{[Done] }
