{100}{}{Ez itt nem más, mint Shady Sands vízforrása. Túl kevés víz van benne, hogy egy egész Menedéket elláthasson.}
{101}{}{Semmi okod nincs rá, hogy lemássz a kútba, de a kötél esetleg jó szolgálatot tehet, ha késõbb még szándékodban áll gödrökbe, lyukakba ereszkedni.}
{102}{}{Semmi újat nem tudsz meg.}
{103}{}{Ahogy hallod a kupak csobbanását a vízben, kívánsz valamit.}
