{100}{}{Ez itt valami hatalmas szupermutáns teremtmény! A kezében egy bazi nagy fegyvert szorongat!}
{101}{}{Az Egység területén járkálsz. Be kell vigyelek.}
{102}{}{Okay.}
{103}{}{Nem hinném.}
{104}{}{Miva'?}
