{100}{}{Thomas Testvért látod.}
{101}{}{Üdvözöllek. Te bizonyára az az újonc vagy, akirõl Talus mesélt nekem. Egy kicsit túl késõ van a látogatáshoz... mindenesetre tehetek érted valamit?}
{102}{}{Szükséges lenne frissíteni a tartalékokat.}
{103}{}{Tréningre lenne szükségem.}
{104}{}{Gyógykezelést igénylek.}
{105}{}{Semmit, bocsánat, hogy zavartalak.}
{106}{}{Yuk Yuk?}
{107}{}{Ruh.}
{108}{}{Mégis mit akarsz ebben a kései órában?}
{109}{}{Nincs idõm erre...}
{110}{}{Micsoda? Úgy nézek én ki, mint valami raktáros, vagy mi? Ha nem tudod, ki vagyok, miért pazarlod az idõmet? Kérlek, haggy magamra!}
{111}{}{Fenébe is, }
{112}{}{, én tréner vagyok nem orvos. Õ a második szinten van.}
{113}{}{Miért zavarsz ilyenekkel? Michael valószínûleg már alszik, hacsak Talus nem osztotta be õrnek. Reggel nézz be hozzá a raktárba!}
{114}{}{A Perjelek azt mondták, hogy újoncokat nem képzünk mostanában, de te... elég jóravaló fiatal kölyöknek tûnsz. Nem venném a lelkemre, ha valami történne veled a pusztaságban, pedig még segíthettem is volna. Mit szeretnél trénelni?}
{115}{}{A Perjelek azt mondták, hogy újoncokat nem képzünk mostanában, de te... elég jóravaló fiatal hölgynek tûnsz. Nem venném a lelkemre, ha valami történne veled a pusztaságban, pedig még segíthettem is volna. Mit szeretnél trénelni?}
{118}{}{Kézi lõfegyverek.}
{119}{}{Nehéz lõfegyverek.}
{120}{}{Energiafegyverek.}
{121}{}{Ökölharc.}
{122}{}{Közelharc.}
{123}{}{Hajítás.}
{124}{}{Semmit, bocs, hogy zavartalak.}
{125}{}{Ki kellene hajítanom téged, de én rendes öreg fickó vagyok. A Perjelek megtiltották, hogy újoncokat képezzünk ki, de... esetleg segíthetnék rajtad. Amikor meghozták ezt a döntésüket, téged bizonyára nem vettek számításba. Mit szeretnél fejleszteni?}
{126}{}{Üdvözöllek újra nálam. Örülök, hogy látlak. Ne légy félénk, már nem nagyon tudok aludni. Szeretnél egy kis képzést? Mi legyen a mai lecke... úgy értem, a ma éjszakai lecke?}
{127}{}{Tudtam, hogy visszajössz! Miben töröd a fejed így éjnek-évadján?}
{128}{}{Megint buta kérdésekkel akarsz zaklatni? Nekem tényleg nem sok idõm van ilyesmire.}
{129}{}{Nos, amint látod, a különbözõ kaliberû fegyvereknek...}
{130}{}{Egy egész napos intenzív kiképzést követõen sokkal képzettebbnek érzed magad a kézi lõfegyverek kezelésében.}
{131}{}{Nos...}
{132}{}{Két álló napig tartó intenzív kiképzést követõen sokkal képzettebbnek érzed magad a nehéz lõfegyverek kezelésében.}
{134}{}{Néhány napos intenzív kiképzést követõen sokkal képzettebbnek érzed magad az energiafegyverek kezelésében..}
{135}{}{Egy egész napos kiképzést követõen sokkal képzettebbnek érzed magad az ökölharc terén.}
{136}{}{Két álló napig tartó intenzív kiképzést követõen sokkal képzettebbnek érzed magad a közelharc terén.}
{137}{}{Egy egész napos kiképzést követõen sokkal képzettebbnek érzed magad a hajítás terén.}
{138}{}{Semmi probléma. Majd szólj, ha meggondoltad magad!}
{139}{}{Nem tudom, miért pazarlom rád az idõmet.}
{140}{}{Igen? Ja, gondolom, további tréning érdekelne. Végül is... már nem nagyon tudnék aludni. Mit szeretnél tanulni?}
{141}{}{Mit szeretnél? Újabb hülye kérdéseid vannak?}
{142}{}{Rendben van. Ahogy mondtam, elég nehezen alszom el. Gyere csak bármikor!}
{143}{}{Akkor ne zargass! Öreg ember vagyok, ki kell aludnom magam.}
