{100}{}{Ez az ember Thorndyke.}
{101}{}{A tudásomat nem akarom arra használni, hogy az ellenséget gyógyítsam. Tûnés innen!}
{102}{}{Már hallottam magáról. Mindenki tudja, hogy egy kérlelhetetlen gyilkos. Nem akarok olyanokat gyógyítani, aki emberek sokaságát bántalmazta. Távozzék!}
{103}{}{Uram, én gyógyító vagyok. A szolgálataimra nincs szüksége.}
{104}{}{Asszonyom, én gyógyító vagyok. A szolgálataimra nincs szüksége.}
{105}{}{Mondjon valamit a munkájáról!}
{106}{}{Mire való ez a hely?}
{107}{}{Mennyit kér a szolgálataiért?}
{108}{}{Maybe later...}
{109}{}{Esetleg fellendíthetném az üzletet. Elég jó vagyok az emberek bántalmazásában.}
{110}{}{He?}
{111}{}{Uram, már túlestünk a gyógykezelésen. Újabb dózisra nem merek vállalkozni.}
{112}{}{Hölgyem, már túlestünk a gyógykezelésen. Újabb dózisra nem merek vállalkozni.}
{113}{}{Mondjon valamit a munkájáról!}
{114}{}{Mire való ez a hely?}
{115}{}{Ez elég harmatos kezelés volt. Nincs valami erõsebb gyógyszere?}
{116}{}{Bocs, hogy zavartam, doki.}
{117}{}{Esetleg fellendíthetném az üzletet. Elég jó vagyok az emberek bántalmazásában.}
{118}{}{He?}
{119}{}{Uram, maga megsérült. Ha gondolja, elláthatom. Gyógyító vagyok.}
{120}{}{Asszonyom, maga megsérült. Ha gondolja, elláthatom. Gyógyító vagyok.}
{121}{}{Mondjon valamit a munkájáról!}
{122}{}{Mire való ez a hely?}
{123}{}{Mennyibe kerül?}
{124}{}{Csinálja csak!}
{125}{}{Kösz, nem.}
{126}{}{Gyûlölöm az orvosokat!}
{127}{}{Úúúú! Aúúúúúú!}
{128}{}{Rarrrr!!!}
{129}{}{Uram, maga komolyan megsebesült. Javasolnám, hogy engedje át magát a szakértelmemnek. Gyógyító vagyok.}
{130}{}{Hölgyem, maga komolyan megsebesült. Javasolnám, hogy engedje át magát a szakértelmemnek. Gyógyító vagyok.}
{131}{}{Mondjon valamit a munkájáról!}
{132}{}{Mire való ez a hely?}
{133}{}{Mennyibe kerül?}
{134}{}{Kösz, nem.}
{135}{}{Gyûlölöm az orvosokat!}
{136}{}{Oooo! Owwwww!}
{137}{}{Rarrrr!!!}
{138}{}{A Szentséges Láng azt parancsolja, hogy gyógyítsak. Mivel a bölcsessége kétségbevonhatatlan, engedelmeskedem. Már eddig is rengeteget tanultam a Katedrálison kívüli életrõl.}
{139}{}{Meséljen a Katedrálisról!}
{140}{}{Milyen ismeretekre tett szert?}
{141}{}{Mire való ez a hely?}
{142}{}{Bocs, hogy zavartam, doki.}
{143}{}{Ez ám a láng!}
{144}{}{Uram, elnézését kérem, de nincs türelmem a hosszadalmas beszélgetéshez. Vannak rajtam kívül sokkal alkalmasabb emberek, akiktõl tanácsot kérhet. Kérem, bocsásson meg.}
{145}{}{Asszonyom, elnézését kérem, de nincs türelmem a hosszadalmas beszélgetéshez. Vannak rajtam kívül sokkal alkalmasabb emberek, akiktõl tanácsot kérhet. Kérem, bocsásson meg.}
{146}{}{Számomra ez a hely a gyógyítás mûvészetének mûhelye, uram. Mások számára a kósza lelkek gyülekezõhelye, olyanoké, akiket gyümölcsözõbb irányba lehet terelni. Elnézését kérem, de nincs türelmem a hosszadalmas beszélgetéshez. Vannak rajtam kívül sokkal alkalmasabb emberek, akiktõl tanácsot kérhet. Kérem, bocsásson meg.}
{147}{}{Számomra ez a hely a gyógyítás mûvészetének mûhelye, asszonyom. Mások számára a kósza lelkek gyülekezõhelye, olyanoké, akiket gyümölcsözõbb irányba lehet terelni. Elnézését kérem, de nincs türelmem a hosszadalmas beszélgetéshez. Vannak rajtam kívül sokkal alkalmasabb emberek, akiktõl tanácsot kérhet. Kérem, bocsásson meg.}
{148}{}{Voltak néhányan az õsök között, akik szentül hitték, hogy az erények önmagukban üdvözítõek. Én is ebben hiszek. Talán ha több ember osztaná ezt a véleményt, nem lenne szükség a Szentséges Lángra... Elnézését kérem, de nincs türelmem a hosszadalmas beszélgetéshez. Vannak rajtam kívül sokkal alkalmasabb emberek, akiktõl tanácsot kérhet. Kérem, bocsásson meg.}
{149}{}{Isten önnel! Ha netán szüksége lenne rám, itt megtalál. Õszintén remélem, hogy sohasem szorul majd rá, hogy találkozzunk.}
{150}{}{Ez szolgálat, nem üzlet. A tehetségével nem illik kérkednie. Most, ha megbocsát...}
{151}{}{A sérülései sajnos meghaladhatják a képességeimet. Azt mondják, a Szentséges Láng képes az elmebetegséggel megvert embereket jó útra téríteni, és megváltást hozni nekik. Imádkozni fogok magáért.}
{152}{}{Maga megsérült. Tartogassuk késõbbre a csevejt... hadd lássam el, kérem...}
{153}{}{Hát, nem túl betegnyugtató a stílusa, doki...}
{154}{}{Igazán szívesen vennék némi infót errõl.}
{155}{}{Mennyit kér a kezelésért?}
{156}{}{Csinálja csak!}
{157}{}{Kösz, nem.}
{158}{}{Gyûlölöm az orvosokat!}
{159}{}{Gyógyító vagyok, nem hitelezõ. A Katedrális foglalkozik az én gondjaimmal, én pedig foglalkozom másokéval. Engedje meg, hogy látleletet vegyek.}
{160}{}{Csinálja csak!}
{161}{}{Nagyon jó.}
{162}{}{Felejtse el! A kutyámat sem bíznám magára, sarlatán!}
{163}{}{Gyûlölöm az orvosokat!}
{164}{}{Néhány napos ágyban fekvést ajánlanék, na nem mintha bárki valaha is megfogadná a tanácsaimat. Most pedig hagyjon magamra!}
{165}{}{Ön dönt. Ha meggondolná magát, én itt leszek.}
{166}{}{[Mosolyog.] Szörnyûek az emberek. Teljes mértékben át tudom élni. [Eltûnik a mosoly.] Ha meggondolná magát, én itt leszek. Ha megbocsát...}
{167}{}{Ezt "igennek" veszem. Kérem, ne öljön meg...}
{168}{}{AÚÚÚÚÚÚ!! [HÖRGÉS!]}
{169}{}{Szegény pára. Egy ilyen alacsony intelligenciával rendelkezõ vadállat még a Szentséges Láng gyógyító erejét is próbára tenné. El innen, el innen...}
{170}{}{Ezt akkor "nemnek" veszem. Ha megbo... ööö... menjen innen. Indulás!}
{171}{}{Nagyon szép hely, habár egy kicsit zsúfolt mostanság. Messzi délen található. Mi, hithûek ott gyülekezünk, és dícsérjük a mesterünket, a Szentséges Lángot. A Békéért és Egységért is imádkozunk. Nos, ha egyéb kérdése nincs, akkor...}
{172}{}{Meséljen a Békérõl és az Egységrõl...}
{173}{}{Egész pontosan hol van ez a hely?}
{174}{}{Mi okozza a zsúfoltságot?}
{175}{}{Gyûlölöm az orvosokat!}
{176}{}{Rájöttem, hogy fajunk rosszindulatú, erõszakos és hülyeségre hajlamos. Nem méltó a Szentséges Lánghoz. Kapzsiságot és gonoszságot látok mindenütt. Hacsak nem hajtunk végre valami drasztikus változtatást, a Szentséges Láng újra végig fog perzselni rajtunk...}
{177}{}{Mondjon még valamit a Szentséges Lángról...}
{178}{}{A maguk vallása egy nagy faszság, jóember!}
{179}{}{Hány vallás állította már, hogy az emberek elégnek a végén?}
{180}{}{Mit takar a "drasztikus" kifejezés.}
{181}{}{Gyûlölöm az orvosokat!}
{182}{}{Ez valóban így van, de vannak még mások, akik sokkal jobban elmerültek a tanokban, mint én. Viszlát!}
{183}{}{Zavarja a koncentrációmat! Akarja, hogy meggyógyítsam, vagy sem?}
{184}{}{Mitõl ilyen feldúlt?}
{185}{}{Nem úgy néz ki, mint akinek túl sok koncentrálnivalója lenne!}
{186}{}{Csinálja csak!}
{187}{}{Kösz, nem.}
{188}{}{Gyûlölöm az orvosokat!}
{189}{}{Amióta világ a világ, a békét háborúk és megpróbáltatások formálták, csakúgy, mint az egységet. Nagy baj, hogy az eljövendõ idõkben nagy szükség lesz a képességeimre.}
{190}{}{Meséljen nekem a háborúról!}
{191}{}{Az Egység megéri ezt az árat?}
{192}{}{Miért gondolja mindenki azt, hogy a békére a háború a megfelelõ válasz?}
{193}{}{Tisztázzunk valamit. Olyan vallást szolgál, amely halált és megsemmisítést hirdet. Nem okoz ez problémát magának? Röviden szólva, maga egy idióta!}
{194}{}{A régi világot gonoszság és dekadencia jellemezte, de a Szentséges Láng elpusztította. Félhetjük a Szentséges Lángot, vagy isteníthetjük, és megpróbálhatjuk megérteni. A Gyermekek a megértést választották. Nem áll szándékunkban újra megtapasztalni a Szsentséges Láng tombolását.}
{195}{}{Honnan tudja, milyen volt a régi világ?}
{196}{}{Isteníteni? A Bombát? Mi olyan nagy szám egy bombában?}
{197}{}{Ha a Szentséges Láng olyan nagyszerû, miért nem akarod mindig látni?}
{198}{}{Tisztázzunk valamit. A megértéshez isteníteni kell valamit?}
{199}{}{Maguk be vannak csavarodva!}
{200}{}{Amikor megkérek valakit valamire, szeretem, ha nem vesz semmibe. Ha úgy gondolja, hogy semmibe veszi a szavaimat, a maga sérüléseit is semmibe vehetem. Minden jót magának!}
{201}{}{Ki a fenének képzeli magát? Tûnjön a szemem elõl, maga gonosztevõ!}
{202}{}{Mára már elég információt csikart ki belõlem. Minden jót, uram!}
{203}{}{Mára már elég információt csikart ki belõlem. Minden jót, hölgyem!}
{204}{}{A Szentséges Láng a régi világ halálának és az új világ kezdetének metaforája. Élet és halál hajtóereje. Mi érhet ennél többet, hogy istenítse az ember?}
{205}{}{A fegyveremnek is élet-halál a hajtóereje, mégsem isteníti egyetlen agyalágyult szekta sem!}
{206}{}{Talán igaza van, gondolkoznom kell efelõl.}
{207}{}{Öö... van ugye az étel, a szex, egy bazi nagy fegyver... sok egyéb dolog, amit szívesen istenítenék.}
{208}{}{Gondolom, nem sok esik le belõle, mi?}
{209}{}{Doki, ez a szöveg nem túl meggyõzõ.}
{210}{}{Ez a társalgás kezd a terhemre lenni. Kérem, távozzék!}
{211}{}{Még nem felejtettem el az inzultusait, uram. Elõbb fog megrohadani az Izzásban, minthogy én segítsek magán.}
{212}{}{Még nem felejtettem el az inzultusait, asszonyom. Elõbb fog megrohadani az Izzásban, minthogy én segítsek magán.}
{213}{}{Jain Anyának az az óhaja, hogy senki ne álljon magával szóba. Minden jót!}
{214}{}{Idióta. Nem látja, hogy pihenni akar?}
