{100}{}{Therax, az Éjfajzat Filozófusok egyike.}
{101}{}{Justin, az Éjfajzat Filozófusok egyike.}
{102}{}{Sereine, az Éjfajzat Filozófusok egyike.}
{103}{}{Dolkarn, az Éjfajzat Filozófusok egyike.}
{104}{}{Hort, az Éjfajzat Filozófusok egyike.}
{105}{}{Chris, az Éjfajzat Filozófusok egyike.}
{106}{}{Jaunita, az Éjfajzat Filozófusok egyike.}
{107}{}{Lesley, az Éjfajzat Filozófusok egyike.}
{108}{}{Renfield, az Éjfajzat Filozófusok egyike.}
{109}{}{Timothy, az Éjfajzat Filozófusok egyike.}
{110}{}{Légy üdvözölve, a körünkben. Épp idõben jöttél, hogy segíthess nekünk.}
{111}{}{He?}
{112}{}{Persze. Semmi gond.}
{113}{}{Bocs, túlságosan elfoglalt vagyok.}
{114}{}{Miért akarnék segíteni nektek?}
{115}{}{Nem számít egyszerû barátom. Jer velem, és kiosztom a feladatod.}
{116}{}{Ez nem kérés volt. Viszünk és kész.}
{117}{}{Nem ti vagytok azok, akik békét akarnak hozni a pusztaságba?}
{118}{}{Persze-persze... de nem látom, ha segítek, mit számít az nektek.}
{119}{}{Nem. A tömegpusztításra esküszöm.}
{120}{}{Abban hiszünk, ha mindenki, legyen az mutáns vagy ember, megtanul együtt dolgozni, hatalmas problémákat tudunk együtt legyõzni.}
{121}{}{Ígéretesen hangzik. Benne vagyok.}
{122}{}{Tegyél le róla!}
{123}{}{Valami egyszerûen nem stimmel ezzel az egésszel.}
{124}{}{Minden tökéletes. Talán a korlátolt agy-ûrméreted hátráltat a gondolkodásban.}
{125}{}{Valószínûleg igazad van. Benne vagyok a témában.}
{126}{}{Talán... Hadd vizsgáljam meg a koponyádat.}
{127}{}{Ha ez a kívánságod, akkor most meghallgattatik...}
{128}{}{Üdvözlünk újra a körünkben. Most szépen segítesz nekünk!}
