{100}{}{A kis kapcsoló egy apró adó-vevõvel és egy elemmel van összeépítve. Valószínûleg egy máshol lévõ kontroll-számítógép ki-be kapcsolója.}
{101}{}{A kis kétállású kapcsoló valamiféle távkapcsolónak tûnik.}
