{100}{}{You see: Glowing Ghoul.}
{101}{}{A ghoul rád sem bagózik.}
{102}{}{A víz megszûnt létezni. Nélküle mindannyiunknak vége.}
#
# Sduibek, Fallout Fixt:
#
{103}{}{You have doomed us all.}
{104}{}{You will pay for your actions with blood...}
{105}{}{The flow ends. So does your life.}
