{100}{}{Ez itt Victor.}
{101}{}{Egy bandatagot látsz.}
{102}{}{Aaaaggghhh... }
{103}{}{Új hús, hehehe.}
{104}{}{Öm, jaja. Öh, asszem most megyek...}
{105}{}{Ugye nem vagy valami boldog ember?}
{106}{}{Höh höh!}
{107}{}{Nem igazán. Azt hiszem, itt tartalak egy darabig.}
{108}{}{Ezt most miért mondod? Boldog vagyok, amennyire csak lehet. Nagyon boldog vagyok, mert sok olyan dolog létezik, ami frankón tud vérezni.}
{109}{}{Te beteg vagy, mondták már?}
{110}{}{Öhm, jaja. Helló...}
{111}{}{Ah, igen, a múvészlélek... Öh, megértem... asszem...}
{112}{}{Hagyd ezt abba! Az anyám mondott ilyeneket! Megfizetsz ezért! Jó fiú vagyok, ugye mami?}
{113}{}{Valaki végre megért engem!}
{114}{}{Helló, helló, mûvész barátom!}
{115}{}{Ha! Ha! Heh heh hee! Ho ho ha!}
{116}{}{Zzzzz}
{117}{}{Victor, mondták már neked valaha, hogy beteg ember vagy?}
{118}{}{Öh, üdv!}
