{100}{}{A Vízkereskedõk egyik õre.}
{101}{}{Megállni! Akik nem tartoznak a kereskedõk közé, nem közelíthetik meg a víztornyot vagy a szivattyúkat!}
{102}{}{Nem jöhetsz ide, menj innen!!}
{103}{}{Ez a terület nem publikus! Tágulj a szivattyúk környékérõl!}
{104}{}{Ha kedves az életed, hordd el magad!}
{105}{}{Ez az utolsó figyelmeztetés! Menj el!}
{106}{}{Addig menj innen, amíg lehet!}
{107}{}{Még néhány másodpercet adok, aztán jön a nemulass!}
{108}{}{Süket vagy? Menj már innen!}
{109}{}{Na, elég volt ebbõl!}
{110}{}{Ha nem értesz a szép szóból...}
{111}{}{Látom, a füleden ülsz...}
{112}{}{Tanítsátok meg a fickót!}
{113}{}{Tanítsátok meg a kiscsajt!}
{114}{}{Akik nem tartoznak a kereskedõk közé, nem közelíthetik meg a víztornyot vagy a szivattyúkat!}
{115}{}{El kéne menned innen!}
{116}{}{Nem bízunk senkiben, és nem kérünk senkibõl.}
{117}{}{Jobb lesz, ha tágulsz a szivattyúktól!}
{118}{}{Ha kell valami, menj a Kereskedõcsarnokba!}
{119}{}{Nem leszünk szívbajosak, és lelövünk ám! Meg se forduljon a fejedben!}
{120}{}{Nem hagyjuk, hogy bárki is veszélyeztesse a Hub éltetõ erejét.}
