{100}{}{This is the disk containing Vree's autopsy report.}
{101}{}{Pip-Boy 2000 displays: "Downloading data from disk...... File found on system. Aborting download."}
{102}{}{Pip-Boy 2000 displays: "Downloading data from disk... ... ... Download complete. Have a nice day."}