#
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
# System
{100}{}{ЗАГРУЗКА}
{101}{}{МЕСТО БЫСТРОЙ ЗАГРУЗКИ}
{102}{}{ЗАПИСЬ}
{103}{}{МЕСТО БЫСТРОЙ ЗАПИСИ}
{104}{}{ДАЛЕЕ}
{105}{}{ОТКАЗ}
{106}{}{Ошибка при загрузке списка сохр. игр!}
{107}{}{Каталог для записи игр:}
{108}{}{Не существует или поврежден.}
{109}{}{ЗАПИСЬ}
{110}{}{ЗАГРУЗКА}
{111}{}{- ПУСТО -}
{112}{}{- БИТАЯ ЗАПИСЬ ИГРЫ -}
{113}{}{- СТАРАЯ ВЕРСИЯ -}
{114}{}{Пусто.}
{115}{}{Ошибка!}
{116}{}{Старая версия.}
{117}{}{ЯНВ}
{118}{}{ФЕВ}
{119}{}{МАР}
{120}{}{АПР}
{121}{}{МАЙ}
{122}{}{ИЮН}
{123}{}{ИЮЛ}
{124}{}{АВГ}
{125}{}{СЕН}
{126}{}{ОКТ}
{127}{}{НОЯ}
{128}{}{ДЕК}
{129}{}{Уровень}
{130}{}{ОПИСАНИЕ}
{131}{}{Запись уже существует, перезаписать?}
{132}{}{Ошибка при записи игры!}
{133}{}{Нельзя записать игру.}
{134}{}{Ошибка при загрузке игры!}
{135}{}{Нельзя загрузить игру.}
{136}{}{Версия записи игры слишком старая.}
{137}{}{Карта}
{140}{}{Игра записана.}
{141}{}{Игра загружена.}
#
# Demo versions only
#
{200}{}{Извините, такая возможность отсутствует}
{201}{}{в демо версии игры.}
