{100}{}{Житель Ёранилища}
{101}{}{}
{200}{}{Горожанин}
{201}{}{Мужчина, одетый в защитное кожаное обмундирование}
{300}{}{Горожанин}
{301}{}{Мужчина, одетый в тяжелую стальную броню.}
{400}{}{Придурок}
{401}{}{Жалкий придурок.}
{500}{}{Крестьянин}
{501}{}{}
{600}{}{Житель Ёранилища}
{601}{}{}
{700}{}{Энерго Доспехи}
{800}{}{Смотритель Ёранилища}
{900}{}{Супер Мутант}
{901}{}{}
{1000}{}{Главный Крото-Крысс}
{1001}{}{}
{1100}{}{Рад Скорпион}
{1101}{}{Рад Скорпион}
{1200}{}{Некто в рясе}
{1300}{}{Торговец}
{1301}{}{}
{1400}{}{Солдат Зомби}
{1401}{}{}
{1500}{}{Женщина в доспехах}
{1600}{}{Светящийся}
{1601}{}{}
{1700}{}{Мужчина в кожанке}
{1800}{}{Крестьянин}
{1900}{}{Женщина в кожанке}
{2000}{}{Крестьянин}
{2100}{}{Мужчина в доспехах}
{2200}{}{Горожанка}
{2201}{}{Женщина с кокетливыми стальными доспехами.}
{2300}{}{Лейтенант Супер Мутантов}
{2301}{}{}
{2400}{}{Горожанка}
{2401}{}{Женщина, затянутая в жесткую кожаную куртку.}
{2500}{}{Найткин}
{2501}{}{}
{2600}{}{Житель Ёранилища}
{2601}{}{}
{2700}{}{Охранник}
{2800}{}{Брама}
{2801}{}{Двухголовая корова - мутант.}
{2900}{}{Крестьянин}
{3000}{}{Крестьянин}
{3100}{}{Мужчина в кожанке}
{3200}{}{Крестьянин}
{3201}{}{}
{3300}{}{Гражданин}
{3301}{}{}
{3400}{}{Житель Ёранилища}
{3500}{}{Житель Ёранилища}
{3501}{}{}
{3600}{}{Пес}
{3601}{}{Собака неопределенного возраста и породы.}
{3700}{}{Женщина}
{3800}{}{Мужчина}
{3900}{}{Крестьянин}
{3901}{}{}
{4000}{}{Крестьянин}
{4001}{}{}
{4100}{}{Некто в Энерго Доспехах}
{4200}{}{Мальчик}
{4201}{}{}
{4300}{}{Меньший Кентавр}
{4301}{}{}
{4400}{}{Мр. Ёанди}
{4500}{}{Летун}
{4501}{}{}
{4600}{}{Писец}
{4700}{}{Смотритель}
{4800}{}{Пещерный Крысс}
{4801}{}{}
{4900}{}{Гизмо}
{5000}{}{Повелитель}
{5100}{}{Рука Смерти}
{5101}{}{}
{5200}{}{Техник}
{5201}{}{}
{5300}{}{Техник}
{5301}{}{}
{5400}{}{Техник}
{5401}{}{}
{5500}{}{Охрана}
{5501}{}{}
{5600}{}{Охрана}
{5601}{}{}
{5700}{}{Охрана}
{5800}{}{Техник}
{5801}{}{}
{5900}{}{Гражданин}
{5901}{}{}
{6000}{}{Бомж}
{6001}{}{}
{6100}{}{Рабочий}
{6101}{}{}
{6200}{}{Служитель Собора}
{6201}{}{}
{6300}{}{Танди}
{6400}{}{Арадеш}
{6500}{}{Сет}
{6600}{}{Торговец}
{6601}{}{}
{6700}{}{Охрана}
{6701}{}{}
{6800}{}{Мантисс}
{6801}{}{}
{6900}{}{Робомозг}
{7000}{}{Рейдер-охранник}
{7100}{}{Гражданин}
{7101}{}{}
{7200}{}{Гражданин}
{7201}{}{}
{7300}{}{Советник Гарла}
{7400}{}{Гражданин}
{7401}{}{}
{7500}{}{Рейдер}
{7600}{}{Ян}
{7700}{}{Летучий Глаз}
{7800}{}{Свино-Крысс}
{7801}{}{}
{7900}{}{Киллиан Даркуотер}
{8000}{}{Ларс}
{8100}{}{Изо}
{8200}{}{Странник}
{8201}{}{}
{8300}{}{Гражданин}
{8301}{}{}
{8400}{}{Гражданин}
{8401}{}{}
{8500}{}{Странник}
{8501}{}{}
{8600}{}{Крестьянин}
{8601}{}{}
{8700}{}{Гражданин}
{8701}{}{}
{8800}{}{Торговец}
{8801}{}{}
{8900}{}{Чужак}
{8901}{}{}
{9000}{}{Охрана}
{9001}{}{}
{9100}{}{Фермер}
{9101}{}{}
{9200}{}{Торговец}
{9201}{}{}
{9300}{}{Крестьянин}
{9301}{}{}
{9400}{}{Нил}
{9500}{}{Крестьянин}
{9501}{}{}
{9600}{}{Рабочий}
{9601}{}{}
{9700}{}{Торговец}
{9800}{}{Крестьянин}
{9801}{}{}
{9900}{}{Вор}
{9901}{}{}
{10000}{}{Чужак}
{10001}{}{}
{10100}{}{Один из Детей Собора}
{10200}{}{Винни}
{10201}{}{}
{10300}{}{Странник}
{10301}{}{}
{10400}{}{Сет}
{10500}{}{Гаррет}
{10600}{}{Мертвяк}
{10601}{}{}
{10700}{}{Найткин-охрана}
{10701}{}{}
{10800}{}{Крутой Супер Мутант}
{10801}{}{}
{10900}{}{Мертвяк Охранник}
{10901}{}{}
{11000}{}{Подземелец}
{11001}{}{}
{11100}{}{Дэн}
{11200}{}{Шериф Грини}
{11300}{}{Участковый Фрай}
{11400}{}{Кейн}
{11500}{}{Деметра}
{11600}{}{Кери}
{11700}{}{Рутгер}
{11800}{}{Дарен Ёайтауэр}
{11900}{}{Марта}
{12000}{}{Лоренцо}
{12100}{}{Джейкоб}
{12200}{}{Песик}
{12300}{}{Жасмин}
{12400}{}{Трой}
{12500}{}{Даррелл}
{12600}{}{Талус}
{12700}{}{Томас}
{12800}{}{Маттия}
{12900}{}{Разор}
{13000}{}{Танглер}
{13100}{}{Талиус}
{13200}{}{Габриель}
{13300}{}{Авеллоне}
{13400}{}{Ван Ёаген}
{13500}{}{Сурф}
{13600}{}{Лэшер}
{13700}{}{Барракус}
{13800}{}{Джеремия}
{13900}{}{Медик Супер Мутант}
{14000}{}{Гидеон}
{14001}{}{Его руки светятся от странной энергии.}
{14100}{}{Доминик}
{14101}{}{Его глаза светятся от странной энергии.}
{14200}{}{Люси}
{14201}{}{Ее голова светится от странной энергии.}
{14300}{}{Виггуп}
{14301}{}{По его телу растекаются искорки энергии.}
{14400}{}{Сид Вишиоз}
{14500}{}{Лейтенант Супер Мутантов}
{14600}{}{Лаура}
{14700}{}{Морфей}
{14800}{}{Николь}
{14900}{}{Врее}
{15000}{}{Макссон}
{15100}{}{Ромбус}
{15200}{}{Кэббот}
{15300}{}{Декер}
{15400}{}{Бутч}
{15500}{}{Локсли}
{15600}{}{Джейн}
{15700}{}{Гарольд}
{15800}{}{Гарри}
{15900}{}{Крутой Крысс}
{15901}{}{}
{16000}{}{Облученный Крысс}
{16001}{}{}
{16100}{}{Крутой Облученный Крысс}
{16101}{}{}
{16200}{}{Меньший Крото-Крысс}
{16201}{}{}
{16300}{}{Койот}
{16301}{}{}
{16400}{}{Большая Брама}
{16401}{}{}
{16500}{}{Отродье Руки Смерти}
{16501}{}{}
{16600}{}{Гнусный Рад Скорпион}
{16601}{}{}
{16700}{}{Кровавый Летун}
{16701}{}{}
{16800}{}{Большой Кентавр}
{16801}{}{}
{16900}{}{Жалкий крестьянин}
{16901}{}{}
{17000}{}{Крестьянин}
{17001}{}{}
{17100}{}{Фермер}
{17101}{}{}
{17200}{}{Рабочий}
{17201}{}{}
{17300}{}{Фермер}
{17301}{}{}
{17400}{}{Торговец}
{17401}{}{}
{17500}{}{Охрана}
{17501}{}{}
{17600}{}{Большой Мантисс}
{17601}{}{}
{17700}{}{Подлый Свино-Крысс}
{17701}{}{}
{17800}{}{Фермер}
{17801}{}{}
{17900}{}{Рабочий}
{17901}{}{}
{18000}{}{Торговец}
{18001}{}{}
{18100}{}{Охрана}
{18101}{}{}
{18200}{}{Светляк}
{18201}{}{}
{18300}{}{Безумный светляк}
{18301}{}{}
{18400}{}{Зомби}
{18401}{}{}
{18500}{}{Охрана}
{18501}{}{}
{18600}{}{Охрана Супер Мутант}
{18601}{}{}
{18700}{}{Подлый Супер Мутант}
{18701}{}{}
{18800}{}{Безумный Супер Мутант}
{18900}{}{Мертвый Супер vутант}
{19000}{}{Крутой Найткин}
{19001}{}{}
{19100}{}{Мертвый Найткин}
{19101}{}{}
{19200}{}{Супер Найткин}
{19300}{}{Главный Найткин}
{19301}{}{}
{19400}{}{Охрана}
{19401}{}{}
{19500}{}{Торговец}
{19501}{}{}
{19600}{}{Охрана}
{19601}{}{}
{19700}{}{Охрана}
{19701}{}{}
{19800}{}{Охрана}
{19801}{}{}
{19900}{}{Девка}
{19901}{}{}
{20000}{}{Писец}
{20100}{}{Охрана}
{20101}{}{}
{20200}{}{Чужак}
{20201}{}{}
{20300}{}{Вор}
{20301}{}{}
{20400}{}{Наемник}
{20401}{}{}
{20500}{}{Охрана}
{20501}{}{}
{20600}{}{Житель Ёранилища}
{20700}{}{Девка}
{20800}{}{Доктор Смерть}
{20900}{}{Гретч}
{21000}{}{Тикхо}
{21100}{}{Джонатан}
{21200}{}{Джейкоб}
{21300}{}{Мэри}
{21400}{}{Рахаэль}
{21500}{}{Калеб}
{21600}{}{Странник}
{21700}{}{Чужак}
{21800}{}{Вор}
{21900}{}{Наемник}
{22000}{}{Охрана}
{22100}{}{Гражданин}
{22200}{}{Чужак}
{22300}{}{Вор}
{22400}{}{Наемник}
{22500}{}{Охрана}
{22600}{}{Гражданин}
{22700}{}{Странник}
{22800}{}{Чужак}
{22900}{}{Вор}
{23000}{}{Наемник}
{23100}{}{Охрана}
{23200}{}{Гражданин}
{23300}{}{Странник}
{23400}{}{Наемник}
{23500}{}{Охрана}
{23600}{}{Странник}
{23700}{}{Чужак}
{23800}{}{Вор}
{23900}{}{Наемник}
{24000}{}{Охрана}
{24100}{}{Вор}
{24200}{}{Наемник}
{24300}{}{Охрана}
{24400}{}{Странник}
{24500}{}{Чужак}
{24600}{}{Вор}
{24700}{}{Наемник}
{24800}{}{Охрана}
{24900}{}{Странник}
{25000}{}{Чужак}
{25100}{}{Вор}
{25200}{}{Наемник}
{25300}{}{Охрана}
{25400}{}{Странник}
{25500}{}{Чужак}
{25600}{}{Вор}
{25700}{}{Наемник}
{25800}{}{Охрана}
{25900}{}{Странник}
{26000}{}{Чужак}
{26100}{}{Вор}
{26200}{}{Наемник}
{26300}{}{Охрана}
{26400}{}{Начинающий рыцарь}
{26500}{}{Старший начинающий рыцарь}
{26600}{}{Помощник рыцаря}
{26700}{}{Умелый Рыцарь}
{26800}{}{Старший рыцарь}
{26900}{}{Начинающий рыцарь}
{27000}{}{Старший начинающий рыцарь}
{27100}{}{Помощник рыцаря}
{27200}{}{Умелый Рыцарь}
{27300}{}{Старший рыцарь}
{27400}{}{Младший паладин}
{27500}{}{Паладин}
{27600}{}{Старший паладин}
{27700}{}{Младший паладин}
{27800}{}{Паладин}
{27900}{}{Старший паладин}
{28000}{}{Начинающий Писец}
{28100}{}{Старший начинающий писец}
{28200}{}{Помощник писца}
{28300}{}{Умелый писец}
{28400}{}{Главный писец}
{28500}{}{Начинающий Писец}
{28600}{}{Старший начинающий писец}
{28700}{}{Помощник писца}
{28800}{}{Умелый писец}
{28900}{}{Главный писец}
{29000}{}{Некто в рясе}
{29100}{}{Дитя Повелителя}
{29200}{}{Священнослужитель}
{29300}{}{Женщина в рясе}
{29400}{}{Дитя Повелителя}
{29500}{}{Зверь Повелителя}
{29600}{}{Вор Повелителя}
{29700}{}{Охрана Повелителя}
{29800}{}{Зверь Повелителя}
{29900}{}{Вор Повелителя}
{30000}{}{Охрана Повелителя}
{30100}{}{Доктор}
{30200}{}{Катюша}
{30300}{}{Сашка}
{30301}{}{Перед вами сибирская ездовая собака, терпеливо ждущая своего хозяина.}
{30400}{}{Таинственный незнакомец}
{30500}{}{Безмозглый мертвяк}
{30600}{}{Глазной Шар типа 2}
{30700}{}{Яйцо}
{30701}{}{Яйцо Руки Смерти}
{30800}{}{Дуган}
{30900}{}{Главная Рука Смерти}
{31000}{}{Молот}
{31100}{}{Мертвый странник}
{31200}{}{Кенджи}
