{100}{}{Bõrpáncél}
{101}{}{Your basic all-leather apparel, a popular choice in the Wasteland. Finely crafted from tanned brahma hide. A lightweight and relatively simply construction, likely based on pre-War armor designed for Motorcycle Football and other dangerous contact sports.}
{200}{}{Fémpáncél}
{201}{}{Polished metal plates, crudely forming a suit of armor. Provides better protection than all leather armors, but slows the wearer's mobility somewhat. This model features spikes added to the shoulder, a popular fashion statement this year!}
{300}{}{Erõpáncél}
{301}{}{A model T-51b West Tek self-contained suit of Powered Armor, with a 60000-watt TX-28 MicroFusion reactor powering HiFlo hydraulics, and enough fuel to last 100 years. It is made of an advanced poly-laminate composite with 10 microns silver ablative coating, and features a bullet-proof eyeslit on the helmet.}
{400}{}{Kés}
{401}{}{Egy pengeéles szúró- és vágófegyver. Min. ER: 2.}
{500}{}{Tonfa}
{501}{}{A hadsereg és a rendõrség által használt népnevelõ eszköz. Anyaga tömör fa. Min. ER: 3.}
{600}{}{Harci pöröly}
{601}{}{Jókora kalapács hosszú nyéllel. Nagyon kedvelt az õt felemelni képes emberek körében. Min. ER: 6.}
{700}{}{Lándzsa}
{701}{}{Borotvaéles szálfegyver. Nyele fából készült, a hegye pedig edzett acél. Min. ER: 4.}
{800}{}{10 mm-es pisztoly}
{801}{}{10 mm-es Colt 6520 öntöltõ pisztoly. Az elsütõ billentyû minden egyes meghúzásakor automatikusan csõre tölti a lõszert, amíg a tár ki nem ürül. A 10 mm-es lövedékeket kibocsátó lõfegyver csak egyes lövések leadására képes. Min. ER: 3.}
{900}{}{10 mm-es GPI}
{901}{}{Heckler & Koch MP9-es géppisztoly (10 mm-es változat). Közepes méretû GPI, mely képes egyes lövések és sorozatok leadására is. Min. ER: 4.}
{1000}{}{Vadászpuska}
{1001}{}{,223-as kaliberû Colt Rangemaster félautomata vadászpuska. Csak egyes lövés adható le vele. Min. ER: 5.}
{1100}{}{Flamethrower}
{1101}{}{A Flambe 450 Flamer(tm) model flamethrower, varmiter variation. Sprays and ignites a short blast of flammable liquid. Requires specialized fuel to work properly. Tends to cause biological targets to die painfully and hilariously.  Min STR: 6}
{1200}{}{Gépágyú}
{1201}{}{Rockwell CZ53-as kézi gépágyú. Ez egy többcsövû forgófejes gépfegyver, mely 5 mm-es lövedékekkel tüzel megközelítõleg 60000-es fordulatszámon. Min. ER: 7.}
{1300}{}{Rakétavetõ}
{1301}{}{Egy Rockwell BigBazooka rakétavetõ, mely a "Deluxe" változatú 1,5 kg-os elsütõbillentyûvel van felszerelve. Páncéltörõ és robbanófejes rakétákat is képes kilõni. Min. ER: 6.}
{1400}{}{Robbanó rakéta}
{1401}{}{Egy mezei rakéta, bazi nagy robbanófejjel.}
{1500}{}{Plazmapuska}
{1501}{}{Winchester Model P94 típusú plazmapuska. Ipari osztályú energiafegyver, mely szuperforró plazmanyalábokat lõ ki szupravezetõ csövén keresztül. Energiáját mikro-fúziós elemekbõl meríti. Min. ER: 6.}
{1600}{}{Lézerpisztoly}
{1601}{}{Wattz 1000 gyártmányú lézerpisztoly. Ez egy utcai változat, ezért a teljesítménye kisebb, mint a rendõrségi vagy a katonai modelleké. Mûködtetéséhez kis elemekre van szükség. Min. ER: 3.}
{1700}{}{Harci páncél}
{1701}{}{First created in 2051, this lightweight, high-tech, military-grade armor protects the wearer from ballistic trauma with hard plates made from advanced defensive polymers and ceramics, and features a flexible body suit interwoven with thermal-dissipative membranes and bulletproof material.}
{1800}{}{,44-es Desert Eagle}
{1801}{}{Egy õsi .44-es Desert Eagle magnum. A késõ XX. századi filmek tették minden idõk egyik legnépszerûbb maroklõfegyverévé. Min ER: 4.}
{1900}{}{Kõdarab}
{1901}{}{Egy egyszerû kõdarab. A Granite-Inc. legkorszerûbb modellje. Min. ER: 1.}
{2000}{}{Feszítõvas}
{2001}{}{A very solid and heavy piece of steel with a hooked wedge, specially designed to exert leverage. Or pound heads.  Min STR: 5.}
{2100}{}{Boxer}
{2101}{}{Acélból készített, ökölre húzható fegyver. Védi a kezet, és nagyobb sebzést biztosít pusztakezes harcban. Min. ER: 1.}
{2200}{}{14 mm-es pisztoly}
{2201}{}{Sig-Sauer típusú 14 mm-es automata pisztoly. Óriási méretû, egyes lövéseket leadó, precíz fegyver. Min. ER: 4.}
{2300}{}{Rohampuska}
{2301}{}{Egy AK-112-es rohampuska. Régi modell, a háború óta nem használja a kutya se. Képes egyenként vagy akár sorozatokban is szórni a nagy sebességû 5 mm-es lövedékeket. Min. ER: 5.}
{2400}{}{Plazmapisztoly}
{2401}{}{Glock 86-os plazmapisztoly, melyet a Gaston Glock mesterséges agy tervezett. Kis nyalábokban nagy hõmérsékletû plazmát lõ ki magából. Kis energiacellákkal mûködik. Min. ER: 4.}
{2500}{}{Repeszgránát}
{2501}{}{Mezei repeszgránát. A gyilkos repeszekbõl álló burkolat kevés, ám nagy erejû robbanószert tartalmaz. Becsapódáskor robban. Min. ER: 3.}
{2600}{}{Plazmagránát}
{2601}{}{Mágnesesen lezárt plazmatároló egység detonátorral ellátva. Becsapódáskor túlhevített plazma lövell ki a gránátból. Min. ER: 4.}
{2700}{}{Grenade (EMP)}
{2701}{}{Elektromágneses gránát, amely a detonáció során kiterjedt mágneses mezõt hoz létre. Szerves élõlényekre nincs hatással. Min. ER: 4.}
{2800}{}{Lézer gépágyú}
{2801}{}{H&K L30-as gyorstüzelõ lézerágyú. Kifejezetten katonai használatra hozták létre, a háború kirobbanásakor még csak prototípusként létezett. Az hat csõ lehetõvé teszi, hogy hosszabb ideig lehessen vele tüzelni a túlmelegedés elõtt. Mikro-fúziós elemekkel üzemel. Min. ER: 6.}
{2900}{}{10 mm ÜH}
{2901}{}{10 mm kaliberû köpenyes üregeshegyû lõszer.}
{3000}{}{10 mm PT}
{3001}{}{10 mm-es páncéltörõ lövedék.}
{3100}{}{,44 ÜH Magnum}
{3101}{}{Egy tár ,44-es magnum típusú, üreges hegyû lõszer.}
{3200}{}{Lángszóró üzemanyag}
{3201}{}{Ez a tartály lángszórókba való fokozottan gyúlékony folyadékot tartalmaz.}
{3300}{}{14 mm PT}
{3301}{}{Nagy kaliberû, páncéltörõ lõszer.}
{3400}{}{,223 FK}
{3401}{}{0,223 hüvelyk átmérõjû, fémköpenyes töltény.}
{3500}{}{5 mm ÜH}
{3501}{}{Egy tár, mely kis kaliberû lõszert tartalmaz. 5 mm-es átmerõ és köpenyelt üreges hegy jellemzi.}
{3600}{}{5 mm PT}
{3601}{}{Ebben a tárban kis kaliberû, 5 mm-es páncéltörõ muníció van.}
{3700}{}{PT rakéta}
{3701}{}{Rakéta, melyben kisebb robbanótöltet van, de páncéltörõ tulajdonságokkal bír.}
{3800}{}{Kis energiacella}
{3801}{}{Kis méretû, független energiatároló eszköz.}
{3900}{}{Mikro-fúziós cella}
{3901}{}{Közepes méretû, fúziós energiatermelõ egység.}
{4000}{}{Stimpakk}
{4001}{}{A stimpak, or stimulation delivery package, is a hand-held portable healing unit that consists of a syringe for containing and delivering the medication, and a gauge for measuring the status of the stimpak's contents. When injected, it provides immediate healing of medium wounds and minor tissue damage. No side effects.}
{4100}{}{Kupakok}
{4101}{}{This bag holds your bottle caps; the accepted monetary unit of the post-apocalyptic world. Referred to by some as "Hub script" or simply "scripts", and sometimes by the archaic pre-War term "buck".}
{4200}{}{Hûtõ}
{4201}{}{A refrigerator. Out of coolant. This one is rusted and lonely.}
{4300}{}{Mélyhûtõ láda}
{4301}{}{Régi stílusú fagyasztó láda. A zsanérok még mindig jó állapotban vannak.}
{4400}{}{Mélyhûtõ láda}
{4401}{}{Egy jéggel töltött láda, még a letûnt korok idejébõl. A csuklópántok még mindig jól mûködnek.}
{4500}{}{Dobókés}
{4501}{}{Ezt a kést kifejezetten dobásra egyensúlyoztak ki. Titánból készült, melyet lézerrel fentek félelemtesen élesre. Min. ER: 3.}
{4600}{}{Zsák}
{4601}{}{An average-sized bag, useful for holding things. Made from woven brahma hairs.}
{4700}{}{Elsõsegély csomag}
{4701}{}{Egy kis készlet, mely a lagalapvetõbb orvosi eszközöket tartalmazza: kötszer, fásli, fertõtlenítõ folyadék, stb.}
{4800}{}{RadAway}
{4801}{}{Vegyi oldat, mely megköti a radioaktív részecskéket, amik így ki tudnak ürülni a szervezetbõl. A megfelelõ hatás eléréséhez kell némi idõ.}
{4900}{}{Ellenméreg}
{4901}{}{Ebben az üvegben házilag kotyvasztott méreg-ellenszer található. Valami tejszerû folyadék, amiben radskorpiók különbözõ darabjai úszkálnak.}
{5000}{}{Reserved Item}
{5001}{}{This is a reserved item.  DO NOT USE.}
{5100}{}{Dinamit}
{5101}{}{Stabil nitroglicerint tartalmazó nagyerejû robbanószer idõzítõvel ellátva.}
{5200}{}{Geiger-számláló}
{5201}{}{Wattz Electronics gyártmányú "C-Radz" Geiger-Müller számláló. Jelzi a radioaktivitást, és annak erõsségét.}
{5300}{}{Mentát}
{5301}{}{Egy doboznyi elmemódosító pirula. Javítja a memóriát, és felgyorsítja az agymûködést. Könnyen függõséget okozhat.}
{5400}{}{Stealth Boy}
{5401}{}{"RobCo Stealth Boy 3001" személyi álcázó készülék. Olyan mezõt hoz létre, amely a visszavert fényt a tárgy másik oldalára irányítja.}
{5500}{}{Víztisztító csip}
{5501}{}{Egy víztisztítást vezérlõ számítógép processzora. Egész meglepõ módon épp úgy néz ki, mint amilyet a Menedékben hiányolnak.}
{5600}{}{Dögcédula}
{5601}{}{Katonai dögcédula. Egyedül a Darkwater név olvasható rajta.}
{5700}{}{Poloska}
{5701}{}{Miniatûr hangfelveõ és továbbító készülék.}
{5800}{}{Holodisk}
{5801}{}{This is a Wattz Electronics Holodisk, designed for THT players. Also called a "holotape" or simply "tape", holodisks are durable laser-readable storage devices based on tape holography technology. Suitable for long-term storage of text, audio, or video, they typically hold 64 to 256 kilobytes of data.}
{5900}{}{Mozgásérzékelõ}
{5901}{}{Ez egy Wattz Electronics C-U (ugye veszed a poént...) típusú mozgásérzékelõ. Radarjával jónéhány méter távolságból is képes detektálni a biológiai eredetû anyagokat.}
{6000}{}{Könyvespolc}
{6001}{}{A wooden bookcase in good condition. It's made of wood and might hold books.}
{6100}{}{Könyvespolc}
{6101}{}{This wooden bookcase is in terrible shape and might collapse at any moment.}
{6200}{}{Könyvespolc}
{6201}{}{You don't like the way this particular wooden bookcase is leaning.}
{6300}{}{Könyvespolc}
{6301}{}{A wooden bookcase in good condition. It's made of wood and might hold books.}
{6400}{}{Könyvespolc}
{6401}{}{This wooden bookcase is in terrible shape and might collapse at any moment.}
{6500}{}{Könyvespolc}
{6501}{}{You don't like the way this particular wooden bookcase is leaning.}
{6600}{}{Asztal}
{6601}{}{A wooden desk. Made of wood, has drawers, holds stuff.}
{6700}{}{Asztal}
{6701}{}{This desk has seen better days. You wouldn't even trust it to hold a paperweight.}
{6800}{}{Komód}
{6801}{}{A wooden dresser. Made of wood, has drawers, holds stuff.}
{6900}{}{Komód}
{6901}{}{This wooden dresser seems to be tired of being mistreated.}
{7000}{}{Komód}
{7001}{}{A wooden dresser with one working drawer. Not very exciting.}
{7100}{}{Irradiated Fruit}
{7101}{}{A strange-looking piece of fruit. It does not look particularly tasty. No preservatives and no additional food coloring added. A low-fat food!}
{7200}{}{Aktatáska}
{7201}{}{Bõr aktatáska, "Made in the USA" címkével. Jó állapotban van, de a számzár nem mûködik.}
{7300}{}{A Tudományok nagy könyve}
{7301}{}{Könyvkészlet, mely különbözõ tudományágak ismereteit gyûjti össze.}
{7400}{}{Bõrdzseki}
{7401}{}{A black, heavy leather jacket. You can't help thinking how badass you'd look wearing this, even in the scorching heat of the wastes.}
{7500}{}{MultiTool}
{7501}{}{A super tool set, containing various useful tools and gadgets. The aspiring engineer or repairman should never leave home without it!}
{7600}{}{Elektronikai szakkönyv}
{7601}{}{Elektronikával foglalkozó tankönyv. A borítója szerint "a mindenkiben megbúvó villamosmérnök számára" készült.}
{7700}{}{Elektromos zárnyitó}
{7701}{}{Wattz Electronics gyártmányú "Micromanipulator FingerStuff" típusú zárnyitó, elektromos zárak, és biztonsági berendezések feltörésére.}
{7800}{}{Festmény}
{7801}{}{Kép egy énekesrõl. Már nagyon régi, de a kép borításának köszönhetõen még mindig jó állapotban van.}
{7900}{}{Jelzõfény}
{7901}{}{Jelzõfény, mely egy rövid ideig fényt bocsát ki. A papír kicsit elnyûtt, de amúgy jó állapotban van. Ha aktiválni akarod, csavard el a tetejét!}
{8000}{}{Elsõsegély könyv}
{8001}{}{A study book on the concepts and practical use of First Aid skills. Much of the information is pre-War, however it is still applicable to most in-the-field practices and skills.}
{8100}{}{Nyárson sült iguana}
{8101}{}{Iguana, a saját bõrében sütve.}
{8200}{}{Kulcs}
{8201}{}{Ez a kulcs egy zárhoz tartozik.}
{8300}{}{Kulcscsomó}
{8301}{}{Több kulcs egybefûzve.}
{8400}{}{Tolvajkulcs készlet}
{8401}{}{Egy készlet, mely minden fontos eszközt tartalmaz egyszerûbb zárak kinyításához, beleértve különbözõ fogókat és feszítõket.}
{8500}{}{Plasztikbomba}
{8501}{}{Egy nagy darab, Cordex márkájú, katonai, plasztik robbanószer. Nagyon stabil és óriási pusztítóerõvel bír. Idõzítõ is van rajta.}
{8600}{}{Felderítõk kézikönyve}
{8601}{}{Egy könyv, mely a felderítés elvi és gyakorlati módszereit ismerteti. Hasznos tudnivalókat nyújt a szabadban való túléléshez.}
{8700}{}{Buffout}
{8701}{}{Highly advanced steroids that were popularized before the Great War by professional athletes and their clandestine use of the drug. While in effect, they increase the user's strength, stamina and reflexes. Very addictive.}
{8800}{}{Karóra}
{8801}{}{Egy értékes karóra. Nem mûködik, de még mindig jól néz ki.}
{8900}{}{Motor}
{8901}{}{Ez egy 40 lóerõs, elektromos motor.}
{9000}{}{Hátizsák}
{9001}{}{Hátizsák a fakultatív szíjakkal.}
{9100}{}{Orvosi táska}
{9101}{}{This black bag contains many instruments and therapeutic drugs used by doctors in the application of their trade.}
{9200}{}{Radscorpion Tail}
{9201}{}{Egy radskorpió levágott farka.}
{9300}{}{Szütyõ}
{9301}{}{Egy átlagos méretû szütyõ. Szõtt brahminszõrbõl készült.}
{9400}{}{Sörétes puska}
{9401}{}{Egy "Özvegyítõ" becenevû Winchester márkajelzésû duplacsövû sörétes puska. Rövid csõ, mahagóni markolat. Min ER: 4.}
{9500}{}{12-gauge Shotgun Shells}
{9501}{}{Lõszer sörétes puskához. A lõszeren ez áll: "12-es kaliberû töltény, 3 éven aluli gyermekek elõl gondosan elzárandó!"}
{9600}{}{Piros kódkártya}
{9601}{}{Elektronikus biztonsági kártya, piros színkóddal.}
{9700}{}{Kék kódkártya}
{9701}{}{Elektromos biztonsági kártya, kék színkóddal.}
{9800}{}{Kacatok}
{9801}{}{Egy kis limlom. Mindenbõl egy kevés.}
{9900}{}{Aranymedál}
{9901}{}{Ez egy igen értékes aranymedál.}
{10000}{}{Rádió}
{10001}{}{Egy 2043B típusú rádió adó-vevõ a Wattz Electronicstól. Megbízható, terepszínû modell, RS-121-es interfésszel felszerelve.}
{10100}{}{Öngyújtó}
{10101}{}{Egy jó állapotban lévõ ezüst butánöngyújtó.}
{10200}{}{Fegyvermánia}
{10201}{}{Fegyvermagazin, mely ismertetõket tartalmaz különbözõ tûzfegyverekrõl és azok hatékony használatáról.}
{10300}{}{Nyárson sült iguana}
{10301}{}{Egy adag nyárson sült iguanapecsenye némi zöldséggel.}
{10400}{}{Lejátszó}
{10401}{}{A Wattz Electronics Play-It-For-Me tape recorder. Plays and records the standard 30-minute high-density Record-It-Once tapes, not to be confused with the newer holodisk technology.}
{10500}{}{Kulcs}
{10501}{}{Speciális kulcs.}
{10600}{}{Nuka-Cola}
{10601}{}{Egy üveg Nuka-Cola, a posztnukleáris világ egyik legnépszerûbb itala. Langyos és buborékmentes.}
{10700}{}{Csontok}
{10701}{}{Egy pár fura csont.}
{10800}{}{Csontok}
{10801}{}{Néhány érdekes csont.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation drugs to be taken before exposure, which in the wastes means more or less constantly. No known side effects. Thankfully they have proven to be non-addictive.}
{11000}{}{Pszicho}
{11001}{}{Valószínûleg katonai eredetû, ismeretlen vegyületeket tartalmazó szer. A katonák harci potenciálját hivatott növelni.}
{11100}{}{,44-es FK magnum}
{11101}{}{Egy tár fémköpenyes, .44-es magnum lõszer.}
{11200}{}{Urna}
{11201}{}{Gyönyörû, aranyból készült urna, melyre a "Harriet" nevet gravírozták. Hamvakat tartalmaz.}
{11300}{}{Köpeny}
{11301}{}{A Katedrális Gyermekeinek köpenye.}
{11400}{}{Tangler keze}
{11401}{}{Egy emberi kezet formázó kibernetikus manipulátor. Sajnos megsérült, ami a hanyag eltávolítás egyik jellegzetes velejárója.}
{11500}{}{Szuper harci pöröly}
{11501}{}{Az Acél Testvérisége által a legfejlettebb technológia szerint gyártott kalapács. A lehetõ legnagyobb ütõerõ elérésének érdekében kinetikus energia tároló egységet tartalmaz. Min ER: 5.}
{11600}{}{Hasfelmetszõ}
{11601}{}{Hasfelmetszõ (TM) márkájú rezgõpenge. A kis energiacellákkal mûködõ lánclap gyorsan megtalálja az utat a célpont belsejébe. Min ER: 4.}
{11700}{}{Virág}
{11701}{}{Egy gyönyörû szép virág.}
{11800}{}{Lézerpuska}
{11801}{}{Wattz 2000 márkájú lézerpuska. Mikro-fúziós cellákkal mûködik, így nagyobb a tûzereje, a meghosszabított csõ pedig nagyobb hatótávolságot eredményez. Min ER: 6.}
{11900}{}{Nyaklánc}
{11901}{}{Egy nagyon drága nyaklánc. Ezüst, arany és gyémánt felhasználásával készült.}
{12000}{}{Idegen fegyver}
{12001}{}{Érdekes formájú, idegen lényektõl származó fegyver. Furcsa módon mégis mûködtethetõ kis energiacellákkal. Min ER: 2.}
{12100}{}{9 mm-es}
{12101}{}{A collection of ancient standard 9x19mm rounds, greased heavily to preserve them from the environment. Before the Great War, 9mm was the preferred type of ammunition for small weapons in the south- west Commonwealth, while the military and the Eastern and Western seaboards tended to favor 10mm ammunition.}
{12200}{}{9 mm-es Mauser}
{12201}{}{Mauser M/96 márkájú, 9x19 mm-es lõszert használó Parabellum. Remek állapotban van. Nagyon pontos. Min ER: 3.}
{12300}{}{Pszichikai megsemmmisítõ}
{12301}{}{Egy különös, ismeretlen technológiával gyártott készülék.}
{12400}{}{Sör}
{12401}{}{Valamiféle házi készítésû sör.}
{12500}{}{Pia}
{12501}{}{Õsi szeszes ital, még a háború elõtti idõkbõl.}
{12600}{}{Kulacs}
{12601}{}{A container, also called a "canteen", designed for the holding and preservation of water or other liquids. Before the Great War, these were commonly used by hikers, campers, soldiers and workers in the field.}
{12700}{}{Kötél}
{12701}{}{A strong, thick line of braided fibers. About 20 feet in length.}
{12800}{}{Láda}
{12801}{}{Zárható tárolóeszköz az ágy lábánál.}
{12900}{}{Láda}
{12901}{}{Zárható tárolóeszköz az ágy lábánál.}
{13000}{}{Láda}
{13001}{}{Zárható tárolóeszköz az ágy lábánál.}
{13100}{}{Láda}
{13101}{}{Zárható tárolóeszköz az ágy lábánál.}
{13200}{}{Öltözõszekrény}
{13201}{}{A storage container. Metal, holds stuff, can be locked.}
{13300}{}{Öltözõszekrény}
{13301}{}{A storage container. Metal, holds stuff, can be locked.}
{13400}{}{Öltözõszekrény}
{13401}{}{A storage container. Metal, holds stuff, can be locked.}
{13500}{}{Öltözõszekrény}
{13501}{}{A storage container. Metal, holds stuff, can be locked.}
{13600}{}{Öltözõszekrény}
{13601}{}{A storage container. Metal, holds stuff, can be locked.}
{13700}{}{Öltözõszekrény}
{13701}{}{A storage container. Metal, holds stuff, can be locked.}
{13800}{}{Öltözõszekrény}
{13801}{}{A storage container. Metal, holds stuff, can be locked.}
{13900}{}{Öltözõszekrény}
{13901}{}{A storage container. Metal, holds stuff, can be locked.}
{14000}{}{Beléptetõ kártya}
{14001}{}{Biztonsági beléptetõ kártya. Még mindig mûködöképes állapotban van.}
{14100}{}{KGY jelvény}
{14101}{}{Egy jelvény, mely a Katedrális Gyermekeinek szimbólumát ábrázolja. Kinézete egy kulcsra emlékeztet téged.}
{14200}{}{KGY jelvény}
{14201}{}{Jelvény, mely a Katedrális Gyermekeinek szimbólumát ábrázolja. Kinézete egy kulcsra emlékeztet téged.}
{14300}{}{Mesterlövész puska}
{14301}{}{DKS-501 mesterlövész puska. Kiváló, nagy hatótávolságú fegyver. Eredetileg .308-as kaliberû, de ezt a darabot a jóval egyszerûbb .223-as lövedékek kilövésére módosították. Min ER: 5.}
{14400}{}{Szuper Stimpakk}
{14401}{}{Also referred to as simply a "superstim", this is a very advanced and powerful piece of healing technology. While it is capable of healing even severe wounds and major tissue damage, it also causes some internal hemorrhaging to the recipient after a short period of time, due to the powerful nature of the chemicals used.}
{14500}{}{Könyvespolc}
{14501}{}{A wooden bookshelf, quietly keeping to itself.}
{14600}{}{Könyvespolc}
{14601}{}{A wooden bookshelf, quietly keeping to itself.}
{14700}{}{Könyvespolc}
{14701}{}{A wooden bookshelf, quietly keeping to itself.}
{14800}{}{Könyvespolc}
{14801}{}{A wooden bookshelf, quietly keeping to itself.}
{14900}{}{Könyvespolc}
{14901}{}{A wooden bookshelf, quietly keeping to itself.}
{15000}{}{Könyvespolc}
{15001}{}{A wooden bookshelf, quietly keeping to itself.}
{15100}{}{Polc}
{15101}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15200}{}{Polc}
{15201}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15300}{}{Polc}
{15301}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15400}{}{Polc}
{15401}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15500}{}{Polc}
{15501}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15600}{}{Polc}
{15601}{}{A set of wooden shelves. It looks much too heavy to carry with you.}
{15700}{}{Munkasztal}
{15701}{}{Munkaasztal. Bizony-bizony, a jó öreg szabványos munkaasztal. Jól mutat a helyén.}
{15800}{}{Szerszámos tábla}
{15801}{}{Ezen a munkaasztal feletti táblán különbözõ szerszámok találhatóak.}
{15900}{}{Molotov-koktél}
{15901}{}{Házi készítésû gyújtógránát. Min ER: 3.}
{16000}{}{Elektromos ösztöke}
{16001}{}{"A farmer legjobb barátja." Wattz Electronics gyártmány. Kis energiacellák mûködtetik. Min ER: 4.}
{16100}{}{Red Ryder BB puska}
{16101}{}{An official Red Ryder BB gun. As you examine this air rifle, a tumbleweed bounces past you. You hear the distant laughter of children...  Min STR: 3.}
{16200}{}{Red Ryder LE BB puska}
{16201}{}{This is the Limited Edition, carbine-action, hundred-shot version of the Red Ryder BB gun, also featuring a compass in the stock! A true classic. Don't shoot your eye out, kid!  Min STR: 4.}
{16300}{}{BBs}
{16301}{}{A box containing BBs from before the war. In excellent condition. Stainless steel.}
{16400}{}{Brotherhood Disk}
{16401}{}{A holodisk with information about the Brotherhood of Steel.}
{16500}{}{Iguana árusító hely}
{16501}{}{Bob Iguana Falatkáinak otthona. Hogyan lehet nem szeretni a frissen sült, ropogós iguanát?}
{16600}{}{Asztal}
{16601}{}{Egy szabványos asztal. Dolgok tárolására alkalmas.}
{16700}{}{Asztal}
{16701}{}{Egy szabványos asztal. Dolgok tárolására alkalmas.}
{16800}{}{Cucc}
{16801}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{16900}{}{Cucc}
{16901}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17000}{}{Cucc}
{17001}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17100}{}{Cucc}
{17101}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17200}{}{Cucc}
{17201}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17300}{}{Cucc}
{17301}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17400}{}{Cucc}
{17401}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17500}{}{Cucc}
{17501}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17600}{}{Cucc}
{17601}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17700}{}{Cucc}
{17701}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17800}{}{Cucc}
{17801}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{17900}{}{Cucc}
{17901}{}{Különbözõ tárgyak, azaz ismertebb nevükön "cuccok".}
{18000}{}{Doboz}
{18001}{}{Különbözõ dolgokkal telerámolt fadoboz.}
{18100}{}{Asztal}
{18101}{}{Egy közönséges asztal. Ha láttál egyet, láttad mindet.}
{18200}{}{Asztal}
{18201}{}{Egy közönséges asztal.}
{18300}{}{Asztal}
{18301}{}{Egy közönséges asztal.}
{18400}{}{Asztal}
{18401}{}{Egy közönséges asztal.}
{18500}{}{Asztal}
{18501}{}{Egy közönséges asztal.}
{18600}{}{Asztal}
{18601}{}{Egy közönséges asztal.}
{18700}{}{Asztal}
{18701}{}{Egy közönséges asztal.}
{18800}{}{Szekrény}
{18801}{}{A locker. Can be locked, holds stuff.}
{18900}{}{Szekrény}
{18901}{}{A locker. Can be locked, holds stuff.}
{19000}{}{FEV Hololemez}
{19001}{}{Hololemez, mely orvosi információkat tartalmaz. Használd, hogy a tartalma bekerüljön a PipBoyba!}
{19100}{}{Biztonsági lemez}
{19101}{}{Hololemez, a címkéjén a "Biztonsági napló" szöveg olvasható. Használd, hogy a tartalma bekerüljön a PipBoyba!}
{19200}{}{Alfa kísérleti lemez}
{19201}{}{Egy hololemez. Ez áll a címkéjén: "Alfa kísérleti napló"}
{19300}{}{Delta kísérleti lemez}
{19301}{}{Egy hololemez. Ez áll a címkéjén: "Delta kísérleti napló"}
{19400}{}{The Master's Guns}
{19401}{}{These are attached to The Master. They look like the standard H&K L30 Gatling Laser but you can't be sure.}
{19500}{}{Testvériségi szabályzat}
{19501}{}{A holodisk, with a rough symbol of the Brotherhood of Steel inscribed on it. Use the disk to transfer the data to your Pip-Boy 2000.}
{19600}{}{Mutáns rádiókommunikációk}
{19601}{}{This holodisk looks like it was set to record audio data from a radio. Use the disk to transfer the information to your Pip-Boy 2000.}
{19700}{}{Doboz}
{19701}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{19800}{}{Doboz}
{19801}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{19900}{}{Doboz}
{19901}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20000}{}{Doboz}
{20001}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20100}{}{Doboz}
{20101}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20200}{}{Doboz}
{20201}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20300}{}{Doboz}
{20301}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20400}{}{Doboz}
{20401}{}{High-tech crate made of a sturdy lightweight composite material. Probably used for the storage of weapons or medical equipment.}
{20500}{}{Flare (Lit)}
{20501}{}{Jelzõfény, mely egy rövid ideig fényt bocsát ki. A papír kicsit elnyûtt, de amúgy jó állapotban van. Éppen ég.}
{20600}{}{Dynamite (Ticking)}
{20601}{}{Stabil nitroglicerint tartalmazó nagyerejû robbanószer. Idõzítõvel vanellátva, ami most éppen ketyeg.}
{20700}{}{Geiger Counter (Activated)}
{20701}{}{Wattz Electronics gyártmányú "C-Radz" Geiger-Müller számláló. Jelzi a radioaktivitást, és annak erõsségét. Be van kapcsolva.}
{20800}{}{Motion Sensor (Activated)}
{20801}{}{Wattz Electronics gyártmányú C-U típusú mozgásérzékelõ. Radarjával érzékeli a szerves létformák mozgását egy bizonyos hatótávolságig. Be van kapcsolva.}
{20900}{}{Plastic Explosives (Ticking)}
{20901}{}{Egy nagy darab, Cordex márkájú, katonai, plasztik robbanószer. Nagyon stabil és óriási pusztítóerõvel bír. Idõzítõ is van rajta, ami most épp ketyeg.}
{21000}{}{Stealth Boy (Activated)}
{21001}{}{RobCo Stealth Boy 3001 személyi álcázó készülék. Egy mezõt hoz létre, amely a visszavert fényt a tárgy másik oldalára irányítja.}
{21100}{}{Csontok}
{21101}{}{Valaha Ednek hívták. Már halott.}
{21200}{}{Tandi}
{21201}{}{Épp Tandi kiszabadításáért próbálsz valamit ajánlani.}
{21300}{}{Gizmo maradványai}
{21301}{}{Ez itt a halott Gizmo, Szemétváros bûnbandájának fõnöke. Eléggé büdös.}
{21400}{}{Asztal}
{21401}{}{Némi vizsgálódás után arra a következtetésre jutsz, hogy "ez bizony tényleg egy asztal".}
{21500}{}{A Testvériség Története}
{21501}{}{Az Acél Testvériségének története. Használata után a PipBoyban olvashatod a tartalmát.}
{21600}{}{Maxson története}
{21601}{}{RESERVED}
{21700}{}{Maxson folyóirata}
{21701}{}{RESERVED}
{21800}{}{Könnyû sérülés gyógykezelése}
{21801}{}{Akkor vásárold meg ezt az opciót, ha nem túl komolyak a sérüléseid.}
{21900}{}{Közepes sérülés gyógykezelése}
{21901}{}{Akkor vásárold meg ezt az opciót, ha nem csak karcolásaid vannak.}
{22000}{}{Súlyos sérülés gyógykezelése}
{22001}{}{Akkor vásárold meg ezt az opciót, ha komoly sérülések értek.}
{22100}{}{Beléptetõ kártya}
{22101}{}{Kulcskártya, melynek egyszerû elektronikája tartalmazza a beléptetõ kódot.}
{22200}{}{Kapcsoló}
{22201}{}{Elektromos váltóberendezés, hatalmas karral. Úgy tûnik, hogy nem rég készült és nagyon nagy kezekre tervezték.}
{22300}{}{Sárga kódkártya}
{22301}{}{Elektronikus biztonsági kártya sárga színkóddal.}
{22400}{}{Szobrocska}
{22401}{}{A PipBoy figurájára hasonlít, de ebben nem vagy biztos.}
{22500}{}{Nem tudod, mi ez}
{22501}{}{Közelebbrõl megnézvén ezt az izét, még mindig nem tudod, mi ez.}
{22600}{}{Egy doboz tészta}
{22601}{}{Fogalmad sincs, mit jelent az, hogy "Instant Spagetti".}
{22700}{}{Valami kisméretû poros doboz}
{22701}{}{Tipikus TV nasi. Nem vagy benne biztos, mi ez, de aligha ehetõ. Arról sem vagy meggyõzõdve, hogy valaha is az volt.}
{22800}{}{Használati utasítás}
{22801}{}{A technical repair manual and desk reference for the T-51b Powered Armor. It seems to explain, in lengthy and boring detail, everything you'd ever want to know about Power Armor repair, use and maintenance.}
{22900}{}{Kicsiny szerkezet}
{22901}{}{This is a Systolic Motivator. This unusual piece of machinery is very small, but surprisingly heavy for its size. It looks very high-tech but you have no idea what it would be used for.}
{23000}{}{Menedék napló}
{23001}{}{A számítógépes rendszer naplója a menedék fontosabb eseményeirõl. Lehet, hogy sérült.}
{23100}{}{Military Base Password}
{23101}{}{So much for security. Remember kids, never write down your password.}
{23200}{}{Megerõsített erõpáncél}
{23201}{}{A modified suit of T-51b Powered Armor. The chemical hardening process has improved the defensive capability of this high-tech armor system, without hindering mobility or the wearer's protection from radiation.}
{23300}{}{Turbó plazmapuska}
{23301}{}{Módosított Winchester P94 plazmapuska. A gerjesztõkamrát átdrótozták, így gyorsabban tud a plazma kialakulni benne. Min ER: 6.}
{23400}{}{Szöges bokszer}
{23401}{}{A bokszer továbbfejlesztett változata. A szöges bokszer nagyobb sérülést okoz, mivel verekedés közben beletép az ellenfél húsába. Min ER: 1.}
{23500}{}{Erõkesztyû}
{23501}{}{Egy "Nagy Zúzó" becenevû erõkesztyû a BeatCo. mûvektõl. Az egyik legjobb fegyvernek tartják az ökölharcban. Senki nem szeret szembetalálkozni vele. Kis energiacellák mûködtetik. Min ER: 1.}
{23600}{}{Harci kés}
{23601}{}{Kiváló minõségû kés a SharpWit, Inc. jóvoltából. A penge éle garantáltan nem kopik, még egy évtizednyi használat után sem. Min ER: 2.}
{23700}{}{Vegyészeti folyóiratok}
{23701}{}{Némi szakirodalom a vegyészet területérõl. A molekuláis kémiával foglalkozó írások elég érdekesek.}
{23800}{}{F.E.V. (Ghoul)}
{23801}{}{ura ghul brah}
{23900}{}{Testvériségi páncél}
{23901}{}{A superior version of Combat Armor. This armor is issued to all Initiates of the Brotherhood of Steel. The Brotherhood has made many improvements over the standard version, both functionally and cosmetically.}
{24000}{}{Tesla-páncél}
{24001}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy such as plasma and laser fire. Unlike the basic metal armor it strongly resembles, this armor is an actual pre-War military design. It is in good condition.}
{24100}{}{223 Pisztoly}
{24101}{}{Egy ,223-as puska levágott csövû, pisztollyá módosított változata. Egyedülálló darab, melyet nagy precizitással és hozzáértéssel készítettek. Min ER: 5.}
{24200}{}{Harci Sörétes}
{24201}{}{Egy Winchester City-Killer harci sörétes hátsótáras változata. Remek állapotban van, és a "Sivatagi hadviselés" védõfelszereléssel van ellátva, mely különösen megbízhatóvá teszi. Min ER: 5.}
{24300}{}{MacRae's Training}
{24301}{}{Use to increase Melee Damage by 1, and Damage Resistance % (Normal) by 5, permanently.}
{24400}{}{Gold Nugget}
{24401}{}{A nugget of gold.}
{24500}{}{Alien Blaster CHEAT}
{24501}{}{You cheating bastard.}
{24600}{}{Uzi 9mm SMG}
{24601}{}{This is an Uzi submachine gun, 9mm caliber. Amazingly, it's still in working condition. The Uzi was cheap, light and rarely jammed, which made it a classic amongst drugrunners during the early stages of the 21st century.  Min STR: 3.}
{24700}{}{Rat Meat}
{24701}{}{Some chopped-up rat parts. Too bad you didn't read Vault Document VTR-003 "How to Eat Rat", otherwise you'd be able to make it more palatable.}
{24800}{}{Brahma Meat}
{24801}{}{Brahma meat is high in vitamins, minerals, fat, protein, and rads. Too bad you don't have time to cook up some tasty brahma burgers!}
{24900}{}{Dog Meat}
{24901}{}{Tough and chewy, but what did you expect? It's rumored that in the 20th and 21st centuries before the Great War, dog meat was a delicacy in China.}
{25000}{}{Ghoul Meat}
{25001}{}{You're not even sure if this is edible. It smells like death and probably doesn't taste any better.}
{25100}{}{Deathclaw Meat}
{25101}{}{Very tough and dry, but almost 100% protein; the most filling and "healthy" meat you'll find in the wastes.}
{25200}{}{Mantis Chunks}
{25201}{}{If you pretend it's iguana bits, it's not so bad, except for the crunch. Actually, it's still pretty bad.}
{25300}{}{Water Flask (Empty)}
{25301}{}{A container, also called a "canteen", designed for the holding and preservation of water or other liquids. Before the Great War, these were commonly used by hikers, campers, soldiers and workers in the field. This one is empty. Remember kids, avoiding dehydration is an important part of any disaster plan!}
{25400}{}{F.E.V. (Super Mutant)}
{25401}{}{Well, you're a Super Mutant now. But hey, look on the bright side: At least they let you keep your stuff. In any case, your Endurance, Strength, and Radiation Resistance are increased, but your Intelligence is lowered and you can't wear any armor.}
{25500}{}{Mutated Meat}
{25501}{}{You watch the meat intently to make sure it's not moving.}
