{100}{}{Tu déverrouilles la porte.}
{101}{}{Tu as cassé ton passe-partout!}
{102}{}{Tu ne peux pas ouvrir ce verrou.}
{103}{}{Tu n'as pas pu crocheter le verrou.}
{104}{}{La porte est verrouillée.}
{105}{}{La porte est ouverte.}
{106}{}{La porte est fermée mais pas verrouillée.}
{107}{}{La porte est verrouillée.}
{108}{}{La porte grince très fort.}
{109}{}{La porte est déjà déverrouillée.}
{110}{}{Tu n'es pas capable de crocheter le verrou.}
{200}{}{Cette porte n'a pas de verrou à crocheter.}
{201}{}{Tu remarques des irrégularités sur le mur.}
