{100}{}{Voici un Holo-disque.}
{101}{}{Sur le Pip Boy s'affiche: Téléchargement à partir du disque.}
{102}{}{Ce disque semble avoir contenu des jeux.}
{103}{}{Le disque est désormais illisible.}
{104}{}{Ce disque semble mentionner un code d'accès à autre disque.}
{105}{}{Sur un petit écran apparaissent les vestiges d'un film sur la Seconde Guerre mondiale.}
{106}{}{Ce disque semble vide.}
{107}{}{Tu jettes ce disque inutile.}
