{100}{}{Voici une créature luminescente.}
{101}{}{Mm...}
{102}{}{Ahhh...}
{103}{}{La créature luminescente marmonne quelque chose puis se tait. Elle radote sans s'en rendre compte.}
{104}{}{Aucune réaction.}
