{100}{}{To uszkodzony pancerz wspomagany.}
{101}{}{The Power Armor is damaged. You cannot use this until it is repaired.}
{102}{}{Wygl¹da na to, ¿e brakuje mu czêœci, której nie jesteœ w stanie znaleŸæ.}
{103}{}{Jest oczywiste, ¿e nie posiadasz jeszcze umiejêtnoœci pozwalaj¹cych na jego naprawê.}
{104}{}{Naprawiasz pancerz.}
{105}{}{To nic nie daje.}
{106}{}{Nie uda³o ci siê naprawiæ pancerza.}
{107}{}{You earn }
{108}{}{ experience for repairing the Power Armor.}
