{100}{}{To ochroniarz.}
{101}{}{I work for the trader here. I make sure nobody messes with him.}
{102}{}{Masz jakieœ p¹czki?}
{103}{}{Jak coœ zepsujesz, to to kupujesz!}
{104}{}{Z³odzieje bêd¹ zabijani!}
{105}{}{Kupisz coœ? Mo¿e w tym stuleciu?}
{106}{}{Bez tego nie da siê walczyæ z radskorpionami.}
{107}{}{I work for the trader here. I make sure nobody messes with him.}
