{100}{}{To Billy.}
{101}{}{Siemanko.}
{102}{}{Czeœæ, co robisz?}
{103}{}{Mogê dostaæ bramina?}
{104}{}{Witaj. Ee, ¿egnaj.}
{105}{}{Arg!}
{106}{}{Da.}
{107}{}{Po co ci bramin? Masz karawanê? Zreszt¹ to nie ma znaczenia, ja tylko siê nimi zajmujê. To Dan jest ich w³aœcicielem, ale i tak ich nie sprzeda.}
{108}{}{Dlaczego?}
{109}{}{To by³ tylko ¿art.}
{110}{}{Z powodu tych wszystkich gin¹cych karawan. Dan nie ma ¿adnych zbêdnych braminów. Karawany wykorzystuj¹ wiêkszoœæ z nich, pozosta³e s¹ sprzedawane na miêso. E, lepiej przestanê gadaæ; Dan siê wœcieknie, jak zobaczy, ¿e rozmawiam z obc¹ osob¹.}
{111}{}{Aha, OK.}
{112}{}{Nic... To znaczy, zajmujê siê braminami.}
{113}{}{Po co ta w³ócznia? Czy one s¹ niebezpieczne?}
{114}{}{Co to braminy?}
{115}{}{'What's a brahmin?' You must be joking. Brahmin are one of the major food sources and forms of transportation around here. They haul the caravans. Dan says this is a really important job, but it's the bone. And by the way, it's 'brahma' - brahmin is plural. Dork.}
{116}{}{Ach, wiem to!}
{117}{}{Dan ma racjê. Wykonujesz dobr¹ robotê.}
{118}{}{Ta, na to wygl¹da. Baw siê dobrze.}
{119}{}{Hej, nale¿ysz do tych ³achów, prawda?}
{120}{}{Naprawdê? Uwa¿asz tak? Rany, dziêki.}
{121}{}{Nie jesteœ st¹d, prawda? Dam ci jedn¹ wskazówkê: nie daj siê przy³apaæ na kradzie¿y!}
{122}{}{Jasne, dziêki.}
{123}{}{Nawet nie myœlê o kradzie¿y. Kradzie¿ jest z³a.}
{124}{}{Ta, chyba zaczynam siê z tob¹ zgadzaæ. Ta praca nie jest taka z³a, powa¿nie. Sprawia, ¿e z jakiegoœ powodu czujê siê dobrze. Có¿, muszê iœæ, zanim wpadnê w k³opoty.}
{125}{}{Proszê, nie krzywdŸ mnie ani moich braminów.}
{126}{}{Nie rób mi krzywdy!}
{127}{}{Przestañ!}
{128}{}{Proszê, zostaw mnie w spokoju.}
{129}{}{Przera¿asz mnie.}
{130}{}{Hej, co ty próbujesz zrobiæ? Nie mam nic, czego mo¿esz chcieæ.}
{131}{}{Przestañ!}
{132}{}{Niebezpieczne? Nie, naprawdê. Mog¹ rzeczywiœcie paskudnie ugryŸæ, ale s¹ ca³kiem spoko. Du¿o pierdz¹ i bekaj¹. Nie wiem dlaczego.}
{133}{}{To do czego jest ta w³ócznia?}
{134}{}{OK, dziêki.}
{135}{}{O, one potrafi¹ byæ okropnie uparte, kiedy chcê, ¿eby coœ zrobi³y. Po prostu delikatnie szturcham je, ¿eby siê ruszy³y... dodatkowo nie chcê, ¿eby do mnie za blisko podchodzi³y; czasem kopi¹.}
{136}{}{Proszê, nie odzywaj siê do mnie. Dan znowu na mnie nakrzyczy. On naprawdê siê wkurza - i to cholernie - kiedy nie zwracam uwagi na to, co robiê.}
{137}{}{On tylko próbuje pomóc. Pracuj ciê¿ko, a na pewno bêdzie milszy.}
{138}{}{Masz dzieciaku, weŸ 50 kapsli i zabieraj siê od tego palanta.}
{139}{}{OK.}
{140}{}{Aaaaaarg!}
{141}{}{Ru?}
{142}{}{Proszê, nie, ja ju¿ mam wystarczaj¹co du¿e k³opoty.}
{143}{}{Ja PRACUJÊ ciê¿ko!}
{144}{}{Przepraszam, nie to mam na myœli. On tylko próbuje ci pomóc.}
{145}{}{Nie ³¿yj, ty leniwy gówniarzu!}
{146}{}{OK.}
{147}{}{Ta, mo¿e masz racjê... Faktycznie wydaje siê byæ ca³kiem spoko, ale wola³bym, ¿eby tak siê na mnie nie dar³.}
{148}{}{Ta, akurat.}
{149}{}{Chrzañ siê, stary pierdzielu!}
{150}{}{Chrzañ siê, stara wiedŸmo!}
{151}{}{O RANY! Mogê z tego ¿yæ przez resztê ¿ycia! Wielkie dziêki, proszê pana!}
{152}{}{O RANY! Mogê z tego ¿yæ przez resztê ¿ycia! Wielkie dziêki, proszê pani!}
{153}{}{O RANY! Dziêki... Eee?... Ty tylko próbujesz znowu wpakowaæ mnie w k³opoty!}
{154}{}{Proszê ze mn¹ nie rozmawiaæ, Dan jest naprawdê wœciek³y.}
{155}{}{Nie martw siê. Porozmawia³ ze mn¹ i postara siê byæ dla ciebie milszy.}
{156}{}{I powinien! Jesteœ okropnym dzieciakiem!}
{157}{}{Wak.}
{158}{}{Czeœæ!}
{159}{}{Te dziewczyny tam, s¹ naprawdê durne.}
{160}{}{Czeœæ ponownie.}
{161}{}{Braminy s¹ spoko.}
{162}{}{Dan zabiera mnie do Soko³a, jak dobrze pracujê.}
{163}{}{Dan zabierze mnie kiedyœ na karawanê!}
{164}{}{Zostanê poszukiwaczem przygód, jak dorosnê.}
{165}{}{Powaga? O, OK. Mam nadziejê, ¿e nie sta³a mu siê krzywda. On tak naprawdê nie jest taki z³y. On tylko du¿o wrzeszczy.}
{166}{}{Witaj ponownie.}
{167}{}{To czym ty siê zajmujesz?}
{168}{}{Czy mogê dostaæ bramina?}
{169}{}{Tylko przystajê, ¿eby zobaczyæ, jak siê sprawy uk³adaj¹. Czeœæ.}
{170}{}{Arg!}
{171}{}{Da.}
{172}{}{Lepiej wrócê do roboty.}
{173}{}{Te dziewczyny tam, s¹ naprawdê durne.}
{174}{}{Czeœæ ponownie.}
{175}{}{Zostanê poszukiwaczem przygód, jak dorosnê.}
{176}{}{Braminy faktycznie du¿o sra... ee, za³atwiaj¹ siê.}
{177}{}{Nie mogê teraz rozmawiaæ.}
{178}{}{Nie chcê wpaœæ w k³opoty.}
