{100}{}{To Bob, w³aœciciela Iguan Boba.}
{101}{}{OK, OK, mam twoj¹ forsê.}
{102}{}{Mam wiêcej wydatków. Muszê podnieœæ op³atê.}
{103}{}{Pierdolê to. Chcê WSZYSTKIE twoje pieni¹dze teraz, albo bêdziesz martwym Bobem.}
{104}{}{Dla mnie robi siê za gor¹co. Odwo³ujê op³aty.}
{105}{}{Chcê informacji o Kafarze.}
{106}{}{Chcê informacji o doktorze Kostusze.}
{107}{}{Dawaj iguanê na patyku.}
{108}{}{Przykro mi. Ju¿ wiêcej nie p³acê. Rób ze mn¹ co chcesz.}
{109}{}{Bob, przecie¿ byliœmy kumplami! W istocie, mia³eœ dostaæ awans w mojej organizacji. Zamiast tego, zdradzasz mnie. To bardzo rozczarowuj¹ce...}
{110}{}{Bob, czemu mam przyj¹æ "nie" za odpowiedŸ? Zw³aszcza od takiej szumowiny, jak ty?}
{111}{}{Mi³o widzieæ, jak siê stawiasz.}
{112}{}{Twoja reputacja to historia, Bob. Hi-sto-rjaa!}
{113}{}{W porz¹dku, póŸniej zadecydujê, co z tob¹ zrobiæ.}
{114}{}{No to mi³o by³o ciê znaæ, Bob. Powiedz ode mnie "siema" Szatanowi.}
{115}{}{Co tu znowu robisz tak szybko? Jeszcze nie czas na op³atê.}
{116}{}{Masz nerwy jak postronki, skoro pokazujesz tu swoj¹ mordê. Sp³ywaj!}
{117}{}{Hej, nie chcê ¿adnych k³opotów!}
{118}{}{Czeœæ. Witaj w Iguanach Boba, restauracji familijnej. Czy mogê przyj¹æ twoje zamówienie?}
{119}{}{No way, forget it.}
{120}{}{You are? Well, okay...}
{121}{}{To wredny sukinsyn. Nie zadzieraj z nim. Czy coœ jeszcze?}
{122}{}{W porz¹dku. Ile mam ci p³aciæ?}
{123}{}{Chcê }
{124}{}{ caps every five days.}
{125}{}{Doktor Kostucha? Wszystko co wiem, to to, ¿e krêci siê ko³o Z³omowa i jest najtañszym Ÿród³em ¿ywnoœci, jakie mog³em znaleŸæ. To wszystko!}
{126}{}{Zobaczmy co mam na sk³adzie.}
{127}{}{Mam ca³e iguany po dwadzieœcia kapsli.}
{128}{}{I've got prime cut select for eight bucks.}
{129}{}{Wezmê któryœ z autentyków.}
{130}{}{Dla mnie na razie nic. Jestem na diecie.}
{131}{}{Wezmê r¹bankê wyborow¹.}
{132}{}{Mam akurat ochotê dostaæ w ³apê jak¹œ pierwszorzêdn¹ r¹bankê. Nawet za ni¹ zap³acê.}
{133}{}{Uhh... Ja tera nie g³odna.}
{134}{}{Œwietnie! Bierz swoj¹ kasê i wynoœ siê!}
{135}{}{Mo¿esz se to wsadziæ! Nigdy ci nie zap³acê! Sp³ywaj!}
{136}{}{Tak, jasne. Poszukaj sobie lepiej kogoœ innego do wydymania.}
{137}{}{Nie mo¿na rzucaæ ³ajnem i nie pobrudziæ sobie nim paluchów. Wynoœ siê st¹d!}
{138}{}{Z pewnoœci¹. Sp³ywaj!}
{139}{}{Przykro mi. Skoñczy³y nam siê iguany.}
{140}{}{Sure. All I got is the whole iguanas at the moment. Thirty bucks each. You won't find a better roasted iguana in the wastes, I guarantee it!}
{141}{}{Mamy tylko pierwszorzêdn¹ potrawkê wyborow¹. Smakuje ona jednak wspaniale. Osiem kapsli za porcjê.}
{142}{}{Jasne. Mamy ca³e iguany na patyku po dwadzieœcia kapsli i nasz¹ pierwszorzêdn¹ potrawkê wyborow¹ z najlepszych kawa³ków po osiem kapsli.}
{143}{}{Wezmê ca³¹ iguanê.}
{144}{}{Wezmê wasz¹ potrawkê wyborow¹.}
{145}{}{Wiesz, podobno wasza potrawka wyborowa smakuje jak kurczak. Lubisz jeœæ tchórzliwych kolesiów?}
{146}{}{¯adna maminsynia kawa³ki! Ja chcieæ ca³a iguana! Ugh!}
{147}{}{Hmm, pachnieæ dobrze! Ja chcieæ pirwszorzendna!}
{148}{}{Nigdy takich nie widzia³em w okolicy. Kupcy Wodni ich nie potrzebuj¹.}
{149}{}{Kupcy Wodni?}
{150}{}{Pan Kafar to szacowny biznesmen zaanga¿owany w zdecydowanie nie szacowny biznes. Czy coœ jeszcze?}
{151}{}{Um... Okay...}
{152}{}{Jakiego rodzaju biznes?}
{153}{}{O czym ty mówisz?}
{154}{}{Chodzi mi o twoje sekretne sk³adniki. Jak œwie¿e musz¹ byæ zw³oki, ¿eby nie pozostawia³y gorzkiego posmaku? U¿ywasz mutantów, ludzi, czy mieszanki?}
{155}{}{W melinie doktorka Kostuchy by³a faktura. Faktura na cia³a...}
{156}{}{Jeœli masz k³opoty z pamiêci¹, mogê porozmawiaæ z szeryfem.}
{157}{}{Pierwszorzêdna potrawka wyborowa jest robiona z ludzi!!!! Ona jest z ludzi!!!}
{158}{}{Nic. Przykro to wyci¹gaæ. A zatem, czy mogê coœ jeszcze dla ciebie zrobiæ?}
{159}{}{Có¿, jest teraz martwy, a dziêki temu wzros³a moja p³ynnoœæ finansowa.}
{160}{}{Ktoœ zabi³ Kafara. Jesteœmy w ¿a³obie. [Chichot.]}
{161}{}{Ktoœ zastrzeli³ szeryfa Greene'a. Nie wiem jednak, co z jego zastêpc¹.}
{162}{}{Daren Wie¿owiec zosta³ zamordowany. I ca³a ta forsa nie mog³a go uratowaæ. Ironiczne, nie?}
{163}{}{Ktoœ ukrad³ naszyjnik Wie¿owcom. Rany, ale wielki b³¹d ten ktoœ pope³ni³. Jest ju¿ stuprocentowym trupem!}
{164}{}{Ktoœ zabi³ Jain. S³ysza³em, ¿e by³a z niej prawdziwa zadra w zadzie!}
{165}{}{Có¿, jedyna nowoœæ to to, ¿e Dzieci Katedry przejê³y szpital. Ostatnio jest tu ca³kiem nudno.}
{166}{}{Coœ jeszcze?}
{167}{}{Rany, w tydzieñ wylecê z interesu. Czy coœ jeszcze, o wszechmocna istoto?}
{168}{}{Nie podoba mi siê twoja postawa.}
{169}{}{Przykro mi, nie staæ ciê.}
{170}{}{Jedna ca³a iguana, nadchodzi! Czy coœ jeszcze?}
{171}{}{Wiesz z czego to jest i nadal chcesz to jeœæ? Przy tobie Kafar wygl¹da na filantropa! Czy coœ jeszcze?}
{172}{}{Nie podoba mi siê twoja postawa.}
{173}{}{Przykro mi, nie staæ ciê.}
{174}{}{One prime cut select, coming up! Anything else?}
{175}{}{Smart decision. You could stand to lose a few pounds.}
{176}{}{C-co?! Ach, rozumiem, ty ¿artujesz...}
{177}{}{Oczywiœcie...}
{178}{}{Nie, nie ¿artujê. Dopilnujê, ¿ebyœ zap³aci³ za tê zbrodniê.}
{179}{}{Nie, nie ¿artujê. I chcê dzia³kê.}
{180}{}{Musisz byæ tu pierwszy raz, skoro pytasz mnie o Kupców Wodnych. Woda to ¿ycie, a trudno jest byæ potê¿niejszym od ¿ycia i œmierci.}
{181}{}{Kto jest szefem Kupców Wodnych?}
{182}{}{Jeœli tylko istnieje coœ, co wi¹¿e siê z nieszczêœciem i cierpieniem w Hubie, Kafar albo tym kieruje, albo chce tym kierowaæ. Czy coœ jeszcze?}
{183}{}{Nie wiem, o czym ty mówisz, i nie ceniê sobie twoich oszczerstw! Lepiej nie pokazuj tu wiêcej swojej gêby.}
{184}{}{Nie rób tego! W porz¹dku, u¿ywam nieco budz¹cych w¹tpliwoœci och³apów. Ale nie jest tak, ¿e pope³niam morderstwa. Towar Kostuchy jest ju¿ martwy, nieprawda¿?}
{185}{}{Na pewno jest, Bob. Mi³ego dnia...}
{186}{}{Kanibalizm to zbrodnia przeciwko ludzkoœci, Bob. Dopilnujê, ¿ebyœ za ni¹ zap³aci³.}
{187}{}{Mo¿e jest. Mo¿e nie jest. Nie obchodzi mnie to. Chcê dzia³kê.}
{188}{}{Nie tak g³oœno! Nie musisz o tym rozpowiadaæ po ca³ym Hubie...}
{189}{}{To chyba by³o niegrzeczne z mojej strony. Mi³ego dnia...}
{190}{}{Wiesz, posterunek policji jest zaraz po drugiej stronie ulicy. Naprawdê muszê odbyæ ma³¹ przechadzkê.}
{191}{}{Potrafiê g³oœniej. Ale potrafiê siê te¿ zamkn¹æ. Ha³as jest tani, cisza jest kosztowna.}
{192}{}{Jak do cholery mam ci p³aciæ, kiedy wy¿erasz mi wszystkie zapasy? Œwietnie! Masz nastêpn¹ iguanê! Mam nadziejê, ¿e siê ni¹ ud³awisz!}
{193}{}{Nie podoba mi siê twoja postawa.}
{194}{}{Trudno. Chcesz pieniêdzy, dam ci je. Chcesz jedzenia, dam ci je. Chcesz umrzeæ, za³atwiê to. Ale "lubienie" nie wchodzi w rachubê.}
{195}{}{Nic mi nie przychodzi do g³owy. A teraz, jeœli mi wybaczysz, mam interes do prowadzenia.}
{196}{}{Przykro mi, skoñczy³y nam siê iguany.}
{197}{}{Mamy tylko ca³e iguany na patyku. Dwadzieœcia kapsli sztuka.}
{198}{}{We only have prime cut select. Eight bucks.}
{199}{}{Znowu? Rany, musisz umieraæ z g³odu. Mamy ca³e iguany na patyku po dwadzieœcia kapsli i nasz¹ pierwszorzêdn¹ potrawkê wyborow¹ z najlepszych kawa³ków po osiem kapsli.}
{200}{}{Wezmê ca³¹ iguanê.}
{201}{}{Wezmê wasz¹ potrawkê wyborow¹.}
{202}{}{Wiesz, podobno wasza potrawka wyborowa smakuje jak kurczak. Lubisz jeœæ tchórzliwych kolesiów?}
{203}{}{¯adna maminsynia kawa³ki! Ja chcieæ ca³a iguana! Ugh!}
{204}{}{Hmm, pachnieæ dobrze! Ja chcieæ pirwszorzendna!}
{205}{}{Jak do cholery mam ci p³aciæ, kiedy wy¿erasz mi wszystkie zapasy? Œwietnie! Masz nastêpn¹ iguanê! Mam nadziejê, ¿e siê ni¹ ud³awisz!}
{206}{}{Nie podoba mi siê twoja postawa.}
{207}{}{Uch, czeœæ.}
{208}{}{Czekaj no. Musimy znaleŸæ jakiœ sposób, by osi¹gn¹æ wzajemne zrozumienie!}
{209}{}{Jedyny sposób, w który mo¿esz mnie uciszyæ, to zabiæ mnie.}
{210}{}{Przykro mi, nie ubijemy interesu.}
{211}{}{Œwietnie. Co z tego bêdzie dla mnie?}
{212}{}{W porz¹dku. Ile mam ci zap³aciæ?}
{213}{}{Chcê }
{214}{}{50}
{215}{}{75}
{216}{}{100}
{217}{}{150}
{218}{}{200}
{219}{}{ caps every five days.}
{220}{}{Chyba ciê nie zaszanta¿ujê. Rób swoje.}
{221}{}{Na twoim miejscu zmieni³bym zdanie. Ludzie ginêli ju¿ w Hubie za mniej.}
{222}{}{Œwietnie. No to sztama.}
# TRANSLATION NOTE: A number of caps is inserted between lines 222 and 223. The space at the end of line 222 is intentional!
{223}{}{ kapsli, p³atnych co ka¿de piêæ dni. Pewnie zobaczymy siê za piêæ...}
{224}{}{Nie ma mo¿liwoœci, ¿ebym na to poszed³. Nie staæ mnie na wiêcej ni¿ p³acê ci teraz.}
{225}{}{Szkoda, Bob. Nie mam ochoty, by zacz¹æ œpiewaæ.}
{226}{}{W porz¹dku. Pozostaniemy przy obecnych ustaleniach... na razie.}
{227}{}{A staæ ciê na pogrzeb, Bob?}
{228}{}{W porz¹dku. Mo¿e bêdzie lepiej, jeœli nasze œcie¿ki ju¿ siê wiêcej nie skrzy¿uj¹.}
{229}{}{Mo¿esz sobie byæ s³owikiem, ale ja jestem kur¹ znosz¹c¹ z³ote jaja. Nie bêdziesz œpiewaæ, nie wtedy, gdy jestem jedyn¹ kur¹, jak¹ masz. Teraz siê wynoœ!}
{230}{}{First sensible thing I've heard you say. Now get out!}
{231}{}{Dawaj iguanê na patyku.}
{232}{}{Co mo¿esz mi powiedzieæ o hydroprocesorze?}
{233}{}{Co mo¿esz mi powiedzieæ o Kafarze?}
{234}{}{S¹dzê, ¿e musimy porozmawiaæ o doktorku Kostusze i niektórych z twoich sekretnych sk³adników.}
{235}{}{Czy wiesz coœ o tych zaginionych karawanach?}
{236}{}{Co, ja to k³opoty? Sk¹d masz takie wra¿enie?}
{237}{}{Dzieje siê w Hubie coœ ciekawego?}
{238}{}{Ja g³odowaæ! Grrrrr!}
{239}{}{Okropna sprawa. Ci biedni ludzie. Och, ci biedacy. Straciæ ¿ycie w taki upiorny sposób! Czy mogê coœ jeszcze dla ciebie zrobiæ? Mo¿e na przyk³ad ciê nakarmiæ?}
{240}{}{Czeœæ.}
{241}{}{Ja tera iœæ.}
{242}{}{I don't have that kind of money. I'm barely making ends meet as it is.}
##
##Sduibek -- Fallout Fixt
##
{243}{}{Thirty caps?! Are you kidding me?}
{244}{}{Look, you're the one who ruined my profit margins. So if you don't like my prices, fuck off. There are plenty of other iguana stands around here. Oh wait, there aren't. Asshole.}
{245}{}{Terrible, thanks to you. Nobody likes snitches. Now, if you ain't here to buy anything, get out of my face.}
{246}{}{Whatever. Bye.}
{247}{}{Actually, come to think of it, I am pretty hungry.}
#
{250}{}{ experience for blackmailing Bob into paying for your silence.}
{251}{}{How's business, Bob? *wink*}
#
# 252 to 260 take place while Bob is in jail
{252}{}{What the hell are you doing here? You shut down my business and got a big fat reward, I'm sure. So you're just here to gloat or what?}
{253}{}{Pretty much, yeah. How's business, Bob? *wink*}
{254}{}{Nah, just checking to see how you're doing.}
{255}{}{Terrible, thanks to you. Nobody likes snitches. They might let me die in here for all I know.}
{256}{}{Serves you right.}
{257}{}{I could have them kill you right now, if you prefer that over waiting.}
{258}{}{I'll ask them if we can turn you into Iguana Bits after your execution!}
{259}{}{Whatever. Fuck off.}
{260}{}{Go away.}
