{100}{}{Potê¿na eksplozja zamyka tunel!}
{101}{}{Upuszczasz materia³y wybuchowe, a one eksploduj¹!}
{102}{}{The explosion just makes the hole larger. It is impossible to close it now.}
{103}{}{Zyskujesz punkty doœwiadczenia za skuteczne u¿ycie materia³ów wybuchowych.}
