{100}{}{Zamkniête z rozkazu szeryfa Justina Greene'a.}
{101}{}{Na straganie wisi niewielkie obwieszczenie.}
{102}{}{Poszukiwany: Bob "Iguana" Frazier, martwy lub ¿ywy. Je¿eli posiadasz jakiekolwiek informacje o aktualnym miejscu jego pobytu lub o osobach odpowiedzialnych za jego ucieczkê, prosimy ciê o niezw³oczny kontakt z szeryfem.}
