{100}{}{Zaczynasz pi¹æ siê po drabince.}
{101}{}{Zeœlizgujesz siê z drabinki i runiesz w ciemnoœæ rozci¹gaj¹c¹ siê poni¿ej. L¹dujesz z hukiem, lecz nie doznajesz obra¿eñ.}
{102}{}{Zeœlizgujesz siê z drabinki i runiesz w ciemnoœæ rozci¹gaj¹c¹ siê poni¿ej. L¹dujesz z hukiem i tracisz }
{103}{}{ PW.}
{104}{}{Bêd¹c niewiele powy¿ej dolnego koñca drabinki, zeœlizgujesz siê z niej i spadasz.}
