{100}{}{To przewodnik karawany.}
{101}{}{A zatem jesteœmy na miejscu. Oto twoja zap³ata w wysokoœci }
{102}{}{ caps. (He pulls out an old, dog-eared bag and gives you the caps) You'll get another }
{103}{}{ kapsli, je¿eli wrócisz z nami do Hubu. Odpoczniemy tu trochê, ale nie odchodŸ zbyt daleko albo nasza karawana wyruszy bez ciebie.}
{104}{}{Aaa... Okay.}
{105}{}{Ile czasu zosta³o do wyjazdu karawany?}
{106}{}{Co mo¿esz mi powiedzieæ o Z³omowie?}
{107}{}{Co mo¿esz mi powiedzieæ o Gruzach?}
{108}{}{Co mo¿esz mi powiedzieæ o Bractwie Stali?}
{109}{}{Nie wiem, czy to zrozumiesz, ale wyruszamy za dwie godziny albo kiedy ju¿ bêdziesz mieæ na to ochotê.}
{110}{}{Um...}
{111}{}{Hunh?}
{112}{}{Iœæ. Dubra.}
{113}{}{Rany, zatrudniamy teraz prawdziwych g³¹bów.}
{114}{}{Zwykle wyruszamy dwie godziny po przybyciu. Nie ma tu jednak nic, czego byœmy wczeœniej nie widzieli, wiêc jeœli chcesz opuœciæ to miejsce wczeœniej, bêdziemy gotowi razem z tob¹.}
{115}{}{Chyba rozejrzê siê trochê po okolicy, zanim st¹d odejdziemy. Do zobaczenia.}
{116}{}{OK. Skierujmy siê z powrotem do Hubu. Dla mnie te¿ nie ma tu nic do ogl¹dania.}
{117}{}{Co mo¿esz mi powiedzieæ o Z³omowie?}
{118}{}{Co mo¿esz mi powiedzieæ o Gruzach?}
{119}{}{Co mo¿esz mi powiedzieæ o Bractwie Stali?}
{120}{}{No, jest ca³kiem podobne do Hubu, naprawdê. Ma sporo problemów: gangi, zbirów, z³odziei, rozumiesz... to co zwykle. Razem wzi¹wszy, to mieœcina w moim guœcie. [Œmiech.]}
{121}{}{Ile czasu zosta³o do wyjazdu karawany?}
{122}{}{Chyba rozejrzê siê trochê po okolicy, zanim st¹d odejdziemy. Do zobaczenia.}
{123}{}{Ta czêœæ Gruzów zwie siê Adytum. Gruzami zasadniczo rz¹dz¹ gangi. Trochê to niespokojna okolica, wiêc uwa¿aj tu na siebie. Adytum jest pod w³adz¹ Regulatorów. Próbuj¹ oni utrzymaæ to miejsce w kupie, w œwietle tych wszystkich wojen gangów. Co zrozumia³e, s¹ podejrzliwi wobec obcych, zatem je¿eli nie zdarzy³o ci siê jeszcze z nimi porozmawiaæ, lepiej zrób to, zanim zaczniesz w³óczyæ siê po okolicy.}
{124}{}{Pusto.}
{125}{}{Ile czasu zosta³o do wyjazdu karawany?}
{126}{}{Chyba rozejrzê siê trochê po okolicy, zanim st¹d odejdziemy. Do zobaczenia.}
{127}{}{Niewiele mogê ci o nich powiedzieæ. Cz³onkowie Bractwa zwykle trzymaj¹ ze sob¹. Mnóstwo ludzi myœli o nich Ÿle, ale z tego co wiem, s¹ dobrzy. Mo¿e to trochê fanatycy, ale porz¹dni goœcie.}
{128}{}{Ile czasu zosta³o do wyjazdu karawany?}
{129}{}{Chyba rozejrzê siê trochê po okolicy, zanim st¹d odejdziemy. Do zobaczenia.}
{130}{}{Chcesz, ¿ebyœmy ju¿ wyruszyli?}
{131}{}{Ruszy³a!}
{132}{}{Nie. Jeszcze siê porozgl¹dam.}
{133}{}{Tak. Mo¿emy ruszaæ.}
{134}{}{Ta czêœæ Gruzów zwie siê Adytum. Gruzami zasadniczo rz¹dz¹ gangi. Trochê to niespokojna okolica, wiêc uwa¿aj tu na siebie.}
{135}{}{Ile czasu zosta³o do wyjazdu karawany?}
{136}{}{Chyba rozejrzê siê trochê po okolicy, zanim st¹d odejdziemy. Do zobaczenia.}
{137}{}{OK. Uda³o ci siê. Oto twoje }
{138}{}{ kapsli. Jak chcesz wiêcej roboty, po prostu pójdŸ znowu porozmawiaæ z szefem. By³bym szczêœliwy mog¹c ponownie z tob¹ pracowaæ. Szepnê o tobie dobre s³ówko szefowi. Spoko.}
{139}{}{pA pA.}
{140}{}{Siema.}
{141}{}{Hej, jak leci?}
{142}{}{Jeœli chcesz znowu popracowaæ, idŸ sprawdziæ u szefa.}
{143}{}{Coœ z tob¹ nie gra?}
{144}{}{Jesteœ popapranym psycholem!}
{145}{}{Ani myœlê z tob¹ pracowaæ!}
{146}{}{200}
{147}{}{400}
{148}{}{600}
{149}{}{Co mo¿esz mi powiedzieæ o Nekropolis?}
{150}{}{To wredne, totalnie popaprane miejsce!}
{151}{}{Karawana wyruszy³a w drogê.}
{200}{}{Hmmmpf...}
{201}{}{Hmm... Szkoda, ¿e nie umiem czytaæ.}
{300}{}{Pilnuj swoich w³asnych spraw, dobrze?}
{400}{}{Nie p³aci mi siê za gadanie.}
{501}{}{Care to tell me why you abandoned the fucking caravan?? I can't believe it! Lucky for you, they finished without yer sorry ass! Get out! I'm not paying you anything!}
{502}{}{I can't believe it! We've lost the whole caravan! Get out! I ain't paying you anything!}
{504}{}{Go to the boss and try to come up with a credible story for why you abandoned the fucking caravan. Maybe then you'll get yer money, but I doubt it.}
{505}{}{I can't believe it! We've lost the whole caravan! I ain't paying you anything. Get out of my face.}
{600}{}{Well, here we are. I can't pay you the normal rate, since we lost some of the caravan. Gotta cover our losses y'know. Here's your payment of }
{601}{}{ caps. (He pulls out an old, dog-eared bag and gives you the caps) You'll get another }
{602}{}{If you want more work, just go talk to the boss. I'd be okay working with you again. Take it easy.}
{603}{}{ caps. (He pulls out an old dog-eared bag and gives you the caps) }
{604}{}{Okay, you made it. I can't pay you anything since we lost the whole caravan. Gotta cover our losses y'know. I wish it could be different but that's the rules.}
{605}{}{Okay, you made it. I can't pay you anything since all of the brahmin died. You cost us a lot of money, bub. No brahmin, no caravan, no money. I hope they don't let you work with us again.}
#
# Unload caravan quest - WG@RestorationProject
#
{506}{}{Any jobs for me here?}
{507}{}{Me wanna job!}
{508}{}{We need muscles to unload the caravan. I'll pay you }
{509}{}{ caps.}
{510}{}{Ug!}
{511}{}{Nop.}
{512}{}{I'm on it.}
{513}{}{I don't like this.}
{520}{}{You've spent an hour unloading the caravan.}
{521}{}{You help finish unloading the caravan and are handed }
{522}{}{ caps.}
