{100}{}{To Cindy.}
{101}{}{Ona p³acze.}
{102}{}{Witaj, }
{103}{}{. Czy uda³o ci siê ju¿ znaleŸæ hydroprocesor?}
{104}{}{Jeszcze nie. Nie dopisywa³o mi szczêœcie.}
{105}{}{Na razie mi siê nie powiod³o, ale na pewno go zdobêdê. Przy okazji, jak ci leci?}
{106}{}{Urug!}
{107}{}{Och... nie rozumiesz mnie. Chyba rzeczywiœcie nie ma dla nas zbyt wiele nadziei. Zostaw mnie, bo muszê teraz pop³akaæ.}
{108}{}{Ugg!}
{109}{}{Proszê, znajdŸ go, zanim pomrzemy z pragnienia.}
{110}{}{Musisz go zdobyæ! Nie pozwól nam przez niego umrzeæ!}
{111}{}{Próbuj dalej. Wierzê w ciebie. Wiem, ¿e zrobisz wszystko, co mo¿liwe, by nas uratowaæ.}
{112}{}{Kto, twoim zdaniem, mo¿e byæ w to zaanga¿owany?}
{113}{}{Bojê siê tego, co siê dzieje. Ktoœ podkrada wodê, wiêc wszyscy s¹ teraz na krawêdzi wybuchu.}
{114}{}{Kto by³by w stanie zrobiæ coœ takiego?}
{115}{}{Co siê sta³o?}
{116}{}{Paru ludzi zosta³o oskar¿onych, i wybuch³y z tego powodu bójki, ale tak naprawdê, to nikt nie wie.}
{117}{}{OK. Dziêki.}
{118}{}{Paru ludzi zg³osi³o, ¿e ich woda zosta³a skradziona. Nie dano im wiêcej wody, ale ich przyjaciele siê z nimi podzielili. Po tym wszyscy zaczêli siê zachowywaæ jak paranoicy i pilnowaæ swojej wody. Parê dni póŸniej ktoœ og³uszy³ stra¿nika przed pomieszczeniem zaopatrzeniowym i ukrad³ wodê.}
{119}{}{To okropne! Co mogê w tej sprawie zrobiæ?}
{120}{}{Mo¿e bêdziesz w stanie powstrzymaæ tego, kto to robi.}
{121}{}{Rozejrzê siê.}
{122}{}{To ty kradniesz wodê?! Jak mo¿esz?}
{123}{}{Bardzo ci dziêkujê za ocalenie nas wszystkich.}
{124}{}{Dobrze, ¿e uda³o ci siê z³apaæ z³odzieja. Proszê, pospiesz siê i zdob¹dŸ ten hydroprocesor.}
{125}{}{Jak mo¿esz siê od nas odwracaæ? Teraz wszyscy tu umr¹! Ale ciebie to nie obchodzi, prawda?}
{126}{}{Jestem przera¿ona. Nie wiem, co siê z nami wszystkimi stanie. Proszê, nie zawiedŸ nas.}
{127}{}{Nie martw siê, zrobiê wszystko, co w mojej mocy. Nic wam siê nie stanie.}
{128}{}{Ta, jak sobie chcesz.}
