{100}{}{To bardzo zniszczone biurko z zakurzonym, roztrzaskanym komputerem posadowionym w przypadkowej pozycji na blacie.}
{101}{}{Ten komputer jest ciê¿ko uszkodzony i niemo¿liwy do naprawy.}
{102}{}{Wiele obwodów usma¿y³ impuls elektromagnetyczny.}
{103}{}{Nie dzia³a.}
{104}{}{Rozcinasz d³onie o obudowê.}
