{100}{}{Ten komputer nadzoruje urz¹dzenia utrzymuj¹ce Kryptê przy ¿yciu.}
{101}{}{Wiêkszoœæ twoich uprawnieñ do korzystania z systemu komputerowego zosta³a ci odebrana na polecenie sztucznej inteligencji Krypty.}
{102}{}{To centralny komputer Krypty 13. Jemu podlega wiêkszoœæ stacji roboczych, znajduj¹cych siê na jej obszarze.}
{103}{}{Majstrujesz przy komputerze, ale tak naprawdê niczego siê nie dowiadujesz.}
{104}{}{Jest tu mnóstwo migaj¹cych œwiate³ek.}
