{100}{}{To przewodnik karawany.}
{101}{}{Niestety, ja ciê nie znam. Je¿eli szukasz pracy, to musisz porozmawiaæ z Rutgerem.}
{102}{}{O pracy nie gadaj ze mn¹, tylko z Rutgerem.}
{103}{}{Co, ca³a twoja forsa posz³a na æpanie? Jak tak dalej pójdzie, twoimi nowymi s¹siadami bêd¹ ³achy na Starym Mieœcie.}
{104}{}{Lepiej wytrzeŸwiej. Wróæ, jak bêdziesz w stanie pracowaæ.}
{105}{}{Szukasz kolejnego zlecenia?}
{106}{}{Pewnie.}
{107}{}{Nie, mo¿e póŸniej.}
{108}{}{Lug.}
{109}{}{Rok!}
{110}{}{Wszyscy gotowi do drogi? Dzisiaj wyruszamy.}
{111}{}{Ta!}
{112}{}{Ni.}
{113}{}{Hrurra?}
{114}{}{Niestety, ale z tob¹ siê ju¿ nie zadajemy. Spróbuj szczêœcia z inn¹ karawan¹; mo¿e oni z tob¹ wytrzymaj¹.}
{115}{}{Niestety, teraz nikogo nie zatrudniamy.}
{116}{}{Masz nerwy jak postronki, skoro znowu pokazujesz tu swoj¹ mordê. Lepiej st¹d odejdŸ.}
{117}{}{Spadaj, mówiê!}
{118}{}{Czego chcesz? Wynajêcie ciebie by³o prawdziw¹ katastrof¹.}
{119}{}{Proszê, daj mi jeszcze jedn¹ szansê! To nie by³a moja wina!}
{120}{}{O, doprawdy? Guzik mnie to obchodzi.}
{121}{}{Nic. Czeœæ.}
{122}{}{Kaa.}
{123}{}{Muu.}
{124}{}{S³uchaj, nie wiem, co siê tam sta³o, ale straciliœmy ca³¹ karawanê! Trzeba by³o nie wracaæ, jak siê jej nie potrafi³o ochroniæ.}
{125}{}{Mowy nie ma, sp³ywaj!}
{126}{}{Sp³ywaj, mówiê!}
{127}{}{Czego chcesz?}
{128}{}{A, zamknij siê i zejdŸ mi z drogi!}
{129}{}{Chcê znowu popracowaæ.}
{130}{}{Nic.}
{131}{}{Zug.}
{132}{}{Ug.}
{133}{}{Co? Po porzuceniu tej ostatniej roboty? Masz szczêœcie, ¿e oni prze¿yli.}
{134}{}{Ja mam szczêœcie? Ty masz szczêœcie, ¿e nie kasujê ci gêby!}
{135}{}{Hej! Akurat trzeba by³o odwiedziæ parê miejsc i spotkaæ parê osób.}
{136}{}{Nie by³o wtedy mowy, ¿e nie mogê odejœæ. Wszystko wydawa³o siê byæ w porz¹dku.}
{137}{}{Mów jasno, albo siê wynoœ.}
{138}{}{Ty ³achu.}
{139}{}{Nie zatrudniamy pijaków.}
{140}{}{Nie zatrudniamy æpunów.}
{141}{}{(The caravan driver is ignoring you.)}
{142}{}{Wróæ, jak to odeœpisz.}
{143}{}{Ty zboczku. Wracaj do zagrody.}
{144}{}{Wydawa³o siê byæ w porz¹dku? Nigdy nie porzuca siê karawany, nawet gdy jest tylko o milê od celu. Wynajêto ciê, ¿eby strzec j¹ na ca³ej trasie podró¿y, w przeciwnym razie wybralibyœmy kogoœ innego.}
{145}{}{Có¿, mnie nikt nie powiedzia³, ¿e nie mogê odejœæ!}
{146}{}{Przepraszam, to siê ju¿ nigdy nie powtórzy.}
{147}{}{Wal siê.}
{148}{}{Co? To twoja pierwsza karawana? Jak to siê sta³o, ¿e ciê zatrudniono? To bardzo odpowiedzialna i wa¿na praca; nale¿y j¹ traktowaæ serio. Stawk¹ jest ¿ycie, tak cz³onków karawany, jak i mieszkañców osad, które zaopatrujemy.}
{149}{}{Na pewno przepe³nia ciê z tego powodu duma.}
{150}{}{Co? Chcesz dostaæ jakiœ medal, albo coœ w tym stylu?}
{151}{}{Pozwól mi ratowaæ ¿ywoty, proszê! Chcê pomóc!}
{152}{}{Mam tak¹ nadziejê! To bardzo odpowiedzialna i wa¿na praca; nale¿y j¹ traktowaæ serio. Stawk¹ jest ¿ycie! Karawany i osady, które zaopatrujemy, zale¿¹ od nas!}
{153}{}{Na pewno przepe³nia ciê z tego powodu duma.}
{154}{}{Co? Chcesz dostaæ jakiœ medal, albo coœ w tym stylu?}
{155}{}{Pozwól mi ratowaæ ¿ywoty, proszê! Chcê pomóc!}
{156}{}{Ale¿ oczywiœcie.}
{157}{}{No, to mogê dostaæ kolejn¹ robotê?}
{158}{}{Mato³ z ciebie!}
{159}{}{Muszê ju¿ iœæ. Bywaj.}
{160}{}{O, tak. To ciê¿ka i brudna praca! Ryzykujemy naszym ¿yciem dla mieszkañców osad, którym siê mniej szczêœci.}
{161}{}{Wyluzuj siê! }
{162}{}{Tak? A co z mniej szczêœliwymi ludŸmi pod twoim nosem?}
{163}{}{Masz racjê. Dostanê kolejn¹ robotê, czy nie?}
{164}{}{Co? Nie wiem, o czym mówisz! A, masz na myœli ³achów? Oni siê nie licz¹. Sami postanowili ¿yæ w ten sposób.}
{165}{}{Chyba masz racjê.}
{166}{}{Sprawiasz, ¿e robi mi siê niedobrze.}
{167}{}{Muszê ju¿ iœæ.}
{168}{}{Co? O co ci chodzi?}
{169}{}{Oczywiœcie, ¿e tak. W g³êbi duszy jestem dobr¹ osob¹... zwykle.}
{170}{}{Oczywiœcie, ¿e tak. Dostanê kolejn¹ robotê, czy nie?}
{171}{}{Znikam st¹d.}
{172}{}{To siê nazywa w³aœciwa postawa! Szkoda, ¿e nie mogê daæ ci kolejnego zlecenia.}
{173}{}{After all that? Oh come on, can I please can I have another job?}
{174}{}{Có¿, no to wracam do ratowania œwiata.}
{175}{}{Bardzo dobrze. Ale nie spodziewaj siê, ¿e jeszcze ciê kiedyœ zatrudnimy!}
{176}{}{Och, proszê! To siê ju¿ wiêcej nie powtórzy!}
{177}{}{Jakby mi na tym zale¿a³o!}
{178}{}{No, OK, dam ci jeszcze jedn¹ szansê. Nasza nastêpna karawana wyrusza }
{179}{}{dzisiaj}
{180}{}{jutro}
{181}{}{on the}
{182}{}{ósmego}
{183}{}{osiemnastego}
{184}{}{dwudziestego ósmego}
{185}{}{. Daj mi znaæ, jak siê przygotujesz do wymarszu. Zap³ata to standardowe 400 kapsli.}
{186}{}{Niestety, ale powa¿nym b³êdem by³o danie ci szansy poprzednim razem.}
{187}{}{Œwietnie, któr¹ trasê wybierasz?}
{188}{}{Siemanko. Karawana wyruszy dopiero jutro. Wróæ wtedy, je¿eli nadal chcesz tê robotê.}
{189}{}{Jednak nie chcê.}
{190}{}{Postaram siê wyrobiæ.}
{191}{}{OK, to do zobaczenia.}
{192}{}{Da.}
{193}{}{Siemanko. Jesteœ tu za wczeœnie. O wiele za wczeœnie. Nastêpna karawana wyrusza dopiero }
{194}{}{ósmego}
{195}{}{osiemnastego}
{196}{}{dwudziestego ósmego}
{197}{}{. Wróæ wtedy, je¿eli nadal ciê to interesuje.}
{198}{}{Rezygnujê z tej roboty.}
{199}{}{Postaram siê wyrobiæ.}
{200}{}{OK. Czeœæ.}
{201}{}{Da.}
{202}{}{OK. Nie gra to dla mnie roli.}
{203}{}{Cholera, dla mnie nie gra roli, czy siê zjawisz, czy nie. Codziennie zg³aszaj¹ siê do nas ludzie szukaj¹cy pracy. Je¿eli nie przyjdziesz, to w porz¹dku.}
{204}{}{Ju¿ by³a o tym mowa. Nie przejmuj siê tym. Jak siê nie wyrobisz, to sobie te¿ poradzê.}
{205}{}{Do Cytadeli Bractwa Stali.}
{206}{}{L.A. Boneyard.}
{207}{}{Do Z³omowa.}
{208}{}{Mimo wszystko nie chcê tej roboty.}
{209}{}{Wspania³e wyczucie czasu, nasze karawany wyruszaj¹ dzisiaj. Zap³ata to standardowe 400 kapsli. Któr¹ trasê wybierasz?}
{210}{}{Œwietnie. Nasza nastêpna karawana wyrusza }
{211}{}{ósmego}
{212}{}{osiemnastego}
{213}{}{dwudziestego ósmego}
{214}{}{. Wróæ wtedy, to ciê przydzielimy. Zap³ata to standardowe 400 kapsli.}
{215}{}{OK.}
{216}{}{Niestety, nie mogê tak d³ugo czekaæ.}
{217}{}{Œwietnie. Sprowadzê twojego przewodnika i resztê za³ogi. Uwa¿aj na Pustkowiu, ostatnio jest niezbyt bezpiecznie.}
{218}{}{Za³oga jest gotowa. Wyruszamy od razu.}
{219}{}{W porz¹dku, zebranie za³ogi do kupy potrwa tylko parê minut.}
{220}{}{W porz¹dku. Wyruszymy do Bractwa, jak tylko zbiorê do kupy resztê za³ogi.}
{221}{}{OK, wyruszysz do Bractwa, jak tylko zgromadzê za³ogê.}
{222}{}{Gotowi do drogi! Tylko trzymajcie siê z dala od gór.}
{223}{}{Gruzy to niebezpieczne miejsce - zachowaj tam ostro¿noœæ. Dopilnuj, ¿eby wszyscy wyrabiali swoje zmiany.}
{224}{}{Za³oga jest ju¿ prawie gotowa. Podobno ostatnio w okolicy Gruzów by³y jakieœ k³opoty, wiêc zachowaj czujnoœæ.}
{225}{}{OK, za³oga karawany do Gruzów jest w komplecie i gotowa do drogi.}
{226}{}{Podró¿ do Z³omowa jest z regu³y krótka i ³atwa - nie powinno byæ ¿adnych problemów.}
{227}{}{Dobrze, za³oga karawany do Z³omowa jest gotowa.}
{228}{}{W porz¹dku. Z³omowo czeka, zbierajmy siê.}
{229}{}{O, witaj. Rozumiem, ¿e szukasz pracy. Dziwi mnie, ¿e Rutger ciê wynaj¹³, ale na pewno mia³ jakieœ powody. Nasze karawany wyruszaj¹ st¹d trzy razy w miesi¹cu: ósmego, osiemnastego i dwudziestego ósmego. Regularnie chodzimy do trzech miejsc: Cytadeli Bractwa Stali, Z³omowa i Gruzów. Zap³ata to zawsze 400 kapsli w jedn¹ stronê. Mo¿esz wróciæ z karawan¹ i zarobiæ kolejne 400 kapsli.}
{230}{}{Masz wspania³e wyczucie czasu, bo wszystkie karawany wyruszaj¹ dzisiaj.}
{231}{}{Wszystkie karawany wyruszaj¹ jutro.}
{232}{}{Karawany wyruszaj¹ dopiero za }
{233}{}{ dni.}
{234}{}{Interesuje ciê to?}
{235}{}{No, to chcesz tê robotê?}
{236}{}{Wszystkie karawany wyruszaj¹ dzisiaj.}
{237}{}{Wszystkie karawany wyruszaj¹ jutro.}
{238}{}{Karawany wyruszaj¹ dopiero za }
{239}{}{ dni.}
{240}{}{Przypuszczam, ¿e szukasz pracy. Mogê ci j¹ daæ. Interesuje ciê to?}
{241}{}{Pewnie.}
{242}{}{Nie.}
{243}{}{Wiesz, gdzie mo¿esz sobie wsadziæ twoj¹ karawanê.}
{244}{}{Jeszcze nie wiem. Powiem ci póŸniej.}
{245}{}{Ug.}
{246}{}{Któr¹ trasê chcesz odbyæ?}
{247}{}{Do Cytadeli Bractwa Stali.}
{248}{}{L.A. Boneyard.}
{249}{}{Do Z³omowa.}
{250}{}{Przepraszam, odwidzia³o mi siê.}
{251}{}{Có¿, wróæ }
{252}{}{ósmego}
{253}{}{osiemnastego}
{254}{}{dwudziestego ósmego}
{255}{}{, to zbierzemy za³ogê.}
{256}{}{Co z tob¹, masz jakiœ problem?}
{257}{}{Ty jesteœ problemem, a moja piêœæ jest rozwi¹zaniem.}
{258}{}{Lepiej uwa¿aj.}
{260}{}{Tak, ciebie.}
{261}{}{To ¿aden problem.}
{262}{}{Ta, OK. Wróæ, jak zmienisz zdanie.}
