{100}{}{To ¿ona Dana.}
{101}{}{Nie powinnam z nikim rozmawiaæ. IdŸ do mojego mê¿a.}
{102}{}{Przykro mi, musisz porozmawiaæ z moim mê¿em.}
{103}{}{Ty straszny cz³owieku, czemu ¿eœ to zrobi³?! Zabi³eœ mojego Danny'ego!}
{104}{}{Ty straszna kobieto, czemu to zrobi³aœ?! Zabi³aœ mojego Danny'ego!}
{105}{}{To ¿ona Dana; obecnie p³acze.}
