{100}{}{To jeden z goryli Kafara.}
{101}{}{Musisz pogadaæ z szefem.}
{102}{}{Lepiej nie w³aŸ nam na odcisk.}
{103}{}{Bêdziemy ciê mieæ na oku.}
{104}{}{Nawet nie dotykaj swojej broni.}
{105}{}{Jak na niego spojrzysz krzywo, bêdziesz trupem.}
{106}{}{Uwa¿aj.}
{107}{}{Poddajê siê!}
{108}{}{Praca dla tego Kafara i tak nigdy mi siê nie podoba³a.}
{109}{}{Skoro nie ma ju¿ Kafara i Kane'a, ja zostanê szefem!}
{110}{}{Od teraz lepiej uwa¿aj na siebie w Hubie. Mam ciê na oku.}
