{100}{}{To Demetre.}
{101}{}{Siemanko! Jak leci? Jestem Demetre, Demetre Romara, szef najlepszej, cholernej karawany na Pustkowiu. Szukasz roboty?}
{102}{}{Hmmm, zupe³nie nie wygl¹dasz na si³acza, ale... NA PEWNO œwietnie pos³ugujesz siê spluwami, skoro uda³o ci siê prze¿yæ poza miastem! Do diab³a, gdy trzeba, jesteœ pewnie wrednym fajterem!}
{103}{}{Wygl¹dasz ca³kiem do rzeczy.}
{104}{}{Na oko masz ca³kiem niez³¹ krzepê.}
{105}{}{Cholera, wygl¹dasz na prawdziwego si³acza!}
{106}{}{Ja pierdzielê! Chyba jesteœ w stanie podnieœæ ca³¹ górê!}
{107}{}{Ta, i co z tego?}
{108}{}{Co ci do tego?}
{109}{}{Hê?}
{110}{}{W³aœnie tego szukamy! Lubisz dreszczyk bitwy, nieprawda¿?! Fruwaj¹ce wszêdzie pociski, œmigaj¹ce ko³o ucha, rozwalanie przeciwników na dwoje, obserwowanie strachu w ich oczach! Aaaach, to jest ¿ycie! Wygl¹dasz na osobê, która mo¿e nam dobrze s³u¿yæ, a my dobrze p³acimy! O tak, naprawdê dobrze! Akurat mamy kilka wolnych etatów, jeœli ciê to interesuje; ale tak oczywiœcie jest, zgadza siê?!}
{111}{}{Jaka jest zap³ata?}
{112}{}{Zabijê wszystko, co wejdzie nam w drogê!}
{113}{}{Nie, dziêki.}
{114}{}{Potrzebny mi hydroprocesor.}
{115}{}{Co wiesz o zaginionych karawanach?}
{116}{}{Muszê ju¿ iœæ.}
{117}{}{Ugggg uggg!}
{118}{}{P³acimy 600 kapsli za trasê! W ka¿d¹ stronê! Do diab³a, ludzie gadaj¹, ¿e wybieramy same niebezpieczne szlaki, ale ja twierdzê, ¿e to one s¹ najbardziej ekscytuj¹ce! W ¿yciu trzeba mieæ trochê ekscytacji, mam racjê?! Oczywiœcie, ¿e tak!}
{119}{}{Do diab³a, chyba w³aœnie tego szukam!}
{120}{}{Czy zawsze mówisz tak g³oœno?}
{121}{}{Niebezpieczne?}
{122}{}{Nie dziêki, z³otko.}
{123}{}{A jak¿e! IdŸ pogadaæ z Keri w pokoju obok, ona ci powie, kiedy wyrusza nastêpna karawana.}
{124}{}{Z³otko? O czym ty, u diab³a, mówisz? Có¿, mam to gdzieœ.}
{125}{}{Co, boisz siê g³oœnych dŸwiêków, czy co?}
{126}{}{Tak.}
{127}{}{Tylko w nocy.}
{128}{}{Nie, zastanawiam siê tylko, czy jesteœ g³uchy, czy g³upi.}
{129}{}{Nie, ale zaczynaj¹ mnie trochê boleæ uszy.}
{130}{}{Ha! Mo¿e i taki, i taki! Có¿, jeœli faktycznie chcesz robotê, idŸ pogadaæ z Keri w pokoju obok.}
{131}{}{Bezczelna z ciebie menda, co? Có¿, mi to nie przeszkadza! Póki bêdziesz broniæ karawan, bêdê zadowolony. Jeœli chcesz robotê, idŸ pogadaæ z Keri w pokoju obok.}
{132}{}{Ha! Zabawne! Có¿, jeœli uznasz, ¿e jesteœ w stanie zmierzyæ siê z ciemnoœci¹, wpadnij do mnie.}
{133}{}{Oczywiœcie, ¿e to niebezpieczne - czemu inaczej buli³bym 600 kapsli?}
{134}{}{A, OK. Czeœæ.}
{135}{}{I tak wezmê tê robotê.}
{136}{}{Wynoœ siê st¹d, zanim oder¿nê ci ³eb!}
{137}{}{Wepchnê ci twój ³eb do dupy!}
{138}{}{Miarka siê przebra³a!}
{139}{}{Oczywiœcie, ¿e tak! IdŸ pogadaæ z Keri w pokoju obok, ona opracowuje harmonogramy.}
{140}{}{Do diab³a, to przykre, ale có¿, trudno.}
{141}{}{Ta! Polubi³em ciê! Dostajesz robotê! IdŸ pogadaæ z Keri w pokoju obok, ona ciê przydzieli do karawany.}
{142}{}{Hydroprocesor? Hmmm, nigdy wczeœniej o czymœ takim nie s³ysza³em. Mo¿esz popróbowaæ w miejscowych sklepach - maj¹ masê rzeczy. No, to chcesz robotê?}
{143}{}{Có¿, jaka jest zap³ata?}
{144}{}{Nie, niezbyt.}
{145}{}{Niewiele, ja straci³em tylko dwie. Naprawdê nie mam pojêcia, czemu Wszêdobylscy Handlowcy obrywaj¹ bardziej ni¿ wszyscy inni.}
{146}{}{Masz jakieœ podejrzenia?}
{147}{}{Mo¿e chodzi o trasy lub ³adunek?}
{148}{}{OK, dziêki.}
{149}{}{Ktokolwiek to robi, musi mieæ zajebist¹ ekipê. Karawany s¹ dobrze uzbrojone, i mo¿na by pomyœleæ, ¿e do tej pory ktoœ z naszych ju¿ powinien ujœæ z ¿yciem. Tymczasem oni nie zostawiaj¹ ¿adnych œladów.}
{150}{}{No, a jaka jest zap³ata za tê pracê?}
{151}{}{Mo¿e chodzi o trasy lub ³adunek?}
{152}{}{OK, dziêki.}
{153}{}{Do diab³a, chodzimy do bardziej niebezpiecznych miejsc ni¿ oni, a nasz towar jest lepszy!}
{154}{}{W czym wasz towar jest lepszy?}
{155}{}{Tylko sprawdzam, dziêki.}
{156}{}{Gówno wy³azi ci uszami!}
{157}{}{Có¿, w porz¹dku - mo¿e nie jest lepszy, ale faktycznie mamy od nich szerszy asortyment.}
{158}{}{OK, dziêki.}
{159}{}{Wiesz, Beth ci¹gle paple o jakimœ Szponie Œmierci. Na twoim miejscu bym to sprawdzi³! Z innych Ÿróde³ s³ysza³em parê plotek o czymœ skradaj¹cym siê po nocy na pó³nocny zachód st¹d.}
{160}{}{Wybacz, ale p³acimy kupê pieniêdzy, ¿eby mieæ pewnoœæ, ¿e robota zostanie wykonana! Zatrudniamy tylko najlepszych! Musimy mieæ w tych karawanach niezawodne osoby obu równoprawnych p³ci!}
{161}{}{Jakby mi rzeczywiœcie zale¿a³o na robocie, ty wielkogêby debilu!}
{162}{}{Przepraszam, ¿e zawracam ci g³owê.}
{163}{}{Proszê, daj mi jeszcze jedn¹ szansê.}
{164}{}{Huda?}
{165}{}{Powiedzia³em ju¿, ¿e ciê nie wynajmiemy!}
{166}{}{Niestety, mam doœæ ryzykowania przez ciebie!}
{167}{}{Marnujesz tu czas!}
{168}{}{Proszê, przestañ zawracaæ mi g³owê!}
{169}{}{Spadaj.}
{170}{}{Demetre ciê ignoruje.}
{171}{}{Do cholery, nie zatrudniam narkomanów! Jak szukasz roboty, to lepiej wytrzeŸwiej!}
{172}{}{Ja nie jestem narko... to jest... ach!}
{173}{}{Chrzanisz!}
{174}{}{Æpamy sobie, no nie? Do diab³a, to dobrze, ¿e ju¿ wiêcej nie wynajmiemy twojej dupy!}
{175}{}{Do diab³a, nie! Chyba nie zdajesz sobie sprawy, jak wielka jest stawka! Nie mo¿emy sobie pozwoliæ na ryzyko! Do diab³a, przy tych wszystkich zaginionych karawanach nie wiem, jakim cudem Wszêdobylscy Handlowcy jeszcze s¹ w interesie!}
{176}{}{Wybacz, ale musisz sprawdziæ, czy któraœ z innych kompanii zaryzykuje ciê zatrudniæ. Ja nie mogê sobie na to znowu pozwoliæ.}
{177}{}{Wynoœ siê st¹d, robi mi siê niedobrze na twój widok!}
{178}{}{Ej! Co ty niby wyprawiasz?}
{179}{}{Têdy idzie siê do naszego magazynu.}
{180}{}{Mo¿na to otworzyæ tylko z drugiej strony.}
{181}{}{Dziwna z ciebie osóbka.}
{182}{}{Marnujesz tu czas.}
{183}{}{Demetre ciê ignoruje.}
{184}{}{No? To chcesz robotê, czy nie? Oferujê ci wielk¹ szansê na ekscytuj¹c¹ przygodê i mnóstwo gotówki! ¯adnej z tych rzeczy nie da siê mieæ w nadmiarze!}
{185}{}{A, tak. To mówi³eœ, ¿e ile?}
{186}{}{Zabijê wszystko, co wejdzie nam w drogê!}
{187}{}{Nie, dziêki.}
{188}{}{Potrzebny mi hydroprocesor.}
{189}{}{Co wiesz o zaginionych karawanach?}
{190}{}{Muszê ju¿ iœæ.}
{191}{}{Bak pyk?}
{192}{}{Hej, to by³a œwietna robota na tej ostatniej karawanie - œwietnie ci idzie! Trzeba ci czegoœ?}
{193}{}{Ta, potrzebujê kolejnego zlecenia.}
{194}{}{Potrzebny mi hydroprocesor.}
{195}{}{Co wiesz o zaginionych karawanach?}
{196}{}{Nie. Wpadam tylko siê przywitaæ.}
{197}{}{Nie, czeœæ.}
{198}{}{Straciliœmy ca³y nasz towar! Obawiam siê, ¿e ju¿ wiêcej nie mo¿emy ciê wynaj¹æ, wybacz.}
{199}{}{Masz szczêœcie, o ma³y w³os byœmy stracili tê olan¹ przez ciebie karawanê! Obawiam siê, ¿e nie mo¿emy zaoferowaæ ci ju¿ ¿adnej roboty, wybacz.}
{200}{}{Nikogo nie zatrudniamy, wiêc czego chcesz?}
{201}{}{Sp³ywaj! Nikogo nie zatrudniamy.}
{202}{}{Potrzebny mi hydroprocesor.}
{203}{}{Powiedz mi, co wiesz o zaginionych karawanach.}
{204}{}{Chcê, ¿eby twoja brzydka gêba zesz³a mi z drogi!}
{205}{}{Chcê nabiæ twój ³eb na pal!}
{206}{}{Niewa¿ne.}
{207}{}{Bak pyk?}
{208}{}{Masz siê za tward¹ sztukê? Nie rozœmieszaj mnie!}
{209}{}{Có¿, porozmawiaj lepiej z moj¹ córk¹, Keri; ona siê tym wszystkim zajmuje! Jest w pokoju obok.}
{210}{}{Ju¿ ci mówi³em. Zwyczajnie pogadaj z Keri w pokoju obok.}
{211}{}{Twoj¹ córk¹?}
{212}{}{To paskudztwo jest twoj¹ córk¹? To wiele t³umaczy!}
{213}{}{OK.}
{214}{}{Tak, jest moim powodem do dumy i radoœci! Czy¿ nie jest piêkna? Gdy bêdziesz znowu potrzebowaæ roboty, po prostu z ni¹ pogadaj. Któregoœ dnia... mam nadziejê, ¿e nieodleg³ego, bêdê móg³ przejœæ na emeryturê, a ona przejmie moje miejsce.}
{215}{}{Nie bêdziesz móg³, jak oboje umrzecie!}
{216}{}{OK, dziêki.}
{217}{}{Œmiesz obra¿aæ czyj¹œ rodzinê? Powinienem wyrwaæ ci serce!}
{218}{}{Przepraszam, to by³ tylko ¿art!}
{219}{}{Czeka ciê wiêcej, ni¿ tylko obraza!}
{220}{}{Za póŸno na przepraszanie! [Jego twarz p¹sowieje... potem mówi spokojnym, opanowanym g³osem.] Won, zanim urzeczywistniê moj¹ groŸbê!}
{221}{}{Czy to ma byæ twoja ¿a³osna namiastka groŸby?}
{222}{}{To nie groŸba! Zaraz umrzesz!}
{223}{}{Ta, có¿, to by³ stary dowcip studencki!}
{224}{}{Nie, przepraszam. Muszê ju¿ iœæ. Czeœæ!}
{225}{}{Có¿, muszê przyznaæ, ¿e s³ysza³em lepsze.}
{226}{}{Ta, wiem. Bywaj.}
{227}{}{Có¿, i tak umrzesz!}
{228}{}{A, OK.}
{229}{}{No, na co czekasz? S¹ karawany, z którymi trzeba wyruszyæ!}
{230}{}{Jeszcze nie s¹ gotowe do drogi.}
{231}{}{Mam jeszcze przedtem parê rzeczy do zrobienia.}
{232}{}{Potrzebny mi hydroprocesor.}
{233}{}{Powiedz mi, co wiesz o zaginionych karawanach.}
{234}{}{OK, czeœæ.}
{235}{}{Bik ruk?}
{236}{}{Bruwru?}
{237}{}{Cholera! Przegapiasz sporo dobrej akcji! Na pewno masa ludzi, stworzeñ i rzeczy tylko czeka, ¿eby zaatakowaæ karawany! Nic nie przebije niez³ej strzelaniny! Masz - pobaw siê tym, dopóki nie wyszykuje siê nastêpna karawana. [Wrêcza ci granat od³amkowy.]}
{238}{}{Cholera! Czy nasze karawany kiedykolwiek wyruszaj¹?}
{239}{}{Co z twoim okresem?}
{240}{}{Niech ci to za d³ugo nie zajmie.}
{241}{}{Keri, zamknê³aœ ju¿ listê?}
{242}{}{Wroga trzeba zabiæ, zanim ciê dorwie!}
{243}{}{Nie ma to jak wyciskanie ¿ycia z wrogów!}
{244}{}{A takiego wa³a!}
{245}{}{Cholera, gdzie moja spluwa?!}
