{100}{}{Uda³o ci siê otworzyæ lodówkê.}
{101}{}{Masz k³opoty z zamkiem.}
{102}{}{To lodówka. Jest zamkniêta na klucz.}
{103}{}{To lodówka. Jest zamkniêta.}
{104}{}{To lodówka. Jest otwarta.}
{105}{}{Drzwi s¹ zamkniête.}
{106}{}{That does nothing.}
{107}{}{It is already unlocked.}
{108}{}{You see a refridgerator.}
