{100}{}{You see: Snake, a member of the Blades.}
{101}{}{You see: Dolgan, a member of the Blades.}
{102}{}{}
{103}{}{}
{104}{}{To Ostrze.}
{105}{}{To Ostrze.}
{106}{}{Myœlisz, ¿e to mo¿e byæ Kujon.}
{107}{}{Myœlisz, ¿e to mo¿e byæ Blizna.}
{108}{}{Myœlisz, ¿e to mo¿e byæ Strzelec.}
{109}{}{Myœlisz, ¿e to mo¿e byæ Nerwus.}
{110}{}{Myœlisz, ¿e to mo¿e byæ M³ot.}
{111}{}{Myœlisz, ¿e to mo¿e byæ Brzytwa.}
{112}{}{Get lost! This is for real fighters only.}
{113}{}{So, you think you can take on the Regulator wimps? Here, I'll teach you how to use that blade.}
{114}{}{You seem to have gotten better. Now go kick Caleb's butt into next year for me.}
{115}{}{Posiekanie tych Rozpruwaczy by³o œwietne. Co mogê dla ciebie zrobiæ?}
{116}{}{Mo¿esz mnie jeszcze podszkoliæ w walce ostrzami?}
{117}{}{How can I get through to the Gun Runners?}
{118}{}{Nic, dziêki.}
{119}{}{Jasna rzecz. Ale to zajmie wiêkszoœæ dnia i da s³abe efekty. Nadal tego chcesz?}
{120}{}{Tak.}
{121}{}{Nie.}
{122}{}{Proszê bardzo. Wykazujesz pewn¹ poprawê. ¯yczê ci powodzenia.}
{123}{}{Jasna rzecz. Wróæ, jak bêdziesz mieæ ochotê na trening.}
{124}{}{Zdaje siê, ¿e przyjêliœmy g³upka. Có¿, jak siê chcesz dostaæ do ich siedziby, to przez w ich fosie jest niewielkie przewê¿enie. Poszukaj go i gnaj jak wariat. Mo¿e nawet uda ci siê przedostaæ.}
{125}{}{Dziêki.}
