{100}{}{You see: Dragon, a member of the Blades.}
{101}{}{}
{102}{}{}
{103}{}{To Ostrze.}
{104}{}{To Ostrze.}
{105}{}{Myœlisz, ¿e to mo¿e byæ Kujon.}
{106}{}{Myœlisz, ¿e to mo¿e byæ Blizna.}
{107}{}{Myœlisz, ¿e to mo¿e byæ Strzelec.}
{108}{}{Myœlisz, ¿e to mo¿e byæ Nerwus.}
{109}{}{Myœlisz, ¿e to mo¿e byæ M³ot.}
{110}{}{Myœlisz, ¿e to mo¿e byæ Brzytwa.}
{111}{}{Sp³ywaj! Nie widzisz, ¿e próbujê trochê odpocz¹æ?!}
{112}{}{Po co siê tu pêtasz?}
{113}{}{Tylko patrzê na gwiazdy.}
{114}{}{Próbujê ciê wypatrzyæ.}
{115}{}{Polujê.}
{116}{}{Patrzenie bêdzie ciê drogo kosztowaæ. O co chodzi? Mów prawdê, to mo¿e prze¿yjesz.}
{117}{}{Tak naprawdê, jestem tu, ¿eby ciê zabiæ.}
{118}{}{Chcê zakoñczyæ wojny gangów.}
{119}{}{Tylko spogl¹dam na mój dom. To tam. Na Ksiê¿ycu.}
{120}{}{Chyba powinno mi byæ z tego powodu wstyd, ale nie zwa¿am na trupy.}
{121}{}{Akurat. Wynoœ siê st¹d, zanim naœlê na ciebie nocn¹ stra¿.}
{122}{}{Rany, niezbyt ci siê podoba ¿ycie. Pomogê ci je zakoñczyæ.}
{123}{}{Tu jestem. A teraz odejdŸ albo zgiñ!}
{124}{}{I think I'll go.}
{125}{}{I'd really rather live.}
{126}{}{Co s³ychaæ z Rozpruwaczami?}
{127}{}{Zabij¹ ciê!}
{128}{}{They're dead. Deathclaws killed'em all, see?}
{129}{}{Jeszcze nic.}
{130}{}{Œwietnie. Zanieœ to Brzytwie.}
{131}{}{Nie wciskaj mi kitu. Wynocha!}
{132}{}{To rusz st¹d twój ty³ek i przerób skurwieli na potrawkê!}
{133}{}{Yo, homie! Nice job you did on the Regulators!}
