{100}{}{Pompa hydrosprê¿eniowa, cewki, magnetyczna plomba pró¿niowa, taœma zasilaj¹ca, adaptery trzy piny na trzy piny... Niez³a kolekcja czêœci.}
{101}{}{Miles prawdopodobnie móg³by wykorzystaæ te czêœci do naprawy farm hydroponicznych.}
