{100}{}{Po raz pierwszy w twoim ¿yciu napotykasz naturalny mrok taki jak ten. Wydaje ci siê on niemal nienaturalny.}
{101}{}{Z ledwoœci¹ udaje ci siê utrzymywaæ twoje lêki pod kontrol¹, lecz jesteœ w stanie zag³êbiæ siê w ciemnoœæ.}
