{100}{}{To przewodnik karawany Wszêdobylskich Handlowców.}
{101}{}{Czeœæ, jak chcesz dostaæ robotê przy karawanie, porozmawiaj z Rutgerem. Stoi tam obok.}
{102}{}{Musisz pogadaæ z Rutgerem.}
{103}{}{Wienc siê zapisujesz. Dobrze to s³yszeæ. Wisz, wyruszamy mniej wiencej co dziesiêæ dni. To ósmy, osiemnasty i dwudziesty ósmy ka¿dego miesionca. Teraz robimy wypady do Bractwa, Z³omowa i Gruzów.}
{104}{}{To jaka jest zap³ata?}
{105}{}{Hm.}
{106}{}{Dostaniesz 400 kapslów. Mo¿esz mówiæ, ¿e to nie za du¿o, ale chodzimy czensto i u nas ³atwo nie traci siê ¿ycia. A tom zap³atem dostajesz za droge w ka¿dom strone, nie ¿e musisz przejœæ w obie strony, tylko ¿e dostaniesz ³oncznie 800, je¿eli tak zrobisz. }
{107}{}{ Wyruszamy dzisiaj. Interesuje ciê to?}
{108}{}{ Wyruszamy }
{109}{}{Pusto}
{110}{}{}
{111}{}{. Interesuje ciê to?}
{112}{}{I tak dam ci robotê, chocia¿... Niewa¿ne. Interesuje ciê to?}
{113}{}{Jasne.}
{114}{}{Nie.}
{115}{}{Mo¿e.}
{116}{}{Tatata.}
{117}{}{Te?}
{118}{}{W porzondeczku. ¯aden problem. Daj mi tylko znaæ, jak zmienisz zdanie.}
{119}{}{Mo¿esz siê wreszcie zdecydowaæ?}
{120}{}{Wróæ tu, je¿eli przyjdzie ci szukaæ zajencia. To ósmy, osiemnasty i dwudziesty ósmy. Bywaj.}
{121}{}{E, nic z tego, jak masz po dwie lewe rence i nogi. Wybacz, wielkoludzie.}
{122}{}{Skieruj siê tu z powrotem, jak siê lepiej poczujesz.}
{123}{}{Rany, nie wyglondasz dobrze. Trzeba ci wzi¹æ coœ na zomb, tylko trzymaj siê z dala od Boba.}
{124}{}{Wynoœ¿e siê st¹d!}
{125}{}{Nie mo¿na by³o zostawiæ moich rzeczy w spokoju, prawda? Po co ci to by³o?}
{126}{}{Bo jezdem wrednym, zielonym matkojebem z kosmosu i jezdem... "z³¹" osob¹!}
{127}{}{Wcale nie chcê tego robiæ, ale umieram z g³odu i mam dzieci do wykarmienia.}
{128}{}{Wyd³ubiê ci serce ³y¿k¹!}
{129}{}{[Surrender]}
{130}{}{[Attack]}
{131}{}{Wienc zwyczajnie plujesz mi w twarz, co? Chyba jedyny sposób, a¿eby przemówiæ ci do rozumu przez tom grub¹ czache, to od³onczyæ j¹ od karku.}
{132}{}{W porzondku, ale to nie usprawiedliwienie. I tak musisz siê stond zabieraæ.}
{133}{}{Myœlisz, ¿e uwierzem w ten bzdet? Stra¿!}
{134}{}{Chyba wsadzenie ciê do zbiornika nauczy ciê lepszych manier. Pójdziesz po dobroci, czy bendzie trzeba za³atwiæ to brutalnie?}
{135}{}{Spotkamy siê w Piekle!}
{136}{}{Tak. Przepraszam.}
{137}{}{Wienc twardziel z ciebie, co? Szukasz tylko kolejnej rozróby?}
{138}{}{Jak stond nie znikniesz, zawo³am gliny!}
{139}{}{Stra¿! Policja!}
{140}{}{Lepiej stond odejdŸ...}
{141}{}{Niestety, nie dam ci roboty.}
{142}{}{Ja naprawde bardzo chcem ci daæ robotem, tyle ¿e nie mogem.}
{143}{}{OdejdŸ.}
{144}{}{Milusio, ale niezbyt mi siê podobasz.}
{145}{}{Wienc OK! Zap³ata to 400 kapslów. Którom trase preferujesz?}
{146}{}{Œwietnie to s³yszeæ. Wróæ tu }
{147}{}{ósmego}
{148}{}{osiemnastego}
{149}{}{dwudziestego ósmego}
{150}{}{}
{151}{}{}
{152}{}{Do Cytadeli Bractwa Stali.}
{153}{}{. Wtedy wyruszysz. Jak zwykle, zap³atom bendzie 400 kapslów.}
{154}{}{OK.}
{155}{}{Niestety, nie mogê czekaæ.}
{156}{}{Nie mam pewnoœci, co siê sta³o, ale ca³a karawana zosta³a stracona. Dziwne, ¿e coœ takiego siê zdarzy³o, a tobie uda³o siê ujœæ ca³o. Zwykle tak siê nie dzieje. Dlatego chyba nie mogem ciê ju¿ wiencej wynaj¹æ. Na pewno rozumiesz, dlaczego.}
{157}{}{Do Z³omowa.}
{158}{}{L.A. Boneyard}
{159}{}{Hm, nie teraz. Mo¿e kiedy indziej.}
{160}{}{Dobrze to s³yszeæ, skrzyknem reszte za³ogi.}
{161}{}{Œwietnie.}
{162}{}{Wynoœ¿e siê ju¿ st¹d. Powodzenia!}
{163}{}{Staraj siê unikaæ k³opotów, a nie ich szukaæ.}
{164}{}{Tylko tam uwa¿aj, Gruzy to nienajbezpieczniejsze miejsce...}
{165}{}{To dobrze. Te ciemne przejœcia s¹ naprawdê dziwne, ale œwietnie siê po nich wendruje.}
{166}{}{Maj¹ tam pe³no z³ego elementu. Lepiej uwa¿aj, z kim siê tam zadajesz.}
{167}{}{Œwietnie. Z³omowo to niez³e miejsce.}
{168}{}{Oh, and stop by to see Killian; tell him 'Hi' for me. Man, the times we used to have on those caravans...}
{169}{}{S³ysza³em, ¿e jest tam jakiœ dziwny doktór. Mówi¹, ¿e robi w trupach.}
{170}{}{Co, u diab³a, przysz³o ci do g³owy, ¿e zachcia³o ci siê porzuciæ tom karawane. Wróci³a bezpiecznie, ale to, cholera, czyste szczêœcie.}
{171}{}{Czy móg³byœ daæ mi jeszcze jedn¹ szansê?}
{172}{}{Nic.}
{173}{}{Gówno mnie to obchodzi!}
{174}{}{Ig wa neeka rooola?}
{175}{}{Lig.}
{176}{}{Znowu zdarzy³o ci siê spieprzyæ robotem. NajwyraŸniej nie jesteœ w stanie podo³aæ tego typu pracy.}
{177}{}{Czemu mia³bym to zrobiæ?}
{178}{}{Nie fatyguj siê.}
{179}{}{Bo zafundujê ci dziurê we ³bie, jak tego nie zrobisz.}
{180}{}{Mam lepsze rzeczy do roboty, ni¿ ³aziæ z jak¹œ durn¹ karawan¹.}
{181}{}{Nie by³o wtedy mowy, ¿e nie mogê odejœæ. Wszystko wydawa³o siê byæ w porz¹dku.}
{182}{}{Rozumiem... to przez narkotyki. Có¿, ¿yj tak, jeœli tego pragnisz.}
{183}{}{Przykro mi, ¿e tak uwa¿asz.}
{184}{}{Dziwne, ¿e nie zdarzy³o ci siê to wczeœniej. Skoro tak w³aœnie jest, to nikomu nie zaszkodzi, jak dam ci nastêpnom szanse.}
{185}{}{To by³ kawa³ dobrej roboty. Chcesz siê zapisaæ na nastêpnom?}
{186}{}{Jasne.}
{187}{}{Nie.}
{188}{}{Mo¿e.}
{189}{}{Iiik!}
{190}{}{Leb.}
{191}{}{Masz wszystkie twoje rzeczy? Dzisiaj wyruszamy.}
{192}{}{Tak.}
{193}{}{Nie!}
{194}{}{Ach!}
{195}{}{Nie przejmuj siê, w razie czego dam te robote komu innemu. Nie masz ¿adnych zobowionzañ... dopóki nie wyruszysz z karawan¹, zgadza siê?}
{196}{}{Nastempna karawana nie wyruszy przed }
{197}{}{ósmym}
{198}{}{osiemnastym}
{199}{}{dwudziestym ósmym}
{200}{}{}
{201}{}{}
{202}{}{}
{203}{}{. Skieruj siê tu z powrotem, jak nadal bendziesz chcieæ te robote.}
{204}{}{January }
{205}{}{February }
{206}{}{March }
{207}{}{April }
{208}{}{May }
{209}{}{June }
{210}{}{July }
{211}{}{August }
{212}{}{September }
{213}{}{October }
{214}{}{November }
{215}{}{December }
{216}{}{Bractwo Stali, przybywamy! Znaczy siê... Ja z wami nie wyruszem, ale wisz, co mam na myœli.}
{217}{}{OK, zejdŸ mi ju¿ z widoku. Czekajom na ciebie te fanatyki z Bractwa.}
{218}{}{Mam nadziejem, ¿e lubisz góry! Idziesz prosto na nie. Czeka ciê tam pewnie sporo akcji.}
{219}{}{Wszystko gotowe do drogi; skierujecie siê na wprost przez góry! Powinna tam byæ solidna zadyma!}
# invasion- WastelandGhost@RestorationMOD
{300}{}{So you signed up; good to hear it. So ya know, we leave just about every ten days. That's the 8th, 18th, and 28th of each month. Right now we're making runs to The Brotherhood and Junktown. There are rumors about a mutant invasion in L.A. Boneyard, so we don't go there anymore.}
