{100}{}{To znu¿ony rybak.}
{101}{}{Panie szanowny, s³ysza³em o tobie, i bêdê wdziêczny, jak zostawisz mnie i mojego ch³opaka w spokoju.}
{102}{}{Pani szanowna, s³ysza³em o tobie, i bêdê wdziêczny, jak zostawisz mnie i mojego ch³opaka w spokoju.}
{103}{}{Witam pana. Nieczêsto widujê tutaj obcych. Czy mogê coœ dla ciebie zrobiæ?}
{104}{}{Witam pani¹. Nieczêsto widujê tutaj obcych. Czy mogê coœ dla ciebie zrobiæ?}
{105}{}{Pewnie nie wiesz, gdzie mo¿na znaleŸæ hydroprocesor, co?}
{106}{}{Pewnie nie wiesz niczego o armiach mutantów, co?}
{107}{}{Sk¹d pochodzisz?}
{108}{}{Jak idzie ³owienie?}
{109}{}{Daj mi wszystko, co masz, albo ciê zabijê!}
{110}{}{Runk!}
{111}{}{Zaraz, czy aby nie jesteœ tym facetem, co wêdruje po Pustkowiu i kopie potworom zady? Czy mogê ci pomóc?}
{112}{}{Zaraz, czy aby nie jesteœ t¹ dzieweczk¹, co wêdruje po Pustkowiu i kopie potworom zady? Czy mogê ci pomóc?}
{113}{}{Mam ju¿ niezbyt wiele zapasów...}
{114}{}{¯aden facet nigdy o mnie nie powiedzia³, ¿e jestem niegoœcinny, i nie chcê powtarzaæ, co mówi¹ o mnie kobiety, ale próbujê ³owiæ ryby i potrzebna mi absolutna cisza, ¿eby te cholery z³apaæ, wiêc proszê, postaraj siê nie robiæ ha³asu.}
{115}{}{Czy ktoœ ci kiedyœ powiedzia³, ¿e bredzisz?}
{116}{}{OK.}
{117}{}{Szukam informacji.}
{118}{}{Czy wygl¹dam ci na szabrownika? No, mo¿e wygl¹dam, ale to dlatego, ¿e spêdzam masê czasu na Pustkowiu, próbuj¹c nauczyæ mojego ch³opaka ³owiæ i byæ mê¿czyzn¹.}
{119}{}{Nie szabrowa³em od szeœciu lat. Za du¿o radskorpionów. Cz³owiek mo¿e tam zgin¹æ, jak wokó³ ganiaj¹ te szkodniki.}
{120}{}{Jakieœ osiem lat temu sprzeda³em jakieœ procesory w Z³omowie. Nie wiem, co one robi³y. Jeden z nich móg³ byæ hydroprocesorem, ale ja bym na to nie stawia³.}
{121}{}{W ka¿dym razie do ³owienia potrzebujê ciszy, wiêc bêdê wdziêczny, jak postarasz siê nie ha³asowaæ i dasz mi siê zaj¹æ robot¹, zanim ja i mój ch³opak pomrzemy z g³odu.}
{122}{}{Mutancie armie? Nie tutaj. Nawet normalne armie by³yby wystarczaj¹co z³e, he he.}
{123}{}{Wiesz, ¿e na œwiecie jest za du¿o polityki. Ci¹gle mówiê mojemu ch³opakowi, ¿e ci politycy nie mog¹ siê doczekaæ, ¿eby znowu nie wysadziæ wszystkiego w powietrze. To dlatego ¿yjê z natury, ¿eby unikaæ polityków! To jedyny sposób, ¿eby prze¿yæ.}
{124}{}{No, to raczej intymna informacja. Zabija³em ludzi za pytanie o mniej osobiste sprawy, mo¿esz spytaæ ch³opaka. Ale wygl¹dasz mi na uczciw¹ personê, wiêc ci tym razem odpuszczê.}
{125}{}{Có¿, ³owiê w tym miejscu od piêciu lat i robi siê tu coraz gorzej. Myœlê, ¿e to Skunks, olbrzymi, trójoki zêbacz, przep³asza wszystko z mojego ³owiska.}
{126}{}{Ale dorwê tê rybê, tylko poczekaj. Miêdzy nami to ju¿ sprawa osobista, i tylko jedno z nas wyjdzie z tego z ¿yciem, mo¿esz mi wierzyæ. W tej kwestii jestem bardziej powa¿ny ni¿ Bractwo Stali.}
{127}{}{Teraz pewnie mnie zabijesz, ale jak ci siê nie postawiê, to dam mojemu ch³opakowi z³y przyk³ad. Rozumiesz mój dylemat? Czemu po prostu st¹d nie odejdziesz, ¿eby u³atwiæ ¿ycie obu stronom?!}
{128}{}{Nie odejdê, a ty w ogóle nie bêdziesz ju¿ chodziæ, chyba ¿e zrobisz, co ci ka¿ê.}
{129}{}{Zamknij siê i zdychaj!}
{130}{}{W porz¹dku. Rozstaniemy siê w pokoju.}
{131}{}{Synu, chyba odrobinê zbyt d³ugo wêdrujesz ju¿ po Pustkowiu.}
{132}{}{Córciu, chyba odrobinê zbyt d³ugo wêdrujesz ju¿ po Pustkowiu.}
{133}{}{Spróbuj tego.}
{134}{}{Spróbuj tego... O cholera, gdzie ja to podzia³em...}
{135}{}{Có¿, s³ysza³em o wielkiej Krypcie kawa³ drogi na wschód, i opowieœci o tajnej Krypcie gdzieœ na po³udniu. I jakieœ procesory mog¹ byæ w Z³omowie i Hubie. Mam nadziejê, ¿e to pomo¿e.}
{136}{}{Nie chcê wydawaæ siê niegoœcinnym, ale do ³owienia potrzebujê ciszy, wiêc bêdê wdziêczny, jak postarasz siê nie ha³asowaæ i dasz mi siê zaj¹æ robot¹, zanim ja i mój ch³opak pomrzemy z g³odu. I powodzenia w zabijaniu tych szkodników.}
{137}{}{Mutancie armie? Nawet normalne armie by³yby wystarczaj¹co z³e. S³ysza³em pog³oskê, ¿e ktoœ nêka ghule w Nekropolis, ale to by³o ju¿ jakiœ czas temu.}
{138}{}{O, to osobiste pytanie. Z ³ona mojej matki, oczywiœcie, ale to odrobinê zbyt proste. Nie mam ju¿ domu. Ja i mój ch³opak ci¹gle tylko wêdrujemy i staramy siê prze¿yæ.}
{139}{}{Wiem wprawdzie gdzie jest parê skrytek z zapasami, ale to moja s³odka tajemnica.}
{140}{}{Có¿, panuje tu Prawo Pustkowia - zabij lub giñ - ale coœ ci powiem. Zabijaj dalej potwory, a ja dam ci trochê zapasów.}
{141}{}{W porz¹dku. Ale co, u diab³a, znaczy "runk"? Cokolwiek to jest, mam nadziejê, ¿e jest przyjazne.}
{142}{}{O, czujê siê ura¿ony. Proszê bardzo, wy³a¿ê ze skóry, ¿eby byæ przyjaznym, a ty twierdzisz, ¿e bredzê! Có¿! £atwo siê nie obra¿am, ale przez ciebie wkurzy³em siê wystarczaj¹co, ¿eby r¹bn¹æ kogoœ atomówk¹.}
{143}{}{Tak czy owak, lepiej idŸ st¹d precz. £ajzo!}
{144}{}{Serdecznie ci dziêkujê.}
{145}{}{O czym chcesz rozmawiaæ?}
{146}{}{Staram siê znaleŸæ hydroprocesor.}
{147}{}{Staram siê czegoœ dowiedzieæ o armiach mutantów.}
{148}{}{Co mo¿esz mi powiedzieæ o Bractwie?}
{149}{}{Co mo¿esz mi powiedzieæ o Gruzach?}
{150}{}{Przykro mi, chyba nie jestem ci w stanie pomóc.}
{151}{}{"Runk" to nie to samo, co nieha³asowanie. Teraz zamknij japê i idŸ precz.}
{152}{}{W porz¹dku. Bierz, co chcesz, i wynoœ siê.}
{153}{}{Nie masz zbyt pozytywnego nastawienia do œwiata, co?}
{154}{}{Wybacz, ¿e nie jestem ju¿ wiêcej goœcinny, ale uwa¿am, ¿e lepiej bêdzie, jak po prostu odejdziesz.}
{155}{}{Staram siê ich unikaæ, jak mogê. Ich patrole potrafi¹ byæ ca³kiem wredne, gdy postanowi¹ ciê nie lubiæ.}
{156}{}{To na wybrze¿u. S³ysza³em historie o szalej¹cych gangach i wszelkich rzeczach, których nie chcê, ¿eby mój ch³opak ogl¹da³, wiêc trzymam siê stamt¹d na dystans!}
{157}{}{Schowaj to, zanim komuœ zrobisz krzywdê. Z broni¹ w rêku nie da siê prowadziæ uprzejmej rozmowy.}
{158}{}{Synu, nie ma to jak starcie ryby z cz³owiekiem.}
{159}{}{Synu, czy opowiada³em ci kiedyœ, jak z³apa³em wêgorza-olbrzyma...}
{160}{}{Synu, nie pyskuj w³asnemu ojcu!}
{161}{}{Mo¿e tym razem z³apiê tego trójokiego zêbacza.}
{162}{}{Nadci¹ga obiad!}
{163}{}{Nie ma to jak smak soczystej rybki pieczonej nad otwartym ogniem.}
{164}{}{Cicho synu, straszysz ryby.}
