{100}{}{To szczup³y, zaniedbany ch³opiec.}
{101}{}{Chyba nie powinienem z tob¹ rozmawiaæ. OdejdŸ st¹d.}
{102}{}{Czemu masz wyci¹gniêt¹ broñ? Nic nie mamy, nawet ryb!}
{103}{}{Czeœæ. Czego chcesz?}
{104}{}{Jak idzie ³owienie?}
{105}{}{Mam ju¿ niezbyt wiele zapasów...}
{106}{}{Widzia³eœ ostatnio coœ niezwyk³ego?}
{107}{}{Chcesz pos³uchaæ o mojej przygodzie w gnieŸdzie radskorpionów?}
{108}{}{Runk!}
{109}{}{Czeœæ. Czy to nie ty jesteœ t¹ osob¹, co wêdruje pomagaj¹c ludziom? Na pewno masz masê ciekawych historii do opowiedzenia!}
{110}{}{Sk¹d pochodzisz?}
{111}{}{Siemanko. Widzê, ¿e masz doœæ oleju w g³owie, ¿eby tu nie ³owiæ. Co s³ychaæ?}
{112}{}{Nie jestem pewny. Tata i ja b³¹kamy siê po Pustkowiu ju¿ tak d³ugo. Mieliœmy z sob¹ przyjaciela, ³owcê skorpionów, ale odbi³o mu, i musieliœmy go zabiæ, a potem...}
{113}{}{Hmmm, mo¿e lepiej o tym nie mówiæ.}
{114}{}{Opowiedz mi o twoim tacie.}
{115}{}{Co ze skorpionami?}
{116}{}{Do dupy. Przepraszam, nie powinienem u¿ywaæ wyra¿enia "do dupy". Tata uwa¿a, ¿e ludzie, którzy mówi¹, ¿e coœ jest do dupy, to albo bezmózgowe prostaki, albo niepotrafi¹cy siê wys³owiæ frajerzy. Tata zawsze stara siê mówiæ m¹drze.}
{117}{}{Zgadzam siê z twoim ojcem.}
{118}{}{Niestety. To nie ze mn¹ rozmawia siê o zapasach.}
{119}{}{Widzia³em wielkiego stwora podobnego do olbrzymiego paj¹ka z dwiema g³owami, i jedna g³owa wygl¹da³a na ludzk¹. Tata uwa¿a, ¿e wch³on¹³em za du¿o promieniowania. Sam nie wim. Ska¿ona woda robi z mózgiem dziwaczne rzeczy.}
{120}{}{Ta, na przyk³ad?}
{121}{}{Co to runk?}
{122}{}{Jasne!}
{123}{}{Najgorsze w polowaniu na radskorpiony jest czekanie, a¿ wpadn¹ w zasadzkê.}
{124}{}{Najgorsze w polowaniu na radskorpiony jest œciganie ich, jak zaczn¹ uciekaæ!}
{125}{}{Najgorsze w polowaniu na radskorpiony jest oberwanie ich kolcem w twarz.}
{126}{}{Ta. Znasz opowieœæ o najeŸdŸcach, którzy wpadli do gniazda radskorpionów, i byli wszyscy ¿¹dleni i ¿¹dleni, i po¿arci ¿ywcem, z wyj¹tkiem jednego, który uciek³ z odgryzion¹ po³ow¹ twarzy?!}
{127}{}{Rany, to by³o niez³e!}
{128}{}{No có¿, jest trochê krzykliwy i nudny, i nie jestem pewny, czy to mój prawdziwy tata. Myœlê, ¿e ukrad³ mnie sk¹dœ, jak by³em niemowlakiem. Ale z regu³y mnie karmi, wiêc chyba go lubiê.}
{129}{}{S¹ wielkie i wredne, i robi siê ich coraz wiêcej. Tata mówi³, ¿e byli bohaterowie, którzy wêdrowali po Pustkowiu i je wybijali, ale myœlê, ¿e wiêkszoœæ z nich ju¿ nie ¿yje.}
{130}{}{Jacy bohaterowie?}
{131}{}{Ta, doroœli zawsze siê ze sob¹ zgadzaj¹. To g³upie.}
{132}{}{Du¿y Henry z nami chodzi³ i by³ lepszy ni¿ tata i ja, dopóki nie zwariowa³ i nie spróbowa³ mnie udusiæ. Tata musia³ go zastrzeliæ!}
{133}{}{Czy twój tata jest dobrym strzelcem?}
{134}{}{Kim by³ Du¿y Henry?}
{135}{}{To brzmi wspaniale! Lepiej jednak wrócê do ³owienia, albo zrobimy siê tacy g³odni, ¿e bêdziemy musieli zjeœæ ciebie!}
{136}{}{Masa bohaterów. Facet, który za³o¿y³ Bractwo Stali, Roger Maxim, by³ naprawdê dobrym zabójc¹ skorpionów. Jak bêdê starszy, dowiem siê, gdzie oni s¹, i siê do nich przy³¹czê!}
{137}{}{Brzmi nieŸle.}
{138}{}{Do Bractwa jest naprawdê trudno wst¹piæ. Poza tym to d³uga, niebezpieczna podró¿.}
{139}{}{Jest w porz¹dku, chyba. Wprawdzie widzia³em, jak r¹bn¹³ radskorpiona miêdzy oczy z ponad szeœædziesiêciu metrów, ale to by³ szczêœliwy traf.}
{140}{}{To facet z po³udnia. Ktoœ w rodzaju najeŸdŸcy, który stara³ siê ¿yæ z natury, a nie z ludzi. By³ naprawdê wspania³ym goœciem, ale czasem mu odbija³o, i pewnego razu... aa... to niewa¿ne.}
{141}{}{Ta. Bêdê bo-ha-te-rem, zupe³nie jak on. Mo¿esz na to stawiaæ!}
{142}{}{Myœlisz, ¿e ¿ycie w ten sposób jest ³atwe? Nie bojê siê trudów, a tu nigdzie nie jest bezpiecznie, wiêc nie zrezygnujê. Muszê tylko urosn¹æ na tyle, ¿eby samodzielnie wyruszyæ.}
{143}{}{Co z walk¹ miêdzy radskorpionem i cz³owiekiem?}
{144}{}{Tylko jakieœ dwanaœcie razy...}
{145}{}{A, tak jest.}
{146}{}{Myœlê, ¿e tym razem siê przeziêbiê...}
{147}{}{Pospiesz siê! Konam z g³odu!}
{148}{}{Ju¿ od tak dawna nic nie z³apa³eœ, ¿e zapomnia³em, jak one smakuj¹.}
{149}{}{Tato, s³ysza³eœ coœ...}
