{100}{}{Zapalasz flarê.}
{101}{}{Ta flara zosta³a zu¿yta.}
{102}{}{We flarze koñczy siê paliwo, wskutek czego przestaje ona emitowaæ œwiat³o.}
{103}{}{To zapalona flara.}
{104}{}{To zu¿yta flara.}
{105}{}{To flara.}
