{100}{}{Nie jesteœmy tu, ¿eby rozmawiaæ.}
{101}{}{Bêdê za tob¹ pod¹¿aæ a¿ do œmierci.}
{102}{}{To ca³kiem wa¿ne zadanie, co?}
{103}{}{Nicole powiedzia³a, ¿e mamy spowodowaæ jak najwiêksze zniszczenia.}
{104}{}{Kogo mam zabiæ w nastêpnej kolejnoœci?}
{105}{}{Po co gawêdzimy?}
{106}{}{Nie lubiê tych zakapturzonych palantów.}
{107}{}{To mo¿e byæ niebezpieczne.}
{108}{}{Czas iœæ.}
{109}{}{To miejsce wygl¹da jak gówno rozbryzgane na œcianie.}
{110}{}{Chyba siê porzygam.}
{111}{}{Nicole kaza³a nam wróciæ, jak tylko opuœcisz Katedrê.}
{112}{}{Mi³o ciê spotkaæ. Pobaraszkujmy.}
