{100}{}{To Jerry ze zwiadu Uczniów Apokalipsy.}
{101}{}{To Postrach ze zwiadu Uczniów Apokalipsy.}
{102}{}{To Richard ze zwiadu Uczniów Apokalipsy.}
{103}{}{To Jason ze zwiadu Uczniów Apokalipsy.}
{104}{}{To Cieñ ze zwiadu Uczniów Apokalipsy.}
{105}{}{To Lynne ze zwiadu Uczniów Apokalipsy.}
{106}{}{To Gwendolyne ze zwiadu Uczniów Apokalipsy.}
{107}{}{To Rosa ze zwiadu Uczniów Apokalipsy.}
{108}{}{To Elizabeth ze zwiadu Uczniów Apokalipsy.}
{109}{}{To Rebeca ze zwiadu Uczniów Apokalipsy.}
{110}{}{Kto wêdruje po gmachu Uczniów?}
{111}{}{Hê?}
{112}{}{Jestem }
{113}{}{. Przybywam w pokoju.}
{114}{}{Jestem }
{115}{}{. Wasza zguba.}
{116}{}{Kim s¹ Uczniowie?}
{117}{}{OK. Widzê, ¿e myœlenie idzie ci z pewnymi oporami. Kto ty?}
{118}{}{Ja }
{119}{}{. Ty trup.}
{120}{}{Ja }
{121}{}{. Ja pymóc.}
{122}{}{Ja zabiæ!}
{123}{}{Ja }
{124}{}{. Ja iœæ.}
{125}{}{Chcesz pomóc? Musisz chyba porozmawiaæ z Nicole lub Jake'm, jeœli chcesz nam pomóc. Oni maj¹ wiêcej czasu na zadawanie siê z wolnomyœlicielami.}
{126}{}{OK. Tylko unikaj tu k³opotów.}
{127}{}{Chcesz skoñczyæ z niegodziwoœciami Dzieci?}
{128}{}{Tak. Chcê zmieœæ te szumowiny z powierzchni Ziemi.}
{129}{}{Nie. Wolê pozabijaæ was, cieniasy.}
{130}{}{Kim s¹ te Dzieci?}
{131}{}{Czemu niby mam zabijaæ dzieci?}
{132}{}{Doskonale! PójdŸ porozmawiaæ z Nicole, a ona powie ci, jak mo¿esz nam dopomóc.}
{133}{}{Dzieci to okultystyczna sekta, która czci jakiegoœ mrocznego boga. Osobiœcie uwa¿am, ¿e jest w nich coœ, co cuchnie z³em.}
{134}{}{Zg³adzê ich.}
{135}{}{No, nie wiem. Wygl¹da na to, ¿e s¹ dla mnie za silni.}
{136}{}{Co mogê zrobiæ, ¿eby wam pomóc?}
{137}{}{Zapomnij! Mowy nie ma, ¿e wam pomogê.}
{138}{}{To silna grupa, ale s¹dzê, ¿e z twoimi umiejêtnoœciami bêdziesz w stanie siê do nich wœlizgn¹æ i pomóc nam ich zniszczyæ.}
{139}{}{W takim razie zrobiê to.}
{140}{}{Nie. Raczej wam nie pomogê.}
{141}{}{Jak ci pasuje. Je¿eli opanuj¹ ca³e Pustkowie, nie mów, ¿e ciê nie ostrzegliœmy.}
{142}{}{Jeœli porozmawiasz z Nicole, ona powie ci wiêcej o tym, co mo¿na zrobiæ, ¿eby ich powstrzymaæ.}
{143}{}{Dziêkujê. ¯egnaj.}
{144}{}{Nie dzieci. Krzywdzenie ich nawet przez myœl by nam nie przesz³o. Nie. Chodzi o Dzieci Katedry. Wredn¹ sektê.}
{145}{}{W takim razie, pewnie - unicestwiê ich.}
{146}{}{Aaa. Zdawa³o mi siê, ¿e mówisz o dzieciakach. Niewa¿ne. Raczej wam nie pomogê.}
{147}{}{Co mo¿esz mi powiedzieæ na temat tych Dzieci?}
{148}{}{Jesteœmy Uczniami Apokalipsy. Próbujemy zaprowadziæ pokój na Pustkowiu.}
{149}{}{Wygl¹da to na dobry pomys³. ¯yczê wam powodzenia w jego realizacji.}
{150}{}{Jak zamierzacie tego dokonaæ?}
{151}{}{Wydaje siê to wysoce nieprawdopodobne.}
{152}{}{Pracujemy nad zaszczepieniem mieszkañcom Pustkowia tolerancji dla tych, którzy zostali zmutowani z powodu destruktywnoœci natury cz³owieka.}
{153}{}{No to ¿yczê wam w tym powodzenia.}
{154}{}{W ca³ej historii nigdy nie by³o tolerancji. Czemu, twoim zdaniem, wybuch³a Wojna?}
{155}{}{To zwyk³a kupa bzdur.}
{156}{}{Masz racjê mówi¹c, ¿e my, jako ludzie, mamy zamkniête umys³y. Jednak¿e zawsze pozostaje nadzieja.}
{157}{}{W takim razie ¿yczê wam powodzenia.}
{158}{}{Podzielam twoje zdanie. Pozwól, ¿e uczyniê twój umys³ bardziej otwarty za pomoc¹ tego.}
{159}{}{Niech bêdzie, jak jest, a o opiniê ciê nikt nie prosi³. ¯egnaj.}
{160}{}{Jest wœród nas cynik. Z pewnoœci¹ masz ku temu jakieœ powody. Bez wzglêdu na nie, z pewnoœci¹ mo¿emy dojœæ do jakiegoœ porozumienia.}
{161}{}{W takim razie ¿yczê ci powodzenia. ¯egnaj.}
{162}{}{Podobno Dzieciom uda³o siê poznaæ niektóre z naszych tajemnic. Ciekawe, jak to siê sta³o?}
{163}{}{Uwa¿am, ¿e gdzieœ tu jest szpieg.}
{164}{}{Wiem. To ja sprzedajê im wasze sekrety.}
{165}{}{Z pewnoœci¹ tylko ci siê tak wydaje. Jak mogliby siê czegokolwiek dowiedzieæ?}
{166}{}{Naprawdê? Te¿ tak myœlê, ale zdawa³o mi siê, ¿e nie zdobêdê wiele poparcia dla tej teorii.}
{167}{}{Czy masz jakieœ podejrzenia, kto to mo¿e byæ?}
{168}{}{Dobrze wiedzieæ. Dziêki za twój czas.}
{169}{}{Jesteœ podwójnym agentem!!!}
{170}{}{Niestety nie. Jedyne, do czego uda³o mi siê dojœæ, to to, ¿e ta osoba musi mieæ dostêp do pewnych informacji i okazjê do wychodzenia na zewn¹trz. Mo¿esz spróbowaæ przyjrzeæ siê nowicjuszom i zwiadowcom.}
{171}{}{Dziêki. Czeœæ.}
{172}{}{Nicole bêdzie wiêc zadowolona, wiedz¹c, ¿e agent zgin¹³ z mojej rêki.}
{173}{}{Z pewnoœci¹ masz racjê. Dziêkujê za rozjaœnienie sprawy.}
{174}{}{Myœlê, ¿e jesteœ podwójnym agentem. Próbujesz mnie oszukaæ, jak widzê. Teraz wiêc UMRZESZ!}
{175}{}{Za³atwienie tego szpiega by³o œwietn¹ robot¹. Teraz mo¿emy mieæ jakieœ szanse w walce przeciw Dzieciom.}
{176}{}{¯yczê wam szczêœcia.}
{177}{}{I can help train you to become a more efficient fighter.}
{178}{}{Naprawdê? By³oby wspaniale.}
{179}{}{There you go. Maybe that will help you, if you get into a fight.}
