{100}{}{Otwierasz zamek.}
{101}{}{Przypadkowo blokujesz zamek.}
{102}{}{Nie jesteœ w stanie otworzyæ zamka.}
{103}{}{Nie udaje ci siê otworzyæ zamka.}
{104}{}{Zamek jest zamkniêty.}
{105}{}{Zamek jest otwarty.}
