{100}{}{To kantorka Dzieci Katedry.}
{101}{}{Mistrz odpuœci twe grzechy! Przy³¹cz siê do nas i ¿yj w swobodzie! Chwalmy Mistrza i jego mi³osierdzie!}
{102}{}{Witaj! Czy zaœpiewasz ze mn¹ hymn pochwalny?... Kiedyœ œlepa wêdrowa³am, po wrogiej ziemi siê b³¹ka³am...}
{103}{}{Przepraszam, ¿e przerywam ci twój hymn, ale gdzie mogê spotkaæ Mistrza?}
{104}{}{Z takim g³osem nie masz szansy na sukces w biznesie rozrywkowym.}
{105}{}{Kto tu rz¹dzi?}
{106}{}{...lecz Mistrza w zad poca³owa³am...}
{107}{}{Fajno! Fajno! Ja dobra œpiwaæ piusenka!}
{108}{}{On odnajduje ciê gdzie i kiedy siê tego najmniej spodziewasz! Chwalmy Mistrza! Chwalmy Œwiêty P³omieñ! Chwalmy œwiat!}
{109}{}{Có¿ za cudowny ¿art! Nie mia³am kiedyœ poczucia humoru, lecz dziêki Mistrzowi jestem teraz pe³na radoœci! Chwalmy Mistrza!}
{110}{}{Ten, który spogl¹da w górê. Ten, który zasiada w dole. Ten, który spoczywa wewn¹trz. Chwalmy Mistrza za klarownoœæ Jego wizji!}
{111}{}{Och, gdybym tylko mia³a takie szczêœcie! Byæ mo¿e pewnego dnia Mistrz pozwoli mi uca³owaæ Swoje cz³onki. Chwalmy Mistrza! Chwalmy Œwiêty P³omieñ!}
{112}{}{Hmm, niezupe³nie o to mi chodzi³o. Lepiej nieco poæwicz. Chwalmy Mistrza! Chwalmy Œwiêty P³omieñ!}
{113}{}{[Koniec]}
