{100}{}{You see: Holodisk.}
{101}{}{Pip-Boy 2000 displays: "Downloading data ... ... ... Done. Have a nice day!"}
{102}{}{Wygl¹da to na taœmê z nagraniem rozrywkowym.}
{103}{}{Ta taœma jest zbyt uszkodzona, by móc z niej cokolwiek odczytaæ.}
{104}{}{Nagranie na tej taœmie wydaje siê dotyczyæ jakiegoœ kodu dostêpowego, zapisanego na innej taœmie.}
{105}{}{Pojawia siê niewielki wyœwietlacz, a na nim resztki jakiegoœ filmu o drugiej wojnie œwiatowej.}
#
{106}{}{The disk is empty.}
{107}{}{You discard the disk.}
