{100}{}{Ten zamek jest ju¿ otwarty.}
{101}{}{Udaje ci siê otworzyæ zamek.}
{102}{}{NajwyraŸniej nie potrafisz otworzyæ tego zamka.}
{103}{}{Elektryczny system zabezpieczaj¹cy pora¿a ciê pr¹dem!}
{104}{}{Uruchamiasz alarm.}
{105}{}{Tê gródŸ blokuje mechaniczny zamek, który nale¿y otworzyæ.}
{106}{}{Elektryczny system zabezpieczaj¹cy zosta³ ju¿ wy³¹czony.}
{107}{}{Wy³¹czasz elektryczny system zabezpieczaj¹cy.}
