{100}{}{To drzwi windy oznaczone na niebiesko.}
{101}{}{System zabezpieczaj¹cy pora¿a ciê pr¹dem, lecz nie odnosisz obra¿eñ. Byæ mo¿e nale¿y go czymœ zdezaktywowaæ.}
{102}{}{System zabezpieczaj¹cy pora¿a ciê pr¹dem, przez co tracisz jeden punkt wytrzyma³oœci. Byæ mo¿e nale¿y go czymœ zdezaktywowaæ.}
{103}{}{System zabezpieczaj¹cy pora¿a ciê pr¹dem, przez co tracisz }
{104}{}{ PW. Byæ mo¿e nale¿y go czymœ zdezaktywowaæ.}
{105}{}{Wy³¹czasz system zabezpieczaj¹cy.}
{106}{}{Ten przedmiot jest tu bezu¿yteczny.}
