{100}{}{To Gunther.}
{101}{}{To powa¿nie usposobiony trzydziestokilkulatek.}
{102}{}{Witaj w moich skromnych progach. Co mogê dla ciebie zrobiæ?}
{103}{}{Czy móg³byœ opowiedzieæ mi co nieco o Hubie?}
{104}{}{Gdzie mogê tu znaleŸæ jak¹œ broñ i amunicjê?}
{105}{}{Co robisz w tym mieœcie?}
{106}{}{Kto tu stanowi prawo?}
{107}{}{Pewnie, co jeszcze chcesz wiedzieæ?}
{108}{}{To rozrastaj¹ce siê miasto, najwiêksze, jakie w ¿yciu widzia³em. Centrum le¿y na po³udnie st¹d, a pozosta³e dzielnice wyrastaj¹ z niego we wszystkich kierunkach.}
{109}{}{Gdzie mogê znaleŸæ zaopatrzenie?}
{110}{}{W razie szukania pracy, gdzie najlepiej zacz¹æ?}
{111}{}{Czy mogê ci zadaæ kolejne pytanie?}
{112}{}{Dziêki za informacje. Bywaj.}
{113}{}{Wszystko, czego potrzebujê, kupujê u Mitcha ko³o Soko³a Maltañskiego. Aby tam trafiæ, wystarczy skierowaæ siê st¹d na po³udnie.}
{114}{}{Ja od czasu do czasu zabieram siê jako stra¿nik z któr¹œ z karawan, które st¹d wyruszaj¹. Je¿eli szukasz takiej pracy, wystarczy, jak pogadasz w jednej z kompanii handlowych. Lubiê Wszêdobylskich Handlowców, ale pracowa³em dla nich wszystkich.}
{115}{}{Có¿, wiêkszoœæ mojego sprzêtu kupujê u Beth, w Sklepie z Broni¹. Ma ca³kiem niez³y wybór.}
{116}{}{Co zrobiæ, je¿eli szuka siê czegoœ nieco bardziej "egzotycznego"?}
{117}{}{Czy powo³anie siê na ciebie pomo¿e z cenami?}
{118}{}{S³ysza³em, ¿e na Starym Mieœcie jest jakiœ facet, który handluje zabawkami o trochê wiêkszym kopie.}
{119}{}{Chyba nie, ona robi maœlane oczy do swojego ochroniarza, Sida. Ale mo¿esz spróbowaæ z Butchem - on szefuje Wszêdobylskim Handlowcom, do których nale¿y jej sklep.}
{120}{}{Radzê sobie. Jak brakuje mi gotówki, wynajmujê siê jako stra¿nik przy karawanach albo trochê pracujê dla farmerów na po³udniu.}
{121}{}{Có¿, po drodze tutaj prawdopodobnie obejrza³ ciê sobie zastêpca Fry. Jego szefem jest szeryf Greene, którego zwykle mo¿na znaleŸæ na posterunku Policji.}
{122}{}{Ciaaassteeeczkooo!}
{123}{}{Przykro mi, ale gadasz od rzeczy. Mo¿e doktor Thorndyke ze szpitala Dzieci Katedry bêdzie w stanie ci pomóc.}
