{100}{}{To George, odŸwierny.}
{101}{}{Czy mogê ci w czymœ pomóc?}
# 102 "I want to see Mr. Hightower
{102}{}{Whant see mistur tower!}
{103}{}{Tak. Jestem tu, ¿eby siê zobaczyæ z panem Wie¿owcem.}
{104}{}{Mam umówione spotkanie z panem Wie¿owcem, a do tego spore spóŸnienie.}
{105}{}{Wpuœæ mnie do œrodka.}
{106}{}{Pan Wie¿owiec nie przyjmuje byle kogo.}
{107}{}{Có¿, on chce siê ze mn¹ widzieæ.}
{108}{}{Jak mo¿na siê umówiæ na spotkanie z nim?}
{109}{}{Nie jestem byle kim, ty idioto!}
{110}{}{A, trudno. ¯egnaj.}
{111}{}{Okay. Go on in.}
{112}{}{Znam wszystkich wspó³pracowników pana Wie¿owca, a ciebie nigdy wczeœniej nie widzia³em, wiêc lepiej st¹d odejdŸ. Natychmiast.}
{113}{}{O rany, to dopiero masz k³opoty! Pan W nie cierpi, jak opóŸniaj¹ mu siê spotkania. Niech sam siê na tobie wy¿yje. WchodŸ.}
{114}{}{Tam nie wejdziesz. Spadaj, ³achu!}
{115}{}{Nie chcê tu ¿adnych awantur, wiêc lepiej natychmiast odejdŸ.}
{116}{}{Sp³ywaj!}
{117}{}{Nie przejdziesz przez te drzwi.}
{118}{}{Po kiego diab³a siê tu skradasz?!? Ochrona!!!}
{119}{}{Zabieraj siê od tych drzwi! Nikt nie wejdzie do œrodka, nie za³atwiwszy siê najpierw ze mn¹!}
{120}{}{Masz wielki tupet, skoro tu przychodzisz! Ochrona!!}
