{100}{}{To Leon, ochroniarz Wie¿owca.}
{101}{}{W jakiej sprawie tu jesteœ?}
{102}{}{Muszê porozmawiaæ z panem Wie¿owcem.}
{103}{}{Przychodzê, ¿eby zabiæ pana Wie¿owca.}
{104}{}{A to twoja sprawa?}
{105}{}{OK. Ale mam ciê na oku. Jest w swoim gabinecie.}
{106}{}{Dziêkujê.}
{107}{}{Ta... Mogê siê za³o¿yæ, ¿e na mnie uwa¿asz.}
{108}{}{Nie podoba mi siê twoja postawa. Muszê ciê poprosiæ o wyjœcie.}
{109}{}{Wyjdê, kiedy mi siê bêdzie podoba³o, koleœ!}
{110}{}{OK, wychodzê.}
{111}{}{Postawa? Ja ci poka¿ê postawê!!!}
{112}{}{O cokolwiek chodzi, mo¿esz to powiedzieæ mi. Pan W jest akurat zajêty.}
{113}{}{Czemu musisz mi stwarzaæ problemy?}
{114}{}{Znacznie bardziej wolê przekazaæ mu to osobiœcie. To sprawa ¿ycia i œmierci.}
{115}{}{Kafar wystawi³ zlecenie na ¿ycie Wie¿owca.}
{116}{}{Mo¿esz powiedzieæ mi albo wyjœæ.}
{117}{}{Ktoœ umar³ i uczyni³ ciê Bogiem?}
{118}{}{Kafar wystawi³ zlecenie na ¿ycie Wie¿owca.}
{119}{}{S³uchaj, nie powiem ci ni cholery!}
{120}{}{Wychodzê.}
{121}{}{Znowu? Co za g³upiec z tego Kafara. Có¿... Chyba nie jest a¿ tak wielkim g³upcem, jak ci goœcie, których wynajmuje do tej roboty. Rzuæ tu okiem, obejrzyj sobie mojego gnata.}
{122}{}{[Leon demonstruje ci swoj¹ broñ, na której chwycie widnieje piêæ g³êbokich naciêæ.]}
{123}{}{Each one of these marks is for a past attempt on Hightower's life. I bagged each and every one of them. Tell me about this fool Decker hired... do you know what they look like?}
{124}{}{Nie.}
{125}{}{To ja, ty debilu!}
{126}{}{Hej! Ja pierdzielê! Masz naciêcia na spluwie! Jesteœ coooooool!}
{127}{}{Dziêkujê za ostrze¿enie, ale pan Wie¿owiec nie lubi, jak przesiaduj¹ tu obcy. Muszê ciê poprosiæ o wyjœcie.}
{128}{}{To wszystko? ¯adnej nagrody? Ludzie, co, do diab³a, jest z wami nie tak?}
{129}{}{Proszê bardzo. ¯egnaj.}
{130}{}{Pan Wie¿owiec nie przyjmuje ¿adnych goœci. Natychmiast st¹d odejdŸ!}
{131}{}{Wyjdê, kiedy mi siê bêdzie podoba³o, koleœ!}
{132}{}{OK, wychodzê.}
{133}{}{Naprawdê muszê porozmawiaæ z panem Wie¿owcem.}
{134}{}{Okay, buddy. Let's go. (He grabs you by the arm.)}
{135}{}{Zabieraj ode mnie te cholerne ³apska!}
{136}{}{W porz¹dku, w porz¹dku! Ju¿ idê.}
{137}{}{Zaczekaj! Nie da³eœ mi dokoñczyæ!}
{138}{}{Ug!}
{139}{}{Rukl!}
{140}{}{Mam piln¹ wiadomoœæ dla pana Wie¿owca.}
{141}{}{Co tu robisz? Teraz nie jestem na s³u¿bie. PójdŸ mêczyæ kogoœ innego.}
{142}{}{Mia³em nadziejê, ¿e twoje ¿a³osne dupsko kiedyœ siê tu zab³¹ka! Ochrona!}
