{100}{}{To Hubijczyk, stra¿nik.}
{101}{}{Czy mogê ci pomóc?}
{102}{}{Tak. Czy móg³byœ mi powiedzieæ, gdzie siê znajdujê?}
{103}{}{¯egnaj.}
{104}{}{Uhhhhhhh. Hu hu. Uhhhhh. Hu.}
{105}{}{Kurde, worek m³otków by³by od ciebie mniej têpy, nieprawda¿? Wynocha st¹d.}
{106}{}{Jesteœ na po³udniowym krañcu Hubu. Jak siê rozejrzysz, znajdziesz tu siedzibê Kupców Wodnych oraz szpitalik.}
{107}{}{Kim s¹ Kupcy Wodni?}
{108}{}{Szpital?}
{109}{}{Dziêkujê. Bywaj.}
{110}{}{To skurwiele. Myœl¹, ¿e s¹ w³aœcicielami ca³ego tego cholernego Hubu tylko dlatego, ¿e trzymaj¹ w garœci Wie¿ê Ciœnieñ.}
{111}{}{Szpital?}
{112}{}{Dziêkujê. Bywaj.}
{113}{}{Dzieci Katedry prowadz¹ tu, w Hubie, niewielki szpital. Wydaj¹ siê byæ przyzwoit¹ zgraj¹.}
{114}{}{Kim s¹ Kupcy Wodni?}
{115}{}{Dziêkujê. Bywaj.}
