{100}{}{To Irwin.}
{101}{}{O rany, nie mo¿esz mnie zostawiæ w spokoju?! Mam ju¿ na g³owie wystarczaj¹co du¿o problemów!}
{102}{}{Problemów? Mo¿e bêdê ci w stanie pomóc.}
{103}{}{Jakbyœ to tylko ty mia³ problemy.}
{104}{}{OK, OK. Nie ma powodu, ¿eby na wrzeszczeæ.}
{105}{}{Hmm... No, nie wiem. Potrzeba mi bohatera innego formatu, ni¿ twój. S³uchaj, wróæ tu, jak bêdziesz mieæ za pasem trochê wiêcej doœwiadczenia, OK?}
{106}{}{Wierz mi, to prawdziwa tragedia. Nic nie jest ju¿ takie, jak by³o. Mam ma³¹ farmê za miastem, a parê dni temu banda najeŸdŸców zjawi³a siê jak spod ziemi, i u¿ywa teraz mojego domostwa jako swojej bazy. Zabili Pugsley'a, mojego osio³ka, i zagrozili, ¿e mnie zabij¹, je¿eli kiedykolwiek spróbujê tam wróciæ.}
{107}{}{Powiedz mi tylko, gdzie to jest, a ja ju¿ zajmê siê reszt¹.}
{108}{}{Wybacz, Irwin, ale mam wa¿niejsze sprawy do za³atwienia.}
{109}{}{Naprawdê, zrobisz to? Wiesz, ja ju¿ nie œmiem tam chodziæ. Mo¿e ty tam pójdziesz, i dasz mi znaæ, jak ju¿ bêdê móg³ bezpiecznie wróciæ do domu?}
# 110 "beat it" means "leave"
{110}{}{S³uchaj, popaprañcu, ju¿ ci powiedzia³em, ¿e masz mi daæ spokój. Teraz spadaj!}
{111}{}{Wiedzia³em, ¿e stchórzysz. Ka¿dy tak robi, kiedy chodzi o najeŸdŸców.}
{112}{}{No, to uda³o ci siê daæ nauczkê tym najeŸdŸcom? Czy mój dom jest ju¿ znowu bezpieczny?}
{113}{}{Jasne, ¿e tak, kolego.}
{114}{}{Na razie brakuje mi czasu, ¿eby siê tym zaj¹æ.}
{115}{}{Oh, thank you so much. I am sorry I don't have any riches to give to you, but here, take this for saving my home. It was my father's, passed down to him from Grandpa Rick. You probably need it more than I do.}
{116}{}{Próbujesz mnie wystrychn¹æ na dudka, prawda? Proszê, nie igraj ze mn¹. Wróæ, i daj mi znaæ, jak ju¿ naprawdê bêdê móg³ bezpiecznie wróciæ do mojego domu, dobrze?}
{117}{}{Naprawdê, bardzo ci dziêkujê za pomoc.}

# Nimrod
{122}{}{You earn 500 experience for saving Irwin's farm.}

#for Stupid characters
{118}{}{Grunk?}
{119}{}{S³uchaj, nie mam czasu na gadanie z debilami. Wróæ, jak bêdziesz mieæ trochê oleju w g³owie.}
{120}{}{Uh huh, uh huh, uh huh. I dood it.}
{121}{}{Ja jeszcza nie za³atwiæ.}
{123}{}{No find farm. You show?}
{403}{}{Tank yoo!}

# the Raiders at his farm
{300}{}{IdŸ na spotkanie ze Stwórc¹!}
{301}{}{Braæ go... trupem!}
{302}{}{To by³a ju¿ twoja ostatnia bu³ka z serem!}
{303}{}{Podziurawiê ciê jak jakiœ szwajcarski ser!}

# Sduibek
{400}{}{Not quite. Could you tell me again how to get there?}
{401}{}{I will, but please hurry. I want to go back to my home.}
{402}{}{Thanks.}
