{100}{}{To chudy, gniewny mê¿czyzna.}
{101}{}{To Ismarc.}
{102}{}{Czego?}
{103}{}{Ta, czego chcesz?}
{104}{}{Hej, dobrze œpiewasz.}
{105}{}{Od twojego wycia popêka³y mi bêbenki w uszach.}
{106}{}{Niewa¿ne.}
{107}{}{Hoo!}
{108}{}{Och, wspaniale. Nawet nie wiesz, jaki jestem dziêki temu zadowolony. Sp³ywaj.}
{109}{}{Dziêki. Co mogê dla ciebie zrobiæ?}
{110}{}{Do you perform anywhere else?}
{111}{}{¯e tak powiem, nasz³a mnie ochota, by trochê sypn¹æ groszem.}
{112}{}{Gdzie nauczy³eœ siê œpiewaæ?}
{113}{}{Dziêki za rozmowê.}
{114}{}{Co?!? Nie mam na to czasu.}
{115}{}{Ta, œpiewam czasem w Hubie, i odwiedzi³em z karawanami Bractwo Stali i Adytum. Czemu pytasz?}
{116}{}{Czy mo¿esz mi powiedzieæ, jak dotrzeæ do Hubu?}
{117}{}{Muszê wiedzieæ, jak dotrzeæ do Bractwa.}
{118}{}{Jak dotrzeæ do Adytum?}
{119}{}{Eee, niewa¿ne, dziêki.}
{120}{}{Do Hubu? O, to tylko krótka przechadzka na po³udnie od Z³omowa. Jeszcze coœ?}
{121}{}{Cytadela Bractwa jest o parê dni na zachód i kapkê na pó³noc st¹d. Nie wybieraj siê tam jednak. Nie wpuszcz¹ ciê, je¿eli nie przyjdziesz z karawan¹. Potrzebujesz jeszcze czegoœ?}
{122}{}{Hmm. Skieruj siê na po³udniowy zachód od Hubu. Adytum jest czêœci¹ Gruzów. To ma³a, wpó³przemys³owa osada. Niezbyt mi siê tam podoba³o. Chcesz jeszcze czegoœ?}
{123}{}{Hej, dziêki. Ciê¿ko byæ przymieraj¹cym g³odem artyst¹. Jeœli tylko chcesz siê czegoœ dowiedzieæ, pytaj œmia³o.}
{124}{}{Doceniam troskê, i w ogóle, ale ciebie sp³uka³o jeszcze gorzej ode mnie.}
{125}{}{A, pod³apa³em to tu i ówdzie. Nauczy³em siê odrobinê od "Dwucalowego Wkrêta" Reznora, starego piosenkarza, w Hubie i dosta³em trochê tekstów od szabrowników w Adytum, w Gruzach. Wiesz, to wymaga tylko trochê praktyki.}
{126}{}{Mê¿czyzna w k¹cie pomieszczenia œpiewa chrypliwym g³osem.}
{127}{}{Twój ³eb to kula!}
{128}{}{Kr¹g³y jest jak rura!}
{129}{}{Prêdzej ju¿ sp³onê!}
{130}{}{Ni¿ przed tob¹ ugnê siê!}
{131}{}{Ja twój umys³ znam}
{132}{}{To stalowa klatka}
{133}{}{Wewn¹trz szaleje...}
{134}{}{Œmierci Szpon!}
{135}{}{Potrzebujê ciê}
{136}{}{Jak dawki trucizny!}
{137}{}{Potrzebujê ciê}
{138}{}{Jak jadu skorpiona!}
