{100}{}{To m³ody mê¿czyzna o ostrych rysach.}
{101}{}{To Jason Zimmerman.}
{102}{}{Hej, jesteœ naprawdê z bardzo daleka? Uda³o ci siê prze¿yæ masê przygód?}
{103}{}{Tak, pochodzê z Krypty daleko na pó³nocy.}
{104}{}{Jeœli chodzi o œcis³oœæ, jestem z Marsa. Chcesz obejrzeæ moj¹ ogniolancê?}
{105}{}{Przydarzy³o mi siê trochê przygód.}
{106}{}{Tak znowu wiele nie zdarzy³o mi siê dokonaæ, naprawdê.}
{107}{}{Eee, daleko. Krypta.}
{108}{}{Ach. Myœla³em, ¿e ktoœ, kto przewêdrowa³ pustkowia poza osad¹, bêdzie, có¿, bystrzejszy. Niewa¿ne.}
{109}{}{Miles mówi, ¿e teraz, jak uda³o ci siê zdobyæ te czêœci, jest w stanie uruchomiæ farmy, ¿ebyœmy nie musieli sprzedawaæ nabojów Hubowi. Nigdy siê tym szczególnie nie przejmowa³em, dopóki Smitty mi nie uœwiadomi³, ¿e naboje, które robi, s¹ }
{110}{}{sprzedawane Hubowi, który sprzedaje je gangom. Myœlê, ¿e uda³o ci siê znaleŸæ dobre rozwi¹zanie.}
{111}{}{Nigdy nie s¹dzi³em, ¿e bêdziemy mogli przestaæ walczyæ z gangami. Ojciec opowiedzia³ mi, jak ci siê uda³o sprawiæ, ¿e obiecali zostawiæ nas w spokoju. Wiesz, zawsze myœla³em, ¿e chcê wyruszyæ na poszukiwanie przygód, ale chyba lubiê... có¿, to }
{112}{}{poczucie bezpieczeñstwa, które tu teraz panuje. Nie trzeba siê ju¿ martwiæ, ¿e gangi nagle zaatakuj¹, i zastanawiaæ siê, kto zginie.}
{113}{}{Lorraine mówi³a, ¿e na po³udnie st¹d by³a Krypta, w której mieszka³a masa moich dziadków. Jak to jest mieszkaæ w Krypcie?}
{114}{}{To tak naprawdê ca³kiem nudne.}
{115}{}{To bardzo ekscytuj¹ce. Mamy wszelkiego rodzaju technologie, w jakie byœ nie uwierzy³!}
{116}{}{Aha. Có¿, ale po wyjœciu stamt¹d na pewno przydarzy³o ci siê trochê przygód, prawda?}
{117}{}{Nie za bardzo.}
{118}{}{Tak, na pustkowiach jest ca³kiem sporo niebezpieczeñstw.}
{119}{}{Jak ktoœ kiedyœ napisa³, "Przygoda jest wtedy, gdy bardzo daleko ktoœ inny ma spore k³opoty".}
{120}{}{Hê. Kupcy z Hubu mówi¹ o radskorpionach i ró¿nych takich.}
{121}{}{W rzeczywistoœci na zewn¹trz jest niemal wy³¹cznie tylko pustynia.}
{122}{}{Có¿, faktycznie, to na zewn¹trz s¹ wszelkiego rodzaju potwory.}
{123}{}{Naprawdê? Jakie potwory uda³o ci siê pokonaæ?}
{124}{}{Niewiele, tylko trochê szczurów i tym podobnych.}
{125}{}{Ta, stra¿nicy z Hubu mówili, ¿e na pustyni ¿yje masa napromieniowanych, zmutowanych stworów. Polowanie na potwory musi byæ naprawdê czaderskie!}
{126}{}{Tak, to prawdziwy odjazd!}
{127}{}{Nie, to raczej bolesne. Jad, ugryzienia, promieniowanie... To zabójcza robota.}
{128}{}{Chcia³bym móc kiedyœ wyruszyæ na poszukiwanie przygód.}
{129}{}{Nigdy o tym nie myœla³em. Ca³kiem lubiê mieæ czyst¹ wodê i k¹t do spania.}
{130}{}{S¹dzi³em, ¿e ¿ycie na pustkowiu jest... no wiesz... twarde i niebezpieczne, i w ogóle. Ale wydaje mi siê, ¿e mamy tutaj wystarczaj¹co du¿o roboty, z gangami i w ogóle.}
{131}{}{Co, jesteœ jakimœ zboczkiem, czy co? Caleb nigdy nie powinien by³ ciê wpuœciæ za bramê!}
{132}{}{Zajebiœcie. Wszystko, co mamy tutaj, to ta durna studnia i te podziemne farmy, które Miles ci¹gle próbuje uruchomiæ.}
{133}{}{Ta, zauwa¿y³em, ¿e nie masz œpiwora, ani niczego takiego. Tam, na zewn¹trz, musi byæ totalnie brudno i niewygodnie.}
{134}{}{Witaj ponownie. Masz jakieœ ciekawe historie do opowiedzenia?}
{135}{}{O czym chcesz wiedzieæ?}
{136}{}{Raczej nie.}
{137}{}{No, jeœli zrobisz cokolwiek ciekawego, opowiedz mi o tym wszystko!}
{138}{}{Daj mi spokój!}
{139}{}{Bogu dziêki, ¿e tu jesteœ! Proszê, pomó¿ mi siê st¹d wydostaæ!}
{140}{}{Ayuh.}
{141}{}{Nie martw siê, wydostanê nas st¹d.}
{142}{}{Wybacz, dzieciaku, radŸ sobie sam!}
{143}{}{Co tu robisz?}
{144}{}{Dziêkujê!}
{145}{}{Proszê, nie zostawiaj mnie!}
{146}{}{Myœla³em, ¿e bêdzie fajnie zostawiæ Adytum i poznawaæ œwiat. Ale Rozpruwacze mnie z³apali i trzymaj¹ mnie tutaj. Proszê, pomó¿ mi!}
{147}{}{W porz¹dku, zje¿d¿ajmy st¹d!}
{148}{}{Mowy nie ma. Ty siê w to wpakowa³eœ, ty siê z tego wydostañ.}
{149}{}{Mam nadziejê, ¿e siê st¹d zaraz zmyjemy!}
