{100}{}{To podró¿nik.}
{101}{}{Czego chcesz?}
{102}{}{Kim jesteœ?}
{103}{}{Co robisz na tym pustkowiu?}
{104}{}{Jaka osada le¿y najbli¿ej?}
{105}{}{Nic, dziêki.}
{106}{}{Uhh...}
{107}{}{Jestem zwiadowc¹ ze Z³omowa.}
{108}{}{Wypatrujê najeŸdŸców i potworów.}
{109}{}{To bêdzie Z³omowo. Jest niedaleko st¹d, w tym kierunku.}
{110}{}{To Stra¿nik Z³omowa.}
