{100}{}{To najeŸdŸca, który wydaje siê byæ oszala³y.}
{101}{}{Starczy! Nie podchodŸ ani kroku bli¿ej. Skasujê j¹. Przysiêgam.}
{102}{}{Nung!}
{103}{}{Nie rób tego!}
{104}{}{Zabijê ciê, jak jej nie puœcisz.}
{105}{}{Nie ma potrzeby stosowaæ przemocy. Porozmawiajmy o tym.}
{106}{}{Co? Ty zwyczajnie chcesz mnie zabiæ, prawda? Tylko pamiêtaj, to twoja wina.}
{107}{}{A dlaczego nie? To zwyk³a kurwa.}
{108}{}{Ona ma takie samo prawo do ¿ycia, jak ty.}
{109}{}{Nie. Mowy nie ma. Nie ta dziwka.}
{110}{}{Na jakim ty œwiecie ¿yjesz? Tutaj, w prawdziwym œwiecie, p³ynie krew. Krew p³ynie, i rozbryzga siê po tym ca³ym pokoju, jak siê st¹d nie wyniesiesz.}
{111}{}{Mo¿emy to omówiæ. Co mogê zrobiæ, ¿eby ci pomóc?}
{112}{}{OK, OK. Wycofujê siê. Nie musisz siê mn¹ przejmowaæ.}
{113}{}{Jezu, to zabawne. Kto mówi, ¿e potrzebujê pomocy?}
{114}{}{Ty. Trzymaj¹c tê kobietê jako zak³adnika, prosisz o pomoc. Ja mogê pomóc.}
{115}{}{Muszê nad tym pomyœleæ. Poczekaj chwilê.}
{116}{}{Ta. Nie próbuj ¿adnych numerów, albo ona dostanie.}
{117}{}{facet}
{118}{}{kobieta}
{119}{}{OK, szefuniu. Zobaczmy, jak siê postarasz. Ale najpierw...}
{120}{}{OK, szefowo. Zobaczmy, jak siê postarasz. Ale najpierw...}
{121}{}{Trzymaj siê z dala... Nie chcê jej skrzywdziæ, ale to zrobiê.}
{122}{}{Nie rób tego, albo zmusisz mnie do skrzywdzenia ciebie.}
{123}{}{Czemu chcesz jej zrobiæ krzywdê?}
{124}{}{Spróbuj, a najpierw ona umrze. To co mówisz?}
{125}{}{Trudno ci bêdzie zrobiæ jej krzywdê z t¹ dziur¹ w twoim ³bie.}
{126}{}{OK, ale musisz do mnie ci¹gle mówiæ.}
{127}{}{Jak¹ dziur¹?}
{128}{}{T¹, któr¹ zaraz tam zrobiê.}
{129}{}{Bêdê gada³, dopóki ty bêdziesz gadaæ, ale jak spróbujesz jakiejœ sztuczki, to ona za to oberwie.}
{130}{}{Nic nie muszê. Ty musisz to robiæ, a nie idzie ci to szczególnie wdechowo.}
{131}{}{Wyœmia³a mnie. One wszystkie mnie wyœmiewa³y. Zap³ac¹ za to, przysiêgam.}
{132}{}{Wierzê ci. Popracujmy nad tym, OK?}
{133}{}{Mo¿e. Nie wim.}
{134}{}{goœæ}
{135}{}{dziewucha}
{136}{}{Robisz wra¿enie porz¹dnego goœcia. Nikt wczeœniej nie próbowa³ mi nigdy pomóc. Chyba mo¿emy jeszcze trochê porozmawiaæ.}
{137}{}{Robisz wra¿enie porz¹dnej dziewuchy. Nikt wczeœniej nie próbowa³ mi nigdy pomóc. Chyba mo¿emy jeszcze trochê porozmawiaæ.}
{138}{}{Zwyczajnie daj mi spokój. Nienawidzê ciê! Jesteœ szatanem. Nie bêdê ciê s³uchaæ.}
{139}{}{Niech bêdzie po twojemu.}
{140}{}{Musisz mnie wys³uchaæ. Zale¿y od tego twoje ¿ycie, i ¿ycie tej dziewczyny.}
{141}{}{Po prostu siê uspokój. Nie zrobiê ci krzywdy. Chcê tylko pos³uchaæ tego, co masz do powiedzenia.}
{142}{}{Znowu zaczynasz, grozisz mi. Giñ!!}
{143}{}{Nie bêdê ciê s³uchaæ. Oszukasz mnie tylko twoimi s³ówkami. Nie wierzê ci. IdŸ sobie.}
{144}{}{Mo¿esz mieæ racjê. Udowodnij mi to.}
{145}{}{I co teraz?}
{146}{}{Ty mi to powiedz. Ty jesteœ szefem.}
{147}{}{Chcê trochê forsy, i chcê st¹d spokojnie odejœæ. Nikt ma za mn¹ nie iœæ.}
{148}{}{Niestety, nie mo¿emy tak zrobiæ.}
{149}{}{Jasne.}
{150}{}{¯adnych pieniêdzy, ale mo¿esz st¹d zwyczajnie odejœæ. Nikt nic nie zrobi. Obiecujê.}
{151}{}{OK, ale musisz najpierw puœciæ dziewczynê. Oka¿ mi trochê zaufania, to ja zaufam tobie.}
{152}{}{Wciskasz mi kit!}
{153}{}{OK. Chcê 100 kapsli. Wtedy st¹d wyjdziemy. Niech nikt za mn¹ nie idzie, to j¹ puszczê, kiedy dotrzemy do skraju osady.}
{154}{}{Oto twoje pieni¹dze.}
{155}{}{Nie mam przy sobie takiej gotówki.}
{156}{}{No to chyba ona dostanie.}
{157}{}{To chyba OK.}
{158}{}{Nie podoba mi siê to. Co ciê powstrzyma przed strzeleniem mi w plecy, kiedy bêdê st¹d wychodzi³?}
{159}{}{Nie zastrzelê ciê. Zaufaj mi.}
{160}{}{Nic, musisz po prostu wierzyæ w to, co mówiê.}
{161}{}{Mowy nie ma! Nie ufam ci!}
{162}{}{W porz¹dku. Zobaczymy, co siê stanie, nieprawda¿?}
{163}{}{Oto 100 kapsli. ¯yczê ci dobrego dnia.}
{164}{}{Mo¿esz spokojnie odejœæ.}
{165}{}{Chcê moj¹ kasê. Chcê 200 kapsli.}
{166}{}{Nie mam tyle pieniêdzy.}
{167}{}{Proszê bardzo.}
{168}{}{Wygl¹dasz mi na ³garza i oszusta.}
{169}{}{To wzajemne odczucie, kolego. Puœæ dziewczynê.}
{170}{}{facet}
{171}{}{kobieta}
{172}{}{Czemu nie uweŸmiesz siê na mnie, zamiast na ni¹? Przekonaj siê, co potrafi prawdziwy mê¿czyzna.}
{173}{}{Czemu nie uweŸmiesz siê na mnie, zamiast na ni¹? Przekonaj siê, co potrafi prawdziwa kobieta.}
{174}{}{Nie! Nie mów mi, co mam robiæ! Nie mo¿esz mi mówiæ, co mam robiæ!}
{175}{}{Ta, ja ci poka¿ê.}
{176}{}{Twoje gadanie w³aœnie kosztowa³o tê kurwê jej ¿ycie!}
{177}{}{Daj mi spokój, do cholery!}
{178}{}{NajeŸdŸca, poch³oniêty swoj¹ spraw¹, ignoruje ciê.}
{179}{}{Hmmm...}
{180}{}{Hej, pobaraszkujmy, dziecinko. Mam gotówkê, jeœli ty masz czas.}
{181}{}{Nie gadaj tak do mnie, suko! Nikt tak do mnie nie bêdzie gadaæ!}
{182}{}{To w³aœnie kosztowa³o ciê twoje ¿ycie!}
{183}{}{Twój precyzyjnie wymierzony cios pozbawia najeŸdŸcê przytomnoœci. Pada on jak szmaciana lalka.}
{184}{}{Mo¿e uda ci siê zakraœæ za plecy najeŸdŸcy, jeœli zachowasz ostro¿noœæ.}
