{100}{}{Unosisz pokrywê studzienki i opuszczasz ociekaj¹ce wilgoci¹ kana³y œciekowe.}
{101}{}{Próbuj¹c unieœæ pokrywê studzienki nadwerê¿asz sobie bark, a nastêpnie zeœlizgujesz siê z drabinki.}
{102}{}{Nie jesteœ w stanie podwa¿yæ pokrywy studzienki.}
{103}{}{Nieomal zeœlizgujesz siê z drabinki.}
{104}{}{Spadasz z drabinki.}
