{100}{}{To Lemmy, podejrzanie wygl¹daj¹cy osobnik.}
{101}{}{Pssst! Cho no tu.}
{102}{}{No, to co robiasz w Hubie?}
{103}{}{Naprawdê nie wiem, czemu by to mia³o ciê interesowaæ.}
{104}{}{A co?}
{105}{}{Szukam czegoœ, co jest mi potrzebne.}
{106}{}{Ty moja Mamuœ?!?}
{107}{}{Niezupe³nie, dr¹galu. Do rych³ego.}
{108}{}{Aach.}
{109}{}{Spoko, po co zaraz te nerwy? Tylko sprawdzam, czy mogem byæ pomocny. [Lemmy odwraca siê od ciebie.]}
{110}{}{Có¿, wygl¹dasz na cz³owieka interesu. I ja jestem cz³owiekiem interesu, no i pomyœla³em, ¿e moglibyœmy, e, przedyskutowaæ, e, interes.}
{111}{}{No, a czym siê tutaj zajmujesz?}
{112}{}{Chyba ci zaraz zafundujê recesjê!}
{113}{}{Raczej nie odczuwam ochoty, by mieæ cokolwiek do czynienia z twoim "interesem".}
{114}{}{Có¿, wszyscy mamy potrzeby. Mogem byæ ci w stanie pomóc z niektórymi. To jakie masz potrzeby?}
{115}{}{No, faktycznie, to szukam hydroprocesora. Muszê go zdobyæ dla mojego ludu.}
{116}{}{Potrzeby, co? Mam œwiadomoœæ potrzeb, ale co ty mo¿esz wiedzieæ o ich zaspokajaniu?}
{117}{}{Potrzebujê pewnych informacji.}
{118}{}{Na pewno nie potrzebujê niczego, co móg³byœ mieæ na myœli.}
{119}{}{Robiê odrobinê tego i odrobinê tamtego. Zdobywam dla ludzi rzeczy i informacje, wszystko, czego mogom potrzebowaæ albo szukaæ.}
{120}{}{No có¿, faktycznie potrzebujê paru rzeczy.}
{121}{}{O czym konkretnie mo¿esz mi coœ powiedzieæ?}
{122}{}{Szukam hydroprocesora. Nie masz go przypadkiem, prawda?}
{123}{}{Spotkamy siê jeszcze.}
{124}{}{Hydroprocesor, hmmmm. Chyba nie s³ysza³em o czymœ takim. Jakbym by³ tobom, to bym spróbowa³ u Kupców Wodnych. Trzymaj¹ ³apê na ca³ej wodzie w okolicy.}
{125}{}{No to czym siê tutaj zajmujesz?}
{126}{}{No to o czym jeszcze mo¿esz wiedzieæ?}
{127}{}{Dziêki za informacje.}
{128}{}{¯aden problem. Jak bêdzie jeszcze coœ, czego mo¿esz chcieæ, w pierwszej kolejnoœci przyjdŸ pogadaæ z Lemmy'm.}
{129}{}{No, to szukasz informacji, co? Bêd¹c szacownym biznesmenem, mam koszty sta³e, wienc bêdê potrzebowa³ paru kapsli, ¿eby ci powiedzieæ to, co chcesz wiedzieæ. Jak ju¿ to sobie wyjaœniliœmy, to o czym ci trzeba wiedzieæ?}
{130}{}{No, to myœlisz, ¿e mogem wiedzieæ trochê wiêcej o tych jakichœ hydroprocesorach, co? Có¿, mo¿esz mieæ racjê. Bêdzie ciê to jednak kosztowaæ. Myœlê, ¿e 500 kapsli powinno wystarczyæ.}
{131}{}{W porz¹dku, co wiesz?}
{132}{}{Dam ci zamiast tego 400.}
{133}{}{Myœlê, ¿e musisz mi to powiedzieæ natychmiast, i to bez tych pierdolonych kapsli!}
{134}{}{To za wysokie progi, jak na moje nogi.}
{135}{}{No, no. Nie by³bym tym, kim jestem, gdybym rozdawa³ informacje poni¿ej ich wartoœci. Wróæ, jak zdobêdziesz te kapsle.}
{136}{}{Próbujemy zastraszyæ starego, biednego Lemmy'ego, co? No có¿, nie bojê siê takich jak ty. Jeszcze siê zobaczymy, i tyle.}
{137}{}{[Lemmy bierze twoje pieni¹dze.]}
{138}{}{Có¿, ujdzie. Niech bêdzie moja strata.}
{139}{}{OK, OK, OK, widzisz, ja tylko ¿artowa³em z tym p³aceniem za informacje. Niez³y kawa³, co?}
{140}{}{Dobra, oto co wiem o hydroprocesorach. To, co s³ysza³em, to to, ¿e one wszystkie pochodz¹ z Krypt. Wienc jak bym takiego szuka³, to bym siê dowiedzia³, gdzie by³a reszta tych Krypt. Nie jestem pewny, gdzie dok³adnie s¹ te wszystkie Krypty, ale podobno jest ich gdzieœ w tej okolicy oko³o czterech.}
{141}{}{Chcê ci zadaæ jeszcze kilka pytañ.}
{142}{}{Dziêki.}
{143}{}{Jasne, o czym jeszcze chcesz wiedzieæ?}
{144}{}{Wiesz coœ o hydroprocesorach, co móg³byœ mi powiedzieæ?}
{145}{}{Co wiesz o Kafarze?}
{146}{}{Czy wiesz coœ o zaginionych karawanach?}
{147}{}{Có¿, szukam pewnego towaru, jeœli wiesz, co mam na myœli.}
{148}{}{Nie teraz.}
{149}{}{No, normalnie nie mam nic przeciwko sprzedawaniu informacji, lecz na temat pana Kafara nie wyci¹gniesz z Lemmy'ego ani s³owa.}
{150}{}{OK, ale mogê ciê wypytaæ o parê innych rzeczy?}
{151}{}{Dziêki.}
{152}{}{Zaginionych karawanach, co? No có¿, móg³bym cosik o nich wiedzieæ. Bêdzie ciê to jednak kosztowa³o 300 kapsli.}
{153}{}{W porz¹dku, co wiesz?}
{154}{}{Dam ci 240.}
{155}{}{Myœlê, ¿e musisz mi to powiedzieæ natychmiast, i to bez tych pierdolonych kapsli!}
{156}{}{To za wysokie progi, jak na moje nogi.}
{157}{}{Có¿, nie jestem tak naprawdê pewny, ale to, co s³ysza³em, to to, ¿e to nie to, o czym wszyscy myœl¹. Jakiœ nowy goœciu wkracza na scenê z jakimiœ mutantami, czy czymœ takim. Ale nie powo³uj siê na mnie w tej sprawie.}
{158}{}{Pasuje to do ciebie. Czy w ogóle istnieje coœ, przy czym mo¿na siê na ciebie powo³aæ, Lemmy?}
{159}{}{Czy mogê ci zadaæ kolejne pytanie?}
{160}{}{Dziêki.}
{161}{}{Co, mo¿e insynuujesz, ¿e Lemmy nie jest odwa¿nym goœciem? Có¿, masz racjê. Ale Lemmy zalicza siê do ¯YWYCH goœci.}
{162}{}{OK, zapomnij o tym. Czy mogê ci zadaæ kolejne pytanie?}
{163}{}{No có¿, zamierzam zrobiæ z ciebie goœcia zaliczaj¹cego siê do le¿¹cych i nieoddychaj¹cych!}
{164}{}{Zapomnij o tym. Siema.}
{165}{}{To towar pierwszej potrzeby, co? No có¿, znam goœcia na Starówce, który pewnie mo¿e ci za³atwiæ trochê takiego towaru. Ale wiesz co? On musi wiedzieæ, kim jesteœ, zanim mu siê zjawisz na progu.}
{166}{}{Niech zgadnê. "Zaproszenie" do niego bêdzie mnie "kosztowaæ"?}
{167}{}{Widzê, dok¹d to zmierza. Znajdê go na w³asn¹ rêkê.}
{168}{}{W samej rzeczy. No wienc myœlê... oczywiœcie to tylko dla ciebie, po znajomoœci... 1000 kapsli, to ten goœæ pogada z tob¹, zamiast ci od razu rozwalaæ ³eb.}
{169}{}{W porz¹dku, zap³acê twoj¹ cenê.}
{170}{}{A mo¿e zamiast tego 800 kapsli?}
{171}{}{Poniewa¿ tak bardzo mnie lubisz, Lemmy, to mo¿e byœ to po prostu zrobi³ za darmo? [Mówisz, jednoczeœnie prê¿¹c miêœnie.]}
{172}{}{Nie staæ mnie.}
{173}{}{Có¿, to, co musisz zrobiæ, to znaleŸæ drogê na Starówkê. Jest tam goœæ imieniem Vance. Zwyczajnie z nim pogadaj. Jak powiedzia³em, dam mu znaæ, ¿e do niego idziesz.}
{174}{}{Jesteœ dusza-cz³owiek. Mogê ciê spytaæ o jeszcze kilka spraw?}
{175}{}{Dziêki.}
{176}{}{Wybacz, mam sprawy do za³atwienia. Choæ mi³o siê z tob¹ gawêdzi.}
{177}{}{No có¿, wracasz, ¿eby pogadaæ z twoim starym przyjacielem Lemmy'm, co? W czym to mogem ci pomóc?}
{178}{}{Có¿, wygl¹dasz na kobietê interesu. I ja siedzê w interesach, no to pomyœla³em, ¿e moglibyœmy, e, przedyskutowaæ, e, interes.}
