{100}{}{To m³oda kobieta o ciemnych w³osach.}
{101}{}{To Lorraine, szabrowniczka z Adytum.}
{102}{}{Czeœæ. Jesteœ tu pierwszy raz?}
{103}{}{Ta. Mo¿esz mnie nieco wprowadziæ w lokalne sprawy?}
{104}{}{Tak, owszem. Nazywam siê }
{105}{}{. }
{106}{}{Ktooo?}
{107}{}{Tak myœlê. O czym chcesz wiedzieæ?}
{108}{}{Kim jesteœ?}
{109}{}{Mo¿esz mi podaæ trochê informacji o Gruzach?}
{110}{}{Opowiedz mi trochê o pozosta³ych mieszkañcach Adytum.}
{111}{}{Z czego siê utrzymujesz?}
{112}{}{Niewa¿ne, dziêki.}
{113}{}{Jestem Lorraine.}
{114}{}{Mogê ci zadaæ kilka pytañ?}
{115}{}{Jestem szabrowniczk¹. Z Sammaelem zbieramy w ruinach rzeczy, które mo¿emy wykorzystaæ do budowy albo na handel.}
{116}{}{Czemu wszyscy tutaj siê tym nie zajmuj¹?}
{117}{}{Ilu jest tu szabrowników?}
{118}{}{Czy mogê ciê spytaæ o coœ innego?}
{119}{}{Mi³o siê z tob¹ rozmawia³o.}
{120}{}{No có¿, tam, na zewn¹trz, s¹ Szpony Œmierci, a dodatkowo Regulatorzy pobieraj¹ z góry pewn¹ kwotê, plus jeszcze trochê za ochronê tu, w Adytum. Pewnie ludzie nie maj¹ wolnej gotówki, albo jaj, ¿eby siê gapiæ Szponom Œmierci w oczy.}
{121}{}{O co chodzi z Regulatorami?}
{122}{}{W jaki sposób unikacie Szponów Œmierci?}
{123}{}{Mogê ciê spytaæ o parê innych spraw?}
{124}{}{Dziêki. Czeœæ.}
{125}{}{A, jest nas pó³ tuzina. Sammael by³ pierwszy, i ci¹gle jest najlepszy.}
{126}{}{Mogê ciê spytaæ o parê innych spraw?}
{127}{}{Ciekawa sprawa. Dziêki.}
{128}{}{Utrzymuj¹ spokój w okolicy i kontroluj¹ wszelkie przep³ywy pieniêdzy do i z Adytum. Reszta tutejszej ludnoœci pracuje prawie tylko na nich, a to nie jest najl¿ejsza robota. Wielu tutejszych nigdy nie by³o za siatk¹, która otacza to miejsce.}
{129}{}{Naprawdê nie wiem, co tej Juliannie strzeli³o do g³owy.}
{130}{}{O co chodzi z Juliann¹?}
{131}{}{To bardzo wredne. Czy mogê ciê spytaæ o parê innych rzeczy?}
{132}{}{Dziêki za ostrze¿enie.}
{133}{}{Ach, zakocha³a siê jakiœ czas temu w pewnym Ostrzu. Biedactwo oczywiœcie nie mo¿e opuœciæ osady, a Caleb zastrzeli³by tego m³odzieñca na sam jego widok.}
{134}{}{Ee... Skoro tak twierdzisz.}
{135}{}{Czy mogê ci zadaæ parê innych pytañ?}
{136}{}{Hmm. Dziêki za informacje. Czeœæ.}
{137}{}{Szabrujemy tylko po zmroku. I jesteœmy bardzo dobrzy w tym, co robimy. Sammael ma ma³y sprawdzian, któremu lubi poddawaæ ludzi, zanim pozwoli im zostaæ szabrownikami.}
{138}{}{Co to za sprawdzian?}
{139}{}{I tak brzmi to niebezpiecznie.}
{140}{}{Rozumiem. Mo¿emy siê trochê cofn¹æ?}
{141}{}{Ciekawe. Czeœæ}
{142}{}{Sammael ka¿e tej osobie schowaæ siê gdzieœ w Adytum za dnia. Jeœli nie mo¿e znaleŸæ delikwenta w ci¹gu godziny, to pozwala mu wzi¹æ udzia³ w najbli¿szym szabrowaniu.}
{143}{}{Co za g³upi system!}
{144}{}{Wygl¹da na to, ¿e to siê sprawdza. Ci¹gle ¿yjesz.}
{145}{}{Aha. Czy mogê ciê spytaæ o parê innych rzeczy?}
{146}{}{Ciekawe. Czeœæ.}
{147}{}{Daj spokój, czy nie ma w tobie za grosz romantyzmu? Naprawdê, to takie smutne. Niespe³niona mi³oœæ i w ogóle. Tragiczne.}
{148}{}{Pfff. Widaæ, co wiesz o ¿yciu. Powiedz to Sammaelowi. Je¿eli zdo³asz go znaleŸæ.}
{149}{}{Tak, chocia¿ czasem mo¿e byæ ciê¿ko. To bardzo niebezpieczne, zw³aszcza jak ciê nakryj¹.}
{150}{}{Bez w¹tpienia. Czy mogê ciê spytaæ o coœ innego?}
{151}{}{Dziêki za informacje.}
{152}{}{O rany, wydaje mi siê, ¿e udzielenie ci pomocy le¿y odrobinê poza zasiêgiem moich mo¿liwoœci.}
{153}{}{To by³o kiedyœ wielkie miasto, zwane Los Angeles. Ale bomby uderzy³y naprawdê mocno. Teraz s¹ tu tylko Gruzy. My, mieszkañcy Adytum, staramy siê po prostu prze¿yæ w ruinach.}
{154}{}{Czy mo¿esz mi powiedzieæ coœ wiêcej o Los Angeles?}
{155}{}{Rozumiem. Dziêki.}
{156}{}{Mnóstwo ludzi tutaj mieszka³o. Z tego co s³ysza³em, ci, co prze¿yli, byli schowani w wielkim schronie zwanym Krypt¹, i wyszli stamt¹d po wielu latach. Niektórzy z nich sformowali Regulatorów, a potem za³o¿yli Adytum, podczas gdy}
{157}{}{ pozostali utworzyli Ostrza. Zbrojeniowcy nie s¹ od pocz¹tku tutejsi.}
{158}{}{Gdzie jest ta Krypta?}
{159}{}{O co chodzi z Regulatorami.}
{160}{}{Sk¹d pochodz¹ Zbrojeniowcy?}
{161}{}{}
{162}{}{Dziêki za pomoc.}
{163}{}{Có¿, podobno znajdowa³a siê gdzieœ na po³udnie st¹d, ale ja tego tak naprawdê nie wiem. Myœlê, ¿e wszyscy j¹ opuœcili, bo by³a uszkodzona.}
{164}{}{Czy mogê ci zadaæ jeszcze parê pytañ?}
{165}{}{Hmm. Dziêki.}
{166}{}{Nie jestem tego do koñca pewna. S¹dzê, ¿e przyszli z jakiegoœ miejsca na pó³noc st¹d.}
{167}{}{Co wiesz o Regulatorach?}
{168}{}{Czy mogê ciê spytaæ o parê innych spraw?}
{169}{}{Dziêki za informacje.}
{170}{}{O kim chcesz siê czegoœ dowiedzieæ?}
{171}{}{O Jonie Zimmermanie.}
{172}{}{O Calebie.}
{173}{}{O Milesie.}
{174}{}{O Tinie.}
{175}{}{O Smitty'm.}
{176}{}{O nikim, dziêki.}
{177}{}{Zimmerman dba o nasz¹ osadê. Pilnuje, ¿eby ka¿dy by³ nakarmiony i mia³ coœ do roboty.}
{178}{}{Caleb jest dowódc¹ Regulatorów. To jego zadaniem jest ochranianie Adytum. Wydaje siê tym rajcowaæ trochê bardziej ni¿ powinien.}
{179}{}{Ach, to nasz miejscowy chemik. Miles robi naboje, a tak¿e zbudowa³ destylator, dziêki któremu czerpiemy ze studni czyst¹ wodê. Teraz pracuje nad podziemn¹ farm¹, ale brakuje mu jakichœ czêœci.}
{180}{}{Tine prowadzi sklep w schronie ko³o bramy. Handluje w naszym imieniu z kupcami z Hubu.}
{181}{}{Hmm. Smitty to ktoœ w rodzaju druciarza. Jest dobry w naprawach. Odlewa pociski i reperuje zepsute rzeczy w ca³ej osadzie.}
{182}{}{Mogê ciê jeszcze o kogoœ zapytaæ?}
{183}{}{Czy mo¿emy porozmawiaæ na inny temat?}
{184}{}{}
