{100}{}{wy³.}
{101}{}{Pozosta³y czas: }
{102}{}{ sek.}
{103}{}{W tym momencie mo¿esz uwa¿aæ siê za trupa.}
{104}{}{wy³.}
{105}{}{w³.}
{106}{}{wy³.}
{107}{}{Pozosta³y czas: }
{108}{}{ sek.}
{109}{}{W tym momencie mo¿esz uwa¿aæ siê za trupa.}
{110}{}{Pozosta³y czas: }
{111}{}{ sek.}
{112}{}{W tym momencie mo¿esz uwa¿aæ siê za trupa.}
