{100}{}{Widzisz Michelle.}
{101}{}{}
{102}{}{}
{103}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{104}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{105}{}{Wydaje ci siê, ¿e to mo¿e byæ Kujon.}
{106}{}{Wydaje ci siê, ¿e to mo¿e byæ Blizna.}
{107}{}{Wydaje ci siê, ¿e to mo¿e byæ Strzelec.}
{108}{}{Wydaje ci siê, ¿e to mo¿e byæ Nerwus.}
{109}{}{Wydaje ci siê, ¿e to mo¿e byæ M³ot.}
{110}{}{Wydaje ci siê, ¿e to mo¿e byæ Brzytwa.}
{111}{}{Co tutaj robisz?}
{112}{}{Hhrrrnnn.}
{113}{}{Nic. Naprawdê.}
{114}{}{Tylko siê rozgl¹dam.}
{115}{}{This! [you slap her]}
{116}{}{G³upek. Lepiej siê st¹d wynieœ. W przeciwnym razie mo¿esz dostaæ posadê ruchomej tarczy.}
{117}{}{Arroo!}
{118}{}{Arook.}
{119}{}{Nic, tak? Myœlê, ¿e coœ ukrywasz. Przyznaj siê, zanim wyprujê ci flaki.}
{120}{}{Tak naprawdê jestem z Marsa.}
{121}{}{Jestem tu, ¿eby zakoñczyæ wojnê gangów.}
{122}{}{Wcale nic nie planujê.}
{123}{}{I'm up to THIS! [slap her]}
{124}{}{Wszyscy wiedz¹, ¿e nie ma Marsjan. Wszyscy obcy pochodz¹ z Wenus. A teraz giñ!}
{125}{}{Jasne, a ja jestem królow¹ Meksyku.}
{126}{}{Powa¿nie. Chcê zakoñczyæ tê wojnê i pomóc Adytum.}
{127}{}{Wasza wysokoœæ, ja naprawdê chcê po³o¿yæ kres tej wojnie.}
{128}{}{Gdyby pozwala³ na to poziom twojej inteligencji, to wyjaœni³abym ci jakie korzyœci daje pokój.}
{129}{}{Musisz znaleŸæ Brzytwê, skoro chcesz to zrobiæ. Ona ci powie co na ten temat myœlimy.}
{130}{}{Hmm, dziêki. Zastanowiê siê.}
{131}{}{Dobrze. Do widzenia.}
{132}{}{SprawdŸ mnie, chcesz? No tak tyle mo¿na siê spodziewaæ po dziecku. A tak przy okazji. Masz!}
{133}{}{Gadaniem nie mo¿na za daleko dojœæ. Za to ³atwo wykopaæ sobie w ten sposób grób.}
{134}{}{Jeœli nie masz nic do roboty, to szybko ci coœ znajdziemy. Wydaje mi siê, ¿e œwietnie nadajesz siê na "ruchomy cel".}
{135}{}{No to ju¿ uda³o ci siê to zrobiæ. Czego chcesz? Tylko myœl szybko. To mo¿e zadecydowaæ o tym, czy st¹d wyjdziesz, czy zostaniesz tu na sta³e.}
{136}{}{Chêtnie tu zamieszkam.}
{137}{}{Tak naprawdê jestem Rozpruwaczem w przebraniu.}
{138}{}{Chcê przynieœæ gangom pokój.}
{139}{}{Idê.}
{140}{}{Nic specjalnego. Patrzê na œmiecie gotowe do powtórnego wykorzystania.}
{141}{}{Nikt nie mówi³ nic o mieszkaniu. Po prostu tutaj zostaniesz. Na czas nieokreœlony. Mi³ego pobytu.}
{142}{}{Cieszê siê, ¿e przesz³o ci to przez usta. Chcia³am to naostrzyæ. }
{143}{}{Nied³ugo bêdê mia³a skórê, na której bêdê mog³a to ostrzyæ.}
{144}{}{Nie tak szybko. St¹d mo¿na odejœæ tylko jako Ostrze, albo w worku.}
{145}{}{Zatem chcê wst¹piæ do Ostrzy.}
{146}{}{A du¿y jest ten worek?}
{147}{}{Zapomnia³aœ o trzeciej mo¿liwoœci. O mnie!}
{148}{}{Du¿a szansa. Ale mam dla ciebie test. Je¿eli uda ci siê znaleŸæ Brzytwê, to mo¿e uda ci siê z ni¹ o tym porozmawiaæ.}
{149}{}{Dostatecznie du¿y, ¿eby w nim poupychaæ kawa³ki twojego cia³a, jak ju¿ skoñczymy.}
{150}{}{Nie jestem Œpi¹c¹ Królewn¹. Nie trzeba mnie budziæ. Wynoœ siê st¹d, albo zdechniesz.}
{151}{}{S³ysza³am, ¿e polujesz na tego bydlaka. Pchnij go ode mnie no¿em.}
{152}{}{Witaj z powrotem. Dziura jest otwarta i przyjmie ciê jeszcze raz.}
