{100}{}{Nie mo¿esz siê przebiæ przez kawa³ki miêsa ró¿nej wielkoœci.}
{101}{}{Lodówka jest wype³niona ró¿nymi organami i kawa³kami cia³.}
{102}{}{Lodówka jest wype³niona pokrojonymi kawa³kami miêsa, przygotowanymi do transportu. Na pewno nie bêd¹ one s³u¿yæ do przeszczepów.}
{103}{}{Lodówka jest wype³niona kawa³kami miêsa.}
{104}{}{Lodówka jest wype³niona czêœciami cia³, pokrojonymi w ma³e kawa³ki ob³o¿one lodem. Dziwne.}
