{100}{}{Widzisz popsutego robota.}
{101}{}{Widzisz sprawnego robota.}
{102}{}{Naprawiasz popsutego robota. B³yskawicznie odzyskuje moc i zaczyna dzia³aæ.}
{103}{}{Uszkodzenia s¹ zbyt powa¿ne jak na twoje umiejêtnoœci.}
