{100}{}{Widzisz drzwi œluzy powietrznej.}
{101}{}{Drzwi s¹ zamkniête na elektroniczny zamek.}
{102}{}{Drzwi nie s¹ zamkniête.}
{103}{}{Udaje ci siê obejœæ elektroniczny zamek.}
{104}{}{Nie udaje ci siê obejœæ elektronicznego zamka.}
