{100}{}{Droga na pó³noc jest zablokowana przez gruzowisko. Musisz znaleŸæ inn¹.}
{101}{}{Droga na po³udnie jest zablokowana przez gruzowisko. Musisz znaleŸæ inn¹.}
{102}{}{Droga na wschód jest zablokowana przez gruzowisko. Musisz znaleŸæ inn¹.}
{103}{}{Droga na zachód jest zablokowana przez gruzowisko. Musisz znaleŸæ inn¹.}
{104}{}{Droga przed tob¹ jest zablokowana przez gruzowisko. Mo¿e uda ci siê znaleŸæ jakieœ przejœcie pod ziemi¹.}
