{100}{}{Widzisz Neala; barmana.}
{101}{}{Widzisz barmana.}
{102}{}{Wygl¹da na to, ¿e za du¿o pracuje.}
{103}{}{Hej! Nie myœl, ¿e uda ci siê to uda rabusiu jeden!}
{104}{}{Nieczynne. PrzyjdŸ ko³o czwartej.}
{105}{}{Zzzz}
{106}{}{Witaj w Norze Szumowin. Co mogê dla ciebie zrobiæ?}
{107}{}{Ee, masz coœ do picia?}
{108}{}{Potrzebujê informacji.}
{109}{}{Nazywam siê }
{110}{}{. Co to za miejsce?}
{111}{}{Gaa hnnngh!}
{112}{}{Œwietnie. Czego chcesz?}
{113}{}{Nuka-cola, 3 kapsle.}
{114}{}{Piwo, 5 kapsli.}
{115}{}{Gorza³a, 20 kapsli.}
{116}{}{Dobra, co chcesz wiedzieæ?}
{117}{}{Co s³ychaæ w miasteczku?}
{118}{}{Co to za niebezpieczny koleœ, tam w rogu?}
{119}{}{Co to za palanty?}
{120}{}{[Neal przygl¹da ci siê ze zdziwieniem.] Co to, pierwszy raz jesteœ w barze? To mój lokal. Nora Szumowin. Tutaj siê pije. No i zostawia mi napiwki.}
{121}{}{Uch, jasne. Oczywiœcie. Mogê dostaæ coœ do picia?}
{122}{}{Taak. Ee, mogê ciê zapytaæ jeszcze o coœ?}
{123}{}{Aa. Dziêki.}
{124}{}{Taak, to samo tobie, koleœ.}
{125}{}{Co to za trofeum tam na pó³ce?}
{126}{}{Zaraz na zachód st¹d stoi kasyno nale¿¹ce do Gizma. Jestem zdziwiony, ¿e jeszcze tego nie wiesz; wiêkszoœæ moich klientów to ludzie, którzy przegrali tam ju¿ wszystkie pieni¹dze. W drugiej czêœci miasta znajdziesz sklep Killiana i Noclegowniê, któr¹ prowadzi Marcelles. Killian to porz¹dny goœæ, prowadzi uczciwy interes. Mo¿na u niego dostaæ prawie wszystko. W Noclegowni odeœpisz zbyt d³ugi pobyt w moim barze. [œmieje siê.]}
{127}{}{Dziêki. Mogê dostaæ coœ do picia?}
{128}{}{Dziêki za informacjê. Na razie.}
{129}{}{Ten goœæ to Tycho. To ranger z wybrze¿a. Twardy zawodnik, ale z tego co s³ysza³em to uczciwy facet.}
{130}{}{Mogê ci zadaæ jeszcze kilka pytañ?}
{131}{}{Aa, ci. To Czachy. Cz³onkowie miejscowego gangu. Straszna ho³ota. Czasem wszczynaj¹ bójki i robi¹ trochê zamieszania. Przez wiêkszoœæ czasu Killian trzyma ich w ryzach.}
{132}{}{Proszê. Smacznego.}
{133}{}{Hej! To moja urna!}
{134}{}{To nie jest trofeum tylko urna. Zawiera prochy mojej ¿ony - nie licz¹c baru to najwa¿niejsza rzecz w moim ¿yciu.}
{135}{}{Coœ jeszcze?}
{136}{}{Potrzebujê jeszcze kilku informacji.}
{137}{}{Nie, dziêkujê.}
{138}{}{Och.}
{139}{}{Taak, nalej mi kielicha.}
{140}{}{Wróæ jak bêdziesz mieæ jakieœ pieni¹dze.}
{141}{}{Co podaæ?}
{142}{}{Co siê sta³o z tym trofeum, które sta³o tam, na barze?}
{143}{}{Dziêkujê. Nie wiesz ile to dla mnie oznacza. Od tej pory wszystkie drinki w tym barze bêdziesz dostawaæ na koszt firmy.}
{144}{}{Chcê ci oddaæ twoj¹ urnê.}
{145}{}{Ktoœ je ukrad³. Ale to nie by³o trofeum, tylko urna. Zawiera³a prochy mojej ¿ony - obok baru to najwa¿niejsza rzecz w moim ¿yciu.}
{146}{}{Wynoœcie siê st¹d przeklête gnojki! Jak któryœ z was jeszcze raz j¹ dotknie, to wystrzelam was jak psy!}
{147}{}{Dzieñ w którym nie dasz sobie rady z ma³ym gównem bêdzie dniem twojej œmierci!}
{148}{}{Co tu do diab³a robisz? Nieczynne. Wynocha!}
{149}{}{Przeklête dzieciaki, poka¿ê wam kilka sztuczek!}
