{100}{}{Widzisz Orfeusza, Starszego Cz³onka Dzieci Katedry.}
{101}{}{Ach. Nowy wyznawca. Witaj.}
{102}{}{Ja zabiæ!!}
{103}{}{Nikt mnie nie nawróci³!}
{104}{}{Dziêkujê Bracie.}
{105}{}{Zatem nied³ugo zajmiemy siê tym problemem.}
{106}{}{Najpierw musimy ciê obmyæ z nieczystoœci pustkowia. ChodŸ.}
{107}{}{Oczyœcimy ciê!}
