{100}{}{Widzisz cz³owieka w pancerzu skórzanym obwieszonym ró¿nymi b³yskotkami.}
{101}{}{Widzisz Patryka, Celta.}
{102}{}{Witaj wêdrowcze. Co ciê sprowadza na takie pustkowie?}
{103}{}{Tylko sobie wêdrujê.}
{104}{}{Ee, a po co dŸwigasz te wszystkie œmieci?}
{105}{}{Muszê znaleŸæ uk³ad kontrolny do systemu oczyszczania wody.}
{106}{}{Zabijam ka¿dego, kto znajduje siê w zasiêgu mojej broni. Przygotuj siê na œmieræ.}
{107}{}{Lub!}
{108}{}{Rozumiem. Ca³kiem jak ja.}
{109}{}{Och? Nie pochodzisz z ¿adnej z lokalnych spo³ecznoœci?}
{110}{}{Mo¿esz mnie skierowaæ do najbli¿szej osady?}
{111}{}{Jaka jest twoja historia?}
{112}{}{No có¿, na razie.}
{113}{}{To nie s¹ œmiecie! To towary!}
{114}{}{Aha, niech bêdzie. ¯egnaj.}
{115}{}{Hmm. Jaka jest twoja historia?}
{116}{}{Hmm. Nigdy nie widzia³em nic takiego. Jakiœ problem?}
{117}{}{Ten uk³ad steruje procesami oczyszczania wody dla mojej Krypty. Ale siê popsu³.}
{118}{}{Nie dzia³a.}
{119}{}{Wêdrujê z miejsca na miejsce. Zarabiam na ¿ycie muzyk¹ i czasem pracujê jako druciarz.}
{120}{}{Czym siê zajmujesz?}
{121}{}{Co œpiewasz?}
{122}{}{Mi³o by³o ciê poznaæ. ¯egnaj.}
{123}{}{Wykorzystuj¹c wybrze¿e jako liniê odniesienia Cieniste Piaski s¹ jakiœ tydzieñ w g³¹b l¹du, kilka dni na po³udnie od tej mieœciny jest Z³omowo. Hub znajduje siê kolejne kilka dni na po³udnie od Z³omowa. Na twoim miejscu unika³bym Nekropolis, które znajduje siê na zachód od tych miast. Nie warto tam zagl¹daæ.}
{124}{}{Co wiesz o Cienistych Piaskach?}
{125}{}{Co wiesz o Z³omowie?}
{126}{}{Co wiesz o Hub?}
{127}{}{Co wiesz o Nekropolis?}
{128}{}{Chyba nie potrafiê ci pomóc. Nie mia³em okazji studiowaæ przedwojennej technologii.}
{129}{}{G³ównie drobne prace mechaniczne i elektryczne. Pomog³em zainstalowaæ w Z³omowie oœwietlenie uliczne, a mieszkañcom Cienistych Piasków zaprojektowaæ lepsze kuchenki.}
{130}{}{Powa¿nie? Myœlisz, ¿e uda³oby ci siê naprawiæ hydroprocesor?}
{131}{}{G³ównie piosenki folkowe i trochê muzyki celtyckiej. To zale¿y kiedy.}
{132}{}{Znasz mo¿e "Na Gheala Mbeadh", wydaje mi siê, ¿e jest taka piosenka?}
{133}{}{Rozumiem. Czym jeszcze siê zajmujesz?}
{134}{}{Cieniste Piaski to ma³e, samowystarczalne miasteczko kierowane przez Aradesha. To uprzejmy cz³owiek i silny przywódca. Mieszkañcy to spokojni i pracowici ludzie. Oni maj¹ chyba najwiêksze szanse na wybudowanie nowej cywilizacji.}
{135}{}{Cieniste Piaski to niewielka osada rolnicza. Jej mieszkañcami przewodzi³ dobry cz³owiek o imieniu Aradesh, ale s³ysza³em, ¿e nie ¿yje. Szkoda. Nie wiem, czy bez niego zdo³aj¹ przetrwaæ.}
{136}{}{Z³omowo? To ma³e miasteczko utrzymuj¹ce siê z handlu. Dziwne miejsce, trzeba siê do niego przyzwyczaiæ. Burmistrzem jest Killian Darkwater. To surowy, ale uczciwy cz³owiek.}
{137}{}{Z³omowo? To ma³e miasteczko utrzymuj¹ce siê z handlu. Dziwne miejsce, trzeba siê do niego przyzwyczaiæ. Kieruje nim Gizmo, magnat hazardowy i przywódca mafii.}
{138}{}{Z³omowo? To ma³e miasteczko utrzymuj¹ce siê z handlu. Nie ma w nim nic nadzwyczajnego.}
{139}{}{Hub to du¿e centrum handlu. Mówi siê, ¿e mo¿na tam znaleŸæ wszystko i uwa¿am, ¿e to stwierdzenie jest bliskie prawdy.}
{140}{}{Nekropolis jest miastem umar³ych. Zamieszkuj¹ je ghule, potomkowie ludzi, którzy schronili siê w tamtejszej Krypcie. Podobno Krypta ich nie uchroni³a i jej mieszkañcy zmienili siê w padlino¿erne potwory.}
{141}{}{Z tego co ostatnio s³ysza³em zosta³o opanowane przez armiê mutantów. Na twoim miejscu trzyma³bym siê z daleka.}
{142}{}{Jak s¹dzisz, czy w tamtejszej Krypcie mog¹ siê znajdowaæ jakieœ przydatne czêœci?}
{143}{}{Mo¿liwe, ale ja bym nie zaryzykowa³ spotkania z ghulami. Ostatnio s³ysza³em, ¿e maj¹ jakiegoœ nowego, silnego przywódcê.}
{144}{}{Dlaczego pytasz, oczywiœcie. Chcesz pos³uchaæ?}
{145}{}{Pewnie.}
{146}{}{Nie.}
{147}{}{[Patrick œpiewa piosenki i na kilka godzin pogr¹¿acie siê we wspomnieniach. Czujesz siê lepiej.}
{148}{}{Witaj ponownie. Mogê ci jakoœ pomóc?}
{149}{}{Mo¿esz mi wskazaæ drogê do kilku miejsc?}
{150}{}{Nie, niewa¿ne, dziêkujê.}
