{100}{}{Wygl¹da na to, ¿e ta osoba pochodzi³a z Bractwa Stali.}
{101}{}{Zastanawiasz siê co tu robi³ ten metalowy cz³owiek.}
{102}{}{Ten cz³owiek zgin¹³ chyba z powodu napromieniowania.}
{103}{}{Nie mo¿esz okreœliæ przyczyny zgonu tego cz³owieka.}
{104}{}{Ta umiejêtnoœæ nie dostarczy ci dodatkowych informacji o tej osobie.}
