{100}{}{Radio. Amazingly, it appears to be functional.}
{101}{}{[Na pocz¹tku s³ychaæ tylko statyczne trzaski, ale potem odzywa siê niski g³os.] Dowodzenie do patrolu, dowodzenie do patrolu! Jaka jest sytuacja? Odbiór.}
{102}{}{Eek!}

##{103}{}{Uh, nothing is wrong here. We're fine, uh, how are you?}

{103}{}{Uhhh, everything's under control, situation normal. Nothing is wrong here. We had a slight... weapons malfunction. But everything's perfectly alright now.  We're all fine, here, now. How are you?}
{104}{}{Dowodzenie, atakuje nad du¿a grupa uzbrojonych ludzi. Proszê o pomoc. Odbiór.}
{105}{}{Pomocy!! Atakuj¹ nas! Ciê¿kie straty! Podajê wspó³rzêdne: 10... Argh!}
{106}{}{Patrol, przyj¹³em. Wysy³amy wsparcie. Bez odbioru.}
{107}{}{Say again? Who is this? What is your purpose?}
{108}{}{Zamkn¹æ siê.}
{109}{}{Jestem, eee... niewa¿ne. I tak pozabijam was wszystkich.}
{110}{}{Mówi, hmm, Fred. Wykonujê patrol. Po tym upadku ci¹gle jestem trochê oszo³omiony.}
{111}{}{Patrol, przyj¹³em. Jakie s¹ wasze wspó³rzêdne?}
{112}{}{224 na 104.}
{113}{}{Cztery mile na po³udnie-po³udniowy zachód.}
{114}{}{Sektor Gamma, punkt Omicron-Delta-Beta.}
{115}{}{Patrol, przyj¹³em. Dowodzenie, bez odbioru.}
{116}{}{Patrol, przyj¹³em. Wysy³amy wsparcie.}
{117}{}{Aaa, to wszystko wyjaœnia. Wysy³amy wsparcie.}
{118}{}{Patrol, przyj¹³em. Wysy³amy wam wsparcie! Trzymajcie siê!}
{119}{}{Z radia wydobywa siê tylko statyczny szum.}
{120}{}{S³yszysz tocz¹c¹ siê przez radio rozmowê. Przys³uchujesz siê przez chwilê, ale nie dowiadujesz siê niczego wa¿nego.}
{121}{}{Miga czerwona kontrolka na radiu. Z g³oœnika dobywa siê piskliwe skrzeczenie.}
{122}{}{To chyba zakodowany przekaz.}
{123}{}{Wysy³asz kod dowodzenia, ¿eby zmieniæ ustawienia pól si³owych.}

##{124}{}{There is only quiet static on the radio [channel].}

{124}{}{You hear some chatter on the radio. You listen for a while, but discover nothing of importance.}
{125}{}{Radio nie dzia³a.}
{126}{}{To radio jest w doskona³ym stanie. Problem musi tkwiæ w czymœ innym.}
{127}{}{Z radia wydobywa siê tylko zakodowany przekaz.}
{128}{}{[bip-bip-bip] Tu dowodzenie, patrol, mo¿ecie mówiæ.}
{129}{}{Auæ!}
{130}{}{Eee, dowodzenie, przepraszam. Przez przypadek nacisn¹³em guzik na radiostacji.}
{131}{}{Intruzi w bazie! Og³oœcie alarm!}
{132}{}{Patrol- przyj¹³em. Dowodzenie, bez odbioru.}
{133}{}{[Ustawiasz radio na czêstotliwoœæ kana³u bezpieczeñstwa] [Klik!] Podaj numer dostêpowy. [Klik!]}
{134}{}{Hng!}
{135}{}{Uch, 69.}
{136}{}{5566534571}
{137}{}{Koniec po³¹czenia.}
{138}{}{Automatyczne wy³¹czenie kana³u bezpieczeñstwa.}
{139}{}{Za wykiwanie mutantów dostajesz 1,500 punktów doœwiadczenia.}
{140}{}{Uzyskujesz 2,000 punktów doœwiadczenia za wœliŸniêcie siê do bazy i unikniêcie stra¿ników (jak do tej pory)...}
