{100}{}{Widzisz przygnêbionego wiêŸnia bandytów.}
{101}{}{Hej! Wyci¹gnij mnie st¹d!}
{102}{}{B¹dŸ cicho, bo ciê us³ysz¹ stra¿nicy!}
{103}{}{Szz! Kim jesteœ?}
{104}{}{Goop}
{105}{}{Nie obchodzi mnie to. Wydostañ mnie st¹d, proszê!}
{106}{}{Nazywam siê Jack. Jestem ze Z³omowa. Te potwory pozabija³y wszystkich cz³onków karawany, a mnie zamknêli.}
{107}{}{Dobra. Zobaczê co da siê zrobiæ.}
{108}{}{Ale z ciebie dupek. Mi³ego pobytu.}
{109}{}{Proszê, pomó¿ mi.}
{110}{}{Au! Moja noga - strasznie mnie boli. Chyba mo¿e byæ z³amana. Pomó¿ mi!}
