{100}{}{Widzisz Kathy, w³aœcicielkê tego sklepu.}
{101}{}{Przykro, niewiele dzisiaj mam.}
{102}{}{Czego dzisiaj szukasz?}
{103}{}{Tak? W czym mogê ci pomóc?}
{104}{}{Przykro mi, wci¹¿ nie mam nowego towaru.}
{105}{}{Masz do sprzedania jakieœ pancerze?}
{106}{}{Witaj.}
{107}{}{Dzieñ dobry.}
{108}{}{Widzisz coœ, co ciê interesuje?}
{109}{}{Dziêkujê za odwiedziny.}
{110}{}{Mi³o ciê widzieæ.}
{111}{}{Zajrzyj do mnie jeszcze.}
{112}{}{Do zobaczenia wkrótce.}
{113}{}{¯egnaj.}
{114}{}{Przykro mi, postaram siê zdobyæ nowy sprzêt.}
{115}{}{Wydaje mi siê, ¿e powinnaœ poszerzyæ ofertê.}
{116}{}{Dziêki.}
{117}{}{Dziêkujê za wizytê.}
{118}{}{Przepraszam jeœli nie mam tego, co ci jest potrzebne.}
{119}{}{Mi³ego dnia.}
