{100}{}{Mój bo¿e! Zgin¹³ z twojej rêki!}
{101}{}{Hng!}
{102}{}{Tak bywa.}
{103}{}{By³ moim wrogiem. Trzeba by³o to zrobiæ.}
{104}{}{Przepraszam. Dopiero teraz siê dowiadujê, ¿e by³ ci tak bliski.}
{105}{}{On nie musia³ zgin¹æ! [Sarah p³acze.] Zostaw mnie w spokoju.}
{106}{}{By³ moim kochankiem. Najlepszym przyjacielem. Nie mogê uwierzyæ w to, co go spotka³o z twojej rêki.}
{107}{}{Jeszcze raz przepraszam. A co niby wskazywa³o na to, ¿e tyle dla ciebie znaczy³? Tylko na niego spójrz. To mutant!}
{108}{}{Zabijê wszystkich takich, jak on.}
{109}{}{By³ istot¹ ludzk¹! Mutacja by³a jedyn¹ szans¹ na prze¿ycie, jak¹ mia³. Zgin¹³ z twojej rêki.}
{110}{}{Przykro mi.}
{111}{}{A, co tam. Jeden trup wiêcej na moim koncie.}
{112}{}{Dupek.}
{113}{}{Co robisz poza swoj¹ cel¹ ochronn¹?}
{114}{}{Zug-zug!}
{115}{}{Tak sobie chodzê.}
{116}{}{Nie jestem tu wiêŸniem.}
{117}{}{Nie, dziêki - ju¿ mam ch³opaka.}
{118}{}{Nale¿y przebywaæ w przydzielonych celach. Stra¿nicy trzymaj¹ nas tu dla naszego bezpieczeñstwa. Roboty zaprogramowano tak, aby atakowa³y normalnych chodz¹cych bez eskorty. Po mutacji bêdê mog³a wspomóc Jednoœæ.}
{119}{}{Ok, super, baw siê dobrze.}
{120}{}{Naprawdê tego chcesz?}
{121}{}{Oczywiœcie, to najwiêksza szansa ludzkoœci na przetrwanie.}
{122}{}{Wow! Chyba napytasz sobie problemów. Proszê, nie krêæ siê przy mnie.}
{123}{}{My tu rozmawiamy!}
