{100}{}{Ta umiejêtnoœæ tu siê nie przyda.}
{101}{}{Znajdujesz topornie zmajstrowany materia³ wybuchowy pod³¹czony do szafki.}
{102}{}{Powodujesz wybuch pu³apki!}
{103}{}{Uda³o ci siê rozbroiæ pu³apkê.}
{104}{}{Pu³apka nie rozbrojona.}
{105}{}{Przypadkowo powodujesz wybuch pu³apki!}
{106}{}{Przypadkowo powodujesz wybuch pu³apki, gdy¿ m¹droœci starczy³o ci na znalezienie jej, ale ju¿ nie na zostawienie jej w spokoju.}
{107}{}{Uuuf!}
{108}{}{Aaargh!}
{109}{}{Widzisz szafkê Seta.}
