{100}{}{Widzisz lit¹ œcianê.}
{101}{}{W tym kawa³ku œciany jest coœ dziwnego.}
{102}{}{Widzisz przesuwane drzwi.}
{103}{}{Drzwi s¹ zamkniête.}
{104}{}{Powodujesz wybuch pu³apki.}
{105}{}{ wykrywa na tych drzwiach pu³apkê.}
{106}{}{Wykrywasz pu³apkê na tych drzwiach.}
{107}{}{To nic nie daje.}
{108}{}{Drzwi ju¿ s¹ otwarte.}
{109}{}{£amiesz swoje wytrychy w tym skomplikowanym zamku.}
{110}{}{Nie uda³o ci siê otworzyæ tego zamka.}
{111}{}{Uda³o ci siê otworzyæ ten zamek.}
{112}{}{Ten zamek jest zbyt skomplikowany, aby da³o siê go otworzyæ przy twoich umiejêtnoœciach.}
{113}{}{Zauwa¿asz materia³ wybuchowy przyczepiony do tych zamkniêtych drzwi.}
{114}{}{Zauwa¿asz materia³ wybuchowy przyczepiony do tych drzwi.}
{115}{}{Zauwa¿asz pu³apkê na tych zamkniêtych drzwiach.}
{116}{}{Zauwa¿asz pu³apkê na tych drzwiach.}
{117}{}{Te zamkniête drzwi nie wyró¿niaj¹ siê niczym szczególnym.}
{118}{}{Te drzwi nie wyró¿niaj¹ siê niczym szczególnym.}
