{100}{}{Widzisz Smitty'ego.}
{101}{}{Widzisz du¿ego, umiêœnionego mê¿czyznê.}
{102}{}{Dzieñ dobry. W czym mogê pomóc?}
{103}{}{Czego chcesz?}
{104}{}{Mogê siê spytaæ o twoje imiê?}
{105}{}{Musisz dla mnie naprawiæ te czêœci, bo nie zdo³am zreperowaæ waszych farm hydroponicznych.}
{106}{}{Chcê coœ kupiæ.}
{107}{}{Mogê ci zadaæ kilka pytañ?}
{108}{}{Nic, dziêkujê. Do zobaczenia.}
{109}{}{Eee...}
{110}{}{Sugerujê wizytê w sklepie Tine, zaraz po drugiej stronie bram. Nie sprzedajê tu nic; Handlujê tylko z Tine lub kupcami z Hubu.}
{111}{}{Wszyscy mnie nazywaj¹ 'Smitty'. Pewnie dlatego, ¿e jestem tu kowalem.}
{112}{}{Strzelaj.}
{113}{}{Sk¹d masz wyposa¿enie sklepu?}
{114}{}{Co tu produkujesz?}
{115}{}{Czy mo¿esz produkowaæ broñ i amunicjê?}
{116}{}{To wszystko, dziêki.}
{117}{}{Przykro mi, nie mogê ci pomóc. Spróbuj u Zimmermana.}
{118}{}{Pewnie.}
{119}{}{Ka¿dy porz¹dny kowal umie zrobiæ sobie kowad³o! Oczywiœcie mojego fachu nauczy³em siê praktykuj¹c go, ale narzêdzia zrobi³em w³aœciwie sam.}
{120}{}{Z regu³y naprawiam tu narzêdzia i inne przedmioty. Naprawiam tez trochê sprzêtu dla kupców z Hub. Z pomoc¹ chemika Milesa od czasu do czasu nape³niam te¿ ponownie naboje.}
{121}{}{Produkcja broni i amunicji wymaga skomplikowanych maszyn, których nie mam jak zbudowaæ. Jednak z pomoc¹ chemika Milesa mogê ponownie nape³niaæ stare ³uski.}
{122}{}{Da siê zrobiæ. Daj mi trochê czasu.}
{123}{}{Proszê. [Smitty wrêcza ci naprawione czêœci.]}
{124}{}{Czêœci s¹ ju¿ naprawione. Musisz je teraz daæ Milesowi.}
{125}{}{Dziêki za zreperowanie farm. Jak wpadnie ci przypadkiem w rêce karabin plazmowy, to mi go podrzuæ. Znam parê sztuczek, które mog¹ go ulepszyæ.}
{126}{}{Tak siê sk³ada, ¿e mam coœ takiego.}
{127}{}{A wiêc uda³o ci siê coœ takiego zdobyæ!}
{128}{}{Daj mi go, zobaczê, co siê da zrobiæ. [Smitty bierze karabin, wyci¹ga swoje narzêdzie i zaczyna przy nim majstrowaæ.]}
{129}{}{Proszê chyba ju¿. [Smitty oddaje ci karabin.] Teraz go wypróbuj.}
{130}{}{Tak jak mówi³em, jeœli uda ci siê zdobyæ karabin plazmowy, to mi go podrzuæ, a mo¿e uda mi siê go trochê podrasowaæ.}
{131}{}{Dobrze ciê znów widzieæ. Mam nadziejê, ¿e u ciebie wszystko w porz¹dku.}
