{100}{}{Widzisz dwa super mutanty. Jeden jest ranny, drugi go opatruje.}
{101}{}{Jak siê teraz czujesz?}
{102}{}{[Rusza ramieniem] Wci¹¿ trochê boli. Przynajmniej ju¿ nie krwawi}
{103}{}{To dobrze. Za¿ywaj leki, a wkrótce bêdziesz jak nowy.}
{104}{}{Doskonale. Gdy tylko dorwê tego ma³ego cz³owieczka, zmia¿d¿ê go.}
{105}{}{Doskonale. Gdy tylko dorwê tego ma³ego cz³owieczka, zmia¿d¿ê j¹.}
{106}{}{Ostatnim razem sporo narozrabia³. Mam nadziejê, ze wkrótce go dostan¹.}
{107}{}{Ostatnim razem sporo narozrabia³a. Mam nadziejê, ze wkrótce j¹ dostan¹.}
{108}{}{Pomyœl tylko, co by by³o, gdyby nasze plany pomiesza³ jeden ma³y cz³owieczek.}
{109}{}{[œmiech] Tak, to by dopiero by³a szkoda.}
{110}{}{[œmiech]}
