{100}{}{Widzisz kilka mutantów i dzieci klêcz¹cych przed wideoekranem.}
{101}{}{Módl siê z nami o pokój, dziecko..}
{102}{}{Jednoœæ zwyciê¿y, jeœli bêdziemy silni. Medytujcie nad wartoœci¹ si³y.}
{103}{}{Nasza misja zbawienia ludzkoœci wymaga wiary. Módl siê z nami.}
{104}{}{Niewierny! BluŸnierca! Spotka ciê kara!}
{105}{}{Musimy siê modliæ, abyœmy byli silni. Zmiana nadchodzi.}
{106}{}{Jednoœæ to nasza przysz³oœæ, bracie.}
{107}{}{Jednoœæ to nasza przysz³oœæ, siostro.}
{108}{}{Wierzê w Mistrza, on jest naszym zbawieniem.}
