{100}{}{Widzisz Katrinê. Ma bardzo ³adny uœmiech.}
{101}{}{Ja nie mam broni, wiêc ty te¿ od³ó¿ swoj¹.}
{102}{}{Hng!}
{103}{}{Dlaczego? Ten œwiat wygl¹da mi na niebezpieczny.}
{104}{}{Dlaczego?}
{105}{}{Mo¿e tak, mo¿e nie.}
{106}{}{Uznam to za 'tak'.}
{107}{}{Zwykle bym siê z tob¹ zgodzi³a. Podró¿owanie jest bardzo niebezpieczne dla kogoœ bez broni. Ale to s¹ Cieniste Piaski - jesteœmy spokojnymi ludŸmi. Tu nie ma potrzeby nosiæ broni.}
{108}{}{Okay. Thanks.}
{109}{}{Jeœli nie od³o¿ysz broni, nie bêdê z tob¹ rozmawiaæ. Jest wielu takich jak ja. Si³y nale¿y u¿ywaæ tylko wtedy, gdy wymaga tego sytuacja.}
{110}{}{Hmm, okay.}
{111}{}{Witaj w Cienistych Piaskach, przybyszu. Nazywam siê Katrina. Moim zadaniem jest witanie takich, jak ty i pomaganie im w zrozumieniu wioski. Z regu³y mniej jest potem problemów, jeœli mnie wys³uchaj¹.}
{112}{}{Wubba!}
{113}{}{Opowiedz mi o sobie.}
{114}{}{Pomó¿ mi, proszê...}
{115}{}{Szukam hydroprocesora. Widzia³aœ coœ takiego?}
{116}{}{Potrzebujê pomocy w znalezieniu Tandi.}
{117}{}{Zajmujê siê waszym problemem z radskorpionami. Jakieœ sugestie?}
{118}{}{Dziêki, mo¿e póŸniej.}
{119}{}{Szkoda, ¿e nie grzeszysz inteligencj¹. Bêdziemy mieæ k³opoty ze wzajemnym zrozumieniem. Mam nadziejê, ¿e pozostali mieszkañcy twojej Krypty s¹ inni.}
{120}{}{Sa-krypta?}
{121}{}{Tak, wiem, ¿e jesteœ z Krypty. Tak w³aœnie wygl¹dasz. Ja jestem z Krypty-15. To na wschód st¹d. Musia³am jednak sobie stamt¹d pójœæ i teraz tu mieszkam. Mam nadziejê, ¿e uda ci siê znaleŸæ to czego szukasz - choæby miejsce do ¿ycia. Mam te¿ nadziejê, ¿e wyrzucili ciê z Krypty z powodu twojej g³upoty. Naprawdê wierzê, ¿e mieli inny powód.}
{122}{}{Hng.}
{123}{}{Musisz znaleŸæ inny sposób zdobywania informacji, rozmawianie nie idzie ci najlepiej. Mam nadziejê, ¿e nie skrzywdzisz zbyt wielu ludzi podczas swych podró¿y. Zachowuj siê tu dobrze, nikt z nas nie chce twojej krzywdy.}
{124}{}{Aaach.}
{125}{}{Z przyjemnoœci¹ ci pomogê. Sama by³am kiedyœ taka, jak ty. Mam nadziejê, ¿e moja wiedza na coœ siê przyda.}
{126}{}{Co mogê zrobiæ, gdy odniosê rany?}
{127}{}{Sk¹d wezmê lepszy sprzêt?}
{128}{}{Opowiedz mi o tym miejscu.}
{129}{}{Opowiedz mi o reszcie œwiata.}
{130}{}{Powiedz coœ o sobie.}
{131}{}{Na razie to wszystko, dziêki.}
{132}{}{Jeœli nie ma pod rêk¹ doktora, trzeba sobie radziæ samemu. Stimpaki to popularne œrodki lecznicze. U¿ycie ich pozwala na leczenie l¿ejszych ran. Umiejêtnoœæ Pierwszej Pomocy jest wolniejsza, ale te¿ zawsze dostêpna. Powa¿niejsze rany, takie jak z³amana noga, wymagaj¹ wykorzystania umiejêtnoœci Doktora.}
{133}{}{Musisz robiæ to, co my. Bierz to, co znajdziesz lub handluj. Gdy ktoœ ciê zaatakuje, mo¿e uda ci siê zabraæ coœ twoim wrogom. Jeœli po¿yjesz doœæ d³ugo. Nasza spo³ecznoœæ jest nastawiona pokojowa, wiêc handlujemy, kupuj¹c przede wszystkim to, czego sami nie produkujemy.}
{134}{}{Opowiedz mi o handlu wymiennym.}
{135}{}{Jesteœ w Cienistych Piaskach. To tylko ma³e miasto w wielkim œwiecie. Nie chcemy nic, oprócz spokoju. Poza zmutowanymi zwierzêtami i innymi pustynnymi istotami, k³opoty sprawiaj¹ nam tylko NajeŸdŸcy. Naszym przywódc¹ jest Aradesh. Jeœli chcesz z nim pomówiæ, to znajdziesz go w du¿ym budynku na œrodku.}
{136}{}{Sama wiem bardzo ma³o o œwiecie zewnêtrznym. Uciek³am z Krypty, gdy j¹ zaatakowano. By³am powa¿nie ranna i nie pamiêtam za bardzo, co siê dzia³o. Dharma mnie strzeg³ i znaleŸli mnie miejscowi. Teraz tu mieszkam. Znasz ju¿ Iana? To stra¿nik karawany, który zosta³ ranny. Dochodzi do siebie w stró¿ówce, tam. [Wskazuje na wschód] Wie wiêcej ode mnie o œwiecie.}
{137}{}{Moje ¿ycie by³o bardzo nudne. Wychowa³am siê w Krypcie. ¯y³am tam przez wiele lat. By³o nas zbyt wiele, ¿y³o siê Ÿle. Nast¹pi³ roz³am, wielu ludzi odesz³o, zabrali ze sob¹ najlepszy sprzêt. Niektórzy z nas próbowali pozostaæ w Krypcie. Ale wtedy nas zaatakowano. Zosta³am ranna i trafi³am tutaj. Teraz staram siê byæ pomocna... }
{138}{}{Gdzie znajduje siê twoja Krypta?}
{139}{}{Handel wymienny polega na wymianie dóbr. Ty mi dajesz jakieœ przedmioty, a ja ci w zamian inne. Poniewa¿ to ty inicjujesz transakcjê, pozwolê ci na wybór, czego chcesz. Ale muszê zaakceptowaæ transakcjê, wiêc najlepiej daj mi niepotrzebne ci przedmioty o sporej wartoœci w zamian za tañsze, ale niezbêdne ci rzeczy. Jeœli nie masz doœæ przedmiotów, zawsze s¹ jeszcze kapsle. To jedyna powszechnie stosowana waluta w okolicy. Uznaj¹ je kupcy z Huba, wiêc mo¿na ich u¿ywaæ wszêdzie.}
{140}{}{Krypta-15, Na wschód st¹d. Próbowaliœmy nawi¹zaæ kontakt z innymi Kryptami, ale nam siê nie uda³o. Ci, których wysy³aliœmy zostali prawdopodobnie zaatakowani przez Bandytów. Uwa¿aj!}
{141}{}{Mam nadziejê, ¿e uda ci siê j¹ znaleŸæ. Jest dla mnie jak siostra. Chyba porwa³a j¹ jedna z grup bandytów. Dowiedz siê o nich jak najwiêcej i uzbrój, jak tylko mo¿esz najlepiej, zanim tam pójdziesz. Nie wdawaj siê od razu w bójkê, nawet ich mo¿na czasem przekonaæ...}
{142}{}{Seth próbowa³ œledziæ radskorpiony. Twierdzi, ¿e zna drogê do ich nory, ale chyba trochê siê boi tam chodziæ. Jeden z mutantów powa¿nie rani³ jego brata i nie bardzo wie, co ma robiæ.}
{143}{}{Owszem. Mój dawny dom, Krypta-15, mia³ coœ takiego. Nie by³am tam od kiedy nie zosta³am ranna, ale mo¿e uda ci siê tam znaleŸæ to, czego szukasz. Ktoœ mówi³, ¿e próbowa³ rozejrzeæ siê po Krypcie, ale by³o ciemno i winda by³a zepsuta. Mam nadziejê, ¿e siê przygotujesz.}
{144}{}{Witam ponownie. Mam nadziejê, ¿e wszystko u ciebie w porz¹dku. Czy mogê ci w czymœ pomóc?}
{145}{}{Czy ty nigdy nie sypiasz?}
{146}{}{Zdarzaj¹ mi siê drzemki, gdy siê tu nie krêcisz. Poza tym pustynne powietrze jest bardzo zdrowe i orzeŸwiaj¹ce. Nigdy mnie te¿ nie nudzi patrzenie na gwiazdy. Mo¿esz sobie wyobraziæ ¿ycie, w czasie którego nigdy nie patrzy siê na gwiazdy? [Przerywa, patrz¹c na ciebie] Ach, chyba tak.}
{147}{}{O, tak. Dziêki.}
{148}{}{Czy w okolicy jest jakiœ lekarz?}
{149}{}{Ma³e wioski jak Cieniste Piaski nie prze¿y³yby bez pomocy uzdrowiciela. Nasz lekarz, Razlo, mieszka w najbardziej na po³udnie wysuniêtej chacie. IdŸ do niego, jeœli z tob¹ kiepsko. Tylko nie przeszkadzaj mu w nocy. Strasznie siê wkurza, gdy mu siê nie daje spaæ.}
{150}{}{Za informacje od Katriny zdobywasz 250 punktów doœwiadczenia.}
{151}{}{W tej okolicy z³odziei siê wiesza. Pilnuj siê.}
