{100}{}{You see: Talius, a member of the Followers.}
{101}{}{OdejdŸ, proszê. Próbujê tu odpocz¹æ. Wróæ w czasie dnia.}
{102}{}{Witaj, siostro. Nazywam siê Talius. W czym mogê ci dziœ pomóc?}
{103}{}{Witaj, bracie. Nazywam siê Talius. W czym mogê ci dziœ pomóc?}
{104}{}{Hê?}
{105}{}{Ja }
{106}{}{. Ja }
{107}{}{.}
{108}{}{Nazywam siê }
{109}{}{. Co tu robisz?}
{110}{}{Mo¿esz zdechn¹æ!}
{111}{}{Mn¹ siê nie przejmuj, mutanciaku! Sk¹d siê tu wzi¹³eœ?}
{112}{}{I ja ciê pozdrawiam. Zw¹ mnie }
{113}{}{. Jak trafi³eœ do grona Uczniów?}
{114}{}{Powiedz mi, jak ktoœ z twoimi zmianami trafi³ do Uczniów?}
{115}{}{Widzê, ¿e nie grzeszysz inteligencj¹. Ja te¿ by³em kiedyœ podobny do ciebie pod tym wzglêdem. Jednak dziêki naukom Uczniów uda³o mi siê nadrobiæ te niedostatki.}
{116}{}{Nie wiedzieæ.}
{117}{}{Zbyt m¹dry. Teraz zgin¹æ.}
{118}{}{Przepraszam. Czasami siê zapominam. Mo¿e trochê wsparcia umys³owego?}
{119}{}{Taaa. Tyyyy!}
{120}{}{Taak! Taak!}
{121}{}{Masz. WeŸ te kolorowe kuleczki. Zwiêksz¹ twoj¹ inteligencjê.}
{122}{}{Tak, }
{123}{}{. Z radoœci¹ widzê, ¿e przyjmujesz odpowiedni¹ nomenklaturê. W czym mogê ci dziœ pomóc?}
{124}{}{Cooo?}
{125}{}{Mózg boleæ. Ja ciê zabiæ. Wzi¹æ mózg.}
{126}{}{Jestem tu, aby u³atwiæ tym poczciwcom zrozumienie dzia³añ Dzieci Katedry.}
{127}{}{A wiêc jesteœ po prostu ich szpiegiem?}
{128}{}{Sk¹d w ogóle wiesz o Dzieciach?}
{129}{}{Ale co ty mo¿esz? Jesteœ przecie¿ mutantem.}
{130}{}{Nie, nie jestem ¿adnym szpiegiem. Mimo, i¿ wielu tak s¹dzi. W naszym skromnym domu dzia³a szpieg. Nie jesteœmy go jednak w stanie wykryæ.}
{131}{}{Jak wiêc pomagasz Uczniom?}
{132}{}{Powiedz mi, co wiesz o tym szpiegu. Mo¿e zdo³am pomóc.}
{133}{}{No to masz problem, mutanciaku!}
{134}{}{Chyba wiem, kto jest szpiegiem. Zaraz go usunê.}
{135}{}{Kiedyœ by³em taki, jak ty. Dziêki kontaktom z Mrocznymi w Nekropolis sta³em siê tym, kim jestem dzisiaj.}
{136}{}{To straszne. Pech to pech. Do zobaczenia.}
{137}{}{Co robi³eœ w Nekropolis?}
{138}{}{Sk¹d pochodzisz?}
{139}{}{Zaraz poddam ciê kolejnej transformacji. Oby ci ziemia lekk¹ by³a...}
{140}{}{Dawno temu mieszka³em w miejscu daleko na pó³noc st¹d. Mieli k³opoty ze Ÿród³ami wody i potrzebowali osób, które by mog³y by je naprawiæ.}
{141}{}{A ty zg³osi³eœ siê na ochotnika.}
{142}{}{Gdzie konkretnie jest to miejsce?}
{143}{}{I co, rozwi¹za³eœ ten problem?}
{144}{}{Wiêc jak trafi³eœ do Nekropolis?}
{145}{}{Tak. Opiekun spo³ecznoœci wrêczy³ mi strzelbê i trochê nabojów. Zaginê³y w toku moich podró¿y. Jako, ¿e nic nie uda³o mi siê znaleŸæ, nie mog³em wróciæ.}
{146}{}{To straszne. ¯a³ujê, ¿e nic nie mogê zrobiæ.}
{147}{}{Kiepsko. Czas na mnie.}
{148}{}{Gdzie konkretnie jest to miejsce?}
{149}{}{I co, rozwi¹za³eœ problem z wod¹?}
{150}{}{Dlaczego poszed³eœ do Nekropolis?}
{151}{}{Jest sposób, w jaki mo¿esz mi pomóc. Trzeba powstrzymaæ tego, kto mi to zrobi³.}
{152}{}{Czyli kogo?}
{153}{}{Ich przywódca to dowódca armii mutantów. Chwyta on ludzi i wystawia ich na dzia³anie mutagenu. Nie jestem pewien, jak - zosta³em wczeœniej og³uszony.}
{154}{}{Zabijê go dla ciebie.}
{155}{}{Brzmi zbyt ryzykownie. Zmywam siê.}
{156}{}{Dziêkujê ci za ³askê. Bardzo mi siê przys³u¿ysz. Przyjmij ten podarunek. Znalaz³em go przy ciele martwego renegata.}
{157}{}{IdŸ zatem w pokoju. Rozumiem twoje w¹tpliwoœci. Byæ mo¿e ktoœ inny wyzwoli œwiat od tej groŸby. ¯egnaj.}
{158}{}{To miejsce znajduje siê w górach na pó³nocy. To ma³a Krypta, w której ¿y³o wiele osób.}
{159}{}{I co, rozwi¹za³eœ problem wody?}
{160}{}{Dlaczego poszed³eœ do Nekropolis?}
{161}{}{Jak siê nazywa³a ta Krypta?}
{162}{}{Dobra. Muszê lecieæ.}
{163}{}{Niestety nie. S³ysza³em, ¿e póŸniej wys³ano innych, aby znaleŸli sposób na naprawê pompy.}
{164}{}{Nie uda³o mi siê o nich nic wiêcej us³yszeæ.}
{165}{}{Dlaczego poszed³eœ do Nekropolis?}
{166}{}{Jak siê nazywa³a ta Krypta?}
{167}{}{Dobra. Muszê lecieæ.}
{168}{}{S³ysza³em od innych podró¿ników, ¿e Nekropolis mia³o sposób na ³atw¹ produkcjê wody.}
{169}{}{Wiêc poszed³em tam, aby zobaczyæ, jak to robi¹.}
{170}{}{I czego siê dowiedzia³eœ?}
{171}{}{Pozabija³eœ ich?}
{172}{}{Dobrze siê tu czujesz?}
{173}{}{Dowiedzia³em siê, ¿e to miejsce jest pe³ne mutantów. To oni mnie schwytali i doprowadzili do obecnego stanu.}
{174}{}{Musieli jednak coœ pomyliæ, bo mój dalszy rozwój przebiega zgodnie z innym cyklem ewolucyjnym.}
{175}{}{Kiepska sprawa. Do zobaczenia.}
{176}{}{Z pewnoœci¹ bêdê na nich uwa¿aæ. Dziêki za cynk.}
{177}{}{Kto im przewodzi?}
{178}{}{Nie. Zabi³em tylko kilku mutantów. Inny mutant, ghul imieniem Set pomóg³ mi i wykoñczy³ wiêkszoœæ.}
{179}{}{Z tego, co wiem, zosta³o ich tam ju¿ tylko kilku.}
{180}{}{Brzmi œwietnie. Do zobaczenia.}
{181}{}{Ju¿ ich nie ma. U Seta wszystko w porz¹dku.}
{182}{}{To rzeczywiœcie dobre wiadomoœci. Z radoœci¹ pryzmujê zniszczenie z³a i uwolnienie miasta. Proszê, weŸ to.}
{183}{}{Sarkazm i ciêty jêzyk nie zmieni¹ mojego dobrodusznego nastroju. Nadszed³ czas rozstania. ¯egnam.}
{184}{}{Mojs Krypta nie mia³a nazwy. Mia³a tylko numer - 13.}
{185}{}{Ja równie¿ pochodzê z tej Krypty!}
{186}{}{Nigdy nie s³ysza³em o tym miejscu.}
{187}{}{Dziêki za informacje. Teraz idê opowiedzieæ o tym mutantom...}
{188}{}{Naprawdê? Czy¿by Opiekun wreszcie opamiêta³ siê i pozwoli³ ludziom na opuszczanie Krypty?}
{189}{}{Nie, wci¹¿ boi siê œwiata zewnêtrznego.}
{190}{}{Nie, boi siê o bezpieczeñstwo mieszkañców.}
{191}{}{Tak, s¹dzi, ¿e niebezpieczeñstwo ju¿ minê³o.}
{192}{}{Tak te¿ s¹dzi³em. Zawsze by³ ostro¿ny. Wspó³czujê mu spoczywaj¹cej na nim odpowiedzialnoœci. Oby lepiej ni¿ mi posz³o ci wykonywanie zlecenia tego g³upca...}
{193}{}{Cieszê siê, ¿e przejrza³ wreszcie na oczy i pozwoli³ ludziom wyjœæ. Nie jest tu wprawdzie bezpiecznie, ale przyda siê odbudowa ziemi. ¯egnaj, przyjacielu.}
{194}{}{Trudno, ¿eby by³o inaczej, bior¹c pod uwagê, ¿e pochodzisz z zewn¹trz. Muszê ju¿ iœæ. Uwa¿aj proszê na istoty, które szerz¹ zniszczenie.}
{195}{}{Nie s¹dzê, aby mia³o ci siê to udaæ.}
{196}{}{Spróbuj mnie powstrzymaæ.}
{197}{}{Dlaczego tak twierdzisz?}
{198}{}{Bo to ja ciê powstrzymam.}
{199}{}{Wiem bardzo ma³o. Tylko tyle, ¿e nasi zwiadowcy s¹ jedynymi, którzy kontaktuj¹ siê z Dzieæmi i ich szpieguj¹. Nikomu innemu siê na to nie pozwala z powodu niebezpieczeñstwa.}
{200}{}{A wiêc mo¿e to zwiadowca? Zajmê siê tym.}
{201}{}{S¹dzê, ¿e to ty. Giñ!}
{202}{}{Wola³bym, aby twoja inteligencja by³a wiêksza. Niewa¿ne, i tak szybko siê ciebie pozbêdê.}
{203}{}{All I know of the Children is that they are in league with the Nightkin, a nasty kind of Super Mutants.}
{204}{}{To oni mnie zmienili w Nekropolis.}
{205}{}{To straszne. Pech to pech. Do zobaczenia.}
{206}{}{Co robi³eœ w Nekropolis?}
{207}{}{Sk¹d pochodzisz?}
{208}{}{Zaraz poddam ciê kolejnej transformacji. Oby ci ziemia lekk¹ by³a...}
{209}{}{Mimo, i¿ mój wygl¹d jest odra¿aj¹cy, wci¹¿ mogê przekazaæ spor¹ wiedzê tym, którzy chc¹ s³uchaæ.}
{210}{}{Nie mam na to czasu, sp³ywam st¹d.}
{211}{}{Co mi powiesz?}
{212}{}{Ci, których Uczniowie i Dzieci nazywaj¹ Mrocznymi, nie s¹ tym, czym siê wydaj¹. Stworzy³ ich ktoœ zwany Porucznikiem. S¹dzê, ¿e mo¿e podlegaæ jeszcze komuœ.}
{213}{}{To dopiero informacje. Idê st¹d.}
{214}{}{Co mi mo¿esz powiedzieæ o tym Poruczniku?}
{215}{}{Nie wiem o nim zbyt wiele. Gdy widzia³em go po raz ostatni - przed moj¹ transformacj¹, szuka³ 'czystych' istot ludzkich.}
{216}{}{Przemyœlê to. Dziêkujê.}
{217}{}{Nie podejrzewasz, jakie mo¿e mieæ ku temu powody?}
{218}{}{Nie jestem jeszcze pewien. Mo¿e inna grupa próbuj¹ca im przeszkadzaæ bêdzie coœ wiedzieæ.}
{219}{}{Dziêkujê. ¯egnam.}
{220}{}{Przykro mi, ale nie tolerujê bezczelnoœci. Wynoœ siê.}
{221}{}{Mój akces do Uczniów nie by³ czymœ skomplikowanym. To oni oszczêdzili mi pe³nych efektów transformacji w potworn¹ bestiê.}
{222}{}{Nie do koñca rozumiem. Kontynuuj.}
{223}{}{Jak wiesz, niegdyœ by³em tym, czym ty teraz - czystym cz³owiekiem. Ale dziêki interwencji Mrocznych zabrano mnie daleko st¹d.}
{224}{}{Mów dalej.}
{225}{}{Mój stan nie pozwala³ na szczegó³owe obserwacje rozwoju wypadków. Wiem tylko, ¿e gdy siê obudzi³em, by³em pod opiek¹ dobrego lekarza.}
{226}{}{Twoje prze¿ycia napawaj¹ mnie prawdziwym smutkiem. Znajdê tych, którzy s¹ za nie odpowiedzialni i naprawiê tê sytuacjê.}
{227}{}{Przykro mi to s³yszeæ. Niestety, doœæ mam zajêcia, próbuj¹c prze¿yæ. ¯egnam.}
{228}{}{Proszê ciê, rozpraw siê z niegodziwcem, który próbuje zniszczyæ zaufanie Wyznawców.}
{229}{}{Gratulujê ci pozbycia siê z naszych szeregów tej wywrotowej Heather.}
{230}{}{Widzisz potwornego ghula.}
{231}{}{W jakiœ sposób kogoœ ci przypomina.}
{232}{}{Niestety, nie mogê ci poœwiêciæ ani chwili d³u¿ej. ¯egnam.}
