{100}{}{Stanowisko Bezpieczeñstwa}
{101}{}{Ten terminal, 'Tylier', kontroluje Operacje Si³ Specjalnych. Przygotuj siê na identyfikacjê g³osu.}
{102}{}{Nuna!}
{103}{}{Pomocy. Ja mieæ kuku.}
{104}{}{Wpuœæ mnie.}
{105}{}{Nazywam siê }
{106}{}{. Proszê o pozwolenie na przejœcie.}
{107}{}{Co tu robisz?}
{108}{}{Identyfikacja g³osu negatywna. Status systemów bezpieczeñstwa: uzbrojone.}
{109}{}{Jestem systemem zabezpieczeñ Poziomu Niebieskiego. Wszystkie systemy uzbrojone.}
{110}{}{Czy mo¿esz je dezaktywowaæ?}
{111}{}{Dlaczego systemy s¹ uzbrojone, skoro wojna ju¿ siê skoñczy³a?}
{112}{}{Dziêkujê.}
{113}{}{Zaprogramowano mnie tak, aby wszystkie systemy by³y uzbrojone, dopóki upowa¿niony do tego personel nie wprowadzi w³aœciwego kodu g³osowego.}
{114}{}{Zdezaktywujesz dla mnie te systemy?}
{115}{}{¯egnam.}
{116}{}{Has³o obejœcia: Gamma Delta Delta. Dezaktywuj wszystkie systemy.}
{117}{}{Nie masz upowa¿nienia. Brak dostêpu.}
{118}{}{Niew³aœciwy kod. Brak dostêpu.}
{119}{}{Has³o obejœcia: Gamma Omikron Delta. Dezaktywuj wszystkie systemy.}
{120}{}{Has³o obejœcia: Omikron Delta Delta. Dezaktywuj wszystkie systemy.}
{121}{}{Has³o obejœcia: Alfa Delta Delta. Dezaktywuj wszystkie systemy.}
{122}{}{Has³o obejœcia: Delta Omikron Gamma. Dezaktywuj wszystkie systemy.}
{123}{}{Do widzenia.}
{124}{}{Potwierdzam has³o obejœcia. Systemy zabezpieczeñ dezaktywowane.}
{125}{}{Nie wprowadzono innych rozkazów. Brak dostêpu do sieci; najwyraŸniej zniszczeniu uleg³ g³ówny procesor, ZAX.}
{126}{}{Dobrze. Has³o obejœcia: Sigma Alfa Delta. Dezaktywuj wszystkie systemy.}
{127}{}{Do widzenia.}
{128}{}{Systemy zabezpieczeñ s¹ wy³¹czone.}
