{100}{}{Widzisz mieszkañca Krypty 13.}
{101}{}{Jak wygl¹da œwiat na zewn¹trz?}
{102}{}{Có¿ za odwaga! Opuszczaæ Kryptê!}
{103}{}{Opiekun mówi, ¿e œwiat zewnêtrzny jest niebezpieczny.}
{104}{}{Musisz uwa¿aæ na siebie gdy ju¿ opuœcisz schron.}
{105}{}{OdwiedŸ lekarza, jeœli odniesiesz obra¿enia.}
{106}{}{Opiekun dba o to, ¿eby wszystkim w Krypcie by³o dobrze.}
