{100}{}{Na zachodzie widzisz œwiat³o dzienne. Po raz pierwszy w swoim ¿yciu patrzysz na œwiat zewnêtrzny.}
{101}{}{Na zachodzie widzisz rozgwie¿d¿one niebo. Po raz pierwszy w swoim ¿yciu patrzysz na œwiat zewnêtrzny.}
