{100}{}{You see a businessman. You are unsure the nature of his business.}
{101}{}{W czym mogê pomóc?}
{102}{}{Hunh?}
{103}{}{Kim jesteœ?}
{104}{}{Co siê dzieje w tym budynku?}
{105}{}{Vance, right? I heard you've got what I need. Can I score some?}
{106}{}{Nothing. Bye.}
{107}{}{Nazywam siê Vance - to wszystko, co musisz wiedzieæ. Czego sobie ¿yczysz?}
{108}{}{Sk¹d mam wiedzieæ, skoro mi nie mówisz, co sprzedajesz?}
{109}{}{Mi³o ciê poznaæ. Co sprzedajesz?}
{110}{}{Me wan' stuff.}
{111}{}{No. Bye.}
{112}{}{Skoro jeszcze tego nie wiesz, to nie powinno ciê tu byæ. IdŸ sobie.}
{113}{}{PÓJDÊ, KIEDY BÊDÊ MIEÆ TAKIE ¯YCZENIE! ID DO DIAB£A!}
{114}{}{Okay. I'll leave.}
{115}{}{'Nothing' is right! Don't waste my time. Now get out of here!}
{116}{}{Spróbuj mnie zmusiæ, popaprañcu!}
{117}{}{Okay okay... I'm leavin'.}
{118}{}{Yeah, you seem okay. Here's what I've got.}
{119}{}{He eyes you suspiciously.}
{120}{}{Oh hey. Always nice to see repeat customers. What can I do for you?}
{121}{}{Chcieæ wiêcej.}
{122}{}{Chcê dokonaæ wiêkszych zakupów.}
{123}{}{Nie lubiê takich jak ty.}
{124}{}{Kim s¹ twoi kumple?}
{125}{}{Kim s¹ twoi kumple na zapleczu?}
{126}{}{Tylko siê rozgl¹dam.}
{127}{}{Przykro mi to s³yszeæ. IdŸ sobie.}
{128}{}{NIE!}
{129}{}{Ju¿ idê.}
{130}{}{To Justin i Chad. Pilnuj¹, ¿eby nikt nie sprawia³ k³opotów.}
{131}{}{Wygl¹daj¹ mi na g³upie cioty.}
{132}{}{Mi³o was poznaæ.}
{133}{}{Pokrêcê siê trochê po okolicy, jeœli nie macie nic przeciwko.}
{134}{}{To moi kumple. To wszystko, co musisz wiedzieæ. Nie zadawaj zbyt wielu pytañ.}
{135}{}{Dobrze. Co sprzedajesz?}
{136}{}{Wiem, co tu wyrabiacie i wcale mi siê to nie podoba.}
{137}{}{Pokrêcê siê trochê po okolicy, jeœli nie macie nic przeciwko.}
{138}{}{Zajmijmy siê interesami.}
{139}{}{Dobra, co tam masz?}
{140}{}{Chyba trochê siê tu pokrêcê.}
{141}{}{You're not welcome here! Get out before things get ugly.}
{142}{}{Zaraz ciê wyœlê do piek³a - bêdziesz tam pasowaæ.}
{143}{}{Przykro mi. Przepraszam.}
{144}{}{Hej, uspokój siê. Nie zrozumieliœmy siê. Porozmawiajmy.}
{145}{}{Nie ¿yczê sobie ¿adnych k³opotów, wiêc chyba lepiej bêdzie, jak sobie pójdziesz, zanim zrobiê coœ, czego móg³byœ ¿a³owaæ.}
{146}{}{No, me stay.}
{147}{}{Do-o-bra. Iœæ.}
{148}{}{Nic mnie nie obchodz¹ twoje ¿yczenia.}
{149}{}{Alright, alright, I'm leaving.}
{150}{}{Nie zu¿yj wszystkiego naraz.}
{151}{}{Thanks, take it easy.}
{152}{}{Ug?}
#
# Fallout Fixt:
#
{153}{}{Who the hell are you and what the fuck are you doing in my place?}
{154}{}{Me }
{155}{}{. [smile] ...who u?}
{156}{}{! [glare] wHo *you*?}
{157}{}{Too many binges of Psycho, eh? Can't say I haven't seen that before. [laughs] }
{158}{}{Great, another burnt-out braindead junkie. Get the fuck out of here.}
{159}{}{Ungh!}
{160}{}{Justin, Chad, let's show this asshole how we deal with their kind...}
{161}{}{me Want some.}
{162}{}{Nuuhhh... buh-bye.}
