{100}{}{W tym fragmentem pod³ogi jest coœ dziwnego.}
{101}{}{Nie zauwa¿asz niczego wyj¹tkowego.}
{102}{}{W oddali rozlega siê alarm.}
{103}{}{U stóp masz jakiœ czujnik.}
{104}{}{Uda³o ci siê rozbroiæ czujnik.}
{105}{}{Nie uda³o ci siê rozbroiæ czujnika.}
