{100}{}{Zauwa¿asz tabliczkê mówi¹c¹, ¿e winda nie dzia³a.}
{101}{}{Widzisz tabliczkê na drzwiach mówi¹c¹, ¿e nie dzia³aj¹.}
{102}{}{Tabliczka mówi: Uwaga: Budowa szybu windy. Prosimy skorzystaæ z innej.}
