# {100}{}{You see an elevator door with blue markings on it.}
# {101}{}{You are shocked by the security system, but sustain no damage. Perhaps you should try using something to bypass the security system.}
# {102}{}{You are shocked by the security system, and sustain a point of damage. Perhaps you should try using something to bypass the security system.}
# {103}{}{You are shocked by the security system, and sustain }
# {104}{}{ points of damage. Perhaps you should try using something to bypass the security system.}
# {105}{}{You disarm the security system on the door.}
# {106}{}{That item has no effect on the door.}
{100}{}{你看到这个电梯门上有个蓝色标记。}
{101}{}{你触发了电子保安系统，但是没有受到伤。也许你该试试别的办法来解除这个电子保安系统。}
{102}{}{你触发了电子保安系统，并且受了伤。也许你该试试别的办法来解除这个电子保安系统。}
{103}{}{你触发了电子保安系统，并且受到}
{104}{}{点伤害。也许你该试试别的办法来解除这个电子保安系统。}
{105}{}{你解除了门上的电子保安系统。}
{106}{}{那东西在门上没用。}