{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Gunther.}
#{101}{}{You see a stern man in his thirties.}
#{102}{}{Welcome to my humble house.  What can I do for you?}
#{103}{}{Could you tell me a little about the Hub?}
#{104}{}{Where can I find some ammo and weapons around here?}
#{105}{}{What do you do around here?}
#{106}{}{Who's the law around here?}
#{107}{}{Sure, what else would you like to know?}
#{108}{}{It is a sprawling city, the largest I have seen in my life.  The center of the town lies to the south, with the other areas branching off in each direction from there.}
#{109}{}{Where can I find supplies?}
#{110}{}{If I was looking for a job, where would be a good place to start?}
#{111}{}{Can I ask you another question?}
#{112}{}{Thanks for the info.  Goodbye.}
#{113}{}{I get everything that I need from Mitch down by the Maltese Falcon.  Just head on south from here.}
#{114}{}{I occasionaly do a stint on one of the caravans that head out from here.  If you're looking for that kind of work, just talk to one of the trading houses. 'm partial to the Far Go Traders, but I've worked with all of them.}
#{115}{}{Well, I buy most of my stuff from Beth over in the Weapon Store.  Got a pretty good selection.}
#{116}{}{What would I do if I was looking for something a little more 'exotic'.}
#{117}{}{Will mentioning your name help with the price?}
#{118}{}{I've heard there is some guy over in Old Town that deals in stuff with a little more punch.}
#{119}{}{Probably not, she's sweet on her bodyguard Sid.  But, you might want to try Butch, he runs the Far Go Traders - which owns her store.}
#{120}{}{I get by.  I hire on with the caravans when I'm a little short on cash, and work for the farmers down south a bit.}
#{121}{}{Well, you probably passed Deputy Fry on your way down here.  His boss is Sheriff Greene, and you'll find him in the Police Station most of the time.}
#{122}{}{Coookkiieee!}
#{123}{}{I'm sorry, but you're not making any sense.  Maybe Dr. Thorndyke with the Children can help you.}

{100}{}{你看到了刚瑟。}
{101}{}{你看到了一个30多岁，神态严厉的男子。}
{102}{}{欢迎来到我的陋室。我能为你做些什么？}
{103}{}{我想知道一些哈勃城的事情。}
{104}{}{我能在哪里找到武器装备？}
{105}{}{你在这里是干什么的？}
{106}{}{这里谁是领导者？}
{107}{}{当然，你还想知道什么？}
{108}{}{这是一个大都会，也是我见过的最大的城市。城市的中心位于南部，其他的部分伸向城市的四面八方。}
{109}{}{我能在哪里找到补给？}
{110}{}{如果我只是想找个工作，哪里比较适合我？}
{111}{}{我想知道一些别的事情。}
{112}{}{谢谢你，再见。}
{113}{}{我需要的每件东西都是从马耳他猎鹰的米奇那弄来的。从这里向南走，你会找到它。}
{114}{}{我偶而会为这里的商队做事。如果你正在找那种工作，你可以和商队的人谈谈。我个人喜欢远行商队，不过我已经为他们工作了。}
{115}{}{我要的大部分东西在贝斯的武器店里买到的。那是一个很好的去处。}
{116}{}{我能到哪里找到一些特别的“刺激”呢？}
{117}{}{提你的名字会便宜点吗？}
{118}{}{我听说有一些家伙在旧城区附近交易一些特别的东西。}
{119}{}{可能不行，她对他的保镖希德情爱有加。但是你可以去找布奇，他管理远行商队-那家雇用她的商店就是远行商队的。}
{120}{}{我明白了。我身上没钱的时候就加入商队，为南面的农民干点活。}
{121}{}{你来这里的路上可能没看到代理警长佛莱，他老板是格林警官，你应该可以在警局找到他。}
{122}{}{饼饼饼饼饼饼饼饼~干干干干干干干【结巴】！}
{123}{}{没办法，我不知道你在说什么，也许大教堂之子的索恩·戴克医生应该能帮你。}


