{100}{}{你看见一个老妇人。}
{101}{}{你看见阿加莎。}
{102}{}{这个女人头发灰白并且脸上布满皱纹，但步伐灵活，个性爽朗。}
{103}{}{你是一个坏人。我不会和你有什么关系。}
{104}{}{我们的年轻人被威胁，实在糟透了。失去坦蒂也是件可怕的事。}
{105}{}{哼~~嗯。}
{106}{}{好吧。}
{107}{}{为什么？}
{108}{}{什么意思？}
{109}{}{我知道你会尽力的，亲爱的，找到坦蒂，帮她逃出那些野蛮人的魔掌，让她回到亚拉德什身边。你会帮这个小镇一个大忙，好人也会有好报。}
{110}{}{亚拉德什很爱他的女儿。也正是这股爱使这个男人成为这个镇的支柱。失去这种爱，他会迷茫，并且沙荫镇肯定也会随之如此……}
{111}{}{我会尽力的。再见。}
{112}{}{我很想帮忙。}
{113}{}{嗯……再见。}
{114}{}{我觉的她被关起来了。她是仇恨的目标。这种仇恨在东南方非常强烈。我肯定你能在那里找到她。祝你好运。}
{115}{}{谢谢。}
{116}{}{你没听说吗？坦蒂失踪了。我觉得她被绑架了。亚拉德什忧心如焚。真是一件可怕的事……}
{117}{}{听说你救了坦蒂。你做得很好。你的命很硬。我感觉你的未来很有希望。}
{118}{}{我对坦蒂的事很遗憾。她是一个那么有朝气的姑娘。她应该活得更好。}
{119}{}{你好。你一定就是那个所有人都在谈论的外地人。【阿加莎叹息】 我有什么能帮你吗？}
{120}{}{嗯。}
{121}{}{你是谁？}
{122}{}{你看起来很疲倦。这里出了什么问题吗？}
{123}{}{为什么你看起来这么疲倦？}
{124}{}{别跟我说，老女人。}
{125}{}{你需要的帮助超出了我的能力，我的孩子。愿达玛与你同在。}
{126}{}{我的名字是阿加莎. 我是沙荫镇的说书人。我的工作就是记录历史，让大家记住并且永不遗忘。}
{127}{}{给我讲一个故事。}
{128}{}{好吧，随便。}
{129}{}{能不遗忘真好。}
{130}{}{我很抱歉，孩子。我现在很疲倦。我需要休息。请过会儿再来。}
{131}{}{千真万确。【阿加莎盯了你一会儿。】 对于年轻人记住历史是好事，但是要在历史的洪流里扮演一个角色却是非常困难的。有些时候，我们所走的路在很久以前就已经就被某些事情所决定了。愿达玛与你同在。我必须休息一小会儿了。过会儿再来，当我有气力时，我们再谈。}
{132}{}{谢谢你提到这点。我已经很老了，这就是为什么。我不能在晚上入睡。当我合上我的眼睛……【阿加莎停了一下。】但是我就是不能睡着。请你理解，我已经是一把老骨头的人了……}
{133}{}{我很抱歉，我非常疲倦。请你过会儿再来好吗？}
{134}{}{再见。}
{135}{}{好吧。}
{136}{}{为什么你这么疲倦？}
{137}{}{我在晚上没有睡好，我的孩子。一定是因为我太老了。}
{138}{}{你好，我的孩子。你看起来不错。你让我想起了我的小孩。}
{139}{}{嗯。}
{140}{}{那么，我想听一个故事。}
{141}{}{我很高兴你感觉好点了。}
{142}{}{谢谢。再见。}
{143}{}{你确实让我想起了我自己的小孩。当她只有几个月大时，实在是像极了。}
{144}{}{谢谢你。达玛总是说，旺季过后，种下礼貌的农夫会更好过。}
{145}{}{请给我讲一个故事。}
{146}{}{这个达玛的家伙听起来像个傻瓜。}
{147}{}{你侮辱了你的长辈。你应该更清楚这点。}
