{100}{}{你看见杂货店的米奇。}
{101}{}{今天我有什么能为你效劳吗？}
{102}{}{我想买点东西。}
{103}{}{我想卖点东西。}
{104}{}{没什么事。谢谢。}
{105}{}{转转。}
{106}{}{好，这是我的货。}
{107}{}{很好，我总爱寻求新东西。}
{108}{}{抱歉，我听不明白。当你变聪明点再回来吧。}
{109}{}{谢谢。下次再来。}
{110}{}{你看见武器商杰克。}
