{100}{}{你看见唐。}
{101}{}{你看见一个大个子的教堂教徒。}
{102}{}{男子}
{103}{}{女子}
{104}{}{【完成】}
{105}{}{【更多】}
{106}{}{抱歉哥们儿，上了我们的船就没回头路了。该走了！}
{107}{}{抱歉姐们儿，上了我们的船就没回头路了。该走了！}
{108}{}{我为什么要和到处杀小孩的人说话？从我面前消失！}
{109}{}{我听说你很强。但那不能让唐感兴趣。你是有话要说还是就开搞？快点！}
{110}{}{安静，兄弟！我只是查看一下这地方。}
{111}{}{我不在乎怎么引起你的兴趣。有话快说！}
{112}{}{开搞？先生，我不是为了这些瘦孩子而来的。}
{113}{}{你想要什么？}
{114}{}{你话太多了。}
{115}{}{你想找死，我想杀人。我有活干了。}
{116}{}{哇！}
{117}{}{老兄，我已经说过了！去别的地方吧！}
{118}{}{男孩}
{119}{}{女孩}
{120}{}{嗨，你觉得武器会让你出人头地？它只会让你踏进棺材，老兄。把它拿开。}
{121}{}{嗨，你觉得武器会让你出人头地？它只会让你踏进棺材，姑娘。把它拿开。}
{122}{}{你想要什么，你这蠢货？从我面前消失，不然我打烂你。}
{123}{}{我在找一个够聪明的人，能告诉我这里究竟发生了什么！}
{124}{}{如果牧师听到你说这些话，他们会怎么说？}
{125}{}{随时奉陪，朋友。我一直在等一场好斗呢！}
{126}{}{嗨，有什么问题？来点喝的，我们交个朋友！}
{127}{}{你知不知道，只要在你膝盖的某点准确的用点力，一个小孩也能让你一辈子成瘸子？你可能想知道这点吧。}
{128}{}{你想和唐说话？好吧。不过如果我听到了“赞美”这个词，我会杀了你。}
{129}{}{你不信教吧？}
{130}{}{你有什么问题，朋友？}
{131}{}{我想和主管说话。}
{132}{}{当然。我唯一想赞美的是一瓶蝎子汁。}
{133}{}{好吧。我们中谁先说那个词的就得死。怎么样？}
{134}{}{你好，小姐。我是唐，主教的最强战士。我也被FEV改造成了别的东西，这点你会知道的。我们开搞吧，宝贝。}
{135}{}{决不可能。}
{136}{}{这有点太快了。我们先互相了解一下。}
{137}{}{你好。我被FEV改造了，所以任何烦我的人都得死。别烦我，小子。}
{138}{}{去别的地方吧。唐不喜欢你陪着。}
{139}{}{好吧。你想开门见山？有时候杀人是必须的。有时候我甚至喜欢杀人。但我听说你酷爱杀人……任何时候。每次我碰到一个疯子，不是他死，就是唐死。唐现在还活着。所以你还是去别的地方吧。}
{140}{}{老兄，我可能会喜欢上你。你要不是个英雄，就是个极品混蛋。两样唐都喜欢，只要你不给我惹麻烦。你想加入我们吗？}
{141}{}{和平和爱也不管了？}
{142}{}{有什么好处？}
{143}{}{决不，朋友。}
{144}{}{我想惹什么麻烦就惹，想在哪里就在哪里。所以让麻烦见鬼去吧！}
{145}{}{来看你吃苦头。来吧，老兄，给我点我想要的东西。}
{146}{}{你要小心你要的东西。你可能不会喜欢的。}
{147}{}{我愿意成为你的朋友。}
{148}{}{你不值得我花功夫。}
{149}{}{来吧，你先动手。我最后动。}
{150}{}{好吧。话都说完了。动手吧。}
{151}{}{我只想说话。}
{152}{}{你去死……}
{153}{}{操！你比僵尸还蠢！快滚吧！}
{154}{}{主教想要和平，他要我们为他取得和平，所以我们就有乐子找了。明白?}
{155}{}{是的，但还有更多的事情。}
{156}{}{主教是真的想要和平还是只想要杀戮？}
{157}{}{这个主教是谁？}
{158}{}{听起来很不错。}
{159}{}{去你妈的主教！我们把他们都干掉！}
{160}{}{兄弟，别问错问题。他们只告诉你他们想说的事。问错问题的人，惹麻烦的人，嗯，他们在这里都呆不长。}
{161}{}{我做我的事。他们喜欢我做事。他们喜欢街头的混混和末世论者都死绝。这让夜行团能去做别的事。别把我扯进去……这不好。}
{162}{}{你穿得像个僵尸干什么？如果你有礼貌，你得把它表示出来！}
{163}{}{老兄，我并不在乎衣服。我只想知道这里发生了什么！}
{164}{}{如果你不是他们想要昄依的人，他们就不会太在意你。}
{165}{}{不关你的事，朋友。}
{166}{}{我是在想昄依。}
{167}{}{这不是你的礼貌. 这是想找死。}
{168}{}{我们在这里不喝酒。夜行团不喜欢。你最好在和唐谈话前能明白些基本的道理。}
{169}{}{你疯了！我差不多喜欢你了，不过我感觉和你扯上关系的人都活不长。快给我出去。}
{170}{}{你在这呆几个月就会变得和他们一样疯。你想从唐那里得到些什么？}
{171}{}{这些人怎么会变成这个样子的？}
{172}{}{我想要性和没有性的暴力。你知道哪里有？}
{173}{}{我在这里把它弄丢了，而我不需要你帮我。快走开。}
{174}{}{那是墨菲斯。他除了布道，一直呆在楼上。他也不常布道。他很聪明，也是个成功者，这才最关键。你自己去找他吧。}
{175}{}{你得去晒骨场，朋友。这里没有，我已经看过了！}
{176}{}{同意。唐能为你做什么？}
{177}{}{婊子！你不知道你正失去什么！滚出去！}
{178}{}{对它来说生命太短了。我来告诉你为什么你不该等。}
{179}{}{但我要找到知道发生了什么的人。}
{180}{}{不，谢了。不过我不介意做朋友。}
{181}{}{快滚蛋，你这废物。}
{182}{}{当然。}
{183}{}{生命比你想的还短。去死吧，杂种！}
{184}{}{我不是小人物，婊子！}
{185}{}{谁相信那些胡扯？他们得设法让这些白痴相信那些鬼话。}
{186}{}{那是怎么发生的？}
{187}{}{真的？}
{188}{}{这些废物。}
{189}{}{多跟我说些你那队人的事。}
{190}{}{好吧，我加入。}
{191}{}{总得有人结束他们的不幸。就像我……}
{192}{}{我们一得到命令，就出去杀人。杀那些末世论者或者更危险一点的帮派之类。}
{193}{}{所以末世论者是个问题？}
{194}{}{这听起来很恶心。}
{195}{}{谁需要命令？为什么不直接杀了他们？}
{196}{}{好吧。随你干什么。不过我得在这里变糟之前离开。}
{197}{}{你这讨厌的杂种。你比迦克镇的人还坏。滚出去。}
{198}{}{还要知道什么？我吃得好，睡得好，杀了以前惹我的人。你还能从生活中得到更多吗？}
{199}{}{谁知道？谁在乎？我吃得好，睡得好，杀了以前惹我的人。你还能从生活中得到更多吗？}
{200}{}{呣，唐从没想过那个。不过如果他们太烦我，我就干掉他们。他们就不能再烦唐了。他们想要什么？}
{201}{}{昄依？嗯，祝你好运。你需要这个。}
{202}{}{为什么我需要好运？}
{203}{}{听起来不好。}
{204}{}{多谢。你是真正的朋友。}
{205}{}{只有我有弹药，我就不需要好运。}
{206}{}{这些人，这些僵尸，他们也不总是这样子。有些我都能忍受。一旦他们昄依了，一些人出来就成了这样子。还有一些人根本就没出来。唐不喜欢，但这些人给了唐很多。}
{207}{}{为什么你在第一人称和第三人称之间不停地变换？}
{208}{}{告诉我更多有关昄依的程序。}
{209}{}{你通过昄依的程序了吗？}
{210}{}{这个地方很便宜。}
{211}{}{真的，多少？}
{212}{}{没人敢对我做这个！}
{213}{}{你和墨菲斯或者拉舍尔谈吧，如果你去打扰唐，唐会让你吃不了兜着走的。}
{214}{}{好了宝贝，发生了什么？发生的就是许多僵尸在唱圣歌，许多人死了，大教堂教徒要接管所有东西。还有就是你和我，没别的了！}
{215}{}{但是巴拉卡斯，亲爱的，肯定还有更多的事发生了……}
{216}{}{喔，唐！}
{217}{}{算了吧，马屁精。你不是我喜欢的那种。}
{218}{}{没别的了？喔，不！我想知道关键的！}
{219}{}{很不幸，这是地球上最糟的体验唐所做的事的地方。僵尸太多了，我不能随便就说。等我想到一个更安全的地方再跟你说……}
{220}{}{你很快就会知道楼上发生了什么。如果你够强，你会很安全地通过。唐就是这样，唐现在很安全！}
{221}{}{喔……我什么也没说。你最好忘了唐和你说的话，要不然唐就会让你永远地忘记的！}
{222}{}{他们以前也是哀诉者。但是唐说的太多了。你快走吧。}
{223}{}{很好。你老老实实等着我发话，然后我们乐一乐。}
{224}{}{他们是些懦夫。他们伏击我们的巡逻队。他们派遣间谍和破坏分子。他们知道他们赢不了真正的战争。主教说我们应该为他们感到难过，但唐只想杀了他们。是个聪明人，唐。}
{225}{}{我们需要纪律，白痴！我们现在是战士！我们要服从命令。杀手会丧命，而战士会赢得战斗。我们要打败末世论者。我们要打败所·有·人！}
{226}{}{谁他妈知道？也许只是墨菲斯在操纵。目前情况还不错，要是这里不行了，唐就到别的地方去。}
{227}{}{好了，别太激动。就算是和夜行团, 那也是很困难的战斗。但是如果我们干得聪明，我们就能搞定。那是唐唯一关心的事。}
{228}{}{昄依并不简单。你看见这些人了，这些僵尸?他们以前就和你我一样。唐幸免了。这些人没有。不过我为什么要管你呢？}
{229}{}{你不喜欢唐说话的方式？那么唐要杀了你！}
{230}{}{Ton go through it fine. I... uh... I... uh... Ton... Ton just fine.}
{231}{}{我以前在死狗帮。总是很饿，总是很累。这地方对唐来说好多了。我为什么要替别人担心？从来没人担心过我。}
{232}{}{你这贪心鬼！在唐杀你之前快滚！}
{233}{}{那么现在快滚，不然就晚了。}
{234}{}{没什么事有你我重要。很不幸，这是地球上最糟的体验唐所做的事的地方。僵尸太多了，我不能随便就说。等我想到一个更安全的地方再跟你说……}
{235}{}{你这婊子要干嘛！没人敢对唐这样！}
