{100}{}{你看见鲍勃，“鲍勃蜥蜴料理”的老板。}
{101}{}{好了，好了，我准备好给你的钱了。}
{102}{}{我最近开销大了些。我要提高你的付费。}
{103}{}{滚你娘的蛋！我要你所有的钱，要不你就是一只死鲍勃！}
{104}{}{我不会再受你摆布了。没钱给你。}
{105}{}{我想知道有关德克的情况。}
{106}{}{我想知道有关莫彼得医生的情况。}
{107}{}{给我一串烤蜥蜴。}
{108}{}{对不起，我不会付钱了。你想怎么着就怎么着吧。}
{109}{}{鲍勃，我还以为我们是朋友！事实上。我还想提拔你呢。而你，却背叛了我。这太让我失望了……}
{110}{}{鲍勃，我怎么能让人对我说不？尤其是像你这样的烂人？}
{111}{}{很高兴看到你能为自己辩护。}
{112}{}{你的名声已经是过去式了，鲍勃。过-去-了！}
{113}{}{很好，我慢慢再想怎么对付你。}
{114}{}{很好，很高兴认识你，鲍勃。替我向撒旦问好吧。}
{115}{}{你这么快回来干嘛？还没到付款的时间。}
{116}{}{你还敢在这里露面。快滚！}
{117}{}{嘿，我不想惹什么麻烦！}
{118}{}{嗨！欢迎到“鲍勃蜥蜴料理”，吃饭的好地方。要来点什么？}
{119}{}{No way, forget it.}
{120}{}{You are? Well, okay...}
{121}{}{他是个婊子养的杂种。你可不要惹祸上身。还要什么？}
{122}{}{好吧，你想要我付多少？}
{123}{}{我想要每五天}
{124}{}{ caps every five days.}
{125}{}{莫彼得医生？我只知道他住在迦克城，而且他的货是我能找到的最便宜的食材。就这些！}
{126}{}{我看看还有什么存货。}
{127}{}{整个的烤蜥蜴我收二十瓶盖。}
{128}{}{I've got prime cut select for eight bucks.}
{129}{}{我来一份整个的。}
{130}{}{这会不要。我在节食。}
{131}{}{我来一份精选肉块。}
{132}{}{这会我就来烤肉块吧。我只付得起这个。}
{133}{}{喔……偶现在不饿饿。}
{134}{}{好了！拿上你的钱快走吧！}
{135}{}{你就跟我耗吧！我不会给你钱的！快滚！}
{136}{}{是的，当然。你为什么不去敲诈别人。}
{137}{}{放屁糟践别人前先想想你有什么证据。滚出去！}
{138}{}{当然你会的。快滚！}
{139}{}{对不起，我们的蜥蜴都用完了。}
{140}{}{Sure. All I got is the whole iguanas at the moment. Thirty bucks each. You won't find a better roasted iguana in the wastes, I guarantee it!}
{141}{}{我们只有精选肉块了。不过吃起来很棒。一个八块。}
{142}{}{当然。烤整蜥蜴是二十块，精选肉块的是八块。}
{143}{}{我来份烤整蜥蜴。}
{144}{}{我来精选肉块。}
{145}{}{你知道吗，我听说你的精选肉块吃起来像鸡肉。你喜欢吃人肉吗？}
{146}{}{别小家子气了！我要所有的烤蜥蜴！噢！}
{147}{}{呣, 闻来好！偶要精选的！}
{148}{}{这里从没见过这种东西。纯水商队不会需要它们的。}
{149}{}{纯水商队？}
{150}{}{德克先生是一个高尚的商人，却干着不那么高尚的行业。还要别的吗？}
{151}{}{Um... Okay...}
{152}{}{哪种行业？}
{153}{}{你在说些什么？}
{154}{}{你的秘密原料。那些尸体变味前新鲜吗？你是用变种人，还是人类，或者混着用？}
{155}{}{我在莫彼得医生的老窝里找到一张发货单。死尸的发货单……}
{156}{}{如果你失忆了，我可以去和治安官谈谈。}
{157}{}{精选肉块是用人肉做的！！！用人肉做的！！！}
{158}{}{没什么。抱歉提起它。我还能为你做什么？}
{159}{}{好吧，他现在死了，因为这个我的钱包也鼓了。}
{160}{}{有人杀了德克。我们现在很悲伤。【窃笑】}
{161}{}{有人向治安官格林开枪。现在还不知道代理治安官有没有出事。}
{162}{}{达伦·海托被谋杀了。所有的钱都救不了他的命。很讽刺，是不是？}
{163}{}{有人从海托家里偷了一条项链。老兄，他们犯了大错。他们死定了！}
{164}{}{有人在大教堂杀了简恩。我听说她都被打得不成人形了！}
{165}{}{嗯，唯一的新闻是大教堂教徒接管了医院。最近这里很无聊。}
{166}{}{还要什么？}
{167}{}{老兄，这个礼拜我就要破产了。还要别的吗，老大？}
{168}{}{我不喜欢你的态度。}
{169}{}{抱歉，你肯定买不起。}
{170}{}{一份烤整蜥蜴来了！还要别的吗？}
{171}{}{你知道了它们是用什么做的你还想要一份？跟你这个变态比起来，德克简直就像个义务志愿者了！还想要什么？}
{172}{}{我不喜欢你的态度。}
{173}{}{抱歉，你肯定买不起。}
{174}{}{One prime cut select, coming up! Anything else?}
{175}{}{Smart decision. You could stand to lose a few pounds.}
{176}{}{什……什么！喔，我明白了，你是在开玩笑……}
{177}{}{当然我是……}
{178}{}{不，不是。我是来惩罚你的罪行。}
{179}{}{不，不是。我是要你意思一下。}
{180}{}{如果你会问我纯水商队的事，那你一定是刚进城的。水就是命，没有什么事情比生死还大。}
{181}{}{谁是纯水商队的头儿？}
{182}{}{在哈勃，如果有什么事情牵扯到不幸和痛苦，那么即使不是德克干的，也是他琢磨着想干的。你还要什么？}
{183}{}{我不知道你在说什么，也不喜欢你的诬蔑！希望你不要再来了}
{184}{}{不要那样做！好吧，我是用了一些可疑的配料。但这和我搞谋杀不一样。莫彼得的原料本来就是死的，是不是？}
{185}{}{我想是的，鲍勃。再见……}
{186}{}{吃人是违背人性的罪行，鲍勃。我是来惩罚你的。}
{187}{}{也许是。也许不是。我不在乎。我想要你意思一下。}
{188}{}{别那么大声！我不想让你喊得全哈勃城都知道……}
{189}{}{我想我有点无礼。再见……}
{190}{}{你知道，警察局就在街对面。我真该过去一趟。}
{191}{}{我还能更大声。但我也可以闭嘴。话多无益，沉默是“金”。}
{192}{}{如果你吃掉了我所有的存货，该死的我拿什么付你钱？好了！再来一串！最好噎死你！}
{193}{}{我不喜欢你的态度。}
{194}{}{呸。你想要钱，我给你。你想要吃的，我给你。你想要死，我帮你安排。但不要说什么“喜欢”，态度不是我的义务。}
{195}{}{我想不起还有什么。如果你不介意，我还有事要办。}
{196}{}{对不起，我们的蜥蜴都用完了。}
{197}{}{我们只有烤整蜥蜴了。二十块。}
{198}{}{We only have prime cut select. Eight bucks.}
{199}{}{又来了？老兄你肯定是饿了。烤整蜥蜴是二十块，精选肉块是八块。}
{200}{}{我来份烤整蜥蜴。}
{201}{}{我来份精选肉块。}
{202}{}{你知道吗，我听说你的精选肉块吃起来像鸡肉。你喜欢吃人肉吗？}
{203}{}{别小家子气！我要所有的烤蜥蜴！噢！}
{204}{}{呣, 闻来好！偶要精花肉！}
{205}{}{如果你吃掉了我所有的存货，该死的我拿什么付你钱？好了！再来一串！最好噎死你！}
{206}{}{我不喜欢你的态度。}
{207}{}{喔，再见。}
{208}{}{等一下。我们可以想办法达成默契。}
{209}{}{要让我保持沉默的唯一办法就是杀了我。}
{210}{}{对不起，没得谈。}
{211}{}{好吧。我能得到什么？}
{212}{}{好吧。你要我付你多少？}
{213}{}{我想要每五天}
{214}{}{50}
{215}{}{75}
{216}{}{100}
{217}{}{150}
{218}{}{200}
{219}{}{ caps every five days.}
{220}{}{我想我不会勒索你的。就这样吧。}
{221}{}{朋友，我是你的话就改主意。在哈勃城是很容易丧命的。}
{222}{}{好吧。就这样。}
# TRANSLATION NOTE: A number of caps is inserted between lines 222 and 223. The space at the end of line 222 is intentional!
{223}{}{块，每五天。我想我们五天后再见……}
{224}{}{那没办法。我付不起比现在更多的钱了。}
{225}{}{太糟了，鲍勃。我讨厌唱歌。}
{226}{}{好吧。暂时……我们就按目前的协议吧。}
{227}{}{你付得起一个葬礼吗，鲍勃？}
{228}{}{好吧。最好我们以后别再打交道了。}
{229}{}{也许你就是只会唱的小鸟，但我是下金蛋的鹅。只要我还能有你要的金蛋，在这你就别唱。现在滚吧！}
{230}{}{First sensible thing I've heard you say. Now get out!}
{231}{}{给我一串烤蜥蜴。}
{232}{}{你能跟我说一些有关净水芯片的事吗？}
{233}{}{你能跟我说一些有关德克的情况吗？}
{234}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
{235}{}{有关失踪的商队，你知道些什么吗？}
{236}{}{什么，我有麻烦？你从哪里看出来的？}
{237}{}{哈勃城发生了什么有趣的事吗？}
{238}{}{我饿了！呃啊！}
{239}{}{可怕的行当。那些可怜的人。喔，那些可怜虫，小命丢得这么惨！我还能为你做些什么？也许，来点吃的？}
{240}{}{没什么，再见。}
{241}{}{我走唔。}
{242}{}{I don't have that kind of money. I'm barely making ends meet as it is.}
##
##Sduibek -- Fallout Fixt
##
{243}{}{Thirty caps?! Are you kidding me?}
{244}{}{Look, you're the one who ruined my profit margins. So if you don't like my prices, fuck off. There are plenty of other iguana stands around here. Oh wait, there aren't. Asshole.}
{245}{}{Terrible, thanks to you. Nobody likes snitches. Now, if you ain't here to buy anything, get out of my face.}
{246}{}{Whatever. Bye.}
{247}{}{Actually, come to think of it, I am pretty hungry.}
#
{250}{}{ experience for blackmailing Bob into paying for your silence.}
{251}{}{How's business, Bob? *wink*}
#
# 252 to 260 take place while Bob is in jail
{252}{}{What the hell are you doing here? You shut down my business and got a big fat reward, I'm sure. So you're just here to gloat or what?}
{253}{}{Pretty much, yeah. How's business, Bob? *wink*}
{254}{}{Nah, just checking to see how you're doing.}
{255}{}{Terrible, thanks to you. Nobody likes snitches. They might let me die in here for all I know.}
{256}{}{Serves you right.}
{257}{}{I could have them kill you right now, if you prefer that over waiting.}
{258}{}{I'll ask them if we can turn you into Iguana Bits after your execution!}
{259}{}{Whatever. Fuck off.}
{260}{}{Go away.}
