{100}{}{This bookshelf is filled with religious and philosophical books. It's also very dusty.}
{101}{}{You take a book down, examine it, and put it back on the shelf. The shelf itself seems very sturdy.}
{102}{}{你发现一个隐藏的门闩。}
{103}{}{那做不了什么。}
{104}{}{书架旁边的墙无声地滑出一个门来。}
{105}{}{你在书架上摸索了一会，但是没找到什么东西。}
{200}{}{书架上装满了宗教和哲学的书籍。}
{201}{}{门闩移动不了。}
