{100}{}{我来这里是来打仗和吃泡泡糖的。现在已经没有泡泡糖吃了。}
{101}{}{兄弟会在期待着我们成功，先生。}
{102}{}{我们开始行动吧。}
{103}{}{保持队形，先生。}
{104}{}{我们最好开始行动。}
{105}{}{没时间闲聊了，先生。}
{106}{}{我来这里是来打仗和吃泡泡糖的。现在已经没有泡泡糖吃了。}
{107}{}{兄弟会在期待着我们成功，女士。}
{108}{}{我们开始行动吧。}
{109}{}{Maintain your tactical presence, ma'am.}
{110}{}{我们最好开始行动。}
{111}{}{没时间闲聊了，女士。}
{112}{}{很好，你在这里。我们来点亮这地方。}
{113}{}{这个房间有点不对头。}
{114}{}{这个地方开始让我不爽了。}
{115}{}{现在我们该返回兄弟会了。}
