{100}{}{Unless it's been looted already, you think there should be an uzi around here somewhere.}
{101}{}{A case on the wall says "Uzi 9mm - for emergencies only". The glass is broken and the case is empty.}
