{100}{}{你看见一个热情的年轻人。}
{101}{}{你看见迈克尔。}
{102}{}{你好，我想我以前没见过你。我能帮你什么忙吗？}
{103}{}{嗨，我能为你做什么？}
{104}{}{你能告诉我一点有关晒骨场的事吗？}
{105}{}{你是谁？}
{106}{}{你们为什么住在这里？}
{107}{}{没什么，谢谢。}
{108}{}{当然。这里南边是内城区，去东北边你能找到军火商，但是你得通过死亡爪才能到那里。西边是末世论者，而我听说，在很南边的地方有个大教堂。}
{109}{}{我是迈克尔。这是我妻子，克力斯廷。我住在这里，作为利刃帮的成员，尽我们所能帮助别人。}
{110}{}{这里没有看上去那么糟。管理者和死亡爪是大麻烦，但我们的头儿，剃刀，在过去几个月帮了我们很大的忙。最近，麦克雷在教我们怎样更好地保护自己。}
{111}{}{谢谢你帮我们在内城区消灭了管理者 。这是我们能拿得出来帮你的一点东西。}
{112}{}{这不是问题。谢谢你的补给。}
{113}{}{不客气，这些东西你们留着自己用吧。}
{114}{}{你一定要收下。}
{115}{}{(He hands you some stimpaks and some caps.)}
{116}{}{你好。祝你旅途顺利。}
