{100}{}{你看见深红商队的一名店员。}
{101}{}{你看见纯水商队的一名店员。}
{102}{}{你看见远行商队的一名店员。}
{103}{}{你好，是找工作来的？}
{104}{}{是。}
{105}{}{不。}
{106}{}{很好，我们缺少一名护卫人员，有兴趣吗？}
{107}{}{好吧，如果你以后需要工作，来这里我们给你安排。}
{108}{}{真可惜，再见。}
{109}{}{太好了。我们有去往晒骨场、迦克镇、大墓地和钢铁兄弟会的商队，你喜欢走哪一路？}
{110}{}{太好了。我们有去往晒骨场、迦克镇和钢铁兄弟会的商队，你喜欢走哪一路？}
{111}{}{太好了。我们有去往晒骨场和迦克镇的商队，你喜欢走哪一路？}
{112}{}{L.A. Boneyard.}
{113}{}{迦克镇。}
{114}{}{钢铁兄弟会。}
{115}{}{大墓地。}
{116}{}{None; I changed my mind.}
{117}{}{太好了，我们现在就走。}
