{100}{}{你看见一个孩子。}
{101}{}{嗨！}
{102}{}{你好。}
{103}{}{你爸妈呢？}
{104}{}{呃……}
{105}{}{不知道，附近吧。}
{106}{}{你有意思！}
{107}{}{嘿，你会杀人？}
{108}{}{对。}
{109}{}{不会。}
{110}{}{呃。}
{111}{}{我要告诉我妈妈！}
{112}{}{那你就不该拿着武器乱晃。}

{980}{}{哈？}
{981}{}{I dunno. Ask mommy.}
{982}{}{问我爸爸。}

{1000}{}{Deathclaw}
{1001}{}{Raiders}
{1002}{}{Junktown}
{1003}{}{Brahmin}
{1004}{}{Chip}
{1005}{}{Merchants}
{1006}{}{Khans}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Hub}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Police}
{1015}{}{Caravans}
{1016}{}{Traders}
{1017}{}{Children}
{1018}{}{Necropolis}
{1019}{}{Spot}
{1020}{}{Brotherhood}
{1021}{}{Boneyard}
{1022}{}{Towers}
{1023}{}{Town}
{1024}{}{Downtown}
{1025}{}{Heights}
{1026}{}{The Boneyard}
{1027}{}{L.A. Boneyard}

{1100}{}{哦！恐怖恐怖的怪物！}
{1101}{}{大坏蛋！}
{1102}{}{I dunno.}
{1103}{}{很大，很臭的东东。}
{1104}{}{问我妈妈。}
{1105}{}{一帮有趣的家伙。}
{1106}{}{大坏蛋！}
{1107}{}{坏蛋。}
{1108}{}{我不告诉你。}
{1109}{}{大城市。}
{1110}{}{不告诉你。}
{1111}{}{我不说。}
{1112}{}{妈妈不让我说他。}
{1113}{}{爸爸说他很好玩。}
{1114}{}{大人。}
{1115}{}{臭臭的东西拉着他们的货。}
{1116}{}{好人，他们给我糖糖吃。}
{1117}{}{他们都不喜欢躲猫猫。}
{1118}{}{可怕的地方。}
{1119}{}{不好玩的地方。}
{1120}{}{可怕的地方。}
{1121}{}{可怕的地方。}
{1122}{}{妈妈不让我去那里玩。}
{1123}{}{爸爸老是让我在那里玩。}
{1124}{}{大人的地方。}
{1125}{}{大人的地方。}
{1126}{}{Scary place.}
{1127}{}{Scary place.}
