{100}{}{你看见一个沙荫镇的居民。}
{101}{}{欢迎来到沙荫镇，陌生人！}
{102}{}{哦，谢谢。}
{103}{}{这里都是做什么的？}
{104}{}{哼哈！}
{105}{}{我们是真正的共同社区，一起工作，一起分享成果。}
{106}{}{你们是怎么存活下来的？}
{107}{}{谁是你们的领导？}
{108}{}{我们有农田和灌溉设施，我们养双头牛。我们的每个人都有自己的一技之长，能为我们的社区做贡献。}
{109}{}{亚拉德什是我们现在的领导。他的经验很丰富，足堪此任。}
{110}{}{嗨！}
{111}{}{你好。}
{112}{}{你好啊。}
{113}{}{很高兴见到你。}
{114}{}{再见。}
