{100}{}{看起来是力场控制计算机。}
{101}{}{看起来是由力场信号传导器、远程指挥接收器和标准无线电数据通信端口组成。}
{102}{}{你打开了力场控制计算机，你听到整个基地里发出一阵低沉的嗡嗡声。}
{103}{}{你没有正确使用电脑。}
{104}{}{你不能关闭力场控制计算机，所有的控制端都被锁住并加密。}
{105}{}{你无法理解这台电脑的操作系统。}
{106}{}{力场控制系统在你这样的天才手里不堪一击，这一层所有的力场全部被关闭了。}
{107}{}{力场系统的防卫很严密，但是你还是解除了一半的力场，这已经是你的极限了。}
{108}{}{力场控制系统能防止电子入侵，你花了些时间破解，但是未能成功。}
{109}{}{你好不容易打赢了21点的游戏，并在游戏结束的画面上找到了进入主系统的后门。}
{110}{}{你玩了21点的游戏，但成绩不好，不能突破系统防护。}
{111}{}{唯一没有加密的目录是“娱乐游戏”，也许这里有后门程序？}
{112}{}{唯一没有加密的目录是“娱乐游戏”。}
{113}{}{你呆呆地看着电脑。}
{114}{}{你发现所有的目录都被加密，但似乎你没搜全。}
{115}{}{你进入了主系统，现在可以进行力场控制程序重新编译。}
{116}{}{由于你以非常规的手段破解了程序，你获得了800点经验值。牛！}
{117}{}{你将无线电连接到力场控制计算机。}
{118}{}{你想把无线电接到计算机，但失败了。}
