{100}{}{你看到了丹。}
{101}{}{救命！}
# Appends line 103 or 104 or 105 depending on character's age and gender.
{102}{}{嘿朋友，欢迎来哈勃城。先做个自我介绍，他们都叫我双头牛丹。我跟商人们打交道，也为他们跑跑腿。通常情况下，鄙人服务的开价是非常，非常低廉的。您有什么需要么？}
{103}{}{年轻人？}
{104}{}{这位先生？}
{105}{}{这位女士？}
{106}{}{我想加入商队。}
{107}{}{呃，你到底能提供哪些服务啊？}
{108}{}{你干嘛老冲着那个可怜的小毛孩大喊大叫？！}
{109}{}{呃。}
{110}{}{这样说吧，这些地方大多数的商队的马车啊，双头牛什么的，都是归我来照管的。要是他们想为他们的商队里添点什么东西的话，也会和我打交道。可是，妈的，三巨头他们不带我玩。}
{111}{}{三巨头是谁？}
{112}{}{看来你是个重要的人嘛。}
{113}{}{真的？太棒了？我也要加入商队。}
{114}{}{嗯，我得走了，拜拜。}
{115}{}{什么？赶快给我滚出去吧，你这个瘾君子！我可不想在你这个低能儿身上浪费时间。}
{118}{}{该死，小子，你是不是一直生活在个什么洞里面啊？三巨头就是这个世界，嗯，也许不是全世界，但是绝对是你能想象到的最大的那么一大块地方上最大的三个商队。}
{119}{}{该死，亲爱的，你是不是一直生活在个什么洞里面啊？三巨头就是这个世界，嗯，也许不是全世界，但是绝对是你能想象到的最大的那么一大块地方上最大的三个商队。}
{120}{}{你才该死，你这个双头牛怪物。}
{121}{}{哦，是他们啊。我还以为你在说别的什么东西呐。我怎么才能加入一支商队？}
{122}{}{好的，谢谢。拜拜。}
{123}{}{双头牛怪物？你不是在侮辱我吧？告诉你吧，陌生人，我会比你要见到的人更懂礼貌。我可以不那么在意，可是，在这个城市里，到处都是些杀手恶汉，他们要是看你不爽，二话不说就会把你的喉咙给割咯。}
{124}{}{混蛋，你这个丑八怪杂种！}
{125}{}{我好怕哦。回见。}
{126}{}{特别，不。幸运，是的。除非你想自触霉头，你就得对你见到的人表现得礼貌一点。我可以不那么在意，可是，在这个城市里，到处都是些杀手恶汉，他们要是看你不爽，二话不说就会把你的喉咙给割了。}
{127}{}{放屁！你个王八肏的！}
{128}{}{要是你这样说的话……}
{129}{}{我至少没有像变种人那样的猪头脸。你妈一定是头双头牛，你爸是只耗子，所以才生出你这个鸟样儿。妈的，你比我丑多了！}
{130}{}{没人可以这样说我的妈妈！受死吧！}
{131}{}{嗯，不错。看来我有地方去了，还能找人打一架。走啦，丹。}
{132}{}{好好好，说话总要有个分寸，但每个人都会探探底线。你在开玩笑是吧，你不会对可怜的老丹动手的吧。}
{133}{}{分寸？动手？你想哦。我对你动的可不止是手！你马上就要成为一具死尸了。}
{134}{}{哈！我跟你开玩笑的，这你都信啊？}
{135}{}{是啊，有那么一点。你不是那么坏嘛，小子。但是记住管好你的嘴巴，我可不想看到这么一张好嘴巴给人废了。}
{136}{}{当然了，随你说。走啦，丹。}
{137}{}{那么，我怎么才能加入一支商队？}
{138}{}{滚蛋。离我的双头牛远一点，你这个肮脏的小杂种。}
{139}{}{滚蛋。离我的双头牛远一点，恶心小婊子。}
{141}{}{保安！警察！这有个疯子要杀我！救命呀！}
{142}{}{我没什么路子，不过你可以去“三巨头”那碰碰运气，商队市场那里有个招募广告牌大概对你有点用，他们既是靠这个招人的。}
{143}{}{喔，抱歉……当然，还有女人…}
{144}{}{你能没路子？你不也是商人吗？}
{145}{}{去商队市场怎么走？}
{146}{}{好的，多谢了。}
{147}{}{哦不，我不是。我和很多小一些的商队关系比较近，所以我知道我们现在不招人。}
{148}{}{这是你的损失。}
{149}{}{好的，一会见，丹。}
{150}{}{商队市场在哪儿？}
{151}{}{沿着路一直往下走。它就正好在哈勃城的中心－－你肯定能看到的。}
{152}{}{那不关你事，陌生人。}
{153}{}{我要忙我的去了，“陌生人”！}
{154}{}{打搅了。}
{155}{}{啊，又见面了！你好吗？}
{156}{}{我想加入商队。}
{157}{}{呃，你这儿有啥来着？}
{158}{}{你干嘛老冲着那个可怜的小毛孩大喊大叫？！}
{159}{}{挺好的，再见。}
{160}{}{哈哈大笑。}
{161}{}{啥事？}
{162}{}{你干嘛老冲着那个可怜的小毛孩大喊大叫？！}
{163}{}{没事。}
{164}{}{哈哈大笑。}
{168}{}{瞧，那个偷东西的小贼给逮个正着。警察让我来教训教训他。}
{169}{}{没必要对他这么狠吧。}
{170}{}{偷东西咋了？}
{171}{}{哦，那就另当别论了！好好教训他！}
{172}{}{你傻啊，我有个好办法，就是把他关到牢里让他慢慢烂掉，或者干脆流放，不给吃，不给穿，更不给武器。}
{173}{}{就是这样的话，你也不能这样对他。}
{174}{}{噢，好的。}
{175}{}{我也许不是这遭瘟的城里最好的家伙，但我是这儿唯一一个会关心别人而且愿意提供帮助的人。你有为这个社会做过什么事没？}
{176}{}{我杀了好多好多东西！}
{177}{}{我很抱歉，我错怪你了。}
{178}{}{你该杀了那个小混蛋！}
{179}{}{嗯，那你也许能对他稍微和气一点。我想他在努力改正了。}
{180}{}{你认为杀人就能解决问题了？}
{181}{}{Ya' think killing people solves the real problem?}
{182}{}{没错！}
{183}{}{这对我来说一直很有效！}
{184}{}{唔，也许不是哦。}
{185}{}{我不知道。}
{186}{}{你让我失望了。你肩膀上的脑袋看上去倒是挺聪明。杀人，也许可以解决一时的问题，但是却让这个问题从本质上变得完全不同了。}
{187}{}{是啊，随便啦。}
{188}{}{呃，好。拜拜。}
{189}{}{你这个白痴。}
{190}{}{嗯，【他停下来往四周看了看】……也许你是对的，伙计。我会考虑的，但是我不敢保证。}
{191}{}{你在开玩笑吧？那只会让我更加目空一切！我的方法或许不是最好的，但至少这可以让我变得更强，更有责任感。}
{192}{}{该死，把得病的人杀了不是最好的办法。你肯定能找到治好他们的方法，因为它就要再次出现了。}
{193}{}{别开玩笑了，你以为你是爱因斯坦啊。}
{194}{}{少废话了，我头都疼了！}
{195}{}{呃，是啊，没错，伙计。我得走了。}
{196}{}{嗯，别总用枪解决问题。再见。}
{197}{}{妈的，真热！}
{198}{}{比利！别在那游手好闲的，你这个垃圾！}
{199}{}{比利！你今晚最好让那些双头牛保持温暖，不然剥了你的皮！}
{200}{}{该死，你这个小混蛋！闭上你的狗嘴干活去！}
{201}{}{走开，我忙着呢。}
{202}{}{我警告你，比利！}
{203}{}{你不是敬酒不吃吃罚酒吧？}
{204}{}{抱歉，小子，我现在不能跟你掰，我得干活去了。}
{208}{}{抱歉，我现在不能跟你扯淡，我得干活去了。}
{209}{}{你最好别烦比利了，他今天有一大堆事要做。}
{210}{}{Beat it, I'm busy.}
{211}{}{为啥每个人都来烦我？你们没看到我正在忙吗？}
{212}{}{要工作的话跟那些商人说。我这里不招人。}
{213}{}{你干嘛不去“马耳他猎鹰”那儿玩玩啊，我忙着呢。}
{214}{}{你到底要干嘛？滚！}
{215}{}{我说了，滚！我不是在开玩笑！我他妈要剁了你！}
{216}{}{你们这些小流氓永远都不懂，是吧！}
