{100}{}{你看见一个德克的守卫。}
{101}{}{你得去和老大谈。}
{102}{}{你最好站在我们这边。}
{103}{}{我们会看着你的。}
{104}{}{不要碰你的武器。}
{105}{}{如果你惹怒了他，你就得死。}
{106}{}{规矩点。}
{107}{}{我投降！}
{108}{}{我从来不喜欢在那个叫德克的家伙手下工作。}
{109}{}{现在德克和凯恩都死了，我将是这儿的老大了！}
{110}{}{你现在最好离哈勃城远点。我会看着你的！}
