{100}{}{【更多】}
{101}{}{【完成】}
{102}{}{笨蛋！你又弄疼我了，你个愚蠢的混蛋！}
{103}{}{笨蛋！你又弄疼我了，你个愚蠢的婊子！}
{105}{}{？笨蛋！你难道没看到和平的信号吗！}
{106}{}{嘿，我只是帮你治疗伤口！}
{107}{}{我想问几个问题。}
{108}{}{请把我医好，医生？}
{109}{}{你治疗的手段真是糟啊。}
{110}{}{医生，我想要点喝的！给我点按摩用的酒精行吗？}
{111}{}{坚持一下，你需要看个医生。}
{112}{}{噢！噢！啊啊！}
{113}{}{你想要什么？你这个笨蛋还不懂吗？我已经厌倦了用我的能力来帮残兵败将。下次射准点！别让他们打到你。}
{114}{}{我在数量上被压过了！}
{115}{}{你是什么，医生还是混蛋？}
{116}{}{也许我该拿你来练练手。}
{117}{}{该死的婊子养的！你又受伤了！我希望他们下次能干掉你！}
{118}{}{谢谢你仁慈相助，医生。}
{119}{}{我也希望他们干掉你……}
{120}{}{如果他那么做，你会第一个倒下。}
{121}{}{你有什么不对吗？笨蛋！也许我该让你永远合眼！}
{122}{}{你让很多人永远合上眼吗，医生？}
{123}{}{你最好别这么做。}
{124}{}{我要打个盹，你这个混蛋！}
{125}{}{这理由对笨蛋没用！你为什么还来烦我？我是个很忙的医生，笨蛋！你还要我帮忙吗？}
{126}{}{什么使你这么忙？}
{127}{}{是的，医生。}
{128}{}{不是现在。}
{129}{}{你的诊断是什么，医生？}
{130}{}{我不是图书馆！你去外面找答案！出去！}
{131}{}{好啊！它总是能治好你！笨蛋！}
{132}{}{我听他们说了一些对你很不好的事……}
{133}{}{主教的敌人将会不惜一切来破坏你们的信仰。}
{134}{}{你发过誓了，医生。做你的工作。}
{135}{}{忘了它吧，我不能相信你。}
{136}{}{医好我，要么死，医生！}
{137}{}{这个应该可以……}
{138}{}{噢噢！！}
{139}{}{哈哈哈！}
{140}{}{你叫起来像个娘们！哈哈哈！}
{141}{}{婊子不应该在男子的世界活动！哈哈哈！}
{142}{}{去死吧！你想被医好还是变成个白痴！}
{143}{}{你个弱智！你为什么不爬到闪光之地去舔泥巴？愚蠢的该死的混蛋！}
{144}{}{也许某天你需要医生而医生不在。白痴！你想医好吗？也许我也要往你的脑子里塞点垃圾。}
{145}{}{Fine. Do it and shut up!}
{146}{}{去死吧。}
{147}{}{闭嘴并告诉我诊断结果。}
{148}{}{你这个愚蠢的笨蛋！你太蠢了所以感觉不到疼痛。你让我想起了某些低级的生命形式。}
{149}{}{像你这种疯子真是蠢到家了！}
{150}{}{哈哈！你真是蠢啊！我刚给了你致命的毒药！哈哈哈！}
{151}{}{这会很疼！}
{152}{}{啊啊！}
{153}{}{你叫的就像是头被骟掉的猪！哈哈哈！}
{154}{}{你这个白痴！质量，不是数量！你认为当夜行团会在乎他们人数太多吗？去你妈的怀里哭吧，小朋友！现在，你想不想更好点？}
{155}{}{安静点！否则我拔掉你的舌头！叫得像条狗一样！哈哈哈！现在你想要更好点吗？}
{156}{}{我是医生，不是拉拉队长！你还想治病吗？}
{157}{}{我的手抖了，笨蛋！现在你想要更好点吗？}
{158}{}{开始吧，只是别催我！}
{159}{}{我做的棒极了。在这儿我成了真正的医生。}
{160}{}{尽管试试看是什么先坏掉。}
{161}{}{夜行团很喜欢这么做。有时我给他们毒品。没人注意到吴医生。他们都是混蛋！现在，你还想医好吗？}
{162}{}{贴上它，医生！}
{163}{}{如果夜行团不相信你，我也一样。我要走了。}
{164}{}{笨蛋！大教堂很忙！团队使吴医生非常忙！现在你还想医好吗？}
{165}{}{现在是有趣的部分！}
{166}{}{应该这么做……}
{167}{}{What a dork! I've heard less screaming from children! Ha ha ha!}
{168}{}{我让这个婊子叫得好大声！哈哈哈！}
{169}{}{蠢货！猪头！我很忙，你又来烦我了！该死！滚出去，立刻！}
{170}{}{你像双头牛一样健康了，但还不够聪明！滚出去，你这个白痴。}
{171}{}{你受伤了，白痴，如果你能安静些的话，我能医好它！}
{172}{}{你对自己的身体一点都不在乎，你真是个蠢蛋。我可以永远“结束”你的痛苦，或者，我也可以医好你。}
{173}{}{不是现在。}
{174}{}{好吧。但我希望今天之内能给你做个手术。}
{175}{}{噢！你这个……}
{176}{}{现在滚出去，别在回来了！}
{177}{}{好，我来医治你。}
{178}{}{那个应该能医好你！}
{179}{}{离开吧，笨蛋！我不久后就可以看着你的尸体哈哈大笑了。}
{180}{}{你这个白痴！你以为你是谁，可以来打扰吴医生？愚蠢的白痴！}
{181}{}{你受伤了，我能医好它，笨蛋，前提是你要安静些！}
{182}{}{至少有五处骨折，而且你失血太多。忠告：做个白痴有损你的健康！你还想医好吗？}
{183}{}{基于“医好”的定义，你可以治疗我，医生。}
{184}{}{我去。}
