{100}{}{You do not see a control panel on this emitter.}
{101}{}{你损坏了发射器使力场临时关闭。}
{102}{}{你彻底摧毁了力场发射器使力场完全消失。}
{103}{}{你临时关闭了力场发射器。}
{104}{}{你没能对力场发射器做任何事。}
{105}{}{你使力场发射器正常工作。}
{150}{}{Your attempt to re-wire the field emitter fails.}
{151}{}{You turn off the field emitter.}
{200}{}{You see a horribly-damaged field emitter.}
{201}{}{The emitter is too damaged to use.}
{202}{}{The emitter is too damaged to repair.}
{203}{}{You notice that the field is damaged enough to walk through.}
#
# Fallout Fixt
#
{204}{}{A well-placed explosive blast might knock out the emitter completely.}
{205}{}{You don't see any way to attach the explosives to the emitter. You'll need to place them nearby.}
