{100}{}{你看到一个远行商队的保镖。}
{101}{}{那些该死的水商人把我们全骗了。}
{102}{}{要保证准时付钱给友好信贷公司，否则他们会要我们的命。}
{103}{}{你去和罗格尔谈谈把。}
{104}{}{远行商队是最好的商队。}
{105}{}{深红商队那群白痴不是疯子就是傻子。}
{106}{}{哎，我好想要串烤大蜥蜴。}
{107}{}{哪个该死的偷了我们的商队？}
{108}{}{我兄弟在上次那个失踪的商队里。}
{109}{}{我认为，那些守水的吝啬鬼该对这事儿负责。}
{110}{}{我听说是变种人干的，真可怕。}
{111}{}{Heard you say it was Super Mutants. Hope you made 'em pay.}
{112}{}{我认为死亡爪该负主要责任，该死的变种人。}
{113}{}{我们关门了。早上再来把。}
{114}{}{嘿，这不是猎鹰。滚到地狱去吧。}
{115}{}{你算老几？什么垃圾货色？滚蛋……}
{116}{}{走开！}
{117}{}{我们只在白天开放。}
{118}{}{你带了毒品了？滚开！}
{119}{}{你只能等早上回来。}
