{100}{}{你看到末世论者的谍报员杰瑞。}
{101}{}{你看到末世论者的谍报员小熊。}
{102}{}{你看到末世论者的谍报员理查德。}
{103}{}{你看到末世论者的谍报员詹森。}
{104}{}{你看到末世论者的谍报员幻影。}
{105}{}{你看到末世论者的谍报员列农。}
{106}{}{你看到末世论者的谍报员格温多林。}
{107}{}{你看到末世论者的谍报员罗莎。}
{108}{}{你看到末世论者的谍报员伊丽莎白。}
{109}{}{你看到末世论者的谍报员丽贝卡。}
{110}{}{谁在大厅转悠呢？}
{111}{}{啊？}
{112}{}{我是}
{113}{}{。我为和平而来。}
{114}{}{我是}
{115}{}{。我是你的丧门星。}
{116}{}{谁是末世论者的信徒？}
{117}{}{很好，我感觉你有些迟钝，你谁？}
{118}{}{我}
{119}{}{。你死。}
{120}{}{我}
{121}{}{。我啊。}
{122}{}{我杀！}
{123}{}{我}
{124}{}{。我去。}
{125}{}{你需要帮助吗？你可以去和妮可尔或者杰克谈谈。如果你想帮助我们，他们有的是时间和你聊。}
{126}{}{好把，别在附近惹麻烦。}
{127}{}{你见过那帮邪恶的大教堂教徒？}
{128}{}{是的，我要除掉这些人渣。}
{129}{}{不，我觉得我更应该杀了你这懦夫。}
{130}{}{大教堂教徒是什么？}
{131}{}{为什么要杀大教堂教徒？}
{132}{}{非常好，去和妮可尔谈谈，她将告诉你如何帮助我们。}
{133}{}{大教堂教徒是一个信奉黑暗之神的秘密组织，我个人认为他们私下里正在做一些见不得人的事情。}
{134}{}{我会杀了他们的。}
{135}{}{我得考虑考虑，他们对我来说太强大了。}
{136}{}{有什么需要我帮忙的？}
{137}{}{忘了这事吧，让我帮你是不可能的。}
{138}{}{他们确实是挺厉害的，但我认为以你目前的实力，你完全有能力帮我们把他们消灭。}
{139}{}{我做。}
{140}{}{我不认为我能帮上忙。}
{141}{}{你随意吧，如果以后他们称霸了废土，可别怪我没警告过你。}
{142}{}{如果你去找妮可尔谈话，她将告诉你更多的计划。}
{143}{}{谢谢你，拜拜。}
{144}{}{我并不想伤害谁，可他们是大教堂的人，是人中之渣！}
{145}{}{原来如此，我着就去收拾了他们。}
{146}{}{哦，我还以为你们所说的大教堂教徒是教堂里的小孩呢，没什么，我看我帮不了你们了。}
{147}{}{你能给我说明下什么是大教堂教徒吗？}
{148}{}{我们是末世论者。我们在正努力给废土带来和平。}
{149}{}{听起来真不错，祝你们好运。}
{150}{}{说说你们的计划？}
{151}{}{那看上去非常不着调.}
{152}{}{我们的工作就是让废土能够包容那些不幸被射线伤害了的变异的人们。}
{153}{}{你们会成功的！}
{154}{}{你认为战争为什么会发生？那是因为自古以来我们就没有获得过同情。}
{155}{}{真能扯。}
{156}{}{你是对的，就拿我这样的人类来说，我们思想封闭，又固执，但总是憧憬着未来。}
{157}{}{祝你好运。}
{158}{}{我认为你说的没错，我希望你在这事上能看开点。}
{159}{}{就算真的是这样，我也不能接受你的观点，再见。}
{160}{}{在我们之间有一个愤青。我确信你有你的理由，我们应该相互理解。}
{161}{}{祝你好运。再见。}
{162}{}{我听说大教堂教徒的人掌握着我们的一些机密，我真不理解他们是如何得到的。}
{163}{}{我怀疑这附近可能隐藏着一个间谍。}
{164}{}{你说的真对，是我把你们的机密卖给他们的。}
{165}{}{我看你是喝多了，他们怎么可能什么都知道？}
{166}{}{真的？我自己也想过很多，我就是害怕现实和我的推测不符。}
{167}{}{你有关于那个间谍的线索吗？}
{168}{}{很高兴您让我知道了那么多事情，耽误您时间了，谢谢。}
{169}{}{你着两面派！墙头草！双重间谍！}
{170}{}{那不是真的！我只是认为只有新会员才有机会到外面接触些情报，因为他们看上去脸生，你应该把希望寄托才新人和谍报员身上。}
{171}{}{谢谢，拜拜。}
{172}{}{妮可尔知道我杀了那间谍一定会很开心的。}
{173}{}{你是对的。谢谢你对我那么真诚。}
{174}{}{我认为你是一个双重间谍！还他妈敢戏弄我，你的死期到了！！}
{175}{}{间谍消灭的好！！也许现在是一个回击大教堂教徒的好机会！}
{176}{}{祝你好运。}
{177}{}{I can help train you to become a more efficient fighter.}
{178}{}{你？啊，那真好！}
{179}{}{There you go. Maybe that will help you, if you get into a fight.}
