{100}{}{你看到一个身材魁梧装备精良的人。}
{101}{}{你看到加布里尔，军火贩子的领袖。}
{102}{}{我们这儿可不常有人来，请问您有何贵干？}
{103}{}{为什么没什么人来这里呢？}
{104}{}{你在这做什么的？}
{105}{}{这地方可不是那么好进来的，有一窝该死的死亡爪就在我们工厂外面。}
{106}{}{你们装备那么好，为什么不出去干掉他们。}
{107}{}{我们去那干掉过一些，可总也杀不完啊。再说我们是造枪的，不是使枪的。}
{108}{}{如果我为你们干掉那些死亡爪，会有什么好处呢？}
{109}{}{我们制造枪支弹药已经三十年了，不过近十年很不好过。}
{110}{}{为什么？}
{111}{}{以前我们在工厂附近战前留下的那些金属垃圾里找原料。现在我们得依靠内城区提供我们原材料。}
{112}{}{内城区提供你们物资有什么不好？}
{113}{}{开始也没什么。他们提供物资，我们制造枪械来卖。但三年前齐默曼雇佣了一些佣兵来保护内城区不受强盗和死亡爪的骚扰。那些佣兵压榨我们，抢我们的东西，是群冷血的杂种。我们造的枪械倒便宜了他们。}
{114}{}{为什么不去别的地方落脚？}
{115}{}{是挺倒霉的。我料理那些死亡爪的话有什么报酬？}
{116}{}{能的话我们早走了。但是搬迁是个大工程，我们有车床和轧钢机器，这些东西可不是拎起来就能走的。我们就是能走还有那些死亡爪挡着呢。}
{117}{}{你们装备这么好，为什么不去搞定那些死亡爪？}
{118}{}{要是你能把那些死亡爪一锅端咯，随便你开价。}
{119}{}{我要很多枪械和弹药，很多。}
{120}{}{}
{121}{}{你能扫荡这地方让我们搬走，我们就会留下很多武器弹药，让你八辈子都用不完。}
{122}{}{好。成交。}
{123}{}{我再考虑一下。}
{124}{}{能解决你们跟内城区所有问题的人。}
{125}{}{你杀光那些死亡爪，全部的死亡爪，就成交。}
{126}{}{Okay. I'll do it.}
{127}{}{我会考虑的。}
{128}{}{你好，又是我。}
{129}{}{你在这是做什么的？}
{130}{}{再见。}
{131}{}{}
{132}{}{It's been going okay.}
{133}{}{我想我已经杀了所有的死亡爪。}
{134}{}{我们得确认一下。过去两年我们杀了20多只，可它们总是会再回来。我们根本没办法。过几天之后如果他们没有再出现，我们会给你报酬的。}
{135}{}{Okay, thanks}
{136}{}{如果你杀掉了所有死亡爪就通知我们。}
{137}{}{好，再见了，也许再不见……}
{138}{}{我明白，跟我说说。}
{139}{}{再见了，也许再不见……}
{140}{}{我们这里可不常有人来，能为你效劳什么吗？}
{141}{}{为什么没什么人来你们这呢？}
{142}{}{你在这做什么的？}
{143}{}{这地方可不是那么好进来的，有一窝该死的死亡爪就在我们工厂外面。}
{144}{}{我杀了所有的死亡爪，连那些该死的蛋也没放过。}
{145}{}{能的话我们早走了。但是搬迁是个大工程，我们有车床和轧钢机器，这些东西可不是能拎起来就走的。我们就是能走还有那些死亡爪挡着呢。}
{146}{}{我杀了所有的死亡爪，连那些该死的蛋也没放过。}
{147}{}{}
{148}{}{我要武器和弹药，要很多。}
{149}{}{}
{150}{}{不用给我报酬，一声谢谢就够了。}
{151}{}{没问题，想要什么尽管拿吧。我们这两天就要搬走了，但我们会留下很多武器弹药的，你拿都拿不了。需要的时候再回来拿吧。}
{152}{}{}
{153}{}{}
{154}{}{谢谢你。}
{155}{}{}
{156}{}{小意思。}
{157}{}{}
{158}{}{}
{159}{}{你们不是要走了吗？}
{160}{}{我只是来拿些东西，今天有什么东西吗？}
{161}{}{没什么，还是谢谢了。}
{162}{}{}
{163}{}{好的，现在有什么东西？}
{164}{}{好吧，再见拉。}
{165}{}{}
{166}{}{我只是来拿些东西，今天有什么东西吗？}
{167}{}{没什么，还是谢谢了。}
{168}{}{抱歉，现在不能聊天，我很忙。}
{169}{}{Guns! I like guns!}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{170}{}{我有些朋友是可以真正能用你们武器的人。}
{171}{}{我有些朋友是可以真正能用你们武器的人。}
{172}{}{伙计，怎样啊？}
{173}{}{朋友，如何啊？}
{174}{}{什么，你把它们全杀了？感谢上帝。现在我们能去可以自己拿到物资的地方了，再也不用依靠内城区了。要什么就说话，伙计。}
{175}{}{什么，你把它们全杀了？感谢上帝。现在我们能去可以自己拿到物资的地方了，再也不用依靠内城区了。要什么就说话，朋友。}
{176}{}{很公平，跟你做交易很愉快，朋友。}
{177}{}{很公平，跟你做交易很愉快，朋友。}
{178}{}{没问题，告诉你的朋友他们有武器了。}
{179}{}{没问题，告诉你的朋友他们有武器了。}
{180}{}{谢谢，兄弟。}
{181}{}{谢谢你，我的朋友。}
{182}{}{抱歉，我不能跟你聊天，我们正忙着收拾东西呢。有什么需要的话你随便拿。}
{183}{}{抱歉，我不能跟你聊天，我们正忙着收拾东西呢。有什么需要的话你随便拿。}
{184}{}{现在不用离开了，那些佣兵已经被搞定了。}
{185}{}{现在不用离开了，那些佣兵已经被搞定了。}
{186}{}{欢迎伙计，能帮你什么吗？}
{187}{}{欢迎朋友，能帮你什么吗？}

#
# Following Line is just to be translated normally.
#
{188}{}{买东西的话你得跟赞克谈。}
