{100}{}{谢谢。}
{101}{}{再见。}
{102}{}{你好。}

{103}{}{You earn }
{104}{}{ experience.}

{105}{}{呃……哦！}
{106}{}{点击！}
{107}{}{Oops!}
{108}{}{哇啊！}
{109}{}{See ya 'round.}
{110}{}{Take it easy.}
{111}{}{以前还挺有趣的。}
{112}{}{这里走。}
{113}{}{还有什么？}
{114}{}{是的。}
{115}{}{不。}

{116}{}{你获得了}

{117}{}{点轻型枪械技能点数。}
{118}{}{点大型枪械技能点数。}
{119}{}{点能量武器技能点数。}
{120}{}{点徒手格斗技能点数。}
{121}{}{点近战武器技能点数。}
{122}{}{点投掷技能点数。}
{123}{}{点急救技能点数。}
{124}{}{点医疗技能点数。}
{125}{}{点潜行技能点数。}
{126}{}{点偷窃技能点数。}
{127}{}{点开锁技能点数。}
{128}{}{点陷阱技能点数。}
{129}{}{点科技技能点数。}
{130}{}{点修理技能点数。}
{131}{}{点口才技能点数。}
{132}{}{点交易技能点数。}
{133}{}{点赌博技能点数。}
{134}{}{点野外生存技能点数。}

{135}{}{你获得了1点轻型枪械技能点数。}
{136}{}{你获得了1点重型枪械技能点数。}
{137}{}{你获得了1点能量武器技能点数。}
{138}{}{你获得了1点徒手格斗技能点数。}
{139}{}{你获得了1点近战武器技能点数。}
{140}{}{你获得了1点投掷技能点数。}
{141}{}{你获得了1点急救技能点数。}
{142}{}{你获得了1点医疗技能点数。}
{143}{}{你获得了1点潜行技能点数。}
{144}{}{你获得了1点偷窃技能点数。}
{145}{}{你获得了1点开锁技能点数。}
{146}{}{你获得了1点陷阱技能点数。}
{147}{}{你获得了1点科技技能点数。}
{148}{}{你获得了1点修理技能点数。}
{149}{}{你获得了1点口才技能点数。}
{150}{}{你获得了1点交易技能点数。}
{151}{}{你获得了1点赌博技能点数。}
{152}{}{你获得了1点野外生存技能点数。}

{153}{}{你的力量增加了}
{154}{}{你的感知增加了}
{155}{}{你的体质增加了}
{156}{}{你的魅力增加了}
{157}{}{你的智力增加了}
{158}{}{你的敏捷增加了}
{159}{}{你的运气增加了}
{160}{}{点。}

{161}{}{你的力量增加了1点。}
{162}{}{你的感知增加了1点。}
{163}{}{你的体质增加了1点。}
{164}{}{你的魅力增加了1点。}
{165}{}{你的智力增加了1点。}
{166}{}{你的敏捷增加了1点。}
{167}{}{你的运气增加了1点。}

{168}{}{谢谢你的帮助。}
{169}{}{还是辛苦你了。}

{170}{}{Your attempt to equip human armor has failed; the armor is destroyed.}

{171}{}{我相信主教想和你谈谈。}
{172}{}{你会为你的亵渎付出代价！}

{173}{}{这机器人看上去不能运转了。或许是因为缺少动力的关系。}
{174}{}{你没看出这个机器人有什么特别的。}

{175}{}{这个利刃帮成员不想和你说话。}

{176}{}{这个手提箱是密封的，无法打开。}

{177}{}{我们得快点，没时间聊天了。}
{178}{}{只有墨菲斯有这扇门的钥匙。我现在必须离开，去告诉妮可尔这里发生了什么。}
{179}{}{求求你，我必须在他们发现我是谁之前逃出这里。}

{180}{}{你偷窃失败，不知有没有被发现。}
{181}{}{兄弟会成员发现你在偷窃。}

{182}{}{}
{183}{}{}
{184}{}{}
{185}{}{}

{186}{}{You hear over the loudspeaker: "Attention! Intruder Alert."}
{187}{}{粘性物拖慢了你的按键速度。}
#188 is below
#189 is below
{200}{}{You see a horribly-damaged field emitter.}
{201}{}{发射器损坏严重，无法使用。}
{202}{}{发射器损坏严重，无法修复。}
{203}{}{你注意到那力场被损坏得已经可以走过了。}


##################################################
##################################################
## Additions by Sduibek for Fallout Fixt:
##################################################
##################################################


#"Push" telling Tycho/Ian/Katja to move if they're blocking your path
{190}{}{Step aside, please.}
{197}{}{Get the fuck out of my way!}

#What the NPC says after you've made them move
{300}{}{Okay.}
{301}{}{Oops, sorry about that.}
{302}{}{Oh, excuse me.}

# System messages
{191}{}{Tycho is now level }
{192}{}{Ian is now level }
{193}{}{Katja is now level }
{294}{}{You are now level }

{214}{}{The poison has left your system.}

{400}{}{The blast greatly weakens this energy field. It should now be harmless to pass through.}

# Stupid character interacting with hirelings
# TRANSLATION NOTE: Messages 194, 195, 196 have poor grammar,
#  improper spelling and improper capitalization on purpose
#  because they are for a character with Intelligence of 3 or less.
# The same should be done with translated versions.
{194}{}{you move? in my WAY! *frown*}# Call "Step Aside" code
{195}{}{go go, no need frend.}# Telling NPC to leave party
{196}{}{we be frend?}# Request NPC to rejoin party

# Hireling inspections
# Spaces at the beginning and end of 198 and 199 are intentional, do not remove them.
#
{198}{}{ He is wearing }
{199}{}{ She is wearing }
{188}{}{Metal Armor.}
{189}{}{Leather Armor.}
{204}{}{Power Armor.}
{205}{}{Combat Armor.}
{206}{}{Leather Jacket.}
{207}{}{Robes.}
{208}{}{Hardened Power Armor.}
{209}{}{Brotherhood Armor.}
{210}{}{Tesla Armor.}

# Message trying to steal from things like brahmin, rats, scorpions
{211}{}{You cannot steal from this critter.}

# When trying to steal from The Master
{225}{}{Nice try, but that won't work.}

# Message when player examines themselves
#first examine
{212}{}{You look at yourself for a while. Do you like what you see?}
#subsequent examines while on the same map
{218}{}{You must have a lot of time on your hands to be checking yourself out like this.}

# Giving item to hireling (Ian/Tycho/Katja)
{215}{}{Thanks, i'll make good use of that in combat!}

# For what distance hirelings should be from player
{216}{}{ Walk when close.}
{217}{}{ Always run.}

# For notifying user of Violence Level
#### NOT USED ####
{219}{}{Violence Level is currently }
{220}{}{None.}
{221}{}{Minimal.}
{222}{}{Normal.}
{223}{}{Maximum Blood.}
{224}{}{ Maximum Blood advised for characters with Bloody Mess.}
#
# This one is for the option in CARVLEAD.SSL that shouldn't show up
#
{401}{}{CONTACT SDUIBEK IF YOU SEE THIS MESSAGE}

#an old option for debugging purposes
{402}{}{EndGame Mod variables reset. Please try to enter Vault 13 again.}

#### NOT USED ####
{403}{}{You have died. The Vault is doomed.}
#
# For displaying player title on levelup, if user chose for that to be enabled
# space at the end of 404 is intentional, do not remove it.
#
{404}{}{Your title: }
{405}{}{Vault Dweller.}
{406}{}{Vault Scion.}
{407}{}{Vault Veteran.}
{408}{}{Vault Elite.}
{409}{}{Wanderer.}
{410}{}{Desert Wanderer.}
{411}{}{Wanderer of the Wastes.}
{412}{}{Elite Wanderer.}
{413}{}{Strider.}
{414}{}{Desert Strider.}
{415}{}{Strider of the Wastes.}
{416}{}{Strider Elite.}
{417}{}{Vault Hero.}
{418}{}{Wandering Hero.}
{419}{}{Striding Hero.}
{420}{}{Hero of the Desert.}
{421}{}{Hero of the Wastes.}
{422}{}{Hero of the Glowing Lands.}
{423}{}{Paragon.}
{424}{}{Living Legend.}
{425}{}{Last, Best Hope of Humanity.}
#
## Warning player if loading character from old version of Fixt
#
#### OLD, not used, 433 and 434 are now used instead ####
#
{426}{}{You have loaded a game from a version of Fallout older than Fallout Fixt }
# 427 is inserted after 426
{427}{}{VERSION_NUM_HERE - }
# 428 is inserted after 427
{428}{}{playing from this save may result in glitches, unintended game behavior, or crashes. Apologies for the inconvenience and for this dialog.}
{429}{}{[Continue] I understand the risk and wish to continue playing.}
{430}{}{[Return to main menu] Hmm. I do not wish to continue loading this savegame.}
{431}{}{Ugga-wuh?}
# 432 not used
{432}{}{[Continue] I understand the risk and agree not to report gameplay bugs when playing characters from older versions. (Bugs such as typos are still reportable)}
#
#### NEW, used ####
#
#system msg
{433}{}{WARNING: Save is from an old version of Fixt. Might get glitches or crashes.}
#float msg over character, currently disabled
{434}{}{I'm from an older version!}

#
# For door to Brotherhood armory (weapons/armor stash on Lvl1)
#
{500}{}{The door mocks you defiantly by withstanding the blast, receiving only dents and scorch marks.}
{501}{}{The door is concerned with its ability to take more punishment, as it creaks and buckles from the blast.}
{502}{}{The door groans in agony as it is blown from its hinges, falling to the floor with a mighty crash.}
#TRANSLATION NOTE: the spaces at end of 503 and beginning of 504 are required, do not remove them.
{503}{}{You earn }
{504}{}{ experience for successful use of explosives.}
{505}{}{The blast doesn't quite destroy the door. You'll need one more.}

#
# For guards within Brotherhood armory (weapons/armor stash on Lvl1)
#
{601}{}{You shouldn't be in here, Initiate.}
{602}{}{What are you doing in here?}
{603}{}{Please leave. You shouldn't be here.}
{604}{}{Hey, no Initiates.}
{605}{}{Sorry, I shouldn't be talking to anyone. You know how it is.}
{606}{}{This is not the library, my boy. If you want to browse, go to the library.}
{607}{}{This is not the library, my girl. If you want to browse, please go to the library.}

#
# For endgame (when blowing up Vats, and Master's Vault. Both give the XP but didn't notify user previously.)
#
{700}{}{You earn 10000 experience!}
{701}{}{You earn 10000 experience for destroying the Vats.}
{702}{}{You earn 10000 experience for destroying The Master.}

{800}{}{Why are you talking to rats?}

# Used to replace "Days Left: #" Post-It note in PIP-Boy 2000, since that cannot be available in Fallout 2 engine.
# These messages will appear in the console window (bottom-left of game screen) at regular intervals.
{900}{}{PIP-Boy 2000 displays "VAULT 13 WATER: }
{901}{}{}
{902}{}{ DAYS LEFT."}
