{100}{}{你看到一个骷髅帮的混混。}
{101}{}{嘿！你想做什么？！}
{102}{}{你在骷髅帮地盘上，最好快点离开！}
{103}{}{来点钱花吧？}
{104}{}{你在那里瞄什么呢？}
{105}{}{别待在这。}
{106}{}{Zzzzzzzz}
{107}{}{真他妈热啊！}
{108}{}{我很饿。}
{109}{}{让我们开始做事吧。}
{110}{}{为什么我们不能找个人动手？}
{111}{}{我想找点乐子。}
{112}{}{Yawn...}
