{100}{}{你看到一个僵尸警卫。}
{101}{}{离开那！你不能靠近那里。}
{102}{}{好的，见到你我也很高兴。}
{103}{}{啊？}
{104}{}{我是个看守，你要见赛特就到里面找他。}
{105}{}{这扇门是锁着的。你要在天黑的时候再回来看看。}
{106}{}{多谢。}
{107}{}{啊？}
{108}{}{我说过让你离开了，你在这里不受欢迎。}
{109}{}{正确。}
{110}{}{噢！}
{111}{}{黑夜之前这门不会开了。}
{112}{}{我想进去，你有什么办法帮我吗？}
{113}{}{Hmm, okay.}
{114}{}{啊！}
{115}{}{Well, I guess it can't hurt. Go ahead, I'll unlock the door for you.}
{116}{}{我很想帮你，但是如果我帮了，赛特会踢烂我的屁股，你知道那会是什么样的……必须服从他的命令。}
{117}{}{是的，我了解，谢谢。}
{118}{}{Thanks!}
{119}{}{You were warned. Prepare to die.}
{120}{}{The ghoul ignores you.}
