{100}{}{你看到一个在地下生活的僵尸。}
{101}{}{我们只想留在这里，不要管我们。}
{102}{}{赛特是一个无能的蠢货，会把我们都害死的。}
{103}{}{过些日子超级变种人就会来把我们全杀掉，而赛特也不会帮忙的。}
{104}{}{千万别告诉任何人我们躲在这里。}
{105}{}{我不喜欢你的样子。}
{106}{}{别管我们，走开！}
{107}{}{我听到关于你的很多坏话，那是真的吗？}
