{100}{}{我不害怕，我不害怕。}
{101}{}{我害怕。}
{102}{}{我在值勤。走开。}
{103}{}{在这个城里规矩点，否则你有好果子吃。}
{104}{}{你有炸面包圈吗？}
{105}{}{你有没有觉得自己在被监视？好象你在被远处的什么东西控制着？我就会有这样的感觉。}
{106}{}{你知道辐射蝎子对比尔做了什么吗？他们仍然在努力寻找他的腿。}
{107}{}{所以你认为你能对付得了一只辐射蝎子，哼？}
{108}{}{在我看来你一点也不强悍。}
