{100}{}{抱歉，今天没有拳击赛。}
{101}{}{恩【有些犹豫】。}
{102}{}{恩，好的。}
{103}{}{下场比赛什么时候？}
{104}{}{你应该试着向吉斯莫找工作。我听说他总是在找新人进拳击场。}
{105}{}{明天再来试吧。你会在拳击场上见到索尔。}
{106}{}{你刚错过了，两三天后再来，索尔每三天有一场比赛。}
{107}{}{多谢。}
{108}{}{索尔是谁？}
{109}{}{索尔是本地的拳击冠军，也是吉斯莫最得力的拳击手。}
{110}{}{嘿，那里，今天没有拳击比赛。}
{111}{}{明天再来吧。}
{112}{}{后天再来试试。}
{113}{}{那么！你想在比赛中下赌注吗？}
{114}{}{我的钱要用到刀口上，再见。}
{115}{}{有多大获胜的把握？}
{116}{}{不，多谢。我能问些问题吗？}
{117}{}{}
{118}{}{抱歉，今天的比赛结束了。}
{119}{}{恩，好的。不要介意。}
{120}{}{你想赌谁？索尔还是挑战者？押索尔要25个瓶盖，但能赢50个。压挑战者能赢100个！}
{121}{}{我押索尔。}
{122}{}{我会押给挑战者。}
{123}{}{我猜都很好。}
{124}{}{拳击手是谁？}
{125}{}{这些比赛是谁组织的？}
{126}{}{啊，别介意。}
{127}{}{抱歉，我没空，等会吧。}
{128}{}{索尔，迦克镇出拳最快的拳击手！他的肌肉非常的夸张！他一拳就可以把人的身体打穿！}
{129}{}{他是一个漂亮的家伙。}
{130}{}{恩，好，谁组织的这些比赛。}
{131}{}{谢谢。一会见。}
{132}{}{吉斯莫，是雇佣索尔的赌场老板。他偶尔来看一两场比赛，但绝大多数时间在背后组织－很多人会赌这种拳击比赛。这里不会死人，不像哈勃那些杀人比赛。}
{133}{}{杀人比赛？}
{134}{}{谢谢。}
{135}{}{嗯，只是“据说”这样。但是他们说有一个地下拳击场，你付钱就能看到他们至死方休。不是现在的这种。}
{136}{}{恩，谢谢。}
{137}{}{嘿，你在干什么？}
{138}{}{没什么。}
{139}{}{你是想干些什么吧，失败者？}
{140}{}{请退出。}
{141}{}{哦不，别在意，忘了我所说的。}
{142}{}{哈哈，好像你是一个获胜者！给你的瓶盖。}
{143}{}{等你有了足够的瓶盖再回来吧！}
{144}{}{你想在这里等2:00的比赛吗？}
{145}{}{当然。}
{146}{}{不了，我知道怎么做了。我一会回来。}
{147}{}{那你要是错过了比赛，你的赌注就没了！}
{148}{}{比赛开始！}
{149}{}{正在比赛不要打扰我。}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{150}{}{你没能全赢他们，朋友，下次好运。}
{151}{}{你没能全赢他们，宝贝儿，下次好运。}

{152}{}{抱歉，一次比赛只能赌一次。}
