{100}{}{你看见哈里，超级变种人。}
{101}{Harry_0}{嗨！你看上去不像僵尸。为什么？}
{102}{}{那是因为我今天打扮的比较时髦。}
{103}{}{我就是僵尸！}
{104}{}{让我猜猜……因为我不是僵尸？}
{105}{}{呃？}
{106}{Harry_0a}{哼？}
{107}{Harry_0a}{哼？}
{108}{Harry_0b}{啊哼？}
{109}{}{妈妈？}
{110}{Harry_01}{哦哦哦哦……真时髦啊，哈？}
{111}{}{嘻，我是和你开玩笑，我不是僵尸。}
{112}{}{你在这做什么？}
{113}{Harry_02}{你不是僵尸！我知道，我知道！休想愚弄哈里！}
{114}{}{我是僵尸啊，很显然嘛。}
{115}{}{你说得对。既然你知道了，我就要宰了你。}
{116}{Harry_03}{你不是僵尸。命令说，不是僵尸，不能在这里。}
{117}{}{谁给你的命令？}
{118}{}{好，谢谢。我现在就走。}
{119}{Harry_04}{“老副”叫我看着这个地方。不让人进去。尤其是正常人类。要把正常人类带给“老副”。嗨嗨……}
{120}{}{但是我不是正常人！}
{121}{}{好，让我们去见“老副”。}
{122}{}{操，“不让你活下去”怎么样。}
{123}{Harry_05}{哦哈哈，你等着瞧吧。}
{124}{Harry_06}{Oh, uh, okay. Have nice... day.}
{125}{Harry_07}{哈里觉得哈里现在想打你的头。}
{126}{Harry_08}{哦哦哦……哈里困惑。你不是僵尸。你不是正常人。嗯嗯，你是什么？【喃喃自语】}
{127}{}{我是新品种的超级变种人。}
{128}{}{我是非常先进的机器人。}
{129}{}{好吧，我是正常人类。}
{130}{Harry_09}{不！哈里不认识你。不喜欢你！}
{131}{Harry_10}{哦，好的。哈里想想怎么做。}
{132}{Harry_11}{不喜欢你。现在打你。混蛋。}
{133}{Harry_12}{呃，喂，漂亮的女士。你看起来真美。}
{134}{}{你很忙吗？我需要一个强壮的大男人。}
{135}{}{靠近点。我有东西告诉你。}
{136}{Harry_13}{哈里必须守卫这里。必须留在这里。}
{137}{}{呵呵，我明白。那么再见吧。}
{138}{}{那真让我伤心。}
{139}{Harry_14}{嗨，你是正常人类！现在必须把你带给“老副”！}
{140}{}{请不要这么做。让我走。}
{141}{}{啊，见鬼！瞧瞧女性的厉害，变种仔！……}
{142}{Harry_15}{哦……快滚开，不然哈里就有麻烦了。}
{143}{Harry_16}{好吧，立刻走。我必须盯着外面的人。没时间和你纠缠。}
{144}{Harry_17}{你要给我什么？}
{145}{}{给你一个刀削肉尝尝……}
{146}{}{给你一个吻。}
{147}{Harry_18}{你伤害了哈里的朋友！我……杀了……你！}
{148}{Harry_19}{哦……你再说一遍？现在想要什么？}
{149}{}{我想要你带我去见你的上司。}
{150}{}{没事，正好路过。}
{151}{}{我回来修理你。}
{152}{Harry_20}{Um... Okay. Move along then.}
{153}{Harry_21}{嗨，你是正常人！你跟哈里来！}
{154}{Harry_22}{呵呵……好。带你去见“老副”。}
{155}{Harry_23}{嗯……是。你是原屎的正常人。“老副”会高兴的。带走，带走。}
{156}{}{等等，等等！你不明白。}
{157}{}{我用拳头就能杀了你。}
{158}{Harry_24}{不要这样，哈里执行命令，带你去见“老副”。}
{159}{Harry_25}{哈里不这么认为，但是你可以试试。兄弟们，上。}
{160}{Harry_26}{嗨，哈里听说过你。你打破了病毒槽！}
{161}{}{对，是我干的，现在我要灭了你。}
{162}{}{没错，就是我干的，你想怎的？}
{163}{}{嗯哼。}
{164}{Harry_27}{呃，那我就不难为你了。好吗？你不会再来吧？拜托？}
{165}{}{开的条件不够好。}
{166}{}{再见，我还不想看到你嘞。}
{167}{}{呃。}
{168}{Harry200}{什么都不能告诉你！}
{169}{Harry201}{你杀了拉里！}
{170}{Harry202}{你杀了加里！}
{171}{Harry203}{你杀了我的兄弟，巴里！}
{172}{Harry204}{你杀了泰里！}
{173}{Harry205}{你杀了赛莉！他的名字是恶心了点，但不能因为这就杀了他吧！}
{174}{Harry26}{不要打扰我。走开！}
{175}{Harry207}{呃……不知道。}
{176}{Harry300}{我不知道，但是他好像是个大人物。}
{177}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里不好玩的。}
{178}{Harry302}{塞特这个蠢货。他觉得是他在管理这个地方，其实是我们在管。}
{179}{Harry303}{什么？}
{180}{Harry304}{哼！下贱货。}
{181}{Harry305}{很逊。不知道为什么“老副”想要正常人。他们都是废物！}
{182}{Harry306}{那就是这里，蠢货。【叹息】你白痴啊？}
{183}{Harry307}{The U-U-U-Un, I don't know.}
{184}{Harry308}{可爱的小家伙。哈里有次受伤了，他们把我弄好了，还把我弄得更好了！}
{185}{}{哈里正在战斗}
{186}{}{哈里正在战斗}
{187}{}{哈里正在战斗}
{188}{}{哈里正在战斗}
{189}{}{哈里等候30秒}
{190}{}{哈里正在离开}
{191}{}{你不能带我到任何地方！}
{192}{}{好，带我去见你的头儿。}
{193}{}{变种人不理睬你。}


#
# Harry Tell-Me-Abouts
#
{970}{Harry_0b}{哦？}

{980}{Harry_0a}{哦？}
{981}{Harry_0b}{哦？}
{982}{Harry207}{呃……不知道。}
{983}{Harry303}{什么？}
{984}{Harry200}{什么都不能告诉你！}

{1000}{}{Master}
{1001}{}{Lou}
{1002}{}{Set}
{1003}{}{Shed}
{1004}{}{Ghouls}
{1005}{}{Norms}
{1006}{}{Necropolis}
{1007}{}{Unity}
{1008}{}{Cathedral}
{1009}{}{Chip}
{1010}{}{Hall}
{1011}{}{Water}
{1012}{}{Human}
{1013}{}{Normies}
{1014}{}{Normals}
{1015}{}{Children}
{1016}{}{Children of the Cathedral}
{1017}{}{Water Shed}
{1018}{}{Lieutenant}
{1019}{}{Lutenant}
{1020}{}{Loo}
{1021}{}{Lou Tenant}
{1022}{}{Larry}
{1023}{}{Barry}
{1024}{}{Gary}
{1025}{}{Terry}
{1026}{}{Sally}
{1027}{}{Watershed}

{1100}{Harry300}{我不知道，但是他好像是个大人物。}
{1101}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里会很不好玩的。}
{1102}{Harry302}{塞特这个蠢货。他觉得是他在管理这个地方，其实是我们在管。}
{1103}{Harry306}{Here, dummy. *sigh* You stupid?}
{1104}{Harry304}{哼！下贱货。}
{1105}{Harry305}{很逊。不知道为什么“老副”想要正常人。他们都是废物！}
{1106}{Harry306}{Here, dummy. *sigh* You stupid?}
{1107}{Harry307}{这这这，我不知道。}
{1108}{Harry308}{可爱的小家伙。哈里有次受伤了，他们把我弄好了，还把我弄得更好了！}
{1109}{Harry303}{什么？}
{1110}{Harry207}{呃……不知道。}
{1111}{Harry207}{呃……不知道。}
{1112}{Harry305}{很逊。不知道为什么“老副”想要正常人。他们都是废物！}
{1113}{Harry305}{很逊。不知道为什么“老副”想要正常人。他们都是废物！}
{1114}{Harry305}{很逊。不知道为什么“老副”想要正常人。他们都是废物！}
{1115}{Harry308}{可爱的小家伙。哈里有次受伤了，他们把我弄好了，还把我弄得更好了！}
{1116}{Harry308}{可爱的小家伙。哈里有次受伤了，他们把我弄好了，还把我弄得更好了！}
{1117}{Harry306}{Here, dummy. *sigh* You stupid?}
{1118}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里会很不好玩的。}
{1119}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里会很不好玩的。}
{1120}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里会很不好玩的。}
{1121}{Harry301}{他是“副官”，我的头儿。别告诉他，要不哈里会很不好玩的。}
{1122}{Harry200}{什么都不能告诉你！}
{1123}{Harry200}{什么都不能告诉你！}
{1124}{Harry200}{什么都不能告诉你！}
{1125}{Harry200}{什么都不能告诉你！}
{1126}{Harry200}{什么都不能告诉你！}
{1127}{Harry306}{Here, dummy. *sigh* You stupid?}
