# These are people who are running caravans. either gender, but majority Male
# Tone of voice similar to truck drivers of California-- rough and partially
# harsh.
{100}{}{你看见一个商队的车夫。}
{101}{}{今天将会是漫长的一天！}
{102}{}{我今天实在不想干活儿。}
{103}{}{希望我们不会遭到袭击，或者更糟。}
{104}{}{抱歉，我想我们的人手够了。}
{105}{}{抱歉我们的人手够了。}
{106}{}{你想找工作的话应当去商人市场看看。}
{107}{}{希望能卖光。}
{108}{}{早点完事就好了。}
# finish this job.

{109}{}{开路了。}
{110}{}{我要骂娘了。}
# i'm ready for some brawling

{111}{}{出发了！}
{112}{}{今天肯定很热。}
{113}{}{我渴坏了。}
# i am very thirsty

{114}{}{今天几号？}
{115}{}{我一弄完就去马耳他猎鹰酒吧！}
# Falcon is short for Maltese Falcon--Drinking and gambling hall

{116}{}{抱歉，我们刚刚完成一程。}
{117}{}{你要是想找工作的话应当去商人集市。}
# Merchant Market is a section of town in which people gather.

{118}{}{今天是发薪日！}
{119}{}{我这就去鲍勃的烤吧!}
# Bob's is short for Bob's Iguana Bits -- eating establishment

{120}{}{我今天要去还款!}
{121}{}{我累坏了！}
{122}{}{真是漫长的行程！}
{123}{}{我想，就要天黑了。}
{124}{}{老兄，明儿见。}
{125}{}{喔老兄，那晚上真是……}
{126}{}{I'm getting old...}
{200}{}{你看见马特。}
{201}{}{明天我再来找你们这些家伙。希望你们睡个好觉。}
{202}{}{那是个奇怪的梦。}
{203}{}{嗯？有何要我效劳的？}
{204}{}{唔?}
{205}{}{这是什么地方？}
{206}{}{你知道哪儿能找到净水芯片吗？}
{207}{}{为什么这里有这么多货车？}
{208}{}{哦。抱歉我认错人了。再见。}
{209}{}{耶。你去死吧。}
{210}{}{在废土待得太久了，嗯？这可不太好。}
{211}{}{这儿是哈勃城。是废土的贸易中心。是我所知道的最大的城市。这儿的东西应有尽有。还有很多的工作机会。可以说这儿的每个人都有能雇你做些合法或者非法的事儿。}
{212}{}{你知道哪儿能找到净水芯片吗？}
{213}{}{为什么这里有这么多货车？}
{214}{}{贸易？你们做什么贸易？}
{215}{}{在哪儿能找到工作？}
{216}{}{再见。}
{217}{}{净水芯片？喔，你问倒我了。我从来没听说过这种东西。也许你应该到城里的百货商店看看，也许他们知道点儿什么。}
{218}{}{为什么这里有这么多货车？}
{219}{}{多谢。再见。}
{220}{}{这是商队。我们把货物运到废土的每一个角落。迦克镇，兄弟会，沙荫镇，以及很多其他地方。只有大墓地和闪光之地这两个地方我们是不去的。我带领这支商队就要出发了。街对面的那支是刚到的。}
{221}{}{看起来像是我早先见到的那支商队？}
{222}{}{你们做什么贸易？}
{223}{}{这是哪儿？}
{224}{}{在哪儿能找到工作？}
{225}{}{多谢。再见。}
{226}{}{嗯……很多货物。百货店提供人们生存所必需的食物，水，大量的水。水应当是整个废土最缺乏的必需品。}
{227}{}{你知道哪儿能找到净水芯片吗？}
{228}{}{在哪儿能找到工作？}
{229}{}{多谢。再见。}
{230}{}{你可以在哈勃城里随便找个人问问。或者去看看工作的布告牌。在哈勃城各处有几个布告牌。说白了，这里就缺干活的人。}
{231}{}{这是什么地方？}
{232}{}{你知道哪儿能找到净水芯片吗？}
{233}{}{为什么这里有这么多货车？}
{234}{}{多谢。再见。}
{235}{}{【大笑】对，我想正如你所说得那样。要不了多久他们开始看起来没有什么分别了。但相信我他们肯定不会一样的。}
{236}{}{敢取笑我，死！！！}
{237}{}{在哪儿能找到工作？}
{238}{}{再见。}
{300}{}{你看见鲁克。}
{301}{}{这是商队。我们把货物运到废土的每一个角落。迦克镇，兄弟会，沙荫镇，以及很多其他地方。只有大墓地和闪光之地这两个地方我们是不去的。我们刚刚长途跋涉归来。街对面的那支正准备出发。}
{400}{}{你看见约翰。}
{401}{}{几点了你还在这儿晃什么晃？}
{402}{}{你这个傻逼，滚你妈的蛋！}
{403}{}{净水芯片？我从来没听说过这种东西。}
{404}{}{这是我护卫的商队。商人们把货物运到废土的每一个角落。迦克镇，兄弟会，沙荫镇，以及很多其他地方。}
{405}{}{Well... lots of stuff. General stuff people need to live: food, water, lots of water. Water is probably the scarcest commodity in the wastes.}
{406}{}{你可以在哈勃城里随便找个人问问。或者去看看工作的布告牌。在哈勃城各处有几个布告牌。}
{407}{}{这些货车的主人请我当安全护卫。这份工作很危险，但是报酬丰厚。就在前天晚上，我的一个看管货物的同事被杀了。}
{408}{}{商队是？}
{409}{}{Ahhhh. (He assumes a sarcastic tone of voice.) What a sad story. How would you like to join your friend?}
{410}{}{再见。}

## Fallout Fixt:

{501}{}{You see a caravan guard.}
{502}{}{You see a caravan driver.}
{503}{}{You see a caravan driver.}
{504}{}{You see a caravan merchant.}
