{100}{}{你看到一个哈勃城警卫。}
{101}{}{有什么我可以帮忙的？}
{102}{}{是的，你能告诉我这是什么地方吗？}
{103}{}{再见。}
{104}{}{啊哈哈哈，呵呵，呵呵，啊哈哈，呵呵，吼吼。}
{105}{}{伙计，你是个大哑铃吗？离开这里。}
{106}{}{如果你看到纯水商会的牌子和一所小医院，你就在哈勃城的最南部了。}
{107}{}{纯水商会是些什么人？}
{108}{}{一所医院？}
{109}{}{谢谢你，再见。}
{110}{}{那些野蛮的混蛋。因为他们控制了大水塔，所以他们就觉得哈勃城是他们的了。}
{111}{}{一所医院？}
{112}{}{谢谢你，再见。}
{113}{}{这些大教堂教徒在一家哈勃城的医院，他们好像是不错的一群人。}
{114}{}{纯水商会是些什么人？}
{115}{}{谢谢你，再见。}
