{100}{}{你看到一个游侠。}
{101}{}{对不起，我们正在警戒。我现在不能和你交谈。}
{102}{}{你有看见什么东西吗。}
{103}{}{那些变种人会为他们所做的一切付出代价。}
{104}{}{别担心，我们已经完全控制了形势。}
{105}{}{如果我是你就绝不会在附近逗留，新兵，这里看起来会发生更多的流血事件。}
{106}{}{当心点，新兵。}
{107}{}{如果我是你就绝不会在附近逗留，新兵，这里看起来会发生更多的流血事件。}
{108}{}{当心点，陌生人, 麻烦随时出现。}
{109}{}{走开。}
{110}{}{别让我分神，我们正在警戒中。}
{111}{}{保持安静。}
{112}{}{别浪费我的时间，新兵。}
{113}{}{扣紧你的护具，陌生人。}
{114}{}{快逃吧陌生人，在这里变成血腥战场之前。}
{115}{}{那些肮脏的东西该从这个世界清理出去。}
{116}{}{那是什么？}
{117}{}{我的脚受伤了。}
{118}{}{他们会为此付出代价……}
{119}{}{他们再来啊～}
{120}{}{这他妈的是……哦，没什么。}
{121}{}{保持警惕！}
{200}{}{鲍勃，你那边的状况怎么样？}
{201}{}{解除警报。}
{202}{}{我不认为他们会回来。}
{203}{}{别指望它。}
{204}{}{我们的侦察兵有回复了吗？}
{205}{}{还没有。}
{206}{}{侦察兵报告一切正常。}
{207}{}{好的。}
{208}{}{那么，今天早上你都干了些什么，雷？}
{209}{}{我一直在尝试为电浆来复枪扩展射程。}
{210}{}{你检查过加特林镭射机枪吗？}
{211}{}{没错，我参与研制了最初的原型。}
{212}{}{保持肃静！}
{213}{}{是的，长官。抱歉，长官。}
