{100}{}{你看见艾尔文。}
{101}{}{噢孩子，你不能让我一个人呆会儿吗？我自己已经有够多的麻烦了。}
{102}{}{麻烦？也许我能帮助你。}
{103}{}{看起来你是唯一惹上麻烦的人。}
{104}{}{好吧，好吧。没必要对我乱吼。}
{105}{}{呃……我不知道。它恐怕得需要比你更有实力的强者才能解决。听着，为什么不等你积累更多经验之后再回来呢？}
{106}{}{这是场灾难，相信我。没有什么事会一帆风顺。我在城外有个小农场，几天前一伙歹徒突然在那里出现，并且占据了我的家作为他们的营地。他们已经杀了派斯依，我的驴子，并且威胁说如果敢再回去就一并干掉我。}
{107}{}{你只需要告诉我他们在哪儿，剩下的就交给我。}
{108}{}{对不起艾尔文，但我有更重要的事情得做。}
{109}{}{真的吗，你想要那么做？你知道，我不敢再靠近那里。为什么不等你回来，然后再告诉我什么时候可以安全的回家呢？}
# 110 "beat it" means "leave"
{110}{}{仔细听, 我告诉过你让我一个人在这里呆着。那么现在滚吧！}
{111}{}{我知道你会退缩。每个人听到要对付那帮强盗的时候都这个样。}
{112}{}{那么，你已经把那些强盗教训了一顿？我的家现在安全了吗？}
{113}{}{当然了，我的朋友。}
{114}{}{我现在还没时间处理这件事。}
{115}{}{Oh, thank you so much. I am sorry I don't have any riches to give to you, but here, take this for saving my home. It was my father's, passed down to him from Grandpa Rick. You probably need it more than I do.}
{116}{}{你是在开玩笑，对吗？请不要愚弄我。请等我的家真正安全的时候再回来告诉我，好吗？}
{117}{}{太感谢你的帮助了。}

# Nimrod
{122}{}{You earn 500 experience for saving Irwin's farm.}

#for Stupid characters
{118}{}{吼吼？}
{119}{}{你看，我可没时间浪费在傻瓜身上。等你学聪明点再回来吧。}
{120}{}{Uh huh, uh huh, uh huh. I dood it.}
{121}{}{我不确定。}
{123}{}{No find farm. You show?}
{403}{}{Tank yoo!}

# the Raiders at his farm
{300}{}{见上帝去吧!}
{301}{}{干掉……他！}
{302}{}{这将是你最后的晚餐！}
{303}{}{我会把你打成筛子！}

# Sduibek
{400}{}{Not quite. Could you tell me again how to get there?}
{401}{}{I will, but please hurry. I want to go back to my home.}
{402}{}{Thanks.}
