{100}{}{我们可以帮助治疗受伤的身体还有精神的创伤，你需要帮助？}
{101}{}{是的，请帮我。}
{102}{}{你们是谁？}
{103}{}{以前住在这里的人出什么事了？}
{104}{}{Uhn...}
{105}{}{很好，孩子，我现在就给你做检查。}
{106}{}{恭顺的人会有好报。你没有受任何伤，我的孩子。去玩吧。}
{107}{}{你的伤治好了。以后要小心。}
{108}{}{你受伤了。}
{109}{}{看得出，你中毒了。}
{110}{}{嗯，你被辐射了。抱歉，我们治不了这个。}
{111}{}{我们需要你捐}
{112}{}{元才能给你治伤。可以吗？}
{113}{}{好。}
{114}{}{不。}
{115}{}{可是我没那么多钱啊。}
{116}{}{要不你出}
{117}{}{ caps instead?}
{118}{}{我们不讨价还价。你到底接不接受这个价格？}
{119}{}{好，当然。}
{120}{}{狗屎！}
{121}{}{谢谢，我的孩子，那我们开始治疗吧。}
{122}{}{谢谢，我的孩子，那我们开始治疗吧。}
{123}{}{好了。愿大教堂教徒的和平和祝福永远伴随你。}
{124}{}{你的钱不够，那你捐出所有的钱，我们还是愿意给你治疗的，可以吗？}
{125}{}{好。}
{126}{}{不。}
{127}{}{捐出你所有的钱，我们就给你治疗的，可以吗？}
{128}{}{好。}
{129}{}{不。}
{130}{}{你的钱是有能力捐助的，你应该好好学学数学，我的孩子。}
{131}{}{我们是大教堂教徒。我们和废土上受难的人们一起生活和奋斗。如果你到了晒骨场，可以去教堂参观一下。}
{132}{}{谢谢。}
{133}{}{你是干什么的？}
{134}{}{我们是医疗师，也是和平的布道者。我们治疗身体的伤痛，也治疗人们的灵魂。我们只要求一点点相当于医疗成本的捐献。}
{135}{}{听起来很不错。}
{136}{}{我看这都是胡说八道。}
{137}{}{我们不管你怎么想。你大概不愿意听我讲信仰问题了。那么，如有需要，欢迎你来找我们。}
{138}{}{这是最崇高的信念！我们致力于废土的最终和平。所有生物都会化为一身。}
{139}{}{谢谢，再见！}
{140}{}{他们把房子捐献给我们了，方便我们的教义传播世界，也方便我们医疗者救苦救难。}
{141}{}{莫彼得医生居然没意见？}
{142}{}{他们还真是好心人哦，谢谢。}
{143}{}{那个异教徒有什么想法和我们教堂无关，我来这里是尽责尽力的。}
{144}{}{哦，多谢了，再见。}
{145}{}{你为什么要这样，我们又没有伤害你！}
{146}{}{你目前不需要任何救治。}
