{100}{}{你看见憔悴的鲍勃。}
{101}{}{别杀我！我发誓会给你钱的！}
{102}{}{嘟呼。}
{103}{}{那就赶紧给我！}
{104}{}{我可能走错房间了。}
{105}{}{你说什么？}
{106}{}{啊！你就是“笨蛋”弗蕾德，肮脏血腥的杀手！不要杀我！}
{107}{}{拿走，拿走，这是我的全部家当了。}
{108}{}{你是说，你不是来杀我的？}
{109}{}{我不是的，算你运气好。}
{110}{}{不是，谁要挟你？}
{111}{}{谢谢，你进来的时候手里拿着}
{112}{}{我有点紧张。}
{113}{}{谢谢，我只是看到你进来的时候手里拿着}
{114}{}{时有点紧张。}
{115}{}{靠，我以为你是赌场里来催债的。的确，我欠他们很多钱。}
{116}{}{你怎么会欠他们那么多呢？}
{117}{}{你欠赌场里的谁那么多钱？}
{118}{}{你欠多少？}
{119}{}{嗯，多谢。}
{120}{}{他们出老千。我玩过轮盘和纸牌，我的水平不低的。我肯定，那些机器有问题，我输光了。}
{121}{}{你欠赌场里的谁那么多钱？}
{122}{}{你欠多少？}
{123}{}{嗯，多谢。}
{124}{}{两个流氓。他们自称是赌场老板的手下，但是我从来没见过老板。有一个家伙叫艾佐，还有一个总是一付老是了不起的样子。两个骗子。}
{125}{}{你怎么会欠他们那么多？}
{126}{}{你欠了多少？}
{127}{}{嗯，多谢。}
{128}{}{不多，两千块吧。我也就玩了四五个小时。也许还要长点。他们给了我一些筹码，我这里的钱还不起。我要去哈勃城拿钱，但是我要是走的话会被他们揍死的。}
{129}{}{你怎么会欠他们那么多？}
{130}{}{你欠赌场里的谁那么多钱？}
{131}{}{嗯，多谢。}
{132}{}{又是你，你的手气比我好吧。}
{133}{}{嘿，你在我这里干什么？你是赌场来的？}
{134}{}{那！}
{135}{}{是的，我是赌场来的。}
{136}{}{不是，我就随便看看。}
{137}{}{赌场怎么了？}
{138}{}{呼呼，我还以为你是赌场来的，你吓死我了。}
{139}{}{Oh, okay. Bye.}
{140}{}{怎么？}
{141}{}{我在那里惹了麻烦，我欠他们很多钱。}
{142}{}{你怎么会欠他们那么多？}
{143}{}{你欠赌场里的谁那么多钱？}
{144}{}{你欠多少钱？}
{145}{}{嗯，多谢。}
{146}{}{噢，又是你，你差点吓死我了。你看到附近有赌场的人么？}
{147}{}{嗯！}
{148}{}{没有。}
{149}{}{有啊。}
{150}{}{嘿，我有点问题问你。}
{151}{}{好，好，我还需要几天，我连本带息还给他们钱。我是个很好的赌手。}
{152}{}{啊！天！我有麻烦了！拜拜！}
{153}{}{来啊，开枪啊。噢，说错话了，鲍勃，说错话了。}
{154}{}{你怎么会欠他们那么多？}
{155}{}{你欠赌场里的谁那么多钱？}
{156}{}{你欠多少钱？}
{157}{}{嗯，多谢。}
