{100}{}{你看见茱莉亚娜。}
{101}{}{You see a simple inhabitant of Adytum.}
{102}{}{你好。}
{103}{}{呃。}
{104}{}{你好。}
{105}{}{罗梅罗让我给你带信。}
{106}{}{你叫什么名字，小姐？}
{107}{}{我是茱莉亚娜。}
{108}{}{你有工作吗？}
{109}{}{我能问你几个有关这里的事情吗？}
{110}{}{卡勒布让我做什么我就做什么。但我也就懂一点农作。帮不上施密蒂和麦尔斯的忙。}
{111}{}{你说的这些人，能多讲点他们的事情吗？}
{112}{}{我们干活，管理者们保护我们，基本上不让我们离开这里。}
{113}{}{麦尔斯是搞化学的，他做子弹之类的货。施密蒂是个手艺人，会做水壶和刀子。}
{114}{}{你有罗梅罗的消息？什么消息？}
{115}{}{他说他和你没关系了。}
{116}{}{他给你带来爱意。}
{117}{}{他把这个盒子给你做定情物。}
{118}{}{No... it can't be true... I... }
{119}{}{他还说什么了？}
{120}{}{没有，抱歉。}
{121}{}{对了，他还要我把这个给你。}
{122}{}{太浪漫了！我要去见他！如果……也许……可能洛林可以帮我给他带话……}
{123}{}{哦！太感谢你了！我们打算住在这里，和末世论者和平相处。感谢你支持我们的结合。}
{124}{}{没了他我还怎么活啊……}
{125}{}{【茱莉亚娜掏出一把刀插进了自己的心窝！】}
{126}{}{你帮助罗梅罗把盒子送给茱莉亚娜，成全了一对坎坷爱人，你获得250点经验值。}

