{100}{}{你看到一位疲惫的旅行者。}
{101}{}{你看到兰斯，一位刚从长途巡逻中返回的沙荫镇守卫。}
{102}{}{站在那别动。我们听说了你在沙荫镇干的好事，这里没人想和你打交道。}
{103}{}{我只想要你运的东西。交出来。}
{104}{}{朋友，我是一个和平主义者。}
{105}{}{嘿！难道不是我杀了那些辐射蝎并且救回了坦蒂？}
{106}{}{我和沙荫镇没过节，我有点喜欢这儿。}
{107}{}{唔唔?}
{108}{}{我听说过你，我不会让你杀了我的。}
{109}{}{我没什么要对你讲的。}
{110}{}{是吗？你想现在要干什么？}
{111}{}{你知道哪里可以找到净水芯片吗？}
{112}{}{有坦蒂的消息吗？}
{113}{}{最近有没有强盗的消息？}
{114}{}{沙荫镇怎么样？}
{115}{}{哼!}
{116}{}{你好，陌生人。什么让你来到废土？你又是从哪里来？}
{117}{}{我会问你同样的问题。}
{118}{}{抱歉朋友，我觉得这样贸然回答你的问题是相当危险的。}
{119}{}{那里补给比较好呢？}
{120}{}{我来自避难所，幸运的13号避难所！}
{121}{}{呃？}
{122}{}{您好，陌生人。如果你不想发生不愉快的事，我建议你走开。}
# TRANSLATION NOTE
# After line 123, the player-character's name is inserted by the code, and
# then line 124 or line 131 is added.
{123}{}{你好，}
{124}{}{。自从你救回坦蒂后我们就把你当成了朋友，但是最近我听到了一些关于你的肮脏谣言，那些是真的吗？}
{125}{}{林子大了什么鸟都有，管他呢？}
{126}{}{别跟我套近乎，如果你敢走错一步，我就会打到你肚肠都流出来。听到了吗？}
{127}{}{什么谣言？}
{128}{}{哈哈，你说对了。现在把你身上的东西都交出来。}
{129}{}{也许我做错了一些会让我后悔的事情，但是你应该明白那些都是对我的诬蔑。}
{130}{}{。我很高兴你和那些强盗不是一路人！怎么说呢！我是兰斯，沙荫镇的治安官。我对我们在你刚来这里表现的不信任表示歉意。}
{131}{}{嘿兰斯，怎么了？}
{132}{}{嘿兰斯。我曾经也是个正派人，但是身不由己，现在交出你的东西。}
{133}{}{别紧张，兰斯。你一个人在这做什么？}
{134}{}{很好。我会记住的。}
{135}{}{随你的。}
{136}{}{小宝贝，留着你的话去吓唬别人吧。我闭着眼睛都能干掉你。把身上的东西交出来，我留你一条命。}
{137}{}{如果你真的认为我是威胁，就过来杀了我吧。}
{138}{}{那就让我们来试试。我一直都想看看自己的肚肠是什么样子。}
{139}{}{此一时彼一时。最近你对我们做了什么？在我发作前滚远点。}
{140}{}{我们也很喜欢。尤其是在你死菜的时候。受死吧！}
{141}{}{老弟，你大概是去了闪光之地太久，待傻了。}
{142}{}{很抱歉我不知道你说的净水芯片是什么。}
{143}{}{那是一个安装在水纯化系统中的电子装置。}
{144}{}{辐射蝎的问题解决了吗？}
{145}{}{强盗把坦蒂绑走了。我也是搜救中的一员。我估计她现在被关在一个位于沙荫镇南边的强盗窝里。但那里戒备森严，可汗帮明显不想让任何人接近。}
{146}{}{你能带我去沙荫镇吗？}
{147}{}{您能带我去见可汗帮吗？}
{148}{}{我们必须设法把她救回来。}
{149}{}{谢谢你的消息，祝你好运。}
{150}{}{自从教训了可汗帮后我们的情况好点了。真的很感谢你，我们欠你太多了。}
{151}{}{我想要点报酬。}
{152}{}{谢谢。还有其他我能做的吗？}
{153}{}{他们再来的话，和我说一声，我来摆平。}
{154}{}{我们还好。}
{155}{}{确定吗？}
{156}{}{太棒了！}
{157}{}{我不明白你的意思，白痴。}
{158}{}{好吧，我相信你。我是从沙荫镇来的。那是一个离此地不远的村落。}
{159}{}{你能带我去哪里吗？}
{160}{}{那个小镇怎么样？}
{161}{}{我能在哪找到净水芯片吗？}
{162}{}{听起来是个好地方。}
{163}{}{好吧，你有你的秘密，我有我的，再见。}
{164}{}{也许是吧。尽管有些遗憾。}
{165}{}{我曾进去过迦克镇。它大概在这儿的西南方，但那时我走了很远的路所以不太确定。}
{166}{}{是的。据我所知，所有的避难所都毁了。告诉我其他的事情。}
{167}{}{那不是我想问的……噢，别介意！}
{168}{}{那算不上什么回答。他们议论说你是一个杀手，小偷，盗墓贼。说你会杀掉任何你看不顺眼的人。这些都是真的吗？}
{169}{}{好了，我不是到现在都没有杀你吗？很明显他们在说谎。}
{170}{}{有不少是真的。我已经过了不少好日子了。}
{171}{}{我曾树敌不少。对他们我已经手下留情了。}
{172}{}{我很少杀人，也不是滥杀无辜。}
{173}{}{他们议论说你是一个杀手，小偷，盗墓贼。说你会杀掉任何你看不顺眼的人。这些都是真的吗？}
{174}{}{当然，我们会的。如果你干的事像个强盗，我们也会宰了你。}
{175}{}{我现在对你暂不下定论。不过一个人的荣誉是最重要的，而你显然仍须努力。希望我们下次见面时你已有所改观。}
{176}{}{我们正要回镇上。一起走吗？我们有保镖护送。}
{177}{}{当然。}
{178}{}{今天不行。}
{179}{}{还有些清理的活儿没干完。我们发现了几个荒废了的强盗窝点没被收拾干净；我猜他们互相火并，我们就能获得更多的弹药和药品。}
{180}{}{我会为此遗憾终生。}
{181}{}{在我发作之前你最好从我眼前消失。}
{182}{}{我们仍看到零星的小群，它们一定是在从沙漠深处和闪光之地向这里迁徙。目前我们看到的还只是一小部分，但比起去年已经好很多了，我们很感谢你。}
{183}{}{听起来不错。再见！}
{184}{}{当然。我们走。}
{185}{}{我想我一定是疯了。我会带你走。走吧。}
{186}{}{好好去寻死吧，反正你觉得很值。祝你好运，朋友。}
{187}{}{我要出发了，你多保重。}
{188}{}{我没有很多，不过你尽管拿。}
{189}{}{我已经顾不了那么多了。走了，你多保重。}
{190}{}{我们会的。我要走了，你多保重。}
{191}{}{好的。我们走。}
{192}{}{我不会带一个炸弹回家。如果你想去沙荫镇，最好给我规规矩矩的。}
{193}{}{村子太小。我们靠养双头牛维生。这儿周围都是贫瘠的荒地，牧场是很宝贵的。}
{194}{}{在这放养双头牛的鬼乡下？你一定是疯了！可能这方圆两百里内没有一块能工作的电子元件。}
{195}{}{你找到了问题的关键。我想我们应当沿着这条线索谨慎的找下去。如果我是你，我会去调查这件事。否则人们将来很难会再信任你。}
{196}{}{你又坏了我的好事，这次我一定要杀了你。}
{197}{}{我们走。}
{198}{}{让我猜猜，一定是有人告诉你我打鼾的秘密了。呵呵，你多保重。}
{199}{}{是这样。好了，我该出发了。你多保重。}
{200}{}{呆在那别动。我不知道你是否加入了变种人。如果是真的，我会毫不犹豫的杀了你。}
{201}{}{变种人是什么？}
{202}{}{你是谁？}
{203}{}{你怎么了？}
{204}{}{好的，非常棒！}
{205}{}{呃哼？}
{206}{}{变种人会席卷沙荫镇，我们大部分人都会死。他们找到我们只是时间问题了！}
{207}{}{你和我说什么都没有用。我们都要死了！我们所有的人！那些该死的强盗和辐射蝎再也算不了什么了……哈！哈！哈！}
{208}{}{闭嘴！我不喜欢像这样毫无意义的争吵！我最烦的就是他妈的吵架……}
