{100}{}{You see a nervous ghoul with an air of authority.}
{101}{}{谢谢你没直接一枪打过来，我有什么可以效劳的？}
{102}{}{有，我在找水。}
{103}{}{当然。你是谁？}
{104}{}{不。}
{105}{}{啊，你如果需要的话，可以在这里休息，我们不会伤害你的。}
{106}{}{啊。}
{107}{}{我是一群被迫转到地下生活的人的领袖。}
{108}{}{谁把你们赶下来的？}
{109}{}{日，这太衰了。}
{110}{}{嗯，好，再见。}
{111}{}{大墓地的地表和水源都被赛特和他的手下控制了，我们是相比而言更爱好和平的一群，这就激怒了赛特。}
{112}{}{谁是赛特？}
{113}{}{我那赛特那厮处理了，他不会再麻烦你们了。}
{114}{}{那你们没了水怎么在这里活下去的？}
{115}{}{我本人也不喜欢娘娘腔的和平分子，赛特至少还算是个爷们。}
{116}{}{赛特和我们一样也是一个僵尸，但在地表世界获得了一定的权力，他是个混球。}
{117}{}{他听起来比你们这些变态分子有趣儿多了。}
{118}{}{他为什么还让你们在这里活下来了？}
{119}{}{他也没说，可能是因为赛特怕防御大墓地城的时候人手不够吧，所以他给了我们必需的水。}
{120}{}{这些水都是哪里来的？}
{121}{}{我的人民需要水！如果你知道从哪里拿的，告诉我！}
{122}{}{我在找净水芯片，为我的人民提供水源，你知道哪里有这个东西么？}
{123}{}{我要是他才不会让你们这些人保护这个破地方，谈谈水的事情吧。}
{124}{}{知道不久前，我们还是从地表的水口用水泵抽水。}
{125}{}{不久前之后呢？}
{126}{}{我怎么去水泵那里？}
{127}{}{什么是水口？}
{128}{}{我们的水泵坏了，所以我们现在是从地下的某个地方取水，我听说那里有台净水控制电脑。}
{129}{}{谢谢。}
{130}{}{那在哪里？}
{131}{}{水口在北方，你可以从下水道去那里。}
{132}{}{你不会是想把净水芯片取走吧？}
{133}{}{呃……不，不是的。我才不会做这种事情呢，我去看看它的工作情况。}
{134}{}{当然了，我们的人民需要净水芯片。}
{135}{}{怎么？}
{136}{}{如果你把芯片拿走，我们都会死的，我们的水泵坏了，我们没有水了。}
{137}{}{我才不管你们的死活，我们也要芯片才能生存下去，再见！}
{138}{}{也许你们的水泵能修好？}
{139}{}{如果这样，我不能让你走！}
{140}{}{我不相信你。}
{141}{}{对不起，我不是想骗你的。如果我拿走了芯片，会怎么样？}
{142}{}{我不在乎，如果你再挡道，我就会让你消失！}
{143}{}{这很难的，修理水泵的那部分零件丢在水口下的下水道了。}
{144}{}{这有什么难的？}
{145}{}{你是说这些零件么？【你把捡到的零件给他看】}
{146}{}{下水道里都是怪物，我派去找零件的人都没回来。你愿意去帮我们拿来再修好水泵吗？}
{147}{}{太烦人了，我还是直接拿走芯片方便。}
{148}{}{好的。}
{149}{}{你们既然这般无能，我就帮你们一把吧。}
{150}{}{谢谢。拿到零件后，回来，也许我能帮上点忙。}
{151}{}{好，我去了。}
{152}{}{你找到水泵零件了？}
{153}{}{还没。}
{154}{}{算了，我不费这个事了。}
{155}{}{我要去哪里找，你再说一遍。}
{156}{}{那好，我祝你好运。}
{157}{}{你回来了，找到修水泵的零件了？}
{158}{}{对，这里。}
{159}{}{没错，但是我不打算去修那个什么水泵了。}
{160}{}{你用这些零件去修理，我可以帮你的。这是我们在附近找到的几本书，也许有用，带上零件去修好它吧。}
{161}{}{我不能再帮你什么了，祝你修理顺利。带上零件去修好它吧。}
{162}{}{你修好水泵了？}
{163}{}{还没，我在努力。}
{164}{}{还没，我不干了。}
{165}{}{没错，这就是我说的那些零件。你先找到了，真是太好了。}
{166}{}{我还需要知道些什么？}
{167}{}{就在水泵旁边。}
{168}{}{我说过了，就在水口下方的下水道里，从这里往东，再往北走，你就可以看见水口了。}
{169}{}{谢谢你的指点，再见。}
{170}{}{谢谢你能帮忙，你还要知道什么？}
{171}{}{你们在这里没水怎么活下去的？}
{172}{}{那里就是我们储水和分发水的地方。}
{173}{}{具体位置？}
{174}{}{最近我听说有人控制了水口，但是，我们的份额没减少。不知道为什么。}
{175}{}{我怎么去水口？}
{176}{}{什么是水口？}
{177}{}{谢谢你修好了水泵，我希望你带着芯片回去之后能帮助你的人民度过难关。}
{178}{}{多谢，再见。}
{179}{}{你修好了水泵，水再次流出来了，但是，你还没有找到你需要的东西。}
{180}{}{是的，我找不到净水芯片。}
{181}{}{我听说它可以在水口地下很深的地方找到。我预祝你成功。}
{182}{}{我看到你找到了你要的东西，你要知道，如果拿走了芯片，我们都会死的。}
{183}{}{是，但是我正在修理水泵，你上次说在哪里找到零件来着？}
{184}{}{我需要芯片，我没时间管你们的破事。}
{185}{}{我没有其他办法了。}
{186}{}{我受够了你的虚伪说辞了，我不想再和你多嘴了。}
{187}{}{我们以前在水口有一台水泵可以抽水，但是现在它坏了，修理的零件就在水口地下的下水道里。}
{189}{}{你们为什么自己不去拿零件？}
{190}{}{你不需要怕我们！}
{191}{}{在你离开前，我有话要和你说。}
{192}{}{你逼人太甚，我要出手了。}
{193}{}{Wait, don't shoot!}
{194}{}{你不需要怕我们！}
{195}{}{在你离开前，我有话要和你说。}
{196}{}{你逼人太甚，我要出手了。}
{200}{}{运气不好。}
{201}{}{水泵不能修好吗？}
{202}{}{对不起，我们的人民需要芯片才能生存。}
{203}{}{别拿走我们的芯片，我们会死的。}
{204}{}{也许吧，但是零件在水口下方的下水道里，那里怪物很多，我们拿不回来。}
{205}{}{对不起，爱莫能助。}
{206}{}{我去找零件。}
#
#  by Sduibek for Fallout Fixt:
#
{300}{}{You see: Undergrounder Leader.}


############ Tell Me Abouts

{1000}{}{Set}
{1001}{}{Master}
{1002}{}{Water}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Necropolis}
{1006}{}{Chip}

{1100}{}{他试图控制整个大墓地，还把我们赶到地下。}
{1101}{}{他和变种人有联系，我也不知道太多。}
{1102}{}{我们从水口下面的地方得到水，可能和那个地方有关系。}
{1103}{}{坏掉的水泵在那里，变种人在那里分发水。}
{1104}{}{赛特所谓的宫殿。}
{1105}{}{死城，我们希望和平地生活，可惜变种人和赛特不让。}
{1106}{}{我们从水口下面的地方得到水，可能和那个地方有关系。}


