{100}{}{你看到一个僵尸哨兵。}
{101}{}{我现在不能说话，我正在侦察。}
{102}{}{一个人类奸细！}
{103}{}{你坐在这干啥？}
{104}{}{嗯，没事。你在干啥？}
{105}{}{我只是四处看看。}
{106}{}{呵。}
{107}{}{怎么？没事啊，我住在这里。}
{108}{}{你在这什么也找不到，走吧。}
{109}{}{【完成】}
{200}{}{我们需要水才能活下去。}
{201}{}{在你离开之前请和我们的头儿谈谈。}
