{100}{}{你看见莱尔。}
{101}{}{因此你就是偷水贼！你是叛徒！}
{102}{}{我非常高兴严酷的考验结束了。谢谢你。}
{103}{}{嗨，}
{104}{}{。}
{105}{}{嗨，莱尔。你进展如何？}
{106}{}{我们这里还好。但是我希望你能很快找到净水芯片。每个人都在生死边缘上，我们快没时间了。}
{107}{}{哇嗷！}
{108}{}{不是那么好。自从前几天我的定额给水被偷，事情就变糟了。每个人都非常恐慌，而且没有人知道该做什么。}
{109}{}{太坏了。我希望事情会好起来。}
{110}{}{我去看看，也许能帮上忙。}
{111}{}{是的，我也这么希望。}
{112}{}{谢谢。我当然希望你能查个水落石出。请赶快去找新的净水芯片。如果我们还有一枚净水芯片在运作，就不会发生这种疯狂的事！}
{113}{}{谢谢你逮到了那个小偷。你做了一件好事。但是请赶快去找净水芯片，否则就太晚了！}
{114}{}{你怎么可以这样背叛我们？走开！}
