{100}{}{你看见一个技师。他正在勤奋的为主教的“同一事业”工作。}
{101}{}{我们为主教而工作。}
{102}{}{我们正在为主教工作，不要骚扰我们。}
{103}{}{主教！一个入侵者！}
{200}{}{你看见超级变种人队长维舍斯。他看起来让人感到恶心。}
{201}{}{你看见一个让人恶心的超级变种人。}
{202}{}{主教必将胜利。你有什么消息告诉我？}
{203}{}{呼！}
{204}{}{嗯，战争很顺利。}
{205}{}{副官让我给主教大人捎个信，我现在就要见他。}
{206}{}{唯一的消息就是你马上要变成原料了。}
{207}{}{一个入侵者！}
{208}{}{你的表情出卖了你，入侵者。我现在就会清除你对我们的威胁。}
{209}{}{开什么玩笑。你一定是在扯谎。}
{210}{}{啊，好，那又如何？}
{211}{}{不是。中尉无法确信常规的方法可以传送这个消息。我必须立刻见主教！不能在这里浪费时间！}
{212}{}{从那里走，走廊上要注意，我想你做好了保护措施。}
{213}{}{当然。谢谢你。“同一”必胜！}
{214}{}{不，还没，那我应该怎么做？}
{215}{}{当然！没有保护装置你别想通过走廊。你把精神攻击免疫器弄到哪去了？}
{216}{}{我把它落在我另一件长袍里了。}
{217}{}{中尉没来得及给我一个。}
{218}{}{啊，幽默，我喜欢。【停顿】很明显我没有。你需要到二层的洗脑室去拿一个。“同一”必胜！}
{219}{}{要么他是个笨蛋，要么你有问题，你到底是怎么回事？}
{220}{}{很明显，他是个白痴。}
{221}{}{第二个可能。}
{222}{}{快走，继续你的任务。我没时间和你耗了。}
{300}{}{房间的一侧烟头已经被堆成了小山。}
{301}{}{一个超级变种人在房间一侧走动，用打火机点着了一支香烟。}
{302}{}{你看到一个超级变种人，他的嘴里叼着一支香烟。}
{303}{}{超级变种人把烟头用手指一弹，烟头掉到了角落里。}
