{100}{}{你看到一个警卫。}
{101}{}{你到这里有什么事？}
{102}{}{呜？}
{103}{}{我只是随便看看。}
{104}{}{我想买几件武器。}
{105}{}{}
{106}{}{}
{107}{}{我没兴趣听笑话，如果你不离开这个区我就用枪招呼你。}
{108}{}{我不喜欢像你这种喜欢四处打探的人，现在走开就不用挨枪子儿了。}
{109}{}{}
{110}{}{}
{111}{}{你闻上去像双头牛，不过我认为你没它那么聪明。}
{112}{}{}
{113}{}{呵，非常好。顾客总是受欢迎的。进来吧，但是你得把枪收起来。去找赞克，他能满足你的任何需要。}
{114}{}{}
{115}{}{我需要和你老板说话，这非常重要。}
{116}{}{哦，好的。加布里尔有话对你说，进去吧。}
{117}{}{是的，我记得你，进去吧。}
{118}{}{我需要和加布里尔说话，这非常重要。}
{119}{}{我想从赞克那买点武器。}
