{100}{}{修复的水泵现在运转的很好。}
{101}{}{水泵不运转是因为真空泵坏了。}
{102}{}{水泵没有运行。}
{103}{}{一个机器。}
{104}{}{水泵不运转是因为真空泵坏了。}
{105}{}{它可能需要一个新的保险丝。}
{106}{}{水泵没有在运转。}
{107}{}{没有备用真空泵你无法修理水泵。}
{108}{}{你修理水泵失败了，它可能需要一个新保险丝。}
{109}{}{你修理水泵失败了。}
{110}{}{这个水泵不能运转是因为真空泵坏了。}
{111}{}{这个水泵或许需要一个新保险丝。}
{112}{}{水泵没有在运转。}
{113}{}{你没有发现什么不正常。}
{114}{}{巨大水泵的一阵颠簸，你把那个丢失的零件安装上了。}
{115}{}{不知什么原因，损坏的零件割破了你的手对你造成1点伤害。}
{116}{}{你修理那个部件有些困难。}
{117}{}{这个不能用在水泵上。}
{118}{}{You earn 1000 experience for fixing the water pump. The ghouls will be grateful!}
