{100}{}{你看到基登，相貌普通的人类。他戴着头箍。}
{101}{}{贾森是活的神！圆满的才可通过。}
{102}{}{圆满？他们用你戴着的那装置扰乱了你的精神吗？}
{103}{}{贾森是谁？}
{104}{}{圆满是什么意思？}
{105}{}{我刚杀了他，现在想来，他是个死的神了。想跟他一样吗？}
{106}{}{哈？}
{107}{}{墙壁也有思想……我……明天见过你？}
{108}{}{其他跟你一样的人在墙里？}
{109}{}{算了。}
{110}{}{真想现在就杀了你。不过你能打开这力场吗？}
{111}{}{打开力场，不然你死定了。}
{112}{}{啊，对拉。你就是我要找的“实验”吧？}
{113}{}{贾森？贾森是谁？}
{114}{}{你刚才说……算了。}
{115}{}{停！}
{116}{}{对，墙是活的和那些从前就走掉的。}
{117}{}{他们怎么了？}
{118}{}{啊，我得走了。}
{119}{}{灵魂的会面……合并，去保护，主教一切。}
{120}{}{明白了。我怎么保护自己不受主教的“保护”？}
{121}{}{狗的战争呢？}
{122}{}{我得保护主教。怎么能找到他。}
{123}{}{挡我者死！我会证明给你看的，如果你不打开这力场的话。}
{124}{}{再见。}
{125}{}{这是唯一的和平，统一……代价……痛苦……必须让个人盲目……麻痹}
{126}{}{好吧，我要加入。上哪能拿到那个傻兮兮的头箍？}
{127}{}{太好了！怎么加入？}
{128}{}{我想崩了你的头！}
{129}{}{我没空玩这个，再见。}
{130}{}{我会净化你，必须给予我所不能。}
{131}{}{谢谢。}
{132}{}{去你的净化，你这个白痴杂种！}
{133}{}{净化？用什么净化？}
{134}{}{不了，谢谢。}
{135}{}{你不能杀掉万中无一的天才，你这个……嚯啊！}
{136}{}{对啊，可我会带来巨大的痛苦！}
{137}{}{我不想杀戮。我要敬拜。}
{138}{}{很明显，再见！}
{139}{}{镇定！脆弱的发展……交流，无效……死亡尽头。}
{140}{}{墙也有思想……我明天……见过你，是吗？}
{141}{}{我当你同意了。}
{142}{}{太好了！怎么加入？}
{143}{}{亵渎……瓦解……死亡将……拯救……力量！}
{144}{}{思想……墙……在伟大之前……}
{145}{}{之前走的人……会阻止你的。}
{146}{}{我得把那改变。}
{147}{}{我必须完成这行程，是主教的意思。}
{148}{}{谁？怎么？}
{149}{}{对，不过他们也不会好过。}
{150}{}{很抱歉打扰了你。再见。}
{151}{}{我想帮你逃走。}
{200}{}{你看到穆尔，穿着破烂的家伙。他戴着头箍。}
{201}{}{你看见一个穿着破烂的家伙。}
{202}{}{道路要被染红！我将破坏！}
{203}{}{对啊！}
{204}{}{你说什么呢？}
{205}{}{是啊，被你的血染红！}
{206}{}{啊对，再见。}
{207}{}{啊！}
{208}{}{我将阻止恒动！主教给了我力量……}
{209}{}{好吧，汉克。我想见主教，怎么走？}
{210}{}{什么恒动？}
{211}{}{当然了。我很了解……}
{212}{}{我想把你的头劈开！你这个扯淡的白痴。}
{213}{}{哦，怎么又来了。再见。}
{214}{}{只有充满力量的可以通过，但他们会阻止的……}
{215}{}{打开这个力场，不然就让你看看我的力量。}
{216}{}{但我需要见主教。}
{217}{}{能教我怎么做吗？}
{218}{}{基登……基登告诉路。}
{219}{}{对哦。}
{300}{}{你看到露西，看起来正常的人类女性。她戴着头箍。}
{301}{}{你见到一个女性人类，她在盯着你的鞋。}
{302}{}{这里不是家园，这里不是家园，这里不是家园……【前后晃着】}
{303}{}{哈！}
{304}{}{够了！}
{305}{}{这地方怎么了？不是你的家？}
{306}{}{我同意。完全彻底同意。你是对的……【她顿了一下】你刚才说什么？哦，你不会注意的。}
{307}{}{【紧张的看着你】我会为此杀掉你！我会让你的血红掉。等等，血本来就是红的，我怎么能让它再红？这我做不来。恩，我得想想，走开！}
{308}{}{我的家，啊，对。这里。是的，是这里。这是我家。【她上蹿下跳的】我太高兴了。你不知道这让我多高兴。我想我得去捶会儿墙。}
{309}{}{忙着呢。我几乎搞定让这世界如此操蛋的环境问题了，但我一直想着紫色的恐龙，停不下来，这有问题吗？}
{310}{}{别烦我了，我在思考……}
{400}{}{你看到维刚，彻底的失败者。他戴着头箍。}
{401}{}{你看到一个彻底的失败者的样子。}
{402}{}{我累了。}
{403}{}{生活是地狱。}
{404}{}{我活够了。}
{405}{}{黑暗降临，}
{406}{}{随便吧。}
{500}{}{墙上写着“警告！请勿打扰！”}
