{100}{}{你看到雷。}
{101}{}{你看到一个超级变种人。}
{102}{}{你不属于这地方。}
{103}{}{【看上去迷茫而悲伤】我不这样想，可……你为什么在这？}
{104}{}{你也一样。}
{105}{}{啊……我是这儿的。主教让我装扮成这样的，为了检视我们的保安状况。}
{106}{}{我是这儿的，来这儿杀你的。}
{107}{}{好的，我这就走。}
{108}{}{哈。}
{109}{}{【叹气】又怎么了？}
{110}{}{我迷路了……能告诉我怎样接近主教吗？我得去杀他。}
{111}{}{没事，再见。}
{112}{}{来看看你的皮被扒掉了是个什么模样，你这个变种杂碎。}
{113}{}{你哪不对劲吗？}
{114}{}{很好，呜呜唔唔。}
{115}{}{我是来……我是来主教商量点事情的。}
{116}{}{当然。“同一”才有和平。能告诉我你从哪来吗？}
{117}{}{哦，我啊。我走了相当长的一段路程就是想来亲眼见一见主教。}
{118}{}{要学的太多了。怎么才能从主教那里赢得人心啊？}
{119}{}{我昨天这么干过。今天我是要来在主教身上点把火，还要在他恶心的尸体上烤点蘑菇，双头牛睾丸之类的，那会是怎样一副盛景啊！}
{120}{}{我觉得主教是疯了。}
{121}{}{我是从那个地方来的……就那个。}
{122}{}{太巧了，我也是！}
{123}{}{哪？}
{124}{}{我从避难所来……是血统纯正的人类。}
{125}{}{什么？你是傻子吗？}
{126}{}{你从哪来？}
{127}{}{【小声地说】我从避难所来……是血统纯正的人类。}
{128}{}{我不想说。再见。}
{129}{}{北面的一个小村子。}
{130}{}{干嘛告诉你。你只是那个“人”的跟班而已。}
{131}{}{跟我说那个干嘛？我应该在主教之前就……}
{132}{}{但你不会。}
{133}{}{那就试试啊。}
{134}{}{啊，我该把枪插进你喉咙然后扣动扳机！}
{135}{}{请别那么做。}
{136}{}{我知道你为什么这么痛苦。}
{137}{}{现在我要走了。}
{138}{}{你说的对……只要我能理清思绪。有什么事情……}
{139}{}{你知道为什么你不能正常思考。}
{140}{}{是主教阻止你思考的。思想会妨碍团结统一。}
{141}{}{主教是你痛苦的根源。}
{142}{}{嘿，我有主意了－不如把主教切开看看里面到底是什么玩意儿。}
{143}{}{告诉我！拜托！！}
{144}{}{You used to be human, too. The Master dipped you in the Forced Evolutionary Virus and mutated you.}
{145}{}{抱歉，我不能。}
{146}{}{只有主教能告诉你一切。}
{147}{}{只有主教能告诉你一切。但你最好快点找他谈，我可要去杀他了。}
{148}{}{抱歉，我得走了。}
{149}{}{你瞧不起我，我该杀了你。}
{150}{}{我有个主意－杀了主教，看他对你做了什么啊。}
{151}{}{不，你该杀主教，看他对你做了什么啊。我正要这么干呢，想跟我一起吗？}
{152}{}{为什么？又不是我把你变成这样的。}
{153}{}{你可以试试啊。}
{154}{}{不了。回见。}
{155}{}{咱们去把他的头拧烂，让他的眼珠子爆出来。}
{156}{}{你杀不了主教。他不会死的。}
{157}{}{说的对。我得离开这。}
{158}{}{咱们走着瞧吧。}
{159}{}{恩。当他的教派被毁了之后，看他还能不能活下去……}
{160}{}{那不可能……主教保卫我们……团结我们……}
{161}{}{哈，朋友，你就是那“同一”活生生的例子。我知道是怎么回事。我就是来阻止主教“同一”其他人的。}
{162}{}{被神保卫，团结一致，是什么感觉？}
{163}{}{啊，对啊，他通过控制所有人来保护他自己。}
{164}{}{够了！再见！}
{165}{}{马上离开，不然我就必须解决你了。}
{166}{}{啊啊啊啊！【他抱着头，痛苦迷茫的】我……不能……}
{167}{}{这就对了，主教剥夺了你在这世界上所有的一切，包括你做人类的权利。}
{168}{}{你知道这是真的……这就是你迷惑的原因。你在跟变异抗争。帮我摧毁主教吧，这也是替你自己报仇。}
{169}{}{你当然能。来吧，咱们去杀了主教，肯定很有趣的。}
{170}{}{我最好走了。}
{171}{}{看到你这么痛苦我很抱歉，但这是主教干的好事。}
{172}{}{我要把他的眼挖出来。我要把他粘乎乎的头从那些电线里扯出来！！！你……最好离开这里……我会料理主教的。}
{173}{}{很好！！}
{174}{}{谢谢你这么说，但我想自己做这事。想帮忙吗？}
{175}{}{我要留下。我还有点事没干完。}
