{100}{}{哦，我的上帝！你杀了他！}
{101}{}{哼！}
{102}{}{可怜的人。}
{103}{}{他是我的敌人。我不得不杀了他。}
{104}{}{我很抱歉。我不知道他与你那么接近你。}
{105}{}{你不是非得杀了他！【莎拉发出呜咽声。】滚开。}
{106}{}{他是我的爱人。他是我最好的朋友。我不能相信你对他这样做了。}
{107}{}{再一次，我抱歉。我怎么能晓得他对你意味着这么多?看他。他是一个变种人。}
{108}{}{我正准备去杀死所有像他的那类人。}
{109}{}{他是个人。他能够生存下来的唯一方法是被浸渍着。你杀了他。}
{110}{}{对不起。}
{111}{}{哦，好吧。至少他是算入我战绩中的一个家伙。}
{112}{}{卑鄙的家伙。}
{113}{}{你在你的保护室外干什么？}
{114}{}{咋咯－咋咯！}
{115}{}{到处走走。}
{116}{}{我在这可不是一个囚犯。}
{117}{}{不，谢了，我已经有个男朋友了。}
{118}{}{你应该在你的小隔间里。卫兵为了保护我们留我们在这儿。机器人已经被设好程序去攻击没有护卫的平民。一旦我被浸渍了，我就会有能力花时间帮助“同一”事业。}
{119}{}{是，好的。管它呢。玩得开心。}
{120}{}{你想要这样？}
{121}{}{当然，这是人类有过的生存下去的最好机会。}
{122}{}{哇噢！我认为你能招致很多不幸。请离我远点。}
{123}{}{对不起，我们在这儿说话！}
