{100}{}{你看到一台黯淡的发光的电脑。}
{101}{}{有一股电力涌入。电力的大多数看上去已经被发送去维持少数仍然半工作中的系统。}
{102}{}{你没注意到什么不同的。}
{103}{}{这台电脑正在发出不可思议的嗡嗡噪声。}
{104}{}{一台连接到这台电脑的监视器正在反复地显示着文字“系统故障”。}
{105}{}{这台电脑看来曾被一个僵尸攻击。}
{106}{}{这台电脑上的灯在闪着，但是它对你来说看上去很混乱。}
{107}{}{当你触碰这台电脑的时候它给了你一下无害的电击。}
{108}{}{在检查后你注意到这台电脑已经被老鼠当作窝了。}
{109}{}{随机数正在通过一个连接到这个系统的屏幕显示出来。}
{110}{}{这台电脑正在发出你曾听过的最糟糕的噪声。文字“加雷德”被显示在监视器上。}
{111}{}{这台电脑的一半是黑的，是被过去的一场火烧焦的。}
