{100}{}{你看见一堵结实的墙。}
{101}{}{墙上的这一块看上去很奇怪。}
{102}{}{你看见一扇拉门。}
{103}{}{门锁着。}
{104}{}{你引爆了门上的陷阱。}
{105}{}{ 探测出这门上的一个陷阱。}
{106}{}{你探测出这门上的一个陷阱。}
{107}{}{什么也没发生。}
{108}{}{门锁已经开了。}
{109}{}{碰上这个困难的锁，你弄坏了你的撬锁工具。}
{110}{}{你没能撬开这锁。}
{111}{}{你撬开了门上的锁。}
{112}{}{这锁太难了，当下你撬不开。}
{113}{}{你注意到这扇锁着的门上的一个高度易爆陷阱。}
{114}{}{你注意到这扇门上的一个高度易爆陷阱。}
{115}{}{你注意到这扇锁着的门上的一个陷阱。}
{116}{}{你注意到这扇门上的一个陷阱。}
{117}{}{你没看见这扇锁着的门上有什么特殊的。}
{118}{}{你没看见这扇门上有什么特殊的。}
