{100}{}{你看到托马斯兄弟。}
{101}{}{好的孩子。今天我们将学习一些搏斗技巧。}
{102}{}{在近战中使用什么技巧取决于你对手的大小，距离和速度。}
{103}{}{如果给你试探对手的机会。}
{104}{}{不要急于进攻。}
{105}{}{来吧小伙子们，和我这个老头子较量较量。}
{106}{}{啊！}
{107}{}{噢。}
{108}{}{人都到齐了，我们开始复习。}
{109}{}{你们看到他刚才怎么失去平衡了吧？}
{110}{}{动作太大反而使你受到攻击。}
{111}{}{当你进攻时最好不要动作幅度太大。}
{112}{}{为什么动作幅度太大不好？}
{113}{}{如果你有一个机会杀死对方，你会不去做吗？}
{114}{}{那是一个致命的危险。}
{115}{}{动作幅度太大的话，你的弱点就被暴露，对方也会轻易的把你打倒。}
{116}{}{轻轻一推你就会屁股落地。}
{117}{}{好，让我们给另外一个壮汉与老头子较量的机会。}
{118}{}{让我们看看你以前学过的是什么？}
{119}{}{不错，你快要打到我了。}
{120}{}{你真的打算做一个初级研究员？}
{121}{}{天赋被浪费是个耻辱。}
{122}{}{我们将会让你继续留在预备役。怎么样？}
{123}{}{我只是开个玩笑。}
{124}{}{应该考虑成为一名骑士。}
{125}{}{考虑考虑。}
{126}{}{谢谢你托马斯兄弟。}
{127}{}{我希望你仔细学习安东尼兄弟是怎么小幅度动作进行进攻的。}
{128}{}{他还知道怎么利用我的身材庞大和体重来进攻。}
{129}{}{搏斗技巧有好的一面和坏的一面。}
{130}{}{我们将会学习一些不同的流派，来更好的了解它们的力道和不足之处。}
{131}{}{好。让我看看你学的如何。}
{132}{}{非常好。你坚持的事件比我料想的还长。}
{133}{}{回到你那一排里去。}
{134}{}{好的，我希望你们这些小子可以觉察正在发生什么事。}
{135}{}{他是一个天生的战士。}
{136}{}{我们再做一些练习。}
{137}{}{集中注意力……}
{138}{}{然后盯紧目标出拳。}
{139}{}{假设你的目标是一些球从远处飞来。}
{140}{}{嗯，托马斯兄弟？}
{141}{}{是的，我的小伙子。}
{142}{}{难道我们也不能像这样去踢？}
{143}{}{嗯，过程。}
{144}{}{很好。我想我应该让你在这里。}
{145}{}{利用微笑让对手放松警惕。}
{146}{}{这不是生死之战。}
{147}{}{以后还有更多的机会。}
{200}{}{不错。}
{201}{}{做的漂亮。}
{202}{}{好，你正在学习。}
{203}{}{集中精神。}
{204}{}{盯着我。}
{205}{}{动作幅度不要太大。}
{206}{}{盯紧你的对手。}
{207}{}{注意脚下。}
{208}{}{压低你的重心。}
{209}{}{非常好！}
{210}{}{保持正确姿势！}
{211}{}{我记住了。}

{300}{}{You earn 500 experience from watching the combat training. You feel like you've learned a few things!}

#
# new for Fallout Fixt:
#

{400}{}{Thomas ignores you.}

