{100}{}{You see a desert bandit with a butcher's knife. Based on how the others look at him, he must have some position of importance or authority.}
{101}{}{你好，我是唐尼亚。看起来你刚刚从沙漠游荡而来。你是谁？}
{102}{}{我是}
{103}{}{。你好。}
{104}{}{能告诉我你们营地的情况吗？}
{105}{}{呃？}
{106}{}{作为一个强盗，我为了寻找新的补给探索大陆。有几个镇因为我们的出现变得“热闹”了。}
{107}{}{换句话说，你们从你拜访的人那偷东西？}
{108}{}{嘿！你真是太棒了。我确信伽尔会对你感到高兴的。}
{109}{}{你去过哪些地方？}
{110}{}{来吧，伽尔告诉我不要和陌生人说话。你至少应该告诉我你的名字。}
{111}{}{你说得对，我是}
{112}{}{。你会告诉我一些关于你们团伙的事吗？}
{113}{}{看你这傻样，我没有任何事要对你说。}
{114}{}{走开，笨蛋。}
{115}{}{我们从不偷窃。我们只是拿走别人多余的东西再把它们分配给我们饿肚子的人们。}
{116}{}{所以，从根本来讲，你们偷东西。}
{117}{}{那听起来真是个妙计。}
{118}{}{我去过许多废土上的地方。我们去过的最近的地方是沙荫镇和迦克镇。他们因为我们去他们的地方感到非常高兴。}
{119}{}{你们去沙荫镇？}
{120}{}{迦克镇在哪？}
{121}{}{你开始变得让我讨厌了。我想我应该停止这些无关紧要的谈话。}
{122}{}{我们是可汗，我们的头儿是伽尔。我们有理由说我们是废土上最可怕的团伙。我们拿走想要的东西，阻挠我们的人要付出代价！}
{123}{}{是的，我们定期去沙荫镇。这样也能给大家的生活带来些新鲜和刺激。}
{124}{}{迦克镇怎么样？}
{125}{}{这有什么问的？迦克镇就在南方，近得要命。走几英里，在死仙人掌那儿向右拐。你要是走丢了才见鬼呢！}
{126}{}{你也说过你们去沙荫镇。}
{127}{}{别烦我了！我要准备下一次掠夺了。}
#
# Fallout Fixt:
#
{200}{}{You see: Tolya, the Khans' resident chef and assistant scav.}
