{100}{}{走开！离我远点！}
{101}{}{你好，陌生人。你可别出去。外面只有死亡。}
{102}{}{你知道关于失踪商队的事情吗？}
{103}{}{你是谁？}
{104}{}{什么样的死亡？}
{105}{}{我需要些补给。把它们拿出来！}
{106}{}{我在找净水芯片。你能帮我吗？}
{107}{}{你是否知道一些关于死亡爪的事情？}
{108}{}{呜哇！哼哼！}
{109}{}{你到底要干什么？走开！}
{110}{}{呜哇！哼哼！}
{111}{}{很大！很大！有三个人那么大！爪子有我前臂那么长！撕裂！撕裂！}
{112}{}{恩。还有吗？}
{113}{}{伙计，冷静点。你现在很安全。}
{114}{}{伙计，听起来真是个丑畜生。}
{115}{}{你把它杀了吗？}
{116}{}{我是特仑特。纯水商队的护卫。我们的商队被……被一个怪物袭击了。非常大，非常敏捷。它吃了乔，被来福枪打中也好象没事一样！非常大！}
{117}{}{袭击你的是什么？}
{118}{}{好象是什么的变种。}
{119}{}{那好象是死亡爪！}
{120}{}{恩，现在你们知道该要求加薪水了吧。}
{121}{}{好，看来我不再需要他们了。}
{122}{}{净水芯片！我是护卫，不是技师！去哈勃城的纯水商队那里看看，他们也许知道。}
{123}{}{Deathclaw!}
{124}{}{你干什么？走开！}
{125}{}{我……我不知道。我很久没休息过了。现在又饿又渴又累。我要回家。}
{126}{}{}
{127}{}{大犄角，恶心的红皮肤，就象故事书里的恶魔，它三口就把乔吃了……}
{128}{}{危险了！都有危险了！大家都有危险了！怎么办？怎么办……}
{129}{}{你疯了吗？我的沙漠之鹰向它打了三弹夹的子弹。它晃都不晃一下。}
{130}{}{我才不管是变种，异形，还是地狱的恶魔，我这辈子可都不想再见到那种东西了。}
{131}{}{他妈的我只是个护卫。不能怪我！他们给很好的报酬。我跟他们没问题，也不会跟钱过不去。}
{132}{}{我能帮你什么？}
{133}{}{是死亡爪。我曾以为那只是故事，但现在……你绝对想象不到他们有多快多壮！我们刚发觉他们，转眼他们就从山脊冲下来了。我们都开始逃跑，好歹我逃出来了。}
{134}{}{特仑特，特仑特·巴瑞斯特。我住在哈勃城。最近工作变的不太好找，但我的枪法很好，所以我自己去做了纯水商队的护卫。报酬不错，风险也小……当时我大概就是这么想的。}
{135}{}{我也没头绪。是很古老的科技了吧？我想流浪汉也许拣到一个，赚了一票。但我也不知道去哪找。现在人们都不用这东西了，不是吗？}
{136}{}{它们很大，象大蜥蜴，但有很硬的皮肤。大爪子，大牙齿，还有大犄角，他们喜欢人肉。而且他们很敏捷，天呐，它们真的太快了。我很高兴他们没选追我，不然我也挂了。}
{137}{}{谢谢。也许那只是个误会，我没有多少钱，不过这些是你的了。}
{138}{}{谢谢。哦天呐，那真是……我没有多少钱，不过这些是你的了。}
{139}{}{谢谢。也许那只是个误会，我没有多少钱，不过……干！我肯定是弄丢了。这些是你的了。}
{140}{}{谢谢。哦天呐，那真是……我没有多少钱，不过……干！我肯定是弄丢了。这些是你的了。}
{141}{}{救命！}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{142}{}{死亡的气息，朋友。死亡的气息……}
{143}{}{死亡的气息，朋友。死亡的气息……}
