{100}{}{你看见一个大教堂的教徒。}
{101}{}{我不和异教的人说话，比如说你。}
{102}{}{你的报告，范·海根。}
{103}{}{主教对于你的进展很满意，但他的需求很大，给你的时间也很有限。}
{104}{}{主教应该知道原料已经不多了，如果没有原料我们就不能制造我们的战士。}
{105}{}{他意识到了你说的问题。他正在做这个，正像我们说的。}
{106}{}{告诉我他的计划，我们必须配合行动，“同一”事业才能取得成功。}
{107}{}{主教觉察到一个运转良好并且不为人知的避难所。那里有很多的原料，我们可以建立一支庞大的军队。按照软件预测，那里的原料数量足够我们取得胜利。}
{108}{}{太棒了。真是幸运。居民们都被污染了吗？}
{109}{}{哦，这才是最令人高兴的地方。如果那里居民中的样品是典型的，那他们真的是干净的，纯种的。}
{110}{}{哦，这真令人兴奋，我们要洗劫哪个避难所？}
{111}{}{13号避难所。我们马上就要占领它了，马上。}
{112}{}{你偷听到关于你避难所的完整谈话，得到了1000点经验值。}
