{100}{}{你看到法斯克兹，赏金亡命徒。}
{101}{}{你看到一个衣着邋遢的枪手。}
{102}{}{你想要什么？}
{103}{}{你是谁？}
{104}{}{嗯。}
{105}{}{我不为低智商的人工作。你现在离开。}
{106}{}{你没听说过我？我受打击了！我是法斯克兹·维拉诺瓦·赫尔南德斯·奥特加。我是个有名的雇佣兵，我的朋友。如果你有需要，我愿随时效劳。}
{107}{}{真的？你出价多少？}
{108}{}{再见，或许……祝你好运。呵。}
{109}{}{啊，开门见山，朋友。好极了，在镇子上活动我收你一星期500块。这服务不便宜，但我再说一遍，值得你花这个钱。}
{110}{}{太棒了，我雇你。这是500块。}
{111}{}{很抱歉打扰你，我想我不需要你的服务。}
{112}{}{对不起，我的朋友，可我不收白条。我要的是实实在在的现金。}
{113}{}{好极了。我是你的人了。我们走吧，我已经厌烦这里了。}
{114}{}{带路，我听你的指挥！}
{115}{}{让我们去找点东西喝！}
{116}{}{我们应该先去哪？}
{117}{}{只要你在迦克镇，我就是你的人。我不想离开这个镇子。}
{118}{}{你知道有人悬赏我的人头吗？不过，赏金太少了点。}
{119}{}{啊，我的朋友。很高兴再见到你。}
{120}{}{我想雇你一个星期。}
{121}{}{很高兴再见到你。}
{122}{}{嗯。}
{123}{}{哦，又看到你大概不是什么好事。祝你好运。}
{124}{}{当然是这样。我要价低，又能打。请出500块吧。}
{125}{}{拿去。}
{126}{}{你不该这么做的，自寻死路的朋友。}
