{100}{}{你看到个商队车夫。}
{101}{}{你好，如果你在我们其中之一的商队找工作的话，应该和商队主管谈，她在东面的屋里。}
{102}{}{抱歉，你要和商队主管说。}
{103}{}{好，你被批准了。我知道这不是个问题。自从达伦·海托开始藏在他的办公室里，她就忙的不可开交。海托真是个奇怪的男人。我们每隔五天离开。1日，5日，10日，15日，20日，25日。我们现在只去迦克镇和洛杉矶晒骨场。}
{104}{}{那么，价钱怎么算？}
{105}{}{嗯。}
{106}{}{报酬是200个瓶盖。不是很多，但是我们活多而且我们工作没有危险。和其他商队一样，这是单程报酬，当然，你不必来回都做。}
{107}{}{我们今天就出发，你有兴趣吗？}
{108}{}{我们的出发时间是}
{109}{}{Empty}
{110}{}{}
{111}{}{。你感兴趣吗？}
{112}{}{不管怎么样，我仍然给你工作，没关系的。你有兴趣吗？}
{113}{}{当然。}
{114}{}{不。}
{115}{}{可能。}
{116}{}{呀呀。}
{117}{}{咦？}
{118}{}{哦，好吧。没问题。如果你改变主意，告诉我。}
{119}{}{我希望你能决定。}
{120}{}{好吧，当你决定为我们干活时过来。1日、5日，之后类推。再见！}
{121}{}{抱歉，但是我不能雇佣你除非你能清楚地与队员沟通。}
{122}{}{当你好点的时候再来。}
{123}{}{额，你还好吧？我认为你需要吃些东西，但是不要去鲍勃那里。}
{124}{}{我说过，走开！}
{125}{}{我对你很失望？偷东西！你为什么那样做？}
{126}{}{我是来自外层空间的邪恶绿妈妈，我很坏！}
{127}{}{我不想做，但是我好饿，而且我有小孩要喂。}
{128}{}{我将用一个勺子挖出你的心！}
{129}{}{[Surrender]}
{130}{}{[Attack]}
{131}{}{我刚才想帮你的，但是有的人就是不识抬举。抱歉这样说，但是我们必须用暴力方法解决这事。}
{132}{}{可以理解，但不能替你开脱，我必须让你离开。我们不雇那些无法自控的人。}
{133}{}{你真的认为那些废话能骗过我？警卫！}
{134}{}{抱歉，但是有时候班房生活可以治愈一个人。警卫！不要杀她。你会向我的警卫投降吗？}
{135}{}{我将在地狱见到你。}
{136}{}{是的，抱歉。}
{137}{}{什么？你想再干一仗？}
{138}{}{抱歉你必须马上离开或者我请警察强制带你走！}
{139}{}{警卫！警察！}
{140}{}{我认为你该离开。}
{141}{}{抱歉，我不雇佣你。}
{142}{}{请吧。你在给我制造麻烦。}
{143}{}{请离开。}
{144}{}{你这个人很有意思，但不是我需要的类型。}
{145}{}{太棒了！报酬是200个瓶盖。你喜欢那条路线？}
{146}{}{好极了。请在这一天来：}
{147}{}{1日}
{148}{}{5日}
{149}{}{10日}
{150}{}{15日}
{151}{}{20日}
{152}{}{25日}
{153}{}{。你那时候就可以出发了。通常我们会付200个瓶盖。}
{154}{}{好吧。}
{155}{}{抱歉，不能等。}
{156}{}{这真是一个悲剧。我们损失了整个商队，但是你一个人生还了？那不该发生，我不知道那儿发生了什么，但是我们不会再雇你了。抱歉。}
{157}{}{迦克镇}
{158}{}{L.A. Boneyard}
{159}{}{嗯，不是现在，或许是其他时间。}
{160}{}{太好了，我这就召集其他人。}
{161}{}{很好。}
{162}{}{出发吧。好运！}
{163}{}{尽量避免任何麻烦，不要好奇心太重。}
{164}{}{小心，我不喜欢晒骨场，它令人毛骨悚然。}
{165}{}{很好。那些黑色的过道真奇怪，但是很好走。}
{166}{}{这里黑帮挺多的，我们和人说话要小心。}
{167}{}{太棒了。迦克镇是个好地方。}
{168}{}{哦，向那个叫什么基里……啥的人问好。我忘了他的名字，但是他是一个相当好的人。我想知道他现在怎么样。}
{169}{}{有趣的地方。我听说这里有个邪恶的医生喜欢摆弄死尸什么的。}
{170}{}{上次你究竟为什么离开了商队？虽然没出什么漏子，但是万一出事呢！}
{171}{}{可以再给我一次机会？}
{172}{}{没事。}
{173}{}{我没啥可说的！}
{174}{}{咦唔药俺？}
{175}{}{唔。}
{176}{}{抱歉，你又失败了。你没有责任感，不适合干这行。}
{177}{}{为什么我应该？}
{178}{}{你不应该。}
{179}{}{如果你不让我干，我在你的头上开个洞。}
{180}{}{我有比这个狗屁商队护卫更好的活去做。}
{181}{}{又没人说我不能中途走。反正也没出事嘛。}
{182}{}{我知道你嗑药了。好吧，你爱怎么过就怎么过吧。}
{183}{}{你这么说就没意思了。}
{184}{}{我很惊讶，你以前从未在商队里干过。这次亏得没出事，所以我打算再给你一个机会。}
{185}{}{这活你干的不错，你想要再保另外一镖吗？}
{186}{}{好。}
{187}{}{不。}
{188}{}{也许。}
{189}{}{呀！}
{190}{}{唔。}
{191}{}{准备好走了吗？我们今天离开。}
{192}{}{是。}
{193}{}{不！}
{194}{}{啊啊！}
{195}{}{或者我就让其他人去保，不要太在意。在你和商队一起离开之前，你没有一定要保镖的义务，明白？}
{196}{}{你来早了，下一次商队要到}
{197}{}{1日}
{198}{}{5日}
{199}{}{10日}
{200}{}{15日}
{201}{}{20日}
{202}{}{25日}
{203}{}{才能出发。如果你仍然喜欢这个工作就回来找我们。}
{204}{}{1月}
{205}{}{2月}
{206}{}{3月}
{207}{}{4月}
{208}{}{5月}
{209}{}{6月}
{210}{}{7月}
{211}{}{8月}
{212}{}{9月}
{213}{}{10月}
{214}{}{11月}
{215}{}{12月}

# invasion - WastelandGhost@RestorationMOD
{300}{}{Good, you got the okay. I knew it wouldn't be a problem. She's so swamped lately, ever since Daren Hightower started hiding in his office. Strange man. We leave just about every five days. That's the 1st, 5th, 10th, 15th, 20th, and the 25th. We currently go to Junktown only. There were rumors about mutants invasion in L.A. Boneyard, so we don't go there anymore.}
