{100}{}{你看到一个负责分发水的警卫。}
{101}{}{你好，}
{102}{}{。}
{103}{}{你好，近来如何？}
{104}{}{嘎！}
{105}{}{好吧！也送你一句问候……很遗憾你从未学过怎么说话，我们本可能会成为好朋友的。}
{106}{}{哦呜。}
{107}{}{我感觉不太好。有人用根大管子打爆了我的头。我去治疗过，但我的头还是很痛。希望有人能逮到那个打我的混蛋。}
{108}{}{他们为什么那样做？}
{109}{}{咕。}
{110}{}{我是在深夜执勤的时候在这被袭击的。一般我都八点左右回家，但自从发生偷水事件后，我就会在这里多值会儿班，那时候我正在查库房。突然我就什么都不知道了，我醒来的时候在医疗室里，头上有个大包。这事情越来越疯狂，这样下去很快大概就会为水而出人命案了，我不知道我们该怎么办。}
{111}{}{我看我能做些什么。}
{112}{}{我很遗憾，我希望你很快就能好起来。}
{113}{}{这是你的水。}
{114}{}{这是你今天的定额。}
{115}{}{嘿！你在干什么！？}
{116}{}{请不要拿走太多补给，我们需要这些。}
{117}{}{你在图书馆计算机系统里更新了你的报告。现在你应该去见所长汇报一下你的进度。}
# TRANSLATION NOTE
# The player-character's name is inserted by code between lines 118 and 119.
{118}{}{日安，}
{119}{}{。}
{120}{}{你好，最近怎么样？}
{121}{}{你在这儿干什么？}
{122}{}{还好，只是每个人都很紧张，当然，到目前为止还没发生什么大事。不过我仍然希望我们很快就能找到那个新的净水芯片。}
{123}{}{我在早晨按定额分配水。尽管我认为我们短时期内还不会有什么麻烦，但我还是要确保按定额分发水。}
{124}{}{嗯，继续工作吧，祝你好运。}
{125}{}{你也是，我希望你很快就能找到净水芯片，那样这里的生活就能恢复正常了。}
{126}{}{你的工作更重要，如果你需要补给就拿吧，不过别拿太多，我们剩下的不多了。}
{127}{}{我能得到一些补给吗？}


{1000}{}{Ration}
{1001}{}{Rations}
{1002}{}{Supplies}
{1003}{}{Water}


{1100}{}{我早晨按照定额分配水。你不需要它们，现在你要去外面。}
{1101}{}{我早晨按照定额分配水。你不需要它们，现在你要去外面。}
{1102}{}{我们只有一点剩下的补给。如果你的任务需要就去拿一些吧，但是不要拿太多。}
{1103}{}{我早晨按照定额分配水。你不需要它们，现在你要去外面。}
