{100}{}{你看到纯水商队的警卫。}
{101}{}{停止前进！非商队成员不准接近水塔或者水泵！}
{102}{}{你不许回来，马上离开！}
{103}{}{这里区域禁止进入！离水泵远点。}
{104}{}{如果不想让你那身实心猪皮变成网面，赶紧他妈的给我滚！}
{105}{}{最后一次警告！离开！}
{106}{}{你最好离开。}
{107}{}{你有几秒时间或者离开或者吃枪子！}
{108}{}{你是聋子？马上离开！}
{109}{}{很好。}
{110}{}{你真是敬酒不吃吃罚酒。}
{111}{}{你没听见么？}
{112}{}{给他点厉害尝尝。}
{113}{}{给她点厉害尝尝。}
{114}{}{非商队成员不准接近水塔或者水泵。}
{115}{}{你应该离开。}
{116}{}{我们不信任任何人，对你也不例外。}
{117}{}{你最好离水泵远点。}
{118}{}{如果你有需要，就去商队大厅吧。}
{119}{}{我们会开枪，不要有非分之想。}
{120}{}{我们不会让任何人威胁哈勃城的救命水。}
