{100}{}{你看到一个睡眼惺松的避难所居民。}
{101}{}{你看到一个鬼鬼祟祟的避难所居民。}
{102}{}{他老是躲开你如炬的目光。}
{103}{}{你认出了偷水的贼！}
{104}{}{杀掉了威胁避难所储备水的小偷得到了500经验值。}
{105}{}{谢谢你解决这桩案子，这可真是稳定人心啊。}
{106}{}{成功逮到了偷水贼你得到了1000经验值。}
{107}{}{你好，}
{108}{}{。}
{109}{}{你好，这个时间你在做什么？}
{110}{}{咦！}
{111}{}{我替避难所感到担忧，还做了个恶梦。睡不着，所以出来散会儿步放松下。}
{112}{}{好的。}
{113}{}{你见到其他人在这周围吗？}
{114}{}{抱歉，我在找一个偷水的贼，我要搜你的身。}
{115}{}{耶。有个家伙鬼鬼祟祟的接近水定额配给的房间。他吓倒了我，希望他没看到我。}
{116}{}{他长什么样？}
{117}{}{抱歉，我仍然要搜你的身。}
{118}{}{因为我在跑，我没有看清他。}
{119}{}{好吧，不管怎样，谢谢。}
{120}{}{当然，我没有任何东西好藏。}
{121}{}{【搜他身】}
{122}{}{不要碰我，我没有任何东西！走开！}
{123}{}{好吧，抱歉。}
{124}{}{你情愿去吃枪子？}
{125}{}{我偷了水，抱歉，请不要伤害我。}
{126}{}{我带你去见长官。}
{127}{}{好吧，好吧，我没有任何东西好藏的。你自己找吧。}
{128}{}{好吧，晚安}
{129}{}{晚安。}
{130}{}{你没找到东西。}
