# These are various People combined into one file.
# They are split into the groups of what they are.
################
# Flat monotonic people. Nothing interesting. they are apathic.
{106}{}{Tu vois une femme.}
{107}{}{Tu vois un homme.}
################
# The drunk has slurred speech. he's been hitting the booze a bit too hard
# and is having problems standing and remembering his name
{100}{}{Voici un ivrogne.}
{110}{}{Occupe-toi de tes oignons.}
{111}{}{C'est toi que je préfère.}
# best friend (slurred)
{112}{}{Pourquoi que... (hic) où suis-je ?}
{113}{}{Qui t'es toi ?}
{114}{}{On s'connaît ?}
{115}{}{J'suis pas dans mon assiette.}
{116}{}{C'est ma tournée, j'veux dire la tienne.}
{117}{}{T'as vu ? T'as un sosie !}
{118}{}{Du calme !}
# laddy is male
{119}{}{Du calme, ma puce !}
#################
# Customer and gamble are both genders. Consider male for translation. They are agitated, yet happy to
# be spending all their money. Consider the people in Las Vegas gambling away their money.
{101}{}{Voici un client.}
{104}{}{Voici un joueur.}
{120}{}{Casse-toi, minable !}
# == "Get out of here loser"
{121}{}{Ici, c'est pas pour les péquenauds.}
# == "you are dropping the class of this place"
{122}{}{Tire-toi, tu me fous la poisse !}
# == "get away. you will bring me bad luck"
{123}{}{Me déconcentre pas.}
{124}{}{Je vais envoyer promener ce foutu jeu !}
{125}{}{T'es bon à ça ?}
{126}{}{T'as vu ça ? C'est pas possible !}
# referring to dice roll
{127}{}{Pour moi, c'est des escrocs.}
# they is referring to the owners of the Maltese Falcon, the drinking/gambling establishment
# They is Male
{128}{}{Cette fois, je la sens bien.}
{129}{}{Ça c'est sûr.}
# referring to a bet.
{130}{}{Quoi ? Comment ça, j'ai perdu ?}
{131}{}{Cette table me porte la poisse !}
# == "this table is cursed/unlucky"
{132}{}{J'ai pas l'temps.}
{133}{}{Tu vois pas que je joue ?}
{134}{}{Parie ou tire-toi.}
#################
# This is a sleazy prostitute who will have sex with anyone who will give
# her $20. She will be talking a sexy, but lewd voice.
{102}{}{Voici une très jolie femme.}
{105}{}{Voici une femme, elle semble occupée.}
{135}{}{Laisse-nous tranquille ou j'appelle les gardes.}
{136}{}{Fais attention, je connais très bien le député Fry.}
{137}{}{Tu permets ?}
{138}{}{C'est pas un peep show ici !}
# == "I don't allow people to watch me having sex with someone else."
{139}{}{C'est chacun son tour.}
# == "I don't have sex with more than one person."
{140}{}{J'ai eu ma dose pour aujourd'hui.}
# referring to having another round of sex.
{141}{}{Non mais tu rêves. Tire-toi !}
{142}{}{Dehors !}
{143}{}{Faut pas s'gêner !}
{144}{}{Un peu de tenue !}
{145}{}{Je vais appeler les flics !}
{146}{}{Et puis quoi encore !}
{147}{}{Dehors !}
{148}{}{Du balai !}
{149}{}{Qu'est-ce tu regardes comme ça ?}
{150}{}{Tu permets ?}
#####################
# This is a customer for the Hooker. Gender is male. He is aburpt and is really not
# interested in the player, only having sex with the prostitute
{109}{}{Voici un mercenaire.}
{151}{}{Sors d'ici !}
{152}{}{Dehors !}
{153}{}{T'es du voyage ?}
# == "are you part of the group of three/threesome/orgy"
{154}{}{Tire-toi, grosse larve vicieuse !}
# == "get out of here, perverse person"
{155}{}{C'est quoi le problème ?}
{156}{}{Tire-toi avant que j'me fâche.}
# "Beat it" == "get out of here"
{157}{}{Paie-t-en une.}
# ==  "get your own hooker"
{158}{}{Elle est pour moi.}
# "She" is referring to the hooker.
######################
# Gambler is Male. The gambler has lost a lot of money and is really upset about
# having done so.
{108}{}{Voici un joueur furieux.}
{159}{}{Putain !}
{160}{}{Tu triches ?}
# referring to the player
{161}{}{J'aurais dû gagner.}
# someone else won a bet, this person thinks they should have won instead
{162}{}{A côté !}
# nearly got his number on the roulette wheel
{163}{}{Raté.}
# pulled up a 19 to the dealers 20 in blackjack
{164}{}{C'est quoi la règle, déjà ?}
# in referrence to a gambling game
{165}{}{Avant, j'étais imbattable.}
# in referrence to a gambling game
{166}{}{Merci de rien.}
{167}{}{J'y crois pas !}
{168}{}{J'ai fait exprès.}
# he meant to lose.
######################
# This is the dealer/roulette shooter for the casino. Monotonic voice and trying to
# pretend to be happy about being here.
{103}{}{Voici un homme à l'air bizarre.}
{169}{}{Faites vos jeux.}
{170}{}{Les mains loin de la table, monsieur.}
# in referrence to taking money from the table while the bet is going on
{171}{}{Gagnant !}
{172}{}{Pas de chance messieurs dames, peut-être la prochaine fois.}
# maybe next time someone can win
{173}{}{Un autre gagnant !}
{174}{}{Les mains loin de la table !}
# don't take the dice off the table while someone is rolling them
{175}{}{A vous de jouer, monsieur.}
# your turn to bet
{176}{}{Ce pari n'est pas valable.}
{177}{}{C'est ça.}
{178}{}{Personne d'autre ?}
