{100}{}{Merci, salut.}
{101}{}{D'accord, merci.}
{102}{}{Hum. Salut.}
{103}{}{A plus.}
{104}{}{Merci.}
{105}{}{D'accord, salut.}
{106}{}{[Suite]}
{107}{}{Zzzzz}
{108}{}{[Terminé]}
{109}{}{Je peux pas me servir de ça.}
