{100}{}{Voici un ordinateur dégageant une pâle lueur.}

{101}{}{Un faible courant électrique arrive jusqu'au système. Le courant semble avoir été dévié pour alimenter les rares systèmes encore à demi en fonctionnement.}

# low IQ
{102}{}{Tu remarques quelque chose d'inhabituel.}
{103}{}{L'ordinateur émet un bourdonnement étrange.}

{104}{}{Un moniteur relié à l'ordinateur affiche sans interruption le message "Erreur système".}
{105}{}{L'ordinateur semble avoir été attaqué par un goule.}
{106}{}{Sur l'ordinateur, des voyants clignotent, mais tu penses qu'il s'agit d'un hasard.}

# low IQ
{107}{}{En touchant l'ordinateur, tu reçois une légère décharge.}
{108}{}{Après examen, tu remarques que l'ordinateur a hébergé des rats.}
{109}{}{Des chiffres aléatoires s'affichent sur un écran relié au système.}
{110}{}{L'ordinateur émet le pire bruit que tu aies jamais entendu. Le message "Incompatible" s'affiche sur le moniteur.}
{111}{}{La moitié de l'ordinateur est noire, brûlée par un vieil incendie.}

{112}{}{}
{113}{}{}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{}
{122}{}{}
{123}{}{}

{124}{}{}
{125}{}{}
{126}{}{}
{127}{}{}

{130}{}{}
{131}{}{}
{132}{}{}

{133}{}{}

{150}{}{}
