{100}{}{Ты видишь члена Последователей.}
{101}{}{Ты видишь Брата Алана из Последователей.}
{102}{}{Эй, приветствую тебя, человек. Что произошло?}
{103}{}{Что я могу сделать для тебя?}
{104}{}{Привет.}
{105}{}{Эй, приветствую тебя, мисс. Что произошло?}
{106}{}{Ооогх!}
{107}{}{Привет.}
{108}{}{Я встречал немногих Последователей. Что конкретно ты делаешь?}
{109}{}{Я пытаюсь найти шпиона в ваших рядах, но мне не везет. Могу я задать тебе 
несколько вопросов?}
{110}{}{Ёорошо, я в основном изучаю философию и материю. Я считаю, если мы собираемся
 прийти к миру, тогда нам нужна хорошая основа для этого, не правда ли? }
{111}{}{Конечно, это имеет смысл.}
{112}{}{Единственная философия, которая тебе нужна - это большое ружье.}
{113}{}{Гмм. Ладно. Ёорошо, я думаю, я поговорю с тобой попозже.}
{114}{}{Эй, я не думаю, что смогу помочь тебе.}
{115}{}{Эй, это точно, что этот вид отношений является причиной всех проблем.
 Просто остынь, ладно?}
{116}{}{Угу. Я просто обманул.}
{117}{}{Лемми даст тебе немного покоя. . . вечного покоя.}
{118}{}{Угу, уверен, продолжай.}
{119}{}{Что еще ты хочешь узнать?}
{120}{}{Ты когда-нибудь сталкивался с Детьми Собора?}
{121}{}{Ты когда-нибудь уходил из библиотеки?}
{122}{}{Ты знаешь о ком-нибудь, кто регулярно выходит наружу?}
{123}{}{Без понятия. Я слыщал, что они все чудаки. Я бы не хотел поговорить с ними.}
{124}{}{Да нет, я тоже. Я просто люблю читать. И так или иначе, только разведчики
 смогут действительно выйти куда-нибудь.}
{125}{}{Точно, только разведчики и охранники. Охранники ходят и немного наблюдают 
время от времени. Я хотел быть охранником, но . . . ладно, я получил пинка
 в рукопашной схватке так, что я не мог идти. Да, я думаю, разведчики, время от времени
 идут намного дальше по по пути к Собору.}
{126}{}{Больше нет вопросов, спасибо.}
{127}{}{[Дальше]}
