{100}{}{Калнор, охранник Джанктауна.}
{101}{}{Ты бы лучше сам посмотрел здесь.}
{102}{}{Это не самый лучший город для поиска проблем на свою голову.}
{103}{}{Ведите себя прилично и неприятности минуют вас.}
{104}{}{Ты в порядке.}
{105}{}{Продолжай хорошую работу.}
{106}{}{Приятный день, не так ли?}
{107}{}{Это - Джанктаун. Неплохое место для жилья, пока ты остаешься на нашей 
хорошей стороне.}
{108}{}{Остерегайся Гизмо и его друзей!}
{109}{}{Мне нравится мой начальник.}
{110}{}{Тебе бы лучше положить это на место. Джанктаун - это миролюбивое место, друг
 и мы хотим сохранить это так.}
{111}{}{Что положить на место?}
{112}{}{Не говори мне, что делать, бедняга.}
{113}{}{Звучит честно. Кстати, что это за местный закон, касающийся оружия?}
{114}{}{О...}
{115}{}{Твое оружие, идиот. Киллиан не хочет отбирать твое оружие, но было бы лучше, 
если ты держал его в кобуре.}
{116}{}{О, извини.}
{117}{}{Никоим образом! Я не убираю свой револьвер ни перед кем!}
{118}{}{Ты бы вел себя получше, так как это закон, и я обеспечиваю его выполнение.
 Убери свое оружие. Не доставай его, кроме случаев самозащиты и у тебя не будет 
проблем с нами, охранниками. Нарушишь закон и мы вернем тебя в необузданную
 пустынную землю - живым или мертвым.}
{119}{}{Уверен, все будет хорошо.}
{120}{}{Подавись своими законами!}
{121}{}{Ёорошо, Но тебе лучше быть поосторожней.}
{122}{}{Ёорошо сказано. Нельзя доставать оружие, кроме случаев самозащиты. Если ты 
затеваешь драку - это твоя вина. По другому, это твое право - ходить везде с 
оружием. Только не вытаскивай нож или пистолет без причины. Счастливо.}
{123}{}{Эй ты, убери оружие! И не волнуйся, если твоя мамочка оплачет тебя горькими
 слезами.}
{124}{}{Эй! Ты! Что это ты тут крадешься? }
{125}{}{Ничего.}
{126}{}{Я не крадусь. Я просто люблю гулять осторожно.}
{127}{}{А-а-а.}
{128}{}{Как бы ты не гулял, не делай этого в этом городе.}
{129}{}{Эй! Сомнительным личностям нельзя в город! Убирайся отсюда, пока мы не выкинули тебя.}
{130}{}{Ёорошо, хорошо. Только не делай ничего из ряда вон выходящего.}
{131}{}{Спасибо, пока.}
{132}{}{Конечно. Я выкину к черту осторожность, сэр.}
{133}{}{Конечно. Я выкину к черту осторожность, мэм.}
{134}{}{Ты бы лучше последил за собой, поскольку мы будем наблюдать за тобой.}
{135}{}{Добро пожаловать в Джанктаун. Что я могу сделать для тебя?}
{136}{}{Ничего, спасибо.}
{137}{}{Что ты здесь делаешь? Что это за место?}
{138}{}{Где я могу достать немного запасов?}
{139}{}{Вах-Вах!!}
{140}{}{Ты хочешь встретиться с Киллианом. Он на севере. Это сюда, наверх.}
{141}{}{На что это похоже? Я охранник, и я держу ухо востро за такими незнакомцами,
 как ты. А это место называется Джанктаун. Эй, не смейся. Мне самому нравится
 это название. В основном, мы торгуем.
 Иногда мы торгуем с этими заносчивыми ублюдками из Ёаба. Эй, а ты
 ведь не из Ёаба, да? }
{142}{}{Что? Ёаб? Точно, так и есть!}
{143}{}{Я? Нет, я не из Ёаба.}
{144}{}{Тогда ты должен больше знать о правилах. Счастливо. И извини за слова об
 ублюдках, ладно?}
{145}{}{Эй, без проблем. Пока.}
{146}{}{Это будет причиной моей некоей душевной травмы. Позже. }
{147}{}{Гм. Ладно. Это не то место, чтобы задавать вопросы. Счастливо и не
 волнуйся.}
{148}{}{О, черт. Тебе нужно сходить в магазин Киллиана. Это недалеко, к
 северу отсюда. Там ты найдешь лучшие припасы в этом городе.}
{149}{}{Спасибо. Пока.}
{150}{}{Ты хочешь показать мне, где ты держишь "свои" запасы?}
{152}{}{О, нет. Извиняюсь, леди.}
{153}{}{Счастливо.}
{154}{}{Держись подальше от неприятностей.}
{155}{}{Парень, я надеюсь скоро получить здесь пополнение. Похоже, я навсегда 
остануюсь на службе охранника.}
{156}{}{Извини, ворота закрыты. Приходи утром.}
{157}{}{Эй, мне надо пройти!}
{158}{}{Без проблем. Увидимся утром.}
{159}{}{Извиняюсь за беспокойство, сэр, но я бы хотел пройти в город. Увидите, я не 
причиню вреда.}
{160}{}{Ёа-ха!}
{161}{}{Возвращайся. . .  днем. . .}
{162}{}{Извини, правила есть правила. Чужих не пускают ночью.}
{163}{}{Ёорошо, я бы не сделал этого, но ты кажешься достаточно приятным человеком.
 Входи, но не создавай беспокойства.}
{164}{}{Эй! Да это же ты! Давай, входи }
{165}{}{. Увидимся снова!}
{166}{}{Эй, тебе лучше повернуться и идти прочь отсюда.}
{167}{}{Давай, входи.}
