{100}{}{Вы видите охранника.}
{101}{}{Я работаю на Торговца.}
{102}{}{Получаешь гроши?}
{103}{}{Если ты сломаешь, ты купишь это.}
{104}{}{Магазинные воры будут убиты.}
{105}{}{Ты собираешься что-нибудь покупать? Наверное, в этом столетии?}
{106}{}{Нельзя сражаться с Рад Скорпионами без этой дряни.}
{107}{}{Я работаю на Торговца.}
