{100}{}{Взрыв разрушил туннель мощной ударной волной!}
{101}{}{Ты кидаешь взрывчатые вещества и убегаешь. }
{102}{}{Взрыв просто сделал дыру пошире. Будет невозможно, ее закрыть.}
{103}{}{Ты зарабатываешь очки за успешное использование взрывчатых веществ.}
