{100}{}{Ты видишь Боба.}
{101}{}{Я не позволю тебе ограбить меня дочиста!}
{102}{}{Эй, я не хочу неприятностей.}
{103}{}{Дайка мне игуану на пруте.}
{104}{}{Что ты можешь рассказать мне о водном фильтре?}
{105}{}{Что ты можешь рассказать мне о Деккере?}
{106}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некоторых его секретных ингридиентах.}
{107}{}{Ты что-нибудь знаешь о пропавших караванах?}
{108}{}{Что, беспокоить меня? Что дает тебе такое впечатление?}
{109}{}{Я голоден! Грррр!}
{110}{}{Привет. Добро пожаловать в "Шашлык из Игуаны от Боба", семейную закусочную. Я возьму у вас заказ?}
{111}{}{Дай ка мне игуану на прутьях.}
{112}{}{Что ты можешь рассказать мне о водном фильтре?}
{113}{}{Что ты можешь рассказать мне о Деккере?}
{114}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некоторых его секретных компонентах.}
{115}{}{Ты знаешь что-нибудь о пропавших караванах?}
{116}{}{Что-нибудь интересное происходить в Ёабе?}
{117}{}{Я голоден! Грррр!}
{118}{}{Извини, мы сыты по горло игуаной.}
{119}{}{У нас только целые игуаны на прутьях. Каждая по двадцать баксов.}
{120}{}{У нас только отличная изысканная нарезка. Впрочем, это отлично по вкусу. Каждая по восемь баксов.}
{121}{}{Уверен. Мы возьмем целую игуану на прутьях за двадцать баксов, и отборную нарезку за восемь баксов.}
{122}{}{Я возьму целую игуану.}
{123}{}{Я возьму вашу отличную нарезку.}
{124}{}{Ты знаешь, я слышал, что ваша отличная нарезка похожа по вкусу на курицу.}
{125}{}{Только не детскую порцию! Я хочу всю игуану! Уф!}
{126}{}{Гмм, пахнет вкусно! Отличная нарезка сделает счастливым мой животик!}
{127}{}{Мы не подаем это здесь. Что-нибудь еще?}
{128}{}{Дай ка мне целую игуану на прутьях.}
{129}{}{Что ты можешь рассказать мне о Деккере?}
{130}{}{Я думаю, нам нужно поговорить о Деккере и некоторых его секретных компонентах.}
{131}{}{Ты знаешь что-нибудь о пропавших фургонах?}
{132}{}{Что-нибудь интересное происходит в Ёабе?}
{133}{}{Я голоден! Гррр!}
{134}{}{Мистер Деккер - известный бизнесмен в не менее известном бизнесе.}
{135}{}{Мне нужны сведения о Доке Морбиде.}
{136}{}{Дай ка мне игуану на прутьях.}
{137}{}{Ничего.}
{138}{}{Он был подлым сукиным сыном и тот, кто не рад, что он умер - проклятый лгун. Могу я сделать тебе заказ?}
{139}{}{Дай ка мне игуану на прутьях.}
{140}{}{Расскажи мне немного о торговцах водою.}
{141}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некоторых его секретных ингридиентах.}
{142}{}{Ты что-нибудь знаешь о пропавших караванах?}
{143}{}{Что-нибудь интересное происходит в Ёабе?}
{144}{}{Я голоден! Гррр!}
{145}{}{Я не знаю, о чем ты говоришь. Ладно. Я заплачу тебе сто баксов, если ты заткнешь свой рот. Забирай это и убирайся.}
{146}{}{Мне нужно двести.}
{147}{}{Я дам тебе сто.}
{148}{}{Я иду в полицию.}
{149}{}{Ёватит торговаться. Сейчас.}
{150}{}{Ужасный бизнес. Эти бедные люди. О, эти бедные люди. Теряющие свои жизни таким страшным образом. Есть что-нибудь, чем я могу тебе помочь? Например, покормить тебя?}
{151}{}{Дай ка мне игуану на прутьях.}
{152}{}{Что ты можешь рассказать мнее о водном фильтре?}
{153}{}{Что ты можешь рассказать мне о Деккере?}
{154}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некоторых его секретных ингридиентах.}
{155}{}{Что-нибудь интересное происходит в Ёабе?}
{156}{}{Ничего. Извини, что завел об этом разговор. Я просто слышал истории. А сейчас есть что-нибудь, чем я могу тебе помочь?}
{157}{}{Дай ка мне игуану на прутьях.}
{158}{}{Что ты мне можешь рассказать о водном фильтре?}
{159}{}{Что ты мне можещь рассказать о Деккере?}
{160}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некоторых его секретных ингридиентах.}
{161}{}{Ты знаешь что-нибудь о пропавших караванах?}
{162}{}{Что-нибудь интересное происходит в Ёабе?}
{163}{}{Кто-то убил Деккера. Мы в трауре, по крайней мере, пока Ёаб не истощит свои запасы спиртного.}
{164}{}{Кто-то застрелил шерифа Грина. Впрочем, не знаю о заместителе.}
{165}{}{Дарен Ёайтауер был убит. И все эти деньги не смогли бы спасти его. Иронично, не правда?}
{166}{}{Похоже начались крупные разборки, потому что недавно, как я слышал  одному моему знакомому очень сильно досталось.}
{167}{}{Кто-то украл ожерелье с Ёайтауэра. Парень, они всегда совершали большие ошибки. Они уже точно мертвы.}
{168}{}{Кто-то убил Джейн у Собора. Я слышал, она была настоящей сукой!}
{169}{}{Ладно, единственная новость - это то, что Дети Церкви захватили Госпиталь, Там была недавно отличная заварушка. Ты полагаешь, это странная компания?}
{170}{}{Что-нибудь еще?}
{171}{}{Дай ка мне игуану на прутьях.}
{172}{}{Что ты мне можешь рассказать о водном фильтре?}
{173}{}{Что ты мне можешь рассказать о Деккере?}
{174}{}{Я думаю, нам нужно поговорить О Доке Морбиде и некоторых его секретных ингридиентах.}
{175}{}{Ты знаешь что-нибудь о пропавших караванах?}
{176}{}{Извини, ты не можешь позволить себе этого.}
{177}{}{Одна целая игуана готова! Что-нибудь еще?}
{178}{}{Дай ка мне игуану на прутьях.}
{179}{}{Что ты можешь мне рассказать о водном фильтре?}
{180}{}{Что ты можешь мне рассказать о Деккере?}
{181}{}{Ты что-нибудь знаешь о пропавших фургонах?}
{182}{}{Что-нибудь интересное происходит в Ёабе?}
{183}{}{Я хочу еще игуану!}
{184}{}{Я объелся! Уфффф!}
{185}{}{Извини, тебе это не по карману.}
{186}{}{Одна отличная отборная нарезка из игуаны готова! Что-нибудь еше?}
{187}{}{Дай ка мне еще игуану на прутьях.}
{188}{}{Что ты можешь мне рассказать о водном фильтре?}
{189}{}{Что ты можешь мне рассказать о Деккере?}
{190}{}{Ты знаешь что-нибудь о пропавших караванах?}
{191}{}{Что-нибудь интересное происходит в Ёабе?}
{192}{}{Я хочу еще игуану!}
{193}{}{Я объелся! Уфффф!}
{194}{}{Спасибо. Приходи еще.}
{195}{}{Ты должно быть недавно в городе, если ты спрашиваешь меня о Торговцах Водой. Вода - это жизнь. И ты не станешь сильнее, чем жизнь и смерть.}
{196}{}{Дай ка мне игуану на прутьях.}
{197}{}{Я думаю, нам нужно поговорить о Доке Морбиде и некотрых его секретных ингридиентах.}
{198}{}{Ты знаешь что-нибудь о пропавших караванах?}
{199}{}{Что-нибудь интересное происходит в Ёабе?}
{200}{}{Я голоден! Грррр!}
{201}{}{Ты жадный сукин сын!}
{202}{}{Ты жадная блудница!}
{203}{}{Ёорошо, ты победил. Это твои деньги. Возьми их и не возвращайся!}
{204}{}{Если бы я был тобой, я бы переменил решение. Сейчас проваливай и лучше не возвращайся!}
{205}{}{Может быть я взял немного сомнительных порций. Но это не значит, что я совершил преступление. Похоже, хлам Морбида уже мертв, не так ли?}
{206}{}{Точно, так и есть, Боб. И я уверен, что полиция согласится.}
{207}{}{Каннибализм - преступление против человечества, Боб. Я собираюсь посмотреть, как ты заплатишь за это.}
{208}{}{Может быть и так. Может и нет. Меня это не волнует. Это амморально. Прекращай это!}
{209}{}{Ни за что! }
{210}{}{Я не собираюсь разорятся из-за твоих дурацких придирок! Жри это!}
