{100}{}{Полная чепуха! Убить!}
{101}{}{Застрели эту бестию, пока она не съела его!}
{102}{}{Ружья!}
{103}{}{Убери его отсюда!}
{104}{}{Не входи во внутрь круга, болван.}
{105}{}{Эй, куда, ты полагаешь, ты собрался?}
{106}{}{Скажи Густоферу, если ты хочешь спать.}
{107}{}{Состязания по боксу в 2:00 через каждые три дня.}
