{100}{}{Вы видите клерка из Караванов Кримсона.}
{101}{}{Вы видите клерка Торговцев Водой.}
{102}{}{Вы видите клерка Торговой Компании Фарго.}
{103}{}{Привет. Ты ищешь работу?}
{104}{}{Да.}
{105}{}{Нет.}
{106}{}{Отлично. У нас есть место для еще одного охранника. Интересует?}
{107}{}{Ёорошо. Если тебе нужна работа, стой и мы тебя тебя подберем.}
{108}{}{Жаль это слышать. Пока.}
{109}{}{Отлично. Наши караваны отправляются в: Бониярд, Джанктаун, Некрополис и Братство Стали. Куда хочешь
 отправиться?}
{110}{}{Отлично. Наши караваны отправляются в: Бониярд, Джанктаун и Братство Стали. Куда хочешь
 отправиться?}
{111}{}{Отлично. Наши караваны отправляются в: Бониярд и Джанктаун. Куда хочешь отправиться?}
{112}{}{Бониярд.}
{113}{}{Джанктаун.}
{114}{}{Братство Стали.}
{115}{}{Некрополис.}
{116}{}{Никуда.}
{117}{}{Отлично, отправляемся.}
