{100}{}{Ты видишь Найткина раньше, чем он увидел тебя.}
{101}{}{Умри!}
{102}{}{Оставь меня или умри!}
{103}{}{Мне не нравится твой тон. Если Повелитель не получит мое сообщение, я позабочусь о том, чтобы твоя смерть была медленной и мучительной.}
{104}{}{Я просто хотел поздравить тебя с громадным горбом на твоей спине. Впрочем, твое дыхание могло бы сослужить службу . . .}
{105}{}{Не мог бы ты направить меня к начальнику?}
{106}{}{Парень, ты мог бы израсходовать напитки похуже, чем я!}
{107}{}{Я не ухожу!}
{108}{}{Ладно. Я ухожу.}
{109}{}{Это глупо - играть с Найткином. Проваливай отсюда!}
{110}{}{Я так не думаю.}
{111}{}{Я буду наслаждаться, наблюдая за твоей смертью.}
{112}{}{Ты не слушаешь? Это глупо - игнорировать Найткина.}
{113}{}{Я должен поговорить с тобой. Это крайне необходимо!}
{114}{}{Никто никогда не обвинял меня в мудрости!}
{115}{}{Я просто хочу поговорить с начальником!}
{116}{}{Ты решил быть упорным или как?}
{117}{}{Извини! Счастливо.}
{118}{}{Ты хочешь увидеть глупца? Глупо дерзить мне, дырка от задницы!}
{119}{}{Иди наверх. Другие из моего семейства оценять важность твоего сообщения.}
{120}{}{Это последнее предупреждение для тебя!}
{121}{}{Это точно! Большая сделка . . .}
{122}{}{Мне ДЕЙСТВИТЕЛЬНО нужно поговорить со старшим парнем.}
{123}{}{Ёорошо! Ёорошо! Извини! Счастливо.}
{124}{}{Ты знаешь, в чем твоя ошибка? Ты даешь предупреждения. Я - нет. Умри!}
{125}{}{[готово]}
