{100}{}{Ты видишь гражданина города Шэйди Сэндс.}
{101}{}{Добро пожаловать в Шэйди Сэндс, чужестранец!}
{102}{}{А, спасибо.}
{103}{}{Что случилось с этим местом?}
{104}{}{Гммм!}
{105}{}{Мы - настояшая коммуна. Мы все работаем и делимся друг с другом.}
{106}{}{Как же вы здесь живете?}
{107}{}{Кто ваш начальник?}
{108}{}{У нас есть фермы и система орошения, и мы выращиваем Брамов.
 Каждый старается по мере своих способностей приносить пользу.}
{109}{}{Арадеш - наш нынешний начальник. Он со своим опытом помогает управлять коммуной.}
{110}{}{Привет.}
{111}{}{Привет.}
{112}{}{Кто ты?}
{113}{}{Приятно увидеть тебя.}
{114}{}{Ёорошего дня.}
