{100}{}{Это диск Кодекса Поведения Братства.}
{101}{}{Экран лаптопа: Файл Найден в Системе. Загрузка прервана.}
{102}{}{Экран лаптопа: Загрузка данных с диска.}
{103}{}{Ты видишь диск с програмным обеспечением кодировщика.}
{104}{}{Ты видишь холодиск.}
