{100}{}{Ты видишь видавшего виды фермера.}
{101}{}{Добрый день.}
{102}{}{Привет.}
{103}{}{Ёубип.}
{104}{}{Привет еще раз.}
{105}{}{Что я могу сделать для тебя?}
{106}{}{Как тебя зовут?}
{107}{}{Что ты можешь рассказать мне о деревне?}
{108}{}{Что ты делаешь?}
{109}{}{Ничего, спасибо.}
{110}{}{Меня зовут Кертис.}
{111}{}{Наша деревня небольшая, но мы сами себя содержим. Помимо нападений рейдеров и редкого посещения Рад Скорпиона, у нас нет проблем. Арадеш - хороший руководитель.}
{112}{}{Я - фермер. Мы осушили пустыню много лет назад. Ёотя пустынные земли суровы, но, благодаря терпению и времени, выращивать что-то возможно.}
{113}{}{Я понимаю. Тебе, кажется, это хорошо удается.}
{114}{}{А сейчас у вас засеяны все поля? Возможно, у вас бы лучше получилось с помощью севооборота.}
{115}{}{Севооборот? А что это такое?}
{116}{}{Без понятия.}
{117}{}{Вы засеиваете только часть из ваших полей, позволяя другим восстановить некоторые из питательных веществ, необходимых для выращивания. Это дает другим полям возможность снова стать плодородными, просто прекращая возделывать эти земли, что бы там ни росло. }
{118}{}{Гм. Никогда не думал об этом. Впрочем, это имеет смысл. Ёорошая идея.}
{119}{}{Могу я задать тебе еще вопрос?}
{200}{}{Ты зарабатываешь 500 очков опыта за помощь в развитии сельского хозяйства Шэйди Сэндс.}
