{100}{}{Ты видишь умирающего мутанта.}
{101}{}{Мутант близок к смерти.}
{102}{}{Ты видишь тело мутанта.}
{103}{}{Мутант мертв.}
{104}{}{Это произошло так быстро... Мой брат подошел... Не смог помочь...}
{105}{}{Кто ты?}
{106}{}{Я, я... я не могу вспомнить... Был начальником... Это... Может быть мой холодиск... (Мутант, слабея, передает тебе окровавленный холодиск)}
{107}{}{Откуда ты пришел?}
{108}{}{Мы... Мы проводили первичную разведку... Пришли из... с северо-запада.}
{109}{}{Кто вас послал?}
{110}{}{Отец... Где твой отец?... Да, Повелитель... (Мутант делает последный вздох и отключается)}
{111}{}{Ммммм... Ааааа....}
{112}{}{Повелитель.....}
{113}{}{Братья.... Где...?}
