{100}{}{Силовой генератор разрушен диверсантыми. Он больше не работает.}
{101}{}{Ты видишь силовой генератор. Это единственный источник энергии в Скрафиде.}
{102}{}{Ты отрезаешь немного проволоки с трансформатора. Силовой генератор больше не функционирует.}
{103}{}{Резцы больше нельзя использовать.}
{104}{}{Этот предмет бесполезен для генератора.}
{105}{}{В частности, ты ничего не замечаешь в генераторе.}
{106}{}{Сам генератор выглядит довольно-таки работоспособным; возможно ты заметил кусок
 проволоки между трансформатором и генератором.}
{107}{}{Ты не видишь ничего особенного в этом тяжелом генераторе.}
{108}{}{Больше ты ничего не можешь определить в генераторе.}
{109}{}{Проволоку можно починить, но это займет много времени, и нет никакой
 гарантии успеха.}
{110}{}{Ты не видишь ничего особенного около поврежденного генератора.}
{111}{}{Ты не в состоянии больше ничего починить.}
{112}{}{Нет необходимости в починке генератора. Он отлично работает.}
{113}{}{Ты не в состоянии починить работающий генератор.}
{114}{}{Это занимает несколько часов, но ты чинишь силовой генератор. Силовой
 генератор отремонтирован, банды ушли, люди, живущие в городе, благодарны
 тебе. Они предоставляют тебе ценную информацию. Твое задание в Скрефиде
 завершено. Миссия - найти водный фильтр еще ожидает.}
{115}{}{Ты не можешь починить генератор. Люди Скрефида будут жить хуже без
 электричества; но с бандами покончено, в конце концов, они хотят жить.
 Твое задание в Скрефиде сделано. Тебя еще ожидает миссия - найти водный фильтр.}
{116}{}{Далее попытка вмешательства в генератор не приносит результата.}
{117}{}{Это умение  не приносит успеха с генератором.}
{118}{}{Генератор уже запущен.}
{119}{}{Ты не в состоянии запустить генератор, потому что он сломан.}
