{100}{}{Ты видишь Крипта.}
{101}{}{Ты видишь бандита.}
{102}{}{Добро пожаловать в банду, парень.}
{103}{}{Мы, Крипты, похороним этих Идиотов.}
{104}{}{Я рад, что ты на на нашей стороне.}
{105}{}{С твоей помощью мы сможем убить этих Идиотов.}
{106}{}{Этот город сейчас весь наш.}
{107}{}{Мне нравится твой стиль.}
{108}{}{Ты получишь немного кожи. Ты сейчас Крипт.}
{109}{}{Нам не нужна здесь твоя доброта, Идиот.}
{110}{}{Убирайся, пока мы не выкинули тебя.}
{111}{}{Если ты начнешь какую-то заварушку, весь Крипт свалится на тебя.}
{112}{}{Ты сделал неправильный выбор. А сейчас тебя похоронят.}
{113}{}{Что здесь происходит?}
{114}{}{Скрефид принадлежит нам.}
{115}{}{В Скрефиде, если ты не с нами, ты или покойник или Идиот. Ну и кто ты?}
{116}{}{Ты мне говоришь? Ты мне это говоришь?}
{117}{}{Это не игрушки, парень. Ты или Крипт или тебя похоронят.}
{118}{}{Только Крипты обладают правом носит кожу.}
{119}{}{Беги, Идиот, пока у тебя еще есть шанс, чтобы выжить.}
{120}{}{Эй, Рейзи, сезон охоты уже открыт, и Идиоты в списке животных.}
{121}{}{Эй, парень, оставь Идиота для меня, чтобы убить его.}
