{100}{}{Это кажется странным. Похоже, это можно использовать в твоем Лаптопе.}
{101}{}{Дисплей лаптопа: Файл находится в системе. Загрузкой прервана.}
{102}{}{Дисплей лаптопа: Загрузка данных с диска.}
