{100}{}{Вы видите Старейшину.}
{101}{}{Приятно познакомиться. Надеюсь, что ты находишь эту деревню
 весьма приятной.}
{102}{}{Да.}
{103}{}{Нет, здесь скучновато.}
{104}{}{Отлично. Я имею честь просить тебя. Я обещаю, что твоя служба 
этим людям будет хорошо оплачена.}
{105}{}{Расскажи-ка мне еще . . .}
{106}{}{Это всего лишь намерения, но тебе должно понравиться то, что 
я сейчас скажу. }
{107}{}{Я весь во внимании . . . }
{108}{}{С некоторого времени нам досаждают Рад Скорпионы. Никто из тех,
 кого мы посылали к ним, не вернулся. Я дам тебе оружие и 
броню, если ты последуешь моим советам и пойдешь убьешь их всех.}
{109}{}{Звучит неплохо.}
{110}{}{Нет, спасибо.}
{111}{}{Жаль. Пожалуйста, уходи.}
{112}{}{Отлично. Сэмми проведет тебя к их логову. 
Возьми это - тебе это понадобится. }
{113}{}{Пожалуйста, помоги нам как можно скорее. Время уходит.}
{114}{}{Я не раговариваю с такими, как ты, незнакомец. }
