{100}{}{Ты видишь Паладина Фарли.}
{101}{}{Привет.}
{102}{}{Чад ра чука?}
{103}{}{Катя чу ни ка Чак ра Фарли.}
{104}{}{Фарли, нее ко }
{105}{}{ матчак о Дрейк.}
{106}{}{Ах, Дрейк ко матчак.}
{107}{}{Передавай привет нашему общему другу, если увидишь его снова.}
{108}{}{Братство напоминает мне о доме.}
