{100}{}{Ты видишь командира каравана Компании Фаргус.}
{101}{}{Привет. Если тебе нужна работа в караване, поговори с Рутгером.  Он где-то тут.}
{102}{}{Тебе нужно поговорить с Рутгером.}
{103}{}{Так ты записался.  Приятно это слышать.  Ты знаешь, мы отправляемся каждые 10 дней. Это
 8ое, 18ое и 28ое число каждого месяца. Сейчас мы совершаем рейсы в Братство Стали, Джанктаун и Бониярд.}
{104}{}{Так какая плата?}
{105}{}{Ёмм.}
{106}{}{Ты получишь 400 монет. Ты можешь сказать, что это не бог весть сколько много, но мы ходим часто. К тому же,
 это 400 монет за путь в каждую сторону. Конечно, тебе не обязательно возвращаться, 
я имею в виду, что ты получишь 800 монет, если все же решишь это сделать. }
{107}{}{ Мы отпраляемся сегодня. Интересно?}
{108}{}{ Мы отправляемся }
{109}{}{Пусто}
{110}{}{}
{111}{}{. Тебе это интересно?}
{112}{}{Я все еще даю тебе работу, несмотря на... неважно. Тебя это интересует?}
{113}{}{Конечно. }
{114}{}{Нет.}
{115}{}{Может быть.}
{116}{}{Да-да.}
{117}{}{Что?}
{118}{}{Чудненько. Без проблем. Дай мне знать, если передумаешь.}
{119}{}{Решишь ты наконец, или нет?}
{120}{}{Возвращайся, когда решишь, что делать. Это будет 8ое, 18ое и 28ое числа. Пока.}
{121}{}{Дааа, так не пойдет; если ты не можешь отличить правую ногу от левой, то нам не о чем разговаривать. Извини.}
{122}{}{Возвращайся, когда тебе будет лучше.}
{123}{}{Да, мужик, кажется, тебе не очень хорошо.   Тебе надо съесть что-нибудь.}
{124}{}{Вали отсюда!}
{125}{}{Нельзя ли не трогать мои вещи? Почему так получилось?}
{126}{}{Да я вааще крутой чувак и вааще, ты чо, наехал?}
{127}{}{Я голодаю и мне нечем кормить детей.}
{128}{}{Я выковырну тебе сердце вилкой! }
{129}{}{(Здаться)}
{130}{}{(Атаковать)}
{131}{}{Ты что, в лицо мне плюешь? Наверное, единственный способ сделать твою голову умнее - это оторвать ее от
 этой тощей шеи.}
{132}{}{Ёорошо, но это ничего не решит. Тебе все равно надо отсюда убираться.}
{133}{}{Ты думаешь, что я поверю в этот бред? Стража!}
{134}{}{Может быть, ты станешь повежливее, когда ты окажешься в баке. Уйдешь по хорошему, или как?}
{135}{}{Увидимся в аду!}
{136}{}{Да. Я извиняюсь.}
{137}{}{Так ты крутой? Ищешь повод для драки?}
{138}{}{Если ты не уберешься отсюда, я вызову полицию!}
{139}{}{Стража! Полиция!}
{140}{}{Я думаю, что тебе надо уйти...}
{141}{}{Извини, но я не предложу тебе работу.}
{142}{}{Я бы хотел дать тебе работу, но этого не случится.}
{143}{}{Уходи.}
{144}{}{Забавно, но ты мне не нравишься.}
{145}{}{Ну хорошо! Я плачу тебе 400 монет. Какой моршрут выбираешь?}
{146}{}{Приятно слышать. Возвращайся }
{147}{}{8ого}
{148}{}{18ого}
{149}{}{28ого}
{150}{}{}
{151}{}{}
{152}{}{Братство Стали }
{153}{}{. Тогда мы отправляемся. Как всегда, я плачу 400 монет.}
{154}{}{Ёорошо.}
{155}{}{Извини, не могу ждать.}
{156}{}{Точно не знаю, что случилось, но весь караван пропал. Забавно, что такое случилось, и забавно, что
 только ты один выжил. Просто так это не случается. Надеюсь, ты понимаешь, что я не могу предоставить
 тебе работу.}
{157}{}{Джанктаун}
{158}{}{Бониярд }
{159}{}{Ёммм, не сейчас. может быть, как нибудь потом?}
{160}{}{Приятно это слышать; я соберу всю команду.}
{161}{}{Отлично.}
{162}{}{Вали отсюда. Удачи!}
{163}{}{Постарайся не попадать в неприятности.}
{164}{}{Будь поосторожнее, Бониярд не самое безопасное место...}
{165}{}{Это хорошо. Эти черные тротуары действительно странные, но по ним очень удобно ходить.}
{166}{}{Тут-то они и облажались. Я буду следить за тем, с кем ты имеешь дело.}
{167}{}{Отлично. Джанктаун неплохое место.}
{168}{}{Да, и остановись у Киллиана и передавай ему от меня привет. Давненько мы с ним не виделись. }
{169}{}{Слышал, что сюда направляется какой-то доктор. }
{170}{}{Что происходило в твоей голове во время оставления каравана? Он дошел невредимым, но это чистая удача!}
{171}{}{Ну еще один шанс!}
{172}{}{Ничего.}
{173}{}{Мне пофигу!}
{174}{}{Иг ва ниае ру лааа?}
{175}{}{Лиг.}
{176}{}{Опять неудача! Ты, кажется, просто не в состоянии справится с такой работой.}
{177}{}{Зачем мне это?}
{178}{}{Незачем.}
{179}{}{Потому что в противном случае у тебя в голове появится дыра благодаря мне.}
{180}{}{У меня есть дела и поважнее, чем шататься вместе с дурацким караваном!}
{181}{}{Никто не говорил мне, что нельзя уходить. Все вроде было нормально.}
{182}{}{Я понимаю... это наркотики. Ну, живи так, если хочешь.}
{183}{}{Мне жаль, что ты так себя чувствуешь.}
{184}{}{Удивительно, что этого не случилось раньше. Если все дело в этом, ты не причинишь никому вреда,
 если я дам тебе еще один шанс.}
{185}{}{Это была хорошая работа. Не хочешь сделать ее еще раз?}
{186}{}{Конечно.}
{187}{}{Нет.}
{188}{}{Может быть.}
{189}{}{Фуу!}
{190}{}{Мдаааа.}
{191}{}{Все с собой? Мы выходим сегодня.}
{192}{}{Да.}
{193}{}{Нет!}
{194}{}{Ах!}
{195}{}{В противном случае я дам ее кому-нибудь другому, об этом не беспокойся. Это ни к чему не обязывает,
 пока ты не отправишься вместе с караваном.}
{196}{}{Следующего каравана не будет до }
{197}{}{8ого}
{198}{}{18ого}
{199}{}{28ого}
{200}{}{}
{201}{}{}
{202}{}{}
{203}{}{Иди сюда, если тебе все еще нужна работа. }
{204}{}{Января }
{205}{}{Февраля }
{206}{}{Марта }
{207}{}{Апреля }
{208}{}{Мая }
{209}{}{Июня }
{210}{}{Июля }
{211}{}{Августа }
{212}{}{Сентября }
{213}{}{Октября }
{214}{}{Ноября }
{215}{}{Декабря }
{216}{}{Братство Стали: вот и мы! Я не иду с тобой, но ты знаешь что я имею ввиду.}
{217}{}{Ёорошо, убирайся с глаз моих долой! Эти фанатики из братства ждут тебя.}
{218}{}{Надеюсь, ты любишь горы. Ты идешь прямо к ним. Там ты увидишь много действия.}
{219}{}{Все готово, и ты направляешься прямо к горам! Это будет круто!}
