{100}{}{Ты видишь охранника торговой компании Фаргус.}
{101}{}{Эти чертовы Торговцы Водой имеют нас, как хотят.}
{102}{}{Плати деньги во время, а не то пожалеешь.}
{103}{}{Тебе надо поговорить с Рутгером.}
{104}{}{Компания ФАРГУС - это лучшее, что тут есть!}
{105}{}{Караван Кримсона это сборище идиотов и лунатиков.}
{106}{}{Ёммм, я бы не отказался бы сейчас от игуаны на палочке.}
{107}{}{Кто, черт возьми, похищает наши караваны?}
{108}{}{Мой брат был в последнем караване, который исчез.}
{109}{}{Эти торговцы водой тут замешаны, я это чую!}
{110}{}{Я слышал, что караваны захватили мутанты. Ужасно.}
{111}{}{Слышал, что ты говорил про мутантов. Надеюсь, они поплатятся.}
{112}{}{Я думал, что это Рука Смерти виноват, чертов мутант.}
{113}{}{Мы закрыты. Приходи утром.}
{114}{}{Эй, это не Сокол. Вали отсюда!}
{115}{}{Кто ты? Дебил какой-то . . . Вали отсюда!}
{116}{}{Проваливай!}
{117}{}{Мы открыты только днем.}
{118}{}{Ты наркоман? Проваливай!}
{119}{}{Возвращайся утром.}
