{100}{}{Ты видишь Мексиканца с зализаными волосами гаденького вида. }
{101}{}{Ты видишь Ёернандеса, игрока-негодяя.}
{102}{}{Ой, мучачо, разреши мне представиться. Я Ёернандес, мужчина мучо густо!
 Ты похоже новичок в этом месте.
 Пожалуйста разреши мне быть твоим гидом по казино.}
{103}{}{Можешь рассказать мне о казино?}
{104}{}{Нет, спасибо.}
{105}{}{Бля?}
{106}{}{Ну, конечно! Это славное заведение руководится известным Гизмо.
 Он настоящий провидец и весьма преуспевающий джентельмен.}
{107}{}{Спасибо.}
{108}{}{Ты говоришь, что Гизмо провидец. Так в чем его дар?}
{109}{}{Каковы шансы на этих играх?}
{110}{}{Друг мой, я не люблю навязываться, но может ты сможешь мне проассистировать.
 Я разработал безпроигрышную систему, так как я вычислил, как Гизмо управляет
 своими столами, но у меня нет монет чтобы играть.}
{111}{}{ (У тебя появляется чувство, что он пытается тебя надуть.)}
{112}{}{Может ты можешь выделить мне несколько монет? Я гарантирую успех.}
{113}{}{Конечно, звучит толково.}
{114}{}{Нет, спасибо.}
{115}{}{Мне кажется, что ты лжешь. Ты пытаешься меня обобрать.}
{116}{}{Извини, ми амиго. Эй, дай мне показать тебе красивую игру...}
{117}{}{Спасибо тебе большое, ми амиго! Через пару дней я смогу тебе вернуть
 твои деньги с процентами. Моя система работает медленно, видишь ли,
 нужно много терпения, но зато потом это принесет немалый доход.}
{118}{}{Очень хорошо, но я гарантирую успех! Если хочешь отхватить прилично деньжат,
 возвращайся поскорее, а то я найду другого партнера!}
{119}{}{Друг мой, я вижу ты тоже человек со вкусом.
 Может простая игра в кости?}
{120}{}{Ладно!}
{121}{}{Нет, спасибо, я лучше попробую что-то другое.}
{122}{}{У Гизмо была мечта обосновать свое собственное местечко, где
 люди могли бы собираться и приятно проводить время. Он хотел,
 чтобы у него все получилось. В результате ты видишь вот это казино.}
{123}{}{Он дает людям возможность скинуть с себя груз неурядиц внешнего мира.
 И он обеспечивает приток денег в Джанктаун.}
{124}{}{Звучит как неплохая мысль.}
{125}{}{Жизнь и так сложна. Я не доверяю мотивации тех, кто подталкивает
 людей к выбрасыванию на ветер их денег.}
{126}{}{Ты очевидно не разделяешь великолепие Гизмо. Это место - убежище от
 повседневности.}
{127}{}{Ну, у Гизмо неплохое место, несмотря на то, что игры здесь, как бы это сказать,
 слегка ориентированы на доход казино. Не то чтобы крупье здесь мухлевали,
 но если у тебя нет системы, как у меня, тебе нужно быть ну очень умным.}
{128}{}{Спасибо.}
{129}{}{}
{130}{}{Как поживает твоя система?}
{131}{}{Ничего, спасибо.}
{132}{}{Моя система развивается медленно. У меня есть статья расходов на проживание и
 все такого рода, но она работает!}
{133}{}{Это здорово!}
{134}{}{Я думаю что ты обманщик и лжец. Где мои деньги?}
{135}{}{Так ты считаешь что напал на дурачка в моем лице, так?
 Ну уж от меня ты ничего не получишь!}
#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{136}{}{Буенос диас, мой друг! Что я могу для тебя сделать?}
{137}{}{Буенос диас, моя подруга! Что я могу для тебя сделать?}
