{100}{}{Охранник разъярен и атакует.}
{101}{}{Охранник напуган твоей мощью.}
{102}{}{Только Меч Тени может смутить этого охранника одним своим видом.
 Тебе придется делать это словами.}
{103}{}{Ты успешно стащил что-то у охранника.}
{104}{}{Тебя заметили.}
{105}{}{У охранника есть еще что-то с собой.}
{106}{}{Орхранник не затронут.}
{107}{}{Охранник на воротах Джанктауна.}
{108}{}{Что ты делаешь в Джанктауне, незнакомец?}
{109}{}{Ищу где бы поразвлечься.}
{110}{}{Дай мне все что у тебя есть!}
{111}{}{Не мог бы ты мне помочь с поисками оружия?}
{112}{}{Ничего. Спасибо. Пока.}
{113}{}{Здесь много чем можно заняться. Давай-ка посмотрим. Можешь тренироваться
 стрелять по коровам, бродить по городу или даже посещать
 достопримечательности, все до тех пор пока ты не причиняешь никаких
 неприятностей.}
{114}{}{А есть здесь еще что-нибудь?}
{115}{}{Прекрасно! Дай мне все что у тебя есть!}
{116}{}{Спасибо. До свидания.}
{117}{}{Ну, считается что старые жители прятали скверную пушку в его доме, на
 северо-западной окраине. Но никто ее никогда не нашел.}
{118}{}{О кей. Спасибо за твое время.}
{119}{}{Есть еще что-то?}
{120}{}{О кей, о кей. Пожалуйста не причиняй мне боли.}
{121}{}{Без мазы! Умри, плесень!!!}
{122}{}{Ну, считается, что паренек, который жил в здании на северо-западной стороне
 города держал у себя крайне неприятную пушку. Может ты сможешь ее найти.}
{123}{}{Прости, но я просто охранник. Попробуй поговорить с одним из других жильцов.}
{124}{}{Это просто общий ход вещей которые могут случатся когда начнется сама игра,
 где ты можешь либо убивать все что попадается на твоем пути, воровать и
 выкручиваться из проблем которые сам себе создаешь, или можешь выбираться
 из передряг путем бесед, заручаясь уважением других.}
{125}{}{Когда выйдет вся игра, ты сможешь стать свидетелем большего раскрытия своих
 возможностей чем здесь.}
