{100}{}{Ты видишь полицейского Ёаба.}
{101}{}{Ёотел бы я стоять на посту поближе к своему дому.}
{102}{}{Интересно что случилось с теми караванами.}
{103}{}{Проходи.}
{104}{}{Тебе лучше держать свое оружие в кобуре, незнакомец.}
{105}{}{Не влезай ни во что.}
{106}{}{У вас есть какие-либо товары для декларации?}
{107}{}{Не размахивай своим оружием у меня перед лицом.}
{108}{}{Убери это если не хочешь мотать срок.}
{109}{}{Ты это на меня наставляешь?}
{110}{}{Я слышал про тебя. Поосторожнее.}
{111}{}{Мы будем за тобой приглядывать.}
{112}{}{Никаких перепалок в нашем городе, крутой.}
{113}{}{Мы не любим убийц детей!}
{114}{}{Только тронь ребенка и мы за тобой устроим охоту.}
{115}{}{Я ненавижу таких как ты.}
{116}{}{Не зови на помощь, когда попадешь в беду.}
{117}{}{Эй, спасибо что сделал нашу работу за нас.}
{118}{}{Мы здесь не позволяем случаться убийствам, даже если они заслужены.}
{119}{}{Если ты тот кто убил Руку Смерти . . . спасибо.}
{120}{}{Не лезь в бутылку пока ты в нашем городе.}
{121}{}{Я бы держался подальше от Деккера на твоем месте.}
{122}{}{Приятного вам пребывания.}
{123}{}{Добро пожаловать в Ёаб!}
{124}{}{Приветствую тебя, незнакомец.}
{125}{}{Посети Мальтийский Сокол пропустить стаканчик.}
{126}{}{Иди вдоль главной дороги если ищешь рынок.}
{127}{}{Продолжай двигаться.}
{128}{}{Проходи. Проходи.}
{129}{}{Мы здесь чтобы Наблюдать и Предотвращать.}
{130}{}{Держи это оружие под контролем пока ты в нашем городе.}
{131}{}{Не ввязывайся ни в какие драки вот с этим.}
{132}{}{Я бы тебе порекомендовал убрать это оружие.}
{133}{}{Тебе лучше это убрать . . . имеется ввиду твое оружие.}
{134}{}{Добро пожаловать Паладин, давно не виделись.}
{135}{}{Это ты тут буйствуешь. Ёватит драк, понятно?}
{136}{}{Тебе лучше не затевать больше драк!}
{137}{}{Это ты . . . попридержи эту свою вспыльчивость.}
{138}{}{Торговую компанию Фаргус уничтожили. Не могу в это поверить.}
{139}{}{Водных Торговцев больше нет. Какое облегчение.}
{140}{}{Кримсон Караван уничтожен.}
{141}{}{Ты слышал? Поземелье наконец разнесли!}
{142}{}{Деккер мертв!}
{143}{}{Проблему Деккера наконец-то решили.}
{144}{}{Будь начеку - это не безопасное место.}
{145}{}{Следи что ты болтаешь, парень.}
{146}{}{Следи что ты болтаешь, леди.}
{147}{}{Старый Гарольд неплохо рассказывает сказки.}
{148}{}{Тебе не стоит быть здесь, это небезопасно.}
{149}{}{Старый Город на самом деле развалился.}
{150}{}{Это место воняет.}
{151}{}{Тебе надо разнести это место к черту.}
{152}{}{Я знаю, что этот Воровской Круг где-то здесь.}
{153}{}{Бедный Гарольд - у него была трудная жизнь.}
{154}{}{Не влезай ни во что.}
{155}{}{Эй. Я тебя знаю. Без драк, о кей?}
{156}{}{Тебе лучше и не думать о еще одной драке!}
{157}{}{Если мы застанем тебя дерущимся, ты сядешь за решетку!}
{158}{}{Ты слышал? Торговую Компанию Фаргус уничтожили.}
{159}{}{Водные Торговцы в прошлом. Какое благословение.}
{160}{}{Кто-то истребил Кримсон Караван.}
{161}{}{Ты слышал? Подземелье наконец-то стерли с лица земли!}
{162}{}{Деккер мертв!}
{163}{}{Этот город будет безопаснее теперь когда Деккер вышел из игры.}
