{100}{}{Ты видишь перед собой Ёолодиск.}
{101}{}{Экран лаптопа: Загружается информация с диска.}
{102}{}{Это похоже на диск на котором была записана какая-то развлекаловка.}
{103}{}{Диск слишком сильно поврежден для того чтобы ты мог с него чего-либо считать.}
{104}{}{Этот диск похоже говорит о каком-то коде для другого диска.}
{105}{}{Ты видишь маленький дисплей, который появляется и показывает куски из фильма про Вторую Мировую Войну.}
{106}{}{Диск пуст.}
{107}{}{Ты выкидываешь этот бесполезный диск.}
