{100}{}{Чего ты хочешь?}
{101}{}{Оставь меня в покое.}
{102}{}{Что?}
{103}{}{Не трогай мои вещи.}
{104}{}{Привет.}
{105}{}{Арррр!}
{106}{}{Грррр!}
{107}{}{Уххг.}
{108}{}{Ух.}
{109}{}{Эй, ты слышал, что Сета порешили?}
{110}{}{Сет мертв. Сет мертв. Сет мертв . . .}
{111}{}{Воды достаточно для всех. Сет об этом заботится.}
{112}{}{Я слышал что мутантов выперли из города.}
{113}{}{С тех пор как ушли мутанты стало лучше.}
{114}{}{Здравствуй.}
{200}{}{Ты изучаешь несчастное существо, но не можешь понять что его сделало таким.}
{201}{}{Это похоже было человеком когда-то или по крайней мере произошло от человека. Ты предполагаешь, что разрушение тела произошло под действием кислоты или радиации.}
{202}{}{Тело гуманоида по всей видимости сильно облучено, но все еще функционирует. Несмотря на то что когда-то это было человеком оно вернулось к какому-то животному существованию.}
{203}{}{Тело гуманоида похоже сильно облучено, и большая часть мышц и мозгового вещества сильно уменьшились. Несмотря на это генетические показатели дают тебе право предположить что произошло это с кем-то, кто как и ты пришел из Ёранилищ.}
