{100}{}{Ты видишь игрока.}
{101}{}{А-а! Это торчок!}
{102}{}{Я не хочу иметь с тобой проблем.}
{103}{}{У него ружье!}
{104}{}{У нее ружье!}
{105}{}{А, это ты.}
{106}{}{Я много плохого про тебя слышал. Здорово.}
{107}{}{Плохое начало, а?}
{108}{}{Ты ужасный человек. Убивать этих детей. Не могу в это поверить.}
{109}{}{Я слышал что за твоей головой охотились. Ты и их убил?}
{110}{}{Не говори со мной.}
{111}{}{Джизус, ты прикончил Мэра, не так ли?}
{112}{}{О, когда Киллиан был жив, мне это место не нравилось. Теперь здесь все о кей.}
{113}{}{Уходи.}
{114}{}{Эй, как у тебя сегодня дела? У меня все о кей.}
{115}{}{Эй, как у тебя этим вечером дела? У меня все о кей.}
{116}{}{Оставь меня в покое. У меня горячая полоса.}
{117}{}{Крошка, эти игровые автоматы мои.}
{118}{}{Дай мне что-нибудь попить, будь добр?}
{119}{}{Гр-р! Это место говно!}
{120}{}{Я сейчас делаю большие баксы.}
