{100}{}{Умри, собака!}
{101}{}{Мое поражение будет отомщено!}
{102}{}{Стой! О чем ты хочешь доложить?}
{103}{}{На западном фронте все спокойно.}
{104}{}{Рад Скорпионы и непереносимая жара. Эээ . . . сэр.}
{105}{}{Вообше-то, мне хотелось узнать, не слышали ли вы чего-нибудь?}
{106}{}{Докладывать не о чем, сэр!}
{107}{}{А?}
{108}{}{Стой! Я узнаю тебя -- тебя видели в Братстве. Кто-то доверяет тебе, а я нет. Занимайся своим делом! }
{109}{}{Мое дело такое же мое, насколько твое - твое.}
{110}{}{Мне хотелось увидеть дружелюбное лицо.}
{111}{}{Бродя по свалке, пытаясь выжить.}
{112}{}{Я смертельный пустынный таракан. Как опровергнешь?}
{113}{}{Отведи меня в Братство.}
{114}{}{Биз?}
{115}{}{Стой! Я узнаю тебя и не верю тебе. Предупреждаю: если ты причинишь нам какие-нибудь неприятности, тебя застрелят. Теперь иди!}
{116}{}{Стой! Кто это тут ходит? Назови свое имя!}
# TRANSLATION NOTES
# The player-character's name is inserted after line 117, and then has
# line 118, 119, 120, or 121 appended.
{117}{}{Я }
{118}{}{ и ищу водный чип для своего Ёранилища. Можешь помочь?}
{119}{}{ и я пытаюсь найти место подготовки атак мутантов.}
{120}{}{ и это не твое дело!}
{121}{}{ и я ищу приключения.}
{122}{}{Вставай, солдат!}
{123}{}{Ранк!}
{124}{}{Стой! Эти земли принадлежат Братству Стали. Немедленно уходи или мы откроем огонь!}
{125}{}{Очень хорошо. Продолжай.}
{126}{}{Я понимаю. Продолжай.}
{127}{}{Нам докладывают о больших людях-мутантах, атакующих путешественников, так что мы удваиваем бдительность. Присматривай за районом, и докладывай, в случае необходимости. Вольно!}
{128}{}{Это трудные времена. Мутанты атакуют караваны. Нам нужна информация, и сейчас! Нечего доложить, это не ответ!}
{129}{}{Уноси свою жалкую задницу отсюда, и принеси обратно ценную информацию! Вольно!}
{130}{}{О, да! Я слышал о тебе. Не много ума, но отличный боец. Плохо.}
{131}{}{Это наша земля, и здесь наше дело -- твое дело. Я повторяю, занимайся своим делом.}
{132}{}{Я ищу водный чип для своего Ёранилища. Ты можешь мне помочь?}
{133}{}{Я ищу базу мутантов.}
{134}{}{Это ваша земля, но я вам не раб.}
{135}{}{Я брожу по свалке довольно долго, и хочу узнать, есть ли у тебя какие-нибудь новости.}
{136}{}{Дружелюбное лицо? Это не мое. Я бы посоветовал уйти.}
{137}{}{Как и все мы. Пока ты не действуешь против Братства, тебе не причинят вреда, но действуй осторожно.}
{138}{}{Это зависит от того, учитываешь ли ты нас или нет. Если ты атакуешь наших врагов, тебе разрешат передвигаться по нашей территории. Если ты нападешь на нас, ты умрешь. Считай, что тебя предупредили.}
{139}{}{Это резонный вопрос. Давай.}
{140}{}{Водный чип? Надеюсь, что ты шутишь! Лучше страдать на поверхности, чем подчинять себя какому-то механизму.}
{141}{}{Как и мы. Самая распространенная теория - то, что мы пришли из Свечения, но я сомневаюсь, что даже мутанты способны там выжить. Если узнаешь что-нибудь интересное, дай нам знать. }
{142}{}{Как ты смеешь так меня оскорблять! Братство Стали никогда никого не принуждало служить себе. Это происходит из того, во что мы верим. Уйди с глаз моих долой!}
{143}{}{Мы нашли разбитый караван в дне пути отсюда на запад. Мы нашли только одного выжившего - бедную девочку. Она говорит, что их атаковали люди - мутанты огромной силы.}
{144}{}{Мы уже слышали достаточно докладов, чтобы . . . обеспокоиться. Я бы на твоем месте говорил бы поосторожнее.}
{145}{}{Мне придется научить тебя кое-каким манерам, мальчик. Это послужит маленьким развлечением.}
{146}{}{Мне придется обучить тебя кое-каким манерам, девочка. Это послужит маленьким развлечением.}
{147}{}{Твой ум совсем атрофировался. Бедное существо.}
{148}{}{Прекрати отнимать у меня время, тупица!}
{149}{}{Что тебе нужно?}
{150}{}{Ничего.}
{151}{}{Тогда я предлагаю тебе уйти.}
