{100}{}{Ты видишь Паладина.}
{101}{}{Извини, не могу говорить.}
{102}{}{Добрый день.}
{103}{}{Ты знаешь, что в моторизованой броне можно неделями жить без воды?}
{104}{}{Разве ты не любишь хорошую битву?}
{105}{}{Я очень люблю новые лазерные винтовки, но старые лазерные пистолеты любил больше.}
{106}{}{Ночные патрули по периметру очень опасны. Если бы я был тобой, то не заходил бы ночью слишком далеко.}
{107}{}{Будь поосторожнее, там смертельно опасный мир.}
{108}{}{Кажется, у меня пятно на броне!}
{109}{}{Братство это здорово! У меня нет никакого опыта вне его, но я не могу представить, что может быть лучше.}
{110}{}{Добрый день.}
{111}{}{Если тебе что-нибудь понадобится, поговори с Врее.}
{112}{}{Врее вон там, если тебе нужно с кем-то поговорить.}
{113}{}{Мне надо найти время между патрулированием и тренировками для занятий. Кажется, я глупею.}
{114}{}{Тебе надо всегда держать свое тело и разум в наилучшей форме.}
{115}{}{Быть Паладином, это не просто сражаться, сын мой.}
{116}{}{Быть Паладином, это не просто сражаться, девушка.}
