{100}{}{Стоп!}
{101}{}{Умри, человек!}
{102}{}{К смерти.}
{103}{}{Ты заплатишь за свои грехи!}
{104}{}{Я сокрушу тебя!}
{105}{}{Единство вечно!}
{106}{}{К Повелителю!}
{107}{}{Ты не должен здесь находиться, братец. Обьяснись!}
{108}{}{Ты не должна здесь находиться, сестричка. Обьяснись!}
{109}{}{Ёммм.}
{110}{}{Ёорошо, я здесь работаю.}
{111}{}{Ёорошо, у меня есть пропуск.}
{112}{}{У меня оружие с разрешения Лейтенанта.}
{113}{}{Что это за измена?}
{114}{}{Тогда покажи пропуск.}
{115}{}{Я, ээээ, он остался в другой куртке.}
{116}{}{Вот он, в дуле моего пистолета.}
{117}{}{Тогда торопись, но знай, я слежу за тобой.}
{118}{}{Да, братец. Что тебе нужно от меня?}
{119}{}{Да, сестричка. Что тебе нужно от меня?}
{120}{}{Ёмм!}
{121}{}{Ёмм, где же Повелитель?}
{122}{}{Молись Единству, брат.}
{123}{}{Я не провожу тебя к Единству. Уходи!}
{124}{}{Ты, наверное, из язычников!}
{125}{}{Тут это тут. Почему ты спрашиваешь?}
{126}{}{Ой, да так просто.}
{127}{}{Я поддам ему под зад и он окажется . . . ну, очень неблизко!}
{128}{}{Какой вопрос? Я говорю 'Да здраствует Повелитель, пока.'}
{129}{}{Ты оскорбляешь меня! Умри!}
{130}{}{Молись Единству.}
{131}{}{Кажется, что ты не веришь тому, что говоришь. Это правда? Тебя совратили с истинного пути?}
{132}{}{Ты ошибочно принимаешь дрожь в моем голосе за страх, а это всего лишь простуда.}
{133}{}{Я думаю, что твой род обречен. Давай, я докажу тебе это с помощью моих друзей.}
{134}{}{Когда ты станешь одним из нас, то не будешь бояться таких вещей. Уведите.}
{135}{}{Что ты хочешь на этот раз? У меня мало времени на болтовню.}
{136}{}{Лаббо!}
{137}{}{У меня очень мало времени для тебя. Умри!}
{138}{}{Ничего, извини.}
{139}{}{Молись Единству, брат.}
{140}{}{Ты, наверное, чужак!}
{141}{}{С глаз моих долой!}
{142}{}{У меня нет для тебя времени. Прекрати мне надоедать.}
{200}{}{Ты видишь Супер Мутанта Сержанта.}
{201}{}{Эй, это похоже на ядерную бомбу. Что она тут делает?}
{202}{}{Это оружие последней надежды Повелителя. Если мы найдем врага, которого не сможем уничтожить в битве, то мы уничтожим его этим. Но я сомневаюсь, что это когда-нибудь случится. Никогда наш Повелитель не захочет освободить спящий атом!}
{203}{}{Ёорошо, спасибо.}
{204}{}{Это работоспособно?}
{205}{}{Пожалуйста. А теперь помолчи, мне нужно сконцентрироваться на охране этого устройства.}
{206}{}{О, да. Мы храним ее в рабочем состоянии. Единство не будет побеждено!}
{207}{}{А, спасибо.}
{208}{}{Не боишься ли ты, что кто-нибудь прокрадется сюда и отключит ее?}
{209}{}{Нет. Мы здесь для защиты от чужаков. Никто не подбереться к бомбе незамеченным. К тому же, ключ, необходимый для ее разрядки, находится в другом мместе.}
{210}{}{Да, это меняет дело. Спасибо.}
{211}{}{Это, ээээ, чисто, чтобы мне спалось спокойно, не скажешь ли ты мне, где ключ?}
{212}{}{А, конечно, без проблем. Ключ у Лейтенанта. Он на военной базе, а вовсе и не здесь. Это хранит нашу бомбу от несанкционированного выключения.}
{213}{}{Спасибо за уделенное мне время.}
{214}{}{[Большой мутант пялится на тебя секунду, подняв пушистые ресницы] Я думаю, что ты задаешь слишком много вопросов.}
