{100}{}{Ты видишь мертвяка-стражника.}
{101}{}{Уходи! Тебя сюда не звали!}
{102}{}{Ёорошо. Приятно познакомиться.}
{103}{}{А?}
{104}{}{Я на посту. Если хочешь увидеть Сета, зайди внутрь.}
{105}{}{Дверь заперта. Тебе надо вернуться позже, когда стемнеет.}
{106}{}{Спасибо.}
{107}{}{А?}
{108}{}{Я говорил тебе уйти. Такие, как ты, здесь не нужны.}
{109}{}{Правильно.}
{110}{}{Муууу!}
{111}{}{Дверь не откроется до темноты.}
{112}{}{Мне нужно внутрь. Можешь мне как-нибудь помочь?}
{113}{}{Ёммм, хорошо.}
{114}{}{Уууу!}
{115}{}{Ну, наверное, это больно.}
{116}{}{Я хотел бы  тебе помочь, но Сет не пощадит моей задницы, если я это сделаю.
 Ты знаешь . . . всегда делай то, что говорит начальник.}
{117}{}{Да, я понимаю. Спасибо.}
