{100}{}{Ты видишь безжизненное тело, лежащее на земле.}
{101}{}{Здесь лежит несчастная душа.}
{102}{}{Останки мутировавшего человека лежат на полу.}
{103}{}{Плодородное поле для падали.}
{104}{}{Кажется, этот человек бросил вызов Танатосу и проиграл.}
