{100}{}{Ты видишь Гизмо, владельца казино.}
{101}{gizmo_1}{Тащи сюда свою задницу, садись. Мне нужно с тобой поговорить о деле.}
{102}{}{Похоже здесь и так предостаточно задниц...}
{103}{}{Я вот сколько собрал. Чего ты хочешь?}
{104}{}{Какое дело?}
{105}{}{Бля.}
{106}{gizmo_1b}{Убирайся отсюда, идиот!}
{107}{gizmo_2}{Я должен тебе верить? Покажи хоть чуточку уважения.}
{108}{}{Ты чем-нибудь, кроме как жрать занимаешься?}
{109}{}{Да ты что надо, извини. Так давай поговорим о деле.}
{110}{gizmo_4}{Ладно, ( Гизмо фыркает ) значит так. Джанктаун уже не тот, что был.
 Единственная причина по которой он еще вообще существует, так это 
мое заведение. Но даже при таком раскладе, Киллиан продолжает
 дышать мне в спину и я начинаю болезненно это воспринимать.
 ( Гизмо фыркает ) И вот здесь появляешься ты, умник.}
{111}{}{Что ты хочешь чтобы я сделал?}
{112}{}{Если ты думаешь, что я тебе помогу, то ты толст и глуп.}
{113}{gizmo_4a}{Смешно.}
{114}{gizmo_5}{Что я думал, так это что ты прикончишь его для меня, понимаешь? Без свидетелей, 
просто раз, два и готово.}
{115}{}{Почему бы тебе не послать одного из твоих собственных орлов?}
{116}{}{Я бы не стал с тобой работать даже если бы ты предложил мне все деньги в 
этом паршивом месте.}
{117}{}{Конечно. Деньги мне пригодятся.}
{118}{}{Я так не думаю. Все равно спасибо.}
{119}{}{Сколько ты готов заплатить?}
{120}{gizmo_6}{Я бы так и поступил бы, но не должно существовать никакой связи между мной и внезапной кончиной Киллиана.}
{121}{}{Толково. Ладно, я это сделаю.}
{122}{}{Ёорошо, я это сделаю.}
{123}{}{Каков трус. Боишься что люди тебя невзлюбят? Слишком поздно для тебя.}
{124}{}{Сколько ты готов заплатить?}
{125}{}{Ни за что.}
{126}{}{Я не думаю.Но все равно спасибо.}
{127}{gizmo_7}{( Гизмо хрипит.) Я знал, что ты это поймешь так же как я. А в доказательство,
 я хочу бирки Киллиана, что он носит на шее. Ты их приносишь, получаешь деньги.
 А сейчас иди. И не зли меня. У меня до сих пор храняться коленные чашечки того, кто
 попытался это сделать.}
{128}{gizmo_8}{Тысяча монет. Не больше, не меньше.}
{129}{}{Звучит неплохо. Я это сделаю.}
{130}{}{Ты называешь это наградой? Если я буду мочить парня то мне понадобится 
больше, чем это.}
{131}{}{Даже не близко. Я не хочу ничего в этом деле.}
{132}{}{Я бы тебе и на расстояние броска не стал бы доверять. Забудь об этом, худышка.}
{133}{gizmo_9}{( Гизмо смеется и кашляет ) Может ты и прав. Я думаю ты стоишь большего. 1500.}
{134}{}{Ну теперь это уже разговор.}
{135}{}{Это что , по доллару за каждый фунт твоего веса? Забудь об этом.}
{136}{}{Спасибо, но что-то не хочется.}
{137}{}{Ни за что.}
{138}{gizmo_10}{Жаль, что ты испытываешь такие чувства по этому поводу. Но ты сейчас еще больше пожалеешь,
 так как мы не можем допустить утечки информации. Изо, покажи-ка нашему гостю, что мы делаем с теми, кто говорит мне нет.}
{139}{gizmo_11}{Один - ничего, два - слишком много. А это было два.
 Изо, достань мне пару коленных чашечек.}
{140}{gizmo_13}{Ты уже закончил работу?}
{141}{}{Да, конечно.}
{142}{}{Нет, еще нет.}
{143}{gizmo_14}{Дай-ка взглянуть на бирки.}
{144}{gizmo_15}{О, да. О, да! Твои деньги у Изо. О, это здорово! Эй, эй, э-э...
 тебе стоит покинуть город на какое-то время. Ну знаешь, на всякий случай.}
{145}{}{О кей, я ухожу.}
{146}{}{Ты мне не указ, толстяк. Понял?}
{147}{}{А если я не стану?}
{148}{}{Конечно я уйду, но запомни, что ты у меня в долгу.}
{149}{gizmo_16}{Если ты не покинешь город, ты окажешься прямо под ним. Ты меня понял?}
{150}{}{О кей, о кей. Я пойду.}
{151}{}{И кто это сделает? Ты? Ты бы не смог поднять свой зад даже чтобы достать сендвич, не то чтобы убить меня.}
{152}{}{Ёорошо, но помни, что ты у меня в долгу.}
{153}{gizmo_17}{Ну а тогда давай мне бирки?}
{154}{}{Э-э...Ну....я... потерял их.}
{155}{}{Что если я не хочу их тебе отдавать?}
{156}{}{Я солгал. У меня их нет.}
{157}{}{Они у меня были, но я их потерял.}
{158}{gizmo_18}{( Гизмо смеется ) Ты знаешь, что ты бездарный лжец. А теперь иди и достань бирки. Я не
 хочу видеть твою физиономию, пока ты не порешишь Киллина.}
{159}{gizmo_19}{Без проблем я сниму их с твоего мертвого тела.}
{160}{}{Ну...я вообщем соврал. У меня их нет.}
{161}{}{Да? Ты наймешь кого-то чтобы делать твои дела за тебя?}
{162}{}{Я их потерял.}
{163}{}{Ну они у меня были, но их украли.}
{164}{gizmo_20}{Нет бирок, нет денег. Еще раз вернешься без бирок и Изо займется
 искусством на твоем теле. А теперь убирайся!}
{165}{gizmo_21}{Чего ты хочешь? Я занятый человек.}
{166}{}{Я здесь чтобы рассказать, что твое покушение не удалось.}
{167}{}{Вообще-то ничего. Я просто пойду.}
{168}{}{Мне хотелось бы знать как кто-то такой дурной, как ты еще жив.}
{169}{}{Я здесь чтобы поговорить о покушении на Киллиана.}
{170}{gizmo_22}{Я не знаю о чем ты.}
{171}{}{Конечно знаешь. Ты кого-то нанял, чтобы убить Киллиана и он напортачил.}
{172}{}{Ты не помнишь, что нанимал кого-то убить Киллиана, ты глупый слизняк?}
{173}{}{Ну давай предположим такую гипотетическую ситуацию...}
{174}{}{Ты лжец!}
{175}{}{Ты прав, пока.}
{176}{gizmo_23}{Я не знаю кто ты, но я не особо люблю, когда незнакомцы вваливаются в мой 
офис и обвиняют меня в чем-то, о чем ни черта не знают.}
{177}{}{А, вот тут то ты и не врубился, Гизмо.
 Я не обвиняю тебя. Я здесь, чтобы помочь тебе.}
{178}{}{Я все знаю. Сознавайся!}
{179}{}{Ты прав. Я ухожу.}
{180}{gizmo_24}{Правда? ( Гизмо закашливается ) Он будет мне помогать? О какой помощи идет речь?}
{181}{}{Просто. Ты послал кого-то чтобы убить Киллиана. Он не справился.
 Тебе нужен кто-то кто бы мог сделать это...лучше.}
{182}{}{Ничего. Забудь, что я это упомянул.}
{183}{gizmo_25}{И дай мне угадать, ты и есть тот самый?}
{184}{}{Очень хорошо...за определенную цену, конечно.}
{185}{}{Я могу замочить его быстрее, чем ты успеешь плюнуть.}
{186}{gizmo_26}{Ну, и как я могу тебе доверять?}
{187}{}{Я здесь. А тебе нужен кто-то не из города, кто бы за тебя сделал твою грязную работу. Так?}
{188}{}{Я не могу... Я хочу сказать ты можешь... Я имею ввиду...}
{189}{}{Потому, что я был в переплетах. Мне и убивать приходилось.}
{190}{gizmo_27}{Ёмм... ладно. Мы можем это сделать. Но если ты на меня работаешь, тебе
 лучше знать, что никто не подставляет Гизмо и не желает, чтобы об этом
 знали. Ты меня понимаешь?}
{191}{}{Я мог бы положиться на тебя... но никто не должен знать.}
{192}{}{Конечно, но сначала я должен знать, что он мертв.}
{193}{gizmo_28}{Ёа, это просто. Я хочу избавиться от него потому, что он встает на пути моего
 дела. Так ты его сделаешь для меня?}
{194}{}{Для этого я и здесь. Он будет мертв до того, как сядет солнце.}
{195}{}{Конечно. Это работа.}
{196}{}{Можешь это еще раз сказать, пожалуйста... в этот раз в кармане моего пальто?}
{197}{}{Ну, нет...Нет, я не могу.}
{198}{gizmo_29}{Ёорошо. Вернись с бирками, что он носит на шее, как доказательство.
 Этого разговора никогда не было, ты никому об этом не говоришь.
 Никто не шутит со мной. Никто.}
{199}{gizmo_30}{Ты или совсем дурак... или очень глупый шпион. Но сейчас это неважно,
 так как Изо сделает тебя очень мертвым. }
{200}{gizmo_32}{Я не люблю людей, которые попусту тратят мое время. В ближайшее время и не
 возвращайся!}
{201}{gizmo_33}{Например?}
{202}{}{Ну, давай предположим, что ты пробовал убить Киллиана и твой человек провалил дело.
 Это значит, что тебе нужен новый человек, чтобы поправить дело.}
{203}{}{Э? Ну, неважно.}
{204}{gizmo_34}{Ты знаешь, ( Гизмо вздыхает ) я не люблю, когда мне говорят гадости в моем
 заведении. Изо, проводи нашего гостя... через окно.}
{205}{gizmo_35}{Ты вернулся. Знаешь, мне пришлось нанять кое-кого другого, чтобы сделать твою работу.
 И это меня не порадовало. Знаешь, Изо тебе покажет в точности как я недоволен. 
Надеюсь, что у тебя был приятный день, потому что он был твой последний.}
{206}{gizmo36a}{( Гизмо бурчит.) Киллиан мэр этого города. Считает, что все знает...
 ну, посмотрим сколько именно он знает, неправда ли?}
{207}{gizmo_37}{( Гизмо кашляет.) Это я, дурак. Я заправляю... игральным заведением здесь.}
{208}{gizmo_38}{Это заведение Киллиана на севере города. Он продает дерьмо.}
{209}{gizmo_39}{Ну, большинство делают здесь ставки. Ты задаешь глупые вопросы.}
{210}{gizmo_42}{Не хотел бы ты знать?}
{211}{gizmo_43}{Тебе не стоит загружать себя этим.}
{212}{gizmo_44}{( Гизмо хлюпает.) Я... не хочу говорить об этом сейчас.}
{213}{gizmo45m}{Эй, что это ты делаешь? Оторви-ка ему руки, Изо.}
{214}{gizmo45f}{Эй, что это ты делаешь? Оторви-ка ей руки, Изо.}
{215}{gizmo_47}{Ты что, не слышишь? Я сказал...}
{216}{gizmo_48}{Эй, я не буду повторять!}
{217}{}{Ты получаешь 600 очков опыта в случае победы над Гизмо.
 Пусть подонок гниет по кусочкам.}
{218}{}{Это весьма вероятно самый гнилой тип которого ты видел на своем веку.}
{219}{}{Ты знаешь, я нашел что-то очень интересное, после того, как ты был здесь в последний раз.
 Если и есть что-то что я не выношу больше вшивой пиццы пеперони, так это жучки.
 Мальчики!}
{220}{}{Значит расклад такой, Киллиан. Вобщем, я не мог больше переносить твою вонь, и положу
 этому конец!}
{221}{}{Я позаботился о Киллиане. Говорят ты можешь это по достоинству оценить.}
{222}{}{Даже так?}
{223}{}{Эй, о кей, если ты не хочешь его смерти, ладно. Просто хотелось помочь.}
{224}{}{Я думал что-то вроде ножа в спину или пули в голову.}
{225}{}{Понял. А для чего тебе от него избавляться?}
{226}{gizmo_24}{Правда? (Гизмо поперхнулся.) Она будет мне помогать?
 О какой помощи идет речь?}
# Gizmo's Tell-Me-Abouts generic responses
{980}{gizmo_42}{Тебе не хотелось бы узнать?}
{981}{gizmo_43}{Тебе не стоит забивать себе этим голову.}
#
# Gizmo's Tell-Me-Abouts
#
{1000}{}{Киллиан}
{1001}{}{Гизмо}
{1002}{}{Даркуотеры}
{1003}{}{Гизмо}
{1004}{}{Даркуотер}
{1005}{}{Гизмо}
{1006}{}{Казино}
{1007}{}{Джанктаун}
{1100}{gizmo36a}{( Гизмо бурчит.) Киллиан мэр этого города. Считает, что все знает... ( Гизмо смеется.)
 ну, посмотрим сколько именно он знает, неправда ли?}
{1101}{gizmo_37}{( Гизмо кашляет.) Это я, дурной. Я заправляю этим игральным заведением.}
{1102}{gizmo_38}{Это местечко Киллиана на север от города. Он торгует всяким дерьмом.}
{1103}{gizmo_39}{Ну, большинство здесь играют. Ты задаешь дурацкие вопросы.}
{1104}{gizmo36a}{( Гизмо бурчит.) Киллиан мэр этого города. Считает, что все знает... ( Гизмо смеется.)
 ну, посмотрим сколько именно он знает, неправда ли?}
{1105}{gizmo_39}{Ну, большинство здесь играют. Ты задаешь дурацкие вопросы.}
{1106}{gizmo_39}{Ну, большинство здесь играют. Ты задаешь дурацкие вопросы.}
{1107}{gizmo_39}{Ну, большинство здесь играют. Ты задаешь дурацкие вопросы.}
