{100}{}{Замороженый труп.}
{101}{}{Это однозначно не земного происхождения.}
{102}{}{Это тело может быть результатом какого-то генетического эксперимента.}
{103}{}{Что? это мертвое тело.}
{104}{}{Это замороженое тело странно выглядит.}
