{100}{}{Ты видишь мертвецкого подземщика.}
{101}{}{Мы просто хотим, чтобы нас оставили в покое.}
{102}{}{Сет - некомпетентный дурак из-за которого нас убивают.}
{103}{}{Супер мутанты убьют нас всех в один прекрасный день, а Сет не помогает.}
{104}{}{Мы здесь прячемся; пожалуйста никому не говори, где мы.}
{105}{}{Мне не нравится твой вид.}
{106}{}{Уходи и оставь нас в покое.}
{107}{}{Я слышал о вас много плохого. Это все правда?}
