{100}{}{Вы видите Дарена Ёайтауера.}
{101}{}{Вы кто?!? И кто вас пустил?}
{102}{}{У меня есть послание от друга.}
{103}{}{Ваша жизнь в опасности, и мне нужно с вами погорорить.}
{104}{}{Меня зовут }
{105}{}{. Меня пустил Леон.}
{106}{}{Мое имя?... Смерть!}
{107}{}{Я твой худший ночной кошмар.}
{108}{}{БоБо?}
{109}{}{У меня нет друзей, что у тебя за сообщение?}
{110}{}{Деккер шлет привет.}
{111}{}{Ёмм...меня послал Боб...э-э...он сказал, что вы заплатили ему лишних 100 долларов, он послал меня вернуть их вам.}
{112}{}{Вообще-то никакого сообщения нет, я просто пытался выпутаться из этой ситуации.}
{113}{}{Я люблю тебя.}
{114}{}{Скажи мне чего-нибудь чего я не знаю, ты, придурок!}
{115}{}{Придурок? Я пытался тебе помочь. Можешь идти к черту.}
{116}{}{Деккер хочет от тебя избавиться и нанял меня чтобы это сделать.}
{117}{}{Ты явно не понимаешь, что сейчас умрешь!}
{118}{}{Забудь об этом. Я просто хотел помочь.}
{119}{}{Было приятно с вами познакомиться. }
{120}{}{. А сейчас мой помошник Леон покажет тебе выход.}
{121}{}{Я не знаю никакого Боба, но я возьму эти 100 баксов и можешь уходить.}
{122}{}{Иди к черту!}
{123}{}{О кей, пожалуйста. Спасибо за твое время.}
{124}{}{А-а... Тот УБЛЮДОК Боб не дал мне все деньги! Я их для вас достану, мистер Ёайтауер, я честно это сделаю!}
{125}{}{Не бери в голову. Мне всегда нравится, когда в мой дом приходят незнакомцы и приносят мне деньги. Леон, покажи этому дураку
 где дверь! Придешь еще раз и мои охранники оторвут тебе голову!}
{126}{}{Леон, покажи этому дураку где дверь! Придешь еще раз и мои охранники оторвут тебе голову!}
{127}{}{Охрана! Киллер!}
