{100}{}{Вы видите низкого коренастого человека.}
{101}{}{Таких, как ты, здесь не любят.}
{102}{}{Здравствуй, незнакомец. Похоже, ты здесь недавно. Как тебя зовут?}
{103}{}{Мое имя тебе ничего не скажет.}
{104}{}{Меня зовут }
{105}{}{.}
{106}{}{Гхрм.}
{107}{}{То же можно сказать и про тебя.}
{108}{}{Приятно познакомиться. Мое имя Ян.}
{109}{}{Что ты здесь делаешь?}
{110}{}{Ёотелось бы познакомиться с этим местечком поближе. Не поможешь?}
{111}{}{Извини, но у меня нет времени на придурков.}
{112}{}{Я был охранником у купца из Ёаба. Однажды меня подстрелили бандиты. Местные жители выходили меня и с тех пор я живу здесь. Тем не менее мои знания о внешнем мире и огромный боевой опыт позволяют мне и тут оставаться полезным. Теперь мой дом это Шэйди Сэндс. Иногда я отправляюсь в Ёаб или Джанктаун с торговыми целями, ведь я едва ли не единственный житель города, бывший за его стенами.}
{113}{}{Ты видишь Яна.}
{114}{}{Мне очень жаль, что тебя ранили.}
{115}{}{Где находятся Ёаб и Джанктаун?}
{116}{}{Расскажи мне побольше о бандитах.}
{117}{}{Шэйди Сэндс это небольшая, но вполне самодостаточная община. Единственные проблемы здесь - это бандиты и Рад скорпионы.}
{118}{}{Почему Радскорпионы вас беспокоят?}
{119}{}{Здесь много бандитов?}
{120}{}{Встречаются. Они из разных группировок. Они воруют у нас еду и время от времени убивают людей. Сет обучает стражников для борьбы с ними.}
{121}{}{Расскажешь мне о Сете?}
{122}{}{Разные группы? А кто они?}
{123}{}{Радскорпионы очень опасны. У них ядовитое жало, и они очень быстры. Арадеш пытается найти способ бороться с ними. Если чувствуешь в себе силы, поговори с нашим руководителем.}
{124}{}{Спасибо. Заживает более-менее быстро, благодаря Разло.}
{125}{}{Сет очень храбрый воин. Он иногда уходит в глубины пещер Рад Скорпионов и убивает несколько, но они всегда возвращаются назад. Просто их слишком много для одного человека.}
{126}{}{А Радскорпионы действительно так опасны?}
{127}{}{Чем я могу вам помочь?}
{128}{}{Есть три группы: Ёаны, Вепри и Шакалы. Ненавидят друг друга самой черной ненавистью, но кое-что их об'единяет - они все нападают на Шэйди Сэндс.}
{129}{}{Расскажи мне о Шэйди Сэндс.}
{130}{}{У него уверенный спокойный вид весьма опытного бойца.}
# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 131 and 132.
{131}{}{Итак, }
{132}{}{что я могу сделать для тебя?}
{133}{}{Расскажи мне о рейдерах.}
{134}{}{Расскажи мне о Рад Скорпионах.}
{135}{}{Расскажи мне о Шэйди Сэндс.}
{136}{}{Расскажи мне о Сете.}
{137}{}{Не скажешь, каким путем пробираются в Ёаб или Джанктаун?}
{138}{}{Спасибо, ничего.}
{139}{}{Ёаб это большой торговый центр сильно южнее Шэйди Сэндс. В нем заправляют несколько разных коммерческих групп : Водоторговцы, Кримсон Караван, Компания Фарго. Джанктаун немного южнее и на восток. Он поменьше, но все равно классное местечко, чтобы промочить горло. В нем заправляет деятель по имени Киллиан Даркуотер, местный торговец, шериф, царь, бог и воинский начальник.}
{140}{}{Спасибо.}
{141}{}{Я уже не тот боец каким был когда-то, но намного лучше хлыщей, подобных тебе!}
# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 142 and 143.
{142}{}{Что я могу сделать, }
{143}{}{?}
{144}{}{Ёмм. Ничего. Не беспокойся, Ян.}
{145}{}{Ты свободен.}
{146}{}{Каким путем пройти в Ёаб и Джанктаун?}
{147}{}{Как скажешь. Увидимся.}
{148}{}{Да нет, спасибо. Я здесь необходим.}
{149}{}{Не поможешь мне? Твой опыт очень даже пригодится.}
{150}{}{Пошли. Как приятно опять заняться своим делом!}
{151}{}{Это магазин Киллиана. Киллиан очень хороший человек, и у него большой выбор разных товаров.}
{152}{}{Казино Гизмо. Просто рассадник азарта и злачной жизни. Будь настороже - говорят, игра идет нечестно.}
{153}{}{Это место по-настоящему пугает меня.}
{154}{}{Что за чертовщина здесь случилась?}
{155}{}{Этот крепкий орешек, сразу не расколешь.}
{156}{}{Ёмм. Интересное предложение, а то что-то скучновато. Вот что тебе скажу. Обычные ставки. 100 монет, и порядок.}
{157}{}{Идет.}
{158}{}{Да нет, спасибо.}
{159}{}{Может, лучше вместо этого делом займемся?}
{160}{}{Ёорошо, помогу тебе с работой за мою долю добычи.}
{161}{}{Нет, не думаю. Приходи опять, когда деньги будут.}
{162}{}{Это оружейный магазин. Ёозяином здесь Бет.  Ёорошо разбирается в патронах и винтовках, но еще лучше в болтовне.}
{163}{}{Оружие Джейка. Высокие цены, но действительно классные пушки.}
{164}{}{Контора Водоторговцев. Они шевелят и развивают Ёаб, поскольку снабжают водой, которая всем необходима. Вода в пустыне - источник жизни.}
{165}{}{Это Кримсон Караван. Я пару раз работал на них. Они частенько проворачивают рискованные делишки.}
{166}{}{Торговая Компания Фарго, начальником здесь Бутч Ёаррис. Он крут, это вам не какой-нибудь придурок.}
{167}{}{Да, вот Мальтийский Сокол - настоящее развлекательное заведение. Ёорошая музыка, хорошая выпивка и подходящая компания.}
{168}{}{Что за мерзкий сукин сын!}
{169}{}{Ты зарабатываешь 100 очков опыта за принятие Яна в свою компанию.}
{170}{}{Слыхал об этих местах раньше, но никогда там не был. Чисто и красиво... Слишком уж чисто на мой вкус.}
{171}{}{Не моего ума дело, но тебе необходимо поразмыслить над сложившейся ситуацией.}
{172}{}{Знаешь, эта женщина и танго не смогла бы вести, не говоря о революции.}
{173}{}{Ты чем воюешь лучше всего?}
{174}{}{Я хорошо стреляю из практически любого пистолета, из автомата тоже неплохо. Кроме того, и с ножом умею обращаться.}
#
# Translation note
# The following	line is	directed at Katja, a female scavenger, not at the player.
# Ian is noting	that he	thinks that the	Boneyard was a worse place than	the
# mutants' military base.
#
{175}{}{Я думал, Бониярд еще хуже.}
{200}{}{Дерись лучшим, что у тебя есть в следующей драке.}
{201}{}{Без вопросов.}
{202}{}{Что-нибудь сделать, прежде чем я уйду?}
{203}{}{Ммм, да. Пожалуй, нам лучше и дальше держаться друг друга.}
{204}{}{Да нет. Спасибо.}
#
# Ian tell-me-abouts
#
{1000}{}{Вода}
{1001}{}{Война}
{1002}{}{Шэйди}
{1003}{}{Джанктаун}
{1004}{}{Ёаб}
{1005}{}{Рейдеры}
{1006}{}{Караваны}
{1007}{}{Фильтр}
{1008}{}{Сэндс}
{1009}{}{Последователи}
{1010}{}{Собор}
{1011}{}{Гарл}
{1012}{}{Повелитель}
{1013}{}{Единство}
{1014}{}{Сет}
{1015}{}{Водораздел}
{1016}{}{Некрополис}
{1017}{}{Залы}
{1018}{}{Библиотека}
{1019}{}{Смотритель}
{1020}{}{Доктор}
{1021}{}{Лечение}
{1022}{}{Ёранилище}
{1023}{}{Ёранилище-13}
{1024}{}{Ёранилище13}
{1025}{}{Киллиан}
{1026}{}{Гизмо}
{1027}{}{Бониярд}
{1028}{}{Казино}
{1029}{}{Магазин}
{1030}{}{Рука Смерти}
{1031}{}{Исход}
{1032}{}{Посвященные}
{1033}{}{Паладины}
{1034}{}{Писцы}
{1035}{}{Дети}
{1036}{}{Братство}
{1037}{}{ВЭТы}
{1038}{}{Военная}
{1039}{}{База}
{1041}{}{Апокалипсис}
{1042}{}{Мутанты}
{1043}{}{Морфей}
{1044}{}{Ёаны}
{1045}{}{Танди}
{1046}{}{Алия}
{1047}{}{Диана}
{1048}{}{Гвен}
{1049}{}{Петрос}
{1050}{}{Толя}
{1051}{}{Выпивка}
{1052}{}{Таблетки}
{1053}{}{Сетч}
{1054}{}{Арадеш}
{1055}{}{Разло}
{1056}{}{Циммерман}
{1057}{}{Регуляторы}
{1058}{}{Собиратели}
{1059}{}{Лезвия}
{1060}{}{Николь}
{1061}{}{Лейтенант}
{1062}{}{Психики}
{1063}{}{Эксперименты}
{1064}{}{Полиция}
{1065}{}{Торговцы}
{1100}{}{Понятия не имею о водяном фильтре. Прости, дружище.}
{1101}{}{Случилось это несколько десятилетий назад. В начале, несколько стран чего-то там не поделили и все вокруг вдруг рвануло к чертям!}
{1102}{}{Маленькая мирная деревушка. Пожалуй, самое многообещающее сообщество в этой дыре.}
{1103}{}{Средних размеров город из старых железяк, которым руководит шериф Киллиан. Несколько дней пути на юго-запад от Шэйди Сэндс.}
{1104}{}{Ёаб это крупнейший торговый центр на Новом Западе. В нем заправляют так называемые Водоторговцы, но есть и другие купеческие конторы. Это развивающийся город, но там идет политическая борьба между конкурентами.}
{1105}{}{Есть несколько разных групп рейдеров. Самые организованные это Ёаны; они похоже думают, что им предстоит возвыситься до завоевателей мира или что-то вроде того.}
{1106}{}{В основном караваны приходят из Ёаба. Они путешествуют повсюду. Я работал на Кримсон Караван, прежде чем меня ранили. Так не вовремя, черт бы их подрал.}
{1107}{}{Не знаю о водяном фильтре. Прости, дружище.}
{1108}{}{Небольшая мирная деревушка. Она вселяет надежду в этой забытой богом выжженной пустыне.}
{1109}{}{Извини, дружище. Не знаю.}
{1110}{}{Извини, дружище. Не знаю.}
{1111}{}{Гарл - это придурок, который вообразил, что может захватить вселенную со своей сворой жалких шавок-райдеров. Ну ну.}
{1112}{}{Извини, дружище. Не знаю.}
{1113}{}{Извини, дружище. Не знаю.}
{1114}{}{Извини, дружище. Не знаю.}
{1115}{}{Извини, дружище. Не знаю.}
{1116}{}{Это часом не мифический город мертвых?}
{1117}{}{Извини, дружище. Не знаю.}
{1118}{}{Извини, дружище. Не знаю.}
{1119}{}{Извини, дружище. Не знаю.}
{1120}{}{Разло очень хороший доктор. Поговори с ним, если будешь ранен.}
{1121}{}{Разло классно чинит раненых, а его знаменитый целебный сок стоит отдельного упоминания.}
{1122}{}{Извини, дружище. Не знаю.}
{1123}{}{Извини, дружище. Не знаю.}
{1124}{}{Извини, дружище. Не знаю.}
{1125}{}{Киллиан - это глава Джанктауна. У него также есть магазин. Он неплохой парень. Никогда на него не работал, но он похоже, ничего.}
{1126}{}{У Гизмо в Джанктауне есть казино. В нем, говорят, не чисты на руку.}
{1127}{}{Извини, дружище. Не знаю.}
{1128}{}{Казино - это большой проект Гизмо в Джанктауне. Он приносит городу много денег и туристов, но и разных проблем немало.}
{1129}{}{У Киллиана неплохой магазин в Джанктауне.}
{1130}{}{Извини, дружище. Не знаю.}
{1131}{}{Извини, дружище. Не знаю.}
{1132}{}{Извини, дружище. Не знаю.}
{1133}{}{Извини, дружище. Не знаю.}
{1134}{}{Извини, дружище. Не знаю.}
{1135}{}{Ну да, в Шэйди Сэндс имеются дети, и что? Моих среди них все равно нет.}
{1136}{}{Извини, дружище. Не знаю.}
{1137}{}{Извини, дружище. Не знаю.}
{1138}{}{Извини, дружище. Не знаю.}
{1139}{}{Извини, дружище. Не знаю.}
{1141}{}{Знаешь, у нас всегда будет какая-нибудь война. Просто следующая будет на палках.}
{1142}{}{Я видал много необычного, пока охранял караваны для Ёаба. Мутировавшие койоты,  мантиссы, скорпионы и так далее.}
{1143}{}{Извини, дружище. Не знаю.}
{1144}{}{Это группа рейдеров, которая атакует Шэйди Сэндс и думает завоевать мир или по крайней мере что-нибудь вроде того.}
{1145}{}{Она дочка Арадеша. Она очень хороша, но меня кое-кто ждет дома.}
{1146}{}{Извини, дружище. Не знаю.}
{1147}{}{Извини, дружище. Не знаю.}
{1148}{}{Извини, дружище. Не знаю.}
{1149}{}{Извини, дружище. Не знаю.}
{1150}{}{Извини, дружище. Не знаю.}
{1151}{}{Пиво есть?}
{1152}{}{Я использовал Психо однажды, когда на караван напали. У меня это вызвало судороги. Странно.}
{1153}{}{Сет - капитан охранников. Между нами говоря, он не смог бы охранить даже корзину фруктов, поставленную между ног.}
{1154}{}{Арадеш - лидер Шэйди Сэндс. Очень добрый и спокойный человек, хотя и одинокий.}
{1155}{}{Если тебе нужна помощь, обязательно поговори с Разло. Он классный доктор.}
{1156}{}{Извини, дружище. Не знаю.}
{1157}{}{Извини, дружище. Не знаю.}
{1158}{}{Извини, дружище. Не знаю.}
{1159}{}{Извини, дружище. Не знаю.}
{1160}{}{Извини, дружище. Не знаю.}
{1161}{}{Извини, дружище. Не знаю.}
{1162}{}{Не знаю. Что-то в этом есть, конечно, но свидетельств еще не достаточно для серьезной разборки.}
{1163}{}{Извини, дружище. Не знаю.}
{1164}{}{Извини, дружище. Не знаю.}
{1165}{}{Торговцы приходят иногда из Ёаба торговать в Джанктаун. Это все, что я знаю.}
