{101}{}{У торговцев в караване не было шансов. Они все мертвы.}
{102}{}{Похоже, мутанты были вооружены до зубов. У караванщиков не было спасения от
 такой огневой мощи и ударного снаряжения.}
{103}{}{Они мертвы.}
{104}{}{Ты не сомневаешься, что это труп.}
{105}{}{Сквозь эту мутировавшую гору мяса проглядывают странно знакомые черты. Это один из не
 вернувшихся разведчиков, отправленных из Ёранилища до тебя...}
{106}{}{В горе мутировавшего мяса и мускулов ты можешь разглядеть одного из разведчиков,
 парня по имени Шон, отправленного из Ёранилища несколько месяцев тому назад,
 еще до тебя.}
{107}{}{Все мутанты мертвы, но один кого-то сильно напоминает, правда, его 'лица'
 различить не удается.}
{108}{}{Мертвые мутанты.}
