{100}{}{Чего вам от меня надо?}
{101}{}{Ваши охранники сказали, у вас есть для меня работа.}
{102}{}{Мне не нравится твое отношение, старикан.}
{103}{}{Ничего.}
{104}{}{Флуууп.}
{105}{}{Все может быть . . . . Не приходилось ли вам раньше иметь дело с жестокой 
бандой воров и убийц?}
{106}{}{Не продолжайте дальше. У вас проблема с разборками.}
{107}{}{А, ничто не ново под луною. Где сейчас в нашей пустыне найдется 
хоть один город без проблемы с бандами.}
{108}{}{Приходилось иметь дело.}
{109}{}{Эээ . . . вы и раньше участвовали в бандитских разборках?}
{110}{}{Нууу . . . можно и так сказать.}
{111}{}{В чем ваша проблема, старикан. Выкладывай поживее, меня ждут другие дела.}
{112}{}{Нет, не бывало такого. И я не собираюсь менять традицию. Прощайте, сэр.}
{113}{}{Ёорошо, тогда вы знаете, каковы бандиты на самом деле - злобные и кровожадные. 
Боюсь, нам придется бороться с Лезвиями - одной из самых свирепых шаек округа. 
У нас скромный, тихий, богобоязненный городок, который всего лишь пытается
 выжить в тяжелых обстоятельствах, а эти . . . . чудовища . . . охотятся за
 нами . . . . [он шепчет пониженным тоном] и нашими детьми . . .}
{114}{}{Да, да, все это замечательно, в смысле, ужасно. Сколько будет стоить моя
 работа и как действовать?}
{115}{}{Что вы имеете в виду под - охотятся за вами?}
{116}{}{Почему бы вашим охранникам не заняться охотой за ними и покончить с этим?}
{117}{}{Регуляторы спасают нас от полномасштабной войны с этими мерзавцами, но 
больше они ничего сделать не в состоянии, не подвергая риску мирную жизнь
 города. А Лезвия пытаются пробраться к нам по ночам, убивают наших сограждан и 
похищают наших детей . . . а после этого . . .
 [он останавливается, чтобы собраться с мыслями, перед тем, как продолжить] 
На прошлой неделе один из них прорвался за городскую стену с привязанным к 
телу зарядом динамита и побежал к баракам Регуляторов, чтобы их подорвать и 
тем самым лишить нас последней защиты и подготовить генеральный штурм города.}
{118}{}{И что с ним случилось?}
{119}{}{Выглядит слишком уж драматично, не так ли?}
{120}{}{К счастью, наши смелые защитники прикончили его до того, как он успел нанести 
кому-нибудь серьезный ущерб. Я сам видел труп.}
{121}{}{Понятно. И каковы будут ваши указания по этому поводу?}
{122}{}{Так вы не видели этого парня с зарядом динамита своими глазами, пока 
он был жив?}
{123}{}{Я даю две тысячи монет за убийство их предводительницы. Мне нужна голова
 этой стервы!}
{124}{}{У вас с ней, видимо, чрезвычайно натянутые личные отношения.}
{125}{}{Почему только главаря?}
{126}{}{Звучит как хорошая сделка.}
{127}{}{Без нее они быстро впадут в ничтожество . . . . без нее и ее тлетворного
 влияния.}
{128}{}{Она, наверное, классная девчонка.}
{129}{}{Ёватит пустых разговоров. Я сделаю это.}
{130}{}{Ухх, правильно. Не собираюсь быть частью этого маразма.}
{131}{}{По ее приказу был похищен мой сын, затем его пытали, а потом убили. 
Его обезображенный труп насадили на кол перед воротами города.}
{132}{}{Шизанутые ублюдки . . . . Я берусь за эту работу.}
{133}{}{Вряд ли после всего услышанного мне захочется воевать с ними.}
{134}{}{Слава Богу. Наконец-то мой сын будет отомщен. Лагерь Лезвий 
находится к северу отсюда. Возвращайтесь, когда дело будет сделано,
 и получите награду.}
{135}{}{Все происходило посреди глухой ночи, пока я спал, да и другие жители тоже. 
Но Регуляторы не дремлют. Впрочем, обычно они перехватывают этих вандалов 
на подходе к городу, не допуская их внутрь.}
{136}{}{Да, очень удачно получается. И весьма удобно для заинтересованных сторон.}
{137}{}{Мне не нравится, как звучит эта история. Не собираюсь ввязываться не в свое
 дело.}
{138}{}{Тогда прочь с глаз моих! Если ты не собираешься помогать Адитуму, наш город
 не нуждается в тебе!}
{139}{}{У меня нет времени для выслушивания идиотов. Прощайте.}
{140}{}{Если бы вы помогли мне решить проблему с Лезвиями, я игнорировал бы это 
нелепое замечание.}
{141}{}{Какую такую проблему?}
{142}{}{Имеется в виду ваша старость и тупость?}
{143}{}{Не приходилось ли вам раньше иметь дело с жестокой бандой воров и убийц?}
{144}{}{Не продолжайте дальше. У вас проблема с разборками.}
{145}{}{А, ничто не ново под луною. Где сейчас в нашей пустыне найдется 
хоть один город без проблемы с бандами.}
{146}{}{Приходилось иметь дело.}
{147}{}{Ну почему все время я? Спасаю города, освобождаю людей, прямо как паладин
 какой-то! Смешно!}
{148}{}{Приятно было бы разделаться с ними раз и навсегда, чтобы они не оскверняли
 нашу землю своим присутствием!}
{149}{}{Позвольте, я угадаю - вы хотите, чтобы они умерли.}
{150}{}{Что от меня требуется?}
{151}{}{Кругом творятся великие дела, а мне о них ничего не известно. Я собираюсь 
уходить, не задерживайте меня.}
{152}{}{Как? Это снова вы? Зачем вы снова заявились ко мне?}
{153}{}{Мне пришло в голову, что на сей раз вашу работу можно взять.}
{154}{}{Мне не нравится твое отношение, старикан.}
{155}{}{Просто так.}
{156}{}{[Он подозрительно смотрит на вас] . . . Лагерь Лезвий находится к северу
 отсюда. Возвращайтесь, когда выполните свое задание, и получите две тысячи
 монет.}
{157}{}{Почему вы до сих пор не разобрались с этим делом?}
{158}{}{У меня появились идеи.}
{159}{}{Я работаю над заданием.}
{160}{}{Эй, старикан, не приставай ко мне.}
{161}{}{Работай побыстрее. И не приходите сюда, пока ее презренная жизнь не 
подойдет к бесславному концу!}
{162}{}{Вы сделали свое дело?! Она мертва? Ведь так, правда?}
{163}{}{Тебе нужна медицинская помощь, старикан. Да, она мертва.}
{164}{}{Разумеется. Она сильно помучилась перед смертью - в качестве личного вам
 одолжения.}
{165}{}{Да.}
{166}{}{Слава Богу!!! Вот, берите ваши деньги. В Адитуме вас всегда будут встречать
 с распростертыми объятиями, дитя мое.}
{167}{}{Наконец-то она познакомится с адским пламенем! Да пребудет с вами благословение 
божье, дитя мое. [Он утирает слезу] Получите пятьсот монет дополнительно за 
приложенный творческий подход. Всегда рад буду вас видеть в Адитуме.}
{168}{}{Вы сделали свое дело?! Она мертва? Ведь так, правда?}
{169}{}{Успокойся, старикан, сядь и выслушай меня. У нас есть одна 
хорошая тема для обсуждения по поводу работы.}
{170}{}{Мне хотелось бы рассказать вам кое-что.}
{171}{}{Достаточно глупых отговорок и наглой лжи! Так она жива или нет?!}
{172}{}{Вот, послушайте это.}
{173}{}{[Пока он слушает запись на голодиске, его лицо медленно проясняется и по нему 
разливается блаженное, умиротворенное выражение]. 
Я перебью вас всех до единого, проклятые ублюдки!}
{174}{}{Скотина! По твоим стопам в наш общий дом пришли демоны разрушения!}
{175}{}{Вы видите человека средних лет в гражданском костюме.}
{176}{}{Вы видите Джона Циммермана, мэра города Адитума.}
{177}{}{Да-да, я вас внимательно слушаю.}
{178}{}{У меня есть кое-какая информация по поводу вашего погибшего сына.}
{179}{}{Нет, ничего.}
{180}{}{Блорб.}
{181}{}{Кто вы и откуда?}
{182}{}{Меня зовут Джон Циммерман, около сорока лет меня избирают здешним мэром. А что?}
{183}{}{Ёэлло.}
{184}{}{Приятно увидеться с вами.}
{185}{}{Спасибо за вашу помощь.}
{186}{}{Теперь мой сын почиет в мире.}
{187}{}{Мой сын отомщен.}
