{100}{}{Вы видите собаку. Похоже, она следует за вами.}
{101}{}{Вы видите собаку.}
{102}{}{Арфф!}
{103}{}{Грр!}
{104}{}{Вы получили 100 очков опыта за помощь несчастному Филу с его собачьей проблемой.}
{105}{}{Похоже, вы подружились с этой симпатичной собачкой.}
{106}{}{Видимо, собака думает, что вы ее хозяин.}
