{100}{}{Вы видите усталого путешественника.}
{101}{}{Вы видите Лэнса, одного из гвардейцев дальних патрулей Шэйди Сэндс.}
{102}{}{ Лучше стой, где стоишь. Мы о тебе уже наслышаны и не желаем иметь
 с тобой ничего общего.}
{103}{}{Единственное, что мне в тебе нравится - это твоя одежда. Раздевайся.}
{104}{}{Я человек мирный, дружище.}
{105}{}{Эй! Разве это не я спас Танди и перебил ваших Рад Скорпионов?}
{106}{}{Я ничего не имею против Шэйди Сэндс. Мне они даже нравятся.}
{107}{}{Чавось???}
{108}{}{Я о тебе слышал, и я не позволю тебе убить меня.}
{109}{}{Мне с тобой не о чем говорить.}
{110}{}{Н-да? Что тебе надо на этот раз?}
{111}{}{Ты не знаешь, где я могу найти водяной фильтр?}
{112}{}{О Танди ничего не слышно?}
{113}{}{У вас были какие нибудь неприятности с рейдерами?}
{114}{}{Как идут дела в Шейди Сэндс?}
{115}{}{Зашибись!}
{116}{}{Привет, незнакомец. Как ты оказался в пустыне? Откуда путь держишь?}
{117}{}{Я могу спросить тебя о том же самом.}
{118}{}{Прости, друг, но у меня такое впечатление, что на этот вопрос 
 отвечать небезопасно.}
{119}{}{Ты не знаешь, где можно раздобыть припасов?}
{120}{}{Я из Ёранилища. Счастливого Ёранилища 13!}
{121}{}{Вах-Вах-Вах!?}
{122}{}{Привет, незнакомец. Если тебе есть, чем заняться - мой тебе совет :
 ступай своей дорогой.}
# TRANSLATION NOTE
# After	line 123, the player-character's name is inserted by the code, and
# then line 124	or line	131 is added.
{123}{}{Привет, }
{124}{}{. Когда ты спас Танди, я стал считать тебя другом. Но в последнее время
 о тебе стали ходить всякие грязные слухи. Они правдивы?}
{125}{}{Мало ли, чего там люди болтают... Кого это волнует?}
{126}{}{Я тебе не друг. И не делай резких движений - кишки выпущу. Усек?}
{127}{}{Какие такие слухи?}
{128}{}{Точно. Все истинная правда. Ты, кстати, раздевайся - я у тебя кое-что позаимствую.}
{129}{}{Ну, я, может, и сделал пару вещей, о которых теперь жалею, но уж тебе-то
 стоило бы самому понять, что к чему.}
{130}{}{Я рад, что это ты, а не бандит какой-нибудь! Как жизнь? Я Лэнс, гвардеец из
 Шэйди Сэндс. Прости, что мы тебя так приняли в первый твой визит!}
{131}{}{Привет, Ленс! Что новенького?}
{132}{}{Привет, Ленс. Обычно я, конечно, белый и пушистый, но суровая жизнь
 ожесточила мою ранимую душу. Короче говоря, раздевайся и складывай пожитки.}
{133}{}{Не обращай внимания, Ленс. Что ты здесь делаешь один?}
{134}{}{Прекрасно. Но я это запомню.}
{135}{}{Твое.}
{136}{}{Избавь меня от своих нелепых угроз. Таких, как ты, я на бутерброд
 намазывал и с маслом ел. Отдавай свои пожитки и останешься цел.}
{137}{}{Если ты и впрямь считаешь меня врагом, просто убей меня.}
{138}{}{Я все-таки сделаю пару резких движений. Мне всегда хотелось посмотреть, какого цвета моя кровь.}
{139}{}{Так то тогда, а это сейчас. Сейчас ты для нас ничего полезного не делаешь.
 По-моему, тебе стоит катиться отсюда, пока я не утомился.}
{140}{}{Нам тоже нравится. Особенно, когда тебя нет рядом. Проваливай!}
{141}{}{Парень, ты, должно быть, на солнце перегрелся!}
{142}{}{Прости, я не знаю, что это за водяной фильтр...}
{143}{}{Это электронный прибор, применяемый в очистных сооружениях.}
{144}{}{Как там без меня Рад Скорпионы?}
{145}{}{Ее похитили рейдеры. Я вхожу в одну из поисковых групп. Я думаю,
 она в лагере рейдеров южнее Шэйди Сэндс, но Ёаны укрепили это место
 не хуже иной крепости.}
{146}{}{Ты можешь провести меня в Шэйди Сэндс?}
{147}{}{Ты можешь провести меня к Ёанам?}
{148}{}{Нам надо придумать, как вызволить ее.}
{149}{}{Спасибо за информацию. Счастливых поисков!}
{150}{}{Ну, да. С тех пор, как Ёаны получили по не в меру длинному носу
 нам стало гораздо легче жить. Я так понимаю, что за это стоит благодарить тебя. Мы очень признательны.}
{151}{}{Я бы не отказался от небольшой, но веской признательности.}
{152}{}{Спасибо. Вам еще нужна моя помощь?}
{153}{}{Еще сунутся - дай мне знать.}
{154}{}{У нас все хорошо.}
{155}{}{Ты абсолютно уверен?}
{156}{}{Это здорово.}
{157}{}{Я понятия не имею. Идиот.}
{158}{}{Ёорошо, я поверю тебе. Я из Шэйди Сэндс. Это поселение недалеко отсюда.}
{159}{}{Ты можешь провести меня туда?}
{160}{}{И на что это похоже?}
{161}{}{Там есть водяные фильтры?}
{162}{}{Звучит отлично.}
{163}{}{Ёорошо. Ты хранишь свои секреты - я свои. Пока.}
{164}{}{Может, оно и к лучшему. Но вообще жаль, конечно.}
{165}{}{Я был в Джанктауне. По-моему, это к юго-западу, но после стольких дней
 пути я запросто могу и ошибаться.}
{166}{}{Ну да, точно. Насколько мне известно, все Ёранилища уничтожены. Говори дальше.}
{167}{}{Это не то, о чем я просил... О, не беспокойся!}
{168}{}{Это не ответ. Говорят, ты вор, убийца и мародер. Говорят, ты убиваешь
 всех на своем пути. Это правда?}
{169}{}{Ну, судя по всему, что я тебя я пока не убил, кто-то явно врет.}
{170}{}{Точно. И в моей жизни бывали светлые моменты.}
{171}{}{Я наделал кучу врагов. И оставил в живых достаточно, чтобы кто-то из них меня
 оклеветал.}
{172}{}{Ну да, прикончил парочку. Так у меня всегда был повод.}
{173}{}{Тебя называют убийцей, вором и мародером. Говорят, ты убиваешь всех на своем
 пути. Это действительно так?}
{174}{}{Ёорошо, я это сделаю. Но если ты продолжишь вести себя по-бандитски,
 как бандит и подохнешь.}
{175}{}{Я позволю тебе посомневаться. но человек хорош ровно настолько,
 насколько хороша его репутация - а над твоей еще работать и работать.
 Надеюсь, ты предпримешь что-нибудь по этому поводу до следующей нашей встречи.}
{176}{}{Просто возвращаюсь в город. Ты собираешься идти один? Я бы не отказался от компании!}
{177}{}{Конечно.}
{178}{}{В другой раз.}
{179}{}{Немного помародерствовали. Мы обнаружили несколько заброшенных бандитских лагерей;
 подозреваю, что они нападали друг на друга. А нам никогда не повредят
 лишние патроны и медикаменты.}
{180}{}{Я жалею об этом.}
{181}{}{Прочь с глаз моих, пока я не передумал.}
{182}{}{Мы видели еще нескольких - должно быть, мигрируют из пустыни или Свечения.
 Но их уже значительно меньше, чем в прошлом году - благодаря тебе.}
{183}{}{Звучит неплохо. Пока.}
{184}{}{Конечно. Пошли.}
{185}{}{Знаешь, я, наверное, свихнулся. Но я возьму тебя с собой. Пошли.}
{186}{}{Приятного самоубийства, друг. Чего бы ты этим ни добивался - удачи!}
{187}{}{Я отчаливаю. Будь осторожен.}
{188}{}{Ну, у меня есть не так уж и много - но все имеющееся принадлежит тебе.}
{189}{}{Никаких мыслей в голову не приходит. Я сваливаю. Будь осторожен.}
{190}{}{Постараемся. Я ухожу. Будь осторожен.}
{191}{}{Ну, хорошо. Пошли.}
{192}{}{Я не поведу к своему дому возможного врага. Если ты доберешься до Шэйди Сэндс,
 держи ухо востро.}
{193}{}{Крохи. Мы существуем за счет разведения Брам и получаемых товаров.
 А рельеф там весьма крут, так что пастбищ довольно мало.}
{194}{}{Среди пастухов? Ты с ума сошел! Да здесь в радиусе двухсот миль
 ни одного исправного электронного прибора не сыщется!}
{195}{}{Прямо в цель. Я думаю, нам стоит поостеречься и идти порознь.
 На твоем месте я бы предпринял что - нибудь по поводу всех этих сплетен.
 Кому понравится, что люди ненавидят и не доверяют ему.}
{196}{}{Мне стоило бы убить тебя прямо сейчас, но я подожду - до следующего раза. А теперь убирайся!}
{197}{}{Пошли.}
{198}{}{Позволь, я догадаюсь - кто-то рассказал тебе о моем храпе.
 Ну вот и хорошо. Будь осторожен.}
{199}{}{Точно. Ну, я пошел отсюда. Будь осторожен.}
{200}{}{Стой, где стоишь. Не знаю, не снюхался ли ты с этими погаными мутантами,
 но учти - узнаю, убью.}
{201}{}{Какими мутантами?}
{202}{}{Кто ты?}
{203}{}{Что с тобой случилось?}
{204}{}{Ёорошо, ладно...}
{205}{}{Эге-ге?}
{206}{}{Мутанты заполонили Шэйди Сэндс. Они перебили почти всех.
 По-моему, рано или поздно они достанут и нас. Это просто вопрос времени.}
{207}{}{Говори, что хочешь, спрашивай, о чем хочешь. Мы все подохнем! Ну ничего!
 Я-то думал, рейдеры и Рад Скорпионы это проблема... Это чушь собачья!
 Ёа! Ёа ха ха!!!}
{208}{}{Заткнись! Я не желаю разговаривать! Разговорами делу не помочь!
 Они будят во мне зверя...}
