{100}{}{выкл.}
{101}{}{Времени осталось:  }
{102}{}{ секунд.}
{103}{}{После этого вас можно будет спокойно считать мертвецом.}
{104}{}{выкл.}
{105}{}{вкл.}
{106}{}{выкл.}
{107}{}{Времени осталось:  }
{108}{}{ секунд.}
{109}{}{После этого вас можно будет спокойно считать мертвецом.}
{110}{}{Времени осталось:  }
{111}{}{ секунд.}
{112}{}{После этого вас можно будет спокойно считать мертвецом.}
