{100}{}{Я не могу поверить во все приписываемые вам злодеяния.}
{101}{}{Мне наплевать. У меня есть раны. Вылечи меня.}
{102}{}{Ёнгх!}
{103}{}{Нет. Я давал клятву ни в коем случае не вредить жизни, но вам я помогать не буду.}
{104}{}{Отсутствие интеллекта не является оправданием для преступных акций. Подите прочь, я больше не собираюсь с вами разговаривать.}
{105}{}{О боже, да вы серьезно ранены. Позвольте, я помогу вам.}
{106}{}{Добро пожаловать, }
{107}{}{. Как продвигаются ваши поиски?}
{108}{}{Все в полном порядке.}
{109}{}{Мне нужна помощь.}
{110}{}{Лол?}
{111}{}{Ах, да. У меня тут завалялась парочка интересных вещиц. Используйте их, когда вам понадобится поддержка.}
{112}{}{Ёорошо, продолжайте свою отличную работу. И дайте мне знать, если добъетесь положительных результатов.}
{113}{}{Что вам от меня нужно?}
{114}{}{Я нуждаюсь в исцелении.}
{115}{}{Мне хочется попробовать наркотики.}
{116}{}{Мне требуются дополнительные стимпаки.}
{117}{}{Дох!}
{118}{}{Дах!}
{119}{}{У меня нет полномочий рапоряжаться общим имуществом.}
{120}{}{Все равно спасибо.}
{121}{}{Но они мне требуются срочно. Без них судьба Ёранилища находится в смертельной опасности.}
{122}{}{Извините, но я не могу вам их выдать.}
{123}{}{Ну, если вы так поворачиваете дело, берите. Никому не рассказывайте, что это я вам дал. Они чрезвычайно опасны и вызывают привыкание при постоянном употреблении.}
{124}{}{Спасибо.}
{125}{}{Стимпаки выдаются строго по норме. Вы можете брать все необходимое из медицинского контейнера на стене. Там хранится весь наш запас на некоторое время. Используйте его экономно, неизвестно, сколько пройдет дней, прежде чем он будет возобновлен.}
{126}{}{Ёмм. Давайте посмотрим, что с вами случилось.}
{127}{}{У вас нет никаких серьезных повреждений. Возвращайтесь, когда поранитесь.}
{128}{}{У вас есть несколько ранений. Позвольте вам помочь.}
{129}{}{В любое время, когда вы страдаете от ран, приходите сюда или используйте один из нашеих стимпаков. Они хранятся в контейнере на стене.}
{130}{}{Укладывайтесь вот сюда, и мы начнем процесс излечения.}
{131}{}{Вы полностью излечились. В будущем поберегите себя, не подставляйтесь по глупому. Возвращайтесь сюда, когда захотите подлечиться. }
{132}{}{Медицинские сканнеры сообщают о наличии у вас почти смертельного лучевого поражения. Вы будете пытаться вылечиться? Это наверняка займет много времени.}
{133}{}{Медицинские сканнеры сообщают о наличии у вас сильного лучевого поражения. Вы будете пытаться вылечиться? Это наверняка займет много времени.}
{134}{}{Медицинские сканнеры сообщают о наличии у вас серьезного лучевого поражения. Вы будете пытаться вылечиться? Это наверняка займет много времени.}
{135}{}{Медицинские сканнеры сообщают о наличии у вас некоторого лучевого поражения. Вы будете пытаться вылечиться? Это наверняка займет много времени.}
{136}{}{Вы видите медика из Ёранилища-13.}
{137}{}{}
{138}{}{Нет.}
{139}{}{Ёорошо, действуйте.}
{140}{}{Сколько именно?}
{141}{}{Сколько времени это займет, и как эффективен предлагаемый вами курс лечения.}
{142}{}{Наа.}
{143}{}{Йаа.}
{144}{}{Это ваша жизнь.}
{145}{}{Это займет около }
{146}{}{ минут. Считаете ли вы, что пора приступать к излечению?}
{147}{}{Нет.}
{148}{}{Да.}
{149}{}{Это займет около }
{150}{}{ минут. Уровень поражения радиацией снизится на }
{151}{}{ процентов. Итак, давайте приступим к началу излечения?}
{152}{}{Нет.}
{153}{}{Да.}
{154}{}{Потерпите немного, сейчас вам будет очень, очень больно.}
{155}{}{Подождите и не волнуйтесь, это совсем не больно.}
{156}{}{Теперь вам должно стать гораздо легче. Постарайтесь в дальнейшем быть поосторожнее.}
{157}{}{Я слышал о ваших подвигах и спасении вами Ёранилища. Большое спасибо.}
{158}{}{[Далее]}
{159}{}{Медик отказывается с вами разговаривать.}
{160}{}{Не делайте этого, прошу вас.}
# Medic tell-me-abouts
{1000}{}{Медик}
{1001}{}{Лечение}
{1100}{}{Я постоянно нахожусь здесь, предоставляя исцеление страждущим.}
{1101}{}{Когда вы поранитесь, я буду вас лечить.}
