{100}{}{Вы видите Мефисто, раздраженного торговца.}
{101}{}{Вы видите торговца по имени Ёармс.}
{102}{}{Вы видите расстроенного торговца Фаулера.}
{103}{}{Вы видите печального торговца Диксона.}
{104}{}{Перед вами торговец Морган.}
{105}{}{Перед вами бывалый торговец Марко.}
{106}{}{Вы видите торговца Кьелльнира.}
{107}{}{Перед вами торговец Марцен.}
{108}{}{Вы видите расстроенного торговца Джошуа.}
{109}{}{Перед вами торговец Энтони.}
{110}{}{Перед вами торговец Кларк.}
{111}{}{Вы видите торговца по имени Малантик.}
{112}{}{Перед вами неистовый торговец Орландо.}
{113}{}{Вы видите известного торговца Илью.}
{114}{}{Перед вами Трэйси.}
{115}{}{Как может твориться подобный беспредел?}
{116}{}{В очередь, граждане.}
{117}{}{Вы не из нашей конторы.}
{118}{}{Ваш караван тоже задержали эти придурки?}
{119}{}{Желаю удачи, ибо она вам понадобится.}
{120}{}{Вы уже говорили с Ёайтауэром?}
{121}{}{На вашем месте надо обратиться в торговую компанию Фаргус.}
{122}{}{Ищете главного торговца? Вон она, пройдите туда, чуть подальше.}
{123}{}{Если груз не будет отправлен сегодня же, я потеряю кучу денег.}
{124}{}{Марта стоит вон там.}
{125}{}{Вы не торговец, это сразу видно.}
{126}{}{Бараки охранников находятся на другой стороне.}
{127}{}{Отвали от меня, я по таким дням не подаю.}
{128}{}{Кругом сплошное просадительство.}
{129}{}{Даже и не думайте забраться на мою территорию.}
{130}{}{Почему мой груз до сих пор не отправлен?}
{131}{}{Где припасы для путешествия?}
{132}{}{Ваши цены меня с ума сведут!}
{133}{}{Где, наконец, Ёайтауэр?}
{134}{}{У меня должен быть приоритет!}
{135}{}{Мой груз опаздывает на две недели!}
{136}{}{Я требую вернуть мне деньги!}
{137}{}{Мне нужно поговорить с Ёайтауэром.}
{138}{}{Я собираюсь обратиться в Кримсон Караван.}
{139}{}{Какого черта вы здесь делаете?}
{140}{}{Я слишком устал ждать!}
{141}{}{Ёватит глупых отмазок!}
{142}{}{Мой груз важнее всей этой хреновины!}
{143}{}{Чего тут непонятного, придурки?}
{144}{}{Или вы начинаете работать - или я ухожу!}
