{100}{}{Вы видите грязного, помятого арестанта.}
{101}{}{Один из заключенных во второй камере не похож на всех остальных. Он стоит 
прямо и глядит вам в глаза, не отводя взгляда.}
{102}{}{Заключенный тупо уставился на стену своей камеры.}
{103}{}{Заключенный не обращает внимания на ваши попытки заговорить с ним.}
{104}{}{Он дико пялится на вас несколько секунд, потом отворачивается в сторону.}
{105}{}{Она смотрит на вас несколько мгновений, а потом плюется.}
{106}{}{Вы не получаете ответа.}
{107}{}{Мы свободны! Мы свободны!}
{108}{}{Существа вашего типа отвратительны. Не пытайтесь заговорить со мной.}
{109}{}{Квиб!}
{110}{}{Вы не имеете права так обращаться со мной! Я буду жаловаться консулу!}
{111}{}{Вы меня не поняли. Я здесь, чтобы принести вам волю!}
{112}{}{Не глумитесь надо мной.}
{113}{}{У меня нет прав, и на это мне больше всего наплевать. Отвали, и оставь нас в покое.}
{114}{}{Я отказываюсь разговаривать в отсутствие консула и представителей прессы!}
{115}{}{Ённг!!}
{116}{}{На самом деле я хочу принести вам волю! Я такой же человек, как все вы.}
{117}{}{Как хотите. Вольному воля, блаженному рай. До свидания.}
{118}{}{Вы что, не помните, как пробовали на мне этот грязный трюк неделю назад? 
У вас совсем слабая фантазия, и я не попадусь на ваши уловки.}
{119}{}{Ваша предательская сущность теперь для меня ясна. Не пытайтесь снова обмануть меня.}
{120}{}{Я здесь, чтобы принести вам волю!}
{121}{}{Тогда до свидания.}
{122}{}{Какая жестокость. Оставьте нас в покое.}
{123}{}{Я ничего не скажу вам, палачи, сатрапы Повелителя! Вихри враждебные веют над нами! 
Темные силы нас злобно гнетут! В бой роковой мы вступили с врагами...}
{124}{}{Нет, вы не понимаете, о чем я вам толкую. Я человек, я собираюсь спасти вас.}
{125}{}{Мне не придется даже принуждать вас гореть в аду. Вы сами себе создаете достаточно 
неудобств.}
{126}{}{Вы все еще глумитесь надо мной.}
{127}{}{Вам не удастся перехитрить меня! Я не куплюсь на эту дешевую уловку.}
{128}{}{Да уж, я догадываюсь. Подите прочь и оставьте нас в покое.}
{200}{}{Заключенный выглядит уставшим и немытым. Однако галстук у него на шее почему-то 
новый и блестящий.}
{201}{}{Арестант смотрит на вас ничего не выражающим взглядом. У него на шее вы 
замечаете галстук.}
{300}{}{Надпись на стене гласит - Проход Запрещен. Только для надзирателей. 
Внимание - опасная Зона работает!}
{301}{}{Вы получаете }
{302}{}{ очков опыта за вызволение несчастных узников из застенков Повелителя.}
