{100}{}{Вы видите охранника.}
{101}{}{Чего тебе тут понадобилось?}
{102}{}{Урр?}
{103}{}{Я так, случайно вокруг брожу.}
{104}{}{Мне хотелось бы купить оружие.}
{105}{}{}
{106}{}{}
{107}{}{У меня не хватает терпения выслушивать тупой юмор. Проваливай, да поживее, а не то стрелять буду!}
{108}{}{Нам не нравятся слишком любопытные люди. Иди отсюда, и я не выстрелю.}
{109}{}{}
{110}{}{}
{111}{}{От тебя воняет, как от брамы, но интеллекта не хватит даже и на крысса.}
{112}{}{}
{113}{}{Ахх, очень хорошо. Добро пожаловать, уважаемый покупатель. Входите, но не забудьте убрать оружие подальше. Отправляйтесь прямиком к Заку, он расскажет вам все необходимое.}
{114}{}{}
{115}{}{Мне обязательно надо поговорить со здешним боссом. Это очень важно.}
{116}{}{Ну, ладно. Сейчас Габриель поговорит с тобой. Проходи.}
{117}{}{Да, я припоминаю тебя. Проходи.}
{118}{}{Мне надо поговорить с Габриелем, и поскорее. Это очень важно.}
{119}{}{Мне хотелось бы купить оружие у Зака.}
