{100}{}{Вы видите сломанного робота.}
{101}{}{Вы видите работающего робота.}
{102}{}{Вы починили сломанного робота. Весело замигали лампочки, заскрежетали шарниры и робот начал двигаться.}
{103}{}{Починка требует слишком высокого для вас умения.}
