{100}{}{Дорога на север преграждена развалинами и грудами мусора. Вам придется
 отыскать другой путь.}
{101}{}{Дорога на юг преграждена развалинами и грудами мусора. Вам придется
 отыскать другой путь.}
{102}{}{Дорога на восток преграждена развалинами и грудами мусора. Вам придется
 отыскать другой путь.}
{103}{}{Дорога на запад преграждена развалинами и грудами мусора. Вам придется
 отыскать другой путь.}
{104}{}{Дорога вперед преграждена развалинами и грудами мусора. Вам придется
 отыскать подземный путь.}
