{100}{}{Вы видите никого иного, как самого Орфео, Старшего Члена Детей Собора.}
{101}{}{Ага. Новообращенный. Добро пожаловать.}
{102}{}{Убивайте!!!}
{103}{}{Я не новообращенный!}
{104}{}{Большое спасибо, Брат.}
{105}{}{Ну, как раз эту проблему мы разрешим быстро.}
{106}{}{Сначала мы очистим тебя от черного зла и всяких мерзостей пустыни. Приди.}
{107}{}{Мы очистим тебя!}
