{100}{}{Паладин}
{101}{}{Остановись, Посвященный!}
{102}{}{Ёорошо выглядишь. Продолжай работу.}
{103}{}{Здравствуй, Посвященный, все в безопасности.}
{104}{}{Привет, Брат }
{105}{}{.}
{106}{}{Извини, мне не следует ни с кем говорить. Ты знаешь, что это значит.}
{107}{}{Если у тебя появились вопросы, тебе следует поговорить с Талусом или Макссоном.}
{108}{}{Если у тебя вдруг появятся технические вопросы, Врее все время в библиотеке.}
{109}{}{Мой идол - это Ромбус.}
{110}{}{Ёотел бы я сейчас быть на тренировках. Это дежурство в страже - сплошная трата времени.}
{111}{}{Мой кумир - Врее.}
{112}{}{Марко!}
{113}{}{Поло!}
