{100}{}{Вы встретили человека в залатанном кожаном доспехе с ассортиментом старинных
 безделушек.}
{101}{}{Вы видите Патрика, Кельта.}
{102}{}{Приветствую, путешественник. Что принесло тебя в эти края?}
{103}{}{Дорога.}
{104}{}{Скажи лучше, а почему ты носишь с собой это старье?}
{105}{}{Мне необходимо отыскать водяной фильтр.}
{106}{}{Я убиваю всех, кто приближается ко мне на расстояние выстрела. Так что готовься к смерти.}
{107}{}{Тормоз!}
{108}{}{Ну да. Прямо как я.}
{109}{}{Ого? Да ты случайно не из одного из тамошних городков?}
{110}{}{Ты можешь меня направить к ближайшему поселению?}
{111}{}{А в чем же дело?}
{112}{}{Ну, пока.}
{113}{}{Это - не старье! Это то, чем я торгую!}
{114}{}{Ну ладно. Пока.}
{115}{}{Угу. Ну так в чем же дело?}
{116}{}{Гм-м. В жизни не встречал ничего подобного. У тебя какие-то проблемы?}
{117}{}{Этот фильтр контролирует чистоту воды в моем Ёранилище. Только он накрылся.}
{118}{}{Он сломан.}
{119}{}{Я странствую от места к месту, зарабатывая на жизнь частично мелкими ремонтами, 
а частично музыкой.}
{120}{}{Какую работу ты можешь делать?}
{121}{}{Какую музыку ты играешь?}
{122}{}{Я был рад тебя видеть. Пока.}
{123}{}{От береговой линии ты доберешься до Шэйди Сэндс примерно за неделю, идя вглубь, 
а оттуда в нескольких днях пути на юг находится Джанктаун. Еще парочка дней на 
юг от Джанктауна, и ты доберешься до Ёаба. От этих городов на востоке находится 
Некрополис. Вот его избегай. Не вали себе на голову лишние проблемы.}
{124}{}{Что тебе известно о Шэйди Сэндс?}
{125}{}{Что тебе известно о Джанктауне?}
{126}{}{Что тебе известно о Ёабе?}
{127}{}{Что тебе известно о Некрополисе?}
{128}{}{Я не думаю, что буду в состоянии тебе помочь. У меня никогда не было
 достаточной возможности изучить довоенную технологию Ёранилищ.}
{129}{}{В основном электрические и механические работы. Я помогал наладить освещение в 
Джанктауне и улучшил устройство печей людям из Шэйди Сэндс.}
{130}{}{В самом деле? А ты не мог бы починить водяной фильтр?}
{131}{}{В основном старые народные песни песни на кельтскую музыку. Смена ритма и все такое.}
{132}{}{Ты никогда не слышал "Песню об ирландской пасхе", или как она называется?}
{133}{}{Понятно. А чем еще ты занимаешься?}
{134}{}{Шэйди Сэндс - это маленькое самодостаточное общество, которое возглавляет 
Арадеш, добрый человек и серьезный лидер. Они люди мирные и работящие. Они, 
наверное, лучшее общество, которое способно создать здесь новую цивилизацию.}
{135}{}{Шэйди Сэндс - маленькое сообщество, которое занимается сельским хозяйством. 
Раньше его возглавлял хороший человек, по имени Арадеш, но я слышал, что он умер. 
Очень жаль. Я не знаю, смогут ли они выжить без него.}
{136}{}{Джанктаун? Небольшой торговый город. Странное место, пока не привыкнешь. 
Их возглавляет мэр Киллиан Даркуотер, человек с тяжелым характером, но справедливый.}
{137}{}{Джанктаун? Небольшой торговый город. Странное место, пока не привыкнешь. Их 
возглавляет Гизмо, аферист, бандит и глава всей преступности города.}
{138}{}{Джанктаун? Маленький торговый городок. Ничем не примечателен.}
{139}{}{Ёаб - это большой торговый центр. Говорят, там можно найти все, что угодно, хоть красную икру. 
Красной икры я там, конечно, не видел, но в остальном это не такое уж и вранье.}
{140}{}{Некрополис - это город живых трупов. Он населен мутантами - мертвяками, это
 потомки людей, которые во время войны пытались спастись в тамошнем Ёранилище.
 Как-то получилось так, что Ёранилище не выдержало, так что теперь город
 населяют только стервятники-монстры.}
{141}{}{Последнее, что я про него слышал, это то, что его завоевала армия монстров. 
На твоем месте я бы туда не ходил.}
{142}{}{Как ты думаешь, есть ли там в Ёранилище детали, которые мне могли бы
 пригодиться?}
{143}{}{Возможно, но я бы не стал лазить к мертвякам. Последнее, что я о них слышал -
 у них появился новый лидер с серьезными намерениями.}
{144}{}{А почему бы и нет? Ты хотел бы что-нибудь послушать?}
{145}{}{Безусловно.}
{146}{}{Нет.}
{147}{}{Вспомним Патрика Пирса и тех, кто ушел умирать - Тома Кларка, МакДанна, МакДармотт, МакБрайд.
 И споем про Джеймса Коннолли, что ура лишь успел прокричать и расставил пулеметы - британцев встречать.}
{148}{}{Привет еще раз. Чем могу служить?}
{149}{}{Да, можешь дать мне кое-какие указания?}
{150}{}{Нет, ничего особенного.}
