{100}{}{Вы видите: Обитателя Ёранилища.}
{101}{}{Вы видите: Расстроенного Обитателя Ёранилища.}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{Спасибо за спасение наших жизней.}
{106}{}{Я не был уверен, справишься ли ты, но теперь я тебе вполне доверяю.}
{107}{}{Спасибо! Спасибо!}
{108}{}{Твой героизм будет жить вечно! Мой маленький Бобби хочет быть похожим на тебя, когда вырастет. Я не знаю, нравится ли мне это.}
{109}{}{Твой героизм будет жить вечно! Мой маленький Бобби хочет быть похожим на тебя, когда вырастет. Я не знаю, нравится ли мне это.}
{110}{}{Ты крутой парень!}
{111}{}{Ты крутая девчонка!}
{112}{}{Ты уверен, что здесь это тебе нужно?}
{113}{}{Это же оружие!}
{114}{}{А тебе его вообще приходилось использовать против кого-нибудь?}
{115}{}{Почему ты думаешь, что по нашему Ёранилищу надо ходить с оружием наизготовку?}
{116}{}{Привет. Как идут поиски?}
{117}{}{Весьма недурственно.}
{118}{}{Не особенно хорошо.}
{119}{}{У-у-у!}
{120}{}{Ну, я полагаю.. я рад это слышать. Работай дальше. Все в порядке.}
{121}{}{Нет проблем.}
{122}{}{Мы знаем, надеяться нет смысла. Я не думаю, что мы достанем новый чип вовремя. Я уверен, кое-кому из нас следует отправиться наружу, пока не поздно.}
{123}{}{Мне это не кажется хорошей идеей.}
{124}{}{Гмм. Может быть, это будет наилучшим.}
{125}{}{Поторопись!}
{126}{}{Не бойтесь, люди, я найду вам фильтр.}
{127}{}{Наверное, тебе надо бы зайти на одно из наших собраний. У Терезы есть кое-какие хорошие идеи. Мы встречаемся в ее комнате каждый вечер в пять часов. Это на втором уровне.}
{128}{}{Я подумаю.}
{129}{}{Нет, спасибо. У меня много дел.}
{130}{}{Вот как считает Тереза. Она это все уже разработала, так что мы уже подумываем о том, чтобы покинуть Ёранилище.}
{131}{}{Удачи!}
{132}{}{Мне кажется, что уходить пока рано.}
{133}{}{Ну почему Смотритель выбрал именно тебя? Ведь ясно - ты не то что водяной фильтр, собственные шлепанцы вряд ли найдешь. Ой, извини.}
{134}{}{Ургхы.}
{135}{}{Тебе опять делать нечего? Иди искать фильтр! Быстро!}
{136}{}{Не давай мне ценные указания, ты, неудачник!}
{137}{}{Так. Ну и люди!}
{138}{}{Гдорф!}
{139}{}{Измена! Из-за тебя мы все подохнем в этой проклятой подземной могиле. Небось злорадствуешь, скотина!}
{1000}{}{Смотритель}
{1001}{}{Ёранилище13}
{1002}{}{Ёранилище-13}
{1003}{}{Ёранилище}
{1100}{}{Смотритель просто хочет держать всех здесь под контролем. Не обращая внимания на его потуги, мы смело двинемся вперед, заре навстречу.}
{1101}{}{Ёранилище было нашим домом, но оно не может больше держаться. Пора идти осваивать этот прекрасный новый мир.}
{1102}{}{Ёранилище было нашим домом, но оно не может больше держаться. Пора идти осваивать этот прекрасный новый мир.}
{1103}{}{Ёранилище было нашим домом, но оно не может больше держаться. Пора идти осваивать этот прекрасный новый мир.}
