{100}{}{Вы увидели Риччи.}
{101}{}{Ты не должен этого делать. Мне придется тебя остановить.}
{102}{}{Тебе не следует здесь быть. Ты понимаешь, что я должен тебя убить?}
{103}{}{Твое продвижение кончилось. Я иду тебя заменять.}
{104}{}{Инспектор Ёранилищ из Ёаба. Я пришел сюда согласно инструкции. Отойди в сторону.}
{105}{}{Детка, давай подеремся. Закончим здесь круг насилия!}
{106}{}{Кто это тебе сказал? Мистер, если ты атакуешь меня, это будет величайшая ошибка в твоей жизни!}
{107}{}{Привет, дитя. Что происходит в стальном хранилище?}
{108}{}{Слишком поздно, подонок. Ты труп.}
{109}{}{У! Ого! Ранк!}
{110}{}{Я не собираюсь трепаться с тобой! Катись отсюда!}
{111}{}{Это почти правда! Здесь горячо! Слишком скучно! Если бы мне не нужна была эта работа, чтобы кормить семью, я сказал бы Лоренцо - а иди ты. Увидимся завтра.}
{112}{}{Мне не следует уходить отсюда, а тебе не следует здесь появляться. Пошел вон!}
{113}{}{Вы, проклятые чиновники Ёаба, вы меня уже достали! Инспектируете хранилище моего начальства! А что дальше? Повышение налогов? Неужели нормальный человек уже не может честно заработать на жизнь без всяких там бюрократов, пытающихся урвать себе кусок от чего угодно? На днях мы собирались устроить вам кое-что! Да уж, когда-нибудь придет к вам обычный человек и врежет вам, толстопузам, по яйцам так, как вы и заслуживаете! Да, когда-нибудь мы вас хорошо сделаем. Жду не дождусь. Кстати, не принимайте это близко к сердцу. Я так, к слову сказал.}
{114}{}{Не неси чепуху! Убирайся немедленно, а то я тебя пристрелю как собаку!}
{115}{}{О да? Знаешь, пока еще никто, кто пытался помыкать Ричи Глоустэдером, не уходил отсюда живым!}
{116}{}{Ну, всего лишь около десяти тысяч монет. Я надеюсь, ты не станешь подумывать о том, чтобы их стащить. Мне придется тебя убить. Я чуть не убил кое-кого еще, так что не связывайся со мной.}
{117}{}{Слушай, ты дурак. Ой, извини, не хотел обидеть. Давай попробуем еще раз. "Да" означает, что я вышибу из тебя мозги. "Нет" означает, что ты сваливаешь отсюда. Итак, ваш выбор, милостивый государь?}
{118}{}{А.. да...}
{119}{}{У.. нет.}
{120}{}{Ранк! Ранк!}
{121}{}{Черт возьми! Это просто невероятно! Все равно, что курицу расстреливать! Вали отсюда, слышишь?}
{122}{}{Это хорошо. Теперь иди. Я уверен, что ты мог бы найти кого-нибудь еще, а затем съесть.}
{123}{}{Так.. Наверно, просто "ранк" означает "да", а "ранк, ранк" означает нет. Ну ладно. Один "ранк" - я тебя убью. Два "ранк" - ты уходишь. Ну?}
{124}{}{Ранк}
{125}{}{Ранк, ранк.}
{126}{}{Ранк, ранк, ранк!}
{127}{}{Три раза "ранк". Черт, не действует. Слушай, да иди ты в пень, раз так, плевать на тебя, и все в порядке.}
