{100}{}{Вы обнаруживаете, что Центр Управления и Контроля погребен под грудой камня. Вам придется искать приступать к поискам водяного фильтра в каком-то другом месте.}
{101}{}{Куча мусора, перегородившая коридор, смотрится впечатляюще. Вам не кажется, что ее можно сдвинуть с места, даже с помощью мощнейшей взрывчатки.}
{102}{}{Вы получаете }
{103}{}{ единиц опыта.}
