{100}{}{Писец.}
{101}{}{Исследования и открытия - это мое любимое занятие. Я чувствую, что об'ясняю миру великие тайны.}
{102}{}{Самое лучшее - это быть писцом. Вы изучаете все старинные технологии и пытаетесь разработать новые.}
{103}{}{Эти терминалы наверняка можно улучшить. Наверное, следовало бы поставить дисплей вот сюда.}
{104}{}{Извините, я не могу с вами поговорить. У меня вот-вот наступит прорыв. И вот тогда и поболтаем.}
{105}{}{Эй, Дружище! Если ты еще не решил, кем будешь. то становись писцом, и не пожалеешь!}
{106}{}{Мы, писцы, разрабатываем все оружие и снаряжение. Это исключительно занимательно.}
{107}{}{Пожалуйста, не мешайте. Я пытаюсь закончить это исследование.}
{108}{}{Вон там Врее, видите? Она тоже писец.}
