{100}{}{Вы видите Слэппи.}
{101}{}{Буги, Вуги, Дуги.}
{102}{}{Это мерзкий паук, убийца, давите его.}
{103}{}{Давай поиграем в Глобальную Термоядерную Войну.}
{104}{}{Где мое ... э-э-э???}
{105}{}{Дыц.. Дыц... Дыц...}
{106}{}{Луна вышла на небо.}
{107}{}{Дай мне сладкую малышку.}
{108}{}{О, как премило. А при чем здесь луна?}
{109}{}{Я говорил с Гарольдом. Рука Смерти - это так мерзко звучит. Что ты мне про это расскажешь?}
{110}{}{Бет сказала мне поговорить с тобой о Руке Смерти.}
{111}{}{Что ты делаешь в этих степях?}
{112}{}{В чем проблема?}
{113}{}{Луна Большой, Я Луна!}
{114}{}{Все ясно, все ярко, свет сходит вниз, и тогда мы обречены на страшную гибель.}
{115}{}{Аххх.}
{116}{}{Рука Смерти, Рука Смерти, Вах Вах Рука Смерти.}
{117}{}{Ну же, скажи, что ты знаешь про Руку Смерти?}
{118}{}{В чем дело?}
{119}{}{Не заставляй меня выбивать это из тебя!}
{120}{}{Сделаю, я, сделаю, затем ты, затем все мы.}
{121}{}{А что ты сделаешь?}
{122}{}{Ты сумасшедший.}
{123}{}{Проблемы, они как миски супа, широкие и глубокие.}
{124}{}{О да, и все, все плавают в твоей голове.}
{125}{}{Рука Смерти жуткий, да, да, действительно жуткий монстр. Ёочешь увидеть?}
{126}{}{Ты можешь провести меня к Руке Смерти?}
{127}{}{Ни черта!}
{128}{}{Да, да, Рука Смерти, прямо сейчас идем на нее смотреть.}
{129}{}{Заткнись и проведи меня туда.}
{130}{}{А, ничего. Подлечись, дорогуша.}
{131}{}{Я делаю это, затем я делаю то. Ты видел Гарольда? Это весело, его волосы падают на ветер. Да, и дальше... ветер, ветер. Дождь. Снег.}
{132}{}{Что ты мелешь?}
{133}{}{Бить и Бить. И еще бить. И бить...}
{134}{}{Почему ветер? Дождь? Снег? Снег с дождем? Почему.}
{135}{}{Бет, Бет, шу ша Бет. Полюби Гарольда. Говори с ним. Слушай его ушами, он расскажет. Я Слаппи и помогу.}
{136}{}{Ёорошо, пойду, поговорю с Гарольдом.}
