{100}{}{Станция безопасности}
{101}{}{Этот терминал "Тилье" контролирует операции Сил Специального Назначения. Пожалуйста, представьтесь голосом.}
{102}{}{Нэээ!}
{103}{}{Помоги! Моя досталось.}
{104}{}{Позволь мне пройти.}
{105}{}{Я}
{106}{}{. Позволь мне пройти.}
{107}{}{Что это еще такое?}
{108}{}{Голос не опознан. Статус систем безопасности: включены.}
{109}{}{Я представляю систему безопасности Синего Уровня. Все системы включены.}
{110}{}{Ты можешь выключить системы?}
{111}{}{Почему системы включены, хотя война уже закончилась?}
{112}{}{Спасибо.}
{113}{}{В программе требуется оставить системы включенными, пока уполномоченный персонал не введет правильный голосовой код.}
{114}{}{Ты отключишь для меня системы?}
{115}{}{До свидания.}
{116}{}{Голосовой код: Гамма Дельта Дельта. Отключи все системы.}
{117}{}{Вы не уполномочены на это. В доступе отказано.}
{118}{}{Неверный код. В доступе отказано.}
{119}{}{Голосовой код: Гамма Омикрон Дельта. Отключи все системы.}
{120}{}{Голосовой код: Омикрон Дельта Дельта. Отключи все системы.}
{121}{}{Голосовой код: Альфа Дельта Дельта. Отключи все системы.}
{122}{}{Голосовой код: Дельта Омикрон Гамма. Отключи все системы.}
{123}{}{До свидания.}
{124}{}{Голосовой код подтвержден. Отключаю системы безопасности.}
{125}{}{У меня нет приказов сделать иначе. Доступ к сети отсутствует. Центральный процессор ZAX, очевидно, уничтожен.}
{126}{}{Прекрасно. Голосовой код: Сигма Альфа Дельта. Отключи все системы.}
{127}{}{До свидания.}
{128}{}{Системы безопасности оключены.}
