{100}{}{Вы могли бы вытащить больше информации из этого терминала при более подробном научном изучении.}
{101}{}{Этот терминал регулирует снабжение Ёранилища и выполняет рутинную административную работу.}
{102}{}{Терминалы на этом уровне выполняют климатический и температурный контроль и обеспечивают функционирование медицинской лаборатории.}
