{100}{}{Вы видите типичного среднестатистического гражданина Ёранилища-13.}
{101}{}{Ну, и как выглядит внешний мир?}
{102}{}{Вы, наверное, смелый человек, раз путешествуете вне Ёранилища.}
{103}{}{Координатор говорит, что внешний мир опасен.}
{104}{}{Будьте осторожны, когда будуте путешествовать вне Ёранилища.}
{105}{}{Не забудьте посетить медика, если вы ранены.}
{106}{}{Координатор позаботится о всех нас в Ёранилище.}
