{100}{}{Вам кажется подозрительным этот участок пола.}
{101}{}{Вы не находите ничего особенного.}
{102}{}{Вдали слышен звук сигнала тревоги.}
{103}{}{Около вашей ноги есть что-то типа сенсора.}
{104}{}{Вы отключаете сенсор.}
{105}{}{Вы не можете отключить сенсор.}
