{100}{}{Из южного конца коридора стреляет лазерное ружье!}
{101}{}{Вы замечаете небольшую подвижную секцию пола.}
{102}{}{Ваше знание ловушек дает вам возможность умозаключить, что это, в некотором роде, переключатель.}
{103}{}{Вы осторожно удаляете пружины на подвижной ячейке пола.}
{104}{}{Вы не знаете точно, как не дать включиться переключателю.}
