{100}{}{Вы видите проводника каравана.}
{101}{}{Привет. Если вы ищете работу на одном из наших караванов, вам следует поговорить с Начальником Караванов. Она в том здании на востоке.}
{102}{}{Извините, поговорите с Начальником Караванов.}
{103}{}{Ёорошо, я так и думал, что это не будет проблемой. Ее настолько завалило работой с тех пор, как Дарен Ёайтауэр стал скрываться в своем офисе. Странный человек. Мы отправляемся практически каждые пять дней: 1-го, 5-го, 10-го, 15-го, 20-го и 25-го. Мы сейчас ходим только в Джанктаун и Бониярд.}
{104}{}{А какова плата?}
{105}{}{Ммм.}
{106}{}{Наша плата 200 Ёаббаксов. Это немного, но мы часто ходим, и наши дороги не настолько опасны, и, конечно же, это в одну сторону, но вы вовсе не обязаны идти туда и обратно.}
{107}{}{Мы уходим сегодня. Вы заинтересованы?}
{108}{}{Мы уходим}
{109}{}{Ничего.}
{110}{}{}
{111}{}{. Вы заинтересованы?}
{112}{}{Я еще предлагаю вам работу, хотя это ваше дело. Вы заинтересованы?}
{113}{}{Конечно.}
{114}{}{Нет.}
{115}{}{Возможно.}
{116}{}{Я, я, натюрлихь.}
{117}{}{Тыгдым?}
{118}{}{Ну хорошо. Не вопрос, только дайте нам знать, если вы измените свое мнение.}
{119}{}{Ёотел бы я, чтобы вы все-таки решили.}
{120}{}{Ну, тогда останавливайтесь, если решите работать на нас. Выход 1-го, 5-го и так далее. Пока.}
{121}{}{Извините, но я не могу вас нанять, пока вы не можете нормально общаться с остальными людьми из команды.}
{122}{}{Пожалуйста, приходите, когда вам станет получше.}
{123}{}{Эй, с вами все в порядке? Мне кажется, вам надо что-нибудь поесть, только не ходите для этого к Бобу.}
{124}{}{Я говорю: исчезни!!!}
{125}{}{Я крайне разочарован, что вы, оказывается, вор! Зачем вы это сделали?}
{126}{}{Моя большой, злой, зеленый, из других мест, жрать хочет, моя плохо!!!}
{127}{}{Я не хотел, но я умираю от голода, а у меня есть дети.}
{128}{}{Я вытащу твое сердце ложкой!}
{129}{}{(Сдаюсь)}
{130}{}{(Атаковать)}
{131}{}{Я пытался вам помочь, но, похоже, некоторые люди недостойны помощи. Извините, но нам придется пресечь это самыми жестокими мерами.}
{132}{}{Я понимаю, но это не оправдание. Я все-таки собираюсь попросить вас уйти. Мы не можем нанимать людей, которые не могут собой управлять.}
{133}{}{Вы думаете, я поймаюсь на такой бред? Охрана!}
{134}{}{Извините, но иногда небольшая камера лечит людей. Охрана! Попытайтесь ее не убить. Вы сдадитесь моим стражникам?}
{135}{}{Увидимся в аду!}
{136}{}{Да. Я сожалею.}
{137}{}{Что? Вы нарываетесь еще на одну драку?!}
{138}{}{Извините, но вы должны уйти сейчас же, иначе я буду вынужден вызвать полицию.}
{139}{}{Охрана! Полиция!}
{140}{}{Я думаю, что вам следует уйти...}
{141}{}{Извините, мне не разрешено вас нанимать.}
{142}{}{Уходите, пожалуйста, у меня будут трудности.}
{143}{}{Пожалуйста, уходите.}
{144}{}{Это интригующе, но вы не в моем вкусе.}
{145}{}{Это изумительно! Плата, как обычно, 200 Ёаббаксов. Какое направление вы предпочитаете?}
{146}{}{Прелестно. Приходите}
{147}{}{1-го}
{148}{}{5-го}
{149}{}{10-го}
{150}{}{15-го}
{151}{}{20-го}
{152}{}{25-го}
{153}{}{. В этот день уходит караван. Как всегда, плата 200 Ёаббаксов.}
{154}{}{Ёорошо.}
{155}{}{Извините, не могу ждать.}
{156}{}{Это просто трагедия! Мы потеряли целый караван, но вы выжили? Такого не должно случиться. Я не знаю, что произошло там, но мы не можем более нанимать вас. Извините.}
{157}{}{Джанктаун}
{158}{}{Боунярд}
{159}{}{Мнэ-э-э, не сейчас. Возможно, в следующий раз.}
{160}{}{Превосходно, я наберу остаток команды.}
{161}{}{Чудесно.}
{162}{}{Ну, вперед. Удачи!}
{163}{}{Попытайтесь избежать неприятностей. Ёотя бы не ищите специально.}
{164}{}{Будьте осторожны, мне не нравится, как выглядит Бониярд. Там жутко.}
{165}{}{Это хорошо. Эти черные дороги воистину странны, но по ним можно очень хорошо путешествовать.}
{166}{}{Мне кажется, там есть банды. Я был бы очень осторожен при разговорах с посторонними.}
{167}{}{Прекрасно. Джанктаун - это достойное место.}
{168}{}{О, передайте привет этому их Килл... Киб.. Ой! Ну как его там? В общем я забыл, но он хороший парень. Я хотел бы знать, как у него дела.}
{169}{}{Интересное местечко. Там, говорят, есть какой-то доктор, который способен поднять даже мертвых... Или что-то еще...}
{170}{}{Какого дьявола вы покинули последний караван? Ничего страшного не случилось, но могло быть всякое.}
{171}{}{Вы дадите мне еще шанс?}
{172}{}{Ничего.}
{173}{}{Я не несу чушь!}
{174}{}{Ихь бин васе нихьт. Я-я.}
{175}{}{Грмнэ.}
{176}{}{Извините, но вы опять меня подвели. Кажется, вы не очень-то ответственны за работу, и это нехорошее качество для нашей работы.}
{177}{}{Почему я?}
{178}{}{Вам не следует!}
{179}{}{Потому что я собираюсь проделать дыру в вашей голове, если вы этого не сделаете!}
{180}{}{У меня есть более важные дела, чем нянчиться с каким-то дурацким караваном!}
{181}{}{Я не знал, что мне нельзя покидать караван. Все казалось в порядке.}
{182}{}{Я смотрю, вы были под наркотой. Ну, живите так, если вам хочется.}
{183}{}{Сожалею, что причинил вам такие ощущения.}
{184}{}{Я удивлен, что у вас никогда не было каравана, но я думаю, что от этого вреда не будет, так что я дам вам еще один шанс.}
{185}{}{Это прекрасная работа! Ёотите еще один караван?}
{186}{}{Конечно.}
{187}{}{Нет.}
{188}{}{Возможно.}
{189}{}{Ик!}
{190}{}{Ла.}
{191}{}{Вы готовы? Мы уходим сегодня.}
{192}{}{Да.}
{193}{}{Нет.}
{194}{}{Эак!}
{195}{}{Иначе я отдам караван другому человеку, так что не беспокойтесь. Вы ни к чему не обязаны, пока вам не вручили караван, угу?}
{196}{}{Вы немного рано. Следующий караван уходит}
{197}{}{1-го}
{198}{}{5-го}
{199}{}{10-го}
{200}{}{15-го}
{201}{}{20-го}
{202}{}{25-го}
{203}{}{. Приходите тогда, если вам будет нужна работа.}
{204}{}{в январе,}
{205}{}{в феврале,}
{206}{}{в марте,}
{207}{}{в апреле,}
{208}{}{в мае,}
{209}{}{в июне,}
{210}{}{в июле,}
{211}{}{в августе,}
{212}{}{в сентябре,}
{213}{}{в октябре,}
{214}{}{в ноябре,}
{215}{}{в декабре,}
