{100}{}{Widzisz Starszego.}
{101}{}{Mi³o mi ciê poznaæ. Mam nadziejê, ¿e jak dot¹d nasza wioska by³a dla ciebie przyjemnym miejscem.}
{102}{}{Pewnie.}
{103}{}{Nie, nie za wiele tu siê dzieje.}
{104}{}{Œwietnie. Muszê poprosiæ ciê o przys³ugê. Zapewniam ciê, ¿e zostaniesz sowicie wynagrodzony.}
{105}{}{S³ucham.}
{106}{}{To tylko urywek, byæ mo¿e zainteresuje ciê, to co zaraz powiem.}
{107}{}{Zamieniam siê w s³uch.}
{108}{}{Od jakiegoœ czasu jesteœmy nêkani przez radskorpiony. Wszyscy, którzy wyruszyli aby rozprawiæ siê z tymi potworami, nigdy nie powrócili. Dam ci broñ i zbrojê, jeœli udasz siê do ich le¿a i je zabijesz.}
{109}{}{Brzmi nieŸle.}
{110}{}{Nie, dziêki. To nie w moim stylu.}
{111}{}{WstydŸ siê! Nie chcê z tob¹ rozmawiaæ.}
{112}{}{Znakomicie. Seth zaprowadzi ciê do ich nory. WeŸ te rzeczy - na pewno siê przydadz¹.}
{113}{}{Proszê, pomó¿ nam tak szybko jak to mo¿liwe. Czas jest dla nas bardzo wa¿ny.}
{114}{}{Nie rozmawiam z takimi jak ty, przybyszu.}
{115}{}{Ocali³eœ nasz¹ wioskê od niebezpieczeñstwa. Teraz okolica nie jest ju¿ zagro¿eniem. Przyjmij to jako dowód naszej wdziêcznoœci. [Daje ci trochê kapsli]}
{116}{}{Dziêkujêmy ci. Tak wiele ci zawdziêczamy.}
