# Alchemist: long phrases should be split and require some smooyhing.

{100}{}{Widzisz Lexa, herszta klanu ¯mij}
{101}{}{Ogromny facet ze z³ym nastawieniem ³ypie na ciebie z³owrogo.}
{102}{}{[...Ju¿ na dobre siê obudzi³eœ i rozejrza³eœ dooko³a. Widzisz niezbyt znajome miejsce z trzema namiotami i kilkoma osobami blisko nich. Wygl¹da na to, ¿e uda³o ci siê odzyskaæ przytomnoœæ w sam raz, zanim zd¹¿yli opró¿niæ twoje kieszenie. Twoje oczy skupiaj¹ siê na mê¿czyŸnie stoj¹cym tu¿ obok ciebie] Och, nasz nieszczêsny klient siê obudzi³.}
{103}{}{[Wiêcej]}
{104}{}{To jak bêdzie? Oddasz nam wszystkie twoje kapsle, to pozwolimy ci odejœæ. Albo mo¿emy pobawiæ siê w nieustraszonych kowbojów.}
{105}{}{A co gwarantuje, ¿e opuszczê to miejsce ¿ywy, jeœli oddam wam kasê?}
{106}{}{Zawsze uwielbia³em westerny!}
{107}{}{Kowboje.}
{108}{}{S³owo bandyty!}
{109}{}{Myœlê, ¿e mogê ci zaufaæ. Bierz. [Dajesz mu swoje oszczêdnoœci]}
{110}{}{Te s³owa nic dla mnie nie znacz¹.}
{111}{}{A wiêc trafi³ nam siê uparty? Nawet mnie siê to podoba. W takim razie myœlê, ¿e koledzy bêd¹ mieli z tob¹ niez³¹ zabawê.}
{112}{}{Jeœli nie ufasz s³owom, powinieneœ zaufaæ spluwom! Taki miêczak jak ty nie jest wyzwaniem dla ca³ego gangu!}
{113}{}{Poza tym, wolê ciê zabiæ. By byæ pewnym, ¿e nikt nie bêdzie paplaæ za du¿o po okolicy. ¯egnam.}
{114}{}{Mi³y goœæ. M¹dra decyzja. Jesteœ wolny, mo¿esz iœæ.}

