{100}{}{Widzisz zwiadowcê Mrocznych.}
{101}{}{Co my tu mamy? Normalniak. Chyba pójdziesz ze mn¹.}
{102}{}{Nu.}
{103}{}{Dobra.}
{104}{}{A to niby dlaczego?}
{105}{}{Chyba nie!}
{106}{}{To naprawdê proste. Jeœli pójdziesz ze mn¹, bêdê ci móg³ pomóc.}
{107}{}{Dobrze. Pójdê z tob¹.}
{108}{}{Lepiej skieruj mnie do swojego wodza.}
{109}{}{Nie ma mowy!}
{110}{}{Szybko. Szukaj Utherna. On ciê ustawi.}
{111}{}{Uthern chce siê z tob¹ zobaczyæ. Chyba ju¿ o tobie s³ysza³.}
