{100}{}{Zdobywasz 400 punktów doœwiadczenia za uratowanie Tandi.}
{101}{}{Na po³udniu widzisz ceglan¹ œcianê otaczaj¹c¹ spokojnie wygl¹daj¹c¹ wioskê.}
{102}{}{Na tym obszarze nie pozosta³o nic poza ma³ym sza³asem. Na szczêœcie twoje dane mówi¹, ¿e znajduje siê tu zapasowe wejœcie do Krypty 15.}
{103}{}{Widzisz ma³y budynek, w pobli¿u którego rozbito kilka namiotów. Mieszkañcy s¹ brudni i wygl¹daj¹ na wrednych.}
{104}{}{Napotykasz œrednie miasto. G³ówne wejœcie jest zablokowane przez rz¹d z³omowanych pojazdów. Wokó³ unosi siê niewyraŸny opar.}
{105}{}{Na po³udniu widzisz du¿e miasto, otoczone wianuszkiem farm. Ta pustynna oaza têtni ¿yciem.}
{106}{}{Zbli¿asz siê do ciemnego, rozk³adaj¹cego siê miasta. Nie widaæ wielu oznak ¿ycia. Ca³y teren przenikn¹³ zapach œmierci.}
{107}{}{Na pó³nocy znajduje siê ma³y budynek otoczony siatk¹ z drutu. GroŸnie wygl¹daj¹cy stra¿nicy w ciê¿kich zbrojach patroluj¹ teren.}
{108}{}{Na pó³nocy rozpoœciera siê du¿y krater.}
{109}{}{Na pó³nocny wschód st¹d widzisz mutantów strzeg¹cych ufortyfikowanej pozycji wbudowanej w skaln¹ œcianê.}
{110}{}{Wielki, bogato zdobiony budynek wznosi siê ku niebu. Przed nim krêci siê bez celu ca³a masa ludzi.}
{111}{}{Na pó³nocy widzisz magazyn otoczony fos¹ pe³n¹ œwiec¹cego siê œwiñstwa.}
{112}{}{Przed tob¹ wy³ania siê du¿a, ufortyfikowana fabryka ze œcianami pomazanymi graffiti i groŸnie wygl¹daj¹cymi strzelnicami.}
{113}{}{Miejscowy, czêœciowo odbudowany klub nocny i malutkie posterunki wyraŸnie zdradzaj¹ œlady dzia³alnoœci gangów.}
{114}{}{W samym sercu miasta wznosi siê wielka, odbudowana i ufortyfikowana biblioteka. Budynek, jednoczeœnie zgrabny i groŸny, napawa ciê spokojem.}
{115}{}{Na po³udniu czeka na ciebie ogrodzona i strze¿ona wioska.}
{116}{}{Na ziemi widzisz ogromny œlad stopy. Przeszukanie najbli¿szej okolicy nie ujawnia ¿adnych innych œladów.}
{117}{}{Ten teren jest pokryty popio³em i œladami po¿aru.}
{118}{}{Ten teren wygl¹da, jakby trafi³aby weñ wysokociœnieniowa bomba ogniowa.}
{119}{}{Dostrzegasz obóz wêdrownych bandytów. Wygl¹da na to, ¿e znajdujesz siê w nieodpowiednim miejscu i czasie.}