##
## NOTE: Each line in the description box holds roughly 40 characters in English. Meaning to add a blank line, add 40 spaces and then reduce as needed.
##       This will differ based on words used (since it wraps based on the word length)  --Sduibek, Fallout Fixt
##
#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{高速循环系统}
{101}{}{彪形大汉}
{102}{}{小巧玲珑}
{103}{}{单枪客}
{104}{}{战略大师}
{105}{}{特工队}
{106}{}{暴力战士}
{107}{}{快枪手}
{108}{}{瘟神}
{109}{}{笨手笨脚}
{110}{}{烂好人}
{111}{}{Drug-Reliant}
{112}{}{Drug-Resistant}
{113}{}{夜猫子}
{114}{}{专家}
{115}{}{天赋异禀}
#
#   TRAIT DESCRIPTIONS
#
##
##
##
##
##
##
{200}{}{你的新陈代谢是别人的两倍。这代表着你对放射线以及毒的防御力较低，但是你的伤恢复的较快。}
{201}{}{你的动作很慢，但身体强壮。在战斗时也许攻击次数比较少，但是每一次攻击会造成相当大的伤害。你的最高行动点数会比较低，你的力量会比较高。}
{202}{}{你比别人要小一号，但动作要比别人快。你无法负荷很重的重量，但你的灵活度会比较高。}
{203}{}{你的一只手臂比另一只要发达许多，因此你对于单手使用的武器相当在行，不过双手使用的武器则会对你造成一些困扰。}
{204}{}{你的普通攻击造成的伤害并不多，但你可以时常的使出特别攻击，造成相当大的伤害。}
{205}{}{你对周围的危险全然不在乎，所以你的动作相当快。因此你的防御点数只有你身上装甲所提供的防御点数，不过在战斗中通常都会由你先攻。}
{206}{}{你的手臂相当强壮，却不够灵活。在攻击时可以造成相当大的伤害，但是却不能经常使出特别攻击。}
{207}{}{你开枪的速度很快，但不能瞄准特殊的部位。在使用枪和空投武器时所用的行动点数会比正常人少一个点。}
{208}{}{不知道为什么，如果你遇到的人会死，他们总会以最惨的方式死去。你总是会看到他人惨死的景象。}
{209}{}{好消息是：你遇到的敌人无论对你使用什么样的攻击都不容易成功。坏消息是：你也一样！}
{210}{}{小时候你并没有学习过很多有关战斗的技巧，因此你的战斗力一开始会比较差。不过医疗技术、急救、演说能力以及杀价能力都会以相当快的速度进步。}
{211}{}{You are more easily addicted to drugs. Your chance to become addicted to substances you use is twice normal, but you recover faster from their ill effects.}
{212}{}{你对化学药品上瘾的几率是别人的50%，但是你受化学药品影响的时间却是别人的两倍。}
{213}{}{作为喜欢晚上四处活动的人，你在夜里是非常清醒的。当太阳落山后你的感知力和智力会有所提升，但在白天你却显的比较迟钝。}
{214}{}{你花相当长的时间来学习一项技术，所以每次升级后你都会多得到五个技能点数，但是你每升四级后才能得到新的特别技能。}
{215}{}{你有很高的天赋，但是你却不够细心。一开始，你的每一项数值都会比别人多一个点，但是你所有的技能都会比别人少5%，同时，每次升级你都会少得到5个技能点数。}
