{100}{}{Вы видите Митча, владельца универсального магазина.}
{101}{}{Я могу вам помочь?}
{102}{}{Я хочу кое-что купить.}
{103}{}{Я хочу кое-что продать.}
{104}{}{Да нет, спасибо.}
{105}{}{Эм-м-м.}
{106}{}{Отлично. Вот что у меня есть.}
{107}{}{Замечательно, я всегда ищу что-нибудь новенькое.}
{108}{}{Извини, я тебя не понимаю. Приходи, когда поумнеешь.}
{109}{}{Спасибо. Заходи еще.}
{110}{}{Вы видите Джейка, торговца оружием.}
