{100}{}{Вы видите Тона.}
{101}{}{Вы видите одного из Чад Собора.}
{102}{}{друг}
{103}{}{подруга}
{104}{}{[Готово]}
{105}{}{[Дальше]}
{106}{}{Извини, друг, но ты зарвался. Ты труп!}
{107}{}{Извини, сестренка, но ты доигралась. Помолись перед смертью!}
{108}{}{Я не буду разговаривать с детоубийцей. Отвали от меня!}
{109}{}{Говорят, ты чертовски крута, но меня-то этим не возьмешь. Ну что, поболтаем или сразу в койку? Давай, не тяни!}
{110}{}{Спокойно, брат! Я просто гуляю, смотрю по сторонам.}
{111}{}{Я не собираюсь покорять твое сердце. Если можешь сказать что-нибудь умное, валяй.}
{112}{}{В койку? Спасибо, малолетками не интересуюсь.}
{113}{}{Чего ты хочешь?}
{114}{}{Ты слишком много болтаешь.}
{115}{}{Ты хочешь умереть, а я хочу кого-нибудь убить. Кажется, мы нашли друг друга.}
{116}{}{Уа-а!}
{117}{}{Слышь, я с тобой уже пообщался. Вали отсюда!}
{118}{}{парень}
{119}{}{сестренка}
{120}{}{Думаешь, с оружием тебя все сразу зауважают? Убери это, друг, если не ищешь короткой дороги на кладбище.}
{121}{}{Думаешь, с оружием тебя все сразу зауважают? Убери это, подруга, если не ищешь короткой дороги на кладбище.}
{122}{}{Тебе чего, зомби тупоголовый? Отвали, пока я тебе кости не переломал.}
{123}{}{Ищу кого-нибудь с мозгами - хочу узнать, что здесь происходит!}
{124}{}{Что скажут жрецы, если узнают, как ты разговариваешь?}
{125}{}{Не вопрос, приятель. Я давно уже хочу с кем-нибудь помахаться!}
{126}{}{Эй, ты чего? Давай хлопнем по стаканчику и подружимся!}
{127}{}{Знаешь, если надавить в определенную точку на колене, можно на всю жизнь искалечить человека. Это по силам даже ребенку. Подумай об этом на досуге.}
{128}{}{Хочешь поговорить с Тоном? Ладно. Но если я услышу слово "восхвалить", я тебя убью.}
{129}{}{Ты явно не поклонник богослужений.}
{130}{}{А в чем проблема, приятель?}
{131}{}{Я хочу поговорить с главным.}
{132}{}{Без проблем. Единственное, что мне действительно хочется восхвалить, так это бутылочку с противоядием.}
{133}{}{Ладно. Первый из нас, кто скажет это слово - умрет. По рукам?}
{134}{}{Здравствуйте, мисс. Меня зовут Тон, я самый крутой боец Создателя. Вирус ВРЭ нарастил мне не только 80 килограммов мышц, но и кое-что еще. Думаю, вам понравится! Приступим?}
{135}{}{Ни за что.}
{136}{}{Боюсь, это слишком быстро. Нам надо получше узнать друг друга...}
{137}{}{Здравствуйте, сэр. Вирус ВРЭ атрофировал у меня чувство юмора, поэтому все, кто меня раздражает, умирают мучительной смертью. Отвали!}
{138}{}{Иди-ка ты своей дорогой. Тон тебе не пара.}
{139}{}{Ладно, давай начистоту. Иногда убивать людей нужно. Иногда я сам это делаю. Но ты убиваешь... слишком часто! Тон не связывается с психами. Обычно он убивает психов. Может, тебе лучше уйти?}
{140}{}{Слушай, ты мне нравишься. То ли у тебя крыша набекрень, то ли наглость зашкаливает... Впрочем, мне все равно, лишь бы меня не доставали. Так что, составишь нам компанию?}
{141}{}{А как же любовь в космических масштабах?}
{142}{}{Что значит "компанию"?}
{143}{}{Нет уж, приятель.}
{144}{}{Я достаю кого хочу и когда хочу. ??? В данный момент это ты!}
{145}{}{Боюсь, для тебя это слишком... Ладно, мачо, дай мне то, что я хочу!}
{146}{}{Осторожнее с желаниями. Иногда они сбываются.}
{147}{}{Лучше останемся друзьями!}
{148}{}{Не хочу тратить на тебя свое время.}
{149}{}{Давай, начинай. Я присоединюсь.}
{150}{}{Все, хватит разговоров. Поехали.}
{151}{}{Мне просто нужно было поговорить.}
{152}{}{Ты труп...}
{153}{}{Черт! Ты тупее, чем зомби. Вали отсюда!}
{154}{}{Создатель хочет, чтобы воцарился мир. Мы ему помогаем, чтобы не заскучать. Врубаешься?}
{155}{}{Да. Но, по-моему, ты что-то недоговариваешь.}
{156}{}{Создатель действительно за мирную жизнь?}
{157}{}{Кто такой этот ваш Создатель?}
{158}{}{А что, мне нравится.}
{159}{}{К черту Создателя! Давай убьем их всех!}
{160}{}{Задавать неправильные вопросы вредно для здоровья, товаристч. Ты знаешь ровно столько, сколько нужно. Тот, кто задает слишком много вопросов, надолго здесь не задерживается.}
{161}{}{Я занимаюсь своим делом. Им это нравится. Им нравится, когда уличные отбросы и Последователи умирают. Это позволяет Детям ночи делать то, что нужно. Не связывайся со мной... Это опасно.}
{162}{}{Почему на тебе шмотки, как у зомби? Если тебе есть что показать, не стоит это скрывать!}
{163}{}{Я не парюсь насчет шмоток, друг. Просто хочу узнать, что тут происходит.}
{164}{}{Они не будут к тебе приставать, если поймут, что тебя не обратить.}
{165}{}{Не твое дело, приятель.}
{166}{}{А я как раз подумываю об Обращении.}
{167}{}{Есть что показать? Я тебе сейчас дорогу на кладбище покажу!}
{168}{}{Мы тут не пьем. Дети ночи этого не любят. Ты сначала разберись, что к чему, а потом уже обращайся к Тону.}
{169}{}{Да ты совсем без башни! Ты мне уже почти нравишься, вот только люди рядом с тобой долго не живут. Вали отсюда.}
{170}{}{Постоишь тут несколько месяцев, крыша еще не так поедет. Что тебе нужно от Тона?}
{171}{}{Как люди дошли до такого?}
{172}{}{Я обожаю секс и насилие... Можно даже без секса. Не поможешь?}
{173}{}{Не нужна мне твоя помощь, у меня крыша едет в этом загоне для зомби. Вали к чертовой матери.}
{174}{}{Это Морфеус. Он живет на верхнем этаже и спускается только читать проповеди, хотя я давно уже его здесь не видел. Он умный и везучий, а это главное. Хочешь - сходи, познакомься с ним.}
{175}{}{Тебе нужно в Могильник, дружище. Здесь не водится напитков, я проверял.}
{176}{}{Согласен. Чем Тон может тебе помочь?}
{177}{}{Дура! Ты не знаешь, от чего отказываешься! Ну и проваливай!}
{178}{}{Жизнь слишком коротка. Давай я покажу тебе то, ради чего ты проделала весь этот путь.}
{179}{}{Но мне нужен человек, который знает, что тут происходит.}
{180}{}{Нет, спасибо. Может, лучше останемся друзьями?}
{181}{}{Отвали, урод.}
{182}{}{Конечно.}
{183}{}{Жизнь действительно слишком коротка. Умри, подонок!}
{184}{}{Это кто тут малолетка, дура?}
{185}{}{Да кто верит в эту хрень? Разве что зомби после промывки мозгов!}
{186}{}{Как это? Объясни!}
{187}{}{Правда?}
{188}{}{Цирк уродов.}
{189}{}{Расскажи мне о своем отряде.}
{190}{}{Ладно, я с вами.}
{191}{}{Кто-то должен решить судьбу этих несчастных. Например я...}
{192}{}{Когда нам прикажут, мы пойдем убивать Последователей или бандитов.}
{193}{}{Значит, вам мешают Последователи?}
{194}{}{Не нравится мне это.}
{195}{}{Да кому нужны эти приказы? Давай просто убьем их!}
{196}{}{Ладно. Делай что хочешь, но на меня не рассчитывай.}
{197}{}{Ты мерзкое отродье, хуже этих уродов из Джанктауна. Убирайся к чертовой матери!}
{198}{}{Что ты еще хочешь узнать? Я привык вкусно есть, мягко спать и убивать тех, кто меня бесит. Чего еще можно желать?}
{199}{}{Кто знает? И кому какое дело? Я привык вкусно есть, мягко спать и убивать тех, кто меня бесит. Чего еще можно желать?}
{200}{}{Хм-м, об этом Тон никогда не думал. Но если они вдруг ко мне пристанут, я раскрою им черепа. И тогда Тону снова будет спокойно. Чего тебе надо?}
{201}{}{Обращение? Что ж, удачи. Она тебе пригодится.}
{202}{}{Почему это она мне пригодится?}
{203}{}{Не нравится мне все это.}
{204}{}{Спасибо. Ты настоящий друг.}
{205}{}{Пока у меня достаточно патронов, удача мне не нужна.}
{206}{}{Эти люди, эти зомби - они не всегда были такими. Когда-то я даже мог общаться с некоторыми из них. А потом их обратили. И они стали такими. А часть вообще не вернулась. Тону это не нравится, но ему здесь хорошо платят.}
{207}{}{А почему ты говоришь о себе то в первом, то в третьем лице?}
{208}{}{Расскажи мне про обряд Обращения.}
{209}{}{А ты прошел Обращение?}
{210}{}{Это паршивое место.}
{211}{}{Серьезно? Сколько же?}
{212}{}{Я им этого не позволю!}
{213}{}{Поговори с Морфеусом или с отцом Битье. Или продолжай доставать Тона глупыми вопросами, и тогда насилия будет много!}
{214}{}{Да что рассказывать: зомби молятся, люди умирают, Чада Собора скоро приберут все к своим рукам... Главное, есть ты и я, а все остальное - ерунда}
{215}{}{Но, милый, меня интересует еще кое-что...}
{216}{}{О, Тон!}
{217}{}{Забудь об этом, урод. Ты не в моем вкусе.}
{218}{}{Как это ерунда? Я хочу узнать, почему люди умирают!}
{219}{}{Увы, это место не подходит для демонстрации всех возможностей Тона. Слишком много зомби... Когда найду более подходящее помещение, дам тебе знать.}
{220}{}{Поднимись по лестнице, и ты все узнаешь. Если хватит силенок, проблем не будет. С Тоном это случилось, и Тон в полном порядке!}
{221}{}{Э-э... Я ничего не говорил. Забудь все, что сказал тебе Тон, или Тон заставит тебя навсегда забыть об этом!}
{222}{}{Они жаловались. Но Тон слишком много говорит. Уйди прочь.}
{223}{}{Хорошо. Жди, пока я тебе не скажу, а пока не привлекай внимания.}
{224}{}{Они трусы. Они устраивают засады на наши патрули. Они засылают шпионов и диверсантов. Они знают, что в честном бою им не выиграть. Создатель говорит, что их надо жалеть, но Тон хочет их убить. Тон умный.}
{225}{}{Нам нужна дисциплина! Теперь мы солдаты! Мы выполняем приказы. Убийцы умирают, а солдаты выигрывают сражения. Мы уничтожим Последователей. Мы уничтожим ВСЕХ!}
{226}{}{Да откуда я знаю? Может быть, за ниточки дергает Морфеус. Но пока все в порядке, а если дело не выгорит, Тон уйдет куда-нибудь еще.}
{227}{}{Не думай, что все так просто. Работа дико опасная, даже с Детьми ночи. Но если все сделать по уму, мы справимся. А Тону только того и надо.}
{228}{}{Обращение - чертовски сложная штука. Видишь всех этих зомби? Раньше они были нормальными, как ты и я. Тон выжил. А они - нет. Впрочем, какое Тону дело до тебя?}
{229}{}{Тебе не нравится, как разговаривает Тон? Тогда Тон убьет тебя!}
{230}{}{Тон прошел Обращение. Я... э... Я... ну... Тон... Тон жив.}
{231}{}{Когда-то я состоял в клане Мертвой собаки. Голодал, работал без отдыха... Здесь намного лучше. Зачем мне беспокоиться еще о ком-то? Обо мне никто никогда не беспокоился!}
{232}{}{Ах ты жадная тварь! Вали отсюда, пока Тон тебя не прикончил!}
{233}{}{Тогда убирайся отсюда, пока не поздно.}
{234}{}{Главное - это мы с тобой. Увы, это место не подходит для демонстрации всех возможностей Тона. Слишком много зомби... Когда найду более подходящее помещение, дам тебе знать.}
{235}{}{Ах ты лживая скотина! Никто не посмеет обидеть Тона!}
