{100}{}{Взрыв засыпал вход в тоннель!}
{101}{}{Вы уронили взрывчатку, и она рванула!}
{102}{}{The explosion just makes the hole larger. It is impossible to close it now.}
{103}{}{Вы получаете опыт за успешное использование взрывчатки.}
