{100}{}{Камни полностью завалили вход. Они слишком тяжелые, и вы не можете разобрать завал. Интересно, был ли там водяной чип? Если и был, теперь вы до него не доберетесь.}
{101}{}{Груда тяжелых камней засыпала вход в комнату. Вы пытаетесь сдвинуть камень с места, но у вас ничего не получается.}
