{100}{}{Вы видите Боба.}
{101}{}{Хочешь обворовать меня?}
{102}{}{Слушай, мне не нужны проблемы!}
{103}{}{Дай мне игуану на палочке.}
{104}{}{Что ты знаешь о водяных чипах?}
{105}{}{Что ты можешь рассказать о Декере?}
{106}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{107}{}{Знаешь что-нибудь о пропавших караванах?}
{108}{}{От меня проблемы? Почему это?}
{109}{}{Жрать хочу! Гр-р-р!}
{110}{}{Добро пожаловать в семейное кафе "Игуанятина Боба". Что будете заказывать?}
{111}{}{Дай мне игуану на палочке.}
{112}{}{Что ты знаешь о водяных чипах?}
{113}{}{Что ты можешь рассказать о Декере?}
{114}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{115}{}{Знаешь что-нибудь о пропавших караванах?}
{116}{}{Что происходит в городе?}
{117}{}{Жрать хочу! Гр-р-р!}
{118}{}{Увы, игуана закончилась.}
{119}{}{Есть только игуана на палочке. Двадцать баксов за порцию.}
{120}{}{Есть только филе. Отличное блюдо! Восемь баксов за порцию.}
{121}{}{Конечно. У нас есть игуана на палочке за двадцать баксов и филе за восемь.}
{122}{}{Я возьму целую игуану.}
{123}{}{Я возьму филе.}
{124}{}{Говорят, филе по вкусу очень похоже на курицу.}
{125}{}{Большую игуану мне! Целиком!}
{126}{}{Хм-м, филе пахнет вкусно! Порадую-ка я свой желудок!}
{127}{}{Такого не подаем. Еще что-нибудь?}
{128}{}{Дай мне игуану на палочке.}
{129}{}{Что ты можешь рассказать о Декере?}
{130}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{131}{}{Знаешь что-нибудь о пропавших караванах?}
{132}{}{Что происходит в городе?}
{133}{}{Жрать хочу! Гр-р-р!}
{134}{}{Мистер Декер - отличный бизнесмен, но занимается не самыми чистыми делами. Что еще?}
{135}{}{Расскажи мне о докторе Морбиде.}
{136}{}{Дай мне игуану на палочке.}
{137}{}{Ничего.}
{138}{}{Он был тем еще сукиным сыном. Если кто-то говорит, что не рад его смерти - он врет. Будешь что-нибудь заказывать?}
{139}{}{Дай мне игуану на палочке.}
{140}{}{Расскажи мне о торговцах водой.}
{141}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{142}{}{Знаешь что-нибудь о пропавших караванах?}
{143}{}{Что происходит в городе?}
{144}{}{Жрать хочу! Гр-р-р!}
{145}{}{Понятия не имею, о чем ты. Ладно, я плачу сотню баксов, и ты молчишь. Бери и вали отсюда!}
{146}{}{Две сотни.}
{147}{}{Хорошо, давай сотню.}
{148}{}{Я иду в полицию.}
{149}{}{Немедленно прекрати продавать это.}
{150}{}{Ужасный бизнес. Несчастные люди. Такая ужасная смерть... Тебе помочь чем-нибудь? Может быть, покормить?}
{151}{}{Дай мне игуану на палочке.}
{152}{}{Что ты знаешь о водяных чипах?}
{153}{}{Что ты можешь рассказать о Декере?}
{154}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{155}{}{Что происходит в городе?}
{156}{}{Так, ни о чем. Извини. Я могу еще чем-нибудь помочь?}
{157}{}{Дай мне игуану на палочке.}
{158}{}{Что ты знаешь о водяных чипах?}
{159}{}{Что ты можешь рассказать о Декере?}
{160}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{161}{}{Знаешь что-нибудь о пропавших караванах?}
{162}{}{Что происходит в городе?}
{163}{}{Кто-то убил Декера. Мы все скорбим. И будем скорбить, пока самогон не кончится.}
{164}{}{Кто-то убил шерифа Грина. Насчет его помощника я ничего не знаю.}
{165}{}{Дарена Хайтауэра убили. И его денежки его не спасли. Ирония судьбы, да?}
{166}{}{Кто-то сильно расстроил одну большую шишку. Разборки были будь здоров.}
{167}{}{Кто-то украл у Хайтауэров драгоценное ожерелье. Не знаю, кто, но ему теперь не жить!}
{168}{}{Кто-то убил Джейн из Собора. Говорят, она была редкостной стервой!}
{169}{}{Чада Собора захватили больницу. Это единственная новость, в последнее время здесь ничего не происходит. Эти Чада - странные ребята.}
{170}{}{Что еще интересного?}
{171}{}{Дай мне игуану на палочке.}
{172}{}{Что ты знаешь о водяных чипах?}
{173}{}{Что ты можешь рассказать о Декере?}
{174}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{175}{}{Знаешь что-нибудь о пропавших караванах?}
{176}{}{Извини, но тебе не хватает денег.}
{177}{}{Игуана на палочке, одна порция! Еще что-нибудь?}
{178}{}{Дай еще одну игуану на палочке.}
{179}{}{Что ты знаешь о водяных чипах?}
{180}{}{Что ты можешь рассказать о Декере?}
{181}{}{Знаешь что-нибудь о пропавших караванах?}
{182}{}{Что происходит в городе?}
{183}{}{Хочу еще одну игуану!}
{184}{}{??? Наелся! Р-р-р!}
{185}{}{Извини, но тебе не хватает денег.}
{186}{}{Филе игуаны, одна порция! Еще что-нибудь?}
{187}{}{Дай еще одну игуану на палочке.}
{188}{}{Что ты знаешь о водяных чипах?}
{189}{}{Что ты можешь рассказать о Декере?}
{190}{}{Знаешь что-нибудь о пропавших караванах?}
{191}{}{Что происходит в городе?}
{192}{}{Хочу еще одну игуану!}
{193}{}{??? Наелся! Р-р-р!}
{194}{}{Спасибо! Приходите еще!}
{195}{}{Ты, наверное, не отсюда. Они торгуют водой, а вода - это жизнь. Что может быть важнее жизни?}
{196}{}{Дай мне игуану на палочке.}
{197}{}{Думаю, стоит поговорить о доке Морбиде и твоих фирменных рецептах.}
{198}{}{Знаешь что-нибудь о пропавших караванах?}
{199}{}{Что происходит в городе?}
{200}{}{Жрать хочу! Гр-р-р!}
{201}{}{Ты жадный сукин сын!}
{202}{}{Ах ты жадная стерва!}
{203}{}{Ладно, твоя взяла. Вот деньги. Забирай и больше сюда не возращайся!}
{204}{}{Подумай как следует. В Хабе убивали и за меньшую сумму. А теперь вали и не приходи сюда больше!}
{205}{}{Не надо! Да, я использовал мясо... неустановленного происхождения. В разумных количествах. Но это же не убийство. То, что мне продавал Морбид, уже было мертвым, ведь так?}
{206}{}{Ну да, Боб. Не сомневаюсь, полиция с тобой полностью согласится.}
{207}{}{Но каннибализм все еще считается преступлением. И ты за это заплатишь.}
{208}{}{Не знаю, но это отвратительно! Хватит!}
{209}{}{Ну нет! Я в эти игры не играю. Получай!}
{210}{}{Мне от твоих угрызений совести ни жарко, ни холодно, а вот ты из-за них умрешь! Получай!}
