{100}{}{Вы видите караванщика.}
{101}{}{Хочешь вернуться в Хаб? Заплачу еще 400 крышек.}
{102}{}{Рутгер будет доволен - добрались без потерь. Вернешься с нами? Мы скоро отправляемся. Плачу еще 400 крышек.}
{103}{}{Оказалось, все не так сложно. Вернешься с нами? Думаю, 400 крышек тебе не помешают.}
{104}{}{Ну, неплохо. Если хочешь вернуться с нами в Хаб, милости просим. Плачу еще 400 крышек.}
{105}{}{Всегда жаль терять людей. Рутгер тоже будет не в восторге. Ты нам пригодишься на обратно пути. Пойдешь? Плачу еще 400 крышек.}
{106}{}{Черт! Ненавижу терять хороших охранников. На обратном пути нужно быть поосторожнее. Придется прикрывать друг друга. Нельзя, чтобы такое повторилось. Я заплачу тебе еще 400 крышек. Пойдешь с нами?}
{107}{}{Ты сможешь вернуться с нами в Хаб? Я не хочу рисковать. Оплата - 400 крышек. Что скажешь?}
{108}{}{Мне бы очень пригодилась твоя помощь на обратном пути. Рутгер с меня шкуру снимет... Это если я вообще дойду в одиночку. Я заплачу еще 400 крышек. Что скажешь?}
{109}{}{Сложно мне будет в одиночку возвращаться... Не хочешь дойти со мной до Хаба за 400 крышек?}
{110}{}{Черт, мы потеряли двух охранников! Рутгер и Бутч меня закопают.}
{111}{}{Да.}
{112}{}{Нет.}
{113}{}{Ы.}
{114}{}{Отлично. Пошли.}
{115}{}{Ты что, боишься?}
{116}{}{Пропустишь самое интересное.}
{117}{}{Ладно. Думаю, мы вернемся без проблем. Спасибо за помощь.}
{118}{}{Что ж, я понимаю. С одним охранником будет сложновато, но мы справимся.}
{119}{}{Хм, ну ладно. Справлюсь так.}
{120}{}{У тебя все в порядке? Паршиво выглядишь.}
{121}{}{Ты что, под кайфом?}
{122}{}{Может, ты и не годишься в караванщики.}
{123}{}{Так тебе нужна эта работа?}
{124}{}{Да.}
{125}{}{Нет.}
{126}{}{А?}
{127}{}{Заработать хочешь? Вернешься с нами в Хаб? Оплата такая же, риск тот же.}
{128}{}{Хочешь заработать еще 600 крышек? Мне надо вернуться в Хаб. Надеюсь, все пройдет спокойно.}
{129}{}{Вернешься с нами? 600 крышек, как обычно. Идет?}
{130}{}{Ненавижу терять людей, поэтому и плачу охранникам такие бабки. Опасный маршрут. Ладно, Деметр нас ждет. Оплата такая же. Ты с нами?}
{131}{}{Ну что, хочешь размяться? В этот раз все пройдет гладко! Вернемся в Хаб - заплачу 600 крышек.}
{132}{}{Знаю, терять людей горько, но по крайней мере, это была смерть в бою. Пойдешь с нами обратно в Хаб? Плачу еще 600 крышек.}
{133}{}{Черт, мы потеряли обоих охранников! Деметр меня живьем сожрет. Идешь с нами обратно? Оплата та же, я скоро отправляюсь. Что скажешь?}
{134}{}{Вот это был бой! Жаль только, потеряли двоих. Деметру это не понравится, но мы, по крайней мере, добрались. Составишь мне компанию на обратном пути? Плачу как всегда - 600 крышек.}
{135}{}{Стрелять люблю, а вот терять людей - нет. Как думаешь, справимся вдвоем? Я скоро выдвигаюсь, пойдем вместе? Оплата та же. Извини, без премии.}
{136}{}{Ым-м.}
{137}{}{Хорошо. Надеюсь, вернемся без проблем.}
{138}{}{??? Мне нужен только один охранник.}
{139}{}{Ну и ладно, сам справлюсь.}
{140}{}{Ага, снова ты. Что, нужна работа?}
{141}{}{Аы-ы.}
{142}{}{Привет! Ищешь работу? Нужно сопроводить караван в Хаб. Плачу четыре сотни.}
{143}{}{Ладно.}
{144}{}{Нет, спасибо.}
{145}{}{Гы.}
{146}{}{Привет! Ищешь работу? Нам нужно доставить товар в Хаба без потерь. Платим 600 крышек, предупреждаю сразу - маршрут опасный.}
{147}{}{Конечно.}
{148}{}{Ы-гы.}
{149}{}{Ну, если передумаешь, приходи. Мы отправляемся в 14.00.}
{150}{}{Извини, но ты не тянешь на охранника каравана.}
{151}{}{Если не можешь нормально разговаривать, работы не получишь.}
{152}{}{Если нужна работа, завязывай с наркотой.}
{153}{}{Ну так что, работа нужна?}
{154}{}{Да, я возьмусь.}
{155}{}{Ы?}
{156}{}{Вот твои деньги. Если соберешься с нами обратно, скажи мне.}
