{100}{}{You see a Nightkin.}
{101}{}{Умри!}
{102}{}{Выйди вон или умри!}
{103}{}{Мне не нравится твой тон. Если мое сообщение не доставят Создателю, тебя ждет долгая и мучительная смерть.}
{104}{}{Просто хотелось похвалить твой чудесный горб. А вот с запахом изо рта тебе надо что-то делать...}
{105}{}{Кто тут главный?}
{106}{}{Э, да ты глотнул что-то совсем убойное!}
{107}{}{Я не уйду!}
{108}{}{Ладно. Ухожу.}
{109}{}{Не стоит шутить с Детьми ночи. Убирайся!}
{110}{}{Не думаю.}
{111}{}{С радостью понаблюдаю за тем, как ты умрешь!}
{112}{}{Ты не слушаешь, что тебе говорят Дети ночи? Очень глупо.}
{113}{}{Мне надо с тобой поговорить. Это срочно!}
{114}{}{А мне всегда нравилось рисковать!}
{115}{}{Мне просто нужно поговорить с главным!}
{116}{}{Ты что тут, круче всех?}
{117}{}{Прошу прощения. Всего хорошего!}
{118}{}{Знаешь, что такое глупо? Глупо мне грубить, задница!}
{119}{}{Поднимайся. Пусть другие решат, насколько важно твое послание.}
{120}{}{Предупреждаю в последний раз!}
{121}{}{Подумаешь, ерунда какая...}
{122}{}{Но мне ОЧЕНЬ нужно поговорить с вашим главным!}
{123}{}{Ладно, ладно. Извини! Я уже ухожу.}
{124}{}{Знаешь, в чем твоя главная ошибка? Ты предупреждаешь. А я нет. Умри!}
{125}{}{[Готово]}