{100}{}{Дверь заперта. Вы никогда раньше не видели таких замков.}
{101}{}{Дверь закрыта, но не заперта.}
{102}{}{Вы пытаетесь открыть дверь, но безуспешно. Вы вдруг понимаете, что дверь заперта.}
{103}{}{Вам не удалось взломать замок.}
{104}{}{Вам удалось взломать замок.}
