{100}{}{Вы видите караванщика.}
{101}{}{Извини, я тебя не знаю. Если ищешь работу, поговори с Рутгером.}
{102}{}{Со мной говорить бесполезно, лучше спроси Рутгера.}
{103}{}{Похоже, у тебя все деньги ушли на наркоту? Ну-ну. Такими темпами ты скоро переедешь в Старый город - там таких торчков полно.}
{104}{}{Проспись и приходи, как протрезвеешь.}
{105}{}{Нужна еще работа?}
{106}{}{Конечно.}
{107}{}{Может быть, позже.}
{108}{}{Бу.}
{109}{}{Му!}
{110}{}{Мы уходим сегодня. Ты с нами?}
{111}{}{Ага!}
{112}{}{Не-а.}
{113}{}{Ыр-рва?}
{114}{}{Извини, но мы с тобой больше не работаем. Попробуй устроиться в другой караван, может, там тебя примут.}
{115}{}{Извини, прием окончен.}
{116}{}{У тебя слишком плохо с нервами. Лучше уходи отсюда.}
{117}{}{Все, иди!}
{118}{}{Чего ты хочешь? От тебя проблем, как от стихийного бедствия.}
{119}{}{Дай мне последний шанс, прошу! У меня нет выбора!}
{120}{}{А мне какое дело?}
{121}{}{Ладно. Пока.}
{122}{}{Хе.}
{123}{}{Му-у.}
{124}{}{Я не знаю, что там произошло, но мы потеряли целый караван! Тебе не стоило возвращаться, если не получилось его защитить.}
{125}{}{Даже не думай. Вали!}
{126}{}{Я сказал, вали!}
{127}{}{Чего ты хочешь?}
{128}{}{Заткнись и уйди с дороги!}
{129}{}{Мне нужна другая работа.}
{130}{}{Ничего.}
{131}{}{Хмы.}
{132}{}{Ы.}
{133}{}{Что? Какая наглость - бросить караван в пути и опять прийти за работой! Радуйся, что еще дышишь.}
{134}{}{Радоваться? Сам радуйся, что в морду еще не получил!}
{135}{}{Да ладно тебе! У меня были неотложные дела.}
{136}{}{Кто же знал, что уходить нельзя. Вроде никто не возражал.}
{137}{}{Говори по-человечески или проваливай.}
{138}{}{Торчок.}
{139}{}{Мы не нанимаем алкашей.}
{140}{}{Мы не нанимаем торчков.}
{141}{}{(The caravan driver is ignoring you.)}
{142}{}{Приходи, когда проспишься.}
{143}{}{Эй ты, ничтожество! Возвращайся в свой хлев.}
{144}{}{Никто не возражал? Нельзя отходить от каравана ни на шаг, даже если вы уже почти на месте. Тебя наняли на весь срок путешествия!}
{145}{}{Да, но меня никто не предупредил!}
{146}{}{Прошу прощения. Этого больше не повторится.}
{147}{}{Пошел ты!}
{148}{}{Это что, твой первый караван? Как тебя вообще наняли? Это очень сложная и ответственная работа, к ней нужно относиться серьезно! От тебя зависят жизни не только караванщиков, но и жителей города, в который мы едем!}
{149}{}{Ты, наверное, собой очень гордишься.}
{150}{}{Ну и что? Тебе медаль за это выдать?}
{151}{}{Дайте мне работу! Я хочу спасать жизни!}
{152}{}{Надеюсь! Это очень сложная и ответственная работа, к ней нужно относиться серьезно! От тебя зависят жизни не только караванщиков, но и жителей города, в котором нас ждут!}
{153}{}{Ты, наверное, собой очень гордишься.}
{154}{}{Ну и что? Тебе медаль за это выдать?}
{155}{}{Дайте мне работу! Я хочу спасать жизни!}
{156}{}{Конечно.}
{157}{}{Ну так что, я получу работу?}
{158}{}{Безмозглое создание!}
{159}{}{Мне пора. Пока!}
{160}{}{Да, это точно. Работа сложная и опасная! Мы рискуем своими жизнями ради тех, у кого все совсем плохо.}
{161}{}{???Вот тебе жизнь!}
{162}{}{Да? А как насчет несчастных, которые страдают здесь, у вас под носом?}
{163}{}{Все правильно. Так я получу работу?}
{164}{}{Что? Ты о ком вообще? Наркоманы не в счет. Они сами себе выбрали такую жизнь.}
{165}{}{Наверное, ты прав.}
{166}{}{Меня от тебя уже тошнит.}
{167}{}{Мне пора.}
{168}{}{???Что? Что ты говоришь?}
{169}{}{Конечно. Я добрый человек... в глубине души. Далеко в глубине.}
{170}{}{Разумеется. Так могу я получить работу или как?}
{171}{}{Пойду я отсюда.}
{172}{}{Вот это правильно! Жаль, работу я тебе не могу дать.}
{173}{}{After all that? Oh come on, can I please can I have another job?}
{174}{}{Ладно, тогда я продолжу спасать мир.}
{175}{}{Отлично. И по поводу работы больше не приходи!}
{176}{}{Ну пожалуйста! В этот раз я все сделаю правильно!}
{177}{}{И не подумаю!}
{178}{}{Ну ладно, дам тебе последний шанс. Караван уходит }
{179}{}{сегодня}
{180}{}{завтра}
{181}{}{on the}
{182}{}{8}
{183}{}{18}
{184}{}{28}
{185}{}{. Приходи, если хочешь идти с нами. Оплата стандартная - 400 крышек.}
{186}{}{Извини, но мне хватило прошлого раза.}
{187}{}{Отлично, какой маршрут выберешь?}
{188}{}{Привет! Караван будет здесь до завтра. Если тебе нужна эта работа, приходи.}
{189}{}{Нет, эта работа мне не нужна.}
{190}{}{Постараюсь.}
{191}{}{Ладно, увидимся.}
{192}{}{Га.}
{193}{}{Привет! Что-то ты рановато. Следующий караван отправится только }
{194}{}{8}
{195}{}{18}
{196}{}{28}
{197}{}{. Приходи, если хочешь заработать.}
{198}{}{Нет, эта работа мне не нужна.}
{199}{}{Постараюсь.}
{200}{}{Ладно. Пока.}
{201}{}{Га.}
{202}{}{Ладно. Мне все равно.}
{203}{}{Черт! Это мне все равно, притащишься ты сюда или нет! Куча народу ищет работу. Не придешь, и хрен с тобой!}
{204}{}{Не волнуйся, говорю. Если ты не сможешь, найдем еще кого-нибудь.}
{205}{}{Братство Стали}
{206}{}{L.A. Boneyard.}
{207}{}{Джанктаун}
{208}{}{А, ладно. Не так уж мне нужна эта работа!}
{209}{}{Отлично, караваны уходят сегодня. Оплата стандартная - 400 крышек. По какому маршруту пойдешь?}
{210}{}{Отлично. Следующий караван отправляется }
{211}{}{8}
{212}{}{18}
{213}{}{28}
{214}{}{. Приходи, если хочешь заработать 400 крышек.}
{215}{}{Ладно.}
{216}{}{Извини, но я не могу ждать так долго.}
{217}{}{Отлично! Я скажу остальным. Будь осторожнее, в последнее время в пустыне неспокойно.}
{218}{}{Команда готова. Выдвигаемся.}
{219}{}{О'кей, через минуту я соберу остальных.}
{220}{}{О'кей, сейчас я соберу людей, и вы отправитесь в Братство.}
{221}{}{Отлично, через пару минут вы отправляетесь в Братство.}
{222}{}{Все готово к отправлению! Держитесь подальше от гор.}
{223}{}{В Могильнике строгие порядки, будь осторожнее. Не влипни в переделку.}
{224}{}{Команда почти готова. Говорят, в Могильнике сейчас неспокойно, так что будь начеку.}
{225}{}{Итак, караван готов. Отправляйтесь в Могильник.}
{226}{}{Джанктаун находится близко. Как правило, караван доходит до него без проблем.}
{227}{}{Отлично, караван в Джанктаун готов к отправлению.}
{228}{}{Ладно, Джанктаун ждет. Выдвигаемся.}
{229}{}{Привет! Я так понимаю, ты хочешь охранять караваны. Странно, что Рутгер тебя нанял... Хотя у него могли быть свои причины. Мы отправляем караваны 8, 18 и 28 числа каждого месяца. У нас три маршрута - Братство Стали, Джанктаун и Могильник. Оплата 400 крышек на любом маршруте. Если вернешься обратно с караваном, заплатим еще 400.}
{230}{}{Тебе повезло, караван уходит сегодня.}
{231}{}{Караваны уходят завтра.}
{232}{}{До отправления еще }
{233}{}{ суток.}
{234}{}{Ну что, едешь?}
{235}{}{Берешься за работу? }
{236}{}{Караваны уходят сегодня.}
{237}{}{Караваны уходят завтра.}
{238}{}{До отправления еще }
{239}{}{ суток.}
{240}{}{Тебе нужна работа. Я тебе ее предлагаю. Интересует?}
{241}{}{Конечно.}
{242}{}{Не-а.}
{243}{}{Засунь свой караван знаешь куда?}
{244}{}{Пока не знаю. Я еще вернусь.}
{245}{}{Ы.}
{246}{}{Куда поедешь?}
{247}{}{Братство Стали.}
{248}{}{L.A. Boneyard.}
{249}{}{Джанктаун.}
{250}{}{Извини, у меня, оказывается, есть одно неотложное дело.}
{251}{}{Ладно, приходи }
{252}{}{8}
{253}{}{18}
{254}{}{28}
{255}{}{.}
{256}{}{У тебя проблема?}
{257}{}{Да. Эта проблема - ты, а мой кулак поможет ее решить.}
{258}{}{Будь осторожнее.}
{260}{}{Ты - моя проблема.}
{261}{}{Никаких проблем.}
{262}{}{Ну ладно. Приходи, если передумаешь.}
