{100}{}{[Дальше]}
{101}{}{[Готово]}
{102}{}{Вот урод! Ну держись, ублюдок!}
{103}{}{Дрянь! Ну держись, сучка!}
{105}{}{Значит, по-хорошему не хочешь?}
{106}{}{Да я просто хочу помочь!}
{107}{}{Я хочу спросить кое-что.}
{108}{}{Просто подлатайте меня, док, ладно?}
{109}{}{Сервис в вашей клинике хреновый.}
{110}{}{Док, мне нужно выпить! Есть хоть какой-нибудь алкоголь?}
{111}{}{??? Продолжай в том же духе, и доктор понадобится тебе!}
{112}{}{Ой! О-о-о! А-а!}
{113}{}{Чего тебе нужно? Идиоты, когда же вы научитесь стрелять? Я трачу свои силы на неудачников! В следующий раз целься как следует! И не давай им попасть в тебя!}
{114}{}{Их было слишком много!}
{115}{}{Ты кто, лекарь в сумасшедшем доме?}
{116}{}{Пожалуй, ты неплохая мишень для тренировки.}
{117}{}{Вот криворукое создание! Опять тебя ранили? Надеюсь, в следующий раз тебя наконец добьют!}
{118}{}{Спасибо за моральную поддержку, док.}
{119}{}{Спасибо, и тебе того же!}
{120}{}{Если меня убьют, ты умрешь следующим.}
{121}{}{В чем проблема, а? Может, тебе наркоз вколоть, безмозглое существо?}
{122}{}{Вы уже многим его вкололи, док?}
{123}{}{Даже не пытайся.}
{124}{}{Ты что, с ума сошел? Я не буду спать!}
{125}{}{Черт, почему вокруг столько идиотов? Зачем ты меня беспокоишь? У меня куча дел! Тебя надо лечить?}
{126}{}{Чем же это ты так занят?}
{127}{}{Конечно, док.}
{128}{}{Не сейчас.}
{129}{}{Каков диагноз, док?}
{130}{}{Я не справочное бюро! Отвали от меня со своими вопросами!}
{131}{}{Отлично! Чини вас тут, латай! Придурки!}
{132}{}{Про вас рассказывают ужасные вещи...}
{133}{}{Враги Создателя стремятся опорочить имя верного служителя.}
{134}{}{Вы дали клятву, док. Так что делайте свою работу.}
{135}{}{Нет, не надо. Я вам не доверяю.}
{136}{}{Лечи меня, или умрешь!}
{137}{}{Ну-ка, вот так...}
{138}{}{Черт!}
{139}{}{Ха-ха-ха!}
{140}{}{Ты кричишь как девка. Ха-ха-ха!}
{141}{}{Мужская работа не для тебя! Ха-ха-ха!}
{142}{}{Иди к черту! Тебя лечить или ты останешься калекой?}
{143}{}{Вот пьянь! Иди к Свечению и попей там водички из лужи! Алкоголики! Наркоманы!}
{144}{}{Однажды тебе понадобится помощь, а доктора не будет. Психованная сволочь! Ты хочешь, чтобы тебя вылечили? Может, тебе лоботомию сделать?!}
{145}{}{Fine. Do it and shut up!}
{146}{}{Иди к дьяволу.}
{147}{}{Заткнись и осмотри меня.}
{148}{}{Тупое животное! У тебя мозгов не хватает даже на то, чтобы боль почувствовать! Ты глупее, чем бактерия!}
{149}{}{Да у тебя не то что мозгов мало, у тебя вообще крыша поехала!}
{150}{}{Ха-ха! У тебя и правда мозгов нет! Я только что вколол тебе смертельный яд! Ха-ха-ха!}
{151}{}{Будет очень больно!}
{152}{}{А-а-а-а!}
{153}{}{Ты визжишь как свинья! Ха-ха-ха!}
{154}{}{Воплощение кретинизма! Дело не в количестве, а в качестве! Детям ночи все равно, сколько врагов им противостоит! Поплачься лучше своей мамочке! Так что, тебя лечить или как?}
{155}{}{Заткнись, или я тебе связки ампутирую! Ха-ха-ха! Так что, тебя лечить?}
{156}{}{Я доктор, а не массовик-затейник! Тебе лечение нужно или как?}
{157}{}{Я прямо весь дрожу! Так ты хочешь, чтобы тебе полегчало?}
{158}{}{Да ради бога. Только не морочь мне голову!}
{159}{}{Ни за что. Здесь должен быть нормальный доктор.}
{160}{}{А в морду не хочешь?}
{161}{}{Дети ночи это любят. Я иногда даю им наркотики. Никто не обращает внимания на доктора Ву. Потому что они все уроды! Так что, тебя лечить?}
{162}{}{Подлатайте меня, док!}
{163}{}{Если уж Дети ночи тебе не доверяют, я и подавно не буду. Пойду я отсюда!}
{164}{}{Тупица! Чада Собора обеспечивают доктора Ву работой! Так что, тебя лечить?}
{165}{}{Теперь самое интересное!}
{166}{}{Ну-ка, вот так...}
{167}{}{What a dork! I've heard less screaming from children! Ha ha ha!}
{168}{}{Сучка развопилась! Ха-ха-ха!}
{169}{}{Дрянь безмозглая! Я занят, а ты меня беспокоишь! Черт тебя побери! Убирайся отсюда, скотина! Живо!}
{170}{}{У тебя здоровья как у брамина, а вот с мозгами проблемы! Убирайся отсюда и не жалуйся!}
{171}{}{У тебя тут пара царапин. Вылечу, если будешь лежать спокойно!}
{172}{}{Как ты обращаешься со своим телом, безмозглая скотина? Я могу тебя вылечить, но лучше бы навсегда избавить тебя от страданий!}
{173}{}{Не сейчас.}
{174}{}{Ладно. Надеюсь, уже вечером я приступлю к вскрытию!}
{175}{}{А-а! Твою мать...}
{176}{}{А теперь вали отсюда и не возвращайся!}
{177}{}{Ладно, вылечу!}
{178}{}{Это должно помочь!}
{179}{}{Тогда вали отсюда, уродина! Я еще повеселюсь на твоих похоронах.}
{180}{}{Эй, ты в своем уме? Как ты смеешь беспокоить доктора Ву, кретинское отродье!}
{181}{}{У тебя тут пара царапин. Вылечу, если будешь лежать спокойно!}
{182}{}{Пять сломанных костей, большие потери крови. Я всегда говорил, недостаток ума опасен для здоровья! Тебя вылечить?}
{183}{}{Главное, не покалечьте еще сильнее, док.}
{184}{}{И-ду.}
