{100}{}{You see: Snake, a member of the Blades.}
{101}{}{You see: Dolgan, a member of the Blades.}
{102}{}{}
{103}{}{}
{104}{}{Вы видите члена банды Клинков.}
{105}{}{Вы видите члена банды Клинков.}
{106}{}{Возможно, это Букс.}
{107}{}{Возможно, это Скарз.}
{108}{}{Возможно, это Канонир.}
{109}{}{Возможно, это Жила.}
{110}{}{Возможно, это Молот.}
{111}{}{Возможно, это Бритва.}
{112}{}{Get lost! This is for real fighters only.}
{113}{}{So, you think you can take on the Regulator wimps? Here, I'll teach you how to use that blade.}
{114}{}{You seem to have gotten better. Now go kick Caleb's butt into next year for me.}
{115}{}{Отлично получилось с Потрошителями! Чем могу помочь?}
{116}{}{Можешь еще потренировать меня?}
{117}{}{How can I get through to the Gun Runners?}
{118}{}{Ничем, спасибо.}
{119}{}{Конечно. Но на это уйдет целый день. Тебя это устроит?}
{120}{}{Да.}
{121}{}{Нет.}
{122}{}{Вот и все. Теперь ты лучше владеешь холодным оружием. Удачи!}
{123}{}{Конечно. Приходи еще, если захочешь потренироваться.}
{124}{}{Кажется, кто-то нарывается на неприятности... Ладно. У них там есть защитный ров, но он не сплошной. Найди место, где можно перебраться, и беги изо всех сил!}
{125}{}{Спасибо.}
