{100}{}{Вы видите странствующего торговца азиатской внешности.}
{101}{}{Вы видите Дака, странствующего купца.}
{102}{}{Привет! Меня зовут Дак, я иду торговать в Шэйди Сэндс. Может, и ты что-нибудь посмотришь из моих товаров?}
{103}{}{Что ты продаешь?}
{104}{}{Ты часто бываешь в Шэйди Сэндс?}
{105}{}{Ырг!}
{106}{}{Я покажу тебе.}
{107}{}{Да, Шэйди Сэндс - часть моего обычного маршрута. Если хочешь, пойдем с нами.}
{108}{}{Отлично, пошли!}
{109}{}{Нет, спасибо.}
# Old response to 114 "None of your business" was 110 "Oh, sorry -- didn't realize you were that stupid."
{110}{}{Hmph! I didn't realize you're an asshole. Go take your bullshit somewhere else.}
{111}{}{Туда примерно день пешим ходом. Вперед!}
{112}{}{SHADYW.MAP}
{113}{}{Немногие решаются путешествовать в одиночку. Кто ты?}
{114}{}{Не твое дело.}
{115}{}{Я }
{116}{}{.}

#TRANSLATION NOTE: 117 & 132 are for Stupid characters,
# they are shouting their name as a greeting. For example "Me John!"
{117}{}{Me }
{132}{}{!}

{118}{}{Привет еще раз! Чем могу помочь?}
{119}{}{Можно пойти с вами в Шэйди Сэндс?}
{120}{}{Что ты продаешь?}
{121}{}{Ничем, спасибо.}
{122}{}{Чего ты хочешь?}
{123}{}{Нет, ничего.}
{124}{}{Что ты продаешь?}
{125}{}{Uh?}
{126}{}{Если путешествуешь в одиночку, будь осторожнее. В последнее время из Шэйди Сэндс пропадают люди.}
{127}{}{Эй, мне про тебя рассказывали. Спасение девушки от налетчиков - твоих рук дело, да? Отличная работа.}
{128}{}{Oh, sorry. I didn't realize you're an idiot.}
{129}{}{Thanks, see you around.}
{130}{}{Rumph!}
{131}{}{Erf!}
