{100}{}{Вы видите тощего взъерошенного мальчишку.}
{101}{}{Не хочу с тобой разговаривать. Уходи.}
{102}{}{Зачем тебе оружие? У нас нет ничего, даже рыбы!}
{103}{}{Привет. Чего надо?}
{104}{}{Как рыбка, клюет?}
{105}{}{У меня заканчиваются припасы...}
{106}{}{Не попадалось в последнее время чего-нибудь необычного?}
{107}{}{Хочешь, расскажу про охоту на радскорпионов?}
{108}{}{Р-ранк!}
{109}{}{Привет! Это ты странствуешь по пустыне и помогаешь людям? Ты, наверное, знаешь кучу интересных историй!}
{110}{}{Откуда ты?}
{111}{}{Приветик! Хорошо хоть тебе хватает ума не ловить здесь рыбу. Как дела?}
{112}{}{Не знаю. Мы с отцом уже сто лет шатаемся по пустыне. У нас был друг, охотник на скорпионов, но он чокнулся, и нам пришлось его убить, а потом мы...}
{113}{}{Хм, наверное, лучше об этом не рассказывать.}
{114}{}{Расскажи мне об отце.}
{115}{}{Скорпионы вам не мешают?}
{116}{}{Хреново. Извини, я не должен произносить это слово. Отец говорит, что так выражаются только безмозглые простофили и тупые неудачники. Сам он всегда старается говорить правильно.}
{117}{}{По-моему, твой отец прав.}
{118}{}{Об этом тебе лучше с отцом поговорить.}
{119}{}{Я видел такую большую штуку вроде гигантского паука с двумя головами, причем одна голова была человеческая. Отец говорит, это мне привиделось из-за радиации. Радиоактивная вода сильно действует на мозги.}
{120}{}{Еще что-нибудь знаешь?}
{121}{}{Что еще за "Р-ранк"?}
{122}{}{Конечно!}
{123}{}{Самое неприятное - ждать, пока скорпион попадет в засаду.}
{124}{}{Самое неприятное - догонять убегающего скорпиона, чтобы добить его!}
{125}{}{Самое неприятное - получить в морду скорпионьим жалом.}
{126}{}{Знаешь историю о том, как налетчики наткнулись на гнездо радскорпионов? Их всех сожрали заживо, кроме одного - ему сжевали пол-лица, но он убежал!}
{127}{}{Ого, вот это круто!}
{128}{}{Ну, он болтливый и скучный. Может, он мне и не отец на самом деле. Скорее всего, он похитил меня еще младенцем. Но, с другой стороны, он меня вырастил. Так что, пожалуй, я его люблю.}
{129}{}{Они огромные и опасные. Никто с ними не может справиться. Отец говорит, что раньше были герои, которые странствовали по пустыне и охотились на скорпионов, но это время уже прошло.}
{130}{}{Какие еще герои?}
{131}{}{Ага, взрослые всегда друг с другом соглашаются. Это глупо.}
{132}{}{Раньше с нами еще бродил Большой Генри. Он был сильнее, чем мы с отцом, но однажды он спятил и начал меня душить. Отцу пришлось его пристрелить!}
{133}{}{Твой отец хорошо стреляет?}
{134}{}{Кто такой Большой Генри?}
{135}{}{О, круто! Но мне надо ловить рыбу. А то, если улова не будет, нам придется съесть тебя!}
{136}{}{Разные. Роджер Максон - парень, который основал Братство Стали, он был классным охотником на скорпионов. Я еще чуть-чуть подрасту и тоже вступлю в Братство!}
{137}{}{А что, неплохо.}
{138}{}{Попасть в Братство очень трудно. Дорога к ним долгая и опасная.}
{139}{}{Неплохо. Однажды он всадил радскорпиону пулю промеж глаз с тридцати метров! Но в тот раз ему повезло, конечно.}
{140}{}{Он был налетчиком с юга. Ему больше нравилось бродить по пустыне, чем жить с людьми. Он был классным парнем, но потом спятил, и... м-м... неважно.}
{141}{}{Да... Я тоже буду героем, как он. Это точно!}
{142}{}{Думаешь, нам тут легко живется? Я-то трудностей не боюсь, поэтому и не ухожу. И потом, безопасных мест все равно в пустыне нет. Я просто жду, когда повзрослею и смогу начать самостоятельную жизнь.}
{143}{}{Видел когда-нибудь, как радскорпион нападает на человека?}
{144}{}{Раз двенадцать, наверное...}
{145}{}{О да.}
{146}{}{Похожу, я простудился...}
{147}{}{Скорее! Я умираю от голода!}
{148}{}{Я уже так давно ничего не вылавливал, что забыл вкус рыбы.}
{149}{}{Пап, ты слышал...}
