{100}{}{Вы видите Сэвил, охранника Последователей.}
{101}{}{Вы видите Нэнси, охранника Последователей.}
{102}{}{Вы видите Джелиссу, охранника Последователей.}
{103}{}{Вы видите Линду, охранника Последователей.}
{104}{}{Вы видите Джессику, охранника Последователей.}
{105}{}{Вы видите Шеннон, охранника Последователей.}
{106}{}{Вы видите Мохандки, охранника Последователей.}
{107}{}{Вы видите Перси, охранника Последователей.}
{108}{}{Вы видите Генри, охранника Последователей.}
{109}{}{Вы видите Гериона, охранника Последователей.}
{110}{}{Кто входит в залы Последователей?}
{111}{}{А?}
{112}{}{Меня зовут }
{113}{}{. Я иду с миром.}
{114}{}{Меня зовут }
{115}{}{. Ваша гибель.}
{116}{}{Кто такие Последователи?}
{117}{}{Хорошо. Вижу, ты медленно соображаешь. Ты кто?}
{118}{}{Моя }
{119}{}{. Твоя умирает.}
{120}{}{Моя }
{121}{}{. Моя помочь.}
{122}{}{Моя убивает!}
{123}{}{Моя }
{124}{}{. Моя идти.}
{125}{}{Хочешь помочь? Тогда поговори с Николь или Джейком. У них есть время на общение с такими заторможенными.}
{126}{}{O'кей. Только не доставляй нам проблем.}
{127}{}{Ты хочешь остановить зло, которое несут Чада Собора?}
{128}{}{Да. Пора избавиться от этих негодяев.}
{129}{}{Нет. Я лучше остановлю вас.}
{130}{}{Кто эти Чада?}
{131}{}{Зачем мне убивать детей?}
{132}{}{Замечательно! Поговори с Николь. Она скажет, чем ты можешь нам помочь.}
{133}{}{Чада - группа оккультистов, которые поклоняются богу тьмы. По-моему, от них просто исходит зло.}
{134}{}{Я их убью.}
{135}{}{Не знаю. Они ведь довольно сильны.}
{136}{}{Чем я могу помочь?}
{137}{}{Забудьте! Я не буду вам помогать.}
{138}{}{Они очень сильны. Но, думаю, ты сможешь пробраться во вражеское логово и помочь нам уничтожить их.}
{139}{}{Хорошо, я сделаю это.}
{140}{}{Нет. Я не стану вам помогать.}
{141}{}{Как хочешь. Только когда они подчинят себе всю пустыню, будет уже поздно.}
{142}{}{Поговори с Николь, она все тебе расскажет.}
{143}{}{Спасибо. Прощай.}
{144}{}{Нет, мы не воюем с детьми. Я говорю о Чадах Собора - это последние мерзавцы.}
{145}{}{Тогда, конечно, я с ними расправлюсь.}
{146}{}{А, понятно. Но я все равно не буду вам помогать.}
{147}{}{Что ты знаешь об этих Чадах?}
{148}{}{Мы - Последователи Апокалипсиса. Мы хотим принести мир в пустынные земли.}
{149}{}{Звучит красиво. Удачи вам!}
{150}{}{Как вы собираетесь это сделать?}
{151}{}{Боюсь, это невозможно.}
{152}{}{Мы хотим, чтобы люди были более терпимы к тем, кто пострадал из-за человеческой тяги к саморазрушению.}
{153}{}{Good luck with that.}
{154}{}{За всю свою историю человечество так и не достигло этой терпимости. Из-за чего, по-твоему, началась Война?}
{155}{}{По-моему, чушь собачья.}
{156}{}{Это верно. У людей слишком много предрассудков, однако надежда все равно остается.}
{157}{}{Что ж, удачи вам!}
{158}{}{Пожалуй, это так. Не буду лишать тебя надежды - лучше лишу жизни.}
{159}{}{Твое мнение не имеет значения. Прощай.}
{160}{}{Как цинично! Видимо, у тебя есть на то причины. Но я надеюсь, мы все же придем к взаимопониманию.}
{161}{}{Удачи вам. До свидания.}
{162}{}{По слухам, Чадам стали известны некоторые наши тайны. Интересно, как?}
{163}{}{Видимо, у вас завелся шпион.}
{164}{}{Очень просто. Это я поставляю им ваши секреты.}
{165}{}{Не может быть! Как они могли что-то узнать?}
{166}{}{В самом деле? Мне тоже так казалось, но у меня не было подтверждения.}
{167}{}{Как ты думаешь, кто бы это мог быть?}
{168}{}{??? Приятно слышать. Спасибо тебе!}
{169}{}{Ты двойной агент!}
{170}{}{??? Трудно сказать. Думаю, у этого человека должен быть доступ к секретным сведениям и право покидать здание. Возможно, это послушник или разведчик.}
{171}{}{Спасибо. До свидания.}
{172}{}{Николь будет рада узнать, что благодаря мне агент мертв.}
{173}{}{Наверное, это так. Спасибо за помощь!}
{174}{}{Я думаю, что ты двойной агент. Пытаешься меня провести... Но теперь ты умрешь!}
{175}{}{Шпион мертв, отлично! Теперь наши шансы на победу возрастут.}
{176}{}{Удачи!}
{177}{}{I can help train you to become a more efficient fighter.}
{178}{}{Правда? Было бы здорово.}
{179}{}{There you go. Maybe that will help you, if you get into a fight.}
