{100}{}{Вы видите Уолтера, послушника Последователей.}
{101}{}{Вы видите Николаса, послушника Последователей.}
{102}{}{Вы видите Уильяма, послушника Последователей.}
{103}{}{Вы видите Мэтью, послушника Последователей.}
{104}{}{Вы видите Джона, послушника Последователей.}
{105}{}{Вы видите Меллени, послушника Последователей.}
{106}{}{Вы видите Дженн, послушника Последователей.}
{107}{}{Вы видите Лори, послушника Последователей.}## was Lori, then Gloria
{108}{}{Вы видите Сару, послушника Последователей.}
{109}{}{Вы видите Кристин, послушника Последователей.}
{110}{}{Пусть твой путь в пустыне будет счастливым.}
{111}{}{Мне уже не терпится сразиться с Чадами.}
{112}{}{Если мне не удастся стать богословом, я буду книжником.}
{113}{}{Я хочу стать богословом.}
{114}{}{Людям пора уже прекратить вражду.}
{115}{}{Интересно, когда же наконец наступит мир.}
{116}{}{Говорят, кто-то передает наши знания Чадам.}
{117}{}{Дети ночи меня пугают до смерти.}
{118}{}{Только разведчики могут выходить наружу после заката.}
{119}{}{Интересно, где книжники берут новые книги.}
{120}{}{Мы потеряли много людей из-за этого шпиона.}
{121}{}{Нил думает, что шпион - кто-то из новеньких.}
{122}{}{Надо найти шпиона как можно скорее.}
{123}{}{Когда же начнется сражение?}
{124}{}{Если бы Амбер нас увидела, ???она была бы в ярости.}
{125}{}{Нил рад, что ты учишь нас.}
{126}{}{Я в одиночку справлюсь со всем Собором!}
