{100}{}{Вы видите члена банды Черепов.}
{101}{}{Эй! Ты что делаешь?!}
{102}{}{Этот район контролируют Черепа. Уходи.}
{103}{}{Одолжи немного денег, а?}
{104}{}{Что смотришь?}
{105}{}{Иди отсюда.}
{106}{}{Zzzzzzzz}
{107}{}{Ох, ну и жара сегодня.}
{108}{}{Хочу есть.}
{109}{}{Надо чем-нибудь заняться.}
{110}{}{Может, набить кому-нибудь морду?}
{111}{}{Пора уже развлечься!}
{112}{}{Yawn...}
