{100}{}{Вы видите охранника-гуля.}
{101}{}{Уходи! Тебе здесь нечего делать.}
{102}{}{Ладно. Приятно было познакомиться.}
{103}{}{А?}
{104}{}{Я на посту. Если тебе нужен Сет, он внутри.}
{105}{}{Закрыто. Приходи, как стемнеет.}
{106}{}{Спасибо.}
{107}{}{А?}
{108}{}{Я же сказал, уходи! Ты нам здесь ни к чему.}
{109}{}{Точно.}
{110}{}{Ум-м!}
{111}{}{Двери не открываются до наступления темноты.}
{112}{}{Мне нужно войти внутрь. Пропусти меня, пожалуйста!}
{113}{}{Hmm, okay.}
{114}{}{Ух-х!}
{115}{}{Well, I guess it can't hurt. Go ahead, I'll unlock the door for you.}
{116}{}{Я бы помог, но Сет мне за это голову оторвет. Знаешь, я должен подчиняться приказам начальства...}
{117}{}{Да, я понимаю. Спасибо.}
{118}{}{Thanks!}
{119}{}{You were warned. Prepare to die.}
{120}{}{The ghoul ignores you.}
