{100}{}{Не страшно.}
{101}{}{Мне страшно.}
{102}{}{Я на посту. Уходи.}
{103}{}{Не создавай проблем.}
{104}{}{Пончики есть?}
{105}{}{Тебе когда-нибудь казалось, что за тобой следят? Что тобой кто-то управляет? Смотрит на тебя откуда-то сверху?}
{106}{}{Уже знаешь про Билла? Беднягу искромсал радскорпион.}
{107}{}{Как думаешь, ты справишься с радскорпионом?}
{108}{}{На вид ты ничего выдающегося собой не представляешь.}
