{100}{}{Вы видите Гюнтера.}
{101}{}{Вы видите сурового мужчину лет тридцати.}
{102}{}{Добро пожаловать в мое скромное жилище. Чем могу помочь?}
{103}{}{Что ты знаешь о Хабе?}
{104}{}{Где тут продают оружие и боеприпасы?}
{105}{}{Что ты здесь делаешь?}
{106}{}{Кто здесь следит за порядком?}
{107}{}{Да, что тебя интересует?}
{108}{}{Это самый крупный город из всех, что я видел. Центральная часть находится к югу отсюда, а окраины - по разные стороны центра.}
{109}{}{Где бы мне купить снаряжение?}
{110}{}{Я ищу работу.}
{111}{}{Можно еще вопрос?}
{112}{}{Спасибо за информацию. Всего хорошего.}
{113}{}{Я все покупаю у Митча, его магазин напротив "Мальтийского сокола", к югу отсюда.}
{114}{}{Иногда я помогаю охранять караваны. Мне нравится работать с Дальнобойщиками, хотя остальные караванщики тоже ничего. Если хочешь, зайди в контору к кому-нибудь из них, спроси насчет работы.}
{115}{}{Я в основном покупаю пушки в лавке у Бет. Там неплохой выбор.}
{116}{}{А если мне нужно что-нибудь экзотическое?}
{117}{}{Мне сделают скидку, если я упомяну твое имя?}
{118}{}{Говорят, в Старом городе один парень торгует оружием помощнее.}
{119}{}{Вряд ли. Ее парень - не я, а Сид, охранник. Насчет скидки поговори лучше с Бутчем, он руководит Дальнобойщиками и владеет этой лавкой.}
{120}{}{Так, занимаюсь всем понемногу. Охраняю караваны, помогаю фермерам.}
{121}{}{Шериф Грин обычно сидит в полицейском участке, а его помощник Фрай дежурит на улице.}
{122}{}{М-м-м!}
{123}{}{Прости, но я тебя не понимаю. Обратись к доктору Торндайку, он живет среди Чад Собора.}
