{100}{}{Вы видите Иеремию, посланника Чад.}
{101}{}{Вы видите Чадо. Он выглядит задумчиво.}
{102}{}{Извини, брат, ты меня напугал. Как я могу послужить Создателю?}
{103}{}{Мудро! ??? Quip!}
{104}{}{Что ты делаешь?}
{105}{}{Ах, да, тренирующийся супермутант. Я займусь своими делами.}
{106}{}{Если ты этого не знаешь, значит это не твое дело. Если ты будешь интересоваться тем, что знать тебе не следует, мне придется составить на тебя рапорт нашим наблюдателям. Тебе лучше бы это знать.}
{107}{}{Я очень важная персона.}
{108}{}{Извини за беспокойство.}
{109}{}{Я здесь недавно.}
{110}{}{Ты вообще кто, чтобы вопросы мне тут задавать?! Тебе повезло, что я не доложил о тебе Священному Пламени!!}
{111}{}{Передача рапортов, конечно.}
{112}{}{Рапорты о чем? Если позволишь.}
{113}{}{Классную работу ты делаешь.}
{114}{}{Это все. Спасибо.}
{115}{}{Хорошо. Мир тебе.}
{116}{}{Я прошу прощения. Я могу как-либо послужить?}
{117}{}{А что это ты делаешь?}
{118}{}{Ты можешь начать с ответа на мой вопрос.}
{119}{}{Ты можешь умереть!}
{120}{}{Охрана!!!}
{121}{}{Ты очевидно не отсюда. Кто ты?}
{122}{}{На самом деле, я из Убежища. И мне нужно поговорить с создателем.}
{123}{}{Эм... Дорфеус... гм... я от Морфеуса.}
{124}{}{Я - Локи. Послушник с юга.}
{125}{}{Нет, я не отсюда. Но я знаю, где должна быть эта пуля... в твоей башке.}
{126}{}{Я доставляю рапорты о чистоте человека по близлежащим областям. Но ты бы должен это знать. [смотрит с подозрением] А кто ты?}
{127}{}{Меня отправил Морфеус, у меня послание Создателю.}
{128}{}{Не твое дело, кто я такое... отвечай на мои вопросы!}
{129}{}{Тебе не нужно знать, кто я, таково желание Создателя.}
{130}{}{Ты посмел спросить, кто я? Глупец, мне следует немедленно поразить тебя прямо на этом самом месте.}
{131}{}{Довольно странно... Я никогда о тебе не слышал.}
{132}{}{Меня отправил Морфеус, у меня послание Создателю.}
{133}{}{Я из высшего ордена. Лишь Создатель и Морфеус знают обо мне, чтобы обеспечить мою безопасность. Но меня призвал назад приказ Создателя.}
{134}{}{Прошу, прости меня. Я извиняюсь за то, что посмел задавать тебе вопросы. Прошу, продолжай свой путь. И если я понадоблюсь, лишь дай мне знать.}
{135}{}{Я не знаю кто ты, но ты посторонний. Охрана!!!}
{136}{}{Кто ты, и что ты здесь внизу делаешь?}
{137}{}{Просто заблудившийся верующий.}
{138}{}{Морфеус отправил меня с посланием к Создателю.}
{139}{}{Ищу одинокую душу, чтобы отправить ее на небеса.}
{140}{}{Урк!}
{141}{}{Тебе запрещено здесь находиться. Только слуги и более высшие звания могут здесь находиться. Лучше возвращайся в Собор.}
{142}{}{Я прошу прощения за доставленные неприятности.}
{143}{}{Позволь задать пару вопросов, прежде чем я уйду.}
{144}{}{Хорошо, но не доводи до того, чтобы я тебе голову проломил.}
{145}{}{Морфеус не послал бы такие отбросы как ты на такое задание. Охрана!!}
{146}{}{Тупица! Тебе запрещено здесь находиться. Немедленно возвращайся в Собор!}
{147}{}{Акай.}
{148}{}{Хынх.}
{149}{}{Неа.}
{150}{}{Я доставляю создателю записи. Это все, что тебе нужно знать, дитя. А теперь тебе пора уходить.}
{151}{}{Я уже ухожу.}
{152}{}{Я хочу задать еще пару вопросов.}
{153}{}{Я уйду. Я уйду. Но не раньше чем вышибу тебе мозги.}
{154}{}{Как тебе удалось проникнуть сюда?! Что ты тут вынюхиваешь?}
{155}{}{Просто хотелось задать тебе пару вопросов.}
{156}{}{Нет, тебе нельзя ничего спрашивать. Уходи сейчас же.}
{157}{}{Стой! Тебе нечего здесь находиться!}
{158}{}{Доо?}
{159}{}{Простите. Здесь так легко заблудиться. Уже ухожу.}
{160}{}{Но мне есть чего здесь делать. Морфеус отправил меня с заданием к Создателю.}
{161}{}{Сюда спустился какой-то подозрительный тип. Вы его не видели?}
{162}{}{Нет. Убивать это мое дело, а дело - это хорошо.}
{163}{}{Нет, я никого не видел. Как он выглядел?}
{164}{}{Не важно. Похоже, он сбежал.}
{165}{}{Это был невысокий зеленый человечек.}
{166}{}{Он был примерно твоего роста, но на нем была кожаная куртка... что у тебя там под мантией?}
{167}{}{Выглядел он так же как и ты, дерьмо вместо мозгов!}
{168}{}{Эм... Я... Я... Ты же не думаешь что это и пр... правда я?  Это же смешно. Я бы никогда!}
{169}{}{Oк. Я пойду тогда, но ты мне дай знать, если узнаешь или увидишь что-нибудь...}
{170}{}{Да! Точно, это был ты! На землю, ноги в стороны!}
{171}{}{Нет, Не думаю, что это ты, но я хотел бы задать тебе пару вопросов?}
{172}{}{Да, брат мой. Чем я могу служить?}
{173}{}{Да, сестра моя. Чем я могу служить?}
{174}{}{Что ты здесь делаешь, брат?}
{175}{}{Служи Создателю. Это все, о чем я прошу. Брат.}
{176}{}{Извини, мне не ты нужен. Вы все выглядите одинаково в этих мантиях.}
{177}{}{Послужи мне своей смертью, уродливый ублюдок!}
{178}{}{Я доставляю рапорты о чистоте человека по близлежащим областям.}
{179}{}{Это все. Спасибо.}
{180}{}{Я хотел бы еще кое о чем спросить тебя, брат.}
{181}{}{Да, и это очень важная работа. И понимаешь ли ты всю важность своего долга перед Создателем и всеми нами?}
{182}{}{Да, конечно. Ведь я один из тех кто приносит Создателю новости о новых незапятнанных людях, нетронутых радиацией. Я тот, кто принес Создателю последнюю весть о возможном затерянном Убежище. Там все еще могут быть люди с чистой наследственностью.}
{183}{}{Да, брат мой. Ты правда понимаешь. Спасибо. Это все.}
{184}{}{Я бы хотел тебя еще кое о чем спросить.}
{185}{}{Ты бы не заметил человека с чистой наследственностью, даже если бы он стоял прямо перед тобой. Идиот.}
{186}{}{Ты бы не заметил человека с чистой наследственностью, даже если бы он стоял прямо перед тобой. Идиот.}
{187}{}{Ты очень странно себя ведешь. Я не верю, что ты говоришь правду. Охрана!}
{188}{}{Ты задаешь слишком много вопросов. Я не верю, что ты говоришь правду. Охрана!}
{189}{}{Эй! Я же сказал, что тебе сюда нельзя! Охрана!}
{190}{}{Ты задаешь слишком много вопросов. Ты кто такой?}
{192}{}{Извини, сестра. Ты напугала меня. Как я могу послужить Создателю?}
