{100}{}{Вы видите Кенни, помощника шерифа.}
{101}{}{Если у вас дело к полиции Хаба, поговорите с шерифом Грином. Я всего лишь веду его дела, когда его нет на месте.}
{102}{}{Не могу поверить, что шериф на самом деле мертв.}
{103}{}{Вот ты где.  Я все ждал, когда ты вернешься. Мы тут слышали, что шерифа убили во время стычки. Трудно поверить, что его на самом деле нет. Он был мне как отец.}
{104}{}{Шериф дал мне указания, что делать, в случае, если он не вернется. Он просил отдать тебе оставшуюся часть твоей награды. По-моему, это 1000 крышек  [Заместитель протягивает вам 1000 крышек]}
{105}{}{Город должен сказать спасибо. Жаль что Шериф не смог тебя сам лично поблагодарить. Счастливо.}
{106}{}{О, Боже! Они убили Кенни! Ублюдки!}
