{100}{}{Осталось }
{101}{}{ сек.}
{102}{}{Вот какой останется от тебя след. (небольшая горстка пепла)}
{104}{}{Осталось }
{105}{}{ сек.}
{106}{}{Вот какой останется от тебя след. (небольшая горстка пепла)}
{108}{}{Осталось }
{109}{}{ сек.}
{110}{}{Вот какой останется от тебя след. (небольшая горстка пепла)}
