{100}{}{Чего ты хочешь?}
{101}{}{Эй, ты собираешься съесть эту мертвую крысу?}
{102}{}{Что?}
{103}{}{Я ищу своего пса, Элвиса. Он где-то здесь поблизости.}
{104}{}{Привет.}
{105}{}{Ар-р!}
{106}{}{Гр-р!}
{107}{}{Я обглодаю твои кости!}
{108}{}{Смерть! Смерть! Смерть!}
{109}{}{Эй, ты знаешь, что Сета прихлопнули?}
{110}{}{Сет мертв. Сет мертв. Сет мертв...}
{111}{}{Воды хватит на всех. Сет в этом убедился.}
{112}{}{Я слышал, что мутанты бегут из города.}
{113}{}{Без мутантов здесь значительно лучше.}
{114}{}{Привет.}
