{100}{}{Паладин}
{101}{}{День добрый, Посвященный.}
{102}{}{Поговори с Врии.}
{103}{}{Врии сидит вон там. Она наверняка с тобой поболтает.}
{104}{}{Мне придется выкроить время между обходами и тренировками, чтобы нагнать учебу. А то я как-то поотстал.}
{105}{}{Поддерживай свою физическую и интеллектуальную форму, Посвященный.}
{106}{}{Мы, писцы, конструируем технику, оружие и боеприпасы. Это очень интересно.}
{107}{}{Да, быть Паладином - это не только сражаться, сын мой.}
{108}{}{Быть паладином не означает лезть в драку, сестра.}
