{100}{}{Паладин}
{101}{}{Будь начеку, Посвященный!}
{102}{}{Прекрасно выглядишь. Так держать.}
{103}{}{Приветствую тебя, Посвященный, все вокруг спокойно.}
{104}{}{Привет, Брат.}
{105}{}{.}
{106}{}{Извини, я на посту.}
{107}{}{Поговори с Талусом или Максоном.}
{108}{}{Если тебе интересна техника, поговори с Врии, она в библиотеке.}
{109}{}{Я хочу стать таким, как Ромбус.}
{110}{}{Лучше бы я тренировался сейчас. Работать охранником - тратить время зря.}
{111}{}{Врии - мой кумир.}
{112}{}{Марко!}
{113}{}{Поло!}
