{100}{}{Убирайся!}
{101}{}{Я слышал о тебе плохие слова, они правдивы?}
{102}{}{Привет.}
{103}{}{Я тут живу, хочешь позависать тут какое-то время?}
{104}{}{Хммм, ути-пути...}
{105}{}{Надеюсь, ты не выкинешь меня отсюда.}
{106}{}{Нет.}
{107}{}{Довольно странный способ начинать разговор.}
{108}{}{Ым-м.}
{109}{}{Да ладно, если хочешь, оставайся тут на время. Я думаю, мы тут в безопасности.}
{110}{}{Да уж, в наши дни нужно быть осторожным. Надеюсь, у тебя жизнь получше, чем у меня.}
{111}{}{Ну, это правда. После того, что случилось с моими друзьями, мне приходится защищать свою территорию. Надеюсь, что ты не собираешься меня убивать.}
{112}{}{Нет, я тебе не сделаю больно. Ну, не очень больно.}
{113}{}{С чего вдруг?}
{114}{}{Бей!}
{115}{}{Нет никакой причины. Правда.}
# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
{116}{}{Это "услужливые" лекари хотели получить жилье моего друга, и они его получили. Я даже не знаю, что с ним произошло.}
{117}{}{А Киллиан слишком занят, чтобы мне помочь.}
{118}{}{А Киллиан слишком занят тем, что вычищает конюшни после Гизмо, чтобы помочь.}
{119}{}{Гизмо мне в лицо рассмеялся, когда я попросил его о помощи.}
{120}{}{Никто мне не хочет помочь.}
{121}{}{Ты в порядке?}
{122}{}{Позор.}
{123}{}{Надеюсь, что так, очень надеюсь.}
{124}{}{Оставь меня в покое!}
