{100}{}{Компьютер: УПРАВЛЕНИЕ РАЦИЕЙ.}
{101}{}{ Похоже, что каналы рации были заблокированы.}
{102}{}{ Управление рацией, кажется, включено.}
{103}{}{Вы включаете каналы рации.}
{104}{}{Вы выключаете каналы рации.}
{105}{}{Вы двигаете какие-то переключатели, но селектор каналов рации не меняет положения.}
