{100}{}{Вы видите Руфуса.}
{101}{}{Прошу вас, не убивайте меня...}
{102}{}{Шшш! Я в играю в игру!}
{103}{}{Тихо! Я пытаюсь играть в игру. Киберхуд, Принц Матрицы, это классика!}
{104}{}{Вот черт! Моего персонажа опять избили. Роджер такой скучный...}
{105}{}{Где этот чертов ключ в Киберпространство? Я уже облазил все здание Круз...}
{106}{}{Ты часом не знаешь пароль в Малибу Стус? Ладно, забудь...}
{107}{}{Эта Каира - чертова лиса!}
{108}{}{Не мешай мне. Я пытаюсь решить эту долбанную утиную загадку...}
