{100}{}{Дверь в "Выгребную яму" заперта.}
{101}{}{Тебе удается отпереть дверь.}
{102}{}{Ты совершаешь разного рода манипуляции над замком, но так и не можешь его отпереть.}
{103}{}{Ты слышишь какой-то щелчок. Кажется, дверь заклинило.}
{104}{}{Дверь не заперта.}
