{100}{}{Вы видите нескольких мутантов и детей на коленях перед видео-экраном.}
{101}{}{Молись с нами о мире, дитя.}
{102}{}{Единство восторжествует, если мы будем сильны. Размышляйте о свойствах силы.}
{103}{}{Наша миссия по спасению человечества требует веры. Молись с нами.}
{104}{}{Святотатство! Богохульство! Тебя нужно наказать!}
{105}{}{Мы должны молиться, чтобы стать сильными. Изменение уже почти пришло к нам.}
{106}{}{Единство - наше будущее, брат. }
{107}{}{Единство - наше будущее, сестра.}
{108}{}{Верую в Создателя. Его воля - наше спасение.}
