{100}{}{Вы видите Катрину. У нее обаятельная улыбка.}
{101}{}{Я безоружна, пожалуйста, спрячь оружие.}
{102}{}{Гм.}
{103}{}{Почему это? Мы живем в опасном мире.}
{104}{}{Зачем это?}
{105}{}{Возможно, спрячу, а может, и нет.}
{106}{}{Я так понимаю, это было согласие.}
{107}{}{Вообще, это правильно. Это очень опасный мир, и тут глупо путешествовать без оружия. Но мы в Шейди Сэндс, и мы - мирные люди. Здесь нет нужды в оружии.}
{108}{}{Okay. Thanks.}
{109}{}{Если ты не спрячешь оружие, я не буду говорить с тобой. Есть много таких людей, как я. Мы должны использовать силу, только когда того требует ситуация.}
{110}{}{Hmm, okay.}
{111}{}{Добро пожаловать в Шейди Сэндс. Мое имя - Катрина. Моя работа - приветствовать чужеземцев и помогать им в понимании того, что происходит в нашей деревне. Будет проще, если ты выслушаешь то, что я скажу.}
{112}{}{Вабба!}
{113}{}{Расскажи мне о себе.}
{114}{}{Пожалуйста, помоги мне...}
{115}{}{Я ищу водный чип. Здесь такого нет?}
{116}{}{Мне нужна помощь, я разыскиваю Танди.}
{117}{}{Я пытаюсь разобраться с вашей проблемой с радскорпионами. Есть идеи по этому поводу?}
{118}{}{Спасибо, возможно, позже.}
{119}{}{Жаль, что у тебя слабоумие. Нам будет сложно понимать друг друга. Надеюсь, что другие в вашем Убежище не похожи на тебя.}
{120}{}{Вабба-вал?}
{121}{}{Да, я могу сказать, что ты - из Убежища. По тебе это видно. Я сама пришла из Убежища-15, на востоке. Но мне пришлось покинуть дом, и теперь я живу здесь. Надеюсь, ты найдешь здесь то, что ищешь, даже если ты ищешь только тихого пристанища. Надеюсь, что тебя не выставили из Убежища за твой острый язык. Очень надеюсь, что была для этого другая причина.}
{122}{}{А?}
{123}{}{Тебе придется найти другой способ получить ответы на твои вопросы, раз ты не можешь нормально разговаривать. Надеюсь, ты не поранишь много людей во время своего путешествия. Пожалуйста, будь осторожен с нашими людьми, они не причинят тебе вреда.}
{124}{}{Ааххх.}
{125}{}{Я буду рада помочь. Я сама когда-то была такой же, как ты. Хотелось бы надеяться, что мои познания будут тебе полезны.}
{126}{}{Что мне делать, если меня ранят?}
{127}{}{Где я могу получить лучшее снаряжение?}
{128}{}{Расскажи мне об этом месте.}
{129}{}{Расскажи мне об остальном мире.}
{130}{}{Расскажи о себе.}
{131}{}{Это пока все, спасибо.}
{132}{}{Хорошо, если не можешь добраться до доктора, придется лечиться самостоятельно. Стимуляторы - обычное лечебное средство. Используй их, чтобы вылечить легкие раны. Первая помощь - более медленный метод, но зато он всегда доступен. Для серьезных ран, вроде переломов, тебе придется использовать навыки доктора.}
{133}{}{Придется тебе делать так, как мы. Искать в развалинах или торговать. Если на тебя нападут, враги принесут тебе дополнительное снаряжение, если ты доживешь до того, чтобы обобрать их тела. Мы - мирное поселение, так что мы, главным образом, покупаем и обмениваем товары, которые не можем произвести сами.}
{134}{}{Расскажи мне больше о бартере.}
{135}{}{Ты находишься в Шейди Сэндс. Это всего лишь маленький город в большом мире. Мы всего лишь хотим, чтобы нас оставили в покое. Кроме мутировавших и одичавших животных и других тварей пустошей, только налетчики доставляют нам неприятности. Арадеш - наш предводитель. Он живет в большом центральном доме, поговори с ним.}
{136}{}{Я мало знаю о внешнем мире. Я убежала из Убежища, когда на него напали. К несчастью, я была серьезно ранена и не помню почти ничего из того, что произошло. Но Дхарма была со мной, и меня нашли люди из Шейди Сэндс. Теперь я живу здесь. Поговори с Яном, он был охранником купца и был ранен. Он поправляется вон там, в домике охраны. [Она показывает на восток], он путешествовал куда больше, чем я.}
{137}{}{Моя жизнь была очень скучна. Я выросла в Убежище. Я жила там много лет. К сожалению, оно было переполнено, и жизнь была очень плохая. Произошел раскол, и многие ушли, забрав с собой лучшее снаряжение. Однако некоторые из нас попробовали остаться в Убежище. А потом на нас напали. Меня ранили, и я оказалась здесь. Теперь я пытаюсь помочь людям...}
{138}{}{Где было это твое Убежище?}
{139}{}{Бартер - обмен товарами. Ты даешь мне какие-то товары, и я даю тебе другие за них. Когда ты начинаешь обмен, я позволю тебе выбрать все, что ты хочешь выменять, но чтобы сделка состоялась, тебе придется предложить мне что-то взамен. Поскольку нужно, чтобы мне она тоже была по душе, тебе стоит предлагать больше ненужных ценных товаров за более дешевые, но необходимые вещи. Если у тебя не хватает вещей для обмена, то всегда есть крышки от бутылок. Крышки от бутылок - единственные общепринятые деньги в этих краях. Их стоимость обеспечивают торговцы из Хаба, так что можешь расплачиваться ими где угодно.}
{140}{}{Это было Убежище 15. Оно находилось к востоку отсюда. Мы пробовали связаться с некоторыми другими Убежищами, но у нас так ничего и не вышло. Я думаю, что на наше Убежище напали налетчики. Так что будь осторожнее!}
{141}{}{Надеюсь, ты ее найдешь. Она мне как младшая сестра. Думаю, это была одна из банд налетчиков. Выясни про них все, что сможешь, и вооружись как следует, прежде чем преследовать их. Но не торопись сразу бросаться в бой, даже они иногда слушают доводы разума...}
{142}{}{Сэт пробовал следить за радскорпионами. Он даже говорит, что знает путь к их логовищу, но я думаю, что он слегка побаивается идти туда. Его брат был серьезно ранен одним из этих мутантов, и Сэт не знает, что ему делать.}
{143}{}{На самом деле, да. В моем прежнем доме, в Убежище 15, был такой чип. Я не была там, с тех пор как меня ранили, но есть шанс, что ты его там найдешь. Говорят, кто-то пытался пробраться в Убежище, чтобы посмотреть, что там осталось, но там было темно, а лифт сломался. Надеюсь, что ты подготовишься лучше.}
{144}{}{И снова здравствуй. Надеюсь, у тебя все идет хорошо. Я могу тебе чем-то помочь?}
{145}{}{Ты вообще когда-нибудь спишь?}
{146}{}{Ну, я сплю урывками, когда вокруг никого нет. Кроме того, как по мне, воздух Пустыни очень оживляет и бодрит. И я никогда не устаю смотреть на звезды. Можешь себе представить - ни разу в жизни не видеть звездного неба? [Она замолкает и смотрит на вас] А, ну да, думаю, ты можешь.}
{147}{}{О, да. Спасибо.}
{148}{}{Есть тут доктор в округе?}
{149}{}{Маленькие города вроде Шейди Сэндс не смогли бы выжить без помощи целителя. Наш доктор, Разло, живет в самом южном доме. Если тебя серьезно ранят, обращайся к нему. Но не беспокой его по ночам. Он сильно ворчит, когда не высыпается.}
{150}{}{Вы получаете 250 единиц опыта за то, что получили знания от Катрины.}
{151}{}{Воров здесь обычно вешают. Будь паинькой.}
