{100}{}{Вы видите радостного человека с коротко подстриженными волосами.}
{101}{}{Вы видите местного купца, Тайна.}
{102}{}{У нас тут не очень много приезжих. Чем могу служить?}
{103}{}{Привет, чужеземец! Чем я могу помочь тебе сегодня?}
{104}{}{Меня зовут }
{105}{}{.}
{106}{}{Расскажи мне о торговцах из Хаба?}
{107}{}{Я хочу заключить с тобой сделку.}
{108}{}{Как ты связан со Святилищем?}
{109}{}{Ничо...}
{110}{}{Да, я торгую с ними.}
{111}{}{Я веду торговлю с ними. Время от времени. Главным образом я продаю патроны в обмен на продовольствие.}
{112}{}{Я - Тайн. Нам есть что обсудить?}
{113}{}{Счастлив познакомиться. Меня зовут Тайн.}
{114}{}{С тобой приятно иметь дело. Приходи еще.}
{115}{}{Как скажешь.}
{116}{}{Не пропадай!}
{117}{}{Что?}
{118}{}{Привет еще раз! Чем могу помочь?}
{119}{}{Это - хороший городок. Мог бы быть немного счастливее, если бы Регуляторы не держали все под таким жестким контролем. Но ведь это у них такой стиль.}
{120}{}{Не худший городок. Циммерман справедливый человек, хотя, возможно, и не самый умный. И, конечно, там живет Майлз, наверное, единственный человек на сто миль вокруг, который знает что-нибудь о науке.}
