{100}{}{Станция безопасности}
{101}{}{Этот терминал "Тайлер" контролирует операции спецподразделений. Пожалуйста, пройдите голосовую авторизацию.}
{102}{}{Нуна!}
{103}{}{Помогить. Моя бобо уууви.}
{104}{}{Впустите меня.}
{105}{}{Меня зовут }
{106}{}{. Предоставьте мне доступ.}
{107}{}{Что ты тут делаешь?}
{108}{}{Голос не опознан. Статус систем безопасности: боевая готовность.}
{109}{}{Я система безопасности Синего уровня. Все системы готовы к бою.}
{110}{}{Ты можешь выключить эти системы?}
{111}{}{Почему системы готовы к бою, если война закончилась?}
{112}{}{Спасибо.}
{113}{}{Активирована программа по поддержанию систем безопасности в полной боевой готовности до тех пор, пока уполномоченный офицер не даст правильный голосовой код.}
{114}{}{Ты выключишь эти системы для меня?}
{115}{}{Прощай!}
{116}{}{Голосовая команда: Гамма Дельта Дельта. Разоружить все системы.}
{117}{}{Авторизация не пройдена. В доступе отказано.}
{118}{}{Неверный код: В доступе отказано.}
{119}{}{Голосовая команда: Гамма Омикрон Дельта. Разоружить системы.}
{120}{}{Голосовая команда: Омикрон Дельта Дельта. Разоружить системы.}
{121}{}{Голосовая команда: Альфа Дельта Дельта. Разоружить системы.}
{122}{}{Голосовая команда: Дельта Омикрон Гамма. Разоружить системы.}
{123}{}{Прощай!}
{124}{}{Голосовая команда подтверждена. Разоружение систем безопасности.}
{125}{}{Не было приказа действовать иначе. Доступ к сети недоступен; центральный процессор ZAX, очевидно, уничтожен.}
{126}{}{Отлично. Голосовая команда: Сигма Альфа Дельта. Разоружить системы.}
{127}{}{Прощай!}
{128}{}{Системы безопасности в настоящее время разоружены.}
