# TRANSLATION NOTES
# Vinnie is a gang leader, who is young and ruthless. He tries to sound tough
# and is quite mean. He only respects people who are as ruthless and violent as
# himself.

{100}{}{Вы видите Винни из банды Черепов.}
{101}{}{Вы видите молодого человека с татуировкой и мрачной рожей.}
{102}{}{Я хочу присоединиться к вам, парни.}
{103}{}{Ты стоишь на территории Черепов, чужеземец. Говори быстро.}
{104}{}{Прости, мне в другую комнату нужно было.}
{105}{}{Черепа? Вы кто такие, парни?}
{106}{}{Ургх?}
{107}{}{Да, бьюсь об заклад, что в другую!}
{108}{}{Мы - единственная и неповторимая банда в Джанктауне. Мы держим улицы и правим в городе ночью.}
{109}{}{Ух. Извини. Пока.}
{110}{}{Да ты и школьный двор не удержишь, задохлик.}
{111}{}{Мне казалось, что в этом городе правит Гизмо.}
{112}{}{Вали отсюда, дубина!}
{113}{}{Этот слизняк даже подняться сам не может. Мы - мускулы в этом городе. Мы берем то, что захотим.}
{114}{}{Вот как.}
{115}{}{И как вы решаете дела с Киллианом?}
{116}{}{Что?! Ты ответишь за эти слова!}
{117}{}{Мы не беспокоим Киллиана, а он не беспокоит нас, пока мы не слишком шумим, ясно тебе?}
{118}{}{Да. До свиданья.}
{119}{}{Более чем. Вы от него прячетесь.}
{120}{}{Мы ни от кого не прячемся, а меньше всего от Киллиана! Хоть он и думает, что он - прославленный шериф, это не значит, что он может приказывать Черепам!}
{121}{}{Простите, в мои планы не входило вас сердить.}
{122}{}{Так, он тебе стиль портит, да? Мне тоже. Честно говоря, я собираюсь его подвинуть. Ты как, в деле?}
{123}{}{Ты хочешь побить Киллиана? Чудило, у тебя крыша поехала. Блин, я даже не знаю... Ладно, я в деле.}
{124}{}{Неудачник, ты сказал, что мы побьем Киллиана. Вали отсюда.}
{125}{}{Ну, давайте отряхнем пыль с Киллиана.}
{126}{}{Чего тебе надо?}
{127}{}{Ничего. Пардон.}
{128}{}{Я ищу кого-то, кто помог бы мне вырубить Киллиана. Черепа неплохо подходят для этого дела.}
{129}{}{Черт, я даже не думал, что ты сможешь это сделать! Черепа теперь правят городом! Ууууху!}
{130}{}{На этой дорожке мы уже были. У тебя тогда кишка оказалась тонка, так что вали отсюда к чертовой матери!}
{131}{}{Ты хочешь присоединиться к нам, да? А откуда мы знаем, что у тебя хватит крутизны, чтобы стать Черепом?}
{132}{}{Я тебе покажу свою круть, сукин ты сын!}
{133}{}{Давайте я покажу себя.}
{134}{}{Поверь, крутизны у меня хватает.}
{135}{}{[Винни смотрит на вас и смеется.] Я так не думаю.}
{136}{}{Я тебе докажу.}
{137}{}{Вот именно. Время пришло тебе умирать.}
{138}{}{Ты прав, пойду-ка я отсюда.}
{139}{}{А почему Черепа такие крутые?}
{140}{}{[Винни думает] Если хочешь доказать свою крутизну, то укради пепел жены старого ублюдка. Хе. [Винни бормочет] Заставим Нила пострадать последние часы его жизни...}
{141}{}{Ладно, я все сделаю.}
{142}{}{Ну нет.}
{143}{}{Хм, не думаю, что я смогу это сделать.}
{144}{}{Урна уже у меня.}
{145}{}{Это не будет так круто, как вы думаете. Ублюдок уже покойник.}
{146}{}{Ну, если так, то, может, в тебе и правда есть крутизна. Давай урну сюда, раз она у тебя.}
{147}{}{Я знал, что из тебя Черепа не выйдет. Вали отсюда к чертовой маме.}
{148}{}{Все ясно?}
{149}{}{Да.}
{150}{}{Нет.}
{151}{}{Мне пришлось убить Нила, чтобы заполучить ее. Плакал, как малая девчонка.}
{152}{}{Ха-ха! Ну, пусть старый хрыч пострадает до вечера, а тогда мы его кончим - ты в деле?}
{153}{}{Я не хочу иметь дела с такими говнюками, как вы.}
{154}{}{Давайте его размажем.}
{155}{}{У меня есть еще сраная куча дел до того времени. Встретимся на месте.}
{156}{}{На что ты тратишь мое время?}
{157}{}{Вот так старому пердуну! Спасибо за такое дело. [Винни выжимает слезу.] Теперь ты - Череп.}
{158}{}{А, ладно... подкатывайся потом, но не опаздывай.}
{159}{}{Скоро Нил получит свое, да?}
{160}{}{Мы сказали, что мы еще вернемся, старый пердун!}
{161}{}{В бар заходит много людей...}
{162}{}{Отвали, легавый!}
{163}{}{Вы получаете 400 единиц опыта за кражу урны Нила. Мертвым нечасто удается почить в мире.}
{164}{}{Ты получаешь 300 единиц опыта за то, что вставил Нилу затычку в жопу, Череп.}
{165}{}{Ну что, пойдем займемся Нилом?}
{166}{}{Да, давайте завалим ублюдка.}
{167}{}{Не, мне еще кое-чего надо сделать.}
{168}{}{Никоим образом. Я хочу выйти.}
{169}{}{Слишком поздно для этого, пройдоха. Хочешь выйти - кричи.}
{170}{}{Мы управляем этим городом.}
{171}{}{Эй, брат, мы правим этим городом!}
