{100}{}{У тебя вид человека в беде. Тебе нужна помощь?}
{101}{}{Мне нужно лечение.}
{102}{}{Аррр.}
{103}{}{Мой муж Разло может помочь тебе... спроси его.}
{104}{}{Прости, но я тебя не понимаю.}
{105}{}{Приходи утром. Дай поспать хоть ночью.}
{106}{}{Нет, спасибо.}
{107}{}{Нет, мне не нужна медицинская помощь.}
