{100}{}{Вы видите охранника.}
{101}{}{Привет, }
{102}{}{. }
{103}{}{Привет. Как жизнь?}
{104}{}{Гахх!}
{105}{}{И тебе того же гахха!.. Жаль, что у тебя так и не получилось выучиться нормальной речи. Мы могли бы стать хорошими друзьями.}
{106}{}{Уфф.}
{107}{}{Плохо себя чувствую. Кто-то вломил мне по голове большой трубой. Я пошел к врачу, но голова все равно раскалывается. Надеюсь, что кто-то поймает того сопляка, который меня пристукнул.}
{108}{}{Зачем они это сделали?}
{109}{}{Фффу.}
{110}{}{Ну, они напали на меня, когда я тут засиделся очень поздно однажды ночью. Обычно я иду домой приблизительно в восемь, но я задержался, потому что у кого-то украли часть воды и я проверял наши запасы. А в следующий момент я уже в мед-лабе с огромной шишкой на голове. Тут все катится в тартарары. Скоро начнут убивать за стакан воды. Не знаю, что нам с этим делать.}
{111}{}{Посмотрим, что я могу сделать.}
{112}{}{Жаль. Надеюсь, что тебе скоро полегчает.}
{113}{}{Вот твоя вода.}
{114}{}{Вот твой паек на сегодня.}
{115}{}{Эй! Что это ты делаешь?!?}
{116}{}{Пожалуйста, не забирай столько припасов, они нам необходимы.}
{117}{}{Вы записали свой отчет в Библиотечной компьютерной системе. Вы должны теперь вернуться к Смотрителю, чтобы закончить дело.}
# TRANSLATION NOTE
# The player-character's name is inserted by code between lines 118 and 119.
{118}{}{Добрый день,}
{119}{}{.}
{120}{}{Привет. Как жизнь?}
{121}{}{А что ты тут делаешь?}
{122}{}{Ну, все, конечно, немного нервничают, но пока у нас не возникало особых проблем. Надеюсь, ты скоро найдешь нам новый чип.}
{123}{}{Я раздаю тут водопайки, разумеется. И слежу, чтобы никто не брал больше своей доли, хоть я и не думаю, что у нас с этим возникнут неприятности}
{124}{}{Хмм. Хорошо, продолжай трудиться в том же духе.}
{125}{}{Тебе того же. Надеюсь, ты скоро найдешь чип, и мы все сможем возвратиться к нормальной жизни.}
{126}{}{Поскольку твоя задача столь важна, можешь брать пайки, но не забирай слишком много, - у нас их маловато осталось.}
{127}{}{Можно, я возьму часть припасов?}


{1000}{}{Паек}
{1001}{}{Пайки}
{1002}{}{Припасы}
{1003}{}{Вода}


{1100}{}{Я раздаю водопайки по утрам. Тебе они уже не понадобятся, раз ты собираешься выходить наверх.}
{1101}{}{Я раздаю водопайки по утрам. Тебе они уже не понадобятся, раз ты собираешься выходить наверх.}
{1102}{}{У нас тут осталось немного припасов. Можешь взять часть из них, если они необходимы тебе для твоей миссии, только, пожалуйста, не забирай слишком много.}
{1103}{}{Я раздаю водопайки по утрам. Тебе они уже не понадобятся, раз ты собираешься выходить наверх.}
