{100}{}{Õ Abel.}
{101}{}{Egy hatalmas mutáns.}
{102}{}{Teneked nem kén' itten lenned.}
{103}{}{Hng.}
{104}{}{Ahogy mondod. Azért vagyok itt, hogy megöljelek!}
{105}{}{Mér' mondol eztet?}
{106}{}{Csakugyan? Anyád!}
{107}{}{Pik!}
{108}{}{Maj'jól picsán rúglak, ha ilyeneket mondol!}
{109}{}{Pik! Pik!}
{110}{}{Na, maj'mostan megkapod magadét!}
{111}{}{Te ember. Én mutáns. Mutáns megöl embert.}
{112}{}{Mégis hogyan? Az erõtér az smafu?}
{113}{}{Abelnek az semmi. Abel maj'jól picsán rúg!}
{114}{}{Gyerekek nem lehetnek itten. Ez mutáns hely. Mennyél elfele!}
{115}{}{Hng!}
{116}{}{Át kell jutnom az erõtéren. Légyszi, semlegesítsd nekem!}
{117}{}{Nem.}
{118}{}{Mán megin' te vagyol? Abel majjól picsán rúg!}# tell me about name
{970}{}{Én Abel.}# tell me about generic
{980}{}{Hng.}
{981}{}{Mér' mondol eztet?}
