{100}{}{Amber, a Tanítványok oktatója.}
{101}{}{Most pihenõidõ van. Jöjjön vissza estefelé!}
{102}{}{Üdvözlet, nemes utazó! Tanulmányokat szeretne nálunk folytatni?}
{103}{}{Nem. Igazából gyilkolászni jöttem.}
{104}{}{Attól függ, mit akar tanítani?.}
{105}{}{Igen, szándékomban áll.}
{106}{}{Igazán sajnálattal hallom ezt. A Tanítványok mindennél jobban hisznek a békében. Ezen oknál fogva elvetem az erõszakot. Legyen jó estéje!}
{107}{}{Számos nyelvben és mûvészetben járatos vagyok. Esetleg ezek valamelyike érdekelné?}
{108}{}{Elnézést, de tudnom kéne, melyik lenne hasznomra a túlélésben.}
{109}{}{Az ilyesmire nincs idõm. Leléptem.}
{110}{}{Meghallgathatnék egy-két dalt netalán.}
{111}{}{Tud valami mást tanítani?}
{112}{}{Ah, egy tanuló, aki az élet dolgai iránt érdeklõdik. Ebben az esetben tudnék tanítnai egy kis gyógyfüvészetet, de a képzés jó darabig eltart, és nagyon lassú a haladás.}
{113}{}{Sebaj, tanítson csak!}
{114}{}{Kérem, tanítson meg a tudására!}
{115}{}{Bocsánat, de nincs igazán sok idõm növényekre. Viszlát!}
{116}{}{Ne keménykedjen! Kérjen bocsánatot, különben nem tanítom magát!}
{117}{}{Bocsánatot kérek. Tanítana kérem?}
{118}{}{Felejtse el!}
{119}{}{Így máris sokkal jobb. Akár kezdhetjük is a tanulást.}
{120}{}{Maga igazán tehetséges tanuló. Kívánom, hogy sose érjék nagy megpróbáltatások. Béke magával!}
{121}{}{Ahogy jónak látja. Remélem, a jövõ megpuhítja a szívét, és kiszélesíti a gondolkodását.}
{122}{}{Jól van, megtanítom magának a túlélés egyes módozatait.}
{123}{}{Maga igazán tehetséges tanuló. Kívánom, hogy sose érjék nagy megpróbáltatások. Béke magával!}
{124}{}{Nem túl meggyõzõ, amit mond. Szerintem az általam nyújtott tudást rosszra használná. Jó éjszakát!}
{125}{}{Ah, a mûvészetek mûvelõje ritka, mint a fehér holló ebben a világban. Talán van reménysugár a számára. Mindegyik dal igen hosszú. Melyiket óhajtja hallani?}
{126}{}{Az Árnyék Nyomában.}
{127}{}{A Fellegvár Balladája.}
{128}{}{Artemis emlékezetére.}
{129}{}{Eljõ a Hajnal Harci Szekere.}
{130}{}{Figyelemreméltó munka. Támogatom a maga meghallgatását.}
{131}{}{Pihennem kell. A tanítás nagyon sokat kivesz belõlem. Jó szerencsét!}
{132}{}{Figyelemreméltó munka. Támogatom a maga meghallgatását.}
{133}{}{Pihennem kell. A tanítás nagyon sokat kivesz belõlem. Jó szerencsét!}
{134}{}{Figyelemreméltó munka. Támogatom a maga meghallgatását.}
{135}{}{Pihennem kell. A tanítás nagyon sokat kivesz belõlem. Jó szerencsét!}
{136}{}{Figyelemreméltó munka. Támogatom a maga meghallgatását.}
{137}{}{Pihennem kell. A tanítás nagyon sokat kivesz belõlem. Jó szerencsét!}
{138}{}{Attól tartok túlságosan kimerítettem magam. Elnézését kérem emiatt.}
{139}{}{Az én életem a Béke és Szépség jegyében telik. Sajnálom, hogy ezek egyike sem nyeri el a tetszését. Legyen jó napja!}
{140}{}{Meg tudom tanítani a régi bárdok és kobzosok mûvészetét.}
{141}{}{Megtisztelne, ha hallhatnék egy dalt.}
{142}{}{Talán máskor. Köszönöm.}
{143}{}{Azt reméltem, hogy esetleg valami hasznosat is tanulhatok.}
{144}{}{Magának nincs szüksége az én mûvészetemre, hisz megtanította a békés embereket a háború mûvészetére. Most gyászolom õket.}