{100}{}{Jade.}
{101}{}{Beca.}
{102}{}{}
{103}{}{}
{104}{}{A Pengések egyik tagja.}
{105}{}{A Pengések egyik tagja.}
{106}{}{Õ minden bizonnyal Books.}
{107}{}{Õ minden bizonnyal Scars.}
{108}{}{Õ minden bizonnyal Gunner.}
{109}{}{Õ minden bizonnyal Twitch.}
{110}{}{Õ minden bizonnyal Hammer.}
{111}{}{Õ minden bizonnyal Razor.}
{112}{}{Ez itt a pihenõkörlet! Most jobb, ha rögtön húzol kifelé, mielõtt jól valagba rúgunk!}
{113}{}{Próbálkozz csak!}
{114}{}{Bocs, nem akartam zavarni! Légy jó!}
{115}{}{Durmolhatok itt egyet?}
{116}{}{Nem. Ez a hely igazi Pengéseknek van fenntartva, nem valami gyíkarcnak.}
{117}{}{Helló-belló! Mizújs? Durmolj csak nyugodtan itt, ha biztonságos helyet akarsz!}