{100}{}{Egy karavánhajtó.}
{101}{}{A Hubba akartál visszamenni? Fizetek újabb 400 szkriptet.}
{102}{}{Rutger elégedett lesz. Veszteségek nélkül átvészeltük. Vissza akarsz jönni velünk? Bármelyik pillanatban indulhatunk. Fizetek neked még 400 szkriptet.}
{103}{}{Ez könnyebb volt, mint gondoltam. Vissza akarsz jönn velünk? Biztos vagyok benne, hogy 400 szkript jól fog jönni.}
{104}{}{Ez bizony nem volt rossz! Ha vissza akarsz jönni velünk a Hubba, örömmel vesszük. Fizetünk érte újabb 400 szkriptet..}
{105}{}{Mindig nagy baj, ha elvesztünk valakit. Rutger nem lesz oda ettõl, de szívesen vennénk a segítségedet a visszaúton. Érdekel a dolog? A fizetség még mindig 400 szkript.}
{106}{}{A fene egye meg! Rühellem, ha jó õrök mennek kárba. A visszaúton sokkal elõvigyázatosabbaknak kell lennünk. Fedeznünk kell egymást, többé ez nem történhet meg. Hajlandók vagyunk újabb 400 szkriptet fizetni, benne vagy?}
{107}{}{Képes vagy visszajönni velünk a Hubba? Nem kockáztathatom meg, hogy egy újabb õrt veszítsek. A fizetség 400 szkript. Mit mondasz?}
{108}{}{Az a helyzet, hogy nagy szükség lenne a segítségedre a visszaúton. Rutger meg fog ölni engem, és nem tudom, hogy egyedül képes leszek-e végigcsinálni. Ha érdekel a dolog, a fizetség továbbra is 400 szkript. Mit mondasz rá?}
{109}{}{Egyedül nagyon kemény lesz a visszautazás. Eljönnél velem a Hubba újabb 400 szkriptért?}
{110}{}{Egyszerûen nem hiszem el, hogy mindkét õrt elveszítettük. Rutger és Butch leszedik a fejem.}
{111}{}{Igen.}
{112}{}{Nem.}
{113}{}{Úg.}
{114}{}{Remek. Induljunk!}
{115}{}{Csak nem berezeltél?}
{116}{}{Ah, szóval hiányzik egy kis akció az életedbõl.}
{117}{}{Rendben van. Biztos vagyok benne, hogy probléma nélkül visszaérünk. Köszönöm, hogy segítettél mindannyiunknak egy darabban idejutni.}
{118}{}{Rendben van. Megértem a döntésed. Mondjuk egy õrrel elég kemény lesz a visszaút, de megpróbáljuk.}
{119}{}{Öö, rendben. I'm sure I can make it alone.}
{120}{}{Rendben vagy? Az utazás minden bizonnyal jobban megviselt, mint gondoltam.}
{121}{}{Drogozol?}
{122}{}{Hát lehet, hogy nem is volna jó, ha elszegõdnél a karavánom mellé.}
{123}{}{Csak nem meggondoltad magad? Jöhet a meló?}
{124}{}{Jöhet.}
{125}{}{Nem nem!}
{126}{}{Ru?}
{127}{}{Pitlák meló, könnyû pénz. Szóval visszajössz velünk a Hubba? A fizetség ugyanannyi, mint korábban. Persze a veszély sem lesz kisebb.}
{128}{}{Mit szólnál további 600 pénzhez? Vissza kell jutnom a Hubba. Remélhetõleg könnyû utazás lesz.}
{129}{}{Tudtam, hogy velünk tartasz! Újra kapsz 600 dolcsit. Érdekel tehát?}
{130}{}{Szörnyû valakit így elveszteni. Emiatt fizetünk nagy pénzeket. Az út nagyon veszélyes, viszont az a helyzet, hogy Demetre rövidesen visszavár bennünket. A fizetség változatlan. Visszajössz velünk?}
{131}{}{Benne vagy még egy kis akcióban? Ezúttal a hajunk szála sem fog görbülni. Kapsz tõlem 600 dolcsit a Hubba való kíséretért cserébe.}
{132}{}{Tudom. Elkeserítõ így elveszíteni valakit, de legalább harcban esett el. Benne vagy egy újabb balhéban? Hamarosan indulunk a Hubba, és adnánk érte 600 dolcsit.}
{133}{}{A francba! Egyszerûen nem hiszem el, hogy mindkét õrünket elveszítettük. Demetre ki fog bukni, ha megtudja. A fizetség ugyanannyi, hamarosan vissza akarunk menni. Mit mondasz? Benne vagy, hogy közösen irtsuk a férgesét?}
{134}{}{Hát ez aztán harc volt a javából, kár, hogy a az a két õr meghalt. Demetre nem lesz oda a veszteségek hallatán, de legalább túl vagyunk rajta. Vissza kísérsz bennünket a Hubba? Természetesen a 600 dolcsi ugyanúgy jár érte.}
{135}{}{Nincs ellenemre egy kics adok-kapok, de azt már nem szeretem, ha embereket is vesztek. Szerinted képes lennél újra megbírkózni a feladattal? Hamarosan indulnánk -- az egyetlen hátulütõje a dolognak, hogy nem tudok többet fizetni. Sajna nincs kompenzáció.}
{136}{}{Mug.}
{137}{}{Oké. Biztos vagyok benne, hogy rendben megérkezünk.}
{138}{}{Az a nagy helyzet, hogy igazából csak egy õrre van szükségem.}
{139}{}{Ne aggódj, egyedül elbánok mindegyikkel.}
{140}{}{Ah, szóval újra itt vagy! Ugye elvállalod akkor a munkát?}
{141}{}{Arg.}
{142}{}{Isten hozott! Munkát keresel? Hasznát vennénk valakinek, aki elkísérné a karavánjainkat a Hubba. A fizetség 400 szkript.}
{143}{}{Legyen.}
{144}{}{Kösz, de nem.}
{145}{}{Zuk.}
{146}{}{Isten hozott! Munkát keresel? Hasznát vennénk valakinek, aki elkísérné a karavánjainkat a Hubba. A fizetség 600 dolcsi, de jó tudni, hogy az út elég veszélyes.}
{147}{}{Jöhet!}
{148}{}{Yek.}
{149}{}{Majd szólj, ha meggondoltad magad! 14 órakor indulnánk.}
{150}{}{Bocs, de nem úgy nézel ki, mint aki képes lenne ellátni egy karavánkísérõ melót.}
{151}{}{Ha képtelen vagy egyenesen tárgyalni, nem fogadlak fel.}
{152}{}{Ha munkát akarsz, hagyj fel a drogokkal!}
{153}{}{Meggondoltad magad a munkát illetõen?}
{154}{}{Igen, jöhet a munka}
{155}{}{Lum?}
{156}{}{Itt a fizetséged. Majd szólj, ha vissza akarsz jönni velünk!}
