{100}{}{Ez itt egy elég gyatrán rendbehozott játékautomata. Tíz dollárba kerül egy játék.}
{101}{}{Bedobod a 10 dollárt a gépbe és meghúzod a kart.}
{102}{}{BING! BONG! BING! BONG!}
{103}{}{Három gránát! Kiváló! }
{104}{}{ dollár hull a tálcába, amit gyorsan fel is markolsz.}
{105}{}{Bing! Bong! Bing! Bong!}
{106}{}{Három töltény! 15 dolcsi hull a tálcába, amit gyorsan fel is markolsz.}
{107}{}{Appicsába! Vesztettél.}
{108}{}{Nincs elég pénzed a játékra.}
