{100}{}{Ez itt egy nagy darab, tagbaszakadt fickó.}
{101}{}{Nem találkoztunk mi már? Azért jöttél, hogy megölj?}
{102}{}{Tudom, hogy az apukák nem szokták megölelni a fiaikat, de én szeretlek téged, apu!}
{103}{}{Mester, vajon azzá kellett válnom, ami vagyok?}
{104}{}{Senki nem érhet fel Dane-nel...}
{105}{}{Mi a kedvenc színed, barátom? Az enyém a tejszín!}
{106}{}{Te komplett hülye vagy, Dane. Hamarosan ki fognak nyírni, és meg is érdemled! Nyeszlett! Nyeszlett!}
{107}{}{Hitted volna, anyám, hogy ledobják a bombát?}
{108}{}{Könnyedséggel tették, lecsapták a labdát!}
{109}{}{A nevem amúgy Dane és távolról sem Donát!}
{110}{}{Te fûzfapoéta! Siralmas! Siralmas! Siralmas!}
{111}{}{Szeretem Mr. Handyt! Szexelni akarok az aranyos kis kezeivel...}
{112}{}{Bolond vagyok. Megõrültem. Istenem! Teljesen megzakkantam! Gondolj a békére! Gondolj az Egységre!}
{113}{}{Lovat akarok! Lovat akarok! Hozz egy lovat a francba! Lovat!}
{114}{}{Még most is figyelnek bennünket! Mr. Éjfajzatok! Felix és Timothy! Macskák! Kutyák! Éjfajzatok!}
{115}{}{Pofa be! Azt fogják hinni, hogy egy õrült seggfej vagy! Szedd már össze magad!}
{116}{}{Ostoros! Meg kell ölnöd Ostorost! Mentsd meg a gyereket! Szegény kis hippi. Szegény én...}
{117}{}{Pofa be, te faszkalap! Önts már lelket magadba!}
{118}{}{[Hamisan énekel] Voltam én már elveszett, de hívõ többet nem leszek!}
{119}{}{Egyszer kihallgattam, ahogy Morpheus az öklét rázza az egyik Éjfajzatra. Vagy csak kiszagoltam?}
{120}{}{Hülyék vagytok, ha sírtok értem! Kár ezen rágódni.... a sérült áruk miatt még annyira sem.}
#ezt nehéz ügy rendesen visszaadni (bass)
{121}{}{Tudja valaki, hogy kell megjavítani egy kenyérpirítót?}
{122}{}{Persze, hogy tudja, te idióta! A fejed az, amit nem tudnak megjavítani, te vadbarom!}
{123}{}{A fegyver a titok nyitja, pöcsfej! A lõpor intelligens és gonosz, szépen irányítja az agyadat! Minél több lõpor van a közeledben, annál jobban megõrülsz! BUMM! BUMM! BUMM!}
{124}{}{...tûzbe akarom borítani a Vilááááááááááááágot!!!}
{125}{}{Akarsz kicsit dulakodni? Elég jó voltam benne valamikor... amíg le nem nyomtak az Éjfajzatok. Mondjuk kettõt én is lenyomtam. Az Éjfajzatok nagyon erõsek!}
{126}{}{Azok mutánsok, te agyatlan! Még jó, hogy erõsek!}
{127}{}{Ezenkívül a pingvinek is, meg a bölények. Bazi nagy bivalyölõ puskákkal lövik ki õket. Vigyázni kell azokkal a bölénynõkkel, olyan gyorsan fognak a fejedre dobni egy bölényt, hogy azt sem tudod, mi talált el! Ha!}
#gozom sincs, mi az a gyro buffalo - shawn se tudta
{128}{}{Nem ismerlek valami más helyrõl? A te fejed nem fáj?}
{129}{}{Persze, hogy ismered õt, Dane! Õ az ellenségünk! Meg kell semmisíteni!}
{529}{}{Persze, hogy ismered õt, Dane! Õ az ellenségünk! Meg kell semmisíteni!}
{130}{}{Ne is törõdj vele, ez egy seggfej! Szeretlek. Te szeretsz engem?}
{131}{}{Pentictonban laktam, British Columbiában. Vagy csak egy régi térképen láttam? Jó kis idõk voltak azok. Bárcsak visszamehetnék...}
{132}{}{Nem fáraszt, hogy velem beszélgetsz? Nem gondolod, hogy az egész hihetetlenül lecsoffasztott?}
{133}{}{Nem fáraszt téged, hogy folyton magaddal beszélgetsz, te skizofrén barom?}
{134}{}{Gyûlölöm magam. Meg akarok halni, de tudom, te számítasz rám. Arra hajazol, hogy ez a sok marhaság, amit összehordok, végül mégiscsak jelent majd valamit! Valami fontosat!}
{135}{}{Miért nem lehetek én valami fontos személy a változatosság kedvéért?}
{136}{}{MÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ!}
{137}{}{MÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ!}
{138}{}{Unatkozom. Mi rosszabb jöhet? Átdobtak a palánkon. Ez már nem poén többé. Volt már valaha olyan érzésed, mintha fellógatott kötél lennél. Kiszaladt a talaj a lábam alól.}
{139}{}{MÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚÚÚ! MÚÚÚÚÚÚÚ!}
{140}{}{Elég a brahminokból! Elkezd olyan szagod lenni, mint nekik! Aztán mindenki csak okádik, mint a gép!}
{141}{}{Régen elmebeteg voltam, amíg át nem mentem a Szolgasági procedúrán. Régen elmebeteg voltam, de most már Egyben vagyok! Egyben! Egyben!}
{142}{}{Te gyökér, én egy puzzle vagyok! Segítesz kiraknom magam?}
{143}{}{Nem hiszem el, hogy létezik még valaki, aki beszélget velem...}
{144}{}{Ez az egész csak játék, tudod... játék, aminek egy kis darabja vagyok. Aztán egy kisgyerek bedühödött és megtaposott. Csak taposott, csak taposott, csak taposott, aztán a végén eltörtem!}
{145}{}{Lehet, hogy ki fogják nyírni az agyam! Kinyírják és szépen átváltoztatnak az ölebükké! Nesze, Dane! Itt a laszti, Dane! Fogd meg, Dane! Fogd meg, Dane! Végezd ki õket, te agyhalott kutya!}
{146}{}{Mibõl gondolod, hogy Mesternek nevezik?}
{147}{}{Az élet egy nagy szívás, de a halál még nagyobb, és nem mehetünk vissza, hogy megakadályozzuk a születésünket. Mi értelme az egésznek?}
{148}{}{Szerintem õk tudják, mi értelme, te gyökér! Tudják, hogy a Szolgasági procedúra teljesen kikészít! Tudják, hogy ez a "Keresztségi gépezet" egyszerûen szétcsesz mindent...}
{149}{}{A nevem Dane. Viking vagyok. Szeretem a kacsákat. Erõszakot veszek mindenkin, és szétfosztogatom az agyam! Jössz velem erõszakoskodni meg fosztogatni?}
{150}{}{Óh, Istenem! Mesterem, nem Istenem! Legalább a saját nevemre emlékszem. Nekem legalább van nevem. A legtöbb selejtnek még neve sem volt, mielõtt szitává lõtték õket. Nem voltak valami szép hullák. Céllövészet volt az Éjfajzatok számára!}
{151}{}{Aztán ott voltak azok, akik teljesen elvesztették az eszüket. Bárcsak meghaltak volna.}
{152}{}{Azt hiszem, az elsõ gyerekemet Falloutnak fogom hívni. Volt egyszer egy fiam, de a sugárzás szétrágta a mamája méhében.}
{153}{}{Seggfej! Csak nevettél rajta! Korábban szart se törõdtél se vele, sem az anyjával!}
{154}{}{A mutánsok nem tudnak szaporodni. És mi mindannyian mutánsok leszünk! Tudod, mit jelent ez? A világ sterillé válik. Sterillé! Sterillé! Nem tudunk majd szaporodni! Mindannyian meghalunk!}
{155}{}{Állítságok meg! Állítsátok meg! Állítsátok meg! Valaki állítsa már meg!}
{156}{}{Mester! Nem kellett volna mondanom semmit. Hallottam, ahogy az Éjfajzatok sírnak, én pedig szánalmat éreztem emiatt.}
{157}{}{Mi a gonoszság? A gonoszság az, amikor a Jó teljesen elcseszõdik! Gonoszság az, amikor a bátrak gyávák lesznek! A gonoszság a hitványség anagrammája! Valahol léteznie kell valami morális korlátnak!}
{158}{}{Fogd már be, te seggfej! Méghogy morális korlát! Hát itt holtbiztos, hogy nincs olyasmi!}
{159}{}{Régen azt hittem, hogy a vallás egyfajta nemes hívás. Talán az is, de nem sétálhatsz bele vakon, különben átveszik az irányítást az agyad felett.}
{160}{}{...a zombik Isten szégyenei, hallod-e...}
{161}{}{Isten mi a fenéért teremt olyanokat, akik ilyen könnyen megtörnek?}
{162}{}{Azt hiszem, végül is képes vagyok néhány kérdésedet megválaszolni. Bocs, hogy ilyen sokáig tartott.}
{163}{}{Mit szolgál ez a hely?}
{164}{}{Mesélj az Éjfajzatokról!}
{165}{}{Mi folyik itt?}
{166}{}{Mit csináltak veled?}
{167}{}{Ki a Mester?}
{168}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{169}{}{Eléggé hülyeségnek tûnik, amiket összehordasz!}
{170}{}{A "Keresztség" folyamata zajlik. Szolgákat gyártanak itt. A betanított ministránsok idehozzák õket, és végrehajtják rajtuk a beavatkozást. Néhányan élik csak túl...}
{171}{}{A legtöbbjük megõrül, de még úgy is egész használhatók. Letaszíttatnak a lépcsõn, szónoklatot tartanak nekik a Mesterrõl, aztán kábultan ténferegnek összevissza. Láttad a zombikat. Jó rabszolga-munkaerõ, nem is beszélve arról, hogy katonának is beválnak...}
{172}{}{John Brown forog a sírjában. John Brown forog a sírjában. John Brown forog a sírjában és a Mester mindannyiunkat átverrrrr...}
{173}{}{Hagyd abba! Egyre nehezebb megemberelni magam.}
{174}{}{Mesélj az Éjfajzatokról!}
{175}{}{Mi folyik itt?}
{176}{}{Mit csináltak veled?}
{177}{}{Ki a Mester?}
{178}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{179}{}{Upsz! Többé nem tudom kontrollálni magam! Jaj! Jaj! Jaj!}
{180}{}{Mutánsok õk. Hallottam õket beszélni. Lopakodós fajta vagyok. Ismerem az összes titkukat. Gyûlölnek engem. Éktelenül gyûlölnek.}
{181}{}{Teljesen kivagyok, de ez a Katedrális Átverõ Tervének még csak az 1-es Fázisa. Amint a szolgákat maradéktalanul agymosták, jöhet a 2-es Fázis. A Mester akkor fogja megkeresztelni õket a FEV-2-ben!}
{182}{}{A legtöbbjük azon nyomban meghal, de akik túlélik, mutánsokká válnak. NAGY mutánsokká. Éjfajzatokká! A Mester szerint csak az Éjfajzatok élhetik túl. Azt akarja, hogy mindenki Éjfajzat legyen, mert õk hihetetlenül szívósak!}
{183}{}{Ismered ezt az egész béke és összevogás baromságot? Ez nem baromság a Mester számára. Õ tényleg meg van gyõzõdve, hogy megmenti a világot!}
{184}{}{Sterilek leszünk! Mindannyian visszataszító, steril torzszülöttek leszünk! Sterilek! Sterilek! Sterilek! A nevem nem Emil, hanem Steril!}
{185}{}{Mesélj az Éjfajzatokról!}
{186}{}{Mi folyik itt?}
{187}{}{Mit csináltak veled?}
{188}{}{Ki a Mester?}
{189}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{190}{}{MÚÚÚÚ! MÚÚÚÚÚ! MÚÚÚÚ! Brahmin Éjfajzatok jõnek! Vár ránk a steril tej!}
{191}{}{Közeleg a világvége. Mutáns seregek lepik el a Menedékeket, de ne engem okolj, ez a Mester hibája. Ha meglesz az Egység, akkor kezdõdik majd igazán a Mester által ígért móka.}
{192}{}{Mesélj az Éjfajzatokról!}
{193}{}{Miféle móka?}
{194}{}{Mit csináltak veled?}
{195}{}{Ki a Mester?}
{196}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{197}{}{Upsz! Többé nem tudom kontrollálni magam! Jaj! Jaj! Jaj!}
{198}{}{Belerakott mindenféle vegyszerekbe, telelyuggatta a testem, ezerféle zajt nyomott a fülembe. Csupa szarokat. Olyasvalamivé akart változtatni, ami nem vagyok. A szülõk állandóan ugyanezt csinálják.}
{199}{}{Komoly fájdalmat tudok okozni.}
{200}{}{Mire jó ez a hely?}
{201}{}{Mesélj az Éjfajzatokról!}
{202}{}{Mi folyik itt?}
{203}{}{Ki a Mester?}
{204}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{205}{}{Eléggé hülyeségnek tûnik, amiket összehordasz!}
{206}{}{Régen én is bántottam az embereket. Tökös gyerek voltam! A francba, igazi isten voltam! Egy tökös, isteni faszkalap! Sajnos nem volt elég! Egy menetelõ harci gépezet voltam! Most viszont nem vagyok más... mint egy... mint egy... segíts rajtam...}
{207}{}{Az Éjfajzatok szerint rondább, mint õk maguk. Ez azt jelenti, hogy akkor mocskosul egy ronda féreg lehet.}
{208}{}{Õ az igazi Ember! Az Ember, akinek Terve van! Azért tervez, mert szeret minket! Ha pedig útjába áll a világ, elsöpri! Na, errõl szól a szeretet!}
{209}{}{Mire jó ez a hely?}
{210}{}{Mesélj az Éjfajzatokról!}
{211}{}{Mi folyik itt?}
{212}{}{Mit csináltak veled?}
{213}{}{Meg akarsz halni? Én elintézhetem neked, hogy megszabadulj a gyötrelmektõl...}
{214}{}{Eléggé hülyeségnek tûnik, amiket összehordasz!}
{215}{}{A Szeretettõl nõ a kaktusz! A Szeretettõl bõgnek a brahminok! A Szeretet elcseszi a dolgokat, elcseszi az életed! Gyûlölöm a szeretetet! Gyûlölöm a gyûlöletet! Ha a Mester gyûlölne minket, mind rendben lennénk!}
{216}{}{Hova tetted az értelmet a szavaidból, ember? Szerinted az élet egy takaros kis festmény, mindenféle problémák nélkül? Az élet egy nagy nyomorúság! Bármi szarságot is akarunk csinálni ellene, nyomorúság marad!}
{217}{}{Küzdünk! Szeretünk! Dugunk! Gyûlölünk! Kihasználjuk a lehetõségeket! Untatjuk az embereket! Elverjük a seggfejeket! Barátkozunk más seggfejekkel! Elfutunk a hibáink elõl! Szembefordulunk a hibáinkkal! És a végén ott a sugárzás!}
{218}{}{Az, hogy van gyereked, és ugyanazt csinálod újra meg újra, néha jobbá, néha rosszabbá teszi a dolgokat!}
{219}{}{Errõl szól az élet, ember! Olyan, mint részegnek lenni; ha így nézed, merõ egy nagy szívás, ha úgy nézed, óriási élmény! A lényeg nem változik! Ez az élet!}
{220}{}{Aha! Ha! Ha! Ha! Ha! Igazad van! Mindannyian hülyék vagyunk! Érted? Ha! Ha! Ha!}
{221}{}{Most egy kicsit keserûbb lettem. Mint az esõn hagyott fekete tea. Hah! Tetszik ez a mondás! Asszem gyakrabban fogom ismételgetni! Most egy kicsit keserûbb lettem. Mint az esõn hagyott fekete tea...}
#Orange pekoe, a kind of black tea. Bass
{222}{}{[TOVÁBB]}