{100}{}{Ez itt egy Hubbeli ember.}
{101}{}{Nem hiszem el, hogy élek és azt végképp nem hiszem, hogy maga nyírta ki mindet! Hé, miket beszélek? Végül is élek, nem igaz? Bármit is mondjon, én elhiszem magának.}
{102}{}{Ezért most megölöm!}
{103}{}{Ide az összes pénzével!}
{104}{}{Vessen számot az életévek, és tûnés kifelé, mielõtt magát is kinyírom!}
{105}{}{Ök?}
{106}{}{De hát... maga? (sóhajt) Oké, de csinálja gyorsan! Utálom a fájdalmat.}
{107}{}{Ne bántson!}
{108}{}{Oké. (Átnyújt 20 hubbeli dollárt.) Most már mehetek?}
{109}{}{Mehet.}
{110}{}{Túrót!}
{111}{}{De hát miért?}
{112}{}{Mert azt mondtam, hogy nem és kész! Van valami gondja ezzel?}
{113}{}{Oké, mehet az útjára!}
{114}{}{Nincs, bocsánat, uram! Kérem, ne bántson - gyûlölöm a fájdalmat!}
{115}{}{Nincs, bocsánat, hölgyem! Kérem, ne bántson - gyûlölöm a fájdalmat!}
{118}{}{Maga elmebeteg? Úgy értem, ezer köszönet, hogy megmentette az életemet, kedves uram. Most mennem kell, viszlát!}
{119}{}{Maga elmebeteg? Úgy értem, ezer köszönet, hogy megmentette az életemet, kedves hölgyem. Most mennem kell, viszlát!}
{122}{}{Igen... igen... igen... uram. Soha többé nem csinálok semmi rosszat! Nem... nem fogok csalni, nem fogok hazudni, nem fogok zsarolni, rabolni, gyilkolni és embereket fogságba ejteni.}
{123}{}{Igen... igen... igen... hölgyem. Soha többé nem csinálok semmi rosszat! Nem... nem fogok csalni, nem fogok hazudni, nem fogok zsarolni, rabolni, gyilkolni és embereket fogságba ejteni.}
{126}{}{Húzza el innen a belét!}
{127}{}{Hazug disznó!}
{128}{}{Igen, uram!}
{129}{}{Igen, hölgyem!}