{100}{}{A Hosszútávú Kereskedõk õrét látod.}
{101}{}{Azok a francos Vízkereskedõk mindannyiunkat levesznek.}
{102}{}{Ügyelj, hogy idõben visszafizesd a pénzt a Baráti Kölcsönös fiúknak! Halálos egy gárda.}
{103}{}{Beszélj Rutgerrel!}
{104}{}{A "Hosszútávú Kereskedõk" a legjobbak.}
{105}{}{A Karmazsin Karaván csupa idiótából és holdkórosból áll.}
{106}{}{Hmm, csorog a nyálam egy kis nyársas gyíkért.}
{107}{}{Ki a fene rabolja el a karavánjainkat?}
{108}{}{A testvérem az utoljára eltûnt karavánnal indult útnak.}
{109}{}{Tudom, hogy azok a vízkufárok a felelõsök!}
{110}{}{Úgy hallottam, a mutánsok vitték el a karavánokat. Szörnyûség!}
{111}{}{Hallottam, hogy Mutánsokat emlegettél. Remélem, jól megadtad nekik.}
{112}{}{Azt hittem, a Halálkarmok csinálják a fesztivált, a fene mutánsaiba.}
{113}{}{Zárva vagyunk. Gyere vissza reggel!}
{114}{}{Hé, ez itt nem a Sólyom! Tûnés innen kifelé!}
{115}{}{Mi vagy te? Valamiféle Sóher? Húzás innen a retekbe!}
{116}{}{Kopj le!}
{117}{}{Csak napközben vagyunk nyitva.}
{118}{}{Csak nem drogos vagy? Na, kifelé!}
{119}{}{Reggel kéne visszajönnöd!}