{100}{}{Egy hololemezt látsz magad elõtt.}
{101}{}{PipBoy képernyõ: Adat letöltése a lemezrõl...}
{102}{}{A lemez valamiféle szórakoztató anyagot tartalmaz.}
{103}{}{A lemez olyannyira megsérült, hogy lehetetlenség bármit is leolvasni róla.}
{104}{}{Úgy tûnik, a lemez olyasmit említ, hogy egy másik lemezen valami belépési kód található.}
{105}{}{Egy apró képernyõ jelenik meg, mely valami második világháborús film maradványait játssza.}
{106}{}{A lemez üres.}
{107}{}{Eldobod az értéktelen lemezt.}