{100}{}{A Hosszútávú Kereskedõk egyikét látod.}
{101}{}{Menj a fenébe innen!}
{102}{}{Húzz innen, különben nem lesz lehetõséged megbánni!}
{103}{}{Sóher!}
{104}{}{Na, akarsz egy kis balhét, punk?}
{105}{}{Készen állsz egy kis büntire?}
{106}{}{Ne akard, hogy újra bántsalak!}
{107}{}{Halálvágyad van, vagy mi a franc? Tûnj már el!}