{100}{}{Helló! Mit tehetek érted?}
{101}{}{Ki vagy te?}
{102}{}{Mit csinálsz épp?}
{103}{}{Add át mindenedet!}
{104}{}{Lub!}
{105}{}{Lox vagyok. Kereskedõ.}
{106}{}{Terrance vagyok, és kereskedéssel foglalkozom.}
{107}{}{Julian a nevem, és ezermester vagyok.}
{108}{}{Dale-nek hívnak. Apró tárgyakat adok-veszek.}
{109}{}{Adytumba igyekszem, hogy eladjak egy-két árumat.}
{110}{}{Roncsvárosba tartok, hogy nyélbe üssek néhány üzletet.}
{111}{}{A Hubba megyek épp, hogy csereberéljek.}
{112}{}{Nekropoliszba indultam egy kis felfedezõ útra.}
{113}{}{Jaj!}
{114}{}{Nem bánnád, ha csatlakoznék hozzád?}
{115}{}{Nyugodtan! Gyere csak. A társaság mindig jól jön.}
{116}{}{Sajnálom, de már teljes a csapat.}
{117}{}{Elnézést, de nem nagyon bízom benned.}