{100}{}{Meghalsz, kutya!}
{101}{}{A vereségem megbosszultatik majd!}
{102}{}{Megállj, újonc! Mi jelentenivalód van?}
{103}{}{Nyugaton a helyzet változatlan.}
{104}{}{A radskorpiók meg ez a szörnyû hõség. Öö... uram.}
{105}{}{Igazából azt akartam tudni, hallottál-e valamit.}
{106}{}{Nincs mit jelentenem, uram!}
{107}{}{Ruh?}
{108}{}{Megállj! Felismerlek téged... a Testvériség látogatója vagy. Lehet, hogy van, aki bízik benned, de én nem. Ki vele, mi dolgod itt!}
{109}{}{Az én dolgom az én dolgom, a magáé meg a magáé.}
{110}{}{Egy barátságos arcot akartam látni.}
{111}{}{Vándorlok a pusztaságban, próbálok túlélni.}
{112}{}{Sivatagi férgeket gyilkolászok. Van valami kifogása?}
{113}{}{Csak a rendjük fejének vagyok halandó bármit is mondani. Vigyen a Testvériséghez!}
{114}{}{Dógom?}
{115}{}{Megállj! Felismerlek téged, és meg kell mondjam, nem bízom benned. Tisztességes figyelmeztetést kapsz tõlem: ha megpróbálsz bajt keverni nálunk, agyonlövünk, mint egy rühös kutyát. Most pedig szedd a lábad!}
{116}{}{Megállj! Ki vagy? Mondd meg a neved és a jöveteled célját!}
# TRANSLATION NOTES
# The player-character's name is inserted after line 117, and then has
# line 118, 119, 120, or 121 appended.
{117}{}{A nevem }
{118}{}{ és egy víztisztító csipet keresek a Menedékem számára. Tud segíteni?}
{119}{}{ és próbálom megtalálni a mutánstámadások forrását.}
{120}{}{ , a többihez pedig semmi köze!}
{121}{}{ és kalandokat keresek.}
{122}{}{Egyél szart, bokorugró!}
{123}{}{Runk!}
{124}{}{Megállni! Ez a hely az Acél Testvériségének tulajdona. Távozz innen, különben birtokháborításért agyonlövünk.}
{125}{}{Nagyon helyes, folytasd a dolgod, Újonc!}
{126}{}{Értem, folytasd a dolgod, Újonc!}
{127}{}{Idõrõl-idõre jelentik, hogy hatalmas mutáns seregek támadják meg az utazókat, ezért megnöveltük a hadrafoghatóságunkat. 
Tartsd szemmel a környéket, és vonulj vissza a bázisra, ha úgy adódik! Leléphetsz, újonc!}
{128}{}{Zavaros idõk járnak, Újonc! Mutánsok masíroznak mindenfelé, és sorra támadják meg a karavánokat! Információra van szükségünk, mégpedig sürgõsen. Ha nincs jelentenivaló, az nem kielégítõ válasz!}
{129}{}{Húzd el innen az irhádat, és szerezz valami használható információt! Leléphetsz, újonc!}
{130}{}{Ó, igen, már hallottam rólad. Nem születtél észkombájnnak, de legalább tökös harcos vagy. Kár érted!}
{131}{}{Ez itt a mi portánk, és itt a te dolgod a mi dolgunk is. Megismétlem tehát: Mondd el a jöveteled célját!}
{132}{}{Víztisztító csipet keresek a Menedékem számára. Tud segíteni?}
{133}{}{Próbálom megtalálni a mutánstámadások forrását.}
{134}{}{Lehet, hogy ez itt mind a maguké, de a rabszolgájuk azért nem vagyok.}
{135}{}{Régóta rovom már a pusztaságot. Csak új híreket akartam hallani.}
{136}{}{Szóval barátságos arcot akartál látni? Hát az nem az enyém lesz. Azt ajánlom, távozz!}
{137}{}{Ahogy mindannyiunk próbál. Amíg nem teszel a Testvériség ellen, nem esik bántódásod. Mindenesetre jól gondold meg, mit csinálsz!}
{138}{}{Attól függ, hogy bennünket is sivatagi féregnek tartasz-e. Ha megtámadod az ellenségeinket, szabad járást biztosítunk a területünkön. Ha ellenünk teszel, meghalsz! Ezt nyugodtan vedd figyelmeztetésnek!}
{139}{}{Elfogadható kérés. Utánam!}
{140}{}{Víztisztító csipet keresel? Nálunk? Remélem, nem gondolod komolyan! Jobban teszed, ha a felszínen próbálod tengetni az életed, minthogy egy gép rabszolgája legyél!}
{141}{}{Mi is ezen munkálkodunk. A legáltalánosabb nézet szerint az Izzás felõl jönnek, de erõsen kétlem, hogy akár a mutánsok is képesek lennének túlélni azt a helyet. Ha találsz valamit, tudasd velünk!}
{142}{}{Hogy merészlesz bennünket ilyesmivel vádolni?! Az Acél Testvérisége sosem erõszakolta rá másokra, hogy bennünket szolgáljon. Ez minden alapelvünkkel ellenkezik. Hordd el magad a szemem elõl!}
{143}{}{Kábé egy napi járóföldre nyugat felé találtunk egy lerobbant karavánt. Egyetlen túlélõ maradt... szegény kislány. Azt állította, hogy hihetetlen erejû mutáns humanoidok támadták meg õket.}
{144}{}{Elég jelentést hallottunk már, amely... elgondolkodtat bennünket. A helyedben elõvigyázatosan járnék a világban.}
{145}{}{Majd megtanítalak én kesztyûbe dudálni, fiam! Könnyed szórakozás lesz.}
{146}{}{Majd megtanítalak én kesztyûbe dudálni, lányom! Könnyed szórakozás lesz.}
{147}{}{Szegény teremtmény, teljesen elvesztetted az eszed.}
{148}{}{Ne fecséreld már az idõmet, te bolond!}
{149}{}{Mit akarsz?}
{150}{}{Semmit.}
{151}{}{Akkor azt ajánlom, hogy menj innen!}