{100}{}{Ezen a biztonsági ajtón vörös festék nyomai látszanak.}
{101}{}{Az ajtóra helyezett elektromos mezõ megráz kissé, és egy pontnyi sérülést szenvedsz.}
{102}{}{Az ajtóra helyezett elektromoz mezõ komolyan megráz és }
{103}{}{ pontnyi sérülést szenvedsz.}
{104}{}{Kifeszíted az ajtót.}
{105}{}{Az ajtó zárva van.}
{106}{}{Hozzáférés megadva... elektromos mezõ lekapcsolása folyamatban.}
{107}{}{Nem vagy felhatalmazva, hogy belépj ebbe a szobába.}
{108}{}{Ez a tárgy semmiféle hatással nincs a biztonsági rendszerekre.}
{109}{}{Sikerült megberhelni a biztonsági ajtó zárját.}
{110}{}{Úgy tûnik, van valami biztonsági célokat szolgáló védelem ezen az ajtón.}
{111}{}{Nem sikerült megberhelni az ajtó zárját.}
{112}{}{Ez a képzettség semmilyen hatással nincs erre az ajtóra.}
{113}{}{Lekapcsolod az ajtó biztonsági rendszerét szolgáló elektromos mezõt.}
{114}{}{Felerõsítetted az elektromos mezõ erejét.}
{115}{}{Nem sikerült hatástalanítanod az ajtó elektromos mezejét.}
{116}{}{Anélkül, hogy a biztonsági rendszer mûködésbe lépett volna, sikerült megberhelned az ajtó zárját.}
{117}{}{Nem sikerült megpiszkálnod az ajtó zárját, ráadásul a biztonsági rendszer komoly sérülést okozott.}
{118}{}{Nem sikerült megpiszkálnod az ajtó zárját, ráadásul a biztonsági rendszer még sérülést is okozott.}
{119}{}{A biztonsági rendszer megrázott, ezért nem tudsz koncentrálni az ajtó zárjának megberhelésére.}
{120}{}{A biztonsági rendszer erõsen megrázott, ezért nem tudsz koncentrálni az ajtó zárjának megberhelésére.}
{121}{}{A zárat olyannyira nem sikerült megpiszkálnod, hogy tönkretetted a tolvajkulcsot.}
{122}{}{Nem sikerült megberhelned a zárat.}
{123}{}{Egy masszív, rozsdás ajtót látsz magad elõtt.}{124}{}{Egy sárga festésû ajtót látsz. A zárja már nem akadály többé.}
{125}{}{Egy sárga festésû ajtót látsz. A zárja már nem akadály többé.}
{126}{}{A megberhelt ajtó elõtt egy mozgó sárga mezõt látsz.}
{127}{}{A megberhelt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{128}{}{Egy sárga festésû ajtót látsz.}
{129}{}{Egy sárga festésû ajtót látsz.}
{130}{}{Az ajtó elõtt egy mozgó sárga mezõt látsz.}
{131}{}{Az ajtót egy nagyfeszültségû biztonsági rendszer õrzi.}
{132}{}{Egy sárga festésû zárt ajtót látsz.}
{133}{}{Egy sárga festésû zárt ajtót látsz.}
{134}{}{A zárt ajtó elõtt egy mozgó sárga mezõt látsz.}
{135}{}{A zárt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{136}{}{Úgy tûnik, ehhez a sárga ajtóhoz valami speciális kulcs kell.}
{137}{}{Úgy tûnik, ehhez a sárga ajtóhoz valami speciális kulcs kell.}
{138}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy csillogó sárga mezõt is látsz elõtte.}
{139}{}{Az ajtó zárjához valami speciális sárga kulcs kell. Ráadásul még egy nagyfeszültségû biztonsági rendszer is van rajta.}{140}{}{Az ajtó zárja már megadta magát.}
{141}{}{Az ajtó zárja már megadta magát.}
{142}{}{A megberhelt ajtó elõtt egy mozgó mezõt látsz.}
{143}{}{A megberhelt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{144}{}{Egy ajtót látsz.}
{145}{}{Egy ajtót látsz.}
{146}{}{Az ajtó elõtt egy mozgó mezõt látsz.}
{147}{}{Az ajtót egy nagyfeszültségû biztonsági rendszer õrzi.}
{148}{}{Egy zárt ajtót látsz.}
{149}{}{Egy zárt ajtót látsz.}
{150}{}{A zárt ajtó elõtt egy mozgó mezõt látsz.}
{151}{}{A zárt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{152}{}{Úgy tûnik, ehhez az ajtóhoz valami speciális kulcs kell.}
{153}{}{Úgy tûnik, ehhez az ajtóhoz valami speciális kulcs kell.}
{154}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy csillogó mezõt is látsz elõtte.}
{155}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy nagyfeszültségû biztonsági rendszer is van rajta.}{156}{}{Egy vörös festésû ajtót látsz. A zárja már nem akadály többé.}
{157}{}{Egy vörös festésû ajtót látsz. A zárja már nem akadály többé.}
{158}{}{A megberhelt ajtó elõtt egy mozgó vörös mezõt látsz.}
{159}{}{A megberhelt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{160}{}{Egy vörös festésû ajtót látsz.}
{161}{}{Egy vörös festésû ajtót látsz.}
{162}{}{Az ajtó elõtt egy mozgó vörös mezõt látsz.}
{163}{}{Az ajtót egy nagyfeszültségû biztonsági rendszer õrzi.}
{164}{}{Egy vörös festésû zárt ajtót látsz.}
{165}{}{Egy vörös festésû zárt ajtót látsz.}
{166}{}{A zárt ajtó elõtt egy mozgó vörös mezõt látsz.}
{167}{}{A zárt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{168}{}{Úgy tûnik, ehhez a vörös ajtóhoz valami speciális kulcs kell.}
{169}{}{Úgy tûnik, ehhez a vörös ajtóhoz valami speciális kulcs kell.}
{170}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy csillogó vörös mezõt is látsz elõtte.}
{171}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy nagyfeszültségû biztonsági rendszer is van rajta.}{172}{}{Egy vörös festésû ajtót látsz. A zárja már nem akadály többé.}
{173}{}{Egy vörös festésû ajtót látsz. A zárja már nem akadály többé.}
{174}{}{A megberhelt ajtó elõtt egy mozgó vörös mezõt látsz.}
{175}{}{A megberhelt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{176}{}{Egy vörös festésû ajtót látsz.}
{177}{}{Egy vörös festésû ajtót látsz.}
{178}{}{Az ajtó elõtt egy mozgó vörös mezõt látsz.}
{179}{}{Az ajtót egy nagyfeszültségû biztonsági rendszer õrzi.}
{180}{}{Egy vörös festésû zárt ajtót látsz.}
{181}{}{Egy vörös festésû zárt ajtót látsz.}
{182}{}{A zárt ajtó elõtt egy mozgó vörös mezõt látsz.}
{183}{}{A zárt ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{184}{}{Úgy tûnik, ehhez a vörös ajtóhoz valami speciális kulcs kell.}
{185}{}{Úgy tûnik, ehhez a vörös ajtóhoz valami speciális kulcs kell.}
{186}{}{Az ajtó zárjához valami speciális kulcs kell. Ráadásul még egy csillogó vörös mezõt is látsz elõtte.}
{187}{}{Az ajtó zárjához valami speciális vörös kulcs kell. Ráadásul még egy nagyfeszültségû biztonsági rendszer is van rajta.}{188}{}{Egy sárga festésû ajtót látsz.}
{189}{}{Az ajtó elõtt egy mozgó sárga mezõt látsz.}
{190}{}{Ezen a sárga ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{191}{}{Ezen a sárga ajtón egy nagyfeszültségû biztonsági rendszert látsz. Azon tûnödsz, vajon van-e valahol egy kódkártya a kinyitásához.}{192}{}{Egy ajtót látsz.}
{193}{}{Az ajtó elõtt egy mozgó mezõt látsz.}
{194}{}{Ezen az ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{195}{}{Ezen az ajtón egy nagyfeszültségû biztonsági rendszert látsz. Azon tûnõdsz, vajon van-e valahol egy kódkártya a kinyitásához.}{196}{}{Egy vörös festésû ajtót látsz.}
{197}{}{Az ajtó elõtt egy mozgó vörös mezõt látsz.}
{198}{}{Ezen a vörös ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{199}{}{Ezen a vörös ajtón egy nagyfeszültségû biztonsági rendszert látsz. Azon tûnõdsz, vajon van-e valahol egy kódkártya a kinyitásához.}{200}{}{Egy vörös festésû ajtót látsz.}
{201}{}{Az ajtó elõtt egy mozgó vörös mezõt látsz.}
{202}{}{Ezen a vörös ajtón egy nagyfeszültségû biztonsági rendszert látsz.}
{203}{}{Ezen a vörös ajtón egy nagyfeszültségû biztonsági rendszert látsz. Azon tûnõdsz, vajon van-e valahol egy kódkártya a kinyitásához.}{204}{}{Észreveszed, hogy csapda van az ajtón.}
{205}{}{A felvonó nem mûködik. Valószínûleg áram kell neki.}
