{100}{}{Ez egy megfagyott tetem.}
{101}{}{A holttest határozottan nem földi eredetû.}
{102}{}{Ez a test nagy valószínûséggel valami genetikai kísérlet eredménye.}
{103}{}{Na mi ez? Egy holttest.}
{104}{}{Ez az összefagyott tetem nagyon furán néz ki.}