{100}{}{A szekrény zárva van.}
{101}{}{Kinyitod a szekrény zárját.}
{102}{}{Feltöröd a szekrény zárját.}
{103}{}{Nem sikerült feltörni a szekrény zárját.}
{104}{}{Miközben megpróbáltad feltörni az ajtó zárját, eltört a tolvajkulcsod.}
{105}{}{Ez a zár túlságosan komplikált neked.}