{100}{}{Harold.}
{101}{HROLD0}{
Adj egy kis aprót, öreg barátom, régi cimbora... ki tudnál segíteni egy szegény, szerencsétlen mutánst? [Köhög]}
{102}{}{Persze, itt van 25 dollár. Sok szerencsét.}
{103}{}{Mit szólna 5 dolcsihoz?}
{104}{}{Elnézést, de nincs nálam pénz.}
{105}{}{Táguljon tõlem, hé!}
{106}{}{Öhhh?}
{107}{HROLD1}{
Ejjj, barátom, te aztán rosszabb helyzetben vagy, mint én. Nem ártana, ha rád mosolyogna a szerencse.}
{108}{HROLD2}{
Óh, nagyon rendes vagy, barátom. Nagyon rendes. Ha valaha képes lennék kitörölni a dzsuvát a Vén Harold szemébõl, még könnycseppet is találhatnál benne.}
{109}{}{Hogyhogy?}
{110}{}{Nincs mit.}
{111}{HROLD3}{
[Köhög] Mióta visszajöttem a városba, a Hublakók többsége valami randa mumusként kezel engem. Sajnos nem tudok elmenni innen. A seggemet a földhöz verhetem [zihál] akkor is itt kell élnem.}
{112}{}{Mi történt?}
{113}{}{Kik azok a Hublakók?}
{114}{}{Remélem, jobbra fordulnak a dolgok. Viszlát!}
{115}{HROLD4}{
Naszóval... a Nagy Háború után az elsõk között nyílt meg a Menedékem. [Nagy levegõt vesz] Fúúú... rég volt.}
{116}{}{Meséljen még azokról az idõkrõl!}
{117}{}{Nem, nem... úgy értettem, mi történt magával...}
{118}{HROLD5}{
A szirénákkal kezdõdött. Fiatal voltam... ajjaj... emlékszem bizony... Szörnyûséges évek következtek. Aztán emlékszem, hogy egyik reggel szépen kisétáltam a Menedékbõl.}
{119}{}{Mit csinált utána?}
{120}{}{Hol volt az a Menedék?}
{121}{}{Tudatában van, hogy ez alapján hány éves?}
{122}{HROLD6}{
Tudod... [köhög] Már nem vagyok benne biztos. Nyugatra talán. Nem, várj csak... keletre? Sajna, nem tudom. [Erõsen köhög]}
{123}{}{Mit csinált utána?}
{124}{HROLD7}{
Kereskedõ voltam. Jól megéltem abból, hogy a túlélõkkel üzleteltem. Sajnos sok jó ismerõst elvesztettem közben. [Köhög]}
{125}{}{Hogyan?}
{126}{HROLD8}{
A bandák karmai közé kerültek. Guberálók támadtak a karavánokra. Meg mocskos mutánsok. Úgy tûntek elõ, mint giliszták az esõben. [Köhög] Ahhoz, hogy nyélbe tudjunk ütni valamit, seregnyi õrre volt szükség.}
{127}{}{Az õrök nem segítettek?}
{128}{}{Honnan jöttek a mutánsok?}
{129}{HROLD9}{
Dehogynem segítettek, te tökkelütött! Csak francos sok támadó volt!}
{130}{}{Hogy élte túl a mutánsok támadását?}
{131}{HROLD9A}{
Sehogy. Megöltek. [Nevetve köhög] Ez a poén mindig tetszett.}
{132}{}{Öö, értem.}
{133}{HROLD10}{
Mindenhonnan! A franc esne beléjük, fingani sem tudtál anélkül, hogy ne ütköztél volna egybe. Mondjuk rendszerint észak-nyugatról jöttek.}
{134}{}{Felkutatta már azt a területet?}
{135}{}{Miért nem kerülte el nagy ívben azt a részt?}
{136}{}{Észak-nyugat felé fingott?}
{137}{hrold10a}{[Nevet] Ez jó...Neem...}
{138}{HROLD11}{
Összehoztunk egy expedíciót. Istenem, Richard... Richard Grey vezette a kis csapatot.}
{139}{}{Richard Grey?}
{140}{}{Egész pontosan hova mentek?}
{141}{HROLD12}{
Akartuk látni, mi van ott. Esetleg közbeavatkozni, bármi is ontsa magából azt a sok tetvedéket. Azt hittük, felkészültünk, de mekkorát tévedtünk.}
{142}{}{Mit csináltak?}
{143}{HROLD13}{
Nem emlékszem az útvonalra, meg ilyesmi, de abban egész biztos vagyok, hogy észak-nyugat felé voltak... szerintem.}
{144}{}{Van ennek a történetnek rövidebb verziója is?}
{145}{}{Mi történt a vezetõjükkel?}
{146}{HROLD14}{
Richard Grey orvos volt. Egy kicsit idõsebb, mint én, barátom, és szerfelett ravasz. Megtalálta a forrást!}
{147}{}{Aztán mi volt az a forrás?}
{148}{HROLD15}{
Szeretem úgy mesélni, ahogy nekem tetszik. A rövid verzió 25 dolcsiba fog kerülni, barátom. Na, melyik legyen?}
{149}{}{Oké, legyen a hosszú.}
{150}{}{A rövid.}
{151}{}{A rövid, de nincs pénzem rá.}
{152}{}{Mit szólna, ha inkább elhallgatna, maga vén trotty?}
{153}{HROLD16}{
Rendes kölöknek látszol. Kicsit megpróbálom meggyorsítani a mondókámat.}
{154}{}{Hálás köszönet.}
{155}{hrold16a}{Hazudsz itt a szegény, vén mutánsnak? Hova tart ez a világ? [Köhög]}
{156}{hrold17}{Megcsappant a pénzmag, mi?}
{157}{hrold17a}{Viseld el, vagy hagyj békén! Te választasz, barátocskám!}
{158}{}{Békén hagyom, jó?}
{159}{}{OKÉ. Legyen a hosszú verzió.}
{160}{HROLD18}{
Valami katonai bázis volt ott. Miközben be akartunk jutni, rengeteg embert vesztettünk.}
{161}{}{Honnan tudja, hogy az a bázis volt a bajok forrása?}
{162}{}{Mivel kellett szembenézniük?}
{163}{HROLD19}{
Robotokkal, meg minden ilyesmivel. Annyi volt belõlük, mint a nyû. Marha meglepõ volt, hogy még ilyen hosszú idõ múltán, a lezajlott háború ellenére is mûködtek. Barátocskám, jól megkaptuk a magunkét.}
{164}{}{Mit csináltak, miután átverekedték magukat a robotokon?}
{165}{HROLD20}{
Mert olyan volt, mintha végkiárusítás lenne mutánséknál! Atyagatya! Ott aztán megkaptuk a magunkét! Másra nem tudtunk gondolni, csak hogy ott van a gyár.}
# Cheaper by the dozen - Ez egy konyv cimebol szarmazo mondas a ficko reszerol, fogalmam sincs, mi a magyar megfeleloje. Probaltam
# felkutatni, de nem nyert - Bass{166}{}{Közelebbrõl is megvizsgálták a bázist?}
{167}{HROLD21}{
Elég jócskán behatoltunk. Addigra már nem maradtunk sokan. Grey, én meg néhány másik.}
{168}{}{És utána mi történt?}
{169}{HROLD22}{
Az egyik robot elkapta Francine-t. Mark megsebesült, visszaküldtük a felszínre. Csak Grey és én maradtunk.}
{170}{}{Mi lett Mark-kal?}
{171}{}{Mi történt utána?}
{172}{HROLD23}{
A mai napig nem tudom. Soha nem tért ide vissza, és... hát... én már képtelen lennék újra kimenni a pusztaságba. Így aztán... sosem jártam utána.}
{173}{}{Mi történt magával és Grey-jel?}
{174}{HROLD24}{
Bejutottunk a bázis gyomrába, valamiféle erõmûbe, vagy mi volt az. És akkor jött a nemulass...}
{175}{}{Micsoda?}
{176}{HROLD25}{
Egy robot-darukar nekünk csapódott. Utoljára még láttam Grey-t, amint repül egyet, és egyenesen valami savfürdõben köt ki. Nagyon rossz állapotban voltam, és hát... elájultam.}
{177}{}{Hogy élte túl?}
{178}{}{Grey-t sosem látta utána?}
{179}{hrold25a}{Nem éltem túl. Megöltek... [Nevet és köhécsel] Istenkém, ez annyira jó poén.}
{180}{}{Hát nem mondom...}
{181}{HROLD26}{
Bizony fogalmam sincs, hogy éltem túl. A pusztában ébredtem, és alig volt bennem szusz. Szerencsés voltam, és pár napon belül rámtalált néhány kereskedõ. Épp idõben, mert már megindult a változás. Idehoztak, és azóta is itt lakom.}
{182}{}{Hogy kezdett el mutálódni?}
{183}{}{Hát nem semmi egy történet. Köszönöm.}
{184}{hrold26a}{Izé... köszönöm, hogy elmondhattam.}
{185}{}{Egyébként ez volt a rövid verzió?}
{186}{hrold26a}{Izé... köszönöm, hogy elmondhattam.}
{187}{hrold26b}{Nem semmi bizony, különösen nekem...}
{188}{HROLD27}{
Nem, te idióta! Annyit mondtam csak, hogy sosem láttam többet. Vagy nem?}
{189}{}{Hogy élte túl?}
{190}{HROLD28}{
Annyit tudok, hogy valami van abban a bázisban.}
{191}{}{Lehetséges, hogy a sugárzástól van?}
{192}{}{Bocs, hogy közbevágok. Kösz a történetet.}
{193}{HROLD29}{
Honnan a fenébõl tudjam? Ha van valaki, akkor Grey tudná. [sóhajt] Egyébként ennyi lenne a nagy sztori.}{194}{}{Köszönöm a történetet.}
{195}{HROLD30}{
Ja, egy vagy két évszázad kutyaéletkorban számolva.}
{196}{}{Tessék?}
{197}{HROLD31}{
Oda se neki, az én idõmbõl való volt. Mióta megváltoztam, punnyadt és öreg vagyok, mint az országút.}
{198}{}{Mit csinált azelõtt, hogy ez történt magával?}
{199}{HROLD32}{
Nos, megmutálódtam. Nyilván nem ilyen rondának születtem. Akkor történt, amikor próbáltunk rájönni, honnan származik az a rengeteg mutáns.}
{200}{}{Mi történt?}
{201}{HROLD33}{
Régi dolgok ezek. Valószínûleg nem kéne bolygatni.}
{202}{}{Kérem, mondja el, mi történt, most nagy segítség lehet ez nekem!}
{203}{}{Legyen, ahogy akarja.}
{204}{HROLD34}{
Hát, ha így van, nem hiszem, hogy nagy bajom lenne, ha belemennék.}
{205}{}{Köszönöm.}
{206}{HROLD35}{
Nem, nem, túl nagy fájdalmat okoz, még manapság is. Köszönöm a segítséged, barátom. Sok szerencsét.}
{207}{HROLD36}{
A Hubban vagy, nem igaz? Na miféle emberek élnek a Hubban? Hublakók. Vágod? [Köhög] Atyagatya! Kösz a segítségért, és sok szerencsét... szerintem elkel majd.}
{208}{HROLD37}{
Ugyanolyan mocsok vagy, mint a többi. [Zihálva köhög]}
{209}{HROLD38}{
Amúgy, köszönöm. [Köhög]}
{210}{HROLD39}{
Hé, ki tudnál segíteni, barátom?}
{211}{}{Persze, itt van 25 dolcsi.}
{212}{}{Tessék 5 dollár.}
{213}{}{Ne csesztessen már!}
{214}{}{Öhhh?}
{215}{HROLD40}{
Köszi, köszi! El kõ ismerni, amikor elõször láttalak, [Köhög] azt gondoltam, hogy összekülönbözünk.}
{216}{}{Miért különböznénk össze?}
{217}{}{Velem ugyan nem! Minden jót!}
{218}{HROLD41}{
Óh, hát megint te vagy?}
{219}{}{Tessék 20 dollár, gondolom, jól jön.}
{220}{}{Üdv!}
{221}{}{Öhh?}
{222}{hrold42}{Bepróbálkozol, he?}
{223}{HROLD43}{
Tehetek valamit érted?}
{224}{}{Hallott valami jó pletykát mostanában?}
{225}{}{Tudnom kéne ezt-azt a Halálkarmokról, és úgy hallottam, magához nem hiába jövök.}
{226}{}{Elmondaná az élettörténetét?}
{227}{}{Nem...}
{228}{hrold43a}{Márminthogy az egészet? Hát...}
{229}{HROLD44}{
Óóóh, nagyon köszönöm. Remélem, nem volt nagy érvágás. [Köhög]}
{230}{HROLD45}{Óhhh, ja, hogy arról... Barátom, az a város rémálom. Mi a fenéért kérdezel te errõl?}
{231}{}{Ki fogom nyírni õket.}
{232}{}{Ha megszorongatnának, tudnom kell, mitévõ legyek.}
{233}{HROLD47}{Oké. Akkorák, mint egy nagy darab ember, bizony. Tüskéi és karmai vannak, amik a legkeményebb páncélt is áthasítják. Mindamellett, ne tévesszen meg a nagyságuk, ugyanis iszonyat gyorsak is.}
{234}{}{Van valami gyengéjük?}
{235}{HROLD49}{Hát, abból, amit hallottam, támadd a fejüket. Én egyenesen a szemükre mennék. Ott valami nem stimmel velük.}
{236}{}{Hogyhogy nem stimmel?}
{237}{HROLD50}{Nem lehet rájuk nézni! Azt mondják, hogy a Halálkarmok meghipnotizálnak már a nézésükkel is. Aztán odajön és nesze neked, annyi!}
{238}{}{Hát, ez nagyszerû, kösz.}
{239}{HROLD51}{Sok szerencsét neked, szükséged lesz rá.}
{240}{}{Akár...}
{241}{HROLD52}{Te nem akarsz semmit tudni a Halálkarmokról, én meg nem akarok semmit mondani róluk.}
{242}{HROLD53}{Nos, hallottam, hogy Decker egyik embere az Óvárosban fogva tart valakit az Acél Testvériségébõl.}
{243}{}{Köszönöm.}
{244}{HROLD54}{Nem hiszem ezt el, de azt mondogatják, hogy egy egész mutáns hadsereg kelt útra. [Köhög]}
{245}{}{Köszönöm.}
{246}{HROLD55}{Hagyj békén! [Köhög]}
{247}{}{Beszélni akarok magával.}
{248}{}{Itt van egy kis pénz.}
{249}{HROLD56}{Én viszont nem akarok beszé'ni veled. Menj innen!}
{250}{HROLD57}{Nem kell a pénzed. Menj el! [Köhög]}
{251}{hrold200}{Szeretek ugyan üzletelni, de egy fia cserealapom sincs. [Köhög]}
{252}{hrold201}{Aludnom kell egy kicsit, elég fáradt vagyok.}
{253}{hrold202}{Jobban kéne vigyáznod. [Köhög] Úgy hallottam, számos embert tettél el láb alól mostanában.}
{254}{hrold203}{Ömm... Decker téged kerestet. Beszélni akar veled. [Köhög]}
{255}{hrold204}{Nincs semmim, csak a ruhám meg a szabadságom, de ez utóbbit azért megkérdõjelezném.}
{256}{hrold300}{Briliáns fickó volt. Orvos és filozófus. Régen õ vezette azt az expedíciót, melynek során mutánssá változtam.}
{257}{hrold301}{Kicsoda? Ez valami szexterapeuta? Hát bizony elkelne egy nekem.}
{258}{hrold302}{Mutánsok azok. Hót mindegy, minek nevezik magukat.}
{259}{hrold303}{Ja, hogy õ... Õ a Tolvajok Körének vezetõje. Valami Robin Hoodnak képzeli magát. [köhög] Amúgy semmi gond vele.}
{260}{hrold304}{Vallások jöttek, vallások mentek, és remélem ez is az utóbbihoz fog tartozni. Mihamarabb.}
{261}{hrold305}{Jaja, én is egy Menedékbõl jöttem. Túl sok ember, kevés étel és víz. Persze honnan is tudhatnád ez, nem igaz?}
{262}{hrold306}{Szörnyûség. A világ egyszerûen megbolondult. Rég volt, de soha nem fogom elfelejteni. Soha.}
{263}{hrold307}{[Köhög] Az az ember csak bajt jelent. Semmi egyebet.}
{264}{hrold400}{Ahogy azt már mondtam...}
{265}{}{Most inkább megyek, kösz...}#
# TRANSLATION NOTE: The following groups of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#{266}{HROLD0}{Adj egy kis aprót, öreg barátom, régi cimbora... ki tudnál segíteni egy szegény, szerencsétlen mutánst? [Köhög]}
{267}{HROLD0}{Adj egy kis aprót, öreg barátom, régi cimbora... ki tudnál segíteni egy szegény, szerencsétlen mutánst? [Köhög]}
{268}{HROLD2}{Óh, nagyon rendes vagy, barátom. Nagyon rendes. Ha valaha képes lennék kitörölni a dzsuvát a Vén Harold szemébõl, még könnycseppet is találhatnál benne.}
{269}{HROLD2}{Óh, nagyon rendes vagy, barátom. Nagyon rendes. Ha valaha képes lennék kitörölni a dzsuvát a Vén Harold szemébõl, még könnycseppet is találhatnál benne.}
{270}{HROLD35}{Nem, nem, túl nagy fájdalmat okoz, még manapság is. Köszönöm a segítséged, barátom. Sok szerencsét.}
{271}{HROLD35}{Nem, nem, túl nagy fájdalmat okoz, még manapság is. Köszönöm a segítséged, barátom. Sok szerencsét.}
{272}{HROLD39}{Hé, ki tudsz segíteni, barátom?}
{273}{HROLD39}{Hé, ki tudsz segíteni, barátom?}#
# Harold's Tell-Me-Abouts
#
{1000}{}{Richard}
{1001}{}{Mester}
{1002}{}{Ghoul}
{1003}{}{Loxley}
{1004}{}{Katedralis}
{1005}{}{Menedek}
{1006}{}{Haboru}
{1007}{}{Decker}
{1008}{}{Grey}{1100}{hrold300}{Briliáns fickó volt. Orvos és filozófus. Régen õ vezette azt az expedíciót, melynek során mutánssá változtam.}
{1101}{hrold301}{Kicsoda? Ez valami szexterapeuta? Hát bizony elkelne egy nekem.}
{1102}{hrold302}{Mutánsok azok. Hót mindegy, minek nevezik magukat.}
{1103}{hrold303}{Ja, hogy õ... Õ a Tolvajok Körének vezetõje. Valami Robin Hoodnak képzeli magát. [köhög] Amúgy semmi gond vele.}
{1104}{hrold304}{Vallások jöttek, vallások mentek, és remélem ez is az utóbbihoz fog tartozni. Mihamarabb.}
{1105}{hrold305}{Jaja, én is egy Menedékbõl jöttem. Túl sok ember, kevés étel és víz. Persze honnan is tudhatnád ez, nem igaz?}
{1106}{hrold306}{Szörnyûség. A világ egyszerûen megbolondult. Rég volt, de soha nem fogom elfelejteni. Soha.}
{1107}{hrold307}{[Köhög] Az az ember csak bajt jelent. Semmi egyebet.}
{1108}{hrold300}{Briliáns fickó volt. Orvos és filozófus. Régen õ vezette azt az expedíciót, melynek során mutánssá változtam.}
