{100}{}{A Gyermekek Õre.}
{101}{}{Phillips! Vidd ki innen ezt az embert!}
{102}{}{Tûnés a szemem elõl!}
{103}{}{Mit akarsz?}
{104}{}{Mesélj a munkádról!}
{105}{}{Mire való ez a hely?}
{106}{}{Nem tudod, hol találhatnék egy víztisztító csipet?}
{107}{}{Mit tudnál mondani egy Decker nevû emberrõl?}
{108}{}{Szép fegyvered van...}
{109}{}{Öö... tejci.}
{110}{}{Bérenc vagyok. Ha bárki zargatni merészeli ezeket az ûrkadétokat, megölöm. Van ezzel valami problémád?}
{111}{}{Ezek szerint testõr vagy...}
{112}{}{Ki bérelt fel?}
{113}{}{Van valami érdekes mostanában a Hubban?}
{114}{}{Mit csináltok?}
{115}{}{Igen. Nagy probléma.}
{116}{}{Nem gond, barátom.}
{117}{}{Valami Szentséges Láng. Ne hallgass erre a sok baromságra! Szétrohasztja az agyad!}
{118}{}{Mi dolgod neked a Szentséges Lánggal?}
{119}{}{Ember, ezek az emberek aztán jó nagy hülyék!}
{120}{}{Van valami érdekes mostanában a Hubban?}
{121}{}{Honnan jöttek ezek az emberek?}
{122}{}{Nem jégcsapot keresel? Talán a hegyek közt találsz olyat.}
{123}{}{Nem csap, csip! Egy víztitszító rendszert vezérlõ számítógép alkatrésze.}
{124}{}{Nem csap, te agybeteg!}
{125}{}{Öö, kösz.}
{126}{}{Voltál valaha a hegyekben?}
{127}{}{Igen, hallottam róla. Jó nagy gyökér, de legalább kifizeti a számláit. Phillips dolgozott neki néhányszor.}
{128}{}{Szerinted faszkalap?}
{129}{}{Phillips?}
{130}{}{Elvállalnál tõle munkát.}
{131}{}{Kösz!}
{132}{}{Ja, már csak pont ez hiányzik egy tûzharcban. Mit tehetek érted?}
{133}{}{Hol vehetne egy magamfajta valami jobbféle fegyvert?}
{134}{}{Mi a dörgés ezekkel a Katedrálisbeli srácokkal?}
{135}{}{Benne lennék egy kis adok-kapokban. Valami ötlet?}
{136}{}{Nem tudod, hol találhatnék egy víztisztító csipet?}
{137}{}{Mit tudnál mondani egy Decker nevû emberrõl?}
{138}{}{Bocs, barátom, de szolgálatban nem cseverészhetek.}
{139}{}{Húzz el a szemem elõl, mielõtt kinyúvasztalak!}
{140}{}{Ez az, te Rakétatudós! Ki más lehetnék, Morbid doki? Jesszus!}
{141}{}{A papribanc. Ki másra gondoltál? Jó ég!}
{142}{}{Nehezemre esik bevallani, barátom, de hetek óta nem vagyok rajta a történéseken. Kérdezz valaki mást!}
{143}{}{Koszt meg kvártély, aztán semmi egyéb. Ezek a vallási balhék elég olcsók!}
{144}{}{Akkor oldjuk meg!}
{145}{}{Jól van. Merthogy senki nem szereti itt a problémákat.}
{146}{}{Ez egy nagy svindli. Senki nem lehet akkora idióta, hogy magától higgyen ebben a vallásos fosban. Vagy igen?}
{147}{}{Hát igen. Még jó, hogy nem fizetnek azért, hogy egyetértsek velük. Szentséges Láng, meg a valagam!}
{148}{}{Nemtom. Egy dolgot mondhatok, bármit is mondasz a vallásról, ezek nem amatõrök. Megjelentek a semmibõl és óramû pontossággal szervezték meg itt a dolgokat. Ezek itt nem egy újabb agyatlan zombicsapat.}
{149}{}{Jesszus, azt hittem, hogy csak a Menedékekben voltak olyan szarok!}
{150}{}{Vigyázz a szádra, seggfej! Ezek az emberek lehet, hogy hisznek a békében meg a szeretetben, de én nem!}
{151}{}{Nem probléma.}
{152}{}{Nahiszen! Minél magasabbra mászol, annál erõsebb a sugárzás.}
{153}{}{Hát, ha kedveled a pszichotikus, kõszívû, könyörtelen vadbarmokat, akkor õ a te embered.}
{154}{}{Õ a partnerem. Õ vigyáz Jainra.}
{155}{}{Attól függ, mennyi kockázatott mersz bevállalni. Az életem elég zûrös volt az utóbbi idõben, és azért jöttem ide, hogy meghúzzam magam. Viszont ha szereted az akciót, akkor hajrá! A lényeg, hogy ne mondj csõdöt, különben meghalsz. Ennyi az egész.}
{156}{}{Úgy hallottam, a Vízkereskedõknek mindig a legjobb cuccaik vannak, de az emberek mindenfélét összehordanak a Vízkereskedõkrõl. Én nem tartozom a tömeghez, az már átkozottul biztos.}
{157}{}{Hetek óta próbálom magam kiismerni magam ezekkel a fickókkal. Elsõre bolondoknak tûntek, de... most már nem vagyok ebben biztos. Szervezettek, és határozott terveik vannak. Én kiszagolom az ilyesmit!}
{158}{}{Deckernél részed lehet valami ilyesmiben, de barátom, szar egy meló az, és ha elcseszed, úgy megdöglesz, mint a pinty!}
{159}{}{Víztisztító csip? Nem kútból veszitek a vizet? Te jó Isten! Beszélnek itt az emberek valami Menedékrõl Shady Sands közelében, ahol találhatnál egy olyat, de a hely teljesen beomlott. Nem hiszem, hogy tudnék ebben segíteni.}
{160}{}{Nem beszélgethetek. A fõnök nem szereti. Bocs.}
{161}{}{Hé, te!}
{162}{}{Hé! Mégis mi a francot képzelsz, mit csinálsz?}
{163}{}{Mit akarsz attól a zártól?}
{164}{}{Jól van, békén hagyom!}
{165}{}{Tudnál segíteni ezzel az ajtóval? Beragadt!}
{166}{}{Megláttál! Ezt most megszívtad...}
{167}{}{Semmi közöd hozzá! Kifelé!}
{168}{}{Jó! Most pedig ki innen!}
{169}{}{Tûnés innen! Ha megint ezen a szarságon foglak, személyesen foglak megölni!}
{170}{}{Nem beszélhetek veled. Eredj a dolgodra!}
{171}{}{Hey! What do you think you're doing!}
{172}{}{Mit akarsz attól a zártól?}
{173}{}{Jól van, békén hagyom!}
{174}{}{Tudnál segíteni ezzel az ajtóval? Beragadt!}
{175}{}{Megláttál! Ezt most megszívtad...}
{176}{}{Semmi közöd hozzá! Kifelé!}
{177}{}{Jó! Most pedig ki innen!}
{178}{}{Tûnés innen! Ha megint ezen a szarságon foglak, személyesen foglak megölni!}