{100}{}{Õ Leon, az õrök egyike.}
{101}{}{Mi dolgod van neked itt?}
{102}{}{Beszélnem kell Mr. Hightowerrel.}
{103}{}{Azért jöttem, hogy megöljem Mr. Hightowert.}
{104}{}{Mi dolgod van vele?}
{105}{}{Oké, de figyellek. Mr. Hightower az irodájában van.}
{106}{}{Köszönöm.}
{107}{}{Igen... gondoltam, hogy szemmel tartasz...}
{108}{}{Nem tetszik a stílusod. Meg kell kérjelek, hogy távozz.}
{109}{}{Majd akkor elmegyek, barátocskám, ha végeztem az itteni ügyeimmel!}
{110}{}{Oké, leléptem.}
{111}{}{Stílus? Majd megmutatom én, milyen az igazi stílus!!!}
{112}{}{Bármirõl is legyen szó, nekem elmondhatod. Mr. H. most nagyon elfoglalt.}
{113}{}{Miért kell így megnehezítened a dolgomat?}
{114}{}{Inkább személyesen mondanám el neki. Élet-halál halál kérdésérõl van szó.}
{115}{}{Decker meg akarja öletni Hightowert.}
{116}{}{Mondd el, vagy menj el innen!}
{117}{}{Ki csinált belõled mindenható jóistent így hirtelenjében?}
{118}{}{Decker meg akarja öletni Hightowert.}
{119}{}{Nézd, barátom, lószart sem fogok neked elmondani!}
{120}{}{Akkor leléptem...}
{121}{}{Már megint te vagy? Ez a Decker egy oltári nagy balfasz. Ellenben... õ mégsem akkora balfasz, mint a bérencei. Gyere, skubizd meg a fegyveremet...}
{122}{}{[Leon megmutatja a fegyverét, amin öt mély rovátka látható.]}
{123}{}{Ezek mindegyike egy Hightower elleni merénylet kísérletérõl tanúskodik. Egytõl-egyig lepuffantottam õket. Meg tudnád nekem mondani, hogy néz ki a fickó, akit az a balfasz Decker felbérelt?}
{124}{}{Nem.}
{125}{}{Én vagyok az, te idióta!}
{126}{}{Hé! Ez már döfi! Rovátkákat gyûjtesz a fegyvereden! Fasza gyerek vagy!}
{127}{}{Kösz, hogy elõre szóltál, de Mr. Hightower nem szereti az itt lófráló idegeneket. Meg kell, hogy kérjelek, távozz!}
{128}{}{Ennyi? Semmi jutalom, vagy valami? Mi a franc esett az emberekbe?}
{129}{}{Nem tesz semmit. Viszlát!}
{130}{}{Mr. Hightower nem fogad látogatókat. Most pedig távozz!}
{131}{}{Majd akkor elmegyek, barátocskám, ha végeztem az itteni ügyeimmel!}
{132}{}{Oké, leléptem.}
{133}{}{Nagyon fontos, hogy beszéljek Mr. Hightowerrel.}
{134}{}{Okés. Menjünk! [Leon megragadja a karod.]}
{135}{}{Vedd le rólam a mocskos kezedet!}
{136}{}{Jól van, jól van! Megyek én, nem kell ráncigálni!}
{137}{}{Várjunk! Még nem végeztem!}
{138}{}{Ög!}
{139}{}{Rúkl!}
{140}{}{Fontos híreket hoztam Mr. Hightower számára.}
{141}{}{Mit csinálsz te itt? Most nem vagyok szolgálatban, menj és zargass mást!}
{142}{}{Szívbõl reméltem, hogy még idetolod azt a szánalmas képed valamikor! Õrség!}