{100}{}{Ez a férfi görcsösen rángatózik.}
{101}{}{Jaaajjj...}
{102}{}{Egy sápadt, inas fiatalembert látsz.}
{103}{}{Ez itt Jarvis, Seth öccse.}
{104}{}{Helló! Elnézést, nem érzem magam valami jól. Kérlek, ha tudsz segíteni a radskorpiók ellen, beszélj a bátyámmal, Seth-el!}
{105}{}{Köszönöm szépen, hogy segítettél rajtam. A nevem Jarvis, Seth öccse vagyok. Ha szükséged van valamire, csak kérdd tõlem bátran!}
{106}{}{Helló-helló. Segíthetek valamiben?}
{107}{}{Tudnál mondani valamit a bátyádról?}
{108}{}{Mondj valamit a városról!}
{109}{}{Csak csevegnék, kösz.}
{110}{}{Seth nagyon jó harcos, nagyon határozott. Néha talán túlságosan is. Ennek ellenére nagyon szívén viseli a falunk jólétét.}
{111}{}{Shady Sands városát a jelenlegi vezetõnk, Aradesh õse alapította. Aradesh az egész történetet el tudná mondani. Van kutunk és öntözünk is, így hát egész jól eléldegélünk itt.}
{112}{}{Ez az ember heveny mérgezésben szenved.}
{113}{}{Nem tudod meghatározni, mi a baja az illetõnek.}
{114}{}{A férfi radskorpió-méregtõl szenved.}
{115}{}{Nem tudod meghatározni, mi a baja az illetõnek.}
{116}{}{Ez a képzettség itt nem használ.}
{117}{}{Az elkövetkezõ néhány percben az illetõ határozott javulást mutat.}
{118}{}{Sef bátty?}
{119}{}{Ezz ahej?}
{120}{}{Duh.}
{200}{}{400 tapasztalati pontot kaptál, amiért meggyógyítottad Jarvist a mérgezésbõl.}