{100}{}{Ez az ember tapasztalt õrszemnek tûnik.}
{101}{}{Jobb lesz, ha féken tartod itt magad!}
{102}{}{Ez a város nem túl jó hely, hogy bajt keverj.}
{103}{}{Viselkedj, akkor nem kell bekeményítenünk!}
{104}{}{Látom, semmi gond veled.}
{105}{}{Csak így tovább!}
{106}{}{Szép napunk van, nem igaz?}
{107}{}{Ez itt Roncsváros. Szép hely, remek hely mindaddig, amíg a jó oldalon állsz.}
{108}{}{Vigyázz Gizmóval meg a sleppjével!}
{109}{}{Kedvelem a fõnökömet.}
{110}{}{Jobb lesz, ha elrakod azt az izét! Roncsváros békés hely, barátom, és reméljük, az is marad.}
{111}{}{Mit kéne elraknom?}
{112}{}{Ne utasítgass, balekpofa!}
{113}{}{Elfogadható. Apropó, mit ír elõ a helyi törvény a fegyverekkel kapcsolatban?}
{114}{}{Ajjaj.}
{115}{}{A fegyveredet, te félkegyelmû! Killian nem fogja elkobozni õket, de õszintén reméljük, hogy a helyükön maradnak.}
{116}{}{Ó, elnézést.}
{117}{}{Még mit nem! Senki kedvéért nem rakom el a csúzlijaimat!}
{118}{}{Össze kell szedned magd! A törvény is ezt írja elõ, és itt én vagyok az, aki betartatja. El kell raknod a fegyvereidet, önvédelmet leszámítva egyiket sem lehet elõvenni. Ha ehhez tartod magad, nem kerülsz összetûzésbe velünk, õrökkel. Ha fittyet hánysz a törvénynek, visszajuttatunk a pusztába... akár élve, akár halva, nekem mindegy.}
{119}{}{Jól van, ha már ilyen szépen tudtomra adtad.}
{120}{}{Kendd a hajadra a törvényeiteket!}
{121}{}{Hát, izé... nekem mindegy. De jobb lesz vigyáznod!}
{122}{}{Jó, hogy megkérdezted. Önvédelmet leszámítva nem veheted elõ a fegyvereidet. Ha balhét kezdeményezel, rád húzzuk a vizes lepedõt. Minden egyebet leszámítva, viselhetsz fegyvert. Egyszerûen ok nélkül ne használj se kést, se lõfegyvert. Minden jót!}
{123}{}{Hé, te ott! Nem lehet fegyveresen mászkálni! Az sem érdekel, hogy az anyád fejreejtett-e gyerekkorában. Nem lehet fegyveresen mászkálni, és kész!}
{124}{}{Hé! te! Mit lopakodsz itt?}
{125}{}{Semmit.}
{126}{}{Nem lopakodok, hanem körültekintõen járok.}
{127}{}{Öhhh.}
{128}{}{Bármit is csinálsz, ebben a városban ne csináld!}
{129}{}{Az õr rádbámul egy pillanatra. Látod rajta a felismerés szikráját, mire elõhúzza a fegyverét.}
{130}{}{Nos, öö, oké. Ahogy gondolod. Csak ne csinálj semmi rendhagyót!}
{131}{}{Kösz, viszlát!}
{132}{}{Természetesen. Féreteszem az elõvigyázatosságot, uram.}
{133}{}{Természetesen. Féreteszem az elõvigyázatosságot, hölgyem.}
{134}{}{Tedd el azt a fegyvert, különben számolnod kell a következményeivel!}
{135}{}{Oké, elég a figyelmeztetésekbõl. Hagyd el a várost, most azonnal, és soha többet ne gyere vissza, különben nagyon megkeserülöd!}
{136}{}{Hé! Mit képzelsz, mit csinálsz?}
{137}{}{Elég! Most neked annyi!}
{138}{}{Most aztán bajban vagy...}
{139}{}{Mivel Skulz bandatag vagy, letartóztatlak!}