{100}{}{Ez az ember nem más, mint Kenny megbízott.}
{101}{}{Ha a Hubbeli rendõrséggel van dolga, kérem, beszéljen Greene Seriffel! Én csak akkor látom el a feladatát, amikor bokros teendõi miatt nem ér rá.}
{102}{}{Nem tudom elhinni, hogy tényleg meghalt a seriff.}
{103}{}{Na, elõkerült végre... már vártam magára, hogy visszajöjjön. Hallottuk, hogy a seriffet megölték a harcban. Nagyon nehéz elhinni, hogy tényleg nincs többé. Olyan volt nekem, mint az apám.}
{104}{}{A Seriff megadta az instrukciókat arra az esetre, ha nem térne vissza a harcból. Megkért, hogy adjam át a jutalma hátralévõ részét. Úgy tudom, 1000 dollárról van szó. [A megbízott átad 1000 kupakot]}
{105}{}{Városunk köszönettel tartozik magának. Bárcsak maga a seriff is itt lehetne, hogy személyesen köszönhesse meg, amit tett. Viszont látásra!}
{106}{}{Jesszusom! Megölték Kennyt! Szemetek!}