{100}{}{A robot nem mûködik. A felületét borító por azt sugallja, hogy nemigen használták mostanában.}
{101}{}{A robot ugyan meg lett javítva, de még mindig nem mûködik.}
{102}{}{Nem a hardverrel van a gond, hanem valószínûleg a szoftverrel.}
{103}{}{Mivel a robot funkciói ki vannak kapcsolva, nem elérhetõk.}
{104}{}{Bütykölsz egy kicsit a meghibásodott alkatrészekkel, de több idõ kéne a javításukhoz.}
{105}{}{Újraindítod a beépített vezérlõ-számítógépet, és sikeresen mûködésbe hozod a robotot. Észreveszed, hogy a robot rádiója elromlott.}
{106}{}{Eltöltesz egy kis idõt a robot számítógépével, de nem tudod újraindulásra bírni.}
{107}{}{462-es egység bekapcsolva. Önellenerzõ-teszt. Egység pozícióadatainak beállítása. Kész. Memória fájl létrehozása. Kész. HIBA -* a parancs nincs végrehajtva.}
{108}{}{Rogga.}
{109}{}{Mi a végrehajtatlan parancsod?}
{110}{}{Na, csináld szépen, és tûnj az utamból!}
{111}{}{[Kattanás] Oki-doki! Parancs újbóli végrehajtása.}
{112}{}{462-es egység takarító feladatokra készült. Be kell fejeznem a takarítást és a karbantartást ezen a szinten.}
{113}{}{Csináld csak!}
{114}{}{Mi maradt hátra a takarításból?}
{115}{}{Tartály-Vezérlõ Terem. [Kattanás] Lista vége.}
{116}{}{Hehe. Fejezd csak be nyugodtan!}
{117}{}{1000 tapasztalati pontot kaptál ezért a kis "takarító" munkáért.}