{100}{}{A hölgy Nicole.}
{101}{}{Tudnál egy kis történelmi betekintést adni a Tanítványokról?}
{102}{}{Milyen tanítást követtek?}
{103}{}{Mi újság itt nálatok?}
{104}{}{Volna némi információm a számodra.}
{105}{Nic_1}{Üdvözlet. Bizony, nagyon örülünk neked, hogy csatlakoztál hozzánk. Reméljük, szerény hajlékunk megelégedésedre válik.}
{106}{}{Köszönöm. Tudnál egy-két dolgot mondani arról, milyen tanítást követtek itt?}
{107}{}{'A szerény' jó szó. 'A szemétrakás' jellemzõbb.}
{108}{}{Úgy van. Feltehetek néhány kérdést?}
{109}{}{Szerintem... semmi gond.}
{110}{}{Nöhh? Öh, nöh, nöh. He?}
{111}{Nic_2}{Nem hódolunk egyébnek, mint néhány lefektetett elvnek. Vissza akarjuk hozni a békét a pusztaságba. A világ a megsemmisülés felé vágtat, mi viszont próbálunk ellene tenni.}
{112}{}{Hogyan?}
{113}{Nic_4}{Megpróbáljuk emlékeztetni az embereket, mik idézték elõ a Nagy Háborút. Ezenkívül azon is dolgozunk, hogy soha többé ne fordulhasson elõ.}
{114}{}{Fel tudtok mutatni valamiféle sikert?}
{115}{}{Eléggé ábrándozásnak tûnik ez nekem... nem sok köze van a valósághoz.}
{116}{Nic_5}{Mi sosem adjuk fel a reményt. Soha nem is fogjuk, még akkor is, ha sokan a fegyverek diktálta életet élik. Ezenkívül eléggé szkeptikusak vagyunk a Katedrális Gyermekeivel kapcsolatban is...}
{117}{}{Miért, mi van velük?}
{118}{Nic_6}{Az állítják magukról, hogy békét akarnak, csakúgy, mint mi, de bárki, aki ellent mer mondani nekik, hirtelenjében eltûnik. A Sötét Istenük nem éppen az, aminek látszik, nekem elhiheted.}
{119}{}{Honnan tudjátok?}
{120}{}{Nem gondolod, hogy egy kicsit üldözési mániában szenvedtek?}
{121}{}{Többes számban beszlsz. Ez tényleg a Tanítványok véleménye, vagy csak a tied egyedül?}
{122}{Nic_7}{Nevezzük ösztönnek. Láttuk Morpheust és az Éjfajzatokat, és nem úgy néznek ki, mint a tipikus békeharcosok. A kórházaik és a békét hirdetõ megnyilvánulásaik vonzóvá teszi õket, de tudjuk, hogy gonoszság lappang a soraik közt.}
{123}{}{Nem gondolod, hogy egy kicsit üldözési mániában szenvedtek?}
{124}{}{Milyen utalások vannak erre?}
{125}{}{Nos, ha valamit találok róluk, elmondom neked.}
{126}{}{"Mi" így, meg "mi" úgy. Nem lehet, hogy csak úgy mások nevében terjesztgetsz légbõlkapott dolgokat?}
{127}{Nic_8}{Meglehet, de ez tartott bennünket életben ilyen sokáig.}
{128}{Nic_8a}{Nálunk megvan az egység. Ha nem így lenne, eltûnnénk a történelem süllyeszõjében. Bocsásd meg nekem, ha ez valamilyen módon irritál téged.}
{129}{Nic_8b}{Van még valami, amit szeretnél tudni?}
{130}{}{Van.}
{131}{}{Nincs, köszönöm. Már épp indulni akartam...}
{132}{Nic_9}{Kérdezz csak, megpróbálok mindenre válaszolni.}
{133}{Nic_10}{A magadfajták kérdéseire nincs idõnk. A segédem kivezet, ha megbocsátasz.}
{134}{Nic_11}{Ez egyáltalán nem tetszik ez nekem, de elnézem, ha bocsánatot kérsz.}
{135}{}{Sajnálom, hogy egyáltalán valaha szóba álltam veled.}
{136}{}{Rendben, elnézést kérek.}
{137}{Nic_12}{Na, jó... nincs idõnk a dajkálgatásra. Távozz tõlünk!}
{138}{Nic_13}{Meg van bocsátva... kérlek jusson eszedbe, hogy te csak vendég vagy nálunk. Nos, volna még valami egyéb?}
{139}{}{Feltehetek még néhány kérdést?}
{140}{}{Nincs, indulok is...}
{141}{Nic_14}{A legjobbakat kívánjuk neked az elõtted álló utazások során. Ha szükségét érzed, bármikor haszálatba veheted a kis bázisunkat.}
{142}{Nic_15}{Tudjuk, hogy lehetne jobb is, de ha háborúra készül az ember...}
{143}{}{Háborúra? Kivel?}
{144}{Nic_16}{A Katedrális Gyermekeivel. Hiszünk abban, hogy elhozzuk a békét a világba, de vannak dolgok, ami fölött nem lehet elsiklani.}
{145}{}{Mire gondolsz? Mivel váltották ki ezt nálatok?}
{146}{}{Miért hisztek annyira a békében?}
{147}{Nic_17}{Amióta csak feltûntek a Gyermekek, sorra tünedeznek el azok az emberek, akik nem állnak ki az õ igazukért. Azt mondják, hogy a béke követei, de nekünk más a véleményünk.}
{148}{}{Honnan tudjátok?}
{149}{}{És mit akartok lépni az ügyben?}
{150}{}{Honnan származnak a Gyermekek?}
{151}{Nic_18}{Semmi mást nem tehetünk, mint készülõdünk. Tudom azonban, hogy eljön majd az idõ, amikor meg kell küzdenünk ezekkel a Gyermekekkel és a Sötét Istenükkel.}
{152}{}{Veszélyesen hanzik. Majd szólok, ha bármit megtudok róluk.}
{153}{}{Mintha a békérõl beszéltél volna nem is olyan régen...}
{154}{Nic_19}{Remek! Bármilyen információt szívesen veszünk. Van még valami kérdeznivalód?}
{155}{}{Igen, van.}
{156}{}{Nincs, köszönöm.}
{157}{Nic_20}{Mi igazán hiszünk a békében, de ha kell megvédjük magunkat. Ha ez azt jelenti, hogy a Tanítványoknak háborúzni kell, hát legyen.}
{158}{}{Eléggé ellentmondásosan hangzik.}
{159}{}{Ez kétszínûség, nem?}
{160}{}{Rendben. Feltehetek még néhány kérdést?}
{161}{Nic_21}{Nem igazán. Azért vagyunk, hogy a békét hirdessük, de ha kell megvédjük magunkat, beleértve a hitünket is.}
{162}{Nic_21b}{Sosem értenéd igazán.}
{163}{}{Hmm, rendben. Kérdezhetek még valamit?}
{164}{}{Rendben. Azt hiszem, eljött az idõ, hogy távozzam.}
{165}{Nic_22}{Nagyjából ugyanakkor tûntek fel, amikor mi. Hallottunk pletykákat a vezetõjükrõl, Morpheusról, aki állítólag a Hasfelmetszõ banda tagja volt, mielõtt a Sötét Istenük által "megvilágosodott volna".}
{166}{}{Az ember megváltozhat.}
{167}{}{Nem tûnik, valami hû, de rokonszenves fazonnak.}
{168}{}{Na, ennek utánanézek...}
{169}{Nic_23}{Ez eléggé szabatos jellemzés. Van még valamilyen kérdésed?}
{170}{}{Igen, van.}
{171}{}{Nincs, köszönöm.}
{172}{Nic_24}{Légy nagyon résen! Természetesen jó lenne tudni, mi folyik éppen náluk.}
{173}{}{Nem bánnál még néhány kérdést?}
{174}{}{Kösz, most mennék.}
{175}{Nic_25}{Ezt a szervezetet azért alapítottuk, mert láttuk a világot beszennyezõ vérontást. Úgy tûnt, nincs remény, de az ember nem élhet reménység nélkül.}
{176}{}{Ti tehát reményt adtok az embereknek?}
{177}{}{Eléggé úgy hangzik ez, mintha a Gyermekek egyike mondta volna!}
{178}{}{Mikor alapítottátok a szervezeteteket?}
{179}{Nic_26}{Próbálkozunk. Megpróbálunk minden tõlünk telhetõt megtenni. Az emberek többsége nem figyel ránk, de néhányan igen.}
{180}{}{Nos, remélem, feltehetek még egy újabb kérdést.}
{181}{}{Eljött az idõ, hogy távozzam.}
{182}{Nic_27}{Biztos vagyok benne, hogy halála untatnálak a Tanítványok teljes történetével. Számos könyv van itt, amiben elolvashatod a történetünket.}
{183}{}{Feltehetek még néhány kérdést?}
{184}{}{Hát, köszönöm szépen. Most mennem kell.}
{185}{Nic_28}{Néhány kémünk látta, amint az Éjfajzatok ki-be mászkálnak a Gyermekek templomának hátsó bejáratán. Valami fontos van ott szerintem.}
{186}{}{Ha tapasztalok valamit, szólni fogok.}
{187}{}{Feltehetnék még néhány kérdést?}
{188}{}{Érdekes dolgok ezek, de most mennem kell.}
{189}{Nic_29}{Mirõl szeretnél hallani?}
{190}{}{Hol kezdték a Tanítványok?}
{191}{}{Ki indította ezt az egészet?}
{192}{}{Mik a céljaitok?}
{193}{Nic_30}{Messze délen, a Nagy Izzás közelében. Kemény idõk voltak azok, de sikerült túlélnünk. Csak utána tudatosult bennünk, hogy a Nagy Háborúnak sosem szabad többé megismétlõdnie.}
{194}{}{Tehát a te személyedhez fûzõdik az Apokalipszis Tanítványainak alapítása?}
{195}{}{Miért jöttetek el északra?}
{196}{Nic_31}{Miután a szüleimet megölte egy rablóbanda [felsóhajt], égetõvé vált, hogy véget vessünk a gyilkolászásnak. Az a célunk, hogy ezt a világot olyanná tegyük, amilyen a háború elõtt volt.}
{197}{}{Sajnálattal hallom, ami a szüleiddel történt.}
{198}{}{Hogy újra bekövetkezzen? Ez jó nagy hülyeség!}
{199}{}{Kik voltak azok a rablók?}
{200}{}{Mi késztetett benneteket arra, hogy feljöjjetek északra?}
{201}{Nic_32}{Sosem jöttünk rá, bár tudomásunkra jutott, hogy egy északi romos városban él egy bizonyos népség. Hagytuk az egészet.}
{202}{}{Miért? Bosszút állhatnátok!}
{203}{}{A végén hogy kerültetek ide északra?}
{204}{Nic_33}{Azért vagyunk itt, hogy békét hirdessünk, nem gyilkolni vagy gyûlöletet terjeszteni jöttünk.}
{205}{}{Nagyon úgy hangzik, mint aki fél valamitõl.}
{206}{}{Ez igazán nemes cselekedet a részetekrõl. Ha rajtam múlna, az egész bandát kiirtanám.}
{207}{}{Miért éltek most itt, északon?}
{208}{Nic_34}{Nem meglepõ. A Tanítványok azért vannak itt, hogy a hozzád hasonlókat meggyõzzék.}
{209}{}{Sok szerencsét hozzá, ez nem egyszerû eset. Ez lenne az oka, hogy északra jöttetek?}
{210}{}{Ezek után azt állítod, hogy az erõszak sosem lehet jó?}
{211}{}{Akkor még néhány kérdés nem árthat meg, ugye?}
{212}{}{Hát... most mennem kell.}
{213}{Nic_35}{[Felsóhajt] Egyszerûen még nem állsz készen, hogy felfogd a különbséget. Rendben van. Mi lenne, ha törnéd rajta a fejed, aztán visszajönnél, és beszélgetnénk róla?}
{214}{Nic_36}{Nem sok ember maradt életben délen. A sugárzás majdnem mindent beszennyezett. A megmaradt emberek többséget követett bennünket, hogy megalapíthassuk a szervezetünket.}
{215}{}{Hogy élte túl a családod?}
{216}{}{Még mindig annyira radioaktív? 80 év elteltével?}
{217}{Nic_37}{A Nagy Izzás peremvidékén éltünk. Betegségek ütötték fel a fejüket, ezért összetereltük az összes embert, és északra vettük az irányt. [Nagyot sóhajt] Ekkor ölték meg a szüleimet.}
{218}{}{Sajnálom...}
{219}{}{Miképp lehet, hogy ilyen sok idõ elteltével még mindig annyira radioaktív az a hely?}
{220}{Nic_39}{Köszönöm, igazán kedves tõled. Van még valami, amit szeretnél megkérdezni?}
{221}{}{Igen, van.}
{222}{}{Nincs, és sajnos le is kell lépnem.}
{223}{Nic_41}{A pletykák szerint volt ott valami nagyon fontos. Bombák tömkelegét szórták le oda, hogy mindenképp elpusztítsák azt a területet.}
{224}{}{Feltehetek még néhány kérdést?}
{225}{}{Érdekes, azt lehet mondani... most viszont mennem kell.}
{226}{Nic_42}{A Csonttelep eléggé kihalt, amint az látható. Adytum nyugatra van, a Katedrális Gyermekei pedig északra. Nem javaslom, hogy túlságosan délre menj a városban. A Hasfelmetszõk és a Pengések tiszta csatatérré változtatták az egészet.}
{227}{Nic_43}{Mirõl?}
{228}{}{Tudom, mi húzódik a Katedrális Gyermekei mögött.}
{229}{}{Mennyit áll szándékodban fizetni az információért?}
{230}{}{Nem számít, vedd úgy, mintha nem is mondtam volna semmit.}
{231}{Nic_44}{Na, végre! Mire jöttél rá?}
{232}{}{Mostantól én vagyok a Gyermekek vezetõje!}
{233}{}{Morpheus nem vezetõje a Gyermekeknek. A háttérben a Mester irányítja a bagázst.}
{234}{}{Ismered az Éjfajzatokat?}
{235}{Nic_45}{Na, várju... a Sötét Istenrõl beszélsz? Ugye nem azt akarod mondani, hogy valódi?!}
{236}{}{Hát, igazinak igazi, csak nem isten. Nem más, mint egy mutáns, aki mindenkibõl Éjfajzatokat akar csinálni a saját céljaira.}
{237}{}{De bizony! Jobb, ha kezdesz félni a mindenható Sötét Istentõl!}
{238}{Nic_46}{Mi köze van ehhez az Éjfajzatoknak?}
{239}{}{Ezek valójában szupermutánsok. A Mester a vezetõjük.}
{240}{Nic_47}{Mit terveznek? }
{241}{}{A Mester mindenkibõl Éjfajzatot akar csinálni. Az a mániája, hogy felsõbbrendûek, és ha mindenkit hozzájuk hasonlatossá tesz, azzal megmentik az emberiséget!}
{242}{}{Nem vagyok biztos benne. Annyit tudok csak, hogy a Mester egyre-másra Éjfajzatokká változtatja az embereket.}
{243}{Nic_49}{Mit tehetnénk vajon?}
{244}{}{Beszélni akarok a Mesterrel.}
{245}{}{Megyek, és most rögtön elintézem az egész Katedrálist.}
{246}{}{Megsemmisítettem azt a helyet, ahol a szupermutánsokat gyártják, de a Katedrális elintézéséhez segítségre van szükségem.}
{247}{Nic_50}{Nem engedhetjük ki a kezünkbõl ezt a lehetõséget. Derítsd fel a Katedrálist! Ott találkozunk majd, és segítünk lerohanni az épületet.}
{248}{}{Nem, ez nem jó. Tudsz valami titkos bejáratot a Katedrálisba?}
{249}{}{Oké. Találkozzunk ott.}
{250}{}{Ne! Nem akarom, hogy bárki más megsérüljön.}
{251}{Nic_52a}{Nem, de tudok valakit, aki segíthet. Menj el a Katedrálisba, és keress egy Laura nevû nõt! Mondd azt neki, hogy "Red Rider". Majd okozunk egy kis galibát, ha tudunk.}
{252}{}{Köszönöm. Remélem, a szerencse a mi oldalunkon áll.}
{253}{Nic_53}{A szerencsének ehhez vajmi kevés köze van. Én hiszek benned.}
{254}{Nic_56}{A sorsunk a mi kezünkben van. Reméljük, hogy érdemesek vagyunk rá.}
{255}{Nic_57}{Micsoda? Ez a mi sorsunk. A Tanítványok harcolni fognak a gonosz ellen, hogy a világ gyógyulása végre megkezdõdhessen.}
{256}{}{Nem. Megtiltom!}
{257}{}{Rendben. Találkozunk a Katedrálisnál.}
{258}{Nic_58}{[Kuncog] Te ugyan nem irányítasz bennünket. Támadni fogunk, akár beleegyezel, akár nem!}
{259}{Nic_59}{Beszélni akarsz vele? Te megõrültél!}
{260}{}{Talán nem éppen ti vagytok azok, akik folyton békérõl papolnak?}
{261}{}{Nem, és nem akadályozhatsz meg!}
{262}{Nic_60}{Hát, mi vagyunk, de...}
{263}{}{Úgy vélem, vérontás nélkül is befejezhetem ezt az egészet. Álljatok azért készen arra az esetre, ha csõdöt mondanék!}
{264}{Nic_61a}{Látom, nagyon elhatároztad magad. Megpróbálok inkább segíteni. Menj el a Katedrálisba, és beszélj egy Laura nevû nõvel! Mondd neki, hogy "Red Rider"! Ja, és még valami... próbáld ép bõrrel megúszni!}
{265}{Nic_63}{Nagyon fucsa humorérzéked van. Miért nem akkor jössz vissza hozzám, amikor komolyabb napot fogtál ki?!}
{266}{}{Elnézést, csak megeresztettem egy poént. Az Éjfajzatokhoz bizony sok köze van.}
{267}{Nic_65a}{Látom, igazi zsoldoskatona vagy. Rendben, adok 100 kupakot.}
{268}{Nic_66b}{Nos, mid van számomra?}
{269}{}{Tudom, hogy valaki meg akar szabadítani téged egy kis pénztõl. Köszönöm.}
{270}{}{Morpheus nem vezetõje a Gyermekeknek. A háttérben a Mester irányítja a bagázst.}
{271}{}{Ismered az Éjfajzatokat?}
{272}{}{A Gyermekeket idegen lények irányítják.}
{273}{Nic_67}{Sok szerencsét! Nekünk most jól át kell gondolnunk a lehetõségeinket...}
{274}{Nic_68}{Milyen nemes, milyen meggyõzõ! És még azt hittem, más vagy, mint a többi. Fogd a pénzed, és távozz!}
{275}{Nic_69}{Üdvözöllek. Most éppen miben segíthetek?}
{276}{}{Fel kell tennem néhány kérdést.}
{277}{}{Elnézést, mennem kell.}
{278}{}{Nöh, nöh, öh?}
{279}{Nic_70}{Mirõl szeretnél hallani?}
{280}{}{Csak a sajnálatomat szerettem volna kifejezni.}
{281}{}{Csak újra látni akartalak.}
{282}{Nic_70a}{Jobb lenne, ha távoznál!}
{283}{Nic_71}{Elfogadom a bocsánatkérést. Segíthetek valamiben?}
{284}{}{Feltehetek még kérdéseket?}
{285}{}{Most ennyi lenne, sajnos mennem kell.}
{286}{Nic_72}{Nagyon elfoglaltak vagyunk. Nincs tennivalód?}
{287}{Nic_74}{Mit csinálsz? Tedd le azonnal!}
{288}{Nic_75}{Megállj!}
{289}{Nic_76}{Hagyd ezt abba!}
{290}{Nic_77}{Hé! Tûnés innen kifelé!}
{291}{Nic_78}{Nos, ha te mondod. Most inkább menj dolgodra, nekünk rengeteg dolgunk van.}
{292}{Nic_79}{Beszélj errõl Jake-kel! Õ többet tud róla.}
{293}{Nic_80}{Ahogy már mondtam...}
{294}{Nic_81}{Ahogy már említettem...}
{295}{Nic_82}{Már mondtam...}
{296}{Nic_83}{Nos, ahogy már mondtam...}
{297}{Nic_84}{Üdv! Te nem elmebeteg vagy véletlenül?}
{298}{Nic_85}{Már számtalan alkalommal elmondtam. Talán kéne egy kicsit edzeni a memóriádat.}
{299}{Nic_86}{Morpheus a Katedrális Gyermekeinek vezetõje. Velejéig gonosz ember, és ezt a világ tudtára kell hoznunk.}
{300}{Nic_87}{Nem sokat tudnék mesélni.}
{301}{Nic_87a}{Laura a Katedrálisban élõ egyik beépített emberünk. Hihetetlenül elkötelezett az ügyünk iránt.}
{302}{Nic_87b}{ake a helyettesem.}
{303}{Nic_88}{Nálunk történelmi iratokat és filozófiai írásokat találhatsz... szinte minden félét. Nyugodtan nézz csak körül.}
{304}{Nic_89}{A Katedrális Gyermekei az õ tanítását követik. Azt mondják, hogy az emberiséget akarja meggyógyítani, de ez hazugság.}
{305}{Nic_90}{Nagyon keveset hallottam róla.}
{306}{Nic_91}{Õk Morpheus személyre szabott szolgái. Nagy, izmoktól dagadó teremtmények. A hátam borsózik tõlük.}
{307}{Nic_92}{Valószínûleg láttad már a kórházaikat. Békét hirdetnek, de valami hibádzik velük kapcsolatban. Rá kell jönnünk, hogy mi.}
{308}{Nic_93}{Adytum egy aprócska település. Nyugat felé megtalálod a Csonttelepen.}
{309}{Nic_94}{A Nagy Háborút megelõzõen hatalmas, virágzó város volt ez. Az édesanyám sokat mesélt róla, mára már alig maradt valami belõle. Csak romhalmaz és halál.}
{310}{Nic_95}{They war with the Blades down south. The Rippers are the most ruthless gang in the Boneyard. When we sent people to convert them, the only thing we got back were their heads.}
{311}{Nic_96}{The Blades fight the Rippers down south. They're the most agreeable of the two gangs, though that's not saying much. We've converted a few of them.}
{312}{Nic_97}{A történelmünk nem számít semmit, érdektelen a jelen szempontjából.}
{313}{Nic_98}{Minden szétégett, minden megsemmisült. Próbáljuk az embereket a béke szavára tanítani, nehogy újra megtörténhessen.}
{314}{Nic_99}{A Hub egy kereskedõváros északon. Próbálunk ott gyökeret ereszteni.}
{315}{Nic_100}{Nem tudunk kiigazodni rajtuk. Fegyvereket terjesztenek, mi a békét. Hogy mi a mozgatórugójuk...}
{316}{Nic_101}{Errõl nem tudunk semmit.}
{317}{Nic_102}{Sosem hallottunk róla.}
{318}{Nic_103}{Nem tudjuk, mirõl beszélsz.}
{319}{}{Mi egyebet tudsz a Katedrális Gyermekeirõl?}
{320}{}{Kérdezhetek még róluk ezt-azt?}
{321}{}{Kérdezhetek valami mást?}
{322}{}{Tudod, ki a vezetõjük?}
{323}{}{Gyanítasz valamit velük kapcsolatban?}
{324}{}{Segítsek eliminálni õketm?}
{325}{}{Köszönöm, minden létezõ segítség jól jön!}
{326}{}{Köszönöm az információt. Most mennem kell.}
# Nicole Tell-Me-Abouts generic responses
{980}{Nic_101}{Errõl nem tudunk semmit.}
{981}{Nic_102}{Sosem hallottunk róla.}
{982}{Nic_103}{Nem tudjuk, mirõl beszélsz.}
#
# Nicole Tell-Me-Abouts
#
{1000}{}{Morpheus}
{1001}{}{Nicole}
{1002}{}{Laura}
{1003}{}{Jake}
{1004}{}{Konyvtar}
{1005}{}{Isten}
{1006}{}{Mester}
{1007}{}{Ejfajzat}
{1008}{}{Katedralis}
{1009}{}{Adytum}
{1010}{}{Angyal}
{1011}{}{Tanitvany}
{1012}{}{Haboru}
{1013}{}{Hub}
{1014}{}{Testveriseg}
{1015}{}{Angyalok}
{1016}{}{Csonttelep}
{1017}{}{Acel}

{1100}{Nic_86}{Morpheus a Katedrális Gyermekeinek vezetõje. Velejéig gonosz ember, és ezt a világ tudtára kell hoznunk.}
{1101}{Nic_87}{Nem sokat tudnék mesélni.}
{1102}{Nic_87a}{Laura a Katedrálisban élõ egyik beépített emberünk. Hihetetlenül elkötelezett az ügyünk iránt.}
{1103}{Nic_87b}{Jake a helyettesem.}
{1104}{Nic_88}{Nálunk történelmi iratokat és filozófiai írásokat találhatsz... szinte minden félét. Nyugodtan nézz csak körül.}
{1105}{Nic_89}{A Katedrális Gyermekei az õ tanítását követik. Azt mondják, hogy az emberiséget akarja meggyógyítani, de ez hazugság.}
{1106}{Nic_90}{Nagyon keveset hallottam róla.}
{1107}{Nic_91}{Õk Morpheus személyre szabott szolgái. Nagy, izmoktól dagadó teremtmények. A hátam borsózik tõlük.}
{1108}{Nic_92}{Valószínûleg láttad már a kórházaikat. Békét hirdetnek, de valami hibádzik velük kapcsolatban. Rá kell jönnünk, hogy mi.}
{1109}{Nic_93}{Adytum egy aprócska település. Nyugat felé megtalálod a Csonttelepen.}
{1110}{Nic_94}{A Nagy Háborút megelõzõen hatalmas, virágzó város volt ez. Az édesanyám sokat mesélt róla, mára már alig maradt valami belõle. Csak romhalmaz és halál.}
{1111}{Nic_97}{A történelmünk nem számít semmit, érdektelen a jelen szempontjából.}
{1112}{Nic_98}{Minden szétégett, minden megsemmisült. Próbáljuk az embereket a béke szavára tanítani, nehogy újra megtörténhessen.}
{1113}{Nic_99}{A Hub egy kereskedõváros északon. Próbálunk ott gyökeret ereszteni.}
{1114}{Nic_100}{Nem tudunk kiigazodni rajtuk. Fegyvereket terjesztenek, mi a békét. Hogy mi a mozgatórugójuk...}
{1115}{Nic_94}{A Nagy Háborút megelõzõen hatalmas, virágzó város volt ez. Az édesanyám sokat mesélt róla, mára már alig maradt valami belõle. Csak romhalmaz és halál.}
{1116}{Nic_94}{A Nagy Háborút megelõzõen hatalmas, virágzó város volt ez. Az édesanyám sokat mesélt róla, mára már alig maradt valami belõle. Csak romhalmaz és halál.}
{1117}{Nic_100}{Nem tudunk kiigazodni rajtuk. Fegyvereket terjesztenek, mi a békét. Hogy mi a mozgatórugójuk...}{1118}{Nic_101}{Errõl nem tudunk semmit.}
{1119}{Nic_102}{Sosem hallottunk róla.}
{1120}{Nic_103}{Nem tudjuk, mirõl beszélsz.}
