{100}{}{Helló, mit tehetek érted?}
{101}{}{Ki vagy?}
{102}{}{Te vagy ennek a bandának a vezetõje?}
{103}{}{Never mind.}
{104}{}{M...Mia?}
{105}{}{Razor a nevem. Én vagyok az, ami a legközelebb áll itt a vezetõhöz.}
{106}{}{Tehát te vagy az itteni bandavezér?}
{107}{}{Milyen indok áll a délre lévõ elkerített terület mögött?}
{108}{}{Örülök, hogy találkoztunk. NAME vagyok.}
{109}{}{Örülök, hogy találkoztunk, de most mennem kell.}
{110}{}{Banda? Aligha nevezném ezt bandának, de valóban én lennék a vezetõjük.}
{111}{}{Ha nem vagytok banda, akkor mik vagytok?}
{112}{}{Hát, eléggé bandának néztek ki.}
{113}{}{Minden jót.}
{114}{}{Ez Adytum. Valóságos rabszolgatelep a Rendfenntartók elnyomása alatt. Õk persze mindenkinek azt mondogatják, hogy igazi VÁROS. Idejönnek, elviszik dolgozni az embereinket, akik aztán szépen meghalnak. Utána újra jönnek, és kezdõdik elölrõl.}
{115}{}{Nem tudjátok felszabadítani az embereiteket?}
{116}{}{Akkor minek jártatom itt a számat? Inkább azokkal a fickókkal akarok egy követ fújni.}
{117}{}{Majd gondolkodom, mit tehetek Adytum érdekében. Viszlát!}
{118}{}{Tehát... mi késztetett arra, hogy a pusztaságnak ebbe a szegletébe jöjj?}
{119}{}{Egy bizonyos víztisztító csipet keresgélek, mint egy hülye. Nem tudod, hol találhatnék esetleg?}
{120}{}{Csak úgy járom a világot.}
{121}{}{Körbenéztem errefelé is. Viszlát!}
{122}{}{Túlélésre játszó emberek vagyunk. Adytum taszított minket erre a sorsra. Elnyomnak minket, a barátainkat, családjainkat állatokként kezelik. Még arra sincs módunk, hogy védekezzünk ellenük.}
{123}{}{Miért nem veszitek fel a harcot velük?}
{124}{}{Ki ellen kéne védekeznetek?}
{125}{}{Nos, Adytum népe erõsebb és okosabb, mint ti vagytok. Jogukban áll, hogy kizsákmányolják a gyengébbet.}
{126}{}{Majd körbenézek, és meglátom, mit találok. Viszlát!}
{127}{}{Bárcsak banda lehetnénk. Legalább volnának rendes fegyvereink, amivel megvédhetnénk magunkat.}
{128}{}{Ki ellen kéne védekeznetek?}
{129}{}{Nem fogsz átverni. Degeneráltak sötét csapata vagytok, szerintem nem sok jót várhat tõletek az ember.}
{130}{}{Hát, eléggé bandának néztek ki.}
{131}{}{Nos, ebben nem tudok segíteni.}
{132}{}{Milyen indok áll a délre lévõ elkerített terület mögött??}
{133}{}{Te vagy a helyi bandavezér?}
{134}{}{Jobb fegyverekre volna szükségünk. A közelben élõ Fegyverkészítõknek vannak fegyvereik, de nem tudunk eljutni hozzájuk.}
{135}{}{Aztán miért nem?}
{136}{}{Gondolkodom, mit lehetne tenni a helyzet megoldására.}
{137}{}{A Rendfenntartók megakadályoznak minket. Õk azok, akik valójában irányítják Adytumot, nem Zimmerman. Idejönnek, elhurcolják az embereinket a városba, és rabszolgaként bánnak velük. Ha harcolni próbálunk ellenük, megölnek. Néha azért jönnek ide, és gyilkolnak le néhányunkat, hogy Zimmermanhoz vihessék az áldozatokat, és azt mondhassák, hogy megpróbáltunk betörni a városukba. Azok a mocsokládák még Zimmerman fiát is eltették láb alól!}
{138}{}{Zimmerman fiát? Miért akarnák eltenni láb alól a gyereket?}
{139}{}{Azt állítod tehát, hogy soha semmit nem ártottatok Adytumnak?}
{140}{}{Köztük és köztünk van egy Halálkarom fészek. Sosem tudtunk még beszélni egyetlen Fegyverkészítõvel sem. A Rendfenntartóknak megvan a tûzerejük, hogy kiirtsák a Halálkarmokat, de valamilyen oknál fogva mégsem teszik.}
{141}{}{Hol találom ezeket a Fegyverkészítõket?}
{142}{}{Rendben, viszlát!}
{143}{}{Josh itt élt velem... úgy értem... velünk. Tudta a háttérben húzódó igazságot. A Rendfenntartók megmondták neki, ha valaha is megpróbál az apjával kapcsolatba kerülni vagy visszatérni Adytumba, rögtön megölik.}
{144}{}{A megölésével fenyegetõztek? Mit tett az a gyerek?}
{145}{}{Elmegyek Adytumba, és utánanézek a dolgoknak.}
{146}{}{Egyik késõ éjjel megpróbált beosonni a városba, hogy elmesélje az apjának a valóságot. Figyelemmel kísértem a Rendfenntartók rádióforgalmazását aznap éjjel... amikor... elfogták a srácot. [Lenéz a földre, és lassan ingatja a fejét.] Tessék, minden itt van ezen a hololemezen.}
{147}{}{Miért nem adtad még oda ezt Josh faterjának?}
{148}{}{Esélyünk sincs arra, hogy megközelítsük Adytumot. Mielõtt elérnénk a kaput, szitává lõnének minket.}
{149}{}{Miért nem adod neki oda a lemezt?}
{150}{}{Miért nem szedtek össze egy nagyobbacska csapatot, és foglaljátok el Adytumot erõvel?}
{151}{}{Kockára tennéd értünk az életed?}
{152}{}{Miért ne. Bármit, hogy segíthessek.}
{153}{}{Esetleg. Mielõtt azonban az ujjamat is mozdítanám, utána kell néznem egy-két dolognak.}
{154}{}{Köszönöm. Ez minden bizonnyal nagy segítségünkre lesz. Sok szerencsét! [Átnyújtja a hololemezt.]}
{155}{}{Késõbb találkozunk.}
{156}{}{Helyes. Remélem, a legjobb döntést hoztad.}
{157}{}{Minden jót!}
{158}{}{A Fegyverkészítõkhöz egy kicsit keletre majd északra kell menned. Vigyázz arrafelé! A Halálkarmokat nem lehet félvállról venni. A saját szememmel láttam, ahogy az egyik Halálkarom laza suhintással kettétépett valakit.}
{159}{}{Megnézzük, mit tehetünk az ügy érdekében.}
{160}{}{Sajnálom, hogy így gondolod. Azt hiszem, az lenne a legjobb, ha távoznál.}
{161}{}{Viszlát!}
{162}{}{Segíthetek?}
{163}{}{Te vagy ennek a bandának a vezetõje?}
{164}{}{Hagyjuk...}
{165}{}{M... Mi?}
{166}{}{Banda? Aligha nevezném ezt bandának. Mondjuk én vagyok az, akihez mindenki jön tanácsért.}
{167}{}{Zimmerman küldött hozzád.}
{168}{}{Hát, eléggé bandának tûntök a szememben.}
{169}{}{Viszlát!}
{170}{}{(Kicsit idegesnek mutatkozik) Mi? Azért, hogy...}
{171}{}{...hogy golyót küldjek a fejedbe.}
{172}{}{...hogy megfizessek a fia haláláért.}
{173}{}{MICSODA??!! AZOK A ROHADT, ELBASZOTT FÉRGEK! MEGÖLÖM ÕKET, MINDET ELKÜLDÖM A POKOLBA!!!}
{174}{}{Nem-nem, te mész a pokolba.}
{175}{}{Öh... kiket akarsz te a pokolba küldeni?}
{176}{}{...a Rendfenntartókat. Õk ölték meg Josht. Én soha nem bántanám azt a fiút. A Rendfenntartók irányítják Adytumot, nem Zimmerman.}
{177}{}{Elég szánalmas egy próbálkozás, hogy kimagyarázd magad a bajból.}
{178}{}{Miért akarnák a Rendfenntartók megölni Zimmerman fiát?}
{179}{}{Josh itt élt velem... úgy értem... velünk. Tudta a háttérben húzódó igazságot. A Rendfenntartók megmondták neki, ha valaha is megpróbál az apjával kapcsolatba kerülni vagy visszatérni Adytumba, rögtön megölik. Kinevették... nagyon meg voltak gyõzõdve arról, hogy nem tud eljutni az apjához.}
{180}{}{Szóval megölték õt? Mit követett el a srác?}
{181}{}{Hogy jön ehhez a mi tervünk?}
{182}{}{Még mindig próbálok megoldást találni.}
{183}{}{M... Mia?}
{184}{}{Nem vagyok valami biztos abban, hogy erõfitogtatás nélkül jutunk valamire. Elmondom, mire van szükség. A Fegyverkészítõktõl szerzett fegyverekre.}
{185}{}{Hol vannak azok a Fegyverkészítõk? Miért nem szereztek tõlük jó kis mordályokat?}
{186}{}{Rendben, az ajánlatomat hallottad... Minden jót!}
{187}{}{Egy kicsit keletre élnek tõlünk, de van egy Halálkarom fészek félúton. Emiatt sosem volt alkalmunk beszélni a Fegyverkészítõkkel. }
{188}{}{Oké, add ide a hololemezt, és mielõtt megkörnyékezem Zimmermant, beszélek ezekkel a Fegyverkészítõkkel.}
{189}{}{Remélem, találsz rá módot, hogy segíts rajtunk. Viszlát!}
{190}{}{Mi a baj?}
{191}{}{Megölték Zimmermant!}
{192}{}{M... Mia?}
{193}{}{...most már nincs más választásunk, mint fegyvereket szerezni a Fegyverkészítõktõl. Segítesz nekünk?}
{194}{}{Segítek.}
{195}{}{Nem.}
{196}{}{Köszönöm. Isten vezéreljen az utadon.}
{197}{}{Köszönet minden segítségért. Le fogjuk rohanni Adytumot, de szívesen vennénk egy hozzád hasonló embert az oldalunkon.}
{198}{}{Nem, köszönöm. Túl sok akcióban volt már részem a héten.}
{199}{}{Benne vagyok. Örömmel látnám, ahogy közösen lenyomjuk a Rendfenntartókat.}
{200}{}{M... Mia?}
{201}{}{Elõször szeretnék Zimmermannal beszélni.}
{202}{}{Nos, újra csak köszönjük a segítséged. Viszlát!}
{203}{}{Remek. Menjünk!}
{204}{}{Nem hinném, hogy ez jó ötlet lenne, de nyugodtan megpróbálhatod.}
{205}{}{Te ártány! A Fegyverkészítõk elpusztításával az utolsó esélyünk is elszállt, hogy fegyverekhezz jussunk. Takarodj a francba! Akkor lássalak, amikor a hátam közepét!}
{206}{}{Igazán sajnálom...}
{207}{}{Egyé' te szart...}
{208}{}{Megyek, beszélek Zimmermannal, odaadom neki a hololemezt, és minden rendben lesz.}
{209}{}{Tudod mit? Inkább helyben megöllek.}
{210}{}{M... Mia?}
{211}{}{Ha a temetõbe akarsz jutni, csináld csak! Azok nélkül a fegyverek nélkül hangyafasznyi esélyünk sincs.}
{212}{}{Menj innen!}
{213}{}{Akkor lássalak, amikor a hátam közepét!}
{214}{}{Tûnés!}
{215}{}{Köszönöm.}
{216}{}{A népem végre szabad.}
{217}{}{Helló!}
{218}{}{Mi történet veled? Tán valaki fejbelõtt idõközben?}
{219}{}{Hönh?}
{220}{}{Ez itt Razor, a Pengések vezetõje.}
{221}{}{Egy nagyon szép, de szomorú szemû nõt látsz.}
{222}{}{Kérlek, menj el innen, sok dolgom van!}
{223}{}{Köszönjük, hogy segítettél a Rendfenntartók ellen. Nyugodtan maradhatsz ameddig csak akarsz. Ha gondolod, ugorj be Miles-hoz és Smittyhez. Õk esetleg tudnak neked adni ezt-azt a késõbbi utazásaidhoz.}
{224}{}{Szia, segítehek?}
{225}{}{Ki vagy te?}
{226}{}{Hutzpa!}
{227}{}{A nevem Razor. Az itteniek vezetõje vagyok. Adytum Rendfenntartóinak elnyomása alatt tengõdünk itt.}
{228}{}{A Rendfenntartókat mondod? Kinyírtam mindet. Remélem, nem baj...}
{229}{}{Kinyírtad õket? Dehogyis baj! A népem mostantól végre szabadon élhet Adytum népével együtt.}
{230}{}{Alig tudom elhinni, hogy mindet sikerült megölnöd. A Pengések és persze saját magam is nagy köszönettel tartozunk neked.}
{231}{}{Úgy hallottam, hogy a Rendfenntartók még mindig uralmuk alatt tartják Adytumot. Nem tudjátok õket mind kinyírni, ahogy már régóta szeretnétek?}
{232}{}{Ne aggódj, elintézem a dolgot.}
{233}{}{Nem hinném, hogy képes lennék rá.}
{234}{}{Veled tartanánk, de fegyverek nélkül a Rendfenntartók mindannyiunkat megölnének. Van mondjuk egy másik lehetõség is... [Razor gondolkodik egy pillanatig.] Ha rá tudnád venni a Fegyverkészítõket, hogy ellássanak minket fegyverekkel, néhányan veled mehetnénk.}
{235}{}{Nem hangzik rosszul. Megyek, és beszélek velük.}
{236}{}{Megpróbálom inkább egyedül kicsinálni azt a Rendfenntartó bandát.}
{237}{}{Üdv! Hallottam, hogy összezördültetek a Rendfenntartókkal. Szerettem volna megköszönni, hogy végre sikerült megszabadulni tõlük. A népem végre szabadon élhet Adytum lakosaival.}
{238}{}{Megpróbálom inkább egyedül kicsinálni azt a Rendfenntartó bandát.}
{239}{}{Megpróbálod? Ha segítség kell vagy sikerrel jártál, keress fel újra!}
