
#
# Coastal encounter messages
#{100}{}{Számos fura, lebegõ kreatúrát látsz...}
{101}{}{Egy kisebb patkánycsapat közeledik feléd.}
{102}{}{Egy csapat parasztot látsz, amint épp fosztogatókkal hadakoznak!}
{103}{}{Jónéhány embert látsz, amint épp horgásznak.}
{104}{}{Egy borzalmas kinézetû holttestet látsz. Elég rendesen megtépázták.}
{105}{}{Néhány víztócsát találsz...}
{106}{}{Mivel nagyon szomjas vagy, beleiszol a vízbe... Nincs valami jó íze.}
{107}{}{A víz erõsen radioaktív és gusztustalan.}
{108}{}{Ahhh...}
{109}{}{Arrgg...}
{110}{}{Fúj!}
