{100}{}{Saul, az ökölvívó-bajnok.}
{101}{}{Egy keménykötésû, izmos férfit látsz.}
{102}{}{A fickó izmait sok éves verekedés tette szívóssá, könnyed tartása tapasztalt ökölvívót enged sejtetni.}
{103}{}{Ah, hát, sok szerencsét!}
{104}{}{Ez nem a legjobb hely a fegyvereknek, barátom. Természetesen, ha a ringben akarsz próbát tenni, ne fogd vissza magad!}
{105}{}{Mit akarsz?}
{106}{}{Igen?}
{107}{}{Mit csinálsz itt?}
{108}{}{Kemény vagy, mint a vídia, mi? Fogadjunk, hogy lenyomlak.}
{109}{}{A nevem }
{110}{}{. Gondoltam, körbenézek nálatok.}
{111}{}{[Saul szívbõl felkacag.] Mi más lennék, mint bokszoló!}
{112}{}{Szerintem simán ellátnám a bajod.}
{113}{}{Hmm. Mi ebben a nagy szám?}
{114}{}{Öh köszi, de ezt most mellõzném.}
{115}{}{Saul eszméletlen.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{}
{122}{}{}
{123}{}{}
{124}{}{ [Saul szívbõl felkacag.]}
{125}{}{ [Saul fenyegetõen nevet.]}
{126}{}{Rendben. Gyorsan lerendezzük...}
{127}{}{Állj ki, vagy pofa be!}
{128}{}{Ha azt szeretnéd, hogy valaki jól beverje azt a randa etetõdet, a legjobb helyen jársz!}
{129}{}{Saulnak hívnak, ha esetleg nem tudnád...}
#ezt egy kicsit egzaktabba kellett tenni a jatek alapjan - bass

{130}{}{Öö, inkább kihagynám. Feltehetek néhány kérdést?}
{131}{}{Régóta élsz Roncsvárosban?}
{132}{}{Örülök, hogy találkoztunk, minden jót!}
{133}{}{Igen.}
{134}{}{Egész életemet itt töltöttem, ugyanis itt nõttem fel.}
{135}{}{Mit tudnál mondani errõl a helyrõl?}
{136}{}{Hogy lettél bokszoló?}
{137}{}{Hmm. Gizmónak dolgozom. Õ a tulajdonosa annak a pazar kaszinónak, ni! Jó pénzt fizet az itteni bunyósoknak! Mit szeretnél még tudni?}
{138}{}{Mit lehet itt csinálni?}
{139}{}{Tudnál mondani valamit Gizmóról és arról a bizonyos kaszinóról?}
{140}{}{Megvan már néhány éve, hogy bokszolgatok.}
{141}{}{A testvéreimmel világ életünkben folyton balhékba keveredtünk. Egyszer egy kisebb fosztogatócsapat támadta meg Roncsvárost, és egyiküket úgy levertem, mint vak a poharat. Elõbb lecsaptam, minthogy a fegyverét rámfoghatta volna. Mondjuk szerencsés voltam, Gizmo viszont szép pénzeket öl a szervezett bunyókba. Nagyon kellett a pénz, és hát... azóta nyomom az ipart.}
{142}{}{Mi történt a testvéreiddel?}
{143}{}{És mit lehet vagy érdemes csinálni itt Roncsvárosban?}
{144}{}{Tudnál valamit mondani a fõnöködrõl?}
{145}{}{Ha csak egyszerûen fel akarod tölteni a készleteidet, próbálkozz Killian Darkwater boltjában, dél-keleti irányban. Ha ki akarod aludni magad, keresd fel a közeli Hétalvó hotelt, ha viszont tovább akarsz maradni, igyál meg egy-két kupicával a Vesztõhelyen. A Skulz bandával viszont csínján bánnék a helyedben.}
{146}{}{Mit kell tudni errõl a Skulz féle társaságról?}
{147}{}{Mondj valamit a kaszinóról!}
{148}{}{Gizmo kaszinójában szokta mindenki kijátszani magából a napi fáradalmakat. Sokféle játékuk van, jól el lehet tölteni az idõt! A Hubtól errefelé az a legjobb hely!}
{149}{}{Mi egyebet lehet itt csinálni?}
{150}{}{James testvérem meghalt egy fosztogatók által végrehajtott támadás során. Röviddel azután a másik tesóm, Darrell összegyûjtött ezt-azt, és dél felé indult az Izzás néven emlegetett mítikus hely felé. Az õsök kincsét keresgélték, vagy valami ilyesmi. Azóta se láttuk.}
{151}{}{Mi késztet arra, hogy Roncsvárosban maradj?}
{152}{}{Öö, beszélhetnénk másról?}
{153}{}{Sajnálattal hallom ezt. Nagy veszteség lehet.}
{154}{}{Mit tudsz errõl az Izzásról?}
{155}{}{Köszönöm... már jónéhány év eltelt, de még mindig nehezemre esik róla beszélnem.}
{156}{}{Feltehetek néhány kérdést?}
{157}{}{Ez a lakhelyem, szeretek bokszolni. Jól élünk Trish-sel, eszem ágában sincs máshova menni.}
{158}{}{Hát, ez bizony jó dolog. Nem baj, ha másra terelem a szót?}
{159}{}{Igen-igen, találkoztam már Trish-sel.}
{160}{}{Mégpedig?}
{161}{}{Miben segíthetek?}
{162}{}{Mit lehet itt csinálni?}
{163}{}{Tudnál valamit mondani a fõnöködrõl?}
{164}{}{[Végigsimítod a fegyveredet.] Szeretnélek bemutatni a kis barátomnak.}
{165}{}{Kösz, hogy csevegtünk egyet. Viszlát!}
{166}{}{A Skulz banda rosszfiúk gyülevész hada, a Hétalvó hátsó fertályában húzták meg magukat és gyakran rontják a levegõt a Vesztõhelyen. Vigyázz velük, szeretnek villogni a késeikkel!}
{167}{}{Kösz a tanácsot. Majd vigyázok.}
{168}{}{Értem. Van még valami, amit érdemes lenne tudnom?}
{169}{}{Tartsd távol magad, ok?}
{170}{}{Trish nagyon fontos nekem.}
{171}{}{ [Saul összevonja a szemöldökét.] Sajnos nem szereti, hogy bokszolok. Nem érti meg, hogy ez az életem.}
{172}{}{Csak a testi épségedért aggódik. Valószínûleg nem bírja végignézni, ahogy folyton csak püfölnek téged, és az életedet kockáztatod Gizmóért. Ha nem találsz kompromisszumot, elvesztheted õt.}
{173}{}{Szerintem aggódik érted.}
{174}{}{Beszélhetnénk valami másról?}
{175}{}{Na, majd késõbb még találkozunk. Viszlát!}
{176}{}{Ezen még sosem gondolkoztam el. Tudom, hogy nem szereti a bokszot. Azt hiszem, el kell beszélgetnem vele errõl. Kösz.}
{177}{}{Egyszerûen nem szereti a bokszot. Ennyi.}
{178}{}{Beszélhetnénk valami másról?}
{179}{}{Késõbb találkozunk.}
{180}{}{Áh, megint te vagy? Mi az ábra?}
{181}{}{Helló.}
{182}{}{Azért jöttem, hogy móresre tanítsalak.}
{183}{}{Beszélnünk kell Trish-rõl.}
{184}{}{Tudnál mondani valamit Roncsvárosról?}
{185}{}{Az alapján, amiket hallottam, az Izzás egy hatalmas kráter, ami izzik éjszakánként. Úgy tudom, messze, messze délen van, de nem tudom pontosan, hol. Azt mondják, a helyet mindenféle mutáns szörnyeteg õrzi. Bõszen vigyáznak a Háború elõtti technológiákra.}
{186}{}{Értem. Kösz a felvilágosítást.}
{187}{}{Érdekes. Tudnál még mondani valami hasznos infót?}
{188}{}{Fej nélkül ez elég nehéz lesz, kispofa!}
