{100}{}{Ez itt Sid, Beth segédje.}
{101}{}{Jó reggelt!}
{102}{}{Jó napot, uram!}
{103}{}{Jó napot, hölgyem!}
{104}{}{Jó estét!}
{105}{}{Tudom, tudom... [suttog] sokat beszél, mi?}
{106}{}{Üdvözöljük Beth Fegyver és Pletykaboltjában.}
{107}{}{Beth, hozzád jöttek!}
{108}{}{Üdvözöljük Beth Gyönyörpalotájában.}
{109}{}{Csak nem ajándékot hoztál nekünk?}
{110}{}{[suttog] Ne mondjon neki semmit, ha azt akarja, hogy az egész város ne halljon róla!}
{111}{}{Ah, újra nálunk...}
{112}{}{Ingyen fegyver! Jöjjön, zsebelje be!}
{113}{}{A hármas fakknál árleszállítás!}
{114}{}{Õ az enyém, ne is gondoljon rá!}
{115}{}{Szereti kéretni magát.}
{116}{}{Reggeliszünet!}
{117}{}{Ebédszünet!}
{118}{}{Jó estét!}
{119}{}{Szép ez a kék öltözék, hehe. A 13-as a szerencseszáma?}
{120}{}{Ó, a rejtélyes ember!}
{121}{}{Ó, a rejtélyes asszony!}
{122}{}{Szokott tenyérbõl jósolni?}
{123}{}{Ó, Beth nagyon szereti a bõrcuccokat!}
{124}{}{Drágám, vedd már meg a bõrdzsekijét nekem!}
{125}{}{Drágám, vedd már meg a bõrdzsekijét nekem!}
{126}{}{Szép ez a tüskés páncél!}
{127}{}{Még ez az álcázás, hogy így összeolvad a környezettel! Várjunk! Hova lett?}
#stealth boy?
{128}{}{Ez aztán a faszányos öltözék!}
{129}{}{Még mit nem!}
{130}{}{Hé! Megjött a bádogember! Mi újság?}
