#ezt a marhasagot
{100}{}{Slappy.}
{101}{}{Bugi, bugi, bugi.}
{102}{}{Mérges pók, eltaposom, eltaposom...}
{103}{}{Játsszunk Globális Termonukleáris Háborút.}
{104}{}{Hol van a plédecském!?!}
{105}{}{Da... Da... Da...}
{106}{}{Ott a Hold!}
{107}{}{Addide a Sugar Baby-t!}
{108}{}{Óóóh, szép, bizony szép, de hogy jön ide a hold?}
{109}{}{Öh, beszéltem Harolddal. A Halálkarmokról szóló rész elég gázos volt. Mit tudsz mondani róluk?}
{110}{}{Beth mondta, hogy beszélgessek veled a Halálkarmokról.}
{111}{}{Mit csinálsz itt?}
{112}{}{Mi bajod?}
{113}{}{Hold nagy... szeretem!}
{114}{}{Fényesség... minden fényes, aztán lejön a fényesség, és mindannyiunknak annyi.}
{115}{}{Ahh.}
{116}{}{Halálkarom, halálkarom, ha-ha-halálkarom...}
{117}{}{Jaj már... mit tudsz a halálkarmokról?}
{118}{}{Mi bajod?}
{119}{}{Nehogy ki kelljen vernem belõled!}
{120}{}{Én csinálom, te csinálod, aztán mindenki csinálja...}
{121}{}{Na, de tényleg, mivel foglalkozol itt?}
{122}{}{Te bolond vagy...}
{123}{}{A baj olyan, mint egy levesestál. Terjedelmes.}
{124}{}{Le se tagadhatnád, hogy ezt te mondtad.}
{125}{}{Halálkarom félelmes, nagyon félelmes. Mongyuk jól néz ki. Akarod látni?}
{126}{}{El tudnál vinni a Halálkarmokhoz?}
{127}{}{A francba, dehogy!}
{128}{}{...Halálkarom, halálkarom, akkor látom, mikor akarom...}
{129}{}{Pofa be, és vigyél oda!}
{130}{}{Na, mindegy. Vigyázz magadra!}
{131}{}{Ilyent is csinálok, olyant is csinálok... találkoztál már Harolddal? Harold mókás, a haja kihullott, elfújta a szél. Ott megy... Ott! Ott!}
{132}{}{Jól van, mond csak...}
{133}{}{Verni, verni, verni, verni...}
{134}{}{Mér fúj a szél? Mér, mér, mér, mér, mér...}
{135}{}{Beth, Beth, kicsi Beth... Ha Harolddal van dolgod, beszélsz Harolddal. Õ elmondja a történetet. Slappy segít utána.}
{136}{}{OKÉ, elõször beszélek Harolddal.}