{100}{}{ úgy érzi, hogy csapda van a közelben.}
{101}{}{Érzed, hogy csapda van a közelben.}
{102}{}{ beindított egy csapdát, ami az egész bázist riasztja a jöveteletekrõl.}
{103}{}{Beindítottál egy csapdát, ami az egész bázist riasztja a jöveteletekrõl.}