{100}{}{Õ Vree.}
{101}{Vree00}{Sajnálom, de épp megzavartad a meditációmat. Kérlek, távozz!}
{102}{}{Bocsánat, késõbb visszajövök.}
{103}{}{Még visszatérek.}
{104}{}{Honnan ismerhettem volna a napirendedet?}
{105}{}{Öhhh?.}
{106}{Vree01}{Ne emeld fel a hangod, nagyon szépen megkérlek! Intézkedjek tán, hogy a Testvérek valamelyike tanítson jómodorra?}
{107}{}{Bocsánat.}
{108}{}{Izé... annyi baj legyen.}
{109}{}{Óh, de beijedtem.}
{110}{Vree02}{Üdvözletem. Jó nap ez a tanulásra. Segíthetek?}
{111}{}{Tudom, hogy te vagy a Fõkrónikás, de ez mit takar valójában?}
{112}{}{Technikai fejtágításra lenne szükségem.}
{113}{}{Öhhh...}
{114}{Vree03}{Én konzerválom az õseink tudását a jövendõ generációk számára.}
{115}{}{Érdekes elfoglaltság lehet. Ez azt jelenti, hogy nagyon vágod itt a témát?}
{116}{Vree03a}{Igen. Azt hiszem, mondhatjuk úgy, hogy "nagyon vágom itt a témát".}
{117}{Vree17}{Miben segíthetek?}
{118}{Vree17a}{Csak rajta!}
{119}{}{Szeretnék megjavítani egy víztisztító csipet. Tudsz segíteni?}
{120}{}{Szeretnék többet megtudni az itt készülõ fegyverek mibenlétérõl.}
{121}{}{Hallottam bizonyos hololemezekrõl. Hogyan lehet õket megnézni?}
{122}{}{Hogy tudnám megakadályozni a radioaktív sugárzást?}
{123}{}{Mi okozza a mutációt a világban?}
{124}{Vree18}{Beszélj a lovagokkal. Kérd meg õket, mutassák meg neked a legújabb saját tervezésû lézerpisztolyt.}
{125}{}{Köszönöm!}
{126}{}{Volna egy másik kérdésem...}
{127}{Vree19}{Nincsenek meg az adottságaid, hogy céljának megfelelõen használd fel a szent tudást.}
{128}{Vree21}{Használd a PipBoy 2000 berendezésedet, azzal átböngészheted a lemezeket. Helyezd a lemezt az olvasóba! Ha megvan a megfelelõ számítógépes ismereted, semmiség a használatuk.}
{129}{}{Hol szedhetnék magamra még több számítógépes ismeretet?}
{130}{}{Köszönöm.}
{131}{}{Feltehetek még egy kérdést?}
{132}{Vree22}{A Testvériségnek van néhány automatizált tanfolyama, amit elvégezhetsz. Tessék, megmutatom...}
{133}{Vree23}{E terminál használatával megtanulhatod az alapvetõ számítástechnikai ismereteket.}
{134}{Vree24}{Látom, nem vagy valami észkombájn. A karodon van egy hololemez olvasó...}
{135}{Vree25}{Anti-Sugárzás tablettákat kell használnod. Nekem van néhány. Ha úgy gondolod, hogy közel állsz a sugárfertõzéshez, ne légy rest használni!}
{136}{}{Köszönöm!}
{137}{}{Kérdezhetek valami mást?}
{138}{Vree26}{Ne igyál izzó vizbõl!}
{139}{Vree27}{Annak tudatában, hogy biológiai és nukleáris fegyverek garmadáját vetették be a Háborúban, meglepõ, hogy csak ekkora a mutáció mértéke. Ha elég kitartóak leszünk, nem lesz semmi gond.}
{140}{}{Miért mondod ezt?}
{141}{}{Igazad van, nem lesz itt semmi probléma.}
{142}{}{Volna még egy kérdésem...}
{143}{Vree28}{Az eddig tanulmányozott összes mutáns meddõ volt, nem tudnak szaporodni. Ha kiirtanánk a mutáció forrását, egyszerûen túlélhetnénk a mutánsokat.}
{144}{}{Egész pofás kis terv.}
{145}{}{Érdekes teória. Van erre valami bizonyíték?}
{146}{}{Volna még egy kérdésem...}
{147}{Vree29}{Tessék, itt ez a hololemez. A mutáns holttesteken végzett boncolások eredményeit tartalmazza. A napnál világosabban mutatja, hogy egyetlen mutáns sem képes a szaporodásra.}
{148}{}{Köszönöm.}
{149}{}{Kérdezhetek valami mást?}
{150}{Vree30}{Nem hinném, hogy jelen pillanatban el kéne árulnom bármit is errõl. Talán késõbb, ha már bizonyítottad elkötelezettségedet a Testvériség irányában. }
{151}{Vree31}{Meglehetõsen biztos vagyok abban, hogy rossz helyen jársz. Kérlek távozz! Nagyon elfoglalt vagyok.}
{152}{Vree32}{Így meg fogod semmisíteni a világ megmentésére hivatott tudást!}
{153}{}{Ahogy mondod, és veled kezdem.}
{154}{}{Nem-nem, csak azokat számolom fel, akik egy újabb nukleáris háborút tudnának kirobbantani.}
{155}{Vree33}{Soha! A Testvériség gondoskodik róla, hogy ez ne történhessen meg többé!}
{156}{}{Ezt mondja mindenki... kivéve te. Nagy újdonság, ha most azt mondom, hogy meghalsz?}
{157}{Vree34}{Miben segíthetek?}
{158}{}{El kell mondanom egy s más fontos dolgot Kedrickrõl. A barátunk áruló!}
{159}{}{Mit tennél abban az esetben, ha cselszövés ütné fel a fejét a Testvériségben?}
{160}{}{Nöhh. Nöh-öh-nöh!}
{161}{Vree35}{Nagyon jó. Tisztán látszik, hogy segített a fejtágítás.}
{162}{Vree36}{Kedrick? Õ mindig is hûséges tagja volt Testvériségünknek. Kétlem, hogy valaha is felfognád, mit jelent ez.}
{163}{}{Nem beszélek mellé. Kedrick áruló, és meg akarja buktatni a vezetõiteket.}
{164}{}{Hát lehet...}
{165}{Vree37}{Egészen biztos vagy ebben? Lehet, hogy kéne beszélnünk a Nagyperjellel.}
{166}{Vree38}{Ne bosszants feltevésekkel! Vigyél bizonyítékot a Nagyperjel elé, vagy tartsd a szád!}
{167}{Vree39}{Tedd, amit meg kell tenned. Ki kell irtani az eretnekséget, el kell távolítani a szégyenfoltért felelõs embert.}
{168}{}{Még akkor is, ha a Testvériség megbecsült tagja az illetõ?}
{169}{}{És ki végezné ezt az eltávolító akciót?}
{170}{Vree40}{Még akkor is... persze bizonyíték az kell.}
{171}{}{Kedrick az áruló. Meg akarja ölni a Perjeleket.}
{172}{}{Megszerzem a bizonyítékot.}
{173}{Vree41}{Akkor a Nagyperjel elé kell járulnunk. Kerítsd elõ azt a bizonyítékot, és beszélünk vele!}
{174}{Vree42}{Természetesen a Nagyperjel és Rhombus.}
{175}{Vree43}{Hallottál az eltûnt Újoncról? Szörnyû dolgok történnek mostanában!}
{176}{}{Egyetértek.}
{177}{}{Nöh-höh.}
{178}{Vree44}{Ha tudnál segíteni neki, nagyon hálás lennék.}
{179}{Vree45}{A jó cselekedeteket jutalmazni kell. Amiért kihúztad a bajból az Újoncot, fogadd el ezt a csekélységet.}
{180}{Vree46}{Ó, te vagy az? Mi járatban épp?}
{181}{}{Azért jöttem, hogy elnézést kérjek.}
{182}{}{Bocsánat, rossz szobába tévedtem.}
{183}{Vree47}{Köszönet a bocsánatkérésért. }
{184}{Vree47a}{Minden jót!}
{185}{Vree48}{Ez gyártási nehézségnek tûnik. Mi itt elméleti és tervezési munkákat végzünk. Vedd rá valamelyik lovagot, hogy segítsen!}
{186}{}{Azért kösz...}
{187}{}{Kérdezhetek valami mást?}
{188}{Vree200}{Kérlek, beszélj a többi krónikás valamelyikével! Épp próbálok befejezni egy jelentést a többi Vezetõ számára.}
{189}{Vree201}{Nem tudok errõl semmit, de esetleg érdemes lenne kutatást végeznem ez irányban.}
{190}{Vree202}{Bocsánat, de ez nem tartozik a szakterületemhez. Talán valamelyik Testvér többet tudna róla.}
{191}{Vree203}{Õrség! Õrség!}
{192}{Vree204}{Szétverted a szobámat!}
{193}{Vree205}{Mit képzelsz, mit csinálsz a dolgaimmal?}
{194}{Vree300)}{Hogy kicsoda? Várjunk csak, ez a megszólítás nagyon ismerõs nekem. Ha minden igaz, egyes mutánsok vezetõjét tituláltak így.}
{195}{Vree301}{Gondolom a Nukleáris Háborúra gondolsz. A Testvériség mindent megtesz, hogy az elveszett dolgokat helyreállítsa.}
{196}{Vree302}{Nagy sûrûségû, lézerolvasóval ellátott, mesterséges kristály alapú háttértár. Minden egyes darab 4 terabyte információt tárol.}
{197}{Vree303}{E megkínzott bolygónak és népének mi jelentjük az egyetlen megváltást. Nélkülünk az emberiség mindenképpen elpusztulna.}
{198}{Vree304}{Nem tudok mit mondani. Kérdezd a Gyártó részleget!}
{199}{Vree305}{Õ gondoskodik róla, hogy a Testvériség a tisztesség útján maradjon.}
{200}{Vree306}{Az õ feladata érvényt szerezni a Nagyperjel akaratának. Ha kell erõvel.}
{300}{}{Érdekes.}
{301}{}{Oké, ez megteszi.}
{302}{}{Ez biztos kijavítja...}
{303}{}{Jó.}
{304}{}{Tudtam, hogy mûködni fog.}
{305}{}{Mi is volt a képlet?}
{306}{}{Az nem lehet, hogy rossz az algoritmus. Valami nem stimmel ezzel a számítógéppel.}
{307}{}{Na, tessék...}
{308}{}{Naszóval, ha ezt így csináljuk... akkor bizony mûködni fog.}
{400}{}{Ha tágítani akarod a számítógépes ismereteidet, használd nyugodtan ezt a terminált!}
{401}{}{A lecke hat órát vett igénybe, és nagyon kimerített...}{980}{Vree200}{Kérlek, beszélj a többi krónikás valamelyikével! Épp próbálok befejezni egy jelentést a többi Vezetõ számára.}
#
# Vree Tell-Me-Abouts
#
{1000}{}{Mester}
{1001}{}{Haboru}
{1002}{}{Lemez}
{1003}{}{Testveriseg}
{1004}{}{Csip}
{1005}{}{Perjel}
{1006}{}{Rhombus}
{1007}{}{Exodus}
{1008}{}{Furcsa hadsereg}
{1009}{}{Kereskedo}
{1010}{}{Karavan}
{1011}{}{Hub}
{1012}{}{A Katedralis Gyermekei}
{1013}{}{Ujonc}
{1014}{}{Kronikas}
{1015}{}{Lovag}
{1016}{}{Paladin}
{1017}{}{Holo}


{1100}{Vree300}{Hogy kicsoda? Várjunk csak, ez a megszólítás nagyon ismerõs nekem. Ha minden igaz, egyes mutánsok vezetõjét tituláltak így.}
{1101}{Vree301}{Gondolom a Nukleáris Háborúra gondolsz. A Testvériség mindent megtesz, hogy az elveszett dolgokat helyreállítsa.}
{1102}{Vree302}{Nagy sûrûségû, lézerolvasóval ellátott, mesterséges kristály alapú háttértár. Minden egyes darab 4 terabyte információt tárol.}
{1103}{Vree303}{E megkínzott bolygónak és népének mi jelentjük az egyetlen megváltást. Nélkülünk az emberiség mindenképpen elpusztulna.}
{1104}{Vree304}{Nem tudok mit mondani. Kérdezd a Gyártó részleget!}
{1105}{Vree305}{Õ gondoskodik róla, hogy a Testvériség a tisztesség útján maradjon.}
{1106}{Vree306}{Az õ feladata érvényt szerezni a Nagyperjel akaratának. Ha kell erõvel.}
{1107}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1108}{Vree201}{Errõl nem tudok semmit, de olyasminek hangzik, ami megérne egy kis kutatást.}
{1109}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1110}{Vree201}{Errõl nem tudok semmit, de olyasminek hangzik, ami megérne egy kis kutatást.}
{1111}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1112}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1113}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1114}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1115}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1116}{Vree200}{Légy szíves beszélj errõl a többi krónikással! Nekem még be kell fejeznem a Perjelek részére készített jelentéseket.}
{1117}{Vree302}{Nagy sûrûségû, lézerolvasóval ellátott, mesterséges kristály alapú háttértár. Minden egyes darab 4 terabyte információt tárol.}
