{100}{}{'ы разозлил Гэри!}
{101}{}{'ы видишь Гэри.}
{102}{}{Эй! 'олько мертвяки получают водный рацион.}
{103}{}{Заткнись!}
{104}{}{Мутант тебя игнорирует.}
{1000}{}{Water}
{1001}{}{Necropolis}
{1002}{}{Set}
{1003}{}{Watershed}
{1004}{}{Hall}
{1005}{}{Lou}
{1006}{}{Ghouls}
{1007}{}{Normals}
{1008}{}{Chip}
{1100}{}{Я не знаю.}
{1101}{}{'ы в нем стоишь.}
{1102}{}{Он слабак. Нам просто надо разнести его и его мертвяков.}
{1103}{}{Это здесь.}
{1104}{}{Я не знаю.}
{1105}{}{Он босс Гарри.}
{1106}{}{Ёлюпики.}
{1107}{}{...ще большие хлюпики нежели мертвяки.}
{1108}{}{Я не знаю.}
