{100}{}{Вы видите 'анди.}
{101}{}{Что еще здесь есть?}
{102}{}{Что здесь творится?}
{103}{}{'ы слышала какие-нибудь истории с юга?}
{104}{}{Как тебе здесь нравится?}
{105}{}{Ну, это уже что-то. 'пасибо, что уделила мне время.}
{106}{TAND_1}{Привет! Я слышала, что в городе путешественник издалека, но признаться, 
не верила, пока не увидела своими глазами. Меня зовут 'анди, а вас?}
{107}{}{Мое имя }
{108}{}{.}
{109}{}{Звать меня }
{110}{}{. Запомни это.}
{111}{}{Гы???}
{112}{tand_2}{Ну,... а как вам в нашем маленьком городе? ...ще не успели соскучиться?}
{113}{}{Да нормально все. Ответишь на пару вопросов?}
{114}{}{Да, настоящий ад. 'олько и развлечений, что смотреть, как Брамы спариваются.}
{115}{}{По-моему, все нормально.}
{116}{}{Да, что есть, то есть. Немного скучновато.}
{117}{TAND_3}{ Да... Думаю, да. Да только я все равно ни разу не была за пределами города.
 'ак что вы там хотели спросить?}
{118}{TAND_4}{Ага. Знаешь, тебе повезло, что тебе довелось родиться не здесь. Здесь абсолютно нечего 
делать, а ухаживать за скотом довольно быстро надоедает, поверь мне.}
{119}{}{...сли тебе так скучно, то почему бы тебе просто не свалить отсюда?}
{120}{}{'ы наверняка преувеличиваешь.}
{121}{}{По-моему, здесь мило и безопасно.}
{122}{TAND_5}{Мне? "йти? Ёотелось бы. 'олько одна я далеко не уйду, а больше никто идти не хочет.
 А хуже всего то, что мой отец заявил, что если со мно что-нибудь случится,
 у него будет сердечный приступ. }
{123}{}{'яжко. Можно задать тебе пару вопросов?}
{124}{}{Ладно, мне пора. "дачи тебе!}
{125}{TAND_6}{О... Я должна оставаться здесь. }
{126}{TAND_12}{Поживи ты здесь с мое - и наверняка крыша бы съехала от скуки. 'ебя 
интересует что-нибудь еще?}
{127}{TAND_13}{Да уж, безопасно... и так скучно, что у меня скоро мозги закиснут и из
 ушей полезут.}
{128}{}{А почему бы тебе просто не уйти?}
{129}{}{Мне очень жаль, но у меня нет времени, чтобы послушать тебя.
 Позволь задать тебе несколько вопросов?}
{130}{TAND_14}{Ну наконец-то! Ёоть кто-то, кто меня понимает! 
Ну, конечно, тебе довелось побывать везде, тебе здесь делать нечего!}
{131}{}{...сли здесь так скучно, то почему бы тебе просто не уйти?}
{132}{}{Ну, я думаю, что ты преувеличиваешь.}
{133}{}{А по-моему, здесь мило и безопасно.}
{134}{TAND_15}{Джанктаун лежит к юго-западу отсюда. Не знаю, как далеко.
 ...ще где-то там есть жуткое место под названием Город 'мерти.
 И еще... Как там его? Да черт возьми, как же? Ах, да. Ёаб.}
{135}{tand_15a}{На юге есть несколько городов. Но с твоим огромным жизненным опытом 
ты наверняка уже это знаешь.}
{136}{}{'пасибо.}
{137}{TAND_16}{Без проблем. Что-нибудь еще?}
{300}{tand_16a}{Да, конечно.}
{138}{TAND_20}{" нас появились Рад 'корпионы! Я имею в виду, что это не очень хорошо,
 но ведь от их укусов никто не умер! Это самая занимательная вещь из
 всего произошедшего за последние годы!}
{139}{TAND_21}{' тех пор, как все Рад 'корпионы погидли от твоей руки, ничего особенного не было.
 Эх, жаль, мне не удалось посмотреть... }
{140}{TAND_22}{Как всегда. 'куч-но.}
{142}{tand_23b}{'ак себе.}
{141}{tand_23g}{'амая жуткая история, которую я слышала, это история о Руке 'мерти.}
{143}{}{'пасибо.}
{144}{}{Рука 'мерти?}
{145}{TAND_24}{Да, ладно. Это, конечно, мой дом и все такое прочее... Но здесь скучно!
 Знаешь, я бы хотела посмотреть мир.}
{146}{}{...сли тебе так скучно, почему ты еще не ушла отсюда?}
{147}{}{Да ладно, наверняка здесь не так уж и плохо.}
{148}{}{По-моему, тут мило и безопасно.}
{150}{tand_27f}{'лушай...э, но... Я.... Я предпочитаю парней, ну... Все в порядке!... Правда? 
"ффф... Прости, у меня дела.}
{149}{tand_27m}{Я не из тех девушек, к которым ты, видать, привык.
 Иди лучше, найди себе Браму или еще что-нибудь такое же.}
{151}{TAND_28}{'пасибо за разговор.
 " нас тут не так много новых лиц, так что я всегда рада поболтать со свежим человеком.
 Пока, увидимся! }
{152}{}{Пока!}
{153}{TAND_29}{Э, слушай! Мне надо пойти, присмотреть за Брамами.
 Было... уф, приятно поболтать. }
{154}{tand_30a}{Привет тебе! Чем еще могу помочь?}
{155}{}{Можно задать тебе еще пару вопросов?}
{156}{}{Ничего, спасибо.}
{157}{TAND_35}{А..., Эй, спасибо. До скорого!}
{158}{TAND_36}{Привет! Я уж боялась, что ты уходишь, и я не смогу
 поблагодарить тебя за свое спасение. О, это было здорово!
 Приключения, путешествия!... Знаешь, если я хоть что-нибудь могу сделать для тебя -
 дай мне знать.}
{159}{}{Как насчет еще пары вопросов?}
{160}{}{Как насчет... Ну, ты и я.... Поближе узнаем друг друга?}
{161}{}{Нета!.. Эта... 'пасибо, не надо.}
{162}{}{Ёрмпх!}
{163}{TAND_37}{'ы кто? Чего тебе надо?}
{164}{}{Меня зовут }
{165}{}{, твой отец прислал меня.}
{166}{}{Я твоя крестная фея. Очень похоже, правда?}
{167}{}{Да...}
{168}{TAND_38}{'ебя прислал отец? 'ы вытащишь меня отсюда?}
{169}{}{Да. Посиди здесь, я тебя выручу.}
{170}{}{Да нет, он просто предложил мне сходить, полюбоваться на тебя.}
{171}{TAND_39}{Ёорошо. " тебя есть план?}
{172}{}{Конечно, у меня всегда есть план! " меня есть целый корабль плана!}
{173}{}{Я собираюсь драться за твою свободу с главным Ёаном!}
{174}{TAND_40}{Это оно и есть? Зачем мне твой план?
 "мм...Ахх! Порядок. 'олько давай побыстрее. Я подслушала их планы, и они мне не
 понравились. }
{175}{TAND_41}{'ы? Драться с ним? 
Да ты смеешься надо мной. (Вздох.) Послушай! ...сли у тебя родится какая-нибудь 
другая мысль - говори, не стесняйся. }
{176}{TAND_42}{О! Никак, сарказм! 'ы меня собираешься выручать, или как?}
{177}{}{'очно. Погоди немного, потом дверь откроется, и тогда беги со всех ног.}
{178}{}{Я собираюсь драться за твою свободу с самым главным Ёаном.}
{179}{TAND_43}{Аа, это опять ты! 'ейчас ты вытащишь меня отсюда?}
{180}{}{Да. Посиди здесь, я тебя выручу.}
{181}{}{Нее, я просто хочу поболтать с тобой о том о сем.}
{182}{}{Даа}
{183}{tand_43a}{Ёелло, разуй глаза! Вытащи меня отсюда, да поторапливайся. ПО'ОРОПИ'Ь, МАЛО ЛИ Ч'О ИМ ПРИД...' В ГОЛОВ"!}
{184}{tand_43b}{Нет времени для болтовни, пошевеливайся, надо выбираться отсюда.}
{185}{TAND_44}{Арадеш это мой папочка. Он совсем неплохо играет свою роль.}
{186}{TAND_45}{Это я. А тебе что пришло в голову?}
{187}{TAND_46}{Разло - старенький доктор, живущий в восточной части города. Он хорошо лечит людей, хоть уже сам и мхом порос. }
{188}{TAND_47}{'етх - капитан стражи. Мой отец пытался осуществить нашу помолвку, но этот герой не моего романа.}
{189}{TAND_48}{Агата наша городская достопримечательность. Она известная сказительница, мы любим ее истории. 'ходи к ней и не пожалеешь.}
{190}{TAND_49}{Как мне доводилось слышать, они очень плохие люди. Мой отец знает о них побольше. Он никогда ничего мне не рассказывает.}
{191}{TAND_50}{'ам мы получаем всю нашу воду. 'ак было всегда, даже до того, как я родилась.}
{192}{TAND_51}{Однажды я видела это существо своими глазами, правда издалека. "родливые монстры, с клешнями и большущим жалом. Их яд смертелен, если вовремя не принять экстренных мер. Поговори с папочкой, Арадешем, он знает побольше моего. }
{193}{TAND_52}{От путешественника с юга я слышала странную историю. Будто бы Рука 'мерти это опасное чудище, убивающее людей по ночам и растворяющееся в воздухе. Никто не смог поймать его или хотя бы ранить. Не очень-то я в это верю.}
{194}{TAND_53}{Джанктаун это небольшое поселение на юго-западе. Предполагают, там идет бойкая торговля, но мой папаша даже не пытался заглянуть туда. Он говорит, мы должны быть защищены. "гу, как бы не так. Заперты как в клетке! }
{195}{TAND_54}{Говорят, Ёаб - огромный город далеко на юге. Я всегда стремилась там побывать, но к сожалению, принуждена сидеть тут. }
{196}{TAND_55}{Я ничего не поняла, но человек, рассказывавший мне об этом, был напуган до смерти. Он кричал о нечисти, бродящей по улицам! }
{197}{TAND_62}{Ничего не знаю. Впрочем, попробуй расспросить об этом 'етха или моего папу.}
{198}{TAND_63}{Ёмм...Чего-то не припоминаю. }
{199}{TAND_64}{Ёмм..нет. Никогда не слышала об этом. }
{200}{TAND_65}{Эй! Чего это ты делаешь! Немедленно положи на место! }
{201}{TAND_66}{Ага, дождался! Вот я все папочке расскажу! }
{202}{TAND_67}{Какого черта ты собираешься делать? Прекрати сейчас же! }
{203}{TAND_68}{Каким образом тебе удалось сюда забраться? "ходи, пока отец не проснулся.}
{204}{TAND_69}{Как я сказала...}
{205}{TAND_70}{Послушай, ведь я же говорила... }
{206}{TAND_71}{'нова? Ёелло? 'колько раз мне придется твердить одно и то же? Давай, вынь бананы из ушей, сразу станет полегче!}
{207}{TAND_72}{Оо. да, мне приходилось слышать об этом. Но лучше сходи в гости к Агате. ...й многое известно.}
{208}{}{Надо выбираться отсюда.}
{300}{}{Ого! Да здесь все совсем не так, как в Шэйди 'эндс.}
{301}{}{Эй, чего это там за странная штука?}
{302}{}{Когда я расскажу обо всем этом людям в Шэйди 'эндс, никто мне не поверит.}
{303}{}{Рад 'корпионы тебе больше не попадались?}
{304}{}{Куда мы сейчас направляемся?}
{305}{}{Когда мы доберемся до Шейди 'эндс?}
{980}{TAND_62}{Ничего не знаю. Впрочем, попробуй расспросить об этом 'етха или моего папу.}
{981}{TAND_63}{Ёмм...Чего-то не припоминаю. }
{982}{TAND_64}{Ёмм..нет. Никогда не слышала об этом. }
{1000}{}{Aradesh}
{1001}{}{Tandi}
#
{1002}{}{Razlo}
{1002}{}{Seth}
{1003}{}{Raiders}
{1004}{}{Well}
{1005}{}{Scorpions}
{1006}{}{Claw}
{1007}{}{Junktown}
{1008}{}{Hub}
{1009}{}{City}
{1010}{}{Scorpion}
{1011}{}{Khans}
{1100}{TAND_44}{Арадеш это мой папочка. Он совсем неплохо играет свою роль.}
{1101}{TAND_45}{Это я. А тебе что пришло в голову?}
#
{1102}{TAND_46}{Разло - старенький доктор, живущий в восточной части города. Он хорошо лечит людей, хоть уже сам и мхом порос. }
{1102}{TAND_47}{'етх - капитан стражи. Мой отец пытался осуществить нашу помолвку, но этот герой не моего романа.}
{1103}{TAND_49}{Как мне доводилось слышать, они очень плохие люди. Мой отец знает о них побольше. Он никогда ничего мне не рассказывает.}
{1104}{TAND_50}{'ам мы получаем всю нашу воду. 'ак было всегда, даже до того, как я родилась.}
{1105}{TAND_51}{Однажды я видела это существо своими глазами, правда издалека. "родливые монстры, с клешнями и большущим жалом. Их яд смертелен, если вовремя не принять экстренных мер. Поговори с папочкой, Арадешем, он знает побольше моего. }
{1106}{TAND_52}{От путешественника с юга я слышала странную историю. Будто бы Рука 'мерти это опасное чудище, убивающее людей по ночам и растворяющееся в воздухе. Никто не смог поймать его или хотя бы ранить. Не очень-то я в это верю.}
{1107}{TAND_53}{Джанктаун это небольшое поселение на юго-западе. Предполагают, там идет бойкая торговля, но мой папаша даже не пытался заглянуть туда. Он говорит, мы должны быть защищены. "гу, как бы не так. Заперты как в клетке! }
{1108}{TAND_54}{Говорят, Ёаб - огромный город далеко на юге. Я всегда стремилась там побывать, но к сожалению, принуждена сидеть тут. }
{1109}{TAND_55}{Я ничего не поняла, но человек, рассказывавший мне об этом, был напуган до смерти. Он кричал о нечисти, бродящей по улицам! }
{1110}{TAND_51}{Однажды я видела это существо своими глазами, правда издалека. "родливые монстры, с клешнями и большущим жалом. Их яд смертелен, если вовремя не принять экстренных мер. Поговори с папочкой, Арадешем, он знает побольше моего. }
{1111}{TAND_49}{Как мне доводилось слышать, они очень плохие люди. Мой отец знает о них побольше. Он никогда ничего мне не рассказывает.}
