{100}{}{Вы видите 'ерезу.}
{101}{}{Привет, }
{102}{}{. Как проходит ваше путешествие?}
{103}{}{Вполне хорошо, спасибо.}
{104}{}{Не слишком хорошо.}
{105}{}{Ёуггх!}
{106}{}{Ёорошо, что так. Я знала, что внешний мир не может быть настолько плох, как говорят. Я имею в виде, что наши потомки уже живут снаружи, так? Но этот параноик 'мотритель не разрешить нам уйти.}
{107}{}{" 'мотрителя, наверное, есть на это причины.}
{108}{}{На самом деле снаружи мир довольно плох.}
{109}{}{Вы правы: снаружи не все так плохо, как кажется.}
{110}{}{'мотритель просто пытается защитить нас. Мир снаружи опасен для тех, кто к нему не готов.}
{111}{}{Мне жаль это слышать. Я надеюсь, что вы сумеете найти фильтр скорейшим образом.}
{112}{}{Не вопрос.}
{113}{}{Во всеми теми проблемами, с которым я встречаюсь, это займет время.}
{114}{}{Гм. Мне кажется, опрометчиво надеяться на то, что мир снаружи научил вас общаться. Ну пусть.}
{115}{}{Ага, и выбрал он вас на поход наружу только потому, что он знал, что вы находитесь под его контролем! Он попросту не хочет терять над нами контроль.}
{116}{}{Я возмущен этим замечанием!}
{117}{}{Мне на самом деле кажется, что он думает, что не имеет смысла рисковать жизнью снаружи, пока внутри все еще безопасно.}
{118}{}{Гм. Из того, что я прочла, наружный мир не весь настолько опасен. Но вы, должно быть, знаете это лучше меня, не так ли?}
{119}{}{Я знала, что снаружи не может быть настолько плохо. Поэтому я пытаюсь убедить других пойти со мной наружу. Мне кажется, что у нас больше шансов выжить снаружи.}
{120}{}{Что вы курите?!!}
{121}{}{Это, вероятно, хорошая идея.}
{122}{}{Предположим. Я всегда считала, что у него когда-то был трудное путешествие. Но мне кажется, что он не стал бы 'мотрительом, если бы его не волновало наше благополучие, не так ли? Мне думается, что нам следует подождать и посмотреть, сможете ли вы найти фильтр.}
{123}{}{Не беспокойтесь, я об этом позабочусь.}
{124}{}{Ну что же вы! Проснитесь! ...сли он считает, что снаружи настолько опасно, как же случилось, что он послал вас туда? " человека просто комплекс управленца и бюрократа. Вы - тупое орудие в его руках и даже этого не знаете!}
{125}{}{Честно говоря, если бы он думал, что снаружи настолько опасно, он бы послал целую группу людей, а не только вас. Но вы его пешка, и он не хочет, чтобы кто-нибудь понял, что они теряют.}
{126}{}{Ну, подумайте же! Неужели вы в самом деле считаете, что мы можем жить в этом Ёранилище поколение за поколением? Ну хорошо, найдете вы фильтр. А что будет, когда еще что-нибудь сломается? И потом еще что-нибудь?}
{127}{}{Ём. Да, похоже, вы правы.}
{128}{}{Мы, наверное, не можем оставаться здесь вечно. Но спешить в мир без подготовки и без согласия всей группы - не выход из положения.}
{129}{}{Многие из нас думают так. И мы планируем взять немного снаряжения и запасов и уйти наружу через несколько дней. 'кажите, какой совет вы можете нам дать?}
{130}{}{Извините, я пока что мало нашел снаружи.}
{131}{}{Вы можете направиться в маленькую деревушку под названием Шэйди 'эндс, это несколько дней пути на восток. Они могли бы помочь.}
{132}{}{Ёорошо. 'пасибо.}
{133}{}{"ходите! Нам не нужна помощь одной из пешек 'мотрителя!}
{134}{}{Добро пожаловать на нашу встречу! Раз для похода наружу 'мотритель выбрал вас, то, может быть, вы можете дать нам какие-нибудь советы, прежде чем мы тоже направимся к внешней двери.}
{135}{}{Не пейте светящуюся воду.}
{136}{}{Да... не идите наружу.}
{137}{}{Мне кажется, что ваши планы ухода не проработаны.}
{138}{}{Бааааа!}
{139}{}{'пасибо. Я вижу, что вы сможете нам сильно помочь. Почему бы вам просто не уйти?}
{140}{}{Извините, я собираюсь здесь послушать это.}
{141}{}{Чудесно.}
{142}{}{В самом деле? Посмотрите на наше положение! " нас не хватает воды! А потом, для чего изначально строилось это Ёранилище? Почему же вы считаете, что нам следует остаться?}
{143}{}{Это просто плохая идея, вот и все.}
{144}{}{Мир снаружи очень опасен для неподготовленных. Лучшим будет, если у вас будет время на соответствующую подготовку перед отправлением. 'мотритель пытается дать Ёранилищу это время.}
{145}{}{Ну, учтя, что у вас есть некоторый опыт в части выживание снаружи, вы, возможно, могли бы оказать нам некоторую ценную помощь.}
{146}{}{'наружи опасно, там полно враждебных существ. Вы долго не проживете.}
{147}{}{Мне требуется еще немного времени, чтобы найти водяной фильтр.}
{148}{}{...сли вы не можете привести нам хорошие доводы, почему мы не должны уходить, то мы не собираемся вас слушать и умереть от отравления водой. Не стойте на нашем пути, пожалуйста.}
{149}{}{Извините, люди. Не могу вам позволить это.}
{150}{}{Ладно, пусть это будет ваш выбор.}
{151}{}{Когда у нас закончится здесь вода, это всего лишь вопрос времени. Но Ёранилище не строилось для того, чтобы держать там людей вечно. " нас есть люди, есть припасы и есть желание уйти отсюда. " нас больше шансов.}
{152}{}{'наружи слишком опасно.}
{153}{}{Да, но люди должны были покидать Ёранилище всей группой, а не маленькими партиями, которых легко уничтожить.}
{154}{}{Да. Здесь вы, похоже, правы. Наверняка снаружи есть еще выжившие люди, и они могут оказаться враждебно настроенными. Мне думается, нам придется подождать, чтобы все оказались готовы.}
{155}{}{Мы хорошо подготовлены. " нас есть снаряжение и имитатор тренировки. Несколько идиотов снаружи - это лучше, чем медленная смерть от жажды.}
{156}{}{Извините, не могу позволить вам уйти.}
{157}{}{Ладно. "дачи!}
{158}{}{Мне это не нравится, но я думаю, что нам надо подождать, пока все не окажутся готовы уйти вместе.}
{159}{}{Это ради вашего блага. Поверьте мне, я знаю, о чем говорю.}
{160}{}{'пасибо вам всем, что пришли.}
{161}{}{Наши планы продолжают развиваться.}
{162}{}{' каждой неделей на нашей стороне все больше народу.}
{163}{}{Вскоре мы получим доступ к нужным нам приборам.}
{164}{}{Водяной фильтр все еще не найден. Мы должны скоро уходить.}
{165}{}{'мотритель не может противостоять такой большой группе.}
{166}{}{Будьте спокойны. Нам потребуется всего лишь еще несколько недель.}
{167}{}{'огда мы наконец-то будем свободны от Ёранилища и 'мотрителя.}
{168}{}{Помните, вы должны практиковать свои навыки на имитаторах!}
{169}{}{Да будет все хорошо, люди.}
{170}{}{Поспешите и найдите водяной фильтр. Мы не можем больше ждать.}
{171}{}{Не беспокойтесь, я сделаю это.}
{172}{}{Я не думала, что вам это удастся, но вы сделали хорошую работу. 'пасибо, что спасли нас.}
{173}{}{Вы получили 750 единиц опыта за мирное успокоение революционной фракции Ёранилища.}
{174}{}{Предатель! Почему ты вернулся сюда? 'еперь все умрут!}
{175}{}{Мы прошли это раньше. Оставьте нас.}
# Theresa's tell-me-abouts
{1000}{}{Chip}
{1001}{}{Vault}
{1002}{}{War}
{1003}{}{Outside}
{1004}{}{Overseer}
{1005}{}{Water}
{1006}{}{Waterchip}
{1100}{}{Без него у нас не останется питьевой воды. Нам необходимо прекратить быть зависимыми от этих механизмов и стать самодостаточными.}
{1101}{}{Ёранилище было нашим домом много времени, но теперь нам пора самим пробивать свою дорогу через наружный мир.}
{1102}{}{Я думаю, мы получили урок. Пора прекратить сожалеть о старом мире и строить новый.}
{1103}{}{'наружи - это там, где нам следует быть. Это великое приключение - начать все сначала и жить собственными усилиями и способностями.}
{1104}{}{Он потерян в прошлом. Он не может принять, что нам пора строить свое будущее.}
{1105}{}{Без него у нас не останется питьевой воды. Нам необходимо прекратить быть зависимыми от этих механизмов и стать самодостаточными.}
{1106}{}{Без него у нас не останется питьевой воды. Нам необходимо прекратить быть зависимыми от этих механизмов и стать самодостаточными.}
