#
# This file is used for the hi-res patch settings (choose Settings and then Screen Settings from the main menu)
#
#
{0}{}{PREFERENCIAS}
{1}{}{OPCIONES DE VIDEO}
{3}{}{Opciones}


{50}{}{Opciones de video}
{51}{}{Personalizado}
{52}{}{Ancho}
{53}{}{Alto}
{54}{}{Vale}
{55}{}{Cancelar}
{56}{}{Fallout debe reiniciarse para poder aplicar la configuración.}
{57}{}{¿Te gustaría reiniciar Fallout ahora?}
{58}{}{Sí}
{59}{}{No}
{60}{}{}


{100}{}{Hi-Res}
{101}{}{RESOLUCIÓN}
{102}{}{Colores}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Cambiar barra lateral}
{107}{}{Invertir lista}
{108}{}{Modo Ventana}
{109}{}{Establecer Tecla de Desplazamiento}
{110}{}{Escalado X2}
{111}{}{FRECUENCIA}

{130}{}{Tecla de Ventana}
{131}{}{Seleccionar}
{132}{}{Nombre}

{140}{}{Modo Gráfico:}
{141}{}{Básico}
{142}{}{Modo Sfall DirectX 9:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Escalado}
{151}{}{No}
{152}{}{Fit}
{153}{}{Fill}

{154}{}{Vídeos}
{155}{}{Splash}
{156}{}{Ayuda}
{157}{}{Muerte}
{158}{}{Final}
{159}{}{Menú}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{MODO DX-9}
{203}{}{Off}
{204}{}{PANTALLA COMPLETA}
{205}{}{Ventana}
{206}{}{GPU Blitting}
{207}{}{Esta opción no tiene efecto en Modo Gráfico Básico.}

{250}{}{Ignorar Límite de Desplazamiento}
{253}{}{Rango de Búsqueda de Ruta}
{254}{}{Normal}
{255}{}{Máximo}
{256}{}{Activar Niebla de Guerra}
{257}{}{Visibilidad de Niebla}
{258}{}{Oscuro}
{259}{}{Claro}

{300}{}{PRESIONA UNA TECLA o ESC para cancelar.}

{500}{}{Configuración del Hi-Res Patch.}
{501}{}{Establece la resolución, modo de color y frecuencia de actualización para el modo de pantalla completa.}
{502}{}{Establece el color de salida para el modo de pantalla completa.}
{503}{}{Establece la frecuencia de actualización. Ponlo en "0" para la config. predeterminada del controlador.}
{504}{}{Haz clic en el recuadro para personalizar el Ancho en el modo pantalla completa.}
{505}{}{Haz clic en el recuadro para personalizar el Alto en el modo pantalla completa.}
{506}{}{Activa o desactiva el Modo Ventana.}
{507}{}{En Modo Ventana, esta será la tecla que deberás presionar cuando uses el ratón para desplazarte por los mapas.}
{508}{}{Pulsa el botón rojo para elegir una tecla diferente. O haz clic en el recuadro para editar el código de la tecla virtual.}
{509}{}{El nombre de la tecla seleccionada actualmente.}
{510}{}{Activa el escalado. Aumentará la res. mínima a 1280x960. El Modo Ventana requerirá más espacio para su marco.}
{511}{}{Activa o desactiva la Niebla de Guerra. Se recomienda activar antes de entrar en un mapa por primera vez.}
{512}{}{Ajusta el nivel de luz y la capacidad de la acción "Examinar" en suelos, paredes y objetos dentro de la niebla.}
{513}{}{El paisaje estará siempre visible y la acción "Examinar" funcionará con normalidad.}
{514}{}{El paisaje estará oscurecido y no se permitirá usar la acción "Examinar" hasta que se descubra este.}
{515}{}{Al activarse, podrás alejar la cámara del personaje todo lo que quieras. Funciona bien con la Niebla de Guerra.}
{516}{}{Aumenta el nº de nodos de búsqueda  para extender el rango de búsqueda de rutas. 2000 nodos por nivel.}
{517}{}{2.000 nodos (valor original). Nota: Cada nivel requiere 156,25 KB de memoria adicional.}
{518}{}{40.000 nodos. Nota: requiere 3.200.000 bytes (3.125 KB) de memoria.}
{519}{}{Establece como se muestran ciertas pantallas. N. del T: "Final" se refiere a las diapositivas del final del juego.}
{520}{}{Tamaño original.}
{521}{}{Estirar para ajustar el tamaño de la pantalla mientras se mantiene la proporción original.}
{522}{}{Estirar para llenar la pantalla. Nota: Habrá un espacio en la parte baja de la pantalla si se activan los subtítulos.}
{523}{}{Haz clic abajo para mostrar como se verá la barra lateral dentro del juego.}
{524}{}{Aplicar cualquier cambio y salir.}
{525}{}{Salir sin guardar.}
