{100}{}{This is a holodisk detailing The Brotherhood of Steel's code of conduct.}
{101}{}{PIP-Boy 2000 displays: "Downloading data from disk...... File found on system. Aborting download."}
{102}{}{PIP-Boy 2000 displays: "Downloading data from disk... ... ... Download complete. Have a nice day."}
{103}{}{You see an encryption decoder disk.}
{104}{}{You see a holodisk.}
