{100}{}{The container appears locked.}
{101}{}{You successfully pick the lock.} #todo_normal success	Sduibek
{102}{}{This lock is beyond your ability to pick.}
{103}{}{You fail to pick the lock.}
{104}{}{The locker is already unlocked.}
{105}{}{You break your picks in the lock!} #todo_ increase percentage
{106}{}{You deftly pick the lock.} #todo_crit success		Sduibek
