#{100}{}{We're heading back to Hub.}
{100}{}{我们正要返回哈伯城。}
#{101}{}{Are you goin' to return with us?}
{101}{}{你要和我们一同返回吗？}
#{102}{}{I love this job!}
{102}{}{我爱这个工作！}
#{103}{}{Hope I have enough bullets.}
{103}{}{希望我的弹药充足。}
#{104}{}{Ready to go.}
{104}{}{准备出发。}

#{105}{}{Let's go!}
{105}{}{上路吧！}

#{106}{}{Get movin'!}
{106}{}{继续前进！}

#{107}{}{We killed them all!}
{107}{}{我们要把他们全干掉！}
#{108}{}{That was easy!}
{108}{}{那真是简单！}
#{109}{}{Don't talk, move yer ass!}
{109}{}{不要多话，快走笨蛋！}