#{100}{}{Hello, what can I do for you?}
#{101}{}{Who are you?}
#{103}{}{Never mind.}
#{104}{}{A...Wha?}
#{105}{}{Razor's the name.  I'm the closest thing we have to a leader.}
#{106}{}{So you are the leader of this gang?}
#{107}{}{What's the story with the Fenced area to the south?}
#{108}{}{Good to meet you.  I'm NAME.}
#{109}{}{Good to meet you.  But I must be going.}
#{110}{}{Gang?  We're hardly a gang. But I am the leader here.}
#{111}{}{If you're not a gang, then what are you?}
#{112}{}{Well, you look like a gang to me.}
#{113}{}{Goodbye}
#{114}{}{That's Adytum. It's a slave labor camp run by a group called the Regulators, but they tell everyone it's a "town". They come here and take our people to work them until they die. Then they come and take more of us.}
#{115}{}{Can't you go in there and free your people?}
#{116}{}{Then what am I talking to you for? Those are the guys I need to hook up with.}
#{117}{}{I'm going to go find out what I can about Adytum. Goodbye.}
#{118}{}{So.  What brought you to this corner of the wastes?}
#{119}{}{I'm looking for a Water Chip.  Do you know where I can find one?}
#{120}{}{I'm just walking the earth.}
#{121}{}{Just lookin' around.  Bye.}
#{122}{}{We are just people tryin' to survive.  Adytum put us in this position.  They keep us down  and use our friends and families like animals. We don't even have a way to defend ourselves.}
#{123}{}{Why don't you  fight them?}
#{124}{}{Defend yourselves from who?}
#{125}{}{Well, the people of Adytum are stronger and smarter than you, it's their right to exploit the weak.}
#{126}{}{I'm going to go look around to see what I can find out.  Bye}
#{127}{}{I wish we were a gang.  At least then we'd have decent weapons to defend our selves with.}
#{128}{}{Defend yourselves from who?}
#{129}{}{Well, you're not foolin' me.  You're all just a bunch of degenerates and I think you're up to no good.}
#{130}{}{You all look a lot like a gang to me.}
#{131}{}{Well, I can't help you with that.}
#{132}{}{What's the story with the Fenced area to the south?}
#{133}{}{Are you the leader of this gang?}
#{134}{}{We need better weapons.  The Gun Runners, a little ways from here, have weapons, but we can't get to them.}
#{135}{}{Why can't you?}
#{136}{}{I'm going to go find out what I can about the situation.}
#{137}{}{The Regulators .  They are the ones that really run Adytum. Not Zimmerman.  They come here and drag our people back to Adytum as slaves. They kill us when we try to fight them off.  Sometimes they just come and kill a couple of us to bring to Zimmerman , so they can say we tried to break into their town, or some other ridiculous story. Those sons of bitches even killed Zimmerman's son!}
#{138}{}{Zimmerman's son?  Why would the they want to kill him?}
#{139}{}{You're saying that you've never done anything against Adytum?}
#{140}{}{There's a Death Claw nest between us and them.  We have never even spoken with any of the Gun Runners.  The Regulators have the fire power to clear out the Death Claws, but they don't for some reason.}
#{141}{}{Where can I find the Gun Runners located?}
#{142}{}{OK.  Goodbye.}
#{143}{}{Josh lived here with me... a... I...I mean us.  He knew the truth behind what was going on.  The Regulators told him if he ever tried to contact his father or return to Adytum that they would kill him.}
#{144}{}{They killed him?  What did he do?}
#{145}{}{I'm going to Adytum to check this out.}
#{146}{}{Late one night he tried to sneak into town to tell his father what was really going on.  I was monitoring the Regulators radio transmissions the night that .. they.. he got ...caught. 【She looks down and shakes her head slowly.】 Here, it's all on this holodisk.}
#{147}{}{Why haven't you given this to Josh's Father?}
#{148}{}{It's not like any of us can even get close to Adytum. We'd be shot dead before we even reached the gates.}
#{149}{}{Why don't I give him the disk?.}
#{150}{}{Why don't you get a large group together and take Adytum by force?}
#{151}{}{You would risk your life to help us?}
#{152}{}{Sure.  Anything to help.}
#{153}{}{I might. I need to go  check things out before I do anything.}
#{154}{}{Thank you.  This really could help us.  Good luck. 【She hands you the holodisk.】}
#{155}{}{See you later.}
#{156}{}{Very well. I hope you make the right decision.}
#{157}{}{Goodbye.}
#{158}{}{The Gun Runners are over to the east  and then north of here.  But be careful - Death Claws are not to be taken lightly.  I've seen a Death Claw tear a man in half with one swipe.}
#{159}{}{I'm going to go see what I can find out.}
#{160}{}{I'm sorry you feel that way.  I think it would be best if you leave.}
#{161}{}{Bye.}
#{162}{}{Can I help you?}
#{163}{}{Are you the leader of this gang?}
#{164}{}{Never mind.}
#{165}{}{A...Wha?}
#{166}{}{Gang?  We're hardly a gang.  But I am the one they all come to for direction.}
#{167}{}{Zimmerman sent me.}
#{168}{}{Well, you look like a gang to me.}
#{169}{}{Goodbye}
#{170}{}{(Looking a little nervous) What? Did he...}
#{171}{}{To put a bullet in your head.}
#{172}{}{To pay you back for killing his son.}
#{173}{}{WHAT!!!  THOSE FUCKING PIECE OF SHIT BASTARDS! I"LL KILL THEM, I"LL SEND THEM ALL TO HELL!!}
#{174}{}{No, you're the one that's going to hell.}
#{175}{}{Uh...who are you going to send to hell?}
#{176}{}{... the Regulators.  They were the ones that killed Josh!  I never would do any thing to hurt Josh.  It's the Regulators who are running Adytum, not Zimmerman.}
#{177}{}{This is a pathetic attempt to talk your way out of this.}
#{178}{}{Why would the Regulators kill Zimmerman's son?}
#{179}{}{Josh lived here with me... a... I...I mean us.  He knew the truth behind what was going on.  The Regulators told him if he ever tried to contact his father or return to Adytum that they would kill him. They laughed at him... they were so sure he couldn't get to his father....}
#{180}{}{They killed him?  What did he do?}
#{181}{}{How's our plan coming along?}
#{182}{}{I'm still trying to get everything worked out.}
#{183}{}{A...Wha?}
#{184}{}{I'm not so sure it would help without the threat of violence to back it up. What we really need are some weapons from the Gun Runners.}
#{185}{}{Well, where are these Gun Runners? Why don't you get some weapons from them?}
#{186}{}{Oh, well, I offered. Goodbye.}
#{187}{}{They're a little to the east of here, but there's a Death Claw nest between us and them.  We have never even spoken with any of the Gun Runners. }
#{188}{}{Okay, give me the holodisk, and I'll go talk to the Gun Runners before I approach Zimmerman.}
#{189}{}{I hope that you can find a way to help us. Goodbye.}
#{190}{}{What's wrong?}
#{191}{}{They killed Zimmerman!}
#{192}{}{A...Wha?}
#{193}{}{....Now we have no choice but to get those weapons from the Gun Runners. Will you help us?}
#{194}{}{Yes.}
#{195}{}{No.}
#{196}{}{Thank you. May the Gods be with you on your journey.}
#{197}{}{Thank you for all your help. We're going to invade Adytum, we could use someone like you on our side.}
#{198}{}{No thanks, I've seen enough action this week.}
#{199}{}{Sure, I'd be glad to take the Regulators down.}
#{200}{}{A...Wha?}
#{201}{}{I'd like to talk to Zimmerman first.}
#{202}{}{Well, thanks again for you help. Goodbye.}
#{203}{}{Great. Let's go.}
#{204}{}{I don't think that's a good idea, but you're welcome to try.}
#{205}{}{You ass! With the Gun Runners gone we will never even have the chance to arm our selves.  Get outta here you're not  welcome here.}
#{206}{}{I'm sorry.}
#{207}{}{Go stuff it.}
#{208}{}{I'm Going to go talk to Zimmerman give him this holodisk disk everything is going to be OK.}
#{209}{}{You know what? I'm going to kill you.}
#{210}{}{A...Wha?}
#{211}{}{Go ahead. It's your funeral.  With out those guns we have nothing to back us up.}
#{212}{}{Go Away!}
#{213}{}{Your not welcome here.}
#{214}{}{Get Lost.}
#{215}{}{Thank you.}
#{216}{}{My people are free.}
#{217}{}{Hello.}
#{218}{}{What happened to you did someone shoot you in the head?}
#{219}{}{Hunh?}
#{220}{}{You see Razor, leader of the Blades.}
#{221}{}{You see a very beautiful woman with a sad look in her eyes.}
#{222}{}{Please go away. I'm very busy.}
#{223}{}{Thank you for helping us with the Regulators. Please feel free to stay as long as you want. You might want to check in with Miles and Smitty, they may be able to help you with your further travels.}
#{224}{}{Hi, can I help you?}
#{225}{}{Who are you?}
#{226}{}{Hootzpah!}
#{227}{}{The name is Razor, I am the leader of the people you see here.   We live here at the whim of the Regulators of Adytum.}
#{228}{}{Regulators? I've taken care of all of them.  Is that a problem?}
#{229}{}{You've killed them all?  That's not a problem at all.  My people can now live free lives with the people of Adytum}
#{230}{}{I can't believe it.  You were able to kill them all.  The Blades and I thank you.}
#{231}{}{I have heard that the Regulators still control Adytum.  Are you not able to kill them all like you had hoped.}
#{232}{}{Don't worry, I'll take care of it.}
#{233}{}{I don't think I am going to be able to do it.}
#{234}{}{We would go with you, but without weapons the Regulators would kill us all.  There might be another possibility 【Razor ponders a moment】  If you could get the Gun Runners to supply us weapons then a number of us could go with you.}
#{235}{}{Sounds good.  I'll go talk to them.}
#{236}{}{I'll try to take the Regulators out myself again.}
#{237}{}{Hello again,  I've heard that you have been playing with the Regulators.  I wanted to thank you for getting rid of them.  My people will be able to live with the people of Adytum in freedom now.}
#{238}{}{I'll just take care of Regulators myself}
#{239}{}{You will?  Well if you need help or have done it come back and talk to me.}


{100}{}{你好，我能为你做什么？}
{101}{}{你是谁}
{102}{}{你是这个帮的老大？}
{103}{}{别介意。}
{104}{}{呃……什么？}
{105}{}{名字剃刀，我是我们中最像领袖像的人。}
{106}{}{那么你是这个帮的老大了？}
{107}{}{对南面被圈起来的地方有什么看法？}
{108}{}{很高兴见到你，我是NAME。}
{109}{}{很高兴见到你，但我得走了。}
{110}{}{帮？我们简直不能称为帮，可这还是我说了算。}
{111}{}{如果不算个帮，那你认为是什么？}
{112}{}{嗯，就我而言你们算个帮。}
{113}{}{再见}
{114}{}{那是内城区。是一群被称为管理者的家伙控制的劳工营，尽管他们告诉大家那是个“镇”。他们从这带走我的人去做苦力直到我的人死掉。之后他们又带走更多。}
{115}{}{你不能进到那里并解救你的人么？}
{116}{}{那要我和你说什么？那些我要吊起来的家伙们。}
{117}{}{我将会尽我所能去收集关于内城区的信息。再见。}
{118}{}{那么，你究竟为了什么来到这个荒废的地方？}
{119}{}{我在找净水芯片。你知道哪有？}
{120}{}{我只是随便转转。}
{121}{}{迅速扫了眼四周，再见。}
{122}{}{我们侥幸得以偷生，内城区将我们集中在这，他们让我们难堪像对待牲口一样奴役我们的家人和朋友，我们甚至没法保护自己。}
{123}{}{你为什么不反抗？}
{124}{}{防御谁？}
{125}{}{噯，内城区的人比你更强壮更聪明，这就是他们向弱者炫耀的。}
{126}{}{我会四处瞧瞧看能发现些什么，再见。}
{127}{}{我宁愿我们是个帮，起码能有像样的武器保护我们自己。}
{128}{}{防御谁？}
{129}{}{哎，别在我面前嬉皮笑脸。你们都不过是群堕落的家伙而且我认为你心怀鬼胎。}
{130}{}{你看起来像是我们这边的。}
{131}{}{嗯，我帮不了你。}
{132}{}{对南面被圈起来的地方有什么看法？}
{133}{}{你是这个帮的老大？}
{134}{}{我们需要更强的武器，军火走私商，从这有条小路、贩卖武器。但我们却得不到。}
{135}{}{为什么？}
{136}{}{我会搞清楚这里大概的形势。}
{137}{}{管理者。他们真正掌控者内城区。而不是齐默曼。他们来到这把我的人拖进内城区当奴隶。我们试着反抗但被残酷镇压。有时他们杀我们两个人运给齐默曼，然后说我们在尝试破坏他们的镇子，或别的什么荒唐的理由。那些狗娘养的甚至杀了齐默曼的儿子！}
{138}{}{齐默曼的儿子？他们为什么要杀他？}
{139}{}{你是说你们没有做任何对内城区不利的事？}
{140}{}{在我们和他们之间有个死亡爪的巢穴。我们无法同军火走私商取任何联系。管理者拥有剿灭死亡爪的火力，但他们没有理由那么做。}
{141}{}{我能在哪里找到军火走私商？}
{142}{}{好的。再见。}
{143}{}{乔希与我在这生活……呃……我……我的意思是我们。他知道到底发生了什么。管理者警告他任何尝试同他父亲接触或是返回内城区的举动都会让他死的很惨。}
{144}{}{他们杀了他？他做了什么？}
{145}{}{我要去内城区探个究竟。}
{146}{}{一天深夜他试着偷偷摸进镇子告诉他父亲真相。那晚我正在管理者无线电发射台值班……他……他被……抓住了。【她向下看并缓缓的摇了摇头】给，所有的东西都在这张磁盘里。}
{147}{}{你干吗不把这个交给乔希的父亲？}
{148}{}{我们根本没法靠近内城区。还没到城门我们就会被射杀。}
{149}{}{我为什么不给他磁盘？。}
{150}{}{你为什么不把大家组织起来反抗内城区？}
{151}{}{你要冒生命危险来帮助我们吗？}
{152}{}{当然。任何我能做的。}
{153}{}{我尽力而为。在做什么之前我需要观察一番。}
{154}{}{谢谢。你真是帮了我们大忙。祝你好运。【她将磁盘交给了你】}
{155}{}{过会见。}
{156}{}{非常好。我希望你做出了正确的决定。}
{157}{}{再见。}
{158}{}{军火商在东边的尽头再向北一些。但要小心－别以为死亡爪好对付。我亲眼看到过死亡爪一下就把人扯成两半。}
{159}{}{我要去看看我能能找到些什么。}
{160}{}{我很抱歉你那么认为。我想你最好离开。}
{161}{}{拜。}
{162}{}{我能帮你什么忙？}
{163}{}{你是这个帮的老大？}
{164}{}{别介意。}
{165}{}{呃……什么？}
{166}{}{帮？我们简直不能称为帮。但这里的人都听我的指挥。}
{167}{}{齐默曼遣我来的。}
{168}{}{。嗯，就我看来你们算个帮派。}
{169}{}{再见}
{170}{}{【看起来有些不安】什么？难道他……}
{171}{}{将子弹射入你的脑袋。}
{172}{}{你杀了他儿子，得血债血尝。}
{173}{}{什么！！！那些该死的杂种！我要宰了他们，我要送他们下地狱！！！}
{174}{}{不，那个该下地狱的人是你。}
{175}{}{啊……你说谁该下地狱？}
{176}{}{管理者。就是他们杀了乔希！我不会做任何伤害乔希的事。内城区是管理者掌控，不是齐默曼……}
{177}{}{这是劝阻你们别做可悲的尝试。}
{178}{}{为什么管理者要杀齐默曼的儿子？}
{179}{}{乔希和我在这生活……啊……我……我的意思是我们。他知道到底发生了什么。管理者警告他任何尝试同他父亲接触或是返回内城区的举动都会让他死的很惨。他们嘲笑他。。。。确信他不敢去找他父亲。。。。}
{180}{}{他们杀了他？他做了什么？}
{181}{}{我们的计划会成功么？}
{182}{}{我仍在尽力尝试去制定一个计划。}
{183}{}{呃……什么？}
{184}{}{我不确信不使用武力威胁能否解决这事。我们真的很需要从军火走私商那里得到武器。}
{185}{}{嗯，这些军火走私商在哪？你为什么不从他们那里搞些武器？}
{186}{}{噢，嗯，我已经给了。再见。}
{187}{}{ 他们就在东边。但在我们之间有个死亡爪巢穴。我们根本没办法同他们取得联系。}
{188}{}{好啊，磁盘拿来，我会在接近齐默曼前同军火走私商谈谈。}
{189}{}{我希望你能找到帮助我们的办法。再见。}
{190}{}{怎么了？}
{191}{}{他们杀了齐默曼！}
{192}{}{呃……什么？}
{193}{}{……现在我们别无他法只有从军火走私商那得到那些武器。你能帮我们吗？}
{194}{}{是的。}
{195}{}{不。}
{196}{}{赞美你。愿上帝与你同在。}
{197}{}{感谢你的鼎力相助。我们将要攻打内城区，我们需要像你这样的战士与我们并肩作战。}
{198}{}{不用了，这个星期我已经目睹了足够多的行动。}
{199}{}{当然，见证管理者的灭亡令我兴奋。}
{200}{}{呃……什么？}
{201}{}{我得先和齐默曼谈谈。}
{202}{}{嗯，再次感谢你的帮助。再见。}
{203}{}{好极了。出发。}
{204}{}{我认为那不是个好主意，但允许你去试试。}
{205}{}{你个蠢驴！没了军火走私商我们甚至连武装自己的机会都没有。从这滚出去别再让我见到你。}
{206}{}{我很抱歉。}
{207}{}{把它填满。}
{208}{}{我会和齐默曼谈谈并给他这个磁盘所有事情都将得到解决。}
{209}{}{你知道吗？我要杀了你。}
{210}{}{呃……什么？}
{211}{}{继续说啊，这是你的葬礼。除了那些枪我们再没有任何支持了。}
{212}{}{走开！}
{213}{}{这里不欢迎你。}
{214}{}{滚开。}
{215}{}{感谢你。}
{216}{}{我的人自由啦。}
{217}{}{你好。}
{218}{}{对着你的脑袋开一枪会怎么样？}
{219}{}{嗯？}
{220}{}{你看到剃刀，利刃帮的老大。}
{221}{}{你看到一个很漂亮的女人，尽管她的双眼透着哀伤。}
{222}{}{拜托你走开。我很忙。}
{223}{}{谢谢你帮我们收拾管理者。你愿意在这呆多久就呆多久。你可能需要麦尔斯和施密蒂加入，他们也许能在你未来的旅行中帮助你。}
{224}{}{嗨，要帮忙吗？}
{225}{}{你是谁？}
{226}{}{呼兹拔！}
{227}{}{名字是剃刀，我领导你看到的这些人。我们生活在内城区管理者的统治下。}
{228}{}{管理者？我已经把他们收拾掉了。那还是个问题吗？}
{229}{}{你是说全部？那不再是个问题。我的人现在能够在内城区自由的生活了。}
{230}{}{难以置信。你竟然能够把他们都干掉。利刃帮和我对你感激不尽。}
{231}{}{据我所知管理者还在统治内城区。你没能够如你已经期望的那样把他们全干掉。}
{232}{}{别担心，一切尽在掌握。}
{233}{}{我觉得我没有能力去完成。}
{234}{}{我们想和你一起去，但是没有武器我们只会被管理者屠杀。再一种可能【剃刀考虑了片刻】如果你能让军火走私商为我们提供武器，那么我们中的许多人会跟随你。}
{235}{}{听起来不错。我会同他们谈谈的。}
{236}{}{我将再次尝试干掉管理者。}
{237}{}{又见面了，听说你和管理者干了一仗。感谢你消灭了他们。我的人民可以平静的和内城区的人一起生活了。}
{238}{}{我将亲手解决管理者。}
{239}{}{你愿意？好吧，如果你需要帮助或已经完成那就回来跟我说。}

