#{100}{}{You see a man in dusty leather armor with a trenchcoat and gas mask.}
#{101}{}{You see Tycho.}
#{102}{}{Another new face. Travelers here are a dime a dozen. But you have the
# look of someone different. Care to join me for a drink?}
#{103}{}{Sorry, I'm rather pressed for time.}
#{104}{}{Sure.}
#{105}{}{Duh-wah?}
#{106}{}{Delightful. I hope you don't mind your drink well-watered - they treat
# beer here like it's a potted plant.}
#{107}{}{So, what's your story?}
#{108}{}{Yeah, a drink of water. Never mind.}
#{109}{}{I could ask the same of you. In the interest of amity, I suppose I'll
# tell first. I'm called Tycho. Came from out east, what used to be called Nevada.}
#{110}{}{That's a pretty long trip.}
#{111}{}{How did you survive all the dangers?}
#{112}{}{Yeah, it was. Decided to take it easy for a while. This place shows some
# promise, just as soon as someone cleans up some of the scum.}
#{113}{}{Why don't you?}
#{114}{}{Yeah, I noticed. What do you know about those jerks?}
#{115}{}{Had some pretty good training, and some good weapons, too. My grandfather
# was a Ranger way back when, and he taught my father everything he knew. Dad
# passed it on to me. So I know enough not to drink glowing water, so to speak.}
#{116}{}{Interesting. Thanks for the drink.}
#{117}{}{Really? Survival's tough these days. You must be pretty knowledgeable.}
#{118}{}{Not my place. I'd rather not cross Killian, after all. He'll clean up
# this town when he gets around to it. A good man, mark my words. But watch out
# for that fellow Gizmo. Reminds me of another fat freak my father told me about
# back in Las Vegas.}
#{119}{}{Thanks for the tip, and the drink.}
#{120}{}{There's two grades of scum here. One of 'em's the Skulz, a gang that hangs
# out in back of Marcelles' crash house. They're just grade-B twerps. But the other
# ones answer to a fat freak whose name you can probably guess. Runs the casino.
# Those guys are organized and dangerous.}
#{121}{}{I see. Thanks for the info.}
#{122}{}{Yeah, well, my family taught me everything there is to know about survival.
# Don't drink water that's totally clear and free of insects and moss, for instance.
# Only poisonous or radioactive water would be that clean in the wilderness.
# Lots of other little things to look out for, too.}
#{123}{}{Like what?}
#{124}{}{Well, if you've got some time, I could go over some pointers.}
#{125}{}{Sure, that would be great.}
#{126}{}{Sorry, I'm kind of pressed for time.}
#{127}{}{Whoa, not so fast. We never finished introductions, remember? What's your
# name, stranger?}
#{128}{}{I'm }
#{129}{}{.}
#{130}{}{None of your business, you nut.}
#{131}{}{Good to meet you. Step carefully, friend.}
#{132}{}{Now, now, no need to get impolite. But with that attitude you'd best be
# on your way.}
#{133}{}{Bite me.}
#{134}{}{Whatever. See ya.}
#{135}{}{What do you want?}
#{136}{}{Sorry to disturb your private time. Go wank somewhere else.}
#{137}{}{I need information about the gangers here.}
#{138}{}{I need information about the town.}
#{139}{}{Hello again. How can I help you?}
#{140}{}{Killian's asked me to clean up this town, and I'd like your help.}
#{141}{}{Well, this is the Skum Pitt, a wretched hive of villainy and all that. Just
# west of here is Gizmo's, a big casino. Word is the games are rigged. A little south
# of here is the Crash House, run by Marcelles, where you can get a night's sleep
# for way too many caps. Past that is Killian's. Killian runs a general store, and
# he also enforces the law in this town - a good man. Then south of there you have
# Doc Morbid, whose operation is a little funny, if you take my meaning.}
#{142}{}{I hope that my little instruction course helped a bit.}
#{143}{}{}
#{144}{}{Word out is that you've been having some contacts with Gizmo. I'd step
# carefully around that barrel of lard if I were you.}
#{145}{}{My business is none of yours.}
#{146}{}{Yeah, I work for Gizmo now. What's it to you?}
#{147}{}{Fair enough. But watch your back. Gizmo isn't known for his consideration
# for his employees.}
#{148}{}{Suffice to say that your employer has caused more than enough misery and
# strife in this town. Don't expect much help from anyone, least of all Gizmo.
# Too bad. You might've been able to change this town for the better.}
#{149}{}{What can I do for you?}
#{150}{}{Any recommendations?}
#{151}{}{Thanks for your help. I think it's time to part ways.}
#{152}{}{Yeah, I'd stay the hell away from whatever made that. Seriously, I've never
# seen anything like that. I think our best option is to move on, fast.}
#{153}{}{Very well. I must say that it has been an honor and a pleasure.}
#{154}{}{Watch out for radioactive hot spots. This place obviously sustained a
# direct nuclear strike, and secondary cascade radiation may be bad. I'd
# recommend avoiding this place completely if we can.}
#{155}{}{Note the lack of any animal life for quite a distance. And the piles of
# bones. Whatever lives here is a real beast. Keep your weapon handy.}
#{156}{}{A military place like this must have a central command room somewhere.}
#{157}{}{I bet we could get through those force-field generators with a little
# hot-wiring, or if we could find the force field control computer.}
#{158}{}{There are many strange tales about Necropolis, the city of the dead. Stay
# alert, because it could get dangerous really fast.}
#{159}{}{I need to change formation.}
#{160}{}{What distance do you want me at?}
#{161}{}{Stay close.}
#{162}{}{Keep a moderate distance.}
#{163}{}{Move out to longer range.}
#{164}{}{What sorts of weapon skills have you learned?}
#{165}{}{Pretty good ranger training: I can use a spear, of course, in a pinch;
# I'm also skilled with small pistols and rifles.}
#{166}{}{Uh, never mind.}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

#{167}{}{Yeah, if you like your lizard well-done.}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

#{168}{}{Well it's about time. Lead on, my friend, and let's do some street sweeping.
# I'd recommend knocking over Gizmo, if I may.}
#{169}{}{Well it's about time. Lead on, my friend, and let's do some street sweeping.
# I'd recommend knocking over Gizmo, if I may.}

#{170}{}{Yes?}
#{171}{}{I think maybe we should stick together, after all.}
#{172}{}{Nothing. Never mind.}
#{173}{}{You gain 300 experience points for recruiting Tycho, the desert ranger.}

#
# Tycho tell-me-abouts
#

# {1000}{}{Junktown}
# {1001}{}{Rangers}
#{1002}{}{Chip}
#{1003}{}{War}
#{1004}{}{Wastes}
#{1005}{}{Followers}
#{1006}{}{Cathedral}
#{1007}{}{Garl}
#{1008}{}{Master}
#{1009}{}{Unity}
#{1010}{}{Set}
#{1011}{}{Watershed}
#{1012}{}{Necropolis}
#{1013}{}{Hall}
#{1014}{}{Library}
#{1015}{}{Overseer}
#{1016}{}{Medic}
#{1017}{}{Healing}
#{1018}{}{Vault}
#{1019}{}{Vault-13}
#{1020}{}{Vault13}
#{1021}{}{Killian}
#{1022}{}{Gizmo}
#{1023}{}{Boneyard}
#{1024}{}{Shady}
#{1025}{}{Sands}
#{1026}{}{Hub}
#{1027}{}{Casino}
#{1028}{}{Store}
#{1029}{}{Deathclaw}
#{1030}{}{Exodus}
#{1031}{}{Initiates}
#{1032}{}{Paladins}
#{1033}{}{Scribes}
#{1034}{}{Children}
#{1036}{}{Brotherhood}
#{1037}{}{Vats}
#{1038}{}{Military}
#{1039}{}{Base}
#{1041}{}{Apocalypse}
#{1042}{}{Mutants}
#{1043}{}{Morpheus}
#{1044}{}{Khans}
#{1045}{}{Tandi}
#{1046}{}{Alya}
#{1047}{}{Diana}
#{1048}{}{Gwen}
#{1049}{}{Petrox}
#{1050}{}{Tolya}
#{1051}{}{Booze}
#{1052}{}{Drugs}
#{1053}{}{Seth}
#{1054}{}{Aradesh}
#{1055}{}{Razlo}
#{1056}{}{Zimmerman}
#{1057}{}{Regulators}
#{1058}{}{Scavs}
#{1059}{}{Blades}
#{1060}{}{Nicole}
#{1061}{}{Lieutenant}
#{1062}{}{Psychics}
#{1063}{}{Experiments}
#{1064}{}{Police}
#{1065}{}{Merchants}

#{1100}{}{Well, Junktown's not really home, but it's an interesting city. It has
# potential, although I don't know that building out of the refuse of the past is #the
# best way to construct the future.}
#{1101}{}{We Rangers hail from back east, what used to be called Nevada. Our
# heritage stretches back to the days of the Texas Rangers. We learn survival and
# combat skills in order to go out into the world and have a chance of surviving and
# making things better.}
#{1102}{}{I haven't seen a relic of old technology like a water chip for a long
# time. Personally, you're better off depending on yourself, not on some piece of
# tech that you can't fix.}
#{1103}{}{The War was a testament to human greed and insanity. Let's hope that we
# have learned enough to never repeat such folly.}
#{1104}{}{The wastes are hostile and dangerous, even to the wary traveler.
# Radiation and strange creatures will take their toll. Tread with caution, and
# remember that everything you see and hear is a clue.}
#{1105}{}{I'm sorry, I can't help you there.}
#{1106}{}{I'm sorry, I can't help you there.}
#{1107}{}{I'm sorry, I can't help you there.}
#{1108}{}{I'm sorry, I can't help you there.}
#{1109}{}{I'm sorry, I can't help you there.}
#{1110}{}{I'm sorry, I can't help you there.}
#{1111}{}{I'm sorry, I can't help you there.}
#{1112}{}{The City of Death is well named. It lies in what used to be the little
# town of Bakersfield. Now, though, it's home to ghouls and worse.}
#{1113}{}{I'm sorry, I can't help you there.}
#{1114}{}{I'm sorry, I can't help you there.}
#{1115}{}{I'm sorry, I can't help you there.}
#{1116}{}{I'm sorry, I can't help you there.}
#{1117}{}{I'm sorry, I can't help you there.}
#{1118}{}{I've heard of the great underground Vaults. I don't know much about them,
# though.}
#{1119}{}{I've heard of the great underground Vaults. I don't know much about them,
# though.}
#{1120}{}{I've heard of the great underground Vaults. I don't know much about them,
# though.}
#{1121}{}{Killian's a good man doing a difficult job.}
#{1122}{}{Gizmo is . . . well, he strikes me as a crook. He'll get his in the end.}
#{1123}{}{The Boneyard? I'm told it's a place of gangs and hard life, near the
# coast.}
#{1124}{}{I'm sorry, I can't help you there.}
#{1125}{}{I'm sorry, I can't help you there.}
#{1126}{}{The Hub's a giant merchantile community, just a short ways south of
# Junktown.}
#{1127}{}{Gizmo's casino is probably one of the last places I'd want to go,
# unless I were going to step on Gizmo's neck. Not that I could get a foot past
# all the blubber.}
#{1128}{}{Killian has a decent general store in Junktown.}
#{1129}{}{Heard some tales about something faster, bigger, and meaner than
# any living creature has a right to be. Not too many, though, which means that
# it doesn't leave many survivors. Big claws, ferocious disposition.}
#{1130}{}{I'm sorry, I can't help you there.}
#{1131}{}{I'm sorry, I can't help you there.}
#{1132}{}{I'm sorry, I can't help you there.}
#{1133}{}{I'm sorry, I can't help you there.}
#{1134}{}{I'm sorry, I can't help you there.}
#{1136}{}{I'm sorry, I can't help you there.}
#{1137}{}{I'm sorry, I can't help you there.}
#{1138}{}{The military had several secret bases scattered about, I know. I just
# don't know where.}
#{1139}{}{The military had several secret bases scattered about, I know. I just
# don't know where.}
#{1141}{}{Nuclear armageddon was the result of pride and foolishness. Now, we're
# paying the price.}
#{1142}{}{Certainly there are some strange things out there. I've seen mutated
# scorpions and cows, and I've heard that Necropolis is home to ghouls, who seem
# human but are far different.}
#{1143}{}{I'm sorry, I can't help you there.}
#{1144}{}{I'm sorry, I can't help you there.}
#{1145}{}{I'm sorry, I can't help you there.}
#{1146}{}{I'm sorry, I can't help you there.}
#{1147}{}{I'm sorry, I can't help you there.}
#{1148}{}{I'm sorry, I can't help you there.}
#{1149}{}{I'm sorry, I can't help you there.}
#{1150}{}{I'm sorry, I can't help you there.}
#{1151}{}{I prefer a good strong stout, or perhaps a Nuka-Cola.}
#{1152}{}{I'd stay away from drugs if I were you. Sure, they can give you a boost,
# but you always wind up paying for it in the end.}
#{1153}{}{I'm sorry, I can't help you there.}
#{1154}{}{I'm sorry, I can't help you there.}
#{1155}{}{I'm sorry, I can't help you there.}
#{1156}{}{I'm sorry, I can't help you there.}
#{1157}{}{I'm sorry, I can't help you there.}
#{1158}{}{I'm sorry, I can't help you there.}
#{1159}{}{I'm sorry, I can't help you there.}
#{1160}{}{I'm sorry, I can't help you there.}
#{1161}{}{I'm sorry, I can't help you there.}
#{1162}{}{You mean telepathetics? Heh . . . seriously, I don't buy it.}
#{1163}{}{I'm sorry, I can't help you there.}
#{1164}{}{I'm sorry, I can't help you there.}
#{1165}{}{Some merchants from the Hub visit Junktown and other cities on
# a regular basis.}

{100}{}{你看到一个穿着皮装甲的男人，还穿着一件破外套，戴着防毒面具。}
{101}{}{你看到提可。}
{102}{}{又是新面孔。来这的旅行者很多。可你看起来不大一样。想跟我喝一杯吗？}
{103}{}{抱歉，我赶时间。}
{104}{}{当然。}
{105}{}{哈啥？}
{106}{}{太高兴了。希望你不介意喝井水，他们象浇花一样往啤酒里兑水。}
{107}{}{那么，说说关于你的事。}
{108}{}{好，白水饮料，没关系。}
{109}{}{我也要问你一样的问题。为表示友好，我想我该先说。我叫提可，从东边一个曾被叫做内华达的地方来。}
{110}{}{那可真是很长的一段路。}
{111}{}{你是怎么逃脱那些危险生存下来的？}
{112}{}{是的，的确。当时决定放松一下。这个地方不错，只要有人出来把那群人渣清理掉。}
{113}{}{为什么你不？}
{114}{}{是的，我注意到了，关于那些混球你知道些什么？}
{115}{}{我经历过一些训练，也有好武器。我祖父是个流浪的人，他把他会的一切都教给我爸爸了，我爸爸又教给我。所以我有足够的生存常识。}
{116}{}{很有意思。谢谢你的饮料。}
{117}{}{真的，如今能生存下来的人可是很强的。你肯定很有才。}
{118}{}{这不是我的地方。不管怎样，我都不想惹基利安。时机一到他会清理这地方的。记住，那是个好人。不过要小心吉斯莫那家伙。让我想起我父亲跟我讲过以前在拉斯维加斯也有这么一个死胖子。}
{119}{}{谢谢你的提醒，还有饮料。}
{120}{}{这里有两伙流氓。一伙是骷髅党，在玛塞尔的破屋后面出没的家伙。不过他们只是一般货色。另一伙是响应一个死胖子的，你猜的到那是谁。他们经营赌场。是很有组织而且很危险的家伙。}
{121}{}{知道了，谢谢。}
{122}{}{啊，是的，我的家族教了我一切要用到的生存之道。比如不要喝从昆虫和苔藓那里得到的，看起来完全洁净的水，在野外只有有毒或者受过辐射的水才会那么干净。还有很多这样的细节要小心。}
{123}{}{譬如？}
{124}{}{如果你有时间的话，我能回想起很多。}
{125}{}{当然好了。}
{126}{}{抱歉，我有点赶时间。}
{127}{}{喂，别着急啊。咱们还没互相介绍完呢，记得吗？你叫什么，陌生人。}
{128}{}{我是}
{129}{}{。}
{130}{}{不关你事，白痴。}
{131}{}{很高兴见到你。小心行走，朋友。}
{132}{}{现在，不用以礼相待了。但如果你是这种态度的话还是赶紧走的好。}
{133}{}{咬我呀。}
{134}{}{随便了。再见。}
{135}{}{你想怎样？}
{136}{}{抱歉占用了你的私人时间。滚别处去。}
{137}{}{我需要这里帮派的信息。}
{138}{}{我需要这个镇的信息。}
{139}{}{嘿，又是你。能帮你吗？}
{140}{}{基利安要我清理这个地方，我想得到你的帮忙。}
{141}{}{这是萨姆·匹特，邪恶家伙的据点。西面是吉斯莫的地方，一个大赌场。传闻他们那里都是作弊的。这里南边一点是棚屋区，由玛塞尔掌管，你晚上可以去那里休息，如果你嫌钱多的话。再过去一点是基利安的地方。他有一个商店，还维持这里的秩序，是个好人。还有在南部的莫彼得大夫，他做的手术和那地方都有点奇怪，懂我的意思了吧。}
{142}{}{希望我的介绍能有点帮助。}
{143}{}{}
{144}{}{传闻你跟吉斯莫有接触。如果我是你，在那桶肥油身边做事的话，我会很小心的。}
{145}{}{我的事不要你管。}
{146}{}{对，我现在为吉斯莫做事了，怎样？}
{147}{}{好吧。不过小心点。吉斯莫可不是很照顾手下的人。}
{148}{}{不客气的说，你和你的手下已经给这个镇带来太多冲突和灾难了。除了吉斯莫别指望任何人会帮助你。很不幸。本来你可以为这个镇做些好事的。}
{149}{}{我能帮你点什么？}
{150}{}{有什么好推荐的吗？}
{151}{}{谢谢你的帮忙，我想现在该分开了。}
{152}{}{可不是，我肯定要躲的远远的。说真的，我从来没见过那种东西。对我们来说最好的选择就是继续跑，拼命跑。}
{153}{}{很好。我必须说这是一种荣幸。}
{154}{}{小心那些辐射点。这个地方明显遭到过直接的核打击，遗留辐射仍然会是很强烈的。如果可能的话，我建议彻底远离这个地方。}
{155}{}{这附近都没有动物生存。这还有成堆的骨骸。这住的肯定是个不好对付的野兽。大家拿好武器。}
{156}{}{这样一个军事区域一定有个中心指挥室。}
{157}{}{我们应该可以通过那些力场，如果在那些电线上动点手脚，或者我们要找到控制力场的电脑。}
{158}{}{关于大墓地有很多奇怪的传说，是个死亡之地。保持警惕，危险会在一瞬间逼近。}
{159}{}{我需要变换队型。}
{160}{}{你要我离多远？}
{161}{}{跟紧我。}
{162}{}{保持适中距离。}
{163}{}{离我远些。}
{164}{}{你都会用什么武器？}
{165}{}{我受过很好的流浪者训练，我可以用矛，当然是在没有其他武器可用的时候，手枪和来福枪是我最拿手的。}
{166}{}{啊，没什么。}

#
# TRANSLATION NOTE: The following line is not spoken to the player, but instead
# is spoken to Katja, a female thief who may be a member of the player's group.
# (See Katja.msg for particulars about Katja).
#

{167}{}{是哦，你要你的蜥蜴十成熟吗？}

#
# TRANSLATION NOTE: The following two lines are identical in English, but they
# differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{168}{}{是时候了。带路吧伙计，咱们来“清理”一下这地盘，如果可以的话，我建议清理掉吉斯莫。}
{169}{}{是时候了。带路吧伙计，咱们来“清理”一下这地盘，如果可以的话，我建议清理掉吉斯莫。}

{170}{}{恩？}
{171}{}{我觉我们应该一起行动。}
{172}{}{没什么。}
{173}{}{因为说服提可加入，你得到３００点经验。}

#
# Tycho tell-me-abouts
#

{1000}{}{Junktown}
{1001}{}{Rangers}
{1002}{}{Chip}
{1003}{}{War}
{1004}{}{Wastes}
{1005}{}{Followers}
{1006}{}{Cathedral}
{1007}{}{Garl}
{1008}{}{Master}
{1009}{}{Unity}
{1010}{}{Set}
{1011}{}{Watershed}
{1012}{}{Necropolis}
{1013}{}{Hall}
{1014}{}{Library}
{1015}{}{Overseer}
{1016}{}{Medic}
{1017}{}{Healing}
{1018}{}{Vault}
{1019}{}{Vault-13}
{1020}{}{Vault13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Boneyard}
{1024}{}{Shady}
{1025}{}{Sands}
{1026}{}{Hub}
{1027}{}{Casino}
{1028}{}{Store}
{1029}{}{Deathclaw}
{1030}{}{Exodus}
{1031}{}{Initiates}
{1032}{}{Paladins}
{1033}{}{Scribes}
{1034}{}{Children}
{1036}{}{Brotherhood}
{1037}{}{Vats}
{1038}{}{Military}
{1039}{}{Base}
{1041}{}{Apocalypse}
{1042}{}{Mutants}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Booze}
{1052}{}{Drugs}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulators}
{1058}{}{Scavs}
{1059}{}{Blades}
{1060}{}{Nicole}
{1061}{}{Lieutenant}
{1062}{}{Psychics}
{1063}{}{Experiments}
{1064}{}{Police}
{1065}{}{Merchants}

{1100}{}{其实，迦克镇不是什么家园，不过是个有趣的地方。很有发展潜力，虽然我不确定否定过去的建设是构建未来的最好方法。}
{1101}{}{我们这些流浪的人从东面来，一个曾经被称作内华达的地方。我们是德克卅斯流浪者的后裔。我们学习生存和战斗技巧用来走到外面的世界去寻找改善生存的机会。}
{1102}{}{我很久没见过这样的象净水芯片这样的古代科技产物了。我个人认为你得靠自己生存，而不是什么你根本修不好的科技产品。}
{1103}{}{战争就是人类贪婪和疯狂的验证。希望我们已经吸取了足够的教训，再也不会让这样的蠢事发生了。}
{1104}{}{充满敌意的荒野是危险的，对谨慎的旅行者也是一样。变异生物不会让人轻易通过。小心对待，记住，你看到的听到的都是生存的线索。}
{1105}{}{对不起，这我可帮不上忙。}
{1106}{}{对不起，这我可帮不上忙。}
{1107}{}{对不起，这我可帮不上忙。}
{1108}{}{对不起，这我可帮不上忙。}
{1109}{}{对不起，这我可帮不上忙。}
{1110}{}{对不起，这我可帮不上忙。}
{1111}{}{对不起，这我可帮不上忙。}
{1112}{}{这个死亡之地可是恰如其名。它位于一个曾经是贝可斯菲德的小镇。现在是僵尸之类的家。}
{1113}{}{对不起，这我可帮不上忙。}
{1114}{}{对不起，这我可帮不上忙。}
{1115}{}{对不起，这我可帮不上忙。}
{1116}{}{对不起，这我可帮不上忙。}
{1117}{}{对不起，这我可帮不上忙。}
{1118}{}{我听说过那些地下避难所。可我知道的不多。}
{1119}{}{我听说过那些地下避难所。可我知道的不多。}
{1120}{}{我听说过那些地下避难所。可我知道的不多。}
{1121}{}{基利安是个好人，他的工作可不轻松。}
{1122}{}{吉斯莫……事实上，他把我当贼打。他会得到报应的。}
{1123}{}{晒骨场？靠近海边的地方。听说那个地方帮派聚集，生活艰辛。}
{1124}{}{对不起，这我可帮不上忙。}
{1125}{}{对不起，这我可帮不上忙。}
{1126}{}{是哈勃的大商会，在迦克镇南边不远。}
{1127}{}{吉斯莫的赌场是我最不想去的地方，除非是踩着那个死胖子的尸体进去。那堆脂肪……}
{1128}{}{基利安在迦克镇有间体面的店铺。}
{1129}{}{的确听说过比任何其他生物都敏捷，强壮，凶残的东西。不过这样的传闻不太多，也就是说它们很少留下生还者。爪子巨大，性情残暴。}
{1130}{}{对不起，这我可帮不上忙。}
{1131}{}{对不起，这我可帮不上忙。}
{1132}{}{对不起，这我可帮不上忙。}
{1133}{}{对不起，这我可帮不上忙。}
{1134}{}{对不起，这我可帮不上忙。}
{1136}{}{对不起，这我可帮不上忙。}
{1137}{}{对不起，这我可帮不上忙。.}
{1138}{}{我知道军方的确曾有一些秘密基地分散在各地。可我不知道在哪里。}
{1139}{}{我知道军方的确曾有一些秘密基地分散在各地。可我不知道在哪里。}
{1141}{}{核战是盲目骄傲愚蠢的结果。现在我们不正在偿还它的代价吗？}
{1142}{}{的确外面有些奇怪的事情。我见过变异的蝎子和牛，还听说大墓地聚集了很多僵尸，看起来有点象人类但其实大不相同的东西。}
{1143}{}{对不起，这我可帮不上忙。}
{1144}{}{对不起，这我可帮不上忙。}
{1145}{}{对不起，这我可帮不上忙。}
{1146}{}{对不起，这我可帮不上忙。}
{1147}{}{对不起，这我可帮不上忙。}
{1148}{}{对不起，这我可帮不上忙。}
{1149}{}{对不起，这我可帮不上忙。}
{1150}{}{对不起，这我可帮不上忙。}
{1151}{}{我更喜欢烈一点的啤酒，核子可乐什么的。}
{1152}{}{如果我是你，我就不会碰毒品。那些东西的确会让你爽一下，不过最终你会毁了自己的，这就是代价。}
{1153}{}{对不起，这我可帮不上忙。}
{1154}{}{对不起，这我可帮不上忙。}
{1155}{}{对不起，这我可帮不上忙。}
{1156}{}{对不起，这我可帮不上忙。}
{1157}{}{对不起，这我可帮不上忙。}
{1158}{}{对不起，这我可帮不上忙。}
{1159}{}{对不起，这我可帮不上忙。}
{1160}{}{对不起，这我可帮不上忙。}
{1161}{}{对不起，这我可帮不上忙。}
{1162}{}{你是说电子设备？哦……说真的，我不买那些东西的。}
{1163}{}{对不起，这我可帮不上忙。}
{1164}{}{对不起，这我可帮不上忙。}
{1165}{}{一些哈勃城的商人会定期去迦克镇和其他的城镇。}

#{1999}{}{I feel more powerful now!}
{1999}{}{我感觉自己更强啦！}

#{2000}{}{Let's discuss our combat tactics.}
{2000}{}{我们来谈谈战斗策略。}

#{2001}{}{Yes?}
{2001}{}{如何？}

#{2010}{}{Draw your best weapon.}
{2010}{}{装备最好的武器。}

#{2011}{}{Change your armour.} 
{2011}{}{更换你的装甲。}                       # changed by WG  

#{2012}{}{Prefer ranged combat against close.}
{2012}{}{尽量用远程攻击。}

#{2013}{}{Prefer close combat against ranged.}
{2013}{}{尽量用肉搏攻击。}

#{2014}{}{Choose distance on your own.}
{2014}{}{自行决定和我的距离。}

#{2015}{}{That's all for now.}
{2015}{}{就这样了。}

#{2100}{}{All right.}
{2100}{}{好的。}