##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
##      (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{rakieta}
{200}{}{kula plazmy}
{300}{}{eksplozja}
{400}{}{krew}
{500}{}{niedostêpne pole}
{501}{}{}
{600}{}{Knife}
{700}{}{Spear}
{800}{}{impuls elektromagnetyczny (EMP)}
{900}{}{promieñ lasera}
{1000}{}{strumieñ plazmy}
{1100}{}{eksplozja}
{1200}{}{blokada przesuwu ekranu}
{1300}{}{wy³adowanie elektryczne}
{1400}{}{eksplozja}
{1500}{}{eksplozja}
{1600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2400}{}{flara}
{2500}{}{granat}
{2600}{}{kamieñ}
{2700}{}{eksplozja}
{2800}{}{eksplozja}
{2900}{}{eksplozja}
{3000}{}{koktajl Mo³otowa}
{3100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
