#
# Item.c messages
#
{1}{}{Zyskujesz %d %s.}
{2}{}{Tracisz %d %s.}
{3}{}{Czujesz siê lepiej.}
{4}{}{Przedawkowanie skutkuje powa¿nym atakiem serca.}
{5}{}{%s to ju¿ tylko surowiec wtórny.}
{6}{}{%s - status aktywny.}
{7}{}{%s - status nieaktywny.}
{8}{}{Przesuwasz licznik Geigera nad twoim cia³em. Wynik pomiaru w remach to %d.}
{9}{}{Tego przedmiotu mo¿na u¿ywaæ wy³¹cznie z paska interfejsu.}
{10}{}{Nic siê nie dzieje.}
