#
#
#
#
#
{0}{}{Opcje Gry}
{1}{}{Ustawienia Ekranu}
{3}{}{Opcje}


{50}{}{Ustawienia Ekranu}
{51}{}{Niestandardowe}
{52}{}{Szerokoœæ}
{53}{}{Wysokoœæ}
{54}{}{Gotowe}
{55}{}{Anuluj}
{56}{}{Aby zastosowaæ, uruchom ponownie.}
{57}{}{Czy chcesz restartowaæ Fallouta teraz?}


{100}{}{Hi-Res}
{101}{}{ROZDZIELCZOŒÆ}
{102}{}{Kolory}
{103}{}{8 Bity}
{104}{}{16 Bity}
{105}{}{32 Bity}
{106}{}{Zmieñ grafikê paneli}


{200}{}{Sfall}
{201}{}{SKALUJ:}
{202}{}{TRYB DX-9}
{203}{}{Wy³.}
{204}{}{Pe³ny Ekran}
{205}{}{Okno}
{206}{}{Przyœp. sprzêt.}
