##
## NOTE: Each line in the description box holds roughly 40 characters in English. Meaning to add a blank line, add 40 spaces and then reduce as needed.
##       This will differ based on words used (since it wraps based on the word length)  --Sduibek, Fallout Fixt
##
#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Ускоренный метаболизм}
{101}{}{Хулиган}
{102}{}{Миниатюрный}
{103}{}{Однорукий}
{104}{}{Точность}
{105}{}{Камикадзе}
{106}{}{Тяжелая рука}
{107}{}{Стрельба навскидку}
{108}{}{Кровавая баня}
{109}{}{Порченый}
{110}{}{Добрая душа}
{111}{}{Drug-Reliant}
{112}{}{Drug-Resistant}
{113}{}{Ночн. существо}
{114}{}{Тренированный}
{115}{}{Одаренный}
#
#   TRAIT DESCRIPTIONS
#
##
##
##
##
##
##
{200}{}{Ваш метаболизм в два раза быстрее обычного. Это означает, что вы более подвержены действию ядов и радиации, но зато процессы восстановления проходят быстрее.}
{201}{}{Пожертвовать скоростью ради мощности. Вы бьете редко, но уж если бьете, будьте уверены - это заметят! Общее число ваших очков действия уменьшено, но показатель силы увеличен.}
{202}{}{Вы несколько меньше других обитателей Убежища, зато намного быстрее. Много вы не унесете, зато проворством обойдете всех.}
{203}{}{Одной рукой вы управляете значительно лучше, чем другой. Одноручное оружие - ваш конек, но вот двуручное вызывает проблемы.}
{204}{}{Ваши удары всегда очень точные. Вы наносите не такой уж большой урон, но имеете больше шансов на критический удар.}
{205}{}{Вы действуете в бою гораздо быстрее. У вас нет добавок к классу брони за ловкость (играет роль только то, что надето на вас), но повышаются шансы опередить противника.}
{206}{}{Главное - хорошо размахнуться, а целиться - дело десятое. Ваши удары жестоки, но не всегда точны. Критический удар для вас редкость, но вы всегда наносите дополнительный урон.}
{207}{}{У вас нет времени, чтобы прицелиться, потому что вы атакуете быстрее, чем обычные люди. Использование оружия стоит вам на 1 ОД меньше.}
{208}{}{Странная ирония судьбы: люди вокруг вас постоянно умирают жестокой смертью. Из всех способов умереть вы всегда выбираете для вашей жертвы самый кошмарный.}
{209}{}{Хорошая новость: у всех вокруг вас повышаются шансы критических промахов во время боя. Плохая новость: у вас тоже!}
{210}{}{В детстве и юности вы отдавали предпочтение мирным занятиям. В результате ваши боевые навыки на низком уровне, зато навыки первой помощи, доктора, красноречия и бартера гораздо лучше.}
{211}{}{You are more easily addicted to drugs. Your chance to become addicted to substances you use is twice normal, but you recover faster from their ill effects.}
{212}{}{Химикаты действуют на вас в два раза меньше по времени, но ваши шансы пристраститься к ним также в два раза ниже, чем у остальных.}
{213}{}{Как ночное существо, вы больше активны, когда солнце закатилось. Ваши интеллект и восприятие улучшены ночью, но уменьшаются днем.}
{214}{}{Вы отточили свои навыки. Вы начинаете игру с более высокими навыками, но вам достанется меньше способностей. Вы будете получать способность каждые четыре уровня.}
{215}{}{Ваши природные данные великолепны, но вы мало тренируетесь. Все ваши характеристики выше на 1, но каждый навык на начало игры меньше на 10%, и вы получаете на 5 очков навыков меньше за уровень.}
