# Alchemist: Warning! Achtung! Uwaga!
# Beca's script is bound to the ol' black male at the Blades map, but this is
# temporary measure. Actually Quatermistress IS a women! So she must be
# referenced as 'SHE/HER' NOT 'he/his/him'. 'Jade' stands for nickname and
# 'Bec'a stands for the real one.

{100}{}{Ves: a Jade.}
{101}{}{Ves: a Beca.}
{102}{}{}
{103}{}{}
{104}{}{Ves a un miembro de los Navajas.}
{105}{}{Ves a un miembro de los Navajas.}
{106}{}{Piensas que puede ser Libros.}
{107}{}{Piensas que puede ser Cicatrices}
{108}{}{Piensas que puede ser Pistolón}
{109}{}{Piensas que puede ser Tembleque.}
{110}{}{Piensas que puede ser Martillo.}
{111}{}{Piensas que puede ser Cuchilla.}
{112}{}{Estos son los dormitorios. Ahora lárgate antes de que te patee el culo.}
{113}{}{Adelante.}
{114}{}{Lo siento. Adiós.}
{115}{}{¿Puedo dormir aquí?}
{116}{}{No. Esto es para los Navajas, no para cualquier debilucho.}
{117}{}{¡Ey, compi! ¿Qué te cuentas? Duerme aquí si necesitas un lugar seguro.}
{118}{}{Así que has ayudado. Mejor que nada, lo reconozco. Gracias. Voy a decírcelo a los demás.}
{119}{}{Sí. Iré a ver lo que puedo hacer.}
{120}{}{Hola de nuevo. He oído que realmente nos has ayudado. Eres más que digno de nuestro respeto. Ahora somos libres. [Ahora eres un miembro de los Navajas.]}
{121}{}{No te puedo ayudar con eso. Ve a hablar con Cuchilla.}
