{100}{}{Gracias.}
{101}{}{Adiós.}
{102}{}{Hola.}

{103}{}{Ganas }
{104}{}{ puntos de experiencia.}

{105}{}{¡Uh, oh!}
{106}{}{¡Haz clic!}
{107}{}{¡Uy!}
{108}{}{¡Ay!}
{109}{}{Nos vemos.}
{110}{}{Tómatelo con calma.}
{111}{}{Ha sido divertido.}
{112}{}{Vamos ya.}
{113}{}{¿Algo más?}
{114}{}{Sí.}
{115}{}{No.}

{116}{}{Ganas }

{117}{}{ puntos de habilidad en Armas Pequeñas.}
{118}{}{ puntos de habilidad en Armas Grandes.}
{119}{}{ puntos de habilidad en Armas de Energía.}
{120}{}{ puntos de habilidad en Combate Desarmado.}
{121}{}{ puntos de habilidad en Armas de Melé.}
{122}{}{ puntos de habilidad en Armas Arrojadizas.}
{123}{}{ puntos de habilidad en Primeros Auxilios.}
{124}{}{ puntos de habilidad en Médico.}
{125}{}{ puntos de habilidad en Sigilo.}
{126}{}{ puntos de habilidad en Robar.}
{127}{}{ puntos de habilidad en Ganzúa.}
{128}{}{ puntos de habilidad en Trampas.}
{129}{}{ puntos de habilidad en Ciencia.}
{130}{}{ puntos de habilidad en Reparar.}
{131}{}{ puntos de habilidad en Conversación.}
{132}{}{ puntos de habilidad en Trueque.}
{133}{}{ puntos de habilidad en Jugar.}
{134}{}{ puntos de habilidad en Supervivencia.}

{135}{}{Ganas 1 punto de habilidad en Armas Pequeñas.}
{136}{}{Ganas 1 punto de habilidad en Armas Grandes.}
{137}{}{Ganas 1 punto de habilidad en Armas de Energía.}
{138}{}{Ganas 1 punto de habilidad en Combate Desarmado.}
{139}{}{Ganas 1 punto de habilidad en Armas de Melé.}
{140}{}{Ganas 1 punto de habilidad en Armas Arrojadizas.}
{141}{}{Ganas 1 punto de habilidad en Primeros Auxilios.}
{142}{}{Ganas 1 punto de habilidad en Médico.}
{143}{}{Ganas 1 punto de habilidad en Sigilo.}
{144}{}{Ganas 1 punto de habilidad en Robar.}
{145}{}{Ganas 1 punto de habilidad en Ganzúa.}
{146}{}{Ganas 1 punto de habilidad en Trampas.}
{147}{}{Ganas 1 punto de habilidad en Ciencia.}
{148}{}{Ganas 1 punto de habilidad en Reparar.}
{149}{}{Ganas 1 punto de habilidad en Conversación.}
{150}{}{Ganas 1 punto de habilidad en Trueque.}
{151}{}{Ganas 1 punto de habilidad en Jugar.}
{152}{}{Ganas 1 punto de habilidad en Supervivencia.}

{153}{}{Tu Fuerza ha incrementado en }
{154}{}{Tu Percepción ha incrementado en }
{155}{}{Tu Resistencia ha incrementado en }
{156}{}{Tu Carisma ha incrementado en}
{157}{}{Tu Inteligencia ha incrementado en }
{158}{}{Tu Agilidad ha incrementado en }
{159}{}{Tu Suerte ha incrementado en }
{160}{}{ puntos.}

{161}{}{Tu Fuerza ha aumentado 1 punto.}
{162}{}{Tu Percepción ha aumentado 1 punto.}
{163}{}{Tu Resistencia ha aumentado 1 punto.}
{164}{}{Tu Carisma ha aumentado 1 punto.}
{165}{}{Tu Inteligencia ha aumentado 1 punto.}
{166}{}{Tu Agilidad ha aumentado 1 punto.}
{167}{}{Tu Suerte ha aumentado 1 punto.}

{168}{}{Gracias por tu ayuda.}
{169}{}{Gracias por nada.}

{171}{}{Creo que el Maestro desea hablar contigo.}
{172}{}{¡Pagarás por tu BLASFEMIA!}

{173}{}{Este robot parece estar fuera de servicio. Posiblemente se deba a la falta de energía.}
{174}{}{No ves nada especial en este robot.}

{175}{}{Este Navaja se niega a hablar contigo.}

{176}{}{La maleta está sellada y no puede abrirse.}

{177}{}{Por favor, tenemos prisa. No tenemos tiempo para hablar.}
{178}{}{Sólo Morfeo tiene la llave de esta puerta. Debo irme ahora para hacerle saber a Nicole lo que ocurre aquí.}
{179}{}{Por favor, tengo que irme de aquí antes de que descubran quién soy.}

{180}{}{No puedes robar nada y piensas que quizás te han pillado.}
{181}{}{Los miembros de la Hermandad te han pillado robando.}

## Mysterious Stranger messages
{182}{}{¡Movámonos!}                         # 0
{183}{}{Parece que necesitas asistencia.}    # 1
{184}{}{Te ayudaré.}                         # 0
{185}{}{No hablo mucho. Lo siento.}          # 1

{186}{}{Escuchas el altavoz. ¡ALARMA! ¡Se ha detectado a un intruso!}
{187}{}{La sustancia pegajosa ha interrumpido la transmisión de tu jugada maestra.}
#188 is below
#189 is below

{200}{}{Estás viendo un emisor de campo muy dañado.}
{201}{}{El emisor está demasiado dañado para utilizarse.}
{202}{}{El emisor está demasiado dañado para repararse.}
{203}{}{Te das cuenta de que el campo está demasiado dañado para funcionar.}

##################################################
##################################################
## Additions by Sduibek for Fallout FIXT:
##################################################
##################################################


#"Push" telling Tycho/Ian/Katja to move if they're blocking your path
{190}{}{Hazte a un lado, por favor.}
{197}{}{¡Quítate de en medio, joder!}

#What the NPC says after you've made them move
{300}{}{Vale.}
{301}{}{Ups, lo siento.}
{302}{}{Oh, perdona.}

# System messages
{191}{}{Tycho es ahora de nivel }
{192}{}{Ian es ahora de nivel }
{193}{}{Katja es ahora de nivel }
{294}{}{Ahora eres de nivel }

{214}{}{El veneno ha abandonado tu sistema.}

{400}{}{La explosión debilita en gran medida este campo de energía. Ahora debería ser inofensivo pasar a través de él.}

# Stupid character interacting with hirelings
# TRANSLATION NOTE: Messages 194, 195, 196 have poor grammar,
#  improper spelling and improper capitalization on purpose
#  because they are for a character with Intelligence of 3 or less.
# The same should be done with translated versions.
{194}{}{¿tÚ Mover? ¡en mi CAMINO! [frunces el ceño]}
{195}{}{tú Ir, No hacer falta amigo...}
{196}{}{¿ser amigos?}

# Hireling inspections
{198}{}{ Lleva puesto }
{199}{}{ Lleva puesto }
{188}{}{Armadura de Metal.}
{189}{}{Armadura de Cuero.}
{204}{}{Armadura de Energía.}
{205}{}{Armadura de Combate.}
{206}{}{Chupa de Cuero.}
{207}{}{Túnica.}
{208}{}{Armadura de Energía (R).}
{209}{}{Armadura de la Hermandad}
{210}{}{Armadura Tesla.}


# Message trying to steal from things like brahmin, rats, scorpions
{211}{}{No puedes robarle a esta criatura.}

# Message when player examines themselves
#first examine
{212}{}{Te miras durante un rato. ¿Te gusta lo que ves?}
#subsequent examines
{218}{}{Debes de tener mucho tiempo para estar viéndote de esta forma.}

# Giving item to hireling (Ian/Tycho/Katja)
{215}{}{¡Gracias, le daré buen uso en combate!}

# For what distance hirelings should be from player
{216}{}{ Caminar al estar cerca.}
{217}{}{ Correr siempre.}

# For notifying user of Violence Level
{219}{}{El nivel de violencia es }
{220}{}{Ninguno.}
{221}{}{Mínimo.}
{222}{}{Normal.}
{223}{}{Máximo.}
{224}{}{ Nivel máximo recomendado para personajes con Masacre.}

#
# This one is for the option in CARVLEAD.SSL that shouldn't show up
#
{401}{}{CONTACTA CON SDUIBEK SI VES ESTE MENSAJE}

#an old option for debugging purposes
{402}{}{Variables del mod EndGame reseteadas. Por favor, intenta entrar de nuevo al Refugio 13.}

#### NOT USED ####
{403}{}{Has muerto. El Refugio está condenado.}

## For displaying player title on levelup, if user chose for that to be enabled
{404}{}{Tu título: }
{405}{}{Moradora del Refugio.}
{406}{}{Vástago del Refugio.}
{407}{}{Veterana del Refugio.}
{408}{}{Élite del Refugio.}
{409}{}{Nómada.}
{410}{}{Nómada del Desierto.}
{411}{}{Nómada del Yermo.}
{412}{}{Élite Nómada.}
{413}{}{Viajera.}
{414}{}{Viajera del Desierto.}
{415}{}{Viajera del Yermo.}
{416}{}{Viajera de Élite.}
{417}{}{Heroína del Refugio.}
{418}{}{Heroína Errante.}
{419}{}{Heroína Viajera.}
{420}{}{Heroína del Desierto.}
{421}{}{Heroína del Yermo.}
{422}{}{Heroína de las Tierras Resplandecientes.}
{423}{}{Parangón.}
{424}{}{Leyenda Viva.}
{425}{}{La Última y Mejor Esperanza de la Humanidad.}

## Warning player if loading character from old version of FIXT
{426}{}{Has cargado una partida de una versión del juego más antigua que Fallout FIXT }
#
# 427 is inserted after 426
#
{427}{}{alpha 6.1 - }
#
# 428 is inserted after 427
#
{428}{}{jugando con esta partida guardada puede causar errores durante la partida o cierres inesperados del juego. Disculpas por la inconveniencias y este mensaje.}
{429}{}{[Continuar] Entiendo el riesgo y deseo seguir jugando.}
{430}{}{[Volver al menú principal] Mmm. Prefiero no cargar esta partida guardada.}
{431}{}{Ugga-eeh?}
# 432 not used
{432}{}{[Continuar] Entiendo los riesgos y acuerdo no reportar bugs de personajes en versiones antiguas del juego. (Bugs tales como errores gramaticales aún pueden ser reportados)}

#
# For door to Brotherhood armory (weapons/armor stash on Lvl1)
#
{500}{}{La puerta se burla de ti al resistir desafiante la explosión, recibiendo solo algunas abolladuras.}
{501}{}{A la puerta le preocupa su habilidad para recibir más daño mientras cruje y se retuerce debido a la explosión.}
{502}{}{La puerta gime en agonía mientras sale volando de sus engranajes, cayendo al suelo y provocando un gran estruendo.}
#TRANSLATION NOTE: the spaces at end of 503 and beginning of 504 are required, do not remove them.
{503}{}{Ganas }
{504}{}{ puntos de experiencia por utilizar explosivos de forma satisfactoria.}


#
# For guards within Brotherhood armory (weapons/armor stash on Lvl1)
#
{601}{}{No deberías estar aquí, Iniciada.}
{602}{}{¿Qué estás haciendo aquí?}
{603}{}{Por favor, vete. No deberías estar aquí.}
{604}{}{Ey, no Iniciados.}
{605}{}{Lo siento, no puedo hablar con nadie. Ya sabes como es.}
{606}{}{Esta no es la biblioteca, chico. Si quieres investigar, por favor, ve a la biblioteca.}
{607}{}{Esta no es la biblioteca, chica. Si quieres investigar, por favor, ve a la biblioteca.}