{100}{}{La puerta ya está abierta.}
{101}{}{Consigues forzar la cerradura.}
{102}{}{Parece imposible forzar la cerradura.}
{103}{}{¡Recibes una descarga del sistema de seguridad electrónico!}
{104}{}{Te tropiezas con una alarma colocada en las puertas de suministros.}
{105}{}{La puerta tiene una cerradura que habrá que forzar.}
{106}{}{El sistema de seguridad electrónico está desarmado.}
{107}{}{Desarmas el sistema de seguridad electrónico.}