{100}{}{No se puede descender por este hueco de ascensor sin una cuerda.}
{101}{}{Consigues colgar la cuerda y bajar por el hueco del ascensor.}
{102}{}{No puedes bajar en la fosa usando sólo la viga metálica.}
{103}{}{Consigues atar la cuerda a la viga metálica.}
{104}{}{No se puede descender por este hueco de ascensor sin una cuerda.}
{105}{}{Consigues colgar una cuerda dentro del hueco del ascensor.}
{106}{}{No es necesario asegurar otra cuerda por el hueco de ascensor.}
