{100}{}{Вы видите привлекательную молодую девушку в темных одеждах.}
{101}{}{Вы видите Катю, вора.}
{102}{}{Вы не из здешних мест. Откуда вы?}
# TRANSLATION NOTE
# The player-character's name is inserted between lines 103 and 104 by the code.
{103}{}{Меня зовут }
{104}{}{.}
{105}{}{Я путешественник.}
{106}{}{Я могу спросить тоже самое.}
{107}{}{И могу я спросить что вы делаете в Бониярде?}
{108}{}{Вы задаете множество вопросов.}
{109}{}{'начала скажите мне кто вы.}
{110}{}{Я просто исследователь.}
{111}{}{Я ищу замену водяному фильтру для Ёранилища.}
{112}{}{Жизнь учит быть осторожным. И так что вы делаете здесь?}
{113}{}{Ладно, достаточно справедливо. Меня зовут Катя. Зачем вам это знать?}
{114}{}{Почему вы так враждебны?}
{115}{}{Ёей, если вы будете такой грубой то я пожалуй зайду позднее.}
{116}{}{Я ищу информацию. Вы не могли бы помочь?}
{117}{}{Вы можете, но вы на моей территории, не наоборот. 'ак что либо слушайтесь
 либо заткнитесь.}
{118}{}{Это неважно, Я просто путешественник. Мне нужна кое-какая информация.}
{119}{}{"ильтр для системы очистки воды? Извините, я ничего об этом не знаю. 'ут
 в Бониярде не так уж много технологических штучек, кроме тех над которыми
 работает Майлс.}
{120}{}{'пасибо в любом случае.}
{121}{}{Майлс? Где могу найти его и сможет ли он помочь мне?}
{122}{}{Вы не могли бы рассказать мне больше про Бониярд?}
{123}{}{Просто путешественник. Я слышала это раньше. Никто не приходит в
 Бониярд кроме торговцев из Ёаба и людей ищущих быструю смерть от рук
 банд. Зачем вы здесь на самом деле?}
{124}{}{Вы правы. Я ищу фильтр для системы очистки воды.}
{125}{}{Я не должен вам ничего рассказывать.}
{126}{}{Чертовски прямо. Но это двухсторонняя улица.}
{127}{}{Может быть. Вы точно не один из этих бандитов. Что
 вы хотите?}
{128}{}{Я ищу фильтр для системы очистки воды.}
{129}{}{Мне нужно больше информации о Бониярде.}
{130}{}{Мне надо знать область вокруг города.}
{131}{}{Что вы можете мне рассказать о Лезвиях?}
{132}{}{Что вы можете мне рассказать о Потрошителях?}
{133}{}{Что вы можете мне рассказать о 'китальцах Пустыни?}
{134}{}{Что вы можете мне рассказать о Последователях?}
{135}{}{Что вы можете мне рассказать об Адитуме?}
{136}{}{Ладно, было очень мило поболтать с вами. Пора идти.}
{137}{}{Майлс живет в Адитуме. Он ученый, работающий с химией.
 ...сли вам нужен водяной фильтр или замена ему, обратитесь к нему.}
{138}{}{'пасибо.}
{139}{}{Адитум это наш дом. Немного скучновато для меня, однако. Это
 отгороженный забором и самостоятельный город на южном конце Бониярда,
 но не так далеко как 'обор. Мы торгуем иногда с Ёабом.}
{140}{}{Я имела дело с ними раньше. Они не так уж и плохи, как банда.
 " них есть аванпост и место где прятаться в старом клубе. ...сли вы будите
 осторожны может вы сможете заставить их поговорить.}
{141}{}{Потрошители просто дикари. Они группа людей получающих наслаждение
 от убийств и мучений. Я держусь подальше от них, и вам советую.
 Они, мать их, все еще кладут гребаные наземные мины вокруг своей крепости.}
{142}{}{'китальцы Пустыни когда-то была настоящая банда но они стали мягкими. Они
 начали заниматься торговлей оружием с Ёабом и отбиранием оружия у людей.
 Поскольку никто здесь не знает дорогу в Ёаб лично, у них довольно
 хороший бизнес, хотя цены и высоковаты.}
{143}{}{Последователи Апокалипсиса это группа миротворцев которые живут в большой
 библиотеке около сердца Бониярда. Почему их еще не перебили, я не знаю.
 Они никудышные бойцы и имеют мало понимания о настоящем мире, но кроме этого
 они очень вежливы и хорошо обучены.}
{144}{}{Бониярд довольно-таки враждебное место. Я никогда не имела возможности
 уехать, и если бы она появилась я бы ею воспользовалась. Посмотрим... на
 юг отсюда находиться 'обор. 'ам какой-то культ, но я держусь подальше от
 этого места. Что-то недоброе происходит там. 'акже я слышала про торговый
 центр под названием Ёаб, и караваны часто приходят оттуда, но я там не была.}
{145}{}{Я не планирую оставаться здесь слишком долго.}
{146}{}{'пасибо за информацию.}
{147}{}{Вы можете рассказать мне еще немного?}
{148}{}{Без шуток. ...сли вам нужна помощь, я готова. Лучше чем проводить
 остаток жизни в этой дыре, не так-ли?}
{149}{}{Буду рад, но пустыня не лучшие место для веселья.}
{150}{}{Не беспокойтесь об этом. 'пасибо в любом случае.}
{151}{}{Могу я задать еще немного вопросов?}
{152}{}{Это область заполнена тремя бандами - Лезвия, Потрошители, и 'китальцы Пустыни
 - а также служит домом Последователям и мне, Адитум.}
{153}{}{Ладно, похоже надо понадавать немного по задницам!}
{154}{}{Послушайте, 90% людей живущих в этом городе попадает под одну из трех
 категорий - насильники, убийцы, и воры. Я вор и вы выглядите довольно вежливым
 и это заставляет меня задуматься, ладно? Назовите это инстинктом выживания.}
{155}{}{Извините что наступила на вас. Я думаю я пойду.}
{156}{}{Я могу по крайней мере задать еще несколько вопросов?}
{157}{}{Я не отсюда, так-что я не думаю что я считаюсь.}
{158}{}{Okей, но давайте быстро.}
{159}{}{Думаю я не могу спорить с логикой. 'ак что вам нужно?}
{160}{}{Могу я задать несколько вопросов?}
{161}{}{Я ищу фильтр для системы очищения воды. Не могли бы вы помочь?}
{162}{}{'пасибо, но я пойду.}
{163}{}{Чего нового?}
{164}{}{Не попробуете этот замок?}
{165}{}{Не посмотрите эту ловушку?}
{166}{}{Какие-нибудь советы?}
{167}{}{'пасибо за помощь. Можете теперь идти.}
{168}{}{Пока ничего. Но будьте готовы.}
{169}{}{Вы опять? Зачем вернулись?}
{170}{}{Просто хотел заскочить и сказать привет.}
{171}{}{" меня есть несколько вопросов если у вас есть время.}
{172}{}{Отперто.}
{173}{}{Что-то странное с книжным шкафчиком в восточной стене. Похоже он
 что-то скрывает.}
{174}{}{"берите свое оружие.}
{175}{}{Я ненавижу собак.}
{176}{}{Эта еда пахнет вкусно.}
{177}{}{Какие боевые искусства вы знаете?}
{178}{}{Я научилась всему в Бониярде. Я хорошо обращаюсь с ножами
 и пулеметами. Но любимое, конечно же метательные ножи.}
{179}{}{Ладно, хотя я не чувствую себя в безопасности без хорошего ножа.}
{180}{}{Вы получили 200 очков опыта за то что Катя присоединилась к вам.}
{181}{}{Что вы хотите теперь?}
{182}{}{Я передумал. Я по-прежнему хочу чтобы вы мне помогли.}
{183}{}{Ничего. Забудьте.}
{184}{}{Я начинаю ненавидеть это место.}
{185}{}{Вау. Я хотел бы чтобы у меня была собака и действительно длинная палка.}
{186}{}{Ох, я думаю меня сейчас вырвет.}
{187}{}{Ёей, вот это стена с слезой на постере выглядит как будто ее можно сдвинуть.}
{188}{}{Не повстречай Руку 'мерти!}
{189}{}{Ёубба хуббаba!}
{190}{}{"ходите!}
{191}{}{Простите но я просто не понимаю вас. Прощайте.}
#
# Katja tell-me-abouts
#
{980}{}{Я ничего не знаю об этом.}
{981}{}{Не могу сказать что я знаю что-то об этом.}
{982}{}{Нет, я ничего об этом не знаю.}
{1000}{}{Вода}
{1001}{}{Бониярд}
{1002}{}{Война}
{1003}{}{Адитум}
{1004}{}{Последователи}
{1005}{}{'обор}
{1006}{}{"ильтр}
{1007}{}{Гарл}
{1008}{}{Повелитель}
{1009}{}{...динство}
{1010}{}{'ет}
{1011}{}{Водораздел}
{1012}{}{Некрополис}
{1013}{}{Залы}
{1014}{}{Библиотека}
{1015}{}{'мотритель}
{1016}{}{Медик}
{1017}{}{Лечение}
{1018}{}{Ёранилище}
{1019}{}{Ёранилище-13}
{1020}{}{Ёранилище13}
{1021}{}{Киллиан}
{1022}{}{Гизмо}
{1023}{}{Джанктаун}
{1024}{}{Шэйди}
{1025}{}{'эндс}
{1026}{}{Ёаб}
{1027}{}{Казино}
{1028}{}{'клад}
{1029}{}{Рука 'мерти}
{1030}{}{Исход}
{1031}{}{Посвященные}
{1032}{}{Паладины}
{1033}{}{Писцы}
{1034}{}{Дети}
{1036}{}{Братство}
{1037}{}{ВЭ'ы}
{1038}{}{Военная}
{1039}{}{База}
{1041}{}{Апокалипсис}
{1042}{}{Мутанты}
{1043}{}{Морфеус}
{1044}{}{Ёаны}
{1045}{}{'анди}
{1046}{}{Аля}
{1047}{}{Диана}
{1048}{}{Гвен}
{1049}{}{Петрокс}
{1050}{}{'оля}
{1051}{}{Бузе}
{1052}{}{Наркотики}
{1053}{}{'етх}
{1054}{}{Арадеш}
{1055}{}{Разло}
{1056}{}{Циммерман}
{1057}{}{Регуляторы}
{1058}{}{'обиратели}
{1059}{}{Лезвия}
{1060}{}{Николь}
{1061}{}{Лейтенант}
{1062}{}{"изика}
{1063}{}{Эксперименты}
{1064}{}{Полиция}
{1065}{}{'орговцы}
{1100}{}{Я не знаю где можно найти такую древнюю реликвию старой технологии.}
{1101}{}{Кладбище Ангелов это все что осталось от Лос Анджелеса.
 Поделен между враждующими группировками в наше время.}
{1102}{}{Война принесла страдания и смерть на весь мир. Я надеюсь что
 что-либо подобное никогда не повториться. Но из того что я видел у
 человечества не очень много шансов.}
{1103}{}{Адитум был когда-то мои домом, но эти люди слишком параноичны.
 Они никогда не выживут просто закрывшись от мира.}
{1104}{}{Последователи Апокалипсиса молятся о мире. Жаль что это не вписывается
 в этот мир.}
{1105}{}{'обор монументальное сооружение на юге от Адитума, что-то около дня
 пешком. Им владеют какой-то странный культ который боготворит какого-то
 черного бога.}
{1106}{}{Не знаю где вы можете найти такую старую реликвию.}
{1107}{}{Я не больше вашего знаю об этом.}
{1108}{}{Я не больше вашего знаю об этом.}
{1109}{}{Я не больше вашего знаю об этом.}
{1110}{}{Я не больше вашего знаю об этом.}
{1111}{}{Я не больше вашего знаю об этом.}
{1112}{}{Что, город мертвецов? Разве это не миф?}
{1113}{}{Я не больше вашего знаю об этом.}
{1114}{}{Я не больше вашего знаю об этом.}
{1115}{}{Я не больше вашего знаю об этом.}
{1116}{}{" Последователей лекарь все время под рукой.}
{1117}{}{Вам следует сходить к лекарю у Последователей если вам нужно лечение.}
{1118}{}{Небыли-ли Ёранилища большими подземными укрытиями?}
{1119}{}{Небыли-ли Ёранилища большими подземными укрытиями?}
{1120}{}{Небыли-ли Ёранилища большими подземными укрытиями?}
{1121}{}{Я не больше вашего знаю об этом.}
{1122}{}{Я не больше вашего знаю об этом.}
{1123}{}{Маленький городок на севере о Ёаба.}
{1124}{}{Шэйди что?}
{1125}{}{Шэйди 'эндс? Никогда не слышала об этом.}
{1126}{}{Огромный торговый центр в Ёабе, с полным набором магазинов и торговцев.}
{1127}{}{Я не больше вашего знаю об этом.}
{1128}{}{'китальцы Пустыни продают вещи, и в Адитуме есть магазин.}
{1129}{}{"хх! Руки 'мерти везде в Бониярде. Я бы даже не думала об этом.
 Огромные и так названые.}
{1130}{}{Я не больше вашего знаю об этом.}
{1131}{}{Я не больше вашего знаю об этом.}
{1132}{}{Я не больше вашего знаю об этом.}
{1133}{}{Я не больше вашего знаю об этом.}
{1134}{}{Я не люблю детей.}
{1136}{}{Я слышал они наподобие высоко технологических монахов.}
{1137}{}{Я не больше вашего знаю об этом.}
{1138}{}{Я не больше вашего знаю об этом.}
{1139}{}{Я так понимаю должны быть остатки старой военной структуры.}
{1141}{}{Вы имеете ввиду большую войну? Вооо, должно быть вы действительно
 вели затворническую жизнь.}
{1142}{}{Я видела крысса с тремя глазами однажды. Это все что я знаю о мутантах.}
{1143}{}{Я думаю он Высший Жрец в 'оборе или что-то типа того.}
{1144}{}{Я не больше вашего знаю об этом.}
{1145}{}{Я не больше вашего знаю об этом.}
{1146}{}{Я не больше вашего знаю об этом.}
{1147}{}{Я не больше вашего знаю об этом.}
{1148}{}{Я не больше вашего знаю об этом.}
{1149}{}{Я не больше вашего знаю об этом.}
{1150}{}{Я не больше вашего знаю об этом.}
{1151}{}{Нет спасибо.}
{1152}{}{Нет. Я бы лучше нет. Я  видела друга умершего от передозировки
 Психотропа. Не очень красиво.}
{1153}{}{Я не больше вашего знаю об этом.}
{1154}{}{Я не больше вашего знаю об этом.}
{1155}{}{Я не больше вашего знаю об этом.}
{1156}{}{Он мэр Адитума. Честный, немного нерешительный человек.}
{1157}{}{Они следят за Адитумом и поддерживают контроль.}
{1158}{}{Я была 'обирателем. Мы ходили по ночам и искали полезные вещи в руинах
 Бониярда. Очень опасная работа. Мне плохо стало от Адитума, однако.}
{1159}{}{Это группа изгнанников живущих за Адитумом.}
{1160}{}{Она лидер Последователей. Интеллектуальная женщина, и с добрым
 сердцем.}
{1161}{}{Я не больше вашего знаю об этом.}
{1162}{}{" меня проявляется 'женская интуиция' время от времени, если вы это
 имеете в виду.}
{1163}{}{Я не больше вашего знаю об этом.}
{1164}{}{Я не больше вашего знаю об этого.}
{1165}{}{'орговцы торгуют с Адитумом время от времени и со 'китальцами Пустыни.}

{1999}{}{'еперь я знаю намного больше!}

{2000}{}{Давай обговорим тактику.}

{2001}{}{Я слушаю.}

{2010}{}{Используй лучшее оружие.}
{2011}{}{Поменяй броню.}                       # changed by WG
{2012}{}{Держись подальше от врагов.}
{2013}{}{'тарайся идти в ближний бой.}
{2014}{}{Поступай во время боя как угодно.}
{2015}{}{Назад}

{2100}{}{"казания поняла.}