# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used in LOADSAVE.C
#
# (These MUST match "text message" enumeration on the top of LOADSAVE.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

# System
{100}{}{读取进度}              # Titles
{101}{}{快速读取进度}
{102}{}{储存进度}
{103}{}{快速储存进度}
{104}{}{完成}
{105}{}{取消}
{106}{}{读取游戏存档列表错误！} # Line 1
{107}{}{游戏储存路径:}    # Line 2
{108}{}{不存在或已经损坏！} # Line 3
{109}{}{SAVE SLOT}
{110}{}{SAVE SLOT}
{111}{}{----- EMPTY -----}
{112}{}{- 坏的游戏存档 -}
{113}{}{- 旧的版本 -}
{114}{}{This save slot is empty.}
{115}{}{错误！}
{116}{}{旧的版本。}
{117}{}{- 1 -}                            # Months
{118}{}{- 2 -}
{119}{}{- 3 -}
{120}{}{- 4 -}
{121}{}{- 5 -}
{122}{}{- 6 -}
{123}{}{- 7 -}
{124}{}{- 8 -}
{125}{}{- 9 -}
{126}{}{- 10 -}
{127}{}{- 11 -}
{128}{}{- 12 -}
{129}{}{等级}
{130}{}{存档名称}
{131}{}{游戏存档已经存在，要覆盖吗？}
{132}{}{游戏储存错误！}             # Line 1
{133}{}{不能储存游戏。}           # Line 2
{134}{}{游戏读取错误！}            # Line 1
{135}{}{不能读取游戏。}           # Line 2
{136}{}{游戏存档是一个旧版本的。}
{137}{}{地图}

{140}{}{游戏已经保存。}
{141}{}{游戏已经读取。}

# Demo versions only
{200}{}{UNUSED}
{201}{}{UNUSED}
