#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used in OPTIONS.C
#
# (These MUST match "text message" enumeration on the top of OPTIONS.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Main option panel
#
# Buttons
{0}{}{储存进度}
{1}{}{读取进度}
{2}{}{系统设定}
{3}{}{离开游戏}
{4}{}{完成}
#
# Preferences
#
{100}{}{           游戏参数设置}
{101}{}{游戏难度}
{102}{}{战斗难度}
{103}{}{暴力程度}
{104}{}{显示目标边框}
{105}{}{UNUSED}
{106}{}{战斗中的对话}
{107}{}{COMBAT FLOATS}
{108}{}{脏话过滤器}
{109}{}{PLAYER RUNNING}
{110}{}{游戏字幕}
{111}{}{显示物品边框}
{112}{}{战斗速度}
{113}{}{对话显示时间}
{114}{}{主要音量}
{115}{}{MUSIC & MOVIE VOLUME}
{116}{}{特别音效音量}
{117}{}{语音音量}
{118}{}{BRIGHTNESS/CONTRAST}
{119}{}{滑鼠敏感度}
{120}{}{预设值}
{121}{}{取消}
{122}{}{影响主角的速度}
{123}{}{UNUSED}
#
# Label text
#
{201}{}{开}             # 1
{202}{}{关}            # 2
{203}{}{简单}           #  1
{204}{}{普通}         #  2
{205}{}{难}           #  3
{206}{}{简易级}          # 1
{207}{}{普通级}         # 2
{208}{}{困难级}          # 3
{209}{}{普通}         #  1
{210}{}{快速}        #  2
{211}{}{多}        # 1
{212}{}{少}          # 2
{213}{}{只有目标}
{214}{}{不要}           # 1
{215}{}{最低程度}        # 2
{216}{}{最血腥}  # 3
{217}{}{慢}           #  1
{218}{}{快}         #  2
{219}{}{开}
{220}{}{一些}
{221}{}{低}          # 1
{222}{}{高}           # 2
{223}{}{亮}
{224}{}{宽}
#
# Pause window
#
{300}{}{完成}
{301}{}{暂停}
#
# Demo versions only
#
{1000}{}{UNUSED}
{1001}{}{UNUSED}

