##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
# (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{Vault-dweller}
{200}{}{本地老乡}
{201}{}{穿着皮甲的男子}
{300}{}{本地老乡}
{301}{}{穿着金属装甲的男子。}
{400}{}{乞丐}
{401}{}{一个可怜的乞丐。}
{500}{}{农民}
{600}{}{Vault-dweller}
{700}{}{动力装甲}
{800}{}{The Overseer}
{900}{}{超级变种人}
{1000}{}{巨大的变种老鼠}
{1100}{}{大蝎子}
{1101}{}{A giant mutated scorpion, scourge to animals and humans alike.}
{1200}{}{穿长袍的人}
{1300}{}{商人}
{1400}{}{僵尸警卫}
{1401}{}{It was human once, or descended from humans. The tissue deterioration is likely due to acid or radiation.}
{1500}{}{穿战斗装甲的女人}
{1600}{}{一个发光的人}
{1601}{}{This humanoid is highly irradiated. While it was once human, it has reverted to a more animalistic lifestyle.}
{1700}{}{穿皮夹克的男人}
{1800}{}{农民}
{1900}{}{穿皮夹克的女人}
{2000}{}{农民}
{2100}{}{穿战斗装的男人}
{2200}{}{本地的女人}
{2201}{}{很有魅力的女人穿着一件金属装甲}
{2300}{}{超级变种人中尉}
{2400}{}{Nightkin}
{2500}{}{Townswoman}
{2501}{}{Human female wearing protective leather armor.}
{2600}{}{Vault-dweller}
{2700}{}{男警卫}
{2800}{}{勃拉莫}
{2900}{}{农民}
{3000}{}{乡下人}
{3100}{}{穿皮甲的男人}
{3200}{}{农夫}
{3300}{}{市民}
{3400}{}{Vault-dweller}
{3500}{}{Vault-dweller}
{3600}{}{狗}
{3601}{}{一条狗，很可能是混种狗。}
{3700}{}{女人}
{3800}{}{男人}
{3900}{}{乡下人}
{4000}{}{农民}
{4100}{}{Person encased in odd armor}
{4200}{}{男孩}
{4300}{}{小多脚兽}
{4400}{}{汉迪先生}
{4500}{}{浮游特}
{4600}{}{秘书}
{4700}{}{The Overseer}
{4800}{}{变种地鼠}
{4900}{}{吉斯莫}
{5000}{}{The Master}
{5100}{}{死亡爪}
{5101}{}{Many myths and rumors exist about these creatures, but their true origin remains unknown. Big, tough, fast.}
{5200}{}{技工}
{5300}{}{技工}
{5400}{}{技工}
{5500}{}{警卫}
{5600}{}{警卫}
{5700}{}{警卫}
{5800}{}{技工}
{5900}{}{市民}
{6000}{}{巴姆}
{6100}{}{工人}
{6200}{}{大教堂的学者}
{6300}{}{坦蒂}
{6400}{}{亚拉德什}
{6500}{}{赛思}
{6600}{}{商人}
{6700}{}{警卫}
{6800}{}{螳螂}
{6900}{}{圆顶机器人}
{7000}{}{歹徒守卫}
{7100}{}{市民}
{7200}{}{市民}
{7300}{}{伽尔的军师}
{7400}{}{市民}
{7500}{}{歹徒}
{7600}{}{伊恩}
{7700}{}{Floating Eye, Mk II}
{7800}{}{变种地鼠}
{7900}{}{基利安·达克沃特}
{8000}{}{拉尔斯}
{8100}{}{艾佐}
{8200}{}{旅行者}
{8300}{}{市民}
{8400}{}{市民}
{8500}{}{旅行者}
{8600}{}{农民}
{8700}{}{市民}
{8800}{}{商人}
{8900}{}{陌生的人}
{9000}{}{警卫}
{9100}{}{农场主}
{9200}{}{商人}
{9300}{}{农民}
{9400}{}{尼尔}
{9500}{}{农民}
{9600}{}{工人}
{9700}{}{商人}
{9800}{}{乡下人}
{9900}{}{恶棍}
{10000}{}{外国人}
{10100}{}{大教堂教徒}
{10200}{}{维尼}
{10300}{}{旅行的人}
{10400}{}{赛特}
{10500}{}{盖瑞特}
{10600}{}{Zombie}
{10601}{}{A highly irradiated ghoul. Its muscle and brain matter have rotted away, but it was once a vault-dweller like you.}
{10700}{}{夜行团警卫}
{10800}{}{超级变种人恶棍}
{10900}{}{僵尸警卫}
{10901}{}{It was human once, or descended from humans. The tissue deterioration is likely due to acid or radiation.}
{11000}{}{地下工作的人}
{11100}{}{丹}
{11200}{}{镇治安官格林}
{11300}{}{代理副警长}
{11400}{}{肯恩}
{11500}{}{戴米德}
{11600}{}{凯利}
{11700}{}{罗格尔}
{11800}{}{达伦·海托}
{11900}{}{玛撒}
{12000}{}{罗仑佐}
{12100}{}{雅各布}
{12200}{}{狗肉}
{12300}{}{茉莉}
{12400}{}{特洛伊}
{12500}{}{达雷尔}
{12600}{}{塔鲁斯}
{12700}{}{托马斯}
{12800}{}{马蒂雅}
{12900}{}{剃刀}
{13000}{}{坦格勒}
{13100}{}{塔琉斯}
{13200}{}{加布里尔}
{13300}{}{艾柏仑}
{13400}{}{万哈根}
{13500}{}{斯尔夫}
{13600}{}{拉舍尔}
{13700}{}{贝瑞卡斯}
{13800}{}{耶利米}
{13900}{}{超级变种人医生}
{14000}{}{基登}
{14001}{}{他用手散发出一种奇怪的能量。}
{14100}{}{多米尼克}
{14101}{}{在他的眼睛里闪耀着一种奇怪的能量。}
{14200}{}{露西}
{14201}{}{他的头上散发出一种奇怪的能量。}
{14300}{}{维葛普}
{14301}{}{在他的身体上有一小股能量在流动。}
{14400}{}{维舍斯}
{14500}{}{超级变种人中尉}
{14600}{}{劳拉}
{14700}{}{墨菲斯}
{14800}{}{妮可尔}
{14900}{}{弗蕾}
{15000}{}{马克松}
{15100}{}{隆伯斯}
{15200}{}{卡波特}
{15300}{}{德克}
{15400}{}{布奇}
{15500}{}{洛克西里}
{15600}{}{简恩}
{15700}{}{哈罗德}
{15800}{}{哈里}
{15900}{}{强壮的大老鼠}
{16000}{}{Irradiated Rat}
{16100}{}{Tough Irradiated Rat}
{16200}{}{巨大的变种地鼠}
{16300}{}{野狼}
{16400}{}{大双头牛}
{16500}{}{死亡爪的卵}
{16501}{}{A smaller and younger version of its terrifying counterpart, but no less dangerous.}
{16600}{}{肮脏的大蝎子}
{16700}{}{留着血的浮游特}
{16800}{}{大多脚兽}
{16900}{}{地位低下的农民}
{17000}{}{乡下人}
{17100}{}{农场主}
{17200}{}{工人}
{17300}{}{农场主}
{17400}{}{商人}
{17500}{}{警卫}
{17600}{}{大螳螂}
{17700}{}{巨大的变种地鼠}
{17800}{}{农场主}
{17900}{}{工人}
{18000}{}{商人}
{18100}{}{警卫}
{18200}{}{发光者}
{18201}{}{This humanoid is highly irradiated. While it was once human, it has reverted to a more animalistic lifestyle.}
{18300}{}{疯狂的发光人}
{18301}{}{This irradiated ghoul has maintained enough brain matter and motor function to be able to speak clearly.}
{18400}{}{蜥蜴}
{18401}{}{It was human once, or descended from humans. The tissue deterioration is likely due to acid or radiation.}
{18500}{}{警卫}
{18600}{}{超级变种人警卫}
{18700}{}{偏小的超级变种人}
{18800}{}{疯狂的超级变种人}
{18900}{}{致命的超级变种人}
{19000}{}{强壮的夜行团变种}
{19100}{}{强壮的夜行团}
{19200}{}{超级夜行团}
{19300}{}{夜行团头目}
{19400}{}{警卫}
{19500}{}{商人}
{19600}{}{警卫}
{19700}{}{警卫}
{19800}{}{警卫}
{19900}{}{女孩}
{20000}{}{秘书}
{20100}{}{警卫}
{20200}{}{陌生人}
{20300}{}{恶棍}
{20400}{}{雇佣兵}
{20500}{}{警卫}
{20600}{}{Vault-dweller}
{20700}{}{伽尔}
{20800}{}{莫彼得医生}
{20900}{}{格雷彻}
{21000}{}{提可}
{21100}{}{乔纳森}
{21200}{}{雅各布}
{21300}{}{玛利亚}
{21400}{}{瑞秋}
{21500}{}{卡勒布}
{21600}{}{旅行者}
{21700}{}{陌生人}
{21800}{}{恶棍}
{21900}{}{雇佣兵}
{22000}{}{警卫}
{22100}{}{市民}
{22200}{}{外国人}
{22300}{}{恶棍}
{22400}{}{雇佣兵}
{22500}{}{警卫}
{22600}{}{市民}
{22700}{}{旅行者}
{22800}{}{异乡人}
{22900}{}{混混}
{23000}{}{雇佣兵}
{23100}{}{警卫}
{23200}{}{市民}
{23300}{}{旅行者}
{23400}{}{雇佣兵}
{23500}{}{警卫}
{23600}{}{旅行者}
{23700}{}{陌生人}
{23800}{}{流氓}
{23900}{}{雇佣兵}
{24000}{}{警卫}
{24100}{}{小混混}
{24200}{}{雇佣兵}
{24300}{}{警卫}
{24400}{}{旅行者}
{24500}{}{陌生人}
{24600}{}{混混}
{24700}{}{雇佣兵}
{24800}{}{警卫}
{24900}{}{旅行者}
{25000}{}{异乡人}
{25100}{}{恶棍}
{25200}{}{雇佣兵}
{25300}{}{警卫}
{25400}{}{旅行者}
{25500}{}{外地人}
{25600}{}{恶棍}
{25700}{}{雇佣兵}
{25800}{}{警卫}
{25900}{}{旅行者}
{26000}{}{陌生人}
{26100}{}{地痞}
{26200}{}{雇佣兵}
{26300}{}{警卫}
{26400}{}{见习骑士}
{26500}{}{进阶见习骑士}
{26600}{}{初级骑士}
{26700}{}{中级骑士}
{26800}{}{资深骑士}
{26900}{}{见习骑士}
{27000}{}{进阶见习骑士}
{27100}{}{初级骑士}
{27200}{}{中级骑士}
{27300}{}{资深骑士}
{27400}{}{高级游侠}
{27500}{}{游侠}
{27600}{}{资深游侠}
{27700}{}{高级游侠}
{27800}{}{游侠}
{27900}{}{资深游侠}
{28000}{}{见习研究员}
{28100}{}{进阶见习研究员}
{28200}{}{初级研究员}
{28300}{}{中级研究员}
{28400}{}{资深研究员}
{28500}{}{见习研究员}
{28600}{}{进阶见习研究员}
{28700}{}{初级研究员}
{28800}{}{中级研究员}
{28900}{}{资深研究员}
{29000}{}{穿长袍的男人}
{29100}{}{主教的孩子}
{29200}{}{初级教徒}
{29300}{}{穿长袍的女人}
{29400}{}{主教的孩子}
{29500}{}{主教的宠物}
{29600}{}{主教的恶棍}
{29700}{}{主教的警卫}
{29800}{}{主教的宠物}
{29900}{}{主教的恶棍}
{30000}{}{主教的警卫}
{30100}{}{医生}
{30200}{}{卡佳}
{30300}{}{萨舍}
{30301}{}{你看到一条很大的爱斯基摩犬在静静的等待着它的主人。}
{30400}{}{神秘陌生人}
{30500}{}{蠢笨的僵尸}
{30501}{}{A highly irradiated ghoul. Its muscle and brain matter have rotted away, but it was once a vault-dweller like you.}
{30600}{}{Floating Eye}
{30700}{}{卵}
{30701}{}{死亡爪的卵}
{30800}{}{杜根}
{30900}{}{雌性死亡爪}
{31000}{}{悍马}
{31100}{}{死了的旅行者}
{31200}{}{肯基}
{31300}{}{Ian}
{31400}{}{Ian}
{31500}{}{Ian}
{31600}{}{Ian}
{31700}{}{Ian}
{31800}{}{Ian}
{31900}{}{Ian}
{32000}{}{Ian}
{32100}{}{Ian}
{32200}{}{Ian}
{32300}{}{Ian}
{32400}{}{Ian}
{32500}{}{Ian}
{32600}{}{Ian}
{32700}{}{Ian}
{32800}{}{Ian}
{32900}{}{Ian}
{33000}{}{Ian}
{33100}{}{Ian}
{33200}{}{Ian}
{33300}{}{Ian}
{33400}{}{Ian}
{33500}{}{Ian}
{33600}{}{Ian}
{33700}{}{Ian}
{33800}{}{Ian}
{33900}{}{Ian}
{34000}{}{Tycho}
{34100}{}{Tycho}
{34200}{}{Tycho}
{34300}{}{Tycho}
{34400}{}{Tycho}
{34500}{}{Tycho}
{34600}{}{Tycho}
{34700}{}{Tycho}
{34800}{}{Tycho}
{34900}{}{Tycho}
{35000}{}{Tycho}
{35100}{}{Tycho}
{35200}{}{Tycho}
{35300}{}{Tycho}
{35400}{}{Tycho}
{35500}{}{Tycho}
{35600}{}{Tycho}
{35700}{}{Tycho}
{35800}{}{Tycho}
{35900}{}{Tycho}
{36000}{}{Tycho}
{36100}{}{Tycho}
{36200}{}{Tycho}
{36300}{}{Tycho}
{36400}{}{Tycho}
{36500}{}{Tycho}
{36600}{}{Tycho}
{36700}{}{Katja}
{36800}{}{Katja}
{36900}{}{Katja}
{37000}{}{Katja}
{37100}{}{Katja}
{37200}{}{Katja}
{37300}{}{Katja}
{37400}{}{Katja}
{37500}{}{Katja}
{37600}{}{Katja}
{37700}{}{Katja}
{37800}{}{Katja}
{37900}{}{Katja}
{38000}{}{Katja}
{38100}{}{Katja}
{38200}{}{Katja}
{38300}{}{Katja}
{38400}{}{Katja}
{38500}{}{Katja}
{38600}{}{Katja}
{38700}{}{Katja}
{38800}{}{Katja}
{38900}{}{Katja}
{39000}{}{Katja}
{39100}{}{Katja}
{39200}{}{Katja}
{39300}{}{Katja}
{39400}{}{Baby Radscorpion}
{39500}{}{Mother Radscorpion}
{39600}{}{The Overseer}
