{100}{}{Взрыв засыпал вход в тоннель!}
{101}{}{Вы уронили взрывчатку, и она рванула!}
{102}{}{Взрыв ??? расширил проход. Теперь загородить его точно не удастся.}
{103}{}{Вы получаете опыт за успешное использование взрывчатки.}
