{100}{}{Вы видите покупателя.}
{101}{}{У них никогда нет того, что мне надо.}
{102}{}{С каждым разом выбор все меньше.}
{103}{}{Извини, с чужаками не общаюсь.}
{104}{}{Нужный товар никогда не привозят.}
{105}{}{Увидишь ??? Редалека, скажи мне.}
{106}{}{Цены какие-то запредельные.}
{107}{}{Хорошо, что торговцы водой сюда больше не приезжают.}
{108}{}{Если есть вопросы, обратись к Кэбботу или Дареллу.}
{109}{}{Кэббот - наш привратник. Поговори с ним или с Дареллом.}
{110}{}{У Красного каравана товары лучше.}
{111}{}{Дальнобойщики - приятные люди, да?}
{112}{}{Караванщики Красного каравана слишком грубые.}
