{100}{}{??? Этот человек вот-вот взорвется.}
{101}{}{Тело настолько обуглилось, что даже непонятно, чей это труп.}
{102}{}{Ветер унес часть пепла.}
{103}{}{Наверное, это был ядерный взрыв.}
{104}{}{Пепел сыпется сквозь пальцы.}
