{100}{}{Это диск с кодексом Братства.}
{101}{}{Pip-Boy: файл найден в системе. Загрузка отменена.}
{102}{}{Pip-Boy: загрузка данных с диска.}
{103}{}{Вы видите диск с зашифрованной информацией.}
{104}{}{Вы видите диск.}
