{100}{}{Вы видите Деметра.}
{101}{}{Привет! Как дела? Меня зовут Деметр, Деметр Ромара. У меня лучшие караваны во всей пустыне. Ищешь работу?}
{102}{}{Хм... Что-то не видно в тебе особой мощи, но... Наверное, ты неплохо владеешь оружием, если тебе удалось выжить в пустыне! Готов спорить, ты круче, чем кажешься на первый взгляд!}
{103}{}{Да, здоровья у тебя хватает.}
{104}{}{Да, сил у тебя хватает.}
{105}{}{Черт, силищи в тебе просто немерено!}
{106}{}{Черт! Похоже, ты гору можешь поднять!}
{107}{}{Ну так что?}
{108}{}{А тебе какое дело?}
{109}{}{А?}
{110}{}{Как раз тебя-то мы и искали! Любишь острые ощущения, да? Пули свистят над головой, ты видишь страх в глазах у врагов! Вот это жизнь, а? Если хорошо на нас поработаешь, мы хорошо заплатим. По рукам?}
{111}{}{И сколько платите?}
{112}{}{Я всех порву на куски!}
{113}{}{Нет, спасибо.}
{114}{}{Мне нужен водяной чип.}
{115}{}{Что ты знаешь о пропавших караванах?}
{116}{}{Мне пора.}
{117}{}{Ух-х, ух!}
{118}{}{600 крышек за поездку. И это в одну сторону! Говорят, что мы выбираем опасные маршруты, но они же самые интересные! В жизни же должна быть какая-то перчинка, так ведь? Так, конечно!}
{119}{}{Черт, это именно то, что мне нужно!}
{120}{}{А ты всегда так орешь, паренек?}
{121}{}{Опасные маршруты?}
{122}{}{Нет, спасибо.}
{123}{}{Именно! Поговори с Кэри в соседней комнате. Она знает, когда уходит следующий караван!}
{124}{}{Паренек? Это ты мне?}
{125}{}{А ты что, громких звуков боишься?}
{126}{}{Да.}
{127}{}{Только по ночам.}
{128}{}{Нет, просто интересно - ты глухой или тупой?}
{129}{}{Нет, просто уши закладывает.}
{130}{}{Ха! И то, и другое! Ладно, иди поговори с Кэри в соседней комнате, если будешь работать.}
{131}{}{Выпендриваешься? Ладно, мне-то все равно! Главное, чтобы караваны были в безопасности. Поговори с Кэри в соседней комнате, если тебе нужна работа.}
{132}{}{Ха! С тобой не соскучишься! Ну, если сумеешь побороть свой страх, приходи!}
{133}{}{Разумеется, это опасно! Иначе с чего я стал платить 600 баксов?}
{134}{}{Ладно, пока!}
{135}{}{Я берусь за эту работу.}
{136}{}{Вон отсюда, или я тебе голову оторву!}
{137}{}{Я тебе кишки на нож намотаю!}
{138}{}{Так-то!}
{139}{}{Еще бы! Поговори с Кэри в соседней комнате, она составляет график ухода караванов.}
{140}{}{Черт, жаль! Ну да ладно.}
{141}{}{Да, ты мне нравишься! Я тебя нанимаю! Поговори с Кэри в соседней комнате, она расскажет тебе про караваны.}
{142}{}{Водяной чип? Не слышал. Может быть, поищешь в наших магазинах? Там кучу всякой ерунды продают. Так что, работать на меня будешь?}
{143}{}{А сколько платят?}
{144}{}{Нет, пожалуй.}
{145}{}{Практически ничего. Мы потеряли только два каравана. Понятия не имею, почему Дальнобойщикам так не везет.}
{146}{}{А сам-то ты что думаешь?}
{147}{}{Может, дело в маршрутах или грузах?}
{148}{}{О'кей, спасибо.}
{149}{}{Не знаю, кто за этим стоит, но команда у него просто убойная! Наши караваны отлично вооружены - хоть кто-то из охранников должен был выжить! Но нет, никто не вернулся.}
{150}{}{Так сколько платят за эту работу?}
{151}{}{Может, дело в маршрутах или грузах?}
{152}{}{О'кей, спасибо.}
{153}{}{Черт, да мы ходим в более опасные места, чем они! И груз у нас лучше!}
{154}{}{Как это - "груз лучше"?}
{155}{}{Не волнуйся, я ни на что не намекаю.}
{156}{}{Врешь!}
{157}{}{Ну ладно, может и не лучше. Зато ассортимент больше.}
{158}{}{О'кей, спасибо.}
{159}{}{Знаешь, Бет что-то болтала про Когтей смерти. Я бы на твоем месте спросил у нее. Говорят еще, что по ночам с северо-востока доносятся какие-то жуткие звуки.}
{160}{}{Знаешь, у нас хорошо платят за работу, поэтому мы нанимаем только лучших. В караванщики не всякий сгодится!}
{161}{}{Да сдалась мне твоя работа, придурок!}
{162}{}{Извини, что пришлось тебя побеспокоить.}
{163}{}{А есть другая работа?}
{164}{}{А-ту?}
{165}{}{Я же сказал, что мы тебя не возьмем!}
{166}{}{Извини, для нас это слишком большой риск!}
{167}{}{Зря теряешь время!}
{168}{}{Прекрати меня доставать!}
{169}{}{Все, хватит!}
{170}{}{Деметр не обращает на вас внимания.}
{171}{}{Эй, я не беру на работу наркоманов! Приди в себя, а потом поговорим!}
{172}{}{Я не нарко.... Э-э... Ар-рг!}
{173}{}{Ха!}
{174}{}{Балуешься наркотиками? Хорошо, что ты с нами уже не работаешь!}
{175}{}{Да нет же, черт побери! Ты просто не понимаешь, чем мы рискуем! Я удивляюсь, как Дальнобойщики держатся на плаву - у них пропала целая куча караванов!}
{176}{}{Извини, лучше обратись еще к кому-нибудь. Я больше рисковать не буду.}
{177}{}{Убирайся отсюда! Мне уже тошно от тебя!}
{178}{}{Эй! Ты что делаешь?}
{179}{}{Эта дверь ведет к нам на склад.}
{180}{}{Она открывается только с другой стороны.}
{181}{}{С тобой что-то не так.}
{182}{}{Ты зря тратишь время.}
{183}{}{Он не обращает на вас внимания.}
{184}{}{Ну так что? Хочешь поработать? У нас и не скучно, и деньги хорошие платят!}
{185}{}{Хм. И сколько же?}
{186}{}{Я всех порву на куски!}
{187}{}{Нет, спасибо.}
{188}{}{Мне нужен водяной чип.}
{189}{}{Что ты знаешь о пропавших караванах?}
{190}{}{Мне пора.}
{191}{}{Уг-гук?}
{192}{}{Привет! Отличная работа, просто отличная! Чего ты хочешь?}
{193}{}{Мне бы еще поработать.}
{194}{}{Мне нужен водяной чип.}
{195}{}{Что ты знаешь о пропавших караванах?}
{196}{}{Так, просто захотелось поздороваться.}
{197}{}{Нет, спасибо. Всего хорошего.}
{198}{}{Мы потеряли весь груз! Нет уж, тебя мы больше на работу не примем.}
{199}{}{Мы чуть не потеряли тот караван! Тебе еще повезло... Больше ты с нами не работаешь.}
{200}{}{Мы не нанимаем! Что еще тебе нужно?}
{201}{}{Исчезни! Вакансий нет.}
{202}{}{Мне нужен водяной чип.}
{203}{}{Что ты знаешь о пропавших караванах?}
{204}{}{Уйди с дороги, чучело!}
{205}{}{Хочу сделать из тебя отбивную!}
{206}{}{Ничего.}
{207}{}{Уг-гук?}
{208}{}{Ой, какие мы крутые... Не смеши меня!}
{209}{}{Поговори с моей дочерью Кэри, она этим занимается. Она в соседней комнате.}
{210}{}{Я тебе уже сказал, поговори с Кэри! Она сидит в соседней комнате.}
{211}{}{Она твоя дочь?}
{212}{}{Это страшилище - твоя дочь? Что ж, это многое объясняет!}
{213}{}{Ладно.}
{214}{}{Да, она моя гордость! Красавица, правда? Если понадобится еще работа, поговори с ней. Когда-нибудь... надеюсь, скоро... я уйду на покой, и тогда она займет мое место.}
{215}{}{Вряд ли, если я убью вас обоих.}
{216}{}{О'кей, спасибо.}
{217}{}{Ты оскорбляешь мою семью? Да я тебе сердце вырежу!}
{218}{}{Прошу прощения. Просто неудачная шутка.}
{219}{}{Ха! Это только начало!}
{220}{}{Поздно извиняться! [Его лицо наливается кровью... Говорит тихим голосом.] Уходи, пока я не сорвался!}
{221}{}{Ты мне угрожаешь?}
{222}{}{Можешь срываться. Ты покойник!}
{223}{}{Ладно, может, это и перебор с моей стороны.}
{224}{}{Извини, мне пора идти. Пока!}
{225}{}{Видали и покруче кое-кого.}
{226}{}{Ладно, пока.}
{227}{}{Ты умрешь!}
{228}{}{Гы, ладно.}
{229}{}{Чего ты ждешь? За работу!}
{230}{}{Караваны еще не готовы.}
{231}{}{У меня тут еще кое-какие дела.}
{232}{}{Мне нужен водяной чип.}
{233}{}{Что ты знаешь о пропавших караванах?}
{234}{}{О'кей, пока!}
{235}{}{Рык-рок?}
{236}{}{Ра-оу?}
{237}{}{Черт! Ты многое теряешь. Наши караваны - отличная приманка для бандитов и диких тварей. Приключения тебе гарантированы! Держи. Думаю, тебе пригодится. [Он протягивает вам осколочную гранату.]}
{238}{}{Черт! Да когда же отправление?}
{239}{}{Как там твое барахло?}
{240}{}{Не задерживайся.}
{241}{}{Кэри, все готово?}
{242}{}{Убей врага, пока он не убил тебя!}
{243}{}{Обожаю наблюдать за гибелью своих врагов!}
{244}{}{Черта с два!}
{245}{}{Черт, где моя пушка?}
