{100}{}{Шкафчик заперт.}
{101}{}{Вы замечаете ловушку на шкафчике и обезвреживаете ее.}
{102}{}{Вы замечаете ловушку на шкафчике, но вам не удается ее обезвредить.}
{103}{}{Вы замечаете ловушку на шкафчике и случайно задеваете ее!}
{104}{}{Вы обезвредили ловушку.}
{105}{}{Вам не удалось обезвредить ловушку.}
{106}{}{Вы случайно задеваете ловушку!}
{107}{}{Вы отперли шкафчик.}
{108}{}{Вам не удалось взломать замок на шкафчике.}
{109}{}{Замок на шкафчике уже взломан.}
{110}{}{Вы заклинили замок. Теперь вы не сможете его открыть.}
{111}{}{Вы замечаете кустарное взрывное устройство на шкафчике.}
