{100}{}{Вы видите Лу, Дитя ночи.}
{101}{}{Вы видите Сью, Дитя ночи.}
{102}{}{Вы видите Дрю, Дитя ночи.}
{103}{}{Вы видите Курта, Дитя ночи.}
{104}{}{Вы видите Берта, Дитя ночи.}
{105}{}{Вы видите Тайке, Дитя ночи.}
{106}{}{Вы видите Майка, Дитя ночи.}
{107}{}{Вы видите Чара, Дитя ночи.}
{108}{}{Вы видите Рейне, Дитя ночи.}
{109}{}{Вы видите Даггарта, Дитя ночи.}
{110}{}{Моей сказали, с тобой надо что-то сделать. То, что делают с нормальными. Моя не помнит, что.}
{111}{}{Моя думает, все нормальные тупые.}
{112}{}{Все нормальные сдохнут!}
{113}{}{Утерн умный. Ага.}
{114}{}{Босс говорит: нормальные - ничто.}
{115}{}{Не знаю, зачем босс хочет эти книжки.}
{116}{}{Моя радуется, что рядом нет нормальных. Они все уроды.}
{117}{}{Моя лучше твоей! Моя лучше твоей!}
{118}{}{Моя твою прибьет!}
