{100}{}{Охранник свирепеет и нападает на вас.}
{101}{}{Охранник устрашен вашей силой.}
{102}{}{Только Меч Тени смог бы устрашить этого охранника. Вам придется произвести нужное впечатление с помощью слов.}
{103}{}{Вам удалось обворовать охранника.}
{104}{}{Вас заметили.}
{105}{}{У охранника больше ничего нет.}
{106}{}{Охранник никак не реагирует.}
{107}{}{Охранник Джанктауна.}
{108}{}{Что ты делаешь в Джанктауне?}
{109}{}{Ищу, где бы поразвлечься.}
{110}{}{Кошелек или жизнь!}
{111}{}{Где тут можно найти оружие?}
{112}{}{Ничего, спасибо. До свидания.}
{113}{}{Здесь много интересного. Походи по городу и посмотри, что тебе по вкусу. Главное, не нарывайся на неприятности.}
{114}{}{Что у вас тут примечательного?}
{115}{}{Отлично! Давай-ка, выворачивай карманы!}
{116}{}{Спасибо. До свидания.}
{117}{}{Говорят, в одном доме на северо-западной стороне спрятано неплохое оружие. Никто его до сих пор не смог найти.}
{118}{}{О'кей. Спасибо, что уделили мне время.}
{119}{}{Что еще?}
{120}{}{Ладно, ладно! Только не трогай меня.}
{121}{}{Не выйдет! Сдохни!}
{122}{}{Говорят, в одном доме на северо-западной стороне спрятано неплохое оружие. Никто его до сих пор не смог найти.}
{123}{}{Извини, я всего лишь охранник. Поговори еще с кем-нибудь.}
{124}{}{В полной версии игры у вас будет множество альтернатив. Вы сможете уничтожить врагов, прокрасться мимо или перехитрить их в разговоре.}
{125}{}{В полной версии игры у персонажей будет больше навыков.}
