{100}{}{Штаб, это пост 4. Все в порядке. Конец связи.}
{101}{}{Умри!}
{102}{}{Чужак!}
{103}{}{Че-ло-век!}
{104}{}{Стоять! Сюда нельзя. Уходи.}
{105}{}{Твоя сдаваться.}
{106}{}{Твоя стоять. Моя отвести к лейтенанту. Подчинись или умри.}
{107}{}{Люг-ги!}
{108}{}{Сдохни, адское отродье!}
{109}{}{Мне нужно поговорить с Создателем.}
{110}{}{Я тоже мутант, особого вида. Выполняю секретное задание Создателя. Пусти, или пожалеешь!}
{111}{}{Я из Собора. Пропусти.}
{112}{}{Умри!}
{113}{}{Прощайся с жизнью.}
{114}{}{Смешно. Теперь ты умрешь!}
{115}{}{Хорошо, пошли. Только без фокусов.}
{116}{}{О'кей, пошли.}
{117}{}{А как насчет такого фокуса - я превращаю тебя в отбивную?}
{118}{}{Я тебе не верю.}
{119}{}{Нет.}
{120}{}{Нет. Ты человек. Ты умрешь.}
{121}{}{Если ты лжет, ты умрет.}
{122}{}{Хорошо, проходи.}
{123}{}{Отлично. Наверное, тебя надо отвести к лейтенанту.}
{124}{}{Ты убийца моего брата! Я отомщу!}
{125}{}{Умри!}
{126}{}{Убийца!}
{127}{}{Умри!}
