{100}{}{Вы видите управляющего-гуля.}
{101}{}{Ты что тут делаешь?}
{102}{}{Ищу связь между прошлым и будущим.}
{103}{}{Я путешествую.}
{104}{}{А тебе-то что, обглоданный?}
{105}{}{Даг-даг.}
{106}{}{Чего-чего?}
{107}{}{Ничего.}
{108}{}{Я ищу забытое знание.}
{109}{}{Я так и понял. Вон из моего дома.}
{110}{}{Тут ничего нет. Поищи в храме или там, где вода хранится. Все, иди.}
{111}{}{О-па! Не надо у меня тут шарить! Иди отсюда! Я серьезно.}
{112}{}{Хватит тут торчать. Я уже устал от тебя.}
{113}{}{Ага.}
{114}{}{Я тебе сейчас голову оторву и знаешь куда ее затолкаю?}
{115}{}{Ох, извини! Уже ухожу.}
{116}{}{Не наглей! Тоже мне, громила. Сейчас огребешь у меня по полной!}
{117}{}{Я не буду с тобой говорить.}
