{100}{}{Вы видите Гарольда.}
{101}{HROLD0}{Подбрось мелочишки, а? Пожалей бедного старого мутанта!}
{102}{}{Вот, держи 25 баксов.}
{103}{}{5 крышек хватит?}
{104}{}{Извини, у меня нет денег.}
{105}{}{Отвяжись!}
{106}{}{Чего?}
{107}{HROLD1}{Сочувствую. Тебе, наверное, совсем тяжко приходится.}
{108}{HROLD2}{О, спасибо за щедрость! Знаешь, если бы я мог, я бы уже расплакался.}
{109}{}{Почему?}
{110}{}{Пожалуйста.}
{111}{HROLD3}{[Кашляет.] С тех пор как я сюда вернулся, хабберы мне покоя не дают. Все время кто-нибудь цепляется к бедному старому Гарольду. Но уехать я не могу. Все-таки [всхлипывает] здесь мой дом.}
{112}{}{Что с тобой случилось?}
{113}{}{Кто такие хабберы?}
{114}{}{Надеюсь, дела наладятся. До встречи!}
{115}{HROLD4}{После Великой войны мое убежище открылось первым. [Глубоко вздыхает.] Ох... Давно это было.}
{116}{}{Расскажи мне о том времени.}
{117}{}{Нет, нет. Я имею в виду, почему ты таким стал?}
{118}{HROLD5}{Вначале загудели сирены... Хоть я тогда был молод, до сих пор все помню. Ужасные были годы... И вот однажды утром я покинул свое убежище.}
{119}{}{Чем ты тогда занимался?}
{120}{}{Где находилось твое убежище?}
{121}{}{Сколько же тебе сейчас лет?}
{122}{HROLD6}{Знаешь, [кашляет] я сейчас уже и не вспомню. На западе, наверное. Или на востоке? Ох, не знаю. [Надрывно кашляет.]}
{123}{}{Чем ты тогда занимался?}
{124}{HROLD7}{Торговал. Мотался от одного поселка к другому. Ох, много я тогда хороших ребят потерял... [Кашляет.]}
{125}{}{Как это случилось?}
{126}{HROLD8}{Бандиты грабили наши караваны. А уж сколько мутантов тогда расплодилось... [Кашляет.] Приходилось кормить целую армию охранников.}
{127}{}{И что, охранники не справлялись?}
{128}{}{А откуда появлялись мутанты?}
{129}{HROLD9}{Они справлялись, дубина! Просто бандитов было слишком много.}
{130}{}{Как тебе удалось спастись?}
{131}{HROLD9A}{Я не спасся. Меня убили... [Смеется, кашляет.] Обожаю эту шутку.}
{132}{}{Мда, понятно.}
{133}{HROLD10}{Отовсюду! Но чаще всего - с северо-запада.}
{134}{}{Вы ходили туда?}
{135}{}{Почему нельзя было просто обойти опасные районы?}
{136}{}{Значит, на северо-запад вы и носа не сунули?}
{137}{hrold10a}{[Смеется.] Нет, ошибаешься!}
{138}{HROLD11}{Мы снарядили экспедицию. Бедняга Ричард... Ричард Грей. Он повел туда наш маленький отряд.}
{139}{}{Ричард Грей?}
{140}{}{Куда именно вы отправились?}
{141}{HROLD12}{Надо было узнать, что там творится. Да и от мутантов хотелось избавиться раз и навсегда. Мы думали, что хорошо подготовились. Ох, напрасно...}
{142}{}{Что произошло?}
{143}{HROLD13}{Я уже точно не помню... Куда-то на северо-запад.}
{144}{}{Можешь излагать покороче?}
{145}{}{Кто руководил вашей экспедицией?}
{146}{HROLD14}{Доктор Ричард Грей. Чуть постарше меня, чертовски умный парень... Он и нашел эту чертову базу.}
{147}{}{И что же это было?}
{148}{HROLD15}{Рассказываю, как хочу. За сокращенный вариант гони еще 25 баксов. Ну что, рассказывать подробно или покороче?}
{149}{}{Ладно, давай подробно.}
{150}{}{Покороче.}
{151}{}{Рассказывай покороче, только денег у меня нет.}
{152}{}{Хватит, надоели мне твои байки!}
{153}{HROLD16}{Ладно, ты мне нравишься. Я слегка подсокращу историю.}
{154}{}{Спасибо.}
{155}{hrold16a}{Врешь старому больному мутанту... Эх, куда мир катится? [Вздыхает.]}
{156}{hrold17}{Плохо с деньгами, да?}
{157}{hrold17a}{Дело твое. Не хочешь - не слушай.}
{158}{}{Мне пора.}
{159}{}{Ладно, рассказывай.}
{160}{HROLD18}{Какая-то старая военная база. Ох, много наших ребят там полегло...}
{161}{}{Почему вы решили, что мутанты именно с этой базы?}
{162}{}{Что вы там нашли?}
{163}{HROLD19}{Кучу роботов и всяких других машин. Странно, что они все работали. Как будто никакой войны и не было. В общем, они рвали нас как тузик грелку.}
{164}{}{Вы уничтожили роботов? Что было потом?}
{165}{HROLD20}{Потому что их там были целые толпы! Они пачками на нас шли. Сразу стало ясно, что все они с этой базы.}
{166}{}{Вы осмотрели базу?}
{167}{HROLD21}{Мы забрались очень глубоко. Наших к тому моменту уцелело совсем мало: Грей, я и еще пара человек.}
{168}{}{А потом?}
{169}{HROLD22}{Потом погибла Фрэнсин - ее подстрелил робот. Марка ранили, и его пришлось отправить на поверхность. Остались только мы с Греем.}
{170}{}{Что случилось с Марком?}
{171}{}{Что было потом?}
{172}{HROLD23}{Не знаю. Здесь он больше не появлялся... А я в пустыню больше ни ногой, так что... В общем, с тех пор я его не видел.}
{173}{}{Что стало с тобой и Греем?}
{174}{HROLD24}{Мы нашли главную лабораторию или что-то подобное. Вот тогда-то все и случилось.}
{175}{}{Что?}
{176}{HROLD25}{Нас сбил с ног робот-кран. Последнее, что помню - как Грей летел в какой-то чан с кислотой. Потом я отключился.}
{177}{}{Как же ты спасся?}
{178}{}{И ты больше не встречал Грея?}
{179}{hrold25a}{Ха-ха. Меня убили! [Смеется, кашляет.] Моя любимая шутка.}
{180}{}{Понимаю.}
{181}{HROLD26}{Очнулся я в пустыне, еле живой. Мне еще повезло - через пару дней меня караван подобрал. Я тогда уже начал мутировать. Привезли меня сюда, и вот с тех пор я здесь.}
{182}{}{Из-за чего ты мутировал?}
{183}{}{Вот это история! Спасибо.}
{184}{hrold26a}{Тебе спасибо, что слушаешь старика.}
{185}{}{И что, это был сокращенный вариант?}
{186}{hrold26a}{Тебе спасибо, что слушаешь старика.}
{187}{hrold26b}{По моим меркам - да.}
{188}{HROLD27}{Не тупи! Я же сказал, мы с ним больше не виделись!}
{189}{}{Как же ты спасся?}
{190}{HROLD28}{Не знаю. Но все это началось после похода на базу.}
{191}{}{Может, это из-за радиации?}
{192}{}{Да уж, не повезло тебе. Спасибо за историю!}
{193}{HROLD29}{Я-то откуда знаю? Вот Грей бы разобрался, если бы был жив. [Вздыхает.] В общем, так все и было.}
{194}{}{Спасибо за историю.}
{195}{HROLD30}{Лет сто. А может, и все двести.}
{196}{}{Что?}
{197}{HROLD31}{Да, я старый и беспомощный, и так живу уже много лет.}
{198}{}{Чем ты занимался до того, как мутировал?}
{199}{HROLD32}{Когда-то я был нормальным. Однажды попытался узнать, откуда берутся мутанты, а вышло так, что мутировал сам.}
{200}{}{Что случилось?}
{201}{HROLD33}{Все это уже в прошлом. Там ему и место.}
{202}{}{Прошу, расскажи, что случилось. Мне нужно это знать.}
{203}{}{Прощайся с жизнью.}
{204}{HROLD34}{Ну ладно, раз ты так хочешь... Надеюсь, это не очень больно.}
{205}{}{Спасибо.}
{206}{HROLD35}{Было чертовски больно, даже сейчас все болит. Ладно, удачи тебе!}
{207}{HROLD36}{Город называется Хабом, а его жителей зовут хабберами. Понятно? [кашляет] Ох... Спасибо за помощь. И удачи! Думаю, она тебе понадобится.}
{208}{HROLD37}{Ты ничем не лучше остальных. [сипло кашляет]}
{209}{HROLD38}{И на том спасибо. [кашляет]}
{210}{HROLD39}{Слушай, выручи меня, а?}
{211}{}{Держи 25 крышек.}
{212}{}{Возьми 5 крышек.}
{213}{}{Отстань.}
{214}{}{Чего?}
{215}{HROLD40}{О, спасибо! Если честно, я сначала подумал: от тебя добра не жди... [кашляет]}
{216}{}{С чего вдруг?}
{217}{}{???Нет, это не я.}
{218}{HROLD41}{Привет! Опять ты.}
{219}{}{Возьми двадцатку, если деньги нужны.}
{220}{}{Привет.}
{221}{}{А?}
{222}{hrold42}{Шутишь надо мной, да?}
{223}{HROLD43}{Чем могу помочь?}
{224}{}{Знаешь какие-нибудь интересные новости?}
{225}{}{Мне нужно узнать про Когтя Смерти. Что тебе о нем известно?}
{226}{}{Расскажи о себе.}
{227}{}{Нет.}
{228}{hrold43a}{Рассказать тебе? Ладно...}
{229}{HROLD44}{Ох, спасибо. Надеюсь, это тебя не слишком напрягло. [кашляет]}
{230}{HROLD45}{Коготь Смерти... Ох, это просто кошмар. Зачем тебе о нем знать?}
{231}{}{Собираюсь прикончить эту тварь.}
{232}{}{Хочу знать, что делать, если наткнусь на него.}
{233}{HROLD47}{Ладно. Ростом Коготь Смерти выше человека. У него есть шипы и когти, они пробивают любую броню. И он мало того что здоровый как черт, так еще и очень быстрый.}
{234}{}{У него есть слабые места?}
{235}{HROLD49}{Говорят, лучше бить его в голову. Я бы целился в глаза. Тут, правда, есть одна сложность...}
{236}{}{Какая сложность?}
{237}{HROLD50}{Нельзя на него смотреть! Говорят, что Коготь Смерти гипнотизирует взглядом. А потом убивает одним махом!}
{238}{}{Отлично, спасибо.}
{239}{HROLD51}{Удачи... Она тебе понадобится.}
{240}{}{Может быть.}
{241}{HROLD52}{Ты не хочешь знать о Когте Смерти, а я не хочу тебе рассказывать.}
{242}{HROLD53}{Говорят, люди Декера держат в Старом городе кого-то из Братства Стали.}
{243}{}{Спасибо.}
{244}{HROLD54}{Хоть я не особо в это верю, но ходит слух, что армия мутантов уже в пути. [кашляет]}
{245}{}{Спасибо.}
{246}{HROLD55}{Оставь меня в покое. [кашляет]}
{247}{}{Я хочу с тобой поговорить.}
{248}{}{Деньги нужны?}
{249}{HROLD56}{А я не хочу с тобой говорить. Уходи!}
{250}{HROLD57}{Не нужны мне твои деньги. Уходи. [кашляет]}
{251}{hrold200}{Поторговать я люблю, только вот предложить мне нечего. [кашляет]}
{252}{hrold201}{Хочу вздремнуть. Я устал.}
{253}{hrold202}{Говорят, тебе человека убить - раз плюнуть. [кашляет] Будь поосторожнее.}
{254}{hrold203}{Хм... Декер тебя ищет. Хочет поговорить. [кашляет]}
{255}{hrold204}{Эти лохмотья да свобода передвижения - вот и все мое имущество. Причем свобода еще под вопросом...}
{256}{hrold300}{Умнейший парень, доктор и философ. Он вел мою последнюю экспедицию.}
{257}{hrold301}{Кто-кто? Это не сексопатолог, случайно? Я бы хотел с ним пообщаться, хе-хе.}
{258}{hrold302}{Мутанты. Неважно, как они сами себя называют.}
{259}{hrold303}{Он главный в гильдии воров. Считает себя Робин Гудом. [кашляет] Вообще, он нормальный парень.}
{260}{hrold304}{Религия приходит и уходит. Надеюсь, и эта скоро уйдет.}
{261}{hrold305}{Да, я жил в Убежище... Много людей, мало еды и питья. Ты-то, наверное, ничего об этом не знаешь, а?}
{262}{hrold306}{Ужасно. Мир тогда просто сошел с ума. Это было давно, но я никогда этого не забуду.}
{263}{hrold307}{[Кашляет.] Беда. Это просто беда.}
{264}{hrold400}{Как я уже говорил...}
{265}{}{Ничем, спасибо.}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{266}{HROLD0}{Подбрось мелочишки, а? Пожалей бедного старого мутанта! [кашляет]}
{267}{HROLD0}{Подбрось мелочишки, а? Пожалей бедного старого мутанта! [кашляет]}
{268}{HROLD2}{О, спасибо за щедрость! Знаешь, если бы я мог, я бы уже расплакался.}
{269}{HROLD2}{О, спасибо за щедрость! Знаешь, если бы я мог, я бы уже расплакался.}
{270}{HROLD35}{Было чертовски больно, даже сейчас все болит. Ладно, удачи тебе!}
{271}{HROLD35}{Было чертовски больно, даже сейчас все болит. Ладно, удачи тебе!}
{272}{HROLD39}{Слушай, выручи меня, а?}
{273}{HROLD39}{Слушай, выручи меня, а?}

#
# Harold's Tell-Me-Abouts
#


{1000}{}{Ричард}
{1001}{}{Создатель}
{1002}{}{Гули}
{1003}{}{Локсли}
{1004}{}{Собор}
{1005}{}{Убежище}
{1006}{}{Война}
{1007}{}{Декер}
{1008}{}{Грей}

{1100}{hrold300}{Умнейший парень, доктор и философ. Он вел мою последнюю экспедицию.}
{1101}{hrold301}{Кто-кто? Это не сексопатолог, случайно? Я бы хотел с ним пообщаться, хе-хе.}
{1102}{hrold302}{Мутанты. Неважно, как они сами себя называют.}
{1103}{hrold303}{Он главный в гильдии воров. Считает себя Робин Гудом. [кашляет] Вообще, он нормальный парень.}
{1104}{hrold304}{Религия приходит и уходит. Надеюсь, и эта скоро уйдет.}
{1105}{hrold305}{Да, я жил в Убежище... Много людей, мало еды и питья. Ты-то, наверное, ничего об этом не знаешь, а?}
{1106}{hrold306}{Ужасно. Мир тогда просто сошел с ума. Это было давно, но я никогда этого не забуду.}
{1107}{hrold307}{[Кашляет.] Беда. Это просто беда.}
{1108}{hrold300}{Умнейший парень, доктор и философ. Он вел мою последнюю экспедицию.}
