{100}{}{Вы видите перед собой стол с низкими ставками. Ставка $40.}
{101}{}{Вам выпало 7. Вы выиграли!!}
{102}{}{Вам выпали 'глаза змеи'. Вы проиграли.}
{103}{}{Вы бросили кости }
{104}{}{! Вы выиграли!!}
{105}{}{Вы бросили кости }
{106}{}{. Вы проиграли.}
{107}{}{Вы бросили кости }
{108}{}{ не ваша комбинация. Вы проиграли.}
{109}{}{Это ваша комбинация. Вы выиграли.}
{110}{}{Вы бросили кости }
{111}{}{. Это ваша комбинация. Кидайте снова.}
{112}{}{Вы получаете 70 очков опыта за убийство крупье.}
