# Chris Avellone is a male bounty hunter. He has an abrupt attitude and is serious about
# his money. He does not like child killers (which is the only way the player will meet him).

{100}{}{Вы видите здорового охотника за головами. На значке у него написано: 'Я - Кристофер, ты - мясо.'}
# Bounty Hunter is considered Male term

{101}{}{Чего ты хочешь?}
{102}{}{Пончик.}
{103}{}{Ты что здесь делаешь?}
{104}{}{Просто смотрю тут.}
{105}{}{Ничего.}
{106}{}{Мы тут умников не жалуем. Отвали.}
# Alternate for "Buzz off" could be "Get lost" or "Get out of here"

{107}{}{Шутка не смешная даже в первый раз. Ты сейчас узнаешь, почему меня считают самым ужасным охотником за головами в пустоши. И мне даже не надо будет платы за это.}
{108}{}{Не твое дело.}
{109}{}{Иди лучше в другом месте людей доставать.}
# Alternate for "poke around" could be "Look around"

{110}{}{А ты в курсе, что за твою голову назначена награда в 1500 крышек за убийство детей? Пришло время ее получить!}
# 1500 caps is equivalant to 1500 dollars. Children is considered male plural

{1000}{}{Адитум}
{1001}{}{Последователи}
{1002}{}{Собор}
{1003}{}{Потрошители}
{1004}{}{Клинки}
{1005}{}{Ружье}
{1006}{}{Хаб}
{1007}{}{Джанктаун}
{1008}{}{Вода}
{1009}{}{Николь}
{1010}{}{Могильник}
{1011}{}{Оружейники}
{1012}{}{Чип}

{1100}{}{Небольшой город к югу отсюда. Иногда здесь появляются люди оттуда.}
{1101}{}{Это дурачки помешанные на мире, живут рядом.}
{1102}{}{Странная секта, обитают к югу от святилища и остальной части могильника. Николь говорит, что они там что-то задумали.}
{1103}{}{Крайне жестокая банда на западе.}
{1104}{}{Банда на востоке. Они используют виброножи.}
{1105}{}{Банда из Хаба, торгуют оружием. Они на севере отсюда.}
{1106}{}{Хаб это большой город торговцев и деловых районов. Находится на востоке.}
{1107}{}{Джанктаун - маленький город к северу от Хаба.}
{1108}{}{С этим я вам ничем не могу помочь.}
{1109}{}{Она лидер последователей.}
{1110}{}{Это место - Могильник Ангела, то что осталось от древнего города Лос-Анджелес.}
{1111}{}{Банда из Хаба, торгуют оружием. Они на севере отсюда.}
{1112}{}{С этим я вам ничем не могу помочь.}
