{100}{}{Вы видите паладина.}
{101}{}{Извини, у нас тревога. Я не могу сейчас говорить.}
{102}{}{Ты видишь что-нибудь?}
{103}{}{Эти мутанты заплатят за все, что сделали.}
{104}{}{Не беспокойся, все под контролем.}
{105}{}{Я бы на твоем месте, послушник, не стал бы тут оставаться. Здесь скоро будет пролито еще немало крови.}
{106}{}{Ты за нами смотри, послушник.}
{107}{}{Я бы на твоем месте не стал бы тут оставаться. Здесь скоро будет пролито еще немало крови.}
{108}{}{Ты за нами смотри. Тут неспокойно.}
{109}{}{Уходи.}
{110}{}{Не отвлекай меня. У нас тревога.}
{111}{}{Тихо.}
{112}{}{Не трать мое время, послушник.}
{113}{}{Захлопни варежку.}
{114}{}{Отвали, пока тут снова кровь не полилась.}
{115}{}{Мир должен быть очищен от этой отвратительной мрази.}
{116}{}{Что это было?}
{117}{}{Ноги просто отваливаются.}
{118}{}{Они заплатят за это...}
{119}{}{Пусть только еще раз попробуют.}
{120}{}{Что за... А, нет, ничего.}
{121}{}{Будь готов!}
{200}{}{Боб, какая у тебя должность?}
{201}{}{Все чисто.}
{202}{}{Не думаю, что они вернутся.}
{203}{}{Не стоит на это рассчитывать.}
{204}{}{Мы получили ответ от разведчиков?}
{205}{}{Пока нет.}
{206}{}{Разведчики сообщают, что все чисто.}
{207}{}{Хорошо.}
{208}{}{Так над чем ты сегодня утром работал, Рэй?}
{209}{}{Я просто пытался увеличить дальность плазменного ружья.}
{210}{}{Ты видел гатлинг-лазер?}
{211}{}{Да, я помогал при создании первого прототипа.}
{212}{}{Хорош болтать!}
{213}{}{Так точно, виноват.}

