{100}{}{Вы видите Дженифер.}
{101}{}{Вы видите паладина.}
{102}{}{Прости, брат. Но ты должен убрать оружие, находясь в Братстве. Мы здесь все друзья, но ты же знаешь, времена сейчас тяжелые.}
{103}{}{Некоторые члены Братства могут обидеться, если незнакомец... в смысле, новый послушник подойдет к ним с оружием.}
{104}{}{Добрый день, послушник. Чем я могу быть полезна?}
{105}{}{Здравствуй, сестра. Приятно видеть, что в этой организации есть и женщины на таких должностях. Я и не знала, чего ожидать от такого названия - Братство.}
{106}{}{Вау, какие ножки. Классно выглядишь! Когда за тобой заскочить вечерком?}
{107}{}{Уууууга!}
{108}{}{Не подскажешь ли, где мне найти Старейшину?}
{109}{}{Кто здесь главный в этой дыре?}
{110}{}{А где этот парень - Старейшина?}
{111}{}{Грук!}
{112}{}{Старейшина Максон сейчас на четвертом этаже. Спускайтесь на лифте на четвертый этаж, там поищите его либо в Зале совета, либо в комнатах Старейшин.}
{113}{}{Можешь там у охранников уточнить, где он именно сейчас.}
{114}{}{Спасибо.}
{115}{}{Где можно найти оружие получше?}
{116}{}{Поговори с Талусом. Может быть он тебе поможет, или хотя бы подскажет, к кому тебе следует обратиться.}
{117}{}{Днем Талус обычно в тренировочном зале. Знаешь, где это?}
{118}{}{Да, знаю. Спасибо.}
{119}{}{Нет.}
{120}{}{Конечно знаю!}
{121}{}{Тренировочный зал сразу за углом. Иди по коридору, затем налево, потом через дверь, и в конце коридора будет дверь справа. Вот там.}
{122}{}{Спасибо, ты очень помогла мне. Спасибо большое. Надеюсь, мы еще встретимся скоро. Счастливо.}
{123}{}{Тренировочный зал? Думаешь я тоже могу там тренироваться? Я же ведь уже член Братства, так?}
{124}{}{Спасибо за помощь, сестра. Приятно видеть, что в этой организации есть и женщины на таких должностях. Я и не знала, чего ожидать от такого названия - Братство.}
{125}{}{Спасибо, моя сладкая. Знаешь, ты классно выглядишь. Как ты смотришь на то, чтобы вечерком встретиться и показать друг другу свое "оборудование"? Во сколько ты заканчиваешь?}
{126}{}{А, вот где. Окей, пока.}
{127}{}{Прости? Что-нибудь не так?}
{128}{}{Мук люг?}
{129}{}{Извини, боюсь, я не смогу тебе помочь. Думаю, тебе стоит сходить к доктору. Она на втором уровне.}
{130}{}{Конечно есть. Двое из пяти Старейшин - женщины, наш главный писарь - женщина, и мы даже рады, что и на других должностях у нас немало женщин.}
{131}{}{Женщин Братства мы также называем братьями. Мы не зовем женщин сестрами. Это же Братство Стали, в конце концов, а не Братство-Сестринство.}
{132}{}{А вам не кажется, что название Братство подразумевает именно то, что оно должно состоять исключительно из мужчин?}
{133}{}{Но почему же тогда вы называете это Братством?}
{134}{}{Ну, мне просто показалось это странным.}
{135}{}{Я не знаю этого. Таково было наше имя всю мою жизнь. Несомненно, для этого есть веская причина.}
{136}{}{Наверное, ты права.}
{137}{}{Ну, все равно, мне это кажется немного странным.}
{138}{}{Это странно. Я никогда особо об этом не задумывалась. Мы были Братством Стали сколько я себя помню. У наших предков наверняка были причины назвать его именно так.}
{139}{}{Но это же не значит, что не может быть никаких изменений.}
{140}{}{Да, возможно ты права.}
{141}{}{Так есть еще что-нибудь, чем я могу помочь?}
{142}{}{Да, где я могу найти Старейшину?}
{143}{}{Где я могу достать оружие получше?}
{144}{}{Нет, это все. Пока.}
{145}{}{Нет, мы очень строго соблюдаем традиции. Не думаю, что мы когда-либо поменяем название. Меня совсем не беспокоит, что ко мне обращаются как к Брату. Хотя это, конечно, любопытно.}
{146}{}{Я думаю, стоит поговорить с Врии. Возможно, она сможет пролить свет на то, почему наши предки решили назвать нас Братством Стали.}
{147}{}{А кто такая Врии? Одна из старейшин?}
{148}{}{Врии - наш главный писарь. Она именно та, с кем тебе стоит поговорить, если у тебя есть какие-либо технические вопросы. Но не беспокой ее только во время ее ночных медитаций.}
{149}{}{Она практически всегда у себя в комнате, в которой также стоит центральный компьютер. Это на третьем этаже.}
{150}{}{Дыра? Как ты смеешь так говорить о Братстве. Ты теперь член нашего ордена, и должен гордиться тем, что состоишь в Братстве Стали.}
{151}{}{Гордиться? Почему это? Вы же просто кучка тупоголовых роботов, которые прячутся от реального мира. Тут нечем гордиться.}
{152}{}{Простите меня. Меня иногда слегка заносит.}
{153}{}{Да, точно.}
{154}{}{Да, я думаю, это со всеми случается.}
{155}{}{Так кто здесь главный?}
{156}{}{Да. Ну, мне пора.}
{157}{}{Старейшина Максон. Он на четвертом этаже.}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Знаешь, ты симпатичный... но думаю, не стоит. Мне кажется, что это не очень хорошая идея связываться с посторонними, в любом случае. Хотя ты и вправду симпатичный, и даже в чем-то привлекательный. }
{164}{}{Не знаю, из-за того ли это, что ты посторонний, или из-за того, что ты... начисто лишен чувства такта? Так что, "дорогой мой", я могу тебе еще чем-нибудь помочь?}
{165}{}{Да, э-э, наверно. Э-э, кто здесь главный?}
{166}{}{Э-э, окей... эмм. Как у вас с оружием? Где его можно достать?}
{167}{}{Фырк!}
{168}{}{Нет.}
{169}{}{Это... очень смешно. Надеюсь, ты шутишь, да? Вообще-то... не отвечай. Думаю, мне не стоит это знать.}
{170}{}{Да, ОЧЕНЬ смешно. Почти так же смешно, как твоя рожа!}
{171}{}{Спасибо большое. Это именно-то что мне нужно было.}
{172}{}{Пойду я отсюда.}
{173}{}{Извини, просто у посторонних всегда такая странная манера говорить с людьми. Я могу чем-нибудь помочь?}
{174}{}{Ну, я думаю, что мне стоит поговорить с этим Старейшиной. Где он?}
{175}{}{Я бы хотел подыскать себе оружие получше. С кем я могу поговорить?}
{176}{}{Нет.}
{177}{}{Ты что, серьезно? В жизни не слышала более глупой фразы!}
{178}{}{Нда? Ну, я особо гулять не хожу. Понял?}
{179}{}{Уйди с глаз моих, ведро с ушами!}
{180}{}{Фырк!}
{181}{}{В общем, да, ты теперь член Братства, но Старейшины пока приостановили тренировки новых послушников.}
{182}{}{Почему?}
{183}{}{Ну, это просто очень КРУТО! И какого черта я вступил в ваш дурацкий орден? Где тут выход?!}
{184}{}{Ходят слухи о некой армии. Думаю, Старейшины хотят сконцентрировать все силы на подготовке тех, кто уже далеко продвинулся, чтобы иметь преимущество, если нам действительно предстоит большая битва.}
{185}{}{Мы придерживаемся веры в то, что лучше превосходно обучить нескольких бойцов, чем дать посредственное обучение толпе новичков. Спасение жизней - одна из наших основных целей.}
{186}{}{Достаточной тренировкой для тебя было бы уже только наблюдать за тренирующимися. Брат Томас лучший тренер из всех в Братстве.}
{187}{}{Ну, я должен работать за пределами Братства, так? Мир там весьма враждебен, и скорее всего, мне придется каждую минуту быть на линии фронта. Я в этом не участвую. Вы не думаете, что мне все-таки нужно дать несколько тренировок, если мне это нужно? Или вы только "говорите", что ваша основная цель "спасать" жизни?}
{188}{}{Спасибо за предложение, пойду посмотрю.}
{189}{}{Вы просто толпа придурков.}
{190}{}{Не подскажешь, где можно Максона найти?}
{191}{}{Ну, я только говорю то, что мне сказали говорить. Поговори с Томасом или Талусом, они могут сделать для тебя исключение.}
{192}{}{О'кей, спасибо.}
{193}{}{Лучше бы им сделать. Я уже достаточно для вас тут попрыгал.}
{194}{}{Так не скажешь ли, где Максон?}
{195}{}{О, дорогой. Когда у нас свадьба?}
{196}{}{Ты выглядишь прекрасно, как и всегда.}
{197}{}{Поцелуй меня.}
{198}{}{Мне так было грустно без тебя.}
{199}{}{Я подожду тебя.}
{200}{}{Я думаю о тебе весь день.}
{201}{}{Ты такой симпатичный, когда так на меня смотришь.}
{202}{}{Не пугай меня так. Я думала, что больше тебя никогда не увижу.}
{203}{}{Ты не пришел прошлой ночью.}
{204}{}{Сколько времени прошло с тех пор, как я тебя видела в последний раз? Кажется, как будто прошла целая вечность.}
{205}{}{Я так по тебе скучала.}
{206}{}{Идем в постель, дорогой.}
{207}{}{Мы можем пожениться утром.}
{208}{}{Я считаю, что нам нужно завести пятерых детишек.}
{209}{}{Где ты хочешь провести медовый месяц? Говорят, у Чад Собора замечательное место.}
{210}{}{Мои родители очень хотят с тобой познакомиться.}
{211}{}{О, привет. Надеюсь, у тебя все хорошо. Ты поговорил с Врии?}
{212}{}{Привет, брат.}
{213}{}{.}
{214}{}{Будь осторожен, если пойдешь на север. Ни один из наших разведчиков так и не вернулся оттуда.}
{215}{}{Брат }
{216}{}{, приятно снова тебя видеть.}
{217}{}{Ты говорил с Ромбусом? Он - Главный рыцарь. Он вот там, в той комнате.}
{218}{}{У меня нет времени на разговоры. Я занята.}
{219}{}{Извини, я не в настроении. Не люблю говорить с грубыми людьми.}
{220}{}{Отстань от меня.}
{221}{}{Что? Иди доставай кого-нибудь другого?}
{222}{}{Уходи.}
{223}{}{Я не хочу с тобой разговаривать.}
{224}{}{Послушник, возвращайся к своим занятиям.}
{225}{}{У меня нет времени, послушник.}
{226}{}{Иди сюда, красавчик!}
{227}{}{Дорогой, сюда!}
{228}{}{Я скучала по тебе.}
{229}{}{Я уже приготовила детскую, дорогой.}
{230}{}{Привет, дорогая.}
{231}{}{Я тебя вижу.}
{232}{}{Ты должен познакомиться с моими родителями.}
{233}{}{Юу-хуу!}
{234}{}{Иди сюда, мой маленький.}
{235}{}{Ты меня дразнишь?}
{236}{}{Играешь в неприступность, правда?}
{237}{}{Сюда, сладенький!}
{238}{}{Привет, дорогая!}
{239}{}{Вот ты где. Я уже начала беспокоиться.}
{240}{}{Иди сюда и поцелуй меня, мой прекрасный.}
{241}{}{Пойдем, дорогая.}

#Женский вариант, Майкл, 15.11.2006 15:11
#{10105}{}{Здравствуй, сестра. Приятно видеть, что в этой организации есть и женщины на таких должностях. Я и не знала, чего ожидать от такого названия - Братство.}
#{10124}{}{Спасибо за помощь, сестра. Приятно видеть, что в этой организации есть и женщины на таких должностях. Я и не знала, чего ожидать от такого названия - Братство.}
{10150}{}{Дыра? Как ты смеешь так говорить о Братстве. Ты теперь член нашего ордена, и должна гордиться тем, что состоишь в Братстве Стали.}
{10175}{}{Я бы хотела подыскать себе оружие получше. С кем я могу поговорить?}
{10183}{}{Ну, это просто очень КРУТО! И какого черта я вступила в ваш дурацкий орден? Где тут выход?!}
{10214}{}{Будь осторожна, если пойдешь на север. Ни один из наших разведчиков так и не вернулся оттуда.}


#Женский вариант, Майкл, 19.10.2007 13:59
{10102}{}{Прости, брат. Но ты должна убрать оружие, находясь в Братстве. Мы здесь все друзья, но ты же знаешь, времена сейчас тяжелые.}
{10187}{}{Ну, я должна работать за пределами Братства, так? Мир там весьма враждебен, и скорее всего, мне придется каждую минуту быть на линии фронта. Я в этом не участвую. Вы не думаете, что мне все-таки нужно дать несколько тренировок, если мне это нужно? Или вы только "говорите", что ваша основная цель "спасать" жизни?}
{10193}{}{Лучше бы им сделать. Я уже достаточно для вас тут попрыгала.}
{10217}{}{Ты говорила с Ромбусом? Он - Главный рыцарь. Он вот там, в той комнате.}
{10211}{}{О, привет. Надеюсь, у тебя все хорошо. Ты поговорила с Врии?}
{10206}{}{Идем в постель, дорогая.}

