{100}{}{Вы видите молодую стройную женщину. У нее грязное лицо и темная одежда.}
{101}{}{Вы видите воровку Катю.}
{102}{}{Ты не из этих мест. Кто ты?}

# TRANSLATION NOTE
# The player-character's name is inserted between lines 103 and 104 by the code.

{103}{}{Меня зовут }
{104}{}{.}
{105}{}{Я путешественник.}
{106}{}{То же я мог бы спросить у тебя.}
{107}{}{А что, позволь спросить, ты делаешь в Могильнике?}
{108}{}{Ты задаешь слишком много вопросов.}
{109}{}{Сначала скажи мне, кто ты.}
{110}{}{Я просто разведчик.}
{111}{}{Мне нужен водяной чип для моего убежища}
{112}{}{Учись здесь быть осторожным. Так что ты здесь делаешь?}
{113}{}{Хорошо, ты прав. Меня зовут Катя. А какое тебе дело?}
{114}{}{А что так враждебно?}
{115}{}{Слушай, если будешь так грубить, тогда лучше в другой раз поговорим.}
{116}{}{Мне нужны кое-какие сведения. Можешь помочь?}
{117}{}{Может быть, но сейчас ты на моей территории, а не наоборот. Так что или мирись, или заткнись.}
{118}{}{Неважно, я просто путешествую. Мне нужно кое-что узнать.}
{119}{}{Чип очистки воды? Не знаю ничего такого, извини. У нас в Могильнике такие технологии нечасто встречаются, вот разве что Майлз над чем-то таким работает.}
{120}{}{Ладно, спасибо и на этом.}
{121}{}{Майлз? А где его можно увидеть, может он поможет мне?}
{122}{}{А можешь тогда рассказать про могильники?}
{123}{}{Хм, "просто путешествую". Я уже такое слышала. Никто не приходит в Могильник кроме этих торговцев из Хаба да людей, которые ищут быстрой смерти от рук бандитов. Зачем ты на самом деле сюда явился?}
{124}{}{Ты права. Мне нужен чип очистки воды.}
{125}{}{Мне не нужно тебе что-либо объяснять.}
{126}{}{Точно. Но мне в таком случае тоже.}
{127}{}{Может быть. Ты определенно не из тех любителей нож в человека всадить. Что же тебе надо?}
{128}{}{Мне нужен чип очистки воды.}
{129}{}{Мне нужны сведения о Могильнике.}
{130}{}{Меня интересует местность вокруг этого города.}
{131}{}{Что ты знаешь про Клинков?}
{132}{}{Что ты знаешь про Потрошителей?}
{133}{}{Что ты знаешь про Оружейников?}
{134}{}{Расскажи мне про Последователей?}
{135}{}{Что ты знаешь про Святилище?}
{136}{}{Ладно, приятно было поболтать. Мне пора.}
{137}{}{Майлз живет в Святилище. Он ученый, в основном работает с химией. Если кто-нибудь здесь мог бы выцыганить где-нибудь водяной чип или сделать такой же, это был бы он.}
{138}{}{Спасибо большое.}
{139}{}{Я выросла в Святилище. Для меня, правда, там скучновато. Огороженный самодостаточный город в южной части Могильника, но не так далеко на юге, как Собор. Мы торгуем иногда с Хабом.}
{140}{}{Я с ними общалась раньше. Для бандитов они не такие уж плохие ребята. Они укрываются в старом клубе, есть несколько сторожевых постов. Если будешь вести себя осторожно, с некоторыми из них можно даже поговорить.}
{141}{}{Потрошители просто свирепые убийцы. У них в природе заложено наслаждение от пыток и убийств. Я от них держусь подальше и тебе советую. Они на самом деле закладывают гребаные мины вокруг своей крепости.}
{142}{}{Оружейники раньше были настоящей бандой, но что-то они размякли. Они начинали с того, что торговали оружием, которое забирали у своих жертв или покупали в Хабе. Поскольку поодиночке люди отсюда в Хаб не ездят, торговля идет хорошо, несмотря на высокие цены.}
{143}{}{Последователи Апокалипсиса - это группа проповедников мира. Они живут в большой библиотеке почти в центре Могильника. Не могу сказать, почему их до сих пор всех не перебили. Бойцы из них никудышные, и понятие о реальном мире у них отсутствует. Зато они вежливые и образованные.}
{144}{}{Могильник достаточно враждебное место. У меня никогда не было возможности уехать отсюда, будь она, я бы ей воспользовалась. Так, посмотрим... еще есть Собор к югу отсюда. Там у них какая-то секта, так что я от них держусь подальше. Там что-то дурное у них творится. А еще я слышала про Хаб, центр торговли Хаб. Караваны иногда приходят оттуда, но я там ни разу не была.}
{145}{}{Я и сам тут надолго не собираюсь задерживаться.}
{146}{}{Спасибо за рассказ.}
{147}{}{А можешь еще что-нибудь рассказать?}
{148}{}{Я не шучу. Если ищешь попутчика, я с тобой. Все лучше, чем провести остаток жизни в этой чертовой дыре, так?}
{149}{}{С удовольствием возьму тебя с собой, правда, не думаю, что в пустыне гораздо интересней.}
{150}{}{Не стоит. Но все равно спасибо.}
{151}{}{Можно я тебе сначала задам еще несколько вопросов?}
{152}{}{Здесь орудуют три банды - Клинки, Потрошители и Оружейники. Кроме того, живут здесь Последователи и мы - в Святилище.}
{153}{}{Понятно, похоже, нам придется скоро некоторым зад надрать!}
{154}{}{Послушай, 90% населения города попадают в одну из трех категорий - насильники, убийцы, воры. Я - воровка, а ты мне кажешься очень вежливым, что заставляет меня задуматься, понимаешь? Можешь назвать это инстинктом самосохранения.}
{155}{}{Извини, что наступил тебе на больную мозоль, в таком случае. Я пожалуй буду валить отсюда.}
{156}{}{Ну, могу ли я задать хотя бы парочку вопросов?}
{157}{}{Я не местная, поэтому толку мало будет.}
{158}{}{Ладно, только быстрее.}
{159}{}{Нда. Наверно мне трудно будет спорить с такой логикой. Так чо те надо?}
{160}{}{Можно задать тебе вопрос?}
{161}{}{Я ищу чип очистки воды. Можешь подсказать что-нибудь?}
{162}{}{Все равно, спасибо. Мне пора.}
{163}{}{Что надо?}
{164}{}{Можешь попробовать открыть этот замок?}
{165}{}{Можешь взглянуть на эту ловушку?}
{166}{}{Что посоветуешь?}
{167}{}{Спасибо за помощь. Можешь идти.}
{168}{}{Ничего. Но будь начеку.}
{169}{}{Снова ты? Теперь-то зачем вернулся?}
{170}{}{Хотел просто сказать привет.}
{171}{}{У меня еще несколько вопросов, если у тебя время есть.}
{172}{}{Он открыт.}
{173}{}{Что-то необычное с этим шкафом у восточной стены. Похоже, в нем что-то есть.}
{174}{}{Убери оружие.}
{175}{}{Ненавижу собак.}
{176}{}{Еда вкусно пахнет.}
{177}{}{Какие боевые навыки у тебя есть?}
{178}{}{Я научилась хорошо драться еще когда жила в Могильнике. Хорошо управляюсь с ножами и автоматами. Отлично метаю ножи, конечно же, любимое дело.}
{179}{}{Хорошо, хотя я без ножа себя не очень уютно чувствую.}
{180}{}{Вы получили 200 очков опыта за то, что подобрали Катю, воровку.}
{181}{}{Чего тебе надо?}
{182}{}{Я передумал. Мне все-таки пригодится твоя помощь.}
{183}{}{Ничего, извини.}
{184}{}{Я уже просто начинаю ненавидеть это место.}
{185}{}{Ух ты. Я бы сейчас с удовольствием съела горячую сосиску на такой длиннющей палочке.}
{186}{}{Ох, ух. Меня, кажется, сейчас стошнит.}
{187}{}{Эй, смотри, похоже эта стена с облупившейся штукатуркой может двигаться.}
{188}{}{Берегись Когтей Смерти!}
{189}{}{Хаба Хаба!}
{190}{}{Уходите!}
{191}{}{Прости, но я просто тебя не понимаю. До свидания.}

#
# Katja tell-me-abouts
#

{980}{}{Я ничего об этом не знаю.}
{981}{}{Не слышала о таком.}
{982}{}{Нет, не слышала о таком.}

{1000}{}{Вода}
{1001}{}{Могильник}
{1002}{}{Война}
{1003}{}{Адитум}
{1004}{}{Последователи}
{1005}{}{Собор}
{1006}{}{Чип}
{1007}{}{Гарл}
{1008}{}{Создатель}
{1009}{}{Единение}
{1010}{}{Сет}
{1011}{}{Водораздел}
{1012}{}{Некрополь}
{1013}{}{Зал}
{1014}{}{Библиотека}
{1015}{}{Смотритель}
{1016}{}{Медик}
{1017}{}{Лечение}
{1018}{}{Убежище}
{1019}{}{Убежище-13}
{1020}{}{Убежище 13}
{1021}{}{Киллиан}
{1022}{}{Гизмо}
{1023}{}{Джанктаун}
{1024}{}{Шэйди}
{1025}{}{Сэндс}
{1026}{}{Хаб}
{1027}{}{Казино}
{1028}{}{Магазин}
{1029}{}{Когти смерти}
{1030}{}{Исход}
{1031}{}{Послушники}
{1032}{}{Паладины}
{1033}{}{Писцы}
{1034}{}{Дети}
{1036}{}{Братство}
{1037}{}{Чаны}
{1038}{}{Военная база}
{1039}{}{База}
{1041}{}{Апокалипсис}
{1042}{}{Мутанты}
{1043}{}{Морфеус}
{1044}{}{Ханы}
{1045}{}{Танди}
{1046}{}{Алия}
{1047}{}{Диана}
{1048}{}{Гвен}
{1049}{}{Петрокс}
{1050}{}{Толя}
{1051}{}{Самогон}
{1052}{}{Препараты}
{1053}{}{Сет}
{1054}{}{Арадеш}
{1055}{}{Разло}
{1056}{}{Циммерман}
{1057}{}{Регуляторы}
{1058}{}{Мусорщики}
{1059}{}{Клинки}
{1060}{}{Николь}
{1061}{}{Лейтенант}
{1062}{}{Психика}
{1063}{}{Эксперименты}
{1064}{}{Полиция}
{1065}{}{Торговцы}

{1100}{}{Не знаю, где можно найти такой реликт древней технологии.}
{1101}{}{Могильник Ангела это все, что осталось от древнего города Лос-Анджелес. В основном поделенный между враждующими группировками.}
{1102}{}{Война принесла страдания и смерть всему миру. Хочу верить в то, что такое больше никогда не повторится. Но, судя по тому, что я вижу, мало надежды на человечество.}
{1103}{}{Святилище было моим домом, но люди там просто параноики и затворники. Они не смогут выжить, не отгородившись от мира полностью.}
{1104}{}{Последователи Апокалипсиса проповедуют мир и терпимость. Жаль, что их идеи ну никак не лезут в рамки этого мира.}
{1105}{}{Собор - монументальное здание к югу от святилища примерно день пешком или около того. Им владеет странная секта, которая поклоняется какому-то темному богу.}
{1106}{}{Не знаю, где можно найти такой реликт древней технологии.}
{1107}{}{Я знаю об этом не больше, чем ты.}
{1108}{}{Я знаю об этом не больше, чем ты.}
{1109}{}{Я знаю об этом не больше, чем ты.}
{1110}{}{Я знаю об этом не больше, чем ты.}
{1111}{}{Я знаю об этом не больше, чем ты.}
{1112}{}{Что, Город Мертвых? А это не миф?}
{1113}{}{Я знаю об этом не больше, чем ты.}
{1114}{}{Я знаю об этом не больше, чем ты.}
{1115}{}{Я знаю об этом не больше, чем ты.}
{1116}{}{У Последователей всегда есть медик под рукой.}
{1117}{}{Если ты будешь нуждаться в лечении, тебе стоит сходить к медику Последователей.}
{1118}{}{А разве Убежища - это были не просто большие подземные укрытия?}
{1119}{}{А разве Убежища - это были не просто большие подземные укрытия?}
{1120}{}{А разве Убежища - это были не просто большие подземные укрытия?}
{1121}{}{Я знаю об этом не больше, чем ты.}
{1122}{}{Я знаю об этом не больше, чем ты.}
{1123}{}{Эм, думаю, это маленький город на севере от Хаба.}
{1124}{}{Что-что?}
{1125}{}{Шэйди Сэндс? Никогда не слышала.}
{1126}{}{Хаб - большой торговый центр со всякими магазинами и торговцами.}
{1127}{}{Я знаю об этом не больше, чем ты.}
{1128}{}{Оружейники продают все, у них есть магазин в Святилище.}
{1129}{}{Ух! Когти Смерти есть повсюду в Могильнике. О них мне даже думать страшно. Они огромны, и имечко их им очень подходит.}
{1130}{}{Я знаю об этом не больше, чем ты.}
{1131}{}{Я знаю об этом не больше, чем ты.}
{1132}{}{Я знаю об этом не больше, чем ты.}
{1133}{}{Я знаю об этом не больше, чем ты.}
{1134}{}{Я не люблю детей.}
{1136}{}{Я слышала, что они что-то типа высокотехнологичных монахов.}
{1137}{}{Я знаю об этом не больше, чем ты.}
{1138}{}{Я знаю об этом не больше, чем ты.}
{1139}{}{Думаю, где-то должны быть остатки старой армии.}
{1141}{}{Имеешь в виду большую войну? Ух ты, а у тебя и вправду была изолированная жизнь, раз ты ничего об этом не знаешь.}
{1142}{}{Мне как-то встречалась крыса с тремя глазами. Это практически все, что я знаю о мутантах.}
{1143}{}{Я думаю он Главный Священник Собора или что-то в этом роде.}
{1144}{}{Я знаю об этом не больше, чем ты.}
{1145}{}{Я знаю об этом не больше, чем ты.}
{1146}{}{Я знаю об этом не больше, чем ты.}
{1147}{}{Я знаю об этом не больше, чем ты.}
{1148}{}{Я знаю об этом не больше, чем ты.}
{1149}{}{Я знаю об этом не больше, чем ты.}
{1150}{}{Я знаю об этом не больше, чем ты.}
{1151}{}{Нет, спасибо.}
{1152}{}{Ух, нет, я не стала бы. Как-то видела, как мой друг умер от передоза психо. Не очень весело.}
{1153}{}{Я знаю об этом не больше, чем ты.}
{1154}{}{Я знаю об этом не больше, чем ты.}
{1155}{}{Я знаю об этом не больше, чем ты.}
{1156}{}{Он мэр Святилища. Честный, но слегка нерешительный человек.}
{1157}{}{Они смотрят за Святилищем и держат его под контролем.}
{1158}{}{Я раньше работал мусорщиком. Ночью мы выбирались наружу и искали полезные вещи в руинах Могильника. Очень опасное занятие. Но мне осточертело и Святилище.}
{1159}{}{Это группа изгнанников, которые живут вне Святилища.}
{1160}{}{Она - лидер Последователей. Умная и добрая женщина.}
{1161}{}{Я знаю об этом не больше, чем ты.}
{1162}{}{У меня иногда бывает "женская интуиция", если ты об этом.}
{1163}{}{Я знаю об этом не больше, чем ты.}
{1164}{}{Я знаю об этом не больше, чем ты.}
{1165}{}{Купцы торгуют со Святилищем. Они много продают Оружейникам.}

#Женский вариант, Майкл, 23.11.2006 16:07
{10105}{}{Я путешественница.}
{10106}{}{То же я могла бы спросить у тебя.}
{10113}{}{Хорошо, ты права. Меня зовут Катя. А какое тебе дело?}
{10145}{}{Я и сама тут надолго не собираюсь задерживаться.}
{10154}{}{Послушай, 90% населения города попадают в одну из трех категорий - насильники, убийцы, воры. Я - воровка, а ты мне кажешься очень вежливой, что заставляет меня задуматься, понимаешь? Можешь назвать это инстинктом самосохранения.}
{10155}{}{Извини, что наступила тебе на больную мозоль, в таком случае. Я пожалуй буду валить отсюда.}
{10169}{}{Снова ты? Теперь-то зачем вернулась?}
{10170}{}{Хотела просто сказать привет.}
{10182}{}{Я передумала. Мне все-таки пригодится твоя помощь.}
