{100}{}{Вы видите Кери.}
{101}{}{Ты кто, черт возьми, такой? Если тебе нужна работа, говори с Деметром.}
{102}{}{Я сказал тебе, говори с моим отцом о работе, а не со мной.}
{103}{}{Так этот старый ублюдок разрешил тебе работать на нас, да? Ты наверно крутая баба. Впечатляет, но посмотрим, как ты будешь справляться. Мы выезжаем дважды в месяц - 3го и 17го. Запомнил? Мы идем по всем местным горячим точкам - Братство Стали, Джанктаун, Некрополь, и Могильник.}
{104}{}{Так этот старый ублюдок разрешил тебе работать на нас, да? Ты наверно крутой мужик. Впечатляет, но посмотрим, как ты будешь справляться. Мы выезжаем дважды в месяц - 3го и 17го. Запомнил? Мы идем по всем местным горячим точкам - Братство Стали, Джанктаун, Некрополь, и Могильник.}
{105}{}{А зарплата?}
{106}{}{Ох.}
{107}{}{Наша зарплата лучшая, 600 баксов, да, за каждую ходку, но ты не обязан участвовать в обеих. Поездка довольна тяжелая, и налетчики нападают практически всегда, или что похуже. Нам сосунки на караванах не нужны, и советую хорошенько запастись патронами.}
{108}{}{ Мы сегодня отправляемся. Интересует?}
{109}{}{ Мы едем }
{110}{}{Пусто}
{111}{}{Пусто}
{112}{}{.  Интересует?}
{113}{}{Мы все сегодня выезжаем.}
{114}{}{Мы собираемся в }
{115}{}{}
{116}{}{}
{117}{}{. Интересует?}
{118}{}{Я, так и быть, дам тебе работу, если тебя это интересует.}
{119}{}{Конечно.}
{120}{}{Нет.}
{121}{}{Думаю, интересует.}
{122}{}{Возможно.}
{123}{}{Ы.}
{124}{}{Ха, я знала, что ты струсишь! Ну, если ты осмелеешь, заходи, и может я тебе таки дам работу. Мы выезжаем 3го и 17го, можешь просто появиться в эти дни, если захочешь. Дополнительные стволы нам не помешают.}
{125}{}{Тебе просто нравится тратить мое время, так?}
{126}{}{Как знаешь. Если захочется приключений, приходи, я тебя поставлю на следующий караван.}
{127}{}{Кстати, я в курсе, что тут можно легко достать наркотики, но я не собираюсь тебя нанимать, если придешь не в себе.}
{128}{}{Сказала же, мужик, оставь наркотики.}
{129}{}{Сказала же, мать, оставь наркотики.}
{130}{}{Ну ладно... Не хотелось, конечно, говорить, но... Я кое-что слышала про тебя.  Ты так же крут лицом к лицу, как и на людях? Посмотрим (Она ведет вас за угол)}
{131}{}{(На обратном пути она сует вам несколько предметов.)}
{132}{}{Ну, ты еще довольно ДОЛГО продержишься.}
{133}{}{Ну, ты и вправду интересный человек, и очень отличаешься от большинства людей... посмотрим, что ты можешь, крутой. (Она ведет вас за угол)}
{134}{}{(На обратном пути она сует вам несколько предметов.)}
{135}{}{Ну, ты еще довольно ДОЛГО продержишься.}
{136}{}{Эй, пап, у нас тут, похоже, вор! Что скажешь в оправдание, уродина?}
{137}{}{Простите меня. Я больше не буду.}
{138}{}{Попробуй догони.}
{139}{}{Не люблю по тихому! Попробуйте меня взять!}
{140}{}{(Кивнуть в знак согласия)}
{141}{}{УУУГАБУУУГА!!!}
{142}{}{Эй, пап, эта дура не научилась с первого раза. Она пыталась что-то у меня украсть опять. Давай ее отдубасим.}
{143}{}{Эй, пап, этот придурок не научился с первого раза. Он пытался что-то у меня украсть опять. Давай его отдубасим.}
{144}{}{Ладно... Я понимаю, насколько легко можно поддаться искушению взять чужое, но... Черт, хорошо, я дам тебе шанс. Не смей здесь больше показываться, и я не стану звать полицию.  Теперь, бегом отсюда.}
{145}{}{О, мы об этом позаботимся. Правда пап?}
{146}{}{Убирайся в ад!}
{147}{}{Думаю, да.}
{148}{}{Ты труп.}
{149}{}{Я сказала, убирайся.}
{150}{}{Полиция!}
{151}{}{Прости, но мы с тобой дела больше не имеем.}
{152}{}{Работы нет, забудь.}
{153}{}{Не заставляй меня показывать свои худшие стороны.}
{154}{}{Дебил.}
{155}{}{Заманчиво, но ты не в моем вкусе.}
{156}{}{Хорошо. Как я уже сказала, платим 600 баксов. Куда ты хочешь ехать?}
{157}{}{Отлично. Следующий отправляется }
{158}{}{. Приходи тогда, я тебя запишу на караван. Как обычно, платим 600 баксов.}
{159}{}{О'кей. }
{160}{}{Извини, но я не могу ждать так долго.}
{161}{}{Мне бы тебя крюками за глаза зацепить да подвесить бы. Из-за тебя мы потеряли весь чертов караван. Прочь с глаз моих! У меня из-за этого столько дерьма будет.}
{162}{}{Мне бы тебя крюками за яйца зацепить да подвесить бы. Из-за тебя мы потеряли весь чертов караван. Прочь с глаз моих! У меня из-за этого столько дерьма будет.}
{163}{}{Братство Стали}
{164}{}{Джанктаун}
{165}{}{Некрополь}
{166}{}{Могильник}
{167}{}{Пожалуй нет. Я кое-что забыл сделать. }
{168}{}{Готовясь! Мы валим отсюда!}
{169}{}{Расскажешь, если что-нибудь интересное произойдет? А то отец заставляет меня тут вокруг склада ошиваться.}
{170}{}{Отлично! Остальные психи тоже готовы. Отправляемся.}
{171}{}{Класс. Нужно всего несколько минут, чтобы собрать всех психов.}
{172}{}{Братство Стали! Мы на месте. Ну, дальше нам не по пути.}
{173}{}{Ладно, двигай отсюда. Психи из Братства тебя уже заждались.}
{174}{}{Надеюсь, ты ничего против гор не имеешь? Потому что мы сейчас в горы направляемся.}
{175}{}{Готовность номер один! Ты поведешь нас прямо через горы!}
{176}{}{Джанктаун довольно спокойное место. Я предпочитаю более опасные маршруты.}
{177}{}{Я слышала, есть тут один доктор чокнутый. Сходи к нему. Его зовут Док Морбид.}
{178}{}{Джанктаун тут недалеко. Ты скоро вернешься.}
{179}{}{Береги свой зад. В Некрополе не самые дружелюбные люди живут.}
{180}{}{Сет - глава города. По крайней мере был, когда там была я.}
{181}{}{В этом городе полно отморозков, я бы советовала тебе двигаться дальше.}
{182}{}{В Анжелесе довольно клево. Тебе понравится. Смотри только не уходи от каравана, пока он не доедет. Это небезопасно, в смысле, для каравана.}
{183}{}{Надеюсь, у тебя будет шанс увидеть, там еще есть классная церковь - буквально несколько миль на юг. Хотя люди там долбанутые живут.}
{184}{}{Мне говорили, что Могильник раньше назывался Л. А. Не знаю, что эти инициалы значат, но, вообще, там круто.}
{185}{}{Какого черта тебе нужно?}
{186}{}{Заткнись и уйди с дороги, я сейчас не в настроении!}
{187}{}{Мне нужна другая работа.}
{188}{}{Ничего.}
{189}{}{Хмы.}
{190}{}{Ы.}
{191}{}{Ну да! Значит, ты оставил еще один караван? Тебе просто повезло, что они целыми добрались.}
{192}{}{Радоваться? Сам радуйся, что в морду еще не получил!}
{193}{}{Эй! Мне надо идти по делам, и... все такое!}
{194}{}{Послушай, ты не говорила, что мне нельзя уйти!  Они ж не посреди боя сейчас.}
{195}{}{Убирайся! Меня от тебя тошнит! Вот почему ты покинул караван! Готова спорить, ты под наркотиками!}
{196}{}{Да? Что же ты не идешь сейчас туда?! Мы тебя навсегда исключили из нашего списка.}
{197}{}{Что? Ты никогда не работал на караванах? Поверить не могу, что отец тебя нанял! Иди отсюда! Мы только профессионалов нанимаем! Поэтому мы и платим такие деньги!}
{198}{}{Ты хорошо поработал в последний раз. Не хочешь ли еще разок?}
{199}{}{Конечно.}
{200}{}{Нет.}
{201}{}{Возможно.}
{202}{}{Ы.}
{203}{}{Бу.}
{204}{}{Ты готов? Мы отправляемся сегодня.}
{205}{}{Ага!}
{206}{}{Не-а.}
{207}{}{Ыр-рва?}
{208}{}{Ты пришел на день раньше. Приходи завтра, если все еще хочешь работать. Не хочешь - не приходи, мне посрать.}
{209}{}{Эй, да ты рано пришел. Они поедут только }
{210}{}{3го}
{211}{}{17го}
{212}{}{ числа. Тогда и приходи, если тебе нужна эта чертова работа. Мне на самом деле все равно, придешь ты или нет. Но если хочешь работать, тогда и приходи.}
{213}{}{Пока нет.}
{214}{}{Пап, заткнись, а!}
{215}{}{Эй, старик, я есть хочу! Я, пожалуй, сделаю паузу!}
{216}{}{Не люблю с этими книгами работать.}
{217}{}{в январе, }
{218}{}{в феврале, }
{219}{}{в марте, }
{220}{}{в апреле, }
{221}{}{в мае, }
{222}{}{в июне, }
{223}{}{в июле, }
{224}{}{в августе, }
{225}{}{в сентябре, }
{226}{}{в октябре, }
{227}{}{в ноябре, }
{228}{}{декабре, }
{229}{}{Вы получили 3 упаковки наркотиков.}

#Женский вариант, Майкл, 24.11.2006 11:54
{10101}{}{Ты кто, черт возьми, такая? Если тебе нужна работа, говори с Деметром.}
{10107}{}{Наша зарплата лучшая, 600 баксов, да, за каждую ходку, но ты не обязана участвовать в обеих. Поездка довольна тяжелая, и налетчики нападают практически всегда, или что похуже. Нам сосунки на караванах не нужны, и советую хорошенько запастись патронами.}
{10167}{}{Пожалуй нет. Я кое-что забыла сделать. }
#{10191}{}{Ну да! Значит, ты оставила еще один караван? Тебе просто повезло, что они целыми добрались.}
#{10192}{}{Радоваться? Сама радуйся, что в морду еще не получила!}
#{10195}{}{Убирайся! Меня от тебя тошнит! Вот почему ты покинула караван! Готова спорить, ты под наркотиками!}
#{10197}{}{Что? Ты никогда не работала на караванах? Поверить не могу, что отец тебя нанял! Иди отсюда! Мы только профессионалов нанимаем! Поэтому мы и платим такие деньги!}
{10198}{}{Ты хорошо поработала в последний раз. Не хочешь ли еще разок?}
{10204}{}{Ты готова? Мы отправляемся сегодня.}
#{10208}{}{Ты пришла на день раньше. Приходи завтра, если все еще хочешь работать. Не хочешь - не приходи, мне посрать.}
{10209}{}{Эй, да ты рано пришла. Они поедут только }
