{100}{}{Вы видите Кайла.}
{101}{}{Вы видите рыцаря.}
{102}{}{А-а... Так это ты тот самый, да?}
{103}{}{Что?}
{104}{}{Ну, кто ты такой?}
{105}{}{Ничего. Этим никто не занимался со времен Древнего Ордена.}
{106}{}{Что ты тут делаешь?}
{107}{}{Что? Зачем они тогда меня сюда отправили?}
{108}{}{Было трудно, но не невозможно.}
{109}{}{Хе-хе, наверно, они просто хотели от тебя избавиться, ха. Хорошо пошутили.}
{110}{}{Нда. А скажи, что ты здесь делаешь?}
{111}{}{Единственное, ради чего я вступил - это чтобы получить силовую броню.}
{112}{}{Идите вы все подальше. Я ухожу.}
{113}{}{Я чиню всякую фигню, провожу проверки оборудования, всяким таким дерьмом занимаюсь.}
{114}{}{Ты мог бы починить водяной чип?}
{115}{}{Какую "фигню"?}
{116}{}{Мне это приятно слышать. Ну, увидимся..}
{117}{}{Силовую броню и все остальное тоже надо чинить.}
{118}{}{Где можно достать силовую броню?}
{119}{}{Я б мог те прям сейчас дать силовую броню, но у нее не хватает систолитического мотиватора. Без него она бесполезна.}
{120}{}{А где можно его достать?}
{121}{}{Ну, все равно, спасибо.}
{122}{}{Да у них их больше чем нужно на складе. Но Майкл со своими чертовыми формами говорит, что они не соответствуют спецификации. Чертовы бюрократы.}
{123}{}{Что значит "не соответствуют спецификации".}
{124}{}{Значит, если я принесу тебе систолитический мотиватор, ты его починишь?}
{125}{}{Видишь вон тот окуляр? Мне пришлось его припаять на место, и теперь он не выглядит достаточно аккуратно, чтобы он прошел инспекцию, наверное.}
{126}{}{Ты прав, выглядит дерьмово. Не хотел бы я, чтоб меня пристрелили в такой силовой броне.}
{127}{}{Катись отсюда, приятель.}
{128}{}{Эй, подожди-ка, приятель, это займет ни много ни мало пару часов. Я тебе могу инструменты дать и инструкцию, но ремонтировать будешь сам.}
{129}{}{Ладно, а кроме Майкла, где еще его можно достать?}
{130}{}{Хорошо. Я скоро вернусь.}
{131}{}{Хе, нда, ну у Ромбуса есть парочка. Хотя я не стал бы у него просить такой костюм. Только "Почетные" люди должны носить такую мощную броню. К тому же, у него какая-то неестественная привязанность к ним.}
{132}{}{Хмм. Окей, спасибо.}
{133}{}{Не думаю. Я даже не знаю, что это такое.}
{134}{}{Все равно, спасибо.}
{135}{}{Что ты за механик такой фиговый, не можешь даже водяной чип починить?}
{136}{}{Как мне достать силовую броню, не тратя на обучение сотню лет?}
{137}{}{Меня звать Кайл. Никогда раньше не видел живой миф.}
{138}{}{Что это значит?}
{139}{}{Что ты тут делаешь?}
{140}{}{Я тоже. Ладно, увидимся.}
{141}{}{Если байки Максона послушать, можно подумать что это все на девятом кругу ада было.}
{142}{}{Максон? Генерал Максон?}
{143}{}{Нет, не генерал Максон, его дед, а Роджер Максон. Слышал, ты диск принес, на котором записано то, что случилось с парнями, которые восстали против него и отправились туда чтобы добыть утраченные технологии.}
{144}{}{Да, похоже, это я. Меня зовут }
{145}{}{, а ты кто?}
{146}{}{Мне бы не хотелось об этом говорить.}
{147}{}{Да, вшивые ублюдки. Не могу поверить, что они вот так просто тебя сюда отправили.}
{148}{}{Все что они мне дали за мои усилия, так это горсть патронов!}
{149}{}{Эй, послушник, есть что-то для меня?}
{150}{}{Нет, я им сказал, что ты меня отправил, но они не дали мне ничего.}
{151}{}{Нет, я еще даже не занимался этим.}
{152}{}{Пока безуспешно.}
{153}{}{Да ладно! А я тут думал, что ты умный. Я ж сказал тебе, что у того парня были официальные формы для мозгов.}
{154}{}{Смотри, кого ты идиотом называешь.}
{155}{}{Я просто пытался выпросить это у Майкла.}
{156}{}{Что я сделаю, если Майкл мне его не дает.}
{157}{}{Уже иду.}
{158}{}{Ну... Не могу сказать, что ты не пытался. Но похоже, у тебя больше нет шансов получить ее со склада. Придется тебе поискать другой путь. Или ищи силовую броню в другом месте.}
{159}{}{OK, увидимся.}
{160}{}{А где еще ее можно откопать?}
{161}{}{Удачи!}
{162}{}{Иди отсюда, я занят.}
{163}{}{Привет, ну что, достал деталь?}
{164}{}{Да, вот она.}
{165}{}{Да, но я пока, пожалуй, придержу ее.}
{166}{}{Отлично! Давай, я сейчас ее установлю в броню.}
{167}{}{OK, ты теперь полностью готов. Вот, возьми инструкцию. Если есть склонность к ремонту всякой механики, у тебя не должно быть проблем. Удачи.}
{168}{}{После всего этого? Ну хорошо, скажи когда тебе нужно будет ее вставить. Тогда сможешь начать чинить ее.}
{169}{}{Ну, не знаю, что тебе сказать. Наверно, тебе придется отточить свои ремонтные навыки немного. Прибор пока у меня полежит.}
{170}{}{Окей, спасибо. Пока.}
{171}{}{Привет. Чем могу помочь?}
{300}{}{[ЕЩЕ]}

#Женский вариант, Майкл, 24.11.2006 16:43
{10102}{}{А-а... Так это ты та самая, да?}
{10111}{}{Единственное, ради чего я вступила - это чтобы получить силовую броню.}
{10128}{}{Эй, подожди-ка, подруга, это займет ни много ни мало пару часов. Я тебе могу инструменты дать и инструкцию, но ремонтировать будешь сама.}
{10150}{}{Нет, я им сказала, что ты меня отправил, но они не дали мне ничего.}
{10151}{}{Нет, я еще даже не занималась этим.}
{10153}{}{Да ладно! А я тут думал, что ты умная. Я ж сказал тебе, что у того парня были официальные формы для мозгов.}
{10154}{}{Смотри, кого ты идиотом называешь.} #Проверить, кто говорит
{10155}{}{Я просто пыталась выпросить это у Майкла.}
{10158}{}{Ну... Не могу сказать, что ты не пыталась. Но похоже, у тебя больше нет шансов получить ее со склада. Придется тебе поискать другой путь. Или ищи силовую броню в другом месте.}
{10163}{}{Привет, ну что, достала деталь?}
{10167}{}{OK, ты теперь полностью готова. Вот, возьми инструкцию. Если есть склонность к ремонту всякой механики, у тебя не должно быть проблем. Удачи.}
