{100}{}{О, нет.}
{101}{}{Вы задели лазерный луч, активировавший защитный механизм. Вы получили один пункт повреждения.}
{102}{}{Вы задели лазерный луч, активировавший защитный механизм. Вы получили }
{103}{}{ ед. урона.}
