{100}{}{Вы видите лидера гулей.}
{101}{}{Спасибо, что не стал сразу стрелять. Я могу чем-нибудь помочь?}
{102}{}{Да, мне нужна вода.}
{103}{}{Скажи мне, кто ты?}
{104}{}{Неа.}
{105}{}{Ахх, если хочешь, можешь здесь отдохнуть, мы тебя не тронем.}
{106}{}{Ахх.}
{107}{}{Я предводитель простых людей, которым пришлось уйти с поверхности из-за других.}
{108}{}{Кто вас сюда загнал?}
{109}{}{Фига, вот вы тупые.}
{110}{}{Хмм. Ок, пока.}
{111}{}{Над землей Некрополь и воду контролирует Сет и его гули. Мы мирные люди - и мы ненавидим Сета.}
{112}{}{Кто такой Сет?}
{113}{}{Я разобрался с Сетом. Он вас больше не побеспокоит.}
{114}{}{А как же вы тут живете без воды?}
{115}{}{Ну, мне бы тоже не понравилась такая толпа хиппи. Сет, похоже, нормальный парень.}
{116}{}{Сет такой же гуль, как и мы. Но он обрел немало власти в наземном мире. Он выродок.}
{117}{}{Похоже, он поинтереснее вас, придурков, будет.}
{118}{}{Почему же он позволил вам тут жить?}
{119}{}{Сет не говорит об этом, но он боится, что ему не хватит людей для защиты Некрополя, если его вдруг придется защищать. Поэтому он дает нам столько воды, сколько надо.}
{120}{}{Откуда берется вся эта вода?}
{121}{}{Мне нужна вода для моих людей! Если знаешь, откуда он ее берет, скажи мне немедленно!}
{122}{}{Мне нужен водяной чип, что бы дать своим людям воду. Не знаешь, где его можно взять?}
{123}{}{Я бы вам не доверил бы охрану кучки мусора. Так что там насчет воды?}
{124}{}{До недавнего времени мы качали воду из земли с помощью насоса на Водоразделе}
{125}{}{До недавнего времени? А что случилось?}
{126}{}{Как мне попасть к Водоразделу?}
{127}{}{Что такое Водораздел?}
{128}{}{С тех пор, как сломался насос, мы брали воду из помещения под землей. Я слышал, что там есть Компьютер, который очищает воду.}
{129}{}{Спасибо.}
{130}{}{Где это?}
{131}{}{Водораздел на севере. Придется лезть через канализацию, чтобы туда попасть.}
{132}{}{Ты же не собираешься забрать у нас водяной чип, правда?}
{133}{}{Эмм... Я, нет, что вы, я бы никогда такого не сделал. Я просто хочу посмотреть, как это все работает.}
{134}{}{Конечно, моим людям нужен водяной чип чтобы выжить.}
{135}{}{Почему?}
{136}{}{Если ты заберешь у нас водяной чип, мы все умрем. Мы не сможем выжить со сломанным насосом.}
{137}{}{Ну, мне на вас на самом деле наплевать. Нам тоже нужен водяной чип чтобы выжить. Счастливо.}
{138}{}{А возможно ли починить ваш насос?}
{139}{}{Если это так, то я не могу отпустить тебя живым.}
{140}{}{Я тебе не верю.}
{141}{}{Прости, я не хотел вас обманывать. А что такого в том, что я заберу водяной чип?}
{142}{}{Да, мне, в общем-то, все равно. Если не уйдешь с дороги, я сам тебя уберу.}
{143}{}{Это будет довольно сложно. Необходимые детали потеряны где-то в канализации под водоразделом.}
{144}{}{Почему это так сложно?}
{145}{}{Ты об этих деталях? (Вы показываете найденные детали лидеру гулей)}
{146}{}{Канализация кишит монстрами, и никто из тех, кого я туда отправлял за этими деталями, не вернулся. Ты хочешь найти эти детали, чтобы починить насос?}
{147}{}{Слишком много возиться, я лучше просто заберу водяной чип.}
{148}{}{Да.}
{149}{}{Поскольку вы, ребята, в этом ничего не смыслите, я, так и быть, вам помогу.}
{150}{}{Спасибо. Найдешь детали, неси их сюда. Я тогда смогу тебе помочь.}
{151}{}{Хорошо, я тогда пошел.}
{152}{}{Ты нашел детали для насоса?}
{153}{}{Пока нет.}
{154}{}{Неа. Я решил бросить это дело.}
{155}{}{Еще раз, где я там их должен искать?}
{156}{}{Ну, удачи тебе, тогда.}
{157}{}{Ты вернулся. Ты принес детали для починки насоса?}
{158}{}{Да, вот они.}
{159}{}{Да, только я решил не чинить ваш водяной насос.}
{160}{}{Ну, похоже, тебе будет нужна некоторая помощь с деталями. Вот тут несколько книг, они валялись вокруг, мы их нашли. Они должны тебе помочь. Пожалуйста, почини наш насос.}
{161}{}{К сожалению, я не смогу тебе больше ничем помочь. Удачи там с починкой. Пожалуйста, почини наш насос.}
{162}{}{Ты починил насос?}
{163}{}{Пока нет, я пока работаю над этим.}
{164}{}{Нет, и решил вообще этим не заниматься.}
{165}{}{Да это те самые детали. Хорошо, что они у тебя уже есть.}
{166}{}{Ты больше ничего не хочешь мне сказать?}
{167}{}{Это максимум, насколько близко они могут оказаться рядом с насосом.}
{168}{}{Как я уже говорил, они где-то в канализации под водоразделом. Иди на восток отсюда, затем поверни на север. В том направлении и будет водораздел.}
{169}{}{Спасибо. Счастливо.}
{170}{}{Спасибо тебе за помощь. Ты что-то еще хотел спросить?}
{171}{}{Как же вы тут живете без воды?}
{172}{}{Там хранится вся вода, и оттуда она к нам поступает.}
{173}{}{И где это?}
{174}{}{Недавно, до меня дошли слухи, что кто-то захватил водораздел. Хотя продовольствие продолжает нам поступать почему-то.}
{175}{}{Как мне попасть к Водоразделу?}
{176}{}{Что такое Водораздел?}
{177}{}{Спасибо, что починил насос. И надеюсь, что и с твоими людьми будет все в порядке, когда ты вернешься со своей находкой.}
{178}{}{Спасибо за помощь. Счастливо.}
{179}{}{Ты починил насос, и вода вернулась к нам из глубин. Хотя, похоже, ты не нашел то, что искал.}
{180}{}{Да, я так и не смог обнаружить водяной чип.}
{181}{}{Я слышал, что он находится глубоко под водоразделом. Желаю тебе удачи в поисках.}
{182}{}{Вижу, ты нашел то, за чем пришел. Ты осознаешь, что мы все умрем, если ты заберешь водяной чип у нас?}
{183}{}{Да, но я все еще работаю над тем, что бы починить ваш насос. Где, ты сказал, я могу найти детали?}
{184}{}{Мне нужен только водяной чип, и у меня нет времени на ваши проблемы.}
{185}{}{Какой у меня есть выбор?}
{186}{}{Я устал от твоих лживых замечаний. Я больше не желаю с тобой говорить.}
{187}{}{Раньше у нас был насос на водоразделе, который качал воду с глубины. Но он сломался, а запчасти были потеряны в канализации прямо под водоразделом.}
{189}{}{А почему вы сами не нашли эти запчасти?}
{190}{}{Тебе нечего нас бояться!}
{191}{}{Я поговорю с тобой, прежде чем ты уйдешь.}
{192}{}{Ты не оставил мне другого выбора, кроме как остановиться.}
{193}{}{Подожди! Не стреляй!}
{194}{}{Тебе нечего нас бояться!}
{195}{}{Я поговорю с тобой, прежде чем ты уйдешь.}
{196}{}{Ты не оставил мне другого выбора, кроме как остановиться.}
{200}{}{Повезло.}
{201}{}{Разве нельзя починить насос?}
{202}{}{Извини, моим людям нужен чип, чтобы выжить.}
{203}{}{Пожалуйста, не забирай наш чип. Без него мы умрем.}
{204}{}{Возможно, но детали к нему утеряны в канализации под водоразделом. А канализация кишит монстрами, мы не сможем вернуть эти детали.}
{205}{}{Извини, я хотел бы вам помочь, но не смогу.}
{206}{}{Я найду эти детали.}


############ Tell Me Abouts

{1000}{}{Сет}
{1001}{}{Создатель}
{1002}{}{Вода}
{1003}{}{Водораздел}
{1004}{}{Зал}
{1005}{}{Некрополь}
{1006}{}{Чип}

{1100}{}{Он пытается контролировать Некрополь и загнал нас под землю.}
{1101}{}{Он как-то связан с мутантами. Больше я ничего не знаю.}
{1102}{}{Мы берем воду из помещения под водоразделом. Может, это как-то связано.}
{1103}{}{Там сломанный насос. Там же мутанты раздают воду из их нового источника.}
{1104}{}{Так называемый дворец Сета.}
{1105}{}{Город мертвых, мы бы хотели там жить в мире, если бы Сет или мутанты нам позволили бы.}
{1106}{}{Мы берем воду из помещения под водоразделом. Может это как-то связано.}

#Женский вариант, Елка, 07.12.2006 19:17
{10101}{}{Спасибо, что не стала сразу стрелять. Я могу чем-нибудь помочь?}
{10113}{}{Я разобралась с Сетом. Он вас больше не побеспокоит.}
{10123}{}{Я бы вам не доверила бы охрану кучки мусора. Так что там насчет воды?}
{10133}{}{Эмм... Я, нет, что вы, я бы никогда такого не сделала. Я просто хочу посмотреть, как это все работает.}
{10139}{}{Если это так, то я не могу отпустить тебя живой.}
{10141}{}{Прости, я не хотела вас обманывать. А что такого в том, что я заберу водяной чип?}
{10142}{}{Да, мне, в общем-то, все равно. Если не уйдешь с дороги, я сама тебя уберу.}
{10151}{}{Хорошо, я тогда пошла.}
{10154}{}{Неа. Я решила бросить это дело.}
{10155}{}{Еще раз, где я там их должна искать?}
{10157}{}{Ты вернулась. Ты принесла детали для починки насоса?}
{10159}{}{Да, только я решила не чинить ваш водяной насос.}
{10162}{}{Ты починила насос?}
{10164}{}{Нет, и решила вообще этим не заниматься.}
{10170}{}{Спасибо тебе за помощь. Ты что-то еще хотела спросить?}
{10177}{}{Спасибо, что починила насос. И надеюсь, что и с твоими людьми будет все в порядке, когда ты вернешься со своей находкой.}
{10179}{}{Ты починила насос, и вода вернулась к нам из глубин. Хотя, похоже, ты не нашла то, что искала.}
{10180}{}{Да, я так и не смогла обнаружить водяной чип.}
{10182}{}{Вижу, ты нашла то, за чем пришла. Ты осознаешь, что мы все умрем, если ты заберешь водяной чип у нас?}
#{186}{}{Я устал от твоих лживых замечаний. Я больше не желаю с тобой говорить.}#Проверить, кто говорит
#{192}{}{Ты не оставил мне другого выбора, кроме как остановиться.}#Проверить, кто говорит
#{196}{}{Ты не оставил мне другого выбора, кроме как остановиться.}#Проверить, кто говорит
#{10205}{}{Извини, я хотела бы вам помочь, но не смогу.}