{100}{}{Вы видите сумасшедшего ученого. Он над чем-то усердно работает.}
{101}{}{Добрый вечер, брат. Что привело тебя в наш райский уголок?}
{102}{}{Добрый вечер, сестра. Что привело тебя в наш райский уголок?}
{103}{}{Я здесь, чтобы проверить твой прогресс.}
{104}{}{А что ты тут такое делаешь?}
{105}{}{Что? Ты смеешь задавать мне вопросы? А может, мне над твоими мозгами поэкспериментировать, отморозок больной?!}
{106}{}{Гак.}
{107}{}{Снова ты? Зачем ты опять потревожил славное будущее Создателя?}
{108}{}{Создатель теряет терпение от твоих неудач, а я от твоей наглости!}
{109}{}{Я хотел узнать, как проходят твои эксперименты.}
{110}{}{Ну все. Я ТВОЕМУ будущему положу конец прямо здесь и сейчас, дубина!}
{111}{}{Ууффх!}
{112}{}{Не очень хорошо. Я пробовал вводить ВРЭ напрямую в пинеальную железу, но не получил те результаты, на которые рассчитывал.}
{113}{}{А почему ты не попробуешь ввести препарат напрямую в миндалевидную железу?}
{114}{}{А почему ты не попробуешь ввести препарат в спинной мозг?}
{115}{}{А какие у тебя результаты?}
{116}{}{Хммм. И?}
{117}{}{Я прошу простить меня, сэр. Чем я могу служить?}
{118}{}{Я прошу простить меня, мэм. Чем я могу служить?}
{119}{}{Говори со мной с почтением в следующий раз, иначе ты уже больше ни с кем никогда не заговоришь!}
{120}{}{Правда Создателя подтверждена, у подопытных усиливаются психические способности. [качает головой] Но дело в том, что их несчастные души безвозвратно теряют рассудок. Их приходится изолировать и нейтрализовывать, чтобы они не напали на других и не навредили себе.}
{121}{}{О, как предусмотрительно...}
{122}{}{Где их держат?}
{123}{}{Ты бессердечный мясник! Я, пожалуй, нейтрализую твой мозг и изолирую его от твоего тела! Умри, ублюдок!}
{124}{}{В помещении к северо-западу отсюда. Я вам могу еще чем-то помочь?}
{125}{}{Спасибо за помощь. Пока.}
{126}{}{Нда, э-э. А что такое ВРЭ?}
{127}{}{Ты можешь умереть!}
{128}{}{У меня нет времени на твои глупые шутки!}
{129}{}{Какая интересная идея! Я должен немедленно ее испробовать!}
{130}{}{Э-э, а где вы держите неудачных подопытных?}
{131}{}{Нет, ничего.}
{132}{}{Да! Давай на тебе испробуем!}
{133}{}{Винсент! Готовь свеженького добровольца!}
{134}{}{Что? Это самая нелепая идея, что я когда-либо слышал! [смотрит с подозрением] А кто ты на самом деле такой?}
{135}{}{О, простите. Мне пора.}
{136}{}{Я тут новый... э-э... новенький я. Меня отправили узнать, как у тебя дела.}
{137}{}{Я тебе уже сказал, меня отправил Создатель проверить тебя.}
{138}{}{Я тебе селезенку сейчас буду удалять... без анестезии!}
{139}{}{Хорошо, ладно. Так как дела идут?}
{140}{}{Твое отношение рассказало мне обо всем, что я хотел узнать. Прощай.}
{141}{}{Ага! Засланец! Я так и подозревал. Винсент!}
{142}{}{Ты кто такой? И почему ты в таком костюме? [про себя] Я уже давно никого в таких костюмах не видел.}
{143}{}{Я специально переодет! Враги проникли в святую святых создателя. А я так одет, чтобы втереться к ним в доверие.}
{144}{}{Как ты смеешь задавать вопросы специальному оперативнику Создателя!}
{145}{}{А когда ты видел такие костюмы?}
{146}{}{Он из резины, чтобы легче было кровь вытирать после того, как я тебя убью!}
{147}{}{А, знаешь, тогда, когда мы получили последнюю партию людей с чистой наследственностью э-э... По-моему, там один остался во временных камерах. А почему ты спрашиваешь?}
{148}{}{Да просто так. Как эксперименты проходят?}
{149}{}{Мне нужно срочно доложить Создателю. У меня нет на это времени.}
{150}{}{[качает головой] Увы, несчастные души безвозвратно теряют рассудок. Их приходится изолировать и нейтрализовывать, чтобы они не напали на других и не навредили себе.}
{151}{}{О, как предусмотрительно...}
{152}{}{Ты бессердечный ублюдок! Я, пожалуй, нейтрализую твой мозг и изолирую его от твоего тела! Умри, ублюдок!}
{200}{}{Вы видите Винсента, охранника-супермутанта. Ему скучно.}
{201}{}{Вы видите супермутанта, очевидно, охраняющего ученых. Ему скучно.}
{202}{}{Угроза вторжения!}
{203}{}{Я просто смотрю за этими сумасшедшими. Не говори со мной.}
{204}{}{Оставь меня в покое.}
{300}{}{Вы видите спящего безумного ученого.}
{301}{}{Хррррр}
{302}{}{А! Что? [трет глаза] Винсент, убери этого варвара из нашего отдела!}
{303}{}{Эх? [всхрап]...хррррррр}
{400}{}{Вы видите Винсента. Он охраняет спящих сумасшедших.}
{401}{}{Вы видите охранника-супермутанта. Он стоит практически над телами, лежащими ничком.}
{402}{}{Оставь их в покое, и убирайся. Сюда никто не допускается, когда они спят.}
{403}{}{Ты снова! Я же сказал, оставь ученых в покое.}
{404}{}{Ты слишком долго был в гостях.}

#Женский вариант, Елка, 09.12.2006 16:00
#{105}{}{Что? Ты смеешь задавать мне вопросы? А может, мне над твоими мозгами поэкспериментировать, отморозок больной?!}#Проверить, кто говорит
{10107}{}{Снова ты? Зачем ты опять потревожила славное будущее Создателя?}
{10109}{}{Я хотела узнать, как проходят твои эксперименты.}
{10134}{}{Что? Это самая нелепая идея, что я когда-либо слышал! [смотрит с подозрением] А кто ты на самом деле такая?}
{10136}{}{Я тут новая... э-э... новенькая я. Меня отправили узнать, как у тебя дела.}
{10137}{}{Я тебе уже сказала, меня отправил Создатель проверить тебя.}
{10141}{}{Ага! Засланка! Я так и подозревал. Винсент!}
{10142}{}{Ты кто такая? И почему ты в таком костюме? [про себя] Я уже давно никого в таких костюмах не видел.}
{10143}{}{Я специально переодета! Враги проникли в святую святых создателя. А я так одета, чтобы втереться к ним в доверие.}
#{10302}{}{А! Что? [трет глаза] Винсент, убери эту хулиганку из нашего отдела!}
#{10404}{}{Ты слишком долго была в гостях.}