{100}{}{Вы видите доктора медицинских наук Солоуна}
{101}{}{Вы видите сестру Марни.}
{102}{}{Вы видите доктора.}
{103}{}{Вы видите сестру.}
{104}{}{Здравствуйте. Чем могу помочь?}
{105}{}{Хырргх.}
{106}{}{Я ранен. Вы сможете меня подлечить?}
{107}{}{Вы можете научить меня медицине?}
{108}{}{Да, я вижу, что у вас серьезные повреждения. Это займет некоторое время. Хотите, чтобы я перевязала серьезные ранения?}
{109}{}{Ага.}
{110}{}{Неа.}
{111}{}{Да, если можно.}
{112}{}{Нет, спасибо.}
{113}{}{Вот так. Так вам будет гораздо лучше. Будьте осторожней там, пожалуйста.}
{114}{}{У вас хорошо получается. Вы можете научить меня, как обращаться с травмами?}
{115}{}{Хорошо. Спасибо.}
{116}{}{Я могу вас немного обучить. Но это займет несколько часов. Вы готовы задержаться на это время?}
{117}{}{Да.}
{118}{}{Извините, я слишком занят.}
{119}{}{Вы очень хороший ученик. Надеюсь, вы будете на нашей стороне. До свидания.}
{120}{}{Как пожелаете. Удачи вам.}
{121}{}{Я могу вас кое-чему научить, но лишь немногому. Это займет какое-то время. Вы сможете задержаться?}
{122}{}{Да.}
{123}{}{Извините, но совсем не хватает времени.}
{124}{}{Вы прекрасный ученик. Удачи вам.}
{125}{}{Пока ничего. Но спасибо.}

#Женский вариант, Елка, 09.12.2006 16:37
{10106}{}{Я ранена. Вы сможете меня подлечить?}
{10118}{}{Извините, я слишком занята.}
{10119}{}{Вы очень хорошая ученица. Надеюсь, вы будете на нашей стороне. До свидания.}
{10124}{}{Вы прекрасная ученица. Удачи вам.}