{100}{}{Вы видите Матию.}
{101}{}{Здравствуй, послушник. Так это ты смог выбраться из Древнего Ордена живым.}
{102}{}{Че?}
{103}{}{А ты кто такой?}
{104}{}{Извини, я тебя с кем-то перепутал. Пока.}
{105}{}{Меня зовут Матия. Я официальный ассистент Максона. И еще я слежу за тем, чтобы никто не доставал старика.}
{106}{}{Старик? Звучит как-то не очень уважительно.}
{107}{}{Какие у тебя обязанности как ассистента?}
{108}{}{Приятно познакомиться. Пока.}
{109}{}{Нет, нет, что ты. Он хороший парень. (шутя) К тому же, я не стал бы ему грубить, если бы он рядом был.}
{110}{}{Так а какие у тебя обязанности, как ассистента?}
{111}{}{До свидания.}
{112}{}{Я делаю всю бумажную работу. Он не должен этим заниматься, чтобы беречь себя. Кроме того, если он разрешает смену оружия кому-то из братьев, я провожу заказ.}
{113}{}{Спасибо за сведения.}
{114}{}{Не могу поверить, что такой идиот, как ты, пробрался в Древний Орден. Это противоречит здравому смыслу.}
{115}{}{Привет, послушник. Чем могу помочь?}
{116}{}{Че?}
{117}{}{Извини, я забыл твое имя.}
{118}{}{Извини, я тебя с кем-то перепутал. Счастливо.}
{119}{}{Все, пошли. (он хватает вас за руку)}
{120}{}{Ага.}
{121}{}{Ого.}
{122}{}{Хорошо, хорошо. Иду я.}
{123}{}{Отвали от меня. Я не пойду никуда.}
{124}{}{Окей. Максон разрешил тебе смену оружия. Что ты возьмешь?}
{125}{}{Че?}
{126}{}{Снайперскую винтовку.}
{127}{}{Гранатомет.}
{128}{}{Лазерный пистолет.}
{129}{}{Силовой кастет.}
{130}{}{Потрошитель.}
{131}{}{Ну вот. Рад, что ты на нашей стороне, послушник.}
{132}{}{Старейшины созвали совет. Они желают встретиться с тобой в зале для конференций прямо сейчас.}
{133}{}{А где зал для конференций?}
{134}{}{Хорошо, спасибо.}
{135}{}{Он на этом этаже. В северо-восточном углу, сразу за залом для собраний.}

#Женский вариант, Елка, 10.12.2006 20:54
{10101}{}{Здравствуй, послушница. Так это ты смогла выбраться из Древнего Ордена живой.}
{10104}{}{Извини, я тебя с кем-то перепутала. Пока.}
{10114}{}{Не могу поверить, что такая идиотка, как ты, пробралась в Древний Орден. Это противоречит здравому смыслу.}
{10115}{}{Привет, послушница. Чем могу помочь?}
{10117}{}{Извини, я забыла твое имя.}
{10118}{}{Извини, я тебя с кем-то перепутала. Счастливо.}
{10131}{}{Ну вот. Рад, что ты на нашей стороне, послушница.}