{100}{}{Спасибо. Пока.}
{101}{}{О'кей, спасибо.}
{102}{}{Хм. Прощай.}
{103}{}{Пока.}
{104}{}{Спасибо.}
{105}{}{О'кей, пока!}
{106}{}{[Дальше]}
{107}{}{Хр-р-р! Пш-ш-ш!}
{108}{}{[Готово]}
{109}{}{Я не могу это использовать.}
