{100}{}{Робот не работает. Слой пыли на нем позволяет предположить, что в последнее время им не пользовались.}
{101}{}{Робот отремонтирован, но все еще не работает.}
{102}{}{Проблема не в деталях. Должно быть, дело в его программе.}
{103}{}{У вас нет доступа к функциям робота, так как он отключен.}
{104}{}{Вы кое-как чините неработающие компоненты, но вам нужно больше времени, чтобы полностью отремонтировать их.}
{105}{}{Вы перезагружаете встроенный компьютер и успешно перезапускаете робота. Вы замечаете, что рация робота сломана.}
{106}{}{Вы проводите некоторое время, работая с компьютером робота, но не можете перезагрузить его.}
{107}{}{Робот #462 готов. Проверка. Определение данных о местонахождении. исправлено. Восстановление файла памяти. Исправлено. Ошибка - задача не выполнена.}
{108}{}{Рогга.}
{109}{}{Какая задача не выполнена?}
{110}{}{Что ж, выполни задачу и убирайся!}
{111}{}{[Щелчок] Отлично! Перезапуск задачи.}
{112}{}{Робот #462 предназначен для уборки. Должен закончить уборку и текущий ремонт данного уровня.}
{113}{}{Приступай!}
{114}{}{Что тебе осталось убрать?}
{115}{}{Цистерну в диспетчерской. [Щелчок] Конец списка.}
{116}{}{Хе. Заканчивай свое задание.}
{117}{}{Вы получили 1000 очков опыта за то, что сделали небольшую уборку.}
