{100}{}{Этот компьютер помечен как "Компьютер атомного доступа".}
{101}{}{К компьютеру доступа подключены кабели, ведущие к боеголовке позади него.}
{102}{}{Вы зарядили боеголовку. Четырехминутный таймер начал отсчет.}
{103}{}{Вы разрядили ядерную боеголовку.}
{104}{}{БА-БА-БАХ! [Вы взорвали ядерную бомбу!]}
{105}{}{Не похоже на то, что это работает.}
{106}{}{Отсчет все еще идет... может, вам следует перерезать красный провод.}
{107}{}{Может, вам также следует использовать ключ.}
{108}{}{Этот компьютер оборудован специальным замком, благодаря которому зарядить бомбу можно лишь имея соответствующий ключ.}
{109}{}{Этот надежно защищенный замок невозможно взломать.}
{110}{}{Этот компьютер нельзя починить.}
{111}{}{Вы не можете использовать навык "ловушки" на этом компьютере.}
{112}{}{Вы еще недостаточно натренированны, чтобы обойти механизм безопасности.}
