{100}{}{Ты! Остановись там и предстань перед законом!}
{101}{}{Спасибо за возвращение водяного чипа. Это поможет укрепить дух и не даст людям нарушать законы Убежища.}
{102}{}{Доброго тебе дня. Что я могу для тебя сделать?}
{103}{}{Чем ты занимаешься?}
{104}{}{Да, мне нужно оружие.}
{105}{}{Почему дверь в Убежище заперта?}
{106}{}{Глоп!}
{107}{}{Хмм. Я думаю, лучше тебе не бродить здесь. Хорошего дня.}
{108}{}{Я отвечаю за безопасность и правопорядок в Убежище. Может, ты и не знаешь этого, но Убежище не работало бы так хорошо, если бы не я.}
{109}{}{Хмм. Не. Спасибо.}
{110}{}{Звучит значительно.}
{111}{}{Так и есть. Без должного повиновения законам, Убежище стало бы беззаконным местом, без руководства. Это угрожало бы безопасности всех нас.}
{112}{}{После того, как я побывал снаружи, есть ли какие-либо законы, применяющиеся ко мне?}
{113}{}{Я видел места во внешнем мире, которые страдают без законов.}
{114}{}{Ну, хоть оружие и необходимо во внешнем мире, не показывай его в угрожающей манере. Помимо этого, я думаю, ничего особенного.}
{115}{}{Спасибо.}
{116}{}{Видишь ли, я знал, что так случится. Люди, повинующиеся закону - единственное, что спасло Убежище от разрушения и нищеты. Продолжай свое доброе дело.}
{117}{}{Смотритель не разрешил мне открыть оружейную и получить больше оружия. Извини, но не могу помочь тебе. }
{118}{}{Пожалуйста! Мне действительно нужно!}
{119}{}{Ладно, в любом случае, спасибо.}
{120}{}{Нет. Я не могу это сделать.}
{121}{}{Хорошего дня.}
{122}{}{Надо держать оружие вне досягаемости тех, кто не имеет к нему доступа.}
{123}{}{У кого есть доступ?}
{124}{}{Это не очень-то честно.}
{125}{}{Жизнь не всегда справедлива. Но наш закон справедлив. Удачного дня.}
{126}{}{Смотритель, я, и служба безопасности. И все.}
{127}{}{Похоже, что только те, кому оно нужно, имеют к нему доступ.}
{128}{}{Действительно небольшой список.}
{129}{}{Да. так и есть. Мне нужно вернуться к работе.}
{130}{}{Да, только те, кому оно нужно, могут получить оружие.}
{131}{}{Что ж, мне нужно. Пожалуйста, открой дверь.}
{132}{}{Извини, это хороший аргумент. но я не могу впустить тебя.}
{133}{}{Хмм. Раз ты так сказал, значит, так и есть. Дай мне открыть дверь для тебя.}
{134}{}{Что я могу для тебя сделать, }
{135}{}{ хватит?}
{136}{}{Мне нужно больше оружия.}
{137}{}{Ты в порядке?}
{138}{}{Ух-ху.}
{139}{}{Отлично. Твой интеллект поражает меня. Я больше не могу думать.}
{140}{}{Извини, ты получил все, что мы могли дать. Удачного дня.}
{141}{}{Такие, как ты, мне не нравятся.  Собиратели толпы. Тебе должно быть стыдно.}
{142}{}{Да, тебе того же, пустоголовый.}
{143}{}{Ты не думаешь, что ведешь себя слишком жестко?}
{144}{}{Следи за своим языком, или я отведу тебя к полицейскому за нарушение законов.}
{145}{}{Да, точно. Увидимся.}
{146}{}{Ну все. Мне надоело.}
{147}{}{Хмм. Возможно. В моей работе важно быть беспристрастным, но я, должно быть, переступил черту в этот раз. Я попытаюсь исправиться в будущем.}
{148}{}{Хмм. нет. Вероятно, недостаточно жестко.}
{149}{}{Удачи. Надеюсь, ты справишься с работой.}
{150}{}{Лучше не подводи меня.}
{151}{}{Отложи оружие, сейчас же.}
{152}{}{Что ты делаешь с этим здесь?}
{153}{}{Просто практикуюсь.}
{154}{}{Ничего, извините. Не хотел его доставать.}
{155}{}{Хнг.}
{156}{}{Будь осторожен, когда зовешь меня. И не доставай оружие внутри. Это же Убежище.}
{157}{}{Лучше не практикуйся здесь. У нас будут серьезные проблемы, если ты еще раз это сделаешь.}
{158}{}{Я знал, что жизнь снаружи не доведет тебя до добра.}
{159}{}{Стой! Тебе не разрешается входить сюда!}

{1000}{}{Смотритель}
{1100}{}{Он - высшая власть в Убежище. Убежище выполняет его решения.}

#Женский вариант, Елка, 11.12.2006 4:14
{10112}{}{После того, как я побывала снаружи, есть ли какие-либо законы, применяющиеся ко мне?}
{10113}{}{Я видела места во внешнем мире, которые страдают без законов.}
{10133}{}{Хмм. Раз ты так сказала, значит, так и есть. Дай мне открыть дверь для тебя.}
{10140}{}{Извини, ты получила все, что мы могли дать. Удачного дня.}
{10154}{}{Ничего, извините. Не хотела его доставать.}
{10156}{}{Будь осторожна, когда зовешь меня. И не доставай оружие внутри. Это же Убежище.}