{100}{}{Вы видите Смотрителя.}
{101}{}{Ааа, ты пришел. Хорошо. Ну, хоть это-то хорошо. У нас тут возникла проблема. И немаленькая. Отдал богу душу контрольный чип в нашей системе водоочистки. Мы не можем сами изготовить замену, а сам процесс слишком сложен, чтобы использовать для него другие системы. Проще говоря, у нас заканчивается питьевая вода. А если не будет воды, не будет и Убежища. После того, как ты вырос, мы не слишком ладили. В тебе сидит жажда странствий - а такие желания Убежище не может удовлетворить. Знаешь, я думаю, что это, вполне может быть, последнее безопасное место в мире, так что я всегда беспокоюсь, когда кто-то отправляется на поиски приключений. Ну, ведь если все поуходят, я же без работы останусь! Но теперь серьезно: для нас это вопрос жизни и смерти. И честно говоря, я так думаю, что ты - наша единственная надежда. Тебе придется пойти и найти для нас новый контрольный чип.}
{102}{Over_0a}{Изображение на твоем PIPboy поможет тебе его опознать.}
{103}{Over_1}{На то, чтобы достать чип, у тебя будет три месяца. Потом в Убежище закончится вода.}
{104}{}{Месяц... два... четыре... пять... шесть...}
{105}{Over_2}{У тебя осталось месяца два, а то и меньше, чтобы добыть чип. Потом в Убежище закончится вода. Найди этот чип!}
{106}{Over_3}{По нашим расчетам, у нас есть от четырех до пяти месяцев до тех пор, пока в Убежище не закончится вода. Найди контрольный чип!}
{107}{Over_4}{Вот снаряжение, которое может тебе пригодится.}
{108}{Over_4a}{Если бы у нас не было такой необходимости, я бы никогда не стал тебя об этом просить. Но если ты этого не сделаешь, то я даже не знаю, кто еще сможет хотя бы попробовать. Помоги нам. Ты - наша последняя... последний шанс, как я понимаю.}
{109}{Over_5}{Если тебе понадобится помощь, возвращайся сюда. Разумеется, мы сделаем все, что в наших силах. Но у нас осталось не так уж много времени. Береги себя, найди этот чип и возвращайся сюда.}
{110}{Over_6}{На твоей карте мы отметили местоположение другого Убежища. Не худшее место для начала поисков, как мне кажется. Впрочем, я ведь ничего не знаю про внешний мир. Я... Ну... Ты знаешь, как я к тебе отношусь и... Правда... просто береги себя, ладно?}
{111}{Over_7}{Ты снова здесь! И даже в добром здравии! Как продвигаются поиски?}
{112}{}{Плохо, но я заметил, что уровень радиации довольно низок. Почему бы нам просто не вывести людей из Убежища?}
{113}{}{Чип я еще не нашел. Может, мы просто сделаем ему замену?}
{114}{}{Пока ничего.}
{115}{}{Неа.}
{116}{Over_8}{Слушай, я понимаю, что это не просто. Но мы все рассчитываем на тебя. И времени у нас в обрез. Пожалуйста! Попытайся найти чип!}
{117}{Over_9}{Эх, ты меня никогда не слушаешь. У нас нет необходимых запчастей. Мы уже все запасы израсходовали.}
{118}{}{А, ладно. Спасибо.}
{119}{Over_10}{Мы это уже обсуждали раньше.  Ты ведь только что оттуда, снаружи! Думаешь, остальные тоже способны там выжить? К тому же, я ведь останусь не у дел! Тут я решаю все организационные вопросы! А делать я ничего особо полезного не умею!}
{120}{}{На это мы согласны.}
{121}{Over_12}{Ну, тебе удалось достать чип?}
{122}{}{Еще нет. Прости.}
{123}{}{Я настаиваю, мы должны собрать всех и выводить их отсюда.}
{124}{}{Нет, но мне нужно сообщить тебе много других вещей!}
{125}{}{Неа.}
{126}{Over_13}{[Смотритель вздыхает.] Не извиняйся. Я знаю, что ты делаешь все возможное. Просто не оставляй усилий.}
{127}{Over_14}{Сейчас не лучшее время для обсуждения этих вопросов. Достань чип, дай нам выбор. Большинство наших, включая меня, не выживут там, снаружи.}
{128}{}{Ладно, я попробую найти его.}
{129}{Over_16}{У нас нет ни времени, ни выбора. Я знаю, что это огромная ответственность, но у нас нет альтернативы. Нам необходим этот чип. Немедленно.}
{130}{Over_19a}{Умоляю, скажи, что тебе удалось найти чип.}
{131}{}{Нет, но я видел совершенно умопомрачительные вещи!}
{132}{}{Прости, пока мне не удалось напасть на его след.}
{133}{}{Не-а.}
{134}{}{У-ух.}
{135}{Over_20}{Ну что ж. Продолжай поиски. Времени осталось мало.}
{136}{Over_21}{На это у нас нет времени! Нам необходим этот чип. Время уходит. [Вздох]}
{137}{Over_22}{У тебя какие-то трудности, нужно какое-то снаряжение? Мы тебе чем-то можем помочь?}
{138}{}{Нет, это только займет какое-то время. Там снаружи - большой мир.}
{139}{}{Кое-что мне бы пригодилось.}
{140}{}{Да уж, ты мог бы оторвать задницу от стула и помочь.}
{141}{Over_23}{Сделай все возможное. Помни, мы все рассчитываем на тебя.}
{142}{Over_24}{Вот, возьми наши последние боеприпасы и походные аптечки. Мы все в опасности. Спеши!}
{143}{Over_25}{Что сделать? Кому сделать? Любой другой тебе и в подметки не годится, да и припасов у него таких не будет. Это было бы просто самоубийство.}
{144}{}{Это твой выбор. Я сделаю все, что от меня зависит, но не знаю, хватит ли моих сил.}
{145}{}{Понимаю.}
{146}{Over_26}{Должно хватить. Если ты потерпишь поражение, погибнет все Убежище.}
{147}{}{Принято.}
{148}{}{Как скажешь.}
{149}{Over_27}{Отлично, тогда - отправляйся в путь!}
{150}{Over_28}{Тебе удалось найти чип?}
{151}{}{Да.}
{152}{}{Да, но я думаю, что нам следует еще обсудить вопрос о том, что пора разрешить людям покидать Убежище.}
{153}{}{Оппа!}
{154}{Over_29}{Прекрасно! Дай его мне. Проверим, работает ли он.}
{155}{Over_30}{Пожалуйста, дай мне чип!}
{156}{Over_31}{Оки-доки. Минуточку, сейчас чип инициализируется. Вот - вот - вот - вот - вот - Пошло-поехало... Внутренняя проверка - зеленый... перезагрузка прошла успешно... Ха! Заработало! И у нас тут есть герой! Ха-ха! [Смотритель вздыхает с облегчением.] Тебе удалось, удалось нас спасти. У тебя получилось!}
{157}{}{Да ладно, ничего особенного.}
{158}{}{Пожалуйста.}
{159}{Over_32}{Особенного? О нет! Это было нечто совсем особенное! Не скромничай! Твоими усилиями спасено множество жизней. Хорошо, теперь мы готовы выслушать твой отчет о происходящем снаружи. Пожалуйста, пройди в Библиотеку.}
{160}{}{Хорошо.}
{161}{Over_33}{Убежище спасено. Ты можешь по праву гордиться собой. Но теперь мы должны выслушать твой отчет. Проведем заседание в Библиотеке. Пожалуйста, пройди туда.}
{162}{}{Хорошо.}
{163}{Over_34}{Ну, ты, безусловно, заслуживаешь это право. Но давай сначала позаботимся о выживании. Давай мне чип, а это мы обсудим, когда ты будешь делать свой доклад.}
{164}{}{Согласен.}
{165}{}{Не уверен, что нужно это делать.}
{166}{Over_37}{Вот и прекрасно! Передай мне тогда, пожалуйста, чип?}
{167}{Over_38}{Нет, не это. Мне нужен ком-пью-тер-ный чип.}
{168}{Over_38a}{Нет. Чип.}
{169}{Over_39}{Дай-мне-этот-чип!}
{170}{Over_40}{Спасибо. Теперь, иди в Библиотеку и отдохни там некоторое время, ладно?}
{171}{}{Угу, угугу?}
{172}{}{Ааа, ага? Угугугу-угу.}
{173}{Over_41}{Да, можешь потрогать.}
{174}{Over_41a}{О да. Тебе отлично удалось справиться с задачей, и я уверен, что тебе есть, что нам рассказать.}
{175}{Over_42}{Я... да, я просто хотел тебе сообщить, что наша система водоснабжения стабилизировалась. На самом деле, мы даже понемногу восстанавливаем запасы воды. У тебя все отлично получилось... Я... я, правда, немного озабочен.}
{176}{}{Чем?}
{177}{}{А?}
{178}{Over_43}{Я... меня очень обеспокоил твой отчет. Его содержание, я имею в виду. Эээ... По правде, они меня до смерти напугали. Эти мутанты. Я кое-что тут подсчитал, и, скажем так, пришел к неутешительным выводам.}
{179}{}{Что же это?}
{180}{Over_44}{[Вздох] Популяция мутантов куда больше, чем можно было бы получить при обычном естественном приросте или мутациях у обычных людей. Это наводит меня на мысли о... я, честно сказать, и сам не совсем понимаю. Но, кажется, кто-то специально производит новых мутантов. И притом с ошеломительной скоростью.}
{181}{}{Повтори еще раз? Без путаницы?}
{182}{}{Стало быть, где-то должна быть лаборатория.}
{183}{Over_45}{Кто-то производит мутантов!}
{184}{}{Что мне нужно делать?}
{185}{Over_46}{Именно! И, как ты, наверное, догадываешься, ни одна из этих мутаций не могла произойти естественным путем, даже с учетом послевоенной радиации.}
{186}{}{Что я должен сделать в связи с этим?}
{187}{Over_47}{Пока кто-то производит враждебных мутантов с такой скоростью, под угрозой сама безопасность Убежища! Найди эту лабораторию и уничтожь ее как можно скорее.}
{188}{}{Хорошо.}
{189}{}{Снова наружу, друг мой.}
{190}{Over_48}{Ты себе не представляешь, как я сожалею о том, что должен снова посылать тебя туда, наружу.}
{191}{Over_49}{О, да. Хмм... Ну... ну... ну, это примерно так: есть такое плохое место, откуда лезут плохие мутанты. Это плохо. Убежище - это хорошее место. Пожалуйста, пойди и уничтожь плохое место.}
{192}{Over_50}{Ну что? Лабораторию мутантов уже нашли? Или даже лучше - уничтожили?}
{193}{}{Нет.}
{194}{}{Нет еще, но у меня есть несколько толковых идей по этому поводу.}
{195}{}{Не-а, чего-то я малость потерялся.}
{196}{}{Нэээ.}
{197}{Over_51}{Ну что ж, продолжай поиски.}
{198}{Over_52}{Прекрасно. Но поторопись! Чем больше у них будет времени на производство, тем труднее нам будет их остановить.}
{199}{Over_53}{Что ж, основываясь на твоих данных о плотности их популяции, я полагаю, тебе стоит направить свои поиски в западном направлении.}
{200}{Over_54}{Ну что? Какие новости о базе мутантов?}
{201}{}{Я угробил главного сукина-сына.}
{202}{}{Я убил Создателя, главаря мутантов.}
{203}{}{Нэээ, энннэээ. А-ннна, ннна.}
{204}{Over_55}{Великолепно! Что с лабораторией? Тебе удалось ее уничтожить?}
{205}{}{Нет.}
{206}{}{Ну, ясен пень. Перебил всех мутантов и подорвал их гнездо. Теперь Убежище снова в безопасности.}
{207}{Over_58}{Ты можешь по праву гордиться собой за все то, что совершил. Мы зависели от тебя, и ты с честью справился. Теперь давай поговорим о твоем будущем...}
{208}{Over_59}{В самом деле? Если ты что-то пропускаешь, это может быть смертельной угрозой для Убежища. Я думаю, тебе стоит сходить и проверить еще раз. Попробуй западное направление, там, кажется, большая концентрация мутантов.}
{209}{Over_60}{Иди обратно и найди ее. Ее необходимо уничтожить, чтобы обезопасить Убежище. Попробуй вести поиски в западном направлении, там, кажется, скопилось большинство мутантов.}
{210}{Over_61}{Ну что? Тебе удалось убить главного мутанта?}
{211}{}{У-ху, ну-у-ху. На-ннна.}
{212}{Over_61aS}{Все еще появляются мутанты? Тебе нужно уничтожить репродуктивные чаны? Прекрасно! Иди обратно и позаботься об этом.}
{213}{Over_62}{Ну, что там с мутантами?}
{214}{}{Я их подорвал.}
{215}{}{Их репродуктивные чаны уничтожены.}
{216}{}{Мнаааа!}
{217}{Over_63}{Все?}
{218}{}{Ну, все, которые были в районе чанов.}
{219}{}{Ах-хха, мнаа-хха.}
{220}{Over_64}{А что с их главарем? Что с этим их так называемым Создателем?}
{221}{}{Насколько мне известно, он все еще жив.}
{222}{}{Ух-ххху-мна-ххха.}
{223}{Over_66}{Его необходимо остановить. Если этого не сделать, он сможет восстановить свою империю мутантов и нанести нам ответный удар. Убежище не будет в безопасности, пока Создатель жив.}
{224}{Over_68}{Главарь мутантов уже... успокоился?}
{225}{}{Нет.}
{226}{}{Он скоро будет... спокоен.}
{227}{}{Неа.}
{228}{Over_69}{Я понимаю, что тебе нелегко пришлось. Но этот Создатель - такой тип, что скоро восстановит свою армию мутантов и вернется, чтобы отомстить. Пожалуйста, иди и доверши начатое.}
{229}{Over_70}{Эээ... это великолепно. Это просто прекрасно. Похоже, что у тебя там все под контролем. Пожалуйста, заканчивай там побыстрее, чтобы ты и я могли... В общем, помни: все люди Убежища знают, что их спасение - твоих рук дело.}
{230}{Over_71}{Нет, сейчас это невозможно. Пока все идет таким образом - нет. Правила Убежища созданы для нашей безопасности и для обеспечения выживания нашего вида.}
{231}{Over_72}{Что с тобой?! Ты обращаешься против нас?! Я не могу этого позволить.}
{232}{Over_73}{Водные караваны стали приходить из этого Хаба. Проведя кое-какие расчеты, я... могу сообщить неприятные новости.}
{233}{}{Что же это?}
{234}{}{А?}
{235}{Over_74}{Впрочем, неважно. Просто найди и принеси нам водяной чип. Найди его. Нам он все еще нужен.}
{236}{Over_75}{Караваны могут поддержать наши запасы воды на теперешнем уровне, но никак не восполнить их. А эти торговцы из Хаба обдирают нас как липку. Это, конечно, нас спасает, но не могу сказать, что это окончательное решение проблемы.}
{237}{}{Хорошо.}
{238}{}{Что-то еще, да?}
{239}{Over_76}{Продолжай искать контрольный чип. Это единственный способ сохранить нашу независимость и безопасность, которая обеспечивается нашим уединением.}
{240}{Over_77}{Мы ужасно рискуем, указывая этим людям путь в наше Убежище. Я понимаю твой выбор, и, вероятно, это спасет нас. Но я сильно обеспокоен. Можем ли мы им доверять?}
{241}{}{Я им доверяю.}
{242}{}{Понимаю.}
{243}{Over_78}{Это я отлично понимаю, но нам нужен сменный чип для выживания в далекой временной перспективе и сохранения нашей экономической стабильности. Мы не производим столько товаров, сколько необходимо, чтобы расплачиваться за воду, скоро нам нечего будет им дать. Найди нам новый чип.}
{244}{Over_79}{Конечно, ты им доверяешь. Тебе следует также понимать и то, как нам нужен сменный чип. Так что, пожалуйста, продолжай поиски.}
{245}{Over_80}{Пожалуйста, продолжай искать водяной чип. Это водные караваны станут для нас серьезной проблемой в перспективе.}
{246}{Over_81}{Сделанное тобой великолепно. Невообразимо! Я так горд твоими свершениями. Люди Убежища никогда не смогут тебя отблагодарить за спасение их жизней. Кто знает, может быть это было даже спасение всего человечества. [Смотритель вздыхает.] Это даже несколько затрудняет дело. Все захотят поговорить с тобой. Каждый подросток захочет быть похожим на тебя. Станет подражать тебе. И что тогда? Они захотят уйти. Что случится с Убежищем, если мы потеряем новое поколение? Что если это - единственное безопасное место в мире? Я не могу рисковать снова потерять все эти молодые жизни. Я уже принял много тяжелых решений с тех пор, как я занял этот пост. Но ни одно из них не было таким тяжелым как это. Ты наше спасение, и ты же - наша гибель. Мне очень жаль. Ты - наш герой... но тебе придется уйти.}
{247}{Over_100}{Я ничего об этом не знаю.}
{248}{Over_200}{Это важнейшая деталь нашей системы водоочистки. Без нее мы скоро останемся без питьевой воды.}
{249}{Over_201}{Это наш дом. Мы все умрем без него. Если мы будем как следует о нем заботиться, он простоит еще очень долго.}
{250}{Over_202}{Это было ужасно. Я надеюсь, что мы усвоили урок и больше этого не сделаем.}
{251}{Over_203}{Откуда мне знать? Я едва справляюсь с тем, что происходит тут! Думаю, тебе предстоит это выяснить самостоятельно.}
{252}{}{Вы получаете 7,500 единиц опыта за возвращение водяного чипа и спасение Убежища. Поздравляем!}
{253}{Over_0ab}{Вот изображение, которое поможет тебе опознать его.}
{254}{Over_1a}{До того, как в Убежище закончится питьевая вода, у вас остается один месяц.}
{255}{Over_1b}{До того, как в Убежище закончится питьевая вода, у вас остается два месяца.}
{256}{Over_1c}{До того, как в Убежище закончится питьевая вода, у вас остается четыре месяца.}
{257}{Over_1d}{До того, как в Убежище закончится питьевая вода, у вас остается пять месяцев.}
{258}{Over_1e}{До того, как в Убежище закончится питьевая вода, у вас остается шесть месяцев.}
{259}{}{Да, думаю, вам придется найти еще кого-то, чтобы он выполнял за вас грязную работу.}
{260}{}{Я понимаю. Я приложу все усилия, чтобы найти чип.}
{261}{Over_81a}{Сделанное тобой великолепно. Невообразимо! Я так горд твоими свершениями.}
{262}{Over_81b}{Люди Убежища никогда не смогут тебя отблагодарить за спасение их жизней. Кто знает, может быть это было даже спасение всего человечества. [Смотритель вздыхает.] Это даже несколько затрудняет дело.}
{263}{Over_81c}{Все захотят поговорить с тобой. Каждый подросток захочет быть похожим на тебя. Станет подражать тебе. И что тогда?}
{264}{Over_81d}{Они захотят уйти. Что случится с Убежищем, если мы потеряем новое поколение? Что если это - единственное безопасное место в мире? Я не могу рисковать снова потерять все эти молодые жизни.}
{265}{Over_81e}{Я уже принял много тяжелых решений с тех пор, как я занял этот пост. Но ни одно из них не было таким тяжелым как это. Ты наше спасение, и ты же - наша гибель. Мне очень жаль. Ты - наш герой... но тебе придется уйти.}

# Overseer Tell-Me-Abouts generic responses
{980}{Over_100}{Я ничего об этом не знаю.}

#
# Overseer Tell-Me-Abouts
#


{1000}{}{Вода}
{1001}{}{Убежище}
{1002}{}{Война}
{1003}{}{Внешний мир}
{1004}{}{Чип}
{1005}{}{Библиотека}
{1006}{}{Лечение}
{1007}{}{Медик}
{1008}{}{Убежище 13}
{1009}{}{Убежище-13}
{1010}{}{Смотритель}
{1011}{}{Водяной чип}

{1100}{Over_200}{Это важнейшая деталь нашей системы водоочистки. Без нее мы скоро останемся без питьевой воды.}
{1101}{Over_201}{Это наш дом. Мы все умрем без него. Если мы будем как следует о нем заботиться, он простоит еще очень долго.}
{1102}{Over_202}{Это было ужасно. Я надеюсь, что мы усвоили урок и больше этого не сделаем.}
{1103}{Over_203}{Откуда мне знать? Я едва справляюсь с тем, что происходит тут! Думаю, тебе предстоит это выяснить самостоятельно.}
{1104}{Over_200}{Это важнейшая деталь нашей системы водоочистки. Без нее мы скоро останемся без питьевой воды.}
{1105}{Over_21q}{На это у нас нет времени!}
{1106}{Over_21q}{На это у нас нет времени!}
{1107}{Over_21q}{На это у нас нет времени!}
{1108}{Over_201}{Это наш дом. Мы все умрем без него. Если мы будем как следует о нем заботиться, он простоит еще очень долго.}
{1109}{Over_201}{Это наш дом. Мы все умрем без него. Если мы будем как следует о нем заботиться, он простоит еще очень долго.}
{1110}{Over_21q}{На это у нас нет времени!}
{1111}{Over_200}{Это важнейшая деталь нашей системы водоочистки. Без нее мы скоро останемся без питьевой воды.}

#Женский вариант, Елка, 11.12.2006 4:21
{10101}{}{Ааа, ты пришла. Хорошо. Ну, хоть это-то хорошо. У нас тут возникла проблема. И немаленькая. Отдал богу душу контрольный чип в нашей системе водоочистки. Мы не можем сами изготовить замену, а сам процесс слишком сложен, чтобы использовать для него другие системы. Проще говоря, у нас заканчивается питьевая вода. А если не будет воды, не будет и Убежища. После того, как ты выросла, мы не слишком ладили. В тебе сидит жажда странствий - а такие желания Убежище не может удовлетворить. Знаешь, я думаю, что это, вполне может быть, последнее безопасное место в мире, так что я всегда беспокоюсь, когда кто-то отправляется на поиски приключений. Ну, ведь если все поуходят, я же без работы останусь! Но теперь серьезно: для нас это вопрос жизни и смерти. И честно говоря, я так думаю, что ты - наша единственная надежда. Тебе придется пойти и найти для нас новый контрольный чип.}
{10112}{}{Плохо, но я заметила, что уровень радиации довольно низок. Почему бы нам просто не вывести людей из Убежища?}
{10113}{}{Чип я еще не нашла. Может, мы просто сделаем ему замену?}
{10131}{}{Нет, но я видела совершенно умопомрачительные вещи!}
{10164}{}{Согласна.}
{10165}{}{Не уверена, что нужно это делать.}
{10186}{}{Что я должна сделать в связи с этим?}
{10195}{}{Не-а, чего-то я малость потерялась.}
{10201}{}{Я угробила главного сукина-сына.}
{10202}{}{Я убила Создателя, главаря мутантов.}
#{10206}{}{Ну, ясен пень. Перебила всех мутантов и подорвала их гнездо. Теперь Убежище снова в безопасности.}
{10214}{}{Я их подорвала.}
