{100}{}{Вы видите Рэя.}
{101}{}{Вы видите супермутанта.}
{102}{}{Ты явно не отсюда.}
{103}{}{(растерянно и печально) Да уж наверное. Но... зачем ты здесь?}
{104}{}{И ты тоже.}
{105}{}{Э.. нет, отсюда. Создатель послал меня под маскировкой проверить нашу систему безопасности.}
{106}{}{Точно, я здесь, чтобы убить тебя.}
{107}{}{Ладно, я уже ухожу.}
{108}{}{Ха.}
{109}{}{(вздох) Чего тебе надо?}
{110}{}{Я потерялся... можешь мне показать, где сидит Создатель? Мне его нужно убить.}
{111}{}{Ничего. Прощай.}
{112}{}{Затем, чтобы посмотреть, как ты выглядишь с содранной кожей, чертов мутант.}
{113}{}{Да что с тобой?}
{114}{}{велик-робин-бобин.}
{115}{}{Я здесь, чтобы... созерцать единство Создателя.}
{116}{}{Конечно. Единство приносит мир. Могу ли я спросить, откуда ты?}
{117}{}{И я тоже. Я отправился в длительное паломничество, чтобы своими собственным глазами узреть Создателя.}
{118}{}{Мне еще многому предстоит научиться. Как можно получить аудиенцию у Создателя?}
{119}{}{Я был у него вчера. Сегодня я медитирую над тем, как бы Создатель выглядел, если бы я поджег его и поджарил яичницу на его гнилой туше.}
{120}{}{Я думаю, что Создатель безумен.}
{121}{}{Я из... ну... из другого места.}
{122}{}{Какое совпадение! И я тоже.}
{123}{}{Где же?}
{124}{}{Я из Убежища... Я чистопородный человек.}
{125}{}{Ты что, полный имбецил?}
{126}{}{Откуда ты родом?}
{127}{}{(шепотом) Я из Убежища... Я чистопородный человек.}
{128}{}{Я лучше промолчу. До свиданья.}
{129}{}{Небольшая деревня к северу отсюда.}
{130}{}{А почему я должен тебе это говорить? Ты всего-то жалкий прислужник "Человека".}
{131}{}{Зачем ты мне это говоришь? Я должен отвести тебя к Создателю...}
{132}{}{Но не отведешь}
{133}{}{Можешь попробовать.}
{134}{}{Хорошо, я должен вставить пистолет тебе в рот и спустить курок!}
{135}{}{Не надо.}
{136}{}{Я знаю, почему ты так страдаешь.}
{137}{}{Я, пожалуй, пойду.}
{138}{}{Ты прав... если бы только я мог очистить свою голову. Что-то...}
{139}{}{Я знаю, почему ты не можешь очистить голову.}
{140}{}{Создатель не позволяет тебе думать внятно. Думание нарушает единство.}
{141}{}{Создатель виной тому, что ты так страдаешь.}
{142}{}{Эй, у меня появилась мысль - давай вспорем брюхо Создателю и поглядим, что там у него внутри!!!}
{143}{}{Скажи мне! Прошу тебя!!}
{144}{}{Ты тоже раньше был человеком. Создатель заразил тебя вирусом ВРЭ и вызвал мутации.}
{145}{}{Прости, я не могу.}
{146}{}{Только Создатель может тебе все рассказать.}
{147}{}{Только Создатель может тебе все рассказать. Но ты лучше говори с ним побыстрее, потому как я его скоро прикончу.}
{148}{}{Прости, мне пора идти.}
{149}{}{Ты издеваешься! Тебя бы следовало за это убить!}
{150}{}{У меня есть идея получше - помоги мне уничтожить Создателя за то, что он с тобой сделал.}
{151}{}{Нет, ты должен убить Создателя за то, что он с тобой сделал. Я именно это и собираюсь сделать... не хочешь мне помочь?}
{152}{}{За что? Ведь это не я превратил тебя в мутанта!}
{153}{}{Можешь попробовать.}
{154}{}{Нет уж, спасибо. До свиданья!}
{155}{}{Давай будем крутить ему голову до тех пор, пока у него глаза не повыскакивают.}
{156}{}{Тебе не удастся убить Создателя. Он бессмертен.}
{157}{}{Ты прав. Лучше я выберусь отсюда.}
{158}{}{Ну, это мы еще посмотрим.}
{159}{}{Хмммм. Интересно, как он будет продолжать жить, когда его единство будет уничтожено...}
{160}{}{Не может быть... Создатель... защищает... объединяет...}
{161}{}{Ну, друг мой, ты - яркий пример "объединения". Поверь мне, я видел весь процесс. Я здесь для того, чтобы Создатель не успел "объединить" еще кого-нибудь.}
{162}{}{И как тебе нравится быть защищенным и объединенным?}
{163}{}{Да, он защищает себя, подчиняя всех остальных.}
{164}{}{Хватит с меня этого. До свиданья.}
{165}{}{Уходи немедленно, а не то мне придется разобраться с тобой.}
{166}{}{АААААГГХХ!!! (Хватается за голову) Я.. не могу...}
{167}{}{Правильно, твой друг, Создатель, лишил тебя всего, что у тебя было в этом мире, включая саму человечность.}
{168}{}{Ты сам знаешь, что это правда... вот почему ты так растерян. Ты сопротивляешься мутации. Помоги мне отомстить за тебя, уничтожить Создателя!}
{169}{}{Разумеется, можешь. Ну же, давай прикончим Создателя, будет весело.}
{170}{}{Я лучше пойду.}
{171}{}{Прости, ты так страдаешь, но это вина Создателя.}
{172}{}{Я вырву ему глаз!! Я сорву его гнусную головку с этих проводов!!!! Ты... уходи отсюда... Я позабочусь о Создателе.}
{173}{}{Прекрасно!!}
{174}{}{Спасибо за предложение, но я лучше сам закончу это дело. Хочешь мне помочь?}
{175}{}{Я пока останусь здесь. У меня остались незаконченные дела.}

#Женский вариант, Елка, 11.12.2006 22:35
{10110}{}{Я потерялась... можешь мне показать, где сидит Создатель? Мне его нужно убить.}
{10117}{}{И я тоже. Я отправилась в длительное паломничество, чтобы своими собственным глазами узреть Создателя.}#Проверить, кто говорит
{10119}{}{Я была у него вчера. Сегодня я медитирую над тем, как бы Создатель выглядел, если бы я подожгла его и поджарила яичницу на его гнилой туше.}
{10125}{}{Ты что, полная имбецилка?}
{10130}{}{А почему я должна тебе это говорить? Ты всего-то жалкий прислужник "Человека".}#Проверить, кто говорит
{10134}{}{Хорошо, я должна вставить пистолет тебе в рот и спустить курок!}#Проверить, кто говорит
{10138}{}{Ты права... если бы только я мог очистить свою голову. Что-то...}
{10152}{}{За что? Ведь это не я превратила тебя в мутанта!}
{10161}{}{Ну, друг мой, ты - яркий пример "объединения". Поверь мне, я видела весь процесс. Я здесь для того, чтобы Создатель не успел "объединить" еще кого-нибудь.}
{10174}{}{Спасибо за предложение, но я лучше сама закончу это дело. Хочешь мне помочь?}