{100}{}{Вы видите Джерри, молодого посвященного.}
{101}{}{Вы видите рыцаря-посвященного.}
{102}{}{Вы видите писца-посвященного.}
{103}{}{Приветствую! Ты, должно быть, брат }
{104}{}{, новый посвященный. Меня зовут Джерри, я твой сосед по комнате. Я тоже посвященный! Я так долго и тяжело учился. А ты посвященный рыцарь или писец?}
{105}{}{Я еще не решил.}
{106}{}{Рыцарь.}
{107}{}{Писец.}
{108}{}{У-ук.}
{109}{}{Да уж, быть рыцарем здорово, много всего насмотришься, во всем поучаствуешь и можно делать все эти устройства. Я еще сам не решил, но меня тянет в рыцари. Я тебя еще не утомил? Кое-кто говорит, что я слишком много болтаю, но я думаю, что они просто ничего не понимают. Мне просто есть что сказать.}
{110}{}{Нет, совсем нет.}
{111}{}{Мне пора идти. Приятно было познакомиться.}
{112}{}{Да уж, писцы занимаются творческой работой. Было бы здорово изобретать новое оружие или модифицировать старое, и вести учет всего и вся в Братстве. Я тебя еще не утомил? Кое-кто говорит, что я слишком много болтаю, но я думаю, что они просто ничего не понимают. Мне просто есть что сказать.}
{113}{}{Да уж, я все еще пытаюсь решить. Так трудно выбрать, везде так весело. Кстати, если захочешь спать на верхней кровати, то я не против, просто дай мне знать.}
{114}{}{Спасибо. Пока.}
{115}{}{С тобой все в порядке? Может, тебе надо сходить к доктору или просто хорошенько выспаться? Ладно, пойду я лучше поучусь. До свиданья.}
{116}{}{Да, кстати, я рад, что ты будешь моим новым соседом по комнате. Мой прежний сосед все время затыкал уши ватой, не могу понять почему. В любом случае, оставляй тут все что хочешь, моих вещей тут мало. Хочешь спать на верхней кровати? Я готов с тобой поменяться, если хочешь... ты ведь не храпишь, правда? Ладно, это неважно. До встречи.}
{117}{}{Да, и я так подумал. Да, кстати, я рад, что ты будешь моим новым соседом по комнате. Мой прежний сосед все время затыкал уши ватой, не могу понять почему. В любом случае, оставляй тут все что хочешь, моих вещей тут мало. Хочешь спать на верхней кровати? Я готов с тобой поменяться, если хочешь... ты ведь не храпишь, правда? Ладно, это неважно. До встречи.}
{118}{}{Просто буди меня, если я начну храпеть.}
{119}{}{Томас говорит, что я слишком много болтаю.}
{120}{}{Талус говорит, что из меня бы получился хороший рыцарь, если бы я не болтал так много.}
{121}{}{Привет-привет, сосед!}
{122}{}{Я прошлой ночью плохо спал.}
{123}{}{Привет еще раз.}
{124}{}{Завтра мне надо будет идти на патрулирование.}
{125}{}{Через несколько лет я стану старшим посвященным.}
{126}{}{Это не твоя комната, уходи, пожалуйста.}
{127}{}{Думаю, ты в комнате Джерри.}
{128}{}{Удачи, тебе предстоит делить комнату с Джерри Трепачом.}
{129}{}{Ты что тут делаешь?}
{130}{}{Ты тоже посвященный?}
{131}{}{В гостях?}
{132}{}{Твоя комната - первая слева от входа.}

#Женский вариант, Елка, 12.12.2006 3:14
{10103}{}{Приветствую! Ты, должно быть, сестра }
{10104}{}{, новая посвященная. Меня зовут Джерри, я твой сосед по комнате. Я тоже посвященный! Я так долго и тяжело учился. А ты посвященный рыцарь или писец?}
{10105}{}{Я еще не решила.}
{10116}{}{Да, кстати, я рад, что ты будешь моей новой соседкой по комнате. Мой прежний сосед все время затыкал уши ватой, не могу понять почему. В любом случае, оставляй тут все что хочешь, моих вещей тут мало. Хочешь спать на верхней кровати? Я готов с тобой поменяться, если хочешь... ты ведь не храпишь, правда? Ладно, это неважно. До встречи.}
{10117}{}{Да, и я так подумал. Да, кстати, я рад, что ты будешь моей новой соседкой по комнате. Мой прежний сосед все время затыкал уши ватой, не могу понять почему. В любом случае, оставляй тут все что хочешь, моих вещей тут мало. Хочешь спать на верхней кровати? Я готов с тобой поменяться, если хочешь... ты ведь не храпишь, правда? Ладно, это неважно. До встречи.}

{10118}{}{Просто буди меня, если я начну храпеть.}
{10119}{}{Томас говорит, что я слишком много болтаю.}
{10120}{}{Талус говорит, что из меня бы получился хороший рыцарь, если бы я не болтал так много.}
{10121}{}{Привет-привет, соседка!}
{10122}{}{Я прошлой ночью плохо спал.}
{10123}{}{Привет еще раз.}
{10124}{}{Завтра мне надо будет идти на патрулирование.}
{10125}{}{Через несколько лет я стану старшим посвященным.}

#{10130}{}{Ты тоже посвященная?}