{100}{}{Вы видите: жителя Убежища.}
{101}{}{Вы видите: огорченного жителя Убежища.}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{Спасибо за наше спасение!}
{106}{}{Мне казалось, ты не справишься, но теперь я в тебя верю.}
{107}{}{Спасибо! Спасибо!}
{108}{}{Ты настоящий герой. Мой малыш Бобби хочет быть таким, как ты, когда вырастет. Не знаю, нравится ли мне такая перспектива.}
{109}{}{Ты наша героиня. Мой малыш Бобби хочет быть таким, как ты, когда вырастет. Не знаю, нравится ли мне такая перспектива.}
{110}{}{Ты отличный парень!}
{111}{}{Ты удивительная девушка!}
{112}{}{Лучше не ходи здесь с оружием.}
{113}{}{Это же оружие!}
{114}{}{На тебя уже кто-нибудь нападал?}
{115}{}{Думаешь, стоит здесь ходить с оружием?}
{116}{}{Приветствую! Как продвигаются поиски?}
{117}{}{Отлично.}
{118}{}{Не слишком хорошо.}
{119}{}{Ухх.}
{120}{}{Ну, приятно слышать. Так держать!}
{121}{}{Никаких проблем.}
{122}{}{Мы всегда знали, что надежды нет. Нам никогда не добыть новый чип вовремя. Думаю, некоторым из нас пора потихоньку перебираться наружу, пока не стало слишком поздно.}
{123}{}{Не думаю, что это хорошая идея.}
{124}{}{Хммм, но может быть - лучшая из имеющихся.}
{125}{}{Поторопись, пожалуйста.}
{126}{}{Не беспокойся, я добуду чип.}
{127}{}{Может быть, тебе стоило бы прийти на одно из наших собраний. У Терезы есть неплохие идеи. Мы собираемся в ее комнате на втором уровне в пять часов каждый вечер.}
{128}{}{Я подумаю об этом.}
{129}{}{Нет, спасибо. У меня много работы.}
{130}{}{Именно об этом Тереза и говорит. У нее есть разработанный план. Мы подумываем вскоре покинуть Убежище.}
{131}{}{Удачи!}
{132}{}{Думаю, вам пока не стоит уходить.}
{133}{}{Почему Смотритель выбрал тебя? Да ты шнурки от своих ботинок найти никогда не мог, не то что водяной чип. Эхх, ладно.}
{134}{}{Урхх.}
{135}{}{Тебе что, заняться нечем? Поторопись и найди нам чип!}
{136}{}{Не учи меня жить, неудачник!}
{137}{}{Конечно! Всегда мечтал!}
{138}{}{Гдорф!}
{139}{}{Ты запечатал нашу судьбу в этом Убежище, предатель. Надеюсь, ты собой доволен.}

{1000}{}{Смотритель}
{1001}{}{Убежище 13}
{1002}{}{Убежище-13}
{1003}{}{Убежище}
{1100}{}{Смотритель хочет просто держать всех здесь под контролем. Мы должны сами выйти во внешний мир.}
{1101}{}{Убежище было нам домом, но оно уже не простоит долго. Пришло время найти себе новый дом.}
{1102}{}{Убежище было нам домом, но оно уже не простоит долго. Пришло время найти себе новый дом.}
{1103}{}{Убежище было нам домом, но оно уже не простоит долго. Пришло время найти себе новый дом.}

#Женский вариант, Елка, 12.12.2006 5:12
{10133}{}{Почему Смотритель выбрал тебя? Да ты шнурки от своих ботинок найти никогда не могла, не то что водяной чип. Эхх, ладно.}
{10139}{}{Ты запечатала нашу судьбу в этом Убежище, изменница. Надеюсь, ты собой довольна.}