{100}{}{Вы видите охранника Братства.}
{101}{}{Тебе не место здесь, посвященный!}
{102}{}{Что ты здесь делаешь?}
{103}{}{Комната охраны - для охранников. Ты не охранник. Ты в комнате охраны. Следовательно, ТЕБЕ НУЖНО УЙТИ ОТСЮДА.}
{104}{}{Покинь помещение, тебе тут не место.}
{105}{}{Эй, Посвященным сюда нельзя.}
{106}{}{Мальчик мой, это не библиотека. Если ты хочешь полистать книжки, иди в библиотеку.}
{107}{}{Дочь моя, это не библиотека. Если ты хочешь полистать книжки, иди в библиотеку.}

#Женский вариант, Елка, 12.12.2006 5:58
{10101}{}{Тебе не место здесь, посвященная!}