{100}{}{Вы получаете 400 очков опыта за то, что вернули Танди.}
{101}{}{На юге вы видите стену из кирпича, окружающую небольшую спокойную деревушку.}
{102}{}{Небольшая хижина - это все, что здесь осталось. К счастью, в ваших записях сказано, что здесь должен быть запасной вход в Убежище 15.}
{103}{}{Вы видите небольшое здание, окруженное несколькими палатками. Их жители выглядят грязными и злобными.}
{104}{}{Вы натыкаетесь на среднего размера город. Проход закрывает стена из ржавых автомобилей. Дым туманом окутывает город.}
{105}{}{На юге вы видите огромный город. Его окружают отдаленные фермы. Кажется, этот оазис среди пустыни полон жизни.}
{106}{}{Вы приближаетесь к темному полуразрушенному городу. Признаки жизни в нем почти не видны. Зловоние смерти окутывает город.}
{107}{}{Небольшое здание, окруженное забором из металлической сетки, находится на севере. Территория патрулируется грозными охранниками в тяжелой броне.}
{108}{}{К северу простирается огромный кратер.}
{109}{}{К северо-востоку от входа в укрепленную базу, встроенную в склон горы, видны охранники-мутанты.}
{110}{}{Огромное, богато украшенное здание, устремлено в небеса. Толпа народа бесцельно слоняется перед входом.}
{111}{}{Вы видите склад к северу отсюда. Он окружен рвом, в котором плещется какая-то светящаяся гадость.}
{112}{}{Вдали виднеется огромная укрепленная фабрика со стенами, исписанными граффити, и грозного вида орудийными турелями.}
{113}{}{В частично восстановленном ночном клубе и вообще в окрестностях явно видны следы преступной деятельности.}
{114}{}{В самом сердце города огромная библиотека, укрепленная и восстановленная, устремляется вверх со зловещей, но в то же время грациозной, статью. Вы чувствуете умиротворение.}
{115}{}{Деревня, огражденная забором и патрулируемая охранниками, дерзко виднеется на юге.}
{116}{}{Вы видите гигантский след на земле. Вы ищете, но больше следов не находите.}
{117}{}{Земля покрыта пеплом и следами пожара.}
{118}{}{Эта территория выглядит так, будто сюда попала зажигательная бомба высокого давления.}
