{100}{}{Вы видите Троя.}
{101}{}{Мои поздравления, человек. Ты был избран, чтобы присоединиться к элитному отряду служителей. Следуй за мной.}
{102}{}{Это часом никак не связано со слухами об обезумевшей армии супермутантов?}
{103}{}{Куда мы идем?}
{104}{}{Чего ты ждешь? Пошли!}
{105}{}{Нет.}
{106}{}{А что это за отвратительная трупная вонь? А, это ты так пахнешь!}
{107}{}{Рух?}
{108}{}{Следуй за мной, и ты узнаешь. Или, выражаясь иначе, следуй за мной и сохранишь жизнь, дубина!}
{109}{}{Так если я не пойду, я умру, да? Звучит очень религиозно.}
{110}{}{Убедил. Потопали!}
{111}{}{Нет.}
{112}{}{Не начинай того, с чем потом не разберешься, уродище!}
{113}{}{Отлично!}
{114}{}{Не играй в игры с Леди Джейн и Чадами Собора.}
{115}{}{Не оскверняй оскорблениями того, кого не можешь убить. Итак, ты идешь со мной и остаешься жить или остаешься тут и умираешь?}
{116}{}{Уже иду!}
{117}{}{И не надейся.}
{118}{}{Блин, некоторые мутанты шуток вообще не понимают!}
{119}{}{Если я еще малость понюхаю твою вонь, я все равно помру!}
{120}{}{Ты, глупое животное! Ты пойдешь со мной или останешься?}
{121}{}{Эээ... Идет!}
{122}{}{Эээ... моя стоять!}
{123}{}{Не изводи меня нерешительностью! Каков твой ответ, человек?}
{124}{}{Я иду с тобой. Пошли.}
{125}{}{И не надейся.}
{126}{}{Да как ты смеешь меня принуждать? Я сам решаю, куда и как идти!}
{127}{}{Наглая шавка! Теперь ты умрешь!}
{128}{}{Не изводи меня своими шуточками! Каков твой ответ, человек?}
{129}{}{Я иду с тобой. Пошли.}
{130}{}{И не надейся.}
{131}{}{Не дави на меня, приятель. Я все еще обдумываю варианты возвращения...}
{132}{}{Мутант не обращает на вас внимания.}

#Женский вариант, Елка, 13.12.2006 6:42
{10101}{}{Мои поздравления, человек. Ты была избрана, чтобы присоединиться к элитному отряду служителей. Следуй за мной.}
{10126}{}{Да как ты смеешь меня принуждать? Я сама решаю, куда и как идти!}