{100}{}{Этот компьютер очищает воду для Убежища.}
{101}{}{Компьютер водоочистки бесполезен без контрольного чипа, который безнадежно испорчен. Вам придется найти чип на замену.}
{102}{}{Вы некоторое время возитесь в компьютером, но больше ничего толкового из него вытянуть не можете.}
{103}{}{На этой штуке много ярких огоньков.}
{104}{}{Компьютер, кажется, функционирует хорошо с новым чипом.}
