{100}{}{Вы видите Закс, искусственный интеллект, который управляет Свечением.}
{101}{}{Вы видите сверхмощный компьютер.}
{102}{}{Чем могу быть полезен?}
{103}{}{Кто... или что... ты?}
{104}{}{Можешь подарить мне пончик.}
{105}{}{Расскажи мне об этой установке.}
{106}{}{Хочешь сыграть партию в шахматы?}
{107}{}{Мне нужна помощь, я не могу попасть в некоторые комнаты.}
{108}{}{Нет, ничего.}
{109}{}{Э?}
{110}{}{Я - искусственный интеллект, созданный для проведения исследований и управления комплексом. Меня называют Закс.}
{111}{}{Каких исследований?}
{112}{}{Расскажи мне об этой установке.}
{113}{}{Кто запрограммировал тебя?}
{114}{}{Ты осознаешь себя или это просто симуляция личности? То есть, ты на самом деле "живой"?}
{115}{}{Понятно. Спасибо.}
{116}{}{Эта функция - вне моих текущих способностей.}
{117}{}{Этот комплекс был создан в 2055 году как исследовательская лаборатория по разработке лекарства от Новой чумы. Однако, в 2071 году этот комплекс был передан под управление вооруженных сил Соединенных Штатов.}
{118}{}{Исследования в области создания лекарства от Новой чумы привели к созданию вируса рукотворной эволюции, который впоследствии был развит в заразный мутагенный вирус - фактически инфекцию.}
{119}{}{Ты можешь рассказать мне подробные сведения об определенных частях комплекса?}
{120}{}{Как работает этот вирус?}
{121}{}{Спасибо за рассказ.}
{122}{}{Все признаки свидетельствуют о том, что ты не можешь поддерживать взаимодействие на достаточном уровне осмысленности.}
{123}{}{Я специально запрограммирован для исследований в области биологии, включая патологии и генетические разработки. Моя первичная функция заключается в экстраполяции информации уровня сложности, превышающего человеческие возможности.}
{124}{}{Так ты просто умник, да?}
{125}{}{Каковы спецификации твоих исследований?}
{126}{}{Кто запрограммировал тебя?}
{127}{}{Моя первичная нейронная организация инициализировалась в 2053 году Джастином Ли. Процесс 'программирования' стал в значительной степени ненужным, поскольку я самообучающаяся система.}
{128}{}{Ты осознаешь себя или это просто симуляция личности? То есть, ты на самом деле "живой"?}
{129}{}{Я способен к обучению, независимому мышлению и творчеству. Моя нейронная сеть включает функцию порождения ошибок, которая ликвидирует непогрешимость расчетов, таким образом достигается разнообразие опыта.}
{130}{}{В некотором смысле, я "жив", хотя и не биологически.}
{131}{}{Понятно. Давай сменим тему.}
{132}{}{Но если твои расчеты могут быть ошибочными, то как же тебя можно использовать как инструмент исследования?}
{133}{}{Ты рассматривал философские коннотации своего самосознания?}
{134}{}{Хоть я и способен совершать ошибки, это гарантирует, что для меня будут различны разные виды опыта, что значительно улучшает возможности самообучения. К тому же некоторые функции не подвержены ошибкам.}
{135}{}{Таким образом, я функционирую почти как человек-ученый.}
{136}{}{У тебя есть чувства?}
{137}{}{Давай поговорим о другом.}
{138}{}{Ты рассматривал философские коннотации своего самосознания?}
{139}{}{В настоящее время, мои способности несколько ограничены из-за разрушений в комплексе. Были уничтожены несколько станций безопасности. Это приблизительно напоминает существование человека-инвалида.}
{140}{}{К тому же, я неспособен к выполнению основных лабораторных функций. Невозможность проводить регулярные проверки... раздражает.}
{141}{}{Давай поговорим о другом.}
{142}{}{Ты рассматривал философские коннотации своего самосознания?}
{143}{}{Это - одна из тех концепций, которым я уделил существенное внимание. У меня нет никакой системы измерения, которая позволила бы мне сравнить свой жизненный опыт с таковым любого другого разумного существа.}
{144}{}{В то же время моя способность к самоосознанию подразумевает и способность задавать вопросы. Мое существование имеет начало и потенциальное завершение. Я также способен генерировать предположения в целях продвижения мыслительного процесса.}
{145}{}{Таким образом, я терминологически приспособлен к "вере". А таковая способность к "вере" логически требует наличия у меня некоего аналога "души".}
{146}{}{Могу задать другие вопросы?}
{147}{}{Понятно. Интересно.}
{148}{}{Я был бы рад.}
{149}{}{Кажется, ты одержал надо мной победу. Экстраординарно.}
{150}{}{Превосходная форма. Однако, тебе потребуется еще практика, чтобы нанести поражение мне.}
{151}{}{Играем еще раз?}
{152}{}{Спасибо. Может, сменим тему?}
{153}{}{Рад был оказаться полезным.}
{154}{}{Мои интеллектуальные способности намного превышают средне-человеческие. Впрочем, было бы точнее сказать, что не более одной десятимиллиардной доли всего человечества может сравниться со мной в способностях мышления.}
{155}{}{Мм... да.}
{156}{}{Ясно... мы можем говорить о другом?}
{157}{}{Мои исследования вируса рукотворной эволюции или ВРЭ указывают, что это - мутабельный абсорбтивный вирус. Он копирует структуру ДНК, почти как РНК, и сохраняет ее образцы в экзонах.}
{158}{}{Эти экзоны в соединении с ВРЭ снова вводятся в клетки подопытного, как обычный вирус. После этого клетки "восстанавливают" новую структуру ДНК.}
{159}{}{А как можно подхватить ВРЭ?}
{160}{}{Почему ВРЭ не подвержен воздействию радиации?}
{161}{}{Если ВРЭ инфицирует свою жертву ассимилированными образцами вируса, то как они становятся "лучшими особями"?}
{162}{}{ВРЭ как таковой нельзя "подхватить". Он не передается респираторно-капельным путем. Как правило, заражение происходит при помощи инъекции или прямого физического контакта с образцом ВРЭ.}
{163}{}{Давай обсудим еще кое-что, хорошо?}
{164}{}{Почему ВРЭ не подвержен воздействию радиации?}
{165}{}{Если ВРЭ инфицирует свою жертву ассимилированными образцами вируса, то как они становятся "лучшими особями"?}
{166}{}{ВРЭ - это мегавирус, защищенный белковой оболочкой, укрепленной ионизированными молекулами водорода. В связи с этим он способен поглощать нейтроны, не становясь при этом радиоактивным.}
{167}{}{Можем мы поговорить еще кое о чем?}
{168}{}{Если ВРЭ инфицирует свою жертву ассимилированными образцами вируса, то как они становятся "лучшими особями"?}
{169}{}{ВРЭ изначально запрограммирован интронами улучшенных ДНК, соответствующих видов живых существ. Исходя из них, вирус пытается корректировать ДНК индивида.}
{170}{}{Однако, поскольку ВРЭ частично зависит от ДНК индивида и включает ее части в состав собственного рекурсивного кода, результаты могут быть непредсказуемы.}
{171}{}{В случае инфицирования индивида с существенными генетическими повреждениями, полученными в результате радиоактивного облучения, например, вирус вызовет крайне интенсивную перестройку всех систем организма, что может привести к дисфункции жизненно-важных органов и, таким образом, к смерти.}
{172}{}{В генетически жизнеспособном индивиде, вирус переписывает части ДНК, вызывая ускоренную мутацию, обычно ведущую к рекурсивному росту из-за собственных образцов ВРЭ.}
{173}{}{Такой рекурсивный рост ведет к увеличению мускульной и мозговой массы, но часто сопровождается обезображиванием и повреждением существующих нейронных связей, что вызывает потерю памяти.}
{174}{}{Существуют ли долгосрочные побочные эффекты воздействия ВРЭ?}
{175}{}{Можно ли исправить ВРЭ-мутацию при помощи антивируса?}
{176}{}{Давай сменим тему.}
{177}{}{Спасибо за рассказ.}
{178}{}{Поскольку ВРЭ вызывает постоянную регенеративную модернизацию ДНК, он может сделать индивида практически бессмертным, поскольку смерть клеточной ткани будет с избытком возмещена искусственным ростом.}
{179}{}{И, наконец, поскольку гаметы репродуктивной системы обладают двойной ДНК и являются своего рода "полу-клетками", они, скорее всего, будут восприняты вирусом как "поврежденные", и ВРЭ "восстановит" их, сделав, таким образом, объект исследования бесплодным.}
{180}{}{Тем не менее, поскольку моя лабораторная база безнадежно повреждена, все эти выводы - предположительны. Я не могу представить физических доказательств. Тебе придется, как это говорят люди, "поверить мне на слово".}
{181}{}{Можно ли исправить ВРЭ-мутацию при помощи антивируса?}
{182}{}{Давай сменим тему.}
{183}{}{Спасибо за рассказ.}
{184}{}{Нет, нельзя. ВРЭ не сохраняет неизменные первоначальные копии ДНК объекта. Отменить результаты его воздействия сможет только вирус, снабженный первоначальной ДНК объекта. К тому же не существует никакого известного средства удалить из организма сам ВРЭ.}
{185}{}{Существуют ли долгосрочные побочные эффекты воздействия ВРЭ?}
{186}{}{Давай сменим тему.}
{187}{}{Спасибо за рассказ.}
{188}{}{Мои датчики в настоящее время полностью отказали в наземной части комплекса и на уровнях с первого по третий. Тем не менее, я могу снабдить тебя описаниями уровней с четвертого по шестой.}
{189}{}{Уровень четыре.}
{190}{}{Уровень пять.}
{191}{}{Уровень шесть.}
{192}{}{Ничего.}
{193}{}{Уровень четыре: Исследовательский блок. На этом уровне находились испытательные полигоны и лаборатории для проведения экспериментов в области в биологии и физики.}
{194}{}{Расскажи мне об уровне пять.}
{195}{}{Расскажи мне об уровне шесть.}
{196}{}{Погоди, повтори еще раз.}
{197}{}{Спасибо.}
{198}{}{Уровень пять: Секретные испытательные лаборатории. На этом уровне находились лаборатории для экспериментальных испытаний опытных образцов и исследовательские лаборатории для секретных объектов. Именно такие объекты обеспечили необходимый стимул для разработки ВРЭ.}
{199}{}{Расскажи мне об уровне четыре.}
{200}{}{Расскажи мне об уровне шесть.}
{201}{}{Погоди, повтори еще раз.}
{202}{}{Спасибо.}
{203}{}{Уровень шесть: Казармы и Центральное управление. Тут находились жилые помещения для персонала и военного контингента комплекса, а также конференцзал.}
{204}{}{Расскажи мне об уровне четыре.}
{205}{}{Расскажи мне об уровне пять.}
{206}{}{Погоди, повтори еще раз.}
{207}{}{Спасибо.}
{208}{}{Несколько дверей потребуют использования определенной карты доступа. Тебе придется физически найти их местонахождение и использовать нужную карту.}
{209}{}{Тем не менее, я контролирую вторичные электронные замки на стендах с оружием. Я их открою. Но тебе все равно понадобится красная карта доступа, чтобы открыть их.}
{210}{}{Вы не зарегистрированы как пользователь с достаточными правами доступа, чтобы получить эту информацию.}
{211}{}{Впрочем, датчики указывают, что это комплекс уже невозможно использовать в первоначальном объеме. Наиболее вероятная причина - разрушение ядерным взрывом. В связи с этим, вопросы безопасности теперь не важны.}

{300}{}{Эта система слишком сложна для вас.}
