{100}{}{Вы видите Дарелла.}
{101}{}{Вы видите паладина.}
{102}{}{Приветствую, добро пожаловать в Братство Стали.}
{103}{}{Ы...}
{104}{}{А что такое Братство Стали?}
{105}{}{Не знаешь, где можно найти водяной чип?}
{106}{}{Знаешь что-нибудь о пропавших караванах?}
{107}{}{Прощай.}
{108}{}{(Смеется над вами.) Дружище, вряд ли у тебя есть хоть малейший шанс попасть сюда. Одно из наших требований - определенный уровень умственного развития.}
{109}{}{Э... Да нет, просто люди даже не хотят понять, чем мы занимаемся.}
{110}{}{Братство - это сообщество людей, посвятивших свою жизнь накоплению технических знаний.}
{111}{}{А мне говорили, вы приносите в жертву щенков.}
{112}{}{А что это за броня на тебе?}
{113}{}{Как бы мне побольше узнать о ваших технологиях?}
{114}{}{Прощай!}
{115}{}{Нет, никогда о таком не слышал. Может, кто-то из писцов знает. Тебе стоит спросить у них... ну, если ты к нам присоединишься.}
{116}{}{Присоединюсь? А как это сделать?}
{118}{}{Да вы, ребята, ничего толком не знаете.}
{119}{}{Приносим в жертву щенков! Кто это тебе сказал такую глупость? Не верь тому, что болтают всякие психи в пустыне.}
{120}{}{А по-моему, это здорово.}
{121}{}{Извини, кажется, ты расстроился.}
{122}{}{По-твоему, все жители пустыни - психи?}
{123}{}{Единственный способ узнать о нас побольше - это присоединиться к Братству. Мой друг Кэббот тебе поможет.}
{125}{}{А у вас в Братстве есть водяной чип?.}
{126}{}{Об этом тебе лучше поговорить с Кэбботом.}
{127}{}{А что такое вообще Братство Стали?}
{128}{}{Да нет, ничего... Обидно, что люди не понимают, чем мы вообще занимаемся.}
{129}{}{А чего тут понимать?}
{130}{}{Ребята, по-моему, вы слегка с приветом.}
{131}{}{Технология. Это единственное, что стоит изучения. Присоединяйся к нам, и ты все узнаешь!}
{132}{}{А как вступить в Братство?}
{133}{}{You people are too strange for me.}
{134}{}{Жаль это слышать.}
{135}{}{Это силовая боевая пехотная броня модели T-51b или, проще говоря, силовая броня.}
{136}{}{Я уже сто лет хожу по пустыне, но такой брони мне никогда не встречалось.}
{137}{}{Похоже, она страшно неудобная.}
{139}{}{Члены Братства - единственные обладатели силовой брони во всей пустыне. Только отличившимся братьям и рыцарям высочайшего ранга разрешено ее носить.}
{140}{}{Но почему она мне не встречалась раньше?}
{141}{}{How does one join the Brotherhood?}
{143}{}{Язычники пытались похитить у нас броню, но, к счастью, у них ничего не получилось. Они были готовы убить одного из наших братьев, но в таком случае броня пришла бы в негодность.}
{144}{}{I think I'll try to take it off your cold, dead body.}
{145}{}{Пока!}
{146}{}{А щенка в жертву приносить придется?}
{147}{}{Неудобная? Ничего подобного. Священная броня сконструирована таким образом, что является как бы продолжением тела. Она многократно увеличивает нашу силу и защищает от облучения. Без брони я чувствовал бы себя практически беспомощным.}
{148}{}{А как так получилось, что больше ни у кого нет такой брони?}
{149}{}{Хочу такую же. Запишите меня.}
{151}{}{Если хочешь вступить в Братство, тебе нужно поговорить с Кэбботом.}
{152}{}{Поверить не могу. Его отправляют туда?}
{153}{}{Поверить не могу. Ее отправляют туда?}
{154}{}{So you took the famous Glow Quest, huh? *chuckle*}
{155}{}{Да нет... Я иду в Древний Орден.}
{156}{}{Свечение? Это еще что?}
{157}{}{Не твое дело, куда я иду.}
{158}{}{Ага. Пока!}
{159}{}{Свечение и Древний Орден - это одно и то же. И это очень скверное место.}
{160}{}{С чего вдруг?}
{161}{}{А что, по-моему, ничего сложного. Мне просто нужно принести оттуда что-нибудь. Старики испытывают салагу, так всегда бывает.}
{162}{}{А откуда взялись два названия?}
{163}{}{А что в этом месте такого особенного?}
{164}{}{Люди называют это место Свечением. В древности там разрабатывалось самое совершенное оружие. По крайней мере, так утверждают древние записи. А выглядит это как кратер, в котором столько радиации, что он даже светится. Я думаю, старейшины посылают туда новичков, просто чтобы избавиться от них.}
{165}{}{А что, до меня туда еще кто-то ходил?}
{166}{}{Я иду в Древний Орден. Где он находится?}
{167}{}{Твоя правда. Не стоит мне совать нос в чужие дела.}
{168}{}{Восемнадцать дней пути к юго-востоку отсюда. Хуже всего, что там сильная радиация. Поэтому никто из нас туда и не ходит. Если не запастись Рад-Х, поджаришься еще на подходе к котловану.}
{170}{}{Слушай, давай по-честному...}
{171}{}{Люди считают, что это просто большая радиоактивная яма, поэтому ее и называют Свечением или "горячей точкой". Но мы-то в Братстве знаем правду. Древние записи гласят, что это место - источник всех наших научных знаний. Кто знает, что еще там есть?}
{173}{}{Слушай, давай по-честному...}
{174}{}{Да, кое-кто пытался. И больше мы их не видели.}
{175}{}{Черт, ты меня почти отговорил. Что-то мне уже не очень хочется вступать в Братство.}
{176}{}{Они были слабаками. Увидимся!}
{177}{}{Чего следует опасаться, когда я спущусь туда?}
{179}{}{Свечение и Древний Орден - это одно и то же.}
{180}{}{Что такое Свечение?}
{181}{}{Не хочу вводить тебя в заблуждение. Братство - отличное место, самое безопасное во всей пустыне. Ты нигде не найдешь брони и оружия лучше, чем у нас. Мы служим технологии, а технология служит нам.}
{182}{}{Впечатляет. Ладно, я пойду.}
{183}{}{Расскажи мне о Свечении.}
{184}{}{Боюсь, для меня это слишком проблемное место.}
{185}{}{Что?..}
{186}{}{А почему у Древнего Ордена два названия?}
{187}{}{Где находится Древний Орден, и каких опасностей там можно ожидать?}
{188}{}{Можно задать тебе пару вопросов?}
{189}{}{Люди считают, что это просто большая радиоактивная яма, поэтому ее и называют Свечением или "горячей точкой". Но мы-то в Братстве знаем правду. Древние записи гласят, что это место - источник всех наших научных знаний. Кто знает, что еще там есть?}
{190}{}{У меня еще вопрос.}
{191}{}{Чем я могу помочь?}
{192}{}{Ладно, пока!}
{193}{}{Конечно, спрашивай.}
{194}{}{Привет!}
{195}{}{Да, недавно сюда приходил сам Рутгер, выходит, дело серьезное. Он хочет выяснить, что случилось с пропавшими караванами. Не представляю, что бы это могло быть. Люди заметили что-то странное у Хаба, но не успели это рассмотреть. Все это меня очень тревожит. Надеюсь, скоро проблема разрешится.}
{196}{}{А мне говорили, вы приносите в жертву животных! Может, вы используете караваны в своих темных ритуалах?}
{197}{}{А сам-то ты что думаешь?}
{198}{}{Ну, если что-нибудь узнаешь, скажи мне. Хочу все выяснить!}
{199}{}{Ничего конкретного. Думаю, кто-то играет не по правилам... Хотя, с другой стороны, в пустыне много опасных существ. На караван могла напасть какая-нибудь тварь или даже целая стая. Надеюсь, тебе это поможет. Хорошего дня.}

{201}{}{Спасибо. Пока!}
{202}{}{Okay, thanks. Bye.}
{203}{}{Спасибо за информацию. Пока!}
{204}{}{Спасибо, пока!}
{205}{}{О'кей... Спасибо за информацию.}
{206}{}{Благодарю за предупреждение. Пока!}
{207}{}{Спасибо. Пока!}
{208}{}{Спасибо, что уделил мне время.}

{209}{}{Если тебе нужно оружие получше, попробуй сходить к Свечению. Это на юге. (Дарелл показывает на юг.)}
{210}{}{Вот, возьми Рад-Х. (Дарелл дает вам таблетки.)}
{211}{}{Надо глотать. (Дарелл делает вид, что глотает таблетки, и хлопает себя по животу.) Вкуснятина!}
{212}{}{Погоди, погоди, пока не надо! (Дарелл не дает вам принять таблетки.) Прими их, когда будешь подходить к Свечению.}
{300}{}{[ЕЩЕ]}
