{100}{}{Вы видите умирающего мутанта.}
{101}{}{Мутант умирает.}
{102}{}{Вы видите тело мутанта.}
{103}{}{Мутант мертв.}
{104}{}{Так быстро... Мои братья погибли... Не смог помочь...}
{105}{}{Кто ты?}
{106}{}{Я, я... не помню... Командир... Это... Мой диск... [Мутант из последних сил протягивает вам окровавленный диск.]}
{107}{}{Откуда вы?}
{108}{}{Мы... Мы были разведчиками... Пришли... Пришли с северо-запада.}
{109}{}{Кто вас послал?}
{110}{}{Отец... Где ты, отец?... Да, Создатель... [Мутант испускает последний вздох и умирает.]}
{111}{}{О-о-о-о.... А-а-а-а...}
{112}{}{Создатель...}
{113}{}{Братья... Где?..}
