{100}{}{Вы видите паладина Фарли.}
{101}{}{Приветствую.}
{102}{}{Чед'ра чу ка?}
{103}{}{Катя чу ни ка чак'ра Фарли.}
{104}{}{Фарли, ни ко }
{105}{}{ мат'чак о Дрейк.}
{106}{}{А, Дрейк ко мат'чак.}
{107}{}{Если еще увидишься с нашим общим другом, передай ему привет.}
{108}{}{Братство напоминает мне родной дом.}
