{100}{}{Вы зажигаете фонарик.}
{101}{}{Этот фонарик не работает.}
{102}{}{Кончилось горючее, и фонарик погас.}
{103}{}{Вы видите горящий фонарик.}
{104}{}{Вы видите израсходованный фонарик.}
{105}{}{Вы видите фонарик.}
