{100}{}{Вы видите Фрая, помощника шерифа.}
{101}{}{Хорошо, что я тебя встретил, детоубийца. Надеюсь, ты скоро покинешь наш город. А пока ты здесь, я буду лично присматривать за тобой. Веди себя тише воды, ниже травы! Если что, отправлю на тот свет без колебаний!}
{102}{}{Приветствую! Помощник шерифа Тони Фрай к вашим услугам.}
{103}{}{Где я?}
{104}{}{Приятно познакомиться. До свидания.}
{105}{}{Уа-ы.}
{106}{}{Эк!}
{107}{}{О, у нас гости! Добро пожаловать в Хаб - крупнейший город на побережье, а может, и во всем мире. Тебя, наверное, подвезли караванщики, да?}
{108}{}{Да.}
{109}{}{Нет.}
{110}{}{Ну разумеется! Новые жители прибывают сюда только с караванами. Хотя у караванщиков сейчас тяжелые времена... Но вообще, у нас тут хорошо, особенно если не связываешься с кем попало. Люди вроде Декера и его головорезов могут доставить кучу проблем.}
{111}{}{У, надо же! В окрестностях города сейчас неспокойно, да что там - у нас целые караваны пропадают... Но здесь ты в безопасности. Главное - держись подальше от "Мальтийского сокола". От этих ублюдков одни неприятности... Я имею в виду Декера и его подручных.}
{112}{}{Кто такой Декер?}
{113}{}{Ну, мне бояться нечего.}
{114}{}{У вас пропадают караваны?}
{115}{}{А где у вас можно заработать?}
{116}{}{Да нет, спасибо.}
{117}{}{Наверное. Еще что-нибудь хочешь узнать?}
{118}{}{Это настоящая беда! Несколько караванов бесследно исчезли. Бутч, глава гильдии Дальнобойщиков, пообещал награду за любую полезную информацию. Поспрашивай об этом в торговом квартале!}
{119}{}{Он владелец бара "Мальтийский сокол" в торговом квартале. Не советую с ним связываться, если тебе не нужны неприятности. Он хладнокровный убийца, но шериф не позволяет его арестовать без доказательств.}
{120}{}{Без проблем. У нас в городе вполне безопасно, наши полицейские - опытные ребята. У тебя здесь не будет никаких трудностей, главной - не суйся в "Мальтийский сокол".}
{121}{}{Извини, не понимаю. Может, тебе к доктору сходить? Чада Собора к югу отсюда - нужно только пройти через торговый квартал.}
{122}{}{Я слежу за тобой, детоубийца.}
{123}{}{Кровожадное чудовище!}
{124}{}{Боже мой! Шериф мертв...}
{125}{}{Вот ты где, подлюга! Я чуть тебя не упустил. Охрана!}
{126}{}{Конечно.}
{127}{}{Поймай меня, если сможешь!}
{128}{}{Нет.}
{129}{}{Арг!}
{130}{}{Привет еще раз. Тебе у нас нравится? Мы всегда рады крепким ребятам вроде тебя. Если поселишься у нас, ты не пожалеешь.}
{131}{}{Привет еще раз. Тебе у нас нравится? Мы всегда рады симпатичным девушкам вроде тебя. Если поселишься у нас, ты не пожалеешь.}
{132}{}{Привет еще раз. Чем могу помочь?}
{133}{}{Я не могу болтать с тобой целый день. Мне нужно следить за порядком.}
{134}{}{Мне нужно сообщить о преступлении!}
{135}{}{У вас есть больница? Меня ранили.}
{136}{}{Где у вас магазины?}
{137}{}{Where do I find work around here?}
{138}{}{Пока!}
{139}{}{Гар-ро?}
{140}{}{У-уга.}
{141}{}{Вот как? Я... э-э, тебе надо поговорить с шерифом. Я не могу покинуть свой пост. Мне надо следить за тем, чтобы налетчики на нас внезапно не напали. И к тому же, я плохо составляю протоколы.}
{142}{}{О, извини! Не заметил. Чада Собора обитают в больнице неподалеку от конторы торговцев водой. Иди на юг, мимо торгового квартала, и ты не ошибешься. Надеюсь, все обойдется!}
{143}{}{Магазины находятся в торговом квартале - это в минуте ходьбы отсюда по направлению к югу. Основная торговля идет в северной части квартала.}
{144}{}{Спроси в торговом квартале - это к югу отсюда. Там держат конторы три гильдии караванщиков. Рекомендую Дальнобойщиков - они хорошо платят и не такие чокнутые, как все остальные.}
{145}{}{Мертвы... Все мертвы...}
{146}{}{Пф-ф... Хр-р-р...}
{147}{}{Не знаешь, где бы мне найти водяной чип? В моем убежище он сломался, и нам срочно нужен новый.}
{148}{}{Водяной чип? Хм, никогда о таком не слышал. Думаю, тебе лучше обратиться к торговцам водой. Их контора на южной стороне, за торговым кварталом.}
