{100}{}{Вы видите крупного мужчину с оружием в руках.}
{101}{}{Это Габриель, главный оружейник.}
{102}{}{Нечасто к нам заходят посетители. Чем могу помочь?}
{103}{}{Почему нечасто?}
{104}{}{Чем вы занимаетесь?}
{105}{}{Недалеко от нас находится логово проклятых Когтей Смерти.}
{106}{}{Вы прекрасно вооружены, почему бы вам их не перестрелять?}
{107}{}{Мы пытались, но они снова откуда-то появляются. Да и потом, мы ведь оружейники, а не охотники.}
{108}{}{А что мне перепадет, если я уничтожу Когтей для вас?}
{109}{}{Мы производим оружие и боеприпасы. Мы занимаемся этим вот уже тридцать лет. Последние десять из них были для нас сущим адом.}
{110}{}{Почему?}
{111}{}{Мы собрали вокруг цеха весь металлолом, который остался здесь после войны. Теперь сырье нам поставляет Адитум, мы полностью зависим от него.}
{112}{}{Разве это плохо?}
{113}{}{Вначале все было прекрасно. Они приносили нам сырье, а мы делали и продавали оружие. Но три года назад Циммерман нанял каких-то бандитов, чтобы защищать Адитум от Когтей Смерти и налетчиков. Эти ублюдки Регуляторы теперь наживаются на нас. Мы делаем оружие, а они на этом богатеют.}
{114}{}{Почему бы вам не обосноваться где-нибудь в другом месте?}
{115}{}{Мда. А что я получу, если разберусь с Когтями Смерти?}
{116}{}{Если бы все было так просто... Нам пришлось бы перевезти все станки и оборудование. Это само по себе нелегко, а уж когда рядом Когти Смерти - просто нереально.}
{117}{}{Вы прекрасно вооружены, почему бы вам их не перестрелять?}
{118}{}{Если ты сможешь избавить нас от Когтей Смерти раз и навсегда - называй любую цену!}
{119}{}{Я хочу оружие с боеприпасами, и побольше!}
{120}{}{}
{121}{}{Если уничтожишь Когтей Смерти, мы уйдем отсюда и оставим столько оружия и боеприпасов, что тебе на всю жизнь хватит!}
{122}{}{О'кей, договорились.}
{123}{}{Мне надо это обдумать.}
{124}{}{Ага. Это поможет решить все проблемы с Адитумом.}
{125}{}{Уничтожишь Когтей Смерти - и считай, что сделка состоялась.}
{126}{}{Okay. I'll do it.}
{127}{}{Мне надо это обдумать.}
{128}{}{Приветик!}
{129}{}{Чем вы занимаетесь?}
{130}{}{Пока!}
{131}{}{}
{132}{}{It's been going okay.}
{133}{}{Благодаря мне все Когти Смерти мертвы.}
{134}{}{Нам нужно знать наверняка. За последние два года мы прикончили их штук двадцать, но каждый раз откуда-то появлялись новые. Если Когтей не будет в течение нескольких дней - проси все, что угодно.}
{135}{}{Okay, thanks}
{136}{}{Дай знать, когда избавишь нас от Когтей Смерти.}
{137}{}{Ага. Может, еще увидимся!}
{138}{}{Я знаю, расскажи мне об этом.}
{139}{}{Может, еще увидимся!}
{140}{}{Нечасто к нам заходят посетители. Чем могу помочь?}
{141}{}{Почему нечасто?}
{142}{}{Чем вы занимаетесь?}
{143}{}{Недалеко от нас находится логово проклятых Когтей Смерти.}
{144}{}{Мне удалось уничтожить Когтей Смерти и все их проклятые яйца!}
{145}{}{Если бы все было так просто... Нам пришлось бы перевезти все станки и оборудование. Это само по себе нелегко, а уж когда рядом Когти Смерти - просто нереально.}
{146}{}{Мне удалось уничтожить Когтей Смерти и все их проклятые яйца!}
{147}{}{}
{148}{}{Я хочу оружие с боеприпасами, и побольше!}
{149}{}{}
{150}{}{Мне не нужна оплата.  Достаточно вашей благодарности.}
{151}{}{Вот наша благодарность - бери все, что захочешь. На сборы у нас уйдет день или два. Мы оставим здесь столько оружия и боеприпасов, что ты за один прием не унесешь. Приходи в любое время и забирай все, что захочешь.}
{152}{}{}
{153}{}{}
{154}{}{Спасибо.}
{155}{}{}
{156}{}{Никаких проблем.}
{157}{}{}
{158}{}{}
{159}{}{Вы разве еще не уехали?}
{160}{}{Хочу подобрать себе кое-что. Что у вас есть?}
{161}{}{Ничего, спасибо.}
{162}{}{}
{163}{}{Отлично. Что у вас есть?}
{164}{}{Ну, еще увидимся.}
{165}{}{}
{166}{}{Хочу подобрать себе кое-что. Что у вас есть?}
{167}{}{Ничего, спасибо.}
{168}{}{Извини, некогда разговаривать, дел по горло.}
{169}{}{Guns! I like guns!}

#
# TRANSLATION NOTE: The following three sets of lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#
{170}{}{Моим друзьям тоже пригодилось бы новое оружие.}
{171}{}{Моим друзьям тоже пригодилось бы новое оружие.}
{172}{}{Как дела, дружище?}
{173}{}{Как дела, дружище?}
{174}{}{Что? Всех Когтей? Слава Богу! Теперь мы можем уехать отсюда! Мы поселимся ближе к источникам сырья и не будем зависеть от этих гадов из Адитума. Теперь проси все, что угодно!}
{175}{}{Что? Всех Когтей? Слава Богу! Теперь мы можем уехать отсюда! Мы поселимся ближе к источникам сырья и не будем зависеть от этих гадов из Адитума. Теперь проси все, что угодно!}
{176}{}{Все честно. Торговать с тобой - одно удовольствие.}
{177}{}{Все честно. Торговать с тобой - одно удовольствие.}
{178}{}{Без проблем. Скажи своим друзьям, что они тоже с пустыми рукам не уйдут.}
{179}{}{Без проблем. Скажи своим друзьям, что они тоже с пустыми рукам не уйдут.}
{180}{}{Благодарю.}
{181}{}{Благодарю.}
{182}{}{Прости, мы сейчас заняты подготовкой к переезду. Забирай все, что тебе нужно.}
{183}{}{Прости, мы сейчас заняты подготовкой к переезду. Забирай все, что тебе нужно.}
{184}{}{Теперь мы можем и не уезжать, ведь твои друзья разобрались с Регуляторами.}
{185}{}{Теперь мы можем и не уезжать, ведь твои друзья разобрались с Регуляторами.}
{186}{}{Добро пожаловать! Я могу чем-то помочь?}
{187}{}{Добро пожаловать! Я могу чем-то помочь?}

#
# Following Line is just to be translated normally.
#
{188}{}{Поговори с Заком, если хочешь что-то купить.}
