{100}{}{Uh-oh.}
{101}{}{Вы наткнулись на ???газовую ловушку и получили 1 единицу урона.}
{102}{}{Вы наткнулись на ???газовую ловушку и получили }
{103}{}{ ед. урона.}
{104}{}{You set off a gas trap!}
