{100}{}{Стой!}
{101}{}{Умри, человек!}
{102}{}{Смерть.}
{103}{}{Ты заплатишь за свои грехи!}
{104}{}{Здесь нельзя носить оружие, братишка. В чем дело?}
{105}{}{Здесь нельзя носить оружие, сестренка. В чем дело?}
{106}{}{Хнг.}
{107}{}{Все в порядке, я здесь работаю.}
{108}{}{Все в порядке, у меня есть пропуск.}
{109}{}{Лейтенант разрешил мне носить оружие.}
{110}{}{А что в этом такого?}
{111}{}{Then show me your pass.}
{112}{}{Э-э, он остался в другой одежде.}
{113}{}{Посмотри в ствол, он прямо там.}
{114}{}{Давай, поторапливайся. Учти, я буду за тобой присматривать.}
{115}{}{Хорошо, братишка. Я могу тебе помочь?}
{116}{}{Хорошо, сестренка. Я могу тебе помочь?}
{117}{}{Гм.}
{118}{}{А где сидит этот, как его... Создатель?}
{119}{}{Воздай молитву Единению, брат.}
{120}{}{Извини, но каждый сам ищет свой путь к Единению.}
{121}{}{Языческое ничтожество! Ты заплатишь за свои грехи!}
{122}{}{На третьем уровне, как обычно. Что за странный вопрос?}
{123}{}{А, м-м, так, просто.}
{124}{}{Я хочу всыпать ему по первое число!}
{125}{}{Какой вопрос? Я говорю: "До свидания, слава Создателю!"}
{126}{}{Ты оскорбляешь меня! Умри!}
{127}{}{Восхвали Единение.}
{128}{}{Твой голос звучит неуверенно. Почему? Может быть, ты отступаешь от пути добродетели?}
{129}{}{Ты принял дрожь в моем голосе за страх, но я просто дрожу от холода.}
{130}{}{Такие, как ты, обречены. Мои друзья помогут доказать это...}
{131}{}{Когда ты станешь одним из нас, тебя перестанет это беспокоить. Иди.}
{132}{}{Что еще? У меня нет времени на разговоры.}
{133}{}{Лаб-бо!}
{134}{}{У тебя нет времени на жизнь... Умри!}
{135}{}{Нет, ничего.}
{136}{}{Воздай молитву Единению, брат.}
{137}{}{Да кто ты? Ну-ка... А-а-а! Незваные гости!}
{138}{}{Делай свое дело во имя Единения и не мешай мне!}
{139}{}{Проходи.}
{140}{}{Займись делом.}
