{100}{}{Привет! Чем могу помочь?}
{101}{}{Кто ты?}
{102}{}{Что ты делаешь?}
{103}{}{??? Давай сюда все свое добро!}
{104}{}{Уб!}
{105}{}{Меня зовут Локс. Я торговец.}
{106}{}{Меня зовут Терранс, я странствующий торговец.}
{107}{}{Меня зовут Джулиан, я приторговываю разным барахлом.}
{108}{}{Меня зовут Дейл, я торгую разным хламом.}
{109}{}{Я иду в Адитум, чтобы кое-что продать.}
{110}{}{Я направляюсь в Джанктаун, поторговать.}
{111}{}{Я везу товары в Хаб.}
{112}{}{Я иду в Некрополь, посмотреть, как там дела.}
{113}{}{А-ак!}
{114}{}{Не возражаешь, если я пойду с тобой?}
{115}{}{Пойдем, конечно. Вместе веселей.}
{116}{}{Sorry, we already have enough people to make the trip safely.}
{117}{}{Извини, но я тебе не доверяю.}
