{100}{}{Вы видите жителя убежища.}
{101}{}{Как себя чувствуешь после предательства?}
{102}{}{Бездушное чудовище!}
{103}{}{Я тебя ненавижу. Что ты вообще здесь делаешь?!}
{104}{}{Надеюсь, твоя подлость тебя погубит!}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{Спасибо за наше спасение!}
{110}{}{Никто не думал, что ты справишься, но теперь я тебе верю.}
{111}{}{Спасибо! Спасибо!}
{112}{}{Ты герой. Мой сынишка мечтает стать таким же, как ты. Правда, не знаю, понравится ли мне это...}
{113}{}{Ты совершила подвиг. Моя дочурка мечтает стать такой же, как ты. Правда, не знаю, понравится ли мне это...}
{114}{}{Ты отличный парень!}
{115}{}{Ты удивительная девушка!}
{116}{}{Лучше не ходи здесь с оружием.}
{117}{}{Это же оружие!}
{118}{}{На тебя уже кто-нибудь нападал?}
{119}{}{Думаешь, стоит здесь ходить с оружием?}
{120}{}{Приятно снова с тобой увидеться.}
{121}{}{Хорошо, что с тобой все в порядке.}
{122}{}{Прекрасно выглядишь. Все эти слухи - полная ерунда.}
{123}{}{Привет, }
{124}{}{. Ты отлично справляешься. Так держать!}
{125}{}{Надеюсь, ты скоро найдешь чип. У нас осталось совсем мало воды.}
{126}{}{У нас кончаются запасы воды. Это ужасно!}
{127}{}{Найди чип как можно скорее. Иначе мы все умрем!}
{128}{}{Мы знаем, ты стараешься. Так держать!}
{129}{}{Мне страшно об этом думать, но без водяного чипа мы все умрем.}
{130}{}{Моя малышка плачет среди ночи и просит пить, но я ничего не могу ей дать.}
{131}{}{Боюсь, мы не выживем.}
{132}{}{Запасы воды кончаются.}
{133}{}{Нам нечем поливать овощи. Скоро у нас закончится еда.}
{134}{}{Хм. Кажется, внешний мир не испортил тебя. Наверное, снаружи не так уж плохо.}
{135}{}{Привет, }
{136}{}{.}
{137}{}{Надеюсь, ты справляешься со своим заданием.}
{138}{}{Увидимся.}
{139}{}{Смотритель давно беседовал с тобой?}
{140}{}{Смотритель очень обеспокоен.}
{141}{}{Поторопись. Мы не выживем, если ты не успеешь найти чип.}
{142}{}{Надеюсь, ты делаешь все возможное.}
{143}{}{Сейчас не время отдыхать. Возвращайся во внешний мир.}
{144}{}{Тебе сейчас нужно заниматься другими вещами.}
{145}{}{Если мы умрем, в этом будет твоя вина.}
{146}{}{Не теряй времени, возвращайся во внешний мир! Скорее!}
{147}{}{Гибель Убежища будет на твоей совести.}
{148}{}{Внешний мир дурно повлиял на тебя?}
{149}{}{Просто оставьте меня в покое.}
{150}{}{Оставь в покое меня и мою семью, }
{151}{}{. Так будет лучше.}
{152}{}{Тебе должно быть стыдно.}
{153}{}{Подумать только, когда-то мы дружили.}
{154}{}{С вами не хотят разговаривать.}
{155}{}{Вас встречают холодным молчанием.}
{156}{}{Жаль, что выбрали именно тебя.}
{157}{}{Вода грязная, но ты еще хуже.}
{158}{}{Уходи отсюда. Ты искупишь свою вину, только если найдешь водяной чип.}
{159}{}{Совесть тебя не гложет?}
{160}{}{С вами не хотят разговаривать.}
{161}{}{Все из-за тебя! Наверняка и сломанный чип - твоих рук дело!}
{162}{}{Я тебя ненавижу. Ненавижу.}
{163}{}{(Горько плачет.)}
{164}{}{Вас встречают холодным молчанием.}
{165}{}{Спасибо.}
{166}{}{Уже поздно. Поговорим утром.}
{167}{}{(Отдыхает.)}
