{100}{}{Ќа земле лежит бездыханное тело.}
{101}{}{«десь покоитс€ кто-то, кому не повезло.}
{102}{}{Ќа полу лежат останки мутировавшего человека.}
{103}{}{ѕахнет мертвечиной.}
{104}{}{Ётого человека подвел инстинкт саморазрушени€.}
