{100}{}{Эй!}
{101}{}{Убери оружие!}
{102}{}{Эй, у нас посторонний!}
{103}{}{Ты что здесь делаешь!}
{104}{}{Хватит тут ходить!}
{105}{}{Здесь не должно быть посторонних!}
{106}{}{Эй, ты чего тут прячешься? Убирайся отсюда!}
{107}{}{Что?}
{108}{}{Привет, можно вопрос?}
{109}{}{Одолжишь пару крышек?}
{110}{}{Нет, ничего.}
{111}{}{У-у-у?}
{112}{}{Я на посту. Давай побыстрее.}
{113}{}{Нет. Уходи.}
{114}{}{На кого ты работаешь?}
{115}{}{Что интересного в городе?}
{116}{}{Тебя мозгами обделили? Проваливай!}
{117}{}{Попрошайкам тут делать нечего!}
{118}{}{Выметайся!}
{119}{}{Нам здесь нищие не нужны.}
{120}{}{Гизмо - правильный босс. Хорошо платит, не зверствует. Будь проще и не создавай проблем!}
{121}{}{Советую сходить в "Выгребную яму" - это бар с неплохой выпивкой. Он открывается в четыре. Все, иди!}
{122}{}{Поторгуй с Киллианом. Его магазин к юго-востоку отсюда. Все, чеши отсюда!}
{123}{}{Поговори с крупье.}
{124}{}{Если хочешь поразвлечься, загляни в гостиницу и спроси Синтию. Она стоит своих денег!}
{125}{}{Никакого жульничества!}
{126}{}{В долг не даем.}
{127}{}{Черт, как шея болит...}
{128}{}{От работы кони дохнут.}
{129}{}{Мне здесь нравится.}
{130}{}{Наведаюсь-ка я к Синтии сегодня вечерком.}
{131}{}{Проваливай, безмозглое существо!}
{132}{}{Убери оружие!}
{133}{}{Эй, ты! Вали отсюда, живо!}
