{100}{}{Вы видите гуля, живущего под землей.}
{101}{}{Мы просто хотим, чтобы нас оставили в покое.}
{102}{}{Сет - дурак. Из-за него нас всех убьют.}
{103}{}{Мутанты когда-нибудь убьют нас всех, и Сет не поможет.}
{104}{}{Мы здесь прячемся. Никому о нас не рассказывай, ладно?}
{105}{}{Не нравится мне твоя рожа.}
{106}{}{Уходи. Оставь нас в покое.}
{107}{}{Слухи о тебе даже до нас доходят. Неужели это все правда?}
