{100}{}{Вы видите Билли.}
{101}{}{Эй! Оставь мои товары в покое!}
{102}{}{Привет!}
{103}{}{Привет, как делишки?}
{104}{}{Я хочу купить брамина.}
{105}{}{Привет. И пока.}
{106}{}{Арг!}
{107}{}{Та-а.}
{108}{}{А зачем тебе брамин? Ты что, караваны водишь? Хотя какая разница - они все равно не мои. Я просто пастух. Брамины принадлежат Дэну, а он их не продает.}
{109}{}{Почему?}
{110}{}{Да я шучу.}
{111}{}{Все из-за этих пропавших караванов. Теперь лишних браминов нет, слишком много их нужно для караванов. А остальных Дэн продает на мясо. Хотя я что-то заболтался... Дэн взбесится, если узнает, что я рассказываю все кому попало.}
{112}{}{Мда, ну ладно.}
{113}{}{Да ничем... Так, за браминами присматриваю.}
{114}{}{А зачем тебе копье? Они что, опасны?}
{115}{}{А кто такие брамины?}
{116}{}{'What's a brahmin?' You must be joking. Brahmin are one of the major food sources and forms of transportation around here. They haul the caravans. Dan says this is a really important job, but it sucks. Oh, and by the way, it's 'brahma' - brahmin is plural. Dork.}
{117}{}{Ну да, у меня просто из головы вылетело!}
{118}{}{Дэн прав. У тебя отлично получается.}
{119}{}{Ну да, все правильно. Удачи!}
{120}{}{Эй, ты на наркотиках, что ли?}
{121}{}{Правда? Ты правда так думаешь? О, спасибо.}
{122}{}{Ты не из этих мест, да? Я тебе дам один совет - смотри, не попадись на краже!}
{123}{}{Спасибо, учту.}
{124}{}{Я и не собираюсь воровать. Воровство - это плохо.}
{125}{}{Да, наверное. Это нормальная работа. Чем-то мне она даже нравится. Ладно, пойду я, пока не случилось чего.}
{126}{}{Прошу, не убивай меня и не трогай браминов.}
{127}{}{Не убивай меня!}
{128}{}{Прекрати!}
{129}{}{Оставь меня в покое!}
{130}{}{Прекрати!}
{131}{}{Эй, ты что делаешь? У меня нет ничего ценного.}
{132}{}{Прекрати!}
{133}{}{Опасны? Да нет. Могут укусить довольно сильно, но обычно они спокойные. Много рыгают и пускают газы. Не знаю, почему.}
{134}{}{Тогда зачем копье?}
{135}{}{О'кей, спасибо.}
{136}{}{Просто иногда они упрямятся. Тогда я легонько тыкаю копьем, чтобы сдвинуть их с места... И потом, я не хочу подходить слишком близко - они иногда лягаются. }
{137}{}{Слушай, не разговаривай со мной, а то Дэн опять разорется. Он дико бесится... в смысле, расстраивается, когда я отвлекаюсь от работы.}
{138}{}{Думаю, он так о тебе заботится. Работай лучше, и он будет добрее.}
{139}{}{Вот, малыш, возьми 50 баксов и уходи от этого урода.}
{140}{}{Ладно.}
{141}{}{А-а-а!}
{142}{}{Ы?}
{143}{}{Не нужно, мне и так проблем хватает.}
{144}{}{I AM working hard!}
{145}{}{Извини, я про другое. Думаю, Дэн просто хочет тебе помочь.}
{146}{}{Ничего подобного, лентяй!}
{147}{}{Ладно.}
{148}{}{Может, и так... Да он вообще-то нормальный мужик, только орет слишком много.}
{149}{}{Да, точно.}

# said to male player
{150}{}{Пошел ты, старый пердун!}
{152}{}{Ух ты! Мне этого хватит до конца жизни! Огромное спасибо, мистер!}

# said to female player
{151}{}{Пошла ты, старая карга!}
{153}{}{Ух ты! Мне этого хватит до конца жизни! Огромное спасибо, мэм!}

{154}{}{Ух ты! Спасибо... Но... Ты хочешь меня во что-то втянуть?}
{155}{}{Не говори со мной, а то Дэн бесится.}
{156}{}{Не волнуйся. Я поговорю с ним, он будет к тебе помягче.}
{157}{}{И правильно делает! Ты ужасный ребенок!}
{158}{}{О как.}
{159}{}{Привет!}
{160}{}{Эти девчонки вон там - дуры набитые.}
{161}{}{Привет еще раз.}
{162}{}{Брамины классные.}
{163}{}{Если буду хорошо работать, Дэн возьмет меня с собой в бар.}
{164}{}{Когда-нибудь я стану караванщиком!}
{165}{}{Вот вырасту и стану искать приключения.}
{166}{}{Правда? О, здорово! Только не покалечь его. Он ведь не такой уж плохой, просто орет много.}
{167}{}{Приветик!}
{168}{}{Повтори, пожалуйста: чем ты занимаешься?}
{169}{}{Я хочу купить брамина.}
{170}{}{Просто смотрю, как ты работаешь. Пока!}
{171}{}{Арг!}
{172}{}{Та-а.}
{173}{}{Мне надо работать.}
{174}{}{Эти девчонки вон там - дуры набитые.}
{175}{}{Привет еще раз.}
{176}{}{Вот вырасту и стану искать приключения.}
{177}{}{От браминов столько дерь... Ну, то есть, навоза.}
{178}{}{Я не могу сейчас говорить.}
{179}{}{Мне неприятности не нужны.}
