{100}{}{Вы видите Дарена Хайтауэра.}
{101}{}{Кто вы?!?  И кто вас впустил?}
{102}{}{У меня послание от друга.}
{103}{}{Ваша жизнь в опасности, мне надо с вами поговорить.}
{104}{}{Меня зовут }
{105}{}{.  Леон впустил меня.}
{106}{}{Мое имя?... Смерть!}
{107}{}{Я твой худший кошмар.}
{108}{}{Бобo?}
{109}{}{У меня нет друзей.  Что за послание?}
{110}{}{Декер передает вам привет.}
{111}{}{Мм... Боб меня послал... аа... он сказал, что ты ему должен 100 крышек и послал меня их забрать.}
{112}{}{На самом деле нет никакого послания, мне просто надо было вас увидеть.}
{113}{}{Я люблю тебя.}
{114}{}{Расскажи мне то, чего я не знаю, придурок!}
{115}{}{Придурок?  И как тебе помогать?  Иди к черту.}
{116}{}{Декер хочет твоей смерти, и он нанял меня для этого.}
{117}{}{Вы даже не догадываетесь, что сейчас фактически находитесь при смерти!}
{118}{}{Забудьте.  Мне хотелось помочь, ну да фиг с ним.}
{119}{}{Приятно было познакомиться }
{120}{}{.  Теперь мой помощник Леон проводит вас.}
{121}{}{Не знаю никакого Боба, но я возьму 100 крышек и ты сможешь уйти.}
{122}{}{Убирайся в ад!}
{123}{}{OK, ну и вот.  Спасибо, что уделил мне время.}
{124}{}{Эээ...  Этот УБЛЮДОК Боб дал мне мало денег!  Я добуду их для вас, мистер Хайтауэр, честное слово!}
{125}{}{Я люблю, когда ко мне домой приходят незнакомые люди и дают мне денег. Леон, покажи этому недоразумению дверь! Придешь еще раз, и мои охранники отрежут тебе голову тупым ножом!}
{126}{}{Леон, покажи этому глупцу, где двери! Появишься снова, и моя охрана спустит с тебя шкуру!}
{127}{}{Охрана!  Убийца!}
