{100}{}{Вы видите Рика, охранника.}
{101}{}{Чче' те' надо?}
{102}{}{Да... Ммм...}
{103}{}{Простите.  Могу я задать несколько вопросов?}
{104}{}{Башка на палочке!}
{105}{}{Прощай.}
{106}{}{Возвращайся в свой Истсайд, тупоголовый!}
{107}{}{Че?}
{108}{}{Уже иду.}
{109}{}{Давай побыстрее.  Не люблю болтать во время работы.}
{110}{}{Где я?}
{111}{}{Что у тебя за работа?}
{112}{}{Простите за беспокойство.  До свидания.}
{113}{}{Смотри, куда прешь, и на кого пасть разеваешь, свинья!}
{114}{}{НЕТ!  Лучше ты посмотри!  Сейчас моя пуля прилетит в твою голову!}
{115}{}{Ты не стоишь того, чтобы на тебя время тратить.}
{116}{}{Если ты не знаешь, тебе не следует здесь находиться. Это частные апартаменты. Мистер Хайтауэр живет здесь и встречается лишь с теми, с кем есть предварительная договоренность о встрече.}
{117}{}{Что у тебя за работа?}
{118}{}{Могу я назначить встречу с мистером Хайтауэром?}
{119}{}{Спасибо, что уделил мне время.}
{120}{}{Я здесь для того, чтоб мистера Хайтауэра не беспокоили.}
{121}{}{Что ж, меня интересует убийство мистера Хайтауэра. Время отрабатывать зарплату!}
{122}{}{Где я?}
{123}{}{Спасибо, что уделил мне время. Пока.}
{124}{}{Нет.}
{125}{}{Не нравится мне твое отношение. Тебе лучше уйти.}
{126}{}{Хорошо. Уже ухожу.}
{127}{}{Заставь меня, урод длинноволосый!}
{128}{}{На этой территории запрещено находиться после заката.  Другие охранники предупреждать не будут.  Если они тебя засекут, сразу откроют огонь на поражение.  Лучше вернись в Бизнес-центр пока твоя голова еще крепко держится на шее.}
{129}{}{оК.  идУ.}
{130}{}{неА.  оСтаюсЬ.}
{131}{}{Никуда я не пойду.}
{132}{}{Простите, меня уже здесь нет.}
{133}{}{Чудило, да ты тупее пробки, ты в курсе? Чеши отсюда!}
