{100}{}{Вы видите возницу.}
{101}{}{Денек сегодня будет тяжелый!}
{102}{}{Работать сегодня никак не могу.}
{103}{}{Надеюсь, что на нас не нападут налетчики... или кто похуже.}
{104}{}{Прости, нам больше не нужны охранники... наверно.}
{105}{}{Прости, вакансий нет.}
{106}{}{Если нужна работа, лучше поищи ее на рынке.}
{107}{}{Надеюсь, мы все продадим.}
{108}{}{Жду, не дождусь, когда мы закончим.}
{109}{}{Я готов надрать кое-кому задницу.}
{110}{}{Мы уходим!}
{111}{}{Сегодня будет жарко.}
{112}{}{Умираю от жажды.}
{113}{}{Какой сегодня день?}
{114}{}{Я уйду из Сокола, когда закончу все свои дела!}
{115}{}{Извини, но мы только вернулись.}
{116}{}{Если нужна работа, лучше поищи ее на рынке.}
{117}{}{Сегодня день расплаты!}
# 118 Bob's Iguana Bits
{118}{}{Я еду прямо к Бобу!}
{119}{}{Мне нужно сегодня вернуть долг!}
{120}{}{Я так устал.}
{121}{}{Это было долгое путешествие!}
