{101}{}{Торговцы из каравана все погибли. У них не было шансов.}
{102}{}{Похоже, что мутанты были хорошо вооружены. У торговцев не было шансов выжить под таким огнем.}
{103}{}{Они мертвы.}
{104}{}{Ты точно уверен что он мертв?}
{105}{}{Сквозь мутировавшие мышцы и плоть проглядывают знакомые черты. Это один из разведчиков, отправленных убежищем. Он так и не вернулся...}
{106}{}{Несмотря на мутировавшие мышцы и плоть, вам удается узнать в одном из мутантов Шона, одного из разведчиков, отправленных вашим убежищем за несколько месяцев до того, как ушли вы.}
{107}{}{Все мутанты мертвы. Черты одного из них кажутся вам странно знакомыми, но вы никак не можете вспомнить кто это.}
{108}{}{Мертвые мутанты.}
