{100}{}{Мы предлагаем исцеление тела ради исцеления души. Могу я тебе помочь?}
{101}{}{Да, помоги мне.}
{102}{}{Кто вы?}
{103}{}{А что случилось с теми, кто был здесь до тебя?}
{104}{}{Ыхн}
{105}{}{Все в порядке, дитя мое. Сейчас мы тебя осмотрим.}
{106}{}{Благословенны будь кроткие. С тобой все в порядке, дитя мое. Беги играй.}
{107}{}{Тебя вылечили. Впредь будь осторожнее.}
{108}{}{У тебя серьезные ранения.}
{109}{}{Кажется, у тебя серьезное отравление.}
{110}{}{О, следы радиации. К несчастью, мы это не лечим.}
{111}{}{Нам нужно пожертвование в размере $}
{112}{}{, прежде чем мы приступим к лечению. Тебя это устроит?}
{113}{}{Да.}
{114}{}{Нет.}
{115}{}{Но у меня нет таких денег!}
{116}{}{Ты возмешь, $}
{117}{}{ caps instead?}
{118}{}{Чада Собора не торгуются. Ты принимаешь нашу цену?}
{119}{}{Да. Конечно возьму.}
{120}{}{Ты можешь укусить меня!}
{121}{}{Спасибо, сын мой. Мы будем молиться за твое выздоровление}
{122}{}{Благодарю тебя, дочь моя. Помолимся за твое выздоровление.}
{123}{}{Ну вот. Мир и благословение Чад с тобой.}
{124}{}{У тебя не хватает денег. Если пожертвуешь нам все, что у тебя есть, мы вылечим тебя. Хорошо?}
{125}{}{Да.}
{126}{}{Нет.}
{127}{}{Если ты пожертвуешь нам все, что у тебя есть, мы вылечим тебя. Хорошо?}
{128}{}{Да.}
{129}{}{Нет.}
{130}{}{Твоих сбережений более чем достаточно. Советую подучить арифметику, дитя мое.}
{131}{}{Мы - Чада Собора. Мы живем и работаем среди этих горемык, живя в пустоши. Если ты когда-либо будешь в Могильнике, подойди к Собору.}
{132}{}{Спасибо.}
{133}{}{Чем ты занимаешься?}
{134}{}{Мы целители и учителя. Мы лечим тело, чтобы исцелить душу. Мы собираем лишь скромные пожертвования, чтобы оплатить расходы на лечение.}
{135}{}{Вы делаете важное дело.}
{136}{}{Дерьмо это, по-моему.}
{137}{}{Мы не нуждаемся в твоих оценках. Я вижу, тебе не интересна наша вера. Если тебе что-то понадобится, мы всегда здесь.}
{138}{}{Это святое дело. Мы трудимся, чтобы в этих бесплодных землях воцарился мир. Все существа должны жить в согласии друг с другом.}
{139}{}{Спасибо. Хорошего дня!}
{140}{}{Они подарили нам этот дом, чтобы мы могли нести слово народу и продолжать наше служение как целители.}
{141}{}{А Док Морбид не очень расстроен по этому поводу?}
{142}{}{Они очень добры. Спасибо.}
{143}{}{Что бы эта языческая душа ни испытывала, Чад это не касается. Мы здесь, чтобы исполнять свой долг, и мы его исполним.}
{144}{}{Ух, да-а, спасибо. Пока.}
{145}{}{Зачем ты это делаешь? Мы не причиним тебе вреда!}
{146}{}{Ты не в том состоянии, когда тебе потребовалась бы помощь.}
