{100}{}{Вы видите путешественника.}
{101}{}{Что тебе нужно?}
{102}{}{Кто ты?}
{103}{}{Что ты здесь делаешь?}
{104}{}{Где ближайший город?}
{105}{}{Ничем, спасибо.}
{106}{}{Uhh...}
{107}{}{Я - разведчик.}
{108}{}{Я слежу за приближением налетчиков и монстров.}
{109}{}{Джанктаун. Он недалеко отсюда.}
{110}{}{Вы видите охранника Джанктауна.}
