{100}{}{Вы сбежали из тюрьмы. Теперь в Джанктауне вы считаетесь беглым преступником!}
{101}{}{На вид дверь очень прочная, и на ней прочный замок. Несмотря на это, можно подобрать отмычки и выбить двери.}
{102}{}{Дверь заперта.}
{103}{}{Вы открываете дверь.}
{104}{}{Вы закрыли дверь.}
{105}{}{Вы не смогли открыть дверь.}
{106}{}{Вы не смогли закрыть дверь.}
{107}{}{You earn 250 experience for busting out of jail!}
