{100}{}{Вы видите огромного мутанта.}
{101}{}{Стой! Ты не сможешь убежать!}
{102}{}{Ты не имеешь права быть здесь. Сюда закрыт проход Чадам.}
{103}{}{Почему? Что это за место?}
{104}{}{У меня есть пропуск во все места - моя пушка!}
{105}{}{А?}
{106}{}{Ты говоришь слишком глупо, ты не Дитя Собора. Ты, наверно, засланец!}
{107}{}{Это отделение с камерами для заключенных. Здесь мы держим людей, прежде чем их купают... Классно, да?}
{108}{}{Что значит "Купают"?}
{109}{}{Ясно, спасибо.}
{110}{}{Ты должен уйти.}
