{100}{}{Вы видите разведчика гулей.}
{101}{}{Я не могу сейчас разговаривать. Я на посту.}
{102}{}{Человеческий шпион!}
{103}{}{Ты что здесь делаешь?}
{104}{}{Хмм, ничего особенного. А ты?}
{105}{}{Так, осматриваюсь.}
{106}{}{Хых.}
{107}{}{Э-э, да ничего. Живу я тут.}
{108}{}{Тебе здесь нечего искать. Уходи.}
{109}{}{[Готово]}
{200}{}{Мы не сможем выжить без воды.}
{201}{}{Пожалуйста, поговори с нашим лидером, прежде чем уйдешь.}
