{100}{}{Есть что-нибудь из еды?}
{101}{}{Ох, как я хочу есть. Сейчас бы браминбургеров...}
{102}{}{Мистер, пожалуйста, дайте мне поесть.}
{103}{}{Мэм, пожалуйста, дайте мне поесть.}
{104}{}{Как бы мне хотелось найти какой-нибудь еды.}
{105}{}{Я умираю от голода!}
{106}{}{Я буду работать за еду.}
{107}{}{Едааааа... дай еду сюда!}
