{100}{}{Вы видите крепкого невысокого мужчину с лохматой бородой.}
{101}{}{Вы видите МакРея.}
{102}{}{Привет, паренек, чего ты ищешь?}
{103}{}{Привет, девочка, чего ты ищешь?}
{104}{}{Ай, что ты еще хочешь узнать?}
{105}{}{Кто ты?}
{106}{}{Что ты знаешь про Клинков?}
{107}{}{Ничем, спасибо.}
{108}{}{Ну, я - МакРей, помогаю Клинкам драться против Когтей Смерти, ага, и этих Регуляторов. Учу их маленько как защищаться от всяких напастей.}
{109}{}{Чему ты их учишь?}
{110}{}{Ты видел Когтей Смерти?}
{111}{}{А что за дело с Регуляторами?}
{112}{}{Можно еще вопрос?}
{113}{}{Ну я-т специалист по кулачному бою, и могу выдать на пару тумаков больше, чем попадет по мне.}
{114}{}{Тупая идея, я лучше воспользуюсь пушкой.}
{115}{}{Ты смог бы меня чему-нибудь научить?}
{116}{}{Можно еще вопрос?}
{117}{}{Ну, коль ты так считаешь, можешь повернуться да уйти.}
{118}{}{Да, ты подходишь для этого. Но мое времечко все занято, я учу Клинков. Если дела-то пойдут на лад, нашел бы я для тя время.}
{119}{}{Хорошо. А можно вас спросить?}
{120}{}{Спасибо, что рассказал.}
{121}{}{Видел я их, ага. Бяжал, тока пятки сверкали. Если ж нужны они те, вон тама вон они. [МакРей показывает на восток]}
{122}{}{Я-то думал, что Когти Смерти - отродья супротив природы, а оказалось-то что это эти Регуляторы само зло. Раз в месяц приходют, рожи свои страшные кажут, да и уводят у каких-нибудь малюток отца родного.}
{123}{}{Я могу чем-нибудь помочь?}
{124}{}{Да, ужасно. Можно, я еще кое-что спрошу?}
{125}{}{Спасибо за рассказ.}
{126}{}{Ты хочешь с Бритвой потолковать. Хорошая девчонка, если такие бывают на свете.}
{127}{}{Хорошие ребята, эти Клинки. Им, конечно, не мед тут сидеть между чертовыми регуляторами и Когтями Смерти, но выживают как-то ж.}
{128}{}{[МакРей хлопает вас по спине] Спасибо тебе, теперича Клинки заживут получшее-то. Ну, что для тебя может сделать старый шотландский горец?}
{129}{}{Ты говорил, что если у тебя будет время, ты сможешь научить меня кое-чему.}
{130}{}{Чем ты занимался в последнее время?}
{131}{}{Что ты здесь делаешь?}
{132}{}{Да нет проблем.}
{133}{}{Ну, уж вот тихо было с тех пор как Клинки помогали Святилищу с Регуляторами.  Мое обучение еще никада не было в таком спросе.}
{134}{}{Чему ты можешь научить?}
{135}{}{Мне жаль это слышать, надеюсь, жить становится интереснее?}
{136}{}{Ты смог бы меня научить?}
{137}{}{Звучит заманчиво, но мне пора.}
{138}{}{Ну теперя-то у меня есть время.  А можно и прям сейчас-то и начать. [МакРей показывает вам несколько боевых позиций, и способы наносить удары как настоящий шотландец.]}
{139}{}{Шустро схватываешь. Надеюсь тебе это поможет в твоих странствиях.}
{140}{}{Ну я помощником ходил у Клинков, учил их хитростям всяким как защититься от Когтя Смерти и Регуляторов.  Теперь, когда ты с ними там разобрался, все как-то скучновато мне стало за последнее время-то.}
{141}{}{Рад, что свиделись.}
#
##Sduibek, Fallout Fixt:
#
{200}{}{You earn 250 experience for learning to brawl like a Scotsman.}
