{100}{}{ќсталось }
{101}{}{ сек.}
{102}{}{Ёто место гарантированной смерти.}
{103}{}{ќсталось }
{104}{}{ сек.}
{105}{}{Ёто место гарантированной смерти.}
{106}{}{ќсталось }
{107}{}{ сек.}
{108}{}{Ёто место гарантированной смерти.}
