{100}{}{Дверь закрыта. Для того, чтобы ее открыть необходим код доступа.}
{101}{}{Вы вводите код с пленки, и отпираете дверь.}
{102}{}{Дверь не заперта.}
{103}{}{Вы обходите код доступа и отпираете дверь.}
{104}{}{У вас не получается отпереть дверь.}
{105}{}{У вас не получается отпереть дверь. Возможно, будет проще, если вы используете набор электронных отмычек.}
{106}{}{Мощный взрыв, но на двери не появилось ни вмятин, ни царапин.}
