{100}{}{¬ы не можете себ€ заставить копатьс€ в этой куче кусков.}
{101}{}{’олодильник заполнен кусками органов и част€ми тел.}
{102}{}{ќрганы в холодильнике нарезаны небольшими кусками и охлаждены перед отправкой. Ќикто не сможет вз€ть органы дл€ трансплантации из этих мелких кусочков.}
{103}{}{’олодильник заполнен част€ми тел.}
{104}{}{’олодильник забит част€ми тел, нарезанными маленьким кусками и упакованными в упаковки со льдом. —транно.}
