# For lines 177 and 180 and 181, spaces are intentional.
# Line 177 is prepended to encounter type. (they begin at 183 below)
{177}{}{You encounter }
{178}{}{Yes.}
{179}{}{No.}
{180}{}{You earn }
{181}{}{ experience for successful use of your Outdoorsman skill.}
# Line 182 is appended after 177 and the encounter type. Period and space is intentional.
{182}{}{. Do you wish to engage?}
# These are apended to line 177.
{183}{}{Floaters}
{184}{}{Manti}
{185}{}{Rats}
{186}{}{Peasants attacked by Raiders}
#
#
# TRANSLATORS: Ignore these blank entries, but do not delete them.
#             They are placeholders and are intentional.
#
{187}{}{}
{188}{}{}
{189}{}{}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{}
{195}{}{}
#
{201}{}{}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{}
{221}{}{}
{222}{}{}
#
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{}
#
{258}{}{}
{259}{}{}
{260}{}{}
{261}{}{}
{262}{}{}
{263}{}{}
{264}{}{}
{265}{}{}
{266}{}{}
{267}{}{}
{268}{}{}
{269}{}{}
{270}{}{}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
#
{289}{}{}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{}
{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
#
{304}{}{}
#
#
# 100 to 103 are NOT USED, looks like it was old code for finding the Radscorpion Cave from the worldmap.
#
{100}{}{Судя по всему, они не могли уйти далеко. Скорее всего, неподалеку их логово.}
{101}{}{Похоже, они прибыли сюда откуда-то неподалеку.}
{102}{}{Похоже, они прибыли с далекого севера.}
{103}{}{Очевидно, они просто блуждали по пустоши.}
#
#
# DEHYDRATION ENCOUNTERS
#
#
{125}{}{You avoid dehydration due to your supply of water, emptying }
{119}{}{ flask.}
{124}{}{ flasks.}
{112}{}{You avoid dehydration due to your supply of fluids, emptying }
# TRANSLATION NOTE: a period is inserted by the script at the end of the list of drinks consumed, and a comma between each if multiple types are consumed.
{116}{}{ water flask}
{117}{}{ water flasks}
{141}{}{ Nuka-cola}
{140}{}{ Nuka-colas}
{142}{}{ beer}
{149}{}{ beers}
{150}{}{ bottle of booze}
{151}{}{ bottles of booze}
{152}{}{Resorting to alcohol reduces your }
{153}{}{Strength}
{154}{}{Endurance}
{156}{}{ by 1 point.}
{157}{}{ by 2 points.}
{155}{}{Strength and Endurance}
{158}{}{ by 1 point each.}
#
# DRANK BUT STILL THIRSTY
#
{114}{}{Your water supply runs out, }
{161}{}{Your supply of fluids runs out, }
{162}{}{and your search of }
{115}{}{ hours fails to locate any water. Dehydration sets in, causing you }
{148}{}{ point of health damage.}
{113}{}{ пунктов здоровья.}
{163}{}{but you manage to avoid dehydration by searching for water. The search takes }
{164}{}{1 hour.}
{111}{}{ ч.}
#
# CRITICAL SUCCESS ON OUTDOORSMAN CHECK
#
{147}{}{You manage to avoid dehydration by searching for water. The search takes 1 hour.}
{138}{}{ You refill your }
{118}{}{flask}
{159}{}{flasks}
{160}{}{ with the drinkable water.}
{165}{}{You earn }
{166}{}{ experience for successful use of your Outdoorsman skill.}
#
#
{109}{}{Вы смогли избежать обезвоживания, найдя источник воды. Поиски заняли еще час.}
{110}{}{Вы смогли избежать обезвоживания, найдя источник воды. Поиски заняли еще }
{120}{}{Вы уже }
{121}{}{ ч. ищете в пустыне воду. Вы ее находите, но ее недостаточно для утоления вашей жажды. Вы восстанавливаете один пункт здоровья.}
{122}{}{Вы уже }
{123}{}{ ч. ищете в пустыне воду. Вы ее находите, но ее недостаточно для утоления вашей жажды. Вы восстанавливаете }
{167}{}{}
{168}{}{}
#
#
# NORTH_TABLE ENCOUNTERS
#
#
# North1
#
# if pass Perception check or have Awareness:
#   197 Uh-oh... a raiding party!
# else is:
{105}{}{ЗАСАДА!!!}
#
# North2
#
{104}{}{Вы наткнулись на жестокую битву между радскорпионами и кротокрысами.}
#
# North3
#
{106}{}{Вы наткнулись на большую стаю радскорпионов!}
#
# North4
#
{107}{}{Вы наткнулись на стаю радскорпионов.}
#
# North5
#
{108}{}{Вы наткнулись на стаю кротокрыс.}
#
# North6
#
# -Dehydration-
#
# SOUTH_TABLE ENCOUNTERS
#
# South1 -- change this encounter to something else??
#
{131}{}{ПАНИКА!!!}
#
# South2
#
{132}{}{Вы наткнулись на большую стаю радскорпионов!}
#
# South3
#
# -Dehydration-
#
# South4 -- change this encounter to something else
#
# 143 "Raiders!!!"
#
# South5
#
{144}{}{Вы наткнулись на большую стаю кротокрыс.}
#
# South6
#
{145}{}{Вы наткнулись на стаю диких радскорпионов.}
#
#
# SHADY ENCOUNTERS
#
#
# Shady1
#
{146}{}{Вы встречаете нескольких крестьян, отбивающих нападение.}
#
# Shady2
#
# -Dehydration-
#
# Shady3
#
{169}{}{Вы наткнулись на семью радскорпионов.}
#
# Shady4
#
{170}{}{Вы встречаете странствующего торговца с охраной.}
#
# unless he's dead, then you get
#
{305}{}{Вы наталкиваетесь на то, что осталось от враждебных охранников торговца Дака.}
#
# once that has been seen, call Shady3
#
# Shady5
#
{175}{}{You encounter a traveler.}
# or if killed,
{171}{}{Вы наткнулись на труп путешественника.}
#
# else call Shady2
#
# Shady
#
{126}{}{Вы встретили нескольких радскорпионов, охотящихся на кротокрыс}
{127}{}{К вам приближаются тощие гуманоиды с зеленоватой кожей.}
{128}{}{Junk and rocks are scattered about. You wonder if anything of value could remain...}
#
# UNUSED ENTRY:
{129}{}{На вас напал одинокий радскорпион!}
#
{130}{}{Вы замечаете полусъеденный труп.}
{134}{}{В пустыне на вас нападает стая мерзких радскорпионов!}
{135}{}{Вы встречаете патруль.}
{136}{}{Вы встречаете торговца с несколькими телохранителями.}
{174}{}{You come across the remnants of a merchant and his guards.}
{137}{}{Вы видите крестьянина со стадом браминов.}
{139}{}{Radscorpions hunt mole rats among the ruined city walls.}//Sduibek, Fallout Fixt
{172}{}{Вы наткнулись на разбросанные по земле предметы.}
{176}{}{You have stumbled across a small patch of ruined and deserted buildings.}
#
#
# RAIDER_TABLE ENCOUNTERS
#
#
# Raider1
#
{133}{}{Вы попадаете в засаду к налетчикам!}
#
# Raider2 - half chance of either msg displayed, but encounter the same
#
{143}{}{Налетчики!!!}
{197}{}{Упс... отряд налетчиков!}
#
# Raider3
#
{173}{}{Вы замечаете остатки каравана, разграбленного налетчиками.}
#
# Raider4
#
{310}{}{На вас нападает небольшая группа налетчиков!}
#
# Raider5 - 198 always, plus 196 half the time
#
{198}{}{Вдали вы видите одинокого налетчика.}
{196}{}{Радскорпионы нападают!}
#
# Raider6 - displays and runs both (because bodies are empty)
#
{199}{}{Вы видите поле битвы, усыпанное трупами.}
#plus 196
#
#
{223}{}{Вы замечаете блуждающую стаю диких койотов.}
{200}{}{Радскорпионы нападают!}
{224}{}{Вы видите нескольких человек, разведывающих местность.}
{225}{}{Вы встречаете небольшую группу торговцев с охраной.}
{226}{}{Вы видите битву людей с мутантами!}
{227}{}{Огромная орда радскорпионов идет сюда!}
#
{250}{}{К вам приближается несколько человек в силовой броне.}
{251}{}{Вы видите группу торговцев с охраной.}
{252}{}{Вы видите жестокую битву между несколькими пустынными налетчиками и группой людей в силовой броне.}
{253}{}{Вы видите нескольких мутантов, исследующих территорию противника.}
{254}{}{Вы видите нескольких странных существ впереди...}
{256}{}{Патруль супермутантов проходит совсем близко!}

{257}{}{You spot the ruins of a tiny village.}

# UNUSED ENTRY:
{255}{}{Вы находите несколько предметов.}

{279}{}{Вы видите разбросанный по пустыне хлам.}
{280}{}{Вы натыкаетесь на боевой отряд супермутантов.}
{281}{}{Вы натыкаетесь на группу причудливых существ.}
{282}{}{Вы натыкаетесь на стаю голодных радскорпионов.}
{283}{}{You feel nauseous, and the air seems to waver with heat. A mutated creature suddenly approaches!}
{284}{}{You have stumbled across a few bizarre mutant creatures.}
{285}{}{Вы находите нечто, похожее на реквизит старого научно-фантастического фильма.}
{286}{}{Коготь Смерти!!}
{287}{}{You stumble into a migrating pack of radscorpions. They seem to be fleeing from...}
{288}{}{Вы встречаете какое-то мутировавшее пустынное существо.}
#
{299}{}{Невдалеке вы видите нескольких радскорпионов.}
{300}{}{Вы встречаете оборванного крестьянина.}
{301}{}{Вы встречаете кротокрысу.}

# was: "The Deathclaw!!"
{302}{}{A young Deathclaw seems to think you are lunch.}

{303}{}{Вы натыкаетесь на мигрирующую стаю радскорпионов.}
#
{306}{}{Вблизи от вас проходит патруль мутантов. С ними какие-то странные существа!}
{307}{}{Вы попали в засаду небольшой боевой группы супермутантов.}
{308}{}{Похоже, вы наткнулись на серьезную бандитскую разборку!}
{309}{}{Внезапно появляется шайка бандитов!}
{311}{}{На вас нападает небольшая группа бандитов!}
{313}{}{Внезапно вас атакует стая мантис!}

# UNUSED ENTRY:
{312}{}{Внезапно вас атакуют крысы!}

# SPECIAL ENCOUNTERS TEXT:
{314}{}{Эй! Они действительно где-то там.}
{315}{}{Вдали вы видите перевернутый грузовик.}
{316}{}{Посреди пустоши вы натыкаетесь на несколько разбитых машин.}
{317}{}{Вы замечаете полицейскую будку на северо-востоке.}
{318}{}{Вы встречаете стадо диких браминов. Вы чувствуете, что что-то не так...}
#
