{100}{}{Вы видите Рутгера.}
{101}{}{Здравствуйте. Добро пожаловать к Дальнобойщикам. Чем мы можем вам помочь?}
{102}{}{Вы можете перевозить воду?}
{103}{}{Я тут по объявлению о работе.}
{104}{}{Я ищу работу.}
{105}{}{Чем вы здесь занимаетесь?}
{106}{}{Ничем не можете. До свидания.}
{107}{}{Гык!}
{108}{}{Мы не берем на работу укурков! Иди отсюда.}
{109}{}{Хмммм. Жаль, что твоим мозгам очень далеко до твоих мышц. От тебя могла бы быть польза.}
{110}{}{Мы, конечно, можем перевозить воду, но это влетит вам в копеечку. Сколько вам надо и куда отвезти?}
{111}{}{Мне нужно достаточно воды, чтобы снабдить Убежище. Оно на севере, в горах, за Джанктауном.}
{112}{}{Мне нужно достаточно воды, чтобы снабдить Убежище. Оно на севере, в горах.}
{113}{}{Мне нужно все, что у вас есть! Вот увидите, однажды я изменю облик планеты!}
{114}{}{Целое Убежище? У тебя крыша съехала? Где мы тебе столько воды наберем? К тому же я не полезу в горы. У нас и так постоянно караваны пропадают.}
{115}{}{А еще кто-то может?}
{116}{}{Так что там насчет объявления?}
{117}{}{Так что там насчет работы?}
{118}{}{Огромное спасибо!}
{119}{}{Прости, ты же не отсюда. Торговцы водой занимаются всей водой в городе. Я бы не связывался с ними. Это стая стервятников.}
{120}{}{Где мне их найти?}
{121}{}{Ясно, спасибо.}
{122}{}{Ну, не заметить их трудно. Они забаррикадировались на юге. У них там еще эта проклятая водонапорная башня.}
{123}{}{Ну, так чем ты тут занимаешься?}
{124}{}{Ясно, спасибо.}
{125}{}{Я заведую... то есть, я помогаю управлять Дальнобойщиками. Если кто-то на нас наезжает, ему приходится иметь дело со мной. Мы торгуем разными товарами по разным поселениям.}
{126}{}{Я уже тебе говорил. Мы с Бутчем управляем Дальнобойщиками.  Что тебе надо?}
{127}{}{А чем вы торгуете?}
{128}{}{Интересно. Пока.}
{129}{}{Хорошо. Так что там насчет той работы?}
{130}{}{Звучит неплохо. Вам нужна помощь?}
{131}{}{Ну, мы торгуем всем, что только может прийти тебе на ум: медпрепаратами, шинами, оружием, патронами, едой, браминами, дерьмом, даже обрезками металла.}
{132}{}{Дерьмом? Металлом?}
{133}{}{Ммм... звучит заманчиво, но мне нужно идти.}
{134}{}{Ты удивишься, когда узнаешь больше о спросе. То, что валяется под ногами в одном месте, может быть роскошью в поселении в каких-то 10 милях оттуда.}
{135}{}{Ладно, хватит с меня нудного болтуна-торговца. Где здесь выход?}
{136}{}{Спасибо. Пока.}
{137}{}{Можете мне рассказать о той работе?}
{138}{}{У вас есть работа?}
{139}{}{Кажется, ты немножко с приветом, но нам это сгодится. Пойди поговори с Бутчем. Он любит встречать новобранцев. Он в комнате позади меня. Заходи.}
{140}{}{Не думаю, что мне нужны детоубийцы в моем караване.}
{141}{}{Убийца детей? Но это был несчастный случай!}
{142}{}{Эй, у меня нет на этот счет предрассудков. Если кто-то встанет на моем пути, я его по стенке размажу, сколько бы лет ему ни было.}
{143}{}{Думаю, несчастные случаи довольно часто случаются. Это грязный мир. Но я не знаю, могу ли я тебе доверять. Пойди поговори с Бутчем. Он в той комнате.}
{144}{}{Ну да, разумеется, это был несчастный случай. Я вас знаю. Думаете, вам все можно? Только не здесь, мужик. Иди поговори с Бутчем, но я за тобой буду присматривать. Он в той комнате за моей спиной.}
{145}{}{Ну да, разумеется, это был несчастный случай. Я вас знаю. Думаете, вам все можно? Только не здесь, дамочка. Иди поговори с Бутчем, но я за тобой буду присматривать. Он в той комнате за моей спиной.}
{146}{}{Ах ты жестокая тварь! Нам такие могут пригодиться, но это не значит, что я согласен с твоими взглядами. Просто не трогай детей при мне, а то по стенке размажу. Иди поговори с Бутчем. Он в своем кабинете позади меня.}
{147}{}{Ищешь работу? Слыхал о тебе много хорошего. Нам нужны люди с такой репутацией. Пойди поговори с Бутчем. Он за той дверью позади меня.}
{148}{}{Ищешь работу, не так ли? Выглядишь ты, в принципе, нормально. Думаю, тебе стоит поговорить с Бутчем. Он в том кабинете за моей спиной.}
{149}{}{Я думал, тебе не нужна работа. Что ты хочешь?}
{150}{}{Ничего. Хотелось еще разок взглянуть на твою мерзкую харю.}
{151}{}{Простите, но мне действительно очень хотелось взяться за эту работу. Можно мне попробовать?}
{152}{}{Ничего.}
{153}{}{Иннах!}
{154}{}{А ну вали отсюда, вонючий укурок!}
{155}{}{Отлично. Я занятой человек, и мне жаль, что вы не можете принять решение... Давайте обсудим детали.}
{156}{}{Проваливай отсюда!}
{157}{}{Чего ты со мной разговариваешь? Я сказал, насчет работы иди к Бутчу, если ты ему понравишься, я раскрою тебе все детали.}
{158}{}{Что? Ты все еще здесь?}
{159}{}{Ну, как поиски?}
{160}{}{Ничего не могу найти.}
{161}{}{Извините, можно повторить детали касательно работы?}
{162}{}{У вас нет никакой работы, связанной с караваном?}
{163}{}{Извините, мне надо идти.}
{164}{}{Че?}
{165}{}{Я и не говорил, что будет легко. Иначе мы бы сами решили эту проблему давным-давно. Порасспрашивай тут и там. Если надо, веди себя грубо. Конечно, без кровопролития. Ну, по крайней мере, не при свидетелях.}
{166}{}{Говорю тебе - завязывай с наркотиками. Они до добра не доведут.}
{167}{}{Мы заплатим 500 хаббаксов, если ты точно сможешь сказать Бутчу, что произошло с недавно исчезнувшими караванами. Поэтому собирай все доказательства, какие только сможешь найти. Лично я думаю, что это чертовы Торговцы водой или те уроды с пушками из Братства Стали. Бутч думает, что это Когти Смерти или что-то в этом роде. Поговори с Бет, она должна кое-что об этом знать.}
{168}{}{Хорошо, но я не знаю, что именно ты не помнишь. Там не так много.}
{169}{}{Я всерьез подумал, что ты оттуда. Я просто проверял тебя. Если ты не оттуда, то откуда, черт побери, у тебя стальной костюм - такой, как у них?}
{170}{}{А, этот? Ну, мне посчастливилось "найти" его, если ты понимаешь, о чем я.}
{171}{}{Мне не позволено об этом говорить.}
{172}{}{Черт, круто. Хорошо, что ты на нашей стороне. Я не понимаю, как можно не знать об этом, но Братство - это очень странная шайка. Они поклоняются технологии или чему-то в этом роде. Они окопались неподалеку, к северо-западу отсюда.}
{173}{}{Что такое Братство Стали?}
{174}{}{Можешь быть уверен, то было не Братство.}
{175}{}{Что ты знаешь о Когте Смерти?}
{176}{}{А где Бет?}
{177}{}{Спасибо. Пока.}
{178}{}{Ну, как скажешь. Уверен, тебе случалось встречать их раньше. Братство - это очень странная шайка. Они поклоняются технологии или чему-то в этом роде. Они окопались неподалеку, к северо-западу отсюда.}
{179}{}{Они действительно странные. Поклоняются технологии, или чему-то в этом роде. И у них дофига оружия. Вынести караван для них - раз плюнуть. А находятся они к северо-западу отсюда.}
{180}{}{Я так и знал, что ты из этих. У тебя их стальной костюм. Надеюсь, что это правда, и что мы не ошиблись, наняв тебя. Но ты не единственный, кого мы наняли, так что, думаю, проблем не возникнет.}
{181}{}{С чего вдруг?}
{182}{}{Потому что мне удалось вступить в их орден и тщательно их проверить. Они тихие и спокойные, и бояться нечего.}
{183}{}{Мне удалось побывать в их бункере. Они не те, кого вы ищете.}
{184}{}{Всего лишь предчувствие.}
{185}{}{Ну, мне кажется, это звучит обнадеживающе.}
{186}{}{Надеюсь, ты не ошибаешься.}
{187}{}{Предчувствия недостаточно. Нам нужны доказательства.}
{188}{}{Бет справа прямо за той дверью. Она здесь продает оружие. Скажи ей, что работаешь на нас, и получишь скидку 15%.}
{189}{}{Ой, ну да, Коготь Смерти, ага, конечно. Они просто психи. Это называется "разыгралось воображение". Нет там никакого призрака или монстра или чего-то еще. Просто оставайся в реальном мире, и все будет нормально.}
{190}{}{Да? Чем я могу помочь?}
{191}{}{Я знаю, что происходит с вашими караванами.}
{192}{}{Ничего.}
{193}{}{Что.}
{194}{}{Гррр.}
{195}{}{Серьезно? Итак, кто ж те засранцы? Торговцы водой?}
{196}{}{Ага, это они! Они, должно быть, собираются на вас напасть. Им... нужны ваши... брамины.}
{197}{}{На самом деле, это была группа этих вот ОГРОМНЫХ мутантов.}
{198}{}{Это был Коготь Смерти. Он съел целый караван на моих глазах.}
{199}{}{Я не помню.}
{200}{}{Ты не помнишь? Смешно, мужик. А теперь вали отсюда!}
{201}{}{Ты не помнишь? Смешно, барышня. А теперь вали отсюда!}
{202}{}{Я так и знал, что это они. У тебя есть доказательства? Эти ублюдки мне за все заплатят.}
{203}{}{Э-э... Нет. По дороге потерялись. Но можете поверить мне на слово.}
{204}{}{Ну, если честно, это были не они. Это была группа огромных мутантов.}
{205}{}{Прошу прощения, мне пора идти.}
{206}{}{Я не смогу ничего сделать, пока нет доказательств. Мне не хочется начинать очередную войну торговцев. Если ты добудешь доказательства, я обращусь к властям, и мы быстро с ними разделаемся.}
{207}{}{Ты скотина! Убирайся прочь!}
{208}{}{Что? Как? Не может быть! Ты шутишь, да? Ты, должно быть, шутишь, не так ли?}
{209}{}{Да, извини. Хочешь верь, а хочешь нет, но это была большая группа мутантов.}
{210}{}{Это было ужасно... Эти большие заостренные зубы...}
{211}{}{Целый караван? Серьезно? Ты меня держишь за легковерного дурачка? А ну быстро иди отсюда и узнай, что же на самом деле происходит с нашими караванами.}
{212}{}{Какие-то огромные мутанты уничтожают мои караваны? Занятно. Почти так же правдоподобно, как сказка о Когте Смерти.}
{213}{}{Я не шучу. Мне удалось найти и убить Коготь Смерти, но голодиск был на теле одного из тех... супермутантов.}
{214}{}{Что ж, проверь этот голодиск. Он снят с тела одного из нападавших мутантов.}
{215}{}{Это правда. Все так и было. Я принесу доказательства.}
{216}{}{Ладно, не хотите - не верьте.}
{217}{}{Мне нужно идти.}
{218}{}{Hey, I know how to use one of those. Butch got some gizmo from some scout from the Brotherhood a long time ago that can read these things. Let's see... [Rutger inserts the disk into the device and quickly reads its contents] ...Sorry I didn't believe you. This does not bode well for the good guys. Well, here's your 500 caps. Hell, make it 800, and thanks for the information! If you need anymore work you will always be welcome.}
{219}{}{Пожалуйста, не укрепляй паранойю Бутча. Он очень... чувствителен, когда разговор затрагивает Когти Смерти. Теперь скажи мне, тебе удалось хоть что-то выяснить? Это были Торговцы водой?}
{220}{}{Ага, это они! Они, должно быть, собираются на вас напасть. Им... нужны ваши... брамины.}
{221}{}{На самом деле, это была группа этих вот ОГРОМНЫХ мутантов.}
{222}{}{Нет, на самом деле это был Коготь Смерти. Он съел целый караван на моих глазах.}
{223}{}{Я не помню.}
{224}{}{Крысы, да? Ну так что, удалось тебе выяснить что-то или нет? Это проклятые Торговцы водой, ведь так? Я же это знаю!}
{225}{}{Ага, это они! Они, должно быть, собираются на вас напасть. Им... нужны ваши... брамины.}
{226}{}{На самом деле, это была группа этих вот ОГРОМНЫХ мутантов.}
{227}{}{Это был Коготь Смерти. Он съел целый караван на моих глазах.}
{228}{}{Я не помню.}
{229}{}{Наши караваны уничтожили мутанты? Звучит почти так же правдоподобно, как и сказка про Коготь Смерти.}
{230}{}{Я не шучу. Мне удалось найти и убить Коготь Смерти, но голодиск был на теле одного из тех... супермутантов.}
{231}{}{Что ж, проверь этот голодиск. Он снят с тела одного из нападавших мутантов.}
{232}{}{Это правда. Все так и было. Я принесу доказательства.}
{233}{}{Мне нужно идти.}
{234}{}{Итак, у тебя есть какие-нибудь доказательства касательно того, кто уничтожил мои, я хотел сказать, наши караваны?}
{235}{}{Ага. Вот голодиск. Он с тела одного из тех... огромных мутантов.}
{236}{}{Нет, все еще ищу. Есть какие-нибудь идеи?}
{237}{}{Нет. Я сразу дам вам знать, как только найду.}
{238}{}{Гык!}
{239}{}{Ну, если этот Коготь Смерти и вправду существует, наверное, стоило бы осмотреть его логово. Может, там будут какие-нибудь подсказки.}
{240}{}{Привет. Чем могу помочь?}
{241}{}{Мне удалось выяснить, что случилось с пропавшими караванами.}
{242}{}{Да нет, ничего.}
{243}{}{Эй! Я слышал, тебе удалось убить главаря тех мутантов. Отличная работа. Это, наверное, спасло жизни всех, кто живет в Хабе. Но интересно, откуда эти мутанты приходили?}
{244}{}{Ура! Еще больше мяса! Интересно, где они прячутся?}
{245}{}{Да, мне нужно полностью очистить всю территорию от злых порождений Создателя. Интересно, где они прячутся.}
{246}{}{Ты прав. Ума не приложу, где они прячутся.}
{247}{}{Мне нужны деньги. У вас есть какая-нибудь работа?}
{248}{}{Куда ж ты денешься? Увидимся!}
{249}{}{Да, получилось надрать ему задницу. Упс... То есть... Гру-чча!}
{250}{}{Привет, мужик, как дела?}
{252}{}{Привет, красотка, как дела?}
{253}{}{Как там поживает моя красавица?}
{254}{}{Нормально. Бывало и хуже. У тебя есть еще какая-нибудь работа?}
{255}{}{Отлично! Так, думаю, загляну, узнаю, как там у вас дела.}
{256}{}{Ы?}
{257}{}{Дела? Отлично! Мутанты больше не нападают на караваны, торговля вновь такая, как раньше. На самом деле, торговля идет еще лучше, чем до этого. Спасибо, что спрашиваешь.}
{258}{}{Эй, я слышал, тебе удалось уничтожить какую-то базу, где околачивались все эти проклятые мутанты. Отличная работа! Жаль, их главаря там не было.}
{259}{}{Ага! Еще мясо! Где же этот Создатель может быть?}
{260}{}{Да, мне нужно убить Создателя. Я не могу позволить злу и дальше распространяться. Интересно, где же прячется этот Создатель.}
{261}{}{Вскоре Создатель встретит того, кто его уделает!}
{262}{}{Ты прав. Где же прячется Создатель?}
{263}{}{Мне деньги нужны. Есть какая-то работа?}
{264}{}{Да, получилось надрать парочку задниц. Упс... То есть... Гру-чча!}
{265}{}{Я слышал, люди говорили, что видели отдельные группы мутантов, которые шли на северо-запад. Как раз туда, где Братство Стали.}
{266}{}{Знаешь, с тех пор, как мутанты были уничтожены, Чада Собора ведут себя, мягко говоря, очень странно. Я нечаянно услышал, как один из них говорил о тебе. Кажется, они отчаянно тебя ищут.}
{267}{}{На самом деле, все не так уж и хорошо. Мутанты - это все еще большая проблема для наших караванов. Нам пришлось задержать почти все наши караваны. Хотя все равно спасибо за то, что спрашиваешь.}
{268}{}{Конечно, мы могли бы взять тебя сопровождать один из наших караванов. В охране работаешь? Плата у нас стандартная - 400 хаббаксов. Интересует?}
{269}{}{Разумеется.}
{270}{}{Не-а.}
{271}{}{Что? А как насчет пропавших караванов?}
{272}{}{Нет лучше способа найти воров, чем присоединиться к каравану.}
{273}{}{Я работаю над этим вопросом, но мне нужно посмотреть кое-какие записи.}
{274}{}{Прощай.}
{275}{}{Ладно, но если передумаешь - сообщи. По большей части это легкие деньги.}
{276}{}{Отлично. Пойди поговори с нашим караванщиком у входа и узнай, когда отправляется следующий караван. Пока ты будешь хорошо работать, мы тебе будем платить.}
{277}{}{Дам тебе еще один шанс. Платим 400 хаббаксов. Пойди поговори с нашим караванщиком у входа, и узнай, когда отправляется следующий караван.}
{278}{}{Прошу прощения, но я уже давал тебе шанс. Теперь уходи.}
{279}{}{Ты что, шутишь? Спасибо, конечно, за твои подвиги, но, боюсь, прошлого этим не изменишь. Теперь уходи.}
{280}{}{Ты что, не слышишь? Я сказал, что нам не нужны такие, как ты. Иди отсюда.}
{281}{}{Не думаю, что это будет очень эффективно, но ты можешь поработать на одном из них, если хочешь.}
{282}{}{С чего вдруг?}
{283}{}{Ты прав. Мне стоит разузнать побольше.}
{284}{}{Устраивает. Я возьмусь за эту работу.}
{285}{}{Хорошо. Поспрашивай там и сям.}
{286}{}{Ну хорошо. Просто поговори с нашим караванщиком у входа, когда подготовишься к поездке. Пока ты будешь хорошо работать, мы будем тебя нанимать.}
{287}{}{Конечно! Только говори не со мной, а с нашим караванщиком.}
{288}{}{[ЕЩЕ]}
{289}{}{Ну, хоть мы и теряем немало караванов, но это не самая большая большая часть нашей деятельности. ???Вероятность того, что ты будешь в том караване, на который будет совершено такое нападение. Тот, кому вздумается уничтожить целый караван, должен обладать крайне высокой мощью.}
{290}{}{Мм, хорошо. Думаю, я еще немного порасспрашиваю здесь.}
{291}{}{Ну, мне нужны деньги.}
{292}{}{Здравствуйте-здравствуйте. Чем могу упечь... Виноват, чем могу помочь?}
{293}{}{Рад видеть тебя снова.}
{294}{}{Интересно, а вы перевозите воду?}
{295}{}{Я здесь насчет работы, о которой вы давали объявление.}
{296}{}{Я ищу работу.}
{297}{}{Чем вы занимаетесь?}
{298}{}{Извините, мне нужно уйти.}
{299}{}{Рарва.}
{300}{}{Ага, какого черта тебе нужно?}
{301}{}{Ты начинаешь меня доставать. Чего тебе?}
{302}{}{Что?!}
{303}{}{Ты всех так достаешь?}
{304}{}{Что с тобой, мужик?}
{305}{}{Интересно, а вы перевозите воду?}
{306}{}{Я здесь насчет работы, о которой вы давали объявление.}
{307}{}{Я ищу работу.}
{308}{}{Чем вы занимаетесь?}
{309}{}{Простите. Мне нужно уйти.}
{310}{}{Туука?}
{311}{}{Босс на тебя разозлился. Вали отсюда!}
{312}{}{Кажется, я знаю, что происходит с караванами.}
{313}{}{Отлично! Расскажи Бутчу, что ты узнал, и если ты заслужил награду, он даст мне знать.}
{314}{}{Гррд!!! Рррвк!!!}
{315}{}{Извините, но мы не ведем никаких дел с... ну... умственно отсталыми.}
