{100}{}{Вы видите Шерри.}
{101}{}{Вы видите члена банды.}
{102}{}{}
{103}{}{Кто ты и что ты здесь делаешь?}
{104}{}{Я }
{105}{}{. Я здесь недавно.}
{106}{}{Не твое собачье дело, потаскуха!}
{107}{}{Чо?}
{108}{}{По-видимому, да, так как все здесь знают, что это - территория Черепов. Вали лучше отсюда, пока никому не вздумалось сделать тебе больно.}
{109}{}{Ну, давай!}
{110}{}{Извините, мне показалось, это туалет. Пока.}
{111}{}{Черепа? Кто это?}
{112}{}{Да, я это знаю. Я просто гуляю.}
{113}{}{Вали отсюда, тупица, пока кто-то из нас не выбил из тебя все дерьмо.}
{114}{}{Э-э, извините.}
{115}{}{Что? Ну-ка, давайте!}
{116}{}{Ты, жалкое создание, шло бы отсюда. Здесь небезопасно. Особенно для безмозглых тварей вроде тебя.}
{117}{}{Это мы! Мы самая крутая банда в городе. Вообще-то, мы единственная банда... Но никто не смеет с нами связываться.}
{118}{}{О, так вы вроде как заправляете всем городом, так?}
{119}{}{Как мило. Увидимся.}
{120}{}{О. Не советую. Понимаешь, ты не из Черепов, а это наше место. Лучше проваливай отсюда, пока Виктор не разозлился.}
{121}{}{Вообще-то, думаю, я останусь.}
{122}{}{А кто такой Виктор?}
{123}{}{Все в порядке, я ухожу.}
{124}{}{Ладно. Это ваше дело.}
{125}{}{Виктор вон там. Он самый крутой из всех нас. Он любит мучить игуан, которых ловит. Мне он не слишком-то и нравится, если честно, но он один из нас.}
{126}{}{Ну, есть Виктор, и Акула, который тусуется в "Выгребной яме". Еще Винни, и еше парочка ребят, которые время от времени здесь останавливаются.}
{127}{}{А где находится "Выгребная яма"?}
{128}{}{Ну, "Выгребная яма"  - это грязный бар к северу отсюда, около казино Гизмо.}
{129}{}{О да! Никто с нами не связывается! Ну, кроме, наверное, Киллиана, но он действительно крутой. Он тут типа шерифа. Мы делаем все, что хотим!}
{130}{}{Мы тут тусуемся, бывает, играем у Гизмо, или зависаем в "Выгребной яме". Иногда выполняем всякую странную работу для Гизмо или всяких путешественников. Виктор любит выслеживать людей. Подумай об этом и лучше держись от него подальше.}
{131}{}{Ты работаешь на Гизмо? И что ты можешь о нем мне рассказать?}
{132}{}{И чем вы здесь занимаетесь?}
{133}{}{А кто вообще в банде?}
{134}{}{А почему вы тусуетесь с этими парнями?}
{135}{}{Мы как семья! Мы заботимся друг о друге. Ну, кроме Акулы, который вечно все портит. И Виктора, который всегда смотрит на людей как-то странно. Но Винни - крутой чувак. И мы вместе мутим всякие темы. Ну мы типа друзья и, там, всякая бодяга.}
{136}{}{О! Опять ты! Знаешь, если ты не из Черепов, то тут лазить опасно. А ты не из Черепов.}
{137}{}{Ну да, ну да. Вы, Черепа, наверное, не сможете завалить и спящего брамина, я уж молчу о себе.}
{138}{}{И что у вас недавно интересного было?}
{139}{}{Правда? Сейчас увидим! Виктор!}
{140}{}{Ну, если честно, то немного. Тут особо нечего делать. Ну, Акула, как обычно, устраивал всякие драки в "Яме", а что тут еще можно делать?}
{141}{}{Ну, наверное, немного.}
{142}{}{Вы всегда можете попробовать что-то новое. У вас же должны быть какие-то таланты, способности, хобби...}
{143}{}{Ну, я, типа, люблю рисовать. И Винни говорит, что я неплохо готовлю. Но я имею в виду, нам весело, круто, ну ты врубаешься...}
{144}{}{Думаю, это понятно.}
{145}{}{Ну а что ты собираешься делать, когда вырастешь? Чем ты будешь заниматься? Как будешь зарабатывать на жизнь?}
{146}{}{Ммм, ну, я об этом как-то особо не задумывалась. Ну, вообще-то, Винни и Виктор как-то зарабатывают деньги, Акула иногда подрабатывает телохранителем... Ну, не знаю...}
{147}{}{Ты бы как-то пыталась выбраться из всего этого, пока еще есть возможность.}
{148}{}{Эй, отвали! Ты говоришь так же, как и предки Винни раньше. Мы поддерживаем друг друга. Ясно? Так что не лезь!}
{149}{}{Думаю, да. Я никогда об этом особо не задумывалась.}
{150}{}{Привет! Как поживаешь? Прошло время с тех пор, как мы виделись.}
{151}{}{У меня все нормально, спасибо.}
{152}{}{Бывало и лучше.}
{153}{}{Нормально. А ты?}
{154}{}{Мне жаль это слышать. Думаю, тебе надо найти себе комнату и отоспаться. Поговори с Марсель. О, вот еще, я могу приготовить тебе поесть, если хочешь.}
{155}{}{Спасибо. Это было бы превосходно.}
{156}{}{Нет, спасибо, увидимся.}
{157}{}{О, у меня все намного лучше, спасибо! Я теперь готовлю еду в "Яме" и "Развалине". Иногда это утомительно, но я люблю готовить, и мне нравится встречать разных интересных людей. И мне, к тому же, платят. Спасибо за помощь.}
{158}{}{Ну пока. Удачи. Увидимся!}
{159}{}{Это большой толстый мужик, владелец Казино. Он хочет править всем Джанктауном, но Киллиан сдерживает его. Правда, он платит весьма неплохо. Иногда он нанимает Винни или Виктора, чтобы они разбирались с теми людьми, кто приносит ему неприятности, как, например, с тем незнакомцем, который приходил сюда пару недель назад.}
{160}{}{Ты хочешь, чтобы я сдала своих друзей?}
{161}{}{Да, мне нужна информация.}
{162}{}{Извини. Забудь об этом.}
{163}{}{Они приносят людям зло, и будут продолжать это делать, пока их не остановят. Ты изменила свою жизнь к лучшему, теперь у тебя есть шанс помочь улучшить жизни других людей.}
{164}{}{Ну, они мои друзья. Но, думаю, они не должны причинять людям зло, а они действительно это делают. И я думаю, тебе можно доверять. Ладно.}
{165}{}{Нет, я никогда не пойду на это! Они ведь мои друзья! Может, я уже и не состою в банде, но я не собираюсь предавать моих старых друзей.}
{166}{}{Мне нужна твоя помощь. Мне нужны показания, чтобы убрать Черепов от греха подальше.}
