{100}{}{Вы видите водозабор Шейди Сэндс. Тут слишком мало воды, чтобы обеспечить Убежище.}
{101}{}{У вас нет никакой причины спускаться в колодец, но вы понимаете, что веревка может пригодиться для спуска вниз.}
{102}{}{Больше вам нет толка от колодца.}
{103}{}{Вы загадываете желание, когда слышите всплеск, с которым крышка от бутылки падает в воду.}
