{100}{}{???Вы видите Теракса, Мыслителя ночи.}
{101}{}{Вы видите Джастина, Мыслителя ночи.}
{102}{}{Вы видите Серин, Мыслителя ночи.}
{103}{}{Вы видите Долкарна, Мыслителя ночи.}
{104}{}{Вы видите Хорта, Мыслителя ночи.}
{105}{}{Вы видите Криса, Мыслителя ночи.}
{106}{}{Вы видите Хуаниту, Мыслителя ночи.}
{107}{}{Вы видите Лесли, Мыслителя ночи.}
{108}{}{Вы видите Рэнфилда, Мыслителя ночи.}
{109}{}{Вы видите Тимоти, Мыслителя ночи.}
{110}{}{Приветствую, о затычка наша. Ты как раз вовремя, чтобы нам помочь.}
{111}{}{А?}
{112}{}{Конечно. Не проблема.}
{113}{}{Прости. Много дел.}
{114}{}{А с чего бы это мне вам помогать?}
{115}{}{Это неважно, тупица. Иди за мной, я приставлю тебя к работе.}
{116}{}{Это не просьба. Твое желание не имеет значения.}
{117}{}{Разве ты не тот, кто хочет принести мир в пустоши?}
{118}{}{Да, только я не понимаю, как это связано с помощью вам.}
{119}{}{Нет. Мне больше по душе всеобщее разрушение.}
{120}{}{Мы полагаем, что если бы все, мутанты и люди, смогли бы научиться работать вместе, это помогло бы решить множество проблем.}
{121}{}{Звучит многообещающе. Я в деле.}
{122}{}{И не надейся.}
{123}{}{Что-то мне тут не нравится.}
{124}{}{Все совершенно прекрасно. Возможно, ограниченные возможности твоего черепа не позволяют тебе продвинуться в мышлении.}
{125}{}{Наверное, вы правы. Я в деле.}
{126}{}{Может, и так. Дай-ка я посмотрю на твой череп.}
{127}{}{Если таково твое желание, то мы тебе в этом поспособствуем.}
{128}{}{И снова добро пожаловать. Теперь ты нам поможешь.}
