{100}{}{You see: Uthern, leader of the Super Mutants.}
{101}{}{Нормик! Да как ты смеешь входить в чертоги высших существ?}
{102}{}{А?}
{103}{}{Шваль вроде тебя не может быть существом выше людей!}
{104}{}{Умри, мутик!}
{105}{}{В самом деле? Ты утверждаешь, что вы выше, а какие у тебя есть доказательства?}
{106}{}{Если ты считаешь себя выше всех других, то ты впадаешь в ошибку по обобщению.}
{107}{}{Удивительно, что ваша раса продержалась так долго. Я начну ее окончательное уничтожение с тебя.}
{108}{}{Ты лишь подтверждаешь мою правоту подобными глупыми замечаниями. Лично я не желал бы даже видеть тебя, но мой Создатель хочет переговорить с тобой.}
{109}{}{Покажи мне твоего Создателя.}
{110}{}{Пробуй такие слова - "упади замертво"!}
{111}{}{Ну-с, с твоим интеллектом тебе должно быть понятно, что такие вещи ничего не решают.}
{112}{}{С удовольствием.}
{113}{}{Ты утверждаешь, что разговор ничего не решает? Ты еще глупее, чем кажется.}
{114}{}{Хоть ты и глуп, речь шла о твоей манере выражаться.}
{115}{}{А, дурак наконец понимает кое-что.}
{116}{}{Слова мало что решают, а вот это - много.}
{117}{}{Я начинаю думать, что в тебе может течь и капля высшей крови. Позволь мне узнать это наверняка.}
{118}{}{Воистину, ибо смерть будет твоей последней милостью.}
{119}{}{Наиболее простые из доказательств - для тебя. Я умнее, сильнее и быстрее тебя. Хочешь испытать мои навыки?}
{120}{}{Нет, спасибо. Я тебе верю.}
{121}{}{Ты забыл - высокомернее, глупее и уродливее.}
{122}{}{Разумеется. Давай посмотрим, на что ты способен.}
{123}{}{Хорошо. Хотешь получить возможность обрести большие силы?}
{124}{}{Еще бы!}
{125}{}{Нет!}
{126}{}{Не знаю.}
{127}{}{Умри!}
{128}{}{Тогда я заберу тебя к моему Создателю.}
{129}{}{Это уже почти жалость. Впрочем, это не продлится долго.}
{130}{}{Тебе предлагают всю мощь мира, а ты все еще боишься. Я помогу тебе решиться.}
{131}{}{Подобные замечания лишь доказывают, насколько я умнее тебя. А теперь ты поплатишься за свою дерзость!}
{132}{}{Ты принимаешь кредитные карточки или только крышки от бутылок?}
{133}{}{Никогда!!}
{134}{}{Прости, у меня сейчас с бутылочными крышками не очень хорошо обстоят дела. Может, ты мне чек выпишешь?}
{135}{}{Что? Я думаю, я могу обобщить это так - ты пойдешь со мной.}
{136}{}{Рад тебя снова видеть. Мне говорили, что ты бродишь тут в округе. У меня ордер на твой арест.}
