{100}{}{“ут под половицей скрыта граната.}
{101}{}{ Ќе функционирует.}
{102}{}{¬ы отключаете западню и забираете плазменную гранату.}
{103}{}{¬ы как раз снимаете нат€нутую проволоку, когда неча€нно выдергиваете чеку из гранаты!}
{104}{}{¬ы пробуете сдвинуть половицу в сторону и разобрать ловушку, но у вас не получаетс€ подн€ть ее, не затронув нат€нутую проволоку.}
{105}{}{¬ы подн€ли половицу, но вам не удаетс€ хорошо вз€тьс€ за гранату.}
{106}{}{¬ы т€нете половицу вверх, но проволока выскальзывает у вас из рук, прежде чем вы доводите дело до конца.}
