{100}{}{Вы замечаете на двери знак, который означает, что лифт неисправен.}
{101}{}{Вы видите на двери знак, который означает, что он неисправен.}
{102}{}{Знак: ОСТОРОЖНО! Шахта лифта ремонтируется. Пожалуйста, используйте другой лифт.}
