{100}{}{¬ы замечаете нить моноволокна, нат€нутую через коридор, и умудр€етесь ее обойти.}
{101}{}{¬ы чувствуете сильную боль в ногах. ¬ы получили глубокие раны, споткнувшись о нить моноволокна.}
{102}{}{¬ы сильно порезали правую ногу.}
{103}{}{¬ы сильно порезали левую ногу.}
{104}{}{¬ы снимаете ловушку с нитью моноволокна, и спокойно избавл€етесь от нее прежде, чем порежете себе руки.}
{105}{}{¬ы пробуете сн€ть нить, но не можете толком за нее ухватитьс€. ¬ы отдергиваете руку, чтобы не порезатьс€.}
{106}{}{¬ы пробуете сн€ть нить, но промахиваетесь, и нить глубоко разрезает вам руку.}
