{100}{}{Widzisz Romero.}
{103}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{104}{}{Widzisz osobê, która nale¿y do Ostrzy.}
{105}{}{Wydaje ci siê, ¿e to mo¿e byæ Kujon.}
{106}{}{Wydaje ci siê, ¿e to mo¿e byæ Blizna.}
{107}{}{Wydaje ci siê, ¿e to mo¿e byæ Strzelec.}
{108}{}{Wydaje ci siê, ¿e to mo¿e byæ Nerwus.}
{109}{}{Wydaje ci siê, ¿e to mo¿e byæ M³ot.}
{110}{}{Wydaje ci siê, ¿e to mo¿e byæ Brzytwa.}
{111}{}{Cofnij siê!}
{112}{}{S³ucham? Co masz na myœli?}
{113}{}{Nigdy!}
{114}{}{Chcê porozmawiaæ o pokoju.}
{115}{}{Dobrze.}
{116}{}{To ja jestem od zadawania pytañ. Co tutaj robisz?}
{117}{}{Szukam przyjaciela.}
{118}{}{Chcê porozmawiaæ o pokoju.}
{119}{}{Chcê zakoñczyæ wojnê gangów!}
{120}{}{Chcê posmakowaæ krwi Ostrzy!}
{121}{}{Zatem szukasz w nieodpowiednim miejscu. Zje¿d¿aj.}
{122}{}{Pewnie nale¿ysz do tych przeklêtych fioletowych tog. Wynoœ siê zanim ktoœ ciê rozwali.}
{123}{}{Czekaj! Nie wiem o czym mówisz. Przychodzê w sprawie Adytum. Mam przekonaæ wszystkich, ¿eby zostawili ich w spokoju.}
{124}{}{Przynieœ pokój TEMU!}
{125}{}{Przepraszam. Muszê ju¿ iœæ.}
{126}{}{Hmm. Je¿eli rzeczywiœcie jesteœ z Adytum, to znaczy, ¿eœ frajer. Nie bêdzie pokoju dopóki w okolicy s¹ Rozpruwacze.}
{127}{}{Co chcesz przez to powiedzieæ?}
{128}{}{Hmm, pewnie.}
{129}{}{Zapytaj Brzytwy. Ona opowie ci o tych krwio¿erczych gnojkach.}
{130}{}{Spadaj!}
{131}{}{Hej, skoro teraz Jesteœ Ostrzem chcê ciê prosiæ o przys³ugê.}
{132}{}{Jasne.}
{133}{}{O co chodzi?}
{134}{}{Nie ma mowy.}
{135}{}{Doskonale. Zanieœ ten medalion Juliannie. Powiedz jej, ¿e nied³ugo siê spotkamy.}
{136}{}{Zakocha³em siê w dziewczynie z Adytum. Regulatorzy strzelaj¹, gdy tylko zobacz¹ któregoœ z nas, wiêc nie mogê siê z ni¹ spotkaæ.}
{137}{}{Jak mogê ci pomóc?}
{138}{}{Mów dalej.}
{139}{}{Masz pecha.}
{140}{}{Bêdê ci bardzo zobowi¹zany je¿eli zaniesiesz Juliannie ten medalion.}
{141}{}{Nie ma sprawy.}
{142}{}{ZnajdŸ sobie kogoœ innego.}
{143}{}{Maj¹c takiego sojusznika jak ty nie potrzebujemy wrogów. Do widzenia.}
{144}{}{Wydaje mi siê, ¿e ona te¿ mnie kocha, ale nie jestem pewien. Ostrza nie pozwol¹ mi zaryzykowaæ i spróbowaæ dostaæ siê do Adytum.}
{145}{}{Masz pecha.}
{146}{}{Dobrze, pomogê ci.}
{147}{}{Dziêkujê! Przys³a³a mi list. Spotkamy siê u Uczniów i tam weŸmiemy œlub.}
{148}{}{Witaj z powrotem.}
{149}{}{Bardzo ci dziêkujê. Zostaniemy z Uczniów, bo u nich mo¿emy mieszkaæ razem.}
