{100}{}{Voici un marchand ambulant d'origine asiatique.}
{101}{}{Voici Duc, le marchand ambulant.}
{102}{}{Salut, nomade. Je m'appelle Duc, je m'en vais faire du commerce aux Sables Ombragés. Y a peut-être des marchandises qui t'intéressent ?}
{103}{}{Qu'est-ce que tu vends ?}
{104}{}{Tu vas souvent aux Sables Ombragés ?}
{105}{}{Bof !}
{106}{}{Je vais te montrer.}
{107}{}{Oui, les Sables Ombragés font partie de ma tournée. Tu seras en sécurité si tu voyages avec nous.}
{108}{}{D'accord, ça me va.}
{109}{}{Non, merci.}
{110}{}{Oh, pardon ; je savais pas que t'étais aussi stupide.}
{111}{}{Ça devrait prendre un ou deux jours. Allons-y !}
{112}{}{ShadyW.map}
{113}{}{Il y a pas beaucoup de gens qui s'aventurent seuls dans le désert. Qui es-tu ?}
{114}{}{C'est pas tes affaires.}
{115}{}{Je m'appelle }
{116}{}{.}
{117}{}{Euh !}
{118}{}{Tiens, re-bonjour ! Je peux t'aider ?}
{119}{}{Je peux vous accompagner jusqu'aux Sables Ombragés ?}
{120}{}{Qu'est-ce que t'as à vendre ?}
{121}{}{Rien, merci.}
{122}{}{Qu'est-ce que tu veux ?}
{123}{}{Rien.}
{124}{}{Qu'est-ce que t'as à vendre ?}
{125}{}{Bof !}
{126}{}{Méfie-toi si tu voyages en solitaire. Récemment, y a eu des disparitions aux Sables Ombragés.}
{127}{}{Ouais, j'ai entendu dire comment t'avais rescapé cette femme des Sables Ombragés. Du beau boulot.}
