{100}{}{Qu'est-ce que tu veux ?}
{101}{}{Laisse-moi tranquille.}
{102}{}{Quoi ?}
{103}{}{Touche pas à mes affaires.}
{104}{}{Salut.}
{105}{}{Arrrr !}
{106}{}{Grrrrr !}
{107}{}{Ouch.}
{108}{}{Ouhh.}
{109}{}{Eh, il paraît que Set s'est fait buter !}
{110}{}{Set est mort. Set est mort. Set est mort....}
{111}{}{Il y a assez d'eau pour tout le monde. Set y veille.}
{112}{}{Il paraît que les mutants se sont fait éjecter de la ville.}
{113}{}{Depuis le départ des mutants, ça va mieux.}
{114}{}{Bonjour.}
{200}{}{Tu examines la misérable créature, mais tu comprends pas ce qui l'a mis dans un état pareil.}
{201}{}{Elle semble avoir été humaine, ou du moins descendre d'humains. Tu supposes que la détérioration du corps est due à l'acide ou aux radiations.}
{202}{}{Le corps de l'humanoïde a l'air très irradié mais il fonctionne encore. D'humain, il semble avoir régressé vers un mode de vie plus animal.}
{203}{}{Le corps de l'humanoïde a l'air très irradié et les muscles et le cerveau semblent détériorés. Pourtant, d'après les indicateurs génétiques, tu penses qu'il descend, comme toi, des êtres entrés dans les Abris.}
{300}{}{Tu es victime d'irradiations !}
