#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu vois Snake.}
{101}{}{Tu vois Dolgan.}
{102}{}{}
{103}{}{}
{104}{}{Tu vois un membre des Ecorcheurs.}
{105}{}{Tu vois un membre des Ecorcheurs.}
{106}{}{Tu penses apercevoir Books.}
{107}{}{Tu penses apercevoir Scars.}
{108}{}{Tu penses apercevoir Gunner.}
{109}{}{Tu penses apercevoir Twitch.}
{110}{}{Tu penses apercevoir Hammer.}
{111}{}{Tu penses apercevoir Razor.}
{112}{}{Vas t'en! C'est seulement pour les vrais combattants ici.}
{113}{}{Ainsi, tu penses prendre le dessus sur les mauviettes de Régulateurs ? Viens ici, je vais te montrer comment utiliser cette lame.}
{114}{}{Tu sembles t'être améliorer. Maintenant allons virer ces Régulateurs mais pour ma part, ce sera l'année prochaine.}
{115}{}{Bon travail pour avoir démonté ces Régulateurs. Que puis-je faire pour toi?}
{116}{}{Peux-tu m'apprendre quelques trucs à l'utilisation des armes blanches?}
{117}{}{Comment puis-je aller jusqu'aux Contrebandiers?}
{118}{}{Rien, merci.}
{119}{}{Bien sûr. Mais ça va prendre une grosse partie de la journée pour une petite amélioration. Tu veux toujours?}
{120}{}{Oui.}
{121}{}{Non.}
{122}{}{Et voilà. Tu t'es un peu amélioré. Bonne continuation.}
{123}{}{Absolument. Reviens quand tu voudras un autre entrainement.}
{124}{}{On dirait que nous avons laissé entré un fou ici. Bon, si tu veux aller chez eux, il y a une zone moins large dans leurs douves. Trouve la et cours le plus vite possible. Tu pourras peut-être passer de l'autre coté en un seul morceau.}
{125}{}{Merci.}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009