#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu vois Dragon.}
{101}{}{}
{102}{}{}
{103}{}{Tu vois un membre des Ecorcheurs.}
{104}{}{Tu vois un membre des Ecorcheurs.}
{105}{}{Tu penses apercevoir Books.}
{106}{}{Tu penses apercevoir Scars.}
{107}{}{Tu penses apercevoir Gunner.}
{108}{}{Tu penses apercevoir Twitch.}
{109}{}{Tu penses apercevoir Hammer.}
{110}{}{Tu penses apercevoir Razor.}
{111}{}{Sors d'ici! Tu ne vois même pas que j'essaye de me reposer !}
{112}{}{Que fais tu à roder dans les parages?}
{113}{}{Je regarde juste les étoiles.}
{114}{}{Je te cherchais.}
{115}{}{En pleine chasse.}
{116}{}{Tes escapades vont te coûter terriblement cher. Quel est ton récit? Dis moi la vérité, et tu vivras.}
{117}{}{Je suis vraiment ici pour te tuer.}
{118}{}{Je veux mettre fin aux guerres des gangs.}
{119}{}{Je cherche ma maison. C'est juste là. La lune.}
{120}{}{Je pense que j'aurai pu être désolé pour ça, mais je ne prête pas attention aux gens morts.}
{121}{}{Pas de chance. Maintenant, pars d'ici avant que j'envoie les gardes de nuit à tes trousses.}
{122}{}{Oh, tu n'apprécies pas beaucoup la vie. Je vais t'aider à y mettre fin dans ce cas.}
{123}{}{Tu m'as trouvé. Maintenant, file ou meurs!}
{124}{}{Je pense que je vais y aller.}
{125}{}{J'aimerai vraiment vivre.}
{126}{}{Qu'est-ce qu'on raconte sur les Eventreurs?}
{127}{}{Ils vont te tuer!}
{128}{}{Ils sont morts. Les Griffemorts les ont tous tué, tu vois?}
{129}{}{Rien pour le moment.}
{130}{}{Bien. Amène ça à Razor.}
{131}{}{Ne me mens pas. Dégage!}
{132}{}{Alors vire ton cul d'ici et met en boîte le bâtard!}
{133}{}{Hé l'ami! Tu as fait du bon travail pour les Régulateurs!}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009