#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu vois Fire.}
{101}{}{}
{102}{}{}
{103}{}{Tu vois un membre du gang des Ecorcheurs.}
{104}{}{Tu vois un membre du gang des Ecorcheurs.}
{105}{}{Tu penses apercevoir Books.}
{106}{}{Tu penses apercevoir Scars.}
{107}{}{Tu penses apercevoir Gunner.}
{108}{}{Tu penses apercevoir Twitch.}
{109}{}{Tu penses apercevoir Hammer.}
{110}{}{Tu penses apercevoir Razor.}
{111}{}{Qu'est ce tu veux, bouseux?}
{112}{}{Err.}
{113}{}{Je veux devenir un Ecorcheur.}
{114}{}{Qu'est-ce que ça va me demander pour que vous fassiez la paix avec le Sanctuaire?}
{115}{}{Ça! *smack*}
{116}{}{Rien. Désolé de t'avoir ennuyé.}
{117}{}{J'inspecte seulement les lieux.}
{118}{}{Bien. Un autre retardé. Tu ressembles à un Eventreur.}
{119}{}{Rrrrr.}
{120}{}{Arrrr.}
{121}{}{Arrooo?}
{122}{}{Toi aussi tu ne les aimes pas tellement? Peut-être pourrions nous t'utiliser pour un petit 'travail'.}
{123}{}{Urroo.}
{124}{}{Un nah.}
{125}{}{Ok, va parler avec la femme à notre tête. Razor te mettra directement dans le bain et te dira quoi faire.}
{126}{}{Stupide comme un pauvre poulet. Je vais te faire sortir de la misère maintenant.}
{127}{}{Ainsi tu es un Eventreur! Je suis désolé d'entendre ça, mais je savais déjà qu'ils étaient stupides. Bonne nuit!}
{128}{}{Les Eventreurs. Ces consanguins de l'autre coté de la ville. Laisse tomber. Tu es trop stupide pour savoir quoi que ce soit.}
{129}{}{Tu veux être un Ecorcheur? Bonne chance. Mais, si tu trouves Razor, parle lui de ça. Elle te laissera peut-être entrer.}
{130}{}{Ok, merci.}
{131}{}{Alors je ne veux pas entrer!}
{132}{}{Que veux tu dire par 'entrer'?}
{133}{}{Tu ne peux pas simplement faire de moi un Ecorcheur?}
{134}{}{Ta mère ne t'a jamais voulu, et c'est pareil pour nous.}
{135}{}{Simple. Tu auras à tuer quelqu'un pour nous rejoindre. Elle te dira qui tu auras besoin de tuer.}
{136}{}{Ok, merci.}
{137}{}{Laisse tomber. Je ne veux pas devenir membre de ton stupide gang.}
{138}{}{Non. Je ne peux pas. Je ne mène pas. Je garde juste Razor dans le droit chemin.}
{139}{}{Simple. Extermine nos ennemis, et ensuite nous ferons une trêve avec le Sanctuaire.}
{140}{}{Qui sont vos ennemis?}
{141}{}{Quel raisonnement! Puis-je avoir ta parole?}
{142}{}{Combattre est injuste! Je ne le ferai pas!}
{143}{}{Les Régulateurs. Ils gouvernent le Sanctuaire. Ils ne sont pas stupides et sont très dangereux.}
{144}{}{Ok, je tuerai les Régulateurs.}
{145}{}{Laisse tomber.}
{146}{}{Si tu comptes faire ça, tu devrais le faire savoir à Razor. Dans le cas contraire, elle aura ta tête avant que tu ne sortes d'ici.}
{147}{}{Comme tu le sens. Salut.}
{148}{}{Je ne donne pas ma parole. Je fais seulement des suggestions. Parle à Razor si tu veux agir.}
{149}{}{Alors te tuer maintenant t'évitera de souffrir encore pour de nombreuses années.}
{150}{}{Alors examine ça!}
{151}{}{Casse toi de là si tu tiens à la vie.}
{152}{}{Silence. Nous essayons d'espionner les Eventreurs.}
{153}{}{Si tu récupères la tête, amène là à Razor. Elle veut toujours jouer au football. Dans le cas contraire, dégage!}
{154}{}{Yo, l'ami!}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009