# Chris Avellone is a male bounty hunter. He has an abrupt attitude and is serious about
# his money. He does not like child killers (which is the only way the player will meet him).
{100}{}{Voici un chasseur de primes très costaud avec un bouton où l'on peut lire, "Je m'appelle Christophe et tu es mon bifteck".}

# Bounty Hunter is considered Male term
{101}{}{Qu'est-ce que tu veux?}
{102}{}{Un beignet.}
{103}{}{Qu'est-ce que fais ici?}
{104}{}{Je me promène.}
{105}{}{Rien.}
{106}{}{Ici, on n'aime pas trop ceux qui se la jouent. Décampe.}
# Alternate for "Buzz off" could be "Get lost" or "Get out of here"

{107}{}{Cette blague n'était même pas marrante la première fois. Tu es sur le point de découvrir pourquoi je suis l'un des plus redoutables chasseurs de primes du désert. Et je ne le ferai même pas pour de l'argent.}
{108}{}{C'est pas tes oignons.}

{109}{}{Bon, va voir ailleurs si j'y suis.}
# Alternate for "poke around" could be "Look around"

{110}{}{Tu savais que ta tête a été mise à prix pour avoir assassiné des innocents? La prime est de 1500 caps. C'est le moment de rafler la mise!}
# 1500 caps is equivalant to 1500 dollars. Children is considered male plural

{111}{}{[Christophe te regarde avec attention, considerant quelque chose... on dirait qu'il vient de prendre une décision]  Dis moi, à quel rythme rends-tu visite au Centre ou à Dépotville?}
{112}{}{Assez souvent, pourquoi cette question ?}
{113}{}{Et bien, tu vois... Le travail m'occupe presque à plein temps et je n'ai aucune opportunité pour me rendre là-bas. Et en tant que fumeur invétéré, un bon vieux briquet Zippo me manque beaucoup. Il est dit que de nombreux objets d'avant-guerre peuvent se trouver dans les magasins là-bas. Si tu me rapportes un Zippo, je partagerai avec toi des informations au sujet des bases voisines. Je pense que cela pourrait être utile !}
{114}{}{Quel dommage. On dirait que je me suis trompé sur ton compte. Dégage de là.}
{115}{}{Pourquoi pas, je vais t'en trouver un.}
{116}{}{Ok.}
{117}{}{Hé, j'en ai justement un ici. Je n'en ai pas vraiment besoin et je peux te le donner en echange d'informations.}
{118}{}{Merci! [Il prend le briquet] Donc, qu'as-tu besoin de savoir, exactement?}
{119}{}{Voici ton briquet. Il est temps de me donner des informations.}
{120}{}{Pas d'autres questions, merci.}
{121}{}{[SUITE]}
{122}{}{Que veux-tu savoir d'autre?}
{123}{}{Je cherche des informations.}

{300}{}{Adytum}
{301}{}{Followers}
{302}{}{Cathedral}
{303}{}{Rippers}
{304}{}{Blades}
{305}{}{Runners}
{306}{}{Hub}
{307}{}{Boneyard}

{310}{}{A small town to the south. Occasionally some of them visit.}
{311}{}{Those are the peace-loving freaks who live near us.}
{312}{}{A strange cult south of Adytum and in the Boneyard. Nicole says that they are up to something.}
{313}{}{An ultra-violent gang to our west. It was, at least... I don't really know what happened but their base is swarming with deathclaws now.}
{314}{}{A gang to the east. They use vibro-knives.}
{315}{}{A gang that came from the Hub, and sells guns. They are north of here.}
{316}{}{The Hub is a large city of traders and businesses to the east.}
{317}{}{This place is the Angel's Boneyard, the remnants of the old city of Los Angeles.}

# Alchemist: These are currently disabled teel-me-abouts. Don't delete, they may be of use in the future.

# {1005}{}{Gun}
# {1007}{}{Junktown}
# {1008}{}{Water}
# {1009}{}{Nicole}
# {1011}{}{Runners}
# {1012}{}{Chip}
# {1107}{}{Junktown is a small city just north of the Hub.}
# {1108}{}{I can't help you with that.}
# {1109}{}{She's the leader of the Followers.}
# {1111}{}{A gang that came from the Hub, and sells guns. They are north of here.}
# {1112}{}{I can't help you with that.}
