#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
# Alchemist: long phrases should be split and require some smooyhing.

{100}{}{Tu vois Lex, chef du clan nomade des Vipères.}
{101}{}{Un gars énorme avec une attitude méchante, flagrante à tes yeux.}
{102}{}{[...Tu te réveilles progressivement et regardes autour de toi. Tu vois un lieu complètement inconnu, trois tentes et plusieurs personnes à coté. On dirait que tu as reppris conscience avant qu'ils aientp pu te vider les poches. Ton regard tombe sur l'homme qui se tient à coté de toi] Oh, notre acheteur malchanceux s'est réveillé.}
{103}{}{[SUITE]}
{104}{}{Ce qu'il va se passer? Tu peux nous donner tous tes caps et nous te laisserons partir. Ou nous pouvons jouer aux intrépides cowboys.}
{105}{}{Et quelles sont mes garanties de quitter ce lieu en vie si vous avez l'argent?}
{106}{}{J'ai toujours aimé les westerns.}
{107}{}{Cowboys.}
{108}{}{Le mot des Raider!}
{109}{}{Tu sembles digne de confiance. Tiens, voici ce que tu veux. [Tu lui donnes tes économies]}
{110}{}{Pour moi, ces mots ne signifient rien du tout.}
{111}{}{Donc, un obstiné? J'aime assez ça. Je pense que les gars vont avoir un peu de divertissement avec toi dans ce cas.}
{112}{}{Si tu ne crois pas ces mots, tu devrais croire nos flingues! Une poulle mouillée comme toi n'est pas un problème pour le gang entier!}
{113}{}{Alors dans ce cas, je préfère te tuer. Pour être sûr que personne n'irait bavarder un peu trop aux alentours. Adieu.}
{114}{}{Bon gars. C'est une sage décision. Tu es libre de partir maintenant.}


#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009