#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu vois un éclaireur mutant.}
{101}{}{Qu'est ce que nous avons là? Un normal! Je pense que tu vas venir avec moi.}
{102}{}{Euh.}
{103}{}{Ok.}
{104}{}{Et pourquoi je devrais?}
{105}{}{Pas de chance! [Attaque]}
{106}{}{Tout est on ne peu plus simple: si tu viens avec moi, je t'aiderai.}
{107}{}{Ok. Alors j'accepte.}
{108}{}{Dirige moi juste vers ton chef à la place.}
{109}{}{Pas question!}
{110}{}{Sûr comme l'enfer. Adresse toi à Uthern. Il t'y amènera directement.}
{111}{}{Uthern veut te voir. On dirait qu'il a déjà entendu parler de toi.}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009