#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu reçois 400 points d'expérience pour avoir ramené Tandi.}
{101}{}{Au sud, tu vois un mur d'adobe encerclant un village apparemment paisible.}
{102}{}{Il ne reste de cette région qu'une petite cabane. Heureusement, selon tes archives, l'Abri-15 possède une entrée secondaire.}
{103}{}{Voici un petit bâtiment bordé d'une série de tentes. Les habitants semblent sales et pauvres.}
{104}{}{Tu tombes sur une ville de taille moyenne. Un mur d'épaves de voitures bloque le passage. Un brouillard de fumée plane sur la ville.}
{105}{}{Au sud, tu vois une grande ville entourée de fermes isolées. Cette oasis située en plein désert semble habitée.}
{106}{}{Tu approches d'une ville sombre et en ruine, apparemment quasi déserte. Une odeur de mort plane sur la région.}
{107}{}{Au nord se trouve un petit bâtiment entouré d'une clôture. Des gardes menaçants en armure lourde patrouillent.}
{108}{}{Au nord s'étend un grand cratère.}
{109}{}{Des gardes mutants peuvent être aperçus au nord-est devant une place forte construite à flanc de montagne.}
{110}{}{Un grand bâtiment décoré se dresse vers le ciel. Une foule de gens déambule, sans but.}
{111}{}{Au nord, tu aperçois un entrepôt entouré de bassins remplis d'une substance collante et rayonnante.}
{112}{}{Une grande usine fortifiée aux murs couverts de graffiti et d'impressionnants orifices à canons se dessine devant toi.}
{113}{}{Ce night-club partiellement reconstruit et ces minuscules postes avancés révèlent la présence de bandes.}
{114}{}{Au coeur de la ville se dresse une grande bibliothèque, fortifiée et restaurée, dont l'aspect menaçant a pourtant quelque chose de gracieux. Tu ressens une sensation de paix.}
{115}{}{Un village clôturé, patrouillé par des gardes, attend avec défi au sud.}
{116}{}{Tu découvres sur le sol une empreinte de pas géante. Tu cherches mais tu ne trouves aucune autre trace aux alentours.}
{117}{}{La région est couverte de traces de brûlé et de cendres.}
{118}{}{Cette région semble avoir été touchée par une bombe à haute pression.}
#Traduit par Ultramedecine
{119}{}{Tu vois le camp d'une bande de Raiders nomades. On dirait que tu es tombé au mauvais endroit au mauvais moment.}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009