#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009
{100}{}{Tu vois Kyle.}
{101}{}{Salut l'ami, comment ça va? Encore à voyager à pieds... Tu n'es pas fatigué? Peut être qu'il serait temps de penser à un moyen de locomotion pour tes trajets? Es-tu prêt à dépenser de l'argent?}
{102}{}{Comment je vais? On ne peut mieux! Et as-tu vraiment un moyen de locomotion pour moi? L'argent n'est pas un soucis.}
{103}{}{Si je te charcute un peu, tu me donneras peut être ça gratuitement?}
{104}{}{C'est une bonne question. Il semblerai que je doive venir te voir plus tard.}
{105}{}{Hmmm.... Et bien, je ne suis pas sûr. Un acheteur plus riche sera d'une meilleure utilité. Ecoute, pourquoi ne reviendrais tu pas un peu plus tard, quand tu auras plus de caps?}
{106}{}{Crois moi, un ami à moi possède un VRAI business. Il semble même être la seule personne des Terres Désolées pouvant te vendre une voiture. L'endroit n'est pas très loin d'ici. Cela devrait prendre une journée pour y aller. Le gars utilise sa propre maison comme garage... 400 caps suffiront pour que je te montre la route.}
{107}{}{Marché conclu. Amène moi seulement jusqu'à ton ami et je m'occupe du reste.}
{108}{}{Désolé Kyle. Mais j'ai des choses plus importante à faire.}
{109}{}{Ok, Je vais t'y amener. Tout pour avoir un consommateur satisfait, tout! Suis moi. [Il prend 400 caps]}
{110}{}{Je savais que tu allais jouer les froussards. Tout le monde a peur de voyager avec autant d'argent. Cependant, mes amis Raiders vont pouvoir t'aider pour ça! [Tu viens de comprendre qu'il se passe quelque chose d'anormal, mais soudain un violent coup de pied dans le crâne te met à terre inconscient. La dernière chose que tu perçois est de te faire trainer quelque part...]}
{111}{}{Ecoute, sac à merde. Fous le camp. Tes menaces sont vaines.}
{112}{}{Je vais devoir chercher un consommateur plus à ma portée.}

#Fallout 1 Update Mod v1.2.5 traduit par Ultramedecine - 15 septembre 2009