{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Barterman.}
{100}{}{你看见商人。}
#{101}{}{Do you want to trade?}
{101}{}{你想交易吗？}
#{102}{}{Click Barter →}
{102}{}{点击交易→}
#{103}{}{Nope.}
{103}{}{不。}
#{104}{}{We have been plagued by Rad Scorpions for some time now. All who have been sent to destroy these monsters have not returned. I will give you weapons and armor if you will follow my guide to their lair and kill them all.}
{104}{}{辐射蝎折磨我们很长时间了。那些派去对付这些怪物的人都没回来。如果你愿意让我的人带你到它们的窝里干掉它们，我就给你武器装备。}
#{105}{}{Sounds good.}
{105}{}{听起来不错。}
#{106}{}{No thanks.}
{106}{}{不，谢了。}
#{107}{}{That is a shame. Please leave.}
{107}{}{那真可耻。请你走吧。}
#{108}{}{Excellent. Sammy here will guide you to the lair. Take these items, they will come in useful. }
{108}{}{好极了。萨米会带你去它们的窝。拿上这些东西，它们会有用的。}
#{109}{}{Please help us as soon as possible. Time is wasting.}
{109}{}{请从速解决。时不我待。}
#{110}{}{I don't talk to your kind, stranger.}
{110}{}{我不和你这种人说话，陌生人。}
