{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Billy.}
{100}{}{你看见比利。}
#{101}{}{Hi there.}
{101}{}{嘿，你。}
#{102}{}{Hi, what are you doing?}
{102}{}{嘿，你在干嘛？}
#{103}{}{Can I have a brahmin?}
{103}{}{我能要一头双头牛吗？}
#{104}{}{Hi.  Uh, bye.}
{104}{}{嘿。喔，再见。}
#{105}{}{Arg!}
{105}{}{啊喔！}
#{106}{}{Ta.}
{106}{}{切！}
#{107}{}{Why would you want a brahmin? Do you have a caravan? Well, it doesn't matter. I only take care of them. Dan is the one that owns them; he won't sell them though.}
{107}{}{你为什么想要双头牛？你有货车吗？算了，这都无所谓。我只是看牛的。丹才是主人；不过他是不会卖的。}
#{108}{}{Why?}
{108}{}{为什么？}
#{109}{}{I was just kidding.}
{109}{}{我只是开个玩笑而已。}
#{110}{}{Cuz of all the missing caravans. He doesn't have any to spare, the caravans use most of them. The others are sold for food. Well, I better stop talking; Dan will get mad if he sees me talking to a stranger.}
{110}{}{是因为那些失踪的商队。他没多少可卖了，大部分被商队用了。其余的卖了换了粮食。算了，我还是不说了；要是丹看到我和陌生人说话，他会气疯的。}
#{111}{}{Oh, okay.}
{111}{}{喔，好的。}
#{112}{}{Nothing . . . I mean, I'm taking care of the brahmin.}
{112}{}{没什么……我是说，我在照看双头牛。}
#{113}{}{What's the spear for? Are they dangerous?}
{113}{}{这根矛是用来干什么的？它们很危险吗？}
#{114}{}{What's a brahmin?}
{114}{}{双头牛是什么？}
#{115}{}{What's a brahmin? You must be joking. Why they're one of the major food sources and forms of transportation around here. They haul the caravans. Dan says this is a really important job, but it's the Bone.}
{115}{}{双头牛是什么？你在开玩笑吧。我们吃喝运货就靠它。它们还能拖货车。丹说这是真正重要的工作，不过没什么油水。}
#{117}{}{Dan's right. You are doing a great job.}
{117}{}{丹说得对。你是在做一件重要的工作。}
#{118}{}{Yea, it looks that way. Have fun.}
{118}{}{是啊，看来是这样。玩得开心点。}
#{119}{}{Hey, you're one of those skags aren't you?}
{119}{}{嘿，你是那些蠢货里的一个，是不是？}
#{120}{}{Really? You think so? Gee, thanks.}
{120}{}{真的？你这么想？多谢啦。}
#{121}{}{You're not from around here, are you? I'll give you one tip: Don't get caught stealing!}
{121}{}{你不是这里的人，是吧？我会给你一条忠告：别因为偷东西被逮住了！}
#{122}{}{Sure, thanks.}
{122}{}{当然，谢谢。}
#{123}{}{I wouldn't dream of stealing. Stealing is wrong.}
{123}{}{我做梦都不会想到去偷东西。偷东西是不好的。}
#{124}{}{Yea, I think I'm starting to agree with you. This job isn't so bad, really. It makes me feel good for some reason. Well, I've got to go before I get in trouble.}
{124}{}{是的，我想我开始同意你的看法了。这份工作其实也不是那么糟。它在有些地方让我觉得很好。好了，在我有麻烦之前，我得走了。}
#{125}{}{Please don't hurt me or my brahmin.}
{125}{}{请别伤害我和我的牛。}
#{126}{}{Don't hurt me!}
{126}{}{不要伤害我！}
#{127}{}{Stop it!}
{127}{}{停下来！}
#{128}{}{Please leave me alone.}
{128}{}{请你离我远点。}
#{129}{}{You're scaring me.}
{129}{}{你吓着我了。}
#{130}{}{Hey what are you trying to do?  I don't have anything you'd want.}
{130}{}{嘿，你想干什么？我没有你想要的东西。}
#{131}{}{Stop that!}
{131}{}{停下来！}
#{132}{}{Dangerous? No, not really. They can give you a really nasty bite, but they're pretty cool. They fart and burp a lot. I don't know why.}
{132}{}{危险？不，其实没什么危险。它们会给你来上一大口，不过它们挺酷的，经常又放屁又打嗝，我也不知道为什么。}
{133}{}{那这根矛用来干什么？}
#{134}{}{Okay, thanks.}
{134}{}{好了，谢谢。}
#{135}{}{Oh, they can be awfully stubborn when I want them to do something.  I just gently stick them to get them to move around . . .  plus I don't want to get too close; they sometimes kick. }
{135}{}{喔，我要它们去做什么的时候，它们犟得要死。我只好轻轻地打着它们走……另外我也不想靠它们太近了，它们有时会踢人。}
#{136}{}{Please don't talk to me. Dan is going to yell at me again.  He really gets pissed -  I mean - mad, when I'm not paying attention to what I'm doing.}
{136}{}{请你不要和我说话了。丹又要吼我了。我不专心干活的话，他会很愤怒–我是说-狂怒。}
#{137}{}{He's just trying to help. Work hard and I'm sure he'll be nicer.}
{137}{}{他只是想帮忙。努力工作后我想他会更好的。}
#{138}{}{Here kid, take 50 bucks and get away from this jerk.}
{138}{}{这里，孩子，拿上50个瓶盖，离开这个笨蛋。}
#{139}{}{Okay.}
{139}{}{好吧。}
#{140}{}{Aaaaaarg!}
{140}{}{啊啊啊啊！}
#{141}{}{Rhu?}
{141}{}{嗯？}
#{142}{}{Please don't, I'm already in enough trouble.}
{142}{}{请别这样，我已经有大麻烦了。}
#{143}{}{I AM working hard!}
{143}{}{我干的很努力！}
#{144}{}{I'm sorry, I didn't mean that. He's just trying to help you.}
{144}{}{对不起，我不是那个意思。他只是想帮你。}
#{145}{}{No you aren't, you lazy little skeev!}
{145}{}{不，你没有，你这条懒虫！}
#{146}{}{Okay. }
{146}{}{好吧。}
#{147}{}{Yea, maybe you're right . . . actually, he seems pretty cool, but I wish he wouldn't yell at me so much.}
{147}{}{是的，也许你是对的……实际上，他看起来很酷，但我希望他不要动不动就朝我吼叫。}
#{148}{}{Yea, right.}
{148}{}{是的，是这样。}
#{149}{}{Up yours, you old fart!}
{149}{}{去你的，你个老混蛋！}
#{150}{}{Up yours, you old hag!}
{150}{}{去你的，你个老巫婆！}
#{151}{}{WOW! I can live on this for the rest of my life! Thanks a lot, mister!}
{151}{}{哇！下半辈子我可以靠这个过了！太感谢了，先生！}
#{152}{}{WOW! I can live on this for the rest of my life! Thanks a lot, ma'am!}
{152}{}{哇！下半辈子我可以靠这个过了！太感谢了，女士！}
#{153}{}{WOW! Thanks . . . Well? . . . You're just trying to get me in trouble again!}
{153}{}{哇！谢……嗯？……你是想再给我惹上麻烦！}
#{154}{}{Please don't talk to me, Dan is really mad.}
{154}{}{请别跟我说话，丹真的很愤怒。}
#{155}{}{Don't worry. I had a talk with him, he'll try to be nicer to you.}
{155}{}{别担心。我和他谈过了，他会对你好一点的。}
#{156}{}{And he should be! You're a terrible kid!}
{156}{}{他该这样！你是一个可怕的孩子！}
#{157}{}{Wac.}
{157}{}{恩。}
#{158}{}{Hi!}
{158}{}{嗨！}
#{159}{}{Those girls over there sure are dumb.}
{159}{}{那边的那些女孩肯定是哑的。}
#{160}{}{Hi again.}
{160}{}{嗨！}
#{161}{}{Brahmin are cool.}
{161}{}{双头牛很酷。}
#{162}{}{Dan's taking me to the Falcon if I do a good job.}
{162}{}{如果我干得好，丹会把我介绍给马耳他猎鹰酒吧。}
#{163}{}{Dan's going to take me on a caravan some day!}
{163}{}{将来丹会带我进商队！}
#{164}{}{I'm going to be an adventurer when I grow up.}
{164}{}{我长大以后要当一个冒险家。}
#{165}{}{Really? Oh, okay. I hope you didn't hurt him. He's really not so bad. He just yells a lot.}
{165}{}{真的？哦，好吧。我希望你没伤着他。他其实并不坏。他只是吼得太多了。}
#{166}{}{Hello again.}
{166}{}{你好。}
#{167}{}{What is it you do again?}
{167}{}{你又要干什么？}
#{168}{}{Can I have a brahmin?}
{168}{}{我能要一头双头牛吗？}
#{169}{}{Just stopping by to see how things are going. Bye.}
{169}{}{只是过来看看情况怎么样。再见。}
#{170}{}{Arg!}
{170}{}{啊！}
#{171}{}{Ta.}
{171}{}{哈。}
#{172}{}{I'd better get back to work.}
{172}{}{我得回去干活了。}
#{173}{}{Those girls over there sure are dumb.}
{173}{}{那边的那些女孩肯定是哑的。}
#{174}{}{Hi again.}
{174}{}{嗨。}
#{175}{}{I'm going to be an adventurer when I grow up.}
{175}{}{我长大以后要当一个冒险家。}
#{176}{}{Brahmin sure do shi . . . uh, poop a lot.}
{176}{}{双头牛确实……唔，放很多屁。}
#{177}{}{I can't talk right now.}
{177}{}{我现在不能说话。}
#{178}{}{I don't want to get in trouble.}
{178}{}{我不想惹麻烦。}
