{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Bob.}
{100}{}{你看见鲍勃。}
#{101}{}{No way I'll let you rob me blind!}
{101}{}{想打劫我，没门儿！}
#{102}{}{Hey, I don't want no trouble!}
{102}{}{嘿，我不想惹什么麻烦！}
#{103}{}{Gimme an iguana on a stick.}
{103}{}{给我一串烤蜥蜴。}
#{104}{}{What can you tell me about a water chip?}
{104}{}{你能跟我说说净水芯片的事吗？}
#{105}{}{What can you tell me about Decker?}
{105}{}{你能跟我说说德克的情况吗？}
#{106}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{106}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{107}{}{Do you know anything about the missing caravans?}
{107}{}{关于失踪的商队，你知道些什么吗？}
#{108}{}{What, me trouble? What gives you that impression?}
{108}{}{什么，我有麻烦？你从哪里看出来的？}
#{109}{}{Me hungry! Grrrr!}
{109}{}{我饿！呃啊！}
#{110}{}{Hi. Welcome to Bob's Iguana Bits, the family eating place. May I take your order?}
{110}{}{嗨！欢迎到“鲍勃的蜥蜴料理”，吃饭的好地方。要来点什么？}
#{111}{}{Gimme an iguana on a stick.}
{111}{}{给我一串烤蜥蜴。}
#{112}{}{What can you tell me about a water chip?}
{112}{}{你能跟我说一些有关净水芯片的事吗？}
#{113}{}{What can you tell me about Decker?}
{113}{}{你能跟我说一些有关德克的情况吗？}
#{114}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{114}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{115}{}{Do you know anything about the missing caravans?}
{115}{}{关于失踪的商队，你知道些什么吗？}
#{116}{}{Anything interesting happening in the Hub?}
{116}{}{哈勃城发生了什么有趣的事吗？}
#{117}{}{Me hungry! Grrrr!}
{117}{}{我饿了！呃啊！}
#{118}{}{Sorry, we're all out of iguana.}
{118}{}{对不起，我们的蜥蜴都卖完了。}
#{119}{}{We only have whole iguana on a stick. Twenty bucks each.}
{119}{}{我们只有烤整蜥蜴了。一个二十块。}
#{120}{}{We only have prime select choice. It tastes great, though. Eight bucks each.}
{120}{}{我们只有精选肉块了。不过吃起来很棒。一个八块。}
#{121}{}{Sure. We got whole iguana on a stick for twenty bucks, and our prime select pieces for eight bucks.}
{121}{}{当然。烤整蜥蜴是二十块，精选肉块是八块。}
#{122}{}{I'll take a whole iguana.}
{122}{}{我来份烤整蜥蜴。}
#{123}{}{I'll take your prime select.}
{123}{}{我来份精选肉块。}
#{124}{}{You know, I hear your prime select tastes like chicken.}
{124}{}{你知道吗，我听说你的烤肉块吃起来像鸡肉。}
#{125}{}{No sissy portions! Me want all iguana! Ugh!}
{125}{}{别小家子气！我要所有的烤蜥蜴！噢！}
#{126}{}{Hmm, smell good! Prime select make tummy happy!}
{126}{}{呣, 闻起来不错！肉块吃得我很舒服！}
#{127}{}{We don't serve that here. Anything else?}
{127}{}{我们这里不卖那个。要点别的？}
#{128}{}{Gimme an iguana on a stick.}
{128}{}{给我一串烤蜥蜴。}
#{129}{}{What can you tell me about Decker?}
{129}{}{你能跟我说一些有关德克的情况吗？}
#{130}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{130}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{131}{}{Do you know anything about the missing caravans?}
{131}{}{关于失踪的商队，你知道些什么吗？}
#{132}{}{Anything interesting happening in the Hub?}
{132}{}{哈勃城发生了什么有趣的事吗？}
#{133}{}{Me hungry! Grrrr!}
{133}{}{我饿！呃啊！}
#{134}{}{Mr. Decker is a distinguished businessman in a less than distinguished business. Anything else?}
{134}{}{德克先生是一个高尚的商人，却从事着并不高尚的行业。还有别的吗？}
#{135}{}{I want information on Doc Morbid.}
{135}{}{我想知道有关莫彼得医生的情况。}
#{136}{}{Gimme an iguana on a stick.}
{136}{}{给我一串烤蜥蜴。}
#{137}{}{Nothing.}
{137}{}{没什么。}
#{138}{}{He was a mean son of a bitch and anyone who isn't glad he's dead is a damned liar. Can I take your order?}
{138}{}{他是个婊子养的杂种，如果他死了，没人会不高兴。你要来点什么？}
#{139}{}{Gimme an iguana on a stick.}
{139}{}{给我一串烤蜥蜴。}
#{140}{}{Tell me a little about the water merchants.}
{140}{}{跟我说一点有关纯水商队的情况。}
#{141}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{141}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{142}{}{Do you know anything about the missing caravans?}
{142}{}{有关失踪的商队，你知道些什么吗？}
#{143}{}{Anything interesting happening in the Hub?}
{143}{}{哈勃城发生了什么有趣的事吗？}
{144}{}{Me hungry! Grrrr!}
{144}{}{我饿了！呃啊！}
#{145}{}{I don't know what you抮e talking about. Okay. I'll pay you one hundred bucks if you keep your mouth shut. Take it and get out.}
{145}{}{好了，我不知道你在说什么。如果你闭嘴，我给你一百块钱。拿着，快走吧。}
#{146}{}{I want two hundred.}
{146}{}{我要两百块。}
#{147}{}{I'll take the hundred.}
{147}{}{行，这一百块我拿了。}
#{148}{}{I'm going to the police.}
{148}{}{我要去警察局。}
#{149}{}{Stop selling them. Now.}
{149}{}{现在不准再卖那些玩艺儿了。}
#{150}{}{Terrible business. Those poor people. Oh, those poor people. Losing their lives in such a ghastly way! Is there anything else I can do for you? Like feed you, perhaps?}
{150}{}{可怕的行当。那些可怜的人。喔，那些可怜虫。小命丢得这么惨！我还能为你做些什么？也许，来点吃的？}
#{151}{}{Gimme an iguana on a stick.}
{151}{}{给我一串烤蜥蜴。}
#{152}{}{What can you tell me about a water chip?}
{152}{}{你能跟我说一些有关净水芯片的事吗？}
#{153}{}{What can you tell me about Decker?}
{153}{}{你能跟我说一些有关德克的情况吗？}
#{154}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{154}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{155}{}{Anything interesting happening in the Hub?}
{155}{}{哈勃城发生了什么有趣的事吗？}
#{156}{}{Nothing. Sorry to bring it up. I just hear stories. Now is there anything else I can do for you?}
{156}{}{没什么。我很抱歉提起它。我只是听到了传言。我还能为你做什么？}
#{157}{}{Gimme an iguana on a stick.}
{157}{}{给我一串烤蜥蜴。}
#{158}{}{What can you tell me about a water chip?}
{158}{}{你能跟我说一些有关净水芯片的事吗？}
{159}{}{What can you tell me about Decker?}
{159}{}{你能跟我说一些有关德克的情况吗？}
#{160}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{160}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{161}{}{Do you know anything about the missing caravans?}
{161}{}{关于失踪的商队，你知道些什么吗？}
#{162}{}{Anything interesting happening in the Hub?}
{162}{}{哈勃城发生了什么有趣的事吗？}
#{163}{}{Someone killed Decker. We're in mourning, at least until the Hub runs out of booze.}
{163}{}{有人杀了德克。我们现在很“悲伤”，一直要到哈勃城的酒被喝光。（嘿嘿）}
#{164}{}{Someone shot Sheriff Greene. Don't know about the deputy though.}
{164}{}{有人向治安官格林开枪。现在还不知道代理治安官情况如何。}
#{165}{}{Daren Hightower was murdered. And all that money couldn't save him. Ironic, ain't it?}
{165}{}{达伦·海托被谋杀了。所有的钱都救不了他的命。很讽刺，是不是？}
#{166}{}{Someone's really pissed off someone important, because I hear that there's a big hit out on some poor sod.}
{166}{}{有人把个大人物惹毛了，因为我听说要收拾一个可怜的家伙。}
#{167}{}{Someone stole a necklace from the Hightowers. Man, did they ever make a big mistake. They're dead for sure.}
{167}{}{有人从海托家里偷了一条项链。老兄，他们犯了大错。他们死定了！}
#{168}{}{Someone killed Jain over at the Cathedral. I hear she was a real bitch!}
{168}{}{有人在大教堂杀了简恩。我听说她是一个真正的婊子！}
#{169}{}{Well, the only new thing is that the Children of the Cathedral have taken over the Hospital. It's pretty boring around here lately. Mind you, they're a strange crowd.}
{169}{}{嗯，唯一的新闻是大教堂教徒接管了医院。最近这里很无聊。你要小心，他们这一伙人很怪。}
#{170}{}{Anything else?}
{170}{}{还要别的吗？}
#{171}{}{Gimme an iguana on a stick.}
{171}{}{给我一串烤蜥蜴。}
#{172}{}{What can you tell me about a water chip?}
{172}{}{你能跟我说一些有关净水芯片的事吗？}
#{173}{}{What can you tell me about Decker?}
{173}{}{你能跟我说一些有关Decker的情况吗？}
#{174}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{174}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{175}{}{Do you know anything about the missing caravans?}
{175}{}{关于失踪的商队，你知道些什么吗？}
#{176}{}{Sorry, you can't afford it.}
{176}{}{抱歉，你肯定买不起。}
#{177}{}{One whole iguana, coming up! Anything else?}
{177}{}{一份烤整蜥蜴来了！还要别的吗？}
#{178}{}{Gimme another iguana on a stick.}
{178}{}{再给我一串烤蜥蜴。}
#{179}{}{What can you tell me about a water chip?}
{179}{}{你能跟我说一些有关净水芯片的事吗？}
#{180}{}{What can you tell me about Decker?}
{180}{}{你能跟我说一些有关德克的情况吗？}
#{181}{}{Do you know anything about the missing caravans?}
{181}{}{关于失踪的商队，你知道些什么吗？}
#{182}{}{Anything interesting happening in the Hub?}
{182}{}{哈勃城发生了什么有趣的事吗？}
#{183}{}{Me want another iguana!}
{183}{}{我还要再来一串烤蜥蜴！}
#{184}{}{Me stuffed! URRRP!}
{184}{}{我饱了！嗝！}
#{185}{}{Sorry, you can't afford it.}
{185}{}{抱歉，你肯定买不起。}
#{186}{}{One iguana prime select choice, coming up! Anything else?}
{186}{}{一份精选肉块来了！还要别的吗？}
#{187}{}{Gimme another iguana on a stick.}
{187}{}{再给我一串烤蜥蜴。}
#{188}{}{What can you tell me about a water chip?}
{188}{}{你能跟我说一些有关净水芯片的事吗？}
#{189}{}{What can you tell me about Decker?}
{189}{}{你能跟我说一些有关德克的情况吗？}
#{190}{}{Do you know anything about the missing caravans?}
{190}{}{有关失踪的商队，你知道些什么吗？}
#{191}{}{Anything interesting happening in the Hub?}
{191}{}{哈勃城发生了什么有趣的事吗？}
#{192}{}{Me want another iguana!}
{192}{}{我还要再来一串烤蜥蜴！}
#{193}{}{Me stuffed! URRRP!}
{193}{}{我饱！嗝！}
#{194}{}{Thank you. Come again!}
{194}{}{多谢光顾。下次再来！}
#{195}{}{You must be new in town if you're asking me about the Water Merchants. Water is life. And you don't get much more powerful than life and death.}
{195}{}{如果你会问我净水芯片的事，那你一定是刚到这城里。水就是命，没有什么其他的东西能大过生死了。}
#{196}{}{Gimme an iguana on a stick.}
{196}{}{给我一串烤蜥蜴。}
#{197}{}{I think we need to talk about Doc Morbid and some of your secret ingredients.}
{197}{}{我想我们该谈一谈有关莫彼得医生和你那些秘密原料的事。}
#{198}{}{Do you know anything about the missing caravans?}
{198}{}{关于失踪的商队，你知道些什么吗？}
#{199}{}{Anything interesting happening in the Hub?}
{199}{}{哈勃城发生了什么有趣的事吗？}
#{200}{}{Me hungry! Grrrr!}
{200}{}{我饿！呃啊！}
#{201}{}{You greedy son of a bitch!}
{201}{}{你这贪心鬼！}
#{202}{}{You greedy whore!}
{202}{}{你这贪婪的婊子}
#{203}{}{All right, you win. Here's your money. Take it and don't come back!}
{203}{}{好吧，你赢了。这是你的钱。拿去，别再回来了！}
#{204}{}{I'd change your mind if I were you, friend. People have died for less in the Hub. Now get out and don't come back!}
{204}{}{朋友，我是你的话就改主意。在哈勃城是很容易丧命的。别再回来了！}
#{205}{}{Maybe I've been using some questionable portions. But it's not like I'm committing murder. Like Morbid's stuff is already dead, ain't it?}
{205}{}{也许我是用了一些可疑的东西。但这和我搞谋杀不一样。莫彼得的原料本来就是死的，是不是？}
#{206}{}{I'm sure it is, Bob. And I'm sure the police will agree.}
{206}{}{我想是的，鲍勃。另外我想警察也会这么认为。}
#{207}{}{Cannibalism is a crime against humanity, Bob. I'm going to see that you pay for your it.}
{207}{}{吃人是违背人性的罪行，鲍勃。我是来惩罚你的。}
#{208}{}{Maybe it is. Maybe it isn't. I don't care. It's immoral. Stop it.}
{208}{}{也许是。也许不是。我不在乎。这是不道德的。不准再干了。}
#{209}{}{No way! I ain't letting you screw me! Eat this!}
{209}{}{决不！我不会让你敲诈我的！尝尝这个！}
#{210}{}{I ain't going broke because of your scruples, but you are going to die from them! Eat this!}
{210}{}{我才不会因为你的狗屁良心而把自己弄破产，不过你倒会送命！尝尝这个！}
