{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{The bookshelf is filled with religious and philosophy books. The bookshelf is very dusty.}
{100}{}{书架上装满了宗教和哲学的书籍。书架上满是灰尘。}
#{101}{}{You take a book down, examine it and quickly replace it on the shelf.  The shelf itself seems very sturdy.}
{101}{}{你拿下一本书，查看了一下，又很快地放回书架。书架本身看上去很坚固。}
#{102}{}{You find a hidden latch.}
{102}{}{你发现一个隐藏的门闩。}
#{103}{}{That does nothing.}
{103}{}{那做不了什么。}
#{104}{}{The wall next to the bookshelf quietly slides out of the way.}
{104}{}{书架旁边的墙无声地滑出一个门来。}
#{105}{}{You fumble with the bookcase for a moment but you fail to accomplish anything.}
{105}{}{你在书架上摸索了一会，但是没找到什么东西。}
#{200}{}{The bookshelf is filled with religious and philosophy books.}
{200}{}{书架上装满了宗教和哲学的书籍。}
#{201}{}{The latch will not budge.}
{201}{}{门闩移动不了。}
