{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see the Doctor's assistant.}
{100}{}{你看见医生的助手。}
#{179}{}{You should see the Doctor.}
{179}{}{你应该去看医生。}
#{180}{}{She's the Doctor, not me.}
{180}{}{她是医生，我不是。}
#{181}{}{I'm only in training.}
{181}{}{我只是在实习。}
#{182}{}{I can't help you, officially.}
{182}{}{从理论上说，我不能帮你。}
#{183}{}{Lori's the Doctor.}
{183}{}{罗伊是医生。}
#{184}{}{You have to ask the Doctor.}
{184}{}{你得去问医生。}
#{185}{}{Don't worry, she's just a kidder.}
{185}{}{别担心，她只是喜欢开玩笑。}
#{186}{}{She just likes to tease, don't worry.}
{186}{}{她只是喜欢开玩笑，别担心。}
