{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see the Brotherhood's Doctor.}
{100}{}{你看见兄弟会的医生。}
#{102}{}{Hello, how can I help you?}
{102}{}{你好，需要我帮忙吗？}
#{103}{}{I'm injured.}
{103}{}{我受伤了。}
#{104}{}{I'm radiated.}
{104}{}{我被辐射了。}
#{105}{}{Do you do operations?}
{105}{}{你会做手术吗？}
#{106}{}{Tell me about the operations again.}
{106}{}{再跟我说说有关手术的事。}
#{107}{}{Ug!}
{107}{}{唔！}
#{108}{}{Are you injured? Let's see...}
{108}{}{你受伤了？让我看看……}
#{109}{}{That was the problem. There you go. Be more careful out there.}
{109}{}{问题在这里。好了。以后在外面要小心些。}
#{110}{}{Sorry, I can't help you if you won't tell me what's wrong.}
{110}{}{对不起，如果你不跟我说哪里不对，我是帮不了你的。}
#{111}{}{ You seem fine.}
{111}{}{你看起来很好。}
#{112}{}{There you are. I hope you feel better.}
{112}{}{好了。我希望你觉得好点了。}
#{113}{}{There you go, but stop getting into fights.}
{113}{}{好了，不过以后别再打仗了。}
{114}{}{那不能把你治疗好。}
#{115}{}{Good as new.}
{115}{}{焕然一新。}
#{116}{}{All healed up.}
{116}{}{全部治愈。}
#{117}{}{Radiation is very dangerous; you should be more careful.}
{117}{}{辐射是非常危险的；你应该更小心些。}
#{118}{}{I don't have the time for games.}
{118}{}{我没时间玩游戏。}
#{119}{}{But of course, but it's very costly and time consuming.}
{119}{}{不过当然了，这是非常昂贵和花时间的。}
#{120}{}{Details?}
{120}{}{详细情况？}
#{121}{}{Okay, never mind.}
{121}{}{好了，没关系。}
#{122}{}{Well, I can help make you stronger, more perceptive, increase your endurance, help improve your learning process, and increase your dexterity. Which would you like more information on? I can only do each operation once.}
{122}{}{好吧，我可以让你更强壮，感觉更敏锐，增强你的忍耐力，提高你的学习能力，并且更敏捷。你想要哪一方面的信息？每种手术我只能做一次。}
#{126}{}{Okay, which operation did you want to talk about?}
{126}{}{好吧，你想谈谈那种手术？}
#{127}{}{Strength.}
{127}{}{力量。}
#{128}{}{Perception.}
{128}{}{感知。}
#{129}{}{Endurance.}
{129}{}{忍耐。}
#{130}{}{Intelligence.}
{130}{}{智力。}
#{131}{}{Agility.}
{131}{}{敏捷。}
#{132}{}{Never mind.}
{132}{}{不用了。}
#{133}{}{That's easy to do but there's a long recovery time. It only costs 2000 scripts but takes 3 weeks to heal.}
{133}{}{这个很容易做，但需要一段较长的恢复时间。它只花费2000块钱，但需要3个星期来恢复。}
#{135}{}{I'll do it!}
{135}{}{我要做这个！}
#{136}{}{I'll pass.}
{136}{}{那算了。}
#{137}{}{Now that's a difficult operation. It costs 4000 scripts, but the recovery from this operation is only a week.}
{137}{}{这是个一个困难的手术。它要花费4000块，但恢复时间只需要一个星期。}
#{139}{}{This one's not that difficult. It takes about a week and will cost 3000 scripts.}
{139}{}{这一个没那么困难。它大概需要一个星期，花费3000块。}
#{141}{}{This is the most complex and dangerous! It'll take 3 weeks and costs 6000 scripts.}
{141}{}{这个是最复杂和最危险的！它要3个星期和6000块钱。}
#{143}{}{This isn't that tough of an operation but it is very costly and time consuming. It will take 3 weeks and cost 5000 scripts.}
{143}{}{这个手术没那么困难，但它很昂贵，又费时。它要3个星期和5000块钱。}
#{146}{}{Okay, there you go. I hope the foam didn't irritate your skin.}
{146}{}{好了，完成了。我希望泡沫材料没有刺激你的皮肤。}
#{147}{}{I'm sorry I can't help you if you don't have the money.}
{147}{}{很抱歉，如果你没钱我就不能帮你了。}
#{148}{}{I'm sorry, but you are an outsider. After you're in the Brotherhood for ten years or so I'll be able to do the operation for free, but we have expenses and you're not a regular working member of the Brotherhood, yet.}
{148}{}{我很抱歉，但你是个外人。如果你加入兄弟会十年了，那我会免费给你做手术，但你还不是兄弟会的正式成员，而我们手术的成本很高。}
#{149}{}{Let me know when you have the funds.}
{149}{}{你有钱了就跟我说。}
#{153}{}{Did you want to ask about another one?}
{153}{}{你想问问其他手术吗？}
#{154}{}{Okay, here goes nothing . . . Just kidding. We can start right away. (She gases you and you slowly slip away.)}
{154}{}{好了，没什么……只是开玩笑。我们马上就开始。【她给你做麻醉，你慢慢地昏了过去。】}
#{156}{}{So how are we feeling? (You can already tell the difference.) You're quite a talkative person in your sleep. You're free to go! Good day.}
{156}{}{觉得怎么样？【你感觉到和以前不一样了】你睡着的时候话很多。你可以自由活动了！}
#{159}{}{Out with the old and in with the new . . . (You drop like a rock into an abyss.)}
{159}{}{旧的不去，新的不来……【你像一块石头掉入了黑暗的深渊。】}
#{161}{}{You look exactly the same, but how do you feel? (All of your senses feel much sharper.) Well, you're taking up valuable bed space. Get going!}
{161}{}{你看上去还是老样子，但感觉如何？【你所有的感觉更敏锐了。】好了，你在占用我们宝贵的床位。快走吧！}
#{164}{}{I hope you have a heart . . . (She winks at you as you fall under.)}
{164}{}{我希望你有心跳……【你倒下时她朝你眨眨眼。】}
#{166}{}{Well, you look a little bulkier. (You feel great!) Well, let me know if there are any problems.}
{166}{}{嗯，你看上去变壮了。【你感觉棒极了！】好吧，如果有什么问题就告诉我。}
#{168}{}{Now where's the brain again? What's this thing supposed to do? (You try to fight the drugs but it's a losing battle.)}
{168}{}{现在你的头脑呢？接下来要做什么？【你想和药物争斗，但那是徒劳的。】}
#{170}{}{Well, it looks like I got it all back in and everything's running great. (It's as if the pathways of your thoughts have direct links to everywhere in your head and your memories are much crisper.) Take it easy.}
{170}{}{嗯，看来都恢复了，一切正常。【似乎你的思路和记忆都更清晰了。】放松。}
#{174}{}{All right, let's give it a spin. (The drugs, are so . . . friendly. Your slumber comes quickly.)}
{174}{}{好吧，我们开始吧。【药物，如此……美妙。你很快沉入梦乡。】}
#{176}{}{Okay you're ready for duty. (You flex your muscles and can feel the increased speed and control.) All I ask of you is to please not damage my masterpiece.}
{176}{}{好了，你已经适合行动了。【你活动你的肌肉，感觉速度和控制提高了。】我唯一的要求是请你别让我的杰作被损坏了。}
#{200}{}{You see the Doctor's assistant.}
{200}{}{你看见医生的助手。}
#{279}{}{You should see the Doctor.}
{279}{}{你应该去看医生。}
#{280}{}{She's the Doctor, not me.}
{280}{}{她是医生，我不是。}
#{281}{}{I'm only in training.}
{281}{}{我只是在实习。}
#{282}{}{I can't help you, officially.}
{282}{}{从职务上说，我不能帮你。}
#{283}{}{Lori's the Doctor.}
{283}{}{罗伊是医生。}
#{284}{}{You have to ask the Doctor.}
{284}{}{你得去问医生。}
#{285}{}{Don't worry, she's just a kidder.}
{285}{}{别担心，她只是喜欢开玩笑。}
#{286}{}{She just likes to tease, don't worry.}
{286}{}{她只是喜欢开玩笑，别担心。}
#{300}{}{I'm sorry but this operation will not help you.}
{300}{}{很抱歉，但这个手术帮不了你什么。}

#{400}{}{Hmmm. If anyone here needs an Intelligence Enhancement, it would be you. In fact, I'll do it for 3000 caps instead of the 6000 you would normally need for the operation. I can't guarantee that it will help you, but I think it would be worth a try. It will also take 3 weeks of recovery time. You probably don't understand this though, do you?}
{400}{}{呣。如果这里有人需要提高智力，那就是你。事实上，我只收你3000块钱，而不是正常情况下的6000。我不能保证手术能帮你什么，但我想值得一试。手术需要3个星期的恢复时间。不过，你大概理解不了这些，是不是？}
#{401}{}{Me want smart.}
{401}{}{俺要变聪聪。}
#{402}{}{No want.}
{402}{}{俺不要。}
#{403}{}{Are you radiated or hurt? I'll help you if I can.}
{403}{}{你是受辐射了还是受伤了？我会尽力帮你的。}
#{404}{}{mE hUrt.}
{404}{}{俺伤了。}
#{405}{}{hAir faLl ouT.}
{405}{}{头发掉掉。}
#{406}{}{No.}
{406}{}{不。}
#{407}{}{Ok. You're awake. Let's see here. Do you feel any smarter?}
{407}{}{好了。你醒了。来看看。你觉得聪明点了吗？}
#{408}{}{Hunh?}
{408}{}{嗯？}
#{409}{}{Yes!}
{409}{}{是！}
#{410}{}{Damn! It was a failure. Well I didn't have much to work with. Sorry, you're just an idiot and will most likely remain an idiot. We can only do the operation once, sorry to say.}
{410}{}{该死！失败了。好了，我没什么能做的了。抱歉，你就是一白痴，看来永远都得是了。我很遗憾地告诉你，这个手术我们只能做一次。}
#{411}{}{It was a success! I was able to increase your IQ to an acceptable level. How does it feel to have half a brain?}
{411}{}{成功了！我把你的IQ提高到了可接受的水平。有了一半脑子能用是什么感觉？}
#{412}{}{It's great. Thanks, Doc. Bye.}
{412}{}{太棒了。谢谢，医生。再见。}
#{413}{}{There you go. All better}
{413}{}{好了。都好了。}
