{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Holy crap! Kill it!}
{100}{}{天哪！杀了它！}
#{101}{}{Shoot that beast before it eats him!}
{101}{}{在那畜牲吃掉他之前射死它！}
#{102}{}{Guns!}
{102}{}{枪！}
#{103}{}{Get him out of there!}
{103}{}{把他弄出去！}
#{104}{}{Don't go inside the ring, chump.}
{104}{}{别走进这场子，白痴。}
#{105}{}{Hey, where do you think you're going?}
{105}{}{嘿，你想去哪里？}
#{106}{}{Talk to Gustofer if you want to bet.}
{106}{}{如果你想赌钱就去和古斯托弗说。}
#{107}{}{Boxing matches at 2:00 every third day.}
{107}{}{拳击比赛在每隔三天的两点钟举行。}
