{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a stern, young initiate with a book.}
{100}{}{你看见一个年轻新兵拿着一本书表情严肃。}
#{101}{}{You see Initiate Brenden.}
{101}{}{你看见新兵布兰顿。}
#{102}{}{Good day. How may I be of assistance?}
{102}{}{你好。我能帮你吗？}
#{103}{}{I'm looking for Master Scribe Vree.}
{103}{}{我要找首席研究员弗蕾。}
#{104}{}{I'm looking for General Maxson.}
{104}{}{我要找马克松将军。}
#{105}{}{I'm looking for Paladin Rhombus.}
{105}{}{我要找游侠隆伯斯。}
#{106}{}{What're you reading?}
{106}{}{你在看什么书？}
#{107}{}{Gaahh.}
{107}{}{嘎嘎。}
#{108}{}{Hmm. Apparently I may not be of assistance.}
{108}{}{呣。显然我帮不了你。}
#{109}{}{Master Scribe Vree is on level three, in the computer lab.}
{109}{}{首席研究员弗蕾在第三层，在计算机室里。}
#{110}{}{General Maxson is usually on level four, in the council chambers.}
{110}{}{马克松将军通常在第四层，在会议室里。}
#{111}{}{Paladin Rhombus spends most of his time on level one, in the supply room.}
{111}{}{游侠隆伯斯大部分时间都在第一层，在库房里。}
#{112}{}{Is there anything else I can help you with?}
{112}{}{还有别的需要我帮忙吗？}
#{113}{}{Thanks. Good day.}
{113}{}{多谢了。再见。}
#{114}{}{Actually, it is a journal that I am keeping. I'm working on a treatise on the social dynamics of the Brotherhood.}
{114}{}{实际上，这是一本日记。我正在写一篇有关兄弟会的社会动力学方面的论文。}
#{115}{}{Hmm. Sounds interesting.}
{115}{}{嗯。听起来很有趣。}
#{116}{}{So, what's the point?}
{116}{}{那么，重点是什么？}
#{117}{}{Indeed. I've been researching information about our predecessors from before the war and about the societies of the outside world. I think that the Brotherhood comes closest in organization to the Knights Templar of the so-called 'Dark Ages'.}
{117}{}{确实。我一直在研究有关战前我们祖先，还有外部社会的资料。我认为兄弟会在组织上和所谓的“黑暗时代”的圣殿骑士团最相似。}
#{118}{}{Why did you decide to study this?}
{118}{}{你为什么要研究这些？}
#{119}{}{The Knights Templar?}
{119}{}{圣殿骑士团？}
#{120}{}{Although the Brotherhood places a high emphasis on hard sciences and applications technology, there has been little in the way of research into the soft sciences, like psychology and sociology. For a well-rounded education, we must apply scientific thought to all endeavors.}
{120}{}{兄弟会把重点放在自然科学和应用技术上，几乎没有对人文科学的研究，比如心理学和社会学。对于一种全面发展的教育来说，我们必须把科学的思考方式应用到所有的实践中。}
#{121}{}{So what have you discovered?}
{121}{}{那么你发现了什么？}
#{122}{}{I've come to the conclusion that the Brotherhood functions mostly like a pseudo-religious organization. We have the strong military hierarchy, combined with codes of honor passed down from our ancestors. Combine this with our technical skills and I think that there are two paths of development for the Brotherhood: a techno-religious dictatorship or a benevolent research society.}
{122}{}{我已经得出了结论，兄弟会的运转非常像一个伪宗教组织。我们有强大的军事集团，结合了我们的前辈流传下来的荣誉感。再综合我们的技术力量，我认为兄弟会的发展有两条路：一个技术-宗教的专政或者一个慈善的研究团体。}
#{123}{}{What could influence the development of the Brotherhood?}
{123}{}{有什么会影响兄弟会的发展？}
#{124}{}{Ultimately we have a command heirarchy, with the Elders at the top. The most influential positions, then, are the Elders and the High Elder. A charismatic High Elder could direct the Brotherhood almost completely. We need to be careful to make sure that we have a leader who is both strong and visionary. Thankfully, I think that General Maxson fits that description.}
{124}{}{从根本上来说我们有一个领导阶层，元老是最顶极的。最有影响力的职位，就是元老和高级元老。一个具有超凡魅力的高级元老差不多就能完全领导兄弟会。我们必须谨慎，要确认我们的领袖既强硬又有远见。感谢上帝，我想马克松将军就适合这种形容。 }
#{125}{}{According to my research, the Knights Templar were a military brotherhood which focused upon the acquisition of wealth and knowledge. Although they had some religious overtones in their structure, their quest for knowledge ultimately made them a secular organization. I think that they would have been a more theocratic organization if they had a greater interest in wealth and power, since the church of that era was primarily involved in control of gold and land.}
{125}{}{根据我的研究，圣殿骑士团是一个军事化的兄弟会组织，它的目的是积敛财富和知识。尽管他们的组织带有一些宗教的色彩，他们对知识的追求最终使他们成为一个非宗教的团体。我认为如果他们对财富和权力有更大的兴趣的话，他们会成为一个神权组织，因为那个时代的教会基本上都在争夺金钱和土地。}
#{126}{}{And how does this relate to the Brotherhood?}
{126}{}{这和兄弟会有什么关系？}
#{127}{}{We must understand our past if we are to recognize our directions for the future …… but I'm sure you wouldn't understand that.}
{127}{}{如果我们要认识到我们未来的方向，我们就必须了解我们的过去……不过我想你理解不了这一点。}
