{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Scholar Theslin of the Children of the Cathedral.}
{100}{}{你看见大教堂教徒的学者泰斯林。}

#{101}{}{You see Scholar Slater of the Children of the Cathedral.}
{101}{}{你看见大教堂教徒的学者斯拉特。}

#{102}{}{You see Scholar Aunanut of the Children of the Cathedral.}
{102}{}{你看见大教堂教徒的学者奥那尼特。}

#{103}{}{You see Scholar Eikenkoff of the Children of the Cathedral.}
{103}{}{你看见大教堂教徒的学者艾肯考夫。}

#{104}{}{You see Scholar Spikavar of the Children of the Cathedral.}
{104}{}{你看见大教堂教徒的学者斯皮卡瓦。}

#{105}{}{You see Scholar Varalone of the Children of the Cathedral.}
{105}{}{你看见大教堂教徒的学者瓦拉隆。}

#{106}{}{You see Scholar Quinonos of the Children of the Cathedral.}
{106}{}{你看见大教堂教徒的学者奎诺诺斯。}

#{107}{}{You see Scholar Ziegliff of the Children of the Cathedral.}
{107}{}{你看见大教堂教徒的学者齐格利夫。}

#{108}{}{You see Scholar Jones of the Children of the Cathedral.}
{108}{}{你看见大教堂教徒的学者琼斯。}

#{109}{}{You see Scholar Smithe of the Children of the Cathedral.}
{109}{}{你看见大教堂教徒的学者史密斯。}

#{110}{}{Somewhere around here are the plans of the Followers.}
{110}{}{这里应该可以找到末世论者们的部署计划。}

#{111}{}{I am certain that the Followers had a list of all their allies.}
{111}{}{末世论者肯定有一份他们同伙的名单。}

#{112}{}{Those fools should have known better than to mess with our god!}
{112}{}{这些笨蛋应该早点知道和我们的神作对的下场。}

#{113}{}{Be gone, lest you end up as those foolish Followers.}
{113}{}{走开，以免你和这些末世论者落得一样的下场。}

#{114}{}{None shall hinder the cleansing of the wastelands.}
{114}{}{谁都不能阻挡我们净化废土的事业。}

#{115}{}{We offered them peace. They sought war.}
{115}{}{我们给他们和平，他们却要和我们作对。}

#{116}{}{Where did that foolish ghoul come from?}
{116}{}{这些愚蠢的僵尸从哪里来的？}

#{117}{}{Somewhere there has to be a list of all the Followers.}
{117}{}{其他地方应该有一份所有末世论者的名单。}

#{118}{}{Unfortunately, we can only search this place during the day.}
{118}{}{可惜，我们只能在白天搜查这里。}

#{119}{}{We must be wary of the Nightkin, for they search during the darkened hours.}
{119}{}{要让夜行团们精神点，他们负责夜间搜查。}

#{120}{}{May you live in interesting times!}
{120}{}{你还以为现在是探险时代啊！}
