{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see before you a Nightkin.}
{100}{}{你看见一名夜行团成员。}

#{101}{}{Die!}
{101}{}{死！}

#{102}{}{Leave me or die!}
{102}{}{滚开，不然我要你命！}

#{103}{}{I don't like your tone. If my message does not get to the Master,
# I will see to it that your death is slow and painful.}
{103}{}{我不喜欢你的口气。如果我不能面见主教，我会让你死的很难看。}

#{104}{}{I just wanted to compliment you on the great looking hump on your back.
# Your breath could use some work, though . . .}
{104}{}{我只是想说，你背上的驼峰好帅啊，当然，这可能对你的呼吸不好。}

#{105}{}{Could you direct me to the man in charge?}
{105}{}{你能领我去见你们的头儿吗？}

#{106}{}{Man, you could use a drink worse than me!}
{106}{}{老兄，你比我更需要来两杯。}

#{107}{}{I'm not leaving!}
{107}{}{我不会离开！}

#{108}{}{Okay. Me leave.}
{108}{}{好吧，我走。}

#{109}{}{It is unwise to play games with the Nightkin. Get out of here!}
{109}{}{和我们夜行团斗嘴可不是好玩的，快滚！}

#{110}{}{I do not think so.}
{110}{}{我倒不觉得。}

#{111}{}{I shall enjoy watching you die!}
{111}{}{那就让你死得痛快！}

#{112}{}{Do you not listen? It is unwise to ignore the Nightkin.}
{112}{}{你没听见吗！藐视夜行团是很不明智的。}

#{113}{}{I must talk with you. It's urgent!}
{113}{}{我有事要和你说，是急事！}

#{114}{}{Nobody's ever accused me of being wise!}
{114}{}{还没人说过我不明智呢！}

#{115}{}{I just want to speak with the man in charge!}
{115}{}{我就是想和你们管事的说话！}

#{116}{}{You supposed to be tough or something?}
{116}{}{你以为你很拽啊？}

#{117}{}{I'm sorry! Have a good day.}
{117}{}{对不起，再见。}

#{118}{}{You wanna see unwise? It's unwise to give me lip, asshole!}
{118}{}{你想知道什么叫不明智？和我拌嘴就是！白痴！}

#{119}{}{Go upstairs. Others of my kind will judge the worth of your message.}
{119}{}{上楼去。我的弟兄们会听听你带来的信息。}

#{120}{}{This is your last warning!}
{120}{}{最后一次警告你！}

#{121}{}{Sure it is! Big deal . . .}
{121}{}{当然！我是大人物……}

#{122}{}{I REALLY need to speak with the guy in charge!}
{122}{}{我真的真的真的要和你们的头儿说话！}

#{123}{}{Okay! Okay! I'm sorry! Have a good day.}
{123}{}{好吧！好吧！再见。}

#{124}{}{You know what your mistake is? You give warnings. I don't. Die!}
{124}{}{你知道你傻在哪里吗？你会警告我，而我不会警告你的。看招！}

#{125}{}{【done】}
{125}{}{【完成】}
