#{100}{}{You see a devout Children of the Cathedral Member.}
{100}{}{你看到一名大教堂的虔诚教徒。}

#{101}{}{We offer healing of the body to heal the spirit. Can I help you?}
{101}{}{我们可以帮助治疗受伤的身体和精神，你需要帮助吗？}

#{102}{}{Yes. Help me.}
{102}{}{是的，请帮我。}

#{103}{}{Who are you people?}
{103}{}{你们是谁？}

#{104}{}{Uhn.}
{104}{}{哦。}

#{105}{}{That is fine, my child. We will examine you now.}
{105}{}{很好，孩子，我现在就给你做检查。}

#{106}{}{Blessed are the meek of mind. There is nothing wrong with you,
# my child. Run along and play.}
{106}{}{恭顺的人会有好报。你没有受任何伤，我的孩子。去玩吧。}

#{107}{}{You have been healed. Be more careful in the future.}
{107}{}{你的伤治好了。以后要小心。}

#{108}{}{You are wounded.}
{108}{}{你受伤了。}

#{109}{}{You are not wounded. That is good.}
{109}{}{你没受伤，很好。}

#{110}{}{I see you are poisoned.}
{110}{}{看得出，你中毒了。}

#{111}{}{Hmm, some radiation poisoning. Unfortunately, we cannot cure that.}
{111}{}{嗯，你被辐射了。抱歉，我们治不了这个。}

#{113}{}{We require a donation of $}
{113}{}{我们需要你捐助}

#{114}{}{ before we can heal you. Is this acceptable?}
{114}{}{元才能给你治伤。可以吗？}

#{115}{}{Yes.}
{115}{}{好。}

#{116}{}{No.}
{116}{}{不干。}

#{117}{}{But I don't have that kind of money!}
{117}{}{可是我没那么多钱啊。}

#{118}{}{Will you take $}
{118}{}{要不给你}

#{119}{}{?}
{119}{}{元？}

#{120}{}{The Children do not haggle. Now, will you accept our price?}
{120}{}{我们不讨价还价。你到底接不接受这个价格？}

#{121}{}{Yes, of course I will}
{121}{}{好，当然。}

#{122}{}{No thank you.}
{122}{}{不，谢了。}

#{123}{}{Thank you, my son. Let us pray for your healing.}
{123}{}{谢谢，我的孩子，那我们开始治疗吧。}

#{124}{}{Thank you, my daughter. Let us pray for your healing.}
{124}{}{谢谢，我的孩子，那我们开始治疗吧。}

#{125}{}{There you go. Peace and blessings of the Children go with you.}
{125}{}{好了。愿教徒的和平和祝福永远伴随你。}

#{126}{}{You do not have enough money. If you donate all you can, we
# will heal you. Is this acceptable?}
{126}{}{你的钱不够，那你捐出所有的钱，我们还是愿意给你治疗的，可以吗？}

#{127}{}{Yes.}
{127}{}{好。}

#{128}{}{No.}
{128}{}{不。}

#{129}{}{If you donate all you can, we will heal you. Is this acceptable?}
{129}{}{捐出你所有的钱，我们就给你治疗的，可以吗？}

#{130}{}{Yes.}
{130}{}{好。}

#{131}{}{No.}
{131}{}{不。}

#{132}{}{You have more than enough to make the donation. You need schooling
# in math, my child.}
{132}{}{你的钱是有能力捐助的，你应该好好学学数学，我的孩子。}

#{133}{}{We are the Children of the Cathedral. We live and work amongst those
# unfortunates living in the wasteland. If you ever get to the Boneyard,
# stop by the Cathedral.}
{133}{}{我们是大教堂的教徒。我们和废土上受难的人们一起生活和奋斗。如果你到了晒骨场，可以去教堂参观一下。}

#{134}{}{Thank you.}
{134}{}{谢谢。}

#{135}{}{What do you do?}
{135}{}{你是干什么的？}

#{136}{}{We are the healers and teachers of peace. We heal the body to heal
# the spirit. All we ask is a small donation to pay for our healing
# supplies.}
{136}{}{我们是医疗师，也是和平的布道者。我们治疗身体的伤痛，也治疗人们的灵魂。我们只要求一点点相当于医疗成本的捐献。}

#{137}{}{Sounds like a good idea to me.}
{137}{}{听起来很不错。}

#{138}{}{Sounds like a load of crap, if you ask me.}
{138}{}{我看这都是胡说八道。}

#{139}{}{We did not ask you. I can tell you are tired of listening to
# our beliefs. If you need anything else, we will be here.}
{139}{}{我们不管你怎么想。你大概不愿意听我讲信仰问题了。那么，如有需要，欢迎你来找我们。}

#{140}{}{It is the most holy of ideas. We are working towards ultimate
# peace in the wasteland. All creatures shall live as one.}
{140}{}{这是最崇高的信念！我们致力于废土的最终和平。所有生物都会化为一身。}

#{141}{}{Thank you. Good day.}
{141}{}{谢谢，再见！}

#{142}{}{We have no time to talk. We are leaving. This place is
# dangerous for us.}
{142}{}{没时间聊天了。我们要走了，这地方太危险了。}

#{143}{}{Why are you doing this? We will do you no harm!}
{143}{}{你为什么要这么做？我们又没伤害你！}


{1099}{}{?}
{1199}{}{我可以告诉你：Cathedral-大教堂、Mutants-变种人、Master-主教、Boneyard-晒骨场、Followers-末世论者、Chip-芯片、Apocalypse-末世论、Necropolis-大墓地城、Set-赛特、Watershed-水处理房、Hall-亡者大厅。}


{1000}{}{Cathedral}
{1001}{}{Mutants}
{1002}{}{Master}
{1003}{}{Boneyard}
{1004}{}{Followers}
{1005}{}{Chip}
{1006}{}{Apocalypse}
{1007}{}{Necropolis}
{1008}{}{Set}
{1009}{}{Watershed}
{1010}{}{Hall}

#{1100}{}{That is us.}
{1100}{}{那就是我们。}

#{1101}{}{They are people who got mutated from the nuclear
# fallout. But they are still good people.}
{1101}{}{那是受辐射尘的污染而变异的人类，其实他们还是好人。}

#{1102}{}{We all have masters, don抰 we?}
{1102}{}{我们都有自己的主教，对吧？}

#{1103}{}{The boneyard is a breeding ground of hatred. There are
# the Followers of the Apocalypse, the gangs: The Rippers, The Blades,
# and The Gunrunners, and a small settlement called Adytum. }
{1103}{}{晒骨场是滋生恨意的地方。那里有末世论者、电锯党、利刃帮、军火商，还有一个很小的内城区。}

#{1104}{}{They are people who seek to destroy the peace which
# the Master is trying to set forth.}
{1104}{}{他们妄图把主教想缔造的和平摧毁。}

#{1105}{}{I have no clue as to what you are talking about.}
{1105}{}{我不知道你说的是什么东西。}

#{1106}{}{They are people who seek to destroy the peace which
# the Master is trying to set forth.}
{1106}{}{他们妄图把主教想缔造的和平摧毁。}

#{1107}{}{That is here. The sad remnants of a ancient world.}
{1107}{}{就是这里。古代世界的一个悲哀的遗存。}

#{1108}{}{I believe he is one of the ghouls.}
{1108}{}{他应该是一个僵尸。}

#{1109}{}{That is right over there to the northeast.}
{1109}{}{往东北走就可以看到了。}

#{1110}{}{I don't know anything about that.}
{1110}{}{我不知道这个东西。}

