{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a Children of the Cathedral technician.}
{100}{}{你看到一名大教堂教徒技师。}

#{101}{}{Drop your weapons and the Nightkin will let you live.}
{101}{}{放下你的武器，夜行团会饶你一命。}

#{102}{}{Join us, don't fight us.}
{102}{}{加入我们，别跟我们作对。}

#{103}{}{You will become one with the Unity!}
{103}{}{你会成为“同一”的一员。}

#{104}{}{Nightkin, take this fool prisoner. Our Master will be pleased.}
{104}{}{夜行团！抓住他。主教会喜欢的。}

#{105}{}{Please don't kill me. I only work here.}
{105}{}{别杀我，别杀我。我只是在这里混口饭吃。}

#{106}{}{You wouldn't kill an unarmed man, would you? Would you?!}
{106}{}{你不会对一个手无寸铁的人下毒手吧？对吗？}

#{107}{}{I surrender!}
{107}{}{我投降！}

#{108}{}{You have no right to be here. What do you want?}
{108}{}{你没资格在这里。你想做什么？}

#{109}{}{Hne.}
{109}{}{哼。}

#{110}{}{Who are you?}
{110}{}{你是谁？}

#{111}{}{You sick dogs! I tire of your life!}
{111}{}{你这个恶心的狗崽子！真不想让你活在世界上。}

#{112}{}{What is this place?}
{112}{}{这是什么地方？}

#{113}{}{You are nearly a Nightkin now. I hope the dipping will not damage
# your intelligence further.}
{113}{}{你已经快是一个夜行团的变种人了。希望“浸泡”还没有把你的智力毁掉。}

#{114}{}{I am part of the Unity. I am a glorious servant of our Master.
# I will be the one who sees you become part of the Unity.}
{114}{}{我是“同一”的一部分。我是主教的光荣仆从！我会让你也成为“同一”的一员的。}

#{115}{}{You will find out soon enough.}
{115}{}{你很快就会知道了。}

#{116}{}{This is the birthplace of the superior race! This is the womb from
# which the armies of god will strike from! From the flesh of the weak comes
# the next race of man. Those who survive the dip will become the soldiers of god,
# and with their hands we shall shape the Unity.}
{116}{}{这里是优越种族的诞生地。这里是神之战士的出击地！弱小的人类将在此演化至新的一代。那些浸泡之后仍能生存下来的人将会成为神的战士，他们将会铸造一个“同一”！}

#{117}{}{You are mad! You are just plain crazy! Die!}
{117}{}{你疯了！你就是疯子！去死！}

#{118}{}{How does it work?}
{118}{}{你们是怎么运作的？}

#{119}{}{You will be bound in the holy restraints. We will lower you into a
# vat of the blood of god, the holiest of holies. The FEV will shape and change
# you. You will be strong. You become a Nightkin if you are fortunate and
# worthy of the honor, else you will die the most painful death possible. Soon, I
# will be honored. I will become strong. Then I will fear no man.}
{119}{}{你会被神圣之缚包围，然后被浸泡到最最神圣的神血池。FEV会改变你的肌体，你会变得更加强壮。如果你受到神的眷顾，就会幸运地成为夜行团的一员，否则就会以最痛苦的形势死去。很快，我就会受到神恩了，我会变壮，我将不再惧怕任何人类！}

#{120}{}{You've been around the Nightkin for far too long. Goodbye.}
{120}{}{你和这些夜行团鬼混了太长时间，再见！}

#{121}{}{Just why are you telling me this?}
{121}{}{你为什么要告诉我这些？}

#{122}{}{Where did you get the FEV from?}
{122}{}{你们从哪里得到FEV的？}

#{123}{}{You will only leave here as part of the Unity, or a lost soul in Hell!
# 【pause】 Besides, I sit down here with a bunch of converts. It felt good to get
# this off my chest.}
{123}{}{你要么在这里成为“同一”的成员，要么就会死得很难看！【停了一下】还有，我成天在这里和一帮子皈依者打交道，这些话吐出来真痛快。}

#{124}{}{Where did you get the FEV from?}
{124}{}{你们从哪里得到FEV的？}

#{125}{}{You killed the Right Hand of god. The Master will be most upset.
# Now, it has come time for us to join the holy flame!}
{125}{}{你杀死了神的得力助手。主教会非常生气的。现在该我们一起加入圣火了。}

#{126}{}{You killed the Master. The death of the Unity is your fault.
# You have caused the death of the human race. I hope you feel good about yourself.}
{126}{}{你杀了主教。“同一”的胎死腹中都是因为你！是你导致了人类的灭亡！你不会还沾沾自喜吧。}

#{127}{}{Hnnn.}
{127}{}{哼。}

#{128}{}{As a matter of fact, I do.}
{128}{}{实际上，我是很沾沾自喜呢。}

#{129}{}{You'll join him in a moment. Pray to whatever god took his place.}
{129}{}{你马上就会和他在一起了。向你的什么破神祈祷吧！}

#{130}{}{I go to join him now, in the holy flames!}
{130}{}{我们加入他了，在圣火中！}
