{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{This looks like the Field Control computer.}
{100}{}{看起来是力场控制计算机。}

#{101}{}{It appears to have a transmitter for field signaling, a receiver for
# remote commands, and a standard radio data communications port.}
{101}{}{看起来是由力场信号传导器、远程指挥接收器和标准无线电数据通信端口组成。}

#{102}{}{As you activate the Field Control computer, you
# can hear a low-pitched hum throughout the complex.}
{102}{}{你打开了力场控制计算机，你听到整个基地里发出一阵低沉的嗡嗡声。}

#{103}{}{You do not use the computer properly.}
{103}{}{你没有正确使用电脑。}

#{104}{}{You cannot deactivate the Field Control computer.
# All the controls are locked and encrypted.}
{104}{}{你不能关闭力场控制计算机，所有的控制端都被锁住并加密。}

#{105}{}{You don't understand the computer operating
# system.}
{105}{}{你无法理解这台电脑的操作系统。}

#{106}{}{The force field subsystems are not nearly protected
# well enough against the likes of your talents.
# You turn off all the force fields on this level.}
{106}{}{力场控制系统在你这样的天才手里不堪一击，这一层所有的力场全部被关闭了。}

#{107}{}{The force field subsystems are well protected, but you
# manage to turn half of them off. It's the best you can do.}
{107}{}{力场系统的防卫很严密，但是你还是解除了一半的力场，这已经是你的极限了。}

#{108}{}{The force field subsystems are protected against
# electronic intrusion. You spend some time working on
# it, but haven't broken them yet.}
{108}{}{力场控制系统能防止电子入侵，你花了些时间破解，但是未能成功。}

#{109}{}{You break the bank in a game of 21 and sneak into
# the main system through the end game screen.}
{109}{}{你好不容易打赢了21点的游戏，并在游戏结束的画面上找到了进入主系统的后门。}

#{110}{}{You play a game of 21 but aren't good enough
# to break it.}
{110}{}{你玩了21点的游戏，但成绩不好，不能突破系统防护。}

#{111}{}{The only folder not protected is the Recreational
# Games folder, which might be used as a backdoor.}
{111}{}{唯一没有加密的目录是“娱乐游戏”，也许这里有后门程序？}

#{112}{}{The only folder not protected is the Recreational
# Games folder.}
{112}{}{唯一没有加密的目录是“娱乐游戏”。}

#{113}{}{You look at the computer in disgust.}
{113}{}{你呆呆地看着电脑。}

#{114}{}{You think all the folders are protected but you
# haven't completed your search.}
{114}{}{你发现所有的目录都被加密，但似乎你没搜全。}

#{115}{}{You have broken into the main system and now need to
# reprogram the force field controls.}
{115}{}{你进入了主系统，现在可以进行力场控制程序重新编译。}

#{116}{}{You gain 800 experience points for your unusual hacking procedures.
# Blackjack!}
{116}{}{由于你以非常规的手段破解了程序，你获得了800点经验值。牛！}

#{117}{}{You link the radio into the force field control computer.}
{117}{}{你将无线电连接到力场控制计算机。}

#{118}{}{Your attempt to wire the radio into the computer fails.}
{118}{}{你想把无线电接到计算机，但失败了。}
