{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a busy cook preparing a meal.}
{100}{}{你看见一个忙着做饭的厨子。}

#{101}{}{I'm too busy to talk right now. I've got to get this meal ready!}
{101}{}{太忙了，我不能和你聊天，我要把饭做好！}

#{102}{}{Hmmm! That smells really good. I bet it tastes great!}
{102}{}{嗯！真香啊，应该很好吃！}

#{103}{}{I'm too busy to talk right now. I've got to get this meal ready!}
{103}{}{太忙了，我不能和你聊天，我要把饭做好！}

#{104}{}{Why, thank you. I'm sure you will enjoy it. Thanks for the compliment.
# I'm going to tell all my friends about you.}
{104}{}{谢谢，你肯定会喜欢这个的！多谢你的夸奖，我会和朋友们说你的好话。}
