
#{100}{}{This computer monitors the machines maintaining the Vault.}
{100}{}{这个电脑监控着避难所所有仪器设施的工作状况。}

#{101}{}{Most of your computer access has been removed by order
# of the Vault AI system.}
{101}{}{避难所智能系统已经把你的大多数电脑权限关闭。}

#{102}{}{This is the Vault 13 Central Computer Core.
# It controls most of the workstations you
# find in the Vault.}
{102}{}{这里是13号避难所的中央计算机核心，多数的工作站都可以在这里找到。}

#{103}{}{You fiddle with the computer but don't really find out anything else
# about it.}
{103}{}{你弄了几下电脑，但实在找不出什么特别的东西。}

#{104}{}{There are lots of blinking lights on this thing.}
{104}{}{这玩意上面有好多小灯闪啊闪的。}
