
#{100}{}{You close the manhole cover.}
{100}{}{你关上了井盖。}

#{101}{}{You open the manhole cover and peer down
# into the darkness. You see a ladder that
# leads into the sewers.}
{101}{}{你打开井盖往下望去，黑漆漆的，只看到一个梯子通往下水道。}

#{102}{}{You strain your muscles, but the heavy iron
# disc is too much for your weak physique. You
# can feel something pop in your back.}
{102}{}{你使足了劲，但是你瘦小的身躯实在推不动沉重的井盖。你感到腰都快断了。}

#{103}{}{The manhole cover is heavy and awkward to lift.}
{103}{}{井盖很重，挪起来恐怕不容易。}
