{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a weather-beaten farmer.}
{100}{}{你看见了一个抱怨天气的农夫。}

#{101}{}{Good day.}
{101}{}{你好。}

#{102}{}{Hello.}
{102}{}{你好。}

#{103}{}{Hubip.}
{103}{}{哈哈咯咯。}

#{104}{}{Hello again.}
{104}{}{你好。}

#{105}{}{What can I do for you?}
{105}{}{你想干什么？}

#{106}{}{What's your name?}
{106}{}{你叫什么？}

#{107}{}{What can you tell me about your village?}
{107}{}{你能说说你们村的事情吗？}

#{108}{}{What are you doing?}
{108}{}{你是做什么的？}

#{109}{}{Nothing, thanks.}
{109}{}{没事，谢谢。}

#{110}{}{I am called Curtis.}
{110}{}{我叫科尔提斯。}

#{111}{}{Our village is small, but we support ourselves. Aside from
# the attacks by raiders and the occasional Rad Scorpion,
# we have no problems. Aradesh is a good leader.}
{111}{}{我们村不大，但是能够自给自足。除了强盗，或者偶尔来点辐射蝎，我们这里没什么大事。亚拉德什是我们的好领袖。}

#{112}{}{I am a farmer. We irrigated the desert many years ago.
# Although the wasteland is harsh, it is possible to
# grow things with patience and time.}
{112}{}{我是种地的。我们很久前就开始灌溉沙漠了，虽然废土环境恶劣，但只要你有耐心和时间，也是能种地的。}

#{113}{}{I see. You seem to be doing pretty well.}
{113}{}{哦，我明白了。你们似乎干的不错。}

#{114}{}{You have all of your fields planted right now? You could
# probably do better with crop rotation.}
{114}{}{你把所有的地都种满了？也许你应该间作，这样会更好些。}

#{115}{}{Crop rotation? What's that?}
{115}{}{间作？什么东西？}

#{116}{}{Never mind.}
{116}{}{算了。}

#{117}{}{You only plant some of your fields, allowing the others to get
# back some of the nutrients that the plants used up. You let the other fields
# become fertile again by just tilling up whatever grows there.}
{117}{}{你在一部分土地上耕作，让另一部分空着恢复肥力。你把这些地耙了，以后会更肥沃的。}

#{118}{}{Huh. Never thought of that. Makes sense, though. Good idea.}
{118}{}{嗯，从没想到。不过很有道理，好主意！}

#{119}{}{Can I ask you another question?}
{119}{}{我们问你其他问题么？}

#{200}{}{You gain 500 experience points for helping to improve the
# agriculture of Shady Sands.}
{200}{}{你提高了沙荫镇的农耕水平，获得500点经验值。}
