{1099}{}{?}
{1199}{}{哈罗德可以告诉你：Richard－理查得、Master－主教、Ghouls－僵尸、Loxley－洛克西里、Cathedral－大教堂、Vault－避难所、War－大战、Decker－德克、Grey－格瑞}


#{100}{}{You see Harold.}
{100}{}{你看到哈罗德。}
#{101}{HROLD0}{
#Spare change, old friend, old pal?  Can you help a poor mutant down on his luck? 【Cough】}
{101}{HROLD0}{给点零钱花好吗，老朋友，老伙计？帮帮我这个可怜的变种人吧？【咳嗽】}
#{102}{}{Yeah, here's $25. Good luck to you.}
{102}{}{好吧，这里是25元。祝你好运。}
#{103}{}{How about $5.}
{103}{}{5元如何。}
#{104}{}{Sorry, don't have any money on me.}
{104}{}{抱歉，我没有钱。}
#{105}{}{Keep away from me!}
{105}{}{离我远点！}
#{106}{}{Uhhh?}
{106}{}{嗯？}
#{107}{HROLD1}{
#Geez. You're worse off than I am, friend. Luck to you.}
{107}{HROLD1}{呃。你比我混得还惨，朋友。祝你好运。}
#{108}{HROLD2}{
#Oh, kind of ya, friend. Very kind. You know, if I could clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{108}{HROLD2}{哦，你真好，朋友。你真是好人。你知道的，如果我清理掉这些粘液，你，会看见老哈罗德眼中的泪水。}
#{109}{}{Why is that?}
{109}{}{怎么会这么感动啊？}
#{110}{}{You're welcome.}
{110}{}{不客气。}
#{111}{HROLD3}{
#【Cough】 Rest of the Hubbers' been picking on me like a bad booger since I came back to town.  I can't leave, though.  When the deals are done 【wheez】 it's still my home.}
{111}{HROLD3}{【咳嗽】自从我回到这个镇子那些哈勃仔把我像垃圾一样对待。但我不能走。虽然受了不少奚落，【喘气】但这里还是我的家啊。}
#{112}{}{What happened to you?}
{112}{}{你怎么了？}
#{113}{}{Who are the Hubbers?}
{113}{}{谁是哈勃仔？}
#{114}{}{Hope things get better. See you around.}
{114}{}{希望事情会变得更好。再见。}
#{115}{HROLD4}{
#Well, after the Great War, my Vault was one of the first to open. 【Takes a deep breath】 Whew.  Long time.}
{115}{HROLD4}{好吧，核战后，我的避难所是第一个打开的。【深呼吸】是啊，很久了。}
#{116}{}{Tell me more about those days.}
{116}{}{告诉我那时的事情。}
#{117}{}{No, no. I meant what happened to change you?}
{117}{}{不，不是。我的意思是什么让你变成这样的？}
#{118}{HROLD5}{
#All started with the sirens.  I was young, but ohh, I do remember that.  Lotta terrible years followed.  And I remember walking outta the Vault late one morning.}
{118}{HROLD5}{所有的事情都是随着打开避难所大门的警报声开始的。我那时候还小，但是，虽然遭了这么多年的罪，我仍然记得当时的事情。我记得我是在一个上午走出避难所的。}
#{119}{}{What did you do then?}
{119}{}{然后呢？}
#{120}{}{Where was your Vault located?}
{120}{}{你的避难所在哪？}
#{121}{}{Do you realize how old that makes you?}
{121}{}{自那以后过了多久了？}
#{122}{HROLD6}{
#You know, 【cough】 I'm not real sure anymore.  West, I think.  Uh wait - east?  Ooh I don't know.  【Hacking cough】}
{122}{HROLD6}{你知道，【咳嗽】我记不清了。西边，我想。哦等等--东边？哦我不知道了。【干咳】}
#{123}{}{What did you do then?}
{123}{}{然后呢？}
#{124}{HROLD7}{
#Well, I was a trader.  Did pretty good making a circuit between survivors.  Lost a lotta good people, though. 【Coughs】}
{124}{HROLD7}{好吧，我那时是个商人。我们在幸存者之间捣腾货物，干得还不赖。可是，也折了很多兄弟。【咳嗽】}
#{125}{}{How?}
{125}{}{他们怎么死的？}
#{126}{HROLD8}{
#Gangers got'em.  Scavengers attacking the caravans.  And mutants, son of a dog, if they weren't springing up like rabbits with a mission. 【cough】 Had to have an army of guards with, just to do a deal.}
{126}{HROLD8}{先是被土匪追杀。后来，拾荒者又抢劫商队。最后是那些变种人，狗娘养的，野兔一样蜂拥而来执行任务。【咳嗽】做什么生意都要雇保镖。}
#{127}{}{Didn't the guards help?}
{127}{}{保镖有用吗？}
#{128}{}{Where were the mutants coming from?}
{128}{}{那些变种人哪里来的？}
#{129}{HROLD9}{
#Course they helped, ya bonehead!  Just too damn many to handle!}
{129}{HROLD9}{你够笨啊，当然是有用的了！但是变种人太多了！}
#{130}{}{How did you survive the mutant attacks?}
{130}{}{你怎么幸免于难的？}
#{131}{HROLD9A}{
#Didn't.  Got killed. 【Laughing cough】 Love that joke.}
{131}{HROLD9A}{没有啊。我死了啊。【笑着咳嗽】真喜欢这个笑话。}
#{132}{}{Uh, yeah.}
{132}{}{哦，是啊。}
#{133}{HROLD10}{
#Everywhere!  Hell, seemed like you couldn't fart without hitting one.  But mostly in the northwest.}
{133}{HROLD10}{漫山遍野！日啊，你放个屁就会砸到一只。但主要是从西北方来。}
#{134}{}{Did you explore that area?}
{134}{}{你去过那个地区吗？}
#{135}{}{Why didn't you just avoid the area?}
{135}{}{为什么你们不避开那个地方呢？}
#{136}{}{You farted northwest?}
{136}{}{你朝西北放屁？}
#{137}{hrold10a}{【Laughs】 Pretty good...Noo...}
{137}{hrold10a}{【笑】很好笑……当然不是了……}
#{138}{HROLD11}{
#We mounted an expedition.  God, Richard.  Richard Grey.  Led a small group of us up there.}
{138}{HROLD11}{我们组织了一支探险队。对了，想起来了，理查德。理查德·格瑞是我们的领袖。}
#{139}{}{Richard Grey?}
{139}{}{理查德·格瑞？}
#{140}{}{Where exactly did you go?}
{140}{}{你们去哪里？}
#{141}{HROLD12}{
#Needed to see what was there.  Maybe stop whatever was churnin them boogers out.  We thought we were prepared.  Were we wrong.}
{141}{HROLD12}{我们想去看看那里有什么。也许能阻止变种人出来。我们以为自己准备的很周到。我们错了。}
#{142}{}{What did you do?}
{142}{}{你们做了什么？}
#{143}{HROLD13}{
#I can't remember the route or anything.  But I am damn sure it was northwest, though...I think.}
{143}{HROLD13}{我记不得路了。但我确定在西北……我想是的。}
#{144}{}{Is there a shorter version of this story?}
{144}{}{可以简略的说吗？}
#{145}{}{What about your leader?}
{145}{}{你的领导怎样？}
#{146}{HROLD14}{
#Richard Grey was a doctor.  Little older than me, and friend was he smart.  He found the source.}
{146}{HROLD14}{理查德·格瑞是个医生。比我年纪稍大一点，是个聪明的哥们。他发现了变种人的源头。}
#{147}{}{And what was that?}
{147}{}{是什么？}
#{148}{HROLD15}{
#I like telling it my way.  Short version will cost you 25 extra, friend.  Which will it be?}
{148}{HROLD15}{我喜欢按自己的意思说。简化版需要你多花25个瓶盖，朋友。同意吗？}
#{149}{}{Ok, long it is.}
{149}{}{好吧，讲长的。}
#{150}{}{Short.}
{150}{}{短的。}
#{151}{}{Short, but I don't have the cash.}
{151}{}{短的，但我没有钱。}
#{152}{}{How about neither, you old fart?}
{152}{}{两个都不要如何，你这个老屁精？}
#{153}{HROLD16}{
#Well, you seem like an okay sort.  I'll speed it up a bit.}
{153}{HROLD16}{好吧，看来你这个人还行。我会尽快讲完。}
#{154}{}{Thanks.}
{154}{}{谢谢。}
#{155}{hrold16a}{Lying to a poor old mutant.  What's the world coming to? 【cough】}
{155}{hrold16a}{欺骗一个可怜的老变种人。这个世界怎么了？【咳嗽】}
#{156}{hrold17}{Little light on funds, huh?}
{156}{hrold17}{钱不够，嗯？}
#{157}{hrold17a}{My way or walk away.  Your choice, friend.}
{157}{hrold17a}{要么按我的说，要么走开。你选吧，朋友。}
#{158}{}{Walking.}
{158}{}{我走了。}
#{159}{}{OK. Long it is.}
{159}{}{好吧。长的。}
#{160}{HROLD18}{
#Some sort of old military base.  We lost a lotta folks getting in there.}
{160}{HROLD18}{某个老军事基地。进基地的路上我们失去了很多同伴。}
#{161}{}{How did you know this base was the cause?}
{161}{}{你怎么知道这个基地是源头？}
#{162}{}{What were you running up against?}
{162}{}{你们碰到了什么？}
#{163}{HROLD19}{
#Robots and such.  Lot of'em.  Damn surprised they was still running after all this time, what with the war and all.  Whooa boy they tore us a good one.}
{163}{HROLD19}{机器人之类的，很多。该死的，这些玩意这么多年来还能用。我们当时被打惨了。}
#{164}{}{What did you do once you got past the robots?}
{164}{}{摆平了机器人后你们都做了什么？}
#{165}{HROLD20}{
#Because it was like someone went bargain shopping at mutantland!  Geez!  Cheaper by the dozens!  Can't figure any other reason except that being the factory.}
{165}{HROLD20}{就像在变种人的地盘上赶集似的！啊！变种人太多了！肯定是有工厂在做变种人，没有其他原因了。}
#{166}{}{Did you examine the base closely?}
{166}{}{你进基地仔细调查过吗？}
#{167}{HROLD21}{
#We got pretty far inside.  Wasn't a lot of us left by then.  Grey, me and couple of others.}
{167}{HROLD21}{我们进的很深。剩下的人不多了。只有格瑞、我和其他几个人了。}
#{168}{}{And then?}
{168}{}{然后呢？}
#{169}{HROLD22}{
#One of them robots got Francine.  Mark was wounded, sent him back to the surface.  Then it was just me and Grey.}
{169}{HROLD22}{机器人打死了弗朗辛。马克受伤了，被送回了地面。然后只剩下了我和格瑞。}
#{170}{}{What ever happened to Mark?}
{170}{}{马克后来怎样了？}
#{171}{}{What happened then?}
{171}{}{然后呢？}
#{172}{HROLD23}{
#To this day, I don't know.  He never made it back here, and...well I...couldn't face the wasteland again, so I...I never looked.}
{172}{HROLD23}{一直没消息，我也不知道。他从没回来，并且……我……也不敢去废土转悠了，因此我……我从没遇见他过。}
#{173}{}{What about you and Grey?}
{173}{}{那你和格瑞呢？}
#{174}{HROLD24}{
#We made it to some sort of central core, like a plant of some sort.  That's when it happened.}
{174}{HROLD24}{我们来到了基地中心，有点像厂房的样子。然后不幸发生了。}
#{175}{}{What?}
{175}{}{什么？}
#{176}{HROLD25}{
#A robot crane crashed into us.  Last I saw of Grey, he was flying through the air in-into some sort of acid bath.  I was in bad shape and...well I passed out.}
{176}{HROLD25}{一台起重机器人掉了下来。我最后看到格瑞时，他被砸飞了掉进了酸液槽。我伤得很重然后……我就晕了。}
#{177}{}{How did you survive?}
{177}{}{你怎样幸免于难的？}
#{178}{}{And you never saw Grey again?}
{178}{}{你再没见过格瑞？}
#{179}{hrold25a}{Didn't.  Got killed...【Laughs then coughs】 God, I love that joke.}
{179}{hrold25a}{没有啊。我死了啊……【笑然后咳嗽】天哪，我喜欢那个笑话。}
#{180}{}{Yeah, I can tell.}
{180}{}{我也看出来了。}
#{181}{HROLD26}{
#Well, I have no idea.  Woke up in the wasteland, barely hanging on.  Got lucky and some traders I knew found me days later.  Good thing, since I was already changing.  They brought me here, and here I've been since.}
{181}{HROLD26}{好吧，我不知道。我是在废土中醒来的，还剩一口气。幸运的是一些商人认出了我，救了我。真是很幸运，我那时候就开始变异了，居然也还有人认识我。他们把我带来这里，我就一直住在这里了。}
#{182}{}{How did you mutate?}
{182}{}{你怎样变异的？}
#{183}{}{Quite a great story.  Thanks.}
{183}{}{真是个很好的故事。谢谢。}
#{184}{hrold26a}{Well...Thanks for letting me tell it.}
{184}{hrold26a}{好的……谢谢你让我讲了这么多。}
#{185}{}{So that was the short version?}
{185}{}{这就是简短的版本？}
#{186}{hrold26a}{Well . . . thanks for letting me tell it.}
{186}{hrold26a}{好的……谢谢你让我讲了这么多。}
#{187}{hrold26b}{For me it was.}
{187}{hrold26b}{对我来说那就是了。}
#{188}{HROLD27}{
#No, you idiot!  I just said I never saw him again, didn't I?}
{188}{HROLD27}{不，你这个白痴！我说过一直没再见到他的，不是吗？}
#{189}{}{How did you survive?}
{189}{}{你怎样幸免于难的？}
#{190}{HROLD28}{
#All's I know, is it was something inside that base.}
{190}{HROLD28}{据我所知，是基地里的某种东西。}
#{191}{}{Do you think it could have been radiation?}
{191}{}{你觉得是辐射吗？}
#{192}{}{Sorry, tough break. Thanks for the story.}
{192}{}{抱歉，休息一下吧。谢谢你的故事。}
#{193}{HROLD29}{
#How the hell should I know?  Grey would've known if anybody could. 【sigh】 Anyway, that's how the deal went down.}
{193}{HROLD29}{我他妈的怎么知道？要是格瑞的话，他肯定知道。【叹气】总之，事情就是这样了。}
#{194}{}{Thanks for the story.}
{194}{}{谢谢你的故事。}
#{195}{HROLD30}{
#Yeah, about a century or two in dog years.}
{195}{HROLD30}{是啊，要是人活1年等于狗活7年的话，起码过了一两个狗世纪了。}
#{196}{}{What?}
{196}{}{什么？}
#{197}{HROLD31}{
#Never mind, that was from my time.  I'm cranky, old and I've been that way ever since I changed.}
{197}{HROLD31}{哦，别介意，那是我对时间的算法。自从我变异后就一直是这么烦躁不安、顽固怪癖了。}
#{198}{}{What did you do before this happened to you?}
{198}{}{你出事之前你在做什么？}
#{199}{HROLD32}{
#Well, I got mutated.  Sure wasn't born this ugly.  Happened when we tried to find out where all the mutants were coming from.}
{199}{HROLD32}{啊，我变异了。我出生时没这么难看。当我们寻找变种人的源头时，我出事了。}
#{200}{}{What happened?}
{200}{}{出了什么事？}
#{201}{HROLD33}{
#It's in the past.  Probably should stay that way.}
{201}{HROLD33}{很久了。就这样吧。}
#{202}{}{Please tell me what happened, it may help me now.}
{202}{}{请告诉我都发生了什么，它对我有用。}
#{203}{}{Have it your way.}
{203}{}{随你。}
#{204}{HROLD34}{
#Well, if you put it that way.  I guess it couldn't hurt.}
{204}{HROLD34}{嗯，如果你这样想的话。我想说说也无妨。}
#{205}{}{Thanks.}
{205}{}{谢谢。}
#{206}{HROLD35}{
#No, no.  It's too painful, even now.  Thanks for the help, friend.  Good luck to you.}
{206}{HROLD35}{不，不。尽管这么多年了，想起来仍然很痛苦。谢谢你的好意，朋友。祝你好运。}
#{207}{HROLD36}{
#You're in the Hub, right?  People who live in the Hub?  Hubbers.  Get it? 【cough】 Sheesh!  Thanks for the help and good luck...think you're gonna need it.}
{207}{HROLD36}{你在哈勃城，不是吗？谁在哈勃城生活？哈勃仔嘛。明白？【咳嗽】谢谢你的帮助并祝你好运……我看你还是需要一点运气的。}
#{208}{HROLD37}{
#You're as bad as the rest of them. 【Wheezing cough】}
{208}{HROLD37}{你像他们一样坏。【喘气、咳嗽】}
#{209}{HROLD38}{
#Oh well, thanks anyway. 【cough】}
{209}{HROLD38}{好的，不管怎样，谢谢。【咳嗽】}
#{210}{HROLD39}{
#Hey, can you help me out, friend?}
{210}{HROLD39}{嗨，你能帮我吗，朋友？}
#{211}{}{Yeah, here's $25.}
{211}{}{给，这是25元。}
#{212}{}{Take $5.}
{212}{}{给你5元。}
#{213}{}{Don't bug me.}
{213}{}{不要打扰我。}
#{214}{}{Uhhh?}
{214}{}{嗯？}
#{215}{HROLD40}{
#Hey, 'preciate it!  Gotta admit, when I first saw you, 【cough】 I figured you might hassle me.}
{215}{HROLD40}{嗨，多谢！不得不承认，当我第一次看见你的时候，【咳嗽】我还以为你是来惹事的呢。}
#{216}{}{Why do you say that?}
{216}{}{为什么你这样说？}
#{217}{}{Nah, not me!  Have a good one.}
{217}{}{不，不是我！祝你愉快。}
#{218}{HROLD41}{
#Oh, hey, it's you again.}
{218}{HROLD41}{哦，嗨，你又来了。}
#{219}{}{Here's $20, if you need it.}
{219}{}{这是20元，如果你需要的话。}
#{220}{}{Hi.}
{220}{}{嗨。}
#{221}{}{Uhh?}
{221}{}{唔？}
#{222}{hrold42}{Just putting me on, huh?}
{222}{hrold42}{想晃点我，是吗？}
#{223}{HROLD43}{
#Anything I can do for you?}
{223}{HROLD43}{我可以帮你做什么？}
#{224}{}{Heard any good words recently?}
{224}{}{近来有什么好消息？}
#{225}{}{I need info on the Deathclaw, and I hear you're the man.}
{225}{}{我需要死亡爪的消息，听说你知道。}
#{226}{}{What's your story?}
{226}{}{你有什么故事？}
#{227}{}{Nope}
{227}{}{不。}
#{228}{hrold43a}{The whole thing?  Well...}
{228}{hrold43a}{整件事？好吧……}
#{229}{HROLD44}{
#Oooh, well thanks.  Hope it wasn't too much of a strain. 【coughs】}
{229}{HROLD44}{哦，谢谢。希望没有给你太多压力。【咳嗽】}
#{230}{HROLD45}{Oooh, that thing.  Friend, that is nightmare city.  Why the hell you asking about that?}
{230}{HROLD45}{哦，那东西。朋友，那东西就像个噩梦。为什么你问它的情况呢？}
#{231}{}{Gonna kill it.}
{231}{}{我要去杀了它。}
#{232}{}{If it catches up with me, I want to know what to do.}
{232}{}{我想知道，如果遇上它，该怎样做。}
#{233}{HROLD47}{Okay.  Well, it's like a damn big man, is what it is.  Got spikes and claws that can cut through the heaviest armor.  But don't let the size fool ya, it's quick.}
{233}{HROLD47}{好的。呃，它看起来就像一个大个子的人，就是这样。角和爪子能破坏最厚的装甲。不要被它的体型骗了，它的速度也很快。}
#{234}{}{Any weaknesses?}
{234}{}{有什么弱点？}
#{235}{HROLD49}{Well, from what I've heard, maybe whack it in the head?  I'd try the eyes.  'Course, there's a problem there.}
{235}{HROLD49}{嗯，我听说，也许是头部？要是我，就打它的眼睛。当然，还有个难题。}
#{236}{}{What kind of problem?}
{236}{}{什么难题？}
#{237}{HROLD50}{You can't look at 'em!  It is said the Death Claw can hypnotize just by lookin'.  Then it walks up and "boom", you're et!}
{237}{HROLD50}{你不能看它们！听说，它们的眼神会让你迷糊。然后，它们走近你，“喀嚓”，你就死了！}
#{238}{}{Great, thanks.}
{238}{}{很好，谢谢。}
#{239}{HROLD51}{Good luck to you...you're gonna need it.}
{239}{HROLD51}{祝你好运……你需要点运气。}
#{240}{}{Could be.}
{240}{}{也许。}
#{241}{HROLD52}{You don't want to know about the Death Claw, and I ain't gonna be the one to tell ya.}
{241}{HROLD52}{你不会想了解死亡爪的，而且我不会告诉你。}
#{242}{HROLD53}{Well, heard one of Decker's men has somebody from the Brotherhood of Steel trapped in Old Town.}
{242}{HROLD53}{嗯，听说德克的手下把钢铁兄弟会的一个家伙关在旧城区了。}
#{243}{}{Thanks.}
{243}{}{谢谢。}
#{244}{HROLD54}{I don't believe this one, but some say an army of mutants is on the way. 【cough】}
{244}{HROLD54}{听说有一支变种人军队正在杀过来，我还是不太相信。【咳嗽】}
#{245}{}{Thanks.}
{245}{}{谢谢。}
#{246}{HROLD55}{Leave me alone. 【cough】}
{246}{HROLD55}{离我远点。【咳嗽】}
#{247}{}{I want to talk to you.}
{247}{}{我想和你说点事。}
#{248}{}{Here's some cash.}
{248}{}{这是一些钱。}
#{249}{HROLD56}{Well, I don't wanta talk to you.  Go away!}
{249}{HROLD56}{好吧，我不会告诉你的。滚开！}
#{250}{HROLD57}{Don't want your money.  Go away. 【cough】}
{250}{HROLD57}{不要你的钱。滚开。【咳嗽】}
#{251}{hrold200}{As much as I love trading, I don't have anything to exchange. 【cough】}
{251}{hrold200}{我喜欢交易，但我没有东西来交换。【咳嗽】}
#{252}{hrold201}{I need to sleep for a while.  I'm kinda tired.}
{252}{hrold201}{我要睡一会。我有点累了。}
#{253}{hrold202}{You might want to be more careful. 【cough】 I've heard that you've wasted several people recently.}
{253}{hrold202}{你要小心点。【咳嗽】我听说这几天你干掉了几个人。}
#{254}{hrold203}{Umm...Decker's looking for you.  He wants to talk. 【cough】}
{254}{hrold203}{嗯……德克在找你。他想和你谈话。【咳嗽】}
#{255}{hrold204}{All I got is clothes and freedom, and the latter's debatable.}
{255}{hrold204}{我有衣服被褥，我也很自由，虽然也不算是绝对的自由。}
#{256}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
{256}{hrold300}{聪明的家伙。是个医生和哲学家。很久以前，他领导了一只探险队，我也是那时候变异的。}
#{257}{hrold301}{Who?  Is he some sort of sex therapist?  I could use one, you know.}
{257}{hrold301}{谁？他是个老军医吗？我需要他的帮助，你知道的。}
#{258}{hrold302}{Mutants.  Doesn't matter what they call themselves.}
{258}{hrold302}{变种人。不管他们怎么称呼自己，他们就是变种人。}
#{259}{hrold303}{Oh, him.  He leads the Thieves Circle.  Thinks he's Robin Hood. 【cough】 He's alright, I guess.}
{259}{hrold303}{哦，他啊。他领导着盗贼团。自以为罗宾汉。【咳嗽】他这个人还算是条汉子，我觉得。}
#{260}{hrold304}{I've seen religions come and religions go, and I hope this one goes.  Soon.}
{260}{hrold304}{我看到很多起起落落的教派，我希望这个教派早点滚蛋。尽早。}
#{261}{hrold305}{Yeah, I came from a Vault.  Too many people, not enough food and water.  But you wouldn't know anything about that, would you?}
{261}{hrold305}{是的，我来自避难所。有很多人，没有足够的食物和水。但说了你也不会明白的，是吧？}
#{262}{hrold306}{Horrible.  The world just went insane.  Long ago, but I'll never forget it.  Never.}
{262}{hrold306}{太可怕了。那时候，整个世界都疯了。很久前的事情了，但是我不会忘记的。绝不会。}
#{263}{hrold307}{【Cough】 Trouble.  Nothing but trouble.}
{263}{hrold307}{【咳嗽】麻烦的人。只会带来麻烦的人。}
#{264}{hrold400}{Well, like I said...}
{264}{hrold400}{是的，就像我说的那样……}
#{265}{}{Nothing, thanks.}
{265}{}{没什么，谢谢。}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

#{266}{HROLD0}{Spare change, old friend, old pal? Can you help a poor mutant
# down on his luck? 【Cough】}
{266}{HROLD0}{给点钱花吧，老朋友，老伙计？你能帮帮我这个变种人吗？【咳嗽】}
#{267}{HROLD0}{Spare change, old friend, old pal? Can you help a poor mutant
# down on his luck? 【Cough】}
{267}{HROLD0}{给点钱花吧，老朋友，老伙计？你能帮帮我这个变种人吗？【咳嗽】}
#{268}{HROLD2}{Oh, kind of ya, friend. Very kind. You know, if I could
# clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{268}{HROLD2}{哦，你真好，朋友。你真是好人。你知道的，如果我清理掉这些粘液，你，会看见老哈罗德眼中的泪水。}
#{269}{HROLD2}{Oh, kind of ya, friend. Very kind. You know, if I could
# clear the gunk out of there, you, just might find a tear in Old Harold's eye.}
{269}{HROLD2}{哦，你真好，朋友。你真是好人。你知道的，如果我清理掉这些粘液，你，会看见老哈罗德眼中的泪水。}
#{270}{HROLD35}{No, no. It's too painful, even now. Thanks for the help, friend.
# Good luck to you.}
{270}{HROLD35}{不，不。尽管这么多年了，想起来仍然很痛苦。谢谢你的好意，朋友。祝你好运。}
#{271}{HROLD35}{No, no. It's too painful, even now. Thanks for the help, friend.
# Good luck to you.}
{271}{HROLD35}{不，不。尽管这么多年了，想起来仍然很痛苦。谢谢你的好意，朋友。祝你好运。}
#{272}{HROLD39}{Hey, can you help me out, friend?}
{272}{HROLD39}{嗨，你能帮我吗，朋友？}
#{273}{HROLD39}{Hey, can you help me out, friend?}
{273}{HROLD39}{嗨，你能帮我吗，朋友？}

#
# Harold's Tell-Me-Abouts
#


{1000}{}{Richard}
{1001}{}{Master}
{1002}{}{Ghouls}
{1003}{}{Loxley}
{1004}{}{Cathedral}
{1005}{}{Vault}
{1006}{}{War}
{1007}{}{Decker}
{1008}{}{Grey}


#{1100}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
{1100}{hrold300}{聪明的家伙。是个医生和哲学家。很久以前，他领导了一只探险队，我也是那时候变异的。}
#{1101}{hrold301}{Who?  Is he some sort of sex therapist?  I could use one, you know.}
{1101}{hrold301}{谁？他是个老军医吗？我需要他的帮助，你知道的。}
#{1102}{hrold302}{Mutants.  Doesn't matter what they call themselves.}
{1102}{hrold302}{他们也是变种人。不管他们怎么称呼自己，他们就是变种人。}
#{1103}{hrold303}{Oh, him.  He leads the Thieves Circle.  Thinks he's Robin Hood. 【cough】 He's alright, I guess.}
{1103}{hrold303}{哦，他啊。他领导着盗贼团。自以为是罗宾汉。【咳嗽】他这个人还算是条汉子，我觉得。}
#{1104}{hrold304}{I've seen religions come and religions go, and I hope this one goes.  Soon.}
{1104}{hrold304}{我看到很多起起落落的教派，我希望这个教派早点滚蛋。尽早。}
#{1105}{hrold305}{Yeah, I came from a Vault.  Too many people, not enough food and water.  But you wouldn't know anything about that, would you?}
{1105}{hrold305}{是的，我来自避难所。有很多人，没有足够的食物和水。但说了你也不会明白的，是吧？}
#{1106}{hrold306}{Horrible.  The world just went insane.  Long ago, but I'll never forget it.  Never.}
{1106}{hrold306}{太可怕了。那时候，整个世界都疯了。很久前的事情了，但是我不会忘记的。绝不会。}
#{1107}{hrold307}{【Cough】 Trouble.  Nothing but trouble.}
{1107}{hrold307}{【咳嗽】麻烦的人。只会带来麻烦的人。}
#{1108}{hrold300}{Brilliant guy.  A doctor and philosopher.  Long ago he lead the expedition where I got changed into a mutant.}
{1108}{hrold300}{聪明的家伙。是个医生和哲学家。很久以前，他领导了一只探险队，我也是那时候变异的。}
