{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Rick, a guard.}
{100}{}{你看见里克，一个守卫。}

#{101}{}{Whadda' ya' want?}
{101}{}{你想干吗？}

#{102}{}{Da... Um...}
{102}{}{那个……嗯呃……}

#{103}{}{Excuse me.  Could I ask you a few questions?}
{103}{}{打扰一下，我能问你一些问题吗？}

#{104}{}{Your head on a stick!}
{104}{}{你脑袋想开花吗！}

#{105}{}{Never mind.}
{105}{}{算了。}

#{106}{}{Get back over to the Eastside, you hop head!}
{106}{}{滚回你的老家去，你这个瞌药仔！}

#{107}{}{Wha?}
{107}{}{什么？}

#{108}{}{I go.}
{108}{}{我走。}

#{109}{}{Make it quick.  I'm not supposed to be talking on the job.}
{109}{}{快点说。我不能在工作的时候瞎扯。}

#{110}{}{Where am I?}
{110}{}{我在哪里？}

#{111}{}{What's your job?}
{111}{}{你是干吗的？}

#{112}{}{Sorry to bother you.  Bye.}
{112}{}{很抱歉打扰你，再见。}

#{113}{}{You'd better watch your step and your mouth, punk!}
{113}{}{别乱走，别乱说，废人！}

#{114}{}{NO!  You'd better watch it!  I'm gonna' put a bullet in your head!}
{114}{}{不！你最好看好你的嘴！我会请你吃花生米！}

#{115}{}{You're not worth my time.}
{115}{}{我不能在你身上浪费时间。}

#{116}{}{If you don't know, you probably shouldn't be here.  This is the Heights.  Mister Hightower lives here
# and he only sees people on appointment.}
{116}{}{如果你不知道，你就不应该在这里。这里是哈勃高地，海托先生住在这里，他只见预约过的客人。}

#{117}{}{What's your job?}
{117}{}{你是做什么的？}

#{118}{}{Can I set up an appointement with Mr. Hightower?}
{118}{}{我可以和海托先生约个见面时间吗？}

#{119}{}{Thanks for your time.}
{119}{}{谢了。}

#{120}{}{I'm here to make sure nobody messes with Mr. Hightower.}
{120}{}{我负责确保海托先生不受打扰。}

#{121}{}{Well, I'm actually interested in killing Mr. Hightower.  It's time to earn your pay!}
{121}{}{很好，我实际上对怎样杀死海托先生很有兴趣。现在先让我搞定你！}

#{122}{}{Where am I?}
{122}{}{我这是在哪？}

#{123}{}{Thanks for your time.  Bye.}
{123}{}{谢谢你。再见。}

#{124}{}{No.}
{124}{}{不。}

#{125}{}{I don't like your attitude.  You'd better leave.}
{125}{}{我不喜欢你的态度。你最好马上离开。}

#{126}{}{All right.  I'm going.}
{126}{}{好吧。我马上就走。}

#{127}{}{Make me, you damn long-haired freak!}
{127}{}{来干我呀，你这个长毛怪物！}

#{128}{}{After sundown nobody is allowed in this area.  The other guards won't even give you a warning.  If they
# catch you they'll attack.  You'd better get back downtown while your head is still attached to your neck.}
{128}{}{晚上不允许有陌生人在这个地方。如果换了别人连警告都不会给，直接把你干掉。你最好趁脑袋没搬家时回到镇子里去。}

#{129}{}{oK.  I gO.}
{129}{}{好，我走。}

#{130}{}{no.  I stAy.}
{130}{}{不。我就在这儿。}

#{131}{}{I'm not going anywhere.}
{131}{}{我哪也不去。}

#{132}{}{Sorry, I'll be on my way.}
{132}{}{对不起，我离开。}

#{133}{}{Man, you are rock-stupid, aren't you?  Take a hike!}
{133}{}{小子，你简直是个花岗岩，离我远点！}