#{100}{}{You see a short, stocky man.}
{100}{}{你看到一个矮小、健壮的男人。}

#{101}{}{We don't like your kind in these parts.}
{101}{}{我们这里不欢迎你这种家伙。}

#{102}{}{Hello, stranger. You look like you're new here. What's
# your name?}
{102}{}{喂，陌生人。你看起来像新来的。你叫什么名字？}

#{103}{}{My name's not important.}
{103}{}{我的名字并不重要。}

#{104}{}{I'm }
{104}{}{我叫}

#{105}{}{.}
{105}{}{。}

#{106}{}{Urgh?}
{106}{}{啊哈？}

#{107}{}{Well, then, neither are you.}
{107}{}{好的，那么，你也是如此。}

#{108}{}{Good to meet you. I'm Ian.}
{108}{}{幸会，我是伊恩。}

#{109}{}{What do you do here?}
{109}{}{你在这儿做什么？}

#{110}{}{I'd like to know more about this place. Can you help?}
{110}{}{我想了解更多关于这地方的消息。你能帮忙吗？}

#{111}{}{Sorry, but I don't have time to waste on morons.}
{111}{}{抱歉，我可没时间浪费在蠢货身上。}

#{112}{}{I was a guard for the merchants of the Hub. However, I was
# shot during a raid by bandits. I've been staying here, since the people
# have helped me recover. Still, my knowledge of the outside world
# and my experience make me useful here. Shady Sands is my
# home now. Occasionally, I even get to visit Junktown or the Hub
# to do some trading, since I'm the only person here who has ever
# really left town.}
{112}{}{我原来是哈勃城商人护卫队的一员。可是我被强盗打中受伤了。既然这里的人能帮我治伤，我就一直待在这里。当然，我对外界的熟悉和积累的经验让我在这里也能发挥作用。沙荫镇现在就是我的家。有时候，我也会去迦克镇或者哈勃城做些买卖，毕竟我是这儿唯一真正离开过城镇见识过世面的人。}

#{113}{}{You see Ian.}
{113}{}{你看见伊恩。}

#{114}{}{I'm sorry to hear about your injury.}
{114}{}{我很抱歉听到你受伤的消息。}

#{115}{}{Where's this Hub, and Junktown?}
{115}{}{你说的哈勃城和迦克镇在哪儿？}

#{116}{}{Can you tell me about the bandits?}
{116}{}{你能告诉我一些关于强盗的事吗？}

#{117}{}{Shady Sands is a small but self-sufficient community. The only trouble
# here is with the bandits and the Radscorpions.}
{117}{}{沙荫镇是一个很小，却能维持自给自足的城镇。这里唯一的问题就是那些歹徒和辐射蝎。}

#{118}{}{Why are the Radscorpions trouble?}
{118}{}{为什么那些辐射蝎会惹麻烦？}

#{119}{}{Are there many bandits?}
{119}{}{这附近有很多强盗吗？}

#{120}{}{There are several. They come from various groups. They steal
# our food and occasionally shoot a few people.
# Seth organized the guards to help fight them off.}
{120}{}{附近有一些，这些人来自不同的部族。他们偷我们的食物有时候甚至开枪伤人。赛思组织了一支护卫队想击退强盗。}

#{121}{}{Can you tell me about Seth?}
{121}{}{你能告诉我赛思是谁吗？}

#{122}{}{There are different groups? Who are they all?}
{122}{}{不同的部族？他们都是谁？}

#{123}{}{Radscorpions are very dangerous. They have a poisonous
# stinger in the tail, and they are very quick.
# Aradesh has been trying to find a way to get rid of them.
# If you feel brave, you could talk to Aradesh about them.}
{123}{}{辐射蝎非常危险。它们的尾部有剧毒的尖蛰，移动速度也很快。亚拉德什曾经设法想解决它们。如果你有勇气，可以去找亚拉德什谈谈这件事。}

#{124}{}{Thanks. It's been healing up well, thanks to Razlo.}
{124}{}{谢谢。伤势复原的很好，这都得感谢拉斯洛。}

#{125}{}{Seth is a very brave fighter. He occasionally goes to
# the Radscorpion caves to kill a few Radscorpions, but
# they always wind up coming back. There are just too many
# for him to fight.}
{125}{}{赛思是非常勇猛的战士。他有时会孤身一人去洞穴里解决掉一些辐射蝎，但过不了多久它们又会卷土重来。那里有太多的威胁让他应接不暇。}

#{126}{}{Are the Radscorpions really that dangerous?}
{126}{}{辐射蝎真的那么危险吗？}

#{127}{}{What can I help you with?}
{127}{}{我能帮助你做些什么？}

#{128}{}{There are three groups: the Khans, the Vipers, and the
# Jackals. They pretty much hate each other, but they
# all raid Shady Sands.}
{128}{}{歹徒有三个部族:可汗，毒蛇和豺狼。他们彼此极端仇视，但共同的袭击目标都是沙荫镇。}

#{129}{}{Tell me more about Shady Sands.}
{129}{}{告诉我更多关于沙荫镇的事。}

#{130}{}{He has the confident, relaxed stance of an experienced fighter.}
{130}{}{他非常自信，也总摆出一副那种身经百战的战士才有的轻松姿态。}

# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 131 and 132.
#{131}{}{So, }
{131}{}{那么，}

#{132}{}{, what can I do for you?}
{132}{}{，我能为你做些什么？}

#{133}{}{Tell me about the raiders.}
{133}{}{告诉我关于歹徒的事。}

#{134}{}{Tell me about Radscorpions.}
{134}{}{告诉我关于辐射蝎的事。}

#{135}{}{Tell me about Shady Sands.}
{135}{}{告诉我关于沙荫镇的事。}

#{136}{}{Tell me about Seth.}
{136}{}{告诉我关于赛思的事。}

#{137}{}{Can you give me directions to the Hub and Junktown?}
{137}{}{你能指引我怎么去哈勃城和迦克镇吗？}

#{138}{}{Nothing, thanks.}
{138}{}{没事，谢谢。}

#{139}{}{The Hub is a big trading center far south of Shady Sands. It's run by
# several different caravan groups of merchants: the Water Merchants, the
# Crimson Caravan, and the Far Go Traders. Junktown is a little south and a ways west.
# It's smaller, but still a good place to drop in for a drink. It's overseen by a
# fellow by the name of Killian Darkwater, the local shopkeeper, sheriff, and mayor.}
{139}{}{哈勃城是在沙荫镇南部的一个大型贸易中心。它被掌握在几个不同的商队组织手中：纯水商队、深红商队和远行商队。迦克镇就在西南面不远的地方。它是一座小城，不过同样值得停下来歇歇脚，顺便去酒馆喝上一杯。那里全归一个叫基利安·达克沃特的家伙说了算, 他既是当地的商店业主，也是治安官和镇长。}

#{140}{}{Thanks.}
{140}{}{谢谢。}

#{141}{}{I may not be a very good fighter any more,
# but I'm good enough to best the likes of you!}
{141}{}{我也许不再是最优秀的战士，但对付你这种下三滥的货色还是绰绰有余！}

# TRANSLATION NOTE
# The player-character's name is inserted by the code in between lines 142 and 143.
#{142}{}{What can I do for you, }
{142}{}{我能为你做些什么，}

#{143}{}{?}
{143}{}{？}

#{144}{}{Hmm. Nothing. Never mind, Ian.}
{144}{}{嗯，没事。别担心，伊恩。}

#{145}{}{You can leave now.}
{145}{}{你现在可以离开了。}

#{146}{}{Can you give me directions to the Hub and Junktown?}
{146}{}{你能指引我怎么去哈勃城和迦克镇吗？}

#{147}{}{Well, since you ask, all right. See you around.}
{147}{}{喔，既然你这么说，那么好吧。再会。}

#{148}{}{No thanks. I'm needed here.}
{148}{}{不，谢谢。这里仍然需要我。}

#{149}{}{Could you help me out a bit? Your experience would be useful.}
{149}{}{你愿意帮我吗？你那些经历对我可是无价之宝。}

#{150}{}{Let's go. It'll be good to get back into action!}
{150}{}{走吧。能重新投入战斗真是太棒了！}

#{151}{}{This is Killian's, a general store. Killian's a good man, and they
# have plenty of stock.}
{151}{}{这是基利安的杂货店。基利安是个不错的家伙，他那里也有足够的存货。}

#{152}{}{Gizmo's casino. A hive of gambling and underworld activity. Careful; they
# say the games are rigged.}
{152}{}{吉斯莫的赌场。赌博和各种地下活动的温床。小心点，他们说赌场里有人会出老千。}

#{153}{}{This place gives me the creeps.}
{153}{}{这地方让我浑身不自在。}

#{154}{}{What the hell happened here?}
{154}{}{这里他妈的发生了什么事？}

#{155}{}{This is gonna be a tough nut to crack.}
{155}{}{这会是块难啃的骨头。}

#{156}{}{Hmm. Tempting offer, since this place gets boring. Tell ya what. Standard
# rates. 100 caps, and you've got a deal.}
{156}{}{嗯，诱人的提议, 况且这地方开始变的愈加无聊。那么告诉你吧，公道价格，100瓶盖，然后我们就成交。}

#{157}{}{Deal.}
{157}{}{成交。}

#{158}{}{No thanks.}
{158}{}{不，谢谢。}

#{159}{}{How about a piece of the action, instead?}
{159}{}{不如让我修理你一顿怎么样？}

#{160}{}{All right, I'll help you out in exchange for my share of loot.}
{160}{}{那么好吧，我会帮你，不过作为交换我得分享一部分战利品。}

#{161}{}{No, I don't think so. Come back when you have some caps.}
{161}{}{不，我可不这么认为。等你有钱了再回来吧。}

#{162}{}{This is the Weapon Shop. It's run by Beth. She's good for guns, but
# better for gossip.}
{162}{}{这里是贝斯的武器店。她精通枪械，但更擅长闲谈。}

#{163}{}{Jake's weapons. High prices, but really good guns.}
{163}{}{杰克的武器库。高价，相当不错的货色。}

#{164}{}{Office of the Water Merchants. They're the big movers and shakers of the
# Hub, since they supply the water that keeps everything going.}
{164}{}{纯水商队的办事处。他们在哈勃城呼风唤雨，只手遮天，因为他们提供这里所有的水源供应。}

#{165}{}{This is the Crimson Caravan. I did some work for them. They do a lot of
# high-risk jobs.}
{165}{}{这里是深红商队。过去我曾经为他们工作，大部分都是高风险的活儿。}

#{166}{}{Far Go Traders, run by Butch Harris. He's ot-nay oo-tay ight-bray, if you
# catch my meaning.}
{166}{}{远行商队的布奇·哈里斯。他是个，呃，不可理喻的家伙，如果你明白我的意思。}

#{167}{}{Ah, now the Maltese Falcon is the place to be. Good music, good drinks,
# and good company.}
{167}{}{啊哈，这里就是马耳他猎鹰。上等的音乐，上等的美酒，还有上等的伙伴。}

#{168}{}{That is one ugly son of a bitch!}
{168}{}{你他妈狗娘养的杂种！}

#{169}{}{You gain 100 experience points for convincing Ian to join your quest.}
{169}{}{你说服伊恩加入队伍，因而得到了100点经验值。}

#{170}{}{Heard about some of these places before, but never been in one. Seems nice
# and clean . . . a little too clean for my taste.}
{170}{}{以前听说过那些地方，但从未去过任何一个。看起来很不错很干净……对我来说未免太干净了些。}

#{171}{}{Not that you asked me, but the man needs to give you a little breathing
# room.}
{171}{}{倒不是你问我，不过那家伙需要给你些喘息空间。}

#{172}{}{Y'know, that woman couldn't lead a tango, much less a revolution.}
{172}{}{你知道，那女人甚至不能领一曲探戈，更别提旋转舞步了。}

#{173}{}{What weapons are you skilled with?}
{173}{}{你擅长什么武器？}

#{174}{}{I'm a good shot with just about any sort of pistol, and I can use a
# submachine gun, too. I also know how to handle a knife.}
{174}{}{我精通任何种类的手枪，也能使用冲锋枪。当然我也知道如何挥舞匕首。}


#
# Translation note
# The following line is directed at Katja, a female scavenger, not at the player.
# Ian is noting that he thinks that the Boneyard was a worse place than the
# mutants' military base.
#

#{175}{}{I thought the Boneyard was worse.}
{175}{}{我觉得晒骨场更糟。}



#{200}{}{Draw your best weapon next time we go into battle.}
{200}{}{下次战斗时装备上你最好的武器。}

#{201}{}{Sure thing.}
{201}{}{当然。}

#{202}{}{Can I do something for you before I go?}
{202}{}{在我离开之前能为你做些什么？}

#{203}{}{Um, yeah. I think we should stick together, after all.}
{203}{}{嗯, 好的。我觉得我们还是应该结伴同行。}

#{204}{}{Uh, no. Thanks.}
{204}{}{唔，不必了。谢谢。}


#
# Ian tell-me-abouts
#
{1099}{}{?}
{1199}{}{我可以告诉你：Water-水、War-大战、Shady-沙荫镇、Junktown-迦克镇、Hub-哈勃、Raiders-歹徒、Caravans-商队、Chip-芯片、Sands-沙荫镇、Followers-末世论者、Cathedral-大教堂、Garl-伽尔、Master-主教、Unity-“同一”、Set-赛特、Watershed-水处理房、Necropolis-大墓地城、hall-亡者大厅、Library-图书馆、Overseer-所长、Medic-医生、Healing-治疗、Vault-避难所、Vault13-十三号避难所、Killian-基利安、Gizmo-吉斯莫、boneyard-晒骨场、Casino-赌场、Store-店铺、Deathclaw-死亡爪、Exodus-大迁徙、Initiates-新兵、Paladins-游侠、Scribes-研究员、Children-大教堂教徒、Brotherhood-兄弟会、Vats-病毒槽、Military-军事基地、Base-军事基地、Apocalypse-末世论、Mutants-变种人、Morpheus-墨菲斯、Khans-可汗帮、Tandi-坦蒂、Alya-艾丽娅、Diana-戴安娜、Gwen-格温、Petrox-派特拉克斯、Tolya-托利亚、Booze-酒、Drugs-毒品、Seth-赛思、Aradesh-亚拉德什、Razlo-拉斯洛、Zimmerman-齐默曼、Regulators-管理者、Scavs-拾荒者、Blades-利刃帮、Nicole-妮可尔、Lieutenant-主教副官、Psychics-心理、Experiments-试验、Police-警察、Merchants-商人。}

{1000}{}{Water}
{1001}{}{War}
{1002}{}{Shady}
{1003}{}{Junktown}
{1004}{}{Hub}
{1005}{}{Raiders}
{1006}{}{Caravans}
{1007}{}{Chip}
{1008}{}{Sands}
{1009}{}{Followers}
{1010}{}{Cathedral}
{1011}{}{Garl}
{1012}{}{Master}
{1013}{}{Unity}
{1014}{}{Set}
{1015}{}{Watershed}
{1016}{}{Necropolis}
{1017}{}{Hall}
{1018}{}{Library}
{1019}{}{Overseer}
{1020}{}{Medic}
{1021}{}{Healing}
{1022}{}{Vault}
{1023}{}{Vault-13}
{1024}{}{Vault13}
{1025}{}{Killian}
{1026}{}{Gizmo}
{1027}{}{Boneyard}
{1028}{}{Casino}
{1029}{}{Store}
{1030}{}{Deathclaw}
{1031}{}{Exodus}
{1032}{}{Initiates}
{1033}{}{Paladins}
{1034}{}{Scribes}
{1035}{}{Children}
{1036}{}{Brotherhood}
{1037}{}{Vats}
{1038}{}{Military}
{1039}{}{Base}
{1041}{}{Apocalypse}
{1042}{}{Mutants}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Booze}
{1052}{}{Drugs}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulators}
{1058}{}{Scavs}
{1059}{}{Blades}
{1060}{}{Nicole}
{1061}{}{Lieutenant}
{1062}{}{Psychics}
{1063}{}{Experiments}
{1064}{}{Police}
{1065}{}{Merchants}

#{1100}{}{No idea what a water chip is. Sorry, friend.}
{1100}{}{不清楚净水芯片是什么。对不起，朋友。}

#{1101}{}{Happened a few decades back. Basically, a bunch of countries got kind of
# antsy, and everything went BOOM!}
{1101}{}{发生数十年后，基本上，很多国家都感到不安，而且一切失去了繁荣！}

#{1102}{}{A small and peaceful village. Probably the most promising community in the
# wastes.}
{1102}{}{一个小而和平的村庄。或许那是最有希望的社区。}

#{1103}{}{A medium-sized town made of junk, overseen by a sherrif named Killian. It's
# just a few days southwest of Shady Sands.}
{1103}{}{一个由垃圾建成的中型城镇, 被一个叫做基利安的人监管。它在沙荫镇的西南方只有几天的路程。}

#{1104}{}{The Hub is the biggest trading center in the New West. It's run primarily
# by a group called the Water Merchants, but there are some other traders there, too.
# It's a booming town, but there's a lot of political fighting between the traders.}
{1104}{}{哈勃城是西方最大的贸易中心。它主要是由一伙称为水商人的团体管理，但那里也有其它一些商人，它是一个急速发展城镇，但是在商人之间有许多政治上的争斗。}

#{1105}{}{There are several different groups of raiders out there. The most organized
# group is called the Khans; they seem to think they can conquer the world or
# something.}
{1105}{}{那边有一些不同群体的歹徒。其中有个大团体叫做可汗；他们似乎认为他们能征服世界。}

#{1106}{}{Most caravans come from the Hub. They travel all over the place. I worked
# for a group called the Crimson Caravan before my untimely injury.}
{1106}{}{大多数的商队来自哈勃城。他们到处旅行。我受伤之前是为一个叫作深红的商队工作。}

#{1107}{}{No idea what a water chip is. Sorry, friend.}
{1107}{}{不清楚净水芯片是什么。对不起，朋友。}

#{1108}{}{A small and peaceful village. Probably the most promising community in the
# wastes.}
{1108}{}{一个小而和平的村庄。或许那是最有希望的社区。}

#{1109}{}{Sorry, bud. Don't know much.}
{1109}{}{对不起，小孩子不要知道的太多。}

#{1110}{}{Sorry, bud. Don't know much.}
{1110}{}{对不起，小孩子不要知道的太多。}

#{1111}{}{Garl's some dumb-ass who thinks he can take over the world with his
# crummy raiders. Yeah, whatever.}
{1111}{}{伽尔是一个笨蛋-他认为他能带着他那些歹徒征服整个世界。}

#{1112}{}{Sorry, bud. Don't know much.}
{1112}{}{对不起，小孩子不要知道的太多。}

#{1113}{}{Sorry, bud. Don't know much.}
{1113}{}{对不起，小孩子不要知道的太多。}

#{1114}{}{Sorry, bud. Don't know much.}
{1114}{}{对不起，小孩子不要知道的太多。}

#{1115}{}{Sorry, bud. Don't know much.}
{1115}{}{对不起，小孩子不要知道的太多。}

#{1116}{}{Isn't that the mythical city of the dead?}
{1116}{}{不是那个死人的城市吧？}

#{1117}{}{Sorry, bud. Don't know much.}
{1117}{}{对不起，小孩子不要知道的太多。}

#{1118}{}{Sorry, bud. Don't know much.}
{1118}{}{对不起，小孩子不要知道的太多。}

#{1119}{}{Sorry, bud. Don't know much.}
{1119}{}{对不起，小孩子不要知道的太多。}

#{1120}{}{Razlo's a great doctor. You should see him if you're hurt.}
{1120}{}{拉斯洛是一位伟大的医生。如果你受伤了，你应该去找他。}

#{1121}{}{Razlo does s good job of fixing people up, and his junja juice is well
# worth it!}
{1121}{}{拉斯洛的工作很能安定人心，而且他的咖喱汁真的很棒。}

#{1122}{}{Sorry, bud. Don't know much.}
{1122}{}{对不起，小孩子不要知道的太多。}

#{1123}{}{Sorry, bud. Don't know much.}
{1123}{}{对不起，小孩子不要知道的太多。}

#{1124}{}{Sorry, bud. Don't know much.}
{1124}{}{对不起，小孩子不要知道的太多。}

#{1125}{}{Killian's mayor of Junktown. He also runs a store there. He's a
# decent fellow. Never did any work for him, but he seems okay.}
{1125}{}{基利安是迦克镇的市长。他在那还经营着一间商店。他是一个相当好的人，他从未做过任何的工作，但是他看起来干的就是好。}

#{1126}{}{Gizmo runs a casino in Junktown. I hear that it's rigged, though.}
{1126}{}{吉斯莫管理着迦克镇的一个赌场。但是，我听说那儿作弊。}

#{1127}{}{Sorry, bud. Don't know much.}
{1127}{}{对不起，小孩子不要知道的太多。}

#{1128}{}{The casino is Gizmo's big project in Junktown. Brings in a lot of
# tourists and money, but problems come with it.}
{1128}{}{迦克镇的赌场是吉斯莫的大计划。为他带来了许多旅游者和钱，但同时也为他带来了一些麻烦。}

#{1129}{}{Killian runs a good general store in Junktown.}
{1129}{}{基利安经营着迦克镇的一间很好的商店。}

#{1130}{}{Sorry, bud. Don't know much.}
{1130}{}{对不起，小孩子不要知道的太多。}

#{1131}{}{Sorry, bud. Don't know much.}
{1131}{}{对不起，小孩子不要知道的太多。}

#{1132}{}{Sorry, bud. Don't know much.}
{1132}{}{对不起，小孩子不要知道的太多。}

#{1133}{}{Sorry, bud. Don't know much.}
{1133}{}{对不起，小孩子不要知道的太多。}

#{1134}{}{Sorry, bud. Don't know much.}
{1134}{}{对不起，小孩子不要知道的太多。}

#{1135}{}{Yeah, there's some kids in Shady Sands. So? None of 'em are mine.}
{1135}{}{是的，沙荫镇是有一些小孩。那怎么了？没有一个是我的。}

#{1136}{}{Sorry, bud. Don't know much.}
{1136}{}{对不起，小孩子不要知道的太多。}

#{1137}{}{Sorry, bud. Don't know much.}
{1137}{}{对不起，小孩子不要知道的太多。}

#{1138}{}{Sorry, bud. Don't know much.}
{1138}{}{对不起，小孩子不要知道的太多。}

#{1139}{}{Sorry, bud. Don't know much.}
{1139}{}{对不起，小孩子不要知道的太多。}

#{1141}{}{You know, we'll always have war. Just the next one's gonna be fought with
# sticks.}
{1141}{}{你知道，我们总是要打仗。下一个战斗我们就要用棍子打了。}

#{1142}{}{I saw some weird things when I was guarding caravans for the Hub.
# Mutated coyotes and mantises and scorpions and such.}
{1142}{}{当我正在为哈勃城保卫商队的时候，我见到一些怪异的事，比如变异的狼，螳螂和蝎子。}

#{1143}{}{Sorry, bud. Don't know much.}
{1143}{}{对不起，小孩子不要知道的太多。}

#{1144}{}{They're a sorry group of raiders who attack Shady Sands and think that
# they're gonna take over the world or some such crap.}
{1144}{}{他们是一群歹徒，并以为攻击沙荫镇是为了接管这个世界。}

#{1145}{}{She's Aradesh's daughter. She's pretty sweet, but I've got someone
# waiting for me back home.}
{1145}{}{她是亚拉德什的女儿。她有漂亮的脸蛋，但是我已经有心爱的人了。}

#{1146}{}{Sorry, bud. Don't know much.}
{1146}{}{对不起，小孩子不要知道的太多。}

#{1147}{}{Sorry, bud. Don't know much.}
{1147}{}{对不起，小孩子不要知道的太多。}

#{1148}{}{Sorry, bud. Don't know much.}
{1148}{}{对不起，小孩子不要知道的太多。}

#{1149}{}{Sorry, bud. Don't know much.}
{1149}{}{对不起，小孩子不要知道的太多。}

#{1150}{}{Sorry, bud. Don't know much.}
{1150}{}{对不起，小孩子不要知道的太多。}

#{1151}{}{Got any beer?}
{1151}{}{有没有啤酒？}

#{1152}{}{I used some Psycho once on a caravan raid. It made me twitchy. Odd.}
{1152}{}{在一次商队受袭中我使用了一些狂躁剂。它使我抽筋。呵呵。}

#{1153}{}{Seth is the captain of the guards. Between you and me, he couldn't
# guard a fruit if it was nailed to his leg.}
{1153}{}{赛思是警卫队的队长。如果你我联手，只要盯着他的腿打，他支持不了多久。}

#{1154}{}{Aradesh is the leader of Shady Sands. A kind and patient man, although
# he's kinda looney.}
{1154}{}{亚拉德什是沙荫镇的领袖。一个和蔼可亲的人，虽然他有点疯狂。}

#{1155}{}{Hey, if you need help, Razlo's the man to see. He's a great doctor.}
{1155}{}{嗨，如果你需要帮助，去找拉斯洛，他是个伟大的医生。}

#{1156}{}{Sorry, bud. Don't know much.}
{1156}{}{对不起，小孩子不要知道的太多。}

#{1157}{}{Sorry, bud. Don't know much.}
{1157}{}{对不起，小孩子不要知道的太多。}

#{1158}{}{Sorry, bud. Don't know much.}
{1158}{}{对不起，小孩子不要知道的太多。}

#{1159}{}{Sorry, bud. Don't know much.}
{1159}{}{对不起，小孩子不要知道的太多。}

#{1160}{}{Sorry, bud. Don't know much.}
{1160}{}{对不起，小孩子不要知道的太多。}

#{1161}{}{Sorry, bud. Don't know much.}
{1161}{}{对不起，小孩子不要知道的太多。}

#{1162}{}{I dunno. I think there's something to it, yeah, but there's
# just not enough evidence.}
{1162}{}{我不知道。我认为那里发生了某些事，但是没有发现足够的迹象。}

#{1163}{}{Sorry, bud. Don't know much.}
{1163}{}{对不起，小孩子不要知道的太多。}

#{1164}{}{Sorry, bud. Don't know much.}
{1164}{}{对不起，小孩子不要知道的太多。}

#{1165}{}{Some merchants come from the Hub to trade with Junktown. That's all
# I know.}
{1165}{}{一些商人从哈勃城来到迦克镇交易。那是我知道的全部。}
