{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Irwin.}
{100}{}{你看见艾尔文。}

#{101}{}{Oh boy, can't you leave me alone? I have enough problems on my hands already.}
{101}{}{噢孩子，你不能让我一个人呆会儿吗？我自己已经有够多的麻烦了。}

#{102}{}{Problems? Maybe I can help you.}
{102}{}{麻烦？也许我能帮助你。}

#{103}{}{Like you are the only one with problems.}
{103}{}{看起来你是唯一惹上麻烦的人。}

#{104}{}{Okay, okay. No reason to yell at me.}
{104}{}{好吧，好吧。没必要对我乱吼。}

#{105}{}{Hmm... I don't know. It takes a different caliber of hero than you. Listen, why don't you come back when you have a little more experience under your belt?}
{105}{}{呃……我不知道。它恐怕得需要比你更有实力的强者才能解决。听着，为什么不等你积累更多经验之后再回来呢？}

#{106}{}{This is a tragedy, believe me. Nothing is the way it used to be. I have a small farm outside town and a few days ago a bunch of Raiders appeared out of nowhere and now use my home as their camp. They killed Pugsley, my donkey and they threatened #to kill me if I ever dare to come back.}
{106}{}{这是场灾难，相信我。没有什么事会一帆风顺。我在城外有个小农场，几天前一伙歹徒突然在那里出现，并且占据了我的家作为他们的营地。他们已经杀了派斯依，我的驴子，并且威胁说如果敢再回去就一并干掉我。}

#{107}{}{Just tell me where and I'll take care of the rest.}
{107}{}{你只需要告诉我他们在哪儿，剩下的就交给我。}

#{108}{}{Sorry Irwin, but I have more important things to do.}
{108}{}{对不起艾尔文，但我有更重要的事情得做。}

#{109}{}{Really, you would do that? You know, I don't dare to go there any more. Why don't you come back and let me know when it is safe to go back home again?}
{109}{}{真的吗，你想要那么做？你知道，我不敢再靠近那里。为什么不等你回来，然后再告诉我什么时候可以安全的回家呢？}

#{110}{}{Listen freak, I told you to let me alone in the first place. Now beat it!}
{110}{}{仔细听, 我告诉过你让我一个人在这里呆着。那么现在滚吧！}

#{111}{}{I knew you would chicken out. Everyone does when it comes to the Raiders.}
{111}{}{我知道你会退缩。每个人听到要对付那帮强盗的时候都这个样。}

#{112}{}{So, have you been able to teach those Raiders a lesson? Is my home safe again?}
{112}{}{那么，你已经把那些强盗教训了一顿？我的家现在安全了吗？}

#{113}{}{It sure is, buddy.}
{113}{}{当然了，我的朋友。}

#{114}{}{I didn't have the time yet to take care of it.}
{114}{}{我现在还没时间处理这件事。}

#{115}{}{Oh, thank you so much. I am sorry I don't have any riches to give to you, but here, take this rifle for saving my home.}
{115}{}{喔，太感谢你了。很抱歉我没什么财产可以报答你，但是这个，但请拿走这把枪当作拯救我家的报酬。}

#{116}{}{You're trying to fool me, right? Please don't play with me. Come back and let me know when it is really safe to get back into my home, will you?}
{116}{}{你是在开玩笑，对吗？请不要愚弄我。请等我的家真正安全的时候再回来告诉我，好吗？}

#{117}{}{Thank you so much for helping me.}
{117}{}{太感谢你的帮助了。}

#{118}{}{Grunk?}
{118}{}{吼吼？}

#{119}{}{Look, I don't have time for idiots.  Come back when you've got some smarts.}
{119}{}{你看，我可没时间浪费在傻瓜身上。等你学聪明点再回来吧。}

#{120}{}{Uh Huh, Uh Huh, Uh Huh.  I dood it.}
{120}{}{噢哈, 噢哈, 噢哈. 我知道。}

#{121}{}{Me no fix yet.}
{121}{}{我不确定。}



#{300}{}{Meet your maker!}
{300}{}{见上帝去吧!}

#{301}{}{Get him... dead!}
{301}{}{干掉……他！}

#{302}{}{You have just had your last cheesebread!}
{302}{}{这将是你最后的晚餐！}

#{303}{}{I'll perforate you like some swiss cheese!}
{303}{}{我会把你打成筛子！}