{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a thin, angry-looking man.}
{100}{}{你看到一个瘦小，满面怒容的男人。}
#{101}{}{You see Ismarc.}
{101}{}{你看见伊斯马克。}
#{102}{}{What?}
{102}{}{什么？}
#{103}{}{Yeah, what do you want?}
{103}{}{喂，你想干什么？}
#{104}{}{Hey, good singing.}
{104}{}{嗨，唱的不错。}
#{105}{}{Your singing makes my ears bleed.}
{105}{}{你的歌声快要让我的耳朵出血了。}
#{106}{}{Never mind.}
{106}{}{别介意。}
#{107}{}{Hoo!}
{107}{}{呼！}
#{108}{}{Oh, great. You don't know how gratified that makes me. Go away.}
{108}{}{喔，太棒了。你不知道那多么让我满足，走开。}
#{109}{}{Thanks. What can I do for ya?}
{109}{}{谢谢。我能为你做些什么？}
#{110}{}{Do you do music anywhere else?}
{110}{}{你也在其他什么地方演出吗？}
#{111}{}{Just felt like tossing some money in the hat, so to speak.}
{111}{}{可以这么说，那种感觉就像摇动帽子里的钱币。}
#{112}{}{Where did you learn to sing?}
{112}{}{你从哪里学习的演唱技巧？}
#{113}{}{Thanks for your time.}
{113}{}{耽误了你的时间，非常感谢。}
#{114}{}{What?!? I don't have time for this.}
{114}{}{什么？！？我可没时间干这些。}
#{115}{}{Yeah, I sing at the Hub sometimes, and I've visited the Brotherhood of Steel and Adytum with the caravans. Why do you ask?}
{115}{}{没错，我有时在哈勃城表演，也跟随商队去过钢铁兄弟会和内城区。你为什么想知道这些？}
#{116}{}{Can you tell me how to get to the Hub?}
{116}{}{你能告诉我怎么去哈勃城吗？}
#{117}{}{I need to know how to get to the Brotherhood.}
{117}{}{我需要知道怎么去钢铁兄弟会。}
#{118}{}{How do I get to Adytum?}
{118}{}{我怎么才能找到内城区？}
#{119}{}{Um, never mind, thanks.}
{119}{}{嗯，没关系，谢谢。}
#{120}{}{The Hub? Oh, it's just a short distance down south of Junktown. What else?}
{120}{}{你说哈勃城？哦，它在迦克镇南方不远的地方。你还需要知道些什么吗？}
#{121}{}{The Brotherhood is a couple days west and a little bit north of here. Don't go there, though. They won't let you in unless you're with a caravan. You need anything else?}
{121}{}{钢铁兄弟会在西面偏北的方向距离这里大约数天的路程。但是，别去那里。除非与商队同行，他们是不会允许你进入的。你还需要别的帮助吗？}
#{122}{}{Hmm. Head southwest of the Hub. Adytum is part of the Boneyard. It's a small, semi-industrial town. I didn't like it much there. What else do you want?}
{122}{}{唔。在哈勃城的西南方。内城区是晒骨场的一部分。它是一个工业薄弱的小型城镇。我并不怎么喜欢那里。你还需要些什么？}
#{123}{}{Hey, thanks. It's hard being a starving artist. You got anything you need to know, you just ask.}
{123}{}{嗨，谢谢。贫困艺术家的生活总是很艰辛。你会得到你想知道的一切答案，随便你问。}
#{124}{}{I appreciate the thought and all, but you're strapped worse than I am.}
{124}{}{我感激你的这些想法，但你显然比我更加一文不名。}
#{125}{}{Ah, I picked it up here and there. Learned a little from an old singer at the Hub, and got some music from the scavs in Adytum, in the Boneyard. You know. Just takes some practice.}
{125}{}{呵，我到处寻访收集。从哈勃城的老歌手那里学习到一些歌唱技巧，从晒骨场的内城区搜寻到一些乐曲。你知道的。只需要进行一些练习。}
#{126}{}{There is a man singing raucously in the corner.}
{126}{}{角落里一个男人在用沙哑的声音唱歌。}
#{127}{}{Your head is a bowl!}
{127}{}{你的脑袋像木碗}
#{128}{}{It's round like a mole!}
{128}{}{和小鼹鼠一样圆}
#{129}{}{I'd rather fry!}
{129}{}{我情愿去下油锅}
#{130}{}{Than pay you the toll!}
{130}{}{也不给你买路钱}
#{131}{}{I know your mind}
{131}{}{我了解你的想法}
#{132}{}{It's a steel cage}
{132}{}{它是个钢铁篱樊}
#{133}{}{Raging inside is . . .}
{133}{}{在里面咆哮的是}
#{134}{}{The DeathClaw}
{134}{}{死亡爪}
#{135}{}{I need you}
{135}{}{我需要你}
#{136}{}{Like a bad dose of poison}
{136}{}{就像中毒已深}
#{137}{}{I need you}
{137}{}{我需要你}
#{138}{}{Like a rad scorpion strike}
{138}{}{就像蝎子毒针}
