#{100}{}{You see Jain}
{100}{}{你看见简恩。}

#{101}{JAIN00}{Why do you disturb an elder of the Cathedral?}
{101}{JAIN00}{你为什么要来打扰一位大教堂高级牧师？}

#{102}{}{I have come seeking a blessing.}
{102}{}{我是来乞求祝福的。}

#{103}{}{I'm interested in your church, and I want some information. Do you have any pamphlets?}
{103}{}{我对你们大教堂很感兴趣，我想打听些消息。你们有宣传手册吗？}

#{104}{}{Just looking around.}
{104}{}{我是来观光的。}

#{105}{}{Mom?}
{105}{}{妈咪？}

#{106}{JAIN01}{I am hardly your mother.}
{106}{JAIN01}{我不是你妈妈。}

#{107}{}{Nuh-uh?}
{107}{}{不，唔？}

#{108}{}{Poopie!}
{108}{}{爸爸！}

#{109}{JAIN02}{How dare you speak to me in that manner! You will be punished for your insolence! Guards!}
{109}{JAIN02}{你怎么能这样和我说话！你会因为你的无礼受到惩罚的，卫兵！}

#{110}{JAIN03}{Perhaps one of our priests will discuss your needed education. Leave now.}
{110}{JAIN03}{也许我们的低级牧师可以教教你基本的待人接物，你走吧。}

#{111}{JAIN04}{Have you studied the sacraments, child?}
{111}{JAIN04}{你研习过圣经没有，孩子？}

#{112}{}{Yes.}
{112}{}{是的。}

#{113}{}{No.}
{113}{}{没有。}

#{114}{JAIN05}{Then you would have known high elders of the Cathedral do not just 'hand out' blessings. You will leave now.}
{114}{JAIN05}{那你就应该明白高级牧师不只是干“施与”祝福的工作，你可以走了。}

#{115}{JAIN07}{Continue to mock me and I will have you thrown out.}
{115}{JAIN07}{再和我胡闹，我就把你扔出去！}

#{116}{}{But I'm not mocking you, honest.}
{116}{}{可是我没有和您胡闹啊，真的。}

#{117}{}{Mock you? Now why would I do something like that?!}
{117}{}{胡闹？那我就换个花样怎么样！？}

#{118}{}{It's obvious that kindness and good temper aren't part of this religion.}
{118}{}{善良和忍耐显然不是你们宗教的教义。}

#{119}{}{Sorry, I think I'll be leaving now.}
{119}{}{对不起，那我走了。}

#{120}{JAIN08}{You will pay for those heretical words.}
{120}{JAIN08}{你要为你的异端邪说而付出代价！}

#{121}{JAIN09}{Your words do not match your conviction. They burn of the heresy within. You will be cleansed, then forgotten.}
{121}{JAIN09}{从你的言辞中看不到一点悔改的意思，只有异端邪说，你会被净化的，然后永远地被人遗忘。}

#{122}{JAIN10}{Then why are you here? What would bring you to the Children of the Cathedral?}
{122}{JAIN10}{那你在这里做什么呢？你来我们大教堂有何贵干？}

#{123}{}{I am a seeker of knowledge. I would like to learn more.}
{123}{}{我是知识的追寻者，我想学习。}

#{124}{}{I need to know how to burn this place down, so I was looking for structural weaknesses.}
{124}{}{我想知道怎么样才能把这个地方烧了，所以来看看建筑结构的弱点。}

#{125}{}{I'm just looking.}
{125}{}{来随便看看。}

#{126}{JAIN11}{Are you a Child?}
{126}{JAIN11}{你是教徒么？}

#{127}{}{Lady, do I look that young to you?}
{127}{}{老姐，你看我是那么年轻的人么？}

#{128}{}{Am I one of the Children of the Cathedral? No.}
{128}{}{我是不是大教堂教徒？不是。}

#{129}{}{I am a devout believer.}
{129}{}{我是一个虔诚的信徒。}

#{130}{JAIN12}{Then you should know better then to be here. I would caution you about your manners. Leave.}
{130}{JAIN12}{那你就应该去参研经文，而不是在这里，要注意你的礼节，走吧。}

#{131}{}{OK.}
{131}{}{好。}

#{132}{}{Bite me.}
{132}{}{扯你娘的蛋。}

#{133}{JAIN13}{Are you interested in converting to our faith? We can offer you what no one else can...}
{133}{JAIN13}{你有兴趣皈依我们么？我可以给你其他人都不能给你的好处……}

#{134}{}{And what's that?}
{134}{}{是什么？}

#{135}{}{No, not interested. I think you're a bunch of kooks.}
{135}{}{不干，没兴趣，你们就是一帮疯子。}

#{136}{JAIN14}{A lifetime of contentment. Fulfillment in the knowledge you're working to rebuild the planet and make a better place for those that follow.}
{136}{JAIN14}{满足的生活。充实的知识，让你用来重建这颗星球还有皈依我们之后更高贵的地位。}

#{137}{}{Sounds very interesting, could you tell me more? I seek fulfillment.}
{137}{}{听起来不错，你能说的仔细一点么？我想“实现”这些梦想。}

#{138}{}{Oh yeah, I bet there's a lot of rebuilding going on and I'm sure your cups are overflowing with fulfillment.}
{138}{}{好哇，我敢打赌到处都是造人计划，你的奶罩里会充实各种“实现”的。}

#{139}{}{I don't think so. Sounds a little fishy to me.}
{139}{}{不干，这里面有蹊跷。}

#{140}{JAIN15}{Believe what you will. Just do it elsewhere. You may leave.}
{140}{JAIN15}{随你怎么想，但别在这里胡言乱语，你可以走了。}

#{141}{JAIN17}{Mocking our holy cause is not appreciated. You will be punished if you continue.}
{141}{JAIN17}{讽刺我们崇高的事业是可耻的。你再这样就会被严惩！}

#{142}{}{And who's going to do the punishing? Ooh, I'd like to request the extra hard whip, if you don't mind.}
{142}{}{谁来主罚啊？我提议加一条带劲的好鞭子，如果你喜欢的话。}

#{143}{}{Sorry.}
{143}{}{对不起。}

#{144}{JAIN18}{When the Children walk the reborn land, your kind will vanish, heretic. Leave now.}
{144}{JAIN18}{当我们大教堂教徒在重生之地兴盛时，便是你们这些垃圾消亡的时候，走开！}

#{145}{JAIN19}{I am not completely devoid of humor, but leading the Children is something I take seriously. Please remember that.}
{145}{JAIN19}{我不是没有幽默感的人，但领导教众是一个很严肃的事情，你要记住。}

#{146}{}{Sorry, I'm not that familiar with the Children.}
{146}{}{对不起，我对教徒不是很熟悉。}

#{147}{}{OK. Bye.}
{147}{}{好吧，再见。}

#{148}{JAIN20}{You are in the right place for spiritual fulfillment. The Children of the Cathedral seek a peaceful resolution of our world's problems and could use your help.}
{148}{JAIN20}{这里就是精神“实现”的地方。教徒寻求世界问题的和平解决，你也许可以帮上点忙。}

#{149}{}{What are the Children's plans for mutants?}
{149}{}{教徒打算如何对待变种种族？}

#{150}{}{How can Children find peace in this wasteland?}
{150}{}{教徒怎么样在荒原实现和平？}

#{151}{JAIN21}{Those that can be brought into the fold, shall be. Those that resist will suffer.}
{151}{JAIN21}{那些愿意合作的可以在圈栏里苟活，那些抵抗的会很惨。}

#{152}{}{Sounds like a tough job.}
{152}{}{听起来不是很简单。}

#{153}{}{Now it's time for you to have a little suffering.}
{153}{}{现在也该你惨一下了！}

#{154}{}{As it should be. May you succeed in your crusade!}
{154}{}{是该这样的，希望你们的十字军行动成功！}

#{155}{}{Uh, I got to go.}
{155}{}{呃，我走了。}

#{156}{JAIN22}{With perseverance, the Children can accomplish anything. We will not fail.}
{156}{JAIN22}{只要有坚定不移的信念，我们教众就无往不利，我们不会失败的。}

#{157}{}{Good. I hope you don't.}
{157}{}{好，我也希望你们不会失败。}

#{158}{}{Yeah, right. Whatever.}
{158}{}{对啊对啊，随你说啦。}

#{159}{}{Okay. Bye.}
{159}{}{好，再见。}

#{160}{JAIN26}{Blasphemer! This is a Holy House! How could you think such a thing?}
{160}{JAIN26}{亵渎者！这里是圣地！你怎么能想这些？}

#{161}{}{Relax, I didn't mean it!}
{161}{}{别紧张啊，我不是故意的啊。}

#{162}{}{Easy. Let me show you.}
{162}{}{别急，我会给你看的。}

#{163}{JAIN27}{Blessings of the Holy Flame to you, my Child.}
{163}{JAIN27}{愿圣火保佑你，我的孩子。}

#{164}{}{Who's the Holy Flame?}
{164}{}{谁是圣火？}

#{165}{}{This place is a sham.}
{165}{}{这个地方该生点火，暖和。}

#{166}{}{And to you, Priestess Jain. Goodbye.}
{166}{}{也祝福你，简恩牧师，再见了。}

#{167}{}{Ug luk to ruk?}
{167}{}{什么猪？}

#{168}{}{Ooook!}
{168}{}{噢噢！}

#{169}{JAIN28}{Once you had potential. You are no longer welcome here.}
{169}{JAIN28}{你要是真有这个能力就算你强。这里不欢迎你。}

#{170}{JAIN29}{You are not welcome here. Please leave.}
{170}{JAIN29}{这里不欢迎你，走吧。}

#{171}{JAIN30}{What brings you here?}
{171}{JAIN30}{你来这里做什么？}

#{172}{}{I have slain the Master, and I believe he was masquerading as the Holy Flame.}
{172}{}{我杀了主教。他就是那个想伪装成伟大圣火的家伙。}

#{173}{}{You have been freed from the oppression of the Master.}
{173}{}{残酷压迫你们的主教已经归天了，你们自由了。}

#{174}{}{Mu tuk doh tub?}
{174}{}{咂了啦？}

#{175}{}{Feeties.}
{175}{}{善布……}

#{176}{JAIN31}{You have done what? You shall pay for your sin against the Holy Flame himself.}
{176}{JAIN31}{你干了什么？你对圣火犯下了不可饶恕的罪行！你会遭到惩罚的。}

#{177}{JAIN32}{The who?}
{177}{JAIN32}{谁？}

#{178}{}{The master. He was going to unite the mutants and take over the world.}
{178}{}{主教。他就是那个联合变种人想统治世界的家伙。}

#{179}{}{Don't worry about it.}
{179}{}{你不用操这个心了。}

#{180}{JAIN33}{You appear delusional. I suggest seeing a counselor to work out your problems.}
{180}{JAIN33}{你神经错乱了，我建议你去医生那里看看。}

#{181}{JAIN204}{I told you to leave. Are you deaf or feeble?}
{181}{JAIN204}{我叫你走，你是聋子还是弱智？}

#{182}{JAIN200}{Leave this room immediately or I will have you cleansed by holy flame.}
{182}{JAIN200}{离开这里，否则我用圣火把你清除。}

#{183}{JAIN202}{There is no one greater then the Holy Flame and we are His servants.}
{183}{JAIN202}{圣火是最高的领导，我们都是他的仆人。}

#{184}{}{Really? Wow. So, what's the reason for someone to join your order?}
{184}{}{是吗？哦。那么你还要其他仆人做什么？}

#{185}{}{Uh, okay. Bye.}
{185}{}{哦，好吧，再见。}

#{186}{JAIN27}{Blessings of the Holy Flame to you, my Child.}
{186}{JAIN27}{愿圣火保佑你，我的孩子。}

#{187}{JAIN22}{With perseverance, the Children can accomplish anything. We will not fail.}
{187}{JAIN22}{只要有坚定不移的信念，我们教徒就无往不利，我们不会失败的。}

#{188}{JAIN201}{That is not an appropriate question.}
{188}{JAIN201}{这不是一个合适的问题。}


#Tell Me Abouts

{1099}{}{?}
{1199}{}{我可以告诉你：War-大战、Master-主教、Cathedral-大教堂、Mutants-变种人、Hub-哈勃、Steel-钢铁、vats-病毒槽、Holy-圣火、Unity-“同一”、Brotherhood-兄弟会、Flame-圣火、Children-大教堂教徒。}


{1000}{}{War}
{1001}{}{Master}
{1002}{}{Cathedral}
{1003}{}{Mutants}
{1004}{}{Hub}
{1005}{}{Steel}
{1006}{}{Vats}
{1007}{}{Holy}
{1008}{}{Unity}
{1009}{}{Brotherhood}
{1010}{}{Flame}
{1011}{}{Children}


#{1100}{JAIN300}{It was the cleansing of the planet.  The inattention by those who came before caused the holy fires.  It was justice.}
{1100}{JAIN300}{那是对地球的清洁。是先人的疏忽造成了圣火，它是公正的化身。}

#{1101}{JAIN301}{There is no Master but the Holy Flame.  He is our master, He is the Master of all.}
{1101}{JAIN301}{没有主教，只有圣火，圣火就是主教，他是万物的主教。}

#{1102}{JAIN302}{The will of the Holy One brings a rebirth to the planet.  We are His Children and carry out His plan.}
{1102}{JAIN302}{圣者的意志为我们的星球带来了重生。我们都是他的子民，受他差遣。}

#{1103}{JAIN303}{They are holy for they bear marks of past sins for present witnesses.}
{1103}{JAIN303}{他们背负了过去的罪衍，亲历现实，所以他们是神圣的。}

#{1104}{JAIN304}{Like many other cities, they will embrace the moral leadership of the Cathedral.}
{1104}{JAIN304}{和其他城市一样，哈勃城会拥护大教堂的领导的。}

#{1105}{JAIN305}{They claim a religious foundation, but lack that which would make them truly righteous.  Their zeal is refreshing, however.}
{1105}{JAIN305}{他们宣传自己有宗教信仰，但却没有足以走上正途的力量。但他们的狂热是值得钦佩的。}

#{1106}{JAIN306}{I have never heard of such things.}
{1106}{JAIN306}{我从未听说这个。}

#{1107}{JAIN308}{The Holiest of Holies.  He is the guiding light we follow.  He shall cleanse those unfaithful when the Nexus of Rebirth is reached.}
{1107}{JAIN308}{神圣之神圣。他是我们的指路明灯，当重生事业开展时，他会消灭所有的不忠诚的物种。}

#{1108}{JAIN309}{It is the uniting, by the Holy Flame, of all people, of all races and the cleansing of the heathens from this world.}
{1108}{JAIN309}{就是在圣火的指引下各种族人民的统一以及异教徒从世界上被清除的这个过程。}

#{1109}{JAIN305}{They claim a religious foundation, but lack that which would make them truly righteous.  Their zeal is refreshing, however.}
{1109}{JAIN305}{他们宣传自己有宗教信仰，但却没有足以走上正途的力量。但他们的狂热是值得钦佩的。}

#{1110}{JAIN308}{The Holiest of Holies.  He is the guiding light we follow.  He shall cleanse those unfaithful when the Nexus of Rebirth is reached.}
{1110}{JAIN308}{神圣之神圣。他是我们的指路明灯，当重生事业开展时，他会消灭所有的不忠诚的物种。}

#{1111}{JAIN302}{The will of the Holy One brings a rebirth to the planet.  We are His Children and carry out His plan.}
{1111}{JAIN302}{圣者的意志为我们的星球带来了重生。我们都是他的子民，受他驱使。}
