{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Jake of the Followers.}
{100}{}{你看见末世论者信徒杰克。}

#{101}{}{You see a Follower of the Apocalypse.}
{101}{}{你看见末世论者的一名信徒。}

#{102}{}{Welcome, my friend! How might I help you today?}
{102}{}{欢迎，我的朋友！你想要什么？}

#{103}{}{Me hep! Me hep!}
{103}{}{我帮！我帮！}

#{104}{}{I heard that you are a decent fighter. Let's find out.}
{104}{}{我听说你是个很好的战士，我来会会你。}

#{105}{}{I hear you need help. What's the problem?}
{105}{}{听说你们需要帮忙。有什么麻烦事？}

#{106}{}{What can you tell me about the Followers?}
{106}{}{你能说说末世论者信徒的事情吗？}

#{107}{}{You want to help. I don't think you are good enough to
# help me out. Go talk to Neil.}
{107}{}{你来帮忙？我觉得你还不够像样啊。和尼尔聊聊去吧。}

#{108}{}{I would love to fight you, but I am much too busy helping
# Nicole right now.}
{108}{}{我也想和你来一架，但是我还要帮妮可尔做很多事情。}

#{109}{}{Figures. You looked like a wimp to me anyways.}
{109}{}{没错，你看起来就是一个垃圾啊。}

#{110}{}{Suit yourself. Good bye.}
{110}{}{随你了，再见。}

#{111}{}{How did a wimp like you become second in command?}
{111}{}{你这样一个垃圾怎么能当了二把手呢？}

#{112}{}{Hey. Just because I don't want to fight doesn't mean I'm a
# wimp. I just don't feel like it.}
{112}{}{嘿，我不想和你打不代表我就怕了你，我现在没心情。}

#{113}{}{I was right. Just a wimp.}
{113}{}{我说的没错，你就是垃圾。}

#{114}{}{Some of us will use our brains to get further in this world.
# A lot can be settled with peace and thinking.}
{114}{}{有时候动动脑子能走得更远。和平和思考能解决很多事情。}

#{115}{}{When are you going to use your brains then?}
{115}{}{那你要什么时候来动你的脑子呢？}

#{116}{}{You're right. I'm sorry.}
{116}{}{你说的对，对不起。}

#{117}{}{That's it. I'm not going to talk to you anymore.}
{117}{}{算了，我不想和你说话了。}

#{118}{}{That's better. Now. I have a problem with a spy around here.
# Will you help me?}
{118}{}{这样就好。我现在要查一个间谍，你能帮我吗？}

#{119}{}{Yes. What is it?}
{119}{}{好，怎么回事？}

#{120}{}{Fix it yourself if you are so great.}
{120}{}{如果你那么棒，你自己去办就是了。}

#{121}{}{I just said we have a spy around here. I think it may be one
# of the guards that is the spy. Though it could be a scout.
# Those are the only two groups that have access to the
# Children.}
{121}{}{我说了，附近有一个间谍。可能是卫士，也可能是哨兵。和大教堂联络的就这两种人。}

#{122}{}{Okay. I'll go get your spy and eliminate the problem.}
{122}{}{好吧，我去找出那个间谍干掉。}

#{123}{}{Have any leads on this spy?}
{123}{}{有什么线索吗？}

#{124}{}{Forget it. I won't help you.}
{124}{}{算了，我不干了。}

#{125}{}{Thank you very much. Now go!}
{125}{}{那就多谢你了。走开！}

#{126}{}{Nothing really. The only things I really know about is
# that a lot of low level information is getting to the
# Children. This is not good. Heather thinks it is either
# Neil or Peter.}
{126}{}{没什么线索。我只知道很多低层次的机密已经泄露给了教堂，这不是什么好事，希瑟认为不是尼尔就是彼得。}

#{127}{}{Okay. I will go check on it.}
{127}{}{好，我去查。}

#{128}{}{Forget it. I won't help you.}
{128}{}{算了，我帮不上你了。}

#{129}{}{I can't let you leave then.}
{129}{}{那我也不能让你走。}

#{130}{}{I will then. Good bye!}
{130}{}{那我就去办，再见。}

#{131}{}{We are having trouble with some of our information
# slipping out to the Children. I think it is a spy.}
{131}{}{我们的机密被泄露给了教堂，有间谍。}

#{132}{}{Okay. So, what is the problem?}
{132}{}{好，有什么问题？}

#{133}{}{Okay, I'll deal with this spy.}
{133}{}{好，我去查间谍。}

#{134}{}{Have any leads yet?}
{134}{}{有线索了没？}

#{135}{}{Forget it. I won't help you.}
{135}{}{算了，我帮不了你。}

#{136}{}{Currently, I can't tell you anything. Good day.}
{136}{}{目前，我还没什么发现。再见。}

#{137}{}{I am trying to sleep. Don't bother me.}
{137}{}{我要睡觉，别吵我。}

#{138}{}{Hurry up and find that vile scum!}
{138}{}{快点，找到那个混蛋。}

#{139}{}{I knew it was Heather all along. She was deceitful from
# the start. I should have told everyone what I thought at first.}
{139}{}{我就知道是希瑟干的，她一开始就鬼头鬼脑的。我应该一开始就告诉其他人的。}

#{140}{}{I never did learn anything from you. Your training
# was useless.}
{140}{}{我从你这里什么也没学到，你的训练毫无用处。}

#{141}{}{I have a package for you from Gabriel.}
{141}{}{我从加布里尔那里给你带来一个包裹。}

#{142}{}{Hmm. I see. Thank you.}
{142}{}{哦，知道了，多谢。}

#{143}{}{Get the hell out.}
{143}{}{走开。}

#{144}{}{It's the hard way. It's always the hard way.}
{144}{}{很难，一直都很难。}
