{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{The man tosses about fitfully.}
{100}{}{这个人痛的翻来覆去。}

#{101}{}{Oohhh . . .}
{101}{}{噢哦哦哦……}

#{102}{}{You see a pale, wiry young man.}
{102}{}{你看见一个苍白，瘦弱的年轻男人}

#{103}{}{You see Jarvis, the younger brother of Seth.}
{103}{}{你看见贾维斯，赛思最小的弟弟。}

#{104}{}{Hello. I'm sorry, but I'm not feeling too well right now.
# Please, if you can help find a way to fight the radscorpions,
# talk to my brother, Seth.}
{104}{}{你好。对不起，我现在的感觉很不好。求求你，你要是有办法消灭辐射蝎，就找我的哥哥赛思。}

#{105}{}{Thank you so much for helping me. My name is Jarvis, and I'm
# Seth's younger brother. Please, if there's anything you need to
# know, just ask.}
{105}{}{非常感谢你帮助我。我的名字叫贾维斯，赛思最小的弟弟。如果你想知道任何有关这里的事情就尽管说。}

#{106}{}{Hello again. Can I help you with something?}
{106}{}{真高兴再次见到你。我能帮你什么忙？}

#{107}{}{Can you tell me more about your brother?}
{107}{}{你能告诉我更多关于你哥哥的事情吗？}

#{108}{}{Tell me a bit about the town.}
{108}{}{告诉我关于这个村子的事情。}

#{109}{}{Just chatting, thanks.}
{109}{}{就是聊聊，谢谢。}

#{110}{}{Seth's a very good fighter. He's very determined. A little too much,
# sometimes. Still, he's devoted to the welfare of our village.}
{110}{}{赛思是一个优秀的战士。他很有韧性，但有时候有点固执，他一直都在为村民的安全着想。}

#{111}{}{Well, Shady Sands was founded by a great ancestor of our current
# leader, Aradesh. He could tell you more of the story. We have a
# well and irrigation, so we do well for ourselves.}
{111}{}{好的，沙荫镇是我们伟大的领导者建立的，他叫亚拉德什。他可以告诉你更多关于这里的故事。我们用井水灌溉，井水也养活了我们自己。}

#{112}{}{This man is suffering from a virulent poison.}
{112}{}{这个男人正在忍受中毒的痛苦。}

#{113}{}{You can't figure out what is affecting this man.}
{113}{}{你不能判断是什么原因让这个男人痛苦。}

#{114}{}{This man is suffering from radscorpion venom.}
{114}{}{这个男人中了辐射蝎的毒。}

#{115}{}{You can't figure out what is affecting this man.}
{115}{}{你不能判断是什么原因让这个男人痛苦。}

#{116}{}{That skill won't help here.}
{116}{}{那个技能什么作用也没有。}

#{117}{}{Over the next few minutes, the man shows definite
# improvement.}
{117}{}{过了几分钟，那个男人显得好点了。}

#{118}{}{Sef is brover?}
{118}{}{赛思是你哥哥？}

#{119}{}{Dis pwace?}
{119}{}{介绍下这个地方？}

#{120}{}{Duh.}
{120}{}{嘟。}

#{200}{}{You gain 400 experience points for curing Jarvis of his poisoning.}
{200}{}{你帮贾维斯解了毒，因此你获得了400点的经验。}
