{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a young man with sharp features.}
{100}{}{你看见一个尖嘴猴腮的年轻人。}

#{101}{}{You see Jason Zimmerman.}
{101}{}{你看见贾森·齐默曼。}

#{102}{}{Hey, are you from really far away? Have you had a lot
# of adventures?}
{102}{}{嘿，你是从远方来的？你一定经历了很多冒险吧。}

#{103}{}{Yes, I'm from a Vault far to the north.}
{103}{}{是的，我是从北方的避难所来的。}

#{104}{}{Actually, I'm from Mars. Want to see my firelance?}
{104}{}{实际上，我是从火星来的。想看看我的火焰长枪吗？}

#{105}{}{I've had some adventures.}
{105}{}{我是经历了不少事情。}

#{106}{}{Haven't done all that much, really.}
{106}{}{其实没经历过什么。}

#{107}{}{Uh, far. Vault.}
{107}{}{呃，远远的，避难所。}

#{108}{}{Oh. I thought someone who'd been through the wastes
# outside would be, well, smarter. Never mind.}
{108}{}{哦，我还以为你是穿过外面的荒原来的呢，聪明人，没关系。}

#{109}{}{Miles says that now that you got those parts,
# he can get the farms working, so that we don't have to
# sell bullets to the Hub. I never thought much about it
# until Smitty pointed out that the bullets he made were }
{109}{}{麦尔斯说你替他找到了零件，他可以让农场运作起来了，我们不必再卖子弹给哈勃城了。我以前从来没有考虑过这件事情，后来是施密蒂说他造的子弹被}

#{110}{}{sold to the Hub, who sold them to the gangs. I guess you
# found a good solution.}
{110}{}{卖给了哈勃商人，再转卖给黑帮。我想，你找到了一个可以避开这个矛盾的办法。}

#{111}{}{I never thought that we would be able to stop fighting
# the gangs. My father told me how you got them to promise
# to leave us alone. You know, I thought I always wanted
# to go adventuring, but I think that I like . . . well, the }
{111}{}{我从没想能组织黑帮间的战斗。我的父亲对我说必须要让他们离我们远远的。我一直想去冒险，但是我想……呃}

#{112}{}{feeling of security here now. No more worrying about the
# gangs suddenly attacking and wondering who's going to be killed.}
{112}{}{我喜欢这里的安全感。这里不用担心黑帮会突然袭击，也不用惴惴不安地想谁会死掉。}

#{113}{}{Lorraine says that there was a Vault south of here,
# where a lot of my grandparents lived. What's it like
# living in a Vault?}
{113}{}{洛林说南边有一个避难所，很多爷爷辈的祖先住在那里，避难所是什么样子的呢？}

#{114}{}{It's pretty boring, actually.}
{114}{}{实际上很无聊的。}

#{115}{}{It's very exciting. We have all sorts of technology
# you wouldn't believe!}
{115}{}{很好玩，有很多你想都想不到的高科技。}

#{116}{}{Oh. Well, you must have had some adventures after leaving, right?}
{116}{}{你离开这里后会再去冒险是吧？}

#{117}{}{Not really.}
{117}{}{不会。}

#{118}{}{Yes, there's quite a bit of danger out there.}
{118}{}{没错，但是外面很危险。}

#{119}{}{As someone once wrote, 'Adventure is someone else far
# away having a very unpleasant time.'}
{119}{}{有个名人说过：“冒险就是某些人在很远的地方遭罪。”}

#{120}{}{Huh. The Hub merchants talk about radscorpions and stuff.}
{120}{}{呵，哈勃城的商人说起过辐射蝎之类的东西。}

#{121}{}{Actually, it's mostly just desert.}
{121}{}{实际上，看到的主要都是荒漠。}

#{122}{}{Well, actually, there are all sorts of monsters out there.}
{122}{}{实际上，外面全是各种怪兽。}

#{123}{}{Really? What kinds of monsters have you fought?}
{123}{}{是吗？你和哪些怪物干过架？}

#{124}{}{Not much, just some rats and stuff.}
{124}{}{不多，就是些老鼠之类的。}

#{125}{}{Yeah, the Hub guards said that there are lots of radioactive
# mutant things living in the desert. Monster hunting must be
# a real blast!}
{125}{}{是啊，哈勃城来的保镖说荒漠里有很多辐射变异的怪物，杀怪物肯定是一个很刺激的事情！}

#{126}{}{Yes, it's a real kick!}
{126}{}{对，很爽的。}

#{127}{}{No; it's more of a pain. Venom, bites, radiation . . . it's deadly.}
{127}{}{不是的，更多的是伤痛。毒，咬伤，辐射……会要命的。}

#{128}{}{I wish that I could go adventuring sometime.}
{128}{}{我想以后去冒险。}

#{129}{}{I never though about that. I rather like having
# clean water and a place to stay.}
{129}{}{我从来没想到过。我就想有干净水源的地方，安安稳稳地过活。}

#{130}{}{I thought that living in the wasteland would be . . .
# you know . . . rugged, and dangerous, and everything.
# But I suppose we have enough to keep us busy here, with
# the gangs and all.}
{130}{}{我原以为生活在废土上是很艰难和危险的事情。但是我在这里实在是太忙了，帮派的事情烦得很。}

#{131}{}{What, are you some kind of weirdo or something? Caleb never
# should have let you in the gates!}
{131}{}{什么，你是变态吗？卡勒布是怎么让你进城门的？！}

#{132}{}{That's cool. All we have here is this stupid well
# and those underground farms that Miles keeps trying
# to get working.}
{132}{}{那太酷了，我们这里只有一些愚蠢的深井，或者麦尔斯一直在料理的地下农场。}

#{133}{}{Yeah, I noticed that you don't have a bedroll or anything.
# It must get pretty dirty and uncomfortable out there.}
{133}{}{我注意到你没有带被褥之类的物件，外面生活肯定是很脏，很不舒服的。}

#{134}{}{Hello again. Have any interesting stories to tell?}
{134}{}{又见面了，有什么好玩的事情要告诉我？}

#{135}{}{What do you want to know about?}
{135}{}{你想知道些什么？}

#{136}{}{Not really.}
{136}{}{没事。}

#{137}{}{Well, if you do anything interesting, tell me all about it!}
{137}{}{如果你遇到好玩的事情，一定要告诉我！}

#{138}{}{Leave me alone!}
{138}{}{别烦我！}

#{139}{}{Thank goodness you're here! Please help me get out of here!}
{139}{}{你终于来了！你一定要帮我出去！}

#{140}{}{Ayuh.}
{140}{}{啊。}

#{141}{}{Don't worry, I'll get us out of here.}
{141}{}{别担心，我们会出去的。}

#{142}{}{Sorry kid, you're on your own!}
{142}{}{抱歉了，你好自为之吧。}

#{143}{}{What are you doing here?}
{143}{}{你在这里做什么？}

#{144}{}{Thank you!}
{144}{}{多谢！}

#{145}{}{Please don't leave me!}
{145}{}{别离开我！}

#{146}{}{I thought that it would be fun to leave Adytum and
# explore the world. But the Rippers caught me and
# have been holding me here. Please, help me!}
{146}{}{我想离开内城区出去冒险是一件很好玩的事情。但是电锯党抓住了我，把我关在这里，拜托，帮帮我！}

#{147}{}{All right, let's get out of here!}
{147}{}{好吧，我们一起出去！}

#{148}{}{No way. You got yourself into this, you get out.}
{148}{}{没门，你自己惹的祸，自己搞定。}

#{149}{}{I hope we get out of here soon!}
{149}{}{我希望快点离开这里！}
