{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{We offer healing of the body to heal the spirit. Can I help you?}
{100}{}{我们可以帮助治疗受伤的身体还有精神的创伤，你需要帮助？}

#{101}{}{Yes. Help me.}
{101}{}{是的，请帮我。}

#{102}{}{Who are you people?}
{102}{}{你们是谁？}

#{103}{}{What happened to the people who were here before you?}
{103}{}{以前住在这里的人出什么事了？}

#{104}{}{Uhn}
{104}{}{唔。}

#{105}{}{That is fine, my child. We will examine you now.}
{105}{}{很好，孩子，我现在就给你做检查。}

#{106}{}{Blessed are the meek of mind. There is nothing wrong with you
# my child. Run along and play.}
{106}{}{恭顺的人会有好报。你没有受任何伤，我的孩子。去玩吧。}

#{107}{}{You have been healed. Be more careful in the future.}
{107}{}{你的伤治好了。以后要小心。}

#{108}{}{You are wounded.}
{108}{}{你受伤了。}

#{109}{}{I see you are poisoned.}
{109}{}{看得出，你中毒了。}

#{110}{}{Hmm, some radiation poisoning. Unfortunately, we cannot cure that.}
{110}{}{嗯，你被辐射了。抱歉，我们治不了这个。}

#{111}{}{We require a donation of $}
{111}{}{我们需要你捐}

#{112}{}{ before we can heal you.
# Is this acceptable?}
{112}{}{元才能给你治伤。可以吗？}

#{113}{}{Yes.}
{113}{}{好。}

#{114}{}{No.}
{114}{}{不。}

#{115}{}{But I don't have that kind of money!}
{115}{}{可是我没那么多钱啊。}

#{116}{}{Will you take, $}
{116}{}{要不你出}

#{117}{}{?}
{117}{}{？}

#{118}{}{The Children do not haggle. Now, will you accept our price?}
{118}{}{我们不讨价还价。你到底接不接受这个价格？}

#{119}{}{Yes. Of course I will}
{119}{}{好，当然。}

#{120}{}{You can bite me!}
{120}{}{狗屎！}

#{121}{}{Thank you, my son. Let us pray for your healing}
{121}{}{谢谢，我的孩子，那我们开始治疗吧。}

#{122}{}{Thank you, my daughter. Let us pray for your healing.}
{122}{}{谢谢，我的孩子，那我们开始治疗吧。}

#{123}{}{There you go. Peace and blessings of the Children with you.}
{123}{}{好了。愿大教堂教徒的和平和祝福永远伴随你。}

#{124}{}{You do not have enough money. If you donate all you can, we
# will heal you. Is this acceptable?}
{124}{}{你的钱不够，那你捐出所有的钱，我们还是愿意给你治疗的，可以吗？}

#{125}{}{Yes.}
{125}{}{好。}

#{126}{}{No.}
{126}{}{不。}

#{127}{}{If you donate all you can, we will heal you. Is this acceptable?}
{127}{}{捐出你所有的钱，我们就给你治疗的，可以吗？}

#{128}{}{Yes.}
{128}{}{好。}

#{129}{}{No.}
{129}{}{不。}

#{130}{}{You have more than enough to make the donation. You need schooling
# in math, my child.}
{130}{}{你的钱是有能力捐助的，你应该好好学学数学，我的孩子。}

#{131}{}{We are the Children of the Cathedral. We live and work amongst those
# unfortunates living in the wasteland. If you ever get to the Boneyard,
# stop by the cathedral.}
{131}{}{我们是大教堂教徒。我们和废土上受难的人们一起生活和奋斗。如果你到了晒骨场，可以去教堂参观一下。}

#{132}{}{Thank you.}
{132}{}{谢谢。}

#{133}{}{What do you do?}
{133}{}{你是干什么的？}

#{134}{}{We are the healers and teachers of peace. We heal the body to heal
# the spirit. All we ask is a small donation to pay for our healing supplies.}
{134}{}{我们是医疗师，也是和平的布道者。我们治疗身体的伤痛，也治疗人们的灵魂。我们只要求一点点相当于医疗成本的捐献。}

#{135}{}{Sounds like a good idea to me.}
{135}{}{听起来很不错。}

#{136}{}{Sounds like a load of crap to me.}
{136}{}{我看这都是胡说八道。}

#{137}{}{We did not ask you. I can tell you are tired of listening to
# our beliefs. If you need anything else, we will be here.}
{137}{}{我们不管你怎么想。你大概不愿意听我讲信仰问题了。那么，如有需要，欢迎你来找我们。}

#{138}{}{It is the most holy of ideas. We are working towards ultimate
# peace in the wasteland. All creatures shall live as one.}
{138}{}{这是最崇高的信念！我们致力于废土的最终和平。所有生物都会化为一身。}

#{139}{}{Thank you. Good day.}
{139}{}{谢谢，再见！}

#{140}{}{They donated this house to us, in order that we might spread
# the word and perform our duty as healers.}
{140}{}{他们把房子捐献给我们了，方便我们的教义传播世界，也方便我们医疗者救苦救难。}

#{141}{}{Isn't Doc Morbid upset about this?}
{141}{}{莫彼得医生居然没意见？}

#{142}{}{That was awfully kind of them. Thanks.}
{142}{}{他们还真是好心人哦，谢谢。}

#{143}{}{Whatever that heathen soul feels is no concern of the Children.
# We are here to do our duty, and it shall be done.}
{143}{}{那个异教徒有什么想法和我们教堂无关，我来这里是尽责尽力的。}

#{144}{}{Uh, gee, thanks. Bye.}
{144}{}{哦，多谢了，再见。}

#{145}{}{Why are you doing this? We will do you no harm!}
{145}{}{你为什么要这样，我们又没有伤害你！}

#{146}{}{You do not have any condition that needs assistance.}
{146}{}{你目前不需要任何救治。}
