{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{What do you want?}
{100}{}{你想做什么？}

#{101}{}{Your guards said you had a job for me.}
{101}{}{你的卫兵说你有工作给我。}

#{102}{}{I don't like your attitude, old man.}
{102}{}{我不喜欢你这个态度，老头。}

#{103}{}{Nothing.}
{103}{}{没事。}

#{104}{}{Fluup.}
{104}{}{咕噜。}

#{105}{}{I might . . . Have you ever dealt with a vicious murdering
# band of thieves before?}
{105}{}{也许吧……你以前对付过凶残的杀人犯罪集团没有？}

#{106}{}{Don't tell me. You've got a gang problem.}
{106}{}{别告诉我你卷进了黑帮的事情。}

#{107}{}{What is it out here? Is there any place in the wasteland
# that doesn't have a gang problem?}
{107}{}{那又怎么了？废土上有不存在黑帮的地方吗？}

#{108}{}{I've dealt with a few.}
{108}{}{我和他们打过些交道。}

#{109}{}{Uh . . . You've dealt with gangs before ?}
{109}{}{哦……你以前和黑帮打过交道？}

#{110}{}{You could say that.}
{110}{}{你说的没错。}

#{111}{}{What's your problem, old man? I just said that I had, didn't I?}
{111}{}{怎么回事，老头？我说过了，我对付过他们。}

#{112}{}{No I haven't, and I don't plan on starting now. Good day, sir.}
{112}{}{我没有，我也不想招惹他们，再见了。}

#{113}{}{Good, then you know how ruthless and bloodthirsty they can be.
# The Blades are the worst of them all, I'm afraid.
# We're a humble, god fearing town that is only trying to survive, and these
# . . . these . . . monsters . . . prey on us . . .
# 【He whispers under his breath】 and our children . . .}
{113}{}{很好。那你就应该知道他们有多残忍和血腥。利刃帮是最坏的一伙。我们这个镇子一向与世无争，不惹事生非，只想好好活下去，但是这些……这些……畜生！他们【激动地喘气】劫掠我们，甚至残害我们的孩子……}

#{114}{}{Yeah, yeah, that's great. What's the job entail and what's it worth to ya?}
{114}{}{好，好，工作的内容和报酬呢？}

#{115}{}{What do you mean "prey on you?"}
{115}{}{什么叫劫掠你们？}

#{116}{}{Why don't you get your guards to do something about them?}
{116}{}{你为什么不让守卫去帮你报仇呢？}

#{117}{}{Well, the Regulators keep them from attacking us outright,
# but it's all they can do to keep our little community safe.
# They try to sneak in at night to kill our citizens, or to,
# to kidnap our children . . . and . . .
# 【He stops a moment to compose himself before continuing】
# Just last week one of them burst through the north gate in the middle
# of the night with dynamite strapped to his body to blow up the Regulator's
# barracks . . . no doubt to weaken us enough so that they could launch
# a full scale attack.}
{117}{}{管理者们可以抵挡他们的正面大规模进攻，但他们也只能做到这点了。利刃帮半夜可以潜入我们的城区，杀死镇民，绑架我们的孩子……【他停下，平复了一下情绪，接着说】上周还有一个匪徒浑身绑了炸药半夜钻进北门，想把管理者的兵营炸掉……显然，他们是为了削弱我们，打算以后全面进攻。}

#{118}{}{What happened to him?}
{118}{}{那个匪徒呢？}

#{119}{}{That sounds a bit extreme, doesn't it?}
{119}{}{太极端了，他们。}

#{120}{}{Luckily, the Regulators killed him before he could complete his plan.
# I saw his body myself.}
{120}{}{还好，管理者在他引爆前把他击毙了，我看过他的尸体。}

#{121}{}{I see. What would you like me to do about it?}
{121}{}{哦，那你要我做什么事情？}

#{122}{}{So you didn't actually see this guy run into your town
# with dynamite strapped to his body?}
{122}{}{也就是说，你没有亲眼看见那个人浑身捆了炸药潜入城市？}

#{123}{}{I'll give you 2000 caps to kill their leader! I want that bitch's head!}
{123}{}{我要你去干掉他们的首领，我给你两千块，要这个婊子的脑袋！}

#{124}{}{You seem to have something personal against her.}
{124}{}{你似乎对她个人有成见。}

#{125}{}{Why just the leader?}
{125}{}{为什么只杀他们的头儿？}

#{126}{}{Sounds good to me.}
{126}{}{报酬不错。}

#{127}{}{They'll fall apart without her . . . her . . . vile influence.}
{127}{}{没有了她……她的邪恶领导，帮会就会四分五裂的。}

#{128}{}{Sounds like a fun girl.}
{128}{}{看起来是个很有趣的姑娘。}

#{129}{}{I've heard enough. I'll do it.}
{129}{}{不用说了，我干！}

#{130}{}{Uh, right. I want no part of this sickness.}
{130}{}{哦，算了，我还是别淌这个混水了。}

#{131}{}{She had my son kidnapped, tortured and killed.
# They left him impaled on a post right outside the gates.}
{131}{}{她绑架了我的儿子，严刑拷打他，最后杀了他。还把他的尸体钉在尖柱上，插在城门口。}

#{132}{}{Those sick bastards . . . I'll take the job.}
{132}{}{这些天杀的混球……我帮你！}

#{133}{}{I don't think I want the job, after all.}
{133}{}{我还是不干了。}

#{134}{}{Thank the gods. Finally, my son shall be avenged.
# The Blades camp is to the north of here. Come back when you've done the job.}
{134}{}{太感谢了，我儿的仇终于可以报了。利刃帮的巢穴就在北边，你杀了那个婊子后回来和我汇报。}

#{135}{}{It was the middle of the night, as I told you. I was asleep.
# Luckily, the Regulators usually catch these barbarians before they even
# make it inside our town.}
{135}{}{那是半夜，我那会在睡觉。还算幸运，管理者经常可以在这些野蛮人闯进来之前逮住他们。}

#{136}{}{Yeah, that's pretty lucky. Pretty convenient, too.}
{136}{}{很幸运……你还很舒适呢。}

#{137}{}{I don't like how this all sounds. Count me out.}
{137}{}{听起来有蹊跷，我不干。}

#{138}{}{Get out of here then! If you won't help Adytum, Adytum has no need for you!}
{138}{}{那就滚！你如果不能帮助内城区，内城区也不需要你！}

#{139}{}{I have no time for idiots. Get out of here.}
{139}{}{我没时间和白痴说话，出去。}

#{140}{}{I might just ignore that remark if you've come here to solve
# my problem for me.}
{140}{}{如果你是来帮我的忙的话，我可以忽略你的无礼。}

#{141}{}{What problem is that?}
{141}{}{你有什么难事？}

#{142}{}{What, that you're old and stupid?}
{142}{}{我无礼了？就因为我说你老而愚蠢？}

#{143}{}{Have you ever dealt with a vicious, murdering band of thieves before?}
{143}{}{你以前对付过凶残的杀人犯罪集团没有？}

#{144}{}{Don't tell me. You've got a gang problem.}
{144}{}{别告诉我你卷进了黑帮的事情。}

#{145}{}{What is it out here? Is there any place in the wasteland that
# doesn't have a gang problem?}
{145}{}{那又怎么了？废土上有不存在黑帮的地方吗？}

#{146}{}{I've dealt with a few.}
{146}{}{我和他们打过些交道。}

#{147}{}{Not another backwater town with a gang problem! This is ridiculous!}
{147}{}{别又是穷乡僻壤闹黑帮这类破事了！太搞笑了！}

#{148}{}{What would be convenient would be to put an end to their foulness
# once and for all!}
{148}{}{最让我舒适的是彻底把他们消灭！}

#{149}{}{Let me guess - you want them dead.}
{149}{}{我猜猜……你是要我把他们都灭了。}

#{150}{}{How can I help?}
{150}{}{那我能为你做什么？}

#{151}{}{There's a lot more going on here than I want to know about.
# I'll be going, now.}
{151}{}{有些事情我还是不知道的好。告辞。}

#{152}{}{What?! You again? What do you want now?}
{152}{}{什么？又是你？你要做什么？}

#{153}{}{I've reconsidered. I'll take the job, old man.}
{153}{}{我考虑过了，我愿意干，老人家。}

#{154}{}{I don't like your attitude, old man.}
{154}{}{我不喜欢你的态度，老头。}

#{155}{}{Nothing.}
{155}{}{没事。}

#{156}{}{【He looks at you warily.】 . . . The Blades camp is to the north of here.
# Come back when you've done the job, and I'll pay you 2000 caps.}
{156}{}{【他谨慎地看了看你】……利刃帮在北边，完事后回来领赏，2000个瓶盖。}

#{157}{}{Why haven't you taken care of it yet?}
{157}{}{你怎么还没把事情做完？}

#{158}{}{I changed my mind.}
{158}{}{我改主意了。}

#{159}{}{I'm working on it.}
{159}{}{我还在努力的。}

#{160}{}{Hey, back off old man.}
{160}{}{嘿，别管这么多，老头。}

#{161}{}{Well, work faster. Don't bother me again until you've ended
# her miserable life!}
{161}{}{好，快点吧。在干掉她之前，你别来我这里烦。}

#{162}{}{Have you done it?! Is she dead? Is she dead?}
{162}{}{你完事了？她死了？她死了？}

#{163}{}{You need some help, old man. Yeah, she's dead.}
{163}{}{别激动，没错，老头，她死了。}

#{164}{}{Of course. I made her suffer as a personal favor to you.}
{164}{}{我让她死得很惨，算是我帮你发泄一下。}

#{165}{}{Yes.}
{165}{}{是的。}

#{166}{}{Thank the gods!!! Here's your money. You'll always be welcome in Adytum,
# my son.}
{166}{}{太感谢了！！！这是你的钱，我们内城区永远欢迎你，年轻人。}

#{167}{}{Finally she knows the taste of hell fire! Bless you, my son.
# 【He wipes away a tear】. Here's an extra 500 caps for putting in the extra
# effort. You'll always be welcome here.}
{167}{}{她终于知道惨死是什么感受了。【老泪纵横】再给你500个瓶盖，谢谢你特殊地关照她。我们永远欢迎你。}

#{168}{}{Have you done it?!? Is she dead? Is she dead?}
{168}{}{你完事了？！她死了？她死了？}

#{169}{}{Wipe the drool off your mouth and sit down, old man.
# There's something we need to talk about.}
{169}{}{把口水擦干净，老实坐下，老头。我们有事要谈。}

#{170}{}{I've got something you need to hear.}
{170}{}{我有事情要和你说。}

#{171}{}{I've had enough of your impudence! Is she dead or not?!}
{171}{}{我受够了你的}

#{172}{}{Here, listen to this.}
{172}{}{给你，听这个。}

#{173}{}{【As he listens to the holodisk he begins to shake and turn red.
# You think he might drop dead on the spot from sheer hate.】
# I'll kill all of you fucking bastards!}
{173}{}{【他听着磁碟上的声音，身子开始发抖，脸涨得通红，你感觉他随时都可能因为愤怒昏厥而死。】我要把你们这些杂种都杀了！}

#{174}{}{You bastard! You've brought the devils in to our home!}
{174}{}{你这个杂种！你把魔鬼带进了我的家门！}

#{175}{}{You see middle aged man in civilian clothing.}
{175}{}{你看见一名穿着便装的中年男子。}

#{176}{}{You see Jon Zimmerman, mayor of Adytum.}
{176}{}{你看见内城区的市长琼·齐默曼。}

#{177}{}{Yeah, what do you want?}
{177}{}{嗯，你想做什么？}

#{178}{}{I have something you should listen to about your son.}
{178}{}{我得了个东西，你应该听听，是有关你儿子的事情。}

#{179}{}{Never mind.}
{179}{}{没事。}

#{180}{}{Blorb.}
{180}{}{那。}

#{181}{}{Who are you?}
{181}{}{你是谁？}

#{182}{}{I'm Jon Zimmerman, mayor of Adytum.  What's it to you?}
{182}{}{我是内城区的市长，琼·齐默曼，你有什么事？}

#{183}{}{Hello.}
{183}{}{你好。}

#{184}{}{Good to see you.}
{184}{}{你好。}

#{185}{}{Thanks for all your help.}
{185}{}{多谢。}

#{186}{}{My son can now rest in peace.}
{186}{}{我儿子终于可以安息了。}

#{187}{}{My son is revenged.}
{187}{}{我儿子的仇终于报了！}

