{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Julianna.}
{100}{}{你看见茱莉亚娜。}

#{101}{}{You see a simple Adytowner.}
{101}{}{你看见一个普通的内城区居民。}

#{102}{}{Hello.}
{102}{}{你好。}

#{103}{}{Erf.}
{103}{}{呃。}

#{104}{}{Hello.}
{104}{}{你好。}

#{105}{}{I have a message from Romero.}
{105}{}{罗梅罗让我给你带信。}

#{106}{}{May I ask your name, miss?}
{106}{}{你叫什么名字，小姐？}

#{107}{}{I'm Julianna.}
{107}{}{我是茱莉亚娜。}

#{108}{}{Do you have a job here?}
{108}{}{你有工作吗？}

#{109}{}{Can I ask a little about your town?}
{109}{}{我能问你几个有关这里的事情吗？}

#{110}{}{I do what Caleb asks. But I am really only able to do a little farming.
# I don't have the skills to help Smitty or Miles out.}
{110}{}{卡勒布让我做什么我就做什么。但我也就懂一点农作。帮不上施密蒂和麦尔斯的忙。}

#{111}{}{Tell me a bit about those others you mentioned.}
{111}{}{你说的这些人，能多讲点他们的事情吗？}

#{112}{}{We survive, and the Regulators make sure that nothing happens to hurt us.
# Mostly by not letting us out of here.}
{112}{}{我们干活，管理者们保护我们，基本上不让我们离开这里。}

#{113}{}{Well, Miles does chemistry, and he makes bullets and things.
# Smitty is a craftsman who builds things like pots and knives.}
{113}{}{麦尔斯是搞化学的，他做子弹之类的货。施密蒂是个手艺人，会做水壶和刀子。}

#{114}{}{You have a message from Romero? What is it?}
{114}{}{你有罗梅罗的消息？什么消息？}

#{115}{}{He says that he's through with you.}
{115}{}{他说他和你没关系了。}

#{116}{}{He says that he sends his love.}
{116}{}{他给你带来爱意。}

#{117}{}{He sent this locket as a token.}
{117}{}{他把这个盒子给你做定情物。}

#{118}{}{No . . . it can't be true . . . I . . .}
{118}{}{不……这不可能……我……}

#{119}{}{Did he do nothing else?}
{119}{}{他还说什么了？}

#{120}{}{No, sorry.}
{120}{}{没有，抱歉。}

#{121}{}{Oh yeah, he sent this locket.}
{121}{}{对了，他还要我把这个给你。}

#{122}{}{How romantic! Oh, I must see him somehow! If only . . .
# perhaps . . . maybe Lorraine can bring him a message . . .}
{122}{}{太浪漫了！我要去见他！如果……也许……可能洛林可以帮我给他带话……}

#{123}{}{Oh! Thank you so much for your help! We have decided
# to live here now, with the Followers, in peace.
# Thank you for supporting our love.}
{123}{}{哦！太感谢你了！我们打算住在这里，和末世论者和平相处。感谢你支持我们的结合。}

#{124}{}{I cannot live without him!}
{124}{}{没了他我还怎么活啊……}

#{125}{}{Julianna draws a knife and plunges it into herself!}
{125}{}{【茱莉亚娜掏出一把刀插进了自己的心窝！】}

#{126}{}{You gain 250 for assisting the star-crossed lovers with the delivery of
# Romero's locket to Julianna.}
{126}{}{你帮助罗梅罗把盒子送给茱莉亚娜，成全了一对坎坷爱人，你获得250点经验值。}
