{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Sheriff Justin Greene.}
{100}{}{你看见治安警长贾斯丁·格林。}

#{101}{}{Awe, it's the slayer of the innocents. I've heard of you, and you're lucky I have a badge stopping me
# from blowing you away on the spot. I suggest you leave our town--Right now. And stay away from our children.}
{101}{}{噢，你就是那个四处残害平民的人。我听说过你，要不是我胸前戴着警徽，我现在就一枪把你就地轰了。你给我离开这个城市，马上！你的脏手别碰孩子们。}

#{102}{}{Hello sir! The name's Justin Greene. I'm the sheriff of this fine city. Is there something I can
# do for you this fine day?}
{102}{}{你好，先生！我是贾斯丁·格林，这个城市的警长。我能帮你什么吗？}

#{103}{}{Hello ma'am! The name's Justin Greene. I'm the sheriff of this fine city. Is there something I can
# do for you this fine day?}
{103}{}{你好，女士！我是贾斯丁·格林，这个城市的警长。我能帮你什么吗？}

#{104}{}{Well, spit it out!}
{104}{}{很好，说出来！}

#{105}{}{Decker tried to hire me to kill some merchant and his wife.}
{105}{}{德克要我去杀一个商人和商人的老婆！}

#{106}{}{Decker tried to hire me to kill someone named Jain.}
{106}{}{德克要我去杀简恩！}

#{107}{}{Nothing, sorry.}
{107}{}{没事，对不起。}

#{108}{}{Sorry, I can't tell you. I'd be dead.}
{108}{}{对不起，我不能告诉你，我会死的。}

#{109}{}{Well, thank you. We try our best. It's really tough in a city this size, but we do the best we can with
# what we've got. It's hard when the thugs have better firepower than you do.}
{109}{}{谢谢你，我们尽我们的全力。这么大的城市，工作可不好做，但是我们会竭尽所能的。有时候匪徒的火力比我们都大，真的不太好办。}

#{110}{}{Thanks again.}
{110}{}{谢谢你。}

#{111}{}{It's time for you to leave, child killer.}
{111}{}{你该走了，杀小孩的人。}

#{112}{}{We couldn't have that. But, if you ever change your mind, please let me know. It's a dangerous
# place out there and someone has to stand up for what's right.}
{112}{}{我们不能那样。如果你改变了主意，告诉我。这是个危险的地方，总有人要站出来伸张正义的。}

#{113}{}{Excellent! I had already heard from other sources about his plan. You're the final confirmation I needed
# to take action against him. This is going to be rough, and I can use any help I can get. I can pay you 1300
# scripts. 300 now, and the rest when we're all done. What do you say?}
{113}{}{太好了！我早就通过其他途径打探到了他的计划。你的举报最后证实了这点，我们可以去端掉他。不过要有一场恶仗要打，我还需要人手。我给你1300个瓶盖，现在先付你300个，办完事后再给你剩下的。你去不去？}

#{114}{}{You're too late...Damn! I knew he was responsible, I only wish I knew in time to stop him. In any case,
# you're the final witness I needed to act. We'll have to "take him out." This is going to be rough, and I can
# use any help I can get. I can pay you 1300 scripts. 300 now, and the rest when we're all done. What do you say?}
{114}{}{你来的太晚了……妈的。我就知道他是幕后黑手，应该早点阻止他的。不管怎么说，你也算是最后一个目击者了。我要去拿下他，还需要人手。我给你1300个瓶盖，现在先付你300个，办完事后再给你剩下的。你去不去？}

#{115}{}{You're too late...How do I know you're not responsible? Decker's not likely to let someone know about his
# plans and live.}
{115}{}{你太晚了……我怎么知道是不是你干的？德克一般不让知道他计划的人活着。}

#{116}{}{I just got word that she's already dead...wait a minute. How do I know that you're not the one responsible?
# Decker's not likely to let someone know about his plans and live.}
{116}{}{我刚刚听到她已经死了……等一下，我怎么知道是不是你干的？德克一般不让知道他计划的人活着。}

#{117}{}{It'll be a pleasure.}
{117}{}{很荣幸。}

#{118}{}{Sorry, I want it all up front.}
{118}{}{对不起，我要一次付清。}

#{119}{}{No way! You're on your own.}
{119}{}{不干，你自己去。}

#{120}{}{No way. You seem trustworthy, but I can't be sure that you won't leave us when it gets hot. This way,
# one of us has to survive to be sure you get paid. This way, it might add a 'little' bit of insurance.}
{120}{}{不可以，你虽然看起来可以信任，但是打得不顺的时候我怎么知道你会不会开溜。分开付，只要我们警察有人活下来，就会给你钱。这样似乎更加保险一点。}

#{121}{}{Let's do it.}
{121}{}{好，走！}

#{122}{}{You're on your own, Sheriff.}
{122}{}{你自己去吧，警长。}

#{123}{}{Great! Here's the first part of your payment.  【The Sheriff hands you 300 caps】}
{123}{}{很好！这是你的定金！【警长给了你300个瓶盖】}

#{124}{}{I'm ready.}
{124}{}{我准备好了。}

#{125}{}{Okay, Bye.}
{125}{}{好，再见。}

#{126}{}{I'm really sorry to hear that. If you change your mind, let me know, but I can't wait very long.}
{126}{}{很遗憾。如果你改主意了，回来和我说，但是我等不了太久的。}

#{127}{}{Okay, I'll do it. Just wait for me to get some supplies.}
{127}{}{好，我去，你先等我去搞点装备。}

#{128}{}{You're mad.}
{128}{}{你疯了。}

#{129}{}{Bye.}
{129}{}{再见。}

#{130}{}{Great!  Here's the first part of your payment.  【The Sheriff gives you 300 caps】}
{130}{}{很好！这是你的定金！【警长给了你300个瓶盖】}

#{131}{}{What? Do you expect me to stand around and let him kill innocent people? I've a responsibility to this
# city, which I don't expect you to understand.}
{131}{}{什么？你让我在他杀死无辜百姓的时候袖手旁观？我肩负了保护这个城市的职责，算了，说了你也不明白。}

#{132}{}{You're right. Now's it's your turn.}
{132}{}{没错，轮到你了。}

#{133}{}{How dare you accuse me!}
{133}{}{你怎么能诬告我！}

#{134}{}{I don't care what you think.}
{134}{}{我不管你怎么想。}

#{135}{}{Well, he didn't try anything.}
{135}{}{他没有做任何事情。}

#{136}{}{We were in the Falcon, and there were a lot of people around.}
{136}{}{我们当时在马耳他猎鹰酒吧，好多人在场。}

#{137}{}{I'm sorry. Decker's been playing us all against each other for years. I don't know who to trust any more.
# I really could use your help, though. It'll be rough, but I'll pay you 1300 scripts. 300 now and 1000 when
# we're done.}
{137}{}{对不起，德克和我们玩了好多年了。我都不知道该相信谁了。但我真的需要帮忙。仗不好打。我给你1300个瓶盖，先付300，后面1000完事后再补上。}

#{138}{}{I know a rat when I smell one! You're lucky I don't have any proof, and I suggest you leave town before I find some.}
{138}{}{你藏不住身上的血腥气。算你走运，我没有指控你的证据，我建议你在我搜到证据前滚出这个城市。}

#{139}{}{That's very strange. I've never heard of Decker coming out of his office. He must be getting braver. That
# damn, murdering...argh! I'll get him yet! I'll tell you what, you help us out, and I'll pay you 1300 scripts--
# 300 now and 1000 when we're all done. What do you say?}
{139}{}{很奇怪。我从来没听说过他会走出办公室。他胆子大起来了？这个无耻的、残忍的……恶！我要去干掉他！我和你说，你可以帮助我们，我给你1300个瓶盖，先付300个，后面1000个完事后再补上。怎么样？}

#{140}{}{That's the biggest pile of Brahmin shit I've ever heard. Decker never leaves his office. I knew there was
# something not right about you. You're lucky I don't have any proof, and I suggest you leave town before I find
# some!}
{140}{}{这是我听过的最他娘扯的谎话。德克从来不离开自己的办公室。我就知道你这个人不地道。算你走运，我没有指控你的证据，我建议你在我搜到证据前滚出这个城市。}

#{141}{}{Okay, let's go...}
{141}{}{好，我们走……}

#{142}{}{So, you came to turn yourself in? I'm impressed.}
{142}{}{你是来自首的？我很钦佩。}

#{143}{}{Yes, I'm sorry.}
{143}{}{对，我很抱歉。}

#{144}{}{Turn myself in? Don't make me laugh.}
{144}{}{自首？别逗了！}

#{145}{}{Get him!}
{145}{}{抓住他！}

#{146}{}{Get her!}
{146}{}{抓住她！}

#{147}{}{Alright, into your cell you go.}
{147}{}{很好，去牢房吧。}

#{148}{}{Just sit tight. You're not going anywhere for a while.}
{148}{}{别动，目前你哪里也去不了了。}

#{149}{}{Fugitive! Get him!}
{149}{}{逃犯！抓住他！}

#{150}{}{Fugitive! Get her!}
{150}{}{逃犯！抓住她！}

#{151}{}{Ready to go take out Decker?}
{151}{}{去拿德克去？}

#{152}{}{Yes.}
{152}{}{对。}

#{153}{}{No.}
{153}{}{不。}

#{154}{}{Ug.}
{154}{}{唔。}

#{155}{}{I can't believe Decker's finally dead. I never thought I'd see the day.}
{155}{}{没想到德克真死了。我从来没想到会有这么一天。}

#{156}{}{Have you changed your mind? We could still use you to get rid of that disease we talked about.}
{156}{}{你改主意了？你可以帮我们去为民除害。}

#{157}{}{I'll go.}
{157}{}{我去。}

#{158}{}{No, sorry.}
{158}{}{不，对不起。}

#{159}{}{Fah?}
{159}{}{嘎？}

#{160}{}{We're watching you.}
{160}{}{我们会盯紧你的。}

#{161}{}{I have a crime to report!}
{161}{}{我要举报！}

#{162}{}{You're doing a fine job.}
{162}{}{你干得不错！}

#{163}{}{Just stopping by. See ya.}
{163}{}{来看看你，再见。}

#{164}{}{Oula.}
{164}{}{噢啦。}

#{165}{}{Hello again, sir. What can I do for you today?}
{165}{}{又见面了，先生，你今天有什么事？}

#{166}{}{Hello again, ma'am. What can I do for you today?}
{166}{}{又见面了，女士，你今天有什么事？}

#{167}{}{Hello. How can I help you?}
{167}{}{你好，我能帮你什么？}

#{168}{}{Yes?}
{168}{}{嗯？}

#{169}{}{Just sleep if off, okay?}
{169}{}{我睡过头了。}

#{170}{}{You're kidding!  Well... uh... did... did he ask you personally?}
{170}{}{你开玩笑吧！呃……他和你单独见面的？}

#{171}{}{Yes, he did.}
{171}{}{是的。}

#{172}{}{Man, that was one hell of a battle!  You did well in there.  Now that Decker and Kane are gone the rest of the
# Underground will fall very shortly.  Without leadership, organizations like that can't last.  Nobody around here is smart
# enough to take up the reigns.}
{172}{}{老天，这真是一场好斗啊！你干得不错。德克和凯恩死了，匪徒也会很快树倒猢狲散的。没有领导的组织是不长久的。没有人敢出头当新老板。}

#{173}{}{Well, here's the rest of your reward.  Thanks again for your help.  This city owes you a debt of gratitidue.
#  【The Sheriff hands you 1000 caps】}
{173}{}{这是你剩下的报酬。多谢你的协助。这个城市欠你的情。【警察给了你1000个瓶盖】}

#{174}{}{We can leave as soon as you're ready.}
{174}{}{只要你准备好，我们就走。}

#{175}{}{Let me know when you're ready. We'll wait for you, but don't take too long.}
{175}{}{准备好和我说一声，我们等你，但不会太久。}
