{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Kane.}
{100}{}{你看见凯恩。}

#{101}{}{What's the job and what's it pay?}
{101}{}{有工作吗？薪水如何？}

#{102}{}{Work for this dump?  You've got to be joking.}
{102}{}{为这个鬼地方工作？你开玩笑吧。}

#{103}{}{Damn straight, and it looks like I'm going to have to kick your ass, just because.}
{103}{}{你真是说得太好了，所以我要扁你一顿啊。}

#{104}{}{Sorry, maybe later.}
{104}{}{算了，以后再说吧。}

#{105}{}{No thanks.}
{105}{}{不，谢谢。}

#{106}{}{Tuk?}
{106}{}{噶？}

#{107}{}{I guess the reports must have been wrong, beat it.  We don't hire skags.}
{107}{}{走开，你找错地方了，我们不需要小混混。}

#{108}{}{It's not skag work. You'll need to do 'it' quick and clean.  The boss'll give you details, but it's
# more money than you'll make in a month working for the caravans, but only if you're good enough. We don't
# take kindly to failures, if you know what I mean.}
{108}{}{这可不是小混混能做的事情。你要做的麻利干净。老板会和你细谈，报酬嘛会比干一个月商队保镖都挣得多，但是首先你要有能力。如果失败了，我们可对你不客气的，你知道我的意思吧。}

#{109}{}{Sounds good.}
{109}{}{听起来不赖。}

#{110}{}{I can't right now.  Let me get back to you.}
{110}{}{现在不行，我等会再回来。}

#{111}{}{Who do I have to kill?}
{111}{}{我要杀谁？}

#{112}{}{No thanks.  I don't need the money.}
{112}{}{不，谢谢。我不想挣钱。}

#{113}{}{I'm sure you're familiar with our sort of business, so let me just say it would be in your best
# interest to keep this to yourself.  Shall we?}
{113}{}{看起来你很熟悉这行当嘛。但是你要管好自己的大嘴巴，知道吗？}

#{114}{}{I hope for your sake that that was an attempt at humor.  Do not cross us, you will regret it.}
{114}{}{刚才的事情都是开玩笑。别和我们做对，要不然你会后悔的。}

#{115}{}{Sure.  Now what does this 'work' involve?}
{115}{}{好好好。那这个“工作”是关于什么的？}

#{116}{}{Yeah, whatever, tough guy.}
{116}{}{哦，好的，你这个大块头。}

#{117}{}{I don't think you understood me. Let me clarify.  If you don't watch your manners, you will find yourself
# dead, tough guy.}
{117}{}{你没听明白我的意思吧，我给你挑明了说，如果你再这么臭屁，你就是死人了，你这个混球。}

#{118}{}{I don't think you understood me. Let me clarify. If you don't watch your manners, you will find yourself
# dead, tough gal.}
{118}{}{你没听明白我的意思吧，我给你挑明了说，如果你再这么臭屁，你就是死人了，你这个糙妹。}

#{119}{}{No, let me clarify--if you don't watch it, I'll be wearing your ass for a shoe.}
{119}{}{我跟你说清楚吧——如果你再这么臭屁，信不信我把你屁股扯下来做鞋面？}

#{120}{}{Okay.  I get the picture.  Now what is it you want me to do?}
{120}{}{哦，我知道了，那你要我做什么？}

#{121}{}{I'll talk to you later. I've got to go.}
{121}{}{我以后再和你聊，告辞了。}

#{123}{}{Oh, please do.  We'll be holding our breath.}
{123}{}{哦？来啊！我悉听尊便哇！}

#{124}{}{But of course, good day.}
{124}{}{是吗，那再见了。}

#{125}{}{Don't need the money?  Surely you're jesting, but from what I've heard about you, you might enjoy the
# work I had in mind for you.}
{125}{}{不想挣钱？开什么玩笑，据我对你的了解，你应该会很喜欢我们的这份工作的。}

#{126}{}{Really?  I might be interested, lead on.}
{126}{}{是吗？也许吧，那说说看。}

#{127}{}{No thanks.}
{127}{}{不，谢谢。}

#{128}{}{I'll get back to you.}
{128}{}{我过阵子再来找你。}

#{129}{}{It's... Would you like to accompany me down stairs?  There are too many ears around.}
{129}{}{好……你跟我下楼吧，这里耳目太多了。}

#{130}{}{Sure.}
{130}{}{好。}

#{131}{}{Not interested.}
{131}{}{算了。}

#{132}{}{Not right now, I'll get back to you.}
{132}{}{现在不行，我待会再找你。}

#{133}{}{Leave, I don't have the patience.}
{133}{}{那就走开，我可没耐心等你。}

#{134}{}{Do you value your life?}
{134}{}{你想不想活了？}

#{135}{}{You've had your chance, now beat it.}
{135}{}{你只有一次机会，现在给我滚。}

#{136}{}{Are you looking for trouble?}
{136}{}{你想找麻烦是吧？}

#{137}{}{You just don't learn do you?  You'll soon learn some respect.}
{137}{}{你是蜡烛啊？你要长点记性啊。}

#{138}{}{I've heard of you.  They say you're one mean son of a bitch.  If you're
# looking for some work, I might be able to set you up with someone.  Are you interested?}
{138}{}{我知道你这个人，他们说你是个十足的恶棍。那么，如果你想要工作，我可以帮你联系，有兴趣吗？}

#{139}{}{I've heard of you.  They say you're one mean bitch.  If you're
# looking for some work, I might be able to set you up with someone.  Are you interested?}
{139}{}{我知道你这个人，他们说你是个十足的悍妇。那么，如果你想要工作，我可以帮你联系，有兴趣吗？}

#{140}{}{I've heard of you.  You're the one that took out Killian in Junktown, nice going.  Gizmo must have
# paid you well for that one. What brings you to the Hub, looking for some work?}
{140}{}{我听说过你，是你杀了伽克镇的基利安，干的漂亮！吉斯莫给你不少好处吧，你怎么来哈勃城了，找活儿干？}

#{141}{}{I've heard of you.  You're the one that took out Gizmo over in Junktown.  Killian must have paid you
# a good sum for that job.  Are you here for some work, maybe?}
{141}{}{我听说过你，是你杀了伽克镇的吉斯莫，干的漂亮！基利安给你不少好处吧，你怎么来哈勃城了，找活儿干？}

#{142}{}{I've heard of you.  You're the bitch that took out Killian and Gizmo.  Now that's the way to
# solve a problem... So, what brings you to the Maltese Falcon?  Looking for some work?}
{142}{}{我听说过你，你这个婊子把伽克镇的基利安和吉斯莫都干掉了，这也是一种解决问题的办法哈……你怎么来马耳他猎鹰酒吧了，找活儿？}

#{143}{}{I've heard of you.  You're the bastard that took out Killian and Gizmo.  Now that's the way to
# solve a problem... So, what brings you to the Maltese Falcon?  Looking for some work?}
{143}{}{我听说过你，你这个牛人把伽克镇的基利安和吉斯莫都干掉了，这也是一种解决问题的办法哈……你怎么来马耳他猎鹰酒吧了，找活儿？}

#{144}{}{I've heard of you.  You're making quite a name for yourself. What brings you to the Hub?}
{144}{}{我听说过你，你也算是打出名号的人了。什么风把你吹到哈勃来了？}

#{145}{}{I'm looking for a water chip.}
{145}{}{我来这里找净水芯片。}

#{146}{}{I need to talk to Decker.}
{146}{}{我要和德克说话。}

#{147}{}{Do you run this joint? }
{147}{}{这里你们开的馆子？}

#{148}{}{I'm here to kick your ass.}
{148}{}{我来这里揍你妈的。}

#{149}{}{I think I'm going to have to hurt you now.}
{149}{}{我要扁死你。}

#{150}{}{You won't have to worry about your health when I get through with you.}
{150}{}{你放心，你马上就会死得没悬念的。}

#{151}{}{I'm cleansing the world of all that is evil!}
{151}{}{我要扫除世界的邪恶！}

#{152}{}{I've got to go, bye.}
{152}{}{我要走了，再见。}

#{153}{}{That's it, bye.}
{153}{}{就这样，再见了。}

#{154}{}{Tuk?}
{154}{}{嘎？}

#{155}{}{Barooka!}
{155}{}{巴茹咔！！！}

#{156}{}{A water chip?  Never heard of it, we only sell drinks.  Go see Bob's Iguana Bits, if you're hungry.}
{156}{}{净水芯片？没听说过，我们只卖酒。你要是饿了，可以去鲍勃的蜥蜴串烧铺。}

#{157}{}{It's an electronic device that regulates the filtering system of a water purifier and monitors the
# output for any contamination.  Mine's broken and I'm looking for a replacement.}
{157}{}{是一种电子装置，可以控制净水过滤，监测污染。我原来的坏了，我要找个新的。}

#{158}{}{No, it's a small piece of machinery that runs a water purifier.}
{158}{}{不是吃的，是一种电子元件，可以控制净水系统。}

#{159}{}{Another question for you... }
{159}{}{还有一个问题……}

#{160}{}{Okay thanks. Bye.}
{160}{}{好，多谢了，再见。}

#{161}{}{Do I look like a merchant? Stop wasting my time.}
{161}{}{我看起来像商人吗？别浪费时间了。}

#{162}{}{You might want to check with the Water Merchants.  They're south of the Merchant Market.  You can't
# miss them.  They surround a big water tower.}
{162}{}{你可以去问问纯水商人，他们在市场的南边，水塔周围。}

#{163}{}{You?  That's the funniest thing I've ever heard.}
{163}{}{就你？这真是我这辈子听过的最搞笑的事情。}

#{164}{}{Things will look really funny to you when I get through rearranging your face!}
{164}{}{等我把你的脸修理一遍，你就会发现很好笑了。}

#{165}{}{We'll see who's laughing when the blood settles.}
{165}{}{我倒要看看谁笑到最后。}

#{166}{}{You think you can take me? You may be a strong one, but that won't help you dodge a bullet.}
{166}{}{你以为能干掉我？你是个厉害的主，但你有子弹硬？}

#{167}{}{You're right, I'm so sorry.  Please don't shoot me.}
{167}{}{你说的对，我道歉，别开枪。}

#{168}{}{I see. You have to hide behind a gun do you?}
{168}{}{看出来了，你除了枪别的什么都不会？}

#{169}{}{You're pitiful. Maybe I should just put a bullet through your head right now and end your misery.
# What do you say, would you like a new hole through that brainless head of yours?}
{169}{}{你真是猥琐。也许我真的应该往你脑袋里送颗子弹结束你的狗命。你说呢？你喜欢在你那个空空的脑袋上扎个眼吗？}

#{170}{}{I'm sorry.  I really didn't mean it. Please don't shoot me.}
{170}{}{对不起，我真的不是冒犯您，别开枪啊。}

#{171}{}{You can only take me with a gun? Are you afraid I'll kick your ass without it?}
{171}{}{你只能用枪摆平我？如果没枪，你是不是怕我海扁你？}

#{172}{}{What?  Are ya afraid of a little girl like me, ya have to use a gun? }
{172}{}{什么！对我这样的弱女子，你还要用枪？}

#{173}{}{Sure.}
{173}{}{好啊。}

#{174}{}{That's it!  If you think you know what pain and suffering is, wait until I get through with you. }
{174}{}{让你能！等会我灭了你，你就知道什么叫痛苦了。}

#{175}{}{Keep that mutt under control or it's dead. }
{175}{}{管好你的狗狗，要不然我宰了它！}

#{176}{}{Keep you friend out of this. }
{176}{}{让你的跟班退后。}

#{177}{}{Keep you buddies out of this or their dead. }
{177}{}{让你的跟班退后，要不然他们就是死人了。}

#{178}{}{Back off boys, he's mine.}
{178}{}{大家退后，我来料理他。}

#{179}{}{Back off boys, she's mine.}
{179}{}{大家退后，我来料理她。}

#{180}{}{You've disappointed me, I thought you where tougher than that.}
{180}{}{你太让我失望了，我还以为你很强呢。}

#{181}{}{Hide?  I don't need to hide behind anything and I do NOT need a gun to deal with you. }
{181}{}{只会用枪？放屁，没有枪我也能搞定你！}

#{182}{}{Keep that mutt under control or it's dead. }
{182}{}{管好你的狗狗，要不然我宰了它！}

#{183}{}{Keep you friend out of this. }
{183}{}{让你的跟班退后。}

#{184}{}{Keep you buddies out of this or their dead. }
{184}{}{让你的跟班退后，要不然他们就是死人了。}

#{185}{}{(over his shoulder) Back off boys, he's mine.}
{185}{}{【轻蔑】大家退后，我来料理他。}

#{186}{}{(over his shoulder) Back off boys, she's mine.}
{186}{}{【轻蔑】大家退后，我来料理她。}

#{187}{}{Tough words, little man.  Tell you what, I'll put my toys away and
# we'll see who's left standing.}
{187}{}{你这个小子真是大言不惭。我跟你说，我不用我的枪揍你，看你我谁先倒下。}

#{188}{}{Though words, little girl. Tell you what, I'll put my toys away and we'll see who's left standing.}
{188}{}{你这个小婊子真是大言不惭。我跟你说，我不用我的枪揍你，看你我谁先倒下。}

#{189}{}{I'm sorry.  I really didn't mean it. Please don't hurt me.}
{189}{}{对不起，我真的不是想冒犯您，别打我啊。}

#{190}{}{Come and get it.}
{190}{}{来啊！}

#{191}{}{Okay, but I'd hate to make you cry.}
{191}{}{来啊，痛了别喊，我最怕吵了。}

#{192}{}{No, thanks.  I don't have the time, bye.}
{192}{}{多谢，我没时间，再见。}

#{193}{}{You'd be wise not to turn your back after what you've been saying.  You should be thankful that I am
# such a forgiving person... this time. Until we meet again.}
{193}{}{你以为说话可以当放屁啊，你太走运了，我心好，这次就放过你了，下次不饶你。}

#{194}{}{I'm going to enjoy this. }
{194}{}{我就喜欢这个。}

#{195}{}{Just keep that mutt under control or it's dead.}
{195}{}{管好你的狗狗，要不然我宰了它！}

#{196}{}{Just keep you friend out of this.}
{196}{}{让你的跟班退后。}

#{197}{}{Just keep you buddies out of this or they're dead. }
{197}{}{让你的跟班退后，要不然他们就是死人了。}

#{198}{}{(over his shoulder) Back off, boys. She's mine.}
{198}{}{【轻蔑】大家退后，我来料理他。}

#{199}{}{(over his shoulder) Back off, boys. He's mine.}
{199}{}{【轻蔑】大家退后，我来料理她。}

#{200}{}{Cleansing? That's quite nice of you, but 'evil' is very subjective. What or who you might consider to
# be evil could very well be the opposite to someone else.}
{200}{}{扫除邪恶？你还是个好人那，不过“邪恶”是很主观的东西。你觉得是邪恶的人或东西，其他人恰恰很喜欢呢。}

#{201}{}{Yes I agree, but does that mean that we sit around and do nothing just because we aren't sure?}
{201}{}{没错，我同意你的观点。可是，我们能因为不肯定就不肯作为吗？}

#{202}{}{That's ridiculous. What's evil is evil.  Anyone who says otherwise is just stupid.}
{202}{}{很可笑的观点，邪恶就是邪恶，其他说辞都是愚蠢。}

#{203}{}{Whatever. I was just joking.}
{203}{}{算了，我只是开个玩笑。}

#{204}{}{I certainly hope so.  We have enough problems in the world without having a blind fanatic running
# around killing everyone.}
{204}{}{我希望那是个玩笑。我们的世界问题很多了，可别再来个满世界宰人的理想主义变态。}

#{205}{}{A pity.  A blind fanatic is a dangerous person indeed.  I hope your stay here in the Hub is not long.
# We don't take kindly to murders that aren't auth... to murders of any sort.  Good day.}
{205}{}{你的想法真糟糕。一个盲目的理想主义者当真危险。我希望你不要在哈勃城呆太久，我们对乱杀人的凶手可不轻饶。再见。}

#{206}{}{No.}
{206}{}{不。}

#{207}{}{Nice answer moron.  Who's in charge?}
{207}{}{很好的回答，你这个白痴。谁是管事的？}

#{208}{}{Who does?}
{208}{}{谁管事？}

#{209}{}{Moron? Do you have any idea who you are talking to? For your sake I hope not. I don't 'run' the Maltese
# Falcon but I AM the one in charge. What do you want before I lose my temper.}
{209}{}{白痴？你知道你在和谁说话吗？你大概不知道吧，那还情有可原。我虽然不是“开”马耳他猎鹰酒吧的人，但我就是这里管事的。你赶紧说自己想干嘛，别让我发火。}

#{210}{}{I know who you are and trust me, you 'are' a moron.}
{210}{}{我知道你是谁，你就是一个白痴！}

#{211}{}{Oh, I'm sorry.  Who runs this place?}
{211}{}{哦，对不起了，那谁是这里的负责人？}

#{212}{}{We'll see. Have 'nice' day.}
{212}{}{好，那我们就看看谁是白痴，你觉悟吧。}

#{213}{}{If you don't know, you shouldn't ask.  It can be bad for your health.}
{213}{}{如果你不知道，你就不要乱问，对你没好处。}

#{214}{}{In regards to what?}
{214}{}{关于什么事？}

#{215}{}{A job.}
{215}{}{一个工作。}

#{216}{}{It's a secret.}
{216}{}{这是秘密。}

#{217}{}{That doesn't concern you.  Now show me to him.}
{217}{}{这和你没关系，你带我去找你老板。}

#{218}{}{Don't push your luck, buddy, or you'll meet Decker in a bag.  This way,
# and watch yourself.  I'll be watching.}
{218}{}{别做傻事，小子，要不然你就在裹尸袋里去见我老板德克了。这里走，你要老实点，我会看着你的。}

#{219}{}{Don't push your luck, lady, or you'll meet Decker in a bag. This way, and watch yourself. I'll be watching}
{219}{}{别做傻事，小妞，要不然你就在裹尸袋里去见我老板德克了。这里走，你要老实点，我会看着你的。}

#{220}{}{I think it 'does' concern me and I don't think I'll be showing you anything... that's if you're lucky.
# Now get lost.}
{220}{}{我觉得这就关我的事，我不会带你去任何地方……这还是因为我心情好。现在给我滚。}

#{221}{}{Sorry, but anything you have to tell Decker can be told to me.  I'm his right hand man and there's
# nothing that goes on here that we both aren't fully aware of.}
{221}{}{你想和德克说什么都要先告诉我，我是他的得力助手，他的事情我都知情的。}

#{222}{}{It's about a job.}
{222}{}{是工作的事情。}

#{223}{}{Sorry, I was sworn to secrecy.  I can only tell Decker.}
{223}{}{抱歉，我一定要保守这个秘密的，我只能和德克说。}

#{224}{}{Well, then you're not going to see him.}
{224}{}{那你就不能见他。}

#{225}{}{Who sent you?}
{225}{}{谁派你来的？}

#{226}{}{Beth sent me.}
{226}{}{贝斯让我来的。}

#{227}{}{Lorenzo sent me.}
{227}{}{罗伦佐让我来的。}

#{228}{}{Loxley sent me.}
{228}{}{洛克西里让我来的。}

#{229}{}{The Sheriff sent me.}
{229}{}{警长让我来的。}

#{230}{}{No one.}
{230}{}{没人派我来。}

#{231}{}{Beth who?}
{231}{}{哪个贝斯？}

#{232}{}{You know.}
{232}{}{你知道的。}

#{233}{}{She didn't say.  She runs the weapon shop.}
{233}{}{她没说她的姓，就是那个开武器店的。}

#{234}{}{Get out of my face.  I don't have time for your games.}
{234}{}{走开，我没时间和你玩游戏。}

#{235}{}{Then you'll see no one.}
{235}{}{你不能进去。}

#{236}{}{Tell our friendly Sheriff Greene that Decker's schedule is looking a bit busy and that he should try
# back in a few months.  I'm sorry, but I think you should leave... for good.}
{236}{}{告诉我们的那个好朋友格林警长，德克最近很忙，让他几个月后再来拜访我们吧。抱歉，你可以走了……这是为你好。}

#{237}{}{I don't think she sent you here.  Please leave.}
{237}{}{我想她不会派你来的，走开。}

#{238}{}{Did he now?  Are they ready to come under our protection?  Are you one of them?}
{238}{}{他？终于想通了？他们打算接受我们的保护了？你是他们的一伙？}

#{239}{}{I don't know what you're talking about.  He just mentioned that Decker might have some work for me.}
{239}{}{我不知道你说什么。他就跟我说德克会有活儿给我做。}

#{240}{}{Me? Work for those thieves, never.  I'd rather have to watch my back than my purse.}
{240}{}{我？跟那些贼一伙？不可能。我宁可打打杀杀，也不和他们玩钱包游戏。}

#{241}{}{You protect us? NEVER!}
{241}{}{你保护我们？门都没有！}

#{242}{}{Look, buddy. I'm just looking for some good, clean, honest, work.}
{242}{}{老兄，我就想找点干净的、诚实的好工作。}

#{243}{}{Are you?  Well you came to the wrong place then, the Hub is anything but honest.  Go back to whatever
# hole you crawled out of.  You'll be happier there.}
{243}{}{是吗？那你走错地方了，哈勃城从来就不是一个诚实的地方。滚回你以前呆的地洞吧，你在那里也许会更自在。}

#{244}{}{I agree.  Well then, follow me and we'll see how useful you are to us.  Just keep in mind that it would
# be in your best interest to keep anything that is said to you to yourself.}
{244}{}{我同意，那你跟我来，也许你能派上用场，但是你要记住，我们和你说的任何话你都要烂在肚子里，明白？}

#{245}{}{That might be.  Are you a member of their 'Thieves Circle?'}
{245}{}{也许有门。你是“盗贼帮”的成员？}

#{246}{}{Yes.}
{246}{}{是。}

#{247}{}{No.}
{247}{}{不是。}

#{248}{}{Well, I'm sorry, but we don't work with your little friends.  We barely tolerate their existence and
# we would never work with them.}
{248}{}{那就抱歉了，我们不愿意和你的那些朋友共事，他们在一天都让我们难受，所以我不和这个圈里的家伙来往。}

#{249}{}{Well then.  You might be useful after all.  Just keep in mind that it would be in your best interest to keep anything that is said to you, to yourself}
{249}{}{好吧，你可能还是有点用处的。但是你要记住，我们和你说的任何话你都要烂在肚子里。}

#{250}{}{He might. What kind of work were you looking for?}
{250}{}{也许吧，你想要做什么工作？}

#{251}{}{Do you need another guard?}
{251}{}{你们还要保镖吗？}

#{252}{}{Oh, nothing in particular.  I was just wondering.}
{252}{}{没什么特别想要的，我也在考虑。}

#{253}{}{Anything.  If it pays well, I'll do it.}
{253}{}{随便什么活儿。只要报酬高，我就干。}

#{254}{}{Anything that won't get me in trouble with the law.}
{254}{}{只要不是违法的就行。}

#{255}{}{Why don't you try the merchants.  I hear they pay reasonably well.}
{255}{}{那你可以找商人们去问问，他们开的工资高。}

#{256}{}{No, I think we're fine.  Have a nice day.}
{256}{}{不需要，那就这样吧，再见。}

#{257}{}{Now, that's what I like to hear.  I think we might be friends after all.  Let me show you down. Just keep in mind that it would be in your best interest to keep anything that is said to you, to yourself}
{257}{}{我爱听这句。我们也许可以交个朋友。我带你下去，但是你要记住，我们和你说的任何话你都要烂在肚子里。}

#{258}{}{Good.  Follow me, but keep in mind that it would be in your best interest to keep anything that is said
# to you, to yourself.}
{258}{}{很好，跟我来。但是你要记住，我们和你说的任何话你都要烂在肚子里。}

#{259}{}{Sure he did, goodbye... Oh, and by the way.  Don't ever lie to me again, I don't like it when people lie
# to me. Not many people live to hear this advise.}
{259}{}{没错，再见……对了，以后别和我扯谎，我最讨厌别人扯谎了，我通常不给别人这种衷告的。}

#{260}{}{A man of action. I like that, even if you are screwed up in the head.}
{260}{}{实干家。我喜欢，虽然你脑袋有点糊涂。}

#{261}{}{A woman of action. I like that. Even if you are screwed up in the head.}
{261}{}{实干家。我喜欢，虽然你脑袋有点糊涂。}

#{262}{}{Yeah, what do you want?  It better be good.}
{262}{}{你想要什么？最好是好事。}

#{263}{}{If you want to talk to me you better put your weapon away.}
{263}{}{你和我说话前最好把武器拿开。}

#{264}{}{Do you have a memory problem?  Put your weapon up if you're going to talk to me.}
{264}{}{你不长记性啊？和我说话前最好把武器拿开。}

#{265}{}{Your weapon?}
{265}{}{你的武器？}

#{266}{}{Not bad, not bad at all, you surprised me.  I didn't think you'd be that tough to beat. I'm normally a
# good judge in character, maybe you are what we're looking for.  Are you interested in a job?}
{266}{}{不错不错，你比我预期的还强。我之前没想到你这么能打。我一向看人很准，你应该就是我们需要的人，你想为我们做事吗？}

#{267}{}{Damn!  That was a good fight!  I haven't had a good match in a long time, and I don't remember when
# I was last bested by someone.  Good job!  How would you like a job?}
{267}{}{靠！打得不赖嘛！我好久没有这么带劲的对手了，更记不得什么时候被人击败过。好样的！你为我们做事如何？}

#{268}{}{Sure what's the job?}
{268}{}{当然，什么活儿？}

#{269}{}{No thanks.}
{269}{}{不，谢谢了。}

#{270}{}{I can't right now.  Let me get back to you.}
{270}{}{我现在不能。以后来找你吧。}

#{271}{}{It's not skag work. You'll need to do 'it' quick and clean.  The boss'll give you details, but it's
# more money than you'll make in a month working for the caravans.  I think you'll do just fine.}
{271}{}{这可不是小混混能做的事情。你要做的麻利干净。老板会和你细谈，报酬嘛会比干一个月商队保镖都挣得多，但是首先你要有能力。我觉得你应该能搞定。}

#{272}{}{Sounds good, lead on.}
{272}{}{很好，带路。}

#{273}{}{Hm, can I think about it?  I have a lot of other things going on.}
{273}{}{我能考虑一下吗？我还有好多事情要做。}

#{274}{}{ No, I don't think so.}
{274}{}{不了。}

#{275}{}{Sure, but let me know as soon as you can.  The sooner the job's done, the better.}
{275}{}{当然可以，你想好了就和我说，这活儿越早完成越好。}

#{276}{}{Well let me know if you change your mind.  I'd hate to see such talent wasted guarding caravans.}
{276}{}{好，如果你想好了就和我说，像你这样的人才去护镖太他妈浪费了。}

#{277}{}{Great, I think things will work out just fine.  Just remember what ever you hear down stairs doesn't
# surface.  Okay let's go.}
{277}{}{很好，我觉得你能够胜任的。记住，下楼后听到的话你不能往外说，好，我们走吧。}

#{278}{}{I understand that you are responsible for the death of a merchant and his wife. I don't know what
# quarrels you had with them and I don't care.}
{278}{}{我知道你要为一对商人夫妇的死负责，我不知道你和他们有什么过节，我也不管。}

#{279}{}{Who told you?}
{279}{}{谁告诉你的？}

#{280}{}{I don't know what you're talking about.}
{280}{}{我不知道你说什么。}

#{281}{}{Wak?}
{281}{}{啥？}

#{282}{}{That is not what you should be concerned about. No one makes a hit one anyone without our okay.
# I think it would be best if you left our city, while you still can.}
{282}{}{这不是你该关心的事情。谁都不能不问我们直接干掉其他人。你最好还是离开我们城市，要不然就没机会了。}

#{283}{}{I'm afraid you do and if you know what's best for you, you should leave this city while you still can.}
{283}{}{我觉得就是你干的，如果你聪明的话，赶紧离开这个城市，要不就走不了了。}

#{284}{}{I didn't think you wanted the job.  I hope it was just a misunderstanding. I'll pay you half, and be
# grateful that I'm giving you anything. 【Kane gives you 1500 hubbucks】}
{284}{}{我以为你不愿意干呢，大概是我误会你了。那就付你一半钱吧，你应该高兴，至少我们还会给你钱。【凯恩给了你1500块钱】}

#{285}{}{Thanks.}
{285}{}{多谢。}

#{286}{}{Oh sorry, I thought I had the job. Is there chance I can still work for you?}
{286}{}{抱歉，我以为我要了这份工作。你们还有其他活儿吗？}

#{287}{}{Give me the rest of the money now or you'll regret it!}
{287}{}{把剩下的一半给我，要不然你会后悔的。}

#{288}{}{Ghu?}
{288}{}{咕？}

#{289}{}{We'll see.  Downstairs, Decker wants to talk to you.}
{289}{}{好，你下楼和德克谈谈吧。}

#{290}{}{You will get nothing.}
{290}{}{想都别想。}

#{291}{}{I don't know what game you're playing but if you know what's best for you, you should leave this city
# while you still can.}
{291}{}{我不知道你葫芦里卖的什么药，但是你要是还知趣的话，赶紧趁早离开这个城市。}

#{292}{}{You said you didn't want the job.  I'm surprised you came back here.  You made a bad mistake to do it
# on your own.  I suggest you get out of town while you still can.}
{292}{}{你那会子说不要这个工作啊。谁知道你去做了呢。你犯了个很大的错误。我建议你趁早离开哈勃城。}

#{293}{}{I understand that you are responsible for the death of Jain, the High Priestess. I don't know what
# quarrels you had with her and I don't care, but we're very grateful nevertheless.
# (Kane gives you 1000 hubbucks)}
{293}{}{我知道你杀了高级牧师简恩。我不知道你和她有什么过节，但是我们还是很感激你。（凯恩给了你1000瓶盖）}

#{294}{}{Who told you?}
{294}{}{谁告诉你的？}

#{295}{}{I don't know what you're talking about.}
{295}{}{我不知道你说什么。}

#{296}{}{Wah?}
{296}{}{呼？}

#{297}{}{That is none of your concern and I'm afraid we can not deal with you.  You've violated our laws but
# because of the problem you eliminated for us we will not kill you, but I think you should leave.}
{297}{}{这你就不必过问了。抱歉我不能再和你打交道了，你违反了我们的法律，虽然你实际上帮了我们的忙，我们不会杀你，但你还是应该离开这里。}

#{298}{}{I'm afraid you do, lying can be a very unhealthy habit.  You've violated our laws but because of the
# problem you eliminated for us we will not kill you, but I think you should leave.}
{298}{}{恐怕就是你干的。撒谎会影响健康的。你违反了我们的法律，虽然你实际上帮了我们的忙，我们不会杀你，但你还是应该离开这里。}

#{299}{}{I don't know what game you're playing, but I'm not amused. You've violated our laws but because of the
# problem you eliminated for us we will not kill you, but I think you should leave.}
{299}{}{我不知道你葫芦里卖的什么药，我一点也不觉得好笑。你违反了我们的法律，虽然你实际上帮了我们的忙，我们不会杀你，但你还是应该离开这里。}

#{300}{}{Don't touch that door, if you want to live.  I'm the only one that can open that door.}
{300}{}{如果你还想活，别碰那个门，我是唯一有权开门的人。}

#{301}{}{The merchant and his wife live over to the west from here.  They're on the
# corner of Barter Street and Thunder Ave. in the Heights, he'll probably have guards. Try to be quiet about
# it and be sure you aren't seen, but if anyone does happen to see you make sure they don't live to tell
# anyone about it.  Once you've finished your little errand come back here. One more thing.  Don't even think
# about going to the police, that's the worst mistake you could ever make. If you can, try not attract their
# attention when doing your work, they can be quite a pain sometimes. 【Kane gives you 500 caps】}
{301}{}{那个商人和他老婆住在西边的高地，巴特街和桑德大道的交道口，很可能有保镖。悄悄地进去，别被人看见，如果被人看见了就灭他们的口。等你完事后回到我这里来。还有，别想着去警察那里告密，那将是一个大大的错误。尽量不要惊动警察，有时候他们确实很麻烦的。【凯恩给了你500个瓶盖】}

#{302}{}{Good work.  Here're your scripts for the completion of the first job. 【Kane hands you 2500 hubbucks】.}
{302}{}{干得好，这是剩下的2500个瓶盖。【凯恩给了你2500个瓶盖】}

#{303}{}{Nice work on the merchant.  I'm expecting the same results on your next job.  Here's your last payment
# for the first job and the first payment for the second. (Kane hands you 3500 Hubbucks). I'm sure you
# already know, but the Children of the Cathedral are down south just north of the water merchants.
# Again, no 'live' witnesses.}
{303}{}{上次的事做得很好，我期待你的这次表现。这里是你上个工作的赏钱，还有你现在这个任务的首付。【凯恩给了你的3500个瓶盖】你应知道，大教堂教徒的地盘在这里的南边，纯水商队的北边。还是那个规矩，不留目击活口。}

#{304}{}{Were you in a hurry to get out of here?  You didn't get your scripts.  Here's your money, initial
# payment and the completion bonus for the first job. (Kane hands you 3000 Hubbucks)}
{304}{}{你上次急着走做什么？你还没拿钱呢，这里是第一个工作给你的首付和余款。【凯恩给了你300个瓶盖】}

#{305}{}{Hey, good work!  You forgot to pick up your initial payment for the job, so here it is with the
# completion fee.  You've proven yourself to be quite useful. }
{305}{}{嘿，干的漂亮！你上次忘了拿首付款了，这次连同余款一起给你。你真是很能干的一个人。}

#{306}{}{ (Kane hands you 5000 hubbucks)}
{306}{}{【凯恩给了你5000个瓶盖】}

#{307}{}{And that's all you're going to get.  Now take off before you regret it.}
{307}{}{这是你所有的钱，赶紧走，否则你会后悔的。}

#{308}{}{Here's your starting pay. (Kane hands you 1000 Hubbucks) I'm sure you already know, but the Children
# of the Cathedral are south, just north of the water merchants.  Again, no 'live' witnesses.}
{308}{}{这是你这个任务的首付款。【凯恩给了你1000个瓶盖】你应该知道，大教堂教徒的地盘在这里的南边，纯水商队的北边。还是那个规矩，不留目击活口。}

#{309}{}{Damn, this is a lot of cash.  Decker really wanted that bitch dead, here're your scripts. (Kane gives
# you 4000 Hubbucks) You've proven yourself to be quite useful.}
{309}{}{靠，真是很多钱呐。德克真是要把那个婊子毙了，这是你的余款。【凯恩给了你4000个瓶盖】你还真是能干呢。}

#{310}{}{What the hell do you want?  I thought you didn't want to meet with Decker.}
{310}{}{你他妈的想做什么？我以为你不愿意见德克呢。}

#{311}{}{No I didn't, but can you give him a message for me?}
{311}{}{我当时不愿意，现在你能帮我给他传个话吗？}

#{312}{}{Yeah, I want to meet him, so I can blow a hole through his head!}
{312}{}{不，我现在想见他了。因为我要在他脑袋上开个眼儿。}

#{313}{}{I'm sorry, I misunderstood you.}
{313}{}{对不起，我当时误会了。}

#{314}{}{Damn straight, why would I ever want to meet with an idiot like him!}
{314}{}{我当时做的太对了。为什么要见一个像他那样的白痴呢。}

#{315}{}{Grug.}
{315}{}{咕咕。}

#{316}{}{Taa?}
{316}{}{达？}

#{317}{}{We don't hire skags.  Now leave before I become annoyed with you.}
{317}{}{我们不需要小混混，走开，别烦我了。}

#{318}{}{That depends on the message.}
{318}{}{那要看你传的是什么话了。}

#{319}{}{Tell him that he's a cowardly bastard for hiding in his little cave. If he wants to be a man he should
# try coming out into the real world.}
{319}{}{告诉他，他是一个只会猫在洞里的胆小鬼王八蛋。如果他还是男人的话，就给我滚出来见见外面的世界！}

#{320}{}{Tell him to start praying for a miracle, because he's going to need it when I get through with him.}
{320}{}{你让他准备祈祷吧，待会我摆平他的时候他用得着。}

#{321}{}{I forgot.}
{321}{}{我忘了。}

#{322}{}{Tell him that he's my idol, and I admire his work.}
{322}{}{告诉他他是我的偶像，我很敬仰他的为人处世。}

#{323}{}{Tell him that I'm going to do to him what he did to the last guy who ran this place!}
{323}{}{告诉他，我要取他而代之！}

#{324}{}{Are you now?  That should prove to be quite amusing.}
{324}{}{不是吧？你很搞笑啊。}

#{325}{}{You're an idiot.}
{325}{}{你这个笨蛋。}

#{326}{}{What are you some kind of freak?  Get the hell out of here!}
{326}{}{你是不是个疯子啊？滚！}

#{327}{}{Oh, I'll be sure to tell him.  I'm sure he will be very interested to hear that...  praying did you
# say? You have my 'word', he'll get the message.}
{327}{}{好，我会和他说，我想他听到……那什么来着，祈祷，是吧？他应该会很乐的。我保证我会给他传话的。}

#{328}{}{I thought I told you to get lost! My patience is wearing thin!  Are you going to tell me why you
# wanted to see Decker or not?}
{328}{}{我以前就让你滚蛋的！我的耐心是有限的！你到底找德克什么事？}

#{330}{}{I don't have to tell you anything.}
{330}{}{我不想和你说。}

#{331}{}{I'm sorry, I just wanted a job.}
{331}{}{对不起了，我就是想要一份工作。}

#{332}{}{I told you, it's a secret!}
{332}{}{我说过了，这是秘密！}

#{333}{}{Nope!}
{333}{}{不。}

#{334}{}{Ru?}
{334}{}{唔？}

#{335}{}{When you're off the drugs come and see me.}
{335}{}{少吸毒，清醒后再来这里见我。}

#{336}{}{I'll let you see him, but you better watch your mouth... after you?}
{336}{}{好吧，我带你去见他，但要看好你的嘴巴……明白？}

#{337}{}{No you don't.  Goodbye.}
{337}{}{不行，再见。}

#{338}{}{That's a secret you'll be taking to the grave.  Decker will never talk to a skag like you.}
{338}{}{你就把这个秘密带到坟里去吧。德克才不会和你这样的瘪三说话。}

#{339}{}{Then I suggest you leave.}
{339}{}{那你就走吧。}

#{340}{}{Yes?}
{340}{}{什么？}

#{341}{}{Lorenzo sent me for a job.}
{341}{}{罗伦佐让我来找工作。}

#{342}{}{Hi!}
{342}{}{嗨！}

#{343}{}{I want a job.}
{343}{}{我要工作。}

#{344}{}{Nothing, bye.}
{344}{}{没事，再见。}

#{345}{}{Kru.}
{345}{}{咕噜。}

#{346}{}{Hi.}
{346}{}{嗨！}

#{347}{}{How are you?}
{347}{}{你好啊。}

#{348}{}{Bye.}
{348}{}{再见。}

#{349}{}{Fine.}
{349}{}{好。}

#{350}{}{How are the kids?}
{350}{}{孩子们还好吧？}

#{351}{}{Nice day isn't it?}
{351}{}{天不错哈。}

#{352}{}{You're looking very handsome today.}
{352}{}{你今天看起来很帅啊。}

#{353}{}{Bye... (Kane Squints at you, as if he's trying to figure out what you're up to.)}
{353}{}{再见……【凯恩斜着眼睛盯着你，似乎要看出你的来意】}

#{354}{}{I suppose. (Kane starts to give you a strange look)}
{354}{}{也许吧。【凯恩怪怪地看着你】}

#{355}{}{Do you have the time?}
{355}{}{你有空吗？}

#{356}{}{Brahmin Shoe's Are Very Tasty.}
{356}{}{双头牛蹄很好吃的。}

#{357}{}{No... Did you want something? (Kane seems to be getting annoyed with you)}
{357}{}{没……你有事？【凯恩似乎有点对你不耐烦了】}

#{358}{}{Yes.}
{358}{}{是。}

#{359}{}{No.}
{359}{}{不是。}

#{360}{}{I think you need another drink there, buddy.}
{360}{}{老弟，你应该再喝一杯的。}

#{361}{}{I think you need another drink there, lady.}
{361}{}{小姐，你应该再喝几杯的。}

#{362}{}{(Kane waits for a few seconds) Well... what is it? (Kane looks very annoyed)}
{362}{}{【凯恩等了你一会】怎么……什么事？【很不耐烦的样子】}

#{363}{}{What is what?}
{363}{}{什么是什么？}

#{364}{}{I forgot.}
{364}{}{我忘了。}

#{365}{}{Oh, nothing.}
{365}{}{哦，没事。}

#{366}{}{(It almost seems like steam is coming out of Kane's ears and the vanes in his neck seem to visibly
# pulsate.) GET OUT! (A few seconds later you can hear again.) ... HERE!  YOU IDIOT!}
{366}{}{【凯恩似乎气得耳朵冒了烟，脖子上的青筋乱跳。】滚！！！！！【几秒钟后你的耳朵才恢复了听觉。】……你！你这个白痴！！！}

#{367}{}{(Kane Grinds his teeth and ignores you.)}
{367}{}{【凯恩咬着牙，不理你了】}

#{368}{}{You forgot? (sigh) Why doesn't that surprise me? (Shaking his head in disbelief.) Now... get OUT!}
{368}{}{你忘了？【叹气】我居然没生气？【难以置信地摇头。】那么……给我滚！！！！}

#{369}{}{(Kane looks at one of the guards and spins a finger around one ear.)}
{369}{}{【凯恩看着一个守卫，用手指在耳朵上画圈。】}

#{370}{}{What the hell are you talking about?}
{370}{}{你他娘的说些什么？}

#{371}{}{That's NOT the proper response!}
{371}{}{这不是很好的回答！}

#{372}{}{I see...  You are not one of them.}
{372}{}{我知道了……你不是和他们一伙的。}

#{373}{}{Response... to WHAT? (Kane looks confused and slightly annoyed.)}
{373}{}{回答……回答什么？【凯恩迷惑不解，有点不耐烦。】}

#{374}{}{To the secret password!}
{374}{}{回答密码啊！}

#{375}{}{I'm sorry, but I'm not allowed to talk about it.  Good bye.}
{375}{}{抱歉，我不能说这个。再见。}

#{376}{}{(Kane looks angry, you don't know why.) Get out of here, you crazy son of a bitch.}
{376}{}{【凯恩看起来很生气，你不知道为什么。】走开，你这个变态。}

#{377}{}{(Kane looks angry. You don't know why.) Get out of here, you crazy bitch.}
{377}{}{【凯恩看起来很生气，你不知道为什么。】走开，你这个臭娘们。}

#{378}{}{I told you to get out of here, you crazy son of a bitch.}
{378}{}{我说，走开，你这个变态。}

#{379}{}{I told you to get out of here, you crazy bitch.}
{379}{}{我说，走开，你这个臭娘们。}

#{380}{}{No, I guess not.  Now LEAVE. (He does not look amused.)}
{380}{}{不好。走开。【他好像也不是很乐的样子。】}

#{381}{}{I don't 'have' any kids!}
{381}{}{我没有孩子！}

#{382}{}{You seem to be a bit upset about that. Do you want to talk about it?}
{382}{}{你好像很不高兴啊，能说说苦衷吗？}

#{383}{}{Well you should, they make good servants.}
{383}{}{你应该生点的，可以呼来喝去的。}

#{384}{}{That's not what Mary said.}
{384}{}{玛丽说你生了。}

#{385}{}{ Really? That's strange...  Very strange...}
{385}{}{是吗，很奇怪啊……奇怪……}

#{386}{}{WHAT? YOU... I... NO!  I do 'not' want to talk about it.  Who the hell do you think you are?  Get the hell
# out of my sight.}
{386}{}{什么！？你……我……天！我不想说这个。你他妈的以为你是谁啊？马上给我消失！}

#{387}{}{I SAID, I do 'not' want to talk about.}
{387}{}{我说了，我不想谈这个。}

#{388}{}{Uh, yeah. Sure, buddy. What ever you say.}
{388}{}{好好好，老弟，随你怎么说了。}

#{389}{}{Uh, yeah. Sure, lady. What ever you say.}
{389}{}{好好好，小姐，随你怎么说了。}

#{390}{}{Do you have any to sell then?}
{390}{}{你有什么要卖的呢？}

#{391}{}{All right then.  Bye!}
{391}{}{好吧，再见了！}

#{392}{}{(Kane looks at one of his thugs and shrugs his shoulders)}
{392}{}{【凯恩看了看他的一名小弟，无奈的耸了下肩膀。】}

#{393}{}{No I DON'T!  Now, leave.}
{393}{}{我没有哇！走开。}

#{394}{}{Mary? I don't know a Mary... I don't have 'time' for this! I don't even know who you're talking about.
# If she want's money tell her to come talk to me herself!}
{394}{}{玛丽？我不认识什么玛丽……我没时间和你聊这个！我都不知道你要说什么。如果她要钱，让她自己来！}

#{395}{}{(You gain 100 experience for thoroughly pissing Kane off.)}
{395}{}{你成功地让凯恩抓狂了，获得了100点经验值。}

#{396}{}{(For a split second you think you see Kane Blush) That's... (he looks side to side) nice.  Now what did
# you want.}
{396}{}{【恍惚间，你似乎看到凯恩脸红了】这……【他四处张望】很好。你还要什么？}

#{397}{}{How about a date? }
{397}{}{要不我们去约会？}

#{398}{}{Oh, nothing.  Bye.}
{398}{}{没事，再见。}

#{399}{}{Yes, I mean no.  I mean I don't... I can't.  I... (Kane suddenly punches one of his guards across the jaw.)
# What are you grinning at! (Then he looks back at you.)  What are you still doing here!}
{399}{}{好啊，啊不，我是说不……我不能啊。我……【凯恩突然一拳打在身边的一个卫士下巴上。】笑什么笑！【他看着你。】你还在这里干什么？}

#{400}{}{(Kane ignores you) What do you want?}
{400}{}{【不理你】你要做什么？}

#{401}{}{How are the kids?}
{401}{}{你的孩子们还好吧？}

#{402}{}{Nice day isn't it?}
{402}{}{天气不错啊？}

#{403}{}{This way.}
{403}{}{这边走。}

#{404}{}{You know the way, let's go.}
{404}{}{你知道怎么走，我们走。}

#{405}{}{Open it up boys.}
{405}{}{打开。}

#{406}{}{All right.}
{406}{}{好。}

#{407}{}{Okay.}
{407}{}{好的。}

#{408}{}{You can want all you like, now take a hike.}
{408}{}{你要什么都行，现在你不要在这里。}

#{409}{}{Do you have any more jobs?}
{409}{}{你还有工作给我吗？}

#{410}{}{Hi!}
{410}{}{嗨！}

#{411}{}{Nothing, bye.}
{411}{}{没事，再见！}

#{412}{}{Acru!}
{412}{}{啊咕噜！}

#{413}{}{Hello again.}
{413}{}{你好。又见面了。}

#{414}{}{What?  You didn't have the nerve, right? (He whispers to you) Don't worry, you get used to it.  If
# he has guards, try waiting until they leave.  They have to eat some time right? If you can, distract them.
# Do what ever it takes, we don't accept failures.  Just do it and you'll get your money and then you can
# high tail it out of here.  Now... did you really need anything?}
{414}{}{什么？你没胆子下手？【他凑到你耳边】别紧张，你以后会习惯的。他有保镖的话，那就等到他们走开。他们总要吃饭吧。或者你把他们引开。总之你要使用各种办法，我们绝对不能失败。完事后，你就拿着钱销声匿迹啦。你还需要什么？}

#{415}{}{Why isn't 'it' done yet.  You better get it done.  I don't want to see you again until you have some
# good news, otherwise we'll have a problem.  You better not disappoint us.}
{415}{}{怎么还没有搞定。你要加紧了。下次要是没进展别来找我，要不然我们都会有麻烦的。你最好不要让我们失望。}

#{416}{}{That's it.  You've made your last mistake.  You better leave town now, if you don't want to stay here...
# six feet under.}
{416}{}{你犯了最大的错误，你最好赶紧离开哈勃，如果你还不想永远睡在这个城市的坟地里。}

#{417}{}{Well... are you going to do the job or not?  They're right over here (Kane points again at your PIPBoy
# town map display.)  You better hurry up, the boss is expecting this to be done soon.}
{417}{}{你到底想不想干这个工作？他们就住在那里。【凯恩指了指你的哔哔小子上的地图。】快点完成，老板都着急了。}

#{418}{}{WHAT THE HELL... (Kane looks around then whispers.)  What the hell are you doing here?  You better
# finish the other one off, and there better not be 'any' witnesses.}
{418}{}{你他娘的……【凯恩看了看四周，对你耳语道。】你他娘的在这里干什么？你赶快去把活儿搞定，不能被活人看见。}

#{419}{}{That's it.  You blew it.  Now you're going to have to pay for your mistakes.  I hope you aren't
# planing on spending the night here.}
{419}{}{看，你把事情办砸了。你应该要为此负责。你今天晚上不会还打算赖在城里吧？}

#{420}{}{You haven't finished your little job. (whispering) You know what's at stake here. You do it and
# you get rich and we're all happy.  Fail and no one's going to be happy.}
{420}{}{你还没把工作完成。【耳语】你知道这很重要的。搞定了，你发财，我们也爽。失败的话谁的日子都不好过。}

#{421}{}{If you're having trouble with your job, try and wait until she's alone.}
{421}{}{如果你有困难的话，等到她一个人在的时候，再下手。}

#{422}{}{You're running out of time and I'm running out of patience.}
{422}{}{你的时间不多了，我的耐心也不多了。}

#{423}{}{I won't do it.}
{423}{}{我不干了。}

#{424}{}{She'll be dead very soon.}
{424}{}{她马上就会死翘翘的。}

#{425}{}{Huh.}
{425}{}{呼。}

#{426}{}{You won't? Now that's a shame.  We can't have people giving their word and then breaking it. I'm sorry
# we couldn't work together.  Have a 'nice' day.}
{426}{}{不干了？真狗屎！我们不能让一个对我们食言的家伙好过，你好好“享受”吧！}

#{427}{}{Okay!  I'll do the damn job.  But you better have the money when I'm done with it.}
{427}{}{好！我去完成这个工作。你最好把钱准备好。}

#{428}{}{Thanks.}
{428}{}{多谢。}

#{429}{}{Oh, I'll have it.  Don't worry.}
{429}{}{哦，我会的，别担心。}

#{430}{}{Still alive I see!  Well, you must not have made any new friends recently.  I hope you keep an eye out
# for them.}
{430}{}{你还活着呢！最近没有人跟你交朋友吧，你最好当点心。}

#{431}{}{(Kane looks quite smug.  He just stands there with and evil grin.)}
{431}{}{【凯恩看起来很得意，他站在那里，不坏好意的笑着。】}

#{432}{}{Well!  I am very surprised to see you alive. You survived, that's very impressive.  I guess I'll let
# you live, you are worth of that much.  Now hit the road.}
{432}{}{你还活着呢，你活下来了，真是了不起。我放你一马吧，你还是个人才，马上给我走。}

#{433}{}{Don't even think of it.}
{433}{}{想都别想。}

#{434}{}{I never miss.}
{434}{}{我从不失手的。}

#{435}{}{I'm allowing you to live, be grateful.}
{435}{}{我饶你一命，你应该感激的。}

#{436}{}{I don't think you want to test me.}
{436}{}{你应该不会想和我试试吧。}

#{437}{}{"I hope you aren't planning on using that, for your sake.}
{437}{}{为了你好，别动那个。}

#{438}{}{You should leave.}
{438}{}{你该走了。}

#{439}{}{Don't be stupid.}
{439}{}{别犯傻。}

#{440}{}{You'll regret it.}
{440}{}{你会后悔的。}

#{441}{}{You're either brave or 'very' stupid to show your face here but don't worry, we'll stop in sometime and
# say 'hello'.}
{441}{}{你要么就是胆子暴大，要么就是十足的傻瓜，居然敢在这里露面，别担心，我们还是可以互相“问问好”的。}

#{442}{}{(Kane just glares at you.)}
{442}{}{【凯恩瞪着你。】}

#{443}{}{You survived my good bye party... I don't know how you did it, I must have underestimated you.  Leave
# and you might live.}
{443}{}{你居然活了下来……我不知道你怎么活过来的，我低估你了，走吧，饶你不死。}

#{444}{}{(Kane ignores you, but has his weapon ready to shoot.)}
{444}{}{【凯恩不理你，但武器处于戒备状态。】}

#{445}{}{All right!  Out you go!}
{445}{}{好吧！你走吧！}

#{446}{}{I won't tell you again.  Get the hell out.}
{446}{}{我不会再说第二遍，滚！}

#{447}{}{I warned you. Okay guys, let 'em have it!}
{447}{}{我警告过你了，弟兄们，拿下他！}

#{448}{}{I warned you. Okay guys, let 'er have it!}
{448}{}{我警告过你了，弟兄们，拿下她！}

#{449}{}{Don't bother me, get to work.  You've got a job to do, and you better do it.}
{449}{}{别烦我，干活去。你有事情要做，赶紧把它做好。}

#{450}{}{Would you get on with it.  I already told you what to do.  Just do it.}
{450}{}{赶紧去办，我告诉你办法了，去做吧。}

#{451}{}{I know you finished the damn job.  You don't have to tell me.  Decker's the one you need to talk to.}
{451}{}{我知道你搞定了，不用和我汇报了，你和德克说去吧。}

#{452}{}{I told you to talk to Decker!}
{452}{}{我让你去和德克说！}

#{453}{}{(Kane gives you a deadly look.) Well then... I'll try to get you in to see him sometime soon.  I'll be
# sure to show you to him 'piece' by 'piece'.}
{453}{}{【凯恩凶恶地看了你一眼。】好吧……我马上就带你去见他，不过是把你撕成碎片之后。}

#{454}{}{I'm sorry you feel that way.  I hope you 'enjoy' the rest of your stay here in our wonderful city. }
{454}{}{你这样就不对了。我希望你能好好享受在城里的最后时光。}

#{455}{}{(Kane ignores you.)}
{455}{}{【凯恩不理你。】}

#{456}{}{(Kane stares at you for a few seconds) All right.  I'll give you one last chance to see him.  Follow me.}
{456}{}{【凯恩瞪了你几秒钟】好吧，我给你最后一次机会，带你去见他。跟我来。}

#{457}{}{(Kane stares at you for a few seconds) You missed your chance.  Beat it.}
{457}{}{【凯恩瞪了你几秒钟】我上次已经给你机会了，滚！}

#{458}{}{What the hell are you doing back here?!?!  You must be an even bigger idiot than I thought.  I knew Decker
# shouldn't have hired an unknown.}
{458}{}{你还回到这里干什么！？！？你比我想象中还要笨呐。我早就知道不该雇用不认识的家伙。}

#{459}{}{What are you talking about?}
{459}{}{你说什么呢？}

#{460}{}{Huh?}
{460}{}{呼？}

#{461}{}{【Kane lowers his voice】  You cocked up the mission, you moron!  You were supposed to kill both of the Hightowers, not wound them for
# Christ sake!  The second you left the Heights they ran off with their guards.  Believe me, they didn't waste time packing either.
#  God knows where they are now!}
{461}{}{【凯恩压低了声音】你把事情办砸了，笨蛋！你应该把夫妻俩都干掉，而不是让他们受点伤，天那！你一离开高地，他们就和保镖一起跑了，还没忘记收拾行李，现在天才知道他们在哪里！}

#{462}{}{Well, what can I say?  I'm sorry.}
{462}{}{我说什么好呢，对不起。}

#{463}{}{Ug.  SOrrY.}
{463}{}{唔，对不起。}

#{464}{}{Sorry doesn't cut it.  You've put Decker at an unacceptable risk.  You can consider yourself an enemy of the Underground
# from now on.  I don't ever want to see your face in here again.}
{464}{}{对不起有个屁用！你让德克冒了多大的险。你以后就是地下黑社会的敌人了。我不想在这里再看到你这张破脸！}

#{465}{}{You cannot get through the door with Kane here.}
{465}{}{凯恩挡住了门。}
