#{100}{}{You see a slender young woman with a smudged face and dark clothing.}
{100}{}{你看见一个身着黑衣、脸上满是污垢的女孩。}

#{101}{}{You see Katja, the thief.}
{101}{}{你看见卡佳，她是个小偷。}

#{102}{}{You're not from around here. Who're you?}
{102}{}{你不是这里人，你叫什么？}


# TRANSLATION NOTE
# The player-character's name is inserted between lines 103 and 104 by the code.

#{103}{}{The name's }
{103}{}{我叫}

#{104}{}{.}
{104}{}{。}

#{105}{}{I'm a traveler.}
{105}{}{我是个旅行者。}

#{106}{}{I might ask the same of you.}
{106}{}{我也想问你同样的问题。}

#{107}{}{And what, may I ask, are you doing in the Boneyards?}
{107}{}{你能说说你在晒骨场干什么么？}

#{108}{}{You ask a lot of questions.}
{108}{}{你的问题很多啊。}

#{109}{}{First you tell me who you are.}
{109}{}{你先告诉我你是谁。}

#{110}{}{I'm just an explorer.}
{110}{}{我只是一个闲逛的人。}

#{111}{}{I'm looking for a replacement water chip for my Vault.}
{111}{}{我想为我的避难所找到净水芯片。}

#{112}{}{You learn to be careful out here. So what are you doing here?}
{112}{}{你在这里要小心点。你是干什么的？}

#{113}{}{All right, fair enough. I'm called Katja. What's it matter to you?}
{113}{}{好啦，我叫卡佳，你为什么要知道？}

#{114}{}{Why so hostile?}
{114}{}{这么敌意做什么？}

#{115}{}{Hey, if you're going to be rude about it, then I'll see you later.}
{115}{}{你再这么粗鲁，我可走了。}

#{116}{}{I'm looking for information. Can you help?}
{116}{}{我想打听点消息，你能帮我么？}

#{117}{}{You might, but you're on my home turf, not vice-versa. So put up or
# shut up.}
{117}{}{随你，你在我的地盘上，而不是我在你的地盘上，所以要么说实话，要么就闭嘴。}

#{118}{}{It's not important, I'm just a traveler. I need some information.}
{118}{}{我是谁不重要。我只是一个旅行者，我需要信息。}

#{119}{}{A water purification chip? Sorry, don't know anything about that. Don't
# see much of that kind of tech here in the Boneyards, except maybe the stuff
# Miles works on.}
{119}{}{净水芯片？抱歉，我对此一无所知。晒骨场没有什么高科技，除了麦尔斯，他经常捣腾一些高级货。}

#{120}{}{Well, thanks anyhow.}
{120}{}{哦，谢谢。}

#{121}{}{Miles? Where can I find him, and could he help?}
{121}{}{麦尔斯？我怎么找到他？他会帮我么？}

#{122}{}{Can you tell me more about the Boneyards, then?}
{122}{}{那你再和我说说晒骨场的事情吧。}

#{123}{}{Just a traveler. I've heard that one before. Nobody comes to the
# Boneyard except those Hub merchants and people looking for a quick death at the
# hands of the gangs. What are you really here for?}
{123}{}{只是一个旅行者？这种话我也听过不少了。除了来混黑道想死得快的人和哈勃城的商人，没人愿意来晒骨场。你到底是来做什么的？}

#{124}{}{You're right. I'm looking for a water purification chip.}
{124}{}{你说的不错，我是来找净水芯片的。}

#{125}{}{I don't need to tell you anything.}
{125}{}{我无可奉告。}

#{126}{}{Damn straight. But that's a two-way street.}
{126}{}{太对了，我来去这里不必你管吧。}

#{127}{}{Maybe. You definitely aren't one of those gangland shiv-shovers. What
# do you want?}
{127}{}{也许吧，你显然不是那些地痞小混混的样子，你想做什么？}

#{128}{}{I'm looking for a water purification chip.}
{128}{}{我在找净水芯片。}

#{129}{}{I need more information about the Boneyard.}
{129}{}{我还想知道些晒骨场的事情。}

#{130}{}{I need to know about the area around this city.}
{130}{}{我想打听城里的一些地方。}

#{131}{}{What can you tell me about the Blades?}
{131}{}{你能和我说说利刃帮吗？}

#{132}{}{What can you tell me about the Rippers?}
{132}{}{你能说说电锯党吗？}

#{133}{}{What can you tell me about the Gun Runners?}
{133}{}{你能和我说说军火商的事情吗？}

#{134}{}{What can you tell me about the Followers?}
{134}{}{你能说说那些末世论者的事情么？}

#{135}{}{What can you tell me about Adytum?}
{135}{}{你能说说内城区的事情么？}

#{136}{}{Well, it was nice chatting. Gotta go.}
{136}{}{和你聊的很愉快，再见。}

#{137}{}{Miles lives in Adytum. He's a scientist, mostly working with chemistry.
# If anyone could scrounge up a water chip or make a replacement, it would be him.}
{137}{}{麦尔斯住在内城区，他是个钻研化学的科学家。如果城里有人能制造净水芯片，那只有他了。}

#{138}{}{Thanks very much.}
{138}{}{太感谢了。}

#{139}{}{Adytum is my original home. A little too boring for me, though. It's a
# fenced-off and self-sufficient town in the south end of the Boneyard, but not as
# far as the Cathedral. We trade sometimes with the Hub.}
{139}{}{内城区是我的老家，虽然有点闷。自我隔绝，自给自足，它处在晒骨场的南区，但是要在大教堂北边一点。我们也和哈勃城做些买卖。}

#{140}{}{I've dealt with them before. They're not too bad, as far as gangs go.
# They have a hide-out in an old club, with some outposts. If you're careful you
# might even be able to get some of them to talk.}
{140}{}{我和他们打过交道。做为一个帮派，他们还不算太坏。他们的总坛在一个旧的夜总会，周围哨所不少。如果你谨慎点，也许还能和他们说上话。}

#{141}{}{The Rippers are just plain ferocious. They're an inbred bunch that
# delights in torture and murder. I stay away from them, and you should, too.
# They actually put fuckin' land mines around their fortress.}
{141}{}{电锯党就是一群混球。他们是热衷于杀戮和折磨的杂种。我尽量会离他们远一点，你也最好别惹他们。他们居然还在总部周围布上了可恶的地雷。}

#{142}{}{The Gun Runners used to be a real gang, but they went soft. They started
# setting up a deal where they trade weapons that they get from their victims or buy
# from the Hub. Since nobody here is up for the trip to the Hub personally, they do
# pretty good business, even though their prices are high.}
{142}{}{军火商以前也是一个黑帮，后来洗手不干了。他们用抢来的或者是从哈勃买来的枪械作买卖。这里没人愿意自己单独去哈勃城，所以他们的货很抢手，就是价格高了点。}

#{143}{}{The Followers of the Apocalypse are a group of peace-preachers who live in
# a large library near the heart of the Boneyard. Why they haven't been wiped out
# yet I can't say. They are lousy combatants and have no understanding of the real
# world, but other than that they are polite and well-educated.}
{143}{}{末世论者是一帮和平倡导者，他们住在晒骨场中心区的一所大图书馆里。我不知道为什么一直没有帮派会去铲除他们。他们是无畏的战士，对现实社会没有认同。但是除此之外，他们还算友好，比较有教养。}

#{144}{}{The Boneyard is a pretty hostile place. I've never had the opportunity to
# leave, though I suppose I'd take it. Let's see . . . just south of here you have
# the Cathedral. There's some sort of cult there, but I stay away from them.
# Something sinister is going on there. Also, I've heard about the trading center
# called the Hub, and caravans occasionally show up, but I've never been there.}
{144}{}{晒骨场是一个充满敌意的地方。我一直没有机会离开这里，大概以后会有机会吧。嗯……再往南走就是大教堂了。那里有一群教众，我宁可离他们远一点。邪恶的东西在那里滋生。我还知道贸易中心哈勃城，经常有那里的商队来这里，但我从来没去过哈勃城。}

#{145}{}{I don't plan to stay in this place too much longer, myself.}
{145}{}{我也不打算一个人在这个城市长呆。}

#{146}{}{Thanks for the information.}
{146}{}{谢谢你的信息。}

#{147}{}{Can you tell me some more?}
{147}{}{你还知道些什么？}

#{148}{}{No kidding. If you're looking for another hand, I'll sign on. Better than
# spending the rest of my existence in this hellhole, right?}
{148}{}{说实话，如果你需要一个帮手，我怎么样？至少我不用在这里继续鬼混下去了，如何？}

#{149}{}{You're a welcome addition, but the desert's not much more fun.}
{149}{}{我很欢迎你，但是荒漠里可没有什么好玩的。}

#{150}{}{Don't worry about it. Thanks anyhow.}
{150}{}{你不用操这个心了，多谢。}

#{151}{}{Can I ask some more questions first?}
{151}{}{那我能先问几个问题么？}

#{152}{}{This area's overrun with the three gangs - the Blades, Rippers, and Gun
# Runners - as well as serving as home for the Followers and for my own home,
# Adytum.}
{152}{}{这个地区有三大帮派－－利刃帮，电锯党和军火商－－还有末世论者以及我的老家内城区。}

#{153}{}{All right, looks like we've got a little ass-kicking to do!}
{153}{}{很好，似乎有不少烂人可以消遣呢。}

#{154}{}{Look, 90% of the people in this city fall into one or more of three
# categories - rapists, murderers, or thieves. I'm a thief and you actually seem
# polite, so that makes me wonder, okay? Call it a survival instinct.}
{154}{}{要知道，城里百分之九十的人都是属于色情狂、杀人犯和小偷三者之一，甚至是多种行当都干。我是个小偷，你还算比较客气，所以我才会有些想法，明白？这叫做生存直觉。}

#{155}{}{Sorry to step on your feet then. I guess I'll just go the hell away.}
{155}{}{抱歉打扰你了，我要走了。}

#{156}{}{Well, can I at least ask a few questions?}
{156}{}{那我还能再问几个小小的问题么？}

#{157}{}{I'm not from around here, so I don't think I count.}
{157}{}{我不是这里的人，所以我不算。}

#{158}{}{Okay, but make it quick.}
{158}{}{好吧，那快点说。}

#{159}{}{Huh. Guess I can't argue with that logic. So waddya want?}
{159}{}{呵，我不知道怎么和你辩，你想做什么？}

#{160}{}{Can I ask you some questions?}
{160}{}{我能问几个问题么？}

#{161}{}{I'm looking for a water purification chip. Can you help?}
{161}{}{我在找净水芯片，你能帮我么？}

#{162}{}{Thanks anyhow, but I'll be going now.}
{162}{}{谢谢你了。我走了。}

#{163}{}{What's up?}
{163}{}{什么事？}

#{164}{}{Can you give this lock a try?}
{164}{}{你能解开这个缩么？}

#{165}{}{Can you take a look at this trap?}
{165}{}{你能看看这个陷阱么？}

#{166}{}{Any advice?}
{166}{}{有什么建议么？}

#{167}{}{Thanks for your help. You can go now.}
{167}{}{谢谢你的帮助，我走了。}

#{168}{}{Nothing yet. But stay tuned.}
{168}{}{没事，小心点。}

#{169}{}{You again? What're you back for now?}
{169}{}{又是你？你还要做什么？}

#{170}{}{Just wanted to stop and say hello.}
{170}{}{只是过来问候你一声。}

#{171}{}{I have a few more questions if you can spare some time.}
{171}{}{如果你有时间的话，我还有几个问题。}

#{172}{}{It's unlocked.}
{172}{}{锁开了。}

#{173}{}{There's something funny about that bookcase on the east wall. Looks like
# it's hiding something.}
{173}{}{东墙的书橱有点怪，好像里面藏着什么。}

#{174}{}{Put your weapons away.}
{174}{}{把你的武器收起来。}

#{175}{}{I hate dogs.}
{175}{}{我讨厌狗。}

#{176}{}{That food smells good.}
{176}{}{这个食物闻起来不错。}

#{177}{}{What kinds of combat skills do you have?}
{177}{}{你会什么战斗技能？}

#{178}{}{I learned how to be a scrapper from my time in the Boneyard. I'm good with
# knives and submachine guns. My favorite is throwing knives, of course.}
{178}{}{我在晒骨场混的时候学习了打拳，我还会用刀和微冲。我最在行的是飞刀。}

#{179}{}{All right, although I don't feel right without a good knife.}
{179}{}{好吧，尽管我没了好刀浑身不自在。}

#{180}{}{You gain 200 experience points for picking up Katja, the Boneyard scav.}
{180}{}{你让晒骨场的盗贼卡佳加入了你的队伍，获得了２００点经验值。}

#{181}{}{What do you want now?}
{181}{}{你想做什么？}

#{182}{}{I changed my mind. I'd still like your help.}
{182}{}{我改主意了，我需要你的帮忙。}

#{183}{}{Nothing. Never mind.}
{183}{}{没事。}

#{184}{}{I'm really starting to hate this place.}
{184}{}{我真的开始讨厌这个地方了。}

#{185}{}{Wow. I wish I had a hot dog and a really long stick.}
{185}{}{哇，我希望我有个热狗，再加一个很长的棒子。}

#{186}{}{Oh, ugh. I think I'm gonna be sick.}
{186}{}{哦，我要恶心坏了。}

#{187}{}{Hey, that wall with the tear in the plaster looks like it could move.}
{187}{}{嘿，那面墙上的灰泥有缝，似乎能活动呢。}

#{188}{}{Watch out for Deathclaws!}
{188}{}{小心死亡爪。}

#{189}{}{Hubba hubba!}
{189}{}{对呀对呀。}

#{190}{}{Leave!}
{190}{}{走开！}

#{191}{}{I'm sorry but I just don't understand you.  Good bye.}
{191}{}{抱歉，我不明白你的意思，再见。}


#
# Katja tell-me-abouts
#

#{980}{}{I don't know anything about that.}
{980}{}{我什么也不知道。}

#{981}{}{I can't really say I have heard of that.}
{981}{}{我好像没听说过。}

#{982}{}{No, I have not heard of that.}
{982}{}{没听说过。}


{1000}{}{Water}
{1001}{}{Boneyard}
{1002}{}{War}
{1003}{}{Adytum}
{1004}{}{Followers}
{1005}{}{Cathedral}
{1006}{}{Chip}
{1007}{}{Garl}
{1008}{}{Master}
{1009}{}{Unity}
{1010}{}{Set}
{1011}{}{Watershed}
{1012}{}{Necropolis}
{1013}{}{Hall}
{1014}{}{Library}
{1015}{}{Overseer}
{1016}{}{Medic}
{1017}{}{Healing}
{1018}{}{Vault}
{1019}{}{Vault-13}
{1020}{}{Vault13}
{1021}{}{Killian}
{1022}{}{Gizmo}
{1023}{}{Junktown}
{1024}{}{Shady}
{1025}{}{Sands}
{1026}{}{Hub}
{1027}{}{Casino}
{1028}{}{Store}
{1029}{}{Deathclaw}
{1030}{}{Exodus}
{1031}{}{Initiates}
{1032}{}{Paladins}
{1033}{}{Scribes}
{1034}{}{Children}
{1036}{}{Brotherhood}
{1037}{}{Vats}
{1038}{}{Military}
{1039}{}{Base}
{1041}{}{Apocalypse}
{1042}{}{Mutants}
{1043}{}{Morpheus}
{1044}{}{Khans}
{1045}{}{Tandi}
{1046}{}{Alya}
{1047}{}{Diana}
{1048}{}{Gwen}
{1049}{}{Petrox}
{1050}{}{Tolya}
{1051}{}{Booze}
{1052}{}{Drugs}
{1053}{}{Seth}
{1054}{}{Aradesh}
{1055}{}{Razlo}
{1056}{}{Zimmerman}
{1057}{}{Regulators}
{1058}{}{Scavs}
{1059}{}{Blades}
{1060}{}{Nicole}
{1061}{}{Lieutenant}
{1062}{}{Psychics}
{1063}{}{Experiments}
{1064}{}{Police}
{1065}{}{Merchants}

#{1100}{}{I don't know where you could find such a relic of old technology.}
{1100}{}{我也不知道在哪里找这个古老科技物件。}

#{1101}{}{The Angel's Boneyard is all that's left of the old city of Los Angeles.
# Mostly divided among warring factions, these days.}
{1101}{}{晒骨场是洛杉矶旧称的遗址，现在四分五裂的，各自为战。}

#{1102}{}{The War brought misery and death all over the world. I sure hope that
# something like that never happens again. But from what I've seen, there's not
# much hope for humanity.}
{1102}{}{战争给全世界带来了死亡和痛苦。我希望这种事情不要再发生了。在我看来，人类是没什么希望了。}

#{1103}{}{Adytum used to be my home, but those people are just too paranoid and
# reclusive. They'll never survive by withdrawing from the world.}
{1103}{}{内城区以前是我的家，但是那里的人疯疯癫癫的，自我隔绝。他们以为隐居能躲离世界，他们错了。}

#{1104}{}{The Followers of the Apocalypse preach peace and tolerance. Too bad it
# just doesn't cut it in this world.}
{1104}{}{末世论者们宣扬和平和忍耐，可惜在这样的世界，这些东西早就不流行了。}

#{1105}{}{The Cathedral is a monumental structure south of Adytum by about a day's
# walk or so. It's run by a weird cult that worships some sort of dark god.}
{1105}{}{从内城区往南方走一天就可以到大教堂，那里似乎有一个崇拜黑暗之神的邪教。}

#{1106}{}{I don't know where you could find such a relic of old technology.}
{1106}{}{我也不知道在哪里找这个古老科技物件。}

#{1107}{}{I don't know any more about that than you do.}
{1107}{}{我知道的还不如你多。}

#{1108}{}{I don't know any more about that than you do.}
{1108}{}{我知道的还不如你多。}

#{1109}{}{I don't know any more about that than you do.}
{1109}{}{我知道的还不如你多。}

#{1110}{}{I don't know any more about that than you do.}
{1110}{}{我知道的还不如你多。}

#{1111}{}{I don't know any more about that than you do.}
{1111}{}{我知道的还不如你多。}

#{1112}{}{What, the city of the dead? Isn't that a myth?}
{1112}{}{我知道的还不如你多。}

#{1113}{}{I don't know any more about that than you do.}
{1113}{}{我知道的还不如你多。}

#{1114}{}{I don't know any more about that than you do.}
{1114}{}{我知道的还不如你多。}

#{1115}{}{I don't know any more about that than you do.}
{1115}{}{我知道的还不如你多。}

#{1116}{}{The Followers have a medic on hand at all times.}
{1116}{}{我知道的还不如你多。}

#{1117}{}{You should go see the medic at the Followers if you need healing.}
{1117}{}{如果受伤了，你应该去找末世论者的医生看看。}

#{1118}{}{Weren't the Vaults like big underground shelters?}
{1118}{}{避难所就像是地下的掩体啊。}

#{1119}{}{Weren't the Vaults like big underground shelters?}
{1119}{}{避难所就像是地下的掩体啊。}

#{1120}{}{Weren't the Vaults like big underground shelters?}
{1120}{}{避难所就像是地下的掩体啊。}

#{1121}{}{I don't know any more about that than you do.}
{1121}{}{我知道的还不如你多。}

#{1122}{}{I don't know any more about that than you do.}
{1122}{}{我知道的还不如你多。}

#{1123}{}{Um, small town north of the Hub, I think.}
{1123}{}{我想那是哈勃城北边的镇子。}

#{1124}{}{Shady what?}
{1124}{}{沙什么？}

#{1125}{}{Shady Sands? Never heard of it.}
{1125}{}{沙荫镇？没听说过。}

#{1126}{}{The Hub's a huge trading center, with all sorts of stores and merchants.}
{1126}{}{哈勃城是大型交易中心，有各种店铺和商家。}

#{1127}{}{I don't know any more about that than you do.}
{1127}{}{我知道的还不如你多。}

#{1128}{}{The Gun Runners sell stuff, and there's a store in Adytum.}
{1128}{}{军火商卖东西，在内城区有店铺。}

#{1129}{}{Ugh! The Deathclaws are all over in the Boneyard. I'd rather not even
# think about them. Huge and aptly named.}
{1129}{}{恶！这些死亡爪在晒骨场到处都有。我想都不愿意想它们。身形巨大，“人”如其名。}

#{1130}{}{I don't know any more about that than you do.}
{1130}{}{我知道的还不如你多。}

#{1131}{}{I don't know any more about that than you do.}
{1131}{}{我知道的还不如你多。}

#{1132}{}{I don't know any more about that than you do.}
{1132}{}{我知道的还不如你多。}

#{1133}{}{I don't know any more about that than you do.}
{1133}{}{我知道的还不如你多。}

#{1134}{}{I don't like kids.}
{1134}{}{我不喜欢小孩。}

#{1136}{}{I hear they're some sort of high-tech monks.}
{1136}{}{听说他们是高科技的修道士？}

#{1137}{}{I don't know any more about that than you do.}
{1137}{}{我知道的还不如你多。}

#{1138}{}{I don't know any more about that than you do.}
{1138}{}{我知道的还不如你多。}

#{1139}{}{I suppose there must be some remnants of the old military.}
{1139}{}{也许那里有古代军事基地的遗址？}

#{1141}{}{You mean the big war? Wow, you sure have led a sheltered life if you
# don't know anything about that.}
{1141}{}{你说的是世界大战吧？如果不知道的话，那你真是在掩体里过的上半辈子。}

#{1142}{}{I've seen a rat with three eyes once. That's about all I know about
# mutants.}
{1142}{}{我看见过三只眼睛的老鼠。这是我所知的唯一变种。}

#{1143}{}{I think he's a High Priest for the Cathedral, or something.}
{1143}{}{我觉得他是大教堂的高级牧师，还是其他什么职位来着。}

#{1144}{}{I don't know any more about that than you do.}
{1144}{}{我知道的还不如你多。}

#{1145}{}{I don't know any more about that than you do.}
{1145}{}{我知道的还不如你多。}

#{1146}{}{I don't know any more about that than you do.}
{1146}{}{我知道的还不如你多。}

#{1147}{}{I don't know any more about that than you do.}
{1147}{}{我知道的还不如你多。}

#{1148}{}{I don't know any more about that than you do.}
{1148}{}{我知道的还不如你多。}

#{1149}{}{I don't know any more about that than you do.}
{1149}{}{我知道的还不如你多。}

#{1150}{}{I don't know any more about that than you do.}
{1150}{}{我知道的还不如你多。}

#{1151}{}{No thanks.}
{1151}{}{不，谢谢。}

#{1152}{}{Ugh. No, I'd rather not. I watched a friend die from an overdose of
# Psycho once. Not pretty.}
{1152}{}{恶，不，我不用那个。我亲眼看到我的朋友过量服用疯狂药而死掉。不好玩的。}

#{1153}{}{I don't know any more about that than you do.}
{1153}{}{我知道的还不如你多。}

#{1154}{}{I don't know any more about that than you do.}
{1154}{}{我知道的还不如你多。}

#{1155}{}{I don't know any more about that than you do.}
{1155}{}{我知道的还不如你多。}

#{1156}{}{He's the mayor of Adytum. A fair, if somewhat vacillating, man.}
{1156}{}{他是内城区的市长。人还行，就是有点优柔寡断。}

#{1157}{}{They watch over Adytum and keep it under control.}
{1157}{}{他们管理内城区，牢牢地控制着那里。}

#{1158}{}{I used to be a scav. We'd go out at night and try to find useful
# stuff in the ruins of the Boneyard. Very dangerous job. I got sick of Adytum,
# though.}
{1158}{}{我以前就是拾荒的，我们晚上出动去晒骨场遗迹翻东西，很危险的。但是我觉得内城区太无聊了。}

#{1159}{}{They're a group of cast-offs who live outside of Adytum.}
{1159}{}{他们是内城区外面的流放者。}

#{1160}{}{She's the leader of the Followers. An intelligent woman, and good
# hearted, too.}
{1160}{}{她是末世论者的头儿，很聪明的女人，心很好。}

#{1161}{}{I don't know any more about that than you do.}
{1161}{}{我知道的还不如你多。}

#{1162}{}{I get "feminine intuition" occasionally, if that's what you mean.}
{1162}{}{有时候我有“女人的直觉”，大概就是这个意思吧。}

#{1163}{}{I don't know any more about that than you do.}
{1163}{}{我知道的还不如你多。}

#{1164}{}{I don't know any more about that than you do.}
{1164}{}{我知道的还不如你多。}

#{1165}{}{Merchants trade with Adytum occasionally, and sell to the Gun Runners.}
{1165}{}{商人有时候会来内城区做生意，主要是卖货物给军火商。}


#{1999}{}{I'm getting pretty good at this!}
{1999}{}{我突然感觉很high啊！}

#{2000}{}{Let's discuss our combat tactics.}
{2000}{}{来谈谈我们的战斗策略。}

#{2001}{}{I'm listening.}
{2001}{}{我在听。}

#{2010}{}{Draw your best weapon.}
{2010}{}{装备最好的武器。}

#{2011}{}{Change your armour.}
{2011}{}{更换你的装甲。}                       # changed by WG

#{2012}{}{Prefer ranged combat against close.}
{2012}{}{尽量用远程攻击。}

#{2013}{}{Prefer close combat against ranged.}
{2013}{}{尽量用肉搏攻击。}

#{2014}{}{Choose distance on your own.}
{2014}{}{自行决定和我的距离。}

#{2015}{}{That's all for now.}
{2015}{}{就这样了。}

#{2100}{}{Whatever you say.}
{2100}{}{听你的喽。}