
{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Keri.}
{100}{}{你看见凯利。}

#{101}{}{Who the hell are you?  If you want a job you'll need to talk to Demetre.}
{101}{}{你它妈的是谁？找工作去和戴米德说！}

#{102}{}{I said to talk to my dad if you want a job, not me.}
{102}{}{我说过了，找工作的话去和我爸爸说，别烦我。}

#{103}{}{So, that old bastard gave you the okay to work for us, eh?  Well you must be one tough bitch.
# I'm impressed, but we'll see how you do.  We leave only twice a month, on
# the 3rd and 17th.  Can you handle that? We go to all the local hot spots:  the Brotherhood of Steel,
# Junktown, Necropolis, and the Boneyard.}
{103}{}{老不死的居然同意你来干活了？你他妈一定是个悍妇。我很欣赏，但要看你的表现了。我们每个月出发两次，3号和17号，你能来吧。我们主要去四个地方：钢铁兄弟会、迦克镇、大墓地和晒骨场。}

#{104}{}{So, that old bastard gave you the okay to work for us, eh?  Well you must have balls of steel.
# I'm impressed, but we'll see how you do.  We leave only twice a month, on
# the 3rd and 17th.  Can you handle that? We go to all the local hot spots:  the Brotherhood of Steel,
# Junktown, Necropolis, and the Boneyard.}
{104}{}{老不死的居然同意你来干活了？你他妈一定是个糙哥。我很欣赏，但要看你的表现了。我们每个月出发两次，3号和17号，你能来吧。我们主要去四个地方：钢铁兄弟会、迦克镇、大墓地和晒骨场。}

#{105}{}{And the pay?}
{105}{}{报酬如何？}

#{106}{}{Uh.}
{106}{}{呜。}

#{107}{}{Our pay's the best, 600 scripts, and yes, that is for each way?but you don't have to do both.  This
# is a pretty tough caravan ride, and you're almost guaranteed to run into some raiders?or worse.  We'll have no
# sissies on my caravans and you better have plenty of ammo.}
{107}{}{我们的薪水最高。600个瓶盖，没错，单程600个瓶盖。不过，你也不必来回都跟着。商队的旅行是很危险的，肯定会遇见强盗的或者更可怕的东西。我们的队伍里没有胆小鬼，你最好带足弹药。}

#{108}{}{ We're leaving today.  Are you interested?}
{108}{}{我们今天走，你有兴趣么？}

#{109}{}{ We leave on }
{109}{}{我们的出发时间是在}

{110}{}{空的}

{111}{}{空的}

#{112}{}{.  Are you interested?}
{112}{}{。有兴趣？}

#{113}{}{We're all heading out today.}
{113}{}{我们今天出发。}

#{114}{}{We're going out on }
{114}{}{我们出发时间在}

#{115}{}{}
{115}{}{}

#{116}{}{}
{116}{}{}

#{117}{}{ Are you interested?}
{117}{}{有兴趣否？}

#{118}{}{I'll still give your sorry ass a job, if you're interested?}
{118}{}{我还是愿意给你这个衰人一个工作，有兴趣吗？}

#{119}{}{Sure.}
{119}{}{好。}

#{120}{}{No.}
{120}{}{不。}

#{121}{}{I think I'm interested in you.}
{121}{}{我对你没兴趣。}

#{122}{}{Maybe.}
{122}{}{也许吧。}

#{123}{}{Ug.}
{123}{}{呜。}

#{124}{}{Ha, I thought you were a coward!  Well?if you brave'n up, stop by and I might still give you a job. We
# leave on the 3rd and 17th, you can just show up that day if you like.  We can always use more guns.}
{124}{}{哈，我还以为你是个胆小鬼的！那么，如果你够种，下次来找我，我给你工作。我们每个月3号和17号出发，你那天来就是了。我们从来都是缺人手。}

#{125}{}{You just love to waste my time, don't you.}
{125}{}{你是不是想浪费我时间啊。}

#{126}{}{Whatever.  If you get the urge for some action come back and I'll hook you up on the next caravan out.}
{126}{}{随你了，如果你想爽的话，下次来找我，我给你安排商队。}

#{127}{}{Hey!  I know you can get some good drugs here, but I'm not supposed to hire you unless your sober.}
{127}{}{嘿！这里的毒品是不赖，但是你要清醒了再来找工作。}

#{128}{}{I said to lay off the drugs, man!}
{128}{}{醒醒你的瘾！}

#{129}{}{I said to lay off the drugs, bitch!}
{129}{}{醒醒你的瘾！}

#{130}{}{Well now?I hate to say it but?I've heard of you.  Are you as tough in private as in public?  Let's
# see?(She leads you around a corner)}
{130}{}{那么……这个……我听说过你。你私底下也和你在外面那样强悍吗？我们试试？【她把你领到了一个无人的地方】}

#{131}{}{(On the way back she slips you a few things.)}
{131}{}{【回来的路上，她塞给了你一点东西。】}

#{132}{}{Well, you can last for QUITE a while.}
{132}{}{啊，你真是能坚持好长一会呢。}

#{133}{}{Well, you 慳re' interesting and 憊ery' different from most people?show me what you've got tough guy.
# (She leads you around a corner)}
{133}{}{你是个很有趣的人，和其他人不一样吧？让我来看看你的能耐，棒小伙。【她把你领到了一个无人的地方】}

#{134}{}{(One the way back she slips you a few things.)}
{134}{}{【回来的路上，她塞给了你一点东西。】}

#{135}{}{Well, you can last for QUITE a while.}
{135}{}{啊，你真是能坚持好长一会呢。}

#{136}{}{Hey Pops, looks like we've got a thief here! What do you have to say for yourself, you scum?}
{136}{}{弟兄们，这家伙是个贼！你还有什么好说，混球？}

#{137}{}{I'm sorry. I'll never do it again.}
{137}{}{对不起，我以后不做这个了。}

#{138}{}{Catch me if you can厎
{138}{}{来啊，来抓我啊。}

#{139}{}{I don't like quiet! Come and get me!}
{139}{}{我不想私了，来干我啊！}

#{140}{}{(Nod yes)}
{140}{}{【点点头】}

#{141}{}{OOOGABOOOGA!!!}
{141}{}{吼吼！！！}

#{142}{}{Hey Pops, this dumb shit didn't learn a lesson the first time. She tried to
# steal from me again.  Let's pummel her.}
{142}{}{弟兄们，这家伙不长记性，她又想偷我的东西，揍她！}

#{143}{}{Hey Pops, this dumb shit didn't learn a lesson the first time. He tried to steal from me again. Let's pummel him.}
{143}{}{弟兄们，这家伙不长记性，他又想偷我的东西，揍他！}

#{144}{}{Well?I know how easy it is to be tempted to steal, but?Hell, I'll give you a chance.  Don't show your
# face around here again and I won't call the cops.  Now beat it.}
{144}{}{嗯，我知道你的手犯贱，我再给你一次机会，赶紧从我眼前消失，要不我喊警察了，滚！}

#{145}{}{Oh we'll make sure of that, won't we Pops?}
{145}{}{好啊，那就满足你。}

#{146}{}{Go to hell!}
{146}{}{去死！！}

#{147}{}{I guess so.}
{147}{}{我想也是。}

#{148}{}{You're dead meat.}
{148}{}{你死定了。}

#{149}{}{I said to get out!}
{149}{}{快滚！}

#{150}{}{Police!}
{150}{}{警察！}

#{151}{}{Sorry, we won't deal with you anymore.}
{151}{}{我们不愿意再和你打交道了。}

#{152}{}{No jobs here, beat it.}
{152}{}{没工作，滚开！}

#{153}{}{Don't get on my bad side.}
{153}{}{别惹我发飙。}

#{154}{}{Moron.}
{154}{}{笨蛋。}

#{155}{}{Intriguing, but you're not my type.}
{155}{}{你很聪明，但是我不喜欢。}

#{156}{}{Good. Like I said before we pay 600 scripts. Which route did you want to take?}
{156}{}{很好，我们说好了600个瓶盖。你想走哪条路线？}

#{157}{}{Cool.  The next one's going out on }
{157}{}{酷啊，下一班是在}

#{158}{}{. Come back then and I'll put you on a caravan. As always, it
# pays 600 scripts.}
{158}{}{。那时候来找我，我会给你安排。工钱是600块。}

#{159}{}{Okay. }
{159}{}{好的。}

#{160}{}{Sorry, I can't wait that long.}
{160}{}{不行，我等不了那么长。}

#{161}{}{I should string you up by your eye lids!  Because of you we lost
# a whole damn caravan!  Get the hell out of my face! I'm going to catch some serious shit for this one.}
{161}{}{我要把你的眼皮串起来吊死你！就是因为你这个婊子，我们损失了整个商队！从我面前消失！这件破事把我逼疯了。}

#{162}{}{I should string you up by your balls!  Because of you we lost
# a whole damn caravan!  Get the hell out of my face! I'm going to catch some serious shit for this one.}
{162}{}{我要把你的鸟蛋串起来吊死你！就是因为你这个衰鬼，我们损失了整个商队！从我面前消失！这件破事把我逼疯了。}

{163}{}{钢铁兄弟会}
{164}{}{迦克镇}
{165}{}{大墓地}
{166}{}{晒骨场}

#{167}{}{Never mind.  I have something I forgot to do. }
{167}{}{算了，我还有自己的事情要做。}

#{168}{}{Lock and load! We're out of this joint!}
{168}{}{出发！我们离开这里了！}

#{169}{}{Let me know if anything cool happens, Dad's making me stay around the warehouse.}
{169}{}{告诉我一些新奇的事情，爸爸非要让我呆在仓库里。}

#{170}{}{Great! The other psychopaths are ready.  We'll leave right away.}
{170}{}{太好了！其他的疯狗们也准备好了，我们马上就走。}

#{171}{}{Cool, it'll just take a few minutes to get the psychos together.}
{171}{}{好，再等几分钟，所有疯子就会集合完毕。}

#{172}{}{Brotherhood of Steel, here we come! Well?I'm not going with you, but you know what I mean.}
{172}{}{钢铁兄弟会！我们来了！虽然我不跟你去，但是你知道我要表达的意思是吧。}

#{173}{}{Okay, get out of my face already.  Those Brotherhood fanatics are waiting for you.}
{173}{}{好，你走吧，那些钢铁兄弟会的变态在等着你呢。}

#{174}{}{I hope you like mountains!  You're going right into them.  You should see lots of action there.}
{174}{}{你会喜欢山区的！你们的必经之地，那里有很多好戏看。}

#{175}{}{Ready to go, and you'll be heading straight though the mountains!  It should be a blast!}
{175}{}{准备出发，要翻过大山，那里有很多架要打。}

#{176}{}{Junktown's pretty tame.  I prefer the more dangerous routes.}
{176}{}{迦克镇很平静。我喜欢更加冒险一点的路线。}

#{177}{}{I hear there's some crazy doctor there, you should check him out.  His name's Doc Morbid.}
{177}{}{我听说那里有个变态医生，你应该去看看，他的名字叫莫彼得。}

#{178}{}{Junktown's a short trip, you should be back soon.}
{178}{}{迦克镇的路线不长，你应该很快就能回来了。}

#{179}{}{Watch your ass, Necropolis isn't a very friendly place.}
{179}{}{路上小心，大墓地不是友好的地方。}

#{180}{}{Set's the leader of the town. At least he was the last time I was there.}
{180}{}{赛特是镇里的领导，至少我上次去的时候还是。}

#{181}{}{That town's full of skags!  Well, I better get you going.}
{181}{}{城里全是嗑药仔！嗯，你还是准备动身吧。}

#{182}{}{LA's pretty cool.  You'll like it, but just be sure not to leave the caravan until it arrives.  It's
# not to safe, for the caravans that is.}
{182}{}{洛杉矶，很酷的地方。最好不要离开商队，那里不太安全。}

#{183}{}{Hope you get a chance to see it, there's also a cool church just a few miles to the south of it.
# The people are whacked, though.}
{183}{}{南边几英里还有一个大大的很酷的教堂，也许你会有机会看到。那里的人似乎都萎靡不振的样子。}

#{184}{}{I'm told the Boneyard used to be a place called LA.  I don't know what the person's initials stand
# for, but it's a cool place.}
{184}{}{我知道晒骨场以前就是洛杉矶。我也不知道这个“洛杉矶”具体是人名还是什么的，但那里是一个很酷的地方。}

#{185}{}{What the hell do you want?}
{185}{}{你到底要干什么？}

#{186}{}{Shut up and get out of my way, I'm not in the mood!}
{186}{}{闭嘴，滚开，我现在没心情！}

#{187}{}{I want another job.}
{187}{}{我要工作。}

#{188}{}{Nothing.}
{188}{}{没事。}

#{189}{}{Zug.}
{189}{}{咂。}

#{190}{}{Ug.}
{190}{}{晤。}

#{191}{}{Yeah right!  So you can abandoned another caravan?  You're lucky they made it in one piece.}
{191}{}{是嘛！然后你就再次擅离职守是吧！你应该庆幸我没把你撕碎了。}

#{192}{}{I'm lucky?  You're lucky I don't pound your face in!}
{192}{}{我要庆幸？你才应该庆幸我没把你脸夯扁了！}

#{193}{}{Hey!  I had places to go and?stuff!}
{193}{}{嘿，我有地方要去，我也有事情要做的嘛。}

#{194}{}{Hey!  You didn't say I couldn't leave!  It's not like they were in the middle of combat.}
{194}{}{嘿！你又没说我不能离开！我又不是在打仗的时候跑走的。}

#{195}{}{Get out of here!  You make me sick!  That's why you left the caravan?  You were on drugs I bet!}
{195}{}{滚！你真恶心！这就是你离开商队的原因？你那会一定在嗑药吧！}

#{196}{}{Yea?  Well why don't you go there now!  You're off our list for good.}
{196}{}{哦？那你现在就去忙那些破事啊！你已经不在我们考虑的人选名单里了。}

#{197}{}{What?  You've never worked a caravan before?  I can't believe my dad hired you in the first place!
# Get lost!  We only hire experienced personnel!  That's why we pay the big bucks!}
{197}{}{你以前没干过保镖？我没想到阿爸居然还是你的第一任主顾呢！我们只要有经验的保镖！所以我们开的工资很高！}

#{198}{}{You did good on that last job. Are you looking for another one?}
{198}{}{你上次干得不错，再做一次？}

#{199}{}{Sure.}
{199}{}{好啊。}

#{200}{}{No.}
{200}{}{不了。}

#{201}{}{Maybe.}
{201}{}{也许吧。}

#{202}{}{Ug.}
{202}{}{晤。}

#{203}{}{Lug.}
{203}{}{咯。}

#{204}{}{Ready to go?  We're leaving today.}
{204}{}{准备好了？我们今天就走。}

#{205}{}{Yep!}
{205}{}{是！}

#{206}{}{Nope.}
{206}{}{不。}

#{207}{}{Hrurra?}
{207}{}{呼啦？}

#{208}{}{You're a day early. Come back tomorrow if you still want the job.  If not, don't show.  I don't give
# a crap.}
{208}{}{你来早了一天，如果还要那个工作，明天再来吧。要是你改主意了，那就不必来了，我不会有什么意见。}

#{209}{}{Hey, you're early.  I'm not sending them out until }
{209}{}{嘿，你来早了。下次出发的时间是}

{210}{}{3号}

{211}{}{17号}

#{212}{}{. Come back then if you still want the damn job.  I really don't care if you show or not.  But if you
# do still want it come back then.}
{212}{}{如果你还想干就那时候再来吧。你来不来都无所谓。如果你要干，那就当天来报道。}

#{213}{}{Not yet.}
{213}{}{还没。}

#{214}{}{Dad, shut the hell up!}
{214}{}{爸爸，你闭嘴！}

#{215}{}{Hey old man, I'm hungry!  I'm going to take a break!}
{215}{}{老家伙，我饿了！我要去休息！}

#{216}{}{I hate working the books.}
{216}{}{我讨厌做账的活儿。}

#{217}{}{January }
{217}{}{1月}

#{218}{}{February }
{218}{}{2月}

#{219}{}{March }
{219}{}{3月}

#{220}{}{April }
{220}{}{4月}

#{221}{}{May }
{221}{}{5月}

#{222}{}{June }
{222}{}{6月}

#{223}{}{July }
{223}{}{7月}

#{224}{}{August }
{224}{}{8月}

#{225}{}{September }
{225}{}{9月}

#{226}{}{October }
{226}{}{10月}

#{227}{}{November }
{227}{}{11月}

#{228}{}{December }
{228}{}{12月}

#{229}{}{You get 3 drug packs.}
{229}{}{你得到了3剂毒品。}
