#{100}{}{You see Killian.}
{100}{}{你看见基利安。}

#{101}{}{Who are you?}
{101}{}{你是谁？}

#{102}{}{How about telling me a bit about this town?}
{102}{}{你能和我讲讲这个城市的事情吗？}

#{103}{}{Do you own this store?}
{103}{}{这是你开的店？}

#{104}{}{I want to buy something.}
{104}{}{我要买点东西。}

#{105}{}{What's there to do around here?}
{105}{}{城里有什么好玩的？}

#{106}{}{What do I have to do to help you get rid of Gizmo?}
{106}{}{我怎么帮你干掉吉斯莫？}

#{107}{}{I'd better go.}
{107}{}{我走了。}

#{108}{}{Nu-uhh?}
{108}{}{唔唔？}

#{109}{Kill0a}{You want to buy something, friend?}
{109}{Kill0a}{你想买点什么，朋友？}

#{110}{}{Uh-huh.}
{110}{}{嗯嗯。}

#{111}{}{Nuh-uh.}
{111}{}{唔呼。}

#{112}{Kill1m}{Welcome to Junktown, stranger. What can I help you with?}
{112}{Kill1m}{欢迎你来到迦克镇，陌生人。你想要什么？}

#{113}{Kill1f}{Hello, darlin'. What can I get ya?}
{113}{Kill1f}{你好，亲爱的，想要做什么呢？}

#{114}{Kill1b}{What do you want?}
{114}{Kill1b}{你要什么？}

#{115}{Kill1g}{Can I help you?}
{115}{Kill1g}{我能帮你什么？}

#{116}{}{How about telling me a bit about this town?}
{116}{}{你跟我说说这个城市吧？}

#{117}{}{Do you own this store?}
{117}{}{这是你开的店？}

#{118}{}{I want to buy something.}
{118}{}{我要买东西。}

#{119}{}{What's there to do around here?}
{119}{}{城里有什么好玩的？}

#{120}{}{What do I have to do to help you get rid of Gizmo?}
{120}{}{我怎么帮你干掉吉斯莫？}

#{121}{}{I'd better go.}
{121}{}{我走了。}

#{122}{}{Nu-uhh?}
{122}{}{唔唔？}

#{123}{Kill02}{The name's Killian. Killian Darkwater. I'm the mayor of this fine
# town. And who might you be?}
{123}{Kill02}{我是基利安，全名基利安·达克沃特。我是这个美丽城市的市长。你是？}

#{124}{}{I'm }
{124}{}{我是}

#{125}{}{.}
{125}{}{。}

#{126}{}{My name is }
{126}{}{我叫}

#{127}{}{. I come from up north.}
{127}{}{。我从北方来。}

#{128}{}{What's it to you?}
{128}{}{关你鸟事？}

#{129}{Kill03}{Not much up that way 'cept desert and Shady Sands. You from there?}
{129}{Kill03}{北方除了沙荫镇，就是沙漠了，你是从沙荫镇还是沙漠里来的？}

#{130}{}{No. I come from a Vault, to the west.}
{130}{}{呃，不。实际上我是从西边的避难所出来的。}

#{131}{}{No. My . . . um . . . village is a little west, in the mountains.}
{131}{}{呃。这个……我……我老家是西边的一个村子，在山里的。}

#{132}{}{Not really. Is there anything else up there?}
{132}{}{我不是沙漠里的，也不是沙荫镇来的。这城市附近还有什么地方？}

#{133}{}{Of course, I come from there, you idiot.}
{133}{}{当然了，我就是那里来的，你这个笨蛋。}

#{134}{Kill03a}{Hey, you sound like you're hopin' I'll fill in some gaps for you.}
{134}{Kill03a}{嘿！你再这态度我给你身上开几个眼儿。}

#{135}{Kill04}{Yeah, if you say so. So what do you need?}
{135}{Kill04}{好好好，随你怎么说，你想要什么？}

#{136}{Kill05}{Oh yeah, sure you do. And when you were a baby, your crib was a safe.}
{136}{Kill05}{是啊！没错！你小时候还在锁柜里吃奶呢。}

#{137}{}{No, no. It's called a Vault. It protected us
# from the war. It's been full of people for 80 years!}
{137}{}{不是锁，是避难所。它可以在战争期间保护我们，80多年来那里住满了人。}

#{138}{}{Heh, you got my joke. I actually come from a
# village not far from Shady Sands.}
{138}{}{嘿嘿，开玩笑啦，实际上我是从沙荫镇西边不远的一个村子里来的。}

#{139}{Kill06}{Don't feel bad, ain't the worst story I've
# been told. So . . . what can I do for ya?}
{139}{Kill06}{想开点，我听过的故事中，你这个还不算太惨的。那么……我能帮你什么？}

#{140}{Kill08}{Well, travelers tell me there's a bunch of crazies up north called the
# Vipers. Another group of yahoos out east called the Khans. Neither
# one of them likely to invite you to supper as anything but the main course,
# if you know what I mean.}
{140}{Kill08}{嗯，旅行者们说，北边还住着一些叫做蝮蛇帮的坏蛋，另外还有一群叫做可汗帮的土匪住在东边。这两拨强盗都不是善茬，只有死人才能和他们和平相处，你明白吧？}

#{141}{}{What else is outside Junktown?}
{141}{}{外边还有什么地方？}

#{142}{}{Thanks.}
{142}{}{多谢。}

#{143}{Kill09}{Well, ya got the Hub southwest. Don't go south, though. That'd be Necropolis;
# the, uh . . . climate's bad there, rain or shine. If you understand what I'm
# saying.}
{143}{Kill09}{往西南走是哈勃城，可别往南走，那里是大墓地。那里……那里不管晴天雨天，总是阴森森的，你明白我的意思吧。}

#{144}{}{Well, thanks for the information. Can I ask you a few more questions?}
{144}{}{多谢你的信息。我还能问你几个问题吗？}

#{145}{}{You just know everything, don't you?}
{145}{}{你好像什么都知道哇。}

#{146}{}{I'd better be going now.}
{146}{}{那我告辞了。}

#{147}{Kill10a}{Hell, why not. Ask away, friend.}
{147}{Kill10a}{靠，当然可以了，说吧，朋友。}

#{148}{Kill10b}{Yeah, okay. But make it quick, I got work to do.}
{148}{Kill10b}{哦，好的。别拖太久了，我还有事要忙呢。}

#{149}{Kill11}{Well, Junktown's not much, but it's home. Mostly we trade with
# people or let 'em forget their troubles for a bit.
# Of course, we have our share of problems.}
{149}{Kill11}{迦克镇不是很大，但这里是我们的家。我们在这里做买卖，外面惹了麻烦的人也可以在这里避避风头。当然，我们也有自己的麻烦。}

#{150}{}{Problems?}
{150}{}{自己的麻烦？}

#{151}{}{What's there to do in this town?}
{151}{}{镇里有什么好玩的地方吗？}

#{152}{}{What other cities are around here?}
{152}{}{周围还有哪些城市？}

#{153}{}{Thanks.}
{153}{}{谢了。}

#{154}{Kill12}{From outside, we've had the occasional to-do with the Khans. But
# they've been pretty quiet lately. Inside, trouble's been from the Skulz.
# And I hear of some strange things happening down by the Hub, but
# they haven't affected us yet, knock on my mother-in-law's head.}
{154}{Kill12}{对外的麻烦呢，我们经常和可汗帮闹点摩擦。最近他们还算老实。内部麻烦主要是骷髅党。我还听说哈勃城出了事，但是还没有影响到这里，搅到鸡飞狗跳。}

#{155}{Kill13b}{Oh, we got tons to do. The Skum Pitt's on the east side, by the
# entrance. Great drinkin' place. Gizmo's is near there. And if you're hurtin', Doc
# Morbid's your man.}
{155}{Kill13b}{很多啊。东边靠城门的萨姆·匹特酒吧是个喝酒的好地方。吉斯莫的赌场也在那附近。如果挂了彩，就去找莫彼得医生。}

#{156}{}{Thanks.}
{156}{}{多谢。}

#{157}{}{That's all there is to do around here?}
{157}{}{就这些啊？}

#{158}{Kill14}{Well, if we're too fast for ya, just pass on by, pal. It is pal,
# ain't it?}
{158}{Kill14}{如果你嫌我们这里太闷，可以走啊。是吧，伙计？}

#{159}{}{Better than nothing, I guess.}
{159}{}{总比什么都没有强吧。}

#{160}{}{Then there won't be anything exciting in town.}
{160}{}{那你们这里可就真是没啥好玩的了。}

#{161}{Kill15}{By a damn sight.}
{161}{Kill15}{当然。}

#{162}{Kill16}{Oh, you obviously have me confused with someone who has to take
# your lip. Why don't you come back when your mama teaches you some manners.}
{162}{Kill16}{别以为我会迁就你。在你妈妈教你懂点礼貌后再来跟我说话！}

#{163}{Kill21}{Well that's a damn fine coincidence! That's what this store's here
# for! We got about everything you can need. Let me show you some
# things over here . . .}
{163}{Kill21}{你算是找对人了。我开店就是要卖东西的。有你想要的一切货色。来看看我的东西吧……}

#{164}{Kill22}{You bet. May not be as big as some in the Hub, but people usually
# find what they're looking for. Take a look around . . .}
{164}{Kill22}{没错。我这里虽然店面不如哈勃城的大，但基本满足顾客需求，来瞧瞧吧……}

#{165}{Kill23}{You have to wear a recorder and tape Gizmo confessing, or plant
# this wire tap in his office. Either way, and we got him.}
{165}{Kill23}{你要么用录音机把吉斯莫的话录下来，要么把这个窃听器安到他办公室里，无论哪种办法，我们都可以搞定他。}

#{166}{Kill24}{Well, howdy! What can I do for you today?}
{166}{Kill24}{嗨，你好啊，今天你想要什么？}

#{167}{Kill26}{You again. What do you want now?}
{167}{Kill26}{又见面了，你想做什么？}

#{168}{Kill27}{Unless you're gonna pay for that, you'd better put it down.}
{168}{Kill27}{如果你不打算买的话，你还是把它放下的好。}

#{169}{Kill28}{You're not too bright, are ya. Boys . . .}
{169}{Kill28}{你不聪明，一点都不。来人！……}

#{170}{Kill29}{It's obvious your mama didn't teach you manners. Am I gonna have to?}
{170}{Kill29}{你妈妈没教你礼貌，要不要我来教教你啊？}

#{171}{Kill30}{Well, congratulations. You just earned yourself a
# night in a cell. Boys . . .}
{171}{Kill30}{很好，恭喜你了，你可以在监狱里蹲一晚上了，来人！}

#{172}{Kill31}{Now what the Uncle Sam-hell do you think you're doing here?}
{172}{Kill31}{你它娘的到底想在这里做什么？}

#{173}{}{Uh . . . I got lost?}
{173}{}{呃……我迷路了？}

#{174}{}{Oh, this is your place?}
{174}{}{啊？这里是你的地方？}

#{175}{}{Well . . . I broke in.}
{175}{}{啊……我进来搞点东西。}

#{176}{Kill32}{You're damn straight this is my place! Now get the hell out before
# I make your head a wall decoration!}
{176}{Kill32}{你说的太他妈对了，这就是我的地方！赶紧滚！要不然我把你脑袋拧下来当壁灯！}

#{177}{}{Okay, okay, I'm going.}
{177}{}{好好好，我马上走。}

#{178}{}{You? Wake up, pal, you're still dreaming.}
{178}{}{你？醒醒吧，伙计，你还在做梦呐。}

#{179}{Kill34}{Uh, no. You got stupid. Get out of here!}
{179}{Kill34}{不是吧，你笨啊，走开！}

#{180}{}{Okay. Sorry about the inconvenience.}
{180}{}{好的好的，对不起啦。}

#{181}{}{Who's going to make me? You? Don't make me laugh . . .}
{181}{}{你要我走……？就凭你？笑死人了……}

#{182}{Kill35}{An honest thief. Hmpf. Well, I'm still gonna have to take you in.
# Come along quietly and you won't get hurt.}
{182}{Kill35}{一个老实的小偷，哼，但是我还是要拘捕你。老老实实地跟我走，要不然你会吃苦头的。}

#{183}{}{All right, I'll come along quietly.}
{183}{}{好好好，我跟你走。}

#{184}{}{Right . . . I don't think so.}
{184}{}{不……我才不听你摆布。}

#{185}{Kill36}{Like I said . . .}
{185}{Kill36}{我说过……}

#{186}{Kill37}{I already told you . . .}
{186}{Kill37}{我早就跟你说过……}

#{187}{Kill38}{I already told you . . .}
{187}{Kill38}{我早就跟你说过……}

#{188}{Kill39}{Are you hearing okay? I said . . .}
{188}{Kill39}{你听力没问题？我说……}

#{189}{Kill40}{Look, if you don't remember, that's tough.}
{189}{Kill40}{如果你记忆有问题，那就不好办了。}

#{190}{Kill41}{Listen, I've already told you that numerous times.}
{190}{Kill41}{听着，我已经跟你说过多少遍了。}

#{191}{Kill42}{You leaving so soon? Better pay first.}
{191}{Kill42}{你这么就想走了？还是先付钱吧。}

#{192}{Kill43}{This is not something I take as a joke. Now. Pay up.}
{192}{Kill43}{我觉得这不好笑。现在马上给我付钱！}

#{193}{Kill44}{All right. Fine. Let's see if a night in the locker will
# cool you off a bit.}
{193}{Kill44}{行，行，行，我看看把你关一晚上你还会不会这么嘴硬。}

#{194}{Kill45}{Any more questions?}
{194}{Kill45}{还有问题吗？}

#{195}{}{You bet.}
{195}{}{当然。}

#{196}{}{Nope. That's it, thanks.}
{196}{}{没了，就这些，谢谢。}

#{197}{Kill46}{See ya 'round town then. Be careful not to get into too much trouble.}
{197}{Kill46}{那再见了。在城里别惹事。}

#{198}{Kill47}{Listen. Thanks for saving my life. It's a mighty brave thing to do.
# Looks like we got ourselves a situation here. I know Gizmo's behind this,
# but I need proof.  You interested in helpin'?}
{198}{Kill47}{听着。我很感谢你救了我的命。现在我们有大事要做了，既然我们自己走到这一步，就没有退路了。我知道一切都是吉斯莫幕后策划的，但是我需要证据，你有兴趣来帮忙吗？}

#{199}{}{Me? What do you need me for?}
{199}{}{我？我能做什么呢？}

#{200}{}{Can't you get someone else? I'm kinda busy . . .}
{200}{}{你找其他人吧。我有点忙呢……}

#{201}{}{I'm in.}
{201}{}{没问题！}

#{202}{Kill48}{Now, if I get proof, the people of Junktown will kick him out.
# Way I figure it, you need to either plant a bug at his place or wear a wire
# and get him to confess to you. Can you handle that?}
{202}{Kill48}{如果我有证据，迦克镇的人就会把他赶出城去。我的办法是，你把窃听器安在他办公室或者用录音机录下他的自供，你能搞定吗？}

#{203}{}{Whoa. Sounds kinda dangerous . . .}
{203}{}{哦，看起来有点危险呐……}

#{204}{}{What do I get in return?}
{204}{}{我能得到什么？}

#{205}{}{Ummm . . . no. Getting involved in other people's
# problems never works out.}
{205}{}{嗯……算了。掺和到别人的恩怨是非里面去是不妥当的。}

#{206}{Kill49}{I'm not gonna lie to you, it will be dangerous. But I'll owe you
# one, and Killian Darkwater always pays his debts.}
{206}{Kill49}{我不想骗你，这的确是有点危险。但我会记住你的这份人情，我，基利安·达克沃特，一定会还你这份人情的。}

#{207}{}{You sure you can't find someone else?}
{207}{}{你真找不到其他人来办这个事情了？}

#{208}{}{What do you mean, 'pays his debts.'}
{208}{}{什么叫做“还我人情”？}

#{209}{}{I don't think so. Sounds too dangerous to me.}
{209}{}{我不干，太危险了。}

#{210}{Kill50}{It'll work best if it's you. Gizmo doesn't know you, so he might trust
# you. Or, at least he'll have a hard time blaming me. Either way, you're the best
# person for the job.}
{210}{Kill50}{你是最适合的人选。吉斯莫不认识你，所以很可能会相信你。至少他不会怀疑到我。怎么说，你都是最好的人选。}

#{211}{}{Fair enough, I'll do it.}
{211}{}{好，我去。}

#{212}{}{Pass. Getting killed doesn't seem like a fun thing for me.}
{212}{}{算了。把小命丢了可不是闹着玩的。}

#{213}{}{What do I get out of this?}
{213}{}{我有什么好处？}

#{214}{Kill51}{I'll tell you what. Anything in the store, even the most expensive,
# it's yours. No charge. If it's a gun, I'll give you all the ammo you can carry.
# Does that sound fair?}
{214}{Kill51}{那我跟你讲清楚吧。这个店里的所有东西，即使是最贵的，都是你的了。免费！如果你要枪，我会给你多到你那不下，这个交易划得来吧？}

#{215}{}{Yeah. I'll do it.}
{215}{}{好，我干了！}

#{216}{}{Not even close. I'm not risking my neck for that.}
{216}{}{还是不想。我不会为这个玩命的。}

#{217}{Kill52}{Well, damn. That's too bad. But, you know, I'm gonna have to lock
# you up until this thing's done. Can't risk Gizmo finding out. Sorry.}
{217}{Kill52}{可恶。真是抱歉，在我自己搞定这件事之前，我要把你关起来，免得你可能会去为吉斯莫通风报信，失礼了。}

#{218}{Kill53}{All right, I owe you. Here's the bug and the wire tap.
# You let me know when it's done. And good luck.}
{218}{Kill53}{太好了，我会报答你的。给你窃听器和录音机，搞定后向我回话，祝你好运！}

#{219}{Kill54}{So, did you get the evidence?}
{219}{Kill54}{你拿到证据了？}

#{220}{}{Not yet. But I will, believe me!}
{220}{}{还没，我会的，相信我！}

#{221}{}{I sure did.}
{221}{}{当然了。}

#{222}{Kill55}{Well, he's not going to come here and confess! You shouldn't even be
# seen with me until this is done. Now go.}
{222}{Kill55}{他不会到我这里来自首吧！拿到证据之前，你不要到我这里来乱晃，免得他起疑，赶紧去办事。}

#{223}{Kill56}{Which, bug or tape?}
{223}{Kill56}{窃听器还是录音带？}

#{224}{}{The bug.}
{224}{}{窃听器。}

#{225}{}{The confession.}
{225}{}{他的自供词。}

#{226}{Kill57}{Great! Let me make sure it's working.}
{226}{Kill57}{太棒了！我来听听，是不是有效。}

#{227}{Kill57a}{Loud and clear. We're going to get him. In the mean time, we've
# got some business . . .}
{227}{Kill57a}{这是很充足的证据！我们现在就去抓他。对了，我还要和你谈个事情……}

#{228}{Kill58}{Let's hear it.}
{228}{Kill58}{好，听一下。}

#{229}{Kill58b}{That's the first time I've been happy to hear his voice. Thanks,
# friend.  Now, time for you and me to take care of the other business.}
{229}{Kill58b}{多年来，这还是第一次我听到这个猪头的声音后没起鸡皮疙瘩，多谢啦，朋友。我还有件事情要和你商量。先说你的报酬吧。}

#{230}{Kill59}{Well, thanks again. Oh, listen, I'm gonna take the guards and run
# Gizmo and his cronies out of town. I could use another gun. You up for it?
# Might be good for a laugh.}
{230}{Kill59}{我再次谢谢你。还有呢，我要带些守卫去废了吉斯莫和他的跟班，我们的人越多越好，你想不想来，看看好戏去？}

#{231}{}{Sure. It'll be worth it just to see him try to walk more than ten feet.}
{231}{}{当然了，看他最后的蹦达还是很有趣的。}

#{232}{}{Kinda depends on what you're willing to give me.}
{232}{}{这次你有什么好处给我？}

#{233}{}{Again? I don't think so. I've got way too much stuff going on.}
{233}{}{还去？不了。我还有好多事情要办呢。}

#{234}{Kill60}{Go to Lars at the guard station. He'll fill you in.
# And listen, this town owes you . . . a lot.}
{234}{Kill60}{跟守卫站的拉尔斯说，他会给你安排。对了，我要说，我们镇子都很感激你……非常感谢。}

#{235}{Kill61b}{Well, I can pay you the standard rate for mercenary work,
# 500 caps.}
{235}{Kill61b}{那，我就再付给你标准的佣兵价格：500个瓶盖。}

#{236}{}{Done.}
{236}{}{成交！}

#{237}{}{Sorry, not enough.}
{237}{}{不行，太少了。}

#{238}{Kill62}{Good enough. Go see Lars, he'll give you the details.}
{238}{Kill62}{很好，找拉尔斯去，他会和你细谈。}

#{239}{Kill63}{Listen, that's all I'm offering. Thanks for getting the
# evidence, but I'm not going to beg for your services.}
{239}{Kill63}{听着，这是我的最高价码了。我很感谢你帮我取得证据，但我也不是事事都要靠你的。}

#{240}{}{All right, I'll do it for that fee.}
{240}{}{那好吧，就这个价了。}

#{241}{}{Oh, well. See ya around.}
{241}{}{哦，那好，回见了。}

#{242}{Kill64}{Good luck in your travels. Now if you'll excuse me, I have a fat ass
# to move.}
{242}{Kill64}{旅途愉快，抱歉，让个道，我要办事去了。}

#{243}{Kill65}{Gizmo owns the casino. Named it after himself.
# Be very careful around him.}
{243}{Kill65}{吉斯莫开了个赌场，就叫吉斯莫赌场。你要小心这个人。}

#{244}{Kill66}{Well, that's me. Where have you been?}
{244}{Kill66}{那就是我啊。你走神了？}

#{245}{Kill67}{Oh, Lars heads up the guards here. He's a good guy.
# Pretty trustworthy.}
{245}{Kill67}{哦，拉尔斯是守卫的头儿，是个好人，很值得信任。}

#{246}{Kill68}{Well Vinnie, he's one of the problem children. He leads a group
# of punks called the Skulz. Still, they pay rent, and they haven't bothered
# anyone too much.}
{246}{Kill68}{维尼是个问题少年。他领着一群朋克，自称什么骷髅党。还好，他们还是缴纳租金的，也没有带来太多的麻烦。}

#{247}{Kill69}{Well, Doc owns a little place in the middle of the town. Does
# a nice patch job if you need it. Fairly reasonable prices.}
{247}{Kill69}{医生在镇中央有个小诊所，手术做得不赖，价格还算公道。}

#{248}{Kill70}{The Skulz are a bunch of punks who work for Gizmo. They don't cause
# that much trouble, but me and Lars keep an eye on them.}
{248}{Kill70}{骷髅党是为吉斯莫跑腿的一帮混混，他们没惹出太大的事情，但是我和拉尔斯一直盯着他们。}

#{249}{Kill71}{Well, the Khans are a bunch of bullies who live outside to the
# east. They've been trying to take over Junktown for as long as I can
# remember, but they never make it past the gates.}
{249}{Kill71}{可汗帮住在城外东边的地方，他们是一群强盗，从我记事以来一直想拿下我们迦克镇，不过从来都没得逞。}

#{250}{Kill72}{The Vipers are a crazy bunch from up north. They worship snakes, or
# something.}
{250}{Kill72}{蝮蛇帮在城外北方区域活动，他们崇拜蛇之类的东西。}

#{251}{Kill73}{That's my store. You need it, I got it.}
{251}{Kill73}{就是我的店铺，你需要什么，我就供应什么。}

#{252}{Kill74}{Great place to get a cheap room. Not too dirty, either. But don't
# mess with the owner, Marcelles, she'll pull your arms out if you smart
# off to her.}
{252}{Kill74}{如果你要找便宜的住宿，那是个不错的选择。而且还不是太脏。但是别去惹那里的老板玛塞尔，你要是和她罗嗦，她会把你胳膊扯下来的。}

#{253}{Kill75}{Ah, Gizmo's is the casino by the entrance. I'm surprised you didn't notice
# it on your way in. You can usually smell the place for miles. But
# hey, it brings in the tourists.}
{253}{Kill75}{吉斯莫赌场就在城区出口处，你要是看不到那就怪了呢。这种地方是顶风也臭八百里，不过，好歹拉了些游客来。}

#{254}{Kill76}{That's our resident bar. The food's okay, but the beer's great.
# The owner, Neil, takes no lip, not even from some of the Raiders that come in.}
{254}{Kill76}{镇民常去的酒吧，料理做的不错，啤酒就更棒了。店主尼尔不是好惹的人，强盗都惧他三分的。}

#{255}{Kill76a}{Not much to say. Doc Morbid's pretty pissed 'cause their prices are
# lower for medical stuff. They're on the west side.}
{255}{Kill76a}{没什么好说的，莫彼得医生很烦他们，因为他们卖的医疗用品很便宜，他们住在城西头。}

#{256}{Kill77}{The Death Claw? Oh, that's a bedtime story. Drinks blood and howls
# at the full moon. Yeah, right.}
{256}{Kill77}{死亡爪？骗小孩睡觉用的传说怪物吧，吸血，满月还嚎，对吧，哈哈。}

#{257}{Kill78}{Well, the Hub's the main place for trade. Anything you don't find
# here you'll probably find in the Hub. Not sure how safe it is nowadays, with
# all those strange things going on.}
{257}{Kill78}{哈勃城是贸易中心。你要的东西如果其他地方找不到，就去哈勃城吧。不过最近闹了很多怪事，也不知道现在安全不安全。}

#{258}{Kill79}{Shady Sands? That's a little place up to the north. I'd like to do
# more trading with them.}
{258}{Kill79}{沙荫镇？是北边的一个小镇子。我想和他们扩大贸易。}

#{259}{Kill80}{That city's death. I sent two patrols
# down there and neither one of them returned.}
{259}{Kill80}{一座死城，我派了两支巡逻队去，都没回来。}

#{260}{Kill81}{Well, there are two kinds, the Khans and the Vipers.
# We usually don't get trouble from the Vipers, and a few of them
# actually pass through town. The Khans, though, they're a mean bunch.
# They think they can conquer the world, or some such crap.}
{260}{Kill81}{有两派，可汗帮和蝮蛇帮，蝮蛇帮没什么了不得，很多强盗还经常来镇里办事，可汗帮是一群嗜血的混球，他们以为自己能征服世界呢，一派胡言。}

#{261}{Kill82}{Where've you been for the last 100 years? In a closet? My father used
# to tell me stories about the War. His father was a soldier before starting
# Junktown.}
{261}{Kill82}{你过去100年在外星球啊！要么就是在柜子里？我爸爸以前跟我讲起世界大战的事情。我爷爷在建立这个镇子之前就是个当兵的。}

#{262}{Kill83}{Well, there're some rumors coming up from the Hub. Caravans
# disappearing, people being butchered, even some talk of big green monsters
# who eat human flesh. All sorts of weird stuff.}
{262}{Kill83}{最近哈勃城有一些谣言。一些商队凭空就消失了，有人被杀了，还有人说看到绿绿的吃人大怪物，很多这样七七八八的东西。}

#{263}{Kill84}{Nope, I've never heard of anything like that.}
{263}{Kill84}{不知道，从来没听说过。}

#{264}{Kill85}{No clue.}
{264}{Kill85}{不知道。}

#{265}{Kill86}{Ohhh . . . I really couldn't tell ya.}
{265}{Kill86}{哦……我真的不能告诉你。}

#{266}{Kill87}{Go talk to Lars. He'll tell you more.}
{266}{Kill87}{和拉尔斯谈谈，他会告诉你的。}

#{267}{}{【Done】}
{267}{}{【完成】}

#{268}{}{【More】}
{268}{}{【更多】}

#{269}{}{You gain 600 experience points for your part in the defeat of Killian.
# Junktown will never be the same.}
{269}{}{你击败了基利安，获得了600点经验值，迦克镇的未来改变了。}

#{270}{}{You gain 500 experience points for securing Gizmo's confession.}
{270}{}{你获取了吉斯莫的证词，得到500点经验值。}

#{271}{}{I'm here to take you in, Gizmo. This time, I've got the proof I need.}
{271}{}{我来这里抓你，吉斯莫，这次我有充分的证据。}

#{272}{}{What do you know about this Gizmo character?}
{272}{}{吉斯莫是怎样的一个人？}

#{273}{}{Okay.}
{273}{}{好的。}

#{274}{}{Yeah, he's dangerous. I'm here to kill you for him.}
{274}{}{是啊，他是很危险啊。我就是他派来杀你的。}

#{275}{}{I'll say . . . that fat slob just tried to hire me to kill you.
# Why don't you do something about him?}
{275}{}{我想说……那个猪头想雇我杀你，你就不想对他动手？}

#{276}{}{I'll take a shotgun and shells.}
{276}{}{我要散弹枪和一些子弹。}

#{277}{}{I'll take a suit of leather armor.}
{277}{}{我要一套皮装甲。}

#{278}{}{I'll take a doctor's medical kit.}
{278}{}{我要医生手术箱。}

#{279}{}{I'll take all the stimpaks you can spare.}
{279}{}{我要你所有的治疗针。}

#{280}{}{No thanks. Knowing that Gizmo's going to get his due is thanks enough.}
{280}{}{不了，谢谢。让吉斯莫罪有应得就是我的最好报偿。}

#{281}{}{I'd like to take a look at traveling gear.}
{281}{}{我要看看旅行用的装备。}

#{282}{}{I'll look around on my own, thanks.}
{282}{}{我自己看看吧。}

#{283}{}{Never mind. Thanks.}
{283}{}{没事，多谢了。}

#{284}{}{You moved against Gizmo without evidence. Y'know, he wasn't on the up-and-up,
# but neither are you. Go see Lars.}
{284}{}{你没拿到证据就和吉斯莫做对。他可不是什么正派货色，当然，你也不是，去找拉尔斯谈谈吧。}



# Killian Tell-Me-Abouts generic responses
#{980}{Kill84}{Nope, I've never heard of anything like that.}
{980}{Kill84}{不知道，我从来没听说过。}

#{981}{Kill85}{No clue.}
{981}{Kill85}{不清楚。}

#{982}{Kill86}{Ohhh . . . I really couldn't tell ya.}
{982}{Kill86}{哦……我真的不能和你说。}

#{983}{Kill87}{Go talk to Lars. He'll tell you more.}
{983}{Kill87}{和拉尔斯谈谈，他会告诉你的。}


#
# Killian Tell-Me-Abouts
#

{1099}{}{?}
{1199}{}{我可以告诉你：Gizmo-吉斯莫、Killian-基利安、Lars-拉尔斯、Vinnie-维尼、Doc-医生、Skulz-骷髅帮、Khans-可汗帮、Vipers-蝮蛇帮、Darkwater's-黑水的店铺、Crash-睡觉、Gizmo's-吉斯莫的赌场、Skum-酒吧、Cathedral-大教堂、Claw-死亡爪、Hub-哈勃、Shady-沙荫镇、Necropolis-大墓地城、Raiders-歹徒、War-大战、Strange-奇怪、Darkwater-黑水、Morbid-莫彼得、Darkwaters-黑水、Gizmos-吉斯莫、Pitt-酒吧、Sands-沙荫镇、Pit-酒吧。}

{1000}{}{Gizmo}
{1001}{}{Killian}
{1002}{}{Lars}
{1003}{}{Vinnie}
{1004}{}{Doc}
{1005}{}{Skulz}
{1006}{}{Khans}
{1007}{}{Vipers}
{1008}{}{Darkwater's}
{1009}{}{Crash}
{1010}{}{Gizmo's}
{1011}{}{Skum}
{1012}{}{Cathedral}
{1013}{}{Claw}
{1014}{}{Hub}
{1015}{}{Shady}
{1016}{}{Necropolis}
{1017}{}{Raiders}
{1018}{}{War}
{1019}{}{Strange}
{1020}{}{Darkwater}
{1021}{}{Morbid}
{1022}{}{Darkwaters}
{1023}{}{Gizmos}
{1024}{}{Pitt}
{1025}{}{Sands}
{1026}{}{Pit}

#{1100}{Kill65}{Gizmo owns the casino over on the east side. Named it after himself.
# Be very careful around him.}
{1100}{Kill65}{吉斯莫开了个赌场，就叫吉斯莫赌场。你要小心这个人。}

#{1101}{Kill66}{Well, that's me. Where have you been?}
{1101}{Kill66}{那就是我啊。你走神了？}

#{1102}{Kill67}{Oh, Lars heads up the guards here. He's a good guy.
# Pretty trustworthy.}
{1102}{Kill67}{哦，拉尔斯是守卫的头儿，是个好人，很值得信任。}

#{1103}{Kill68}{Well Vinnie, he's one of the problem children. He leads a group
# of punks called the Skulz. Still, they pay the rent, and they haven't bothered
# anyone too much.}
{1103}{Kill68}{维尼是个问题少年。他领着一群朋克，自称什么骷髅党。还好，他们还是缴纳租金的，也没有带来太多的麻烦。}

#{1104}{Kill69}{Well, Doc owns a little place in the middle of the town. Does
# a nice patch job if you need it. Fairly reasonable prices.}
{1104}{Kill69}{医生在镇中央有个小诊所，手术做得不赖，价格还算公道。}

#{1105}{Kill70}{The Skulz are a bunch of punks who work for Gizmo. They don't cause
# that much trouble, but me and Lars keep an eye on them.}
{1105}{Kill70}{骷髅党是为吉斯莫跑腿的一帮混混，他们没惹出太大的事情，但是我和拉尔斯一直盯着他们。}

#{1106}{Kill71}{Well, the Khans are a bunch of bullies who live outside to the
# east. They've been trying to take over Junktown for as long as I can
# remember, but they never make it past the gates.}
{1106}{Kill71}{可汗帮住在城外东边的地方，他们是一群强盗，从我记事以来一直想拿下我们迦克镇，不过从来都没得逞。}

#{1107}{Kill72}{The Vipers are a crazy bunch from up north. They worship snakes, or
# something.}
{1107}{Kill72}{蝮蛇帮在城外北方区域活动，他们崇拜蛇之类的东西。}

#{1108}{Kill73}{That's my store. You need it, I got it.}
{1108}{Kill73}{就是我的店铺，你需要什么，我就供应什么。}

#{1109}{Kill74}{Great place to get a cheap room. Not too dirty, either. But don't
# mess with the owner, Marcelles, she'll pull your arms out if you smart
# off to her.}
{1109}{Kill74}{如果你要找便宜的住宿，那是个不错的选择。而且还不是太脏。但是别去惹那里的老板玛塞尔，你要是和她罗嗦，她会把你胳膊扯下来的。}

#{1110}{Kill75}{Ah, Gizmo's is the casino by the entrance. I'm surprised you didn't notice
# it on your way in. You can usually smell the place for miles. But
# hey, it brings in the tourists.}
{1110}{Kill75}{吉斯莫赌场就在城区出口处，你要是看不到那就怪了呢。这种地方是顶风也臭八百里，不过，好歹拉了些游客来。}

#{1111}{Kill76}{That's our resident bar. The food's okay, but the beer's great.
# The owner, Neal, takes no lip, not even from some of the Raiders that come in.}
{1111}{Kill76}{镇民常去的酒吧，料理做的不错，啤酒就更棒了。店主尼尔不是好惹的人，强盗都惧他三分的。}

#{1112}{Kill76a}{Not much to say. Doc Morbid's pretty pissed 'cause their prices are
# lower for medical stuff. They're on the west side.}
{1112}{Kill76a}{没什么好说的，莫彼得医生很烦他们，因为他们卖的医疗用品很便宜，他们住在城西头。}

#{1113}{Kill77}{The Death Claw? Oh, that's a bedtime story. Drinks blood and howls
# at the full moon. Yeah, right.}
{1113}{Kill77}{死亡爪？骗小孩睡觉用的传说怪物吧，吸血，满月还嚎，对吧，哈哈。}

#{1114}{Kill78}{Well, the Hub's the main place for trade. Anything you don't find
# here you'll probably find in the Hub. Not sure how safe it is nowadays, with
# all those strange things going on.}
{1114}{Kill78}{哈勃城是做买卖的集散地。你要的东西如果其他地方找不到，就去哈勃城吧。不过最近闹了很多怪事，也不知道现在安全不安全。}

#{1115}{Kill79}{Shady Sands? That's a little place up to the north. I'd like to do
# more trading with them.}
{1115}{Kill79}{沙荫镇？是北边的一个小镇子。我想和他们扩大贸易。}

#{1116}{Kill80}{That city's death. I sent two patrols
# down there and neither one of them returned.}
{1116}{Kill80}{一座死城，我派了两支巡逻队去，都没回来。}

#{1117}{Kill81}{Well, there are two kinds, the Khans and the Vipers.
# We usually don't get trouble from the Vipers, and a few of them
# actually pass through town. The Khans, though, they're a mean bunch.
# They think they can conquer the world, or some such crap.}
{1117}{Kill81}{有两派，可汗帮和蝮蛇帮，蝮蛇帮没什么了不得，很多强盗还经常来镇里办事，可汗帮是一群嗜血的混球，他们以为自己能征服世界呢，一派胡言。}

#{1118}{Kill82}{Where've you been for the last 100 years? In a closet? My father used
# to tell me stories about the War. His father was a soldier before starting
# Junktown.}
{1118}{Kill82}{你过去100年在外星球啊！要么就是在柜子里？我爸爸以前跟我讲起世界大战的事情。我爷爷在建立这个镇子之前就是个当兵的。}

#{1119}{Kill83}{Well, there're some rumors coming up from the Hub. Caravans
# disappearing, people being butchered, even some talk of big green monsters
# who eat human flesh. All sorts of weird stuff.}
{1119}{Kill83}{最近哈勃城有一些谣言。一些商队莫名消失了，有人被杀了，还有人说看到绿绿的吃人怪物，很多这样七七八八的东西。}

#{1120}{Kill66}{Well, that's me. Where have you been?}
{1120}{Kill66}{那就是我啊。你走神了？}

#{1121}{Kill69}{Well, Doc owns a little place in the middle of town. Does
# a nice patch job if you need it. Fairly reasonable prices.}
{1121}{Kill69}{医生在镇中央有个小诊所，手术做得不赖，价格还算公道。}

#{1122}{Kill73}{That's my store. You need it, I got it.}
{1122}{Kill73}{就是我的店铺，你需要什么，我就供应什么。}

#{1123}{Kill75}{Ah, Gizmo's is the casino by the entrance. I'm surprised you didn't notice
# it on your way in. You can usually smell the place for miles. But
# hey, it brings in the tourists.}
{1123}{Kill75}{吉斯莫赌场就在城区出口处，你要是看不到那就怪了呢。这种地方是顶风也臭八百里，不过，好歹拉了些游客来。}

#{1124}{Kill76}{That's our resident bar. The food's okay, but the beer's great.
# The owner, Neal, takes no lip, not even from some of the Raiders that come in.}
{1124}{Kill76}{镇民常去的酒吧，料理做的不错，啤酒就更棒了。店主尼尔不是好惹的人，强盗都惧他三分的。}

#{1125}{Kill79}{Shady Sands? That's a little place up to the north. I'd like to do
# more trading with them.}
{1125}{Kill79}{沙荫镇？是北边的一个小镇子。我想和他们扩大贸易。}

#{1126}{Kill76}{That's our resident bar. The food's okay, but the beer's great.
# The owner, Neal, takes no lip, not even from some of the Raiders that come in.}
{1126}{Kill76}{镇民常去的酒吧，料理做的不错，啤酒就更棒了。店主尼尔不是好惹的人，强盗都惧他三分的。}
