{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a shifty looking character.}
{100}{}{你看见一个鬼头鬼脑的家伙。}

#{101}{}{Pssst! Come 'ere.}
{101}{}{嗤！借步说个话。}

#{102}{}{So'a, whatcha doin' in the Hub?}
{102}{}{那么，你来哈勃城做什么？}

#{103}{}{I don't really see where that is any of your business.}
{103}{}{我觉得这和你没有什么关系吧。}

#{104}{}{Why?}
{104}{}{怎么？}

#{105}{}{Looking for something that I need.}
{105}{}{我在找样东西。}

#{106}{}{Where my Mommie?!?}
{106}{}{我妈妈在哪里！？}

#{107}{}{Not really sure big fella.  I'll see ya around.}
{107}{}{没关系，大个子，那后会有期了。}

#{108}{}{Ahh.}
{108}{}{啊。}

#{109}{}{No sweat off my back.  Just seein' if I could be neighborly like. 【Lemmy turns away】}
{109}{}{没事没事，我就是看看我们能不能以后和睦相处。【莱米转身去了】}

#{110}{}{Well, you look like a businessman.  And I'm a businessman, and I thought we could, ah, discuss, ah, business.}
{110}{}{你看起来像生意人。我也是。我们，嘿嘿，也许可以做一笔。}

#{111}{}{Well, what do you do around here?}
{111}{}{你在这里做什么？}

#{112}{}{I think I'm just going to give you the business!}
{112}{}{我就给你个生意吃吃！}

#{113}{}{I don't think I want to have anything to do with your "business".}
{113}{}{我对你的“生意”毫无兴趣。}

#{114}{}{Well, we all got needs.  I might be able to help with some of 'em.  So what sort of needs do you got?}
{114}{}{我们都有需求，也许我可以帮你呢。你需要什么？}

#{115}{}{Well, I'm really looking for a Water Chip.  I need to get one back to my people.}
{115}{}{我在找一个净水芯片，我需要它来拯救人民。}

#{116}{}{Needs, huh?  I understand needs, but what might you know about satiating these needs?}
{116}{}{需求？我知道需求，但是你知道怎么满足需求？}

#{117}{}{I have need of some information.}
{117}{}{我需要情报。}

#{118}{}{I certainly don't need anything you might be talking about.}
{118}{}{我不需要你说的任何东西。}

#{119}{}{I do a little bit of this, and a little bit of that.  I get things and information for people,
# whatever they might need or be lookin' for.}
{119}{}{我做点这，做点那，我给人们带去消息和想要的东西，什么我都可以找到。}

#{120}{}{Well, I do need some things.}
{120}{}{嗯，我的确是在找东西。}

#{121}{}{Anything you can tell me about specifically?}
{121}{}{你能具体点吗？}

#{122}{}{I'm looking for a Water Chip.  You wouldn't happen to have one, would you?}
{122}{}{我在找净水芯片，你不会正好有一个吧？}

#{123}{}{I'll see you later.}
{123}{}{再见了。}

#{124}{}{Water Chip, hmmmm.  Don't think I've heard of one of those things.  If I's was you,
# I'd try the Water Merchants.  They got a grip on all the water around here.}
{124}{}{净水芯片，嗯。没听说过，我要是你，就去问纯水商人，他们负责这里的所有和水有关的交易。}

#{125}{}{So what do you do around here?}
{125}{}{你在这里做什么？}

#{126}{}{So what else might you know about?}
{126}{}{你还知道些什么？}

#{127}{}{Thanks for the information.}
{127}{}{谢谢你的信息。}

#{128}{}{Not a problem.  If there's anything else you might be wanting, you come and talk to Lemmy first.}
{128}{}{没问题。如果你还需要什么，就来问我莱米。}

#{129}{}{So, you're lookin' for information, huh?  Being a respectable businessman, I gots overhead, so I'll
# need a few caps to tell you what you need to know.  Now that we got that straight, whattcha' wanna' know about?}
{129}{}{你在找情报，对吧？作为一个受人尊敬的生意人，我的开销不小，所以要收取一点信息费。打开天窗说亮话，你想知道什么？}

#{130}{}{So, you think I might know a little more about those Water Chip things, huh?  Well, you might be right.
#  It's gonna' cost you, though.  I think 500 bottle caps oughta' do it.}
{130}{}{你觉得我知道这个净水芯片的事情，啊？太对了！不过，要收你点费用，500瓶盖怎么样？}

#{131}{}{Alright, what's the info?}
{131}{}{好，告诉我你知道的。}

#{132}{}{I'll give you 400 instead.}
{132}{}{我给你400吧。}

#{133}{}{I think you need to tell me, right now, and without the freakin' caps!}
{133}{}{你现在就告诉我，马上！我一个子儿也不给！}

#{134}{}{Too rich for my blood.}
{134}{}{我的钱不够。}

#{135}{}{Now, now.  I wouldn't be the man I am if I gave information away for less than it's
# worth.  Come back when you've got the caps.}
{135}{}{啧啧，贱卖不是我的风格，等你凑够了回来找我吧。}

#{136}{}{Trying to intimidate poor old Lemmy, huh?  Well, I's not afraid of the likes of you.
# I'll just be seein' you around.}
{136}{}{想要威胁我莱米这样的可怜老人？我不怕你这样的家伙，我走了。}

#{137}{}{【Lemmy takes your money】}
{137}{}{【莱米拿走了你的钱】}

#{138}{}{Well, that's fair enough.  I'll take that instead.}
{138}{}{好吧，那就这个价钱。}

#{139}{}{Ok, Ok, Ok, see I was just kidding about paying for the info.  Good joke, huh?}
{139}{}{好好好！我刚才说卖消息是开玩笑的，很好笑的笑话呢，对……对吧？}

#{140}{}{Well, so here's what I know about the Water Chips.  The thing I've heard is that they all used
# to come from the Vaults.  So if I was lookin' for one, I'd find out where the rest of these Vaults were.
# I'm not sure where all the Vaults are exactly, but I've heard that there are about 4 around here somewhere's.}
{140}{}{那我就告诉你吧。所有芯片都是避难所的，我要是想找芯片呢，就会去找那些避难所。我不知道这些避难所在哪里，但我知道这附近有4个。}

#{141}{}{I want to ask you a few more questions.}
{141}{}{我还要问你几个问题。}

#{142}{}{Thanks.}
{142}{}{多谢。}

#{143}{}{Sure, what else do you want to know about?}
{143}{}{没问题，还有啥想知道的？}

#{144}{}{Anything you know about Water Chips that you can tell me?}
{144}{}{净水芯片的消息有什么能告诉我的？}

#{145}{}{What do you know about Decker?}
{145}{}{你了解德克吗？}

#{146}{}{Do you know anything about the missing caravans?}
{146}{}{你知道失踪的商队吗？}

#{147}{}{Well, I'm looking for a certain commodity, if you know what I mean.}
{147}{}{我在找一种日用品，你明白吗。}

#{148}{}{Nothing right now.}
{148}{}{现在没有。}

#{149}{}{Now, normally I don't mind selling information, but you're not gonna' get anything outta' Lemmy about Mr. Decker.}
{149}{}{通常呢，我不介意卖点消息，但是德克先生的事情我可不说的。}

#{150}{}{Ok, but can I ask you about some other things?}
{150}{}{好，我能问问其他事情吗？}

#{151}{}{Thanks.}
{151}{}{谢了。}

#{152}{}{Missing caravans, huh?  Well, I might be knowin' a bit about those.  It's gonna cost you 300 caps, though.}
{152}{}{失踪的商队？我也许知道些，你要花300瓶盖。}

#{153}{}{Alright, what do you know?}
{153}{}{好。你知道什么？}

#{154}{}{I'll give you 240.}
{154}{}{我给你240吧。}

#{155}{}{I think you need to tell me, right now, and without the freakin' caps!}
{155}{}{你现在就告诉我，马上，别提那什么臭钱！}

#{156}{}{Too rich for my blood.}
{156}{}{我买不起。}

#{157}{}{Well, I'm not really that sure, but what I's heard is that it ain't what everybody thinks.
# Some new guy is getting into the action with some kind of mutants or something.  But don't quote
# me on that.}
{157}{}{其实呢，我也不肯定，但是我听说大家都猜错了。有新的势力在幕后策划，可能变种人之类的是受他们指使。但是我的话也不一定作数。}

#{158}{}{Figures.  Is there anything I can quote you on, Lemmy?}
{158}{}{明白了，你还知道什么能作数的事情，莱米？}

#{159}{}{Can I ask you another question?}
{159}{}{我再问你一个问题？}

#{160}{}{Thanks.}
{160}{}{多谢。}

#{161}{}{Now, you might be insinuating that Lemmy ain't a stand-up guy.  Well, you's right.  But Lemmy
# is an ALIVE type of guy.}
{161}{}{听着，你是在嘲笑我不是一个有种的男人。也许没错。但是，我莱米至少是一个不容易死掉的家伙。}

#{162}{}{Ok, forget about it.  Can I ask you another question?}
{162}{}{好吧，算了，我再问个问题。}

#{163}{}{Well, I'm going to make you a lying down and not breathing type of guy!}
{163}{}{好，我就要把你变成一个横躺着出不了气的家伙！}

#{164}{}{Forget about it.  See ya'.}
{164}{}{算了，再见。}

#{165}{}{Stuff for needs, huh?  Well, I knows a guy over in Old Town that can probably fix you up
# with some stuff like that.  But you know what?  He needs to know who you are before you show up
# at his doorstep.}
{165}{}{需要东西？我知道在旧城有一个家伙也许能帮你找到你要的东西。但是，他需要有人引荐你。}

#{166}{}{Let me guess.  This "invite" is going to "costs" me?}
{166}{}{我猜，这种“引荐”是要钞票的咯？}

#{167}{}{I can see where this is going.  I'll find him on my own.}
{167}{}{我知道了，我自己去找他。}

#{168}{}{Exactly.  So I'm thinking... only for you of course... 1000 caps so youse can talks to this guy
# without him blowing your head off first.}
{168}{}{太对了，我觉得……大概1000块钱就可以让这个人和你好好聊天而不是直接一枪打在你脑袋上。}

#{169}{}{Alright, I'll pay your price.}
{169}{}{很好，我付你这笔钱。}

#{170}{}{How about 800 caps instead?}
{170}{}{800怎么样？}

#{171}{}{Because you like me so much Lemmy, why don't you just do it for free? 【As you flex your muscles】}
{171}{}{你这么和我要好，干嘛不免费带我去呢？【你抖了抖野猪般的肌肉】}

#{172}{}{Can't afford that.}
{172}{}{付不起。}

#{173}{}{Well, what you gotta' do is find your way over to Old Town.  Over there is a guy
# named Vance.  Just talk to him.  Like I said, I'll let him know you're coming.}
{173}{}{呃，你去旧城区，找一个叫万斯的家伙，和他说，就可以了。}

#{174}{}{You're all heart.  Can I ask you a few more things?}
{174}{}{你真热心，我还能问点事儿吗？}

#{175}{}{Thanks.}
{175}{}{多谢。}

#{176}{}{Sorry man, got things to do.  Nice chattin' with you, though.}
{176}{}{对不起，我有事情要做，和你聊天很愉快。}

#{177}{}{Well, you've come back to talk to your old firend Lemmy, huh?  What's it I can
# help you with?}
{177}{}{哈，你回来找老朋友莱米说话了？我能帮你什么？}

#{178}{}{Well, you look like a businesswoman.  And I'm a in business, so I thought we could, ah, discuss, ah, business.}
{178}{}{你看起来像生意人。我也是。我们，嘿嘿，也许可以做一笔。}

