{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Just because you've got a weapon drawn doesn't mean that I'm gonna give
# you what you want . . .}
{100}{}{别以为你手里有家伙我就会怕你……}

#{101}{}{You've beaten me! What more do you want, dammit!}
{101}{}{你打了我！你还要干什么，我靠！}

#{102}{}{I don't got nothing to say! Talk is for the weak!}
{102}{}{我什么都不说！说话是弱者的能事！}

#{103}{}{I don't know who you are, but I'll give you a fair warning: anyone who
# messes with the Khans, dies messy.}
{103}{}{我不知道你是谁，但是我明白地警告你：谁敢和可汗帮过不去，死路一条。}

#{104}{}{You know, if you really thought you were stronger, you'd kill me.}
{104}{}{你要是真觉得你强，你就把我杀了！}

#{105}{}{Too bad. I'm messing with you!}
{105}{}{抱歉，我就要和你过不去！}

#{106}{}{Fine. Let's not mess with each other, and we'll be happy.}
{106}{}{好吧，我们井水不犯河水，大家高兴。}

#{107}{}{I surrender. Please don't kill me!}
{107}{}{我投降，别杀我！}

#{108}{}{Hngrrr!}
{108}{}{哼！！！}

#{109}{}{Huh?}
{109}{}{哈？}

#{110}{}{Hail brother Khan! How goes the hunt? Have many weaklings died today?}
{110}{}{嗨，可汗帮的老兄！买卖不错吧，杀了多少贱民？}

#{111}{}{Hail sister Khan! How goes the hunt? Have many weaklings died today?}
{111}{}{嗨，可汗帮的老姐！买卖不错吧，杀了多少贱民？}

#{112}{}{I will save my boasts for the campfire, but I have many tales to tell!}
{112}{}{我现在不想吹牛，我有很多事迹要说！}

#{113}{}{I have seen much blood and taken much plunder.}
{113}{}{他们流了很多血，我的收获不错。}

#{114}{}{Not bad. How about you?}
{114}{}{不错，你呢？}

#{115}{}{I've done better . . .}
{115}{}{我干得更棒……}

#{116}{}{You are an enemy of the Khans! You attack our warriors and take our women!
# Give me a reason why I shouldn't cut out your heart!}
{116}{}{你是可汗帮的敌人！你杀了我们的男人，抢了我们的女人！你倒是说一个不杀你的理由！}

#{117}{}{Cut the bravado. Where's Tandi? Tell me, or you die!}
{117}{}{少废话！坦蒂在哪里？说，要不你就是死人！}

#{118}{}{Can't think of anything. Let's fight!}
{118}{}{想不出，开打吧！}

#{119}{}{Because we'll both live if you don't try.}
{119}{}{你要是不动手，我们还都是活人。}

#{120}{}{I'm in no condition to fight. I surrender.}
{120}{}{我现在不在状态，我投降。}

#{121}{}{Are you one of them? One of the mutants?}
{121}{}{你是他们的成员之一？变种人？}

#{122}{}{What do you know about mutants?}
{122}{}{你知道什么关于变种人的事情？}

#{123}{}{Yeah, I'm a mutant!}
{123}{}{没错，我就是变种人！}

#{124}{}{Do I look like a mutant to you?}
{124}{}{我看起来像是变种人吗？}

#{125}{}{No.}
{125}{}{不。}

#{126}{}{Perhaps. If you wish to fight, I'll fight. If you wish to go in peace,
# you have my word as a Khan that I will not attack.}
{126}{}{也许。你如果想打，我就和你打。如果你想和平，那么以我一个可汗帮帮员的身份，我告诉你，我不会动手的。}

#{127}{}{Let's fight.}
{127}{}{打。}

#{128}{}{Let's not fight.}
{128}{}{不打。}

#{129}{}{Word of a Khan? What a joke!}
{129}{}{可汗帮的誓言？笑话！！}

#{130}{}{You are too strong for me, and I am tired by many days in the wastes. I do
# not wish to die. Though it shames me, I surrender.}
{130}{}{你太壮了，我这几天都在废土里，累得要死。我不想死。这是很丢人，但是我还是要投降。}

#{131}{}{I agree. I give my word that you may go in peace, provided that you do not
# provoke me. Do not trouble me again.}
{131}{}{同意，我们和平相处，只要你不要再来惹我。别来打扰我了。}

#{132}{}{I don't want anything that belongs to a coward, including your life! Get
# out of my sight!}
{132}{}{我不想要懦夫的任何东西，包括懦夫的生命！滚开！}

#{133}{}{You stupid animal. I shall enjoy killing you.}
{133}{}{你这个白痴的畜生，我就是要杀你为乐！}

#{134}{}{Uh, yes . . .}
{134}{}{呃，是的……}

#{135}{}{I shall enjoy hearing them. Farewell, brother!}
{135}{}{我也喜欢听他们尖叫。再见了，老兄！}

#{136}{}{I shall enjoy hearing them. Farewell, sister!}
{136}{}{我也喜欢听他们尖叫。再见了，老姐！}

#{137}{}{Really? Then I must have it for my own!}
{137}{}{是么？我自己去做！}

#{138}{}{Yes, I have heard that fortune heavily favors you. It is for that reason
# alone that I do not challenge you for your spoils. Farewell, my brother! May we
# next meet side by side in battle.}
{138}{}{是的，我听说你是福星高照啊。就因为这个，我也不想惹你。再见了，老兄！也许下次我们能并肩作战。}

#{139}{}{Yes, I have heard that fortune heavily favors you. It is for that reason
# alone that I do not challenge you for your spoils. Farewell, my sister! May we
# next meet side by side in battle.}
{139}{}{是的，我听说你是福星高照啊。就因为这个，我也不想惹你。再见了，老姐！也许下次我们能并肩作战。}

#{140}{}{I am tired and weary from a journey many days longer than I expected. Rad
# scorpions killed my companions. I long for the comforts of the camp and the
# healing caress of our women.}
{140}{}{我走了太长的路，精疲力竭。辐射蝎杀了我的战友。我希望能露个营，让我的女人照顾我一下。}

#{141}{}{May fortune again find favor with you. Farewell, my brother.}
{141}{}{祝你好运再来，再见，老兄！}

#{142}{}{May fortune again find favor with you. Farewell, my sister.}
{142}{}{祝你好运再来，再见，老姐！}

#{143}{}{They have destroyed Shady Sands. They kill anyone in their path. I never
# dreamt such ferocity existed. We are all doomed . . .}
{143}{}{他们踏平了沙荫镇。他们一路不留活口。我没见过这么凶残的行径。我们都活不了了……}

#{144}{}{Murdering dog!}
{144}{}{杀人狂！}

#{145}{}{No, but it is hard to tell. I have heard that they cloak themselves in
# night, that they cloud men's minds, and take the form of beautiful women!
# We are all doomed!}
{145}{}{不，很难的。我听说他们可以混在夜色之中无法追踪，他们可以摄人心魄，还可以化身变成美女，我们死定了！}

#{146}{}{That is good. I long to avenge our dead, and even the dead of Shady Sands.
# Any mutant that crosses my path will die! Go forth, friend! Go forth and kill!
# Death to the mutants!}
{146}{}{很好，我要为死去的战友、甚至是沙荫镇的百姓们报仇。那些变种人我要杀光他们！前进！朋友们！前进！杀杀杀！杀光变种人！}

#{147}{}{You will die for those words!}
{147}{}{你说这种话，你就要死！}

