{1099}{}{?}

{1199}{}{这个人似乎没什么可以告诉你的。}


{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a strong, stout man with a bushy beard.}
{100}{}{你看见一个胡子拉碴、长得五大三粗的男人。}

#{101}{}{You see MacRae.}
{101}{}{你看见麦克雷。}

#{102}{}{Hello Lad, what might you be looking for today?}
{102}{}{你好小伙子，今天你在寻找什么？}

#{103}{}{Hello Lass, what might you be looking for today?}
{103}{}{你好小姑娘，今天你在寻找什么？}

#{104}{}{Ai, What else would you be looking to know?}
{104}{}{哎，你还想知道些别的什么吗？}

#{105}{}{Who are you?}
{105}{}{你是谁？}

#{106}{}{What can you tell me about the Blades?}
{106}{}{关于利刃帮的事，你能告诉我些什么？}

#{107}{}{Nothing, thanks.}
{107}{}{没了，多谢。}

#{108}{}{Well, I'm MacRae.  I help the Blades some against the Deathclaws and that Regulator bunch.
#  Teach'em a bit about protectin 'emselves against those nasties.}
{108}{}{嗯，我是麦克雷。我帮助利刃帮对抗死亡爪和那些管理者。教他们如何在那些坏蛋面前保护他们自己。}

#{109}{}{What kind of stuff do you teach them?}
{109}{}{你教他们什么东西？}

#{110}{}{Have you seen the Deathclaws?}
{110}{}{你见到过死亡爪吗？}

#{111}{}{What's the deal with the Regulators}
{111}{}{管理者有什么问题？}

#{112}{}{Can I ask you something else?}
{112}{}{我能问你些别的事情吗？}

#{113}{}{Well m' specialty is fightin with my fists, and takin a punch or two more than 
#the guy throwin 'em at me.}
{113}{}{嗯……我拿手的是空手格斗，在对方出拳打我之前，我可以更快的打出一两拳。}

#{114}{}{Sounds like a dumb idea, I'd rather use a gun.}
{114}{}{听起来像是个白痴想法,我宁可用枪。}

#{115}{}{Do you think you could teach me anything?}
{115}{}{你认为你能教我些什么？}

#{116}{}{Can I ask you something else?}
{116}{}{我能问你些别的吗？}

#{117}{}{Well if that's how you be feeling, you can just turn yourself around and walk away.}
{117}{}{好吧，如果你这么认为，你现在就可以转身滚蛋了。}

#{118}{}{You seem to be an alright lad, but me times busy with keeping the Blades schooled.  If 
#things were to straighten themselves, I might be havin the time then.}
{118}{}{你似乎是个好小伙儿，但是我正忙着教利刃帮。假如现在手头儿上的事情不这么复杂的话，我也许会有些时间。}

#{119}{}{Alright, can I ask you something else?}
{119}{}{好吧，我还能问你些别的事情吗？}

#{120}{}{Thanx for the info.}
{120}{}{谢谢你的信息。}


#{121}{}{Seen em I have.  Ran like hell, I did.  If yer lookin for 'em, you'll find 'em over there. 
#【MacRae points over to the east】}
{121}{}{我曾经见它们。当时我是屁滚尿流的跑开了。如果你想找它们，会在那边找到的。【麦克雷指了指东边】}

#{122}{}{I was thinkin the Deathclaws were the spawn of an unnatural act, but 'em Regulators are evil.  
#Come once a month or so and they shows their ugly faces and drag a father away from is wee ones.}
{122}{}{我之前一直认为死亡爪是非自然事件产生的物种，但是管理者，作为人类，他们却是一帮邪恶的混蛋。他们差不多每月来一次，到这里寻衅滋事，杀人害命，让弱小的孩子们失去父亲的保护。}

#{123}{}{Anything I could do to help?}
{123}{}{我可以帮你做什么？}

#{124}{}{Sounds bad, could I ask you another question?}
{124}{}{听起来是很坏，我能问你别的问题吗？}

#{125}{}{Thanks for the info.}
{125}{}{谢谢你的信息。}

#{126}{}{You be wantin to talk to Razor.  A good lass if there ever was one.}
{126}{}{你去和剃刀谈谈吧。她可是个好姑娘。}

#{127}{}{A good group of people is what the Blades are.  Stuck ere between the damn Regulators and the 
#Deathclaws ain't meant the happiest life for em, but they survive.}
{127}{}{利刃帮可是一群好人。周旋于那些混蛋管理者和死亡爪之间，对利刃帮来说这并不意味着是他们最好的生活，但是他们还是顽强的生活着。}

#{128}{}{【MacRae claps you on the back】 Thanks to you, the Blades are going to live a better life.  So, 
#what can an old Scotsman do for ya?}
{128}{}{【麦克雷拍了拍你的后背】谢谢你，你的所作所为让利刃帮能活得更好。那么，我这个苏格兰老头儿能为你做些什么？}

#{129}{}{You had said earlier that if you had some free time, you could teach me a few things.}
{129}{}{你曾经说过，如果你有时间的话，你也许能教我些东西。}

#{130}{}{What have you been doing lately?}
{130}{}{你最近干了什么？}

#{131}{}{What do you do around here?}
{131}{}{你在这儿干吗？}

#{132}{}{Not a problem.}
{132}{}{没问题。}

#{133}{}{Well it's been a wee bit quiet since the Blades helped out Adytum with the Regulators.  Me 
#teaching services haven't been in such demand.}
{133}{}{嗯……自从利刃帮帮助内城对抗那些管理者以后，这地区就稍微安宁了些。我所能提供的帮助也不是那么炙手可热了。}

#{134}{}{What do you teach?}
{134}{}{你都教些什么？}

#{135}{}{Sorry to hear that, hope things get more interesting?}
{135}{}{很遗憾听到那些，希望事情能有转机吗？}

#{136}{}{Could you teach me?}
{136}{}{您可以教我吗？}

#{137}{}{Sounds interesting, but I gotta get going.}
{137}{}{听起来很有趣，但是我必须要走了。}

#{138}{}{Well I guess I do have the time.  Might as well start right now. 【MacRae starts showing you some 
#fighting stances, and ways to take punches like a true Scotsman.】}
{138}{}{好吧，我想我现在的确有些时间。也许我们最好现在就开始。【麦克雷开始向你演示一些格斗招式，以及如何像一个真正的苏格兰人那样出拳的方法。】}

#{139}{}{You be a quick learner.  Hope that helps you in your travels.}
{139}{}{你学得很快。希望你所学到的能在你的旅行中能有所帮助。}

#{140}{}{Well I used to be helpin the Blades out by teachin them a few things about protectin themselves 
#against the DeathClaws and the Regulators.  Now with you takin care of all that, things have been a wee 
#bit on the boring side lately.}
{140}{}{嗯……我过去一直对利刃帮传授经验以便他们能对抗死亡爪和管理者。现在由于你搞定了那些麻烦，我最近的生活开始变得有那么一点点无聊了。}

#{141}{}{Good seein ya.}
{141}{}{见到你很高兴。}


