{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a mad scientist. He is working diligently on something.}
{100}{}{你看见一位疯狂的科学家。他正在努力的研究着什么。}

#{101}{}{Good evening, brother. What brings you to our little corner of heaven?}
{101}{}{晚上好，兄弟。是什么风把你吹到我们这个小乐园的？}

#{102}{}{Good evening, sister. What brings you to our little corner of heaven?}
{102}{}{晚上好，姐妹。是什么风把你吹到我们这个小乐园的？}

#{103}{}{I'm here to check on your progress.}
{103}{}{我是来检查你的进度的。}

#{104}{}{What might you be doing here?}
{104}{}{你在这能做什么？}

#{105}{}{What?! You dare question me? How about I experiment on your brain,
# you twisted skag?!}
{105}{}{什么？！你胆敢质问我？你这个坏家伙！让我拿你的脑子做做实验怎么样？}

#{106}{}{Gack.}
{106}{}{咯咯。}

#{107}{}{You, again? And why are you disturbing the Master's glorious
# future this time?}
{107}{}{又是你？你怎么又来妨碍主教的光荣事业？}

#{108}{}{The Master grows impatient with your failures, and I with your
# impudence!}
{108}{}{主教对你的失败越来越不耐烦了，而我也对你的厚颜无耻越来越讨厌了！}

#{109}{}{I want to know what's happening with your experiments.}
{109}{}{我想要知道你的实验怎么样了。}

#{110}{}{That's it, I'm putting an end to YOUR future right here and now, chump!}
{110}{}{没错儿，我此时此刻就是要给你的人生画上一个句号的，你这个笨蛋！}

#{111}{}{Oofah!}
{111}{}{啊！}

#{112}{}{It's not going well. I've been injecting the FEV directly into the
# pineal gland, but I'm not getting the results I'd hoped for.}
{112}{}{进展并不顺利。我一直在把FEV病毒直接注射到松果体，但是没有得到我所期待的结果。}

#{113}{}{Why don't you try injecting it  into the Amygdala?}
{113}{}{你为什么不试试把它注射到扁桃腺？}

#{114}{}{Why don't you try injecting it into the Medula?}
{114}{}{你为什么不试试把它注射到骨髓？}

#{115}{}{What results are you getting?}
{115}{}{你得到了什么结果？}

#{116}{}{Hmmm. And?}
{116}{}{嗯……结果如何？}

#{117}{}{I beg your forgiveness, sir. How may I be of service?}
{117}{}{我请求您的宽恕，先生。我能帮您做些什么？}

#{118}{}{I beg your forgiveness, ma'am. How may I be of service?}
{118}{}{我请求您的宽恕，夫人。我能帮您做些什么？}

#{119}{}{You can speak to me with respect next time, or you'll never speak to
# anyone again!}
{119}{}{你下次跟我说话要尊敬点，否则你就再也无法讲话了！}

#{120}{}{The Master's truth is revealed, resulting in increased psychic
# ability. 【shakes his head】 But the poor souls become terminally insane and
# must be sequestered and nullified to keep them from harming themselves or
# others.}
{120}{}{主教真理被揭示了，精神能力会增强。【摇头】但是那些可怜的灵魂会变得极端的狂暴，所以他们必须被隔离，被销毁，这样才会保证他们不伤害自己或其它人。}

#{121}{}{Oh, how thoughtful of you...}
{121}{}{哦，你想的真周到啊……}

#{122}{}{Where are they being kept？}
{122}{}{他们被关在哪里？}

#{123}{}{You heartless butcher! I think I'll nullify your brain and sequester
# it from the rest of your body! Die, you bastard!}
{123}{}{你这个无情的刽子手! 我倒是要把你的脑子从你的身体里隔离出来然后销毁!去死，你这个王八操的！}


#{124}{}{In a room northwest of here. Is there anything else I can help you with?}
{124}{}{在这西北部的一个房间里。还有别的事情需要我帮忙吗？}

#{125}{}{Thank you for your help. Bye.}
{125}{}{感谢你的帮助。再见。}

#{126}{}{Yeah, uh. What's FEV?}
{126}{}{呀，嗯。什么是FEV？}

#{127}{}{You can die!}
{127}{}{你给我死吧！}

#{128}{}{I have no time for your tomfoolery!}
{128}{}{我可没时间理会你的愚蠢行为！}

#{129}{}{What an intriguing idea! I must try it at once!}
{129}{}{这是一个多么令人感兴趣的想法啊！我必须马上试试！}

#{130}{}{Uh, where are you keeping the failed experiments?}
{130}{}{呃，你实验的失败品在哪？}

#{131}{}{Don't mention it.}
{131}{}{别提了。}

#{132}{}{Yeah! Let's try it on you!}
{132}{}{对啊！让我在你身上试试！}

#{133}{}{Vincent! Prepare our newest volunteer!}
{133}{}{文森特！准备我们最新的志愿者！}

#{134}{}{What? That's the most ludicrous thing I've ever heard! 【looks at
# you suspiciously】 Who are you, really?}
{134}{}{什么？那是我听到的最可笑的事！【怀疑的看着你】你到底是谁？}

#{135}{}{Oh, sorry. I've got to go now.}
{135}{}{哦，对不起。我现在必须走了。}

#{136}{}{I'm a new..uh...guy.... I've been sent to find out how you are doing.}
{136}{}{我是一个新……呃……人……我被派来看看你做得怎么样了。}

#{137}{}{I already told you, I've been sent by the Master to check up on you.}
{137}{}{我已经告诉你了，是主教派我来看看你做得怎么样了。}

#{138}{}{I've come to remove your spleen... without anesthetic!}
{138}{}{我要切除你的脾脏了……不用麻醉剂！}

#{139}{}{Alright, then. So how is it going?}
{139}{}{那么好吧，事情进展如何？}

#{140}{}{Your attitude has told me all I need to know. Goodbye.}
{140}{}{从你的态度我已经知道了我想要的一切。再见。}

#{141}{}{Ah ha! An interloper! Just as I suspected. Vincent!}
{141}{}{啊哈！一个闯入者！正如我猜测的那样。文森特！}

#{142}{}{Who are you? And why are you wearing that suit? 【to himself】 I haven't
# seen one of those in a long time.}
{142}{}{你是谁？你为什么穿着那种衣服?【对他自己说】我已经很久没有看到这样的衣服了。}

#{143}{}{I'm in disguise. Intruders have infiltrated the Master's sanctuary,
# and I'm dressed like one of them to gain their confidence.}
{143}{}{我是在伪装。入侵者已经渗入主教的庇护所，我穿得和他们一样以取得他们的信任。}

#{144}{}{How dare you question one of the Master's special operatives!}
{144}{}{你怎么胆敢询问主教的特派员！}

#{145}{}{When have you seen a suit like this before?}
{145}{}{你以前看见过像这样的衣服？}

#{146}{}{It's extruded rubber, so it's real easy to wipe your blood off after
# I kill you!}
{146}{}{这是压制橡胶，所以在我杀了你之后擦干净你的血是件很容易的事情。}

#{147}{}{Oh, you know, when we got that last batch of pure-strain humans in...
# I think there is still one in the holding pens. Why do you ask?}
{147}{}{噢，你知道，当我们抓住最后一批纯种人时……我认为在拘押栏中还有一个。你为什么要问这个？}

#{148}{}{No reason. How are the experiments going?}
{148}{}{没有理由。实验是如何进行的？}

#{149}{}{I've got to report back to the Master. I don't have time for this.}
{149}{}{我没时间，我必须回去报告主教。}

#{150}{}{【shakes his head】 Alas, the poor souls become terminally insane and
# must be sequestered and nullified to keep them from harming themselves or
# others.}
{150}{}{【摇头】哎，那些可怜的灵魂会变得极端的狂暴，所以他们必须被隔离，被废掉，这样才会保证他们不伤害自己或其它人。}

#{151}{}{Oh, how thoughtful of you...}
{151}{}{噢，你想的真周到啊……}

#{152}{}{You heartless bastard! I think I'll nullify your brain and sequester
# it from the rest of your body! Die, you bastard!}
{152}{}{你这个冷血的杂种! 我倒是要把你的脑子从你的身体里隔离出来然后废掉!去死吧，你这个杂种！}

#{200}{}{You see Vincent, a super mutant guard. He looks bored.}
{200}{}{你看见文森特，一个超级变种人警卫。他看起来很无聊。}

#{201}{}{You see a super mutant, obviously guarding the scientists. He looks
# bored}
{201}{}{你看见一个超级变种人，很明显他在保卫着科学家们。他看起来很无聊。}

#{202}{}{Intruders!}
{202}{}{入侵者！}

#{203}{}{I'm just watching the mads. Don't talk to me.}
{203}{}{我正在守护着这些疯子们。不要和我说话。}

#{204}{}{Leave me alone.}
{204}{}{别理我。}

#{300}{}{You see a sleeping mad scientist.}
{300}{}{你看见一位睡着的疯狂科学家。}

#{301}{}{Zzzzzz}
{301}{}{ZZzzz}

#{302}{}{Huh! What? 【rubs eyes】 Vincent, remove this heathen from our chambers!}
{302}{}{哼！什么？【擦眼睛】文森特，把这个野蛮人从我们的房间弄走！}

#{303}{}{Huh? 【snort】 ...zzzzzzzzz}
{303}{}{哼？【打鼾】……Zzzzzz}

#{400}{}{You see Vincent. He is guarding the sleeping mads.}
{400}{}{你看见文森特．他正在守护着疯狂的科学家。}

#{401}{}{You see a super mutant guard. He is nearly standing over the prone bodies.}
{401}{}{你看见一个超级变种人警卫。他几乎站着睡着了。}

#{402}{}{Leave them alone, and get out. No one is allowed in here while they
# are sleeping.}
{402}{}{别打扰他们，离开这儿。在他们在睡觉的时候，不允许有人在这里。}

#{403}{}{You again! I told you to leave the scientists alone!}
{403}{}{又是你！我告诉过你别打扰那些科学家！}

#{404}{}{You have overstayed your welcome.}
{404}{}{你在这儿待的太久，该滚了。}

