{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Mathia.}
{100}{}{你看见马蒂雅。}

#{101}{}{Hello, Initiate. So, you are the one who made it out
#of the Ancient Order alive.}
{101}{}{你好，新兵。看来你就是那个把磁盘从远古遗迹【闪光之地】活着拿回来的人。}

#{102}{}{Wha?}
{102}{}{什么？}

#{103}{}{And who are you?}
{103}{}{你是谁？}

#{104}{}{Sorry, I thought you were someone else. Bye.}
{104}{}{抱歉，我认错人了。再见。}

#{105}{}{The name is Mathia. I am officially Maxson's assistant, but
#I am also here to make sure no one messes with the old man.}
{105}{}{我的名字叫马蒂雅。职务上我是马克松将军的助手，但我还要确保没人打扰这个老头。}

#{106}{}{Old man? That sounds a bit disrespectful.}
{106}{}{老头？这个称呼是不是有点不妥。}

#{107}{}{What do you do as Maxson's assistant?}
{107}{}{身为马克松将军的助手都负责什么？}

#{108}{}{Good to meet you. Bye.}
{108}{}{见到你很高兴。再见。}

#{109}{}{No, no, not at all. He's a good guy. (Jokingly) Besides,
#I wouldn't bad mouth him while he is standing next to me.}
{109}{}{不，不，绝对不是。他是一个好人。【开玩笑】此外，他站在我身边时我从不说他坏话。}

#{110}{}{So, what is it that you do for Maxson as his assistant.}
{110}{}{那么，你身为马克松将军的助手都做什么？}

#{111}{}{Goodbye.}
{111}{}{再见。}

#{112}{}{I take care of all the paper work. He could not do paperwork to save his life. Also, if he clears a Weapons Upgrade for oneof the Brothers, I process the order.}
{112}{}{我负责所有的文书工作。他如果干这些简直是要了他的命。所以，如果他命令为某位兄弟升级武器，我就处理相应的工作。}

#{113}{}{Ok, thanks for the information.}
{113}{}{好，谢谢你告诉我这些事情。}

#{114}{}{I can't believe an idiot like you is the one who made the
#Ancient Order run. Go figure.}
{114}{}{真不敢相信你这样的一个白痴能让远古遗迹【闪光之地】重新运转起来。想想看吧。}

#{115}{}{Hello again Initiate. How can I help you?}
{115}{}{真高兴再见到你，新兵。我能为你做点什么？}

#{116}{}{Wha?}
{116}{}{什么？}

#{117}{}{I'm sorry, I forgot your name.}
{117}{}{对不起，我忘了你叫什么。}

#{118}{}{Sorry, I thought you were someone else. Good day.}
{118}{}{抱歉，我认错人了。日安。}

#{119}{}{Alright, let's go. (He grabs you by the arm)}
{119}{}{好，我们走。【他抓住你的胳膊】}

#{120}{}{Uh huh.}
{120}{}{呃呼。}

#{121}{}{Uh uh.}
{121}{}{呃唔。}

#{122}{}{Alright, Alright. I'm moving.}
{122}{}{好吧，好吧，我走。}

#{123}{}{Get the hell away from me. I'm not going anywhere.}
{123}{}{你他妈的离我远点。我哪也不去。}

#{124}{}{Ok. Maxson has cleared a weapons upgrade for you. What would
# you like?}
{124}{}{好的，马克松将军命令我升级你的武器装备。你想要什么？}

#{125}{}{Wha?}
{125}{}{什么？}

#{126}{}{Sniper Rifle.}
{126}{}{狙击来福枪。}

#{127}{}{Rocket Launcher.}
{127}{}{火箭筒。}

#{128}{}{Laser Pistol.}
{128}{}{雷射手枪。}

#{129}{}{Power Fist.}
{129}{}{动力拳套。}

#{130}{}{Ripper.}
{130}{}{开膛手。}

#{131}{}{There you go. Glad you are on our side Initiate.}
{131}{}{拿好。欢迎你加入我们的队伍，新兵。}

#{132}{}{The Elders have called a meeting. They wish you to meet them in the
# conference room right away.}
{132}{}{元老们召开了一个会议。他们希望你能马上到会议室见他们。}

#{133}{}{Where is the conference room?}
{133}{}{会议室在哪里？}

#{134}{}{Ok, thank you.}
{134}{}{好的，谢谢你。}

#{135}{}{It's on this floor. The northeast corner, right behind the assembly hall.}
{135}{}{就在这一层。东北角，会议大厅的后边。}
