
#{100}{}{You see a battered man.}
{100}{}{你看见一个被狂扁过的男人。}

#{101}{}{Thank you stranger! I don't know how many weeks, perhaps months, those thugs have
# had me here. I'm very grateful for your help, and I'm sure the Brotherhood of Steel is also.}
{101}{}{谢谢你陌生人！我已经不知道过了几个礼拜了，大概有一个月了，那些恶棍一直在囚禁我。对你的帮助我感激不尽，钢铁兄弟会也会同样感激你的。}

#{102}{}{Brotherhood of Steel?}
{102}{}{钢铁兄弟会？}

#{103}{}{Well, I'm glad that I could help.}
{103}{}{没关系，我很高兴我能帮上忙。}

#{104}{}{Are you going to be okay?}
{104}{}{你还好吗？}

#{105}{}{I'm from the Brotherhood. I've been looking for you.}
{105}{}{我来自钢铁兄弟会。我一直在找你。}

#{106}{}{You're welcome. Bye.}
{106}{}{不客气，再见。}

#{107}{}{Uh.}
{107}{}{哦。}

#{108}{}{You haven't heard of us? I'm really surprised. You must not leave the Hub very often. You
# should get out more. We're northwest of here, on the west side of the mountain range.}
{108}{}{你没有听说过我们？我真的感到很惊讶。你不能一直呆在哈勃城。你应该到处走走。我们在哈勃城的西南方向，西边的山脉上。}

#{109}{}{I really appreciate you helping me, but why are you trying to lie to me? Do you not think
# I know every member of our order?}
{109}{}{我对你的帮助心存感激，但你不该骗我，你应该想到组织里的每个人我都认识。}

#{110}{}{Talus sent me.}
{110}{}{塔鲁斯派我来的。}

#{111}{}{Well, you don't know me, because I just joined.}
{111}{}{嗯，你之所以不认识我，是因为我刚刚加入钢铁兄弟会。}

#{112}{}{You obviously don't know what you're talking about.}
{112}{}{你明显不知道你自己在说什么。}

#{113}{}{Thanks again! If you stop by the Brotherhood, I'd appreciate it if you could let Talus know I'm
# okay. I'm sure he's worried. Bye, and take care.}
{113}{}{再次谢谢你！如果你到了钢铁兄弟会，请告诉塔鲁斯我现在很好。我知道他很担心。再见，路上小心。}

#{114}{}{Oh, I'll be fine now, thanks. I have some friends here that I can stay with while I regain my strength. I'll try to send word to the Brotherhood to let them know that I am safe now, thanks to you. Bye}
{114}{}{哦，我会好起来的，谢谢。我有一些朋友在这里，他们可以照顾我直到我完全恢复。我会试着捎口信到兄弟会告诉他们我现在很安全，谢谢你，再见。}
#{115}{}{How?Oh, I'm sorry. You must have passed that "test" the Elders made up. I completely forgot
# about that. Well, my thanks goes even deeper. I'm glad you never gave up. My life could have been in jeopardy at any moment. It must have taken you a while to hunt me down. This city is huge. The obstacles you must have overcome.}
{115}{}{什么？哦，对不起。你应该通过了元老的“测试”。我都忘了。好吧，非常感谢你。很高兴你一直坚持不懈。我总是处在危险中。再迟一会我就会被他们打死。这个地方很大。你要处处小心。}

#{116}{}{Well, you know?I'm just that good.}
{116}{}{嗯，你知道吗？我那仅仅是运气好。}

#{117}{}{Actually, it was quite easy. Talus knew where you went.}
{117}{}{实际上这很容易。塔鲁斯知道你去什么地方了。}

#{118}{}{Just lucky I guess.}
{118}{}{我猜仅仅是运气好而已。}

#{119}{}{Well, you're welcome. I'm just glad I found you.}
{119}{}{不用谢，我很高兴能找到你。}

#{120}{}{Oh?Well, I'm still very grateful.}
{120}{}{哦？好吧，我仍然很感谢你。}

#{121}{}{I guess so. that was some fine handy work you did.}
{121}{}{我想那对你来说是举手之劳。}

#{122}{}{Well, I'm glad I could help.}
{122}{}{我很高兴能帮上忙。}

#{123}{}{Are you going to be okay?}
{123}{}{你还好吗？}

#{124}{}{Well, thanks again. I am going to stay with some friend of mine until I regain my strength. By the
# way, I'd watch it around here. I heard my hosts talking about some Thieves' Circle. I guess we're close to
# their territory or something. I think that might be why they were talking about moving to a different
# location. Bye.}
{124}{}{很好，再次感谢你。我要到我朋友那里休养一段时间，直到我恢复健康。顺便说一下，我以前在这里听人说过小偷公会。我猜我们离他们的地盘太近了。他们可能正在商量要搬到其它地方。再见。}

#{125}{}{Well, I'm glad your luck held out. I've heard some bad things about Old Town. The skags are creepy, I
# think it's something else.}
{125}{}{很好，我很高兴你能救我出去。我听说旧城区发生了一些不好的事情。那些人鬼鬼祟祟的，我想一定有什么事情发生。}

#{126}{}{Whatever you say. I'm just grateful to be free again. I don't take well to torture.}
{126}{}{无论你怎么说。我非常感谢你让我获得自由。我不用再受折磨了。}

#{127}{}{No, really, Talus sent me.}
{127}{}{不，我真的是塔鲁斯派来的。}

#{128}{}{Well, I'm glad i could help.}
{128}{}{我很高兴能帮上忙。}

#{129}{}{Are you going to be okay?}
{129}{}{你还好吧？}

#{130}{}{Maybe not. I've been having trouble remembering things. I think it was something they fed me.}
{130}{}{也许不是。我的记忆力好像有点问题了。我想他们大概给我吃了什么东西。}

#{131}{}{No, really, Talus sent me.}
{131}{}{不，我真的是塔鲁斯派来的。}

#{132}{}{Well, I'm glad I could help.}
{132}{}{我很高兴能帮上忙。}

#{133}{}{Are you going to be okay?}
{133}{}{你还好吗？}

#{134}{}{Hello again.}
{134}{}{很高兴再次见到你。}

#{135}{}{I'm leaving soon. Just gathering my strength.}
{135}{}{我就要离开了。我得再休息一会来养足力气。}

#{136}{}{Thanks again.}
{136}{}{再次感谢你。}


#// Tell me abouts

{1099}{}{?}
{1199}{}{我可以告诉你：Brotherhood-兄弟会、Steel-钢铁、Talus-塔鲁斯。}


{1000}{}{Brotherhood}
{1001}{}{Steel}
{1002}{}{Talus}

#// Answers
#{1100}{}{The only salvation this tortured planet and its people have.  Without them, humanity is sure to perish.}
{1100}{}{唯一能拯救这个世界上所有受苦平民的组织。没有他们，世界就会灭亡。}

#{1101}{}{The only salvation this tortured planet and its people have.  Without them, humanity is sure to perish.}
{1101}{}{唯一能拯救这个世界上所有受苦平民的组织。没有他们，世界就会灭亡。}

#{1102}{}{He is my mentor and a great man.  I look forward to seeing him once again.}
{1102}{}{他是一个伟大的人，我的良师益友。我希望能再次见到他。}
