{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see a technician. He is working diligently for the Unity and the Master.}
{100}{}{你看见一个技师。他正在勤奋的为主教的“同一事业”工作。}

#{101}{}{We do the work of the Master.}
{101}{}{我们为主教而工作。}

#{102}{}{We do the work of the Master, and we cannot be interrupted!}
{102}{}{我们正在为主教工作，不要骚扰我们。}

#{103}{}{Master! An intruder!}
{103}{}{主教！一个入侵者！}

#{200}{}{You see Viscious, a super mutant leader. He looks mean.}
{200}{}{你看见超级变种人队长维舍斯。他看起来让人感到恶心。}

#{201}{}{You see a mean-looking super mutant.}
{201}{}{你看见一个让人恶心的超级变种人。}

#{202}{}{The will of the Master prevails. What news do you have for me?}
{202}{}{主教必将胜利。你有什么消息告诉我？}

#{203}{}{Hng!}
{203}{}{呼！}

#{204}{}{Uh, the war goes well.}
{204}{}{嗯，战争很顺利。}

#{205}{}{I have a message for the Master from his Lieutenant. I must see the Master now.}
{205}{}{副官让我给主教大人捎个信，我现在就要见他。}

#{206}{}{The only news that I have is that you're about to become fertilizer.}
{206}{}{唯一的消息就是你马上要变成原料了。}

#{207}{}{An intruder!}
{207}{}{一个入侵者！}

#{208}{}{Your manner betrays you, intruder. I will end the threat here.}
{208}{}{你的表情出卖了你，入侵者。我现在就会清除你对我们的威胁。}

#{209}{}{You cannot be serious. In fact, you must be lying.}
{209}{}{开什么玩笑。你一定是在扯谎。}

#{210}{}{Uh, yeah, so what?}
{210}{}{啊，好，那又如何？}

#{211}{}{I'm not. The Lieutenant could not trust this message to the usual method. I have to see the Master right now! There is no time to waste!}
{211}{}{不是。中尉无法确信常规的方法可以传送这个消息。我必须立刻见主教！不能在这里浪费时间！}

#{212}{}{Then use the door, and beware the Corridor. I assume that you haveyour protection in place?}
{212}{}{从那里走，走廊上要注意，我想你做好了保护措施。}

#{213}{}{Of course. Thank you. Unity prevails.}
{213}{}{当然。谢谢你。“同一”必胜！}

#{214}{}{No, not really. Should I?}
{214}{}{不，还没，那我应该怎么做？}

#{215}{}{Of course! You cannot hope to pass the Corridor without it. What didyou do with your nullifier!}
{215}{}{当然！没有保护装置你别想通过走廊。你把精神攻击免疫器弄到哪去了？}

#{216}{}{I left it in my other robes.}
{216}{}{我把它落在我另一件长袍里了。}

#{217}{}{The Lieutenant did not have time to give me one.}
{217}{}{中尉没来得及给我一个。}

#{218}{}{Ah, humor, I like that. 【pauses】 I do not have one, obviously. Youneed to go get one from the braindrains on the second level. Unity prevails.}
{218}{}{啊，幽默，我喜欢。【停顿】很明显我没有。你需要到二层的洗脑室去拿一个。“同一”必胜！}

#{219}{}{Then he was a fool, or you are not who you seem to be. What is it?}
{219}{}{要么他是个笨蛋，要么你有问题，你到底是怎么回事？}

#{220}{}{Obviously, he is a fool.}
{220}{}{很明显，他是个白痴。}

#{221}{}{The second part.}
{221}{}{第二个可能。}

#{222}{}{Move alone and continue your mission. I haven't the time for you.}
{222}{}{快走，继续你的任务。我没时间和你耗了。}

#{300}{}{There is a small pile of cigarette butts in the corner of the room.}
{300}{}{房间的一侧烟头已经被堆成了小山。}

#{301}{}{The super mutant walks to one side of the room, and lights up acigarette.}
{301}{}{一个超级变种人在房间一侧走动，用打火机点着了一支香烟。}

#{302}{}{You see a super mutant with a cigarette dangling from his mouth.}
{302}{}{你看到一个超级变种人，他的嘴里叼着一支香烟。}

#{303}{}{The super mutant flicks the butt into the corner.}
{303}{}{超级变种人把烟头用手指一弹，烟头掉到了角落里。}

