{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{The robot is non-functional. The layer of dust on it suggests that it
# hasn't been active recently.}
{100}{}{这是个失效的机器人。从上边的一层灰尘来看它最近都没动过。}

#{101}{}{The robot has been repaired, but it is still not functioning.}
{101}{}{这个机器人已经被修好了，但是它仍然没反应。}

#{102}{}{The hardware is not a problem, it must be the software.}
{102}{}{硬件没有问题，它必须安装软件。}

#{103}{}{You cannot access the robot's functions, as it is disabled.}
{103}{}{你不能访问机器人的系统，因为它被禁用了。}

#{104}{}{You tinker with the malfunctioning components, but need more time to make
# the fix.}
{104}{}{你胡乱修复故障部分，但是需要更多的时间来修复。}

#{105}{}{You reboot the onboard computer, and successfully restart the robot.
# You notice that the robot's radio is broken.}
{105}{}{你重新启动了机载电脑，而且顺利的重新启动了机器人。你注意到机器人的无线电设备坏掉了。}

#{106}{}{You spend some time working on the robot's computer, but cannot get it
# restarted.}
{106}{}{你在这个机器人电脑上花了很多时间，但是没有让它重新启动。}

#{107}{}{Unit #462 online. Self-test. Adjusting unit location data. Fixed.
# Rebuilding memory file. Fixed. Error - task incomplete.}
{107}{}{462号单位在线。测试。调整单元位置数据。修复。重新建立存储文件。修复。错误－任务未完成。}

#{108}{}{Rogga.}
{108}{}{诺嘎。}

#{109}{}{What is your incomplete task?}
{109}{}{什么是任务未完成？}

#{110}{}{Well, just do it and get out of my way!}
{110}{}{很好，该干什么干什么，别妨碍我！}

#{111}{}{【Click】 Okey-dokey! Restarting task.}
{111}{}{【点击】搞定！重新启动任务。}

#{112}{}{Unit #462 is a cleaning model. Must finish cleaning and maintenance of
# this level.}
{112}{}{462号单位是一个清洁模式。必须完成本层的清洁和维护。}

#{113}{}{Go to it!}
{113}{}{立刻去执行！}

#{114}{}{What do you have left to clean?}
{114}{}{你要清理什么地方？}

#{115}{}{Vat Control Room. 【Click】 End of list.}
{115}{}{病毒槽控制室。【点击】结束列表。}

#{116}{}{Heh. Finish your task.}
{116}{}{嗯，你完成了任务。}

#{117}{}{You gain 1000 experience points for doing a little clean-up work.}
{117}{}{因为完成了一个小的清洁工作，你获得了1000点经验值。}
