{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Neil, the head of the guard for the Followers.}
{100}{}{你看到尼尔，末世论者守卫的头领。}

#{101}{}{You see Neil, the head of the guard for the Followers.}
{101}{}{你看到尼尔，末世论者守卫的头领。}

#{102}{}{If you seek someone to talk to, talk to Peter. I'm
# trying to get some sleep.}
{102}{}{你若想找人说话，可以去找彼得。我得小睡一会。}

#{103}{}{Why are you here?}
{103}{}{你在这里做么？}

#{104}{}{Hrr. Arrooo?}
{104}{}{嗬。啊哦？}

#{105}{}{Nuh nuh.}
{105}{}{喏……喏。}

#{106}{}{KILL!!}
{106}{}{杀！}

#{107}{}{I'm }
{107}{}{我是}

#{108}{}{. I was sent to look for you.}
{108}{}{。我被派来找你。}


#{109}{}{I'm }
{109}{}{我是}

#{110}{}{. And you are dead.}
{110}{}{。而且你得死了。}

#{111}{}{What can you tell me about the Followers?}
{111}{}{你能告诉我关于末世论者的事吗？}

#{112}{}{I have come to offer my assistance.}
{112}{}{我是来提供帮助的。}

#{113}{}{I seek ways in which to instill peace upon this desolate wasteland.}
{113}{}{我正在寻求一条能将这荒凉的废土慢慢恢复和平的出路。}

#{114}{}{I am sorry, but I can't understand you. Now, what are you doing here?}
{114}{}{我很抱歉，但我不理解你所说的。你现在到底在这里做什么？}

#{115}{}{Nuh nuh.}
{115}{}{喏……喏。}

#{116}{}{Me Kill!!}
{116}{}{我废了你！}

#{117}{}{Hep. Me hep.}
{117}{}{帮！我帮！}

#{118}{}{If you are doing nothing, then I suggest that you leave. Now!}
{118}{}{如果你没事做，你最好马上离开！}

#{119}{}{You wish to help? Maybe I can use you.}
{119}{}{你想要帮我？或许我可以雇佣你。}

#{120}{}{Yes. Me hep! Me hep!}
{120}{}{是的。我帮！我帮！}

#{121}{}{No. No hep!}
{121}{}{不。不帮！}

#{122}{}{You are simple enough to find this person that others are
# too smart to find. There is a spy around here who is giving
# our secrets to the Children. Find the spy. Kill the spy. Go.}
{122}{}{你那么单纯，我相信你能找出其他聪明人找不出的人来。我们这里有个间谍将我们的机密传给了大教堂教徒。找到这家伙。杀了他。去吧。}

#{123}{}{I thought as much. Be off with you.}
{123}{}{果然。你走吧。}

#{124}{}{Figures that Jake doesn't think that I can get the job
# done right. He's the only one who could have sent you.
# Then you know about the spy.}
{124}{}{显然杰克并不认为我能做好这工作。他是唯一一个能派你过来的人。现在你知道谁是间谍了。}

#{125}{}{Jake didn't send me. One of your guards did.}
{125}{}{不是杰克派我来的。而是你的一个守卫。}

#{126}{}{I know some. Jake was very short with words.}
{126}{}{我知道的不多。杰克不太擅于言辞。}

#{127}{}{What is this about a spy? Maybe I can help.}
{127}{}{这是关于什么的间谍? 也许我能帮忙。}


#{128}{}{My guards are no fools. They sent you to the right person.
# There is a leak in here, and we need to find out where it is and seal it.}
{128}{}{我的守卫并不弱智。他们把你派来正合适。这里出了点疏漏，我们得找出问题的关键然后解决掉。}

#{129}{}{Have any leads?}
{129}{}{有线索了吗？}

#{130}{}{I'm a fighter, not a plumber. If you have leaks, talk to someone else.}
{130}{}{我是个战士，不是水管工。如果你捅出了漏子，去找别人。}

#{131}{}{I think you are the leak. Die!!}
{131}{}{我想你就是那漏洞。死吧！}

#{132}{}{Forget it. I'm nobody's lackey.}
{132}{}{忘了它吧。我不是任何人的手下。}

#{133}{}{The only thing that we know so far is that the person has
# to have access to the Children's Cathedral. I think it may be one of our scouts.}
{133}{}{我们目前所知的唯一线索是此人和大教堂有联系。我想他可能是我们的侦查员中的一个。}

#{134}{}{Okay. I will check it out right now.}
{134}{}{好的。我会马上去核实的。}

#{135}{}{Are you sure it is not a guard?}
{135}{}{你确定那不是守卫？}

#{136}{}{Tough luck then. You'll never catch the person now.}
{136}{}{运气不好。你还没能揪出那家伙。}

#{137}{}{I am quite certain. They only have access to the halls
# of the Followers. They are not allowed outside.}
{137}{}{我确定。末世论者的大厅对他们来说只能进不能出。}

#{138}{}{Then I don't know who it could be.}
{138}{}{那我就不知道会是谁了。}

#{139}{}{I'll look into the scouts then.}
{139}{}{我会去拜访各个侦查员的。}

#{140}{}{I think there is a cover-up here. You die!}
{140}{}{我认为这里面有鬼。你死定了！}

#{141}{}{That is why I am asking you to look around and see
# if you can find someone. Will you help?}
{141}{}{我要你在附近看看能不能找到帮手。可以吗？}

#{142}{}{Yes.}
{142}{}{好吧。}

#{143}{}{No.}
{143}{}{不行。}

#{144}{}{Thank you. This means a lot to us.}
{144}{}{谢谢你。这对于我们来说意义太重大了。}

#{145}{}{Then I must detain you from warning anyone.}
{145}{}{那我只好拘禁你了，免得你去给奸细报信。}

#{146}{}{How he ever became second in command is beyond me. Since he
# was so scarce in words, I will fill you in. We have a leak who
# is feeding the Children some of our movement patterns.}
{146}{}{他究竟是何时成为我的副手的，这一点我已经记不得了。既然他不善言谈，我打算启用你。我们这里有个内奸把我们的机密泄露给了大教堂教徒。}

#{147}{}{Have any leads?}
{147}{}{有线索了吗？}

#{148}{}{I'm a fighter, not a plumber. If you have leaks, talk to someone else.}
{148}{}{我是个战士，不是水管工。如果你捅出了漏子，找别人去。}

#{149}{}{I think you are the leak. Die!!}
{149}{}{我认为你就是那奸细。死吧！}

#{150}{}{Forget it. I'm nobody's lackey.}
{150}{}{忘了它吧。我不是任何人的手下。}

#{151}{}{You don't even know? I guess you wouldn't; most people
# in here don't. Someone is sneaking information of our
# movements to the Children. We need that person gone.}
{151}{}{你还不知道吗？我想你还不明白；这里的许多人也都不知道。有人偷了我们的机密提供给了大教堂的人。我们要让那个奸细消失。}

#{152}{}{Have any leads?}
{152}{}{有线索了吗？}

#{153}{}{I think you are the leak. Die!!}
{153}{}{我想你就是那叛徒。死吧！！}

#{154}{}{Forget it. I'm nobody's lackey.}
{154}{}{忘了它吧。我不是任何人的手下。}

#{155}{}{How much are you willing to offer?}
{155}{}{你愿意出多少？}

#{156}{}{I don't have much money. How about 200 caps?}
{156}{}{我的钱不多。200瓶盖如何？}

#{157}{}{Sorry, I'm broke.}
{157}{}{抱歉，我身无分文。}

#{158}{}{Your life.}
{158}{}{你的命。}

#{159}{}{Sounds fair to me.}
{159}{}{听起来很公平。}

#{160}{}{Now I will end this leak in the Followers!}
{160}{}{现在我要把末世论者里的内奸清除掉！}

#{161}{}{Tough luck then.}
{161}{}{太糟糕了。}

#{162}{}{What would you like to know?}
{162}{}{你想知道什么？}

#{163}{}{Who is the leader?}
{163}{}{谁是头儿？}

#{164}{}{Why are you attacking the Children?}
{164}{}{你为何攻击大教堂教徒？}

#{165}{}{Where can I get some first aid?}
{165}{}{我在哪里可以得到急救？}

#{166}{}{Nothing. Just checking.}
{166}{}{没什么。只是核对一下。}

#{167}{}{Nothing. Thank you.}
{167}{}{没什么。谢谢你。}

#{168}{}{Our leader is Nicole. Really nice person, but a bit flighty.
# Anything else you want to know?}
{168}{}{妮可尔是我们的头。是个真正的好人，但有些轻狂。你还想知道什么？}

#{169}{}{Why are you attacking the Children?}
{169}{}{你为何攻击大教堂的人？}

#{170}{}{Where can I get some healing?}
{170}{}{我在哪里可以得到医疗？}

#{171}{}{Nothing. Just checking. ＊smack＊}
{171}{}{没什么。只是检查一下。【拍打声】}

#{172}{}{Nothing. Thank you.}
{172}{}{没什么。谢谢你。}

#{173}{}{The Children are not what they appear to be. They
# are hiding something. Something related to those Nightkin. Anything else?}
{173}{}{大教堂教徒同他们表面看起来不是那么一样。他们的外表下潜藏了一些东西。比如涉及到夜行团的那些。还有什么事吗？}

#{174}{}{Who is the leader?}
{174}{}{谁是头儿？}

#{175}{}{Where can I get some healing?}
{175}{}{我在哪里能得到医疗吗？}

#{176}{}{Nothing. Just checking. ＊smack＊}
{176}{}{没什么。只是检查一下。【拍打声】}

#{177}{}{Nothing. Thank you.}
{177}{}{没什么。谢谢你。}

#{178}{}{There is the Children's healer, but I don't trust them. We
# also have a doctor or nurse on duty here at all times. Anything else?}
{178}{}{这里有大教堂教徒的医生，但我并不信任他们。我们也有医生或护士全天待命。还有别的什么想问吗？}

#{179}{}{Who is the leader?}
{179}{}{谁是头儿？}

#{180}{}{Why are you attacking the Children?}
{180}{}{你为何攻击大教堂教徒？}

#{181}{}{Nothing. Just checking. ＊smack＊}
{181}{}{没什么。只是检查一下。【拍打声】}

#{182}{}{Nothing. Thank you.}
{182}{}{没什么。谢谢你。}

#{183}{}{I am truly sorry to hear that. Pieces be with you!}
{183}{}{我真的很抱歉。我们是一伙的！}

#{184}{}{Who sent you?}
{184}{}{谁派你来的？}

#{185}{}{Your guard sent me.}
{185}{}{你的守卫。}

#{186}{}{Jake sent me.}
{186}{}{杰克派我来的。}

#{187}{}{I sent me.}
{187}{}{我自己来的。}

#{188}{}{Never mind. Good bye.}
{188}{}{没什么。再见。}

#{189}{}{A bit sure of yourself. I have no need for you.
# Talk to Nicole if you wish to offer your services.  Good night.}
{189}{}{你太自以为是了。我不需要你。如果你愿提供你的服务，找妮可尔谈谈。晚安。}

#{190}{}{Then you will want to search out Nicole. She can help
# you better with that. Good evening.}
{190}{}{那你就应该找妮可尔。她能帮你。晚安。}

#{191}{}{Go find that spy. We need to keep our plans secret still longer.}
{191}{}{去找出那奸细。我们得长久保持计划的绝密。}

#{192}{}{Good job on finding and removing Heather. Her meddling
# nearly got everyone killed. I wish there was something more we could do.}
{192}{}{做的不错，你找到并且除掉了希瑟。她差点把我们都卖了。我希望我们能一起做更多的工作。}

#{193}{}{Perhaps I can help you once more.}
{193}{}{或许我可以再帮你一次。}

#{194}{}{Good luck to you.}
{194}{}{祝你好运。}

#{195}{}{How so?}
{195}{}{那又如何？}

#{196}{}{I can train the Followers in some skills for war. Maybe
# your chances will improve.}
{196}{}{我可以训练末世论者一些战斗的技能。或许你的机遇会改善些。}

#{197}{}{I can leave. Good bye.}
{197}{}{我得走了。再见。}

#{198}{}{That would be wonderful. Thank you.}
{198}{}{真令人愉快。谢谢你了。}

#{199}{}{Now you are a bit more prepared. Good evening.}
{199}{}{现在你有点准备了吧。晚安。}

#{200}{}{Thank you for your teachings. Now we have a chance to
# beat back those Children.}
{200}{}{谢谢你的教学。现在我们有条件打翻那些个大教堂教徒了。}
