
#{100}{}{You see a water processing control computer. It has
# malfunctioned due to the removal of a critical piece
# of hardware.}
{100}{}{你看到一个控水计算机。它因为一个主要硬件被取出而产了生故障。}

#{101}{}{Your search the water processing control computer is successful.
# You find the water chip without a problem.}
{101}{}{你成功的搜索了控水计算机，顺利地找到了净水芯片。}

#{102}{}{You search the water computer. It takes a while but you
# eventually discover the water chip.}
{102}{}{虽然花了不少时间，但你还是找到了净水芯片。}

#{103}{}{The computer cannot be repaired without a functional water
# chip.}
{103}{}{没有净水芯片所以不能修理计算机。}

#{104}{}{You easily remove the water chip from the computer. You hear
# the flow of water to the city stop.}
{104}{}{你轻易的从电脑上拔下了净水芯片。城市的供水似乎停止了。}

#{105}{}{You struggle with the computer for a while, but you cannot
# remove the chip. After a moment, you realize you forgot to remove
# the locking bolts.}
{105}{}{你费了好大劲摆弄计算机，但是仍没有取下净水芯片。过了一会，你才发现你没有把芯片边上固定用的卡子掰开。}

#{106}{}{You did not remove the chip. Perhaps you should try again,
# this time a little more carefully.}
{106}{}{你没能取下净水芯片，或许你应该再更小心的试试。}

#{107}{}{You are too far away to carefully examine the water computer.}
{107}{}{你观察水控制计算机时离的太远了，没能看仔细。}

#{108}{}{You fail to repair the computer.}
{108}{}{你修理电脑失败了。}

#{109}{}{You learn nothing special about the water computer.}
{109}{}{在控水计算机上你学不到任何特别的知识。}

#{110}{}{You reinstall the water chip into the computer. The computer
# reboots after a moment, and proceeds to function as normal.}
{110}{}{你把净水芯片重新安装在计算机上。过了一会计算机重新启动完毕，开始正常运转了。}

#{111}{}{This item cannot be used on the computer.}
{111}{}{这个物品不能使用在计算机上面。}

#{112}{}{You see a water processing control computer. It is functional.}
{112}{}{你看见一个水控制计算机，它运转的很正常。}

#{113}{}{You gain }
{113}{}{因为你搞到了净水芯片，你获得了}

#{114}{}{ experience points for getting a water chip.}
{114}{}{点经验值。}

#{115}{}{You examine the computer carefully. Your analytical mind discovers
# a couple of methods that will ease the removal of the water chip.}
{115}{}{你仔细观察计算机。发现可以用两个办法轻易的取下净水芯片。}

#{116}{}{You learn that there is no way to fix the computer without
# reinstalling the water chip.}
{116}{}{你意识到没有净水芯片就永远无法修理控水计算机。}

#{117}{}{After shutting down the Water Purification Computer, you can now
# hear the repaired water pump working in the distance, bringing water up
# from what must be a deep well under Necropolis.}
{117}{}{关闭控水计算机后，你能听见修复后的水泵在很远的地方运转，水从大墓地以下很深的井里涌了出来。}