
#{100}{}{The water pump is fixed and working fine.}
{100}{}{修复的水泵现在运转的很好。}

#{101}{}{The water pump isn't working due to a broken vacuum pump.}
{101}{}{水泵不运转是因为真空泵坏了。}

#{102}{}{The water pump isn't working.}
{102}{}{水泵没有运行。}

#{103}{}{A piece of machinery.}
{103}{}{一个机器。}

#{104}{}{This water pump isn't working due to a broken vacuum pump.}
{104}{}{水泵不运转是因为真空泵坏了。}

#{105}{}{It might need a new fuse.}
{105}{}{它可能需要一个新的保险丝。}

#{106}{}{The water pump isn't working.}
{106}{}{水泵没有在运转。}

#{107}{}{You cannot repair the water pump without a replacement vacuum
# pump.}
{107}{}{没有备用真空泵你无法修理水泵。}

#{108}{}{You fail to repair the water pump. It might need a new fuse.}
{108}{}{你修理水泵失败了，它可能需要一个新保险丝。}

#{109}{}{You fail to repair the water pump.}
{109}{}{你修理水泵失败了。}

#{110}{}{This water pump isn't working due to a broken vacuum pump.}
{110}{}{这个水泵不能运转是因为真空泵坏了。}

#{111}{}{This water pump may need a new fuse.}
{111}{}{这个水泵或许需要一个新保险丝。}

#{112}{}{The water pump isn't working.}
{112}{}{水泵没有在运转。}

#{113}{}{You notice nothing unusual.}
{113}{}{你没有发现什么不正常。}

#{114}{}{The massive pump struggles to life after you successfully
# install the missing parts.}
{114}{}{巨大水泵的一阵颠簸，你把那个丢失的零件安装上了。}

#{115}{}{You somehow manage to destroy the parts while cutting
# your hand for 1 point of damage.}
{115}{}{不知什么原因，损坏的零件割破了你的手对你造成1点伤害。}

#{116}{}{You are having difficulties making these parts work.}
{116}{}{你修理那个部件有些困难。}

#{117}{}{This item cannot be used on the pump.}
{117}{}{这个不能用在水泵上。}

#{118}{}{You gain 1000 experience points for fixing the pump.}
{118}{}{你修好了水泵，获得了1000点经验值。}

