#{500}{}{After destroying the Master and his lab which he was creating his army of Super Mutants, you
# return home, only to discover that you are thrown out of your vault for being too destructive. Thank you
# for playing Fallout. }
{500}{}{消灭了建立变种人军队的主教和他的研究室后，你回到了家乡，没想到因为你具有破坏性，他们把你赶出了避难所。感谢你玩辐射游戏。}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#      "my name"       #
#      (970-979)       #
#                      #
#                      #
#{970}{}{That is my name.}
{970}{}{那是我的名字。}
#{971}{}{You are talking to me.}
{971}{}{你在和我说话。}
#{972}{}{Why do you ask silly questions. I am that person.}
{972}{}{为什么你问那么愚蠢的问题。我就是那个人。}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#     "don't know"     #
#      (970-979)       #
#                      #
#                      #
#{980}{}{I don't know anything about that.}
{980}{}{我不知道那些事情。}
#{981}{}{Sorry. No clue.}
{981}{}{抱歉。没有线索。}
#{982}{}{Never heard of it.}
{982}{}{从没听说过。}

# DESERT1.MAP (1000)
# DESERT2.MAP (1600)
# DESERT3.MAP (2200)

#
# HALLDED.MAP
# The Necropolis Hall of the Dead Tell-Me-Abouts
#
{2800}{}{The Master}
{2801}{}{Water Chip}
{2802}{}{Necropolis}
{2803}{}{Set}
{2804}{}{Watershed}
{2805}{}{Hall}
#{2900}{}{Isn't he some big important guy?}
{2900}{}{他就是那个重要人物？}
#{2901}{}{I dunno, but the watershed might have one.}
{2901}{}{我不知道，但是水处理房那里也许会有一个。}
#{2902}{}{Yer standing in it.  All that's left of it, at least.  This
# place is dying, slowly but surely.}
{2902}{}{你可以待在那里。最起码，应该休息一会。这个地方虽然逐渐没落了，但仍然安全。}
#{2903}{}{Oh, I like him, I do.  You can find him at the Hall.}
{2903}{}{哦，我喜欢他，我确信。你可以在大厅找到他。}
#{2904}{}{It's to the north.  Watch out for the guards.  They take their
# job real serious like.}
{2904}{}{在北面。注意警卫。他们都很尽责。}
#{2905}{}{The Hall of the Dead.  Where Set does his business.  It's smack
# right in the center of Necropolis.}
{2905}{}{这是死人大厅。赛特交易的地方。大墓地的权力中心。}


#
# HOTEL.MAP
# The Necropolis Hotel Tell-Me-Abouts
#
{3400}{}{The Master}
{3401}{}{Water Chip}
{3402}{}{Necropolis}
{3403}{}{Set}
{3404}{}{Watershed}
{3405}{}{Hall}
#{3500}{}{Isn't he some big important guy?}
{3500}{}{他就是那个重要人物？}
#{3501}{}{I dunno, but the watershed might have one.}
{3501}{}{我不知道，但是水处理房那里也许会有一个。}
#{3502}{}{Yer standing in it.  All that's left of it, at least.  This
# place is dying, slowly but surely.}
{3502}{}{你可以待在那里。最起码，应该休息一会。这个地方虽然逐渐没落了，但仍然安全。}
#{3503}{}{Oh, I like him, I do.  You can find him at the Hall.}
{3503}{}{哦，我喜欢他，我确信。你可以在大厅找到他。}
#{3504}{}{It's to the north.  Watch out for the guards.  They take their
# job real serious like.}
{3504}{}{在北面。注意警卫。他们都很尽责。}
#{3505}{}{The Hall of the Dead.  Where Set does his business.  It's smack
# right in the center of Necropolis.}
{3505}{}{这是死人大厅。赛特交易的地方。大墓地的权力中心。}


#
# WATRSHD.MAP
# The Necropolis Watershed Tell-Me-Abouts
#
{4000}{}{The Master}
{4001}{}{Water Chip}
{4002}{}{Necropolis}
{4003}{}{Set}
{4004}{}{Watershed}
{4005}{}{Hall}
#{4100}{}{Isn't he some big important guy?}
{4100}{}{他就是那个重要人物？}
#{4101}{}{I dunno, but the watershed might have one.}
{4101}{}{我不知道，但是水处理房那里也许会有一个。}
#{4102}{}{Yer standing in it.  All that's left of it, at least.  This
# place is dying, slowly but surely.}
{4102}{}{你可以待在那里。最起码，应该休息一会。这个地方虽然逐渐没落了，但仍然安全。}
#{4103}{}{Oh, I like him, I do.  You can find him at the Hall.}
{4103}{}{哦，我喜欢他，我确信。你可以在大厅找到他。}
#{4104}{}{Watch out for the guards.  They take their job real
# serious like.}
{4104}{}{注意警卫。他们都很尽责。}
#{4105}{}{The Hall of the Dead.  Where Set does his business.  It's smack
# right in the center of Necropolis.}
{4105}{}{这是死人大厅。赛特交易的地方。大墓地的权力中心。}


#
# VAULT13.MAP
# Vault 13 Tell-Me-Abouts
#
{4600}{}{Vault}
{4601}{}{Water}
{4602}{}{Overseer}
{4603}{}{Chip}
{4604}{}{Waterchip}
{4605}{}{Vault-13}
{4606}{}{Vault13}
{4607}{}{Medic}
{4608}{}{Healing}
{4609}{}{Library}
#{4700}{}{This is where we live. You should understand that.}
{4700}{}{这是我们生活的地方。你会熟悉的。}
#{4701}{}{The chip controls the level of purity in the underground water
# supply. It is a critical piece of equipment that cannot be repaired.}
{4701}{}{这个芯片控制着地下水的净化。这是个不能修复的重要零件。}
#{4702}{}{A good man doing a difficult job.}
{4702}{}{一个好男人应该迎难而上。}
#{4703}{}{The chip controls the level of purity in the underground water
# supply. It is a critical piece of equipment that cannot be repaired.}
{4703}{}{这个芯片控制着地下水的净化。这是个不能修复的重要零件。}
#{4704}{}{The chip controls the level of purity in the underground water
# supply. It is a critical piece of equipment that cannot be repaired.}
{4704}{}{这个芯片控制着地下水的净化。这是个不能修复的重要零件。}
#{4705}{}{This is where we live. You should understand that.}
{4705}{}{这是我们生活的地方。你会熟悉的。}
#{4706}{}{This is where we live. You should understand that.}
{4706}{}{这是我们生活的地方。你会熟悉的。}
#{4607}{}{The medic is on the first floor, in the medlab. Go there if you are
# hurt.}
{4607}{}{医生在一层，医务室里。如果你受伤了就去那里。}
#{4608}{}{The medic is on the first floor, in the medlab. Go there if you are
# hurt.}
{4608}{}{医生在一层，医务室里。如果你受伤了就去那里。}
#{4609}{}{The library is on the west wing of the third floor. That's where the
# research computers are located.}
{4609}{}{图书馆在三层西面。那里有电脑终端可以查询。}


# VAULTENT.MAP (5200)
# VAULTBUR.MAP (5800)
# VAULTNEC.MAP (6400)

#
# JUNKENT.MAP
# Junktown Entrance Tell-Me-Abouts
#
{7000}{}{Killian}
{7001}{}{Gizmo}
{7002}{}{Junktown}
{7003}{}{Shady Sands}
{7004}{}{The Hub}
{7005}{}{Water Chip}
{7006}{}{Casino}
{7007}{}{Store}
{7008}{}{Deathclaw}
#{7100}{}{Killian is the mayor. He runs a store.}
{7100}{}{基利安是镇长。他开了一间商店。}
#{7101}{}{Gizmo runs a casino. He seems okay.}
{7101}{}{吉斯莫经营着一家赌场。看起来他很受欢迎。}
#{7102}{}{This is Junktown.}
{7102}{}{这里是迦克镇。}
#{7103}{}{Umm, I think it is a real small place. I've never been there.}
{7103}{}{嗯，我认为这是个小地方。我从没到过这里。}
#{7104}{}{It's a larger city somewhere to the south.}
{7104}{}{南面有一个大城市。}
#{7105}{}{What? I'm sorry.}
{7105}{}{什么？我很抱歉。}
#{7106}{}{It's a large building in the northwest part of town.}
{7106}{}{有一个大型建筑在镇子西北。}
#{7107}{}{Killian's store? It's in the center of town.}
{7107}{}{基利安的商店？在镇中心。}
#{7108}{}{I dunno, but the name scares me.}
{7108}{}{我不知道，但是这个名字吓坏我了。}


#
# JUNKCSNO.MAP
# Junktown Casino Tell-Me-Abouts
#
{7600}{}{Killian}
{7601}{}{Gizmo}
{7602}{}{Junktown}
{7603}{}{Shady Sands}
{7604}{}{The Hub}
{7605}{}{Water Chip}
{7606}{}{Casino}
{7607}{}{Store}
{7608}{}{Deathclaw}
#{7700}{}{Killian is the mayor.  He took over when his dad died.}
{7700}{}{基利安是镇长。他父亲死后就接手了这里。}
#{7701}{}{Gizmo is a big man in Junktown.  He runs the casino, and the
# boxing ring.  He makes a lot of money, and buys a lot of stuff from the
# Hub.}
{7701}{}{吉斯莫在迦克镇里是一个高大的人。他开了间赌场，和一个拳击场。他赚了很多钱，并且在哈勃城买了很多原料。}
#{7702}{}{This is Junktown.}
{7702}{}{这里是迦克镇。}
#{7703}{}{Well, it's a really small community to the north.  The people who
# live there are mostly farmers.  We occasionally trade with them, but they
# mostly want to be left alone.}
{7703}{}{是的，北面有一个部落。生活在那里的主要是一些农民。我们有时和他们交易，但是通常情况下他们不与人交往。}
#{7704}{}{The Hub is the center of commerce around here.  Almost all of the
# traders come from the Hub.  They have some companies there that still
# make things.  If you want, you can go with one of their trading parties
# back to the Hub.}
{7704}{}{哈勃城是这附近的商业中心。绝大多数商人都来自哈勃城。他们有自己的商队来运送东西。如果你想去那里，你可以和他们的商队一起返回哈勃城。}
#{7705}{}{I don't know anything about that.}
{7705}{}{我不知道那些事情。}
#{7706}{}{Gizmo runs it.  Watch out for the slot machines, you can lose a
# lot of money if you play them.}
{7706}{}{吉斯莫经营着它。小心那些老虎机，如果你想玩的话你会输掉很多钱。}
#{7707}{}{Darkwaters?  It's in the center of town.  You can barter with
# him, or pay cash.}
{7707}{}{达克沃特？在镇中心。你可以同他交易。}
#{7708}{}{I hear people talking about it, but I've never seen it.  They
# say it roams the desert, striking mostly at night.}
{7708}{}{我听说人们都在谈论死亡爪，但是我从没看到过。他们说死亡爪生活在沙漠里，主要在晚上猎食。}


#
# JUNKKILL.MAP
# Junktown Killian's Tell-Me-Abouts
#
{8200}{}{Killian}
{8201}{}{Gizmo}
{8202}{}{Junktown}
{8203}{}{Shady Sands}
{8204}{}{The Hub}
{8205}{}{Water Chip}
{8206}{}{Casino}
{8207}{}{Store}
{8208}{}{Deathclaw}
#{8300}{}{Killian is the mayor.  He took over when his dad died.}
{8300}{}{基利安是镇长。他父亲死后就接手了这里。}
#{8301}{}{Gizmo is a big man in Junktown.  He runs the casino, and the
# boxing ring.  He makes a lot of money, and buys a lot of stuff from the
# Hub.}
{8301}{}{吉斯莫在迦克镇里是一个高大的人。他开了间赌场，和一个拳击场。他赚了很多钱，并且在哈勃城买了很多原料。}
#{8302}{}{This is Junktown.}
{8302}{}{这里是迦克镇。}
#{8303}{}{Well, it's a really small community to the north.  The people who
# live there are mostly farmers.  We occasionally trade with them, but they
# mostly want to be left alone.}
{8303}{}{是的，北面有一个部落。生活在那里的主要是一些农民。我们有时和他们交易，但是通常情况下他们不与人交往。}
#{8304}{}{The Hub is the center of commerce around here.  Almost all of the
# traders come from the Hub.  They have some companies there that still
# make things.  If you want, you can go with one of their trading parties
# back to the Hub.}
{8304}{}{哈勃城是这附近的商业中心。绝大多数商人都来自哈勃。他们有自己的商队来运送东西。如果你想去那里，你可以和他们的商队一起返回哈勃。}
#{8305}{}{I don't know anything about that.}
{8305}{}{我不知道那些事情。}
#{8306}{}{Gizmo runs it.  Watch out for the slot machines, you can lose a
# lot of money if you play them.}
{8306}{}{吉斯莫经营着它。小心那些老虎机，如果你想玩的话你会输掉很多钱。}
#{8307}{}{Darkwaters?  It's in the center of town.  You can barter with
# him, or pay cash.}
{8307}{}{达克沃特？在镇中心。你可以同他交易。}
#{8308}{}{I hear people talking about it, but I've never seen it.  They
# say it roams the desert, striking mostly at night.}
{8308}{}{我听说人们都在谈论死亡爪，但是我从没看到过。他们说死亡爪生活在沙漠里，主要在晚上猎食。}


# BROHDENT.MAP  (8800)
{8800}{}{The Master}
{8801}{}{The War}
{8802}{}{The Exodus}
{8803}{}{The Strange Army}
{8804}{}{The Brotherhood}
{8805}{}{The Merchants}
{8806}{}{The Missing Caravans}
{8807}{}{The Hub}
{8808}{}{Children of the Cathedral}
{8809}{}{Initiates}
{8810}{}{Scribes}
{8811}{}{Knights}
{8812}{}{Paladins}
{8813}{}{Water Chip}
#{8900}{}{I have no idea what you are talking about.}
{8900}{}{我不知道你在说什么。}
#{8901}{}{A terribly low point in the human history which formed our present world. We preserve the knowledge
# from the War to prevent another holocaust.}
{8901}{}{纵观人类历史，正是我们毁灭了原来的世界。我们保护战前的科技正是为了防止历史重演。}
#{8902}{}{A difficult and sorrowful decision. We lost a great many people who chose to go off on their own
# rather than traveling with the main force searching for a safe haven to live.}
{8902}{}{一个让人心痛的艰难决定。我们失去了太多的伙伴，其中大多数人离开了，还有一部分死于探索外面的世界。}
#{8903}{}{I don't know much about it. The reports I've hear is that they are amassing somewhere to the north of us.}
{8903}{}{我不知道太多情况。我听说在我们北面某处有些人收集了一些报告。}
#{8904}{}{That is where we stand.}
{8904}{}{就是我们站着的地方。}
#{8905}{}{Those Water Merchants are thieving bastards, but of the other groups, I have no opinion.}
{8905}{}{那些水商人是一些小偷，但对于其他团体，我没有看法。}
#{8906}{}{I don't know anything about that.}
{8906}{}{我不知道。}
#{8907}{}{A slime pit for those vile merchants. Though, occasionally, we will let one of the more civil trading companies
# exchange goods with us.}
{8907}{}{那些卑鄙的商人是狡猾的。可是，有时候，我们也需要一些商人来和我们交易。}
#{8908}{}{They are a cult.}
{8908}{}{我们是虔诚的信徒。}
#{8909}{}{They are the future of the Brotherhood.}
{8909}{}{未来属于我们兄弟会。}
#{8910}{}{They are the keepers of the knowledge.}
{8910}{}{他们是知识的监管者。}
#{8911}{}{They are the ones who make the weapons for the Brotherhood.}
{8911}{}{他们是给兄弟会制造武器的人。}
#{8912}{}{They are the protectors of the Brotherhood.}
{8912}{}{他们是兄弟会的保护者。}
#{8913}{}{I have no idea what you are talking about.}
{8913}{}{我不知道你在说什么。}

# BROHD12.MAP   (9400)

{9400}{}{The Master}
{9401}{}{The War}
{9402}{}{The Exodus}
{9403}{}{The Strange Army}
{9404}{}{The Brotherhood}
{9405}{}{The Merchants}
{9406}{}{The Missing Caravans}
{9407}{}{The Hub}
{9408}{}{Children of the Cathedral}
{9409}{}{Initiates}
{9410}{}{Scribes}
{9411}{}{Knights}
{9412}{}{Paladins}
{9413}{}{Water Chip}
#{9500}{}{I have no idea what you are talking about.}
{9500}{}{我不知道你在说什么。}
#{9501}{}{A terribly low point in the human history which formed our present world. We preserve the knowledge
# from the War to prevent another holocaust.}
{9501}{}{纵观人类历史，正是我们毁灭了原来的世界。我们保护战前的科技正是为了防止历史重演。}
#{9502}{}{A difficult and sorrowful decision. We lost a great many people who chose to go off on their own
# rather than traveling with the main force searching for a safe haven to live.}
{9502}{}{一个让人心痛的艰难决定。我们失去了太多的伙伴，其中大多数人离开了，还有一部分死于探索外面的世界。}
#{9503}{}{I don't know much about it. The reports I've hear is that they are amassing somewhere to the north of us.}
{9503}{}{我不知道太多情况。我听说在我们北面某处有些人收集了一些报告。}
#{9504}{}{That is where we stand.}
{9504}{}{就是我们站着的地方。}
#{9505}{}{Those Water Merchants are thieving bastards, but of the other groups, I have no opinion.}
{9505}{}{那些水商人是一些小偷，但对于其他团体，我没有看法。}
#{9506}{}{I don't know anything about that.}
{9506}{}{我不知道。}
#{9507}{}{A slime pit for those vile merchants. Though, occasionally, we will let one of the more civil trading companies
# exchange goods with us.}
{9507}{}{那些卑鄙的商人是狡猾的。可是，有时候，我们也需要一些商人来和我们交易。}
#{9508}{}{They are a cult.}
{9508}{}{我们是虔诚的信徒。}
#{9509}{}{They are the future of the Brotherhood.}
{9509}{}{未来属于我们兄弟会。}
#{9510}{}{They are the keepers of the knowledge.}
{9510}{}{他们是知识的监管者。}
#{9511}{}{They are the ones who make the weapons for the Brotherhood.}
{9511}{}{他们是给兄弟会制造武器的人。}
#{9512}{}{They are the protectors of the Brotherhood.}
{9512}{}{他们是兄弟会的保护者。}
#{9513}{}{I have no idea what you are talking about.}
{9513}{}{我不知道你在说什么。}

# BROHD34.MAP  (10000)

{10000}{}{The Master}
{10001}{}{The War}
{10002}{}{The Exodus}
{10003}{}{The Strange Army}
{10004}{}{The Brotherhood}
{10005}{}{The Merchants}
{10006}{}{The Missing Caravans}
{10007}{}{The Hub}
{10008}{}{Children of the Cathedral}
{10009}{}{Initiates}
{10010}{}{Scribes}
{10011}{}{Knights}
{10012}{}{Paladins}
{10013}{}{Water Chip}
#{10000}{}{I have no idea what you are talking about.}
{10000}{}{我不知道你在说什么。}
#{10101}{}{A terribly low point in the human history which formed our present world. We preserve the knowledge
# from the War to prevent another holocaust.}
{10101}{}{纵观人类历史，正是我们毁灭了原来的世界。我们保护战前的科技正是为了防止历史重演。}
#{10102}{}{A difficult and sorrowful decision. We lost a great many people who chose to go off on their own
# rather than traveling with the main force searching for a safe haven to live.}
{10102}{}{一个让人心痛的艰难决定。我们失去了太多的伙伴，其中大多数人离开了，还有一部分死于探索外面的世界。}
#{10103}{}{I don't know much about it. The reports I've hear is that they are amassing somewhere to the north of us.}
{10103}{}{我不知道太多情况。我听说在我们北面某处有些人收集了一些报告。}
#{10104}{}{That is where we stand.}
{10104}{}{就是我们站着的地方。}
#{10105}{}{Those Water Merchants are thieving bastards, but of the other groups, I have no opinion.}
{10105}{}{那些水商人是一些小偷，但对于其他团体，我没有看法。}
#{10106}{}{I don't know anything about that.}
{10106}{}{我不知道。}
#{10107}{}{A slime pit for those vile merchants. Though, occasionally, we will let one of the more civil trading companies
# exchange goods with us.}
{10107}{}{那些卑鄙的商人是狡猾的。可是，有时候，我们也需要一些商人来和我们交易。}
#{10108}{}{They are a cult.}
{10108}{}{我们是虔诚的信徒。}
#{10109}{}{They are the future of the Brotherhood.}
{10109}{}{未来属于我们兄弟会。}
#{10110}{}{They are the keepers of the knowledge.}
{10110}{}{他们是知识的监管者。}
#{10111}{}{They are the ones who make the weapons for the Brotherhood.}
{10111}{}{他们是给兄弟会制造武器的人。}
#{10112}{}{They are the protectors of the Brotherhood.}
{10112}{}{他们是兄弟会的保护者。}
#{10113}{}{I have no idea what you are talking about.}
{10113}{}{我不知道你在说什么。}


# CAVES.MAP    (10600)
# CHILDRN1.MAP (11200)

{11200}{}{Holy Flame}
{11201}{}{The Unity}
{11202}{}{Children of the Cathedral}
{11203}{}{Morpheus}
{11204}{}{Mutants}
{11205}{}{Master}
{11206}{}{Followers of the Apocalypse}
{11207}{}{Military Base}
{11208}{}{The Vats}
{11209}{}{Water Chip}

#{11300}{}{The Holy Flame is the one who will
# lead us into a brave new world which doesn抰 have hatred or war.}
{11300}{}{圣火将带领我们开创一个没有憎恨和战争的新世界。}
#{11301}{}{We are all part of the Unity. It is the love and
# peace which we pass on to our fellow people ?human and mutant.}
{11301}{}{我们是团结的集体。我们向谁传播爱和宽容？人类和变种人。}
#{11302}{}{That is us.}
{11302}{}{那就是我们。}
#{11303}{}{Morpheus is the High Priest of the Children.
# Typically, he is in his rooms when he is not preaching to us.}
{11303}{}{墨菲斯是孩子们的高级牧师。通常，在不给我们传教的时候他会在他的房间里。}
#{11304}{}{They are people who got mutated from the nuclear
# fallout. But they are still good people.}
{11304}{}{他们是受核辐射变异的人。但他们仍然是好人。}
#{11305}{}{We all have masters, don抰 we?}
{11305}{}{我们都有主教，不是吗？}
#{11306}{}{They are people who seek to destroy the peace which
# the Master is trying to set forth.}
{11306}{}{他们是寻找主教预言的遗迹的人。}
#{11307}{}{Sorry, never have heard of that.}
{11307}{}{抱歉，从没听说过。}
#{11308}{}{Sorry, I don抰 know what you are talking about.}
{11308}{}{抱歉。我不知道你在说什么。}
#{11309}{}{I have no clue as to what you are talking about.}
{11309}{}{我没有你要的线索。}

# CHILDRN2.MAP (11800)

{11800}{}{Holy Flame}
{11801}{}{The Unity}
{11802}{}{Children of the Cathedral}
{11803}{}{Morpheus}
{11804}{}{Mutants}
{11805}{}{Master}
{11806}{}{Followers of the Apocalypse}
{11807}{}{Military Base}
{11808}{}{The Vats}
{11809}{}{Water Chip}

#{11900}{}{The Holy Flame is the one who will
# lead us into a brave new world which doesn抰 have hatred or war.}
{11900}{}{圣火将带领我们开创一个没有憎恨和战争的新世界。}
#{11901}{}{We are all part of the Unity. It is the love and
# peace which we pass on to our fellow people ?human and mutant.}
{11901}{}{我们是团结的集体。我们向谁传播爱和宽容？人类和变种人。}
#{11902}{}{That is us.}
{11902}{}{那就是我们。}
#{11903}{}{Morpheus is the High Priest of the Children.
# Typically, he is in his rooms when he is not preaching to us.}
{11903}{}{墨菲斯是孩子们的高级牧师。通常，在不给我们传教的时候他会在他的房间里。}
#{11904}{}{They are people who got mutated from the nuclear
# fallout. But they are still good people.}
{11904}{}{他们是受核辐射变异的人。但他们仍然是好人。}
#{11905}{}{We all have masters, don抰 we?}
{11905}{}{我们都有主教，不是吗？}
#{11906}{}{They are people who seek to destroy the peace which
# the Master is trying to set forth.}
{11906}{}{他们是寻找主教预言的遗迹的人。}
#{11907}{}{Sorry, never have heard of that.}
{11907}{}{抱歉，从没听说过。}

#{11908}{}{Sorry, I don抰 know what you are talking about.}
{11908}{}{抱歉。我不知道你在说什么。}
#{11909}{}{I have no clue as to what you are talking about.}
{11909}{}{我没有你要的线索。}


# CITY1.MAP    (12400)
# COAST1.MAP   (13000)
# COAST2.MAP   (13600)
# COLATRUK.MAP (14200)
# FSAUSER.MAP  (14800)

#
# RAIDERS.MAP
# Raiders Tell-Me-Abouts
#
{15400}{}{Khans}
{15401}{}{Garl}
{15402}{}{Junktown}
{15403}{}{Shady Sands}
{15404}{}{The Hub}
{15405}{}{Water Chip}
{15406}{}{Tandi}
{15407}{}{Alya}
{15408}{}{Diana}
{15409}{}{Gwen}
{15410}{}{Petrox}
{15411}{}{Tolya}
{15412}{}{Booze}
{15413}{}{Drugs}
#{15500}{}{That's us, you lackey.}
{15500}{}{那就是我们，你的仆人。}
#{15501}{}{He's the leader of the Khans.  He is the most feared man in the
# wasteland.}
{15501}{}{他是可汗的领导。他是废土中最可怕的人。}
#{15502}{}{They are to the southwest.  We sometimes go there to relax after
# a hard day pillaging.}
{15502}{}{他们要去西南方。我们经常在抢劫后去那里放松。}
#{15503}{}{Why we don't crush them completely is beyond me.}
{15503}{}{为什么我们不干掉靠近我们的人。}
#{15504}{}{They are to the south.  We will trade with them.  Mostly for
# water and ammo, but sometimes they get better weapons, too.}
{15504}{}{他们要去南方。我们要和他们交易。通常是水和弹药，但有时他们也会带来好武器。}
#{15505}{}{Why should I care?}
{15505}{}{为什么我要小心？}
#{15506}{}{I don't know anyone by that name.}
{15506}{}{我没听说过那个名字。}
#{15507}{}{She is an advisor. She plans the raids.}
{15507}{}{她是顾问。负责制定袭击计划。}
#{15508}{}{She is the armorer. She repairs our equipment.}
{15508}{}{她是军械修护员。负责维修我们的装备。}
#{15509}{}{She is second in command.}
{15509}{}{她是副指挥。}
#{15510}{}{He collects our supplies.}
{15510}{}{他收集我们的补给。}
#{15511}{}{He is the cook.}
{15511}{}{他是厨师。}
#{15512}{}{Do you have any?}
{15512}{}{你还有事吗？}
#{15513}{}{Do you have any?}
{15513}{}{你还有事吗？}


#
# SHADYE.MAP
# Shady Sands East Tell-Me-Abouts
#
{16000}{}{Khans}
{16001}{}{Garl}
{16002}{}{Junktown}
{16003}{}{Shady Sands}
{16004}{}{The Hub}
{16005}{}{Water Chip}
{16006}{}{Tandi}
{16007}{}{Aradesh}
{16008}{}{Seth}
{16009}{}{Razlo}
#{16100}{}{They are a lawless group who pretend to be some people from the
# far past.}
{16100}{}{他们是伪装后的非法组织。}
#{16101}{}{He leads the Khans.  He is one of the most dangerous men that
# has ever set eyes on Shady Sands.  He leads the raider clans with a
# heavy fist.}
{16101}{}{他领导着可汗。而且是曾经想侵占沙荫镇最危险的人物之一，他以铁腕统领着这个匪帮。}
#{16102}{}{It's 4-6 days to the southwest.  Good trading occasionally, but
# more often than not, they try to stiff us.}
{16102}{}{需要4到6天才能到西南方。运气好的话可以遇到商队进行交易，但经常不行，他们会刁难我们。}
#{16103}{}{You're standing in it.}
{16103}{}{你正站在它里面。}
#{16104}{}{Much farther to the south than Junktown.  The Hub is the largest
# city I've heard about.  Must be a thousand people there, at least.}
{16104}{}{到了迦克镇还要往北。哈勃城是我听说过的最大的城市。至少有一千个人生活在那里。}
#{16105}{}{Sorry, I can't help you.}
{16105}{}{抱歉，我不能帮助你。}
#{16106}{}{She is the daughter of Aradesh.  Some day she could lead us, but
# she must learn to temper her ways.}
{16106}{}{她是亚拉德什是女儿。将来她会领导我们，但她应该改改她的脾气。}
#{16107}{}{He is the leader of our community, and a true hero.  You can always
# find him at work in the communal hall.}
{16107}{}{他是我们组织的领导者，一个真正的英雄。经常可以在公共礼堂见到他在工作。}
#{16108}{}{He works with Aradesh to make sure we are safe.}
{16108}{}{他和亚拉德什一同确保我们的安全。}
#{16109}{}{Our Doctor.  See him if you are hurt.}
{16109}{}{我们的医生。如果你受伤了可以去见他。}

#
# SHADYW.MAP
# Shady Sands West Tell-Me-Abouts
#
{16600}{}{Khans}
{16601}{}{Garl}
{16602}{}{Junktown}
{16603}{}{Shady Sands}
{16604}{}{The Hub}
{16605}{}{Water Chip}
{16606}{}{Tandi}
{16607}{}{Aradesh}
{16608}{}{Seth}
{16609}{}{Razlo}
#{16700}{}{They are a lawless group who pretend to be some people from the
# far past.}
{16700}{}{他们是伪装后的非法组织。}
#{16701}{}{He leads the Khans.  He is one of the most dangerous men that
# has ever set eyes on Shady Sands.  He leads the raider clans with a
# heavy fist.}
{16701}{}{他领导着可汗。而且是曾经想侵占沙荫镇最危险的人物之一，他以铁腕统领着这个匪帮。}
#{16702}{}{It's 4-6 days to the southwest.  Good trading occasionally, but
# more often than not, they try to stiff us.}
{16702}{}{需要4到6天才能到西南方。运气好的话可以遇到商队进行交易，但经常不行，他们会刁难我们。}
#{16703}{}{You're standing in it.}
{16703}{}{你正站在它里面。}
#{16704}{}{Much farther to the south than Junktown.  The Hub is the largest
# city I've heard about.  Must be a thousand people there, at least.}
{16704}{}{到了迦克镇还要往北。哈勃城是我听说过的最大的城市。至少有一千个人生活在那里。}
#{16705}{}{Sorry, I can't help you.}
{16705}{}{抱歉，我不能帮助你。}
#{16706}{}{She is the daughter of Aradesh.  Some day she could lead us, but
# she must learn to temper her ways.}
{16706}{}{她是亚拉德什是女儿。将来她会领导我们，但她应该改改她的脾气。}
#{16707}{}{He is the leader of our community, and a true hero.  You can always
# find him at work in the communal hall.}
{16707}{}{他是我们组织的领导者，一个真正的英雄。经常可以在公共礼堂见到他在工作。}
#{16708}{}{He works with Aradesh to make sure we are safe.}
{16708}{}{他和亚拉德什一同确保我们的安全。}
#{16709}{}{Our Doctor.  See him if you are hurt.}
{16709}{}{我们的医生。如果你受伤了可以去见他。}

# GLOWENT.MAP  (17200)


#
# LAADYTUM.MAP
#
#

#  ======================================================================
#     ADYTUM
# Info Level 1 【People who know nothing】
{17800}{}{Adytum}
{17801}{}{The Followers}
{17802}{}{The Cathedral}
{17803}{}{The Rippers}
{17804}{}{The Blades}
{17805}{}{The Gun Runners}
{17806}{}{The Hub}
{17807}{}{Junktown}
{17808}{}{Water Chip}
{17809}{}{Store}
{17810}{}{Zimmerman}
{17811}{}{Necropolis}
{17812}{}{The Glow}
{17813}{}{The Regulators}
{17814}{}{The Scavs}
{17815}{}{The Boneyard}
#{17900}{}{That's here.}
{17900}{}{在这里。}
#{17901}{}{They live north of here.}
{17901}{}{他们住在这儿的北区。}
#{17902}{}{It's a ways south of us.}
{17902}{}{那是通向我们南区的路。}
#{17903}{}{They're on the west side.}
{17903}{}{他们在西区。}
#{17904}{}{They're on the east side.}
{17904}{}{他们在东区。}
#{17905}{}{They're past the Followers to the north.}
{17905}{}{他们是越过北方的末世论者。}
#{17906}{}{We trade with them.}
{17906}{}{我们和他们交易。}
#{17907}{}{Isn't that a city north of here?}
{17907}{}{那个城市在北面？}
#{17908}{}{A what?}
{17908}{}{什么？}
#{17909}{}{Tine's store is underground near the gate.}
{17909}{}{提恩的商店在大门旁的地下。}
#{17910}{}{He's the mayor.}
{17910}{}{他是市长。}
#{17911}{}{I hear it's out east.}
{17911}{}{我听说他去了东方。}
#{17912}{}{That's a myth.}
{17912}{}{真荒唐。}
#{17913}{}{They protect us.}
{17913}{}{他们保护我们。}
#{17914}{}{They go outside to get things.}
{17914}{}{他们出去找东西了。}
#{17915}{}{This is the Boneyard.}
{17915}{}{这里是晒骨场。}


# Info level 2 【People who know something】
{18000}{}{Adytum}
{18001}{}{The Followers}
{18002}{}{The Cathedral}
{18003}{}{The Rippers}
{18004}{}{The Blades}
{18005}{}{The Gun Runners}
{18006}{}{The Hub}
{18007}{}{Junktown}
{18008}{}{Water Chip}
{18009}{}{Store}
{18010}{}{Zimmerman}
{18011}{}{Necropolis}
{18012}{}{The Glow}
{18013}{}{The Regulators}
{18014}{}{The Scavs}
{18015}{}{The Boneyard}
#{18100}{}{You're in Adytum, outsider.}
{18100}{}{你是在内城区，外来者。}
#{18101}{}{The Followers live in an old library just to the north. They preach
# tolerance and peace.}
{18101}{}{末世论者住在北面的老图书馆里。他们信奉宽恕和和平。}
#{18102}{}{The Cathedral is a ways to the south, by the bay. The Children are a
# peaceful religion.}
{18102}{}{顺着这条路一直走，就会到达大教堂。孩子们信仰的和平宗教。}
#{18103}{}{They're on the west side. They are very vicious and have lots of traps.}
{18103}{}{他们在西区。他们十分可恶并且有很多陷阱。}
#{18104}{}{They're on the east side. They use some sort of high-tech knives.}
{18104}{}{他们在东区。他们使用高科技的刀子。}
#{18105}{}{They're past the Followers to the north. They sell weapons to the gangs.}
{18105}{}{他们住在末世论者北面。他们向帮派出售武器。}
#{18106}{}{We trade with them. They're the largest city I know of.}
{18106}{}{我们同他们交易。那是我所知道的最大的城市。}
#{18107}{}{They're a small city northeast of us.}
{18107}{}{那个小镇在我们东北方。}
#{18108}{}{Never heard of it.}
{18108}{}{从没听过。}
#{18109}{}{Tine's store is underground near the gate. He can sell you many supplies.}
{18109}{}{提恩的商店在大门旁的地下。}
#{18110}{}{He's the mayor. He does a good job.}
{18110}{}{他是市长。他很走运。}
#{18111}{}{It's a city of the dead, several days to the east.}
{18111}{}{那是个死亡之城，向东走几天就可以到。}
#{18112}{}{I hear it's way, way south.}
{18112}{}{我听说过那条路，通向南方。}
#{18113}{}{They protect us from the gangs and keep the peace.}
{18113}{}{他们保护我们不受帮派骚扰和维持治安。}
#{18114}{}{They go outside to search for stuff.}
{18114}{}{他们出去寻找材料。}
#{18115}{}{We're in the Boneyard.}
{18115}{}{这里是晒骨场。}



# Info level 3 【People who know more than something but less than everything】
{18200}{}{Adytum}
{18201}{}{The Followers}
{18202}{}{The Cathedral}
{18203}{}{The Rippers}
{18204}{}{The Blades}
{18205}{}{The Gun Runners}
{18206}{}{The Hub}
{18207}{}{Junktown}
{18208}{}{Water Chip}
{18209}{}{Store}
{18210}{}{Zimmerman}
{18211}{}{Necropolis}
{18212}{}{The Glow}
{18213}{}{The Regulators}
{18214}{}{The Scavs}
{18215}{}{The Boneyard}
#{18300}{}{We're the descendants of an old Vault that used to be under the south
# side of this city.}
{18300}{}{我们是老避难所的后代住在城南。}
#{18301}{}{The Followers are a learned and peaceful people. They live in an old
# library north of here.}
{18301}{}{末世论者是群爱好和平的学者。他们住在北边的老图书馆。}
#{18302}{}{The Children worship a mysterious Dark God. They seem harmless, but
# there is something strange about their religion. The Cathedral is
# south of here.}
{18302}{}{教徒们信仰这神秘的黑暗之神。他们看起来是无害的，但是他们的信仰有些奇怪。大教堂在南面。}
#{18303}{}{The Rippers are all inbred. They have a fortified building with traps
# around it where they take prisoners to be tortured and killed.}
{18303}{}{电锯党是天生的罪犯。他们用周围布满了陷阱的坚固的建筑来折磨并杀害他们的俘虏。}
#{18304}{}{The Blades are notorious for their vibro-knives. They are the
# arch-enemies of the Rippers. Their leader is a woman named Razor.}
{18304}{}{声名狼藉的利刃帮由他们的刀子而得名。他们是电锯党的主要敌人。他们的老大是个叫利刃的女人。}
#{18305}{}{They used to be a gang, but they set up in a warehouse on the north
# side and started trading weapons and guns to people.}
{18305}{}{他们经常火并，他们在北面建了一个仓库来向人们出售武器。}
#{18306}{}{The Hub is a center of trade and commerce. They have companies that
# actually produce things. They're east of us.}
{18306}{}{哈勃城是经贸中心。他们竟然有制造公司。他们在我们东方。}
#{18306 alternate If hydroponic farms aren't fixed:}{We sell bullets to the Hub.}
#{18307}{}{Junktown is a moderate-sized city east of here and just north of the
# Hub.}
{18307}{}{迦克镇是一个中型城市，它在这里的东面，哈勃城北面。}
#{18308}{}{Sorry, can't help you with that.}
{18308}{}{抱歉，没法帮你。}
#{18309}{}{Tine runs the general store near the front gate. He can sell you
# weapons and traveling supplies.}
{18309}{}{提恩在前面的大门附近开了一家综合商店。他可以卖给你武器和补给。}
#{18310}{}{Jon is our mayor. He makes trade agreements, dictates policy, and
# delegates responsibility to the Regulators and the Scavs.}
{18310}{}{乔恩是我们市长。他制定了贸易协定，政策，和代表职责。}
#{18311}{}{The city of the dead? It's supposedly a place inhabited by strange
# cannibals far to the east. I wouldn't visit there if I were you.}
{18311}{}{死亡之城？据说那是在很远的东方奇怪的食人者待的地方。我是你的话不会到那里去的。}
#{18312}{}{It's a big radioactive place far, far to the south, or so I'm told.}
{18312}{}{一个很大的辐射地域，在很远的南方，好像我说过。}
#{18313}{}{They're the police force of Adytum. They protect us from the gangs.
#  Caleb is the leader.}
{18313}{}{他们是内城区的保卫力量。他们保护我们不受帮派骚扰。卡勒布是他们的首领。}
#{18314}{}{The Scavs have the job of searching the Boneyard for valuable
# equipment. They are led by Sammael.}
{18314}{}{任务是用贵重的器材探索晒骨场。他们由山谬带队。}
#{18315}{}{The Angel's Boneyard is the remains of the old city of Los Angeles.
#  We're in the middle of the Boneyard.}
{18315}{}{美丽的晒骨场是古老的城市洛杉矶的遗迹。我们在晒骨场中央。}
#  ======================================================================


#
# LAFOLLWR.MAP  (18400)
#
#

#======================================================================
#    FOLLOWERS OF THE APOCALYPSE
# Info Level 1 【People who know nothing】
{18400}{}{Adytum}
{18401}{}{The Followers}
{18402}{}{The Cathedral}
{18403}{}{The Rippers}
{18404}{}{The Blades}
{18405}{}{The Gun Runners}
{18406}{}{The Hub}
{18407}{}{Junktown}
{18408}{}{Water Chip}
{18409}{}{Nicole}
{18410}{}{The Boneyard}
#{18500}{}{It's a village south of here.}
{18500}{}{南面有一个小村。}
#{18501}{}{We are the Followers of the Apocalypse.}
{18501}{}{我们是末世论者。}
#{18502}{}{A cult to the south, past Adytum.}
{18502}{}{穿过内城区，南面有一群信徒。}
#{18503}{}{A gang to the west.}
{18503}{}{西面有个帮派。}
#{18504}{}{A gang to the east.}
{18504}{}{东面有个帮派。}
#{18505}{}{A gang to the north.}
{18505}{}{北面有个帮派。}
#{18506}{}{A big trading city to the northeast.}
{18506}{}{东北有一个大的贸易城市。}
#{18507}{}{A medium-sized city north of the Hub.}
{18507}{}{一个中型城市在哈勃城北面。}
#{18508}{}{Can't help you, sorry.}
{18508}{}{没法帮你，抱歉。}
#{18509}{}{She's our leader.}
{18509}{}{她是我们领袖。}
#{18510}{}{This is the Boneyard.}
{18510}{}{这里是晒骨场。}

# Info level 2 【People who know something】
{18600}{}{Adytum}
{18601}{}{The Followers}
{18602}{}{The Cathedral}
{18603}{}{The Rippers}
{18604}{}{The Blades}
{18605}{}{The Gun Runners}
{18606}{}{The Hub}
{18607}{}{Junktown}
{18608}{}{Water Chip}
{18609}{}{Nicole}
{18610}{}{The Boneyard}
#{18700}{}{A small town to the south. Occasionally some of them visit.}
{18700}{}{南面有个小镇。有时会有人去那里。}
#{18701}{}{We are the Followers of the Apocalypse. We take this name because we
# come after the storm of war, to bring the balm of peace.}
{18701}{}{我们是末世论者。我们叫这个名字是因为我们生于战争之后，来抚平战争的伤痛。}
#{18702}{}{A strange cult south of Adytum and the rest of the Boneyard. Nicole
# says that they are up to something.}
{18702}{}{一个奇怪的仪式要在内城区和晒骨场其他的地方举行。妮可尔说他们好像在等什么。}
#{18703}{}{An ultra-violent gang to our west.}
{18703}{}{我们西边有一个暴力帮派。}
#{18704}{}{A gang to the east. They use vibro-knives.}
{18704}{}{一个帮派在西边。他们使用开膛手。}
#{18705}{}{A gang that came from the Hub, and sells guns. They are north of here.}
{18705}{}{有一伙人来自哈勃城，在这里贩枪。他们在北边。}
#{18706}{}{The Hub is a large city of traders and businesses, to the east.}
{18706}{}{哈勃城是个巨大的商业城市，在东方。}
#{18707}{}{Junktown is a small city just north of the Hub.}
{18707}{}{迦克镇是哈勃城北面的一个小镇。}
#{18708}{}{I can't help you with that.}
{18708}{}{我帮不了你。}
#{18709}{}{She is our leader. She has a vision to restore peace to a factionalized world.}
{18709}{}{她是我们的领袖。她的梦想就是恢复这个破碎世界的和平。}
#{18710}{}{This place is the Angel's Boneyard, the remnants of the old city of
# Los Angeles.}
{18710}{}{这个地方就是美丽的晒骨场，古老的城市洛杉矶的遗迹。}

# Info level 3 【People who know more than something but less than everything】
{18800}{}{Adytum}
{18801}{}{The Followers}
{18802}{}{The Cathedral}
{18803}{}{The Rippers}
{18804}{}{The Blades}
{18805}{}{The Gun Runners}
{18806}{}{The Hub}
{18807}{}{Junktown}
{18808}{}{Water Chip}
{18809}{}{Nicole}
{18810}{}{The Boneyard}
#{18900}{}{A small town to the south. They are good people, if a trifle
# paranoid. Some of them work with us from time to time.}
{18900}{}{南方有个小镇。那里有很多好人，如果不算那些精神病的话。}
#{18901}{}{We are the Followers of the Apocalypse. It is our duty to bring peace
# and learning once again to the world, and to make sure that the
# weapons of war never again scar the earth.}
{18901}{}{我们是末世论者。我们的职责就是让和平和知识再次来到这个世界，确保战争不再给这个地球带来伤痛。}
#{18902}{}{The Cathedral is a great building south of the Boneyard. The Children
# are a cult worshipping a dark and evil god. They must be stopped
# before they spread their religion through violence.}
{18902}{}{大教堂是晒骨场南边最伟大的建筑。教徒们都在崇拜着黑暗罪恶之神。他们必须在使用暴力推广信仰之前停下来。}
#{18903}{}{Inbreds and jackals. They attack anything in sight that isn't related
# to them. They live west of here in a fortress surrounded by traps.}
{18903}{}{天生的豺狼。他们攻击所有他们见到的人。他们住在西面被陷阱环绕的要塞里。}
#{18904}{}{A singularly dangerous group living to the east, who fight with
# vibro-knives. Their leader, Razor, came from the Hub and molded them
# into a fierce family.}
{18904}{}{少见的危险组织住在东面，他们用开膛手杀人。他们的首领，利刃，来自哈勃城，让他们成为了凶残的家族。}
#{18905}{}{They are a gang living in a warehouse to the north, inside a moat of
# radioactive sludge. They sell guns to the other gangs.}
{18905}{}{他们是住在北面仓库的帮派，周围有充满了放射性污泥的护城河。他们向其他帮派出售武器。}
#{18906}{}{The Hub is a vast mercantile city far to the east of us. They send
# caravans to many places, including Adytum.}
{18906}{}{哈勃城是遥远东方的巨大的商业城市。他们向很多地方派遣商队，包括内城区。}
#{18907}{}{It's a small city north of the Hub. I'm told it's a good place to
# stop for the weary traveler.}
{18907}{}{哈勃城北有个小镇。对于疲劳的旅行者来说是个好地方。}
#{18908}{}{Although I've read about Vault technology, it's a little beyond me.}
{18908}{}{我读过避难所科技，没人能超过我。}
#{18909}{}{Nicole is our leader. She's compelled by insight and spirituality to
# bring peace to a world broken by war.}
{18909}{}{妮可尔是我们的领导。她的睿智会给这个被战争破坏的世界带来和平。}
#{18910}{}{This is the heart of the Angel's Boneyard, named for the old city of
# Los Angeles, and for the skeletons of the dead that littered the place
# after the Bomb.}
{18910}{}{这里是美丽的晒骨场的中心，因古老的城市洛杉矶中，充满了核弹袭击后动物的骨架而得名。}
#======================================================================


# MBENT.MAP     (19000)

{19000}{}{Master}
{19001}{}{Lieutenant}
{19002}{}{Children of the Cathedral}
{19003}{}{Followers of the Apocalypse}
{19004}{}{Nightkin}
{19005}{}{Super Mutants}
{19006}{}{Psychics}
{19007}{}{Experiments}
{19008}{}{Water Chip}

#{19100}{}{I don't have to tell you anything.}
{19100}{}{我不会告诉你的。}
#{19101}{}{Such knowledge does not belong with lesser beings.}
{19101}{}{这种知识不属于渺小的生命。}
#{19102}{}{You need not concern yourself with them.}
{19102}{}{不要管的太多。}
#{19103}{}{You are too lowly to question me.}
{19103}{}{你的地位太低不能和我谈话。}
#{19104}{}{None of your business.}
{19104}{}{不会和你交易的。}
#{19105}{}{That is not your concern.}
{19105}{}{不关你的事。}
#{19106}{}{You are too foolish to know of them.}
{19106}{}{你太蠢才不知道他们。}
#{19107}{}{You are not authorized to know of them.}
{19107}{}{你没被授权来了解他们。}
#{19108}{}{Do not bother me about toys.}
{19108}{}{不要用玩具的事打扰我。}

# MBSTRG12.MAP  (19600)

{19600}{}{Master}
{19601}{}{Lieutenant}
{19602}{}{Children of the Cathedral}
{19603}{}{Followers of the Apocalypse}
{19604}{}{Nightkin}
{19605}{}{Super Mutants}
{19606}{}{Psychics}
{19607}{}{Experiments}
{19608}{}{Water Chip}
#{19700}{}{I don't have to tell you anything.}
{19700}{}{我不会告诉你的。}
#{19701}{}{Such knowledge does not belong with lesser beings.}
{19701}{}{这种知识不属于渺小的生命。}
#{19702}{}{You need not concern yourself with them.}
{19702}{}{不要管的太多。}
#{19703}{}{You are too lowly to question me.}
{19703}{}{你的地位太低不能和我谈话。}
#{19704}{}{None of your business.}
{19704}{}{不会和你交易的。}
#{19705}{}{That is not your concern.}
{19705}{}{不关你的事。}
#{19706}{}{You are too foolish to know of them.}
{19706}{}{你太蠢才不知道他们。}
#{19707}{}{You are not authorized to know of them.}
{19707}{}{你没被授权来了解他们。}
#{19708}{}{Do not bother me about toys.}
{19708}{}{不要用玩具的事打扰我。}

# MBVATS12.MAP  (20200)

{20200}{}{Master}
{20201}{}{Lieutenant}
{20202}{}{Children of the Cathedral}
{20203}{}{Followers of the Apocalypse}
{20204}{}{Nightkin}
{20205}{}{Super Mutants}
{20206}{}{Psychics}
{20207}{}{Experiments}
{20208}{}{Water Chip}
#{20300}{}{I don't have to tell you anything.}
{20300}{}{我不会告诉你的。}
#{20301}{}{Such knowledge does not belong with lesser beings.}
{20301}{}{这种知识不属于渺小的生命。}
#{20302}{}{You need not concern yourself with them.}
{20302}{}{不要管的太多。}
#{20303}{}{You are too lowly to question me.}
{20303}{}{你的地位太低不能和我谈话。}
#{20304}{}{None of your business.}
{20304}{}{不会和你交易的。}
#{20305}{}{That is not your concern.}
{20305}{}{不关你的事。}
#{20306}{}{You are too foolish to know of them.}
{20306}{}{你太蠢才不知道他们。}
#{20307}{}{You are not authorized to know of them.}
{20307}{}{你没被授权来了解他们。}
#{20308}{}{Do not bother me about toys.}
{20308}{}{不要用玩具的事打扰我。}


# MSTRLR12.MAP  (20800)

{20800}{}{Master}
{20801}{}{Lieutenant}
{20802}{}{Children of the Cathedral}
{20803}{}{Followers of the Apocalypse}
{20804}{}{Nightkin}
{20805}{}{Super Mutants}
{20806}{}{Psychics}
{20807}{}{Experiments}
{20808}{}{Water Chip}
#{20900}{}{I don't have to tell you anything.}
{20900}{}{我不会告诉你的。}
#{20901}{}{Such knowledge does not belong with lesser beings.}
{20901}{}{这种知识不属于渺小的生命。}
#{20902}{}{You need not concern yourself with them.}
{20902}{}{不要管的太多。}
#{20903}{}{You are too lowly to question me.}
{20903}{}{你的地位太低不能和我谈话。}
#{20904}{}{None of your business.}
{20904}{}{不会和你交易的。}
#{20905}{}{That is not your concern.}
{20905}{}{不关你的事。}
#{20906}{}{You are too foolish to know of them.}
{20906}{}{你太蠢才不知道他们。}
#{20907}{}{You are not authorized to know of them.}
{20907}{}{你没被授权来了解他们。}
#{20908}{}{Do not bother me about toys.}
{20908}{}{不要用玩具的事打扰我。}

# MSTRLR34.MAP  (21400)

{21400}{}{Master}
{21401}{}{Lieutenant}
{21402}{}{Children of the Cathedral}
{21403}{}{Followers of the Apocalypse}
{21404}{}{Nightkin}
{21405}{}{Super Mutants}
{21406}{}{Psychics}
{21407}{}{Experiments}
{21408}{}{Water Chip}
#{21500}{}{I don't have to tell you anything.}
{21500}{}{我不会告诉你的。}
#{21501}{}{Such knowledge does not belong with lesser beings.}
{21501}{}{这种知识不属于渺小的生命。}
#{21502}{}{You need not concern yourself with them.}
{21502}{}{不要管的太多。}
#{21503}{}{You are too lowly to question me.}
{21503}{}{你的地位太低不能和我谈话。}
#{21504}{}{None of your business.}
{21504}{}{不会和你交易的。}
#{21505}{}{That is not your concern.}
{21505}{}{不关你的事。}
#{21506}{}{You are too foolish to know of them.}
{21506}{}{你太蠢才不知道他们。}
#{21507}{}{You are not authorized to know of them.}
{21507}{}{你没被授权来了解他们。}
#{21508}{}{Do not bother me about toys.}
{21508}{}{不要用玩具的事打扰我。}


# V13ENT.MAP    (22000)

# HUBENT.MAP    (22600)

{22600}{}{Police}
{22601}{}{Water Merchants}
{22602}{}{Crimson Caravans}
{22603}{}{Far Go Traders}
{22604}{}{Children of the Cathedral}
{22605}{}{Necropolis}
{22606}{}{Hot Spot}
{22607}{}{Junktown}
{22608}{}{Brotherhood of Steel}
{22609}{}{Shady Sands}
{22610}{}{LA Boneyard}
{22611}{}{Water Towers}
{22612}{}{Old Town}
{22613}{}{Downtown}
{22614}{}{The Heights}
{22615}{}{Deathclaw}
{22616}{}{Water Chip}
#{22700}{}{The police are run by Sheriff Greene to keep law and order in the Hub. There are
# some who believe them to be more of a hindrance than help.}
{22700}{}{格林警长领导着警察负责维护哈勃城的法律和秩序。这里有些人总是扰乱治安。}
#{22701}{}{They control all of the water in the Hub. They seized control of the water towers, and now
# people have to pay them to get water.}
{22701}{}{他们控制着哈勃城所有的水源。他们控制着水塔，现在人们只能向他们买水。}
#{22702}{}{A crazed group of traders who take great risks in order to get to the top.}
{22702}{}{一个疯狂的商人组织为了对高层施加影响而冒着极大的风险。}
#{22703}{}{A medium tempered group of traders who offer fair prices without having to seek out danger to themselves.}
{22703}{}{中层的商人组织为了避免风险而提出公平的价格。}
#{22704}{}{A religious cult who worships something called the Master. They run a hospital on the southeast side of town
# by the Water Merchants.}
{22704}{}{那是一群崇拜主教的信徒。他们在镇西纯水商队附近经营着一家医院。}
#{22705}{}{Creepy place. Some same that it is haunted by mutated humans who eat normal people's brains for food. It is
# somewhere to the east of the Hub.}
{22705}{}{令人毛骨悚然的的地方。据说那里有一些专吃普通人脑子的变种人鬼魂。在哈勃城东面某处。}
#{22706}{}{There are some stories which say there is a place to the southeast of here which got hit by a nuclear warhead.}
{22706}{}{据说东南方的某处曾遭受过核弹攻击。}
#{22707}{}{That's to the north of us. There is a fair amount of trading between us and them. From rumors, Killian and
# Gizmo are at each other's throats.}
{22707}{}{在我们北面。在那里我们公平交易。据说，基利安和吉斯莫互相指责。}
#{22708}{}{That place is the northwest of here. They are a bunch of techno freaks who worship technology. Very spooky people.}
{22708}{}{那个地方在西北。他们是一群崇拜科技的怪人。很怪的人。}
#{22709}{}{A primitive town that is far to the north of here. Not much is known about them, because they don't have enough money
# to trade with us.}
{22709}{}{一个原始村落在北面很远的地方。很少人知道他们，因为他们没钱和我们交易。}
#{22710}{}{That rat infested place is riddled with gang warfare. Were it not for the great trading with Adytum and the Gunrunners, I
# doubt any trader would venture there.}
{22710}{}{那个老鼠滋生的地方因为一场战争而变得神秘。那里很少和内城区以及军火走私者交易，我怀疑有商人在那里冒险。}
#{22711}{}{Those store the water for the Hub. The Water Merchants control the towers.}
{22711}{}{那里储藏哈勃城的饮用水。纯水商队控制着水塔。}
#{22712}{}{Old town is on the northeastern side of town. Only people that hang out there are skags and muties. I've heard that
# there is a thieve's den somewhere in there.}
{22712}{}{旧城区在镇子的东北。那里只有僵尸和变种人。我听说那儿的某个地方有个强盗洞穴。}
#{22713}{}{That's where all the merchants sell things. The Weapon Shop, The Armory, Friendly Lending Company and Maltese Falcon are
# all in that area.}
{22713}{}{那是商人们卖东西的地方。武器店，装备店，友好借贷公司和马耳他猎鹰都在那个地方。}
#{22714}{}{That is where all the rich merchants live. The Water Merchants' leader, Daren Hightower has a huge place there.}
{22714}{}{那是富商聚居区。纯水商队首领，达伦·海托，在那里有一块地。}
#{22715}{}{A myth to scare little children into behaving.}
{22715}{}{一个荒唐的举动吓坏了小孩子。}
#{22716}{}{I don't know anything about that.}
{22716}{}{我不知道。}

# DETHCLAW.MAP  (23200)

# HUBDWNTN.MAP  (23800)

{23800}{}{Police}
{23801}{}{Water Merchants}
{23802}{}{Crimson Caravans}
{23803}{}{Far Go Traders}
{23804}{}{Children of the Cathedral}
{23805}{}{Necropolis}
{23806}{}{Hot Spot}
{23807}{}{Junktown}
{23808}{}{Brotherhood of Steel}
{23809}{}{Shady Sands}
{23810}{}{LA Boneyard}
{23811}{}{Water Towers}
{23812}{}{Old Town}
{23813}{}{Downtown}
{23814}{}{The Heights}
{23815}{}{Deathclaw}
{23816}{}{Water Chip}
#{23900}{}{The police are run by Sheriff Greene to keep law and order in the Hub. There are
# some who believe them to be more of a hindrance than help.}
{23900}{}{格林警长领导着警察负责维护哈勃城的法律和秩序。这里有些人总是扰乱治安。}
#{23901}{}{They control all of the water in the Hub. They seized control of the water towers, and now
# people have to pay them to get water.}
{23901}{}{他们控制着哈勃城所有的水源。他们控制着水塔，现在人们只能向他们买水。}
#{23902}{}{A crazed group of traders who take great risks in order to get to the top.}
{23902}{}{一个疯狂的商人组织为了对高层施加影响而冒着极大的风险。}
#{23903}{}{A medium tempered group of traders who offer fair prices without having to seek out danger to themselves.}
{23903}{}{中层的商人组织为了避免风险而提出公平的价格。}
#{23904}{}{A religious cult who worships something called the Master. They run a hospital on the southeast side of town
# by the Water Merchants.}
{23904}{}{那是一群崇拜主教的信徒。他们在镇西纯水商队附近经营着一家医院。}
#{23905}{}{Creepy place. Some say that it is haunted by mutated humans who eat normal people's brains for food. It is
# somewhere to the east of the Hub.}
{23905}{}{令人毛骨悚然的的地方。据说那里有一些专吃普通人脑子的变种人鬼魂。在哈勃城东面某处。}
#{23906}{}{There are some stories which say there is a place to the southeast of here which got hit by a nuclear warhead.}
{23906}{}{据说东南方的某处曾遭受过核弹攻击。}
#{23907}{}{That's to the north of us. There is a fair amount of trading between us and them. From rumors, Killian and
# Gizmo are at each other's throats.}
{23907}{}{在我们北面。在那里我们公平交易。据说，基利安和吉斯莫互相指责。}
#{23908}{}{That place is to the northwest of here. They are a bunch of techno freaks who worship technology. Very spooky people.}
{23908}{}{那个地方在西北。他们是一群崇拜科技的怪人。很怪的人。}
#{23909}{}{A primitive town that is far to the north of here. Not much is known about them, because they don't have enough money
# to trade with us.}
{23909}{}{一个原始村落在北面很远的地方。很少人知道他们，因为他们没钱和我们交易。}
#{23910}{}{That rat infested place is riddled with gang warfare. Were it not for the great trading with Adytum and the Gunrunners, I
# doubt any trader would venture there.}
{23910}{}{那个老鼠滋生的地方因为一场战争而变得神秘。那里很少和内城区以及军火走私者交易，我怀疑有商人在那里冒险。}
#{23911}{}{Those store the water for the Hub. The Water Merchants control the towers.}
{23911}{}{那里储藏哈勃城的饮用水。纯水商队控制着水塔。}
#{23912}{}{Old town is on the northeastern side of town. Only people that hang out there are skags and muties. I've heard that
# there is a thieve's den somewhere in there.}
{23912}{}{旧城区在镇子的东北。那里只有僵尸和变种人。我听说那儿的某个地方有个强盗洞穴。}
#{23913}{}{That's where all the merchants sell things. The Weapon Shop, The Armory, Friendly Lending Company and Maltese Falcon are
# all in that area.}
{23913}{}{那是商人们卖东西的地方。武器店，装备店，友好借贷公司和马耳他猎鹰都在那个地方。}
#{23914}{}{That is where all the rich merchants live. The Water Merchants' leader, Daren Hightower has a huge place there.}
{23914}{}{那是富商聚居区。纯水商队首领，达伦·海托，在那里有一块地。}
#{23915}{}{A myth to scare little children into behaving.}
{23915}{}{一个荒唐的举动吓坏了小孩子。}
#{23916}{}{I don't know anything about that.}
{23916}{}{我不知道。}

# HUBHEIGT.MAP  (24400)

{24400}{}{Police}
{24401}{}{Water Merchants}
{24402}{}{Crimson Caravans}
{24403}{}{Far Go Traders}
{24404}{}{Children of the Cathedral}
{24405}{}{Necropolis}
{24406}{}{Hot Spot}
{24407}{}{Junktown}
{24408}{}{Brotherhood of Steel}
{24409}{}{Shady Sands}
{24410}{}{LA Boneyard}
{24411}{}{Water Towers}
{24412}{}{Old Town}
{24413}{}{Downtown}
{24414}{}{The Heights}
{24415}{}{Deathclaw}
{24416}{}{Water Chip}
#{24500}{}{The police are run by Sheriff Greene to keep law and order in the Hub. There are
# some who believe them to be more of a hindrance than help.}
{24500}{}{格林警长领导着警察负责维护哈勃城的法律和秩序。这里有些人总是扰乱治安。}
#{24501}{}{They control all of the water in the Hub. They seized control of the water towers, and now
# people have to pay them to get water.}
{24501}{}{他们控制着哈勃城所有的水源。他们控制着水塔，现在人们只能向他们买水。}
#{24502}{}{A crazed group of traders who take great risks in order to get to the top.}
{24502}{}{一个疯狂的商人组织为了对高层施加影响而冒着极大的风险。}
#{24503}{}{A medium tempered group of traders who offer fair prices without having to seek out danger to themselves.}
{24503}{}{中层的商人组织为了避免风险而提出公平的价格。}
#{24504}{}{A religious cult who worships something called the Master. They run a hospital on the southeast side of town
# by the Water Merchants.}
{24504}{}{那是一群崇拜主教的信徒。他们在镇西纯水商队附近经营着一家医院。}
#{24505}{}{Creepy place. Some say that it is haunted by mutated humans who eat normal people's brains for food. It is
# somewhere to the east of the Hub.}
{24505}{}{令人毛骨悚然的的地方。据说那里有一些专吃普通人脑子的变种人鬼魂。在哈勃城东面某处。}
#{24506}{}{There are some stories which say there is a place to the southeast of here which got hit by a nuclear warhead.}
{24506}{}{据说东南方的某处曾遭受过核弹攻击。}
#{24507}{}{That's to the north of us. There is a fair amount of trading between us and them. From rumors, Killian and
# Gizmo are at each other's throats.}
{24507}{}{在我们北面。在那里我们公平交易。据说，基利安和吉斯莫互相指责。}
#{24508}{}{That place is to the northwest of here. They are a bunch of techno freaks who worship technology. Very spooky people.}
{24508}{}{那个地方在西北。他们是一群崇拜科技的怪人。很怪的人。}
#{24509}{}{A primitive town that is far to the north of here. Not much is known about them, because they don't have enough money
# to trade with us.}
{24509}{}{一个原始村落在北面很远的地方。很少人知道他们，因为他们没钱和我们交易。}
#{24510}{}{That rat infested place is riddled with gang warfare. Were it not for the great trading with Adytum and the Gunrunners, I
# doubt any trader would venture there.}
{24510}{}{那个老鼠滋生的地方因为一场战争而变得神秘。那里很少和内城区以及军火走私者交易，我怀疑有商人在那里冒险。}
#{24511}{}{Those store the water for the Hub. The Water Merchants control the towers.}
{24511}{}{那里储藏哈勃城的饮用水。纯水商队控制着水塔。}
#{24512}{}{Old town is on the northeastern side of town. Only people that hang out there are skags and muties. I've heard that
# there is a thieve's den somewhere in there.}
{24512}{}{旧城区在镇子的东北。那里只有僵尸和变种人。我听说那儿的某个地方有个强盗洞穴。}
#{24513}{}{That's where all the merchants sell things. The Weapon Shop, The Armory, Friendly Lending Company and Maltese Falcon are
# all in that area.}
{24513}{}{那是商人们卖东西的地方。武器店，装备店，友好借贷公司和马耳他猎鹰都在那个地方。}
#{24514}{}{That is where all the rich merchants live. The Water Merchants' leader, Daren Hightower has a huge place there.}
{24514}{}{那是富商聚居区。纯水商队首领，达伦·海托，在那里有一块地。}
#{24515}{}{A myth to scare little children into behaving.}
{24515}{}{一个荒唐的举动吓坏了小孩子。}
#{24516}{}{I don't know anything about that.}
{24516}{}{我不知道。}

# HUBOLDTN.MAP  (25000)

{25000}{}{Police}
{25001}{}{Water Merchants}
{25002}{}{Crimson Caravans}
{25003}{}{Far Go Traders}
{25004}{}{Children of the Cathedral}
{25005}{}{Necropolis}
{25006}{}{Hot Spot}
{25007}{}{Junktown}
{25008}{}{Brotherhood of Steel}
{25009}{}{Shady Sands}
{25010}{}{LA Boneyard}
{25011}{}{Water Towers}
{25012}{}{Old Town}
{25013}{}{Downtown}
{25014}{}{The Heights}
{25015}{}{Deathclaw}
{25016}{}{Water Chip}
#{25100}{}{The police are run by Sheriff Greene to keep law and order in the Hub. There are
# some who believe them to be more of a hindrance than help.}
{25100}{}{格林警长领导着警察负责维护哈勃城的法律和秩序。这里有些人总是扰乱治安。}
#{25101}{}{They control all of the water in the Hub. They seized control of the water towers, and now
# people have to pay them to get water.}
{25101}{}{他们控制着哈勃城所有的水源。他们控制着水塔，现在人们只能向他们买水。}
#{25102}{}{A crazed group of traders who take great risks in order to get to the top.}
{25102}{}{一个疯狂的商人组织为了对高层施加影响而冒着极大的风险。}
#{25103}{}{A medium tempered group of traders who offer fair prices without having to seek out danger to themselves.}
{25103}{}{中层的商人组织为了避免风险而提出公平的价格。}
#{25104}{}{A religious cult who worships something called the Master. They run a hospital on the southeast side of town
# by the Water Merchants.}
{25104}{}{那是一群崇拜主教的信徒。他们在镇西纯水商队附近经营着一家医院。}
#{25105}{}{Creepy place. Some say that it is haunted by mutated humans who eat normal people's brains for food. It is
# somewhere to the east of the Hub.}
{25105}{}{令人毛骨悚然的的地方。据说那里有一些专吃普通人脑子的变种人鬼魂。在哈勃城东面某处。}
#{25106}{}{There are some stories which say there is a place to the southeast of here which got hit by a nuclear warhead.}
{25106}{}{据说东南方的某处曾遭受过核弹攻击。}
#{25107}{}{That's to the north of us. There is a fair amount of trading between us and them. From rumors, Killian and
# Gizmo are at each other's throats.}
{25107}{}{在我们北面。在那里我们公平交易。据说，基利安和吉斯莫互相指责。}
#{25108}{}{That place is to the northwest of here. They are a bunch of techno freaks who worship technology. Very spooky people.}
{25108}{}{那个地方在西北。他们是一群崇拜科技的怪人。很怪的人。}
#{25109}{}{A primitive town that is far to the north of here. Not much is known about them, because they don't have enough money
# to trade with us.}
{25109}{}{一个原始村落在北面很远的地方。很少人知道他们，因为他们没钱和我们交易。}
#{25110}{}{That rat infested place is riddled with gang warfare. Were it not for the great trading with Adytum and the Gunrunners, I
# doubt any trader would venture there.}
{25110}{}{那个老鼠滋生的地方因为一场战争而变得神秘。那里很少和内城区以及军火走私者交易，我怀疑有商人在那里冒险。}
#{25111}{}{Those store the water for the Hub. The Water Merchants control the towers.}
{25111}{}{那里储藏哈勃城的饮用水。纯水商队控制着水塔。}
#{25112}{}{Old town is on the northeastern side of town. Only people that hang out there are skags and muties. I've heard that
# there is a thieve's den somewhere in there.}
{25112}{}{旧城区在镇子的东北。那里只有僵尸和变种人。我听说那儿的某个地方有个强盗洞穴。}
#{25113}{}{That's where all the merchants sell things. The Weapon Shop, The Armory, Friendly Lending Company and Maltese Falcon are
# all in that area.}
{25113}{}{那是商人们卖东西的地方。武器店，装备店，友好借贷公司和马耳他猎鹰都在那个地方。}
#{25114}{}{That is where all the rich merchants live. The Water Merchants' leader, Daren Hightower has a huge place there.}
{25114}{}{那是富商聚居区。纯水商队首领，达伦·海托，在那里有一块地。}
#{25115}{}{A myth to scare little children into behaving.}
{25115}{}{一个荒唐的举动吓坏了小孩子。}
#{25116}{}{I don't know anything about that.}
{25116}{}{我不知道。}

# HUBWATER.MAP  (25600)

{25600}{}{Police}
{25601}{}{Water Merchants}
{25602}{}{Crimson Caravans}
{25603}{}{Far Go Traders}
{25604}{}{Children of the Cathedral}
{25605}{}{Necropolis}
{25606}{}{Hot Spot}
{25607}{}{Junktown}
{25608}{}{Brotherhood of Steel}
{25609}{}{Shady Sands}
{25610}{}{LA Boneyard}
{25611}{}{Water Towers}
{25612}{}{Old Town}
{25613}{}{Downtown}
{25614}{}{The Heights}
{25615}{}{Deathclaw}
{25616}{}{Water Chip}
#{25700}{}{The police are run by Sheriff Greene to keep law and order in the Hub. There are
# some who believe them to be more of a hindrance than help.}
{25700}{}{格林警长领导着警察负责维护哈勃城的法律和秩序。这里有些人总是扰乱治安。}
#{25701}{}{They control all of the water in the Hub. They seized control of the water towers, and now
# people have to pay them to get water.}
{25701}{}{他们控制着哈勃城所有的水源。他们控制着水塔，现在人们只能向他们买水。}
#{25702}{}{A crazed group of traders who take great risks in order to get to the top.}
{25702}{}{一个疯狂的商人组织为了对高层施加影响而冒着极大的风险。}
#{25703}{}{A medium tempered group of traders who offer fair prices without having to seek out danger to themselves.}
{25703}{}{中层的商人组织为了避免风险而提出公平的价格。}
#{25704}{}{A religious cult who worships something called the Master. They run a hospital on the southeast side of town
# by the Water Merchants.}
{25704}{}{那是一群崇拜主教的信徒。他们在镇西纯水商队附近经营着一家医院。}
#{25705}{}{Creepy place. Some say that it is haunted by mutated humans who eat normal people's brains for food. It is
# somewhere to the east of the Hub.}
{25705}{}{令人毛骨悚然的的地方。据说那里有一些专吃普通人脑子的变种人鬼魂。在哈勃城东面某处。}
#{25706}{}{There are some stories which say there is a place to the southeast of here which got hit by a nuclear warhead.}
{25706}{}{据说东南方的某处曾遭受过核弹攻击。}
#{25707}{}{That's to the north of us. There is a fair amount of trading between us and them. From rumors, Killian and
# Gizmo are at each other's throats.}
{25707}{}{在我们北面。在那里我们公平交易。据说，基利安和吉斯莫互相指责。}
#{25708}{}{That place is to the northwest of here. They are a bunch of techno freaks who worship technology. Very spooky people.}
{25708}{}{那个地方在西北。他们是一群崇拜科技的怪人。很怪的人。}
#{25709}{}{A primitive town that is far to the north of here. Not much is known about them, because they don't have enough money
# to trade with us.}
{25709}{}{一个原始村落在北面很远的地方。很少人知道他们，因为他们没钱和我们交易。}
#{25710}{}{That rat infested place is riddled with gang warfare. Were it not for the great trading with Adytum and the Gunrunners, I
# doubt any trader would venture there.}
{25710}{}{那个老鼠滋生的地方因为一场战争而变得神秘。那里很少和内城区以及军火走私者交易，我怀疑有商人在那里冒险。}
#{25711}{}{Those store the water for the Hub. The Water Merchants control the towers.}
{25711}{}{那里储藏哈勃城的饮用水。纯水商队控制着水塔。}
#{25712}{}{Old town is on the northeastern side of town. Only people that hang out there are skags and muties. I've heard that
# there is a thieve's den somewhere in there.}
{25712}{}{旧城区在镇子的东北。那里只有僵尸和变种人。我听说那儿的某个地方有个强盗洞穴。}
#{25713}{}{That's where all the merchants sell things. The Weapon Shop, The Armory, Friendly Lending Company and Maltese Falcon are
# all in that area.}
{25713}{}{那是商人们卖东西的地方。武器店，装备店，友好借贷公司和马耳他猎鹰都在那个地方。}
#{25714}{}{That is where all the rich merchants live. The Water Merchants' leader, Daren Hightower has a huge place there.}
{25714}{}{那是富商聚居区。纯水商队首领，达伦·海托，在那里有一块地。}
#{25715}{}{A myth to scare little children into behaving.}
{25715}{}{一个荒唐的举动吓坏了小孩子。}
#{25716}{}{I don't know anything about that.}
{25716}{}{我不知道。}

# GLOW1.MAP     (26200)
# GLOW2.MAP     (26800)


#
# LABLADES.MAP
#
#

#  ======================================================================
#    BLADES
# Info Level 1 【People who know nothing】
{27400}{}{Adytum}
{27401}{}{The Followers}
{27402}{}{The Cathedral}
{27403}{}{The Rippers}
{27404}{}{The Blades}
{27405}{}{The Gun Runners}
{27406}{}{The Hub}
{27407}{}{Junktown}
{27408}{}{Water Chip}
{27409}{}{Razor}
{27410}{}{Necropolis}
{27411}{}{The Glow}
{27412}{}{The Boneyard}
#{27500}{}{They're a town to the west.}
{27500}{}{他们住在西面的镇里。}
#{27501}{}{A bunch of wimps.}
{27501}{}{一群懦夫。}
#{27502}{}{Religious nuts.}
{27502}{}{狂热的信徒。}
#{27503}{}{Our sworn enemies!}
{27503}{}{我们不共戴天的敌仇。}
#{27504}{}{That's us!}
{27504}{}{是我们！}
#{27505}{}{They sell guns to us sometimes.}
{27505}{}{他们有时卖给我们武器。}
#{27506}{}{I think it's a trading place.}
{27506}{}{我想那是个集市。}
#{27507}{}{Never heard of it.}
{27507}{}{从没听说过。}
#{27508}{}{A what?}
{27508}{}{什么？}
#{27509}{}{She's our leader, the most bad-ass bitch in town!}
{27509}{}{她是我们的领袖，镇里一个倔脾气的母狗！}
#{27510}{}{Necro- what? That's sick.}
{27510}{}{活死人－什么？真恶心。}
#{27511}{}{You're kidding, right?}
{27511}{}{你在开玩笑，不是吗？}
#{27512}{}{This is the Boneyard.}
{27512}{}{这里是晒骨场。}


# Info Level 2 【People who know something】
{27600}{}{Adytum}
{27601}{}{The Followers}
{27602}{}{The Cathedral}
{27603}{}{The Rippers}
{27604}{}{The Blades}
{27605}{}{The Gun Runners}
{27606}{}{The Hub}
{27607}{}{Junktown}
{27608}{}{Water Chip}
{27609}{}{Razor}
{27610}{}{Necropolis}
{27611}{}{The Glow}
{27612}{}{The Boneyard}
#{27700}{}{They are a village of weaklings to the southwest.}
{27700}{}{他们是西南村里的一群懦夫。}
#{27701}{}{Pathetic peace-preachers to the west. We'd crush them if we weren't
# busy fighting the Rippers.}
{27701}{}{可怜的和平传教士在西面。如果我们不能战胜电锯党，我们会消灭他们。}
#{27702}{}{Religious freaks. Harmless and useless.}
{27702}{}{奇怪的信徒。没有一点用处。}
#{27703}{}{Our arch-enemies to the west will be crushed soon!}
{27703}{}{我们的西面的死敌就要被干掉了！}
#{27704}{}{We are the Blades! Never forget it!}
{27704}{}{我们是利刃帮！不要忘了！}
#{27705}{}{They were once a gang, but they became soft. They do sell good guns,
# though.}
{27705}{}{他们曾经是一伙人，不过他们变得温和了。尽管他们卖了很多枪。}
#{27706}{}{Traders and merchants.}
{27706}{}{商人和店主。}
#{27707}{}{I've heard of that place, but not anything about it.}
{27707}{}{我听说过那个地方，但不知道它的事情。}
#{27708}{}{A what?}
{27708}{}{什么？}
#{27709}{}{Razor is the most accomplished fighter of us all. She will lead us to
# victory.}
{27709}{}{剃刀是我们中间最优秀的战士。她会带领我们走向胜利。}
#{27710}{}{That's some story about a city of cannibals, used to frighten children.}
{27710}{}{那些食人者城市的故事，经常用来吓唬小孩子。}
#{27711}{}{Must be where a nuke hit.}
{27711}{}{应该是核弹袭击过的地方。}
#{27712}{}{This is the Boneyard.}
{27712}{}{这里是晒骨场。}


# Info level 3 【People who know more than something but less than everything】
{27800}{}{Adytum}
{27801}{}{The Followers}
{27802}{}{The Cathedral}
{27803}{}{The Rippers}
{27804}{}{The Blades}
{27805}{}{The Gun Runners}
{27806}{}{The Hub}
{27807}{}{Junktown}
{27808}{}{Water Chip}
{27809}{}{Razor}
{27810}{}{Necropolis}
{27811}{}{The Glow}
{27812}{}{The Boneyard}
#{27900}{}{Don't be fooled. Adytum looks like a little village, but their
# Regulators are tough.}
{27900}{}{不要干蠢事。内城区看起来像个小村，但他们的调解者像个恶棍。}
#{27901}{}{Hmph. Don't get me started. They don't have the stomach or courage to
# fight.}
{27901}{}{哈哈。不要吓我。他们没有勇气也没有实力来开战。}
#{27902}{}{They're cultists in a big church to the south. They seem harmless but
# something weird is going on there.}
{27902}{}{他们生活在南边的大教堂里。看起来一副无害的样子但有些古怪。}
#{27903}{}{The Rippers are like mangy dogs - vicious, inbred, and stupid.}
{27903}{}{电锯党像疯狗一样－可恶的，天生的，愚蠢的。}
#{27904}{}{See my blade? We make these ourselves. Every one of use makes his
# own. Hence our name.}
{27904}{}{看到我的刀刃了吗？我们自己做的。所有人都使用自己做的刀子。所以我们叫这个名字。}
#{27905}{}{They came down from the Hub looking for turf, but they decided to
# become salesmen instead of warriors.}
{27905}{}{他们看起来像是哈勃城里赶出来的，但他们决定由战士变成商人。}
#{27906}{}{That's a trading city to the east. Merchants from there come here
# sometimes to trade with Adytum and the Gun Runners.}
{27906}{}{那是东边的一个商贸城。那里的商人有时会和内城区和武器走私贩交易。}
#{27907}{}{I think it's north-east of here. It's a small city.}
{27907}{}{我想它在东北方。是个小镇。}
#{27908}{}{A what?}
{27908}{}{什么？}
#{27909}{}{Razor is our leader and champion. I have no doubt that her experience
# will grant us victory at last over those Rippers.}
{27909}{}{剃刀是我们的领袖和战士。我从没怀疑过她的经验会让我们战胜电锯党。}
#{27910}{}{Far east of here. Supposedly, ghouls that eat human flesh live there.
# I wouldn't want to fight the ghouls.}
{27910}{}{离这很远的东方。据说，那里的僵尸以人肉为生。我不想和僵尸打仗。}
#{27911}{}{That's supposed to be the ruins of some place that got hit
# straight-on by a nuke. I think it's way to the south.}
{27911}{}{可以想象直接被核弹命中的地方会被彻底摧毁。我想那是通向南方的路。}
#{27912}{}{This is the Boneyard.}
{27912}{}{这里是晒骨场。}
#  ======================================================================


#
# LARIPPER.MAP  (28000)
#
#

#======================================================================
#
#RIPPERS
#
#The Rippers will not engage in dialog, and thus have no
#tell-me-abouts.
#
#======================================================================


#
# LAGUNRUN.MAP  (28600)
#
#

#  ======================================================================
#   GUN RUNNERS
#Info Level 1 【People who know nothing】
{28600}{}{Adytum}
{28601}{}{The Followers}
{28602}{}{The Cathedral}
{28603}{}{The Rippers}
{28604}{}{The Blades}
{28605}{}{The Gun Runners}
{28606}{}{The Hub}
{28607}{}{Junktown}
{28608}{}{Water Chip}
{28609}{}{The Boneyard}
#{28700}{}{A small village south of here.}
{28700}{}{南边有个小村。}
#{28701}{}{A group of hippies to the south.}
{28701}{}{一群嬉皮士在南面。}
#{28702}{}{Do you mean those guys in the brown robes?}
{28702}{}{你的意思是那些家伙穿着褐色长袍？}
#{28703}{}{Hair-trigger gang to the west.}
{28703}{}{一群长发人在西面。}
#{28704}{}{Sneaky gang to the east.}
{28704}{}{一群鬼鬼祟祟的人在东面。}
#{28705}{}{Yeah? What?}
{28705}{}{是？什么？}
#{28706}{}{We buy guns from them and sell 'em direct to you!}
{28706}{}{我们从他们那里买枪并要他们注意你！}
#{28707}{}{Yeah, small city north of the Hub.}
{28707}{}{是的，哈勃城北面有个小镇。}
#{28708}{}{A what?}
{28708}{}{什么？}
#{28709}{}{This is the Boneyard.}
{28709}{}{这里是晒骨场。}

# Info Level 2 【People who know something】
{28800}{}{Adytum}
{28801}{}{The Followers}
{28802}{}{The Cathedral}
{28803}{}{The Rippers}
{28804}{}{The Blades}
{28805}{}{The Gun Runners}
{28806}{}{The Hub}
{28807}{}{Junktown}
{28808}{}{Water Chip}
{28809}{}{The Boneyard}
#{28900}{}{That's a small village to the south. They're pretty well fortified.}
{28900}{}{南面有个小镇。他们几乎是加强的。}
#{28901}{}{A group of peace-lovers hiding out south of here. We should just get
# rid of them.}
{28901}{}{一群和平爱好者隐居在南面。我们只是想摆脱他们。}
#{28902}{}{Oh yeah, those crazy old monks. They're nuts. Their big church is
# south of the Boneyard.}
{28902}{}{哦耶，那些疯狂的老信徒。他们很狂热。他们的大教堂在晒骨场南方。}
#{28903}{}{Hey, they may be stupid, but they sure buy a lot of guns!}
{28903}{}{嗨，他们真愚蠢，但他们买了很多枪！}
#{28904}{}{They always use those weird vibro-knives that they make. I'd like to
# get my hands on one. But at least they buy some guns, too.}
{28904}{}{他们经常使用自制的古怪刀子。我想帮他们。但他们也买了一些枪。}
#{28905}{}{You're talking to us.}
{28905}{}{你在和我说话。}
#{28906}{}{It's a big trading center back east. We trade with Hub merchants to
# buy and sell weapons and armor.}
{28906}{}{背对的东面就是一个大的交易中心。我们同哈勃商人交易武器和装甲。}
#{28907}{}{A small town north of the Hub. Kinda strict.}
{28907}{}{准确的说。哈勃城北面有个小镇。}
#{28908}{}{Never heard of that.}
{28908}{}{从没听说过。}
#{28909}{}{We're in the north side of the Boneyard.}
{28909}{}{我们住在晒骨场北面。}

# Info Level 3 【People who know more than something but less than everything】
{29000}{}{Adytum}
{29001}{}{The Followers}
{29002}{}{The Cathedral}
{29003}{}{The Rippers}
{29004}{}{The Blades}
{29005}{}{The Gun Runners}
{29006}{}{The Hub}
{29007}{}{Junktown}
{29008}{}{Water Chip}
{29009}{}{The Boneyard}
#{29100}{}{They are a small town to the south. They don't deal with us. I
# couldn't care less about them.}
{29100}{}{他们住在南边的小镇。从不与我们做生意。我从不关心他们。}
#{29101}{}{They try to convert everyone to their ways of peace while they hide
# in their library to the south. They don't help business any!}
{29101}{}{当他们从南面的图书馆时想利用和平的手段让人们接受我们的信仰。他们不会对商业有帮助的！}
#{29102}{}{The Cathedral's this big church south of the Boneyard, where some
# strange cult worships a Dark God. I think they're freaky.}
{29102}{}{大教堂是晒骨场的一个很大的教堂，在那里一群奇怪的信徒信奉着黑暗神。我认为他们有病。}
#{29103}{}{The Rippers are all one big family, literally. They're impossible to
# deal with if they don't know you, so don't even try. They are in a big
# booby-trapped fortress southwest of us. Watch out for land mines if
# you're stupid enough to visit.}
{29103}{}{表面上看，电锯党是个大家族。他们不会同不认识的人做生意，所以不要试了。他们住在西南一个傻瓜留下的要塞里。如果你愚蠢到想去那里旅游就要小心地雷。}
#{29104}{}{They've converted several small buildings to the southeast into their
# home. They are pretty well organized and smarter than the Rippers.
# They sometimes let outsiders join, too. Their leader, Razor, is one
# tough woman.}
{29104}{}{他们在东南的家里建了几个小建筑。他们比电锯党要有组织的多。他们有时也会让外人加入。他们的领袖，剃刀，是个粗暴的女人。}
#{29105}{}{That's us. Good money in selling guns to the Blades and the Rippers here.}
{29105}{}{那是我们。向利刃帮和电锯党卖武器而赚了很多钱。}
#{29106}{}{That's the trading city east of here where we get our guns and do
# trading. They send out caravans all over the place. You could probably
# travel with a caravan when one shows up in Adytum.}
{29106}{}{东边是个贸易城，我们在那里进行交易并获得武器。他们的商队遍布各地。当商队从内城区出发时也许你可以加入。}
#{29107}{}{It's a small frontier town just north of the Hub. There's a great
# casino there, but the town's sheriff is just a little too
# overbearing.}
{29107}{}{那是个哈勃城北面的边境小镇。那里有很棒的娱乐场，但那里的治安官很是蛮横。}
#{29108}{}{I have no idea what that is.}
{29108}{}{我不知道那是什么。}
#{29109}{}{This is the north side of the Boneyard. It's funny, people from
# outside use it as a curse - if something's bad, they say it 'Bites the
# Bone'. But it's not too bad once you get used to it.}
{29109}{}{这里是晒骨场北面。真有趣，外来人把它看作诅咒－如果那些东西不好的话，他们会说“喝凉水都塞牙”。其实你习惯的话你会不认为那有这么糟。}
#  ======================================================================


# CHILDEAD.MAP  (29200)

# MBDEAD.MAP    (29800)

# MOUNTN1.MAP   (30400)
# MOUNTN2.MAP   (31000)
# FOOT.MAP      (31600)
# TARDIS.MAP    (32200)
# TALKCOW.MAP   (32800)
# USEDCAR.MAP   (33400)
# BRODEAD.MAP   (34000)
# DESCRVN1.MAP  (34600)
# DESCRVN2.MAP  (35200)
# MNTCRVN1.MAP  (35800)
# MNTCRVN2.MAP  (36400)
