#{100}{}{You see the Overseer.}
{100}{}{你看见所长。}
#{101}{}{Ahh, you're here. Good. Well, only good that you're here. We've got
# a problem. A big one. The controller chip for our water purification system has
# given up the ghost. We can't make another one and the process is too complicated
# for a work-around system.
# Simply put, we're running out of drinking water. No water, no Vault.
# Now we both know we've had our differences as you've grown up. You've got the
# wanderlust in you - desires for things the Vault just can't satisfy. And you know
# I think this just might be the last safe place anywhere so I'm always worried
# about those who want to take off on adventures. Hey, if everyone left, I'd be out
# of a job!
# Seriously, this is crucial to our survival. And frankly, I think you're the only
# hope we have.
# You need to go find us another controller chip.}
{101}{}{啊，你在这里。呃，唯一的好事是你在这里。我们出了麻烦，大麻烦。我们净水系统中的控制芯片坏了。再造一个出来也不太可能，而其他处理办法又太过复杂。简单地说，我们快没饮用水了。没有水，就没有避难所。我们俩都明白我们之间有分歧，你骨子里头有一股不羁的野性－－自从你长大后就一直渴望出去旅行。而你要知道，我想这里是世上最后一个安全的地方了。所以我总是担心那些想出去冒险的人。嘿，如果人都走光了，我可就没用了！严肃点讲，这是我们继续生存的关键。老实说，我想你大概是我们唯一的希望。你必须去找另一个控制芯片来。}
#{102}{Over_0a}{There's a picture on your PIP to help you identify it.}
{102}{Over_0a}{你的哔哔小子上有张帮你鉴别它的图。}
#{103}{Over_1}{You have three months to retrieve the chip before the vault runs out
# of water.}
{103}{Over_1}{你只有三个月的时间取回芯片，不然避难所就会断水。}
#{104}{}{One month . . . two . . . four . . . five . . . six . . .}
{104}{}{一个月……二……四……五……六……}
#{105}{Over_2}{You have two months, maybe less, before the vault runs out of water.
# We need that chip!}
{105}{Over_2}{你还有两个月，也许更少，避难所的水就要用完了。我们急需那芯片！}
#{106}{Over_3}{We estimate we have four to five months before the vault runs out of
# water. We need that chip!}
{106}{Over_3}{我们估计大约还有四到五个月避难所的水会被用完。我们要那芯片！}
#{107}{Over_4}{Here's some equipment you'll probably need.}
{107}{Over_4}{这儿有些装备你大概用得上。}
#{108}{Over_4a}{If we didn't have to do this, I'd never ask. And if you don't do this,
# I don't know who else can. Help us. You're our only . . . chance, I guess.}
{108}{Over_4a}{我不敢想象如果我们失败会怎样。如果连你也做不到，我不知道还有其他谁能干。救救我们。我想，你是唯一……的机会。}
#{109}{Over_5}{If you need help, come back here. Obviously, we'll do whatever we
# can. But we don't have a lot of time.  Be safe, find that chip, and get back here.}
{109}{Over_5}{如果你有困难，就回来。我们会尽一切努力提供帮助。但我们的时间不多。尽快的找到那芯片，然后安全的带回来。}
#{110}{Over_6}{We marked your map with the location of another Vault. Not a bad
# place to start, I think. Then again, what the heck do I know
# about the outside? I . . . look. Y' You know you're important to me and
# to . . . I-I really . . . just be safe, OK?}
{110}{Over_6}{我们在你的地图上标出了另一个避难所的位置。我想，先去那儿试试不算坏主意吧。还有，我还知道些外面的什么来着？我……啊对了，你，你对我很重要所以……我，我真的……在外面小心保住命，好吗？}
#{111}{Over_7}{You're back! And in one piece! How goes the search?}
{111}{Over_7}{你回来了！而且还没缺胳膊少腿的！太不可思议了！有什么发现没？}
#{112}{}{Not good, but I noticed the radiation count is low. Why don't we just move the people out of the vault?}
{112}{}{不太乐观，不过我发现放射线强度低了很多。我们为什么不把大家迁出避难所呢？}
#{113}{}{I haven't found the chip yet. Can't we just make a replacement?}
{113}{}{我还没找到那芯片。我们干脆再造一块新的如何？}
#{114}{}{Nothing yet.}
{114}{}{还没有。}
#{115}{}{Nuh.}
{115}{}{没。}
#{116}{Over_8}{Look, I know it's got to be tough. But we're counting on you. And
# we're running out of time. Please! Keep trying!}
{116}{Over_8}{看，我知道这会很难。但我们全都指望你了。而且时间所剩不多。求你！继续找下去！}
#{117}{Over_9}{Ahh, you never did listen to me. We don't have the necessary parts
# anymore. We've used up all the supplies required.}
{117}{Over_9}{啊，你显然没听我说话。那些关键的零件早就没了。我们已经用完了所有的备用品。}
#{118}{}{Oh, ok. Thanks.}
{118}{}{哦，好。谢谢。}
#{119}{Over_10}{We've debated this before. You ought to know now, after being out
# there! You think the rest of us could survive that?
# Besides, I'd be out of a job! I'm management! It's not like I know how to
# do anything useful!}
{119}{Over_10}{我们之前已经争论过了。如今你已经去过了野外，你应当明白！你认为我们这些人能在那样的环境下活命？再说，我会丢了工作！我做的是管理！到了外面之后我干什么啊！}
#{120}{}{We agree on that.}
{120}{}{这一点上我们没分歧。}
#{121}{Over_12}{Well, do you have the chip?}
{121}{Over_12}{好，你弄到芯片了？}
#{122}{}{Not yet. Sorry.}
{122}{}{还没。抱歉。}
#{123}{}{I still say we just pack everybody up and move out of here.}
{123}{}{我还是坚持应该召集大家搬出这里。}
#{124}{}{No, but I have a lot of other things to tell you!}
{124}{}{不，但我还有很多事要告诉你！}
#{125}{}{Nuh.}
{125}{}{唔。}
#{126}{Over_13}{【The Overseer sighs.】 Don't be sorry. I know you're trying your best and that means a lot.
# But you can't give up now.}
{126}{Over_13}{【所长叹气道】别难过。我知道你已经尽力了，这一点很重要。但你现在不能放弃。}
#{127}{Over_14}{This isn't the best time to debate that. Get the chip, give us the
# option. Most of these people, including me, won't survive out there.}
{127}{Over_14}{现在不是为那问题争论的时候。搞到那芯片，给我们选择的余地。这里的大多数人，包括我，不能在外头生存下来。}
#{128}{}{OK, I'll go see if I can find it.}
{128}{}{好吧，我去看看我能不能找到。}
#{129}{Over_16}{We have no time, no options. I know it's a lot of responsibility
# for you, but we have no choice. We need the chip now.}
{129}{Over_16}{我们没时间了。我知道这对你来说压力很大，但我们别无选择。我们现在就需要那芯片。}
#{130}{Over_19a}{Please tell me you've found the chip.}
{130}{Over_19a}{求求你，告诉我，说你找到了那芯片。}
#{131}{}{No, but I've seen some amazing things!}
{131}{}{没有，但我看到了令人惊奇的东西！}
#{132}{}{Sorry, haven't been able to track it down yet.}
{132}{}{抱歉，还没能打探到它的下落。}
#{133}{}{Nope.}
{133}{}{没。}
#{134}{}{Nuh-uh.}
{134}{}{啊噢。}
#{135}{Over_20}{Well, keep looking. Time's growing short.}
{135}{Over_20}{好吧，继续找。时间不多了。}
#{136}{Over_21}{We don't have time for this! We need the chip. Time's running out. 【Sigh】}
{136}{Over_21}{我们没时间谈这个！我们急需那芯片。时间越来越少。【叹气】}
#{137}{Over_22}{Is there some problem, do you need more equipment?  Is there anything
# we can do to help?}
{137}{Over_22}{有什么难题么？要不要更多装备？有什么我们能帮忙的？}
#{138}{}{Nope, just going to take some time.  It's a big world out there.}
{138}{}{不用，只是要花些时间。那外面的世界可真大。}
#{139}{}{I could use some more stuff.}
{139}{}{我还需要些东西。}
#{140}{}{Yeah, you could get off your fannies and help.}
{140}{}{是啊，把你那成天不动的大屁股从椅子上挪下来大概还能帮上忙。}
#{141}{Over_23}{Do your best. Remember, we're all counting on you.}
{141}{Over_23}{你尽力而为吧。要记得，我们全都靠你了。}
#{142}{Over_24}{Here, take the last of our ammo and portable healing supplies.
# We're in trouble. Hurry!}
{142}{Over_24}{拿着，最后一些弹药和随身急救补给品。我们的情况已经很危急了。赶快！}
#{143}{Over_25}{Do what? With who? Anyone else would be less qualified and have less
# supplies. It'd be suicide.}
{143}{Over_25}{做什么？和谁？其他人没你有用，补给品也不够。那简直是自杀。}

#{144}{}{Your choice. I'll do my best, but I don't know if it'll be enough.}
{144}{}{随你。我会尽我所能，但我不知道这行不行。}

#{145}{}{I understand.}
{145}{}{我理解。}

#{146}{Over_26}{It has to be. If you fail, so does the Vault.}
{146}{Over_26}{必须这样。如果你失败了，避难所也就完了。}

#{147}{}{Got it.}
{147}{}{明白。}

#{148}{}{Whatever.}
{148}{}{随你怎么办。}

#{149}{Over_27}{Good, then get going!}
{149}{Over_27}{好，那就快去！}

#{150}{Over_28}{Have you found the chip?}
{150}{Over_28}{找到芯片没有？}

#{151}{}{Yes.}
{151}{}{是的。}

#{152}{}{Yes, but I think we should talk more about letting people leave the Vault.}
{152}{}{是的，但我想多谈谈关于把大家搬出避难所的事儿。}

#{153}{}{Nuh-huh!}
{153}{}{啊哈！}

#{154}{Over_29}{Great! Let me have it. We'll see if it works.}
{154}{Over_29}{好极了！把它给我。让我们看看它能不能用。}

#{155}{Over_30}{Please, the chip!}
{155}{Over_30}{求你，那芯片！}

#{156}{Over_31}{Okey-dokey. One moment, the chip is initializing. Here - here - here -
# There it goes . . . Self-test is green . . . re-boot is good . . .
# Hah! It's working! And it looks like we have a winner! Haha!
# 【The overseer sighs with relief.】 You -- you've saved us. You've done it!}
{156}{Over_31}{好地好地。等一下，芯片正在初始化。嗯－唔－嗯－动了动了……自我检验通过……重启正常……哈！它正常工作了！看起来我们成功了！哈哈！【所长松了口气。】你－－你救了我们。你做到了！}

#{157}{}{Ahh, it was nothing.}
{157}{}{啊，那不算什么。}

#{158}{}{You're welcome.}
{158}{}{不用谢。}

#{159}{Over_32}{Nothing? No, oh no! It was something.
# Don't downplay what you've done. You've saved a lot of lives.
# All right, now we need a report on what's out there.
# Please go to the library.}
{159}{Over_32}{不算什么？不，哦不！那可是意义重大。不要看低你所做的这一切。你救了很多人命。好，现在我们需要一份关于外面世界的详细报告。请到图书馆去。}

#{160}{}{Ok.}
{160}{}{好。}

#{161}{Over_33}{You saved the Vault. You should be proud. But now, we need your
# report. We'll get it from you in the library. Please go there now.}
{161}{Over_33}{你拯救了避难所。你该感到自豪。但现在，我们需要你的报告。跟我们到图书馆记录下来。请现在就去那里。}

#{162}{}{Ok.}
{162}{}{好。}

#{163}{Over_34}{Well, you've certainly earned that right. But let's take care of
# survival first. Give me the chip and we'll discuss this when you
# give your report.}
{163}{Over_34}{好，你现在当然有资格谈这个了。不过让我们先解决生存问题。把芯片给我，那个事在你汇报的时候我们再讨论。}

#{164}{}{Fair enough.}
{164}{}{好罢。}

#{165}{}{I don't know.}
{165}{}{我不知道。}

#{166}{Over_37}{Oh, that's great! Can I have the chip, please?}
{166}{Over_37}{哦，那太好了！请给我那个芯片好吗？}

#{167}{Over_38}{No, not that. I want the com-pu-ter chip.}
{167}{Over_38}{不，不是那个。我要那电－脑－芯－片。}

#{168}{Over_38a}{No. The chip.}
{168}{Over_38a}{不。芯片。}

#{169}{Over_39}{Just-give-me-the-chip!}
{169}{Over_39}{就－给－我－芯－片！}

#{170}{Over_40}{Thank you. Now, go to the library and rest for a while, ok?}
{170}{Over_40}{多谢你。现在，到图书馆去休息一会儿，好吗？}

#{171}{}{Nuh-huh, uh-nuh?}
{171}{}{啊哈，噢？}

#{172}{}{Uh, nuh? Nuh-uh-uh-nuh.}
{172}{}{噢，呵？啊嗬嗬呵。}

#{173}{Over_41}{Yes, you can touch things.}
{173}{Over_41}{是的，你可以碰东西。}

#{174}{Over_41a}{Oh, yes. You did good and I'm sure you have a lot to tell.}
{174}{Over_41a}{哦，是的。你做得很好而且我肯定你有很多要告诉我的。}

#{175}{Over_42}{I uh, I just wanted to let you know that the water supply has
# stabilized. Actually, we're rebuilding our reserves.
# You did great . . . I uh, I am a little concerned, however.}
{175}{Over_42}{我，呃，我就想让你知道饮水供给已经稳定了。实际上，我们正在重建备用库存。你干得好极了……我呃，但是我有一些小担心。}

#{176}{}{About what?}
{176}{}{关于什么？}

#{177}{}{Huh?}
{177}{}{嗯？}

#{178}{Over_43}{I' I don't like your reports. What was in the reports,
# that is. Heh. In fact, they scared the heck out of me. It's those mutants.
# I've done some calculations and, well, I've come to an unpleasant conclusion.}
{178}{Over_43}{我，我不喜欢你的报告。我是说，你报告里的那些东西。呵。说实话，他们快把我吓出魂了。是那些变种人。我做了些计算，然后，呃，得出些不太乐观的结论。}

#{179}{}{What's that?}
{179}{}{怎么说？}

#{180}{Over_44}{【Sigh】 The mutant population is far greater than could be expected
# by natural growth or mutations. This leads me to believe in -- I
# don't really understand it. But it looks like someone's
# generating new mutants. And at a startling rate.}
{180}{Over_44}{【叹气】变种人的数量远超过我们按照自然增长和突变率的预期。这使我相信——我不能理解。但目前看起来是有人在制造新的变种人，而且其速度令人吃惊。王八肏的……}

#{181}{}{Say again? Without the confusion?}
{181}{}{你再清楚地说一遍？}

#{182}{}{Must be a lab somewhere then.}
{182}{}{肯定是某处有个实验室。}

#{183}{Over_45}{Someone's making mutants!}
{183}{Over_45}{有人在造变种人！}

#{184}{}{What do I need to do?}
{184}{}{我要做些什么？}

#{185}{Over_46}{Exactly! And as you've probably guessed, none of these mutations could
# have occurred naturally, even with the radiation from the war.}
{185}{Over_46}{一点没错！就如你大概已经猜到了，这些突变不可能自然出现，就算是受到大战时的辐射。}

#{186}{}{What do you want me to do about it?}
{186}{}{你要我做些什么？}

#{187}{Over_47}{As long as someone is creating hostile mutants at this rate, the
# Vault's safety is at stake! Find and destroy this lab as soon as you can.}
{187}{Over_47}{只要有人继续以这种速度制造敌对的变种人，避难所的安全就岌岌可危！以最快的速度找到那个实验室并把它轰成碎片。}

#{188}{}{Ok.}
{188}{}{好。}

#{189}{}{Once more into the breach, my friend.}
{189}{}{再次临危授命吧，我的朋友。}

#{190}{Over_48}{You have no idea how sorry I am to send you back out.}
{190}{Over_48}{你不明白我再次让你出去的时候，其实心里有多愧疚啊。}

#{191}{Over_49}{Oh, yeah. Hmm . . . I' I' I' It's like this.
# There is a bad place where the bad mutants come from.
# It is bad. Vault is good. Please, go destroy bad place.}
{191}{Over_49}{哦，是的。唔……是，是是这样的。有个尽出变种坏人的坏地方。它是坏的。避难所是好的。请去摧毁那坏的地方。}

#{192}{Over_50}{Has the mutant laboratory been discovered yet?  Even better, tell me
# it's been destroyed.}
{192}{Over_50}{有没有找到变种人？或者更好的事，告诉我它已经被消灭了。}

#{193}{}{No.}
{193}{}{不。}

#{194}{}{Not yet, but I've got some good leads.}
{194}{}{还没有，但我有些好的线索。}

#{195}{}{Nope, I'm a little lost.}
{195}{}{不，我有点没了头绪。}

#{196}{}{Nungh.}
{196}{}{没有。}

#{197}{Over_51}{Well, keep searching.}
{197}{Over_51}{好吧，继续找。}

#{198}{Over_52}{Good. But hurry, the more time they have to produce them, the harder
# they'll be to stop.}
{198}{Over_52}{好。但要快点，越给他们时间制造更多的变种人，他们就越难打败。}

#{199}{Over_53}{Well, based on the information you provided about
# population density, I think you should concentrate your search to the west.}
{199}{Over_53}{嗯，根据你提供的关于人口密度的情报，我想你应该集中精力去西边搜索。}

#{200}{Over_54}{What news do you have of the mutants?}
{200}{Over_54}{有什么关于变种人的消息？}

#{201}{}{I wasted the head SOB.}
{201}{}{我把那狗娘养的杂种老大干掉了。}

#{202}{}{I've killed the Master, the mutant leader.}
{202}{}{我杀了主教，变种人的头目。}

#{203}{}{Nuh, ungh. Uh-nuh, nuh.}
{203}{}{呐，嗯。呃－呐，唔。}

#{204}{Over_55}{Excellent! What about the laboratory? Did you destroy that, too?}
{204}{Over_55}{好极了！那实验室怎么样？你也把它摧毁了吗？}

#{205}{}{No.}
{205}{}{不。}

#{206}{}{Yep, sure did.  Killed all the mutants and blew up their production vats. The vault has nothing to fear now.}
{206}{}{当然。杀了所有的变种人也炸了他们的病毒槽生产线。现在没什么能让避难所害怕的了。}

#{207}{Over_58}{You should be proud of yourself for all you've accomplished. We
# depended on you and you came through. Now let's talk about your future . . .}
{207}{Over_58}{你应该为你所完成的感到自豪。我们都依赖你,而你做到了。现在让我们谈谈你的未来……}

#{208}{Over_59}{Are you sure?  Missing something would be deadly to the Vault. I
# think you should go back and check it out.  Try to the west, there
# seems to be a large concentration of mutants there.}
{208}{Over_59}{你确定？漏掉任何东西对避难所都会是致命的。我认为你应该回去再检查一遍。试试西边，那儿看起来像是有一大堆变种人。}

#{209}{Over_60}{Go back out and find it.  It needs to be destroyed for the vault
# to be safe. Try to the west, most of the mutants seem to be there.}
{209}{Over_60}{回去找出它。为了避难所的安全它必须被摧毁。到西边去看看，看上去大部分变种人都在那儿。}

#{210}{Over_61}{What's that? You've killed the mutant leader?}
{210}{Over_61}{什么？你杀了变种人的头目？}

#{211}{}{Uh-huh, nuh, huh. Nuh-nuh.}
{211}{}{唔呼，呐，呼呼。呐呐。}

#{212}{Over_61aS}{There are still more mutants appearing? You need to destroy their
# vats? Great job! Go back out there and take care of it.}
{212}{Over_61aS}{仍有更多变种人出现？你必须毁掉他们的病毒槽？好好干！回到外头去解决它。}

#{213}{Over_62}{What news of the mutants?}
{213}{Over_62}{变种人有什么消息？}

#{214}{}{I blew them up.}
{214}{}{我把他们炸上了天。}

#{215}{}{The mutant vats have been destroyed.}
{215}{}{变种人病毒槽已经被摧毁了。}

#{216}{}{Nuhh!}
{216}{}{嗬嗬！}

#{217}{Over_63}{All of them?}
{217}{Over_63}{他们全部？}

#{218}{}{Well, all of them at the vats.}
{218}{}{嗯，病毒槽里的全部杂碎都死菜了。}

#{219}{}{Uh, nuh-nuh.}
{219}{}{呃，卜卜。}

#{220}{Over_64}{What about the mutant leader? What about this so-called Master?}
{220}{Over_64}{那他们的头目呢？那个所谓的主教？}

#{221}{}{Far as I know, he's still alive.}
{221}{}{据我所知，他还活着。}

#{222}{}{Uh-nuh-nuh.}
{222}{}{呃，卜卜。}

#{223}{Over_66}{He must be stopped. If not, he could rebuild his empire of mutants
# and would certainly strike back at us. The vault will not be safe
# until the Master is dead.}
{223}{Over_66}{必须阻止他。否则，他会重建他的变种人帝国，而且肯定会反击我们。在主教死之前避难所不可能安全。}

#{224}{Over_68}{Is the mutant leader . . . taken care of?}
{224}{Over_68}{变种人的头目……处置了没有？}

#{225}{}{No.}
{225}{}{没有。}

#{226}{}{He will be . . . soon.}
{226}{}{他会被……很快．}

#{227}{}{Nuh.}
{227}{}{没。}

#{228}{Over_69}{I know this has been hard on you. But this Master's the type who'll
# rebuild his mutant army. Then he'll come for us. Please, go
# out and finish the job.}
{228}{Over_69}{我知道这一直对你很难。但主教是那种会东山再起的家伙。然后就会冲着我们而来。请回去完成任务。}

#{229}{Over_70}{Well, Th' Tha' That's great. That's very good. You sound
# like you're in control out there. Please, finish this up soon so that you
# and I can . . . When you're out there, remember, the people
# of the Vault know you've saved them.}
{229}{Over_70}{呃，那，那那太好了。非常好。听起来你已经控制了外面的形势。请快回去把这事了结了那么你我就能……你在外头的时候要记得，避难所里的人都明白你救了他们。}

#{230}{Over_71}{We can't have this. Not now. Not with everything else going on. The
# rules of the Vault are there for our protection and the survival of
# our species.}
{230}{Over_71}{我们不可以。现在不行。特别是正发生这么多事的这个时候。避难所的原则是用来保护我们自己和人类的幸存。}

#{231}{Over_72}{What's wrong with you?! You turned against us?!
# I can not allow that.}
{231}{Over_72}{你在搞什么？！你背叛了我们？！我不能允许那样。}

#{232}{Over_73}{The water caravans from this Hub place have started to arrive. I've
# been running the figures and I've got some disturbing news.}
{232}{Over_73}{从哈勃城来的纯水商队已经开始陆续抵达了。我统计了一下数据，看来情况并不乐观。}

#{233}{}{What's that?}
{233}{}{是什么？}

#{234}{}{Huh?}
{234}{}{嗯？}

#{235}{Over_74}{Oh, never mind. Just try and find the water chip. Get the chip.
# We still need it.}
{235}{Over_74}{哦，别介意。继续试着找净水芯片。搞到芯片。我们仍需要它。}

#{236}{Over_75}{The caravan water will maintain our current supply, but not increase
# it substantially. And these Hub merchants are charging us an arm
# and leg. This helps and we're thankful for that, but it's not a solution.}
{236}{Over_75}{纯水商队的水能维持我们的日常供给，却不能可观补充我们的库存。而且这些哈勃城商人要的简直是天价。这的确帮了我们的忙，我很感激，但并不是一个根本的解决办法。}

#{237}{}{Ok.}
{237}{}{好。}

#{238}{}{There's something else, isn't there?}
{238}{}{还有些别的，不是吗？}

#{239}{Over_76}{Keep looking for a replacement chip. It's the only way we can
# maintain our independence and the security that comes with our seclusion.}
{239}{Over_76}{继续寻找那替换芯片。这是维持我们独立，以及由隔离所带来安全的唯一方法。}

#{240}{Over_77}{We're taking a terrible risk by showing these people the way to our
# vault. I understand your choice, and it may be what saves us. But
# I'm worried. Can we trust these people?}
{240}{Over_77}{这些外人知道了找到避难所的路，这是很危险的事情。我理解你的选择，那也许是救了我们。但是我很担心，这些人值得信赖吗？}

#{241}{}{I trust them.}
{241}{}{我信任他们。}

#{242}{}{I understand.}
{242}{}{我明白。}

#{243}{Over_78}{I'm sure you do, but we need that replacement chip for our long-term
# survival and economic stability.  We don't produce as many goods as
# we need to pay for this water, and soon we won't be able to pay.
# Find the chip.}
{243}{Over_78}{我知道你信任他们，但为了长远的生存和经济稳定，我们需要那替换芯片。我们不能生产足够的货物来换取这些水，很快我们就付不起了。找到那芯片。}

#{244}{Over_79}{I'm sure you do. You must also understand our need for that
# replacement chip. Please keep looking.}
{244}{Over_79}{我知道你信任他们。你也一定知道我们急需那替换芯片。请继续找。}

#{245}{Over_80}{Please keep looking for the water chip. These water caravans are
# going to cause us problems in the long run.}
{245}{Over_80}{请继续寻找净水芯片。那些纯水商队迟早会给我们带来麻烦。}

#{246}{Over_81}{You've done it! That's . . . wonderful. Amazing! I'm so
# proud of what you've accomplished, what you've endured. There's no way
# the people of the Vault can ever thank you enough for what you've done.
# You've saved all our lives. Who knows, maybe even saved the human race.
# 【The Overseer sighs.】 That makes the rest of this even harder.
# Everyone will want to talk to you. Every youngster will look up to you.
# And want to emulate you. And then what? They'll want to leave. What
# happens to the Vault if we lose the best of a generation? What if we
# are the only safe place in the world? You just gave us back all these
# lives . . . I can't take the chance of losing them. I've made a lot of
# tough decisions since I took this position. But none of them harder
# than this one. You saved us, but you'll kill us. I'm sorry. You're
# a hero . . . and you have to leave.}
{246}{Over_81}{你做到了！那真是……好极了。令人惊讶！我为你所完成的、所忍受的感到无比骄傲。避难所里的人们对你所做的一切永远都感激不尽。你救了我们所有人的命。天晓得，说不定还拯救了全人类。【所长叹了口气。】但是这确让我对你很难办。每个人都想跟你谈话。每个年轻人都把你视为偶像。然后仿效你。然后怎样？他们就想着要出走。如果我们失去了最有希望朝气的一代，避难所会变成什么样？万一我们这儿是世上唯一安全的地方那怎么办？你刚刚拯救了这些人……我不能冒险再失去他们。自从我坐到这个位置上以来我作了很多痛苦艰难的决定。但它们比起这个来一点也不算什么。你救了我们，但你也会毁了我们。我很抱歉。你是个英雄……但是你必须离开。}

#{247}{Over_100}{I don't know anything about that.}
{247}{Over_100}{我对那个一无所知。}

#{248}{Over_200}{It is a critical part that allows us to purify the water. Without
# it, we'll run out of drinking water.}
{248}{Over_200}{那是能让我们净化水的关键部件。没了它，我们就会没了水喝。}

#{249}{Over_201}{This is our home. We'd all be dead without it. If we care for it
# properly, it should last us for a long time.}
{249}{Over_201}{这是我们的家。没了它我们活不了。如果我们小心照料，它将是我们的长久之计。}

#{250}{Over_202}{It was terrible. I hope we learned our lesson and we never do it
# again.}
{250}{Over_202}{极其可怕。我希望我们已从中汲取教训将来永不再犯。}

#{251}{Over_203}{How would I know? I can barely keep up with what goes on in here!
# I suspect you're going to find out.}
{251}{Over_203}{我怎么知道？内部事务已经够我忙的了！我看你得自己去搞明白。}

#{252}{}{You gain 7,500 experience points for returning the water chip and saving
# the Vault. Congratulations!}
{252}{}{你成功找回了净水芯片并拯救了避难所，获得7500点经验值。恭喜！}

#{253}{Over_0ab}{Here's a picture to help you identify it.}
{253}{Over_0ab}{这里有张图片帮你识别它。}

#{254}{Over_1a}{You have one month to retrieve the chip before the vault runs
# out of water.}
{254}{Over_1a}{在避难所的水用完之前你还有一个月的时间取得芯片。}

#{255}{Over_1b}{You have two months to retrieve the chip before the vault runs
# out of water.}
{255}{Over_1b}{在避难所的水用完之前你还有两个月的时间取得芯片。}

#{256}{Over_1c}{You have four months to retrieve the chip before the vault runs
# out of water.}
{256}{Over_1c}{在避难所的水用完之前你还有四个月的时间取得芯片。}

#{257}{Over_1d}{You have five months to retrieve the chip before the vault runs
# out of water.}
{257}{Over_1d}{在避难所的水用完之前你还有五个月的时间取得芯片。}

#{258}{Over_1e}{You have six months to retrieve the chip before the vault runs
# out of water.}
{258}{Over_1e}{在避难所的水用完之前你还有六个月的时间取得芯片。}

#{259}{}{Yeah, well I guess you'll have to find someone else to do your dirty work.}
{259}{}{是啊，嗯我猜你得另找别人替你做那肮脏的活儿。}

#{260}{}{I understand. I'll work harder to find the chip.}
{260}{}{我明白。我会更用心的寻找芯片。}

#{261}{Over_81a}{You've done it! That's . . . wonderful. Amazing!
# I'm so proud of what you've accomplished, what you've endured.}
{261}{Over_81a}{你做到了！那真是……好极了。令人惊讶！我为你的丰功伟绩和坚韧不拔感到自豪。}

#{262}{Over_81b}{There's no way the people of the Vault can ever thank you
# enough for what you've done. You've saved all our lives. Who knows, maybe
# even saved the human race. 【The Overseer sighs.】
# That makes the rest of this even harder.}
{262}{Over_81b}{避难所里的人们对你所做的一切永远都感激不尽。你救了我们所有人的命。天晓得，说不定还拯救了全人类。【所长叹了口气。】这却使得我对你更加难办了。}

#{263}{Over_81c}{Everyone will want to talk to you.
# Every youngster will look up to you, and want to emulate you. And then what?}
{263}{Over_81c}{每个人都想跟你谈话。每个年轻人都把你视为偶像。然后仿效你。然后怎样？}

#{264}{Over_81d}{They'll want to leave. What happens to the Vault if we
# lose the best of a generation? What if we are the only safe place in the world?
# You just gave us back all these lives . . . I can't take the chance of losing them.}
{264}{Over_81d}{他们就想着要出去。如果我们失去了最有希望朝气的一代避难所会变成什么样？万一我们这儿是世上唯一安全的地方那又怎么办？你刚刚拯救了这些人……我不能冒险再失去他们。}

#{265}{Over_81e}{I've made a lot of tough decisions since I took this position.
# But none of them harder than this one. You saved us, but you'll kill us.
# I'm sorry. You're a hero . . . and you have to leave.}
{265}{Over_81e}{自从我坐到这个位置上以来我作了很多痛苦艰难的决定。但它们比起这个来一点也不算什么。你救了我们，但你也会毁了我们。我很抱歉。你是个英雄……但是你必须离开。}

# Overseer Tell-Me-Abouts generic responses
#{980}{Over_100}{I don't know anything about that.}
{980}{Over_100}{我对那个一无所知。}

#
# Overseer Tell-Me-Abouts
#

{1099}{}{?}
{1199}{}{我可以告诉你：Water-水、Vault-避难所、War-大战、Outside-外面、Chip-芯片、Library-图书馆、Healing-治疗、Medic-医生、Vault13-十三号避难所、Vault-13-十三号避难所、Overseer-所长、Waterchip-净水芯片。}

{1000}{}{Water}
{1001}{}{Vault}
{1002}{}{War}
{1003}{}{Outside}
{1004}{}{Chip}
{1005}{}{Library}
{1006}{}{Healing}
{1007}{}{Medic}
{1008}{}{Vault13}
{1009}{}{Vault-13}
{1010}{}{Overseer}
{1011}{}{Waterchip}

#{1100}{Over_200}{It is a critical part that allows us to purify the water. Without
# it, we'll run out of drinking water.}
{1100}{Over_200}{那是能让我们净化水的关键部件。没了它，我们就会没了水喝。}

#{1101}{Over_201}{This is our home. We'd all be dead without it. If we care for it
# properly, it should last us for a long time.}
{1101}{Over_201}{这是我们的家。没了它我们活不了。如果我们小心照料，它将是我们的长久之计。}

#{1102}{Over_202}{It was terrible. I hope we learned our lesson and we never do it
# again.}
{1102}{Over_202}{极其可怕。我希望我们已从中汲取教训将来永不再犯。}

#{1103}{Over_203}{How would I know? I can barely keep up with what goes on in here!
# I suspect you're going to find out.}
{1103}{Over_203}{我怎么知道？内部事务已经够我忙的了！我看你得自己去搞明白。}

#{1104}{Over_200}{It is a critical part that allows us to purify the water. Without
# it, we'll run out of drinking water.}
{1104}{Over_200}{那是能让我们净化水的关键部件。没了它，我们就会没了水喝。}

#{1105}{Over_21q}{We don't have time for this!}
{1105}{Over_21q}{我们没时间谈这个！}

#{1106}{Over_21q}{We don't have time for this!}
{1106}{Over_21q}{我们没时间谈这个！}

#{1107}{Over_21q}{We don't have time for this!}
{1107}{Over_21q}{我们没时间谈这个！}

#{1108}{Over_201}{This is our home. We'd all be dead without it. If we care for it
# properly, it should last us for a long time.}
{1108}{Over_201}{这是我们的家。没了它我们活不了。如果我们小心照料，它将是我们的长久之计。}

#{1109}{Over_201}{This is our home. We'd all be dead without it. If we care for it
# properly, it should last us for a long time.}
{1109}{Over_201}{这是我们的家。没了它我们活不了。如果我们小心照料，它将是我们的长久之计。}

#{1110}{Over_21q}{We don't have time for this!}
{1110}{Over_21q}{我们没时间谈这个！}

#{1111}{Over_200}{It is a critical part that allows us to purify the water. Without
# it, we'll run out of drinking water.}
{1111}{Over_200}{那是能让我们净化水的关键部件。没了它，我们就会没了水喝。}
