{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{Get out of here!}
{100}{}{离开这里！}

#{101}{}{I've heard bad things about you, are they true?}
{101}{}{我听说你干过很多坏事，真的吗？}

#{102}{}{Hi.}
{102}{}{嘿。}

#{103}{}{This is my place, wanna hang out for a while?}
{103}{}{这是我的地方，要离开一会儿？}

#{104}{}{Hmm, you look juicy . . .}
{104}{}{嗯，你看上去很诱人……}

#{105}{}{I hope you're not going to kick me out of here.}
{105}{}{我希望你不要把我赶出去。}

#{106}{}{No.}
{106}{}{不。}

#{107}{}{That's a strange way to start a conversation.}
{107}{}{那是一个奇怪的交谈方式。}

#{108}{}{Hnnn.}
{108}{}{噢噢噢。}

#{109}{}{Oh, well, if you want to stay a while, go right ahead. I think we are
# safe here.}
{109}{}{哦，好吧，如果你要在这待一段时间，最好去前边。我想我们这里安全些。}

#{110}{}{Well, you gotta be careful these days. I hope you're having a better life
# than I am.}
{110}{}{很好，今天你得小心点。我希望你活的命比我长。}

#{111}{}{Well, it's true. After what happened to my friends, I gotta protect my
# turf. I just hope you're not gonna kill me.}
{111}{}{好，这是真的。我的朋友到底发生了什么事情，我必须保护我的家，我只是希望你不要杀我。}

#{112}{}{No, I won't hurt you. Much.}
{112}{}{不，我不想再更多的伤害你了。}

#{113}{}{Why do you say that?}
{113}{}{你为什么会那么说？}

#{114}{}{Gack!}
{114}{}{唧唧！}

#{115}{}{No reason. Really.}
{115}{}{没有原因。真的。}

# Translation note:
# Line 116 has one of lines 117-120 appended to it, depending upon circumstances.
#{116}{}{Those 'helpful' healing guys wanted my friend's place, so they took it.
# I don't know what happened to my friends.}
{116}{}{那些有助于健康的家伙想要我朋友的地盘，结果他们占领了那里，我不知道我的朋友现在怎样。}

#{117}{}{ And Killian is too busy to help me.}
{117}{}{基利安太忙，没法帮我。}

#{118}{}{ Killian is too busy cleaning up Gizmo's mess to help.}
{118}{}{基利安忙着帮助我们清理吉斯莫惹的麻烦。}

#{119}{}{ Gizmo laughed at me when I asked for his help.}
{119}{}{当我求基利安帮助我时他来嘲笑我。}

#{120}{}{ There's nobody around to help me.}
{120}{}{周围没人来帮我。}

#{121}{}{Are you safe?}
{121}{}{你还好吧？}

#{122}{}{That's a shame.}
{122}{}{真是个耻辱。}

#{123}{}{I hope so, I really hope so.}
{123}{}{我希望是这样，我真的希望是这样。}

#{124}{}{Please leave me alone!}
{124}{}{求你离我远点！}