{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{radio}
{100}{}{无线电}
#{101}{}{【There is a squeal of static, then you hear a deep voice over the
# radio.】 Command to patrol, command to patrol. What is your status?
# Over.}
{101}{}{【一声刺耳的噪声，你听到一个低沉的声音从无线电里传来。】指挥官呼叫巡逻兵，指挥部呼叫巡逻兵。报告你的情况？完毕。}

#{102}{}{Eek!}
{102}{}{呀！}

#{103}{}{Uh, nothing is wrong here. We're fine, uh, how are you?}
{103}{}{嗯，这里没有异常情况。我们很好，嗯，你怎么样？}

#{104}{}{Command, we are under attack by a large group of armed
# humans. Request assistance. Over.}
{104}{}{长官，我们遭到了一大群人类的攻击。请求支援。完毕。}

#{105}{}{Help! Unknown attackers! Heavy damage! Coordinates follow: 10 . . . Argh!}
{105}{}{救命！有人袭击！我们受了重伤！坐标：10……啊！}

#{106}{}{Understood, patrol. We are sending assistance now. Over.}
{106}{}{明白，巡逻兵。我们马上赶去支援。完毕。}

#{107}{}{Who is this? What is your purpose?}
{107}{}{你是谁？你想干吗？}

#{108}{}{My purpose is to shut the hell up.}
{108}{}{我要关闭这里的地狱之门。}

#{109}{}{I'm, uh, oh, never mind. I'm just going to kill you all anyways.}
{109}{}{我是，嗯，噢，这不重要。我仅仅是个想来杀死你的人。}

#{110}{}{This is, hmm, Fred. My purpose is patrol. I guess I'm a, uh,
# little dazed after that fall.}
{110}{}{我是，呃，弗瑞德。我的任务是巡逻。我猜我是一个，嗯，有点头晕。}

#{111}{}{Understood, patrol. What are your coordinates?}
{111}{}{明白，巡逻兵，报告你的坐标？}

#{112}{}{224 by 104.}
{112}{}{横坐标224纵坐标104。}

#{113}{}{Four miles, south-southwest.}
{113}{}{四英里，南部西南方向。}

#{114}{}{Gamma sector, at Omicron-Delta-Beta.}
{114}{}{伽马地区，在欧米嘎区至德尔塔区至贝塔区。}

#{115}{}{Understood, patrol. Command, out.}
{115}{}{明白，巡逻兵。指挥部，通话结束。}

#{116}{}{Understood, patrol. We are sending reinforcements.}
{116}{}{明白，巡逻兵。我们马上支援。}

#{117}{}{Ah, that explains it. We are sending help now.}
{117}{}{啊，说清楚点，我们马上去增援！}

#{118}{}{Roger, patrol. We're sending help now! Hold on!}
{118}{}{收到，巡逻兵。我们马上支援你！撑住！}

#{119}{}{There is only static on the radio.}
{119}{}{这只有无线电的噪音。}

#{120}{}{You hear some chatter on the radio. You listen for a
# while, and discover nothing of importance.}
{120}{}{你听到无线电传出了一些嘈杂声。你听了一会，但是没有听到任何关键的事情。}

#{121}{}{The radio has a red blinking light. You hear a high
# pitched squealing over the radio speaker.}
{121}{}{无线电的红灯闪了一下。你听到了一声刺耳的鸣叫。}

#{122}{}{It sounds like encrypted audio.}
{122}{}{它听上去像是音频密码。}

#{123}{}{You send the command code to toggle the force field
# settings.}
{123}{}{你发出命令代码改变力场设定。}

#{124}{}{There is only quiet static on the radio channel.}
{124}{}{这里只有无线电频段发出的声音。}

#{125}{}{The radio is not functioning.}
{125}{}{无线电没有在工作。}

#{126}{}{This radio is in perfect condition. The source
# of the problem must be external.}
{126}{}{这个无线电很正常。问题在另一台无线电上。}

#{127}{}{There is nothing but the squeal of encrypted data
# over the radio.}
{127}{}{无线电只发出刺耳的像数据密码的声音。}

#{128}{}{【Squeal-snick-pop】 Command here, go ahead patrol.}
{128}{}{【噪音－咝咝－嗤嗤】这里是指挥部，到前边巡逻。}

#{129}{}{Ack!}
{129}{}{啊！}

#{130}{}{Uh, sorry, Command. I hit the talk button by mistake.}
{130}{}{嗯，对不起，指挥部。我按错按钮了。}

#{131}{}{Intruders in the base! Sound the alert!}
{131}{}{有入侵者进入基地！启动警报！}

#{132}{}{Roger Patrol, Command out.}
{132}{}{收到，巡逻兵，指挥部通话完毕。}

#{133}{}{【You dial the frequency of the radio to the security control
# channel】 【Click!】 Enter access number. 【Click!】}
{133}{}{【你把无线电拨到安全控制频段】【咔哒】输入密码【咔哒】}

#{134}{}{Hng!}
{134}{}{哼！}

#{135}{}{Uh, 69.}
{135}{}{呃，69。}

#{136}{}{5566534571}
{136}{}{5566534571}

#{137}{}{End access.}
{137}{}{结束访问。}

#{138}{}{Automatic security channel shutdown.}
{138}{}{自动化安全频段关闭。}

#{139}{}{You gain 1,500 experience points for tricking the mutant guards.}
{139}{}{你戏弄变种人卫队获得了1500点经验值。}

#{140}{}{You gain 2,000 experience points for sneaking into the depths of the
# military base without getting caught (yet) . . .}
{140}{}{你秘密潜入军事基地却没有被人逮到所以获得2000点经验值。}
