{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{The Raider is too frightened of Garl to speak to you any more.}
{100}{}{歹徒被伽尔吓坏了以至于再也不和你进一步交谈。}

#{101}{}{You see a tough desert Raider.}
{101}{}{你看到一个彪悍的沙漠歹徒。}

#{102}{}{It's the Death-Hand. He's returned!}
{102}{}{是死亡之手。他回来了！}

#{103}{}{Excuse me, Death-Hand. I'm sorry to disturb you.}
{103}{}{对不起，死亡之手，抱歉打扰你。}

#{104}{}{Have you come back to kill your son?}
{104}{}{你回来杀你的儿子？}

#{105}{}{Aiyeee! A ghost!}
{105}{}{啊啊啊！一个鬼！}

#{106}{}{The dead walk again! The Death-Hand has returned!}
{106}{}{死人再次光临！死亡之手回来了！}

#{107}{}{Well met.}
{107}{}{很高兴见到你。}

#{108}{}{Hi.}
{108}{}{嘿。}

#{109}{}{I'm waiting for Garl to crush Shady Sands. I want some loot.}
{109}{}{我等伽尔把沙荫镇打垮后，再去洗劫一番。}

#{110}{}{Welcome friend.}
{110}{}{欢迎你朋友。}

#{111}{}{I'm glad that you could return for a visit.}
{111}{}{我很高兴你能回来看看。}

#{112}{}{Unless you want trouble, you'd better put that away.}
{112}{}{除非你想惹麻烦，你最好收起武器。}

#{113}{}{Do you want to party?}
{113}{}{你要参加宴会吗？}

#{114}{}{Oh, a tough one, huh?}
{114}{}{哦，一个恶棍，嗯？}

#{115}{}{Garl Death-Hand loves his warriors. Put that thing away and go talk to him.}
{115}{}{“死亡之手”伽尔喜欢他的战士。收起你的武器和去和他谈谈。}

#{116}{}{So, you think you're tough, huh? Mess with me and we'll both find out.}
{116}{}{你觉得你很壮，嗯？我们比试比试看谁更厉害。}

#{117}{}{I don't like your looks.}
{117}{}{我不喜欢你盯着我。}

#{118}{}{Go away!}
{118}{}{滚！}

#{119}{}{What do you want?}
{119}{}{你要干吗？}

#{120}{}{I'm looking for a woman named Tandi. Seen her?}
{120}{}{我正在找一个叫坦蒂的女人。你看见她了吗？}

#{121}{}{Nothing. Just looking around.}
{121}{}{没事。就是来看看。}

#{122}{}{Huh??}
{122}{}{嗯？？}

#{123}{}{Oh. You must be looking for a job. Go and see Garl in the big room and leave us alone.}
{123}{}{哦。你必须找个活干干。到大房子里找伽尔去吧。}

#{124}{}{Then do it elsewhere.}
{124}{}{然后在别的地方也这样干。}

#{125}{}{Nah. I ain't seen her. Why are you asking?}
{125}{}{没。我没有看见过她。你为什么这么问？}

#{126}{}{Nothing. Just looking for a friend of mine.}
{126}{}{没事。我仅仅是来找我的一个朋友。}

#{127}{}{There is a bounty on her head. If I can kill her, I can get some good cash.}
{127}{}{她的头可值大价钱。如果我杀了她，我就能拿到很多的钱。}

#{128}{}{You're lying. Where is she?}
{128}{}{你在撒谎。她在哪？}

#{129}{}{Ah, ok.}
{129}{}{啊，好。}

#{130}{}{Really? What does she look like?}
{130}{}{真的吗？她长什么样子？}

#{131}{}{About 6 feet tall. Blonde. She's from Shady Sands.}
{131}{}{大概六英尺高。白皮肤。她来自沙荫镇。}

#{132}{}{Yeah, she's here. She's in the big house. You know, if we tell Garl,
# then he would want a piece of the bounty. You might want to think about that.}
{132}{}{是的，她在这里。她在一个大房子里。你知道的，如果我们告诉伽尔，他会给我点甜头，你或许应该考虑考虑这问题。}

#{133}{}{You don't sound like you mean it. I think that you are up to something.
# And if you are telling the truth, then I'll bag the reward for myself.}
{133}{}{听上去不是真的。讲讲那些事情。如果你跟我说实话，我就给你一大笔奖励。}

#{134}{}{I . . . I can't say any more, or Garl will kill me.}
{134}{}{我……我不能说太多，不然伽尔会杀了我的。}

#{135}{}{Bite me!}
{135}{}{干我呀！}

#{136}{}{I don't like your looks. You'd better get away from me.}
{136}{}{我不喜欢你这样盯着我。你最好离我远点。}

#{137}{}{What? Go away!}
{137}{}{什么？滚！}