
#{100}{}{This looks like a robot control terminal.}
{100}{}{这东西看上去像个机器人控制终端。}

#{101}{}{There is no response.}
{101}{}{它没有反应。}

#{102}{}{Reprogramming complete. Initializing voice communication subsystems.
# Initializing personality subsystem. 【Click!】 How may this terminal
# be of service?}
{102}{}{程序调整完毕。初始化音频通讯子系统。初始化仿生子系统。【叮叮】你需要什么帮助？}

#{103}{}{Hng.}
{103}{}{呼。}

#{104}{}{Who or what are you?}
{104}{}{你是谁？或者是什么东西？}

#{105}{}{What is your function?}
{105}{}{你有什么功能？}

#{106}{}{Display list of programs.}
{106}{}{显示程序列表。}

#{107}{}{Input error. Command not in set. Please restate.}
{107}{}{输入错误。没有这项指令。请重新输入。}

#{108}{}{Hng.}
{108}{}{喔。}

#{109}{}{La-la.}
{109}{}{啦－啦。}

#{110}{}{Brai!}
{110}{}{卟啦！}

#{111}{}{Niggle!}
{111}{}{小气！}

#{112}{}{End communication subsystem. End process.}
{112}{}{结束信息子系统。处理结束。}

#{113}{}{This terminal is an Artificial Intelligence. This terminal
# is part of a WLAN matrix network to optimize remote unit
# operations.}
{113}{}{这个终端机是智能化的。这个终端机是WLAN矩阵网络的一部分，可以优化控制细微的单元。}

#{114}{}{Thanks. Uh, end input.}
{114}{}{谢谢。呃，结束操作。}

#{115}{}{What are the remote units that you control?}
{115}{}{你能控制的细微单元是什么？}

#{116}{}{What programs are running?}
{116}{}{正在运行什么程序？}

#{117}{}{This terminal is responsible for the operation of all General
# Atomics International industrial robots in this facility.}
{117}{}{这个终端内嵌有国际原子能机构的控制技术。}

#{118}{}{Please be more specific.}
{118}{}{告诉我更多的细节。}

#{119}{}{What programs are running?}
{119}{}{正在运行什么程序？}

#{120}{}{The style of industrial robots are commonly referred to as
# 'Robobrain'. 【Click!】 General Atomics International has the
# finest industrial robots in the world. Buy two or more GAI
# robots and save! Special deal on 'Mr. Handy' models! 【Click!】
# Advertising applet terminated.}
{120}{}{通用工业机器人一般被称为“智能机器人”。【叮叮！】本产品被国际原子能机构评为世界上最好的机器人。购买两台以上价格优惠！还附赠一个“省钱先生”的玩具模型！【叮叮！】广告程序结束。}

#{121}{}{What programs are running?}
{121}{}{正在运行什么程序？}

#{122}{}{Current applications are: Facility Maintenance v2.1, Movement
# v4.8b, Repair v0.8a, Pest Control v1.4, Hearts v1.0 and Sensors '76.}
{122}{}{当前软件是：设备维护v2．1，运转系统v4．8b，修理系统v0．8，病毒控制系统v1．4，红心大战v1．0，传感器＇76。}

#{123}{}{Terminate Movement.}
{123}{}{终止运转。}

#{124}{}{Terminate Sensors.}
{124}{}{终止传感器。}

#{125}{}{Terminate Pest Control.}
{125}{}{终止病毒控制。}

#{126}{}{Terminate Hearts.}
{126}{}{终止红心大战。}

#{127}{}{Thanks. End input.}
{127}{}{谢谢。结束。}

#{128}{}{Attempting to terminate. 【Click!】 System error. Failure to
# terminate application. Delete rights not available.}
{128}{}{尝试终止。【叮叮！】系统错误。终止请求失败。删除无效请求。}

#{129}{}{Hmm, adjust parameters on Movement.}
{129}{}{呵呵，调整运转系统。}

#{130}{}{Adjust parameters on Sensors.}
{130}{}{调整传感器参数。}

#{131}{}{Modify Pest Control.}
{131}{}{修改病毒活体控制。}

#{132}{}{Play Hearts.}
{132}{}{启动红心大战。}

#{133}{}{Thanks. End input.}
{133}{}{谢谢。结束操作。}

#{134}{}{Current application: Movement v4.8b. Current setting:
# 【maximum/half rate/minimum】. Change to: maximum, half rate,
# or minimum.}
{134}{}{当前请求：运转系统v4·8b。当前设置：【最大的、一半比率的、最小的】。可变成：最大的、一半比率的、最小的。}

#{135}{}{Maximum movement.}
{135}{}{最大运转。}

#{136}{}{Half rate movement.}
{136}{}{一半比率运转。}

#{137}{}{Minimum movement.}
{137}{}{最小运转。}

#{138}{}{Current application: Sensors '76. Current setting:
# 【full/minumum】. Change to: full, or minimum.}
{138}{}{当前软件：感应器＇76。当前设置：【完整／最小】。可变为；完整或最小。}

#{139}{}{Full sensors.}
{139}{}{完整传感器。}

#{140}{}{Minimal sensors.}
{140}{}{最小传感器。}

#{141}{}{Current application: Pest Control v1.4. Current setting:
# 【Click!】 unauthorized. Change to: 【Click!】 all, none, small
# living, large living, or unauthorized.}
{141}{}{当前请求：病毒活体控制系统v1·4。当前设置【叮叮！】未经认可活体。转换为：【叮叮！】所有的、空的、少量的活体、大量的活体、未认可的活体。}

#{142}{}{All pests.}
{142}{}{全部病毒活体。}

#{143}{}{No pests.}
{143}{}{没有病毒活体。}

#{144}{}{Small living pests.}
{144}{}{少量病毒活体。}

#{145}{}{Large living pests.}
{145}{}{大量病毒活体。}

#{146}{}{Unauthorized pests.}
{146}{}{未经认可的病毒活体。}

#{147}{}{Application Hearts running. User Wins. 【Click!】 Thank you for the game.}
{147}{}{红心大战正在运行。玩家胜利。【叮叮！】感谢您玩本游戏。}

#{148}{}{Application Hearts running. This terminal wins. 【Click!】 Thank you
# for the game.}
{148}{}{红心大战正在运行。系统胜利。【叮叮！】感谢您玩本游戏。}

#{149}{}{Program parameter changed. Current applications are: Facility
# Maintenance v2.1, Movement v4.8b, Repair v0.8a, Pest Control
# v1.4, Hearts v1.0 and Sensors '76.}
{149}{}{程序参数改变。当前软件是：设备维护v2．1，运转系统v4．8b，修理系统v0．8，病毒控制系统v1．4，红心大战v1．0，传感器＇76}

#{150}{}{Adjust parameters on Movement.}
{150}{}{调整运转系统参数。}

#{151}{}{Adjust Sensor parameters.}
{151}{}{调整传感器参数。}

#{152}{}{Modify Pest Control.}
{152}{}{修改病毒活体控制。}

#{153}{}{Play Hearts.}
{153}{}{启动红心大战。}

#{154}{}{Thanks. End input.}
{154}{}{谢谢。结束输入。}

#{155}{}{Current applications are: Facility Maintenance v2.1, Movement
# v4.8b, Repair v0.8a, Pest Control v1.4, Hearts v1.0 and
# Sensors '76.}
{155}{}{当前软件是：设备维护v2．1，运转系统v4．8b，修理系统v0．8，病毒控制系统v1．4，红心大战v1．0，传感器＇76}

#{156}{}{Adjust parameters on Movement.}
{156}{}{调整运转系统参数。}

#{157}{}{Adjust Sensor parameters.}
{157}{}{调整传感器参数。}

#{158}{}{Modify Pest Control.}
{158}{}{修改病毒控制。}

#{159}{}{Play Hearts.}
{159}{}{启动红心大战。}

#{160}{}{Thanks. End input.}
{160}{}{谢谢。结束。}

#{161}{}{Initializing voice communication subsystems. Initializing personality
# subsystems. 【Click!】 How may this terminal be of service?}
{161}{}{正在初始化声音通讯子系统。正在初始化个体子系统。【叮叮！】你需要什么帮助？}

#{162}{}{Hnng.}
{162}{}{呼。}

#{163}{}{Show me your programs.}
{163}{}{显示你的程序。}

#{164}{}{Shut down all force fields.}
{164}{}{关闭所有力场。}

#{165}{}{Do you know what this location is?}
{165}{}{你知道这是什么地方吗？}

#{166}{}{Initiate emergency shutdown.}
{166}{}{启动紧急关闭程序。}

#{167}{}{End input.}
{167}{}{结束。}

#{168}{}{This terminal cannot perform that function. Request denied.}
{168}{}{这个终端不能执行那个功能。请求被拒绝。}

#{169}{}{Show me your programs.}
{169}{}{显示你的程序。}

#{170}{}{Do you know what this location is?}
{170}{}{你知道这是什么地方吗？}

#{171}{}{Initiate emergency shutdown.}
{171}{}{启动紧急关闭程序。}

#{172}{}{End input.}
{172}{}{结束。}

#{173}{}{This is the -- classified 【click!】 【click!】}
{173}{}{这是——机密【叮叮！】【叮叮！】}

#{174}{}{Abort request. Show programs.}
{174}{}{终止请求，显示程序。}

#{175}{}{Override, continue request.}
{175}{}{覆盖，继续请求。}

#{176}{}{【Click!】 This is the FEV production control facility. This
# terminal online 2074. Final pre-production process 2075. It
# is currently under final construction, and is due to open
# 2078. 【Click!】}
{176}{}{【叮叮！】本终端在启动于2074，最近一次试生产于2075，目前正在调试，最终将于2078正式投入生产【叮叮！】}

#{177}{}{Do you know what FEV is?}
{177}{}{什么是FEV？}

#{178}{}{Do you know what date it is?}
{178}{}{你知道日期吗？}

#{179}{}{FEV is Forced 【click!】 Evolutionary Virus, a product of the
# Livermore/Broansoun Laboratories. It is designed to increase
# the genetic complexity of a DNA/RNA series in a shorter period
# of time.}
{179}{}{FEV是被强行【叮叮！】进化的病毒，产自雷蒙莫／布朗讯实验室。它的功能是短时间迅速改变基因／核糖核酸的排列顺序。}

#{180}{}{Show programs.}
{180}{}{显示程序。}

#{181}{}{End input.}
{181}{}{结束。}

#{182}{}{Affirmative. Terminal date is February 2, 2077.}
{182}{}{确定。终端的日期是2077年2月2日。}

#{183}{}{Show programs.}
{183}{}{显示程序。}

#{184}{}{End input.}
{184}{}{结束。}

#{185}{}{That date is incorrect. Please recalibrate.}
{185}{}{日期错误。请重新核对。}

#{186}{}{Correcting. 【Click!】 Error. Attempting self-diagnostics.
#【Click! CLICK!】 ERROR! FATAL SYSTEM ERROR. SYSTEM CORRUPTED,
# ATTEMPTING RECOMPILATION. 【Long pause.】}
{186}{}{警告。【叮叮！】错误。正在尝试自测试。【叮叮！叮叮！】错误！致命系统错误。系统崩溃，尝试终止。【死机。】}

#{187}{}{Terminal?}
{187}{}{终端？}

#{188}{}{【click】 Error in recompilation . . . 【click】}
{188}{}{【叮叮】重新启动错误……【叮叮】}

#{189}{}{Cannot process request. Terminating dialogue.}
{189}{}{无法处理请求。结束对话。}

#{190}{}{Confirm emergency codescram.}
{190}{}{确认紧急口令。}

#{191}{}{Confirmed.}
{191}{}{确定。}

#{192}{}{Terminate shutdown procedure.}
{192}{}{终止关闭程序。}

#{193}{}{【Click!】}
{193}{}{【叮叮！】}

#{194}{}{Processing request. Terminating dialogue.}
{194}{}{正在处理请求。正在访问终端。}

#{195}{}{This computer is not compatible with your radio. It uses a special high-
#frequency band for robotic use only.}
{195}{}{这个计算机不能与你的无线电兼容。它使用的是机器人专用的一个特别频率波段。}

#{196}{}{You press some buttons but the computer seems to be damaged. It will take
# some work to operate it.}
{196}{}{你按了几个按钮却没反应，计算机看上去已经坏掉了。它需要调理一下才能再操作。}

#{197}{}{The computer is not physically damage, but instead seems to have corrupted
# data.}
{197}{}{计算机的本身没有损坏，但是里边的数据已经被破坏了。}
