{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see Romero.}
{100}{}{你看到罗梅罗。}

#{103}{}{You see a member of the Blades.}
{103}{}{你看到一个利刃帮的成员。}

#{104}{}{You see a member of the Blades.}
{104}{}{你看到一个利刃帮的成员。}

#{105}{}{You think that might be Books.}
{105}{}{你认为那可能是“书”。}

#{106}{}{You think that might be Scars.}
{106}{}{你觉得那可能是“疤痕”。}

#{107}{}{You think that might be Gunner.}
{107}{}{你觉得那可能是“枪手”。}

#{108}{}{You think that might be Twitch.}
{108}{}{你觉得那可能是“抽筋”。}

#{109}{}{You think that might be Hammer.}
{109}{}{你觉得那可能是个“锤子”。}

#{110}{}{You think that might be Razor.}
{110}{}{你认为那可能是“剃刀”。}

#{111}{}{Stand down!}
{111}{}{别动！}

#{112}{}{What? What do you mean?}
{112}{}{什么？你说什么？}

#{113}{}{Never!}
{113}{}{没门！}

#{114}{}{I'm here to talk about peace.}
{114}{}{我是来这里讲和的。}

#{115}{}{Okay.}
{115}{}{好吧。}

#{116}{}{I ask the questions here. What are you doing here?}
{116}{}{我问你。你在这里做什么？}

#{117}{}{I'm here looking for a friend.}
{117}{}{我在这找一个朋友。}

#{118}{}{I'm here to talk about peace.}
{118}{}{我来这里讲和。}

#{119}{}{I want to end the gang war!}
{119}{}{我要结束殴斗！}

#{120}{}{I want to drink the blood of the Blades!}
{120}{}{我要让利刃帮血流成河！}

#{121}{}{Then you're looking in the wrong area. Get lost.}
{121}{}{你来错地方了，滚。}

#{122}{}{You must be one of those wimpy little purple robes. Get out
# of here before we blow you away.}
{122}{}{你一定是那些穿紫色长袍的废物。在我杀了你之前离开这里。}

#{123}{}{Wait! I don't know what you're talking about. I'm here for
# Adytum. They want me to get everyone to leave them alone.}
{123}{}{等等！我不知道你在说什么。我来这里是那些内城区的家伙要我把所有人都赶走。}

#{124}{}{Peace THIS!}
{124}{}{这是和谈！}

#{125}{}{Sorry. I'll be going now.}
{125}{}{对不起。我马上走。}

#{126}{}{Hmm. If you are really from Adytum, then you are still a loser.
# There can never be peace while those Rippers are still around.}
{126}{}{嗯，如果你真的来自内城区，你是个败者，如果电锯党在这周围就永远没有和平。}

#{127}{}{What do you mean?}
{127}{}{你什么意思？}

#{128}{}{Uh, sure.}
{128}{}{哦，当然。}

#{129}{}{Ask Razor. She'll explain about those bloodthirsty inbreds.}
{129}{}{去问问剃刀。她会告诉你关于那些噬血如命的疯子的事儿。}

#{130}{}{Get lost!}
{130}{}{滚开！}

#{131}{}{Hey, now that you are a Blade, I need to ask you a favor.}
{131}{}{嘿，你是利刃帮的人，我得问你一点私事。}

#{132}{}{Sure.}
{132}{}{当然。}

#{133}{}{What is it?}
{133}{}{它是什么？}

#{134}{}{No way.}
{134}{}{没门。}

#{135}{}{Great. Take this locket to Julianna. Tell her that I hope
# to see her soon.}
{135}{}{很好。把这个小盒子带给茱莉亚娜。告诉她我希望马上见到她。}

#{136}{}{It seems that I have fallen for a girl in Adytum. Because of
# the Regulators shooting us on sight, I can't get close to her.}
{136}{}{她是让我为之倾倒的一个内城区女孩。因为管理者一看到我们就开枪，我不能接近她。}

#{137}{}{How can I help?}
{137}{}{我能帮上什么忙？}

#{138}{}{Go on.}
{138}{}{继续。}

#{139}{}{Tough break.}
{139}{}{听够了。}

#{140}{}{If you take this locket to Julianna, I would be in your debt.}
{140}{}{如果你能把这个小盒子带给茱莉亚娜，我会欠你一份人情。}

#{141}{}{Sure thing.}
{141}{}{确实。}

#{142}{}{Find someone else.}
{142}{}{找别人吧。}

#{143}{}{With allies like you, who needs enemies? Good bye!}
{143}{}{和你这样的盟友在一起，谁又敢作对？再见！}

#{144}{}{I think she loves me too, but I don't know. The Blades won't
# risk letting me try to break into Adytum.}
{144}{}{我想她也爱我，但是我不确定。利刃帮不敢冒险让我冲进内城区。}

#{145}{}{Tough break.}
{145}{}{听够了。}

#{146}{}{Okay, I'll help.}
{146}{}{好，我会帮忙。}

#{147}{}{Thank you! She sent me a note. We are going to meet at
# the Follower's place and get married.}
{147}{}{谢谢你！她给我递纸条来说，我们要在末世论者的地盘重聚并结婚！}

#{148}{}{Welcome back.}
{148}{}{欢迎回来。}

#{149}{}{Thank you so much. We will stay here with the Followers now,
# where we can be happily married.}
{149}{}{非常感谢你，我们将会和末世论者一起住在这里，然后幸福的结婚。}

