{1099}{}{?}
{1199}{}{此人不能告诉你什么。}

#{100}{}{You see one of Shady Sands' guards.}
{100}{}{你看到一个沙荫镇的卫兵。}
#{101}{}{Hey, I think you'd better be leaving. We don't want your kind here.}
{101}{}{嘿！我认为你最好离开这儿。我们不希望有你这样的人在这里。}
#{102}{}{I can't believe that Tandi has disappeared. I hope you are going to find her. It would really hurt Aradesh if something bad happened to her.}
{102}{}{难以相信，坦蒂居然失踪了。我希望你能找找她。如果有什么不好的事发生在她身上，亚拉德什会很受打击的。}
#{103}{}{Thanks for returning Tandi. It's a good sign for the future, don't you think?}
{103}{}{谢谢你送回了坦蒂。这是个好兆头，对吧？}
#{104}{}{That's a damn shame about Tandi. I hope Aradesh will be ok.}
{104}{}{那对坦蒂来说是奇耻大辱。我真希望亚拉德什不会太难过。}
#{105}{}{Welcome, stranger. We don't see your kind often.}
{105}{}{你好，陌生人。我们可不常见到你这样的人。}
#{106}{}{Uh, thanks. Bye.}
{106}{}{呃，谢谢了。再见。}
#{107}{}{Why not?}
{107}{}{为什么不？}
#{108}{}{Hnnng!}
{108}{}{哼！}
#{109}{}{Not so fast! This is a small community. We don't see strangers often, and we don't really need them if you get my meaning. If you don't have a good reason to be here, you'd better just keep moving.}
{109}{}{别急！这是个小部落。我们不常见到陌生人，我们不需要陌生人你明白吗？如果你拿不出个留下来的好理由，就最好快滚。}
#{110}{}{Hey, I ain't gonna hurt anybody.}
{110}{}{嘿！我不会伤害任何人的。}
#{111}{}{Uh.}
{111}{}{嗯。}
#{112}{}{I wasn't saying that you was gonna. You'd just better leave us alone.}
{112}{}{我没说你会伤害谁。你最好快点离我们远点。}
#{113}{}{I'll try not to make trouble.}
{113}{}{我会尽量不捅乱子的。}
#{114}{}{I'm sick and tired of your trash. Prepare to meet your maker.}
{114}{}{我受够了你的废话！准备受死吧。}
#{115}{}{Look, Shady Sands don't need your kind from the Hub, or Junktown, or wherever you come from. We do pretty good by ourselves.}
{115}{}{你得明白，沙荫镇不需要像你这样来自哈勃城，迦克镇或是其他什么鬼地方的家伙。我们自己可以过得非常好！}
#{116}{}{The last trader from the Hub sold us a malfunctioning irrigation pump. We've had it with your dirty deals.}
{116}{}{最近有个哈勃城商人卖给了我们一个有故障的灌溉水泵。我们就是和类似你那样肮脏的人交易才得到这个破东西。}
#{117}{}{You got it all wrong. I'm not like that.}
{117}{}{你弄错了。我可不那么龌龊。}
#{118}{}{Yeah, right. So you say. Just don't get into any trouble, Ok?}
{118}{}{好。这可是你说的。千万别出什么岔子，知道了吗？}
#{119}{}{No problem.}
{119}{}{没问题。}
#{120}{}{Yeah, whatever.}
{120}{}{好，随便吧。}
#{121}{}{Well, maybe you aren't. You do seem a little different to me. I'll tell you what. You should go talk to Aradesh. He is in the center of town.}
{121}{}{那么，可能你不是那样。但你似乎真的跟我不太一样。我会告诉你我们的差别在哪儿。你应该去见见亚拉德什。他在镇中心。}
#{122}{}{We don't want your kind here. Go back to wherever you came from.}
{122}{}{我们不想让你这样的人呆在这里。哪儿来的就回哪儿去！}
#{123}{}{Hey, no need for weapons. We don't look too kindly on those around here.}
{123}{}{嘿！别拿武器，我们当地人对外面来的人也不会太友善的。}
#{124}{}{Hey, you didn't turn out to be such a bad person after all. Have a nice day.}
{124}{}{嘿！事实证明你并不是个坏人。祝你过得愉快。}
#{125}{}{I really wish you would just leave town.}
{125}{}{我真的希望你可以离开这个小镇。}
#{126}{}{【MORE】}
{126}{}{【更多】}
