{100}{}{Das Geröll ist hoch vor dem Eingang aufgestapelt. Es ist zu schwer, 
 um es zu bewegen. Du fragst dich, ob der Steuerchip einmal hier gewesen ist. 
 Wenn er hier war, dann ist er jetzt verschwunden.}
{101}{}{Große, schwere Felsen blockieren den Weg zu dem Raum. Du machst dich
 an einem Felsen zu schaffen, aber er bewegt sich nicht von der Stelle.}