{100}{}{Du beginnst, die Leiter hinaufzusteigen.}
{101}{}{Du rutschst von der Leiter ab und fällst in die Dunkelheit.
 Du landest mit einem Knall, bist aber nicht verletzt.}
{102}{}{Du rutschst von der Leiter ab und fällst in die Dunkelheit.
 Du landest mit einem Knall und hast eine}
{103}{}{ Verletzung.}
{104}{}{Du fällst nahe am Boden von der Leiter.}
