{100}{}{Nie zuvor in deinem Leben hast du eine Dunkelheit wie diese gesehen. Sie erscheint dir fast unnatürlich.}
{101}{}{Dir gelingt es kaum deine Ängste in Schach zu halten, dennoch schafst du es dich in die Dunkelheit zu begeben.}