{100}{}{Du benutzt den Türcomputer. Dein Zugriffscode wird vom Computer nicht erkannt.}
{101}{}{Du benutzt den Türcomputer. Ein Lautsprecher schaltet sich mit einem Rauschen ein.}
{102}{}{Tut uns leid, wir können dich momentan nicht hereinlassen. Uh, technische Probleme. Versuch's später noch mal.}
{103}{}{Du siehst den Eingangscomputer der Tür zu Vault-13.}
