{100}{}{Thanks, bye.}
{101}{}{Okay, thanks.}
{102}{}{Hmm. Bye.}
{103}{}{See ya.}
{104}{}{Thanks.}
{105}{}{Okay, bye.}
{106}{}{[More]}
{107}{}{Zzzzz}
{108}{}{[Done]}
{109}{}{I can't use that.}## "that weapon"?
