{100}{}{ senses a trap nearby.}
{101}{}{You sense a trap nearby.}
{102}{}{ sets off a trap, alerting the base to your presence!}}
{103}{}{You set off a trap, alerting the base to your presence!}
{104}{}{You earn }
{105}{}{ experience points for successful use of your Traps skill.}
{106}{}{ disarms the trap.}
{107}{}{You disarm the trap.}
{108}{}{ sets off a trap.}
{109}{}{You set off a trap.}
