##
## NOTE: EACH LINE IN THE MESSAGE BOX AT 640x480 ONLY DISPLAYS TWENTY SIX
# (26) CHARACTERS. Anything over that will wrap.  --Sduibek, Fallout Fixt
##
{100}{}{Rocket}
{200}{}{Plasma Ball}
{300}{}{Explosion}
{400}{}{Blood}
{500}{}{No-Trans hex}
{501}{}{}
{600}{}{Knife}
{700}{}{Spear}
{800}{}{EMP Explosion}
{900}{}{Laser Blast}
{1000}{}{Plasma Blast}
{1100}{}{Explosion}
{1200}{}{Scroll Blocker}
{1300}{}{Electricity Bolt}
{1400}{}{Explosion}
{1500}{}{Explosion}
{1600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{1900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{2400}{}{Flare}
{2500}{}{Grenade}
{2600}{}{Rock}
{2700}{}{Explosion}
{2800}{}{Explosion}
{2900}{}{Explosion}
{3000}{}{Molotov Cocktail}
{3100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3700}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3800}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{3900}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4000}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4100}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4200}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4300}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4400}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4500}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
{4600}{}{an "Exit Grid". You didn't learn about exit grids in your Vault. Sounds scary}
