#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš Abela.}
{101}{}{Vidíš velikého mutanta.}
{102}{}{Tady nemáš co dìlat!}
{103}{}{Hng.}
{104}{}{Souhlasím. Jen tì zabiju a hned zase pùjdu!}
{105}{}{Proè tohle øíkáš?}
{106}{}{Oh, opravdu? Na to TY nemáš!}
{107}{}{Pik!}
{108}{}{Jestli to øekneš ještì jednou, nakopu ti zadek!}
{109}{}{Pik! Pik!}
{110}{}{Oh, teï TY to schytat!}
{111}{}{Ty být èlovìk. Já mutant. Mutant zabíjet èlovìk.}
{112}{}{A jak to udìláš? Co to silové pole, to ti nevadí?}
{113}{}{Abel se o to postará. Potom Abel nakopat tvùj zadek!}
{114}{}{Dìti nesmìt být tady. Tohle být místo pro mutanty. Jdi pryè.}
{115}{}{Hng!}
{116}{}{Potøebuju projít skrz tohle silové pole. Vypni ho prosím.}
{117}{}{Ne.}
{118}{}{Zase ty? Abel tì teï zabít!}

# tell me about name
{970}{}{Já být Abel.}

# tell me about generic
{980}{}{Hng.}
{981}{}{Proè tohle øíkáš?}
