#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš Jadea.}
{101}{}{Vidíš Becu.} 
{102}{}{}
{103}{}{}
{104}{}{Vidíš èlena Blades.}
{105}{}{Vidíš èlenku Blades.}
{106}{}{Tohle bude nejspíš Books.}
{107}{}{Tohle bude nejspíš Scars.}
{108}{}{Tohle bude nejspíš Gunner.}
{109}{}{Tohle bude nejspíš Twitch.}
{110}{}{Tohle bude nejspíš Hammer.}
{111}{}{Tohle bude nejspíš Razor.}
{112}{}{Tohle jsou naše ložnice. A teï odsud vypadni, než tì nakopu do zadku.}
{113}{}{Zkus to.}
{114}{}{Omlouvám se za to vyrušení. Sbohem.}
{115}{}{Mùžu si tu trochu oddechnout?}
{116}{}{Ne. Tohle je jenom pro opravdové Blades, ne pro kdejakého pøivandrovalce.}
{117}{}{Hej, kámo! Jak je? Lehni si tu, jestli hledáš kousek klidnýho místeèka.}
