#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Z pøíkazu šerifa Justina Greena uzavøeno.}
{101}{}{Na boudì je malá vývìska.}
{102}{}{Hledá se: Bob 'Leguán' Frazier, mrtvý nebo živý. Pokud jsou vám známy jakékoli informace o místì jeho souèasného pobytu nebo o osobì zodpovìdné za jeho útìk, informujte prosím okamžitì šerifa.}
