#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš muže. Na chvíli se ti strnule podíval do oèí, a pak rychle uhnul pohledem.}
{101}{}{Vidíš Grega.}
{102}{}{Co?  Proè na mì mluvíš? Oni tì uslyší.}
{103}{}{Ahoj, tak jsi tu.  Nemluv tak nahlas, mùžou nás slyšet.}
{104}{}{OK, ale buï potichu. Jestli nepøestaneš køièet, tak nás chytí oba dva.}
{105}{}{Kdo jsi?}
{106}{}{Proè jsi tak ustrašený?}
{107}{}{Myslím, že by ti mìli zvýšit dávky lékù.}
{108}{}{No jo.}
{109}{}{Já jsem...Greg...ale nikomu to neøíkej, nebo mì najdou.}
{110}{}{Ustrašený? Já nejsem ustrašený.  Jen opatrný.  Všichni øíkají, že jsem paranoik, ale já vím, že si pro mì brzy pøijdou.}
{111}{}{Pøijdou si pro tebe?  Kdo si pro tebe pøijde?}
{112}{}{Jasnì, že jsi paranoidní. Promluvíme si nìkdy jindy.}
{113}{}{No oni jsou...víš pøece, ne?...Všechna ta hrùza teprve zaèíná.  Teï pøijdou a všechny nás dostanou.  Ale ty jsi jako všichni ostatní.  Nevìøíš mi a proto budeš ztracen.  Pamatuj si moje slova.  JÁ TU BUDU POØÁD, ALE TEBE ONI DOSTANOU. VÁS VŠECHNY DOSTANOU. Já . .  DOSTANOU. [Greg se chytil za hlavu a s kòuèením pobíhá okolo]}
{114}{}{Lékù...Aha, tak ty jsi jeden z nich, chceš mì taky dostat....Ale to se ti nepodaøí.  JÁ SI TY LÉKY NEVEZMU. NE, NEVEZMU.  TY HLASY. NE JÁ NECHCI, NECHTE MÌ. [Greg zavøel oèi, zuøivì si sevøel hlavu do dlaní, a teï mluví s hlasy, které mùže slyšet jen on sám.]}
{115}{}{TO MI NESMÍŠ UDÌLAT!}
{116}{}{NIC, CO UDÌLÁŠ, JE NEZASTAVÍ!}
{117}{}{JE PO VŠEM!}
{118}{}{UŽ JDOU A TY JE NEZASTAVÍŠ!}
{119}{}{VŠECHNY VÁS ZNIÈÍ!}

