#tento soubor pøeloil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš Cabbota, Zasvìcence Bratrstva Oceli.}
{101}{Cab_1}{Buï pozdraven a vítej v sídle Bratrstva Oceli. Mùu vìdìt, co tì sem pøivádí?}
{102}{}{Kdo jsi?}
{103}{}{Mùu se tì zeptat na pár vìcí?}
{104}{}{Uhhh?}
{105}{}{Chci se k vám pøidat.}
{106}{}{Co tu dìláš?}
{107}{}{Vlastnì nic, díky.}
{108}{Cab_2}{Uh, já jsem Cabbot, ale tys mi neodpovìdìl. Co pro tebe mùu udìlat? }
{109}{}{Mùu se tì zeptat na pár vìcí?}
{110}{}{Ó ano, kdy to chceš vìdìt.}
{111}{}{Chci se k vám pøidat.}
{112}{}{Co tu dìláš?}
{113}{}{Vlastnì nic, díky.}
{114}{Cab_4}{To je skvìlé! Uh, p-poèkej tu chvíli a já se skoèím zeptat co a jak!}
{115}{Cab_5}{Uh, no, mluvil jsem s Nejvyšším Velitelem a on øekl, e momentálnì nikoho nebereme. On, ehm, on øíkal, e musíš nejdøív splnit jeden úkol.}
{116}{}{Jakı úkol?}
{117}{}{Hmm, uvidíme se pozdìji.}
{118}{}{Ty jsi taky skládal nìjakou zkoušku, ne tì pøijali?}
{119}{Cab_5a}{Uh, ne tak docela. Ale kdy ono je teï všechno trochu jiné.}
{120}{}{Tak co je to za úkol?}
{121}{}{No tak mi povìz, co se tak zmìnilo.}
{122}{}{Tak fajn, pøijdu nìkdy jindy.}
{123}{Cab_6}{Musíš dojít a k ruinám Starého Øádu. To je na jih odsud. Uh a taky budeš muset vejít dovnitø a pøinést zpátky nìco, co dokáe, e jsi tam byl.}
{124}{}{A jak poznáš, e to, co ti pøinesu, je tam odsud?}
{125}{}{Oukej.}
{126}{}{Ani náhodou.}
{127}{Cab_7}{To místo je vysoce technologické. Uvnitø jsou vìci, jaké jsi v ivotì nevidìl. Oh, uh, a taky je to tam radioaktivní. Aheh.}
{128}{}{Oukej, udìlám to.}
{129}{}{To zní nebezpeènì. Z toho mì vynechte.}
{130}{Cab_9}{Ty to udìláš? Udìláš? Vıbornì! Tak mi to pøines! A hodnì štìstí.}
{131}{Cab_10}{Oh . . . tak dobøe.  Sbohem. }
{132}{Cab_12}{No uh, já jsem Zasvìcenec. A právì teï mám slubu jako uvítací vıbor u dveøí.}
{133}{}{To sice nezní zrovna napínavì, ale pøesto chci poøád vstoupit do Bratrstva.}
{134}{}{Oukej, díky. Uvidíme se.}
{135}{}{Mùu se tì na pár vìcí zeptat?}
{136}{Cab_16}{No uh, mám se ptát. To je mùj úkol na tomhle místì.}
{137}{}{Mùu se tì na pár vìcí zeptat?}
{138}{}{Mùu vstoupit do Bratrstva?}
{139}{}{Tobì nic neøeknu. Jdi ke svému veliteli.}
{140}{}{Dobrá tedy, já u jdu.}
{141}{Cab_17}{Lituju, to opravdu nemùu. Oni - oni øekli, e ne. Sbohem!}
{142}{Cab_18}{Ne! Jdi pryè! }
{143}{Cab_19g}{Á opìt tì zdravím. U víš co chceš?}
{144}{Cab_19n}{Ahoj. A co potøebuješ teï?}
{145}{}{Rozmyslel jsem si to. Chci vstoupit do Bratrstva.}
{146}{}{Mùu se tì na pár vìcí zeptat?}
{147}{}{No nic. Sbohem.}
{148}{Cab_20}{Dìláš si ze mnì legraci, e jo? Sbohem! }
{149}{Cab_21}{Sbohem!}
{150}{}{Prosím, promiò mi, e jsem tì rozzlobil. Mùeme zaèít od zaèátku?}
{151}{}{Oukej.}
{152}{Cab_22}{Ne! Myslím, e mi poøád leš. Sbohem!}
{153}{Cab_23}{Hmmm. No dobrá, prozatím ti tedy vìøím. Tak co chceš?}
{154}{}{Rozmyslel jsem si to. Chci vstoupit do Bratrstva.}
{155}{}{Mùu se tì na pár vìcí zeptat?}
{156}{}{No nic. Sbohem.}
{157}{Cab_24}{Hej! Ty ses vrátil! Máš nìco?}
{158}{}{Jasnì e mám.}
{159}{}{Ne, ještì ne.}
{160}{Cab_25}{Skvìle! Ale . . . um . . . Nejvyšší velitel øekl, e mi to máš nejdøív dát, ne tì pustíme dovnitø. Sorry.}
{161}{}{Dobøe.}
{162}{}{Ne, to se mi nelíbí.}
{163}{Cab_27}{To je úasné! Poèkej chvíli, ne otevøu ty dveøe.}
{164}{}{OK.}
{165}{Cab_28}{Hmmm . . . Lituju, ale tohle mùeš mít i odjinud ne z Kráteru.}
{166}{}{Ale . . .}
{167}{Cab_30}{Dobøe, tak tì tedy pustím dovnitø. Ale nejdøív ti øeknu, co bude následovat. Dobøe? Já budu ve stránici. Ty potom mùeš odejít pryè, ale já to budu, kdo tì pak zase pustí dovnitø. Oh, a Nejvyšší velitel s tebou chce mluvit ve velitelské místnosti. Ta je ve tøetím patøe.}
{168}{Cab_31}{Zbyteènì mi leš. Vra se, a budeš nìco mít.}
{169}{Cab_32}{Dobrá, dej mi tedy vìdìt a nìco budeš mít.}
{170}{Cab_33g}{Ahoj! Chceš zase dovnitø?}
{171}{Cab_33b}{Jdeš zase zpátky dolù?}
{172}{Cab_33n}{Chceš dovnitø?}
{173}{}{Ano, prosím.}
{174}{}{Kdybys mohl otevøít ty dveøe.}
{175}{Cab_34g}{Bezva! Uvidíme se, huh?}
{176}{Cab_34b}{Fajn.}
{177}{Cab_34n}{Oukej.}
{178}{}{Co pøesnì dìláš?}
{179}{}{Slyšel jsi v poslední dobì nìjaké zajímavé drby?}
{180}{}{Sbohem, Cabbote.}
{181}{Cab_35a}{Pokraèuj.}
{182}{Cab_36g}{Nazdar! S èím ti mùu píchnout?}
{183}{Cab_36b}{Co potøebuješ?}
{184}{Cab_36n}{Mùu ti v nìèem píchnout?}
{185}{}{Mùu se tì na pár vìcí zeptat?}
{186}{}{No nic. Sbohem.} 
{187}{Cab_37}{Sbohem.}
{188}{Cab_38}{Vítám návštìvníky u dveøí a rozhoduju, jestli je vpustíme dovnitø nebo ne. Ty a obchodníci jste ti jediní, kteøí sem teï smí, protoe to vypadá, e Rada Starších nìco chystá.}
{189}{}{A ty víš, co to všechno znamená?}
{190}{}{Proè pouštíte dovnitø obchodníky?}
{191}{Cab_39}{Uh . . . to pøesnì nevím, ale ehm, slyšel jsem, e se Nejvyšší velitel hádá s ostatními Staršími.}
{192}{}{Mùu se tì na pár vìcí zeptat?}
{193}{}{Díky. Uvidíme se.}
{194}{Cab_40}{Proè je pouštíme dovnitø? No . . . potøebujeme pøece jídlo a spoustu dalších vìcí.  Prodáváme jim za to naše zbranì.}
{195}{}{A proè si nepìstujete jídlo sami?}
{196}{}{Mùu se tì na pár vìcí zeptat?}
{197}{}{Díky. Uvidíme se.}
{198}{Cab_41}{Uh, no, úèelem tohohle místa je vychovávat Písaøe a Rytíøe. Kdokoliv chce bıt nìèím jinım, mùe klidnì odejít.}
{199}{}{Ach tak. Mùu se tì na pár vìcí zeptat?}
{200}{}{Díky. Uvidíme se.}
{201}{Cab_42}{No, nìkteøí ze Zasvìcencù si myslí, e se pøipravujeme na válku. To je taky dùvod, proè skoro nikoho nepouštíme dovnitø. Vlastnì mì pøekvapilo, kdy mi Nejvyšší velitel øekl, abych tì pustil.}
{202}{}{Proè?}
{203}{}{Díky. Mùu se tì na pár vìcí zeptat?}
{204}{}{Díky za to info. Uvidíme se.}
{205}{Cab_43}{Nemyslím, e by ti do toho nìco bylo.}
{206}{Cab_44}{Je mi líto, ale budu muset zavolat stráe.}
{207}{Cab_45}{Myslím, e tohle bys nemìl dìlat.}
{208}{Cab_46a}{Oh, oukej. Jak chceš.}
{209}{Cab_47}{U jsem ti øíkal . . .}
{210}{Cab_48}{No, jak jsem ti øíkal . . .}
{211}{Cab_49}{Jak u jsem ti povídal . . .}
{212}{Cab_50}{U jsem ti to pøece øíkal . . .}
{213}{Cab_51}{No, ehm, já - já nechci bıt nezdvoøilı, ale nerad bych se opakoval. Rozumíš?}
{214}{}{Um, víš, na to, abych tu sedìl a dokola poøád opakoval jedno a to samé, opravdu nemám èas. Rozumíš mi, e ano?}
{215}{Cab_53}{No, to jsem pøece já.}
{216}{Cab_54}{Je to vedoucí Písaøù. Vìtšinou bıvá v knihovnì. Sjeï dolù do suterénu a uh, a potom je to po pravé ruce.}
{217}{Cab_55}{Rytíøi o nìm øíkají, e bıvá velice pøísnı. Já osobnì to o nìm neøíkám, protoe já uh, já se pod vedením Vree uèím na Písaøe.}
{218}{Cab_56}{Generál Maxson byl døíve Pánem Rytíøù. Myslím, e bıt Nejvyšším velitelem ho moc nebaví.}
{219}{Cab_57}{Rozhodují tu o všem. Od toho, co budeme mít k jídlu, a po naší strategii. A uh, taky se dost hádají. Nejvyšší velitel s nimi èasto nesouhlasí.}
{220}{Cab_58}{OK, no, Písaøi jsou stráci celıch našich dìjin a taky shromaïují plány zbraní, které tu vyrábíme. Já miluju knihy; to je dùvod, proè chci bıt jedním z . . . Písaøù.}
{221}{Cab_59}{No, víš, oni jsi to, kdo se chtìjí stát ochránci našeho Bratrstva. Moc jich tu není, ale celı svùj ivot trénují, aby se z nich stali Paladini.}
{222}{Cab_60}{To je to mìsto na jihu, e ano? Obèas sem k nám odtamtud pøicházejí obchodníci, ale já sám tam nikdy nebyl. Jeíši, vdy já bych ani nevìdìl, co v takovém velikém mìstì dìlat.}
{223}{Cab_61}{Myslím, e o tom ti by ti víc povìdìla Vree. Ona o tom ví víc.}
{224}{Cab_62}{Prodávají nám jídlo, vodu a spoustu dalších vìcí. My jim za to dodáváme zbranì.
 Nechodí sem moc èasto, ale uh, ani nevím proè.}
{225}{Cab_63}{Ó, to je dlouhı pøíbìh. Zajdi si do knihovny za Vree. Ukáe ti, kde jsou holodisky s historickımi daty.}
{226}{Cab_64}{Oh, tak, v dobì Exodu se Bratrstvo rozdìlilo na dvì skupiny.  Èást, která se oddìlila, ukradla ostatním nìjaké ty zbranì, a potom zamíøila na jih.  Asi pøed deseti lety jsme poslali pár našich Rytíøù, aby se po nich podívali, ale ti našli jen ruiny. Nikdo neví, co se tam stalo.}
{227}{Cab_65}{Starodávné Bratrstvo sem pøišlo z nìjakého místa daleko na severu u pøed dlouhou dobou. Tomu øíkáme velkı Exodus. Mùeš si o tom pøeèíst nìco v knihovnì, kdy poádáš Vree, aby ti ukázala disky.}
{228}{Cab_66}{Uhh . . . o tom nic nevím.}
{229}{Cab_67}{Hmm . . . nevím. Moná by ses mìl zeptat nìkoho dùleitìjšího, ne jsem já.}
{230}{Cab_68}{Nevím co je to. Moná by ses mìl pozeptat jinde.}
{231}{}{Promluv si s Mathiou. Ona ti o tom øekne víc.}
{232}{}{Obdrel jsi 2000 zkušenostních bodù za získání statutu Zasvìcenec.}
{233}{}{O takové jako jsi ty, tu nestojíme. Jdi pryè!}


# Cabbot Tell-Me-Abouts generic responses
{980}{Cab_66}{Uhh . . . o tom nic nevím.}
{981}{Cab_67}{Hmm . . . nevím. Moná by ses mìl zeptat nìkoho dùleitìjšího, ne jsem já.}
{982}{Cab_68}{Nevím co je to. Moná by ses mìl pozeptat jinde.}

#
# Cabbot Tell-Me-Abouts
#


{1000}{}{Zasvecenec}
{1001}{}{Vree}
{1002}{}{Rhombus}
{1003}{}{Starsi}
{1004}{}{Rada Starsich}
{1005}{}{Pisari}
{1006}{}{Rytiri}
{1007}{}{Hub}
{1008}{}{Disky}
{1009}{}{Kupci}
{1010}{}{Bratrsvo}
{1011}{}{Starobyly}
{1012}{}{Exodus}
{1013}{}{Cabbot}
{1014}{}{Rad}
{1015}{}{Paladini}
{1016}{}{Vudce}
{1017}{}{Valka}
{1018}{}{Armada}
{1019}{}{Karavany}
{1020}{}{Katedrala}
{1021}{}{Cip}

{1100}{Cab_53}{No, to jsem pøece já.}
{1101}{Cab_54}{Je to vedoucí Vìdcù. Vìtšinou bıvá v knihovnì. Sjeï dolù do suterénu a uh, a potom je to po pravé ruce.}
{1102}{Cab_55}{Rytíøi o nìm øíkají, e bıvá velice pøísnı. Já osobnì to o nìm neøíkám, protoe já uh, já se pod vedením Vree uèím na Písaøe.}
{1103}{Cab_56}{Generál Maxson byl døíve Pánem Rytíøù. Myslím, e bıt Nejvyšším velitelem ho moc nebaví.}
{1104}{Cab_57}{Rozhodují tu o všem. Od toho, co budeme mít k jídlu, a po naší strategii. A uh, taky se dost hádají. Nejvyšší velitel s nimi èasto nesouhlasí.}
{1105}{Cab_58}{OK, no, Písaøi jsou stráci celıch našich dìjin a taky shromaïují plány zbraní, které tu vyrábíme. Já miluju knihy; to je to, proè chci bıt jedním z . . . Písaøù.}
{1106}{Cab_59}{No, víš, to jsou ti, kdo se chtìjí stát ochránci našeho Bratrstva. Moc jich tu není, ale celı svùj ivot trénují, aby se z nich stali Paladini.}
{1107}{Cab_60}{To je to mìsto na jihu, e ano? Obèas sem k nám odtamtud pøicházejí obchodníci, ale já sám tam nikdy nebyl. Jeíši, vdy já bych ani nevìdìl, co v takovém velikém mìstì dìlat.}
{1108}{Cab_61}{Myslím, e o tom ti by ti víc povìdìla Vree. Ona o tom ví víc.}
{1109}{Cab_62}{Prodávají nám jídlo, vodu a spoustu dalších vìcí. My jim za to dodáváme zbranì.
 Nechodí sem moc èasto, ale uh, ani nevím proè.}
{1110}{Cab_63}{Ó, to je dlouhı pøíbìh. Zajdi si do knihovny za Vree. Ukáe ti, kde jsou holodisky s historickımi daty.}
{1111}{Cab_64}{Oh, tak, v dobì Exodu se Bratrstvo rozdìlilo na dvì skupiny.  Èást, která se oddìlila, ukradla ostatním nìjaké ty zbranì, a potom zamíøila na jih.  Asi pøed deseti lety jsme poslali pár našich Rytíøù, aby se po nich podívali, ale ti našli jen ruiny.  Nikdo neví, co se tam stalo.}
{1112}{Cab_65}{Starodávné Bratrstvo sem pøišlo z nìjakého místa daleko na severu u pøed dlouhou dobou. Tomu øíkáme velkı Exodus. Mùeš si o tom pøeèíst nìco v knihovnì, kdy poádáš Vree, aby ti ukázala disky. }
{1113}{Cab_53}{No, to jsem pøece já.}
{1114}{Cab_64}{Oh, tak, v dobì Exodu se Bratrstvo rozdìlilo na dvì skupiny. Èást, která se oddìlila, ukradla ostatním nìjaké ty zbranì, a potom zamíøila na jih.  Asi pøed deseti lety jsme poslali pár našich Rytíøù, aby se po nich podívali, ale ti našli jen ruiny.  Nikdo neví, co se tam stalo.}
{1115}{Cab_20}{Dìláš si ze mnì legraci, e jo? Sbohem! }
{1116}{Cab_67}{Hmm . . . nevím. Moná by ses mìl zeptat nìkoho dùleitìjšího, ne jsem já.}
{1117}{Cab_63}{Ó, to je dlouhı pøíbìh. Zajdi si do knihovny za Vree. Ukáe ti, kde jsou holodisky s historickımi daty.}
{1118}{Cab_67}{Hmm . . . nevím. Moná by ses mìl zeptat nìkoho dùleitìjšího, ne jsem já.}
{1119}{Cab_62}{Prodávají nám jídlo, vodu a spoustu dalších vìcí. My jim za to dodáváme zbranì.
 Nechodí sem moc èasto, ale uh, ani nevím proè.}
{1120}{Cab_66}{Uhh . . . o tom nic nevím.}
{1121}{Cab_61}{O tom si promluv spíš s Vree. Ona ti o nich poví víc.}
