#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš malé dítì.}
{101}{}{Ahoj!}
{102}{}{Nazdar.}
{103}{}{Kde máš rodièe?}
{104}{}{Fòò.}
{105}{}{Nevím. Nìkde tady okolo.}
{106}{}{Ty jsi ale legraèní!}
{107}{}{Hej, chceš nìkoho zabít?}
{108}{}{Ano.}
{109}{}{Ne!}
{110}{}{Fòò.}
{111}{}{Øeknu to na tebe mamince!}
{112}{}{Tak tu nechoï s takovou velkou zbraní.}

{980}{}{Huh?}
{981}{}{Nevím. Zeptej se mámy.}
{982}{}{Zeptej se táty.}

{1000}{}{Parac}
{1001}{}{Bandita}
{1002}{}{Junktown}
{1003}{}{Brahmin}
{1004}{}{Cip}
{1005}{}{Kupci}
{1006}{}{Khanove}
{1007}{}{Garl}
{1008}{}{Shady Sands}
{1009}{}{Hub}
{1010}{}{Tandi}
{1011}{}{Aradesh}
{1012}{}{Seth}
{1013}{}{Razlo}
{1014}{}{Policie}
{1015}{}{Karavany}
{1016}{}{Obchodnici}
{1017}{}{Deti}
{1018}{}{Nekropolis}
{1019}{}{Spot}
{1020}{}{Bratrstvo}
{1021}{}{Pohrebiste}
{1022}{}{Veze}
{1023}{}{Mesto}
{1024}{}{Centrum}
{1025}{}{Pahorky}

{1100}{}{Jú! To je zlá pøíšera!}
{1101}{}{Strašnì zlobí!}
{1102}{}{Nevím.}
{1103}{}{Velcí smraïoši.}
{1104}{}{Zeptej se mámy.}
{1105}{}{Hodný lidi. Dávají mi bonbóny.}
{1106}{}{Strašnì zlobí!}
{1107}{}{Ošklivej pán.}
{1108}{}{To ti nepovím.}
{1109}{}{Velký mìsto.}
{1110}{}{To se neøíká.}
{1111}{}{Néévíím.}
{1112}{}{Máma nechce, abych o nìm mluvil.}
{1113}{}{Táta o nìm øíká, že je legraèní.}
{1114}{}{Velký lidi s puškama.}
{1115}{}{Mají ty smraïochy, co jim táhnou ty vozy.}
{1116}{}{Hodný lidi. Dávají mi bonbóny.}
{1117}{}{Neradi si hrajou na schovávanou.}
{1118}{}{Strašidelný místo.}
{1119}{}{Ošklivý místo.}
{1120}{}{Strašidelný místo.}
{1121}{}{Strašidelný místo.}
{1122}{}{Máma nás tam nenechá hrát.}
{1123}{}{Táta øíká, abysme si hráli tam.}
{1124}{}{Tam jsou velký lidi.}
{1125}{}{Tam jsou velký lidi.}
