{100}{}{Decker u si s tebou nepøeje mluvit.}
{101}{}{Vidíš Deckera.}
{102}{}{Decker má moc práce na to, aby se s tebou bavil. Udìlej, co máš, a pak se vra.}
{103}{DECK_1}{Take ty hledáš práci. Máš štìstí. Nìco tady mám. Ale, kde je moje vychování? Jak se jmenuješ?}
{104}{}{Jmenuju se }
{105}{}{.}
{106}{}{Co je ti do toho?}
{107}{DECK_2}{Tak, ertování máme za sebou. Chceš slyšet, co je to za práci?}
{108}{}{Proto jsem tady.}
{109}{}{Nijak zvláš.}
{110}{DECK_3}{Nástin situace:  Jsou tady nìkteøí kupci, kteøí . . . jak to správnì nazvat . . . úplnì nespolupracují s Podsvìtím.}
{111}{}{A ta práce?}
{112}{DECK_4}{Velice snadná. Vypátráš kupce a spolu s jeho enou je odstraníš. }
{113}{}{Myslíš tím zabít je?}
{114}{}{Kolik za tuhle práci?}
{115}{}{To nemohu udìlat!}
{116}{DECK_5}{To je jen otázka sémantiky, ale vlastnì ano. Zabij je. Bereš tu práci?}
{117}{}{Hmm, jistì - proè ne?}
{118}{}{Ne! To by bylo špatné!}
{119}{}{Kolik?}
{120}{DECK_6}{Á, skvìle. Normální taxa je 500 babek na zaèátek, a dalších 2500 . . . na konec.}
{121}{}{Kde toho kupce najdu?}
{122}{DECK_7}{Kupec ije v Pahorkách, na rohu Barter Street a Thunder Avenue. Splò úkol, a pak se vra.}
{123}{}{Jo, provedu.}
{124}{}{Jak poznáte, e jsem je zabil?}
{125}{}{To asi ne.}
{126}{DECK_8}{Skoro skvìlé. Mùj asistent tì doprovodí ven. Zavøi za sebou dveøe, prosím.}
{127}{deck_9}{Vìø mi. Poznáme to.}
{128}{}{Dobøe, udìlám to.}
{129}{}{Bì.}
{130}{DECK_10}{Musím se pøiznat, e jsi mne  . . . trochu zklamal. Ale to se stává. Nezapomeò, e tato rozmluva zùstane v tajnosti. Sbohem.}
{131}{DECK_11}{Standardní taxa. 500 pøedem, dalších 2500 po práci. Bereš to?}
{132}{}{Ne, díky.}
{133}{}{Jo, udìlám to.}
{134}{DECK_12}{Tak fajn. Kupec ije v Pahorkách, na rohu Barter Street a Thunder Avenue. Tìch 500 dostaneš pøi odchodu.}
{135}{DECK_13}{V Hubu je mi do VŠEHO nìco. Buï øekneš, nebo mùeš jít.}
{136}{}{Jmenuju se }
{137}{}{.}
{138}{}{Nic ti neøeknu.}
{139}{DECK_14}{Aha . . . Mùj asistent ti ukáe vıchod.}
{140}{DECK_15}{Jsem na tebe pyšnı. Jsi nelítostnı, to je vlastnost, kterou obdivuji.  Kane ti zaplatí. Doufám, e budeš k dispozici i v budoucnu.}
{141}{}{Mohu se na nìco zeptat?}
{142}{}{Díky.}
{143}{DECK_16}{Podle toho na co, prosím.}
{144}{}{Co je v Hubu?}
{145}{}{Slyšels nìjaké øeèi?}
{146}{}{Tak nic.}
{147}{Deck_16b}{Struènì. prosím.}
{148}{DECK_17}{V centru mìsta je Trištì, obklopené nìkolika ètvrtìmi. Na západì jsou to Pahorky, Staré mìsto je zase na vıchodì.}
{149}{}{Co je to za ètvrti?}
{150}{}{Díky za informace. Mohu se ještì zeptat?}
{151}{DECK_18}{
Jsi v Maltese Falconovi. Je tu ještì krámek Všechno-v-Jednome, the Armory, Friendly Lending Company, policie a, bohuel, nemocnice patøící Dìtem Katedrály.}
{152}{}{Vypadá to, e Dìti nemáš moc v lásce, o co jde?}
{153}{}{Díky. Mohu se ještì na nìco zeptat?}
{154}{DECK_19}{
Oni se . . . rozlézají. Nechme to bıt, ano?}
{155}{}{Jasnì. Mohu se ještì ptát?}
{156}{DECK_20}{Nejsem turistickı prùvodce. Jdi si to zjistit sám.}
{157}{}{Mohu se ještì na nìco zeptat?}
{158}{}{Pravda. Prùvodci by byli mnohem milejší.}
{159}{DECK_21}{Ne. Vem si svoje peníze a odejdi.}
{160}{DECK_22}{Coe? }
{161}{}{Slyšels dobøe.}
{162}{}{Nic. Mohu se ještì na nìco zeptat?}
{163}{DECK_23}{Ty drzoune. Mùj asistent tì vyhodí . . . chci øíct . . . odvede ke dveøím.}
{164}{deck_24}{Ne.}
{165}{}{Dobrá. Mohu se ještì na nìco zeptat?}
{166}{}{Ty jseš ale potrhlej.}
{167}{DECK_25}{Vypadá to, e nìco krade kompletní karavany firmy Far Go Traders. A Zlodìjskı cech má své obvyklé drobné potíe.}
# Line 168 has been changed due to gender issues. See lines 232-233.
{168}{}{}
{169}{}{jistì.}
{170}{}{Ani náhodou, kurva!}
{171}{DECK_27}{Vıbornì. Víš, minulı kšeft byl jenom k otestování tvıch schopností. Osvìdèil ses skvìle. A teï je tu práce, na které opravdu záleí.}
{172}{}{A co to je?}
{173}{}{To zní hrùzostrašnì. Myslím, e nemám zájem.}
{174}{DECK_28}{Moná u víš, e Dìti Katedrály získávají v tomto mìstì vliv, a upøímnì, to já nebudu trpìt.}
{175}{}{Take, co je tøeba udìlat?}
{176}{DECK_29}{Jen drobnost. Zabij hlavní knìku, Jain. Její smrt bude znamenat konec tìchto malıch otravù. Bereš?}
{177}{}{Samozøejmì.}
{178}{}{Ale to by bylo nemorální!}
{179}{DECK_30}{
Zaèínám tì mít vánì rád. Tentokrát je 1000 pøedem a 4000 po akci. A vìø mi, poznám, a to bude hotovo.}
{180}{}{Dobøe.}
{181}{DECK_31}{Promluv si na odchodu s Kanem. Seznámí tì s detaily.}
{182}{DECK_32}{a zabití kupce snad nebylo?}
{183}{}{Dobrá, dobrá, udìlám to.}
{184}{}{Na to seru. Tohle neudìlám.}
{185}{DECK_33}{Taxa je tentokrát 1000 pøedem a 4000 po akci. A vìø mi, poznám, a to bude hotovo.}
{186}{}{Dobøe.}
# Line 187 has been changed due to gender issues. See 234-235.
{187}{}{}
{188}{DECK_35}{Jaká škoda. Opravdu nechceš ani slyšet, co je to za práci?}
{189}{}{Jo, udìlám to.}
{190}{}{Dobrá, o co de?}
{191}{DECK_36}{V tom pøípadì nemáme o èem mluvit.}
{192}{DECK_37}{Vynikající práce. Vìøím, e náboenská frakce u víckrát zasahovat nebude. Máš mé díky a Kane pro tebe má slíbenou odmìnu. Urèitì si na tebe v budoucnu ještì vzpomenu.}
{193}{DECK_38}{Dej to pryè.}
{194}{DECK_39}{Jsem pomìrnì trpìlivı, ale jsou jisté hranice. Kane, dej tomu pitomci lekci.}
{195}{DECK_40}{Dost.}
{196}{DECK_42}{Promluv se s Kanem. Øekne ti víc.}
{197}{DECK_43}{Jak u jsem øekl . . .}
{198}{DECK_44}{Jak jsem øekl . . .}
{199}{DECK_45}{U jsem ti øekl . . .}
{200}{DECK_46}{Neposlouchals mì? Øíkal jsem . . .}
{201}{DECK_47}{Varuji tì: Nejsem zvyklı øíkat nìco víckrát.}
{202}{DECK_48}{Nebudu to opakovat.}
{203}{DECK_49}{O mì nic víc vìdìt nepotøebuješ.}
{204}{DECK_50}{Vìtšina lidí nešíøí jméno mé organizace ve správném svìtle. My øídíme celı Hub.}
{205}{DECK_51}{Má matka, nejlepší ena, kterou jsem znal, mì pøivedla na tuto myšlenku - vytvoøit nejlepší zábavní zaøízení v Hubu.}
{206}{DECK_52}{Kradou kupcùm a rozdávají to chudım, nebo nìjakı podobnı nesmysl. Pro mì jsou bezvıznamní. Ten starı mutant Harold snad ví víc.}
{207}{DECK_53}{Je velitelem policie. Pøíjemnej chlap, pokud máš rád fairplay, èestnej tıpek. Ne jako jeho táta; teï je tu loajální èlovìk.}
{208}{DECK_54}{Harold se tam potloukal nìjakou dobu. ije nìkde ve Starém Mìstì. Dobrej zdroj jistého druhu informací.}
{209}{DECK_55}{Mají pod kontrolou vodu. Najdeš je na jiním konci Kupeckého trištì.}
{210}{DECK_56}{Je šéfem Kupcù s vodou.}
{211}{DECK_57}{Øídili nemocnici, ne je vytlaèily Dìti Katedrály. Teï døepìj a dumaj ve svım skladišti-divnı, co. Najdeš je na severozápadním konci Kupeckého trištì.}
{212}{DECK_58}{Je šéfem firmy Crimson Caravan.}
{213}{DECK_59}{Jsou poslední z kupcù, myslím doslovnì. Krátkodobı záleitosti, vìtšinou. Jsou na severovıchodì Kupeckého trištì.}
{214}{DECK_60}{Zábavné. Myslí si, e je šéfem Far Go Traders. Ve skuteènosti je spíš loutka. Spíš se mi umí plést do obchodù.}
{215}{DECK_61}{Má pod palcem obchod se zbranìmi.}
{216}{DECK_62}{Kvùli nìèemu mizí karavany Far Go Traders. Rád bych vìdìl proè, protoe to narušuje èást mıch aktivit.}
{217}{Deck_63}{To je v centru mìsta.}
{218}{DECK_64}{Mıty a legendy. Páraè je nìjakı pøízrak nebo nìco takového.}
{219}{DECK_65}{Staré mìsto se rozkládá po celé vıchodní èásti. ijí tam Skagové.}
{220}{DECK_66}{Vìtšinou tam ijí kupci. Jdi pøímo na západ.}
{221}{DECK_67}{Otravná organizace. Brzy by mìli dostat lekci v pouití síly.}
{222}{DECK_68}{Morpheus je hlavou Dìtí Katedrály. ije nìkde v Pohøebišti.}
{223}{DECK_69}{V souèasnosti je šéfkou Dìtí zde v Hubu. Mám dùvod vìøit, e se to ale brzy zmìní.}
{224}{DECK_70}{Jeden z vımyslù Dìtí. Pravdìpodobnì nìjaké menší bostvo nebo tak nìco.}
{225}{DECK_71}{Malı koutek, kde prodávají . . . dobré zbranì.  Za budovou Far Go Traders.}
{226}{DECK_72}{Vyjdeš ze dveøí a poøád na sever. Nemùeš minout.}
{227}{DECK_73}{To není dùleité.}
{228}{DECK_74}{Coe? To teï není dùleité.}
{229}{DECK_75}{Vánì. Teï vánì, proè bych to mìl chtít udìlat?}
{230}{}{Vidím, e jsi zlikvidoval mého poboèníka. Budu to s tebou muset vyøídit sám.}
{231}{}{Rád vás vidím šerife Greene! Vidím, e jste se pøišel rozlouèit.}

#
# TRANSLATION NOTE: The following groups of  lines are identical in English,
# but they differ in foreign translations. The first line is for the case of the
# player-character masculine ("my friend" will be masculine); the second line is
# for the case of the player-character feminine ("my friend" will be feminine).
#

{232}{DECK_26}{Jak rád tì zase vidím. Mám pro tebe další práci.
 Máš zájem?}
{233}{DECK_26}{Jak rád tì zase vidím. Mám pro tebe další práci.
 Máš zájem?}

{234}{DECK_34}{A já ti tolik vìøil!
 Ale nemùu tì nechat varovat Dìti Katedrály. Kane, odstraò tuto osobu a nemusíš brát ohled na hluk.}
{235}{DECK_34}{ A já ti tolik vìøil!
 Ale nemùu tì nechat varovat Dìti Katedrály. Kane, odstraò tuto osobu a nemusíš brát ohled na hluk.}

# Decker Tell-Me-Abouts generic responses
{980}{DECK_73}{To není dùleité.}
{981}{DECK_74}{Co? To teï není dùleité.}

#
# Decker Tell-Me-Abouts
#

{1000}{}{Decker}
{1001}{}{Podsvetí}
{1002}{}{Maltese}
{1003}{}{Zlodeji}
{1004}{}{Justin}
{1005}{}{Harold}
{1006}{}{Kupci}
{1007}{}{Daren}
{1008}{}{Crimson}
{1009}{}{Demetre}
{1010}{}{Far}
{1011}{}{Butch}
{1012}{}{Beth}
{1013}{}{Ztracene}
{1014}{}{Trziste}
{1015}{}{Paradlo}
{1016}{}{Mesto}
{1017}{}{Pakorky}
{1018}{}{Katedrála}
{1019}{}{Morpheus}
{1020}{}{Jain}
{1021}{}{Vudce}
{1022}{}{Obchod}
{1023}{}{Vsechno-v-jednom }
{1024}{}{Falcon}
{1025}{}{Nightclub}
{1026}{}{Greene}
{1027}{}{Hightower}
{1028}{}{Karavany}
{1029}{}{Romara}
{1030}{}{Go}
{1031}{}{Trader}
{1032}{}{Harris}
{1033}{}{Parac}
{1034}{}{Paraci}
{1035}{}{Stare}
{1036}{}{Mesto}
{1037}{}{Deti}
{1038}{}{Vsechno}

{1100}{DECK_49}{O mì nic víc vìdìt nepotøebuješ.}
{1101}{DECK_50}{Vìtšina lidí nešíøí jméno mé organizace ve správném svìtle. My øídíme celı Hub.}
{1102}{DECK_51}{Má matka, nejlepší ena, kterou jsem znal, mì pøivedla na tuto myšlenku, nejlepší zábavní zaøízení v Hubu.}
{1103}{DECK_52}{Kradou kupcùm a rozdávají to chudım, nebo nìjakı podobnı nesmysl. Pro mì jsou bezvıznamní. Ten starı mutant Harold snad ví víc.}
{1104}{DECK_53}{Je velitelem policie. Pøíjemnej chlap, pokud máš rád fairplay, èestnej tıpek. Ne jako jeho táta; teï je tu loajální èlovìk.}
{1105}{DECK_54}{Harold se tam potloukal nìjakou dobu. ije nìkde ve Starém Mìsto. Dobrej zdroj jistého druhu informací.}
{1106}{DECK_55}{Mají pod kontrolou vodu. Najdeš je na jiním konci Kupeckého trištì.}
{1107}{DECK_56}{Je šéfem Kupcù s vodou.}
{1108}{DECK_57}{Øídili nemocnici, ne je vytlaèily Dìti Katedrály.  Teï døepìj a dumaj ve svım skladišti-divnı, co. Najdeš je na severozápadním konci Kupeckého trištì.}
{1109}{DECK_58}{Je šéfem firmy Crimson Caravan.}
{1110}{DECK_59}{Jsou poslední z kupcù, myslím doslovnì. Krátkodobı záleitosti, vìtšinou. Jsou na severovıchodì Kupeckého trištì.}
{1111}{DECK_60}{Zábavné. Myslí si, e je šéfem Far Go Traders. Ve skuteènosti je spíš loutka. Spíš se mi umí plést do obchodù.}
{1112}{DECK_61}{Má pod palcem obchod se zbranìmi.}
{1113}{DECK_62}{Kvùli nìèemu mizí karavany Far Go Traders. Rád bych vìdìl proè, protoe to narušuje èást mıch aktivit.}
{1114}{Deck_63}{To je v centru mìsta.}
{1115}{DECK_64}{Mıty a legendy. Páraè je nìjakı pøízrak nebo nìco takového.}
{1116}{DECK_65}{Staré Mìsto se rozkládá po celé vıchodní èásti. ijí tam Skagové.}
{1117}{DECK_66}{Vìtšinou tam ijí kupci. Jdi pøímo na západ.}
{1118}{DECK_67}{Otravná organizace. Brzy by mìli dostat lekci v pouití síly.}
{1119}{DECK_68}{Morpheus je hlavou Dìtí Katedrály. ije nìkde v Pohøebištì.}
{1120}{DECK_69}{V souèasnosti je šéfkou Dìtí zde v Hubu. Mám dùvod vìøit, e se to ale brzy zmìní.}
{1121}{DECK_70}{Jeden z vımyslù Dìtí. Pravdìpodobnì nìjaké menší bostvo nebo tak nìco.}
{1122}{DECK_71}{Malı koutek, kde prodávají . . . dobré zbranì. Za budovou Far Go Traders.}
{1123}{DECK_72}{Vyjdeš ze dveøí a poøád na sever. Nemùeš minout.}
{1124}{DECK_51}{Má matka, nejlepší ena, kterou jsem znal, mì pøivedla na tuto myšlenku - vytvoøit nejlepší zábavní zaøízení v Hubu.}
{1125}{DECK_51}{Má matka, nejlepší ena, kterou jsem znal, mì pøivedla na tuto myšlenku - vytvoøit nejlepší zábavní zaøízení v Hubu.}
{1126}{DECK_53}{Je velitelem policie. Pøíjemnej chlap, pokud máš rád fairplay, èestnej tıpek. Ne jako jeho táta; teï je tu loajální èlovìk.}
{1127}{DECK_56}{Je šéfem Kupcù s vodou.}
{1128}{DECK_62}{Kvùli nìèemu mizí karavany Far Go Traders. Rád bych vìdìl proè, protoe to narušuje èást mıch aktivit.}
{1129}{DECK_58}{Je šéfem firmy Crimson Caravan.}
{1130}{DECK_59}{Jsou poslední z kupcù, myslím doslovnì. Krátkodobı záleitosti, vìtšinou. Jsou na severovıchodì Kupeckého trištì.}
{1131}{DECK_59}{Jsou poslední z kupcù, myslím doslovnì. Krátkodobı záleitosti, vìtšinou. Jsou na severovıchodì Kupeckého trištì.}
{1132}{DECK_60}{Zábavné. Myslí si, e je šéfem Far Go Traders. Ve skuteènosti je spíš loutka. Spíš se mi umí plést do obchodù.}
{1133}{DECK_64}{Mıty a legendy. Páraè je nìjakı pøízrak nebo nìco takového.}
{1134}{DECK_64}{Mıty a legendy. Páraè je nìjakı pøízrak nebo nìco takového.}
{1135}{DECK_65}{Staré Mìsto se rozkládá po celé vıchodní èásti. ijí tam Skagové.}
{1136}{DECK_65}{Staré Mìsto se rozkládá po celé vıchodní èásti. ijí tam Skagové.}
{1137}{DECK_67}{Otravná organizace. Brzy by mìli dostat lekci v pouití síly.}
{1138}{DECK_72}{Vyjdeš ze dveøí a poøád na sever. Nemùeš minout.}
