{100}{}{Co chceš?}
{101}{}{Nech mì na pokoji.}
{102}{}{Co?}
{103}{}{Nehrabej se mi ve vìcech.}
{104}{}{Ahoj.}
{105}{}{Arrrr!}
{106}{}{Grrrrr!}
{107}{}{Uungh.}
{108}{}{Uhh.}
{109}{}{Už jsi to slyšel, že byl Set odstranìn?}
{110}{}{Set je mrtvý. Set je mrtvý. Set je mrtvý . . .}
{111}{}{Je tu dost vody pro všechny. Set se o to stará.}
{112}{}{Slyšel jsem, že mutanti zmizeli z mìsta.}
{113}{}{Od té doby, co jsou mutanti pryè, je to tu mnohem lepší.}
{114}{}{Ahoj.}
{200}{}{Prozkoumáváš tu nebohou vìc, ale ani v nejmenším netušíš, jak z ní mohlo vzniknout to, èím je teï.}
{201}{}{Možná to byl kdysi èlovìk, nebo aspoò jeho pøedkové. Pøedpokládáš, že za jeho úpadkem lze tušit radiaci èi pùsobení kyseliny.}
{202}{}{Tìlo poloèlovìka bylo asi vystaveno tìžké dávce radiace, ale stále drží po hromadì. I když to byl kdysi èlovìk, teï se nenávratnì zmìnil do témìø zvíøecí formy.}
{203}{}{Tìlo poloèlovìka bylo asi vystaveno tìžké dávce radiace, vìtšina svalstva i mozkové hmoty byla jejich pùsobením rozežrána. Ale podle genetických znakù lze pøedpokládat, že stejnì jako ty to kdysi byl obyvatel Vaultu.}
{300}{}{Dostal jsi dávku radiace!}
