{100}{}{Zdá se, že skøíòka je zamèená.}
{101}{}{Šikovnì vylamuješ zámek.}
{102}{}{Nejsi schopen zámek vylomit.}
{103}{}{Nepovedlo se ti vylomit zámek.}
{104}{}{Zámek už je odemèený.}
{105}{}{Zlomil jsi si v zámku šperhák.}
