{100}{}{Vidíš písaøe.}
{101}{}{Vree je mùj idol.}
{102}{}{Vree je tak krásná.}
{103}{}{Sophia je moc pìkná.}
{104}{}{Derek je v pohodì.}
{105}{}{Bude se vesmír dál rozpínat do nekoneèna, nebo se zaène smršovat?}
{106}{}{Mám rád ty staré knihy a èasopisy. Ale hroznì tìko se shánìjí.}
{107}{}{Vìdomost je síla.}
{108}{}{Pero je silnìjší meèe.}
{109}{}{Technologie se musí uchovat.}
{110}{}{Vìda je tak zábavná.}
{111}{}{Vidìl jsem loï mimozemšanù.}
{112}{}{Vìdìl jsi, e slunce je jenom velká jaderná reakce?}
{113}{}{Vìdìl jsi, e èerná díra je prakticky brána do jiného vesmíru?}
{114}{}{Vìdìl jsi, e vodík je z 99.9843425% prázdnı prostor?}
{115}{}{Jednou bude moné cestovat èasem, a pak budeme moci odvrátit katastrofu, která znièila Zemi v minulosti.}
{116}{}{Vızkum je moje oblíbená aktivita. Cítím se, jako kdy se snaím rozluštit nìjakou záhadu.}
{117}{}{Nejlepší je bıt písaø. Studuješ všechny ty staré technologie a snaíš se vytvoøit nové.}
{118}{}{Tyhle terminály by snesly vylepšení. Moná bychom mohli dát ten display sem.}
{119}{}{Sorry, jsem uprostøed moného prùlomu. Nemùu s tebou teï mluvit.}
{120}{}{Hej zasvìcenèe. Mìl bys trénovat, aby ses stal písaøem, jestli ses ještì nerozhodl.}
{121}{}{My badatelé navrhujeme všechno vybavení, zbranì a zásobování. Je to docela vzrušující.}
{122}{}{Prosím, neruš mì, snaím se dokonèit svùj vızkum.}
{123}{}{Támhleto je Vree, je taky písaø.}

