{100}{}{Velení, toto je Strážnice. Všude klid. Konec.}
{101}{}{Smrt na tebe, hade!}
{102}{}{Vetøelec!}
{103}{}{Èlo-vìk!}
{104}{}{Stùj. Tohle zakázané území. Ty nebýt tady.}
{105}{}{Radìji se vzdej.}
{106}{}{Ty stát. Já ty vzít k poruèík. Pojï mírumilovnì nebo zemøít.}
{107}{}{Luggi!}
{108}{}{Zhebni, zplozenèe pekla!}
{109}{}{Pøišel jsem si promluvit s vaším pánem.}
{110}{}{Jsem zvláštní mutant a mám poslání od vašeho pána. Nech mì projít nebo si poneseš následky.}
{111}{}{Jsem s Katedrálou. Nech mì projít.}
{112}{}{Zhebni!}
{113}{}{No, jak chceš.}
{114}{}{Fajn. Smrti vstøíc.}
{115}{}{Dobrá. Jít se mnou, žádný žert.}
{116}{}{OK. Jdeme.}
{117}{}{Žert? Budeš vypadat srandovnì, až ti dám pìstí!}
{118}{}{Nevìøím ti.}
{119}{}{To si nemyslím.}
{120}{}{Ne. Ty èlovìk. Zemøít.}
{121}{}{Jestli ty lhát, já zabít.}
{122}{}{Och, OK. Hni s sebou.}
{123}{}{Uh, fajn. Myslím. Radši viï Poruèík.}
{124}{}{Zabil jsi mi bratra. Má je pomsta!}
{125}{}{Smrt na tebe!}
{126}{}{Vrah!}
{127}{}{Zabiják!}

