#tento soubor pøeložil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš tlustého trpaslíka.}
{101}{}{Vidíš Gretche, pomocníka Dr. Morbida.}
{102}{}{Co chceš tady dole?}
{103}{}{Urgh?}
{104}{}{Poslal mì sem tvùj šéf.}
{105}{}{Takhle se mnou nemluv, kreténe.}
{106}{}{Jdu se podívat, jak ti to jde.}
{107}{}{Nic. Ahoj.}
{108}{}{Znám tì, ..... že jo?}
{109}{}{Ne.}
{110}{}{Ano.}
{111}{}{Zapomeò na to.}
{112}{}{Hm . . . jde to dobøe.}
{113}{}{Co právì dìláš?}
{114}{}{Dobøe? Znamená to, že už je to skoro hotový?}
{115}{}{Jde ti to nìjak pomalu, co?}
{116}{}{Jo, jo už to skoro mám.}
{117}{}{A co?}
{118}{}{Už taky bylo naèase.}
{119}{}{Dobrá. Uvidíme se pozdìji.}
{120}{}{Èásti mrtvol už jsou skoro pøipraveny pro Hub.}
{121}{}{Pro co?}
{122}{}{Jasnì. Proto jsem tady.}
{123}{}{Myslím, že o tom nechci slyšet.}
{124}{}{Leguán Bob tì poslal . . . bude spokojený, hodnì dobrého jídla . . .}
{125}{}{On prodává èásti mrtvol na pøípravu jídla pro lidi?}
{126}{}{Ty mròavej strupe, já tì rozøežu a prodám tì taky na maso!}
{127}{}{Jasnì . . . Hned jsem zpátky.}
{128}{}{Pro Boba, prodat . . . jíst . . . proè se ptáš, na co to používáme?}
{129}{}{Jen tak. Ahoj.}
{130}{}{Nebyl jsem si jistý, jestli má Bob to lidské maso právì odsud.}
{131}{}{Nìkdy mám potíže s pøemýšlením.}
{132}{}{Taky s tím mám nìkdy problémy . . . o èem jsme mluvili?}
{133}{}{Nevzpomínám si. Ahoj.}
{134}{}{Mluvili jsme o tom, co dìláš.}
{135}{}{Mluvili jsme o tvojí blbosti.}
{136}{}{To je fuk.}
{137}{}{Už Ti nic neøeknu.}
{138}{}{Jo . . . Doktor Morbid má nejlepší lidská tìla. Nikdo nemá lepší.}
{139}{}{Hm, . . . Vrátím se, abych vyzvednul ty . . . mrtvoly . . . za chvilku. Ahoj.}
{140}{}{Musím už zpátky do práce.}
{141}{}{Nestrkej nos do doktorových vìcí!}
