#tento soubor pøeloil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Nebojím se.}
{101}{}{Mám strach.}
{102}{}{Mám slubu. Jdi pryè.}
{103}{}{V tomhle mìstì buï v klidu nebo ti ukáu.}
{104}{}{Nemáš nìco k jídlu?}
{105}{}{Mìl jsi nìkdy pocit, e jsi sledován? Jako kdyby tì nìkdo z dálky pozoroval na nìjaké obrazovce? Já jo.}
{106}{}{Slyšel jsi, co udìlal radškorpión Billimu? Poøád ještì nemùou najít jeho nohy.}
{107}{}{Tak ty se chceš utkat s radškorpiónem?}
{108}{}{Nezdáš se mi nìjak zvláš tvrdı.}
