#tento soubor pøeloil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš Leona, stráného.}
{101}{}{Co tu chceš?}
{102}{}{Musím mluvit s panem Hightowerem.}
{103}{}{Chci zabít pana Hightowera.}
{104}{}{Co tu dìláš ty?}
{105}{}{OK. Ale budu tì sledovat. Je v kanceláøi.}
{106}{}{Dík.}
{107}{}{Jo... To se vsadím, e mì pozoruješ.}
{108}{}{Nìjak se mi nelíbíš. Radši si dej odchod.}
{109}{}{Odejdu a budu chtít, kámo!}
{110}{}{OK, já odejdu.}
{111}{}{Nelíbím, jo? Já ti teda ukáu!}
{112}{}{A je to cokoliv, øekni mi to. Pan H. teï nemá èas.}
{113}{}{Proè to dìlat tak sloitì?}
{114}{}{Radši s ním chci mluvit osobnì. Je to otázka ivota nebo smrti.}
{115}{}{Decker vypsal na pana Hightowera odmìnu.}
{116}{}{Øekni mi to, nebo mùeš jít.}
{117}{}{Kdo umøel a udìlal z tebe Boha?}
{118}{}{Decker vypsal na pana Hightowera odmìnu.}
{119}{}{Hele, tobì já nic øíkat nebudu!}
{120}{}{U jdu.}
{121}{}{U zas? Ten Decker je ale vùl.  Fakt?... Myslím ale, e poøád ještì to není takovı vùl, jako ti chlapi, které si na tu práci najal. Koukni, podívej se na mojí zbraò.}
{122}{}{[Leon ti ukazuje svojí zbraò, kde vidíš pìt hlubokıch záøezù.]}
{123}{}{Kadı z tìch záøezù znamená pokus o zabití pana Hightowera. Dostal jsem všechny. Øekni mi...víš jak vypadá ten, koho ten cvok Decker najal?}
{124}{}{Ne.}
{125}{}{To jsem já, ty blbèe!}
{126}{}{Hej! Páni! Ty máš záøezy na svojí zbrani! Ty jsi ale booorec!}
{127}{}{Dík za upozornìní, ale pan Hightower nemá rád, kdy je tu nìkdo cizí. Musíš odejít.}
{128}{}{To je všechno? ádná odmìna? Co se to s váma lidi, sakra, dìje?}
{129}{}{Není zaè. Sbohem.}
{130}{}{Pan Hightower nikoho nepøijímá. Vypadni!}
{131}{}{Odejdu, a se mi bude chtít, kámo!}
{132}{}{OK, jdu.}
{133}{}{Fakt potøebuju mluvit s panem Hightowerem.}
{134}{}{Jak myslíš, kámo. Jdeme. [Leon tì popadne za rameno.]}
{135}{}{Dej pryè ty svoje prašivı pracky!}
{136}{}{Dobøe, dobøe! U jdu.}
{137}{}{Poèkej! Ještì jsem neskonèil!}
{138}{}{Ug!}
{139}{}{Rúdl!}
{140}{}{Mám pro pana Hightowera dùleitou novinu.}
{141}{}{Co tu dìláš? Nemám slubu. Otravuj nìkoho jinıho.}
{142}{}{Doufal jsem, e se chceš omluvit za to, e tady zacláníš! Stráe!}
