{100}{}{Vidíš Jakea z Následníkù.}
{101}{}{Vidíš Následovníka Apokalypsy.}
{102}{}{Vítej, mùj pøíteli! Jak ti dnes mohu pomoci?}
{103}{}{Mì pomoc! Mì pomoc!}
{104}{}{Slyšel jsem, že jsi tuhej bojovník. Hned to vyzkoušíme.}
{105}{}{Slyšel jsem, že potøebuješ pomoct. Co máš za problém?}
{106}{}{Co mi mùžeš øíct o Následnících?}
{107}{}{Chceš pomoct. Nemyslím si, že jsi dost dobrej, abys mi mohl 
 pomoci. Promluv si s Neilem.}
{108}{}{Rád bych s tebou bojoval, ale mám teï moc práce s pomáháním Nicole.}
{109}{}{To sedí. Stejnì jsi na mì pùsobil jako chcípák.}
{110}{}{Vyliž si, sbohem.}
{111}{}{Jak to mohl posera jako ty dotáhnout tak daleko?}
{112}{}{Hej. Jen proto, že nechci bojovat, pøece nejsem strašpytel. Prostì to tak necítím.}
{113}{}{Mìl jsem pravdu. Prostì posera.}
{114}{}{Nìkteøí z nás používají mozek, aby se dostali dál. Mnoho lidí se mùže
 usadit v klidu.}
{115}{}{A kdy teda ty svý mozky zaènete používat?}
{116}{}{Máš pravdu. Omlouvám se.}
{117}{}{To je to. Už se s tebou nebudu bavit.}
{118}{}{To je lepší. Takže, mám tady problém se špiónem.
 Pomùžeš mi?}
{119}{}{Ano. O co jde?}
{120}{}{Pomož si sám, když jsi taková hvìzda.}
{121}{}{Jen jsem øekl, že tu máme špióna. Myslím si, že by to mohl
 být nìkdo ze strážných. Nebo nìkterý ze zvìdù. To jsou jediné skupiny,
 které mají pøístup k Dìtem.}
{122}{}{Dobøe. Dostanu toho zvìda a vyøeším tím tvùj problém.}
{123}{}{Je nìco známo o tom špiónovi?}
{124}{}{Zapomeò na to. Nepomùžu ti.}
{125}{}{Díky moc. Teï jdi!}
{126}{}{Nic moc. Jediné, co vím, že se k Dìtem nìjak dostávají
 naše ménì dùležité informace, a to není dobré. Heather si myslí, že by to mohl
 být buï Neil nebo Peter.}
{127}{}{Fajn. Jdu se porozhlédnout.}
{128}{}{Zapomeò na to. Nepomùžu ti.}
{129}{}{Pak tì nemohu nechat odejít.}
{130}{}{Ale mùžeš. Sbohem!}
{131}{}{Máme problém. Naše informace nìjak prosakují k Dìtem. Podle mì tu máme špióna.}
{132}{}{Dobøe. Co je tu za problém?}
{133}{}{Dobøe, postarám se o toho špióna.}
{134}{}{Nìjaké stopy?}
{135}{}{Zapomeò na to. Nepomùžu ti.}
{136}{}{Momentálnì ti nemohu nic øíct. Hezký den.}
{137}{}{Pokouším se spát. Neotravuj mì.}
{138}{}{Pospìš a najdi toho hnusného neøáda!}
{139}{}{Já vìdìl, že to musí být Heather. Byla od zaèátku
 prolhaná a neèestná. Mìl jsem hned všem øíct, co jsem si od zaèátku myslel.}
{140}{}{Nikdy jsem se od tebe nic nenauèil. Tvùj výcvik byl
 k nièemu.}
{141}{}{Mám pro tebe balíèek od Gabriela.}
{142}{}{Hmm. Aha Díky.}
{143}{}{Koukej kurva zmizet.}
{144}{}{Je to tìžký. Vždycky je to tìžký.}
