{100}{}{Vidíš mue s ostrımi rysy.}
{101}{}{Vidíš Jasona Zimmermana.}
{102}{}{Hej, jseš opravdu z velké dálky? Proil jsi 
 mnoho dobrodruství?}
{103}{}{Ano, jsem z Vaultu daleko na severu.}
{104}{}{Vlastnì jsem z Marsu. Chceš vidìt moje ohnivé kopí?}
{105}{}{Nìco jsem proil.}
{106}{}{Zas tolik jsem toho neudìlal, vánì.}
{107}{}{Uf, daleko. Vault.}
{108}{}{Oh. doufal jsem, e nìkdo, kdo prošel Pustinami, bude, no, trochu
 chytøejší. No nic.}
{109}{}{Miles øíká, e kdy jsi získal ty souèástky,
 tak zprovozní farmy, take nebudeme muset prodávat
 støelivo do Hubu. Nikdy jsem o tom moc nepøemıšlel,
 dokud Smitty neupozornil na to, e náboje od nás }
{110}{}{se v Hubu prodávají gangùm. Myslím, e jsi 
 pøišel na dobré øešení.}
{111}{}{Nikdy jsem nedoufal, e dokáeme zastavit gangy.
 Otec mi vyprávìl, jak jsi je donutil ke slibu, aby nás nechali na pokoji.
 Víš, myslel jsem si, e bych chtìl vyrazit za dobrodrustvím,
 ale myslím, e mám rád . . . no, asi }
{112}{}{Ten pocit bezpeèí, co tu mám. U ádné obavy z nájezdù gangù
 a strachu z toho, kdo pøijde o ivot.}
{113}{}{Lorraine øíká, e na jih odsud byl Vault, odkud byli moji
 pøedkové. Jaké to je, ít ve Vaultu?}
{114}{}{Vlastnì je to dost nudné.}
{115}{}{Velmi vzrušující. Máme všemoné technologie, o kterıch se ti 
 ani nesnilo!}
{116}{}{Oh. Nìco jsi proít musel, ne?}
{117}{}{Nic moc.}
{118}{}{Jo, venku je to trochu nebezpeènìjší.}
{119}{}{Jak kdosi napsal, 'Dobrodruství znamená bıt
 hodnì daleko v hodnì velkım marastu.'}
{120}{}{Huh. Obchodníci z Hubu mluví o radškorpiónech a chlastu.}
{121}{}{Vlastnì je to skoro poøád pouš.}
{122}{}{No vlastnì jsou tam všechny druhy pøíšer.}
{123}{}{Vánì? S jakımi pøíšerami jsi bojoval?}
{124}{}{Nic moc, jen pár krys a tak.}
{125}{}{Jo. Strání z Hubu mluvili o mnoství radioaktivních mutantù
 v poušti. Lovení monster musí bejt fakt náøez!}
{126}{}{Jo, fakt bomba!}
{127}{}{Ne; je to víc o bolesti. Jed, rány, radiace .. . je to smrtící.}
{128}{}{Pøál bych si vyrazit jednou za dobrodrustvím.}
{129}{}{O tom jsem nikdy nepøemıšlel. Radši mám èistou vodu
 a místo k pøespání.}
{130}{}{Myslel jsem, e ivot v pustinách bude . . .
 víš. . . chlapskı, nebezpeènı a tak. Ale myslím, e toho tady máme
 sami dost, myslím všechny ty gangy, víš.}
{131}{}{Coe, jsi blázen nebo co? Caleb tì nemìl vùbec nechat 
 projít branou!}
{132}{}{To je perfektní. Všechno, co tu máme, je tahle pitomá studna
 a ty podzemní farmy, které Miles snaí udret v chodu.}
{133}{}{Jo, všiml jsem si, e nemáš ádnı spacák ani nic podobného.
 To musí bıt dost nepohodlné a špinavé tam venku, co.}
{134}{}{Ahoj. Máš nìjaké zajímavé historky?}
{135}{}{Co chceš vìdìt?}
{136}{}{Ani ne.}
{137}{}{Dobøe, pokud udìláš nìco zajímavého, dej mi vìdìt!}
{138}{}{Nech mì bıt!}
{139}{}{Díky bohùm, e jsi tady! Prosím, pomoz mi odsud!}
{140}{}{Ayuh.}
{141}{}{Neboj, dostanu nás pryè.}
{142}{}{Promiò, postarej se o sebe sám!}
{143}{}{Co tady dìláš?}
{144}{}{Díky!}
{145}{}{Prosím, neopouštìj mì!}
{146}{}{Myslel jsem, e bude zábavné vyrazit z Adyta a
 poznávat svìt. Ale Rippeøi mì chytili a drí mì
 tady. Prosím, pomoz mi!}
{147}{}{Dobøe, padáme odsud!}
{148}{}{NE. Dostal ses do toho sám, tak se z toho taky sám dostaò ven.}
{149}{}{Doufám, e se odsud brzo dostaneme!}
