{100}{}{Vidíš unaveného poutníka.}
{101}{}{Vidíš Lanceho, stráce shadysandskıch zvìdù.}
{102}{}{Jenom stùj kde si. Slyšeli jsme o tobì v Shady Sands a nechceme s tebou mít cokoliv spoleèného.}
{103}{}{Jediná vìc, která mì na tobì zajímá, je tvoje vybavení. Tak ho naval!}
{104}{}{Nechci ádnı rozpory, kámo.}
{105}{}{Hele, nezachránil jsem Tandy a nepobil všechny ty radškorpióny?}
{106}{}{Nemìl sem ádnı potíe se Shady Sands. Naopak, mìl sem to tam docela rád.}
{107}{}{Herung?}
{108}{}{U jsem o tobì slyšel, ale já se jen tak odprásknout nenechám.}
{109}{}{Nemám ti co øíct.}
{110}{}{Jo? Co chceš tentokrát?}
{111}{}{Nevìdìl bys, kde najdu vodní èip?}
{112}{}{Nìco o Tandi?}
{113}{}{Nìjaké problémy s nájezdníky?}
{114}{}{Jak to jde v Shady Sands?}
{115}{}{Hnng!}
{116}{}{Zdravím tì, cizinèe. Co tì pøivádí do tìhle konèin? Odkud vùbec jsi?}
{117}{}{To samé bych se mohl zeptat tebe.}
{118}{}{Sorry kámo, ale mám takovej dojem, e bych ti to radši nemìl øíct.}
{119}{}{Nevíš kde se dají koupit zásoby?}
{120}{}{Jsem z Vaultu. Šastného Vaultu 13!}
{121}{}{Cooo?}
{122}{}{Zdravím tì, cizinèe. Doporuèoval bych ti jít dál, pokud víš, co je pro tebe dobré.}
# TRANSLATION NOTE
# After line 123, the player-character's name is inserted by the code, and
# then line 124 or line 131 is added.
{123}{}{A hele, }
{124}{}{. Pùvodnì jsem si myslel, e jsi náš pøítel, kdy jsi zachránil Tandi, ale poslední dobou jsem o tobì zaslechl ošklivé vìci. Mùe to bıt pravda?}
{125}{}{Lidí øíkaj rùznı vìci. Koho to zajímá?}
{126}{}{JÁ nejsem ádnej tvùj pøítel! A jestli se jen blbì pohneš, tak se podívám na tvoje støeva. Jasnı?}
{127}{}{Jakı 'vìci'?}
{128}{}{Jasnì. To je všechno pravda. A teï mi radši dej všechno, co máš, nebo . . .}
{129}{}{Moná sem udìlal pár vìcí, kterejch lituju, ale sám bys mìl posoudit, kterejm blábolùm uvìøíš a kterejm ne.}
{130}{}{. No to jsem rád, e si to ty a ne nìjakej nájezdník! Jak se vede? Já jsem Lance, patøím ke strái ze Shady Sands. Sorry, e jsme na tebe byli takovı, kdy si poprvé pøišel do mìsta!}
{131}{}{Èau Lanci, co se dìje?}
{132}{}{Èau Lanci. Bıval jsem dobrák, ale èasy se mìní. Teï mi dej všechno co máš, jinak . . .}
{133}{}{Vyvejkni se Lanci. Copak tu sám dìláš?}
{134}{}{Dobøe. Ale tohle si zapamatuju.}
{135}{}{Zvedni svoje.}
{136}{}{Ušetøi mì tìch kecù, chlapèe. Dìti jako ty si dávám k obìdu. Naval všechno, co máš, a moná tì nechám jít.}
{137}{}{Pokud si opravdu myslíš, e pøedstavuju ohroení, tak mì zabij.}
{138}{}{Jen se pohni. Sem zvìdavej, jak vypadaj tvoje vnitønosti.}
{139}{}{To bylo tehdy a teï je teï. Co si pro nás poslední dobou udìlal? Mìl bys radši vypadnout, ne se naštvu.}
{140}{}{To my taky rádi. Hlavnì e v tom nemáš svı pazoury. Teï padej.}
{141}{}{Èlovìèe, tys to nìjak s tím opalováním v Kráteru pøehnal!}
{142}{}{Já nevím, co je to vodní èip. Sorry.}
{143}{}{To je taková elektronická vìcièka, co se pouívá v zaøízeních èistících vodu.}
{144}{}{Co je s tìma radškorpiónama?}
{145}{}{Nájezdníci jí dostali. U jsem jí hledali a myslíme, e jí drí v táboøe na jih od Shady Sands. Ale dej si bacha, Khanové tam mají takovou menší pevnost.}
{146}{}{Mùeš mì vzít do Shady Sands?}
{147}{}{Mùeš mì vzít ke Khanùm?}
{148}{}{Musíme vymyslet, jak ji dostat nazpátek.}
{149}{}{Díky za informace a pøeju hodnì úspìchù pøi hledání.}
{150}{}{Uh, jo, daøí se nám o nìco líp, od té doby, co Khanové dostali po rypáku. Vím, e je to tvoje zásluha a jsme ti za to všichni vdìèní.}
{151}{}{Nevadil by mi malı projev vdìènosti.}
{152}{}{Díky. Mùu udìlat ještì nìco?}
{153}{}{Jen mi dejte vìdìt, a vás zaènou zase obtìovat.}
{154}{}{Daøí se nám dobøe.}
{155}{}{Jsi si tím jistı?}
{156}{}{To je perfektní.}
{157}{}{Nic mì nenapadá. Debile.}
{158}{}{Jo, budu ti vìøit. Já jsem ze Shady Sands. Jsme malá komunita kousek odtud.}
{159}{}{Mùeš mì tam vzít?}
{160}{}{Jak to tam vypadá?}
{161}{}{Máte tam nìjaké vodní èipy?}
{162}{}{Jo, to vypadá jako pìkné místo.}
{163}{}{Dobøe, nech si své tajemství a já si nechám své. Sbohem.}
{164}{}{Moná e je. I kdy lítostivı.}
{165}{}{Byl jsem v Junktownu. Myslím, e to je jihozápadnì odtud, ale cestuju u tak dlouho, e si tím nejsem jistı.}
{166}{}{Jo, pravda. Všechny Vaulty byly znièenı. Øekni mi ještì nìco.}
{167}{}{To není to, na co sem se ptal . . . oh, to nevadí!}
{168}{}{To není odpovìï. Øíkají o tobì, e si vrah, zlodìj a vykradaè hrobù! Øíkají, e sejmeš kohokoliv, kdo ti stojí v cestì. Je to pravda?}
{169}{}{No, tebe sem zatím nesejmul, take aspoò nìkdo kecal.}
{170}{}{Docela dost. Mìl jsem taky svùj podíl na dobrejch èasech.}
{171}{}{Udìlal jsem si i pár nepøátel a nechal jsem jich ít dost na to, aby o mì zaèali šíøit pomluvy.}
{172}{}{Sejmul jsem pár lidí, co o to. Ale k tomu jsem vdycky mìl dùvod.}
{173}{}{Øíkají o tobì, e si vrah, zlodìj a vykradaè hrobù! Øíkají, e sejmeš kohokoliv, kdo ti stojí v cestì. Je to pravda?}
{174}{}{Dobøe, já to udìlám. Ale pokud budeš jednat jako nájezdník, tak i chcípneš jako nájezdník.}
{175}{}{Dobrá, nebudu tì soudit dopøedu. Ale èlovìk je dobrı jenom tak, jak dobrá je jeho povìst. A zrovna ta tvoje by potøebovala dost zlepšovat. Doufám, e ne se pøíštì setkáme, tak s tím nìco udìláš.}
{176}{}{Mám namíøeno zpátky do mìsta. Nechceš jít se mnou? Nìjaká spoleènost by se mi líbila.}
{177}{}{Jasnì.}
{178}{}{Dneska ne.}
{179}{}{Trochu práce s odklízením. Našli jsem opuštìné tábory nájezdníkù, které ještì nikdo nevybral. Mám podezøení, e se pobili mezi sebou. Trocha munice a chemikálií se nám bude vdycky hodit.}
{180}{}{Budu toho litovat.}
{181}{}{Padej mi z oèí, ne se naseru.}
{182}{}{Ještì na nì obèas narazíme, nejspíš migrují z pouští nebo od Kráteru. Ale je to mnohem lepší, hlavnì díky tobì.}
{183}{}{To zní dobøe. Mìj se.}
{184}{}{Jasnì, jdeme.}
{185}{}{Chlape, asi sem se pomátnul. Ale vezmu tì. Jdeme..}
{186}{}{Pøíjemnou sebevradu, kámo. Doufám, e to za to stojí, hodnì štìstí.}
{187}{}{Míøím pryè. Mìj se.}
{188}{}{No, nemám moc, ale co je moje je teï i tvoje.}
{189}{}{Nic o èem bych uvaoval. Míøím pryè. Opatruj se.}
{190}{}{Budeme. Míøím pryè. Opatruj se.}
{191}{}{No dobøe, jdeme.}
{192}{}{Nedovedu domù nìkoho, kdo je moná nepøítel. Pokud se nìkdy zastavíš v Shady Sands, tak si dej pozor.}
{193}{}{Málo. ijeme z chovu brahminù. Je to pìknì drsnej kraj a pastviny jsou tady velice vzácnı.}
{194}{}{Brahminí buranov? Musíte bıt blázni! Nejspíš tu v okruhu dvou set mil nebude jedinı kousek funkèní elektroniky.}
{195}{}{Uhodils høebíèek na hlavièku. Myslím ale, e musíme bıt opatrní a ít dál naším ivotem. Ale na tvém místì bych nìco udìlal se svojí povìstí, pokud nemáš radši, kdy ti lidé nevìøí nebo tì nenávidí.}
{196}{}{Mìl jsem tì zabít hned. Ještì jednou mi zkøííš cestu a je z tebe mrtvola. Teï padej.}
{197}{}{Jdeme.}
{198}{}{Nech mì hádat, nìkdo ti øekl o mém chrápání. No dobøe. Opatruj se.}
{199}{}{To je. No, míøím pryè. opatruj se.}
{200}{}{Jen zùstaò kde jsi. Nevím, jestli si ve spojení s tìmi mutanty, ale jestli ano, tak tì zabiju.}
{201}{}{Jakımi mutanty?}
{202}{}{Kdo jsi?}
{203}{}{Co se ti stalo?}
{204}{}{Dobrı, no to je hezkı.}
{205}{}{Ru-co?}
{206}{}{Mutanti napadli Shady Sands. Vìtšina z nás je u mrtvá. Hádám, e to je jenom otázka èasu ne dostanou i ty ostatní.}
{207}{}{Nezajímá mì, co kecáš neb na co se ptáš. Všichni jsme mrtvoly! Všichni! A to jsem si myslel, e radškorpióni nebo nájezdníci byli hrozní . . . proti tomuhle to byla švanda! Ha! Ha ha ha!}
{208}{}{Sklapni! Nesnáším prázdnı vatlání. To nic nevyøeší!
Jenom mì tím nasereš . . .}
