{100}{}{Máš pøed sebou poèítaè Mach IV.}
{101}{}{Vypadá to, že se systém restartuje.}
{102}{}{Systém se zdá být uzamèený.}
{103}{}{Monitor poblikává.}
{104}{}{Na obrazovce se objevily rùznì zbarvené pruhy.}
{105}{}{Obrazovka poèítaèe ukazuje malé zelené bomby nekoneènì padající k zemi.}
{106}{}{Nemùžeš se hacknout do poèítaèe.}
{107}{}{Získal jsi pøístup k nìjakým elektronickým poznámkám. Nejzajímavìjší je zpráva
 od poruèíka"...další lidské objekty k transformaci.
 Pošlete je okamžitì do vojenské základny."}
