{100}{}{Vidíš Vasqueze, otrlého žoldáka.}
{101}{}{Vidíš zpustošeného pistolníka.}
{102}{}{Co chceš?}
{103}{}{Kdo jsi?}
{104}{}{Hnn.}
{105}{}{Nepracuju pro pitomce. Zmiz.}
{106}{}{Ty jsi o mì nikdy neslyšel? To mì trochu uráží! Celé mé jméno zní  Vasquez
 Villanova Hernandez Ortega. Jsem slavný desperado,
 mùj pøíteli. A jestli budeš nìkdy potøebovat, nechám se i najmout.}
{107}{}{Skuteènì? Jaká je tvoje cena?}
{108}{}{Uvidíme se, možná . . . hodnì štìstí. Heh.}
{109}{}{Ahh, takže zpátky k vìci mùj pøíteli. Výbornì. V rámci 
 tohodle mìsta ti pomùžu za mrzkých 500 týdnì. Moje služby 
 nejsou laciné, ale jak øíkám, stojím za to.}
{110}{}{Skvìle. Najmu si tì. Tady je 500.}
{111}{}{Promiò za to obtìžování, ale nemyslím si, že budu tvé služby potøebovat.}
{112}{}{Je mi líto, kámo, ale za neviditelný prachy nepracuju.
  Potøebuju hmatatelný, zvonivý penízky.}
{113}{}{Paráda. Jsem tvùj. Pojïme, už se tu nudím.}
{114}{}{Ty tu velíš. Udìlám co øekneš!}
{115}{}{Pojï, trochu se napijeme!}
{116}{}{Kam pùjdeme nejdøív?}
{117}{}{Po dobu, co budeš v Junktownu, jsem tvùj, ale jinak se mnou nepoèítej.}
{118}{}{Víš vùbec, že na mojí hlavu byla vypsaná odmìna? Nicménì nestála ani za to.}
{119}{}{Ah, Jsem rád, že tì zase vidím mùj pøíteli.}
{120}{}{Chci si tì na týden najmout.}
{121}{}{Rád tì zase vidím.}
{122}{}{Hnn.}
{123}{}{Hmm, možná není dobrý, že tì zase vidím. Pøeji dobrý den.}
{124}{}{Samozøejmì. Mùj úèet je moc malý a má hodnota pøíliš vysoká. 500, prosím.}
{125}{}{Tady to je.}
{126}{}{Tohle jsi nemìl dìlat, mùj už-brzo-mrtvý pøíteli.}
